### ISSUE TITLE
Feature Request:  Nvidia Gameworks DLL integration for SH2 and SH3

### ISSUE THREAD

**Issue by Cool-Gamer** [elishacloud/Silent-Hill-2-Enhancements#1]
Hi Elisha,

Thanks for starting this SH2 enhancements projects.  I hope you add lots of features to it over time.  I hope you also start one for SH3 in the future.

I have a feature request.  Is it possible to take advantage of Nvidia Gameworks DLLs and add features such as HBAO+, TXAA, Global Illumination, advanced shadows, DoF Bokeh, etc. via ASI loader patches? I wrote some links below, the last one includes implementation example for HBAO+.
https://developer.nvidia.com/gameworks-visualfx-overview
https://developer.nvidia.com/postworks
http://docs.nvidia.com/gameworks/content/gameworkslibrary/visualfx/hbao/product.html

Nvidia provides example source code (free of charge) that shows programmers how to use HBAO+ and other Gameworks features in their games. It is on Github but you have to signup through Nvidia's website to request access to the HBAO+ repository (it is hidden from public view). Instructions are shown on the link below.
https://developer.nvidia.com/gameworks-source-github

After you complete the signup you should be able to access the "hidden HBAO+ repo" under the following web page when you login to Github.
https://github.com/NVIDIAGameWorks

It might be possible to make Silent Hill games look amazing, if you can find a way to integrate Nvidia Game Works DLL calls into your ASI script. Those DLLs work on all platforms (Intel GPUs, AMD GPUs and Nvidia GPUs), not just on Nvidia.

On a separate note, dgVoodoo2 wrapper can be used to convert "DirectX 1 to 8" games to "DirectX 11".  I wanted to mention this in case Gameworks DLLs require DX11.
dgVoodoo2 website is:
http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html
Latest Work In Progress Release is:
http://dege.fw.hu/temp/dgVoodooWIP38.zip
http://www.vogons.org/viewtopic.php?f=59&t=51790
Support forum is:
http://www.vogons.org/viewforum.php?f=59

Thanks for your reply in advance.

**Comment by elishacloud** [comment]
@Cool-Gamer, check out these three threads:
1. [Options/Inventory Font Resolution](https://github.com/ThirteenAG/WidescreenFixesPack/issues/375)
2. [Porting audio and soft shadows from PS2 build to PC](https://github.com/elishacloud/dxwrapper/issues/6)
3. [Checklist of Remaining/Wishlist Fixes](https://github.com/elishacloud/dxwrapper/issues/9)

**Comment by mirh** [comment]
I found funny to mention dgVoodoo2 in a repo of its open source alternative.
