### ISSUE TITLE
Silent Hill 2 Enhanced Edition won't launch.

### ISSUE THREAD

**Issue by SuperCool609** [elishacloud/Silent-Hill-2-Enhancements#1000]
I downloaded the game, followed the setup instructions, and after launching sh2pc.exe, the game doesn't start. I also tried running it as an administrator (which as you can tell didn't work).

I also checked the page on the Enhanced Edition website where all the files are listed, and I have every file except the ones that appear after launching the game, which doesn’t start.

I have Windows 11, so I’m unsure if that could be causing the problem.

If anyone can help, please leave a comment. Thanks

**Comment by Polymega** [comment]
If you are using BitDefender please tell the software to allow sh2pc.exe/our project to run.

**Comment by SuperCool609** [comment]
It worked, thank you!
