### ISSUE TITLE
Fresh install from backup

### ISSUE THREAD

**Issue by Radian000** [elishacloud/Silent-Hill-2-Enhancements#1002]
Hi!
I ran a full installation of SH2EE with the backup option. I would now like to use this backup on another pc (without downloading again). How do I do this? I haven't found an option in this installer to select a saved backup.

**Comment by MarioTainaka** [comment]
If your files are backed up from the initial install with the option that I'll create a new folder called sh2e in the root of your C drive by default. Just launch the setup in that folder.

**Comment by Polymega** [comment]
Hi there,
When you run the installer (`SH2EEsetup.exe`) for the very first time, it will ask if you want to install the project files to a temporary folder during installation or make a backup for future offline installation use. If you have chosen the latter option, the tool will then ask what folder you want to save the backup files to. This folder will contain the project files for future/offline use.

**Comment by Radian000** [comment]
> If your files are backed up from the initial install with the option that I'll create a new folder called sh2e in the root of your C drive by default. Just copy that folder and launch the setup in that folder.

It worked, thank you!
