### ISSUE TITLE
the game is not responding 

### ISSUE THREAD

**Issue by Rizex98** [elishacloud/Silent-Hill-2-Enhancements#1006]
![Desktop Screenshot 2024 08 22 - 19 34 45 69](https://github.com/user-attachments/assets/3abe1a1f-bec4-48f5-9f2b-3498b8cac891)
i use windows 11 and i dont have any anti virus apps

**Comment by Polymega** [comment]
Please share an image of the files inside the game's main folder.

**Comment by Rizex98** [comment]
[sh.txt](https://github.com/user-attachments/files/16723652/sh.txt)
i don't is that help but can you give me more specific

**Comment by Polymega** [comment]
Take a snapshot of your game's folder. It will look something like this:
![image](https://github.com/user-attachments/assets/80353e59-4d4d-48ef-9ae3-6d2e8eb888d8)

**Comment by Rizex98** [comment]
![Desktop Screenshot 2024 08 23 - 13 33 40 36](https://github.com/user-attachments/assets/ba872d26-acee-4d6f-9ec1-356ed4e98f40)
![Desktop Screenshot 2024 08 23 - 13 33 42 90](https://github.com/user-attachments/assets/ddc978be-6b86-44cb-908b-96e386e59351)

**Comment by Polymega** [comment]
The Arabic characters a few folders back might possibly be the cause. Try putting the game's folder in a completely Latin/UTF-8 directory path.

**Comment by Rizex98** [comment]
![Desktop Screenshot 2024 08 25 - 18 11 26 51](https://github.com/user-attachments/assets/a2c91816-65b4-4e85-8442-26b7d43fa016)
thx it's working now
