### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by 18daniel81** [elishacloud/Silent-Hill-2-Enhancements#1007]
Hey Silent Hill 2: Enhanced Edition !

I can help you with the Russian language, but I do not know which program to use.

If you can help with this, I can fully translate !

I really hope that you accept me.

Thanks,
18daniel81

**Comment by Polymega** [comment]
Hi there,

I believe this person is already creating a Russian translation pack for our project. Maybe you could assist this person in their translation pack? https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus

Thanks
