### ISSUE TITLE
Shotgun is way too loud

### ISSUE THREAD

**Issue by RudeCanine** [elishacloud/Silent-Hill-2-Enhancements#1011]
Just updated from an earlier version (i don't remember which one sorry) to the latest one, and for some reason it's detecting my windows settings as 7.1 Surround (it's not, I am however using a MOTU M2 audio interface that uses ASIO drivers, so might be that?) so whenever certain things like the shotgun are fired in a specific part of a corridor or what have you, it down-mixes the 7.1 to stereo which then proceeds to make it extremely loud.

Any way to fix this?

**Comment by MarioTainaka** [comment]
> Just updated from an earlier version (i don't remember which one sorry) to the latest one, and for some reason it's detecting my windows settings as 7.1 Surround (it's not, I am however using a MOTU M2 audio interface that uses ASIO drivers, so might be that?) so whenever certain things like the shotgun are fired in a specific part of a corridor or what have you, it down-mixes the 7.1 to stereo which then proceeds to make it extremely loud.
> 
> Any way to fix this?

one fix I found is that go into sound settings and do a speaker test in windows, That actually fixes it for me

**Comment by Polymega** [comment]
It's part of what happens when you have a loud-ish sound in conjunction with 3D audio. We do offer the tools for a user to edit any of the sound files. See here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts
