### ISSUE TITLE
Error when updating the FMV pack

### ISSUE THREAD

**Issue by Tasosgemah** [elishacloud/Silent-Hill-2-Enhancements#1013]
I always get this error when i try to update to the latest version

![Untitled](https://github.com/user-attachments/assets/f4fc4e0e-8829-4aef-8ef7-c7c9f9492322)

**Comment by Polymega** [comment]
Please see here: https://x.com/WhereAllBegins/status/1829643993917112408

**Comment by M00nBr1ght** [comment]
now I'm getting a "failed to query" error after attempting a download multiple times, is this related?

**Comment by Polymega** [comment]
The servers are hit really hard.

![Screenshot_20240830-202809](https://github.com/user-attachments/assets/16f30e20-d016-40f2-9746-e2e602c23f01)

**Comment by Guilherme-Weber** [comment]
i gonna try again tomorrow...
![image](https://github.com/user-attachments/assets/ac34fae9-76c4-40d2-9933-27166f8c1231)

**Comment by rockinathan** [comment]
![Screenshot (1070)](https://github.com/user-attachments/assets/bd449238-c2b6-44da-9df4-0027f6e493c5)
Do I cancel this? Or will I update it after two days?
