### ISSUE TITLE
Castillian Spanish Fan-Translation breaks main menu screen with the newest update.

### ISSUE THREAD

**Issue by AmyRoxwell** [elishacloud/Silent-Hill-2-Enhancements#1014]
First, thank you so much for this massive update, really love to see my favorite game running so well on linux!

Now, Currently it seems that trying to boot the game with the Castillian Fan-Translation made by Victor "IlDucci" González causes the main title screen to freak out and show as this 

![Screenshot_20240830_170755](https://github.com/user-attachments/assets/3d2edc3d-3750-4664-95d4-68ff41559085)

Changing the language doesn't seem to have any effect after applying the translation: (switching to english for this screenshot)

![Screenshot_20240830_171219](https://github.com/user-attachments/assets/cd0f0157-23c0-4760-ae6f-c3cd60a02b89)

At least for the small amount of testing I had done it only seems to affect the Title Screen, you can see here in the settings menu and in-game inventory look correct

![Screenshot_20240830_171320](https://github.com/user-attachments/assets/16e51441-c96d-4d2d-aeff-7fcc9756b999)

![Screenshot_20240830_171339](https://github.com/user-attachments/assets/3d4c7739-67f2-49bf-97ce-45e2b50c7f94)

Log:
[d3d8.log](https://github.com/user-attachments/files/16822426/d3d8.log)

**Comment by Polymega** [comment]
I've messaged Victor and he's going to check/troubleshoot this. I'll let you know when it gets resolved. Sorry about that.

**Comment by AmyRoxwell** [comment]
> I've messaged Victor and he's going to check/troubleshoot this. I'll let you know when it gets resolved. Sorry about that.

It's fine!, I can wait until it gets fixed, just in case tho, Is there a way to remove this fan-translation package in the mean time?

**Comment by Polymega** [comment]
> > I've messaged Victor and he's going to check/troubleshoot this. I'll let you know when it gets resolved. Sorry about that.
> 
> It's fine!, I can wait until it gets fixed, just in case tho, Is there a way to remove this fan-translation package in the mean time?

Yep, simply delete the `lang` folder found in the game's main directory and it'll fully remove the translation package.

**Comment by AmyRoxwell** [comment]
> > > I've messaged Victor and he's going to check/troubleshoot this. I'll let you know when it gets resolved. Sorry about that.
> > 
> > 
> > It's fine!, I can wait until it gets fixed, just in case tho, Is there a way to remove this fan-translation package in the mean time?
> 
> Yep, simply delete the `lang` folder found in the game's main directory and it'll fully remove the translation package.

Thanks!

**Comment by Polymega** [comment]
This is now fixed/addressed. Please re-download the Castilian Language Pack from the project's website!
