### ISSUE TITLE
Congrats on The Final Release!

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#1015]
Really, that’s all I wanted to say. I’ve been following this for years and attempted to make small contributions if I could, but you guys deserve all the glory and credit for this massive achievement.

Really. Thank you for keeping this game alive and bringing it to be the best it can be (refrigerator cords and all!)

(btw are you guys fully done or is there still room for hot fixes and the like? I shouldn’t want to report sniveling issues if you’ve wrapped!)

**Comment by Polymega** [comment]
Thank you!! For all intents and purposes, we're wrapping up the project now.

**Comment by UserGit-2021** [comment]
> Thank you!! For all intents and purposes, we're wrapping up the project now.

Questions.
Is this the last update? What are your plans for the future?

**Comment by Polymega** [comment]
> > Thank you!! For all intents and purposes, we're wrapping up the project now.
> 
> Questions. Is this the last update? What are your plans for the future?

Please see here: https://x.com/WhereAllBegins/status/1829600150899343500
