### ISSUE TITLE
SHEE Setup Tool/Updater - webcsv.url Error

### ISSUE THREAD

**Issue by GrEgStAr3000** [elishacloud/Silent-Hill-2-Enhancements#1016]
Hello,

I can´t get the Online updater to work and it always show´s me a ,, webcsv.url ,, error message.

My anti Virus Program & the Windows Firewall are both turned off.

For that reason I really would appreciate a Standalone Installer or a Folder with all the necessary Files bundled together.

I can´t tell if it is just me and my old OS but please help me out with this one dear SH EE - Team.

**Comment by GrEgStAr3000** [comment]
![Uploading Unbenannt.png…]()

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Polymega** [comment]
Please see here: https://x.com/WhereAllBegins/status/1829643993917112408

**Comment by GrEgStAr3000** [comment]
. . .doesn´t work for me. =// When i double click the w32-w64_ranlib.exe only a black windows for a brief moment appears. . .

**Comment by Polymega** [comment]
We don't recommend download repacks of our project. We can't monitor or control what other files people may put in their repacks of our project.

**Comment by GrEgStAr3000** [comment]
I think it would be really, really handy if you good developers could provide a ready to go-Folder with all the neccesary files placed in it. I know that it sounds kind of arrogant.

**Comment by GrEgStAr3000** [comment]
. . . Mr. Polymega, is there really no way you could provide me with a portable folder & ready to play Folder? I want to enyoj the new updates like everybody else. Please

**Comment by Polymega** [comment]
We've had reports it's not wanting to connect based on location/region. I'm unsure at the moment why that is but it's something we of course want to look into.

If you can temporarily use a free VPN, please try that and see if it will then allow you to connect. Sorry for the troubles here.

**Comment by GrEgStAr3000** [comment]
I´m sorry, don´t want to be rude or something but where is this topic completed?? Ó__ò I still can´t get the installer to work and there hasn´t been a ready to play / portable - release. ?????
