### ISSUE TITLE
Downloading at 1/2 a megabyte per second, says it need two hours

### ISSUE THREAD

**Issue by Sapdud** [elishacloud/Silent-Hill-2-Enhancements#1019]
Hi there, I tried to download the game from the enhanced edition setup installer, but for some reason on the very first file (the audio enhancement pack) its starts at about 1.2mb/s before slowing down to around 500kb/s, then slowing even further to 400kb/s (Edit: It has stabilized to 380kb/s and says it will take 2 hours and 52 minutes to complete) (Edit 2: The speed has jumped up to 420kb/s, but it has only loaded a third of the audio file size, it still needs 2 hours, I have attached an extra screenshot). I'm not sure what's the cause of this, is it just the normal download speed for audio files? Perhaps your hosting from somewhere and there's a lot of downloads coming in all at once and I just need to wait maybe two weeks for the traffic to cool down. Alternatively it could have something to do with the fact that my gaming laptop is 10 years old and the website says that it needs to be at least 8 years old to run at minimum, but I don't think that has anything to do with the download rate since I can install other games at above 60mb/s at least, so going less than a megabyte per second doesn't make much sense.

If you need PC specs, I have a gaming laptop from 2014-2015 that has a GTX 1050 graphics card and a CPU with base 2.2Ghz, so its slow in comparison to modern standards. Also my Wi-Fi has full bars, so it's not that.

Here are the screenshots of the speed getting slower and slower.
![Screenshot (1)](https://github.com/user-attachments/assets/15063b42-e15e-43f0-bafe-e44ce37c544c)
![Screenshot (2)](https://github.com/user-attachments/assets/fa8d574e-e021-4953-a3f4-048c626544b0)
![Screenshot (3)](https://github.com/user-attachments/assets/8675cf0f-0db2-4837-a37a-0b9757dc2e08)
![Screenshot (4)](https://github.com/user-attachments/assets/14cad3eb-846b-4d4d-9d01-ccc29a771d18)
![Screenshot (6)](https://github.com/user-attachments/assets/61d5b075-32d9-404b-bc62-62fc3ceca265)
![Screenshot (7)](https://github.com/user-attachments/assets/48bca908-8034-49d5-b38f-386c186f82e8)

I hope this issue is resolved or at least explained to me, if it does come down to it I'll leave my PC on for two hours.

**Comment by AeroWidescreen** [comment]
The server is being hammered because a large amount of people are all trying to download the files at once. I would suggest just waiting a day or two before attempting it again. There's really nothing we can do about it.

**Comment by Sapdud** [comment]
> The server is being hammered because a large amount of people are all trying to download the files at once. I would suggest just waiting a day or two before attempting it again. There's really nothing we can do about it.

Oh, thanks for telling me that, I'll wait maybe three weeks or even until Halloween. Have a good night, if it is night where you are.
