### ISSUE TITLE
Hungarian and Serbian translation

### ISSUE THREAD

**Issue by cs-nokturnal** [elishacloud/Silent-Hill-2-Enhancements#1020]
Hello,

I would like to create a translation pack for the game but i dont know where to start. The last time i translated a game, there was an excel file with all the strings that had to be translated. Can you please help me where to start?

**Comment by Pocokk** [comment]
For a Hungarian translation pack, this person started it, try to contact/get in touch with him: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/788

**Comment by cs-nokturnal** [comment]
What would be the process to start my own translation pack in serbian?

**Comment by Pocokk** [comment]
In that task I linked above (#788), you can see some brief description on how to start the whole process.

**Comment by cs-nokturnal** [comment]
Thanks!
