### ISSUE TITLE
Direct download Links

### ISSUE THREAD

**Issue by robertesaum** [elishacloud/Silent-Hill-2-Enhancements#1022]
Hey!

You guys can share the new direct download links? Cause I'm getting a error on the Setup (something like "files unavailable - failed to query one or more components" - I don't know the error message exactly because I'm using Windows in Portuguese).

Thanks!

**Comment by Nicolas-Miranda** [comment]
Search for "SH2EE_" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the temp folder you can find a .csv file with all the package urls, you can use them to download the packages manually.

**Comment by robertesaum** [comment]
> Search for "SH2EE_" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the temp folder you can find a .csv file with all the package urls, you can use them to download the packages manually.

Thanks, I did this previously but couldn't get the link for the new hotfix :(

**Comment by Nicolas-Miranda** [comment]
> > Search for "SH2EE_" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the temp folder you can find a .csv file with all the package urls, you can use them to download the packages manually.
> 
> Thanks, I did this previously but couldn't get the link for the new hotfix :(

[sh2ee.txt](https://github.com/user-attachments/files/16848246/sh2ee.txt)
