### ISSUE TITLE
Doors from the first floor of the Bluecreek apartaments use door textures from the 2nd floor

### ISSUE THREAD

**Issue by ApolloEM** [elishacloud/Silent-Hill-2-Enhancements#1025]
![Screenshot_2](https://github.com/user-attachments/assets/1efb4a10-9478-4bf2-8cc1-f40ad507c679)
![Screenshot_3](https://github.com/user-attachments/assets/af11e8aa-d312-45ee-805d-3c3738b23ec8)

I was in front of room 105 of the Bluecreek apartaments, the room with the little coin table, but I realized the door said '205'. I checked my map and it was actually room 105, I don't know if this is how it always was, but it made me scratch my head a little. It's like this for all the other doors on the floor as well, they all say '20x'.

**Comment by Polymega** [comment]
Oh how strange. Let me look into that. We'll fix it either way but I'm curious if it's like that for all versions or a mistake on our end. Thanks for catching that!

**Comment by Polymega** [comment]
This is now fixed as part of our first hotfix for this update release! Thanks again for catching this.
