### ISSUE TITLE
Files unavailable to install (Fixed)

### ISSUE THREAD

**Issue by JIF03** [elishacloud/Silent-Hill-2-Enhancements#1026]
![Sem título](https://github.com/user-attachments/assets/aab7cf02-b269-45a8-a348-0a0aeef46f7d)

**Comment by magorockeiro** [comment]
same here :/

**Comment by tioslash** [comment]
Same error here. I´ve tried to download yesterday as soon as I saw that the final update was available but the download speed was so slow that I canceled it and was waiting to try again today. Now I´m getting this error everytime. Tried to re-download the setup tool but did not work aswell.

**Comment by JIF03** [comment]
> same here :/ 
> Eu não sei dizer se isso tá acontecendo por causa do excesso de tráfego online ou por causa de alguma outra coisa

**Comment by JIF03** [comment]
> Same error here. I´ve tried to download yesterday as soon as I saw that the final update was available but the download speed was so slow that I canceled it and was waiting to try again today. Now I´m getting this error everytime. Tried to re-download the setup tool but did not work aswell.
> Vou te responder em português. Cara, isso é exatamente o que aconteceu comigo, tentei atualizar e não deu, aí desinstalei e quando vou instalar de novo, sempre dá essa tela pra mim. Não sei se isso é excesso de tráfego online ou algum outro problema que a gente não sabe ainda.

**Comment by kingphil006** [comment]
same for me

**Comment by robertesaum** [comment]
> Same error here. I´ve tried to download yesterday as soon as I saw that the final update was available but the download speed was so slow that I canceled it and was waiting to try again today. Now I´m getting this error everytime. Tried to re-download the setup tool but did not work aswell.

Same here, I can only download it via the direct link, but I don't know which ones are the most recent.

**Comment by Guilherme-Weber** [comment]
same here

**Comment by Guilherme-Weber** [comment]
on the temp files createt by the Setup i found this thing
![image](https://github.com/user-attachments/assets/08a5d0cb-24f3-4254-86ff-941c95e62bbd)
inside was the individual downloads that the setup(SH2EEsetup.exe) would download, 
![image](https://github.com/user-attachments/assets/198ef6bb-90a2-4bc2-9468-9635e780f017)
most of then download just fine, but "https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.6.0.zip" it simply error out
![image](https://github.com/user-attachments/assets/6257262a-4e97-4ecc-a494-0e431f720fcd)

The first problem of this Open Issue is on the SH2EEsetup.exe, the FMV pack problem is on the server...
i dont know why or how... but this was what i discover, hope it helps

**Comment by AshwinFuller** [comment]
i have same issue here right now, no idea on when it will be fixed?

**Comment by jessicappagostini** [comment]
Same here 🙁

**Comment by danonezz** [comment]
same thing here :/

**Comment by robertesaum** [comment]
As @Nicolas-Miranda said in my ticket, you can search for "_sh2ee.csv" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the "_sh2ee.csv" file, open with notepad and you can find all the package URLs, you can use them to download the packages directly.

**Comment by tioslash** [comment]
> As @Nicolas-Miranda said in my ticket, you can search for "_sh2ee.csv" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the "_sh2ee.csv" file, open with notepad and you can find all the package URLs, you can use them to download the packages directly.

Thanks. I could download most packages individually but the SH2EE_FMV_Enhancement_Pack_1.6.0.zip never downloads and gives a message that the file is not on the website.

**Comment by lecosilva** [comment]
> > As @Nicolas-Miranda said in my ticket, you can search for "_sh2ee.csv" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the "_sh2ee.csv" file, open with notepad and you can find all the package URLs, you can use them to download the packages directly.
> 
> Thanks. I could download most packages individually but the SH2EE_FMV_Enhancement_Pack_1.6.0.zip never downloads and gives a message that the file is not available on the website.

If you're getting this message, try a VPN and do not let it choose the fastest available by itself, pick an uncommon location.
It appears that the fastest locations available are being used to a sum where they still remain as congested ones, so you won't be able to download the packages. I've manually selected Andorra (while actually in Brazil) and the setup worked, even though slowly.

**Comment by kingphil006** [comment]
> > > As @Nicolas-Miranda said in my ticket, you can search for "_sh2ee.csv" under C:/Users/%UserName%/appData/local/temp when you run the SH2EEsetup.exe. Once you locate the "_sh2ee.csv" file, open with notepad and you can find all the package URLs, you can use them to download the packages directly.
> > 
> > 
> > Thanks. I could download most packages individually but the SH2EE_FMV_Enhancement_Pack_1.6.0.zip never downloads and gives a message that the file is not available on the website.
> 
> If you're getting this message, try a VPN and do not let it choose the fastest available by itself, pick an uncommon location. It appears that the fastest locations available are being used to a sum where they still remain as congested ones, so you won't be able to download the packages. I've manually selected Andorra (while actually in Brazil) and the setup worked, even though slowly.

Hello, I'm also from Brazil, there's any free vpn solution that I can use? Or maybe you can share the SH2EE_FMV_Enhancement_Pack_1.6.0 by any means. Thanks in advance.

**Comment by LogeViper** [comment]
same here.

hope they fix this soon.

really annoying.

**Comment by D4rkZ0mb1e** [comment]
same here. save us !!! ♥

**Comment by leandrofmoraes** [comment]
same here

**Comment by Polymega** [comment]
We've had reports it's not wanting to connect based on location/region. I'm unsure at the moment why that is but it's something we of course want to look into.

If robertesaum's recommendation of temporarily using a VPN to connect works, I'd encourage you to test that out.

**Comment by AshwinFuller** [comment]
i managed to make it work by using a VPN and also downloading the FMV Pack through a mirror i made.

https://pixeldrain.com/u/uct12PNd

let me know if i'm not allowed to post it and i'll delete it promptly!

after doing that it worked pretty perfectly

**Comment by Nicolas-Miranda** [comment]
@D4rkZ0mb1e, I'm uploading the latest packages to a Dropbox folder:

https://www.dropbox.com/scl/fo/colox2vpyinjukycr8av7/AL3O_u41tfK-QfU5o-H2508?rlkey=tsmra1ayhs28kousrkop14tlm

Give it some minutes as some packages are still uploading

**Comment by robertesaum** [comment]
Here are official direct download links to the latest packages:

| **Module** | **Link** |
| --- | --- |
| Setup Tool | https://files.townofsilenthill.com/SH2EE/SH2EEsetup.exe |
| Enhancements Module | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhancements_Module_3.0.2210.0.zip |
| Enhanced Executable | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.4GB.zip |
| Wine Stub | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Wine_Stub_1.0.1.zip |
| Enhanced Edition Essential Files | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.3.1.zip |
| Image Enhancement Pack | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.2.0.zip |
| FMV Enhancement Pack | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.6.0.zip |
| Audio Enhancement Pack | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.1.0.zip |
| Xidi | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Xidi_4.2.0.zip |
| Credits | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Credits_1.6.1.zip |

**Comment by LogeViper** [comment]
Fixed.

it's now working without any issues.

**Comment by JIF03** [comment]
For those involved in the resolution of this issue, thank you! :)

**Comment by JIF03** [comment]
For those involved in the resolution of this issue, thank you! :)
