### ISSUE TITLE
Small Request: Please replace the "tricycle wheel" sound for the Creeper enemy.

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1028]
You will have my eternal gratitude for that small improvement that went overlooked.

https://www.youtube.com/watch?v=Mze8wvJPF7g

**Comment by Polymega** [comment]
Sorry, but the cockroaches will continue to ride their little tricycles. We do, however, provide the tools for you to edit/modify any given sound file in the game. See here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts
