### ISSUE TITLE
Offline Installer Error Message

### ISSUE THREAD

**Issue by Atrus99** [elishacloud/Silent-Hill-2-Enhancements#1029]
When I select the "Install and backup enhancement packages" option in SH2EEsetup to create an offline installer everything seems to download and install as it should, but when I attempt to install the backup using the SH2EEsetup file I receive an error message that says "Runtime error (at 334:2603): List index out of bounds (-2)".  

I can manually copy files over to the SH2 directory from each zip file, but I was under the impression this was an offline installer and if that's the case something doesn't seem to be working properly.  I was thinking maybe something might be missing in the "local_sh2ee.dat" file but I wouldn't know what I'm looking for.

![Error Message](https://github.com/user-attachments/assets/0fbd7161-9512-4db2-a343-0195d7edbe36)
![Local DAT](https://github.com/user-attachments/assets/b4a54bf7-f9eb-4d8e-a510-5e38721146ba)

**Comment by szbozso94** [comment]
I have the same problem. i wanted to install the new update but I received a Rintime error. The only difference I have is the in the error pop up window.
![Képkivágás](https://github.com/user-attachments/assets/b873b1f9-8b54-4310-859b-4cfa7b6a5103)

**Comment by MarioTainaka** [comment]
Same problem here, just reported it as well in a separate thread.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/1034

**Comment by juampe82** [comment]
También me sale el mismo error para la instalación offline, ayuda por favor.
![error](https://github.com/user-attachments/assets/6db258dc-91a4-4731-9397-afb69afe870f)

**Comment by Polymega** [comment]
We'll have to make our installer programmer @nipkownix aware of this to have him look into what's going on.

**Comment by juampe82** [comment]
muchas gracias, somos muchos a la espera de una solución.

**Comment by nipkownix** [comment]
Sorry for the delay, I'll be taking a look at this during the weekend.

**Comment by juampe82** [comment]
> Iba a hacer una publicación para informar este problema, me alegra ver que alguien se me adelantó.
> 
> La única forma que tuve de instalarlo localmente en modo automático fue usar la versión 1.1.3 del exe y cambiar el número de versión en la línea 3 de “local_sh2ee.dat”. Luego, una vez instalada la edición mejorada, reemplacé la versión 1.1.3 de “SH2EEsetup.exe” con la versión 1.1.4 en el directorio del juego.
> 
> Me alegra ver que esto se va a solucionar, me encanta el trabajo que han hecho aquí para este juego que todos amamos.

Hola, gracias por esa idea.
Lastimosamente no todos los usuarios conservamos la version 1.1.3 del exe. No es una solución fácil y valida para todos.
A la espera de la solución definitiva!!

**Comment by Polymega** [comment]
We just pushed out a hotfix for our project an hour ago that resolves this issue. Thanks for being patient with us about this!

**Comment by Atrus99** [comment]
> We just pushed out a hotfix for our project an hour ago that resolves this issue. Thanks for being patient with us about this!

I just tested the app and it's working great!  Thanks so much to everyone involved!
