### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by Orileh** [elishacloud/Silent-Hill-2-Enhancements#1031]
[d3d8.log](https://github.com/user-attachments/files/16830590/d3d8.log)
Every time I open the game it's stuck on black screen and then crashes. Please help!

**Comment by Polymega** [comment]
Have you modified your log file?

**Comment by elishacloud** [comment]
Try disabling DSOAL.

**Comment by Orileh** [comment]
> Have you modified your log file?

No

**Comment by Orileh** [comment]
> Try disabling DSOAL.

How do I do that?

**Comment by Orileh** [comment]
> Try disabling DSOAL.

![image](https://github.com/user-attachments/assets/0274aa74-9d02-4190-9a3e-66eb3a55d4ba)

**Comment by Polymega** [comment]
To disable DSOAL, open `SH2EEConfig.exe`, go to the audio tab, and _uncheck_ "Use DSOAL and OpenAL for EAX audio".

I asked if you modified your log file as there are several blank lines under the `|-------- MODULES LOADED --------` section. Also, it says your game's directory path is `4816 00:36:08.380 PatchSFXAddr Error: Could not open sddata.bin file! C:\Users\abdce\OneDrive\????? ??????\Games\Silent Hill 2\data\sound\sddata.bin` which is weird because you can't use question marks as part of a folder or file name.

Lastly, near the top of your log, it's says you're running the game as `Game.exe` whereas this should be saying `sh2pc.exe`. The whole log is odd to me.

**Comment by Orileh** [comment]
> To disable DSOAL, open `SH2EEConfig.exe`, go to the audio tab, and _uncheck_ "Use DSOAL and OpenAL for EAX audio".
> 
> I asked if you modified your log file as there are several blank lines under the `|-------- MODULES LOADED --------` section. Also, it says your game's directory path is `4816 00:36:08.380 PatchSFXAddr Error: Could not open sddata.bin file! C:\Users\abdce\OneDrive\????? ??????\Games\Silent Hill 2\data\sound\sddata.bin` which is weird because you can't use question marks as part of a folder or file name.
> 
> Lastly, near the top of your log, it's says you're running the game as `Game.exe` whereas this should be saying `sh2pc.exe`. The whole log is odd to me.

I changed up the sh2pc file name.
I redownload the entire folder from MyAbandonware and did everything again. I'll send the new log in a sec.

**Comment by Orileh** [comment]
[d3d8.log](https://github.com/user-attachments/files/16830745/d3d8.log)
There you go

**Comment by Orileh** [comment]
> > To disable DSOAL, open `SH2EEConfig.exe`, go to the audio tab, and _uncheck_ "Use DSOAL and OpenAL for EAX audio".
> > I asked if you modified your log file as there are several blank lines under the `|-------- MODULES LOADED --------` section. Also, it says your game's directory path is `4816 00:36:08.380 PatchSFXAddr Error: Could not open sddata.bin file! C:\Users\abdce\OneDrive\????? ??????\Games\Silent Hill 2\data\sound\sddata.bin` which is weird because you can't use question marks as part of a folder or file name.
> > Lastly, near the top of your log, it's says you're running the game as `Game.exe` whereas this should be saying `sh2pc.exe`. The whole log is odd to me.
> 
> I changed up the sh2pc file name. I redownload the entire folder from MyAbandonware and did everything again. I'll send the new log in a sec.

Figured what the issue was. The directory folder was located in my desktop. I moved it to disk C and it solved everything. my pc seems to cause issues when I locate stuff on my desktop. I wonder what could cause that.

**Comment by Orileh** [comment]
> > > To disable DSOAL, open `SH2EEConfig.exe`, go to the audio tab, and _uncheck_ "Use DSOAL and OpenAL for EAX audio".
> > > I asked if you modified your log file as there are several blank lines under the `|-------- MODULES LOADED --------` section. Also, it says your game's directory path is `4816 00:36:08.380 PatchSFXAddr Error: Could not open sddata.bin file! C:\Users\abdce\OneDrive\????? ??????\Games\Silent Hill 2\data\sound\sddata.bin` which is weird because you can't use question marks as part of a folder or file name.
> > > Lastly, near the top of your log, it's says you're running the game as `Game.exe` whereas this should be saying `sh2pc.exe`. The whole log is odd to me.
> > 
> > 
> > I changed up the sh2pc file name. I redownload the entire folder from MyAbandonware and did everything again. I'll send the new log in a sec.
> 
> Figured what the issue was. The directory folder was located in my desktop. I moved it to disk C and it solved everything. my pc seems to cause issues when I locate stuff on my desktop. I wonder what could cause that.

So as it turns out. The problem was that my desktop's folder name was not in english. I switched it to english and it solved the issue. Thank you for your help and time guys. I really appreciate it.
