### ISSUE TITLE
Updating packages will not let me click on them

### ISSUE THREAD

**Issue by Horrorfan316** [elishacloud/Silent-Hill-2-Enhancements#1033]

**Comment by Horrorfan316** [comment]
i cannot click on any of them to install

**Comment by Nicolas-Miranda** [comment]
@Horrorfan316, there is a SH2EE_Setup.dat file (may have a different name but is a .dat file) delete it and open the SH2EE_Setup.exe to install the packages from scratch. It will download the latest ones available.

**Comment by MarioTainaka** [comment]
Using repair and redownloading via that actually fixes the issue. I think something's wrong with the dat file
