### ISSUE TITLE
Index Out Of Bounds Error With Local installation

### ISSUE THREAD

**Issue by MarioTainaka** [elishacloud/Silent-Hill-2-Enhancements#1034]
tried installing the latest local install I backed up during the weekend on my main system and  I keep getting this error. It also happens on my lapton
![Untitled](https://github.com/user-attachments/assets/b0d4a456-133d-44ab-86e7-f7f8b0be063e)

**Comment by Atrus99** [comment]
I'm also receiving the same error message. #1029

**Comment by leandrofmoraes** [comment]
Same issue here. :/

**Comment by Polymega** [comment]
We'll have to make our installer programmer aware of this to have him look into what's going on.

**Comment by juampe82** [comment]
Tengo el mismo problema, tengo copia de seguridad de los paquetes de instalación ya actualizados. Quiero hacer una instalación offline pero al ejecutar el instalador "SH2EEsetup" me sale el siguiente error. Con la actualización antigua este error no sucedía. Somos muchos usuarios indicando este error, ayuda por favor!!.

![error](https://github.com/user-attachments/assets/26b049cc-8ecd-4efe-bf2c-94e9626edfaa)

**Comment by juampe82** [comment]
Hola, sigue sin solución este error?

**Comment by Polymega** [comment]
We have a fix in place for this that we'll be releasing soon.

**Comment by juampe82** [comment]
> We have a fix in place for this that we'll be releasing soon.

No hay solución todavia?

**Comment by Polymega** [comment]
We just pushed out a hotfix for our project an hour ago that resolves this issue. Thanks for being patient with us about this!
