### ISSUE TITLE
Inverted "No Parking" texture in building after Pyramid Head apartment boss.

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1035]
Just after the Pyramid Head boss fight and right before the painted wall where you find Laura, there is a building with inverted "No Parking" textures as shown here:

![20240902235712_1](https://github.com/user-attachments/assets/3199a319-673a-4abb-9d62-64cf1a174559)

The same building asset is used right beside where Laura was sitting and has the "No Parking" texture in the right orientation as shown here:
 
![20240902235931_1](https://github.com/user-attachments/assets/9de46886-b799-4da6-a9f5-e172aab61388)

I hope this can be considered for a future patch

**Comment by Polymega** [comment]
Hi there,

I went ahead and fixed this as part of the hotfix we released a couple days ago: https://x.com/WhereAllBegins/status/1830064141316288659

**Comment by Nicolas-Miranda** [comment]
@Polymega Thanks for the update. How can I install the hotfix? The SH2EEsetup tool doesn't let me update anything after installing the final update.

**Comment by Polymega** [comment]
There was a lot of congestion last week on the server. Has it cleared up to inform you of a new project update? That update would be the hotfix.
