### ISSUE TITLE
I wish to get a Spanish (Latin America) translation working. Where to start?

### ISSUE THREAD

**Issue by dravenlh4** [elishacloud/Silent-Hill-2-Enhancements#1036]
Hi!

I am licensed English-Spanish translator (from South America), and I would love to work on a Latam Spanish language pack, since the final update for SH2EE has been released as of now and many text strings have changed to accomodate to those modifications. The available official Spanish language is serviceable enough, but since there's an excellent updated Castillian (Spain) pack available, I would love to work on one for us, latin-american players.

Where should I start? I know my basic translation software but I'm not familiar with the tools needed to edit those ".mes" files I see. I would appreciate any guidance. 

EDIT: Found the translation guide doc file... reading it...

Cheers, and congrats on this grand milestone!

**Comment by Polymega** [comment]
Hi there,

Just a heads-up that the person who made the Castilian translation pack also re-did the entire official Spanish language in the game. His work for the Latin American Spanish is included in our project and replaced the game's original Spanish language files.

**Comment by dravenlh4** [comment]
Hi,

Yes. From what I understand, a lot of the now-present Spanish files have been updated as I have read to make up for a "neutral" experience for any Spanish speaker, by the same folks who worked on the Castillian translation. 

While a lot of it is great, there's some stuff that may have been overlooked, like some expressions, names for things, adjectives or cases of structural verb tense that are more common in Spain but not so much over here (more noticeable in notes, newspapers and riddles found throughout the game, and also during exploration, things like interactive objects or some dialogues).

Just to give an example, there is this "Dear Tim" note, where "to run errands" is used. In the game it reads "_hacer recados"_ in the current Spanish, but in Latin America we would say _"hacer mandados"_. That's one of the many discrepancies found, which is reasonable enough, to be honest.

So yeah, if not an issue, I would still love to give it a go.

**Comment by danuffo** [comment]
> Hi,
> 
> Yes. From what I understand, a lot of the now-present Spanish files have been updated, as I have read, to make up for a "neutral" experience for any Spanish speaker, by the same folks who worked on the Castillian translation.
> 
> While a lot of it is great, there's some stuff that may have been overlooked, like some expressions, names for things, adjectives or cases of structural verb tense that are more common in Spain but not so much over here (most noticeable in notes, newspapers and riddles found throughout the game, and also during exploration, things like interactive objects or some dialogues).
> 
> Just to give an example, there is this "Dear Tim" note, where "to run errands" is used. In the game it reads "_hacer recados"_ in the current Spanish option, but in Latin America (where _"recado"_ is related to given messages) we would say _"hacer mandados"_. That's one of the many discrepancies found, which is reasonable enough, to be honest.
> 
> So yeah, if not an issue, I would still love to give it a go.

Hello, I am also interested helping, and I have experience editting Silent Hill games, those called .mes files are the same names as the SH2 PlayStation 2 version, there's a probability I can figure it out.

Actually, I have recently finished my Latinamerican Spanish translation for Silent Hill 4 (PlayStation 2), and it also has .mes files, I will be releasing it soon on romhacking.net, blog and any other good place I can find.

I had the same idea for SH2, do you have other way to contact? discord?

**Comment by dravenlh4** [comment]
> 
> Hello, I could help.
> 
> I have recently finished my Latinamerican Spanish translation for Silent Hill 4 (PlayStation 2), and I know Silent Hill 2 in the console also has .mes files, I will be releasing it soon on romhacking.net, blog and any other good place I can find.
> 
> I will try by myself later because it's the same idea I got, but if you wish to team up, just tell me.

Yo. I just saw this! I recently figured how to mess with the .mes files and I've been experimenting a little. I would definitely love to team up, tho. 

I just looked up your username on Discord. Mine is "fandreios".

**Comment by danuffo** [comment]
Guess I better write my translation by my own, maybe I will share it along the other mods or maybe will make public at my own sites.

**Comment by Polymega** [comment]
Would you mind if I close the ticket here since you're continuing discussions on Discord?

**Comment by dravenlh4** [comment]
> Would you mind if I close the ticket here since you're continuing discussions on Discord?

Yes. Please do. After some nasty racist remarks by that guy on Discord I'm doing it on my own. I'll submit it when it's done, if it's not a problem. Thank you, and sorry for the inconvenience.
