### ISSUE TITLE
Missing Master volume and render scale and health indicator options

### ISSUE THREAD

**Issue by VermillionFury007** [elishacloud/Silent-Hill-2-Enhancements#1038]
![image](https://github.com/user-attachments/assets/69fff86d-478f-4631-9d44-a8c201d6fdf8)
![image](https://github.com/user-attachments/assets/24afdd37-a67c-4472-be9d-a5187cfa6df7)

**Comment by Polymega** [comment]
Ensure you've updated the "SH2E Module" package, as it will contain the updated files to show these new text strings within this menu.

**Comment by VermillionFury007** [comment]
I did, but nowthe updater is giving me this error
![image](https://github.com/user-attachments/assets/8c7f1425-c6ad-4471-adf2-8022c72be9ca)
can't redownload as of now

**Comment by VermillionFury007** [comment]
I did a fresh install and transfered all the sh2e files and it worked! I have no idea why but I'm not complaining. thank you for your work!
