### ISSUE TITLE
Game hangs on boot, then crashes.

### ISSUE THREAD

**Issue by WHERESMYFUCKINGWIFE** [elishacloud/Silent-Hill-2-Enhancements#1039]
While trying to record footage for another issue i was having. when I went to open SH2EE, it just opened up to a black screen, waited a bit, then closed.

[d3d8.log](https://github.com/user-attachments/files/16884968/d3d8.log)

Thanks in advance!

**Comment by Polymega** [comment]
I'm not sure off the top of my head. I noticed the game is located in your OneDrive, is that correct? Would that maybe have something to do with it? (Not sure as I don't use OneDrive.)

**Comment by Polymega** [comment]
Haven't heard a follow-up. Feel free to re-open this ticket if you'd like for us to help and assist.
