### ISSUE TITLE
JoyStick layout is wrong, L2/R2 triggers doesnt work

### ISSUE THREAD

**Issue by albusgod** [elishacloud/Silent-Hill-2-Enhancements#1040]
Game is installed on Arch linux and Flatpak bottles.
SH2Ee runs perfect with all the enhancements, but my dualshock 3 controller doesnt work properly on this game, i tried Xinput and directInput but my controller works like this.
The L2 and R2 trigger doesnt work, instead Select if L2 and Start is R2
Circle is Cross (X)  and some buttons are changed, cannot aim or play this amazing game, any help?

i install mGBA and the control works like intended, my problem is with the SH2Ee.
can anyone help me?

**Comment by largestgithubuseronearth** [comment]
Have you rebound the controls in the game's options? I've been running the game through Lutris Flatpak and using an Xbox One controller. The controls have been perfect except the right stick doesn't work (Search View). The mouse works though.

**Comment by Polymega** [comment]
Hi @albusgod ,
No team members active on our GitHub tickets use Linux so we'll unfortunately not be able to assist with this. I'm hoping largestgithubuseronearth's suggestion works and that other Linux users can further assist in this ticket.

**Comment by albusgod** [comment]
> Have you rebound the controls in the game's options? I've been running the game through Lutris Flatpak and using an Xbox One controller. The controls have been perfect except the right stick doesn't work (Search View). The mouse works though.

Hi, i manage to get my Dualshock3 joystick to work, in the wine config >libraries >add the followings dlls (that are in the games folder).
"x_input1_3" as native
"dinput8" as native/ build in
and in the Sh2EE config i select "dinput" with the playstation layout to use the Right analog for the search camera, with xinput that analog doesnt work.
i hope this info help someone.

> Hi @albusgod , No team members active on our GitHub tickets use Linux so we'll unfortunately not be able to assist with this. I'm hoping largestgithubuseronearth's suggestion works and that other Linux users can further assist in this ticket.
in any case thank for the reply.
maybe this works on lutris too.
