### ISSUE TITLE
Alternate Hospital Reversed "Information Desk" texture

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1041]
The "Information Desk" texture at the hospital entrance is reversed. I noticed this on the alternate version but may be present in the normal version of the hospital too.

![20240905043813_1](https://github.com/user-attachments/assets/fe79f427-be1d-4b77-a40b-974ac847ccef)

**Comment by Polymega** [comment]
Oh wow; good eye! The download package that would address this will be a part of an upcoming hotfix, so I'll go ahead and fix this up. I'm going to pre-emptively close this ticket but it'll be corrected for our future hotfix. Thanks again.
