### ISSUE TITLE
Map Issues

### ISSUE THREAD

**Issue by Piscariello** [elishacloud/Silent-Hill-2-Enhancements#1042]
Hi.
Sometimes when I open up the map the issue I encounter is that I can only move the map but not the character's arrow and the other symbols such as dots, circles and so on. Can you please fix it? 

P.S. I just love your work :)

**Comment by Polymega** [comment]
We pushed out a hotfix a few days ago that we believe should fix this issue for you. If you launch the game again, you should receive a message that updates are available. Please ensure you perform the updates and let us know if the issue still persists or not.

**Comment by Piscariello** [comment]
Thank you very much my friend 🙂
________________________________
Da: Polymega ***@***.***>
Inviato: lunedì 9 settembre 2024 00:11
A: elishacloud/Silent-Hill-2-Enhancements ***@***.***>
Cc: Piscariello ***@***.***>; Author ***@***.***>
Oggetto: Re: [elishacloud/Silent-Hill-2-Enhancements] Map Issues (Issue #1042)


We pushed out a hotfix a few days ago that we believe should fix this issue for you. If you launch the game again, you should receive a message that updates are available. Please ensure you perform the updates and let us know if the issue still persists or not.
