### ISSUE TITLE
Soft crashing in when entering room

### ISSUE THREAD

**Issue by Rintere** [elishacloud/Silent-Hill-2-Enhancements#1044]
Currently at the apartments section, and everything was working fine until I went into room 210. The game shows a black screen for a solid 20 seconds before stating that files are missing and "please reinstall Silent Hill 2". I've reinstalled the original game and the mod to no avail. It's the only room that does this as far as I know, no other rooms in the complex do it.

**Comment by Rintere** [comment]
![image](https://github.com/user-attachments/assets/0545ba03-4688-4399-b3a4-b33954ffcca2)

**Comment by Rintere** [comment]
Didn't even realize the room had barely any significance, I feel stupid now

**Comment by Rintere** [comment]
Reopening because the issue persists when going through the blue door on the second floor after finishing the clock puzzle. Initially closed the issue because it seemed like a one time problem in an unimportant room, but this halts my progression as far as I'm aware. Even if it doesn't, I would like to find a fix simply to be able to explore everywhere.
![image](https://github.com/user-attachments/assets/695f3a56-e644-4b43-bcba-7e70770c30b6)
![image](https://github.com/user-attachments/assets/c729b812-9bf7-489a-8ab3-627104b45173)
[d3d8.log](https://github.com/user-attachments/files/16914232/d3d8.log)

**Comment by AeroWidescreen** [comment]
This doesn't sound like a problem with SH2EE. I can enter these rooms just fine. Your log doesn't show anything out of order, at least at first glance. And I'd assume more people would be reporting such a significant issue if they were experiencing it as well.

Have you verified that your copy of SH2 is working correctly? Create a backup of your install folder, then use **SH2EEsetup.exe** (located in the install folder) to uninstall SH2EE. Then check if the problem persists.

**Comment by Polymega** [comment]
If it consistently crashes in one, particular spot, that's usually an indicator that there's a bad/corrupt game file somewhere. I can't remember if we modified the staircase file or not, but here's what I'd recommend:

- Launch `SH2EEsetup.exe`, select "Install or Repair Packages", and re-download the "Enhanced Edition Essential Files".

If that doesn't resolve the problem then try this:

- Redownload and install **the vanilla version of SH2 PC** to a whole new directory. Once you have the vanilla game reinstalled, go into its `data\bg\` folder and copy **all** folders in here and past them into your existing `data\bg\` directory where SH2:EE is also installed.

**Comment by Rintere** [comment]
Accidentally deleted a folder by accident, very simple problem apparently lmao. Works fine now
