### ISSUE TITLE
Shadow error in apartments lobby

### ISSUE THREAD

**Issue by Hans1Poppof** [elishacloud/Silent-Hill-2-Enhancements#1046]
Hello, James shadow rapidly changes position in the lobby of the apartments, video below

https://github.com/user-attachments/assets/b612285a-9bb8-4ba9-aa22-b237ddb77dbe

**Comment by largestgithubuseronearth** [comment]
IIRC this is happens with the PS2 original, and is not a bug with enhanced edition or even the PC port. Would be nice if it were improved but that'd prob require a lot more work than just fixing a code mistake. And it doesn't seem like they're done making any big changes.

**Comment by Polymega** [comment]
Yes, that's correct; this is "normal" behavior seen on all versions. We have not reverse engineered shadow trigger zones for the game so are unable to address this.
