### ISSUE TITLE
Prison blackboard texture reversed

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1047]
The blackboard texture in the room before you get the rifle in reversed. The same blackboard texture is in the hallway and is used correctly there.

![20240907041526_1](https://github.com/user-attachments/assets/e1204503-1fbb-4b86-8392-a5c39bf94c17)

**Comment by Polymega** [comment]
Thanks! The download package that would address this will be a part of an upcoming hotfix, so I'll go ahead and fix this up. I'm going to pre-emptively close this ticket but it'll be corrected for our future hotfix. Thanks again.
