### ISSUE TITLE
Image Enhancement Undo

### ISSUE THREAD

**Issue by kotodorii** [elishacloud/Silent-Hill-2-Enhancements#1049]
Having issues disabling the Image Enhancement Pack with the new update. 
There doesn't seem to be an option in the .ini config. 
Any ideas?

**Comment by Polymega** [comment]
Delete `sh2e\pic\` folder.

**Comment by elishacloud** [comment]
Or you could set this option:

![image](https://github.com/user-attachments/assets/ac57a1d5-d921-4b2c-a86d-ab7983180458)
