### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gerooo909** [elishacloud/Silent-Hill-2-Enhancements#1050]
please add the possibility to play the game at a resolution lower than 640x480. People that use CRT monitors like myself can make custom resolutions lower than 640x480. for example i would like to play this enhanced edition but at the original silent hill 2 ps2 internal resolution of 512x448 which is a 8:7 aspect ratio. i made the resolution on nvidia control panel but cant select it on the game and if i try to run it on borderless fullscreen it will change my display resolution to whatever is set on the game menu.

**Comment by Polymega** [comment]
You can set a specific resolution to play the game in. See here: https://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY

**Comment by gerooo909** [comment]
> You can set a specific resolution to play the game in. See here: https://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY

cant find the ResX and ResY settings in d3d8.ini,. maybe they eliminated that? or can i add those lines somewhere?

**Comment by gerooo909** [comment]
> > You can set a specific resolution to play the game in. See here: https://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY
> 
> cant find the ResX and ResY settings in d3d8.ini,. maybe they eliminated that? or can i add those lines somewhere?

okay nevermind that actually worked. i added the "ResX" and "ResY" lines to d3d8.ini in the display section and it worked great, thank you!!
