### ISSUE TITLE
Game freezing, not responding and then crashing upon launch.

### ISSUE THREAD

**Issue by LondoLoafer** [elishacloud/Silent-Hill-2-Enhancements#1051]
Earlier today the game was working for me, later when trying to launch the game again i ran into this issue, after moving the folder from my desktop to my drive I'm now getting a notification from my antivirus that the program does not have a valid digital signature.

[d3d8.log](https://github.com/user-attachments/files/16925902/d3d8.log)

**Comment by elishacloud** [comment]
What antivirus are you using?  Based on where it stopped in the log it looks like something might be damaged or there could be an issue with the dinput8.dll file.

1. Try replacing the d3d8.dll with a good one downloaded from GitHub release page.
2. Try renaming the dinput8.dll file to remove it from the loading cycle.

**Comment by LondoLoafer** [comment]
It seems uninstalling then reinstalling the files fixed the issue, something must have become damaged somehow, thank you for your help!
