### ISSUE TITLE
Question about anti-aliasing

### ISSUE THREAD

**Issue by Nessu4K** [elishacloud/Silent-Hill-2-Enhancements#1054]
So playing this before, I remember using anti-aliasing from my Nvidia GPU, but updating the game or a windows update wiped my settings and I forgot what settings I had or if it's needed.

Should I mess with this or use it?

my GPU anti-aliasing is FXAA and I think I remember putting Anisotropic filtering at x16 (not sure if it does anything)

I know the final update has or it's been there, I don't remember, SSAA for render, but it's not in the setup launcher options anymore
(and I know not to enable SMAA)

Should I put FXAA [On] and AF x16 back or not touch? Also in-game should I turn up the render resolution to "2.0"?

I just want the best quality possible (I'm on 4K monitors and have a modern PC)

**Comment by Polymega** [comment]
In the past, we had a somewhat convoluted fix in place to support MSAA (via forced AA through your GPU's control panel). Since then, we've introduced SSAA, which is a better (but more costlier) version of AA over MSAA.

If you have a modern/respectable PC, you should use SSAA for the best AA available.

Here's what you do:

- Disable any form of forced AA for SH2 PC through your GPU's control panel.
- Update our project.
- Launch the game, go to Options > Advanced Options, and set the Render Resolution to x2.

Render resolution, or render scaling, is another term form super sample anti-aliasing.

**Comment by Nessu4K** [comment]
So in Program Settings to add sh2pc.exe, it was wiped and had to add it again. This is the default settings for my GPU without touching anything.
![Untitled](https://github.com/user-attachments/assets/dc612022-caee-4c7a-a008-631e592dde23)
Anything that needs tweaking? Also, should on put Anisotropic Filtering on (x16) or leave it off?

**Comment by Polymega** [comment]
If there are any lines that are **bold** under the Settings column, that means it's been modified by you. Otherwise, it's the default setting.

You can enable AF if you'd like. I couldn't get it to work with this game but others have reported they successfully could.

**Comment by Nessu4K** [comment]
Yea I don't know completely everything about most of this stuff, this is just default, I didn't alter any of these.
The global settings are just default for me, I'm guessing I can leave all of this as is. 

I will try putting Anisotropic Filtering to x16 again.

**Comment by Nessu4K** [comment]
I see what you mean, THIS bold.
![Untitle2d](https://github.com/user-attachments/assets/64edcd08-25e4-4575-b1a2-e78bb35a5afd)
I went further down the list, these two were like this on their own. 
Last question, should I change these?

**Comment by Polymega** [comment]
> Last question, should I change these?

Truth be told, I'm not sure what those settings do.

**Comment by Nessu4K** [comment]
No problem, thank you for your replies. I will just leave them as they are.

**Comment by TommvinHuwaltzky** [comment]
The best option would be to use DLDSR. And since a 3080 is still pretty ok, you could even combine that with a 2x renderscale.

**Comment by AeroWidescreen** [comment]
> The best option would be to use DLDSR. And since a 3080 is still pretty ok, you could even combine that with a 2x renderscale. And I don't remember if driver-AF works in SH2. Go in game, take a screenshot, close the game, then set the driver-settings to "override", "16x", and leave "clamp" ("Sample-optimization" I personaly have turned to "on"). Then start the game again, take a screenshot in the same spot, and then compare the two.
> 
> And by gawd, leave FXAA off.

Personally I think DLDSR + 4xSSAA (2x Render Scale) is excessive for someone playing at 4K. The render scale alone would be 8K, then you're increasing that even further with DLDSR. lol

I mostly agree with everything else though.

**Comment by Polymega** [comment]
I did a little Googling and it looks like DLDSR is Nvidia's version of SSAA? Our project already offers SSAA (via the Render Resolution) and x2 should be well good to remove aliasing.

**Comment by Nessu4K** [comment]
I don't know how to access DLDSR (I'm still a dummy with computers), is it from the control panel? I will probably take a look at a later date.

**Comment by TommvinHuwaltzky** [comment]
In the Ngreedia-cintrol-panel as well:
<img width="794" alt="Untitled" src="https://github.com/user-attachments/assets/7e88d6b1-0820-40a1-8a4f-46b5e6db3eb7">


After you've checked the boxes and clicked on "apply", you will have the resolutions in Windows as well:
<img width="377" alt="Untitled_" src="https://github.com/user-attachments/assets/d1e538d0-225f-4909-bdbe-f2093b530906">

**Comment by Tasosgemah** [comment]
I don't think you need to go through all that. The enhanced version of the game itself has a scaling slider. If you go above the default 1.0 it will work in a similar way.

**Comment by Nessu4K** [comment]
I switched it in global settings, DSR didn't show in the games specific settings. I'm on a 4K monitor.
I honestly can't tell the difference. Is this right?
![Untitled](https://github.com/user-attachments/assets/aad06d94-cd40-446f-a7f5-476850735d4c)

**Comment by Nessu4K** [comment]
I didn't switch Legacy Scaling to 4.00x, just did now to see. I still can't tell a difference.
I probably don't need to mess with the DSR at all. It looks just as good without it.

**Comment by Polymega** [comment]
Using our built-in Render Resolution at x2 should be more than ample for your needs.

**Comment by TommvinHuwaltzky** [comment]
> DSR didn't show in the games specific Program Settings

So in game you can't select the higher resolutions? Then the game doesn't support arbitrary resolutions, and that wouldn't be correct behavior.

Did you check if you can select the new resolutions for your desktop? If so, you can switch it there, and then run the game in borderless window/fullscreen.

> Using our built-in Render Resolution at x2 should be more than ample for your needs.

DLDSR has objectively higher quality and runs better (haha sorry if I sound like an Ngreedia-shill, but that's just how it is).

**Comment by elishacloud** [comment]
> So in game you can't select the higher resolutions? Then the game doesn't support arbitrary resolutions, and that wouldn't be correct behavior.

The game never supported arbitrary resolutions.  The game has an internal list of supported resolutions and that is it.

However, with this enhancement module we added the ability to support other resolutions.  By default in the game we just list whatever resolutions your video card/monitor can support.  Also, keep in mind that if you are playing in a windowed mode (fullscreen windowed or just windowed) that we don't show any resolutions larger than the current resolution because you cannot make a window larger than the screen resolution.  So if you want to use a resolution larger than the current screen resolution you need to start the game in fullscreen mode.

Additionally, you can add a custom resolutions by modifying the `ResX` and `ResY` values in the ini file.  See here for more details: #1050

**Comment by TommvinHuwaltzky** [comment]
It was not a knock on you guy's work, obviously. The mere fact of you integrating a res-scale is fucking awesome!

Just saying that, if you have an Ngreedia-card, DLDSR is objectively better quality. That's obviously not your fault, it is just by virtue of how it works by utilizing AI.

And as I said before, if one wants to play borderless, just set the desktop-res to the higher DLDSR-one, and the game will start with it.

**Comment by Polymega** [comment]
@Nessu4K I'll close this ticket out. If you have any other questions, feel free to ask. If you run into issues with AA, feel free to re-open the ticket. Thanks

**Comment by Nessu4K** [comment]
@Polymega Sure thing!
