### ISSUE TITLE
Controller not detected 

### ISSUE THREAD

**Issue by Darko-69** [elishacloud/Silent-Hill-2-Enhancements#1057]
I just launched the game some time ago and the inputs of my controller dont seem to register, although the inputs of my keyboard and mouse do register perfectly. My controller is connected to my pc by usb and it doesn't seem to work. I use a PS5 controller.

**Comment by Polymega** [comment]
Hello,

Please refer to these troubleshooting steps: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#my-controller-is-not-being-detected-by-the-game

**Comment by Polymega** [comment]
Closing ticket. If you're still experience issues, please re-open the ticket.
