### ISSUE TITLE
SH1, SH3, SH4 Easter Eggs?

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#1059]
I’ve given the game six long playthroughs analyzing every camera angle I’m aware of and played BfaW twice doing the same. I then broke down and tried the level viewer to no avail.

To my knowledge the rules are:
- Not literal eggs
- Can be found through normal gameplay
- Are not “big ticket” items
- Cannot be acquired or interacted with
- Are found in the game environment

My questions are:
- Are these items that were previously inventory items? Or can they be environmental objects? (For example: a toy car that looks like Harry’s car.)
- Do they depend on triggering flags (like New Game+ or difficulty levels) or specific game states (like when the Woodside apartment 1F is empty during the first RPT appearance; day or night version of the town)?
- Can they appear in scenes only seen in cutscenes such as the ending scene with Mary? (Even if ‘no’ would it be possible? I don’t need a straight answer!)
- Can they be behind new level data similar to RE4 HD’s new bonus room?

I don’t need you to confirm or deny anything you don’t want to, but I’m pulling my hair out doing this hunt! lol
Part of me suspects they didn’t get published in the final update, but I believe!

I guess I just need absolute confirmation that, yes, they’re in the game and I just need to look harder.

If you don’t want to answer any of these questions to keep the hunt going, may I request at least an emoji response just to know that I’m not getting anymore hints? Haha.

Regardless, thanks for giving me and my Twitch community new goals for this nearly 25 year old game!

**Comment by Polymega** [comment]
Hi,

They're in the game. They won't be obvious to find because, well, that wouldn't be much of a challenge then. 😛  They're items that can be obtained from their respective games hidden in SH2's environments. They can be found by playing normally, but you need to look carefully as they won't be placed anywhere incredibly obvious.

Thanks

**Comment by GlitchyReal** [comment]
Okay, thanks! Man, this'll help me keep the hunt going, just knowing it exists for sure. Thanks for the reply!
