### ISSUE TITLE
Fix for the disappearing hanging meat and water?

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#106]
@Bigmanjapan @AeroWidescreen 

I may have stumbled upon an address fix to keep the hanging meat always loaded in during the cutscene:

`Dynamic object draw distance 00803888 (float)`

This address seems to be the "threshold" for how far out the game hides dynamic objects based on the distance from the camera. By default it's set to `1`. When I change it to `0.1` it makes James disappear if he goes a little too far away from the camera. 

During the Eddie meat cutscene I change this number constantly to better illustrate. I set it to `7` to keep all the meat shown during the cutscene. 

I'm sure this number could be lowered while still keeping all meat loaded in; it just needs to be playtested more. But I didn't want to dive too deep into this until more competent modders verify the address I'm using won't have any catastrophic consequences from using/adjusting it: 

https://youtu.be/LlLglPmjvO0

@Bigmanjapan it also fixes the chainsaw log from disappearing too early. Just an added benefit to fixing the hanging meat? 

https://youtu.be/KpQjr5e0RlM

**Comment by Polymega** [comment]
Okay, I did a playtest. It seems to be fine overall besides it having a negative effect on water layers (it makes them too bright and/or "solid" when the flashlight touches the water). So changing this on a per-room basis is the way to go.

One opcode accesses this address, and nothing writes to the address. Being an amateur, I'm not sure if it'd negatively affect anything because of the opcode? 

@elishacloud, assuming this address is fine to use, the following could be done: 

This could be added to `IncreaseDrawDistance`, since it's semi-related to that fix, or be made into a new fix: 

- On `Room ID 01FB7DAC (4 bytes) - 00000003 (forest with chainsaw logs)`  set `00803888 (float)` to `44` (one write, no constant iteration)
- On `Room ID 01FB7DAC (4 bytes) - 00000090 (Eddie boss meat cold room)`  set `00803888 (float)` to `2` (one write, no constant iteration)
- **ELSE** set `00803888 (float)` back to `1` (default value)

This fixes the issue of [the hanging meat disappearing during certain camera cuts](https://www.youtube.com/watch?v=XY5kRFLcYO8) and [the chainsaw wood logs from disappearing at certain angles when using a widescreen resolution](https://youtu.be/KpQjr5e0RlM).

**Comment by Polymega** [comment]
I hoping I'm getting somewhere with Cheat Engine. I may have found another fix for a "chunk" of water that disappears based on James' distance to it in the hallway leading up to Maria's prison cell room. This issue affects at least the PS2 version of the game as well.

I filtered to find the address that's causing the problem (it changes each playthrough), found what instructions access it, filtered what instruction is causing it, showed it in the disassembler, and found the permanent address that affects this: 

https://youtu.be/Sv97UXEwpZo

`Increase water render distance 004D1BBD (byte)` - set to `52` (default is `51`)

The process of what I did is surely old trick to you gents, but I wanted to explain my process out loud in case I could've went about that another way.

The address seems to be set once on game launch and stays at that value. I did a playtest of the whole game with that value set to `52` and nothing crashed, and nothing seemed unusual. But we could play things safe and only change it to `52` while in that particular room and set it back to `51` elsewhere? 

I'd love to hear thoughts from you guys as I'm very new and unsure about myself with all of this.

If this checks out, it could be added to the fixes above?

**Comment by Polymega** [comment]
Thanks for helping my greenhorn self, Aero_. From what I've gathered, that particular labyrinth hallway water (seen in that YouTube video) is the only area in the whole game with the issue of a chunk of water loading in "too short" for it to be seen when playing normally.

**Comment by AeroWidescreen** [comment]
No problem. So far it looks like this is true:

> It's also possible that the functions are for the same thing (water chunks) but for different parts of the game, similar to the water effects.

So what I would do is redirect the call to our own subroutine with the `xor eax,eax` instruction replaced with `mov eax,00000001`. This will write a value of 1 to the dynamic address that causes the water chunk issue when its value is at 0. 

No Room ID check should be necessary since this should only affect that one hallway in the Labyrinth. I confirmed this by going to different sections of the game where water was present and checking if the function was active at all.

[Cheat Table](https://mega.nz/#!oeQEGCIT!mjqx0zGGTPsabgA6-E6Mz8R32Zd7gmbAxqUObvoZZW4)

```
004E6C4D call 00000000
00000000 mov ecx,[esp+08]
00000001 test ecx,ecx
00000002 jna 00000008
00000003 push edi
00000004 mov edi,[esp+08]
00000005 mov eax,0000001
00000006 repe stosd
00000007 pop edi
00000008 ret
```

Good job discovering this, by the way. 👍

**Comment by Polymega** [comment]
Well done! Worked like a charm. 

> So what I would do is redirect the call to our own subroutine with the xor eax,eax instruction replaced with mov eax,00000001

By the way, you'd be a proud that I attempted a fix similar to this first through Cheat Engine and it worked 50%. It fixed the water loading in from one direction, but not the other by changing: 

`mov [edx+esi*4],00000000` to `mov [edx+esi*4],00000001` 
**(Worth clarifying: My change here is wrong, fyi, do not use.)**

But only be 50% proud as it was complete guess-work without knowing what the hell I was doing. :)

**Comment by Polymega** [comment]
If you'd want to keep the good times rolling: If you Quick Save in the hotel stairs that are on fire and Quick Load back into this area the fire/smoke doesn't render: 

![sh2pc 2019-04-10 17-13-49](https://user-images.githubusercontent.com/27395260/55914042-21c04380-5bb4-11e9-80a6-dc5f57c8cdb3.png)

I believe these addresses (one, some, or all of them?) are what affects this effect: 

`sh2pc.exe+5635E8 (009635E8)`
`sh2pc.exe+5635EC (009635EC)`
`sh2pc.exe+6C70C8 (00AC70C8)`
`sh2pc.exe+6C72DC (00AC72DC)`

Although I'm not entirely sure as the values don't change upon invoking the bug.

**Comment by AeroWidescreen** [comment]
It might be because you're not suppose to return to that room. The problem occurs with normal saves as well. I think the best solution is to disable save option, like when you're in a boss fight.

**Comment by Polymega** [comment]
> the best solution is to disable save option, like when you're in a boss fight.

Excellent idea. Because if we can figure out how to do that, we can also disable saving in the RPT closet apartment room, as if you quick save/load within the closet it blacks out the camera.

And possibly in the mannequin flashlight apartment room to avoid the mannequin from spinning erradicately from a quick load. Although it may be better to not do that for this room as it could tip off a player that something bad is about to happen. 

In any case, figuring out how to do that would universally fix problems elsewhere.

The feature of being able to save/load almost anywhere is one of the best things about SH2 PC. But it's something Team Silent never planned on having so a lot of bugs come as a result from it.

Something to worry about in more detail later on.

**Comment by Polymega** [comment]
Aero_, something else, if you don't mind. I forgot Bigmanjapan and I discussed this during your break: 

https://www.youtube.com/watch?v=LeHhhIoKzrU

Bigmanjapan found the address which makes the fog instantly disappear depending on James' orientation at this spot (right upon exiting the apartments). 

`01F7A6A8 byte`

The value should be 8 but turns to 0 at this point. The function seems to be the culprit?: 

![image](https://user-images.githubusercontent.com/27395260/55976440-348d5380-5c5a-11e9-8c2a-8fd7944f55d0.png)

Is it safe to NOP it? Or is it used elsewhere? Can it be set to write a value of 8 here instead of 0?

**Comment by Polymega** [comment]
Aero_, something else, if you don't mind. I forgot Bigmanjapan and I discussed this during your break: 

https://www.youtube.com/watch?v=LeHhhIoKzrU

Bigmanjapan found the address which makes the fog instantly disappear depending on James' orientation around this area (right upon exiting the apartments). 

`01F7A6A8 byte`

The value should be 8 but turns to 0 at this point. This function seems to be the culprit?: 

![image](https://user-images.githubusercontent.com/27395260/55976440-348d5380-5c5a-11e9-8c2a-8fd7944f55d0.png)

~~Is it safe to NOP it? Or is it used elsewhere?~~ 
Scratch the NOP statement, I'm reading back on Bigmanjapan's notes and found the following: 

> Maybe Aero can trace the function that sets the value to 0 and make it assign a value of 8 instead. Simply disabling the function won't do because it assigns other values (different from 8) later on. 

Can it be set to write a value of 8 here instead of 0?

**Comment by AeroWidescreen** [comment]
Well, I have no clue what that value actually does, so I need you and @Bigmanjapan to confirm that this works properly. I couldn't find the exact source of the value, but I was able to determine which function was responsible and nop a conditional jump that was causing the value to be set to 0 in that location.

[Cheat Table](https://mega.nz/#!8exRHCSI!xs0zZKuy7IxD1o23IIpU-J3WERuVcE3algG2rz6q5Tw)

**Comment by Polymega** [comment]
Thanks Aero_. The script has a negative effect on the first (small) Eddie boss room, changing its byte from `C1` to `01`, and the Dog Ending room, changing its byte from `C1` to `40`, which changes how the fog behaves/renders for the worse (notable worse for the Eddie room).

These are just the areas that I happened to notice. There may be other areas that are affected like this, but maybe not. What's your opinion on this? Is it worth fixing the fog in that one area but risking overlooking and making it worse elsewhere?

**Comment by AeroWidescreen** [comment]
> These are just the areas that I happened to notice. There may be other areas that are affected like this, but maybe not. What's your opinion on this? Is it worth fixing the fog in that one area but risking overlooking and making it worse elsewhere?

Honestly, I don't think it's worth the trouble. It's an incredibly small part of the game that's probably ignored most of the time because it's a dead end. The people that do go there will spend 5 seconds picking up the first aid kit before they start running in the other direction. 

If the problem didn't also exist in the PS2 version then I would be more inclined to fix it.

**Comment by Polymega** [comment]
> If the problem didn't also exist in the PS2 version then I would be more inclined to fix it. **Edit:** Or does it not?

This issue affects all versions, so it would've been something fixed exclusive to our project. 

However, I agree with you. At least with this current fix method, it's best to not fight this and risk messing up the fog elsewhere. The fog, in a bigger-picture sense, is just too important to risk hurting elsewhere. 

I think the other two fix solutions above, while not planned for this release, will make nice, added-bonus fixes for the release, and we'll stop adding any more fixes for this release so we can push it out. (Although I'm definitely an advocate for figuring out how to disable saving in certain rooms to squash other save/load related bugs in the future.) 

Once these fixes and the rumble fix get implemented, and we hear back from FrozenFish24 about any additional .map edits, we'll be ready to prep for release. 

---------------------

@elishacloud 
Let me know if you'd like me to give you name/description suggestions if the following below get made into their own fixes:

---------------------

[This fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/106#issuecomment-481053430) could either be added to `CatacombsMeatRoomFix`, since it was primarily made to fix the hanging meat in these rooms, or be made into a new fix. 

The issue was, when using a widescreen resolution, the hanging meat would sporadically appear/disappear during the cutscene beyond the original 4:3 region. 

**If implemented into `CatacombsMeatRoomFix`, you'd want this fix to work regardless if the adjusted .map files are detected or not for the original fix.**

---------------------

[This fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/106#issuecomment-481774396) could either be added to `IncreaseDrawDistance`, since it's related to that, or made into a new fix. 

The issue was, a certain water-filled hallway didn't load the next chunk of water geometry until you got very close to it, so it's was very noticeable when the geometry popped in-and-out.

**Comment by elishacloud** [comment]
I put both of these fixes under the `IncreaseDrawDistance` setting, since they both seemed to effect the draw distance.  I can change it if that is an issue.  Here is a test module for these fixes:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3075738/d3d8.zip)

_Note: this only works on v1.0._

**Comment by Polymega** [comment]
> I put both of these fixes under the IncreaseDrawDistance setting

Perfect! Okay, [the first fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/106#issuecomment-481053430) works great (that fixes the hanging meat). 

However, [the second fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/106#issuecomment-481774396), which uses Aero_'s nop code, crashes the game as soon as you load into the area where the fix should take affect.

**Comment by AeroWidescreen** [comment]
@elishacloud 
> However, the second fix, which uses Aero_'s nop code, crashes the game as soon as you load into the area where the fix should take affect.

You need to use a call instead of a jmp.

**Comment by elishacloud** [comment]
This update should work on all versions and should work with the second fix also.  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3075862/d3d8.zip)

**Comment by Polymega** [comment]
All worked great for all versions!

**Comment by elishacloud** [comment]
Fixed in check-in [5039b06](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/5039b0671c5d4b867b0163363269764e9bb550f7).

**Comment by Polymega** [comment]
Well done team!

**Comment by Polymega** [comment]
Hi Elisha,

Whenever you have a spare moment, could you please add Room `0xD4` [to this line](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/DrawDistance.cpp#L196)?

Thank you

**Comment by elishacloud** [comment]
Done.  This will be in the next update.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4929805/d3d8.zip)

**Comment by elishacloud** [comment]
Added in:  25705f7f22bc73b54af511ea5afe3b3b05656f3a

**Comment by Polymega** [comment]
Thanks, Elisha!
