### ISSUE TITLE
[Request] Improve graveyard floor grass/flowers textures / Forest area incorrect bush texture placement

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1060]
As you can appreciate in the screenshot, the textures for the grass and flowers in the graveyard didn't age well for new resolutions and rendering scale. As many other elements got new textures to improve the experience, I think this area got overlooked but it would really help to get new textures for it.

![20240916052109_1](https://github.com/user-attachments/assets/40f74e30-f42a-453a-9392-da0e8dfeec43)

Incorrect bush placement in the forest area that looks floating:

![20240916051250_1](https://github.com/user-attachments/assets/c7dbd51a-a3a5-49a6-8f72-4d0def6b9b4b)

Again, Thanks so much for the incredible work on this game

**Comment by Atrus99** [comment]
I could see them maybe adjusting the bush placement but asking them to create a whole new grass texture doesn't seem like something they would do for this project.

**Comment by Polymega** [comment]
Hi there,

We've officially wrapped up work on the project so unfortunately we won't be performing any additional adjustments for the game. 

Thanks
