### ISSUE TITLE
white shadow when entering apartment building

### ISSUE THREAD

**Issue by goliat11** [elishacloud/Silent-Hill-2-Enhancements#1061]
https://github.com/user-attachments/assets/ccbbeb8f-e0b7-4775-8321-b2602316a11b

when entering the building the white shadow was there, it doesn't go away. 
reloading my save didn't fix it, it just loaded a different white shadow of James (the camera angle of him when loading into the game or entering the building)
Is this a bug or is there a graphics setting i must change to fix the issue?

**Comment by Polymega** [comment]
This is a result of using forced anti-aliasing through your GPU's control panel. There are two options for this:

1. (Recommended) Disable forced AA through your GPU's control panel and instead utilize our built-in render scaling mode. You can find this under Options > Advanced Options > Render Resolution. This will give you the best AA possible.
2. Open `SH2EEconfig.exe` and enabled Advanced > Fix GPU anti-aliasing.

**Comment by Polymega** [comment]
Closing ticket. The recommendation posted should fix it. If not, let us know.
