### ISSUE TITLE
Black screen + Not responding on startup

### ISSUE THREAD

**Issue by mysteGH** [elishacloud/Silent-Hill-2-Enhancements#1069]
As post says, i launch the game and instantly get a black screen and eventually not responding, game downloaded from myabandonware full rip, d3d8 log attached for insight :D (CONTEXT: i had to install msvcr70, msvcp70 and blinkw32 DLLs after install due to error codes, for some reason .net framework didn't install with them for me)

[d3d8.log](https://github.com/user-attachments/files/17199479/d3d8.log)

Image also below:
![result](https://github.com/user-attachments/assets/ed83a68a-458b-49ec-b08f-65f6a4da5cf4)

pc spec: 
7800x3d
4080 super
32x6000mhz ddr5

installation is on an ssd

**Comment by Polymega** [comment]
Hello, 

You do not have the base, vanilla game installed. Our project requires you to install the base game first in order for our project ot work. I recommend starting over while first ensuring you have downloaded and installed vanilla SH2 PC. You want the PC version of the game; not the PS2 version.
