### ISSUE TITLE
Trojan alert

### ISSUE THREAD

**Issue by Gr33nEyes** [elishacloud/Silent-Hill-2-Enhancements#1070]
Dr. Web CureIt found this in setup exe 
![image](https://github.com/user-attachments/assets/a15528a5-f1fe-4b19-ba08-e5cf65a51739)

**Comment by Polymega** [comment]
It's a false positive. The installer's code is open source. You can review the code for yourself: https://github.com/nipkownix/SH2EE-web-installer

**Comment by Gr33nEyes** [comment]
Microsoft Defender - OK, Kaspersky - OK
