### ISSUE TITLE
Aliasing on text elements - Scaling issue

### ISSUE THREAD

**Issue by Doze-D** [elishacloud/Silent-Hill-2-Enhancements#1072]
Fired up the game after installing the last SH2EE version, and I immediately noticed that the scaling of some elements are little off, text looks littlebit coarse and the two left arrows in this picture have little step to them, indicating that the scaling is not working as it should. 
SMAA didn't seem to work either on my end, and when using some other AA options from Nvidia Profile Inspector, the image turns little blurry.

![kuva](https://github.com/user-attachments/assets/acea0348-bd40-4b8f-a4f5-10659c04ba1e)

Win10 x64
Ryzen 7 3700X
RTX 2080 Ti
QHD monitor at 125% DPI scale

**Comment by AeroWidescreen** [comment]
This looks completely normal. The font is not vector, so what you're seeing is visible aliasing and soft edges from the texture being upscaled to fit your screen. Perhaps @Polymega is willing to export them at a higher resolution, but nothing else can be done about it. 

The arrows and lines are drawn in real-time via vertices that have no aliasing applied to them. So they look extremely sharp but jagged as a result. You could try changing the render resolution to 2x. This will clean up the aliasing at the cost of softer edges in the UI.

**Comment by Doze-D** [comment]
Allright, that resolution scale did the trick, thanks. 

Wanna post this too btw, just noticed that Maria's shoes have red texture at the bottom, I suppose it shouldn't be like that?

![kuva](https://github.com/user-attachments/assets/b626e1f3-183e-4fe4-8381-d06c3555ea3a)

**Comment by AeroWidescreen** [comment]
That's normal too. It's like that on the original PS2 release.
https://youtu.be/ZqL530nVzi8?si=QyLyhN0Ay2GXabyK&t=247
