### ISSUE TITLE
How to access minimap?

### ISSUE THREAD

**Issue by PhoenixCyanFire** [elishacloud/Silent-Hill-2-Enhancements#1074]
I was told the minimap secret was still in this Enhanced edition, yet I cannot find a way to activate it. the PS2 way to activate it doesnt work, I was told I had to edit a file or change a setting or something. Cant figure out how

**Comment by Polymega** [comment]
The minimap does not exist in the PC version. The code/functions for it were removed by the PC developers when they ported it over.
