### ISSUE TITLE
Downloadable full offline installer? (suggestion)

### ISSUE THREAD

**Issue by ImpalerF5** [elishacloud/Silent-Hill-2-Enhancements#1075]
Hello, amazing work on the restoration of this timeless classic. Thank you for that.

I thought since the game enhancement is now finalized, perhaps you can also offer a offline installer too?

Thanks :)

**Comment by Polymega** [comment]
Our installer offers an offline installation option. When you first run the installer, a few steps in, it'll ask if you want to make a backup of the files for offline installation use in the future.

![image](https://github.com/user-attachments/assets/647eb8e8-3b93-41e5-88b4-b410cce1d6cb)
