### ISSUE TITLE
3 second delay for almost all menus and all loading screens when in exclusive fullscreen mode.

### ISSUE THREAD

**Issue by asterisk17** [elishacloud/Silent-Hill-2-Enhancements#1077]
Title should be self-explanatory of the issue, and since this bug **only** occurs on exclusive fullscreen, it's quite difficult for me to gather actual footage of it but I could edit something up in Premiere to showcase what it looks like if required. I will try to be as in-depth as I can with my description for now. 

Note that this issue also consistently occurs every time with the new update.

This isn't (or at least doesn't seem to be) hardware/driver related, as this issue did not occur on an older version I tested. However, I will mention that I play this on a hard drive and not an SSD, which shouldn't matter as load times were still instant on the older versions even with the hard drive.

This issue affects entering and exiting of all the following menus:
1. Options (only **not** present when **entering** through the start menu, exiting it still occurs)
2. Movies (only **not** present when **entering** through the start menu, exiting it still occurs)
3. Save/load (only **not** present when **entering** through the start menu, exiting it still occurs)
4. Pause menu (game-world still pauses instantly, but the actual menu is delayed by 3 seconds like the rest).

This also affects **every single loading/transitionary screen in the game**, making load times no longer instant like they were in previous versions, which you could imagine is quite frustrating.

Luckily this doesn't affect any actions in the game as far as I can tell. All combat and movement is unaffected. And like I previously said, this bug doesn't occur on windowed, or fullscreen-windowed mode. Only exclusive fullscreen.

Since I have older versions of all packages for the Enhanced Edition, I was able to narrow down that it's the base "SH2 Enhancements Module" itself that causes the issue. The version I tested that does have the issue is the most recent one, that being version 3.0.2210.0.

The older version I have access to which _doesn't_ have this issue is version 2.1.2050.0.

Since I don't have access to any in-between versions, I have no idea when this bug first appeared. If I were to speculate (with lack of knowledge, mind), it might be due to the newer version(s?) adding the fullscreen/window toggle settings into the game itself rather than in the config, as that's the only difference regarding those modes I can find other than the obvious delay bug.

I really hope this can be fixed soon so I can finally experience the culmination of all the hard word put into this project (as windowed is immersion breaking and fullscreen-windowed causes flickering due to an unavoidable driver bug. To provide some context, my graphics card is a Radeon RX580). 

If you need to know anything else or have anything extra provided, please ask.

**Comment by Polymega** [comment]
If you disable the option below, does it still happen?

![image](https://github.com/user-attachments/assets/cc4af808-6b97-4267-8954-3deee39bebb5)

**Comment by asterisk17** [comment]
Yeah, that fixed the issue completely on my end!

Only issue is I can't use built in or forced anti-aliasing due to both relying on DX9, but at least the game works fully now. I won't close this yet in case there is a workaround I don't know about, though (if not, at least I have the old version to enable it for, haha).

Thanks for the help and the incredible work on this project!

**Comment by arrese64** [comment]
Hey I had the same issue as OP but now that I disabled this feature I have a considerably lower framerate. Is that expected?

**Comment by Polymega** [comment]
Try running the game in Windowed or Fullscreen Windowed mode to see if that alleviates the issue.
