### ISSUE TITLE
persisten webcsv.url note

### ISSUE THREAD

**Issue by GrEgStAr3000** [elishacloud/Silent-Hill-2-Enhancements#1079]
I still can´t get pass the installer after choosing the language. My Anti Virus Programms are all turned of and it´s STILL showing me this error:

Error: Download Failed
Couldn´t donwload webcsv.url.
The installation cannot continue.

Why, WHY can´t you just provide me/us with a portable folder including all needed files. I can´t even choose the offline-installer because I can´t get pass this prompt. People, like for real! I need help with this one. Re-Provide at last a genuine offline Installer without the ne of internet connectivity like it was done in the past. Like PLEASE! ´- ___ -` I feel like I´m totally beeing ignored by you guys. I just downloaded the installer again since there has been released a hotfix or something and still nothing.
![Unbenannt](https://github.com/user-attachments/assets/14517e08-bc70-49a8-8817-bcde66db728f)

**Comment by Polymega** [comment]
Grab them from here: https://files.townofsilenthill.com/SH2EE/_sh2ee.csv

**Comment by GrEgStAr3000** [comment]
While it helped and seem to work, a standalone package still would be a usefull. deciphering all the .csv stuff was a nightmare for me. Requesting for the next hotix just that: A seperate package folder with all the files bundled together. Case now can be closed.
