### ISSUE TITLE
Any idea why mods for Maria have stopped working after updates?

### ISSUE THREAD

**Issue by Nessu4K** [elishacloud/Silent-Hill-2-Enhancements#1083]
All the Maria costume mods that I was able to use before just stopped working altogether.

**Comment by Polymega** [comment]
Not sure.

**Comment by Nessu4K** [comment]
Yea, the costume mods I have for the other characters work, just not Maria unfortunately.

**Comment by Polymega** [comment]
Try re-downloading re-placing the modded outfit.

**Comment by Nessu4K** [comment]
I downloaded one today as well, a newer one, and it didn't work.
Followed what it said in the posts too
https://www.nexusmods.com/silenthill2directorscut/mods/29

**Comment by Nessu4K** [comment]
Tried this one too I had before, I keep the extracted folder too
https://www.nexusmods.com/silenthill2directorscut/mods/21

**Comment by Polymega** [comment]
I apologize, but we cannot guarantee outside mod support with our project. I'd recommend redownloading then re-extracting those mode files to see if it restores them, or reach out to the mod creators to update their mods to be compatible with our project files.

**Comment by Nessu4K** [comment]
It seems like those files were overriding any mods for her.
