### ISSUE TITLE
Doghouse not appearing

### ISSUE THREAD

**Issue by Nessu4K** [elishacloud/Silent-Hill-2-Enhancements#1084]
I have both cleared the game on Main and Sub scenario's and have saves, start new game with green tint behind it and no doghouse so I can get the Dog Ending.

**Comment by Polymega** [comment]
You need to unlock either all three main endings, or the rebirth ending: https://www.silenthillmemories.net/sh2/endings_en.htm#Dog

**Comment by Nessu4K** [comment]
I made a mistake, you're right. So used to having all of it unlocked on my PS2, I forgot the nuance XD
