### ISSUE TITLE
Feature Request: On save screen, display 'free space' in GB instead of KB

### ISSUE THREAD

**Issue by seagull** [elishacloud/Silent-Hill-2-Enhancements#109]
Noticed this after looking at the 2TB fix (nice work with that). [Here's the image enclosed.](https://user-images.githubusercontent.com/27395260/49704674-d9951280-fc0d-11e8-9c02-2cb2e31acb21.png)
It always looked funny to me how the game says "Free space: 9999999+ KB" when attempting to save. Is it possible to format the size in GB instead?
It's not like it's a particularly useful metric in this day and age but it looks a lot more presentable.

**Comment by Polymega** [comment]
There's been some discussion on this before found here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/70#issuecomment-467902078

Elisha isn't necessarily interested in bothering with this and, my $0.02 which doesn't mean much on the matter, I think while 9999999+KB looks a little silly it's nice to keep the units the same (KB to KB) so a user doesn't have to do any conversions in their head, on the crazy off-chance they're almost at capacity with their disk space.

**Comment by AeroWidescreen** [comment]
I think the ideal solution would be to have it change dynamically based on how much space is reported. For example:

Free space: 482 KB (if less than 1 MB)
Free space: 564 MB (if less than 1 GB)
Free space: 635 GB (if less than 1 TB)
Free Space: 3.2 TB (if less than 1 PB)

The save requirement would always display in KB. It should be possible assuming Elisha has a way to check for the amount of free space available.

**Comment by elishacloud** [comment]
Yes, I am able to get the disk space. In fact, for this fix I already created the ability to get disk space dynamically, see [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/011282d6e1d82d162cba0d6a35e9eff33d8833e3/Patches/2TBHardDriveFix.cpp#L90).  This gets the amount of free disk space left in the Silent Hill 2 folder.  Keep in mind that the disk space is reported back as a `ULARGE_INTEGER`, which is basically two DWORDs put together, or a 64bit DWORD.

**Comment by Polymega** [comment]
If you'd be interested in trying something like this in the future Elisha, I'm sure Belek666 could find a way to overwrite the preset "KB" text for the available space to other formats (MB, GB, TB, etc) in the future. It would mirror similar work he's done in the past with modifying text in the game.

**Comment by seagull** [comment]
I like the sound of that solution, @AeroWidescreen.
@elishacloud, glad to hear it. Thanks for all the work you've put into this!
Cheers guys

**Comment by Polymega** [comment]
Better late than never! Steam006 has made such a feature for his own module and has given us the okay to use and modify it to fit into our project. Here is his code:

```c++
msvcr70.dll - sprintf:

int SilentHill2_sprintf(char* Buffer, const char* a1, ...)
{
	if (Buffer != nullptr && a1 != nullptr)
	{
		char FullMessageBufferReturn[MAX_PATH] = { 0 };

		va_list vaReturn;
		va_start(vaReturn, a1);

		_vsnprintf_s(FullMessageBufferReturn, MAX_PATH, _TRUNCATE, a1, vaReturn);
		va_end(vaReturn);

		if (DisplayCorrectDiskSize == 1)
		{
			if (stristr(FullMessageBufferReturn, szFreeSpaceString) != nullptr)
				return osprintf(Buffer, szNewFreeSpaceString);
			else if (stristr(FullMessageBufferReturn, "2097151") != nullptr)
				return osprintf(Buffer, szNewFreeSpaceString);
			else if (stristr(FullMessageBufferReturn, "99999999+") != nullptr)
				return osprintf(Buffer, szNewFreeSpaceString);
		}

		return osprintf(Buffer, FullMessageBufferReturn);
	}
	return osprintf(Buffer, a1);
}

GetDiskFreeSpaceExA:
BOOL WINAPI SilentHill2_GetDiskFreeSpaceExA(LPCSTR lpDirectoryName, PULARGE_INTEGER lpFreeBytesAvailableToCaller, PULARGE_INTEGER lpTotalNumberOfBytes, PULARGE_INTEGER lpTotalNumberOfFreeBytes)
{
	BOOL FreeSpaceEx = oGetDiskFreeSpaceExA(lpDirectoryName, lpFreeBytesAvailableToCaller, lpTotalNumberOfBytes, lpTotalNumberOfFreeBytes);

	if (FreeSpaceEx == TRUE)
	{
		if (lpFreeBytesAvailableToCaller != nullptr)
		{
			if (DisplayCorrectDiskSize == 1)
			{
				SecureZeroMemory(szFreeSpaceString, MAX_PATH);
				SecureZeroMemory(szNewFreeSpaceString, MAX_PATH);

				_snprintf_s(szFreeSpaceString, MAX_PATH, _TRUNCATE, "\\h%lld", lpFreeBytesAvailableToCaller->QuadPart / 1024);
			}

			if (lpFreeBytesAvailableToCaller->QuadPart / 1024 < 0xF4240)
			{
				if (DisplayCorrectDiskSize == 1)
					_snprintf_s(szNewFreeSpaceString, MAX_PATH, _TRUNCATE, "\\h%lld MB", lpFreeBytesAvailableToCaller->QuadPart / 1024 / 1024);
			}
			else if (lpFreeBytesAvailableToCaller->QuadPart / 1024 < 0x3B9ACA00)
			{
				if (DisplayCorrectDiskSize == 1)
					_snprintf_s(szNewFreeSpaceString, MAX_PATH, _TRUNCATE, "\\h%lld GB", lpFreeBytesAvailableToCaller->QuadPart / 1024 / 1024 / 1024);
			}
			else if (lpFreeBytesAvailableToCaller->QuadPart / 1024 > 0x3B9ACA00)
			{
				if (DisplayCorrectDiskSize == 1)
					_snprintf_s(szNewFreeSpaceString, MAX_PATH, _TRUNCATE, "\\h%lld TB", lpFreeBytesAvailableToCaller->QuadPart / 1024 / 1024 / 1024 / 1024);

				if (lpFreeBytesAvailableToCaller->QuadPart / 1024 > 0x7FFFFFFF)
				{
					lpFreeBytesAvailableToCaller->QuadPart = 0x7FFFFFFF;
				}
			}
		}

		if (lpTotalNumberOfBytes != nullptr)
		{
			if (lpTotalNumberOfBytes->QuadPart / 1024 > 0x7FFFFFFF)
			{
				lpTotalNumberOfBytes->QuadPart = 0x7FFFFFFF;
			}
		}
	}

	return FreeSpaceEx;
}
```

**Comment by elishacloud** [comment]
I was able to repurpose this code and use it in our project.  However, this code just adds the "MB", "GB" or "TB" unit but it does not remove the "KB" unit.  So now it says both.  If someone can help me figure out what part of the code is adding the "KB" unit in that would be great!

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8384884/d3d8.zip)

**Comment by Polymega** [comment]
Thanks, Elisha! 

Steam006 contacted me to say notes for the "KB" part were in another .txt file.

### TextToGame.txt
```c++
8B 44 24 04 85 C0 74 16 66 8B 4C 24 08

int __cdecl SilentHill2_TextToGame(unsigned __int16* a1, unsigned __int16 a2);

Remove "KB" text:
int __cdecl SilentHill2_TextToGame(unsigned __int16* a1, unsigned __int16 a2)
{
	int TTG = oTextToGame(a1, a2);

	if (a2 == 147)
	{
		BYTE RemoveKBPatch[2] = { 0x00, 0x00 };
		WriteToMemory(TTG + 0x10, RemoveKBPatch, 2);
	}

	return TTG;
}
```

Note: This function returns a pointer and not an int.

**Comment by elishacloud** [comment]
Thanks!  It should be fixed now.

Testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8393795/d3d8.zip)

**Comment by Polymega** [comment]
Yep! All looked good in all binaries for this. Thank you again.

**Comment by Polymega** [comment]
Re-opening this to remind us to also implement this fix for the Japanese language. We're in the process of restoring this language selection and, currently, this feature does not work with that language.

**Comment by elishacloud** [comment]
Ok, I have a fix ready for this.  I removed the "KB" and also converted the text to use the larger Japanese font rather than the smaller English font text it was using.

Here is the update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9579626/d3d8.zip)

However, the Japanese text does cause extra space between the decimal and the fractional numbers.  Let me know if this is ok.  See pictures below:

![image](https://user-images.githubusercontent.com/25625456/190528745-85d1be09-3bce-457a-9a45-ca277e58dd85.png)

![image](https://user-images.githubusercontent.com/25625456/190529371-a03173e2-ab71-464a-9fa8-9ac697aefba4.png)

**Comment by Polymega** [comment]
This is great. Thank you very much! As for the odd space in the full width ".", this is due to it not being aligned in the center of its cell:

![image](https://user-images.githubusercontent.com/27395260/190533988-88e1c00f-1345-4107-ade8-1a599e455810.png)

I can certainly center it in the font sheet, but I'm not sure if that would make its alignment elsewhere in the game look odd. 

@toraMeeKay: Please see Elisha's post directly above this one. Is it preferred to keep the period (".") where it's at or should we center it within the font sheet? If we center it, will this make the "." look awkward elsewhere in the game? Thanks!

**Comment by elishacloud** [comment]
Ok, I will check-in the code since I am pretty sure the code is ok.  If the font needs updated, that is outside the scope of the code change.

**Comment by toraMeeKay** [comment]
> Is it preferred to keep the period (".") where it's at or should we center it within the font sheet? If we center it, will this make the "." look awkward elsewhere in the game?

In the case of fullwidth periods, Japanese people are accustomed to this notation, so I don't think there is a need to change it.
However, I am very sorry to have you do a difficult work, but I think that the notation of the data size is the same as before, and there is no problem with English fonts (half-width).

I'm afraid to keep asking you to do this, but I will leave the final decision to you, @Polymega 🥺

**Comment by Polymega** [comment]
Awesome! Since Japanese people are accustomed to how this would look, we are totally fine to keep it the way it is then with these full width characters. 👍 

We are working with belek666 to finalize how the HD font sheets will be handled in the project moving forward. After that, I believe we will have everything locked in place with how we'll handle language packs moving forward. 😁 

Thank you very much again for sticking with us, toraMeeKay! You've been a big help!

**Comment by Polymega** [comment]
Closing ticket. Available space for Japanese fixed in commit https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/2d3e0a75f6c49ea3e8b7e302b5902b33a757c3dd
