### ISSUE TITLE
Extremely choppy FMV audio

### ISSUE THREAD

**Issue by RileyAllenBurch** [elishacloud/Silent-Hill-2-Enhancements#1091]
Not sure if this has been answered anywhere here, but all of my FMV audio (Music excluded, strangely enough) is extremely choppy. Like less than a whole syllable, a second of silence, repeat until end of speaking segment. 
[d3d8.log](https://github.com/user-attachments/files/17387731/d3d8.log)

**Comment by RileyAllenBurch** [comment]
Well never mind, I went to record it with OBS but it seems to have fixed itself.

**Comment by Polymega** [comment]
Glad it resolved itself. If, in the future, you run into something similar, try out some of these recommendations: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm

**Comment by RileyAllenBurch** [comment]
The issue seems to have been that the game and FMV's were running at 30 while the logic was trying to run at 60. The game and FMVs were both slow, so I changed it to 30, then back to 60, suddenly everything was fixed.
