### ISSUE TITLE
Technical Audio Question; Curious Non-Issue

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#1093]
I'm currently putting together a video about the narrative of the original SH2 and want to showcase it at its best. Naturally, the EE version is visually the best but it's been brought to my attention that the PS2 audio quality is slightly better in some rare instances.

I've noticed in doing direct comparisons between the PS2 version (emulated via PCSX2) and the EE version, the PS2 version sounds more "warm" while the EE version sounds just a smidge crushed. I only noticed when comparing them back to back. Some other audio differences being the Forest Trail stalking footsteps sound effects play very loudly in EE compared to PS2, but also in better quality in EE. Later the "chattering" sounds around the street entrance to the first Lying Figure encounter tunnel are much harder to hear in EE. There also seems to be a sound that plays in the Historical Society when approaching the Misty Day painting in the PS2 version, but not the EE version. The SFX in general seem to be just ever so slightly pitched up compared to PS2. There may be other differences I haven't noticed yet.

My question then is, is this a matter of needing higher quality audio samples, or is this just how the PC version's audio system renders sound (which iirc you had rewritten), or a mixing/levels issue? Maybe just my playback system? I don't expect you guys to address this with an update at this stage, but since you're confident in the project's completion there is seems to me some reason the differences were conceded as close enough (and they really are, this is a maximal purist splitting of hairs lol) and is still miles better than the vanilla PC version. I'm just curious how deep the reasons go, if an independent mod could address this or if this is some hardcoded stuff that's impossible to change.

As always with my nonsense, feel free to ignore if you don't have time to answer all of my tedious questions!

**Comment by Polymega** [comment]
The audio will sound different as its different hardware and software rendering it. Also, the way the PS2 processes and arranges audio for playback is quite unique in its own right. We've extracted the raw audio samples from a PS2 retail disc and "baked in" a proxy reverb effect like what the PS2 does through its post-processing filters, but the sound will never be identical.

**Comment by GlitchyReal** [comment]
Thank you so much for the reply! That's all I wanted to know :)
