### ISSUE TITLE
final boss crash

### ISSUE THREAD

**Issue by k0bdaz** [elishacloud/Silent-Hill-2-Enhancements#1095]
after playing the final boss cutscene, after two or one seconds of gameplay, the game crashes without any error code or anything, it happens either way  by letting the cutscene play or skippíng it, tried restarting or playing it on compatibility mode, didnt work
[d3d8.log](https://github.com/user-attachments/files/17469407/d3d8.log)

**Comment by Polymega** [comment]
Typically, if the game is consistently crashing at the same point, that means one of the game's files is corrupted or simply bad. I'd recommend making a backup of your save folder (`Silent Hill 2\data\save\Folder 01`) then removing the game files and doing a fresh install.

**Comment by k0bdaz** [comment]
you where right, thank you

**Comment by k0bdaz** [comment]
you where right, thank you!
