### ISSUE TITLE
problema con cinematicas 

### ISSUE THREAD

**Issue by Juanes2sh** [elishacloud/Silent-Hill-2-Enhancements#1101]
Tengo un problema y es que en las cinematicas el audio se corta o y van lentas

**Comment by Polymega** [comment]
Please try some of these suggestions: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general

**Comment by Polymega** [comment]
Closing ticket due to no response. If you're still having playback issues with the FMVs, please check out this post: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/1107

Feel free to re-open the ticket if you need further assistance.
