### ISSUE TITLE
Silent Hill 2 Enhanced Edition free camera

### ISSUE THREAD

**Issue by Gomufra** [elishacloud/Silent-Hill-2-Enhancements#1105]
Hello friends and developers <3

 I'm a content creator and I was wondering if there is a way to be able to move the camera freely in Silent Hill 2 enhanced edition.

Some time ago I saw a post on reddit about this camera mod but the website hosting the files is down.... https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/351#issuecomment-728266241

I would like to know if I can find the files so I can get shots of some scenes from the game for my youtube channel.

Researching, I found that one person is selling the ‘mod’ but I don't find it funny that files that used to be easily accessible and free are now being sold for 40$ by a person taking advantage of that https://ko-fi.com/s/6e17a881da

I look forward to your reply, thank you <3

**Comment by Polymega** [comment]
Hi there,

> Some time ago I saw a post on reddit about this camera mod but the website hosting the files is down.... https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/351#issuecomment-728266241

The download link from that link still works. Be sure to right click the link and "Save as..."

Do note that you will need to have Cheat Engine installed in order for my camera editor tool to work. Acquiring Cheat Engine can be... a little sketchy... and if you have it running while a client such as Steam or Epic Games is running could lend you in trouble. There for, I won't guide you on how to get Cheat Engine. But, if you already have Cheat Engine, my camera editor tool will work with this link: http://www.igotaletter.com/temp/sh2pc/_UNIVERSAL_LIST.zip

Download it, unzip the Cheat Table (.ct) from within, then load the Cheat Table within Cheat Engine. Then, hook Cheat Engine into the game (sh2pc.exe) and you should be good. Just make sure the game is using our executable (sh2pc.exe) that was provide with our project files.

You can see the shortcut keys to use the cam tool here: https://youtu.be/G-XvyIjZQoE?si=Se1SFwq22K38NxPj&t=42

> Researching, I found that one person is selling the ‘mod’ but I don't find it funny that files that used to be easily accessible and free are now being sold for 40$ by a person taking advantage of that https://ko-fi.com/s/6e17a881da

This doesn't appear to be my cam tool. It looks like this person made their own cam tool, so they have the right to sell it if they choose. Their cam tool looks a lot "smoother" to use than mine, as well.
