### ISSUE TITLE
Complex fog creates massively low framerate and stuttering

### ISSUE THREAD

**Issue by Manodahour** [elishacloud/Silent-Hill-2-Enhancements#1106]
I have a brand-new computer with a 4070ti super 32 gigs of ram and the complex fog setting causes massive framerate drops and stuttering. Is there any workaround other than turning the complex fog off? Thats all that is causing the framerate drop

**Comment by Polymega** [comment]
That's obviously not normal behavior for such a stout graphics card. Are you using any form of Nvidia DSR or the like to render the game at an extremely large resolution and having it downsample? By chance does your PC also have an integrated graphics option that the game might be using instead of your dedicated/discrete graphics? See here: https://www.techadvisor.com/article/727646/how-to-set-a-default-graphics-card.html

**Comment by Manodahour** [comment]
So I don't have DSR in my control panel options and when I try to choose a dedicated graphics card for my game that option is also not available either. It seems like when am running through thicker fog, my character slows down noticeably which leads me to believe that there is a framerate drop.
![Screenshot 2024-11-07 114048](https://github.com/user-attachments/assets/ad977b6a-ab4b-4e5c-b552-bfa00557386d)
![Screenshot 2024-11-07 115525](https://github.com/user-attachments/assets/b8282069-0a34-4b26-ac20-e15e65c181cc)
![Screenshot 2024-11-07 115643](https://github.com/user-attachments/assets/0cf4e655-dee8-4f10-8cee-00c6b621b3b2)

**Comment by Polymega** [comment]
At this time, I'm not sure what's going on. As reference, I have no issues running it with my RTX 3060 or GTX 1660 with the fog fix enabled.

**Comment by AeroWidescreen** [comment]
> It seems like when am running through thicker fog, my character slows down noticeably which leads me to believe that there is a framerate drop.

My advice is to use software like MSI Afterburner to determine what your framerate actually is and to get a better idea of what's going on with your hardware. I have the same graphics card and experience no performance issues at native 4K.

https://www.youtube.com/watch?v=H23FSEybZsk

Uploading your d3d9.log file (located in the SH2 install folder) could also be helpful here, as it will give us more information about your setup: the amount of cores the game is using, the exact resolution you're playing at, etc.

**Comment by Manodahour** [comment]
Here are my logs. BTW when I turn on directx 9, I get a black screen when starting the exe. I can only play on directx 8
[d3d8.log](https://github.com/user-attachments/files/17674425/d3d8.log)

**Comment by AeroWidescreen** [comment]
From your log:
> 19536 00:52:14.567 | Using video card: Intel(R) UHD Graphics 770 (0x8086)

It says the game is using your integrated graphics (not your 4070 Ti Super). This is likely the issue. If you're using a desktop computer:

A. Verify that your HDMI / DIsplayPort cable is plugged into your graphics card, not your motherboard.
B. [Disable your integrated graphics through the device manager](https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/09/disabling-igpu-in-device-manager.jpg). DO NOT do this if only one display adapter is listed!
C. Disable your integrated graphics through the BIOS. DO NOT do this if you don't know how to reset your BIOS without display output!

**Comment by AeroWidescreen** [comment]
I also noticed that you're completely missing the entire Display category in your Nvidia Control Panel. I'm betting you don't have your HDMI / DisplayPort cable plugged into your graphics card, so your system has been using Intel UHD the entire time... have you tried any other games? You might be in for a pleasant surprise lol.

**Comment by Manodahour** [comment]
Okay so I was not connected to my graphics card lol. But the issue still persists. When I run through thick white clouds of fog, my character noticeably slows down. My frames actually do not drop but maintain a consistent 59-60 FPS with an average of 7% latency. I'm thinking that this may just be a normal part of the game.

**Comment by Polymega** [comment]
- Can you re-check your log file and confirm it is now using your 4070?
- While outdoors, James will begin to slow down his run speed after running for X amount of seconds. If you stop running and let him catch his breath, he'll run at full speed for X seconds before slowing down again. Are you sure this isn't what's happening?

**Comment by Manodahour** [comment]
[d3d8.log](https://github.com/user-attachments/files/17681701/d3d8.log)
![Screenshot 2024-11-08 115556](https://github.com/user-attachments/assets/847a2770-cd3c-4565-bab1-196c140487c7)
![Screenshot 2024-11-08 115731](https://github.com/user-attachments/assets/1b6eadc6-cd83-4070-8485-37283b53b85b)
![Screenshot 2024-11-08 115801](https://github.com/user-attachments/assets/3315bec3-b877-48e6-a3e6-d7745890b51e)
![Screenshot 2024-11-08 115815](https://github.com/user-attachments/assets/6ac80b55-b1f9-4cfa-9c4b-143a34793411)

here is the log a some more possibly important information. I have not disabled integrated graphics card or changed the bios. Is that still necessary?

**Comment by Manodahour** [comment]
Also yes my character is running the whole time. I will also have to check that out

**Comment by Polymega** [comment]
> I have not disabled integrated graphics card or changed the bios. Is that still necessary?

No, it's not. If you look at your new log file, the game is now using your discrete GPU instead of your integrated GPU:

```
17536 11:31:12.444 |------------- GPUs -------------
17536 11:31:12.444 m_IDirect3D9::LogAdapterNames | - Adapter: 0 \\.\DISPLAY1 NVIDIA GeForce RTX 4070 Ti SUPER
17536 11:31:12.444 |--------------------------------
```

> Also yes my character is running the whole time. I will also have to check that out

It's really hard to say without seeing a video of it happening, but I'd suspect it's just James naturally slowing down his stride after running for a while. See here for an example: https://youtu.be/k7Kr15i7qeI?si=QK70e4qwbJcw5QQT&t=846

Notice after about 5-7 seconds he begins to slow down a little. You need to let James catch his breath again in order to run at full speed for a short while. He'll eventually lose speed again until you let him catch his breath again.

**Comment by Polymega** [comment]
Closing ticket out. Feel free to re-open if you need further assistance.
