### ISSUE TITLE
I have chosen English, but my everything besides the menu is spanish, the exploration, the items, the inventory. How can I fix this, maybe I can delete every language besides english, could somebody help me please?

### ISSUE THREAD

**Issue by raintucha** [elishacloud/Silent-Hill-2-Enhancements#1108]

**Comment by AeroWidescreen** [comment]
Can you verify if this occurs _**without**_ the Enhanced Edition installed? Because it sounds like an issue with your copy of the game.

**Comment by Polymega** [comment]
Closing ticket due to no response. Feel free to re-open if you need further assistance.
