### ISSUE TITLE
Game immediately crashing upon jumping down the hole at the start of the Prison segment

### ISSUE THREAD

**Issue by RealColinNight** [elishacloud/Silent-Hill-2-Enhancements#1109]
[d3d8.log](https://github.com/user-attachments/files/17698157/d3d8.log)
Log file is included. The game has had no prior issues. Multiple attempts have been made, however the game crashes every time.

**Comment by Polymega** [comment]
When the game consistently crashes in one spot that usually means there's a corrupt file. I'd recommend making a backup of your save files (found in `SILENT HILL 2\data\save\Folder 01`), then deleting your game folder and re-downloading the game and our project.

**Comment by RealColinNight** [comment]
Thank you. Will try and get back about it.

**Comment by Polymega** [comment]
Closing ticket for now. Please feel free to re-open if you need further assistance. I do believe backing up your save files and re-downloading everything should resolve the problem.
