### ISSUE TITLE
Resolution Issues, Display Issues and Windowed Mode Crashes

### ISSUE THREAD

**Issue by GeekyGoneWilds** [elishacloud/Silent-Hill-2-Enhancements#1112]
![sh2 settings main screen](https://github.com/user-attachments/assets/6a164bb2-d326-46fd-8c9f-127d9f09af2f)

So this is a weird one. Up until recently everything was working fine. I'm not sure what exactly had changed on my end but I'm having an issue with resolutions and windowed mode.
No matter what display settings I have in-game, it opens up 640x480, and I get the UAC popup/admin mode. The picture I uploaded shows exactly what it does and the settings in-game is 1920x1080, but it is forcing my display to not only change but also the way they're laid out. This is only however if I've left it in windowed mode (after successfully keeping it that way) If I'm in FS or FSW, it's fine except it does still force my display to change resolution to match, even if I change it in Windows settings, that's ignored and it overrides. My main screen is 2560x1440 connected via Display Port, and my other two monitors are HDMI 1080p. 
I can change between FS and FSW no problem though again, the forced resolution change is aggravating. When I try to go into windowed mode, the game instantly crashes and my screens are constantly refreshing/flickering making it extremely difficult to kill the task as I tend to lose the curser and unable to see anything. Currently been playing in Speedrun mode however even if I'm not using that option and try to mess about with the settings, it seems to make no difference. I haven't touched any other settings as I never needed to.

Hopefully, I have managed to attach the d3d8 log and a picture to give you an idea of what it does.  Apologies if I've done that incorrectly, I'm not too savvy with Github. 

I appreciate any assistance and just wondering what I'm missing here. If you require anything else please let me know.
[d3d8.log](https://github.com/user-attachments/files/17740384/d3d8.log)

**Comment by Polymega** [comment]
@elishacloud could you check out his log? There's some weird entries going on inside it.

**Comment by Polymega** [comment]
This line in the log caught my attention:

```
2400 18:13:51.313 Environment variable __COMPAT_LAYER = "640X480 Installer"
```

Can you right click `sh2pc.exe`, select **Properties** and share a snapshot of what's shown under "Compatibility"?

**Comment by GeekyGoneWilds** [comment]
Absolutely! I'm just out of the house right now but will be back shortly.
Off the top of my head I'm pretty sure nothing is checked (run as admin,
compatibility or 640x480) but I'll of course double check. I have no eyes
deer what's happened lol I do get the admin prompt every time I run the
game though even though I looked to see if that was checked.

Again, sincerely appreciate you looking into this, no doubt it's something
my end.

**Comment by GeekyGoneWilds** [comment]
![image](https://github.com/user-attachments/assets/ad5099cc-9ea8-4b79-8b5e-24c5394b48ca)
here you go! Sorry for the delay

**Comment by elishacloud** [comment]
Windows is giving you the compatibility settings.  They are probably a registry key or a compatibility pack entry.  The easiest way to check is to rename `sh2pc.exe` to something else, like `sh2pctest.exe` and run it with the new name.  Compatibility settings are tied to the name.

**Comment by GeekyGoneWilds** [comment]
I don't want to jinx it, but that seems to have worked like a charm! No idea what was going on. I did another fresh install and registry clean which, SH2 was coming up with issues for some reason. Either way, I think this is the fix!
