### ISSUE TITLE
Animation Issue - Maria Ending; James' Eyes

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#1113]
I just noticed in the Maria ending at Rosewater Park, when James says, "It's okay. I have you." his eyes snap down, darken, and loose their shine. Then they return to normal. It kinda looks like a different texturing or a flipped/zoomed out UVs, not sure. I don't think it's actually the animation since his eyes seem to track properly, but the irises are too low and you can start to see the top edge of the eye texture under his upper eyelid.

I understand the project is wrapped and cutscene data is a pain to mess with, but I hope it's not too late or an impossible fix.

**Comment by Polymega** [comment]
There's several instances of eye behavior like this as you play. If you look at James and Mary/Maria's eyes during the cutscenes before the final boss fights, similar behavior is exhibited here. Unfortunately, this is something we probably won't be looking into.
