### ISSUE TITLE
Is there any way to bring back the old FMVs without black pillars?

### ISSUE THREAD

**Issue by nomadspy** [elishacloud/Silent-Hill-2-Enhancements#1119]
The new AI upscaled FMVs are beyond ugly like cheap smoothing instagram filter. I want the old FMVs from the project the ones that were just slightly upscaled to higher res, I brought them back but the issue is no matter what setting I use in the newest build they are always with the black borders. Tried every setting in the config tool and the ini.

**Comment by Polymega** [comment]
The borders were "baked in" to the older versions of the FMVs due to limitations of FMV scaling with our project at the time. They cannot be removed unless you edit them out and re-export them back to Bink format.
