### ISSUE TITLE
Erase/Hide knife pointer

### ISSUE THREAD

**Issue by RenoFriends** [elishacloud/Silent-Hill-2-Enhancements#114]
Hi there, in the old SH2 enhancement mods I was able to "hide" the knife cursor pointer just deleting the image from Media/pic/etc but know that doesn't seems to work... ¿Where is that image?

Thanks!

**Comment by Polymega** [comment]
Did you run into any stability issues by deleting that file? It would probably be wiser to find a small, 100% transparent PNG image to replace it instead.

**Comment by Polymega** [comment]
Remember: If you remove a file from the "sh2e" folder, the game will instead pull whatever file is in the "data" folder, which also holds the original knife cursor file. You should definitely NOT delete anything in the "data" folder. 

I'm not at my computer tonight to help you with this, but you should instead find a fully transparent PNG to replace the file instead.

**Comment by RenoFriends** [comment]
I already rewrote the point with a transparent PNG image and that fixed the thing! Thanks

By the way can I ask why the new FMVs are in 16:10 instead of 16:9? I have small verticals bars at both sides of the FMVs now

**Comment by Polymega** [comment]
Good!

About the FMVs:

In my quest to simplify the installation guide for users (as people who are less computer savvy have mentioned it's a bit overwhelming) I removed the FMV options and made it to where only the original FMV pack is available (the one originally made by angular graphics).

If you still have your 16:9 FMV download you're completely fine to use that still.

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
