### ISSUE TITLE
Translucent objects

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#117]
When **Room312ShadowFix** is enabled, James and other objects become translucent in Room 312 of the Hotel.

![bug](https://i.imgur.com/HWTra4m.jpg)

> 9880 12:12:36.161 "Radeon RX 580 Series"
> 9880 12:12:36.162 Windows 10 64-bit (10.0.17763) 
> 9880 12:12:36.162 Running from: "D:\Games\KONAMI\SILENT HILL 2\sh2pc.exe"
> 9880 12:12:36.162 Config file: "D:\Games\KONAMI\SILENT HILL 2\d3d8.ini"
> 9880 12:12:36.162 Loading as dll: "d3d8.dll"
> 9880 12:12:36.164 Wrapper created for "d3d8.dll"
> 9880 12:12:36.197 Hooking the FileSystem APIs...
> 9880 12:12:36.197 Setting SingleCoreAffinity...
> 9880 12:12:36.197 DisableCDCheck searching for memory address!
> 9880 12:12:36.201 DisableCDCheck Error: Could not find CD check function address in memory!
> 9880 12:12:36.201 Finding SFX file locations...
> 9880 12:12:36.706 Updating SFX memory address locations...
> 9880 12:12:36.706 Allocating memory buffer for sddata.bin file...
> 9880 12:12:36.706 Setting 2TB hard disk Fix...
> 9880 12:12:36.706 Setting PS2 Style Noise Filter...
> 9880 12:12:36.706 Increasing the Draw Distance...
> 9880 12:12:36.706 Setting Cemetery Lighting Fix...
> 9880 12:12:36.706 Setting Rowboat Animation Fix...
> 9880 12:12:36.721 Updating the Catacomb Meat Cold Rooms color...
> 9880 12:12:36.721 Updating Fog Parameters...
> 9880 12:12:36.721 Setting Piston Position Fix...
> 9880 12:12:36.721 Hiding Red Cross health indicator during cutscenes...
> 9880 12:12:36.721 Enabling PS2 Flashlight Fix...
> 9880 12:12:36.721 Enabling Lighting Transition Fix...
> 9880 12:12:36.721 Enabling XInput Vibration Fix...
> 9880 12:12:36.734 Enabling Custom Fonts...
> 9880 12:12:36.746 Enabling Custom Exe Strings...
> 9880 12:12:36.755 Loading the "Nemesis2000 Fog Fix" module...
> 9880 12:12:36.757 Loading the "WidescreenFixesPack and sh2proxy" module...
> 9880 12:12:37.847 Loading the "modupdater" module...
> 9880 12:12:38.143 Silent Hill 2 Enhancements module loaded!
> 9880 12:12:38.316 Redirecting 'Direct3DCreate8' ---> Passing on to 'Direct3DCreate9'
> 9880 12:12:40.572 Setting Hotel Water Fix...
> 9880 12:12:40.578 Setting Hotel Room 312 Shadow Flicker Fix...
> 9880 12:12:40.578 Setting RPT Apartment Closet Cutscene Fix...
> 9880 12:12:40.578 Setting RPT Hospital Elevator Animation Fix...
> 9880 12:12:40.578 Fixing Esc while transition is active...
> 9880 12:12:40.578 Setting infinite rumble window hook...
> 9880 12:12:43.058 Unhooking library functions
> 9880 12:12:43.058 Unloading Silent Hill 2 Enhancements!

**Comment by Polymega** [comment]
That's trippy looking! I tested v1.0, 1.1, and DC on my Win7/Nvidia machine and didn't run into this problem. I also watched a few streamers on Twitch playing with our latest build and all seems fine for them, too. 

Do you remember what area you were at before you loaded into this room? Maybe a value carried over from there that didn't get changed/reset for this room?

Can you confirm for me this byte is set to the following value while you're in this room? 
sh2pc.exe+6333C5 (00A333C5) byte

1.0: 7
1.1: 3
DC: 3

**Comment by AeroWidescreen** [comment]
> Do you remember what area you were at before you loaded into this room? Maybe a value carried over from there that didn't get changed/reset for this room?

I don't know, all I did was use the same downloaded saves I've been using for years now. I tried the 3rd floor hallway save (after viewing the videotape), and I tried the Elevator room save. They both resulted in the same issue.

> Can you confirm for me this byte is set to the following value while you're in this room?
sh2pc.exe+6333C5 (00A333C5) byte

The value is at 7 for v1.0. If I change it to 0 then the objects become opaque again, but the shadow glitch returns. Is it suppose to remove the fake bloom effect? Because if so, I don't think that's the best solution.

This appears to work for me:

```
00A333C5 00000000
006BCE50 00000000

```

![bugfix](https://i.imgur.com/rKq1rFz.jpg)

**Comment by AeroWidescreen** [comment]
sh2pc v1.0: [Cheat Table](https://mega.nz/#!kTRUnKSJ!lIMRl7xT4XVMAdmIdcYrerinRs9R4vSyEjBYh4CAdJI)

Tell me if this works for you. If it does then I'll check the other executables.

**Comment by Polymega** [comment]
> Is it suppose to remove the fake bloom effect?

No, it's not and is retained for me. 

> Tell me if this works for you. If it does then I'll check the other executables.

Works good for me, well done! Be mindful when you do the other executables; you'll notice the value for the original address are different from 1.0 to the others. It turned out the 7 value made the inventory items disappear on 1.1 and DC. Just be sure to check everything (including menus) when including the other executables for this fix.

**Comment by AeroWidescreen** [comment]
> It turned out the 7 value made the inventory items disappear on 1.1 and DC while in this room. Just be sure to check everything (including menus) when including the other executables for this fix.

Hmm, that's probably because of how many different instructions use that address for different things. Only one of them needed to be changed I think.

Can you confirm this works with the other versions?

[Cheat Table](https://mega.nz/#!gbBkWYjS!qbKo_Bf-KCGteumP0QaNpKQZ27dnHxmSY_Mfc_-xqfA)
[Executables](https://mega.nz/#!BXpV3IyZ!25ZG-6IjcqTMo26H6bkcf9vD1oUbOpoGwNqFLg29kUA)

**Comment by Polymega** [comment]
Yes sir, confirmed working well on all versions.

**Comment by AeroWidescreen** [comment]
@elishacloud The code for **Room312ShadowFix** needs to be replaced due to unreliability. Too many instructions were using that address and different executables produced different results with the same value.

I improved the fix by changing the instruction responsible for the bug when the player is in Room 312. It worked for me and Polymega using v1.0, v1.1 and DC.

---


`006BCE50` can be found here:

00503812
005AF736

```
005B01BF jmp 00000000
00000000 cmp [RoomID],000000A2
00000001 je 00000004

// if not Hotel Room 312
00000002 mov edx,[edx+006BCE50]
00000003 jmp 005B01C5

// if Hotel Room 312
00000004 mov edx,00000000
00000005 jmp 005B01C5
```

**Comment by elishacloud** [comment]
Updated this in the latest build.  Test module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3445366/d3d8.zip)

**Comment by Polymega** [comment]
I can confirm the shadow flicker (the original intent of this fix) is gone across all binaries. Aero_'s translucence glitch from this is probably also resolved, as he's the one who provided the new code fix, but he can confirm that when he has a moment. Thank you both!

**Comment by AeroWidescreen** [comment]
It's working for me, thanks.
