### ISSUE TITLE
Apartment shadow pop-in

### ISSUE THREAD

**Issue by JoesGuy** [elishacloud/Silent-Hill-2-Enhancements#120]
Hi folks! Not sure if this has been mentioned before or is something that's even fixable. It's almost too small to care about. But when first entering the Apartment building, to the right of the save square, there is a mailbox. Approaching that mailbox has James' shadow pop in out of nowhere and back out again when you walk away from it. Just thought I'd throw that in there if it's one of those quick fixes to make this game perfect. ;D

**Comment by Polymega** [comment]
Hi @JoesGuy , 

Thanks for the comment! Believe it or not, this is correct, normal behavior for the game. 

Whenever James is inside a specialized lighting zone (that produces its own shadowings), any shadows that enter or leave the zone will simply disappear. Compared to other games like Haunting Ground, Silent Hill 2 doesn't fade out/fade in shadows when near the edge of a lighting zone. Here's a animated demonstration: 

![sh2pc-2019-04-29-13-55-11111](https://user-images.githubusercontent.com/27395260/56916868-fd0b0d80-6a87-11e9-9da8-f99fd8e7adfb.gif)

Here is the same behavior on the PlayStation 2 version: https://youtu.be/DlmOMTAfBBk

And a more obvious example of this is when you play the Born From a Wish campaign, as there are many light fixtures within the Baldwin Mansion: https://youtu.be/XxAjQ4JxEyI?t=307

**Comment by JoesGuy** [comment]
Wow, that's still a pretty nifty effect in the early 2000's. Thanks for clearing that up.
