### ISSUE TITLE
Languages on website

### ISSUE THREAD

**Issue by Adam-Saeed** [elishacloud/Silent-Hill-2-Enhancements#121]
Could there be any support for translations in Installation Guide webpage?
it would be great for those who have fan translations relying on the Enhanced Edition.

**Comment by Polymega** [comment]
That sounds like a pretty good idea. The only two things that make me hesitant are: 

1. We need someone native in the language to play the entirety of the game to confirm the fan translation pack is working correctly and everything is translated well. 
2. We need to ensure the fan translation pack works with the high resolution font mod (`UseCustomFont`) without any negative issues.

I'd then need to know from the play tester how to install it (which I assume is just replacing `.mes` files) and what language selection the fan translation pack overwrites. 

In the meantime, over at PC Gaming Wiki, there seems to be a list of many current fan translation packs you can download: https://pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Audio_settings

**Comment by Adam-Saeed** [comment]
I meant to just translate the guide.
The inclusion of other fan translations sounds great, but there’s another problem which is in some languages we need to insert it’s characters and there’s no way but to replace an already existing characters in the font.

**Comment by Polymega** [comment]
I'm going to close this for now, as I don't plan to add various languages to the site at this time. Google Translate should be able to handle most of the heavy lifting with verbiage on the site. And if we're able, we hope to make an installer for the overall project at some point.
