### ISSUE TITLE
Console style save points?

### ISSUE THREAD

**Issue by powerpuffboysz** [elishacloud/Silent-Hill-2-Enhancements#122]
I was wondering if it would be possible to have the option of the limited save point system used in the console versions accompanied by the weird red halo/ logo thing

**Comment by Polymega** [comment]
Hi @powerpuffboysz,

Probably not. Removing a useful game feature isn't really good to do, nor the best use of time/resources. 

You can limit yourself to only saving at the "red squares" found within the game to provide a more console-like feel with the save system. 

Also, the Halo of the Sun wasn't part of SH2; it was introduced/used in SH3.

**Comment by AeroWidescreen** [comment]
> You can limit yourself to only saving at the "red squares" found within the game to provide a more console-like feel with the save system.

Indeed. I'm not sure what this person wants us to do when there's nothing stopping them from doing this. The limited save point system is already there, unless they're talking about something else.

**Comment by powerpuffboysz** [comment]
My mistake I got my wires crossed it was the red squares in SH2. And I was not asking for removal of the save anywhere system but a similar save system to the ps2 where you had reach certain points on the map to save. I apologize if I confused anyone. Thanks anyway if it's not possible or worth implementing

**Comment by Polymega** [comment]
The red squares are still there. Meaning, all the original save points from the console versions are still here and you can still save at them. 

The only difference is, with the PC version, on top of saving at the "normal" save spots, you also have the ability to save nearly anywhere else. 

If you prefer, you can make save files only at the red squares, just as it's done in the console versions.

**Comment by Polymega** [comment]
Just interact with the red squares you find throughout the game and the save system will act like it does in the console versions.
