### ISSUE TITLE
Menu map and advance options

### ISSUE THREAD

**Issue by HollyDJones** [elishacloud/Silent-Hill-2-Enhancements#123]
Hi!

Is there any way to see the menu map at 16:9?

On the other hand, in the Advance Options, "Advance Filters" and "Lens Flare" is set to "off".  May I set to "on"?

Regards :)

**Comment by Polymega** [comment]
Hi @HollyDJones, 

The next major mod we're hoping to do for the game is to make the main menu, save screen, and maps properly display in widescreen (along with making all other fullscreen images look nicer). 

In the meantime, if you'd like, you can stretch the fullscreens images (which includes the maps) to fill your entire screen. As you can guess, this will stretch the map images. 

If you'd like to do this, open the `d3d8.ini` and set: 
`Fix2D = 0`
` FullscreenImages = 0`

> On the other hand, in the Advance Options, "Advance Filters" and "Lens Flare" is set to "off". May I set to "on"?

Yes! Definitely turn those on for a better experience. :)

Also, in that Options menu, ensure fog is set to "complex" and High Res Textures is set to "On."

**Comment by HollyDJones** [comment]
Ok! Thanks for the reply :D

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
