### ISSUE TITLE
Complains on ReShade module

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#124]
1. I don't know why it was decided to choose "Ctrl+W" as the effect toggle button, but it's REALLY ANNOYING for all who decide to set some custom controls. For example, I always set WASD on movement and Ctrl to control the camera. Considering the "EE" pretends to make game actual, the modern controls are good fit to. I understand the hotkey may be changed, but how many people will do that? It's simplier for them to redefine game controls instead. The default Rehsade menu hotkey "Home" was pretty engoug; I really don't know why it was needed to change that.

2. The preset built-in "HQ4X" effects gives just little blurry picture that looks bad on HD and 4K monitors. I think it would better to replace this with FXAA or another layer of MSAA that would give smooth lines without significant loosing sharpness.

3. I think the name of the preset is too out of the game's file system aesthetics. At least it might be shortened to sh2pc-reshade.ini...

**Comment by Polymega** [comment]
Hi @Psycho-A,

> I don't know why it was decided to choose "Ctrl+W" as the effect toggle button, but it's REALLY ANNOYING for all who decide to set some custom controls.

Sure, this can be changed to something like the 'Home' key instead.

> The preset built-in "HQ4X" effects gives just little blurry picture that looks bad on HD and 4K monitors.

This filter is used to help bring the visuals more in line with the PCSX2 version. It can be disabled from the user end, of course. I can also experiment further with other AA solutions. FXAA did more harm than good to the high resolution fonts, which is why I opted to not include that AA method. And I don't believe ReShade offers MSAA.

> I think the name of the preset is too out of the game's file system aesthetics. At least it might be shortened to sh2pc-reshade.ini...

Sure, that can change as well. At the time, I had that named the way it was due to multiple ReShade test filters I was experimenting with.

**Comment by Psycho-A** [comment]
Thanks for answer, changing would be really nice!

As for PCSX2 - not sure we may consider all rendering factors, because the upscaling mechanism of PCSX2 and often certain PS2 games too isn't always can reach the true HD image with native monitor DPI and no interpolations. At least, the TV interlacing makes almost all games look more blurry (if it has no progressive out) and even built-in de-interlacing doesn't help enough.

**Comment by Polymega** [comment]
I've updated the ReShade package. Notes about the update/change can be found on the changelog: 
http://enhanced.townofsilenthill.com/SH2/#changelog 

> As for PCSX2 - not sure we may consider all rendering factors, because the upscaling mechanism of PCSX2 and often certain PS2 games too isn't always can reach the true HD image with native monitor DPI and no interpolations.

This is very true. At the same time, a goal on my end is to make installation as straight-forward to install/use as possible for the common player. Many gamers don't understand the intricacies and cost/reward for the many different types of anti-aliasing solutions out there (even I don't fully understand them all). So while ReShade may not have the most robust AA solutions, its simple drag-and-drop method to improving visuals is an ideal approach for the common player. 

This is a balance I'm personally trying to achieve with the project; if a PC gamer understands and knows how to utilize more advance AA techniques such as supersampling, then they should definitely utilize it! But for our intents and purposes--at least during this moment in time--making the steps as easy to follow/use while still providing good results is the ideal approach.

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
