### ISSUE TITLE
Game unable to load

### ISSUE THREAD

**Issue by spoopmark** [elishacloud/Silent-Hill-2-Enhancements#125]
Recently my SH2 game decided it doesn't want to run, and through some tests I figured out that it was my d3d8.dll file. If you remove it, the game loads fine, so I'm assuming the problem is incompatibility. (I even reinstalled the Enhanced mod thinking it was corrupted). With the dll file still in, I get this error message: 
The application was unable to start correctly (0x0000005) Click OK to close the application.
I can't find anything about it on this page or online. Hoping I can find some help here.

**Comment by Polymega** [comment]
Hi @spoopmark,

Sorry you're having some troubles. After launching the game with the `d3d8.dll` file and receiving the error message, can you then please attach your `d3d8.log` file here?

**Comment by spoopmark** [comment]
Thanks for getting back to me so quick. Here's the log @Polymega 

6588 10:07:41.496 Starting Silent Hill 2 Enhancements! v1.2.1298.0
6588 10:07:41.497 "Intel(R) Q45/Q43 Express Chipset (Microsoft Corporation - WDDM 1.1)"
6588 10:07:41.503 Windows 10 64-bit (10.0.18362) 
6588 10:07:41.503 Running from: "C:\Users\Nevaeh Stiffey\Desktop\Games\Silent.Hill.2.Director.Cut\sh2pc.exe"
6588 10:07:41.503 Reading config file: "C:\Users\Nevaeh
Stiffey\Desktop\Games\Silent.Hill.2.Director.Cut\d3d8.ini"

**Comment by elishacloud** [comment]
@spoopmark, you are using an old version of the d3d8.dll Enhancement module.  There is a known issue with that version of the module and Windows 10 build 18362 (Windows 10 Insider Preview).  Can you try downloading the latest and see if that fixes the issue?  Just download and unzip it into your Silent Hill 2 folder.

You can download the latest from here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/download/v1.3.1340.0/d3d8.zip)

**Comment by spoopmark** [comment]
@elishacloud I tried what you said but I still received the same error message.

**Comment by AeroWidescreen** [comment]
If you remove d3d8.dll, does the game work or do you still have the same problem?

**Comment by spoopmark** [comment]
The game works and text loads properly. If nothing works I could just use the game without the enhancements.

**Comment by AeroWidescreen** [comment]
Of course, but it's important to know if the enhancement module is truly the source of the problem or not.

If you replace the ini file with the one I attached below, does it still give you trouble? Make sure d3d8.dll has been moved back to your installation folder again, obviously.

[settings](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3145912/d3d8.settings.zip)

**Comment by spoopmark** [comment]
Yes, the game still gives me trouble.

**Comment by Polymega** [comment]
> I removed the admin rights (which it had needed previously) and it opened. 

I'm not sure if the two are related, and this _shouldn't_ have any affect on launching/playing the game, but did you set read/write rights of the game's parent folder to **Modify**?

More info on how to do that can be found on this step: 
http://enhanced.townofsilenthill.com/SH2/#installGame
(Click the "View the steps to change folder permissions" link.)

**Comment by Polymega** [comment]
From your log file, it doesn't seem you installed the game to an admin-protected directory but it wouldn't hurt to check. 

[Also, perhaps the Intel(R) Q45/Q43 Express Chipset has conflictions with the game?](https://forums.tomshardware.com/threads/what-to-replace-an-intel-r-q45-q43-express-chipset-with.3059951/)

> You're not describing a discrete GPU, but the integrated graphics contained within your CPU, from about 2008. With that chipset, you either have the integrated GMA X4500 or GMA X4500 HD. So it's not surprising that you're running into issues; those integrated graphics weren't even really made for running the games of 2008.

**Comment by spoopmark** [comment]
I wouldn't think the chipset would have problems, because as I said before, it ran fine. Even with that, I don't have the funds to get a new card, so if it does get replaced it would be some time before I could do so. And, no, the game isn't in an admin-protected directory.

**Comment by Polymega** [comment]
> I wouldn't think the chipset would have problems, because as I said before, it ran fine

Apologies, you did say that. 

Have you tried downloading the Microsoft libraries suggested from the guide (mentioned for other issues)? It wouldn't hurt either way to download these: 

- https://www.microsoft.com/download/details.aspx?id=35
- https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by spoopmark** [comment]
I already have the most (or somewhat) recent versions of D3D (12) and of the Microsoft Visual (2017).

**Comment by elishacloud** [comment]
@spoopmark, I added some extra logging to see which line it is crashing on.  Can you try with this update and then upload the full log file?

Here is the update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3151110/d3d8.zip)

**Comment by spoopmark** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3154222/d3d8.log)

The game loaded fine, but yet again, the options and save menu don't have any text.

**Comment by elishacloud** [comment]
Thanks for the logs.  What version of the binary are you using?  The version that seems to work best is the North American v1.0.  You can download it [here](http://www.enhanced.townofsilenthill.com/SH2/#installEnhancedEXE).

Here are a couple of options you can try disabling to see if they help:
* `d3d8to9`
* `EnableWndMode`

**Comment by spoopmark** [comment]
It still doesn't display text. I also disabled both things you told me and it didn't change it.

**Comment by Polymega** [comment]
The text thing may be related to the high resolution font mod. Although it's supposed to fall back to the default (low res) font if it doesn't find the correct files. 

At the beginning of the troubleshooting it was determined the version of the SH2 Enhancements module wasn't up-to-date. 

Did you also download/update the Enhanced Edition Essential Files to v1.0.4? That update package contains the high res font: http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles

If it turns out that package also wasn't updated and you are also using ReShade, go ahead and update that too if you haven't done so in a while: http://enhanced.townofsilenthill.com/SH2/#installReShade

We're just trying to cover all bases in terms of updated files for the moment.

**Comment by AeroWidescreen** [comment]
@Polymega @elishacloud 

The ini file I asked him to try should've had everything disabled (check for yourself) except for the fog because I forgot about that. I doubt it would've made a difference anyway. This was his response:

> Yes, the game still gives me trouble.

I thought it had something to do with one of those features, but apparently not.

**Comment by Polymega** [comment]
Thanks, Aero_. I didn't check what was done in your test ini. 

@spoopmark It's not fun to do, but uninstalling the game, deleting any remaining files found within `\KONAMI\Silent Hill 2\`, and re-following the Installation Guide may be an option worth pursuing. Essentially the "did you restart it?" philosophy I.T. takes.

**Comment by spoopmark** [comment]
I uninstalled the game, re-downloaded it and added the enhancements. I still had problems. I'm currently not on my pc so I can't send any logs until I get home.

**Comment by spoopmark** [comment]
Sorry I took so long in getting the logs, I tried many things to fix it on my own. I removed enhancements and added them one by one, rolled back a few updates but nothing worked. The logs seem to still be the same.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3169492/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3169493/d3d9.log)

**Comment by Polymega** [comment]
Hi @spoopmark,

Sorry for the very long delay on this, but after other people had similar issues with the text not appearing as you, we've determined that weaked/older Intel integrated graphics chips cannot support the massive resolution size of the HD font.

You can see the similar issues here:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/264
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/240

Because of the integrated graphics you are using, I recommend setting the following in the `d3d8.ini` file for the best experience:

```
d3d8to9 = 0
UseCustomFonts = 0
Nemesis2000FogFix = 0
```

**Comment by elishacloud** [comment]
Closing this out.   It should be fixed in the next update.
