### ISSUE TITLE
I have a problem glithc with the inventory screen

### ISSUE THREAD

**Issue by CarrloX** [elishacloud/Silent-Hill-2-Enhancements#127]
I just open the inventory and everything is wrong
I can not appreciate anything
Is there any solution for this?
By the way, I speak and play in Spanish so if you see that my English is very bad, sorry
![glitch inventory](https://user-images.githubusercontent.com/42298361/57573601-d2a64200-73ef-11e9-8ad2-b44170032140.png)

**Comment by KitatusStudios** [comment]
When reporting issues like this, you should always post your log - so the issue can be investigated instead of just spitballing reasons why this has happened.

You can see how to find the log in pretty much any other thread, such as this one: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/125

**Comment by Polymega** [comment]
Hi @CarrloX 
Wow! That's pretty crazy looking! 

As KitatusStudios mentioned, can you please attach your `d3d8.log` file for us to look at? 

Also, can you tell us more about the following: 

- Does this happen every time you play the game? Or was this a one-time bug? 
- Are you also using [ReShade](http://enhanced.townofsilenthill.com/SH2/#installReShade)?

**Comment by CarrloX** [comment]
@Polymega right now I can not give you the registry of the dll file because right now I am using linux, but I can install windows back and replicate the glitch and send you the registry.
And about the other question, yes, the glithc always occurs on my PC when I open the inventory, and I did not have the reshade installed.

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.
