### ISSUE TITLE
Blood Size/Placement Fixes

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#128]
Hi Elisha, 

This fix would increase the size of the blood pools for fallen enemies to better match the PS2 version, along with changing the elevation of the blood pools while in two particular rooms to avoid the blood from "glitching" into other geometry: 

Possible fix name: 
`IncreaseBlood = 1 // Increases the blood pool size of dead enemies to better match the PS2 version.`

-----------------------

### Part 1: Increase blood pool size

- Upon game launch, set `00892AFC (float)` to `1` (one write, no constant iteration).

I've already play tested this on 1.0 and ran into no issues.

There's no exact science to the increased value, as all blood pools are randomly generated in terms of final size/placement. The blood pools on the PC version have always been noticeably smaller, so this increase just brings it more in line to the PS2 version: 

![blood_pool](https://user-images.githubusercontent.com/27395260/57644133-74ad6200-7589-11e9-8f0e-e954edb8fa07.gif)

If you'd like me to test this across all binaries, could you temporarily change the value to something like `4` so the blood pools become absurdly large? (That way I can easily tell if they're working on all executables.)

---------------------

### Part 2: Adjust blood pool position for apartment flashlight room

This prevents the blood from visually glitching into other geometry in these rooms, which can affect all versions of the game.

- When `Room ID 01FB7DAC (4 bytes) - 00000017 (Apartment Mannequin/Flashlight Room)` set:
   - `00956414 (float)` to `-3` (one write, no constant iteration).
   - `00956364 (float)` to `-3` (one write, no constant iteration).
   - `009563BC (float)` to `-3` (one write, no constant iteration).
   - `00956834 (float)` to `-3` (one write, no constant iteration).
- When this Room ID goes away **do nothing**, as the game will change these address values upon various new Room ID loads.

This raises the blood pool elevation to be above the carpet, in case the Mannequin dies on the carpet. If you kill the creature on the carpet the game knows to form the blood pool above it. But if you leave/re-enter the room the game puts the blood back on the main floor elevation which will clip into the carpet geometry: 

---------------------

### Part 3: Adjust blood pool position for Abstract Daddy boss room
![sh2pc-2019-05-24-22-18-28](https://user-images.githubusercontent.com/27395260/58373388-83860400-7efb-11e9-81ba-fd2f15496f0d.gif)

- When `Room ID 01FB7DAC (4 bytes) - 0000008A (Flesh Room)` set:
   - ~~`00892580 (float)` to `-1`  (one write, no constant iteration).~~
   - `00892588 (float)` to `0.25`  (one write, no constant iteration).
   - `00892598 (float)` to `-3`  (one write, no constant iteration).
   - `008925A0 (float)` to `-1.75`  (one write, no constant iteration).
- **When this Room ID goes away set those four addresses back to `-1` (one write, no constant iteration).**

This moves the X/Z coordinates of the blood pool around Abstract Daddy in the Flesh Room, so the blood won't clip into the bottom curved portions where the floor meets the walls. We can't use the previous blood elevation addresses here because, if you let the cutscene play out, special instructions will then control the blood elevation upon cutscene end which would need to be nop'ed, so this is the easier/safer approach to fix the blood here. 

![wwwwwwwwwwww](https://user-images.githubusercontent.com/27395260/58373835-81737380-7f02-11e9-9e31-9b4776e267d0.gif)

**Comment by elishacloud** [comment]
Ok, I implemented this fix.  I am pretty sure that Part 1 is good.  However, I had some trouble getting the correct addresses for Part 2, so you may want to test that a bit more on each version of the SH2 binary.

Here is the test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3440483/d3d8.zip)

_Note that this part of the fix `00892580 (float) to -1 (one write, no constant iteration)` does not seem needed since I think this is set to -1 by default, at least that is what you had me set it back to._

**Comment by Polymega** [comment]
Thank you Elisha! 

Yes, Part 1 is looking good. Unfortunately the bulk of addresses for Part 2 aren't being called.  Is this a case of needing the offsets for them?

**Comment by elishacloud** [comment]
>  Is this a case of needing the offsets for them?

No, let me check the addresses when I get home.  Is Part 2 working on v1.0?

And what about this address `00892580`?  Do I need to modify this to -1?  Isn't that what it defaults to?

**Comment by Polymega** [comment]
Thanks again for the test modules for all of this. Testing it in real-time helps me find things I wouldn't be able to find by manually adjusted the addresses after-the-fact in Cheat Engine. 

> Is Part 2 working on v1.0?

**I edited my original post and turned it into three (3) parts for ease of discussion.** 

**For Part 2 (Apartment flashlight room):**
It seems only one address (00956364) is changing to -3 when entering this room. The other three addresses aren't being affected. 

Not only that, but being able to test it in real-time now, it seems the game writes the blood elevation values to a dead enemy in a room _slightly after_ the Room ID has loaded in, which means our changes in this room are being overwritten. 

A possible revision (for Part 2 only) would be to change the values to `-3` (one write, no constant iteration) if/when those address values change from `0` to `any other value` while in this Room ID.

**For Part 3 (Flesh Room):**
> Do I need to modify this to -1? Isn't that what it defaults to?

No. You're correct; that one doesn't need to change as the value remains the same. I think I included it just because it's part of the "set" that makes up this enemy's blood pool positionings.

So if we drop that address from the list (since we're not changing it), it seems only 1 out of the 3 addresses are changing. 008925A0 is being incorrectly changed to `0.25` (that one should be `-1.75`).

**Comment by elishacloud** [comment]
> It seems only one address (`00956364`) is changing to -3 when entering this room. The other three addresses aren't being affected.

Thanks for the details.  I believe I know what the problem is.  I am using the wrong syntax for the address offsets.

> A possible revision (for Part 2 only) would be to change the values to `-3` (one write, no constant iteration) if/when those address values change from `0` to `any other value` while in this Room ID.

Ok, I should be able to do this pretty easy.

> No. You're correct; that one doesn't need to change as the value remains the same. I think I included it just because it's part of the "set" that makes up this enemy's blood pool positionings.

Ok, I thought so.  I will drop this one.

> it seems only 1 out of the 3 addresses are changing. `008925A0` is being incorrectly changed to `0.25` (that one should be `-1.75`).

Looks like I am using the wrong syntax for the address offsets here also.  I will fix all these issues when I get home.

**Comment by elishacloud** [comment]
Ok, I believe this update this work:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3444829/d3d8.zip)

**Comment by Polymega** [comment]
Yes, sir! All worked great across all binaries. Thank you!
