### ISSUE TITLE
Cut scene skipping issue, SMAA disabled

### ISSUE THREAD

**Issue by kingrulerCA** [elishacloud/Silent-Hill-2-Enhancements#130]
Hi all, 
Cut scenes skip and become out of sync but continue to play. I am using the ps2 video files. It seems to skip when there is a jump in FPS. I disabled SMAA.fx in the control panel and it seems to fix it. I'm new to this so I'm wondering if turning off SMAA.fx will create graphical issues, although so far I haven't noticed anything. 
Thanks

**Comment by Polymega** [comment]
Hi @kingrulerCA ,

Yes, very few people experience this issue while using ReShade with the SMAA filter. To start: Are you using the latest version (4.2.1) of ReShade provided on the install guide?

http://enhanced.townofsilenthill.com/SH2/#installReShade

If you aren't, try using that version first to see if you can then use the SMAA filter without issues. 

> I'm wondering if turning off SMAA.fx will create graphical issues, although so far I haven't noticed anything.

No, there will be no issues if you disable this. The only thing you will lose is the anti-aliasing benefits that the SMAA filter provides.

**Comment by kingrulerCA** [comment]
Hi, I was playing last night, and kept running into stuttering issues in gameplay and cut scenes even with the SMAA filter disabled :/  seems to be a problem with the FPS, it doesn't cap at 30; it hovers more around 60. I will install the latest version of reshade and let you know if it fixes the problem. Ill see if any of the troubleshoot guides fix it also.  Thanks again.

**Comment by kingrulerCA** [comment]
installed new reshade package and the NA executable and turned of SMAA, has seemed to fix most of my problems. thanks again

**Comment by Polymega** [comment]
Were you using the European executable prior? Also: 

> it doesn't cap at 30; it hovers more around 60.

Did you increase the FPS of the game from the `d3d8.ini` file? 

> Still getting slight stuttering when monsters make sounds in the distance though, any recommendations?

What are your PC specs? Have you tried fully removing ReShade, toning down the fog fix values, or disabling your GPU's anti-aliasing for the game (if you were using that)?

**Comment by kingrulerCA** [comment]
Yeah I was using the European executable before. I didn't change the FPS in the ini file but it was still hovering around 60, but after updating it, it sits at 30.  I've got a 2.16ghz processor and 4gb ram. I tried turning down the fog effects to no success. Tried removing reshade also to no effect. Not sure how to turn off GPU's anti aliasing?

**Comment by Polymega** [comment]
Hmm... It's always a bit tricky to troubleshoot things like this on our end. This isn't fun to do, but I'd recommend disabling some of the enhancements found within the `d3d8.ini` file. Disable one effect, launch the game, and if the problem persists, close the game, disable another effect, relaunch, and repeat. 

This will be a bit time-consuming but this would at least help pin-point if any particular enhancement(s) are causing you issue.

**Comment by kingrulerCA** [comment]
Ok I will try that, thanks for your help.

**Comment by Polymega** [comment]
@kingrulerCA 
I should probably also mention that on my Surface Pro 3 laptop, which has a 1.9 GHz processor and Intel HD Graphics, I **cannot** use the fog fix without consistent stuttering/lag. I have to disable the complex fog when I play on that laptop. Additionally, I can't use ReShade either, as that laptop isn't capable of running that well on top of the game. 

I'm not sure if you're also using Intel IGD for your graphics processing, but with your processor speed being very close to mine, I thought this might be worth mentioning.

**Comment by Badore90** [comment]
My PC is a 2.16ghz dual core with 4gb ram and integrated GPU. 

Enabling Re-Shade the game stutters on FMV and go out of sync in cut-scenes simply 'cause the PC isn't powerfull enough to handle the Re-Shade anti-aliasing solutions. Just disable them both the problem is solved.

It's weird to see that problem on a PC capable to run the game at 60 fps. Wich GPU model do you have??

**Comment by Polymega** [comment]
Thanks for confirming this. 

The base game--even with the SH2 Enhancement module project on top of it--isn't very demanding. It's ReShade that requires the extra power. And as you and I noted, integrated graphics (at least at this time) struggle with it.

**Comment by Badore90** [comment]
...Just tried the game at 60fps for the first time: completely disabling Re-Shade and the noise filter the game actually hit 60fps in some places (35fps max enabling Re-Shade but only with the 2 color related options).

I'd never thought it to be possible, since with the game capped at 30fps it is quite unstable.
In some places I used to get 19fps, and now setting 60fps in the .ini I get 30fps...

I'll test it more carefully.

**Comment by Badore90** [comment]
Nah, just a little difference once in a while (maybe 'cause capping at 60 the pc have more room for buffering or so), with Re-Shade completely off my PC is capable to run the game at 30fps almost without drops.

Side note: playing SH2 at 60fps is awesome. When on map/menù screens it seems to me to be playing the Xbox version :D  ...Btw on normal gameplay Xbox version too was capped at 30fps (even if to my eyes the Xbox version always appears a little smoother than the Ps2...).

**Comment by Polymega** [comment]
> Side note: playing SH2 at 60fps is awesome. 

Just be aware that [there are noted issues playing the game at 60 FPS](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28). This is because the game was only ever designed to be played at 30 FPS. 

> When on map/menù screens it seems to me to be playing the Xbox version :D

The creator of the 'FMV Enhancement Pack' has expressed interest in making a "version 2" of his work, but only if the videos can be played back at 60 FPS this time. We tried experimenting with changing the game's FPS dynamically between 30 and 60 (30 for gameplay and 60 for the FMVs). Unfortunately it doesn't behave well. 

All this is to say that if we ever figure out a way to make that work, it should then be easy to switch the game to 60 FPS while in the menus, too--just like what the Xbox version does for silky-smooth menu navigation.

**Comment by Badore90** [comment]
> Just be aware that there are noted issues playing the game at 60 FPS. This is because the game was only ever designed to be played at 30 FPS.

Yes I read about it in your installation guide. Btw even disabling Re-Shade my PC hit 60 fps only on internals (and not all the time). 

> The creator of the 'FMV Enhancement Pack' has expressed interest in making a "version 2" of his work, but only if the videos can be played back at 60 FPS this time. We tried experimenting with changing the game's FPS dynamically between 30 and 60 (30 for gameplay and 60 for the FMVs). Unfortunately it doesn't behave well.

So it would be already possible to plat FMVs at 60fps?? How?? You managed to extract/convert the Ps2 FMVs??

> All this is to say that if we ever figure out a way to make that work, it should then be easy to switch the game to 60 FPS while in the menus, too--just like what the Xbox version does for silky-smooth menu navigation.

It would be a nice touch :D

**Comment by Badore90** [comment]
> installed new reshade package and the NA executable and turned of SMAA, has seemed to fix most of my problems. Thanks again. Still getting slight stuttering when monsters make sounds in the distance though, any recommendations?

Until you'll get a more powerful PC I suggest you to do as I do:
Do not disable Re-Shade entirely. Open the menù (with the Home key) and uncheck both SMAA and HQ4X (this one too is quite heavy). 
Leave DPX and Levels checked. So you'll play with Ps2-like colors and Black/white levels. 
Your PC should be able to handle these features decently.

**Comment by kingrulerCA** [comment]
@Badore90 cheers for the advice, recently uninstalled silent hill 2 completely. I will reinstall soon and let you know if it works

**Comment by Polymega** [comment]
> So it would be already possible to play FMVs at 60fps?? How?? You managed to extract/convert the Ps2 FMVs??

We're not sure how yet. Whenever we dynamically change the FPS _while in the game_ between 30 to 60 FPS the game doesn't like that. Until we can find a way to make this work smoothly, we can't utilize 60 FPS FMVs (or menus). 

Once we figure that out, the creator of the original 'FMV Enhancement Pack,' angular_graphics, said he'd make newer versions of his FMV work at 60 FPS.

angular_graphics did a LOT of work on the videos to make them look arguably better than the original PS2 versions. I'd only trust him to make a "version 2.0" of his work if we can ever make the videos play at 60 FPS.

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
