### ISSUE TITLE
Can't Launch ("modupdater" problem?)

### ISSUE THREAD

**Issue by BowHeadshot** [elishacloud/Silent-Hill-2-Enhancements#132]
Upon launching the game, a black screen appears saying: "Compiling (3 effects remaining)... This could take a while. The application could become unresponsive for some time." Sometimes it sayed it was 1 or 4 effects remaining.

Thing is, it stays like that forever and the game just doesn't load. If I go to the d3d8.log file it says:

5616 19:08:39.885 LoadModuleFromResourceToFile Error: "modupdater" module could not be written!
5616 19:08:39.885 LoadModuleFromResourceToFile Error: failed to load "modupdater" module!

Is that problem? Or is it something else? Please help.

**Comment by Polymega** [comment]
Hi @BowHeadshot ,

The "Compiling (3 effects remaining)... This could take a while." message is in regards to ReShade. Try disabling ReShade to see if the game launches for you then. You can quickly do this by setting `d3d8to9 = 0` in the `d3d8.ini` file. 

Let me know if that at least gets the game to launch for you.

**Comment by BowHeadshot** [comment]
> 
> 
> Hi @BowHeadshot ,
> 
> The "Compiling (3 effects remaining)... This could take a while." message is in regards to ReShade. Try disabling ReShade to see if the game launches for you then. You can quickly do this by setting `d3d8to9 = 0` in the `d3d8.ini` file.
> 
> Let me know if that at least gets the game to launch for you.

**Comment by BowHeadshot** [comment]
Nope, now when I launch it it's nothing but a black screen. No text or anything.

**Comment by Polymega** [comment]
Can you attach a copy of your `d3d8.ini` and `d3d8.log` as a reply message here, please?

**Comment by BowHeadshot** [comment]
Yes sir, here's the d3d8.log file:

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3269186/d3d8.log)

And here's the content of the d3d8.ini file: 

[General]
AutoUpdateModule = 1 // Checks for updated versions of the SH2 Enhancement module.
d3d8to9 = 0 // Causes Silent Hill 2 to use DirectX 9.
UseCustomModFolder = 1 // Uses files in the 'sh2e' folder rather than the 'data' folder.
WidescreenFix = 1 // Enables WidescreenFixesPack and sh2proxy module. See options below.
XInputVibration = 1 // Replaces DirectInput based vibration with XInput based vibration.
DPadMovementFix = 1 // Allows movement with D-pad on DirectInput and XInput gamepads.
UseCustomExeStr = 1 // Loads "exe_str.txt" file located in the "sh2e\text" folder as built-in strings. Restores the language selection in the Options menu.
UnlockJapLang = 0 // Unlocks Japanese language in the Options menu. It is recommended to keep this disabled for now, as not all Japanese characters are currently supported.

[GAME FIXES]
CatacombsMeatRoomFix = 1 // Updates the color and lighting of the catacomb meat cold rooms to be more like the PS2.  This update also requires updated 'ps189.map' and 'ps193.map' files.
CemeteryLightingFix = 1 // Prevents saving wrong lighting values in the cemetery, which can corrupt the fog.
ClosetCutsceneFix = 1 // Adjusts visuals during the apartment closet cutscene to resemble the PS2 version.
DisableRedCross = 0 // Disables the low health indicator completely. This option is recommended only if you are using a controller with vibration enabled.
DisableRedCrossInCutScenes = 1 // Hides the low health indicator during in-game cutscenes. Use with FastTransitions = 1 for best results.
EnableSFXAddrHack = 1 // Allows custom SFX files to be used. Required if using the Audio Enhancement Pack.
FixHangOnEsc = 1 // Fixes an issue where the game will hang when Esc is pressed while transition is active.
FixMissingWallChunks = 1 // Fixes an issue on Nvidia graphics cards where wall chunks are missing in some locations.
Fog2DFix = 1 // Fixes an issue on Nvidia graphics cards where the 2D fog is missing.
FogParameterFix = 1 // Adjusts the fog-of-war boundaries for specific areas to fix visual errors.
HalogenLightFix = 1 // Fixes the prison hallway halogen lights.
HospitalChaseFix = 1 // Correctly syncs an attack animation to the rest of the cutscene that plays out during the Hospital chase.
HotelWaterFix = 1 // Restores lighting values for the hotel water.
ImproveStorageSupport = 1 // Allows you to save the game when you have more than 2 TB of free space.
IncreaseDrawDistance = 1 // Increases the front draw distance in certain areas to hide the environment loading in.
LightingTransitionFix = 1 // Makes lighting transition smooth from one light source to another for a few particular areas.
Nemesis2000FogFix = 1 // Enables the Nemesis2000 Fog Fix module. See options below.
NoCDPatch = 1 // Removes the CD checks on some versions of SH2.
PistonRoomFix = 1 // Hides a piston behind a door that should not be seen during a cutscene.
PS2FlashlightBrightness = 1 // Adjusts flashlight brightness to resemble the PS2 version. Reduces flashlight intensity for environments, but keeps enemies and NPCs bright.
PS2StyleNoiseFilter = 1 // Adjusts noise filter to resemble the PS2 version. Use with IncreaseNoiseEffectRes = 512 for best results.
Room312ShadowFix = 1 // Prevents distracting shadow flickering while in Room 312 of the Hotel.
RowboatAnimationFix = 1 // Fixes an issue with rowboat animation if you exit to the menu and reload the game.
WhiteShaderFix = 1 // Fixes an issue on Nvidia graphics cards where certain textures would appear as white when they should be black.

[Plugins]
LoadPlugins = 0 // Loads ASI plugins
LoadFromScriptsOnly = 0 // Loads ASI plugins only from the 'scripts' and 'plugins' folders.

[WINDOWED MODE]
EnableWndMode = 1 // Enables forced windowed mode.
FullscreenWndMode = 1 // Enables fullscreen windowed mode. Requires EnableWndMode = 1.
WndModeBorder = 0 // Enables window border when WndMode is enabled.

// ThirteenAG Silent Hill 2 WidescreenFixesPack
[MAIN]
ResX = 0 // Resolution width, set to 0 to inherently size to your display width.
ResY = 0 // Resolution height, set to 0 to inherently size to your display height.
FMVWidescreenMode = 1 // Cutscenes and movies will display better in widescreen.
FMVWidescreenEnhancementPackCompatibility = 1 // Adds compatibility when using the FMV Enhancement Pack.
Fix2D = 1 // Enable to set 2D images to their original full screen aspect ratio. Disable to stretch the images to fill the screen.

// Some features from https://github.com/emoose/sh2proxy
[MISC]
DisableCutsceneBorders = 1 // Removes cutscene letterboxing.
SingleCoreAffinity = 1 // Limits game to one CPU core to prevent sound loop and other various bugs.
DisableSafeMode = 1 // Prevents the game from using the lowest settings upon relaunch if the game crashes.
FastTransitions = 1 // Increases speed of all transitions.
CreateLocalFix = 1 // For anti-aliasing support.
FPSLimit = 30 // Controls the framerate limit, but may cause bugs if increased.
PS2CameraSpeed = 1 // Changes camera speed to match PS2 version. Use with FPSLimit = 30.
GamepadControlsFix = 1 // Allows the same button to be assigned to multiple actions.
LightingFix = 1 // Fixes a flashlight bug, and restores the fog and lighting conditions for one of the ending cutscenes.
ReduceCutsceneFOV = 1 // Cutscenes will use vert- scaling to hide off-screen characters.
SteamCrashFix = 1 // Prevents a crash when Steam controller configuration is used.
IncreaseNoiseEffectRes = 512 // Use 128 and above to increase noise effect resolution.
FullscreenImages = 1 // Crops letterboxing to fill the screen.

[FONTS]
UseCustomFonts = 1 // Loads 'font000.tga' file located in 'sh2e\font' folder as font texture and "fontwdata.bin" as width data for the first 224 chars.
DisableEnlargedText = 1 // Disables enlarged, floating save/load menu text.
CustomFontCol = 100 // Number of chars in column on font texture.
CustomFontRow = 14 // Number of chars in row on font texture.
CustomFontCharWidth = 20 // Width of single char on font texture.
CustomFontCharHeight = 32 // Height of single char on font texture.
NormalFontWidth = 20 // Width of single char in game.
NormalFontHeight = 30 // Height of single char in game.
SmallFontWidth = 16 // Width of single char in game.
SmallFontHeight = 24 // Height of single char in game.

[XINPUT_VIBRATION]
PadNumber = 0 // XInput pad ID to vibrate.

// Nemesis2000 Fog Fix
[FOG]
fog_custom_on = 1 // 0 - Off, 1 - On
fog_transparency_layer1 = 128 // original value 128
fog_transparency_layer2 = 138 // original value 128
fog_layer1_x1 = 0.250 // original value 0.125
fog_layer1_x2 = 0.250 // original value 0.125
fog_layer1_y1 = 0.250 // original value 0.125
fog_layer1_y2 = 0.250 // original value 0.125
fog_layer2_density_mult = 1.4 // original value 1.0
fog_layer2_density_add = 100.0 // original value 0.0
fog_layer2_complexity = 0.066406 // original value 0.048828

// Update settings for modupdater
[MISC]
SelfUpdate = 0

[MODS]
d3d8.dll = https://github.com/elishacloud/Silent-Hill-2-Enhancements

[d3d8.dll]
PlaceToRoot

**Comment by Polymega** [comment]
If I were to guess, the window for the modupdater is being hidden behind the game upon game launch and maybe it's leaving you stuck there until you determine what update choices you want to make via that window screen?

Try setting `AutoUpdateModule = 0` in the `d3d8.ini` file and seeing if the game will launch for you then. Maybe also ensure there isn't another instance of the modupdater running that could be causing this issue. You can open your Task Manager to see if another copy of modupdater is still open.

**Comment by BowHeadshot** [comment]
No, it's still the same. By the way, launching the game also completely slows down my PC by 50% and to just close the aplication I'm forced to use task manager.

**Comment by Polymega** [comment]
Hmm... I'm not sure on this one then. I'll tag @elishacloud, our lead programmer, to see what he says.

In the meantime, can you try two more things for me?

- Temporarily **remove** `dsound.dll` and `dsound.ini` from the game's directory and see if it'll launch then. 
- Download the [DirectX 9 SDK](https://www.microsoft.com/download/details.aspx?id=35) and [Microsoft C++ 2010 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=5555) to see if that will allow the game to launch for you.

**Comment by BowHeadshot** [comment]
Hello, removing both dsound.dll and dsound.ini actually worked, now it lets me play the game and at first glance it seems like the enhancements work fine but I didn't play very far. 

What do you think the problem could have been then? Removing dsound.dll and dsound.ini could result in a problem or I can confortably play the whole game without them?

**Comment by Polymega** [comment]
Removing those files removed IndirectSound which helps with audio issues in the game. 

It sounds like you need to install the C++ 2010 library, as IndirectSound was built off of and requires that library in your computer to run. 

Try downloading that package, then place those files back in the game's directory, and try launching the game again.

**Comment by BowHeadshot** [comment]
I downloaded that DirectX 9 file you gave me and now I can play the game just fine. Some of the assets seem to not work (like the flashlight effect) but nothing special, I can live without them. 

Thank you so much for your help and attention, you've all made an excellent job with this remaster and I'm so happy to finally play SH2 in such a high level of quality. Keep up the great work.

**Comment by Polymega** [comment]
Great! Glad things are working for you now. 

> Some of the assets seem to not work (like the flashlight effect) but nothing special, I can live without them.

Ensure they are enabled in the Options > Advanced Options menu. For that one in particular, you'll want to enable the lens flare. Also ensure things like high res textures, dynamic shadows, complex fog, and advanced filters are all turned on.

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
