### ISSUE TITLE
Possible fix for the rotating Lying Figures under vehicles

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#133]
**ISSUE:** When triggering Lying Figures that are hiding under vehicles, they will do an odd 180 vertical rotation as they exit the vehicle which looks wrong/funny:

![Lying Figure Van - Upside Down](https://user-images.githubusercontent.com/27395260/59175384-5c4a4c00-8b23-11e9-9786-bf489ec3a95c.png)

This will need to be looked into more by more competent people, because I'm uncertain what my changes mean in a programming/coding sense, but I believe changing any of these instruction lines will fix the problem. It needs to be checked by more competent folks because I'm not sure what else the instruction(s) here may affect. I'm not sure how to determine if they affect anything else or not. 

Address | Opcode | Opcode Changed To
-- | -- | --
sh2pc.exe+C5C42 | [esi+10],ecx | [esi+06],ecx
-OR- |   |  | 
sh2pc.exe+C5C45 | byte ptr [esi+06],00 | byte ptr [esi+10],00
-OR- |   |  | 
sh2pc.exe+C5C49 | mov [esi+03],al | mov [esi+10],al

Video example of the change in effect: https://youtu.be/1ZX-l7EUbAE

From my quick tests, the Lying Figure's behavior seems the same as normal elsewhere. I can do a more thorough play test of the entire game with this change, but again, this needs to be double-checked by a smarter person, please.

(Incidentally, this also happens in the Xbox version.)

Possible fix name:
```
; Fixes an issue where creatures would erratically exit from underneath a vehicle.
FixCreatureVehicleSpawn = 1
```

**Comment by Polymega** [comment]
Thank you to Aero_ for reviewing the proposed fix solution. Let's please try nop'ing the following instruction found at `004C5C42` first:

`mov [esi+10],ecx`

This can be set on game launch.

**Comment by Polymega** [comment]
Hi Elisha, 

Using the current test build I get an immediate crash upon game launch. I tried disabling `Fix2D` and/or `FixDrawingTextLine` but with no success. Attached is the log file: 

```
8812 14:06:03.075 Starting Silent Hill 2 Enhancements! v1.3.1396.0
8812 14:06:03.075 ASUSTeK COMPUTER INC. MAXIMUS V GENE Rev 1.xx (Desktop)
8812 14:06:03.091 "NVIDIA GeForce GTX 670"
8812 14:06:03.091 Windows 7 64-bit (6.1.7601) Service Pack 1
8812 14:06:03.091 "sh2pc.exe" (PID:5888)
8812 14:06:03.091 Running from: "C:\Program Files (x86)\KONAMI\Silent Hill 2\sh2pc.exe"
8812 14:06:03.091 Config file: "C:\Program Files (x86)\KONAMI\Silent Hill 2\d3d8.ini"
8812 14:06:03.091 Loading as dll: "d3d8.dll"
8812 14:06:03.091 Wrapper created for "d3d8.dll"
8812 14:06:03.156 Hooking the FileSystem APIs...
```

...and Windows error: 

```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	sh2pc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	3d93137b
  Fault Module Name:	kernel32.dll
  Fault Module Version:	6.1.7601.24475
  Fault Module Timestamp:	5cdd8010
  Exception Offset:	0002cff4
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	4c0d
  Additional Information 2:	4c0d4d78887f76d971d5d00f1f20a433
  Additional Information 3:	4c0d
  Additional Information 4:	4c0d4d78887f76d971d5d00f1f20a433
```

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	sh2pc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	3d93137b
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24475
  Fault Module Timestamp:	5cdd7f6d
  Exception Code:	c0000005
  Exception Offset:	0004ebab
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	1855
  Additional Information 2:	1855b9125e127baefef515c5f5f52fa4
  Additional Information 3:	05f2
  Additional Information 4:	05f2f532d60977a12e01abb272ecf1a7
```

**Comment by elishacloud** [comment]
Weird.  It works fine on my computer.  I tried all three versions of the binary.  I don't think it is related to this fix.  Something else is making it crash.  Maybe it is the project setting changes.

Try this one:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3602745/d3d8.zip)

Also try disabling both `UseCustomFonts` and `FixDrawingTextLine` options.  This should fully disable the code to the new check-in.

**Comment by Polymega** [comment]
Still no luck. :-/

For build 1.3.1396 I disabled a slew of things in the INI file and nothing allowed me to launch it. Looks to be the same with the test build you just provided above as well.

I also tested the current public release, along with a few previous test builds (such as when we first implemented soft shadows, etc) and they all boot up fine.

**Comment by AeroWidescreen** [comment]
I just tested the build Elisha attached above and it works fine for me.

> 
> 328 14:58:32.887 Starting Silent Hill 2 Enhancements! v1.3.1396.0
> 328 14:58:32.887 "Radeon RX 580 Series"
> 328 14:58:32.888 Windows 10 64-bit (10.0.18362) 
> 328 14:58:32.888 "sh2pc.exe" (PID:1316)

**Comment by Polymega** [comment]
Thanks. This is probably definitely an isolated thing with me again. I'm trying to think of all the possible reasons why I'm getting the crash. 

Before it was using an updated `\sh2e\text\exe_str.txt` that caused the issues before Belek's fork was committed. I removed that from the equation and still no luck.

I disabled your post-processing SFX ASI plugin on the random off-chance that would cause issues even with 1.0 EXE and still no luck. 

It might be an OS thing on my side?

**Comment by elishacloud** [comment]
@Polymega, it looks like it crashes when hooking the APIs.  Can you try disabling the following items:
* Nemesis2000FogFix
* WidescreenFix
* UseCustomModFolder
* DisableGameUX

**Comment by Polymega** [comment]
Yep, it launched when I disabled all four of those things. It also crashed whenever I enabled even just one of those things.

**Comment by elishacloud** [comment]
Ok, try it with this one: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3602950/d3d8.zip)

**Comment by Polymega** [comment]
Thank you sir; that one launches!

**Comment by elishacloud** [comment]
Looks like my [last check-in](https://github.com/elishacloud/Hooking/commit/104473c99ab58510231841c6706f42b189ed90b2) for the hooking module was bad.  I will revert that check-in and create another testing build with this fix in it soon.

**Comment by elishacloud** [comment]
OK, try this one.  This should fix the Lying Figures issue.  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3603214/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha, this worked great and `FixCreatureVehicleSpawn` worked across all three binaries.
