### ISSUE TITLE
Controllers Not Working

### ISSUE THREAD

**Issue by GareldField** [elishacloud/Silent-Hill-2-Enhancements#136]
None of my controllers will work. I've tested my Dualshock 4 with native controls and Xinput from DS4Windows, a Nintendo Switch GameCube controller, and a Logitech F310 and none of them will work in Silent Hill 2. I've tested them in other games and they work as intended.

**Comment by GareldField** [comment]
Nevermind. I was able to get my controllers to work.

**Comment by Polymega** [comment]
Hi @GareldField ,
I'm glad you were able to figure out the controller issue. Would you mind sharing how you fixed it, as it could help us troubleshoot future users with the same/similar issue?

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.

**Comment by GareldField** [comment]
Sorry. I wasn't able to respond earlier. I don't know what exactly I did to get controllers to work. I added the game as a Steam shortcut and then controllers just started to work. Controllers won't work if I don't play the game through the Steam shortcut though. Something about Xinput Plus maybe.
