### ISSUE TITLE
Unable to load sh2-enhce.asi Error: 126

### ISSUE THREAD

**Issue by ambystona** [elishacloud/Silent-Hill-2-Enhancements#14]
I recently installed your SH2 audio mod, but when launching the game it gives me this error: "Unable to load sh2-enhce.asi Error: 126" then the game starts but it soon after freezes, showing a japanese text saying "there's a problem with your disk. The disc may be dirt or it may be damaged.". I didn't touch nor the sh2-enhce.ini nor the .asi file. I've installed the FMV upgrades, the fog fix, the widescreen fix, the indirect sound and WineD3D and obviously the Audio Enhancement mod.
https://imgur.com/a/FDj1J46 (sorry for the bad quality, they were taken in a rush.)

**Comment by Polymega** [comment]
Hi @ambystona can you also share a snapshot of your game's installation directory and your /scripts/ folder?

**Comment by ambystona** [comment]
https://imgur.com/a/kgLdJrX 
I followed the instructions on http://enhanced.townofsilenthill.com/SH2/ so it's pretty strange that it gives me an error.

**Comment by Polymega** [comment]
Hmm, yeah, your files look good. 

I noticed yesterday that [PC Gaming Wiki](https://pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut) was linking and telling people to use a test module for an upcoming [SH2 Enhancements](https://github.com/elishacloud/Silent-Hill-2-Enhancements) update that shouldn't be released to the public yet. (I've reverted that Wiki page back for the time being.) To be sure: You didn't download any files from that site, yes? 

> I recently installed your SH2 audio mod, but when launching the game it gives me this error: "Unable to load sh2-enhce.asi Error: 126"

So to confirm: The other fix packages were working before you implemented the SH2 audio mod? Also, in the `sh2-enhce.ini` file `EnableSFXAddrHack `is set to `1`?

**Comment by ambystona** [comment]
Well the only files I downloaded were from http://enhanced.townofsilenthill.com/SH2/ ,so I didn't download anything from PC Gaming Wiki.

The other fixes worked, except WineD3D which gives me some troubles, the version 1.7.etc works fine with the cutscene, but if I'm using the flashlight and there's an enemy towards me it's totally black. I didn't tried the other version though. But if I don't use it the cutscenes are light blue-esque tinted (basically unwatchable), but the flashlight works fine.
Yes the EnableSFXAddrHack is set to 1, as default.

**Comment by Polymega** [comment]
Ah, someone else had a similar problem many, many months back with enemies being black when the flashlight turned on. I'll try and find that post but I can't remember where it was at (I want to say on the Silent Hill subreddit?). Off the top of my head though I want to say they re-did the entire installation process and it fixed things for them. 

So cutscenes without using WineD3D are blue tinted and practically unwatchable? That's odd. As far as we know so far, FMV issues like that are associated with integrated graphics. What graphics card are you using? 

Also, download the attached files below. Make a backup of your files first and replace them with the attached: 
[2018-07-09_SH2_WSF.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2176292/2018-07-09_SH2_WSF.zip)

Does that fix any of the issues?

**Comment by ambystona** [comment]
I'm using a Intel HD Graphics 620, so I think the blue tinted FMV are a graphics fault. 

> I'll try and find that post but I can't remember where it was at (I want to say on the Silent Hill subreddit?).
Thanks very much if you can find the exact thread! I tried to reinstall it multiple time, but I doesn't fix.

> Does that fix any of the issues?
Nope, the shadows are still black using WineD3D and the audio mod won't start.

**Comment by Polymega** [comment]
> I'm using a Intel HD Graphics 620

Ah. First I'd recommend removing WineD3D and its associated files: 

```
d3d9.dll
libewine.dll
wined3d.dll
```

This is because WineD3D is fairly resource heavy and integrated graphics don't run well when using WineD3D. (Plus, WineD3D is really only beneficial for people who are using Nvidia cards.) For example: On my Surface laptop (which also uses integrated graphics) the game won't even boot up while also using WineD3D.  

Now, in regards to your FMVs being blue-tinted once removing the WineD3D files: We found a similar problem with this (while using integrated graphics) sometime back... [but the FMVs were completely red](https://github.com/crosire/d3d8to9/issues/42#issue-252455438). However, that issue [was resolved](https://github.com/crosire/d3d8to9/pull/77#issue-185624992) by Elisha sometime after. 

Did you recently receive an update notification from the WSF package when you started the game? I know [ThirteenAG recently updated it](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/12#issuecomment-403397102) with the improved D3D8to9 converter that fixes the red-tinted FMVs.

**Comment by ambystona** [comment]
<Did you recently receive an update notification from the WSF package when you started the game? I know ThirteenAG recently updated it with the improved D3D8to9 converter that fixes the red-tinted FMVs.

Well, I received an update some months ago (January/February) but then I changed PC and OS so the game was deleted and installed multiple times. Until now (I reinstalled it yesterday) it doesn't give me any update message, so should it be the last version? I'll try to run it with admin privileges, but the games is in a local directory, so I don't think it's the issue.

**Comment by Polymega** [comment]
> but if I use the modded audio files the game freezes upon launching. 

It seems as though `sh2-enhce.asi` is not running at all for you then. If your game freezes when using the custom sound files that's indicative of the mod not working as the game would naturally freeze using any modified sound files without any mods. 

If you're able to wait some time (hopefully within the next few weeks) there will be an all-new method to installing all of these mod fixes and hopefully that'll also fix your problems as well. But perhaps @elishacloud may be able to think of a solution for you in the meantime.

**Comment by elishacloud** [comment]
Interesting.  I just tested on my laptop and the game hangs when IndirectSound is enabled.  I am getting the following errors:

```text
Failed to create the XAudio2 interface
Failed to load the XAudio2 Library
The new instance of IDirectSound8 didn't successfully initialize
```

@ambystona, try removing the IndirectSound files and disabling `d3d8to9`.  Also can you send me the log files for sh2-enhce and IndirectSound?

**Comment by Polymega** [comment]
To further add to the confusion:

The new IndirectSound works on my Windows 10 laptop. 
On my laptop I am **not** using WineD3D, LoadWineD3D, or the custom sound files. 
I **am** using WSF, global.ini (d3d8to9), SH2 Enhance ASI, and Xinput Plus files.

**Comment by elishacloud** [comment]
@ambystona, I just remembered that sh2-enhce requires [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685).  I will remove this requirement later.  But you may want to make sure you have this installed.

**Comment by ambystona** [comment]
As @elishacloud I installed C++ 2015 and the game doesn't freeze upon launching. I've installed 2010 before because the game doesn't even start with the Microsoft Visual C++ libraries, but I didn't see if there are any audio glitch.

sh2-enhce log:
`21:27:11.778 Starting Silent Hill 2 Enhancement ASI!
21:27:11.779 Reading config file:  C:\Users\user\Desktop\Silent Hill 2\scripts\sh2-enhce.ini
21:27:11.916 Could not find CD check function address in memory!
21:27:11.925 Found SFX pointer address at: 008A67DC
21:27:11.925 Opening C:\Users\user\Desktop\Silent Hill 2\data\sound\sddata.bin
21:27:12.575 Found all WAV file indexes in sddata.bin
21:27:12.575 Updating SFX memory addresses
21:27:12.773 Found sddata.bin pointer at address: 00515163
21:27:12.773 Updating sddata.bin pointer memory addresses
21:27:21.204 Unloading ASI!
`

IndirectSound log:
https://pastebin.com/tqJPj1J8

**Comment by elishacloud** [comment]
@ambystona,  Thanks for the log files.  Everything looks good in the log files.

> I installed C++ 2015 and the game doesn't freeze upon launching.

Is everything working correctly now?

> I've installed 2010 before because the game doesn't even start with the Microsoft Visual C++ libraries

Yes, this project requires 2015.  Installing 2010 won't help.  Later I will remove this requirement.

**Comment by ambystona** [comment]
> Is everything working correctly now?

Now it works! I played until the first Pyramid Head battle and it works fine.

**Comment by elishacloud** [comment]
Great!  Then I am going to close this.  You can reopen or open a new issue if you have any other problem.
