### ISSUE TITLE
Pull request fix for ThirteenAG & SH2 PC WSF

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#143]
Hi @elishacloud,

May I ask your consideration in helping to improve a fix over at ThirteenAG's WSF side via pull request? ThirteenAG has been completely swamped with work on other titles for the past months and work there doesn't seem to be letting up. 

**The fix in question would be:** 
When cutscene ID is `00000019` (Eddie & Laura bowling cutscene) **disable** `Fix2D` & `FullscreenImages` fixes if they are enabled. Restore these fixes upon cutscene ID end if they were originally enabled.

**An explanation for this fix request:** 
The game uses a solid black image to fade out the end of this cutscene early. Why the developers did this? No clue. But if `Fix2D`/`FullscreenImages` is enabled this solid black image is also affected by these fixes which results in this: https://youtu.be/yO6QknrItqc?t=3581

Notice how that black fade image doesn't stretch to fill the screen (it stays at 4:3) so you still see sides of the game world on each end. 

If we disabled `Fix2D` and `FullscreenImages` that solid black image will stretch to fill the whole screen and all will look good.

Aero_ and I were convinced we could simply edit the size/dimensions of this image, similar in spirit to how we'll approach the "Fullscreen Image Enhancement Pack" project. We both searched high and low but could not find a dedicated image file for this source. 

Aero_ eventually traced the image back to a DDS file. Looking at this file in a hex editor it's completely foreign-looking. Basically it looks like a custom DDS file specifically made for the game/game engine and we have no clue how to decipher it. 

Our GitHub project friend **lakeviewhotel** also extracted this same DDS file from the console-released **HD Collection** [and the data within (when looking at it through a hex editor) is identical to the PC version](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/48#issuecomment-490622405). This tells me that the developers for the HD Collection did **not** edit this file to make it fill the screen. Perhaps they used a similar approach to have it fill the screen as the fix requested here.

**Comment by AeroWidescreen** [comment]
Actually, now that I think about it, only `Fix2D` would need to be disabled during this cutscene. FullscreenImages should have absolutely no effect, because if it did then this wouldn't be a problem in the first place. 😛

**Comment by elishacloud** [comment]
@Polymega, I can take a look at this but I am not sure about updating the code in the widescreen fix project.  There is a lot of stuff in that code I don't understand.  I would need some time to review it.  What if we just stretch the solid black image to fill the whole screen rather than disabling `Fix2D` and `FullscreenImages`?

The main reason I am asking about that is because I don't think it is possible to disable `Fix2D` or `FullscreenImages` while the game is running.  I believe those options are set at launch and used by Direct3D8.  Changing them might require re-initializing Direct3D8 in the middle of the game, which would be difficult.

What's the best way for me to test this?

**Comment by Polymega** [comment]
> What if we just stretch the solid black image to fill the whole screen rather than disabling `Fix2D` and `FullscreenImages`?

The issue Aero_ and I had, as mentioned above, is we're not sure how to do that while `Fix2D` and `FullscreenImages` is active. :-/ 

> I believe those options are set at launch and used by Direct3D8. Changing them might require re-initializing Direct3D8 in the middle of the game, which would be difficult.

Very true. I wasn't sure if that cutscene and/or any images called/contained during that cutscene could be excluded/blacklisted at launch with a revised `Fix2D`/`FullscreenImages` fix. But that may definitely not be the best way to go about it, either.

> What's the best way for me to test this?

Attached is a save file right before this cutscene plays out. Like before, backup and/or remove your `\Silent Hill 2\data\save\Folder 01\` folder and replace it with this one: [Folder 01.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3365364/Folder.01.zip)

Be sure `Fix2D` and `FullscreenImages` are enabled for testing. [As a refresher, here is how it incorrectly looks when those two fixes are enabled.](https://youtu.be/yO6QknrItqc?t=3581)

Launch the game, load the Quick Save save file, and enter the door directly in front of you to start the cutscene. Afterwards, you can always press F9 to reload that Quick Save point.

Thank you sir.

**Comment by AeroWidescreen** [comment]
@elishacloud If it's too much trouble then  we'll see what ThirteenAG can do. I was trying to save us some time because he's been busy lately and I don't know how soon he'll be able to get this done, however, [he has recently offered to help](https://github.com/ThirteenAG/WidescreenFixesPack/pull/688#issuecomment-508399141) so we'll see what he says about this.

**Comment by elishacloud** [comment]
Ok, thanks!  I'll wait and see if ThirteenAG can fix this first.  If not I will check it out.

**Comment by AeroWidescreen** [comment]
@elishacloud ThirteenAG has kindly completed our request and has uploaded a stable build for us to use. https://github.com/ThirteenAG/WidescreenFixesPack/releases/download/sh2/SilentHill2.WidescreenFix.zip

Feel free to update the module with this whenever you can.

**Comment by elishacloud** [comment]
I updated the WidescreenFix module.  It will be included in the next build.  I believe this issue can be closed now.
