### ISSUE TITLE
Music crossfade

### ISSUE THREAD

**Issue by umbrellacorp53** [elishacloud/Silent-Hill-2-Enhancements#149]
Is there any way to restore the overlapping/crossfade transition to the music in the game? One thing I've noticed in the native PS2 version is that the music seamlessly flows and overlaps slightly in some places, but on the PC version even with the restored quality, the music fades out to silence, then the next track fades in, this for me, especially in the intro as James is leaving the restroom and we're first introduced to the lake, is a big atmosphere killer. It sounds like someone has "decided to play the next track" instead of it being an evolving, living breathing soundscape as it was originally intended.

Edit: 
PS2: [Original transition](https://youtu.be/MfJ3ix4yjc0?t=67)
SH2PC: [PC fade out, then in](https://youtu.be/jNGWutc4rOQ?t=61)

I know it's a bit nitpicky, but for me the difference while playing is pretty dramatic.

**Comment by Polymega** [comment]
The PC version cross fades most BGM tracks. For the bathroom-to-observation deck transition that does seem to be an exception. In fact, the PCSX2 version also experiences this behavior but even worse: 

https://youtu.be/mIvT7AM4r7w

In the video, the first one is PCSX2, then PC.

I don't think anything can be done about this. The PC version is a port of the Xbox version. The Xbox version was also done by Team Silent. While I don't think Team Silent purposefully changed this part of the BGM transition, we're at the mercy for some of the technological changes from PS2 to Xbox.

**Comment by umbrellacorp53** [comment]
Thanks for the quick response. I have several other things I've noticed but I don't want to create a new issue for each one. 

1. Menu text is stacking![sh2pc 2019-07-11 11-53-02](https://user-images.githubusercontent.com/52713938/61076231-5923d380-a3e1-11e9-9323-809ea49b63bc.png)

2. Xbox 360 controller is not recognized. I installed Xinput as directed and have no 3rd party software installed that should interfere with the controller. I am able to use it in other games. I saw someone else having a similar issue but they launched the game through steam big picture and that solved the problem, this did not fix it for me.

**Comment by Polymega** [comment]
> Menu text is stacking

This is correct behavior. It signifies what selection you're on. Notice it does it in other areas such as the Options menu, too. 

> Xbox 360 controller is not recognized.

I'm not sure how to troubleshoot this beyond what's listed on the troubleshooting table on the installation guide. Sorry. 

> The 'Brightness' slider does not seem to affect the brightness of the game, the only effect it has is making the film grain more or less pronounced.

Yes, this is explained on the [troubleshooting table](http://enhanced.townofsilenthill.com/SH2/#troubleshooting) of the installation guide: 

Issue | Recommendation
-- | -- 
The brightness adjuster in the game's options menu isn't working. | The in-game brightness adjuster only works when playing in fullscreen mode. Set `EnableWndMode = to 0` in the d3d8.ini file to play the game in fullscreen mode. Keep the brightness level at 3 (default) for the most accurate respresentation of the noise grain filter.

**Comment by Polymega** [comment]
Do you have more than one gamepad device connected and/or plugged into your PC? Such as a bluetooth connected peripheral as well?

**Comment by umbrellacorp53** [comment]
I had a dongle for a 2.4ghz wireless keyboard plugged in so I can control my PC from the couch. Unplugging this dongle seems to have solved the issue. **Thank you**. This should have been a fairly obvious troubleshooting step but I've been spoiled by how modern games are almost sentient when it comes to what peripherals it's supposed to use.

I confirmed the stacking text is as intended by loading up the pcsx2 in software mode. Probably should have done that first as well. It just looked weird, as if the text behind should have disappeared. Wrong on my part.

I thought I had disabled fullscreen window by setting FullscreenWndMode = 0, but I missed the line you mentioned above. Thank you.

As far as the music fading goes, I can live without it. I ran it in PCSX2 and it smoothly transitioned the first few times, but after testing it again there was a nearly 10 second gap, like in the video you posted.

Anyway thanks for the hands on troubleshooting. I'll go ahead and close this one. It may be basic stuff but someone as inept as me may find this useful! Lol

**Comment by umbrellacorp53** [comment]
I had a dongle for a 2.4ghz wireless keyboard plugged in so I can control my PC from the couch. Unplugging this dongle seems to have solved the issue. **Thank you**. This should have been a fairly obvious troubleshooting step but I've been spoiled by how modern games are almost sentient when it comes to what peripherals it's supposed to use.

I confirmed the stacking text is as intended by loading up the pcsx2 in software mode. Probably should have done that first as well. It just looked weird, as if the text behind should have disappeared. Wrong on my part.

I thought I had disabled fullscreen window by setting FullscreenWndMode = 0, but I missed the line you mentioned above. Thank you.

As far as the music fading goes, I can live without it. I ran it in PCSX2 and it smoothly transitioned the first few times, but after testing it again there was a nearly 10 second gap, like in the video you posted.

Anyway thanks for the hands on troubleshooting. I'll go ahead and close this one. It may be basic stuff but someone as inept as me may find this useful! Lol

**Comment by Polymega** [comment]
> This should have been a fairly obvious troubleshooting step but I've been spoiled by how modern games are almost sentient when it comes to what peripherals it's supposed to use.

And thank you for understanding that this is just how old PC games did things. :) Someone else may have jumped down our necks over this, being unaware just how primitive/different PC gaming used to be in the late 90s/early 2000s. 

I'll add this recommendation to the troubleshooting guide as it's something I wasn't aware of at the time and would be good to add to help others in your predicament.

> I thought I had disabled fullscreen window by setting FullscreenWndMode = 0, but I missed the line you mentioned above. 

Yeah, `FullscreenWndMode `is reliant on `EnableWndMode` being enabled. `FullscreenWndMode` keeps the game in windowed mode but takes up the whole space of your screen. If your game resolution is different than your display's resolution, `FullscreenWndMode` will blacken out the difference in space for a nicer presentation. 

You can also disable `FullscreenWndMode` and just leave `EnableWndMode` on, but if you play at a different resolution than your monitor doing it this way, you'll still see all other windows/desktop/etc in the spaces between the game windows and your display's real estate. I hope that made sense. 

> As far as the music fading goes, I can live without it. I ran it in PCSX2 and it smoothly transitioned the first few times, but after testing it again there was a nearly 10 second gap, like in the video you posted.

Yeah, believe me when I said we did _a lot_ to bring the audio back up to snuff. The audio enhancement project to Elisha and I nearly a year to complete due to being as meticulous as we could within the technological boundaries we were given! 

>  It may be basic stuff but someone as inept as me may find this useful! Lol

Definitely! I'll add that controller troubleshoot step to the guide soon. :)

**Comment by elishacloud** [comment]
> I had a dongle for a 2.4ghz wireless keyboard plugged in so I can control my PC from the couch. Unplugging this dongle seems to have solved the issue.

Keep in mind that there is an option in the d3d8.ini file for this called `PadNumber`.  You may need to switch the pad number if you have more than one gamepad plugged in.

I beleive it works this way:
* `PadNumber = 0`  Is the first gamepad listed in Windows.
* `PadNumber = 1`  Is the second gamepad listed in Windows.
* `PadNumber = 2`  Is the third gamepad listed in Windows.
* `PadNumber = 3`  Is the fourth gamepad listed in Windows.
* Etc.

Also keep in mind that some gamepads show up as more than one pad in Windows and the second pad may be the one you need to use.  In that case you may only have one gamepad installed but you will still set this to `PadNumber = 1`.

Anyways you can have more than one pad plugged in so long as you tell Silent Hill 2 which pad to use.

**Comment by Polymega** [comment]
Great to know. I was going to suggest this but wasn't sure if `PadNumber` only assigned vibration to a pad for the game, or if it assigned a whole new pad to the game.

**Comment by elishacloud** [comment]
> I was going to suggest this but wasn't sure if `PadNumber` only assigned vibration to a pad for the game, or if it assigned a whole new pad to the game.

Interesting.  I did not think about that.  I am not in a place I can test this, but looking at the code this option does appear to only affect the vibration setting.
