### ISSUE TITLE
Add one room to HotelWaterFix

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#151]
[Please add 0x85 to this line.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/HotelWater.cpp#L197)

Thank you.

**Comment by elishacloud** [comment]
Done!  This will be in the next update.  Attached for testing module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3439794/d3d8.zip)

**Comment by Polymega** [comment]
All is good across all binaries here; thanks!
