### ISSUE TITLE
Save game faulty.

### ISSUE THREAD

**Issue by Erginol** [elishacloud/Silent-Hill-2-Enhancements#157]
Saved the game in the elevator just before labyrinth and upon loading I cannot leave the elevator at all and now my only savegame is borked. Any way to fix?

**Comment by Polymega** [comment]
Hi @Erginol,

I tried replicating this bug but to no success. Upon entering the elevator, did you save your game before or after the elevator completed its journey from top to bottom? 

When you load the game the elevator door is still closed, preventing you from leaving? Or is it something different?

If it helps, here is a ZIP package that contains save points throughout the entire game. You can load the save point labeled "Elevator" to bring you back to your old spot. The saves are on Beginner/Easy. Do note that if you use the save files below, it will overwrite your current save files:

Go to `KONAMI\Silent Hill 2\data\save\Folder 01\` and delete any files within this folder. Download the package below and place the files in your `Folder 01` folder: [Folder 01.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3390607/Folder.01.zip)

If you can provide more details of when/where within this room you saved your game it can help me to try and replicate the bug. 

Thanks

**Comment by Erginol** [comment]
Hey,

Here is the save in question.
I saved as the elevator arrived to the bottom and was not aware that there was a save point right after. The doors opened normally and I did face the issue only after loading the current file.

Thank you for the files and quick answer.
[sh2pcsave00.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3391508/sh2pcsave00.zip)

**Comment by Polymega** [comment]
Thanks @Erginol. In order for me to check out that save file I'll need the `.dat` file you already provided, along with the original `SaveImage.pcv` and `sh2pc.sys` files that were linked to that `.dat` file.

**Comment by Erginol** [comment]
Hey,

Here is the whole package.
[Folder 01 backup.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3393923/Folder.01.backup.zip)

**Comment by Polymega** [comment]
Thank you, that worked. I was able to replicate this bug now. If you save your game the literal second the elevator stops moving (when the game unlocks the ability for you to save again) this will happen: https://youtu.be/-ujurU3FLdI

I put in a request to hopefully prevent this game-breaking save bug from happening again [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/118). 

Thanks for finding this for us and sorry you had to go through it!
