### ISSUE TITLE
Resolution Freeze

### ISSUE THREAD

**Issue by KatoSoul** [elishacloud/Silent-Hill-2-Enhancements#158]
Please excuse me if this is a quick fix, I know nothing of programming. 
Whenever I start the game its in Full screen mode only, and if I click on resolution it freezes. I would like for it to be bordered and at a different resolution. 
Am I missing something or making a mistake?

**Comment by Polymega** [comment]
Hi @KatoSoul,

You will now change the resolution in the `d3d8.ini` file by adjusting `ResX` and `ResY`.

In a future update, we will prevent users from trying to change the game's resolution through the in-game options menu, as you no longer do it that way.

You can also disable `FullscreenWndMode` to play the game in windowed mode but without it making the surrounding areas of your monitor black.

**Comment by KatoSoul** [comment]
Fantastic! Thank you so much for this. 

SH2 holds a very special place in my heart, and I am eternally grateful for the hard work you've all done to keep this iconic game alive.

**Comment by Polymega** [comment]
Thank you for your kind words. :)

> In a future update, we will prevent users from trying to change the game's resolution through the in-game options menu, as you no longer do it that way.

Here's what that update will look like, for future reference. It will also display the true resolution you are using as well: https://twitter.com/WhereAllBegins/status/1142898738597421059

**Comment by KatoSoul** [comment]
OMG Thats amazing. Blows my mind how you all do what you do.
