### ISSUE TITLE
Any chance of Downsampling?

### ISSUE THREAD

**Issue by umbrellacorp53** [elishacloud/Silent-Hill-2-Enhancements#159]
I'd love to run the game in 1444p or 4k on my 1080p monitor. As of now if the resolution doesn't match my screen it won't launch. Any way around this? Maybe through GeForce Experience app?

**Comment by umbrellacorp53** [comment]
Side note: would the team be interested in some high res textures for some of the worst offenders? I understand the driving desire of keeping the vanilla look and feel as much as possible but on the original ps2 version the lower resolution and crt screens hid most of the texture flaws.

Does the engine have a file size or texture resolution cap in place?

**Comment by Polymega** [comment]
The memory space for textures is hard-coded into the game's binary, from what I remember (Elisha can clarify this if I'm off). We will work on increasing this space for when we work on the [Fullscreen Image Enhancement Pack](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/48) project, but have no plans on modding the game to rework any of the in-game textures at this moment. An explanation for that can be found [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/48#issuecomment-492808605). 

Work on upscaling the fullscreen images is postponed for now, as we will be putting full concentration on soft/self shadows in the upcoming future first. 

In regards to downsampling: That currently can't be done through this project. As you mentioned, your GPU might be able to do something within its own control panel, but I personally couldn't say for certain as I've never tried to do so.

**Comment by DonelBueno** [comment]
![image](https://user-images.githubusercontent.com/4239694/61193268-c9a44c00-a690-11e9-9175-c78ca67cc8e6.png)
If you have an Nvidia GPU, you can download Nvidia Inspector and use the settings on the image above, it works great. You can also use DSR.

**Comment by umbrellacorp53** [comment]
Madlad. Thank you bud. I wonder if I need to change the resolution in the d3d8.ini

**Comment by umbrellacorp53** [comment]
@polymega if you were to pick a resolution multiplier for your average texture what do you think would be ideal... I may or may not start playing with files now so that when the team eventually gets to that point I can actually be of some service instead of wasting valuable time on requests. 

Also what method did you use to extract and reencode the files in a lossless manner for the changes you've made? 

Oh... (sorry to ask so many questions) did you just use reverse image search to figure out the lake location or did you have some insider knowledge? I'm going to shoot an inquiry towards the RE4HD project team and see if I can get some tips. Their work so far is masterful.

**Comment by umbrellacorp53** [comment]
Again though thank you for taking time to answer questions. I know you guys are really busy. I'm just looking for any way I can be of service.

**Comment by umbrellacorp53** [comment]
![sh2pc 2019-07-15 15-27-05](https://user-images.githubusercontent.com/52713938/61246816-5c86ca00-a715-11e9-92f1-d4340c823ec2.png)

Really happy with the results. I'm running it at 2x2 SS and the SH2EE reshade + chromatic aberration and vignette. Anyone who may be curious, I left the d3d8.ini resolution set to 1920x1080 to match my monitor.

**Comment by umbrellacorp53** [comment]
@Polymega I'm going to close this since the posted solution is good enough for the time being and I'm not sure if there's much of a demand for DS as there are more efficient ways of improving image quality and removing shimmering...

I'm very curious about your texture work so far and I hope that if you get some downtime you may 
be able to answer my previous questions. I have done some texture mods before and even if this project never includes texture modification or if it's not a priority, I'd still love to poke around and make some mods for my own personal use. Thanks! You guys are doing god's work.

**Comment by Polymega** [comment]
Thanks for the tip, @DonelBueno.

@umbrellacorp53 I'm happy to type up some info on how to losslessly extract and replace the current texture files but give me some time for that. It wouldn't be a quick blurb on how to do it, [mostly because the SH Resource Editor introduces artifacts if you re-import textures using that software](https://github.com/ThirteenAG/WidescreenFixesPack/issues/375#issuecomment-379928324). So the work in lossless extraction/re implementation is be a bit more involved.

**Comment by umbrellacorp53** [comment]
Thanks @Polymega. I just wanted to make sure I wasn't getting lost in the sea of comments. I'm amazed at how you keep up with all of it to be honest.

**Comment by Polymega** [comment]
Lots of OCD, lol.
