### ISSUE TITLE
Rowboat Cutscene Animation Fix

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#16]
@elishacloud 
[A continuation of this discussion.](https://github.com/elishacloud/dxwrapper/issues/9#issuecomment-374322883)

@Bigmanjapan has found that the issue has to do with address 008BB78C. By default this is set to FFFFFFFF, but after the rowboat cutscene ends the value is changed to 0. This value is necessary for the rowing animation to work correctly. The problem is when you reload a save and view this cutscene again, the value does not change back to FFFFFFFF and causes a weird bug where James twists his entire body.

The solution is to write FFFFFFFF to address 008BB78C when the rowboat cutscene is active. Once the cutscene is over, the game will change the value to 0 for the rowing animation as it normally does.

```
004A02B5 jmp XXXXXXXX
XXXXXXXX cmp eax,4C
XXXXXXXX jne // jumps to return if not cutscene 76: James enters Rowboat
XXXXXXXX mov [008BB78C],FFFFFFFF 
XXXXXXXX ret // jump goes here
```

**Comment by elishacloud** [comment]
@AeroWidescreen, I implemented this in [c77f1d8](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/c77f1d85dada1eb15b045ae54bfce472a129302b).  However I had to use a different branch for this fix because unfortunately it causes a potentially worse problem.  It only allows you to row in one direction.  If you start rowing to the right then you will keep rowing that way, and vice versa.

**Comment by AeroWidescreen** [comment]
Huh, thought I solved that problem. It's okay, I have an idea that I'm going to try in a second.

**Comment by AeroWidescreen** [comment]
Try adding another compare & conditional jump so that it only writes FFFFFFFF once instead of continuously. That should fix it based on my testing.

```
cmp eax,4C
jne // jumps to return if not cutscene 76: James enters Rowboat
cmp [008BB78C],FFFFFFFF
je // jumps to return if value is FFFFFFFF
mov [008BB78C],FFFFFFFF
ret
```

**Comment by AeroWidescreen** [comment]
By the way, it does look like you made an error but you should still do what I suggested to ensure it works properly.

The code you currently have is writing FFFFFFFF to 008BB78C when it's _not_ cutscene 76, so it's basically writing that value constantly. That would conflict with the rowing animation.

![error](https://i.imgur.com/JhQBbjd.png)


That `jne` should be a `je`.

**Comment by elishacloud** [comment]
Yep, I just spotted my error also.

However, I am not sure why we need this.  If the value is already FFFFFFFF then what difference does it make if we write FFFFFFFF to it again?

```asm
     je // jumps to return if value is FFFFFFFF
     mov [008BB78C],FFFFFFFF
```

**Comment by AeroWidescreen** [comment]
> However, I am not sure why we need this. If the value is already FFFFFFFF then what difference does it make if we write FFFFFFFF to it again?

It's not doing that though. If the value is already FFFFFFFF then it writes nothing and jumps to `ret`. There's multiple ways you could write this:

```
00000001 cmp eax,4C
00000002 je 00000004 // jumps if cutscene 76
00000003 ret
00000004 cmp [008BB78C],FFFFFFFF
00000005 jne 00000007 // jumps if not FFFFFFFF
00000006 ret
00000007 mov [008BB78C],FFFFFFFF
00000008 ret
```

**Comment by elishacloud** [comment]
Ok, I think I have an implementation that works.  Thanks for your help!  :-)

The check in is [3e1cbeb](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/3e1cbeb3e5c2626ba38c637b6fecb443b82f8f97).

**Comment by AeroWidescreen** [comment]
Yeah sorry, I was under the impression there was some kind of conflict with the game writing 0 at the end of the cutscene when I made my 2nd reply. Of course it was actually a small error you made that we both overlooked.

I was only suggesting you add the compare to ensure the game had no trouble overwriting that value when it needed to, if that makes any sense. But if it works then it works, that's all that matters. 👍
