### ISSUE TITLE
Game freezes loading ReShade plugins

### ISSUE THREAD

**Issue by seagull** [elishacloud/Silent-Hill-2-Enhancements#160]
Try opening the game, it freezes on a black screen, usually while saying "Loading x of 4 plugins".
I've had some varied success but 9 times out of 10 it just doesn't launch and hangs instead.
Standard configuration using the Enhancement pack, nothing funny.
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3404038/d3d9.log)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3404039/d3d8.log)

Sometimes it freezes on a white screen.
I know it's loaded the effects because the logfile says so. It doesn't display the Konami logo.
Any ideas welcome.

**Comment by seagull** [comment]
Logs from a successful execution:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3404084/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3404085/d3d9.log)

**Comment by Polymega** [comment]
If you keep `d3d8to9 = 1` but **temporarily** remove `d3d9.dll` will the game launch for you then?

**Comment by seagull** [comment]
Hi, here are the results:

1: failed, black screen
2: launched, but crashed upon exiting
3: launched, but crashed upon exiting
4: launched, but crashed upon exiting
5: failed, black screen

**Comment by Polymega** [comment]
Thanks seagull. And if you set `d3d8to9 = 0` the same results? 

Are you using the North American executable? I doubt this would affect anything, but, if you're not, trying using this EXE and see if it helps any: http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE

If you're still having problems, we might need to get Elisha to help with troubleshooting.

**Comment by elishacloud** [comment]
If that does not work then try setting `SingleCoreAffinity = 0`.

**Comment by seagull** [comment]
Setting `d3d8to9` to 0:
attempt 1: passed
attempt 2: passed, but crashed exiting
attempt 3: passed, but crashed exiting
attempt 4: failed
attempt 5: passed, but crashed exiting

Logfiles from a session with a crashed exit:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3408320/d3d8.log)

Adjusting `SingleCoreAffinity` seems to make no difference; it's still a crapshoot.
My odds are definitely much better without the d3d8to9, but I'm running Windows 10 x64 with a 1070; I sort of feel like I ought to be able to handle it.

**Comment by Polymega** [comment]
As lame as this sounds, would consider uninstalling everything and starting from scratch?

**Comment by seagull** [comment]
Already tried it, unfortunately.

**Comment by Polymega** [comment]
Your antivirus software isn't trying to give you headaches when you laucnh the game?

Does running the game in administrator mode help?

Sorry seagull... I'm stretching for ideas on this one. :-/

**Comment by elishacloud** [comment]
@seagull, try installing the Microsoft Visual C++ 2010 Redistributable Package (x86).  You can download it [here](https://www.microsoft.com/en-us/download/details.aspx?id=5555).

Also try setting `AutoUpdateModule = 0`.

**Comment by Polymega** [comment]
Oh, semi-related Elisha: I mentioned these libraries being required on the main steps now: 

http://enhanced.townofsilenthill.com/SH2/#installSH2Enhancements

http://enhanced.townofsilenthill.com/SH2/#installIndirectSound

**Comment by seagull** [comment]
Hi, thanks for all your help so far.

- I already have the x64 and x86 C++ 2010 redistributables installed.
- Testing with AutoUpdateModule OFF, SetCoreAffinity ON, D3D8to9 OFF:
test 1: passed
test 2: passed
test 3: passed, but crashed exiting
test 4: passed, but crashed exiting
test 5: passed

I've also noticed that skipping the Angela video sometimes crashes the title.
d3d8.dll version: 1.3.1365.0

Please let me know if I can give you any more detailed information.
Cheers

**Comment by elishacloud** [comment]
@seagull, Try installing the DirectX 9.0c Runtime library from [here](https://www.microsoft.com/en-us/download/details.aspx?id=35).

> Oh, semi-related Elisha: I mentioned these libraries being required on the main steps now: 
>
> http://enhanced.townofsilenthill.com/SH2/#installSH2Enhancements
>
> http://enhanced.townofsilenthill.com/SH2/#installIndirectSound

@Polymega, Ok.  Do you have plans to switch over from IndirectSound to OpenAL 3D Audio?

**Comment by Polymega** [comment]
> Do you have plans to switch over from IndirectSound to OpenAL 3D Audio?

Very much so. [This particular version](https://www.nexusmods.com/newvegas/mods/65094) of OpenAL Soft works beautifully with the game and would be the cherry on top of our previous work with the game's audio, as it restores the sound delivery/presentation for all audio, comparable to the PS2 version.

I haven't pushed for a jump to Open AL yet as I'm hoping we can find help in making an integrated solution to remove the pops/clicks when audio ends abruptly in the game. If we make a fix that's built-in to this module, we can take full advantage of Open AL at that point. 

Until that time, I feel IndirectSound's pop/click fix is more important at the moment, as the pops/clicks can be very noticeable, even to regular players.

**Comment by umbrellacorp53** [comment]
Is there a downside to using Open AL?

**Comment by Polymega** [comment]
Yes, it doesn't alleviate the popping and clicking for audio that ends abruptly.

**Comment by elishacloud** [comment]
> I'm hoping we can find help in making an integrated solution to remove the pops/clicks when audio ends abruptly in the game.

Ok, I can look at this later.  I have not worked on DirectSound much, but I would like to get into it some day.  I already created a [wrapper](https://github.com/elishacloud/DirectX-Wrappers/tree/master/dsound) for it so I can probably use this to build the fix.

**Comment by Polymega** [comment]
@seagull If you want to try a newer version of ReShade, I've updated the package here: 
http://enhanced.townofsilenthill.com/SH2/#changelog

**Comment by seagull** [comment]
That seems to have fixed it, @Polymega! Thank you!

**Comment by Polymega** [comment]
Oh wow, really?! That was a complete shot in the dark. I'm very glad things are working well for you again.

**Comment by seagull** [comment]
Unfortunately, revisiting this, the old 'fix' – if that is what it was – is no longer working.
The issue seems to have to do with the loading and compiling of shaders within ReShade.
If I remove the `.fx` files within the `reshade-shaders\Shaders` folder, the game loads every time.
With them in, it's a crapshoot as to whether the game will launch properly.

**Comment by Polymega** [comment]
Can you try two things for me? 

1. Try this ReShade package and see if it works: [TEST.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3695210/TEST.zip)
   - Only one file is added to it but maybe that'd make all the difference? 
2. If that doesn't work, navigate to `C:\Users\<your-login-name>\AppData\Local\Temp\`. 
[You may need to show hidden files/folders to find it.](https://www.technipages.com/show-hidden-files-windows)
   - Delete all files and folders within this `Temp` folder that you are able. If you get a prompt that some can't be deleted, just skip those. 
   - After clearing out your `Temp` folder, see if the game will launch with ReShade then.

**Comment by elishacloud** [comment]
@seagull, also try with this test build and send me the log file.  Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3684478/d3d8.zip)

**Comment by seagull** [comment]
Hi everyone, thanks for your continued assistance with this.

@Polymega:
- ReShade 'test' package works; however, it works because when I press HOME to show the shaders I notice that they are all unchecked. Checking any one of them causes the game to freeze immediately.
- Clearing the TEMP directory briefly yielded very good results. I launched it three times in a row without issues. I then took a second to do something else, came back to the screen and tried a run of five to give you the statistics; it didn't launch once.

@elishacloud:
Here are the log files with the new d3d8.dll. The success rate remains the same.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3696190/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3696191/d3d9.log)

Cheers!
seagull

**Comment by elishacloud** [comment]
The logs look ok.  This seems to be an issue specific to ReShade.  You might want to [open an issue](https://reshade.me/forum) on that project.

**Comment by seagull** [comment]
https://reshade.me/forum/troubleshooting/4730-silent-hill-2-reshade-is-stuck-at-startup#36248

**Comment by Polymega** [comment]
@seagull 
I looked into your thread over at ReShade and [crosire thinks v4.4 should fix the issue](https://reshade.me/forum/troubleshooting/4730-silent-hill-2-reshade-is-stuck-at-startup#36582). I've also updated it to that version on our install guide if you want to try it out: http://enhanced.townofsilenthill.com/SH2/#installReShade

**Comment by seagull** [comment]
That looks like just the ticket. Thanks for keeping on top of this!
I'll give it a shot and let you know.

**Comment by Polymega** [comment]
Closing ticket. We've dropped our external need for ReShade so this issue should hopefully be resolved. Feel free to make a new ticket if it isn't.
