### ISSUE TITLE
With Fix2D disabled, images display justified to the left

### ISSUE THREAD

**Issue by seagull** [elishacloud/Silent-Hill-2-Enhancements#161]
![2019-07-18 00-09-12 mp4_snapshot_00 02 086](https://user-images.githubusercontent.com/241834/61417838-85af8200-a8f0-11e9-84f3-99057d834536.png)

I like my 2D images stretched to take up the whole screen, so I disable Fix2D.
With things this way, the Konami and Creature Labs logos display justified to the left; so does the title screen.
The save screen does this. (The b;ack borders aren't the issue – that's my fault – the grey is.)

**Comment by Polymega** [comment]
Hi @seagull,
`Fix2D` and `FullscreenImages` work in tandem. So if you enabled/disable one, you'll have to do the same for the other. Try that out and let me know if things get fixed up for you. In the future, once we make the Fullscreen Image Enhancement Pack, we hopefully shouldn't have to worry about that anymore.

**Comment by seagull** [comment]
Hey Polymega, good to speak with you again.
Unfortunately both Fix2D and FullscreenImages are set to 1 in this instance.
Here is my d3d8.ini.

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3404113/d3d8.zip)
Cheers!

**Comment by Polymega** [comment]
> I like my 2D images stretched to take up the whole screen, so I disable Fix2D.

> Unfortunately both Fix2D and FullscreenImages are set to 1 in this instance.

Apologies, as this confused me. To be sure, if you want your images stretched, you set `Fix2D = 0` and `FullscreenImages = 0`?

**Comment by seagull** [comment]
Yes, you're absolutely right. My mistake.
I think the wording "fullscreen" is what threw me; to me, "fullscreen" means "stretched".
Regardless -- when the game launches, it works fine now. Thanks!
