### ISSUE TITLE
Flashlight issue in hospital elevator

### ISSUE THREAD

**Issue by LiamTell** [elishacloud/Silent-Hill-2-Enhancements#162]
Just wanted to report an issue that’s been bugging me since I first played the game a few years ago. It occurs right after the hospital chase scene, in the elevator.

![20190501164505_1](https://user-images.githubusercontent.com/51883449/61693238-76389a80-ad2f-11e9-9fbd-99bb9ca4f650.jpg)

As you can probably see (sorry about the noise filter), the flashlight shines straight through the elevator walls to the other side here. No idea if this is PC exclusive or if it's even possible to fix, but I wanted to report it just in case.

**Comment by Polymega** [comment]
Hi @LiamTell,
Thanks for sharing this. This is actually a limitation of the game/game engine that affects all versions. The flashlight will shine through all walls like this. 

For most of the game, Team Silent expertly positioned the camera to make this limitation as unnoticeable as possible, but they really dropped the ball with this cutscene. There is actually a shadow being cast along that left hallway from his light shining through the wall, but the flashlight itself brightens said shadow! 

Maybe in the future we could shift the camera to the right during this cutscene to completely hide that left hallway, or something else similar in spirit to clean up its presentation.

**Comment by LiamTell** [comment]
Ah, that's what I feared.  I was hoping it would be an easy fix, but at least I can put it out of my mind now. Keep in mind that this happens during gameplay as well, not just during the cutscene.

**Comment by Polymega** [comment]
> Keep in mind that this happens during gameplay as well, not just during the cutscene.

That's true. I've tried brainstorming ideas to make this particular area less noticeable with the flashlight thing, but no epiphanies have hit me yet.
