### ISSUE TITLE
... Butterfly shadows? 

### ISSUE THREAD

**Issue by umbrellacorp53** [elishacloud/Silent-Hill-2-Enhancements#163]
Probably not worth asking, but seeing the new soft/self shadows got me thinking while in the butterfly room. It would be incredible if shadows were enabled for the butterflies that surround your flashlight...

I'm gonna go out on a limb and assume that because they're just a simple "sprite" with transparency there's probably no chance of this happening but damn would it look amazing.

**Comment by Polymega** [comment]
> I'm gonna go out on a limb and assume that because they're just a simple "sprite" with transparency there's probably no chance of this happening but damn would it look amazing.

That's a very reasonable guess as to why they don't have shadows. 

Unfortunately, in regards to shadow work like this, we're essentially limited to what was already done by the developers. If the original game(s) didn't have shadows for certain things, we almost assuredly can't have them in ours, either. The `.kg2` file format houses level shadow data, but we have no documentation/clue on how to work with it.
