### ISSUE TITLE
Silent Hill 2 on Windows Boot Camp (Mac) Black Screen

### ISSUE THREAD

**Issue by nero978devil** [elishacloud/Silent-Hill-2-Enhancements#166]
I wasn't sure where to post this since I wouldn't assume that there are many people here using Windows on Mac but it's still Windows so I assume that a non-Mac Windows experienced this issue somewhere as well, but I wasn't able to find it on Google, unfortunately. Also, it's not even a problem with Enhanced Edition since I can't get the actual game to work but I assume that people here know plenty of things.

For several nights I've been trying to get Enhanced Edition to work, before checking if the game runs without any mods and it didn't. I downloaded the game from 3 different sources and to my non-surprise none of them worked. I gave up until I decided to give it another shot today and it was the same, but I had my brother's Windows PC near me and decided to try it on there and it launched without any mods or fixes as far as I know, and that is the case for most Win 10 users from what I gathered. But it gets completely stuck for me on Boot Camp, to the point where I can't alt+tab or open the Task Manager so I have to Log Out every time to make it close.

My Mac has i9, 32Gb, and Radeon Pro 560X, so it should be able to easily run Silent Hill 2 unless there's an AMD GPU specific problem. I tinkered with affinity, compatibility mode and checked that I have DirectX9 and such installed.

I know it's kind of dumb to have Windows on Mac anyway (might as well just get a Windows machine, right?) but in my experience, it's somewhat smoother than Windows on Windows machines I tried in the past and I can run 2019 games on mids-highs in 1080p at stable 60FPS so I like it, but trying to get old games to work is a whole other can of worms that I'm willing to open only for Silent Hill 2 (because Konami just couldn't do a simple and proper remaster) and I will be thankful to anyone who is willing to dedicate their time to help me solve this issue.

**Comment by PretentiousGeek** [comment]
I'm not sure if this will be seen but I am also having this issue with a 16" MacBook Pro with the most up to date version of SH2 Enhancements. I've tried basically everything I've seen others (and myself) do to get their game launching on native Windows machines with no avail, just a black screen with a Reshade bar at the top frozen. The auto-updater works fine when there is an update to download, but no matter how long the program is left it never loads.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4605017/d3d8.log)
![image](https://user-images.githubusercontent.com/5261175/81489247-28176800-926b-11ea-83f1-f3dde2e347da.png)

**Comment by AeroWidescreen** [comment]
Another SingleCoreAffinity bug?

**Comment by PretentiousGeek** [comment]
I believe so, that's where the log stops. I tried a variety of different core options with no change to the crash. Apologies if this is a frequently raised issue already!

**Comment by AeroWidescreen** [comment]
If you use SingleCoreAffinity = 0, does your game launch?

> Apologies if this is a frequently raised issue already!

A few things have been done to address this issue already, so it's surprising to hear someone else having trouble yet again. Assuming it is SingleCoreAffinity at fault.

**Comment by PretentiousGeek** [comment]
Hello again, apologies for the delayed response. 

Setting SingleCoreAffinity to 0 in d3d8.ini results in the same freeze unfortunately. I'll attach the current logs, which seem to show it freezing at the Room 312 fix.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4714600/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4714601/d3d9.log)
[dsound.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4714605/dsound.log)

**Comment by ArgonautSD** [comment]
I'm having the exact same issue on a Macbook.
