### ISSUE TITLE
Game freezes loading ReShade plugins (same issue with seagull)

### ISSUE THREAD

**Issue by lebouffon88** [elishacloud/Silent-Hill-2-Enhancements#173]
When I tried to load the game, it is just saying that it is loading 4 effects. And the application became unresponsive. I had to use task manager to end it.

I have tried everything suggested here. :( it just does not work. I wanted to uninstall the game and reinstall it but I cannot do it either since it says that it was having a catastrophic error. I have tried to delete the files, but if I do that and insert the disc to install the game again, it was just saying "uninstall game" instead of "install game".

You guys are always saying that I have to install Direct8X but I can not install them because I have a newer version of it. Same problem with the Microsoft Visual C++ 2010 Redistributable Package (x86). I am not allowed to install them because my computer have a newer version of them.

I am running a Windows 10 64 bit with a GeForce 1070 on my laptop.

Any help or ideas would be appreciated. Thanks!

These are the logs. I have tried moving the game to drive C too. It did not work either. :(

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3650028/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3650029/d3d9.log)

**Comment by Polymega** [comment]
Sorry you're having issues and thanks for trying some things first and attaching your log files. 

Have you tried the latest version of ReShade available on the install guide? seagull mentioned that's what fixed it for him: http://enhanced.townofsilenthill.com/SH2/#installReShade

**Comment by Polymega** [comment]
D'oh. I forgot to check your `d3d9.log` file and now see you're using the latest version. 

Next question: Do you have your Nvidia GPU set to force things like anti-aliasing for the game? As in, did you make a specific profile within your Nvidia Control Panel to alter video effects for the game, or do you have a global setting that would affect all games? 

Does your laptop have **both** a dedicated GPU _and_ integrated graphics such as Intel IGP?

Lastly, are you playing in windowed mode (`EnableWndMode = 1` in the `d3d8.ini` file)?

**Comment by lebouffon88** [comment]
Hallo thanksss for the response. 

No, I don't have any specific profile for the game to force AA. And no, my laptop only has the GeForce graphic card. And yes, the EnableWndMode is 1. :( Tried to make it to 0, and it just crashed. Could not even turn off the game with task manager. Had to force sign out from Windows.

**Comment by Polymega** [comment]
> And yes, the EnableWndMode is 1. :( Tried to make it to 0, and it just crashed.

That's probably normal. If you're using a custom resolution (`ResX` and `ResY`) the resolution you use must be inherently supported by your display if playing in fullscreen mode (`EnableWndMode = 0`). That's probably why it was crashing. 

> You guys are always saying that I have to install Direct8X but I can not install them because I have a newer version of it

Do note that while Silent Hill 2 PC requires DirectX 8 to run, ReShade requires/runs on DirectX **9**. Have you also tried downloading the DX9 SDK found here?: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by lebouffon88** [comment]
> > And yes, the EnableWndMode is 1. :( Tried to make it to 0, and it just crashed.
> 
> That's probably normal. If you're using a custom resolution (`ResX` and `ResY`) the resolution you use must be inherently supported by your display if playing in fullscreen mode (`EnableWndMode = 0`). That's probably why it was crashing.
> 
> > You guys are always saying that I have to install Direct8X but I can not install them because I have a newer version of it
> 
> Do note that while Silent Hill 2 PC requires DirectX 8 to run, ReShade requires/runs on DirectX **9**. Have you also tried downloading the DX9 SDK found here?: https://www.microsoft.com/en-us/download/details.aspx?id=35

Hi again. My computer says, it has a newer version of Direct X so no new installation is necessary (I have clicked the link you have given me). I am at a loss now, I almost give up.

**Comment by elishacloud** [comment]
@lebouffon88, this sounds like it could be a video card driver issue.  Try installing the latest Nvidia driver.  It could also be related to some Nvidia driver setting.  Also you may want to try setting `d3d8to9 = 0`.

**Comment by lebouffon88** [comment]
@elishacloud
I have installed the newest Nvidia driver. I have done this d3d8to9 = 0 and it didn't work (one of the first things I have tried).

**Comment by elishacloud** [comment]
I see.  Ok a few more things to try.  First of all I did some fixes in a newer build so try the build below.  Also try setting `SingleCoreAffinity = 0`.

Test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3660984/d3d8.zip)

**Comment by lebouffon88** [comment]
Tried it @elishacloud 
It did not work. :(

**Comment by lebouffon88** [comment]
Does anyone have any other idea? I'm at a loss here.
:(

**Comment by Polymega** [comment]
At this moment I unfortunately have no other solution ideas. However, ReShade is not imperative/critical to enjoy our project. ReShade provides some anti-aliasing and _slightly_ adjusts the color/level balance of the game (nothing major). 

So if you don't use ReShade you're not missing much; you'll still have all the other benefits. To disable ReShade you can set `d3d8to9 = 0` in the `d3d8.ini` file. 

Sorry we don't have an better answer for you at this time, but I think you'll still enjoy the experience even without ReShade for now.

**Comment by elishacloud** [comment]
Actually I don't think the issue is related to ReShade at all.  If he sets `d3d8to9 = 0` the game still freezes.

@lebouffon88, try this: 
1. Remove `dsound.dll` from the Silent Hill 2 folder.
2. Remove `dinput8.dll` from the Silent Hill 2 folder.
3. Unzip these three files to the Silent Hill 2 folder: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3672718/d3d8.zip)

This should disable all updates and test if the core module works with your copy of Silent Hill 2.

**Comment by lebouffon88** [comment]
Thank you for the response. Tried what you suggested @elishacloud
First I could not find the file dinput8.dll in my folder.
And second, it still does not work. So I think the installation has some error in it right.
I am trying now to uninstall and to reinstall the game, unfortunately the ingame uninstaller and also the windows remove app program does not allow me to uninstall the game, how should I uninstall it... I will try to figure this out. Thanks again!

**Comment by elishacloud** [comment]
Try using the Microsoft FixMe tool from here:

https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

**Comment by lebouffon88** [comment]
Hallo again!
I uninstalled the game, and installed it again on the C:\ directory. I then dont install the reshader now and it worked! I might try again with the reshader later, but now, I will enjoy the game without it. Thank you guys so much for the help. I am a bit dissapointed that I can not use the Reshade option, but it is better than nothing. :) I hope the problem can be resolved later. Thank you so much again!

**Comment by lebouffon88** [comment]
Hi guys, 
I just wanted to inform you, that it is all working properly now. I just installed the Mods one by one and try to start the game with it, rather than installing all the mods simultaneously like the last time. I installed the reshade mods the last, and now it is working. Thanks again!! You guys are awesome! :)

**Comment by elishacloud** [comment]
Thanks for the follow up.  I'm glad you got it all working!  Just let us know if you have any issues.
