### ISSUE TITLE
Runtime error when gameplay start

### ISSUE THREAD

**Issue by LewisBR-mdl** [elishacloud/Silent-Hill-2-Enhancements#174]
Hi there, I downloaded SH2: Enhanced Edition step by step, the game starts normally until the gameplay starts, it gives me a error box saying:  
**Microsoft Visual C++ Runtime Library**
**Runtime Error!**
**Program C:\Program Files (x86)\Silent Hill 2\sh2pc.exe**
**This application has requested the Runtime to terminate it in an unusual way.**
**Please contact the application's support team for more information.**
I've already tried to update Microsoft Visual C++ Runtime Library and DirectX 9 SDK
but everything just keeps the same, please help!

**Comment by Polymega** [comment]
Hello, 

A Google search of your issue suggests uninstalling the Microsoft Visual C++ Runtime Library and re-installing the package. 

Go to your **Add or Remove Programs** window, search for and uninstall the Microsoft Visual C++ 2010 Redistributables and re-install them from the following link: 
https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by elishacloud** [comment]
@LewisBR-mdl, You might also want to try to set `d3d8to9 = 0` and `AutoUpdateModule = 0`

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.
