### ISSUE TITLE
Grammar, punctuation, and sentence structure adjustments to the English text of Silent Hill 2 PC

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#18]
_@elishacloud this post can be closed in the near future. Posting so people are aware._

------------------------

I have made grammar, punctuation, and sentence structure adjustments to the English text of Silent Hill 2 PC. This was done by editing the `*_e.mes` files. 

**These files are included as part of the new [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles) download package.** 

**If you wish to not use these files** simply remove them from the following directory: 
`\KONAMI\Silent Hill 2\sh2e\etc\message\*_e.mes`

------------------------

### List of text changes
View the Google Doc here (MASSIVE GAME SPOILERS IN THE DOC!):
https://docs.google.com/spreadsheets/d/1YFiLSLvFXhiSmog9-hHtEU2ea-zQYXrSDPJnrm5j7wM/edit?usp=sharing

------------------------

### Example (taken from PCSX2 but says the same on PC): 
![image](https://user-images.githubusercontent.com/27395260/43689246-6d031e42-98c5-11e8-8357-c330b2a2a77b.png)

### Edited:
![image](https://user-images.githubusercontent.com/27395260/43689250-77a15562-98c5-11e8-8f78-8e357ecaed1e.png)

------------------------

In addition, I fixed a font color continuity error  in one spot present on all builds. Any time and every time something is read from a source in the game the font should be blue: 

### All builds: 
![sh2pc 2018-07-31 21-53-25](https://user-images.githubusercontent.com/27395260/43496616-42142b3e-950c-11e8-9659-0d88c6e281ca.png)

### Edited: 
![sh2pc 2018-07-31 21-52-48](https://user-images.githubusercontent.com/27395260/43496619-4558820e-950c-11e8-9272-b2c654d69218.png)

**Comment by Bullsquiddy** [comment]
Is the blue text fix included with the grammar fix? I ask just because someone might want the blue text fix, but the original writing.

**Comment by Polymega** [comment]
Yes, it'll be an all inclusive package for this.

**Comment by Bullsquiddy** [comment]
Are the .mes files editable in any way?
(Sorry to pester)

**Comment by Polymega** [comment]
No worries, you're not pestering, and yes, there is:
http://alchemillahospital.net/silent-hill-resource-editor/

**Comment by Bullsquiddy** [comment]
Would you happen to remember which .mes file contains the BAR Neely's text colour issue?

**Comment by Polymega** [comment]
I can't check right now to confirm but I believe it's `stage_town_east_msg_e`

**Comment by Bullsquiddy** [comment]
I really don't mean to be bothersome, but I can't find the BAR Neely's text - and I don't think it's documented on the Google Sheets spreadsheet you made of your dialogue changes. If you don't want to go looking for it again, I understand. Thank you in advance.

**Comment by Polymega** [comment]
Here you go. I went ahead and replaced it with the blue text. Place it under:
`\KONAMI\Silent Hill 2\sh2e\etc\message\`

[stage_toilet_msg_e.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2327963/stage_toilet_msg_e.zip)

**Comment by Polymega** [comment]
Fixed another font color continuity error for the English version of the game: 

### Before
![sh2pc 2018-08-30 20-23-00](https://user-images.githubusercontent.com/27395260/44886410-01cab800-ac94-11e8-94d2-b034039ff64f.png)

### After
![sh2pc 2018-08-30 20-24-17](https://user-images.githubusercontent.com/27395260/44886414-042d1200-ac94-11e8-9a6d-75c48d3de682.png)

**Comment by Polymega** [comment]
This one is for all the peeps who got stuck for an hour or two on their first playthrough with the canned juice (people like... ahem... me):

![sh2pc 2019-02-24 19-36-12](https://user-images.githubusercontent.com/27395260/53307988-adcc1500-386b-11e9-8959-aa48191167b8.png)

**Before**

> Six-pack of canned juice. It was in the hallway on the 1st floor.

**After:**

> A heavy six-pack of expired canned juice. It was in the hallway on the 1st floor.

It now mentions **heavy** to hint to the player what it's used for, as James comments that something heavy can unblock the garbage chute. 

It now mentions **expired** so dumbasses like me don't try to drink the damn thing a dozen times during their first playthrough (that's a true story) because they have no clue why they picked up juice to begin with.

**Comment by Polymega** [comment]
Purists look away now, as I'm adjusting some text (at least for the English version) to make things easier for first-timers. Just like the canned juice (above) the following text below is too cryptic to be of any help: 

> The door won't open.
>  [WAITING FOR KEY PRESS]
> Some power is holding the
> door closed from the other side.

That text happens at the main apartment door to get to Angela if you try to open the door before speaking to Eddie. Simply put: The original text doesn't help you in any way to know what to do which can absolutely lead to player frustration. I changed it to: 

> The door won't open.
> [WAITING FOR KEY PRESS]
> It feels like some power is holding
> the door closed from the other side...
> [WAITING FOR KEY PRESS] 
> Almost as if I need to find something... 
> or someone... before it will let me in.
