### ISSUE TITLE
[Request] Detailed changelog for enhanced edition essentials pack

### ISSUE THREAD

**Issue by SilentHeII** [elishacloud/Silent-Hill-2-Enhancements#180]
Would the team be willing to put a detailed changelog of what each file in the essentials pack does or, at the very least, the .map files?

I mainly ask for the people like me who find certain changes like the added power cable or the signs on the road unnecessary. While I do heavily appreciate the love and work being done on this project, I believe that after the massacre that was the HD collection, people should be able to choose whether they want a more faithful gameplay experience. I believe the game is a product of its time and in some respects should stay that way.

**Comment by Polymega** [comment]
That's a reasonable request but I haven't planned on cataloging every change/detail for all files at this time. Perhaps once the project comes to full/near completion I can then go and comb through everything to make a full, comprehensive list. Until we get closer to that point, I can't say what will change before that time. 

In the meantime, you can use the folder names to know what general locations the files within them would affect: 

ap - apartments
bw - bowling alley
ca - forest trail
cb - town east
cc - town west
cd - rebirth island
er - beginning bathroom/motorhome/bar neelys
hp - hospital
mr - ???
ob - observation deck
ps - prison/labyrinth
qp - mary & james bedroom/dog room
qt - mary & james bedroom
rr - hotel
ru - hotel alternate
th - heaven's night
bg2\ma - bfaw scenario

**Comment by SilentHeII** [comment]
Thank you. I've already deleted the files I didn't want while browsing files in the map viewer, but I still thought it'd be something people would appreciate. Thanks again.

**Comment by DaRkL3AD3R** [comment]
SilentHell could you elaborate on how you did that? There are a couple map changes I tend to agree stray from the original artistic direction and would like to specifically nip those from the fix files.

**Comment by Polymega** [comment]
These are .map files. You'd remove them from the `sh2e\bg\` folder. For example, off the top of my head, `hp\hp190.map` is the hospital day room.

**Comment by Polymega** [comment]
I do not have an itemized list of every edit done. I'd recommend downloading the SH2 Level Viewer/Editor to help determine which `.map` files you want to hone in on: https://github.com/pmttavara/ph2
