### ISSUE TITLE
Enhanced game running slow

### ISSUE THREAD

**Issue by luisdanielfc** [elishacloud/Silent-Hill-2-Enhancements#183]
Greetings, I've never played Silent Hill 2 so I wanted to do it with the best experience implementing the Enhanced Edition. I followed the guide step by step, but when I launch the game is kind of slow (I assumed this is because my computer's specs, since is not a fast one); for example: in the menu screen when I place the knife (mouse) over the "New Game" option is doesn't get marked, I have to place it a tiny bit up the option; also, when I started the game (It looks amazing by the way) it is slow.

What I want to know is what options in the .ini file should I modify (and if necessary, sacrifice some enhancements) so my game can run smoothly? 

My computer specs (again, I know is not that potent):
Processor: AMD Athlon(tm) X2 Dual Core Processor 3250e (1.50 GHz)
RAM: 2 GB
OS: Windows 7 (64 bits)
GPU: none (haha)

Note: I have the US Restless dream edition.

**Comment by luisdanielfc** [comment]
The solution was in the offical web page http://www.enhanced.townofsilenthill.com/SH2/troubleshoot.htm

I sacrificed ReShade by setting d3d8to9 = 0.

**Comment by Polymega** [comment]
Hi @luisdanielfc ,

> I sacrificed ReShade files by deleting them (reshader folder and both reshade ini files)

You beat me to it! That was the first thing I was going to suggest to disable/remove. The biggest thing ReShade does for the game is add anti-aliasing. The game experience is still excellent even without ReShade. :) I'm glad the game is playing smoothly for you now!
