### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by SpaceCowboy3514** [elishacloud/Silent-Hill-2-Enhancements#187]
I'm not sure what is happening. I have virtually no programming experience

[the d3d8 file](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3827976/silent.hill.2.txt)

 sorry that I can't provide more details

**Comment by Polymega** [comment]
Can you describe what exactly is happening? Looking at your `d3d8.ini` file you are playing in windowed mode (which we recommend) and having it fill the entire space of your screen (as `ResX` and `ResY` are both set to `0`).

**Comment by SpaceCowboy3514** [comment]
It loads in the standard 4:3 aspect ratio instead of the 16:9 was hoping for. Sorry if my initial posting was vague

**Comment by Polymega** [comment]
No worries. Please launch the game then close/exit it. Afterwards, attach your `d3d8.log` file here. This is different than the `d3d8.ini` file you attached previously.

**Comment by SpaceCowboy3514** [comment]
thanks for helping
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3828021/d3d8.log)

**Comment by Polymega** [comment]
Looking at your log file, the issue appears to be that you're trying to launch `sh2pc.bak.exe.exe` instead of `sh2pc.exe`.

I suggest turning on file extensions to ensure you are launching the correct executable. [You can learn how to do that here.](https://www.wikihow.tech/Show-File-Extensions-on-Windows) 

Once you enable file extensions, rename `sh2pc.bak.exe.exe` to `sh2pc.exe.bak` and then make sure you are launching the new executable you downloaded from our installation guide (which would just be `sh2pc.exe`).

**Comment by SpaceCowboy3514** [comment]
wait so do I run autorun after I mount the iso or do I launch sh2pc?

**Comment by Polymega** [comment]
You install the game like normal, then, after installation, [follow the install steps on our installation guide](http://enhanced.townofsilenthill.com/SH2/). On Step #2, you will replace the `sh2pc.exe` that came with the installation of the base game with our executable instead. You will rename your original `sh2pc.exe` to `sh2pc.exe.bak` for safe-keeping, and run/launch the game using our `sh2pc.exe` going forward.

**Comment by SpaceCowboy3514** [comment]
ok thank you

**Comment by Polymega** [comment]
Let me know if launching the game through our `sh2pc.exe` (found here: http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE ) works for you. It must be exactly named that.

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.
