### ISSUE TITLE
Few questions about the folders "data" and "movies"

### ISSUE THREAD

**Issue by nomadspy** [elishacloud/Silent-Hill-2-Enhancements#188]
Hi, everyone, I'm new here! First I want to thank the modders for their work! Second I got questions:
1. When comparing the FMVs from sh2e to the original data movies noticed that there is one additional file in the new "movies" folder called "ending" which was odd because there is the file "end" which is byte for byte the same size and both play the same video. Why is that and which one should I delete if needed? The original folder doesn't have "ending"
2. Can I actually delete the files within the "data" folder since the .dll is forcing the use "sh2e"?
3. Tried everything but the new FMVs despite looking a lot better can run on full screen on my setup. I got two screens one is 1080p and the other is 4K both 16:9 and both display the videos with black pillars on the sides which makes me want to revert back to the original files. Any fix for that?

**Comment by Polymega** [comment]
Hi there, 

1. The added `end.bik` movie is an exact copy of `ending.bik` movie. The reason for this inclusion is that [the game may give you an error as it expects `end.bik` but only finds `ending.bik`](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#.22Insert_a_disc.22_message_in_the_ending). This inclusion is simply a safety measure (redundancy).
2. No! Do **not** delete _anything_ within the `data` folder. The `data` folder holds all of the game's files. [The `sh2e` folder holds our custom, improved files so as not to overwrite the original files.](http://enhanced.townofsilenthill.com/SH2/config.htm#UseCustomModFolder) The `sh2e` folder _only_ houses files we've modified for our project; all other files we haven't touched are still used/called within the `data` folder. Additionally, your save files are housed/stored in the `data` folder at all times. 
3. [The pillar boxes are part of the Enhanced FMVs.](http://enhanced.townofsilenthill.com/SH2/config.htm#FMVWidescreenMode) This was a deliberate choice by the creator of the FMV Enhancement Pack. The original 4:3 FMVs do not properly/correctly scale to a 16:9 aspect ratio which means you must either a) crop the videos or b) place pillar boxes on the side to preserve the composition. angular_graphics (the FMV creator), opted for the latter choice. He has expressed interest in doing a "2.0" version of his FMV work in the future and, if he does, we can see about giving more choices/options for FMV scaling/cropping at that time.

**Comment by nomadspy** [comment]
> Hi there,
> 
> 1. The added `end.bik` movie is an exact copy of the `ending.bik` movie. The reason for this inclusion is that [the game may give you an error as it expects `end.bik` but only finds `ending.bik`](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#.22Insert_a_disc.22_message_in_the_ending). This inclusion is simply a safety measure (redundancy).
> 2. No! Do **not** delete _anything_ within the `data` folder. The `data` folder holds all of the game's files. [The `sh2e` folder holds our custom, improved files so as not to overwrite the original files.](http://enhanced.townofsilenthill.com/SH2/config.htm#UseCustomModFolder) The `sh2e` folder _only_ houses files we've modified for our project; all other files we haven't touched are still used/called within the `data` folder. Additionally, your save files are housed/stored in the `data` folder at all times.
> 3. [The pillar boxes are part of the Enhanced FMVs.](http://enhanced.townofsilenthill.com/SH2/config.htm#FMVWidescreenMode) This was a deliberate choice by the creator of the FMV Enhancement Pack. The original 4:3 FMVs do not properly/correctly scale to a 16:9 aspect ratio which means you must either a) crop the videos or b) place pillar boxes on the side to preserve the composition. angular_graphics (the FMV creator), opted for the latter choice. He has expressed interest in doing a "2.0" version of his FMV work in the future and, if he does, we can see about giving more choices/options for FMV scaling/cropping at that time.

Thank you for the detailed clarification!
