### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by CaMack51** [elishacloud/Silent-Hill-2-Enhancements#189]
Hi there,

When I change the resolution to my desired (2560x1440) in the d3d8.ini, the changes do not take effect in the game. Please see the attached ini that i had to paste into a txt to post. I've tried changing to fullscreen from windowed and that does not change either.

Thanks in advance!

[d3d8.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3853320/d3d8.txt)

**Comment by Polymega** [comment]
Hi, 
Is your monitor/display capable of a 2560x1440 resolution? If so, try setting `FullscreenWndMode = 0` in the `d3d8.ini` file and see if that helps any.

If it still doesn't work, please attach a copy of your `d3d8.log` file and a snapshot of your game's directory for Silent Hill 2.

**Comment by CaMack51** [comment]
Hi,

It is, that's its native res. I tried that by unfortunately nothing.

[d3d8log.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3853374/d3d8log.txt)
![SH2 Directory](https://user-images.githubusercontent.com/57815414/68979606-e21aa380-07f5-11ea-97e4-103c6f613b0d.png)

**Comment by Polymega** [comment]
Thanks for the added info. 

Looking at your log file, it seems the integrated "SH2 Widescreen Fix" package (that adjusts things like the resolution) isn't taking effect.

[Comparing to the files that you'd include with our project](http://enhanced.townofsilenthill.com/SH2/#directorytree), it looks like you have an extra file that's not a part of our project.

Try deleting/removing the `dxgi.dll` file from the game's directory, as that might be conflicting with the SH2 Widescreen Fix and associated integrated packages. See if it launches in your desired resolution after removing that file.

**Comment by CaMack51** [comment]
Thanks for the quick replies here, really appreciate you trying to help here.

Unfortunately this also did not work.

**Comment by elishacloud** [comment]
The problem seems to be here:

```
14244 21:08:15.630 Loading the "Nemesis2000 Fog Fix" module...
14244 21:08:15.630 LoadModuleFromResourceToFile Error: "Nemesis2000 Fog Fix" module could not be written!
14244 21:08:15.630 LoadModuleFromResourceToFile Error: failed to load "Nemesis2000 Fog Fix" module!
14244 21:08:15.631 Loading the "WidescreenFixesPack and sh2proxy" module...
14244 21:08:15.632 LoadModuleFromResourceToFile Error: "WidescreenFixesPack and sh2proxy" module could not be written!
14244 21:08:15.632 LoadModuleFromResourceToFile Error: failed to load "WidescreenFixesPack and sh2proxy" module!
14244 21:08:15.632 Loading the "modupdater" module...
14244 21:08:15.633 LoadModuleFromResourceToFile Error: "modupdater" module could not be written!
14244 21:08:15.633 LoadModuleFromResourceToFile Error: failed to load "modupdater" module!
```

It looks like none of the built-in modules are loading.  Try adding the following line into the ini file under the `[General]` section:

```ini
LoadModulesFromMemory = 1
```

**Comment by CaMack51** [comment]
Hi,

No change after this either :(

**Comment by elishacloud** [comment]
Please post the updated log file.

**Comment by CaMack51** [comment]
Certainly, i've uploaded the .ini and the .log
[d3d8log.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854116/d3d8log.txt)
[d3d8ini.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854117/d3d8ini.txt)

**Comment by Polymega** [comment]
It looks like the previous `d3d8.log` file was re-uploaded? (All same timestamps.)

Try relaunching the game with the newly-added `LoadModulesFromMemory = 1` line in the `d3d8.ini` file then, after closing the game, attach the newly-made `d3d8.log` file. If it's easier, you don't have to rename the files with a ".txt" at the end; you can just upload them as `d3d8.ini` and `d3d8.log`.

**Comment by CaMack51** [comment]
[d3d8log.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854631/d3d8log.txt)
[d3d8ini.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854632/d3d8ini.txt)

**Comment by Polymega** [comment]
Oops, it looks like `d3d9.log` got uploaded as `d3d8log.txt`. After launching then closing out the game using  `LoadModulesFromMemory = 1` in the `d3d8.ini` file, we'll need the `d3d8.log` file from it.

**Comment by CaMack51** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854854/d3d8.log)

**Comment by CaMack51** [comment]
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3854862/d3d9.log)

**Comment by CaMack51** [comment]
Sorry,  I''m not 100% if these are that right ones

**Comment by CaMack51** [comment]
I added the LoadModulesFromMemory = 1 to the d3d8.ini, launched and resent the logs

**Comment by elishacloud** [comment]
Hello @CaMack51, can you try this update here:  [sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3861853/sh2pc.zip)

Steps:
1. Delete all log files from your Silent Hill 2 folder.
2. Extract these updated files into your Silent Hill 2 folder overwriting any existing files.
3. Then double click on the `sh2pc.exe` file.
4. If you have any issues attach your updated `d3d8.log` file.

**Comment by CaMack51** [comment]
That worked!!

Thank you so much for your help on this, this community rocks! :)

**Comment by elishacloud** [comment]
Great!  I believe the issue was that your temp folder is not properly configured.  By default the module uses the temp folder.
