### ISSUE TITLE
I keep getting error 0xc0000005 when trying to launch the game

### ISSUE THREAD

**Issue by mrfloot** [elishacloud/Silent-Hill-2-Enhancements#190]
Hi.

I did a fresh install of Silent Hill 2 and copied over all of the files on the installation instructions and I keep getting the 0xc0000005 error.

If I try and start the game using the original .exe file it loads up fine, but using the enhanced .exe gives me the error.

Here is my folder 
![SH](https://user-images.githubusercontent.com/57846786/68999638-11471880-08bb-11ea-9371-df8928f92f1d.jpg)

Strangely, I don't get any log files either. No idea what to do. 

Thanks

**Comment by Polymega** [comment]
> If I try and start the game using the original .exe file it loads up fine

Ah! We have a lead now!

A few follow-up questions:

1. To confirm: When using the original executable (that _does_ launch the game), you still don't get a `d3d8.log` file after launching/closing the game.
2. Keep your original executable (that does work) as a backup still, but try using version 1.1 of the North American executable and see if this one will launch for you. Let us know if it works or not:
http://enhanced.townofsilenthill.com/SH2/files/SH2PC_Enhanced_EXE_NA_v1.1.zip
3. Lastly: Did you install Silent Hill 2 PC from a legitimate copy (from the official discs), or was this obtained through an abandonware site? We're not here to judge or anything; but we're trying to see if this error happens to stem from a particular source for the game.

**Comment by mrfloot** [comment]
Hi, thanks for getting back to me so quick.

Yes, when I use the original .exe the game loads, but it's just the standard settings and stuff. 

I'll give the new 1.1 exe a try later (giving my eyes a break from the computer haha)

Also I installed it using legit disks, not a downloaded version. I'll let you know if I have any progress with the new exe.

Thanks

**Comment by mrfloot** [comment]
Hey, so the new 1.1 .exe still gives me the error.

When I use the original .exe this also now gives me the same error :( Not sure what to do.

**Comment by Badore90** [comment]
What if you run the game's exe as administrator??

**Comment by mrfloot** [comment]
Yeah, I've been running it as an administrator. :(

**Comment by Polymega** [comment]
This error 0xc0000005 that's been reported a few times is completely new to us. I'm starting to wonder if a recent Windows Update may have something to do with it. 

From Googling the error, it seems to stem from missing .dll files needed to run the game. Assuming you downloaded the DirectX 9 SDK and Visual C++ 2010 packages from the install guide, all extra, required runtime libraries should be accounted for. 

We really want to get to the bottom of this issue but are still left in the dark on it.

**Comment by Polymega** [comment]
What antivirus are you using? Can it be preventing you from launching the game?

**Comment by mrfloot** [comment]
I ran all of the packages in the tutorial. The DX9 one kept saying that it detected a newer version so no need to install and I couldn't find a way to get that to run. 

I'm using Kaspersky anti-virus but I don't get any kind of notification from it when trying to run SH2.

**Comment by Polymega** [comment]
Can you try this and see if the game launches for you then?
https://support.kaspersky.com/common/windows/1161

If it says some files can't be deleted you can skip those.

**Comment by mrfloot** [comment]
Hey,

I tried that and it took longer to give me the same error. Still no luck.

**Comment by mrfloot** [comment]
Ok, so I got it working! I was trying to swap in the 1.0 exe back into the folder after you send me the 1.1 exe. So I just renamed the exe to sc2pc1 and it works! If I take the 1 away I get the error, but simply renaming the exe lets the game run! It seems to be working absolutely fine now.

**Comment by elishacloud** [comment]
That sounds like an issue with compatibility settings.  Try renaming the file back to `sh2pc.exe` and then check the compatibility settings.  All compatibility options should be disabled.

![image](https://user-images.githubusercontent.com/25625456/69116012-978c6780-0a3f-11ea-8fed-6726a9dcef78.png)

**Comment by Polymega** [comment]
Thanks for testing these things out, @mrfloot. We want to find a true solution to this issue so your testing helps.

**Comment by mrfloot** [comment]
I tried the compatibility thing the other day and still got the error. 
After running the .exe after I’ve renamed it, I get the logs and the ReShader thing pops up and in game you can see the enhancements are working.
