### ISSUE TITLE
Microsoft Visual C++ Runtime Libary ERROR

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#191]
Runtime Error!

Program: \Silent Hill 2\sh2pc.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Anyone can help me to fix that?

**Comment by Polymega** [comment]
Hi @ppsalvador,

Can you attach a snapshot of your game's installation directory?

**Comment by ppsalvador** [comment]
how i can send

**Comment by ppsalvador** [comment]
![Sem Título](https://user-images.githubusercontent.com/57973510/69206766-875eb000-0b45-11ea-9303-5a5a981147b4.png)

**Comment by Polymega** [comment]
Thank you. Please **delete** the following files/folders from the game's directory and see if that fixes the error. 

### Delete: 

```
\AudioScripts\
\Common\
\External\
\Logging\
\Patches\
\Resources\
\Wrappers\
.gitnore
.gitmodules
device
dllmain.cpp
sh2-enhce.sln
sh2-enhce.vcxproj
sh2-enhce.vcxproj.filters
```

**Comment by ppsalvador** [comment]
Thank You,
But my game now crashed sometimes, idk why.

What could it be?

**Comment by Polymega** [comment]
> But my game now crashed sometimes, idk why.

Please attach a copy of your `d3d8.log` file.

@elishacloud 
For future troubleshooting: I believe ppsalvador's original problem is that they downloaded the source files (instead of the compiled download) and this creates the launch error they received when `AutoUpdateModule` is also enabled. I only thought about this as I helped troubleshoot the same issue for a streamer a week ago.

**Comment by ppsalvador** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3872398/d3d8.log)

**Comment by Polymega** [comment]
Thank you. The issue might be that you are running the game under `sh2pc.bak.exe` and not `sh2pc.exe`. 

Try this: 
- **Delete** your `sh2pc` file from the game's directory. 
- [Download this file](http://enhanced.townofsilenthill.com/SH2/files/SH2PC_Enhanced_EXE_NA_v1.0.zip) (which is a new `sh2pc`) and place it in the game's directory.
- Launch the game and see if you still experience issues.

Lastly, I'd recommend showing known file type extensions. [You can learn how to do this here.](https://www.wikihow.tech/Show-File-Extensions-on-Windows)

**Comment by ppsalvador** [comment]
Thank You

**Comment by ppsalvador** [comment]
So, one more thing, I'm Portuguese and like to put Portuguese subtitles in the game. Will it work without any error?
If u know ;)

**Comment by Polymega** [comment]
So to confirm: The game is running fine for you now?

> I'm Portuguese and like to put Portuguese subtitles in the game. Will it work without any error?

I'm not sure. I haven't tested any fan translation packs myself. 

However, you can ask @renan-de-souza to send you his Portuguese fan translation files, as they seem to be fully compatible with our project.

**Comment by ppsalvador** [comment]
So to confirm: The game is running fine for you now?
 - YES THANKS <3

**Comment by ppsalvador** [comment]
i put the game at 60fps now so cool

**Comment by ppsalvador** [comment]
Btw, how i can talk with @renan-de-souza ??

**Comment by Polymega** [comment]
> Btw, how i can talk with @renan-de-souza ??

He will receive a notification of this thread since we tagged his username. Hopefully he'll reply with the Portuguese translation files for you.

**Comment by ppsalvador** [comment]
Ok, @Polymega Tanhk you so much!!!
