### ISSUE TITLE
I found another missing texture.

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#192]
Hi!

Sorry for create a new post only for this.

On the second floor of Brookhaven Hospital, in room M3, if you pay attention to the turned bed, you will see that the lower part has some missing textures. You can see through the other side.

**Comment by Badore90** [comment]
It seems all normal on my PC. Where should be exactly the missing textures?

![sh2pc 2019-12-05 16-33-51](https://user-images.githubusercontent.com/44087144/70249975-789b0e80-177d-11ea-899f-c88cc74a9235.png)
![sh2pc 2019-12-05 16-33-25](https://user-images.githubusercontent.com/44087144/70249980-7b95ff00-177d-11ea-952f-11bde534963e.png)
![sh2pc 2019-12-05 16-33-37](https://user-images.githubusercontent.com/44087144/70249984-7cc72c00-177d-11ea-94c7-9fdb6e16e248.png)

**Comment by Polymega** [comment]
I believe he's referring to the bed at the bottom of the camera. 

All the beds were modeled to only have the top and sides (no bottoms), to save on poly budget. The position of that bed shows that no bottom side was modeled. So it's not that there's no texture there; it's that there's no polygons there.

We can try and address this sometime in the future. Thanks, Storm3000 :+1: 

![sh2pc 2019-12-05 10-50-27](https://user-images.githubusercontent.com/27395260/70251391-6a34fe80-174d-11ea-8fcb-eec93e31e048.png)

**Comment by Polymega** [comment]
I'm going to close this ticket but I have added this to my to-do list for when Phillip finalizes the level editor. Thanks again!
