### ISSUE TITLE
sh2pc.exe does not open - log stays reading d3d8.ini file seemingly infinitely

### ISSUE THREAD

**Issue by Jared20098** [elishacloud/Silent-Hill-2-Enhancements#194]
Hi there. I've been experiencing an issue with SH2 for a while now, which is frustrating me a lot due to me just wanting to play the damn game.

When I open the game, it never actually opens. It goes immediately into the background, and it never actually opens the game, no matter how long I wait.
After some digging, I still can not find the solution to this problem. From what I see in the log file, it begins to read the .ini file, and then it just... stops there. Nothing else happens.

Thank you in advanced.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3947721/d3d8.log)

**Comment by Polymega** [comment]
Hi there, 

Looking at your log file, you're using an older version of the SH2 Enhancements module. This version suffers from a Windows Update bug that will cause severe performance issues with the game, including running in the background as you've mentioned. 

Please watch this video which will describe some of these issues: 
https://www.youtube.com/watch?v=jAIL37IL2uU

You can download the latest version of the SH2 Enhancements module by going here (and downloading the **d3d8.zip** package):
https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

Lastly, consider subscribing/following us on [YouTube](https://www.youtube.com/user/WhereAllBegins) and [Twitter](https://twitter.com/WhereAllBegins) for the latest news and announcements for the project.

**Comment by Jared20098** [comment]
Alright, I did some troubleshooting again. My module and essential files weren't updated, and I finally managed to fix it by updating them manually and replacing the old files. This probably should have been more obvious to me before, but I'm dumb...
