### ISSUE TITLE
need help, i have tried everything 

### ISSUE THREAD

**Issue by camtmann** [elishacloud/Silent-Hill-2-Enhancements#195]
[d3d8txt.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3964593/d3d8txt.txt)

I installed the microsoft visual c++ runtime library 2010 edition and directx. I've tried a combination of different file settings and this is the closest I've gotten. When I try to launch it, it freezes and a "this program has stopped responding" message pops up. I really don't know what to do anymore.

**Comment by Polymega** [comment]
Hi there,
Please attach a copy of your `d3d8.log` file. (Your `d3d8.ini` file was attached instead.) 

You can learn how to show known file extensions by following these steps: https://www.wikihow.tech/Show-File-Extensions-on-Windows

**Comment by camtmann** [comment]
Oh, I'm sorry.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3964635/d3d8.log)

**Comment by Polymega** [comment]
No worries. [Please check out this post,](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/194#issuecomment-564320391) as I'd wager you're having the same problem and the solution is also posted there.

**Comment by camtmann** [comment]
I've installed the files and the same exact problem is happening. It did not work.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3964648/d3d8.log)

Thank you.

**Comment by Polymega** [comment]
Thank you. Now that I can see the full log file, you're having a similar problem due to how/where you have the game saved. [Check out this post for more info.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/179#issuecomment-544001266)

In short: One of your folder names has the trademark (TM) symbol in it which isn't a single-byte character, which causes conflict with our fix.

The easiest thing to do is either remove the trademark symbol from that folder name, or place Silent Hill 2 PC in a cleaner directory, such as `C:\Users\theaq\My Games\Silent Hill 2\`

**Comment by Polymega** [comment]
If that doesn't work, please send me a snapshot of the game's installation directory (so I can see all the files/folders for the game).

**Comment by camtmann** [comment]
It didn't work sadly, but thanks again for being so helpful.

![folder1](https://user-images.githubusercontent.com/58898019/70859002-77cf4e80-1eda-11ea-9521-3fdaa8d81c3b.PNG)

![folder2](https://user-images.githubusercontent.com/58898019/70859004-7bfb6c00-1eda-11ea-8166-065b00b55584.PNG)

**Comment by Polymega** [comment]
Okay, **a lot** of things are incorrect in your directory! That would be the cause of the issues. 

My recommendation? Start from scratch. Here are some tips:

- You game's installation directory needs to ultimately look like this when you're done: http://enhanced.townofsilenthill.com/SH2/#directorytree
- When you download the packages from the install guide, make sure they go in the correct folder. 
   - For example, when you download the "[Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles)", it'll create a new `sh2e` folder in the game's directory. And within that `sh2e` folder will hold other folders/files.
- When you download the SH2 Enhancements module be sure to download the **"d3d8.zip"** package and **not** the "Source code" package.

**Comment by Polymega** [comment]
You want your directory to look like this: 

![image](https://user-images.githubusercontent.com/27395260/70859120-52dbdb00-1edc-11ea-87aa-b8fb04da1737.png)

If you're not using ReShade or a controller you can **exclude**...

```
reshade-shaders\
d3d9.dll
d3d9.log
Dinput.dll
Dinput8.dll
ReShade.ini
ReShade_sh2pc.ini
XInput1_3.dll
XInputPlus.ini
```

... from that list.

**Comment by camtmann** [comment]
IT WORKED!!! thank you so much for walking me through this, you've been so helpful it's incredible. Now I can finally relive SH2 from an enhanced perspective. Thank you so much!!

**Comment by Polymega** [comment]
Great! I'm glad things are working for you now!
