### ISSUE TITLE
crash for the game help please

### ISSUE THREAD

**Issue by kobalex51** [elishacloud/Silent-Hill-2-Enhancements#197]
What I have a problem with is that I get to the kinematics of the emergency door just after my game doesn't respond anymore I can't find the solution, I'm on Windows 10 with all the sh2 patches.

**Comment by kobalex51** [comment]
![image](https://user-images.githubusercontent.com/59045794/71157080-95394b00-2241-11ea-8947-a9ca155306cc.png)

**Comment by kobalex51** [comment]
![image](https://user-images.githubusercontent.com/59045794/71157271-f7924b80-2241-11ea-95f6-57c8153ba862.png)

**Comment by Polymega** [comment]
Hi @kobalex51 ,
Thank you for the provided photos. Can you also take a screenshot of the game's directory for us? (A screenshot of the main folder that holds all the game files)

**Comment by kobalex51** [comment]
hi and yes 
=> 
![image](https://user-images.githubusercontent.com/59045794/71339503-fcae0e00-2553-11ea-8821-11f58a81ce4c.png)

**Comment by kobalex51** [comment]
@Polymega

**Comment by Polymega** [comment]
Hmm... Everything _seems_ fine in your directory, and you're using the latest public build of the SH2 Enhancements module. 

We may need to ask @elishacloud about this, as nothing is coming to mind for me. I believe the next line that would have populated in your `d3d8.log` file would have been for GetDiskSpace.

**Comment by Badore90** [comment]
> hi and yes
=>

The problem occurs using the 1.0 executable too?? I'm asking 'cause I got a freeze with the 1.1 once.

**Comment by kobalex51** [comment]
> > salut et oui 
> > =>
> 
> Le problème se produit en utilisant l'exécutable 1.0 aussi ?? Je demande parce que j'ai eu un gel avec le 1.1 une fois.



> > hi and yes
> > =>
> 
> The problem occurs using the 1.0 executable too?? I'm asking 'cause I got a freeze with the 1.1 once.
the two

**Comment by kobalex51** [comment]
> Hmm ... Tout _semble_ correct dans votre répertoire, et vous utilisez la dernière version publique du module SH2 Enhancements.
> 
> Nous devrons peut-être demander à @elishacloud à ce sujet, car rien ne me vient à l'esprit. Je crois que la ligne suivante qui aurait été remplie dans votre `d3d8.log`fichier aurait été pour GetDiskSpace.

yes please :(

**Comment by kobalex51** [comment]
@Polymega 
yes please :(

**Comment by kobalex51** [comment]
![image](https://user-images.githubusercontent.com/59045794/71541792-99124f00-295e-11ea-8624-dd69e771f1c8.png)

in d3d8 (no d3d9) 

translated : There is something wrong with the disc being used. It may be dirty or damaged.

**Comment by Polymega** [comment]
Did you download and install these packages?
- https://www.microsoft.com/download/details.aspx?id=35
- https://www.microsoft.com/en-us/download/details.aspx?id=5555

Also, do you own a legitimate copy of Silent Hill 2 PC? Or did you download the game somewhere from the Internet?

Can you please take a screenshot of your `data\` folder.

**Comment by elishacloud** [comment]
Closing this out.
