### ISSUE TITLE
Weird transparency bug in Room 302

### ISSUE THREAD

**Issue by rlsprite** [elishacloud/Silent-Hill-2-Enhancements#198]
This is caused by Room312ShadowFix. If disable everything works fine but the flickering shadow returns. My GPU is quite old but it should be more than capable to run this game with no issues (AMD 6950). I'm using up to date drivers for everything and I'm on updated Windows 7 installation. 
![gsT9r79](https://user-images.githubusercontent.com/33965548/71218717-f0e2f300-2298-11ea-92a6-fd65ffd8d53a.jpg)

**Comment by Polymega** [comment]
This is a visual bug that affects certain GPUs from one of our fixes, that we overlooked. It'll be addressed/fixed in the next public update for the project. In the meantime, you can use this development build to fix the issue: https://t.co/7Iq5FRbXHs?amp=1

**Comment by rlsprite** [comment]
That solved the issue. Thank you very much!

**Comment by Polymega** [comment]
Great! Sorry for the inconvenience with that. You can close the ticket if all checks out for you now. :)
