### ISSUE TITLE
Menu Principal are invisible

### ISSUE THREAD

**Issue by yolanda123a** [elishacloud/Silent-Hill-2-Enhancements#20]
Hello
i've have installed european version
and i've used multilanguage exe, and the menu are invisible to start game, 
i dont see "continue", "new game" "option" "exit" etc

**Comment by Polymega** [comment]
Hi @yolanda123a , 
Please open your `language.ini` file and copy + paste the content found within this file here.

**Comment by yolanda123a** [comment]
SET DX_CONFIG_LANGUAGE 5

**Comment by Polymega** [comment]
Thank you. If you change this line to `SET DX_CONFIG_LANGUAGE 1` and re-launch the game can you then see text on the main menu? (It should be in English if it works.)

**Comment by yolanda123a** [comment]
not still invisible
https://imgur.com/a/hGQ74Cx

**Comment by Polymega** [comment]
@yolanda123a if you use the original .exe (that you've backed up) when you installed the game can you see text on the main menu then?

**Comment by yolanda123a** [comment]
yes

**Comment by Polymega** [comment]
Okay, assuming your copy of the game was physically purchased (legitimately obtained), it is fine/safe to use the original executable that was installed with the game. There should be no conflicts with the mod fixes when using an original, legitimate executable. 

If you are able to continue using your originally-installed executable then the issue should be resolved. If we receive more reports on this issue we'll look further into it.

**Comment by yolanda123a** [comment]
but i lose advance option if i use my exe

**Comment by yolanda123a** [comment]
i test with USA version install and run fine in spanish
maybe you need make different exe for EUR  version
is not the same that USA version

**Comment by yolanda123a** [comment]
https://uptobox.com/jx8akqhdnndg

**Comment by Polymega** [comment]
@yolanda123a Can you please send the Director's Cut .exe (the one where you couldn't see text on the main menu)? You can package it in a .ZIP container and upload it here on GitHub. Thanks.

**Comment by yolanda123a** [comment]
i dont see menu with the exe posted in enhanced edition page both exe posted eur or usa
with my EUR disc instalation

**Comment by Polymega** [comment]
Hi @Marcspar , 
To confirm: You can't see the main menu selections when using **either** the North American **or** European executables?

### North American: 
![image](https://user-images.githubusercontent.com/27395260/44872281-12af0580-ac63-11e8-985e-c0659098be91.png)

### European: 
![image](https://user-images.githubusercontent.com/27395260/44872291-1773b980-ac63-11e8-9018-ac98703d2ca9.png)

**Comment by Marcspar** [comment]
I only used Multilanguage Enhanced.exe so far I can download the other one and tell you the results as well.

**Comment by Polymega** [comment]
> I can download the other one and tell you the results as well.

Yes, please, if you don't mind. If it only happens on the multilanguage executable there is possibly a solution we can test (I will send you details later once I am home). 

If you can't see the menu selections on either version, then my theory for a fix probably won't work.

**Comment by Marcspar** [comment]
Yes North American works, Multilanguage does not sadly, I like the font better on that one. Hope this helps you guys on a solution :)

**Comment by Polymega** [comment]
Thank you for the information. 

Would you please set `UseCustomModFolder = 0` in the `d3d8.ini` file and tell me if the multilanguage executable works for you then?

Once you are done testing, be sure to set `UseCustomModFolder = 1` again.

**Comment by Polymega** [comment]
Can you please .zip package and attach your `d3d8.log` file here?

Also, let's do a few more tests:

In the `d3d8.ini` file: 

Set `d3d8to9 = 0`, save changes, launch the multilanguage executable. 

If the main menu selections are still invisible: 

Set `WidescreenFix = 0`, save changes, launch the multilanguage executable. 

Once you perform both of these tests set `d3d8to9 = 1` and `WidescreenFix = 1` again.

**Comment by Marcspar** [comment]
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2337684/d3d8.zip)

Here's the log, changed both settings, and it still didn't work unfortunately.

**Comment by Polymega** [comment]
I was able to replicate the problem but have yet to find a solution. 

This only happens if you install the North American version of the game and then use the European executable in its place. I will report back if/when I find a solution.

**Comment by Polymega** [comment]
@Marcspar @yolanda123a 
[Please download this ZIP package](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2338315/TEST.zip) and place the .mes files in the following folder: 
`\KONAMI\Silent Hill 2\sh2e\etc\message\`

Let me know if that fixes the missing text when using the multilanguage executable.

**Comment by Marcspar** [comment]
It worked I can see the main menu options now ;D

**Comment by Polymega** [comment]
Great!

**Comment by yolanda123a** [comment]
i think is not the same cd instalation european and north american
one is director cut another not is
is different CD

**Comment by Polymega** [comment]
Did the fix I linked above work for you though?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/20#issuecomment-417506612

**Comment by yolanda123a** [comment]
i've reinstall again european version and work with @Polymega package

**Comment by elishacloud** [comment]
Looks like this issue has been resolved.  I am going to close this issue.  If there is still an issue you can reopen it.

**Comment by yolanda123a** [comment]
try solve wine 3d

**Comment by DarkBoxTwo** [comment]
y ya realize los cambios que sugieren, pero no consigo nada

**Comment by Polymega** [comment]
Is your computer using an integrated graphics processor (IGP)? If so, we recommend playing with a dedicated graphics card as older IGPs can't handle the resolution of the HD fonts. You can set `UseCustomFonts = 0` in the `d3d8.ini` file to disable HD fonts.

**Comment by DarkBoxTwo** [comment]
No, it uses a dedicated card, the ATI Radeon X700, and I'm doing fine on performance, except for those issues

**Comment by Polymega** [comment]
It might still relate to the extremely high resolution of the font texture file. If I remember correctly, the HD font texture is over 4000 pixels in one direction. The Radeon X700, released in 2004, may not play nice with an in-game texture that large.

**Comment by DarkBoxTwo** [comment]
No lo creo, ya que solo son el inventario, las selecciones del menu de opciones y las seleciones de cuando esta pausa que no se ven, y de resto si se ven las texturas bien y sin ningun error, sin bajas en los fps
