### ISSUE TITLE
The game hangs upon launch and stop Running 

### ISSUE THREAD

**Issue by Evilscar3** [elishacloud/Silent-Hill-2-Enhancements#204]
When I start the game it shows me the following.

![Error](https://user-images.githubusercontent.com/59951871/72502483-0814f200-37ff-11ea-8497-dac80bc864a7.png)

And it doesn't let me update the files it recommends. 

![Error2](https://user-images.githubusercontent.com/59951871/72502482-0814f200-37ff-11ea-9a2a-efa06e0767cf.png)
I put my .log file and the features of my pc 

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4069821/d3d8.log)

perating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: B450 AORUS PRO WIFI
                     BIOS: F41 (type: UEFI)
                Processor: AMD Ryzen 5 2600 Six-Core Processor             (12 CPUs), ~3.4GHz
                   Memory: 15832MB RAM
      Available OS Memory: 15832MB RAM 

I hope there is a solution 👍

**Comment by Polymega** [comment]
If you set `AutoUpdateModule = 0` in the `d3d8.ini` file will the game launch correctly for you then?

**Comment by Evilscar3** [comment]
Apparently there is an effect that cannot be loaded.
First it shows that you need to load 8 effects but the game stops running and I need to close it.

![Error3](https://user-images.githubusercontent.com/59951871/72505462-97bd9f00-3805-11ea-9e5b-997f57f80da5.png)

Then I start it again and it appears that it is a single effect that cannot be loaded.

![Error4](https://user-images.githubusercontent.com/59951871/72505481-a4da8e00-3805-11ea-8cbc-22ddc7e10031.png)

**Comment by Polymega** [comment]
That has to do with ReShade. First I would set `d3d8to9 = 0` in the `d3d8.ini` file to disable ReShade to see if the game launches then.

If it does launch after disabling `d3d8to9` then I recommend ensuring you've installed the DirectX 9 SDK: https://www.microsoft.com/download/details.aspx?id=35

Either way, can you also include a copy of your `d3d8.ini` file and a screenshot of the game's installation directory on your PC?

**Comment by Evilscar3** [comment]
Well, this is what happened after deactivating the ReShade. The game stops and stops running.

![Error5](https://user-images.githubusercontent.com/59951871/72507864-55e32780-380a-11ea-8463-c37ab34eebd7.png)

This is my game directory.

![Directory](https://user-images.githubusercontent.com/59951871/72507924-6dbaab80-380a-11ea-993a-28d5ff5c512b.png)

Try installing DirectX 9 SDK but the installer tells me that I have a more recent version or equivalent to Directx. "Installation is not necessary" appears on the screen.

and This is my .ini
[D3d8.ini.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4070144/D3d8.ini.zip)

**Comment by Polymega** [comment]
Thanks for the photos. If you **remove** `dinput8.dll` from the directory does the game work then?

**Comment by Evilscar3** [comment]
Nop, 
The game still does not work despite deleting that file.

**Comment by Polymega** [comment]
Okay, one more suggestion. If this doesn't work we might need @elishacloud to help us. 

--------------------

**Remove the following files/folders from the game's installation directory:

Redist\
scripts\
dinput8.dll
Uninstall
Uninstall

------------------------

**Elisha:** In Evilscar3's original post I noticed his mod updater also wanted him to update/download UAL under `dinput8.dll`. I don't believe it should do that? 

He's not using Xinput Plus as he doesn't have the other files that would go with dinput8, so I figured his dinput8 is from UAL?

**Comment by Evilscar3** [comment]
Ok

I already removed the files and ran the game, but immediately stop responding.

My English is not very good. So I don't quite understand what he means with "He's not using Xinput Plus as he doesn't have the other files that would go with dinput8, so I figured his dinput8 is from UAL?"

**Comment by Polymega** [comment]
> My English is not very good.

No worries. You're English is very good. You don't have to worry about that line as it was written for another member of the project to read.

Question for you: How did you get the `Redist` and `scripts` folder in the first place? Did you download an extra, outside package? Did you download the base game somewhere from the internet?

**Comment by Evilscar3** [comment]
hahaha ok thanks

Well, before anything else, before I had an older PC in which the game ran without any problem, this game had a W7, an Intel Pentium at 2.20 GHz with a graphics card zotac geforce gt 9500.

If I remember correctly, those files came with the installation of the base game, before the mod, when installing the base game it already had those files if I remember correctly.

**Comment by Evilscar3** [comment]
OH! WAIT!
I remember, in an attempt to update the files that from the beginning did not let me do it, go to the following page:
http://thirteenag.github.io/wfp
It is assumed that from that page I was going to download the update, according to what it says in the photo of the first post I made.

On this page I searched for "Silent Hill 2" and downloaded some files thinking that would solve it and put them at the root of the game.

**Comment by Polymega** [comment]
Yeah, I know the `dinput8.dll` file and the `scripts\` folder come from http://thirteenag.github.io/wfp. You would **not** use the files from this project... because it is already integrated into our project. :) So if you use both it will likely create conflicts.

I know this isn't fun to hear, but I recommend reinstalling everything and checking to make sure the game still runs after each step.

- Install the base game and ensure it runs. 
- If it runs, install the enhanced executable and ensure it still runs. 
- If it runs, install the SH2 Enhancements module and ensure it still runs.
- ... Etc

**Comment by Evilscar3** [comment]
Alright, I will try to install it from scratch following the instructions on the page, and something goes wrong, I will come back here and comment on what happened.

**Comment by Evilscar3** [comment]
We're back, the game just works, the Redist folder comes with the original game without mods.
Now, notice something and I think it's my mistake, what file of these should I download? 

![version](https://user-images.githubusercontent.com/59951871/72570445-89619880-3882-11ea-8a85-3511780d8b61.PNG)

**Comment by Polymega** [comment]
You will download the **d3d8.zip** package. 

For the next release, I will ask Elisha if we can hide all those downloads within the Assets dropdown list and make just one noticeable Download link. Something like this:

![image](https://user-images.githubusercontent.com/27395260/72570638-73a4a100-388b-11ea-8278-827b4753d106.png)

There have been multiple instances of someone downloading and using the source code instead, which causes launch/performance issues.

**Comment by Polymega** [comment]
Also: 

>  the Redist folder comes with the original game without mods.

That's odd. Do you own a legitimate copy of the game? Or did you acquire the game from a website? We're not here to judge... I'm just curious why your copy of the game includes that folder.

**Comment by Evilscar3** [comment]
I got the game on a website ... To be more precise of a video on YouTube that explained how to install it.
Reinstall the game, the game itself works fine, starts and runs well, but when installing the entire mod generates the same errors as mentioned above ...
Do you think it is because of the base game because it is not a "legitimate copy"?
It's strange, since this same copy used on my old PC with W7.

**Comment by Evilscar3** [comment]
On this occasion, I followed the instructions mentioned in the official page of the mod, change the configuration of the auto update in the .ini file but the error is repeated.

**Comment by Polymega** [comment]
> To be more precise of a video on YouTube that explained how to install it.

Can you please share a link of where you obtained it?

> but when installing the entire mod generates the same errors as mentioned above ...

Did you try running the game after installing each package from the steps outlined in the installation guide? If so, at what point did it stop working?

> Do you think it is because of the base game because it is not a "legitimate copy"?

Most likely. You shouldn't have folders/files such as `Uninstall, dinput8.dll, Redist/, and scripts/`. If you never used our project before on your Win7 machine, that is likely why you didn't have these issues before. When using our project files, something is likely creating conflict with the copy of the game you found from the internet.

**Comment by Evilscar3** [comment]
Hi, it's me again, reinstall the game, it worked fine. I installed the SH2 Enhancements Module and ran the game, it started fine but I jumped the message to update the d3d8.ini file. He put it up to date and immediately got updated and gave me the option to restart the game, by doing so I start normally.

![OVNI](https://user-images.githubusercontent.com/59951871/72583622-8da2ab80-38ac-11ea-98a6-b3b3b860b3cf.png)

At the moment, just install the Enhancements Module, as soon as you install the other parts, I will report what happened.

**Comment by Evilscar3** [comment]
Well, I think I found the error in this, as soon as I installed all three IndirectSound files, the game stopped working. If I remove them, the game works normally. I attached the file that was generated as soon as I ran the game with the IndirectSound already installed.

Enhanced Executable Ok
Enhancements Module Ok
Enhanced Edition Essential Files OK
IndirectSound ERROR

[dsound.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4075018/dsound.log)

**Comment by Polymega** [comment]
Okay, good! That's progress! 

IndirectSound requires Microsoft Visual C++ 2010 runtime library to run. If you haven't downloaded it already, be sure to do so and then see if IndirectSound will work for you: https://www.microsoft.com/en-us/download/details.aspx?id=5555

If it still doesn't work for you, you can opt to play without IndirectSound. You should still have a good experience without it.

**Comment by Evilscar3** [comment]
Well, in the end the IndirectSound didn't work, I already installed Audio Enhancement Pack and ReShade & Filters and it seems to work.
Check and I already have the version of Microsoft Visual C ++ 2010 but still those IndirectSound files do not work. At least I can play and with excellent graphics quality. Thank you very much for the help and time given to my problem. May the Force be with you

**Comment by Polymega** [comment]
I'm glad it all worked out. :)

**Comment by elishacloud** [comment]
Closing this out.
