### ISSUE TITLE
Game Worked Upon First Launch, But Second Time Around It Won't

### ISSUE THREAD

**Issue by Swangtheugly** [elishacloud/Silent-Hill-2-Enhancements#208]
Hey, clueless user here. I installed the Europe Version of SH2 and followed all steps correctly,  but with that the game worked the first time around in which I fiddled with the resolution with what was already available. After that I started a new game and this is what I found.

- No In-Game Audio besides footsteps.
- FMV Audio Worked 

I just presumed that I messed up Audio Enhancement's so I went fixed it by messing with SH2E folder where it was suppose to go correcting what I did originally.

Unfortunately upon loading the game I get told that the game crashed my previous time playing and that it will revert to safe settings. This would follow by a black screen and then Japanese Text.

![SH2PC Title 1_28_2020 6_28_05 PM](https://user-images.githubusercontent.com/60411889/73315352-dab44500-41fd-11ea-84dd-ce73dadd8a78.png)

![screenshot-translate yandex com-2020 01](https://user-images.githubusercontent.com/60411889/73315342-d38d3700-41fd-11ea-9e49-ee8e26fa09e0.png)
 
D3D8:

25744 17:50:55.465 Starting Silent Hill 2 Enhancements! v1.3.1365.0
25744 17:50:55.466 ASUSTeK COMPUTER INC. TUF Gaming FX505DT_FX505DT 1.0 (Notebook)
25744 17:50:55.466 ASUSTeK COMPUTER INC. FX505DT 1.0 (Notebook)
25744 17:50:55.466 "AMD Radeon(TM) Vega 8 Graphics"
25744 17:50:55.466 Windows 10 64-bit (10.0.17763) 
25744 17:50:55.467 "sh2pc.exe" (PID:24248)
25744 17:50:55.467 Running from: "C:\Program Files (x86)\Konami\Silent Hill 2\sh2pc.exe"
25744 17:50:55.467 Config file: "C:\Program Files (x86)\Konami\Silent Hill 2\d3d8.ini"
25744 17:50:55.467 Loading as dll: "d3d8.dll"
25744 17:50:55.470 Wrapper created for "d3d8.dll"
25744 17:50:55.668 Hooking the FileSystem APIs...
25744 17:50:55.668 Hooking the CreateProcess APIs...
25744 17:50:55.668 DisableCDCheck searching for memory address!
25744 17:50:55.672 DisableCDCheck Error: Could not find CD check function address in memory!
25744 17:50:55.672 Finding SFX file locations...
25744 17:50:55.823 Updating SFX memory address locations...
25744 17:50:55.823 Allocating memory buffer for sddata.bin file...
25744 17:50:55.823 Setting 2TB hard disk Fix...
25744 17:50:55.823 Setting PS2 Style Noise Filter...
25744 17:50:55.823 Increasing the Draw Distance...
25744 17:50:55.823 Setting Cemetery Lighting Fix...
25744 17:50:55.823 Setting Rowboat Animation Fix...
25744 17:50:55.823 UpdateCatacombsMeatRoom Could not load fix.  This fix requires 'UseCustomModFolder' enabled and custom map files 'ps189.map' and 'ps193.map'.
25744 17:50:55.823 Updating Fog Parameters...
25744 17:50:55.823 Setting Piston Position Fix...
25744 17:50:55.823 Hiding Red Cross health indicator during cutscenes...
25744 17:50:55.823 Enabling PS2 Flashlight Fix...
25744 17:50:55.823 Enabling Lighting Transition Fix...
25744 17:50:55.823 Enabling XInput Vibration Fix...
25744 17:50:55.823 UpdateCustomFonts Error: Could not find font file
25744 17:50:55.824 UpdateCustomExeStr Error: Could not find text file
25744 17:50:55.830 Loading the "Nemesis2000 Fog Fix" module...
25744 17:50:55.830 LoadModuleFromResourceToFile Error: "Nemesis2000 Fog Fix" module could not be written!
25744 17:50:55.830 LoadModuleFromResourceToFile Error: failed to load "Nemesis2000 Fog Fix" module!
25744 17:50:55.833 Loading the "WidescreenFixesPack and sh2proxy" module...
25744 17:50:55.833 LoadModuleFromResourceToFile Error: "WidescreenFixesPack and sh2proxy" module could not be written!
25744 17:50:55.833 LoadModuleFromResourceToFile Error: failed to load "WidescreenFixesPack and sh2proxy" module!
25744 17:50:55.835 Loading the "modupdater" module...
25744 17:50:55.835 LoadModuleFromResourceToFile Error: "modupdater" module could not be written!
25744 17:50:55.835 LoadModuleFromResourceToFile Error: failed to load "modupdater" module!
25744 17:50:55.835 Silent Hill 2 Enhancements module loaded!
25744 17:50:57.132 Starting D3d8to9 v1.9.2.0
25744 17:50:57.132 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
26180 17:51:01.951 Setting SingleCoreAffinity...

Thanks!

**Comment by Polymega** [comment]
Hi @Swangtheugly ,
Could you also share a screenshot of your game's installation directory? And also a screenshot of the contents within your `sh2e` folder?

**Comment by Swangtheugly** [comment]
Don't know if it is 100% but here it is. 

![Silent Hill 2 1_28_2020 6_57_40 PM](https://user-images.githubusercontent.com/60411889/73316173-2962de80-4200-11ea-857c-f908ca47ed54.png)
![Silent Hill 2 1_28_2020 6_57_47 PM](https://user-images.githubusercontent.com/60411889/73316178-2bc53880-4200-11ea-83a7-485f48fc5513.png)
![Silent Hill 2 1_28_2020 6_58_08 PM](https://user-images.githubusercontent.com/60411889/73316184-2ec02900-4200-11ea-9da4-d79ddd7cff0a.png)

**Comment by Polymega** [comment]
Thanks for the screenshots. When you downloaded the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles), those files should have went into your `sh2e` folder. The `sh2e` folder should look something like this: 

![image](https://user-images.githubusercontent.com/27395260/73316582-4c41c280-4201-11ea-9464-ec2b3c3b6590.png)

By chance, when you downloaded the Essential Files, did you move them into your `data` folder instead? If so, that might be causing the issues. The `data` folder holds all of the original, untouched vanilla PC game files. The `sh2e` folder holds our improved files (and our project will use files from `sh2e` first, if available), so as not to overwrite any original game files.

**Comment by Swangtheugly** [comment]
Okay, I'll do a fresh install and follow the screenshot.

**Comment by Polymega** [comment]
Sure thing, let us know how it goes. As a recap: 

After installing the base game, you won't touch anything within the `data` folder. When you download the Essential Files package, it'll create a `sh2e` folder in the game's directory (with its own files in it). Then, when you download the FMV and Audio Enhancement packs, additional files from these packages will also go in the `sh2e` folder.

You will change the resolution for the game in the `d3d8.ini` file (change [ResX and ResY](http://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY)). You **won't** change the game's resolution from the game's options menu. In the upcoming update for our project, we will prevent you from changing the resolution in the game's option menu and also have it show the **true** resolution you are using.

**Comment by Swangtheugly** [comment]
Fresh Install:

![Silent Hill 2 1_28_2020 7_41_41 PM](https://user-images.githubusercontent.com/60411889/73318066-439fbb00-4206-11ea-89ee-dc2a8d6c906f.png)
![Silent Hill 2 1_28_2020 7_41_49 PM](https://user-images.githubusercontent.com/60411889/73318071-46021500-4206-11ea-82a8-39f97fda2fd3.png)

**Comment by Polymega** [comment]
Yes, because you installed the game to an administrator-protected directory (`Program Files`) you will need to run the game as adminstrator in order to save your game progress. Do the following: 

- Go to `<path-to-game>\Silent Hill 2\data\save\`
- If you have a `Folder 01` folder inside your `save` folder, **delete** the `Folder 01` folder
   - If you do **not** have a `Folder 01` folder inside your `save` folder, skip this step.
- Go to `<path-to-game>\Silent Hill 2\`
- Right-click `sh2pc.exe` and select **Properties**.
- Go to the **Compatibility** tab.
- Check/enable the **Run this program as an adminstrator** checkbox.
- Apply changes.

**Comment by elishacloud** [comment]
Closing this out.
