### ISSUE TITLE
certain aspects of mods not working for me

### ISSUE THREAD

**Issue by mugmonster** [elishacloud/Silent-Hill-2-Enhancements#21]
I'm missing the fog overlay at the observation deck, which is one of the fixes WineD3D is supposed to fix, but I know wine is working in other ways because the tunnel is properly black.  Also the reshade filter doesnt seem to be active, it's not letting me take screenshots or anything.  There might be some other issues I'm experiencing but I'm not entirely certain; for instance, the screenshot for the grammar fixes shows James commenting on Laura's graffiti, but when I'm at that wall it doesnt even let me interact, also in the room with the dead guy in front of the TV it wasnt playing the right background music until I went to another area with music and came back.  I was told by the person who made the youtube demonstration video to include a screenshot of my game folder

![directory](https://user-images.githubusercontent.com/42703230/44622141-fb49d400-a880-11e8-9eec-9fecc44de997.png)

**Comment by mugmonster** [comment]
hmm I thought that room's music worked differently.  when you first enter it before pyramid head appears, it sounds sort of like a clock, but when pyramid head is there and you see the dead body the music is more tense.  for me, it was playing the clock music even when I left and re-entered, until I went to a different floor and came back, you're saying that's how it's supposed to be?

well anyway, here's the files
[d3d8check.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2321022/d3d8check.zip)

**Comment by Polymega** [comment]
Thank you. Hmm, so WineD3D doesn't seem to be working yet the white shaders bug is still fixed for you. If you temporarily remove the `d3d9.dll`, `wined3d.dll`, and `libwine.dll` files from the game's directory is the fog then restored (and the white shaders bug still fixed)?

**Comment by mugmonster** [comment]
nope, that brings the white shaders bug in without fixing the fog

**Comment by mugmonster** [comment]
it says it "determined a newer version is installed already, no installation necessary."  and isnt wine opengl anyway?

**Comment by Polymega** [comment]
Yes, it converts DirectX games to OpenGL. @elishacloud , sorry to get you involved, but would have any ideas on this?

**Comment by elishacloud** [comment]
> isnt wine opengl anyway?

Yes, but we are using the Direct3D9 version of WineD3D and the game is running under Direct3D8.  So we need to convert from Direct3D8 to Direct3D9 and then WineD3D can get enabled.

It looks like this:

```text
sh2pc --> d3d8 --> d3d9 --> WineD3D --> ReShade --> OpenGL
```

We need DirectX 9 SDK for this step here:  `d3d8 --> d3d9`

As far as the issue where you are missing the fog overlay at the observation deck, it looks like an issue with WineD3D.  I am already working to try and [remove the need for WineD3D](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/10), but that is still a ways off.

**Comment by elishacloud** [comment]
Can you go the Advanced Settings and make sure that `Fog` is set to `Complex`?

![advanced settings](https://user-images.githubusercontent.com/25625456/44623857-6f8b7400-a88f-11e8-975a-50dd23e69f9c.png)

**Comment by mugmonster** [comment]
it's definitely set to complex

**Comment by Polymega** [comment]
@mugmonster did you happen to update ReShade by chance? While not identical to your problem, another user had similar issues to where certain aspects of ReShade weren't working and determined it was due to updating ReShade: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/24

**Comment by mugmonster** [comment]
I only downloaded what was on the page (http://enhanced.townofsilenthill.com/SH2/files/SH2PC_ReShade_3.4.0_OpenGL.zip), I wouldnt even know this could be updated without any kind of prompt.  also that person was still getting the white tunnel which I'm not, so wined3d seems to be doing Something

**Comment by mugmonster** [comment]
ah I dont mean to come off as impatient, I'm not in a rush with this or anything, I'm just trying to answer troubleshooting questions as they come up

**Comment by Polymega** [comment]
No, you didn't come off like that at all. :) WineD3D For Windows has been a pain in our sides for years now. As mentioned on the [ticket](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/10) about this, the majority of issues people come to us about when following the Installation Guide stems from implementing WineD3D. It'll be a great day once we can remove our need for this fix!

**Comment by mugmonster** [comment]
I only just noticed that elishacloud asked for screenshots the last time I was here.  while I dunno if they'll help at this point, I probably should've provided some to begin with 
![20180905130404_1](https://user-images.githubusercontent.com/42703230/45109428-893d7e80-b10d-11e8-84ef-da1b1c357c67.jpg)
![20180905130413_1](https://user-images.githubusercontent.com/42703230/45109429-89d61500-b10d-11e8-8d32-a3501ca61062.jpg)

compare those with screenshots from the youtube demonstration video (although while taking these shots I realized the fog is subtle and difficult to see when not in motion) 
![fogtest1](https://user-images.githubusercontent.com/42703230/45109471-a8d4a700-b10d-11e8-8413-da06761f16cc.jpg)
![fogtest2](https://user-images.githubusercontent.com/42703230/45109472-a8d4a700-b10d-11e8-9b6e-2666e50bb207.jpg)

so yeah, black tunnel is there, fog is not, despite those both being related to wined3d

also I had to launch through Steam to take screenshots since I dont have the reshade option, and I noticed that when playing through Steam the game crashes when I try and open the Options menu, both when I do it in the middle of the game and through the start menu.  I assume this has something to do with XInputPlus, because I dont get the chime indicating it's working when I load through steam, so I'm guessing there's some mixup with my controller mapping.  it doesnt crash when I just open it up from the game's folder

**Comment by AeroWidescreen** [comment]
@mugmonster Have you tried enabling SteamCrashFix in the ini? It's in the [MISC] section.

**Comment by mugmonster** [comment]
oh right, I completely forgot that was a setting because it isnt one of the ones enabled by default, thanks lol

**Comment by elishacloud** [comment]
@mugmonster, I just added a fix for the 2D fog issue on Nvidia.  You can download the patch for that here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2432138/d3d8.zip)

**Comment by mugmonster** [comment]
that did the trick! all that work for such a subtle effect but I appreciate it!

**Comment by elishacloud** [comment]
Glad that worked for you!  Are you still having any other issues or can we close this case out?

**Comment by mugmonster** [comment]
I completed my first playthrough the other day and didnt notice anything else.  there was one instance of the ambient music skipping which I guess means the single core affinity isnt foolproof, but it went away as soon as I went to another area and loaded a different track

**Comment by elishacloud** [comment]
Yeah, the audio skipping is some thread deadlock issue.  The single core affinity is just a band aid.  However it works most of the time.  I will close this for now.  If you have any other issues you can reopen or file a new case.  Thanks.
