### ISSUE TITLE
Issues with reshade

### ISSUE THREAD

**Issue by eight85** [elishacloud/Silent-Hill-2-Enhancements#210]
Clean install and slowly added everything from the guide. I have narrowed it down to the reshade 4.5.3 and this prevents me from playing. Once i remove it, it works fine. Does anyone have any advice or older/newer builds of reshade to try?

**Comment by Polymega** [comment]
Are you using a laptop with integrated graphics, or an older/weaker PC? ReShade can be too demanding for such computers, and we advise you remove ReShade, if that's the case.

**Comment by eightbitbang** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4150975/d3d8.log)

i posted the d3d8 txt file

**Comment by Polymega** [comment]
You're definitely not using integrated graphics! That's a beefy GPU you have.

You can try the previous version of ReShade we provided on the installation site, to see if that works. Replace the files/folders, when prompted:

http://www.enhanced.townofsilenthill.com/SH2/files/SH2PC_ReShade_4.4.2_DirectX9.zip

If that still doesn't work, can you send a snapshot of the game's installation directory on your computer?

**Comment by eight85** [comment]
<img width="768" alt="sh2pcdir" src="https://user-images.githubusercontent.com/60632993/73707490-5c561800-46c1-11ea-9304-36f70cd9e260.png">

I tried using 4.4.2 with same results. Just goes to a white screen and then crashes

**Comment by AeroWidescreen** [comment]
Aren't the drivers for that graphics card a mess? Wouldn't be surprised if that had something to do with it.

**Comment by Polymega** [comment]
> Hopefully you'll be able to resolve your issue, but losing ReShade isn't a big deal last time I checked. The difference is subtle and you can get better AA through your control panel.

Indeed. The main reason we instruct people to use ReShade is for its anti-aliasing feature. The "drag-and-drop" methodology behind ReShade makes it easier for users to follow to get anti-aliasing benefits. The other effects ReShade provides for our project are very subtle things that have no major impact on the experience, as Aero_ mentioned.

So ReShade is not critical to have/use with our project. If you're comfortable with it and know how, you can remove ReShade and force anti-aliasing through your AMD GPU control panel. Or, you can try updating your GPU drivers to see if that would allow you to then use ReShade.

Worth mentioning: A future goal of this project is to include built-in anti-aliasing, so we wouldn't have to be reliant on ReShade (or instuct the user on how to force AA through their GPU CP).

**Comment by Badore90** [comment]
> Hopefully you'll be able to resolve your issue, but losing ReShade isn't a big deal last time I checked. The difference is subtle and you can get better AA through your control panel.
> 
> Indeed. The main reason we instruct people to use ReShade is for its anti-aliasing feature. The "drag-and-drop" methodology behind ReShade makes it easier for users to follow to get anti-aliasing benefits. The other effects ReShade provides for our project are very subtle things that have no major impact on the experience, as Aero_ mentioned.
> So ReShade is not critical to have/use with our project. If you're comfortable with it and know how, you can remove ReShade and force anti-aliasing through your AMD GPU control panel. Or, you can try updating your GPU drivers to see if that would allow you to then use ReShade.
> Worth mentioning: A future goal of this project is to include built-in anti-aliasing, so we wouldn't have to be reliant on ReShade (or instuct the user on how to force AA through their GPU CP).

What about Ps2-like colors and basic levels, you already found a way to adjust them internally??

**Comment by Polymega** [comment]
> What about Ps2-like colors and basic levels

These adjustments are _incredibly_ subtle and not worth keeping ReShade around if we can create our own anti-aliasing feature. It's the smarter choice to remove ReShade from the installation process. 

Of course, you can continue to use ReShade if you want; you can disable its SMAA filter and keeping using the color/level balancers.

**Comment by Badore90** [comment]
> These adjustments are incredibly subtle and not worth keeping ReShade around if we can create our own anti-aliasing feature. It's the smarter choice to remove ReShade from the installation process.

It seems not that subtle to me. With the Re-shade adjustment the color temperature is visibly colder (as on Ps2) and the picture is considerably darker (also the noise filter is affected in a good way, not lighting up dark areas too much).
Btw I agree that's not a fundamental thing, plus it's possible to still use Re-Shade as you said.

At least, putting Re-Shade out you won't have to make an update once every two days :D

**Comment by Polymega** [comment]
> At least, putting Re-Shade out you won't have to make an update once every two days :D

The purpose is: ReShade is the most common reason why people can't launch the game. Whether it's because their PC can't handle it, or their's some sort of incompatibility with their specific GPU.

It's not worth the headache of keeping if we can make our own AA solution.

**Comment by Badore90** [comment]
> The purpose is: ReShade is the most common reason why people can't launch the game. Whether it's because their PC can't handle it, or their's some sort of incompatibility with their specific GPU.
> It's not worth the headache of keeping if we can make our own AA solution.

For the PC not powerful enough matter, it'd be a good thing to default the re-shade settings with just the 2 color boxes enabled. 

Actually enabling or disabling the AA doesn't make a much noticeable difference. With AA off the picture detail is crisper (the ginning is very difficult to notice).
But indeed I prefer to enable the AA to have the image a little blurrier (it reminds me alittle more of the Ps2 version dirtiness).

My current PC can handle Re-Shade with all enabled up to full-hd resolution. The aliasing is not a problem at all in this game imho. But I know there can be people with different needs.

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
