### ISSUE TITLE
Using AI Networks for upscaling FMV

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#215]
The idea of upscaling static images is excellent. What about upscaling the videos too? I know it doesn't work well frame-by-frame because of blurring movement on each frame. But now there are programs like Topaz Gigapixel AI for Video that handle video very well. Has anyone tried them? There are also plugins that makes frame doubling with adding new interpolated frames, so that we could get full 60fps videos.

**Comment by Psycho-A** [comment]
Did some comparsions using Topaz Sharpen AI. For me, results are really good.
http://www.framecompare.com/image-compare/screenshotcomparison/J2MMCNNU

**Comment by Polymega** [comment]
> Did some comparsions using Topaz Sharpen AI. For me, results are really good.

[On a per-frame basis Topas Gigapixel looks good.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/13#issuecomment-570749811) But when all the frames are put back together in motion, not so much. 

You can read my notes on using Gigapixel for the FMVs here (along with some AI upscaled, finished FMV examples): https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/13#issuecomment-575954651

**Upscaling:**
I think using something like [ESRGAN](https://github.com/xinntao/ESRGAN) is probably the best way to go, in terms of AI upscaling. But you'd also need time to train a model to understand SH2 FMV's "look and feel" to get any worthwhile results, or find someone already comfortable with ESRGAN to train a model for us.

**Interpolation:**
I personally haven't looked too much into the best interpolation methods, but [DAIN](https://sites.google.com/view/wenbobao/dain) looks to the current state-of-the-art method.

And to anyone else who might read this thread: It's worth reiterating again that the PS2 videos are not true 60 frames per second. [A brief recap of that can be read here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/214#issuecomment-586518038)

**Comment by Psycho-A** [comment]
"But when all the frames are put back together in motion, not so much."
-- That's what I'm talking above. There are special Topaz AI version for videos (Topaz Video Enhance AI, formerly Topaz Gigapixel for Video) that have models optimized for motion pictures. I couldn't make it work on my old PC, but I tried early online demo versions before, and results are impressive.

Also, I tried to process about 4 seconds of Intro video using Sharpen AI tool (for static images) and results are good for motion pictures if we're using "Sharp" preset. It adds details very accurately, not touching blurred areas, and there are no big differences between frames unlike Gigapixel AI or ESRGAN. The only lack is the program have no batch processing, so every frame needs to be processed manually.

**Comment by Polymega** [comment]
I've read a little about Topaz Video Enhance AI (it's still new/in beta), but haven't tried it myself yet.

> but I tried early online demo versions before, and results are impressive.

Did you try it specifically with a SH2 FMV? I would love to see the results of your test.

I think it's only a matter of time until we properly address AI upscaling for the FMVs. As you said, we just need to find the right toolset for the job. Whether that be Topaz Video Enhance, ERSGAN, or something completely different.

> The only lack is the program have no batch processing, so every frame needs to be processed manually.

Yes... this was a pain in my ass when doing the test videos using Gigapixel!

**Comment by Badore90** [comment]
**@Polymega** You know perhaps if there's a Pc version 60fps interlaced FMV pack online?? If it exist I'd like to try it out on the HD CRT at 1080i.

**Comment by Polymega** [comment]
I don't believe there exists a BINK 30i/60i format of the FMVs.

**Comment by Badore90** [comment]
> I don't believe there exists a BINK 30i/60i format of the FMVs.

I see. Thank you.

**Comment by Polymega** [comment]
We're dabbling [with AI upscaling for a new FMV Enhancement Pack update coming soon](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/402#issuecomment-805399613). Given the nature of the native video files (their resolution, grittiness, and "CG-ness") only so much can be done with them, but we're able to give a slight bump to their quality for this next update.
