### ISSUE TITLE
Minor issue with soft shadows

### ISSUE THREAD

**Issue by Bruno3589** [elishacloud/Silent-Hill-2-Enhancements#216]
Hi everybody,
so today I started a new game with the updates, both to enjoy the gamplay with the new updates and to test my translation.

While playing I came across a fairly minor issue with the new shadow work.
I'm in the apartment building and I just acquired the torch.
The thing I noticed is, when you do quick turns, the area behind you suddenly "switches" from the torch's shadow to the ambient one, without a transition.

I made a small demonstration video here: https://youtu.be/aca0vt-M9Vg
Notice how the kitchen suddenly "switches" from black to dark.
I also tested in other areas and I can confirm it's not tied to a specific location (e.g. it also happens when you enter a room, the previous one does the same "switch").

I'm no expert but it looks like this can't be fully fixed, but maybe there's a way to add at least some kind of fade so the transition becomes less noticeable?

Apart from that, the new shadows really look amazing. Great work!

**Comment by Polymega** [comment]
Nothing to be concerned over; this is normal shadow behavior/logic for the game. :)

SH2's shadow programming was amazing for its time, but it's not perfect.

**Comment by Bruno3589** [comment]
> Nothing to be concerned over; this is normal shadow behavior/logic for the game. :)
> 
> (**Edit:** As in, this is normal behavior for all versions of the game.)

Thought so... As I said, this is a minor issue, so no big deal, I just thought it was wort a shot.

> SH2's shadow programming was amazing for its time, but it's not perfect.

Yes, at the time it was really on another level compared to other games. I remember playing it in the dark on a CRT TV...
