### ISSUE TITLE
Endgame save bug

### ISSUE THREAD

**Issue by Bruno3589** [elishacloud/Silent-Hill-2-Enhancements#217]
Hi,
sorry to bother you again, I promise this one's the last for today.

I randomly found out another weird and quite funny bug with an endgame save.
If I load the save from the main menu, the game stats show correctly. However, if I load the save while playing, here's what happens: https://youtu.be/n8uVWixvdus
After this, the game becomes unresponsive and I have to force close it.

Now, this obviously need further testing, but here's 2 quick observations:
- The location seems to be from the Leave ending, which is the ending I got in that save;
- The equipped item is carried over from the final boss battle (I wanted a more "dramatic "ending so for the last hit I used the Great Knife)

**Comment by Polymega** [comment]
This is a critical bug to fix that's on our to-do list. We just need to find the right person to look into this one, as it seems to be a more involved/complicated thing to address: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/47

**Comment by Bruno3589** [comment]
Ah sorry, didn't see there already was an open issue. I'll go on and close this one then, no need for duplicates :)

Thanks anyway!
