### ISSUE TITLE
I cant seem to make this mod work

### ISSUE THREAD

**Issue by Smersh12** [elishacloud/Silent-Hill-2-Enhancements#22]
Yes, I have carefully read the instructions numerous times, and followed everything to the letter, skipped the Wine and XInput part, as I dont plan on using a pad and my notebook uses an Intel HD 3k card
But no matter how many times I try and what configuration I try, the game either crashes on startup or straight up nothing happens when I try to launch, nothing on the troubleshooting guide helped, either, what else can I do?
Thanks in advance

**Comment by Polymega** [comment]
Thank you. Looking at the log file it seems to get hung while trying to load the Widescreen Fix/sh2proxy fixes. In the `d3d8.ini` set `WidescreenFix = 0` and re-launch the game. Does it boot up now?

This will disable the Widescreen Fix fixes but we're temporarily disabling it just to see if the game will now launch.

**Comment by Smersh12** [comment]
Yes, the game launches now

**Comment by Polymega** [comment]
Okay, try this for me: 

1.  [Install DirectX 9 SDK](https://www.microsoft.com/download/details.aspx?id=35)
2. Set `WidescreenFix =` back to `1` in your `d3d8.ini` file
3. Launch the game and wait at least 60 seconds before attempting to force close the game

**Comment by Smersh12** [comment]
The DirectX installation didnt go through, with a message saying that a more recent or equivalent version is already installed

**Comment by elishacloud** [comment]
@Smersh12, can you try using the following files:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2321138/d3d8.zip)

Just do the following:
1. Unzip these into your `Silent Hill 2` game folder.
2. Start the game.
3. If it still crashes please send me the updated `d3d8.log` files.

**Comment by AeroWidescreen** [comment]
> Have you had any reports of people on Windows 8 running into any hiccups launching the WSF?

Not that I recall, no. There was that issue with SingleCoreAffinity not working on Windows 7; I don't know if that affects Windows 8 as well. He could also try using the stable build of the widescreen fix and see if that works, but I'll leave you and Elisha to decide what's best here.

**Comment by Smersh12** [comment]
@elishacloud 
It crashed
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2321628/d3d8.zip)

**Comment by elishacloud** [comment]
@Smersh12, thanks for the log file.  It looks like it is crashing after the Widescreen module is loaded and initialized.  Which exe file are you using?  Are you using one of the exe files from the [Installation Guide](www.enhanced.townofsilenthill.com/SH2/)?

@AeroWidescreen, I added some log entries into the module to see where it is crashing.  Here are the log entries I added:

```text
12:22:56.496 WidescreenFixesPack and sh2proxy module loaded...
12:22:56.496 Getting 'InitializeASI' function Address...
12:22:56.496 Running 'InitializeASI' function...
12:22:57.310 'InitializeASI' function finished!
```

You can see that it is able to load the module and call the initialization routine.  I am pretty sure this is an issue somewhere in the WSF module.

**Comment by AeroWidescreen** [comment]
@Smersh12 
It's recommended you use the exe provided in the installation guide. Make no further modifications to it. If you're already doing that then here's a few things you can try:

Try changing all features of the widescreen fix to **0** and see if that makes a difference. The features are located in d3d8.ini's [MAIN] and [MISC] sections. Does it work? No? Okay then, try this:

1. Use **WidescreenFix = 0** in d3d8.ini. 
2. Download the widescreen fix [here](https://github.com/ThirteenAG/WidescreenFixesPack/releases/download/sh2/SilentHill2.WidescreenFix.zip)
3. Extract the archive and move the **scripts** folder to your SH2 install directory. DO NOT use dinput8.dll, ignore it.
4. Use **LoadPlugins = 1** in d3d8.ini
5. Launch the game and tell us if it works.

**Comment by AeroWidescreen** [comment]
@elishacloud @Polymega  I just had an issue with the game freezing on launch due to the widescreen fix. It had something to do with SingleCoreAffinity and Malwarebytes not liking it.  Maybe this is what's happening to @Smersh12 as well? Wish he would respond.

Anyway, this problem only occurred with the DC and v1.1 executable. v1.0 always worked.

**Comment by elishacloud** [comment]
Looks like the code is setting SingleCoreAffinity after some threads may have already started up.  This can cause a race condition here.  Antivirus programs, such as Malwarebytes, can change the load timing and cause this kind of issue.

My suggestion would be to set this in `APIENTRY DllMain()`, which will be run **before** any other thread starts up, since in SH2 d3d8.dll is a statically loaded DLL.  This reduces the chance of a race condition and will likely prevent it from freezing on launch.

I will implement this in my module, no need to change Widescreen Fix.

**Comment by elishacloud** [comment]
@AeroWidescreen, Try this one out, see if the freeze with Malwarebytes goes away:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2351455/d3d8.zip)

**Comment by AeroWidescreen** [comment]
@elishacloud Unfortunately, no. It's the same as before: sometimes it works, sometimes it doesn't. If try to launch the game 5 or 6 times, it always freezes at least once.  Disabling Malwarebytes or SingleCoreAffinity always fixes it.

Either way I think adding an AV exclusion to the install folder might be a good recommendation.

**Comment by Kernee** [comment]
Sorry if I'm resurrecting this thread (also want to say thank you for all the work on this mod), but I'm having a similar problem where the game will hang on a white screen when loading the game.

I tried the various fixes mentioned in this thread and the referenced threads with no luck.

After some messing around with the d3d8.ini file I've found that, for me, it looks like if I set WidescreenFix = 1 and d3d8to9 = 1 I get the hang, but if I set one (or both) of those values to 0 I don't get the hang.

I tried using the plugin to load the widescreen fix script while having d3d8to9 = 1 and WidescreenFix = 0 , but that also hangs.

Here are the different log files based on the different configurations I made to those two settings.
[logs.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2444228/logs.zip)

**Comment by Kernee** [comment]
Hi @elishacloud @Polymega 
Tried the SingleCoreAffinity = 0 fix and was still getting the hang. Set that back to 1 and deleted the WineD3D files you mentioned and ensured d3d8to9 = 1 and WidscreenFix = 1 were active in the d3d8.ini file. The game loaded then. 
So it looks like it may be WineD3D related. I'll keep track of the fix progress in that other thread. 

Thank you!

**Comment by elishacloud** [comment]
@Kernee, glad you figured it out.  I already put in a fix for the 2D fog issue and the white shader issue.  You can download the patch here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2432138/d3d8.zip)

**Comment by Kernee** [comment]
Awesome. Thank you @elishacloud

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.
