### ISSUE TITLE
FMV 16:9 filling (Update 4)

### ISSUE THREAD

**Issue by Richard-L** [elishacloud/Silent-Hill-2-Enhancements#220]
Whilst I'm usually in total awe and fascination of the things you do, this update had a couple of unpleasant surprises for me. I wanted to voice this particular concern with the FMVs.

I've watched this part of the video three times, but just to be sure that I understand correctly: you've scaled the video until it filled the width of a 16:9 aspect, and then cropped the extending top and bottom parts away?

If that's true I am personally very against this, as you are essentially removing a part of the original SH2 footage, and the FMVs look wrongfully zoomed in as the framing intended by Team Silent is violated.

Please consider making this optional, perhaps via a boolean in the config file you mention for CPU core count.

Many thanks

**Comment by Polymega** [comment]
Thank you for the kind words, and I'm sorry you feel personally violated by any FMV changes.

We can look into making this a toggle feature in the future. We're not done with FMV work anyways, so nothing is set in stone for them at the moment.

**Comment by Badore90** [comment]
> Thank you for the kind words, and I'm sorry you feel personally violated by any FMV changes.
> We can look into making this a toggle feature in the future. We're not done with FMV work anyways, so nothing is set in stone for them at the moment.

I seems to remember that with some of the previous fmvs pack it was so:

FMVWidescreenMode: 1 
FMVWidescreenEnhancementPackCompatibility: 0
(This way no image cropping, little vertical pillar boxes)

FMVWidescreenMode: 1 
FMVWidescreenEnhancementPackCompatibility: 1
(This way no pillar boxes, image zoomed a little)

**Comment by Badore90** [comment]
Btw now if setting FMVWidescreenEnhancementPackCompatibility: 0, it adds pillar boxes but the verical zoom remains (so proportions are distorted).
It'd be perfect for everyone if this option (FMVWidescreenEnhancementPackCompatibility) would simply adjust the zoom.

**Comment by Polymega** [comment]
This will be fixed in the next update to where there will be three choices. Copied from the upcoming INI changes for this feature:

``` ini
; Display settings for the FMV Enhancement Pack. 1 = Displays FMVs in full for 16:9, but will have pillarboxes. 2 = Scales FMVs to remove pillarboxes for 16:9, which will crop the videos some vertically. 3 = Shrinks FMVs to display them in full for 4:3, but will have letterboxes. (0|1|2|3)
FMVWidescreenEnhancementPackCompatibility = 2
```

**Comment by Richard-L** [comment]
Beautiful!!

**Comment by elishacloud** [comment]
Closing this out.
