### ISSUE TITLE
Resolution UHD

### ISSUE THREAD

**Issue by Spunky78** [elishacloud/Silent-Hill-2-Enhancements#223]
I wonder why nobody has asked a question about the resolution. I can't find an option anywhere to set the resolution to UHD. 1080p is the maximum. I've seen a lot videos on youtube that were captured in UHD

**Comment by Polymega** [comment]
You set the game's resolution by changing the `ResX` and `ResY` options in the `d3d8.ini` file. So, if your display can support 4K, for example, you can set:

```
ResX = 3840
ResY = 2160
```

... or are you referring to something like downsampling/super sampling? As in, play the game in 1080, but have the game internally render at something like 4K?

**Comment by Badore90** [comment]
However if you leave it as default: ResX = 0 / ResY = 0, the game will out-put at the current screen settings. 
I have the game installed on a notebook with a full-hd screen. Sometimes i connect it to a QHD (2550x1440) monitor and the game automatically output at that resolution.

**Comment by elishacloud** [comment]
Closing this out.
