### ISSUE TITLE
Film grain filter from scratch.

### ISSUE THREAD

**Issue by snigelpasta** [elishacloud/Silent-Hill-2-Enhancements#225]
Even when optimized, the film grain filter designed for a 480p game, looks very crappy in HD in my opinion.

An interesting thing and one of the few things that it did right, I think was the HD collection's use of an entirely new film grain filter that sort of looks like actual film grain.

Would it be feasible to just overlay a transparent video file of authentic film grain filter? If not, is there any smart way to create a better looking filter?

If the enhanced edition is supposed to look better than the retail PC release, I really think this is a must.

Best of Love.

**Comment by Polymega** [comment]
> Would it be feasible to just overlay a transparent video file of authentic film grain filter?

Unfortunately, I don't think so. The game dynamically creates the noise filter, so it doesn't use any sort of video/texture image sequence to create it (iirc). 

> the film grain filter designed for a 480p game, looks very crappy in HD in my opinion. [...] If not, is there any smart way to create a better looking filter?

Keep in mind, you can change the resolution of the noise filter. Personally, I love the default noise size, but if you want smaller (finer) noise grain, you can always change its resolution.

Video example: https://youtu.be/6v1USVhtfjQ?t=143
More information: http://enhanced.townofsilenthill.com/SH2/config.htm#IncreaseNoiseEffectRes

**Comment by elishacloud** [comment]
Closing issue.
