### ISSUE TITLE
Game no longer recognising my settings

### ISSUE THREAD

**Issue by Calverz** [elishacloud/Silent-Hill-2-Enhancements#229]
I started the game and it wanted an update. I clicked cancel before game launched. Now when I launch, game defaults to 4:3 with black bars and 30 frames. 

I was previously playing on a 3440x1440 resolution at 60fps. As far as I can tell in d3d8.ini these are still the settings but the game is ignoring this.

[myd3d8.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4242477/myd3d8.txt)

**Comment by Polymega** [comment]
It sounds like you might have two instances of the game running. When you clicked cancel, the first instance of the game will still run. And if you launch the game again while the first instance is still running, the project files won't hook onto the other instances (which adjusts things like the resolution and frame rate).

Ensure only one instance of the game is running. If you prefer, you can set `AutoUpdateModule = 0` in the `d3d8.ini` file to remove the update message box on game launch. If you do this, you'll just have to manually update the [SH2 Enhancements module](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases), whenever any updates are available for it, which isn't that big of a deal to do.

**Comment by Calverz** [comment]
That worked. i restarted and updated game. now it runs fine again. thank you for the advice.
