### ISSUE TITLE
Resize windows problem

### ISSUE THREAD

**Issue by yolanda123a** [elishacloud/Silent-Hill-2-Enhancements#23]
(sorry i press enter quick)
hello
 have this problem

https://i.imgur.com/12t0SzP.jpg

i try with 
EnableWndMode = 0
WndModeBorder = 0
or
EnableWndMode = 1
WndModeBorder = 1

and the problem not solve

and too try res x and res y 1920x1080 or 0 both
but either solve

**Comment by yolanda123a** [comment]
my desktop resolution is 1920x1080

**Comment by elishacloud** [comment]
Can you send a copy of your d3d8.ini file?

Also can you validate that you don't have a 'scripts' folder.  Did you make sure that all other plug-ins are removed before adding this one?

**Comment by yolanda123a** [comment]
i use the plugin in the order that posted in page

[FOG]
// Update settings for modupdater
fog_custom_on = 1
fog_layer1_x1 = 0.250
fog_layer1_x2 = 0.250
fog_layer1_y1 = 0.250
fog_layer1_y2 = 0.250
fog_layer2_complexity = 0.066406
fog_layer2_density_add = 100.0
fog_layer2_density_mult = 1.4
fog_transparency_layer1 = 128
fog_transparency_layer2 = 138

[GAME FIXES]
CatacombsMeatRoomFix = 1
CemeteryLightingFix = 1
DisableRedCrossInCutScenes = 1
EnableSFXAddrHack = 1
IncreaseDrawDistance = 1
Nemesis2000FogFix = 1
NoCDPatch = 1
PS2StyleNoiseFilter = 1
ResetScreenRes = 1
RowboatAnimationFix = 1

[General]
AutoUpdateModule = 1
UseCustomModFolder = 1
WidescreenFix = 1
d3d8to9 = 1

[MAIN]
// Some features from https://github.com/emoose/sh2proxy
FMVWidescreenEnhancementPackCompatibility = 1
FMVWidescreenMode = 1
Fix2D = 1
ResX = 0
ResY = 0

[MISC]
// Nemesis2000 Fog Fix
CreateLocalFix = 1
DisableCutsceneBorders = 1
DisableSafeMode = 1
FPSLimit = 30
FastTransitions = 1
FullscreenImages = 1
GamepadControlsFix = 1
IncreaseNoiseEffectRes = 4096
LightingFix = 1
PS2CameraSpeed = 1
ReduceCutsceneFOV = 1
SelfUpdate = 0
SingleCoreAffinity = 1
SteamCrashFix = 0

[MODS]
d3d8.dll = https://github.com/elishacloud/Silent-Hill-2-Enhancements

[Plugins]
LoadFromScriptsOnly = 0
LoadPlugins = 0

[WINDOWED MODE]
// ThirteenAG Silent Hill 2 WidescreenFixesPack
EnableWndMode = 0
WndModeBorder = 0

[d3d8.dll]
PlaceToRoot

**Comment by yolanda123a** [comment]
first i try
WidescreenFix = 0
d3d8to9 = 0

and run fine but 800x600

and after set resx resy 1920x1080
and set
WidescreenFix = 1
d3d8to9 = 0

and run fine

but i dont lose effect over directx8 ?
so the problem directx9 for resize

**Comment by elishacloud** [comment]
> but i dont lose effect over directx8 ?

Yes, that is correct.

Can you try with the following files: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2321141/d3d8.zip)

Just do the following:
1. Unzip these into your `Silent Hill 2` game folder.
2. Start the game.

**Comment by yolanda123a** [comment]
now work fine in openGL

**Comment by elishacloud** [comment]
Sorry, I don't quite understand.  Are you saying that the files I gave you worked or did you do something else to fix it?

**Comment by yolanda123a** [comment]
yes work with your files
but now after update dll come back same error
maybe i dont should update

**Comment by elishacloud** [comment]
Send me the `d3d8.ini` and `d3d8.log` files after it is updated.

**Comment by elishacloud** [comment]
@yolanda123a, can you try with this update to see if it fixes the issue: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2409446/d3d8.zip)

Note: you will need to delete `dxwrapper.asi` and `dxwrapper.ini` files.

**Comment by yolanda123a** [comment]
@elishacloud i've reinstall again european version
and follow steps "Enhanced Edition page"
and using your d3d8.zip

if i copy d3d9.dll libwine.dll wine3d.dll of step  8,  the game only open a windows in white, and i have to force close game
here a log

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2409484/d3d8.log)

and if i don't install wine 3d, game open fine with your d3d8.zip

**Comment by elishacloud** [comment]
WineD3D can take up to 2 minutes to load on some computers.  Just wait a bit longer on the white screen it should eventually load, or you can just play without WineD3D.  We are working on replacing it, see #10.

**Comment by elishacloud** [comment]
Closing this issue since the original issue is resolved.  We are tracking the WineD3D issues on #10.
