### ISSUE TITLE
Two more (minor) problems

### ISSUE THREAD

**Issue by Badore90** [elishacloud/Silent-Hill-2-Enhancements#230]
**1.** I get a occasional red dots/lines flickering artifacts in the option screens when playing in FHD res. (1920x1080). 
Setting a different res. like 1366x720 or 1280x720 it doesn't happen. 
I connected also the notebook to a external QHD monitor via HDMI cable. Playing at the monitor native res. (2550x1440) the artifacts don't show up. Setting 1920x1080 they come back (enabling/disabling Re-Shade doesnt' make any difference, every other setting is at default).

I recorded and uploaded the video (I haven't uploaded on YT due to the compression making the artifacts even more difficult to notice since they're small and flicker pretty fast).

Here's the download link: https://mega.nz/#!0QsSiQhR!wi4dwqOAKr1WgiXRU5KuFJ0r9SbOv_2x5Nd68Ja7Ta0

I captured a screenshot from the video for a quick idea of the issue (you can see a little red line above the M of Luminosità) . The dots/lines could appear on different places and even more than one dot/line per time.

![Immagine](https://user-images.githubusercontent.com/44087144/75170519-859b1e80-572a-11ea-984a-fdf311d1ab85.jpg)

**2.** Nowadays I think most widespread PCs are notebooks and manufacturers started to provide them with 2 GPUs for power saving, using the integrated one for general purposes and the dedicated more powerful one for intensive tasks like gaming.

The problem is that the software that choose wich GPU have to be used for a given application, doesn't seem to recognize SH2 (probably due to it's old age) as a game.

At least this is what happens on my Acer TravelMate X (Intel UHD 620 + GeForce MX130) that keeps using the integrated GPU with SH2.
The UHD 620 perfectly handle the game with max graphics (Re-Shade filter all enabled) up to Full-HD resolution.
I'm pretty sure using the MX130 this PC could easilly handle the game in 4k too (since there's a huge power difference between the 2 cards).

I think this can be a problem for many people complaining about performance. I still have to search for a good solution (noticed this thing just now).
I prefer to have the nvidia panel set on "leave the application to decide". But the option for manually choose which card must be used on a given application, is on the "manage 3d settings" screen. And I seems to remember if I change just a option there, then the application will refer to the nvidia settings for all graphics options.

I hope there's a way for just making the dedicated card recognizing SH2's exe as one of his applications, but leaving the application choosing the graphics setting.

**Comment by Badore90** [comment]
About the red dot problem. I connected my old netbook (1366x768 screen) to the QHD monitor, run the game at 1920x1080 and the issue doesn't show up.
I'll do some more tests hoping to figure out what can make this strange issue to happen. Maybe it has something to do with the DPI settings?

**Comment by Badore90** [comment]
All solved for me. This is the procedure thanks to **@Bruno3589**

![Immagine1](https://user-images.githubusercontent.com/44087144/75191779-4b924280-5753-11ea-9944-5b3d4d1eb456.jpg)
![Immagine2](https://user-images.githubusercontent.com/44087144/75191790-5220ba00-5753-11ea-9fa2-1f178f587827.jpg)
![Immagine3](https://user-images.githubusercontent.com/44087144/75191799-564cd780-5753-11ea-864e-4329fb6be41b.jpg)
![Immagine4](https://user-images.githubusercontent.com/44087144/75191806-5a78f500-5753-11ea-9609-925808104ba9.jpg)

This way you'll have your app selecting the desire GPU keeping the graphic settings to be set by the app.

Using the dedicated GPU I solved the red (actually even white sometimes and maybe other colors too) dots/lines. Probably a problem of my integrated card driver. Btw being a custom one (many new notebooks have one) it advises me to not update the driver using the normal ones and it seems that Acer isn't going to do something about it.

Btw even if it happens to someone else that only has a integrated card on his PC, it's really a negligible problem that happens only in the option menu and only at certain resolutions (only at 1920x1080 in my case).

**Comment by Polymega** [comment]
I'm glad you and Bruno3589 figured it out.

> Using the dedicated GPU I solved the red (actually even white sometimes and maybe other colors too) dots/lines. Probably a problem of my integrated card driver. 

[It might be partially related to this.](https://youtu.be/6v1USVhtfjQ?t=437) Hard to say, really.

**Comment by Badore90** [comment]
> It might be partially related to this. Hard to say, really.

It is probable. All those fixes are enabled by default right??

Btw even my old PC have a integrated intel card (only that one and it's older and less powerful than the one mounted on the new notebook), but it has updated drivers.

**Comment by Polymega** [comment]
Yes, things like the integrated graphics red FMV fix are enabled by default.
