### ISSUE TITLE
How run the game at 60FPS?

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#231]
I have the Silent Hill Enhanced Edition but my game runs at 30FPS.
How i can run at 60FPS?

**Comment by Polymega** [comment]
[Certain animations and audio cues are synced to a frame rate of 30 FPS.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28#issue-354537681) This was common practice for game development during the release of Silent Hill 2.

Playing at a higher frame rate will result in certain animations playing faster than intended, reduce the effectiveness of frame-based post-processing effects such as motion blur, and completely glitch certain sound effects. It is strongly recommended to play the game at its original, intended 30 frames per second.

If you still wish to play the game at a different frame rate, open the `d3d8.ini` file and add the following code to its own line: `FPSLimit = 30`. Change the `30` value to your desired frame rate.

**Comment by DaRkL3AD3R** [comment]
This raises an important question and consideration for future improvements when the time comes to properly tackle the FMV problem. A major element to the surrealness of Silent Hill 2's original PlayStation 2 FMVs was that they played at 60 frames per second. By having a global variable constantly applying a 30 fps limiter at all times, even with properly encoded 60 fps video files you will still get 30 fps output. I hope some day to see this particular issue resolved and the 60 fps FMVs fully restored.

**Comment by AeroWidescreen** [comment]
@DaRkL3AD3R 
Apparently the FMVs aren't actually in 60 FPS. Something to do with interlacing vs progressive scan, I don't remember. **Polymega** has had a discussion on Github about this before. There's nothing technically stopping us from uncapping the framerate when the FMVs are playing, we just decided it wasn't worth looking into anymore.

**Comment by DaRkL3AD3R** [comment]
I'm not entirely certain how that's the drawn conclusion? I just ran a test recording 60 fps video out of PCSX2 from the NTSC copy of SH2 I have and there is a clear difference between 30 fps gameplay (2 video frames : 1 game frame) vs the FMV sequences where 1 video frame : 1 unique FMV frame. It's most apparent in scenes with heavy motion where there are clear and unique motions happening that have nothing to do with deinterlacing. This is a known problem since the Xbox release when the videos were reencoded down to 30 fps and those files have been the basis for all subsequent releases. I'm sure you guys are aware of this no?

I'm not the guy to do it but I would definitely think it's possible to record the 59.94 fps videos from the PS2 version and then with the right context switches in the SH2E project files, we could enable the 60 fps toggle for FMVs and get back that unique soap opera effect that's been so badly missing from all Xbox -> and on releases of the game.

**Comment by Polymega** [comment]
We don't need to record the PS2 videos as we used them as the base for the FMV enhancement work. Meaning, we already have the PS2 source files for the videos.

I've mentioned details about the videos many times elsewhere, but the videos are not 60 frames per second. They're 60 half frames per second, or 30 interlaced frames per second. Meaning, they are not 60 true, full frames per second. 

CRTs were designed for interlaced footage. So when viewed on a CRT, the FMVs look legitimately like 60 fps. But on digital displays, the interlacing sticks out like a sore thumb.

You can combine the half frames to make full frames to fix the deinterlacing, which reduces the temporal resolution in half (i.e. making the videos 30 full frames per second). This is also one of the options PCSX2 can do for deinterlacing the videos and is also the best-looking deinterlace option on the emulator for this game.

You can also interpolate the footage to "fill in the blanks" of the missing half frames to make 60 full frames per second. There is software out there that can do it well, but nothing we've looked into yet as there currently are errors when playing the game at 30 fps then switching it over to 60 fps for FMVs on the PC version. 

Until we can address that, there's not much incentive about changing the frame rate of the videos at this time.

**Comment by DaRkL3AD3R** [comment]
How is it possible for PCSX2 to deinterlace the videos without cutting the framerate in half? I have 60 fps recordings from the emulator where there's 0 interlacing visible yet each individual frame is unique and perceptibly different. Here's an example recording I took showing it off: https://www.youtube.com/watch?v=lwxKCYPi6UY

It's most noticeable at 0:22 where you can pause the video and step through it with , and . frame by frame and see how every frame is unique and free of interlacing. It is quite visibly 60 true fps, and it is this 60 fps smoothness that gives the FMVs their surreal lifelike feeling.

All I'm saying is, something has to be done to restore that surrealness. I'm not convinced sticking with the raw 30 fps output is the best way to go.

**Comment by Polymega** [comment]
The source files for the PS2 videos are 30i (or 60i, used interchangeably), and not 60 fps. Not sure what else to say about it: https://twitter.com/theRatiocinator/status/1194872713615163393?s=09

PCSX2 has several deinterlacing methods: One is Bob (line doubling for 60 fps but playback looks "jittery"), another is Blend which combines the half frames to output at 30 fps, and there's Weave which doesn't do much: https://forums.pcsx2.net/Thread-Let-s-talk-De-Interlacing

The Bob deinterlacing method, which line doubles for 60 fps just doesn't look all that good. So if we're going to do 60 fps for our project, we're likely going to have to interpolate the footage. To interpolate, we need to properly research the best tools/method to do so.

But again, this isn't on the radar at the moment until we can get the game to switch from 30 fps for gameplay to 60 fps for FMVs without problems.

We never said we're not going to do it; just it's not happening in the near future.

**Comment by DaRkL3AD3R** [comment]
"The Bob deinterlacing method, which line doubles for 60 fps just doesn't look all that good."
That's entirely subjective, and many people disagree myself included. But then again there are many decisions being made on this project (such as vertical zoom cropping on FMVs to remove pillar boxes) that seem to be controversial among purists looking for a nearly bug free PC version that mirrors the PS2 , but with higher resolution and widescreen support. I just hope the day comes in the future when at least the fps switch can be properly handled, then I guess either myself or someone else will just record the line doubled 60 fps footage for our own usage as a mod of sorts.

**Comment by Polymega** [comment]
>I just hope the day comes in the future when at least the fps switch can be properly handled, then I guess either myself or someone else will just record the line doubled 60 fps footage for our own usage as a mod of sorts.

I'm not sure what the issue here is? It's planned for us to do, and we're going to do it in a way where it's both 60 fps and there's no jitter, so what's the concern?

> That's entirely subjective, and many people disagree myself included. But then again there are many decisions being made on this project that seem to be controversial among purists looking for a nearly bug free PC version that mirrors the PS2

We can't please everyone, and this project was never meant to be exactly 1:1 to the PS2 version. Sorry to say.

**Comment by TommvinHuwaltzky** [comment]
https://www.youtube.com/watch?v=6hDIvDPRcPA&t=0s
as seen in the video, it's more than doable.. you have to reverse-engineer it, and change all the 30fps-variables to 60 (which is not as desirable as making the animations adhere to any framerate you're currently running the game at, but easier and better than 30 for starters). this guy did it for a PS4-game, so it should be easier when you already have a PC-version at hand. not to say that it's easy at all (I myself know next to nothing about programming :-x), but I believe the Enhanced-Edition-guys already did some reverse-engineering to bring back the soft-shadows, so they DO have the skillz :P

**Comment by elishacloud** [comment]
> you have to reverse-engineer it, and change all the 30fps-variables to 60

This is already done.  We already have code to modify the game's fps variables and change them to any value we choose.  However, there are issues in other places because parts of the game's timing and logic is based on 30fps.  This means that not only the variables need to change, but also some of the logic.  Changing the variables is quite easy (once you find them) however, changing the logic can be much more difficult.

Plus, changing the pre-rendered videos is not as easy as just modifying a variable, as @Polymega has mentioned.

Anyways, we plan to support 60fps later.  We are all just working on this project as we have time, since most of us have full-time jobs elsewhere.

**Comment by Polymega** [comment]
Closing this ticket. Discussion for 60 fps can be found here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28

**Comment by Walter00Sullivan** [comment]
> I have the Silent Hill Enhanced Edition but my game runs at 30FPS. How i can run at 60FPS?

![Screenshot (871)](https://user-images.githubusercontent.com/102943279/161480943-d7b7030f-aeb8-4b31-8f11-381de83242af.png)

There's someone already explained  @Polymega thanks to him
