### ISSUE TITLE
Silent Hill 2 CRASH

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#235]
Hello,
I have the "Silent Hill 2" enhanced edition, but the game continues to crash, allways crash when im playing. 
How i can do to fix that?
Thnks.

**Comment by Bruno3589** [comment]
Hi,
I'm not really the right person to give you an answer since I don't know how the enhancements work code-wise, however I do know there is a log file you should provide to better troubleshoot the issue you're having.

Look in the main Silent Hill 2 folder for a d3d8.log file and upload it here.

**Comment by Polymega** [comment]
Yes, please upload your `d3d8.log` after trying to launch the game.

Please also upload a screenshot of your game's main installation directory.

Also, where did you obtain your copy of Silent Hill 2 PC? That may pertain to any issues you are having.

**Comment by Polymega** [comment]
Closing this ticket for now. Send us your log file and we can try and assist you.
