### ISSUE TITLE
Black Screen but controls still work after Quick Save

### ISSUE THREAD

**Issue by dgwdv666** [elishacloud/Silent-Hill-2-Enhancements#239]
I'm at the end in the Lakeview Hotel, I got into the elevator to get to the basement and quick-saved. I pressed the button to go to the basement, and the game crashed. I launched it again (and yes, as admin) and loaded my save, and now the screen is black. The controls still work though: I move the joystick and I hear James' footsteps. I can shoot. I can go into my inventory. I can pause, but the game screen is black. I tried turning on my flashlight, and it said, "I pressed the switch, but nothing happens."

I am so mad because I'm SO DAMN CLOSE to finishing the game (this is my first playthrough ever), and I'm loving it. I need help! 
(My last manual save, which was 3 hours ago, has the same problem.)

Here are my logs:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4290933/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4290934/d3d9.log)
[dsound.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4290935/dsound.log)

**Comment by Polymega** [comment]
I'm sorry you ran into this problem. The Quick Save/Quick Load feature is an amazing and convenient feature added to the PC version of the game, but its implementation was definitely not fully play tested.

I was able to replicate your issue. Here's how you can fix it:

Load back into your game. It will still be black. Move James around and keep spamming the action button until you eventually interact with the elevator doors. Once you find/interact with the elevator buttons, click the "open elevator door" button

![image](https://user-images.githubusercontent.com/27395260/75951968-62374880-5e7b-11ea-8280-515bb06d9cfc.png)

This will fix the issue. You can then go back into the elevator and proceed like normal. Be sure to **not** save back in this elevator and make a new Quick Save to overwrite the bad one.

-------------------------

Coincidentally, we had another similar elevator save issue [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/157). We addressed this save bug, and I will put in a request to also prevent the player from saving in this elevator as well, so no one else runs into the issue you experienced. 

Sorry that happened, but we'll have it fixed for the next update!

**Comment by Polymega** [comment]
PS

> (My last manual save, which was 3 hours ago, has the same problem.)

Are you meaning your last manual save is also displaying a solid black screen?

**Comment by dgwdv666** [comment]
Thanks so much! This actually fixed both saves, which is weird since the manual one was so far back. I just finished the game (got the "Leave" ending, even though I met all the criteria for the "In Water" ending), and it was amazing. Thanks for the amazing work on the Enhanced Edition!

**Comment by Polymega** [comment]
The latest update to the project now prevents a player from saving in the elevators, which could provoke this issue. You can get the latest update here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

Closing the issue. Thanks again for reporting this bug!
