### ISSUE TITLE
White Textures Still Present

### ISSUE THREAD

**Issue by SPHarker** [elishacloud/Silent-Hill-2-Enhancements#24]
I followed the enhanced edition instructions to the letter, everything looks good, but I get to the tunnel on the observation deck and the back of it still has white textures. I'm using the WineD3D and shaders because of my Nvidia card. What am I doing wrong?

**Comment by Polymega** [comment]
Thank you for testing and following up with the solution on this. We can now recommend this as a solution for others who experience the same problem.
