### ISSUE TITLE
New font missing and slowdown with WidescreenFix = 1

### ISSUE THREAD

**Issue by eddiepm** [elishacloud/Silent-Hill-2-Enhancements#240]
I am having issues with some os the fixes and enhancements.
The new HD fonts simply doesn't show up for me, being invisible in all screens (menu, options, in-game texts, etc). Old texts appears normal, but if the "_Use custom fonts_" option is ON, all texts desappear.
Also, the game suffers a contant lag and drop of fps upon turning the "_Widescreen Fix_" option on the "_Integrated Packages_" ON.
I tried modifying all other options, but only the "_Widescreen Fix_" option causes this constant lag.

Both problems occurs everytime the game is launched. It is impossible to watch in-game cutscenes with the _Widescreen Fix_ on, since it slowsdown too much.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4302175/d3d8.log)

![WhatsApp Image 2020-03-07 at 14 04 36](https://user-images.githubusercontent.com/60447340/76147594-ab0a1f80-607c-11ea-820e-aceb02431fa9.jpeg)
![WhatsApp Image 2020-03-07 at 14 04 37](https://user-images.githubusercontent.com/60447340/76147595-ac3b4c80-607c-11ea-882a-a9895dfce952.jpeg)
![WhatsApp Image 2020-03-07 at 14 04 36 (1)](https://user-images.githubusercontent.com/60447340/76147597-acd3e300-607c-11ea-8ffd-f001734741aa.jpeg)

**Comment by Polymega** [comment]
To start, can you try using the executable provided on our site to see if that fixes issues for you?
http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE

**Comment by Polymega** [comment]
The Intel Q35 Express chipset your using for graphics handling will indeed struggle for things like the FMVs, Fog Fix, and higher render resolutions. There's not much we can offer to suggest with the lag your experiencing, unfortunately.

- https://www.videocardbenchmark.net/gpu.php?gpu=Intel+Q35+Express
- https://forums.tomshardware.com/threads/good-graphics-card-to-replace-intel-r-q35-express-chipset-family.2862311/#post-18188494

**Comment by eddiepm** [comment]
> To start, can you try using the executable provided on our site to see if that fixes issues for you?
> http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE

I already use it.

**Comment by Polymega** [comment]
Looking at your log file it says you are using the European Director's Cut executable:

```
5560 13:37:53.426 "sh2pc.exe" (PID:4816)
5560 13:37:53.426 Game binary version: Director's Cut
```

Can you re-download our executable then just to be sure? Perhaps that may also fix the font issue; it's worth trying out first.

**Comment by eddiepm** [comment]
> Looking at your log file it says you are using the European Director's Cut executable:
> 
> ```
> 5560 13:37:53.426 "sh2pc.exe" (PID:4816)
> 5560 13:37:53.426 Game binary version: Director's Cut
> ```
> 
> Can you re-download our executable then just to be sure? Perhaps that may also fix the font issue; it's worth trying out first.

Did it, but now the text only shows up in the main menu. Every other menu and text are still invisible.

**Comment by Polymega** [comment]
Inside the `d3d8.ini` file, set `UseCustomFonts = 0` and see if the text is restored in the game. I want to see if the original, low resolution text will at least display for you.

**Comment by eddiepm** [comment]
> Inside the `d3d8.ini` file, set `UseCustomFonts = 0` and see if the text is restored in the game. I want to see if the original, low resolution text will at least display for you.

It does. It’s how I’m playing the game for now.

**Comment by Polymega** [comment]
Can you confirm the following files are located inside `sh2e\font\`:
```
font000.tga
fontwdata.bin
```

**Comment by eddiepm** [comment]
Yes, both files are located in those folder.

**Comment by Polymega** [comment]
The high res font file is quite large at 4400 x 896. There's a possibility that the Intel Q35 chipset might not be able to handle a texture file of that resolution (4000+ pixels in any dimension) in-game.

**Comment by eddiepm** [comment]
Hum, got it. 
Gonna assemble a new PC soon, so the problem probably won’t show up anymore.
Thanks for the assist.

**Comment by Polymega** [comment]
If you remember, please report back after you build your new PC. I'd like to know if the lag and HD fonts are fixed for you.

Just so you know that you're not alone: My Surface Pro 3 laptop also uses Intel integrated graphics, and I must disable the Fog Fix when playing on my laptop, otherwise the game lags very badly during outside fog segments.

While the requirements aren't too high to run the game (even with our project), more advanced features such as the Fog Fix and HD Fonts will require more graphical power than what's needed to just play the vanilla PC game.

**Comment by eddiepm** [comment]
Yeah, I have to disable Soft Shadows and tone down the Custom Fog intensity also, but at least I can play with the rest of the fixes without any frame drop.
And I will report as soon as I get my new PC. Thanks again!

**Comment by elishacloud** [comment]
Closing this out.
