### ISSUE TITLE
Cannot launch the game

### ISSUE THREAD

**Issue by neko85** [elishacloud/Silent-Hill-2-Enhancements#241]
Hi there!
I installed the game and all the archives, and i wasnt able to launch the game, nothing happens.
Then i searched here in the forum, and downloaded a d3d8.ini file that was in a previous post about launch issues, and it seemed worked, but now i get a black screen in japanese that says the disc is dirty, or something like that...
i add the screenshot here, and my log
I aprecciate any help, thanks!

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4310003/d3d8.log)
![89653298_193710165287574_6164209420533235712_n](https://user-images.githubusercontent.com/62000666/76275509-c6934700-6283-11ea-9c41-ba737997088f.jpg)

**Comment by Polymega** [comment]
Did you obtain your copy of the game through a website called "nitroblog?" If so, refer to this thread to see if it may help you: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/107#issuecomment-483053545

**Comment by neko85** [comment]
thanks for the quick answer!
yes...is that site lol

**Comment by Polymega** [comment]
Unfortunately there's no telling what was added or removed to any pirated copy of the game. And when files are tampered with, it will likely create conflict/incompatibility with our project (as what's happening to you). 

The person in the thread I linked resolved the same issue by reinstalling the game. I cannot condone piracy, but you may want to find another copy of the game that hopefully might not be tampered with if you're still having troubles.

**Comment by neko85** [comment]
yeah... i am still getting the same screen in japanese after doing the language.ini thing and all that...
I guess i will play it in my old PS2, i am not into programming and all that, i though it will be more simple to play the enhanced version lol :S
thanks anyway

**Comment by elishacloud** [comment]
Closing this out.
