### ISSUE TITLE
Linux/Wine: d3d8 tests and report

### ISSUE THREAD

**Issue by legluondunet** [elishacloud/Silent-Hill-2-Enhancements#243]
Hello @elishacloud, I just tested last d3d8.dll release v1.5.1700.0 and it works great on Linux/Wine! Thanks a lot to support this platform :)
I didn't play much time but I saw no issue with last d3d8 version.

However If you could answer few questions:
1°) is there an option to restore PC menu design:
--> black background
--> "Silent Hill 2" red letters
--> old bloody knife cursor

![29600007-245e8040-8788-11e7-8598-a1b17e5e58a8](https://user-images.githubusercontent.com/325405/76645046-77d1ff80-6558-11ea-9acc-8c9e26e5b66b.png)

2°) Menu letters are a bit too large, aren't they? is there a ratio issue?

![Capture d’écran de 2020-03-13 18-31-39](https://user-images.githubusercontent.com/325405/76645360-25451300-6559-11ea-8697-3494ec125282.png)

3°) there is a white line on urinal, is it normal?

![Capture d’écran de 2020-03-13 16-06-51](https://user-images.githubusercontent.com/325405/76633664-5ca9c480-6545-11ea-8154-ebbcd18909a1.png)
![Capture d’écran de 2020-03-13 16-07-03](https://user-images.githubusercontent.com/325405/76633663-5ca9c480-6545-11ea-9dd3-35be68c2a868.png)
![Capture d’écran de 2020-03-13 16-06-51b](https://user-images.githubusercontent.com/325405/76633660-5c112e00-6545-11ea-9f11-890246c519a2.png)

Thank you for your help.

**Comment by Polymega** [comment]
> 1°) is there an option to restore PC menu design:

You can remove the `sh2e\pic\etc\` folder. You'd then be using the incredibly low resolution main menu images (from vanilla PC version), and the main menu text would no longer be translated when using the North American executable.

> Menu letters are a bit too large, aren't they? is there a ratio issue?

No, it is correct. Here is the main menu on PS2/Xbox versions:

![image](https://user-images.githubusercontent.com/27395260/76647078-7c83bd00-6532-11ea-824d-66cfade94acc.png)
![image](https://user-images.githubusercontent.com/27395260/76646994-565e1d00-6532-11ea-8789-146ea1746181.png)

Also: 

![image](https://user-images.githubusercontent.com/27395260/76647169-a50bb700-6532-11ea-87cf-dc15c95fd3fb.png)

The European executable doesn't use the official main menu font. For the record: [You probably shouldn't use the European executable](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-occasionally-freezescrashes-as-im-playing) if it's a cracked, "No-CD" version.

> there is a white line on urinal, is it normal?

I'm pretty sure this is a rim of [specular shine](https://i.stack.imgur.com/gIaQ5.png). Anti-aliasing would lessen how noticeable it is.

**Comment by elishacloud** [comment]
> Hello @elishacloud, I just tested last d3d8.dll release v1.5.1700.0 and it works great on Linux/Wine! Thanks a lot to support this platform :)

Great!  I am glad the fixes still work on the latest build.

> --> old bloody knife cursor

I believe you can restore the old bloody knife by deleting (or renaming) the file:
`sh2e\pic\etc\MousePointer.png`

For a high res version of the bloody knife see [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues/375#issuecomment-349175618).

> I'm pretty sure this is a rim of [specular shine](https://i.stack.imgur.com/gIaQ5.png). Anti-aliasing would lessen how noticeable it is.

I have seen this in other places in the game, like in room 213.  Anti-aliasing makes a big difference here, at least on my computer.

**Comment by legluondunet** [comment]
@Polymega 

> 1°) is there an option to restore PC menu design:
You can remove the sh2e\pic\etc\ folder. You'd then be using the incredibly low resolution main menu images (from vanilla PC version), and the main menu text would no longer be translated when using the North American executable.

You and the team did a very excellent job but I prefer to let the choice to gamers, in my Lutris script they could soon choose between "PC" or "PS2" menu. PC theme will restore this screen too:
![1](https://user-images.githubusercontent.com/325405/76679521-81537a00-65e1-11ea-852b-05b49774a9ad.png)

Could you tell me how to modify tex file? I would like to remove "director'cut" from the "the incredibly low resolution main menu image".

**Comment by legluondunet** [comment]
@elishacloud 
Thank you for the cursor, it works great!
Now for urinal anti-aliasing I didn't understand if it is an issue or not? 
If it is an issue, it is a Linux/Wine issue?

**Comment by elishacloud** [comment]
> Now for urinal anti-aliasing I didn't understand if it is an issue or not?
> If it is an issue, it is a Linux/Wine issue?

Yes, this is normal.  I see the same thing on my computer.

**Comment by Polymega** [comment]
> Could you tell me how to modify tex file? I would like to remove "director's cut" from the "the incredibly low resolution main menu image" ;).

Well, it is very low res.

The easiest way to do this is to download and use the SH Texture Explorer:
http://alchemillahospital.net/how-to-use-sh-texture-explorer/

You might need to use Windows to use the program.

**Comment by elishacloud** [comment]
Closing this out.
