### ISSUE TITLE
Green half of box and how do I remap controller buttons in menu

### ISSUE THREAD

**Issue by doctorix** [elishacloud/Silent-Hill-2-Enhancements#245]
The game seems to have a half of green box surrounding the game its very annoying. Also how do I remap the buttons in the menu?

**Comment by Polymega** [comment]
Can you please provide a photo of the issue?

Controller remapping can be found on this step:
http://enhanced.townofsilenthill.com/SH2/install.htm#controllerSetup

**Comment by doctorix** [comment]
![Uploading Untitled.png…]()
Here is a screen shot of the green box

**Comment by doctorix** [comment]
![Untitled](https://user-images.githubusercontent.com/62318865/76921064-70399000-68a3-11ea-83d9-5a44bba4c09b.png)

**Comment by doctorix** [comment]
That green half of box doesn't go away but the arrow does in game. Also in regards to the button remapping, I go to the Button Configuration menu in game when I press enter on keyboard and in the controller input it is unresponsive when I press the button on the controller. I am using DS4Windows and a PS4 Controller the setup works perfectly, rumble works etc, but I hate the button layout, for example the R3 button access the menu

**Comment by doctorix** [comment]
![Untitled2](https://user-images.githubusercontent.com/62318865/76921280-01a90200-68a4-11ea-903d-cfdab2adc576.png)


Here is an example in game of the green half of box

**Comment by Polymega** [comment]
> Here is a screen shot of the green box

1. Can you open your `settings.ini` file and confirm the following are set to `0`?

```
SET DX_CONFIG_SCREEN_POS_X 0
SET DX_CONFIG_SCREEN_POS_Y 0
```

2. Are you using any other enhancement packages for the game that are not covered/detailed within [our installation site](http://enhanced.townofsilenthill.com/SH2/)?
3. Do you have any custom settings for this game (or perhaps global settings for any games) within your GPU's control panel that might cause this?

> That green half of box doesn't go away but the arrow does in game.

The arrow is the PC mouse cursor. It'll appear in menu screens such as the main menu, save screens, inventory screen, and map screen.

> when I press enter on keyboard and in the controller input it is unresponsive when I press the button on the controller. I am using DS4Windows and a PS4 Controller the setup works perfectly, rumble works etc, but I hate the button layout, for example the R3 button access the menu

It sounds like DS4Windows is overriding the game's input mapping with its own. We don't really cover outside software for controller support on the guide. [You can search for other tickets on here about DS4Windows](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues?q=is%3Aissue+ds4windows) to see if any of them help. Or, you can forgo DS4Windows and [use the DS4 as a simple plug-and-play device.](http://enhanced.townofsilenthill.com/SH2/install.htm#controllerSetup)

**Comment by Polymega** [comment]
Also, please include a copy of your `d3d8.log` file. 

And is your green lines related to this?
https://nvidia.custhelp.com/app/answers/detail/a_id/1842/~/what-are-the-green-lines-that-appear-on-my-screen-when-in-sli-mode%3F

**Comment by doctorix** [comment]
I can't find how to access SLI settings so I can shut off  the green indicators. No other enhancement packages used. I do have global settings. I see a d3d8.ini & .dat & .dll file no log file. Which do you need?

**Comment by Polymega** [comment]
The `d3d8.log` file is made when you launch and close the game after implementing [the SH2 Enhancements module](http://enhanced.townofsilenthill.com/SH2/install.htm#installSH2Enhancements). It would be found in the game's main directory, beside your `d3d8.ini, d3d8.dat, and d3d8.dll` files.

> I can't find how to access SLI settings so I can shut off the green indicators.

You may not be using SLI; I'm not sure. It was something worth checking. If you can't find settings for SLI in your GPU's control panel that likely means you're not using it.

Anyway, ensure you have the SH2 Enhancements module files placed in the game's directory, launch/close the game, and see if it produces a `d3d8.log` file for you in the directory.

**Comment by doctorix** [comment]
I followed the steps one by one. So the SH2 Enhancements module is placed. Still no d3d8.log file.

**Comment by Polymega** [comment]
Okay, we'll probably need @elishacloud to chime in on this, as you should have a log file after launching the game. In the meantime, just to be sure, can you take a snapshot of the game's main directory, so we can see all the files put in place, and post it here?

**Comment by doctorix** [comment]
![Untitled](https://user-images.githubusercontent.com/62318865/77131087-c12abf00-6a30-11ea-97fb-e5091d447de4.png)

**Comment by Polymega** [comment]
You're not launching the game through `Squ1zZy_ResPatcher.exe`, are you? As the name of that software alone sounds like something that might be causing your problem. 

[Do you have other foreign files that are not included as part of our project?](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

In regards to producing a `d3d8.log` file: Can you try running `sh2pc.exe` as an **Administrator** and seeing it makes one for you then?

**Comment by doctorix** [comment]
After I ran as administrator it got rid of the line and the game works if I run it regular not as administrator afterwards and the line is gone. I see some new folders were made. I am assuming thats where the saves go now as I lost all my saves but the original save I made before I changed to enhanced edition. I think you have to add in the steps to run as administrator the first time. Also do you recommended downloading latest version of reshade or leave well enough alone?

**Comment by Polymega** [comment]
That's good to hear. I accidentally replicated your issue of no log files being produced, which is why I thought to suggest running the game as admin. 

It turns out, even though I've given my account read/write permissions for the game's folders/files within the `Program Files (x86)` directory, you still need to run the game as admin in order for it to create/write its own files, such as the `.log` files and save files (found in `SILENT HILL 2\data\save\Folder 01\`).

What this means is, before you started running your game as admin, your log and save files were being saved/stored/read from a virtual directory. Info on that here:
https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Notes

I'm sure you know, but you can right click `sh2pc.exe`, go to **Properties**, then click the **Compatibility** take and check/enable the **Run this program as administrator** button. **Apply** changes.

> Also do you recommended downloading latest version of reshade or leave well enough alone?

You don't have to worry about that. We plan to ultimately remove ReShade from the installation process, so you can keep using the current version until now, as it will ultimately be gone in the future.

**Comment by Polymega** [comment]
PS

> I think you have to add in the steps to run as administrator the first time.

That shouldn't be the case with the `CheckForAdminAccess` feature:
http://enhanced.townofsilenthill.com/SH2/config.htm#CheckForAdminAccess

But if you have user read/write permissions for an admin-protected directory (which is not typical) then it could throw `CheckForAdminAccess` off.
