### ISSUE TITLE
More Natural Fog Movement Fix

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#246]
This feature [will slow the fog movement](https://www.youtube.com/watch?v=kpMtGKERvB0) in certain areas of the game to better match the PS2's fog movements, which are slower and more natural.

------------------

`01F7A68C float (Fog Speed)` (this is a new address for use in the project)

- If in Room 

```
0x03 (Forest)
0x04 (Town East)
0x08 (Town West)
0x8E (Hallway before Eddie boss)
0xBB (Final Boss)
0xBD (DOG Room)
0xC0 (Mansion Entrance Hall)
0xC2 (Mansion Lounge)
0xCA (Mansion 1F Grand Hallway)
0xC4 (Mansion Service Room)
0xD3 (Mansion Outside Entrance)
0xD4 (Blue Creek Mansion Entrance)
```

...  Fog Speed: `0.25f`

- If in Room 

```
0x07 (Woodside Courtyard)
0x8F (Eddie Boss Room Small)
0x90 (Eddie Boss Room Large)
```

...  Fog Speed: `0.50f`

------------------

Additionally, this will prevent patches of fog "sticking" to James during certain parts of the Forest trail, which can happen with or without the use of this fix or the Fog Fix:

`006A7940 float (James' Influence on Fog)` (this is a new address for use in the project)
`01FB1020 float (James' Y Position)` (this is a new address for use in the project)

- If in Room `0x03 (Forest)` && James' Y Position is between `1125.0f` and `1575.0f`
   - James' Influence on Fog: `10.0f`
- Else
   - James' Influence on Fog: `200.0f`

-----------------

``` ini
; Adjusts the speed of the fog in certain areas for slower, more natural movement. (0|1)
FogSpeedFix = 1
```

Similar to as you've done with `GameLoadFix`, you'll want this code to constantly monitor any value changes for the "Fog Speed"  address while in these rooms, to ensure the game doesn't overwrite our value changes. As there are certain triggers within each of these rooms that'll set the value back for fog speed to its default numbers. (**Note:** "James' Influence on Fog" is a static value and doesn't require a constant check.)

Additionally, I have some value changes for the fog fix in general, to bring it closer to the PS2 version, so I'll paste the whole thing below for revision. I won't go into detail about why I made the changes I did, but the fog speed fix above indirectly affects the fog fix values below, which is why I changed some of them:

``` ini
[FOG]
; Enables the fog fix. Settings for the fog fix are below. (0|1)
fog_custom_on = 1

; Original value 128. Default custom value 128. (0-255)
fog_transparency_layer1 = 128

; Original value 128. Default custom value 90. (0-255)
fog_transparency_layer2 = 90

; Original value 0.125. Default custom value 0.250. (*)
fog_layer1_x1 = 0.250

; Original value 0.125. Default custom value 0.250. (*)
fog_layer1_x2 = 0.250

; Original value 0.125. Default custom value 0.125. (*)
fog_layer1_y1 = 0.125

; Original value 0.125. Default custom value 0.125. (*)
fog_layer1_y2 = 0.125

; Original value 1.0. Default custom value 1.4. (*)
fog_layer2_density_mult = 1.4

; Original value 0.0. Default custom value 100.0. (*)
fog_layer2_density_add = 100.0

; Original value 0.048828. Default custom value 0.08. (*)
fog_layer2_complexity = 0.08
```

**Comment by Badore90** [comment]
> 0xD3 (Mansion Outside Entrance)

Here you're referring to the Maria's scenario apartment?? 

https://youtu.be/zTQ6weUTYjY

**Comment by Polymega** [comment]
No, but good catch. I've added that and some other rooms to the list now.

**Comment by elishacloud** [comment]
Implemented this Fog Speed Fix feature.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4527154/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha!

The fog speed part of the fix is working well across all binaries.

However, the "James' Influence on Fog" part doesn't seem to be taking effect. It's not changing to `10.0f` during the certain Y elevation within the forest area. I'm not sure if it's because of the fog influence address or James' Y pos address that works alongside it.

---------------

Also, within the INI, can you please add `(0|1)` to the end of the `LockScreenPosition` and `UseBestGraphics` descriptions.

And a slight tweak to this description (I changed the word "in" to "for" in several spots):

``` ini
; Display settings for the FMV Enhancement Pack. 1 = Displays FMVs in full for 16:9, but will have pillarboxes. 2 = Scales FMVs to remove pillarboxes for 16:9, which will crop the videos some vertically. 3 = Shrinks FMVs to display them in full for 4:3, but will have letterboxes. (0|1|2|3)
FMVWidescreenEnhancementPackCompatibility = 2
```

(Right now, we have `FMVWidescreenEnhancementPackCompatibility` set to `1` but it'll need to be set to `2` by default before next public release.)

**Comment by elishacloud** [comment]
Ok, I fixed all those items.  The "James' Influence on Fog" part had a typo.  I was checking for `0.03` for the room ID rather than `0x03`.

New test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4531129/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha. I get a crash whenever `006A7940 float (James' Influence on Fog)` is about to change to `10.0f`. This is on binary 1.0.

**Comment by elishacloud** [comment]
Ok, I should have realized that this is protected section of memory.

Try this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4531446/d3d8.zip)

**Comment by Polymega** [comment]
This is the ticket. Thank you again, it's working well across all binaries.
