### ISSUE TITLE
Weird shadow behaviour

### ISSUE THREAD

**Issue by Bruno3589** [elishacloud/Silent-Hill-2-Enhancements#248]
Hi,
first and foremost, given the current situation: how are you? Everything okay?
I am currently at my second week of "quarantine", which means I work from home and I never go out if not for buying food. Other than that, I'm fine.

Now, back to business: me and @Badore90 are currently in the process of testing the new Italian translation in-game. While in the apartments, I noticed a strange shadow behaviour.

The problem is in the stairs of Wood Side Apartments: https://youtu.be/WOrcyu0_RlY
As you can see ambient shadow seems to "go wild" when turning corners. This is _before_ acquiring the flashlight.

I'm not sure if it's still a game engine limitation as in issue #216 , if that's the case feel free to close this one as well.

**Comment by Polymega** [comment]
I'm glad you're doing well, with everything currently going on. I hope your friends and family are safe and well, also. Over here, the other week all non-essential business have been most closed or limited to shoppers, and we've been instructed to staying at home as much as possible. 

The shadow behavior you're describing is correct. Shadow behavior such as this is, for better and worse, 1:1 the same as the console versions. Shadow programming wasn't perfect for this game.

More info:
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/120
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/216
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/224

**Comment by AeroWidescreen** [comment]
Glad you're doing OK in Italy. Stay home, stay safe.

**Comment by Bruno3589** [comment]
Glad to know you're all doing well too.

> The shadow behavior you're describing is correct. Shadow behavior such as this is, for better and worse, 1:1 the same as the console versions. Shadow programming wasn't perfect for this game.

I suspected that was an expected behaviour, thanks for confirming it nonetheless.
