### ISSUE TITLE
Map indications still visible even when they're supposed to not be visible.

### ISSUE THREAD

**Issue by gambaaaa** [elishacloud/Silent-Hill-2-Enhancements#25]
The description is confusing, though. (english is not my first language)
I made a screenshot, so it can be easier to know the problem: https://i.imgur.com/XirYpg0.jpg
I tried the fix2d option in d3d8.ini, but it doesn't work, it seems like that the arrows are rendered in 16:9 format, but the map is still 4:3.

**Comment by Polymega** [comment]
Hello, 

From the [troubleshooting section](http://enhanced.townofsilenthill.com/SH2/#troubleshooting) of the guide:

**THE MARKINGS ON THE MAP "FLOAT" ABOVE THE BORDERS ON THE SIDES OF THE SCREEN**
The game does not render its overlaid 2D images beyond their original full screen aspect ratio, so when you open the map you will see borders on the sides. Yet, the markings on the map "float" above these borders. This issue can be resolved by setting Fix2D = to 0 in SH2 Enhancement's d3d8.ini file. Using this fix will make the map fill the widescreen resolution of your display, but will stretch the image in the process. This will affect all overlaid 2D images including the menu/inventory screen, memo screens, save screen, subtitles, etc.

**Comment by Polymega** [comment]
Did you set `Fix2D =` to `0` in the` d3d8.ini` file? Some people have gotten confused on the wording of this fix and accidentally think that setting it to `1` fixes the problem. 

You have two choices for the map: 

`Fix2D = 0` will stretch the map to fill the width of your screen. By doing this, the markings on the map no longer "float" above the black borders on the side. Note: This will also stretch all other images in the game.

`Fix2D = 1` will keep the map at a 4:3 aspect ratio but you will see the markings on the map "float" above the black borders on the side.

**Comment by Polymega** [comment]
> it seems like that the arrows are rendered in 16:9 format, but the map is still 4:3.

Yes, this is an issue we are aware of. This is why you can use `Fix2D = 0` to stretch the map to alleviate this problem. We hope to fix this issue in the future without having to stretch the map.

**Comment by ambystona** [comment]
Now works perfectly, thanks again!
I forgot to set FullscreenImages to 0, anyway the stretched map looks fine, at least in a 16:9 monitor.

**Comment by AeroWidescreen** [comment]
This will hopefully be the next thing we work on so we can remove pillarboxing without the need of stretching of anything.
