### ISSUE TITLE
Which version of the game you recommend?

### ISSUE THREAD

**Issue by nomadspy** [elishacloud/Silent-Hill-2-Enhancements#250]
I know both SH2 and SH2DC work but I also found out there is a patch 1.1 for the game that fixes something like audio loops. Should I install it or the mod takes care of these issues?

**Comment by Polymega** [comment]
Patch 1.1 was made and only works for the North American v1.0 executable to fix the sound looping issues. Unfortunately, it didn't actually fix it.

You can install either the NA or EU version of the game and, afterwards, [we recommend you use the North American executable provided on our site.](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE)

In the future, we plan to change this on our site to v1.1. Using Konami's official patch tool on an untouched v1.0, it will "officially" remove the DRM found within v1.0. 

We haven't made this transition yet, but the v1.0 executable we provide should be completely fine to use for now.

**Comment by nomadspy** [comment]
> Patch 1.1 was made and only works for the North American v1.0 executable to fix the sound looping issues. Unfortunately, it didn't actually fix it.
> 
> You can install either the NA or EU version of the game and, afterwards, [we recommend you use the North American executable provided on our site.](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE)
> 
> In the future, we plan to change this on our site to v1.1. Using Konami's official patch tool on an untouched v1.0, it will "officially" remove the DRM found within v1.0.
> 
> We haven't made this transition yet, but the v1.0 executable we provide should be completely fine to use for now.

Thank you both for the response and the work you do. Bless you all.

**Comment by elishacloud** [comment]
Closing this out.
