### ISSUE TITLE
Issue Installing the Game

### ISSUE THREAD

**Issue by chrisvtheactivist** [elishacloud/Silent-Hill-2-Enhancements#251]
Hey yall was looking to play SH2 on PC with the Enhanced Edition patch. However when I go to install the game (without the patch first) I get Error 0x80040707. Anyone got any ideas? I am on Windows 10. I tried running it on Administrator, but that didn't work. And I tried running it in compatibility mode on every option. Didn't work either. Any ideas?

I also tried installing the DirectX 8.1 to see if that did anything (it didn't) but then I saw that Enhanced Edition says not to. Idk if I messed myself up or not so if there is any suggestions on that.

**Comment by Polymega** [comment]
To confirm: If you run setup.exe as administrator it won't run at all? And if it does run, selecting "No" at the end of installation, when the game asks if you want to install any DirectX 8.1 drivers, will not let you finish installation?

**Comment by chrisvtheactivist** [comment]
I actually got it fixed now! This [link](https://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/installation-error-0x80040707/6d7431f5-e936-47db-9540-33290a388d43) helped me fix it. Weird issue

**Comment by Polymega** [comment]
Okay, great! I'm glad you got it sorted out.

**Comment by elishacloud** [comment]
Closing this out.
