### ISSUE TITLE
Hangs on launch when dualshock 4 is plugged in, launches fine otherwise

### ISSUE THREAD

**Issue by blue-schuhart** [elishacloud/Silent-Hill-2-Enhancements#252]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4379151/d3d8.log)

I can launch the game fine when it's not plugged in, but when my dualshock 4 controller is plugged in the game hangs on launch.

I've messed around with DS4Windows trying to fix it but I can't figure out anything to change that makes any difference. When DS4Windows is not running it still happens, simply having the dualshock 4 plugged in seems to be the issue.

I have tried setting RestoreSearchCamMovement to 0,1,2, and 3, none seem to make a difference.

I've tried turning off RestoreVibration 

Also wanted to say thank you for all the work you've done on the enhanced edition, you're really keeping this game alive and I have a huge amount of respect for this team.

**Comment by Polymega** [comment]
Hi @blue-schuhart,

Thanks for trying out a few solutions ahead of time before making the ticket, and sorry you're having troubles with the controller.

Troubleshooting controllers can be a bit tricky, as there can be issues beyond our control with what's happening. I tested the latest build using my DS4 and didn't experience any issues, so this doesn't appear to be a problem on the project's end. (I also don't use DS4Windows or any other external software for this controller.)

Beyond DS4Windows, are you sure you don't have any other software running in the background that might be hooking into your controller that would cause this? Do you have another type of controller you can use instead? An Xbox 360/One controller or generic PC gamepad? Or maybe a friend has one they can lend you to test?

**Comment by blue-schuhart** [comment]
Hey thanks for the reply, I messed around with drivers for a while and then restarted my PC (which I should've tried sooner) and now it seems to be working. I would feel foolish if it was JUST restarting that fixed it but maybe something I did helped and I just needed to restart to see the effects. Who knows.

But anyway I've got it working now on DS4 with vibration so all is well. For context in the past with the EE I used an xbox 360 controller but I recently moved and didn't bring it with me so my only option was DS4.

Thanks for the help, and thanks for all the work on the EE.

Actually side note, do you know if there is any way to disable the text adjustments to grammar and stuff? Or is that completely set in stone?

**Comment by Polymega** [comment]
That's good to hear. Sometimes the simple I.T. approach of "did you restart your computer?" can be all it takes.

You can rename the `sh2e\etc\message\` folder to anything else to prevent the game from reading the files in that directory.

**Comment by elishacloud** [comment]
Closing this out.
