### ISSUE TITLE
Feature Request: Disable Screensaver In WndModeFullscreen

### ISSUE THREAD

**Issue by KojiKenshiro** [elishacloud/Silent-Hill-2-Enhancements#254]
I just want to take a moment to thank you guys for the hard work you guys do on Silent Hill 2: Enhanced Edition. Would it be possible to add a feature to d3d8.ini to temporarily disable the screensaver set in Windows when playing in WndModeFullscreen? When I take the time to sit through the end credits without touching my controller, the screensaver kicks in and in essence I have to force close the game because of it. Thank you and have a good day. :)

**Comment by Badore90** [comment]
I don't know if the team could/will add this feature. My is just an external advice.

If you have a lcd monitor, you don't need the screensaver to be enabled. You don't need it even with a CRT (they are really difficult to get printed, indeed even in old times it was recommended to disable the screensaver for saving memory).

Best thing to do imho is to set the PC monitor to just turn off after, let's say, 10/15 minutes.
This way it shouldn't turn off when something is moving on screen and even if it happens, it will turn on again just moving the mous/touchpad or pressing any button.

So even if you use a Plasma or Oled monitor, you really don't need the screensaver to be enabled.

**Comment by KojiKenshiro** [comment]
@Badore90 Thank you for your advice. I disabled the screensaver and set my monitor to turn off after 20 minutes of inactivity. Thank you all for fixing/updating the great game for the modern era. If only Silent Hill 3 and 4 could get the same treatment. Have a good day. :)

**Comment by elishacloud** [comment]
Interesting.  I did not realize that the screensaver is allowed in fullscreen windowed mode.  Normally the screensaver is disabled while using Direct3D9 in fullscreen.  See [here](https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dcreate).

As far as implementing this, it is quite easy and would only need two lines of code.  I can just call the [SetThreadExecutionState](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate) API.

**Comment by KojiKenshiro** [comment]
@elishacloud That would be awesome if it's as easy as you say to implement. Thank you for responding and have a good day. 😄

**Comment by elishacloud** [comment]
Added option to disable the screensaver:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4392180/d3d8.zip)

**Comment by KojiKenshiro** [comment]
@elishacloud Thank you for creating an updated d3d8.ini with the fix added. Will this make it into the next update by chance for anyone else that might have the same issue? Have a good day! :smiley:

**Comment by KojiKenshiro** [comment]
Since I see that this and the white shader fixes have been added I'll close this topic and download the d3d8.zip file when I turn my computer on in a bit.

**Comment by KojiKenshiro** [comment]
@elishacloud It works like a treat. Thanks again for helping me and anyone else who might have this issue down the road. 👍
