### ISSUE TITLE
Windows XP Support

### ISSUE THREAD

**Issue by aggserp4** [elishacloud/Silent-Hill-2-Enhancements#256]
I am trying to install SH2 Enhanced Edition on a Windows XP VM (VirtualBox 6.0.18 / Ubuntu 18.04). The base game installed successfully and runs with some minor issues. However, after installing the enhanced edition following the steps outlined in the installation guide I get a "The procedure entry point K32GetProcessImageFileNameW could not be located in the dynamic link library KERNEL32.dll" error. I assume this is a problem with Windows XP as you list Windows 7 as the minimum supported OS in your system requirements.

In issue #146 a fellow user has the same problem as me, and they are provided with a version of the SH2 Enhancements Module that is compiled for Windows XP. I haven't had the chance to try installing that yet, however it appears to be out of date now as the aforementioned module was last updated in February.

Out of curiosity I decided to clone this repository to my computer to see if I could compile the project for Windows XP. After opening the solution file in Visual Studio 2017 and downloading all the modules I was asked to (I should mention that I haven't used Visual Studio before) it appears that the target platform is already Windows XP (In the Project properties, Platform Toolset is set to "Visual Studio 2017 - Windows XP (v141_xp)). Upon attempting to build the project it tells me that I am missing the header file 'VersionHelpers.h', so I'm guessing I am missing some dependencies required to build the project.

My question is: Are the binaries on your website compatible with XP? And if they are not, is it possible for me to somehow compile the project so that it works on XP?

Thanks in advance.

EDIT: So I've just tried installing the SH2 Enhancements Module that was provided in issue #146. Upon launching the game it gives an "The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll" error. However, surprisingly, after pressing OK, the game launches! Only to immediately crash after the intro video ends.

I should mention that my copy of the game is the Restless Dreams edition and that I have installed patch 1.1. I have not installed IndirectSound or ReShade. The contents of d3d8.log are on [this](https://pastebin.com/C24006YA) pastebin.

Could this have anything to do with the fact that I'm running this on a VM? I do see a line that says `2888 13:00:20.548 Direct3DCreate8to9 Warning: WineD3D detected!  It is not recommended to use WineD3D with Silent Hill 2 Enhancements.`.

**Comment by elishacloud** [comment]
> it appears that the target platform is already Windows XP (In the Project properties, Platform Toolset is set to "Visual Studio 2017 - Windows XP (v141_xp))

Yes, the latest build is compiled with target platform Windows XP.  I don't have any Windows XP system on hand to test this.  If I have time I will take a look, but frankly I'm not sure when I will get to this.  If possible I would recommend running this on Windows 7 or Windows 10.

> Upon launching the game it gives an "The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll" error. However, surprisingly, after pressing OK, the game launches! Only to immediately crash after the intro video ends.

Yeah, I am not using that API in my code so it should run fine.  The crash may be related to something else, besides the missing entry point.

> Could this have anything to do with the fact that I'm running this on a VM?

No, it should work fine on a VMware.

> I do see a line that says `2888 13:00:20.548 Direct3DCreate8to9 Warning: WineD3D detected! It is not recommended to use WineD3D with Silent Hill 2 Enhancements.`.

This means that the game is able to detect "libwine.dll" or "wined3d.dll" loaded into memory.  You are either running this under Linux or you have added the WineD3D files.  Try renaming "d3d9.dll" to something else.

**Comment by aggserp4** [comment]
> This means that the game is able to detect "libwine.dll" or "wined3d.dll" loaded into memory. You are either running this under Linux or you have added the WineD3D files. Try renaming "d3d9.dll" to something else.

Yeah, I am running this VM on Linux. By "d3d9.dll" do you mean the file in the system32 folder? According to your website this file is a part of ReShade, which I haven't installed as I mentioned in my original post.

**Comment by mirh** [comment]
VersionHelpers.h only ships with [W8.1+ SDK](https://docs.microsoft.com/en-us/windows/win32/sysinfo/version-helper-apis). 
Microsoft itself is recommending to copy and use it wherever else you like though. 

Or you can even just mindlessly transclude those two or three functions you care for in [your code](https://github.com/elishacloud/Logging/blob/master/Logging.cpp) and call it a day.

**Comment by elishacloud** [comment]
Thanks @mirh!  Unfortunately, it was not quite that simple.  Copying `VersionHelpers.h` into the include folder did not immediately work.  Also, some of the hooking API's also had some issues.  Anyways, I think I got this working now.

@aggserp4, can you try the update below?  I think it should work on Windows XP.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4533650/d3d8.zip)

**Comment by aggserp4** [comment]
I finally got around to testing the build and I can confirm that it does work. It initially gives an error message that says something among the lines of "The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll" but after that, it appears to work perfectly. Unfortunately, as I anticipated it was a little slow on my VM but it should work well on a more powerful computer or real hardware.

Apologies for the time it took me to respond, I had deleted my VM and was a little busy for while. I have only tested this with the newest versions of the modules that were available at the time of your last response, so I can't guarantee that the current versions work.

**Comment by mirh** [comment]
> "The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll" but after that, it appears to work perfectly

That sounds like some dependency still having been built without v141_xp

**Comment by elishacloud** [comment]
> It initially gives an error message that says something among the lines of "The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll" 

The issue may be related to one of the [modules](https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/0c04c7e8f25c1e46fbfcfb283c9c20989bcf140d/Resources) that are included in the project.

Try this update.  It is the latest build and has all the additional modules disabled:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4840942/d3d8.zip)

**Comment by mirh** [comment]
2€ it's one of the 13AG's projects.

**Comment by aggserp4** [comment]
> Try this update. It is the latest build and has all the additional modules disabled: d3d8.zip
I tried this with the newest versions of all the packages and it works perfectly without any errors. Thanks a lot!

In case anyone else is trying to run the game under XP in the future, do not install IndirectSound, since XP has support for the hardware-accelerated sound that it emulates.
