### ISSUE TITLE
String fix/change proposal

### ISSUE THREAD

**Issue by Bruno3589** [elishacloud/Silent-Hill-2-Enhancements#257]
Hi,
while doing some tests for the new italian translation (and that means exploring every nook and cranny in the town) I think I came across a string issue very similar to Heaven's Night gate being reported with a "broken lock" while hanging ajar.

I also did a test in English to be sure it was not language-specific.
While exploring the town at night (after Brookhaven Hospital), if you try to get back to the alley where you first find the radio and wooden plank, you come to a closed gate.
However, if you try to open it, James says he can't get the _door_ opened:
![gate](https://user-images.githubusercontent.com/12817088/77855409-85da7e00-71f0-11ea-933f-dfb465b66c00.jpg)

This is a common string (it can be found **only** in common_msg_X) so it's the same one used in other parts of the game.
As I see it, there are 2 possible options here:
- Make the game use another common string, I guess the "broken lock" one can be used, however I'm not sure since there seems to be no lock and the gate is just blocked/boarded to keep it in place;
- Change the string in common_msg to be more generic, for example "I can't get it open.". This also works in Italian btw, though I'm not sure it can be applied to other languages.

**Comment by Bruno3589** [comment]
Another small one worth mentioning, this should be fixable with a simple string change in stage_hospital_3f_b_*.

In a room on the 3rd floor of otherworld Brookhaven Hospital, there is a note related to the "Lady of the Door" puzzle.
The string states the note is on the ground, however it isn't:
![immagine](https://user-images.githubusercontent.com/12817088/77855995-8c6af480-71f4-11ea-98c4-64a517009a3b.png)

It's hard to say since all furniture is wrapped up, but given the standard layout of the rooms on this floor, I'm guessing this is the bed? I think it can also be made generic, like "There's a scrap of paper here.".

**Comment by Bruno3589** [comment]
> 
> It's hard to say since all furniture is wrapped up, but given the standard layout of the rooms on this floor, I'm guessing this is the bed? I think it can also be made generic, like "There's a scrap of paper here.".

I just tried again with the flashlight turned off, and this time the string clearly refers to a "bed", so it's confirmed :)
![immagine](https://user-images.githubusercontent.com/12817088/77856581-65162680-71f8-11ea-90e5-02b74300a137.png)

**Comment by Polymega** [comment]
> I just tried again with the flashlight turned off, and this time the string clearly refers to a "bed", so it's confirmed :)

Nice catch. I changed it for English from:

 _"There's a scrap of paper on the ground."_ to _"There's a piece of paper on the bed."_

This is similar to another change I did a while back:

![image](https://user-images.githubusercontent.com/27395260/77856830-dbe6fb80-71c7-11ea-8a71-d67a2ee52b1a.png)

It used to say, _"There are dead butterflies on the ground. There's nothing else of interest here."_

--------------------------

**About the closed gate in Town East at night:**

I looked at the text strings for `stage_town_east_msg_*` and the only somewhat suitable replacement line I could find is: 

```
---------------
The road is blocked.
	I can't go any further this way.

I can't make it to the park this
	way. I'll have to find another way.<SEPARATORB>
---------------
```

But this shouldn't be used because, if the player interacts with this gate _before_ finding the letter and wrench, then James should have no knowledge that he should be returning to the park to find the key.

> Change the string in common_msg to be more generic, for example "I can't get it open.". This also works in Italian btw, though I'm not sure it can be applied to other languages.

I'm a little hesitant to change it like that for English. Mostly because the _"I can't get the door open"_ line has become infamous to most players. Let me think about that one for English...

**Comment by Polymega** [comment]
Actually, `stage_town_east_msg_*` also has this line: 

```
---------------
There's no reason to go back.
	I'm going to look for Mary...<SEPARATORB>
---------------
```

We could ask Belek666 to do the same type of thing with this gate [as we did with this one.](http://enhanced.townofsilenthill.com/SH2/config.htm#FixTownWestGateEvent)

**Comment by Bruno3589** [comment]
I guess it could work, also it would fix all languages at once.

For the "bed fix", now that I think of it, there might be the same issue for another note on the 1st or 2nd floor of the otherworld hospital.
I'm going to check it out, just to be sure.

**Comment by Bruno3589** [comment]
> 
> For the "bed fix", now that I think of it, there might be the same issue for another note on the 1st or 2nd floor of the otherworld hospital.
> I'm going to check it out, just to be sure.

Nevermind, there is another note on a bed on the 2nd floor (the room where you find the battery) but it's already correct.

**Comment by Badore90** [comment]
> About the closed gate in Town East at night:
> I looked at the text strings for stage_town_east_msg_* and the only somewhat suitable replacement line I could find is:
> ---------------
> The road is blocked.
> 	I can't go any further this way.
> 
> I can't make it to the park this
> 	way. I'll have to find another way.<SEPARATORB>
> ---------------
> 
> But this shouldn't be used because, if the player interacts with this gate before finding the letter and wrench, then James should have no knowledge that he should be returning to the park to find the key.
> 
> Change the string in common_msg to be more generic, for example "I can't get it open.". This also works in Italian btw, though I'm not sure it can be applied to other languages.
> 
> I'm a little hesitant to change it like that for English. Mostly because the "I can't get the door open" line has become infamous to most players. Let me think about that one for English…

What about "I can't open it". In italian it is good just this way "Non riesco ad aprire", literally: "I cannot open". It would solve for any kind of locks, doors and barred gates.

Or if you want to just correct this one separately. I don't know if I'm understanding correctly: you can point to any string of any file? If it's the case, it'd be possible to just point to a unused line??

i.e. **stage_hotel_3f_b_msg_e** lines **13**, **14**

**The lock might be broken.**
	**I can't seem to open it.**

**Comment by Polymega** [comment]
> What about "I can't open it"

I'm a little hesitant to change it like that for English. Mostly because the "I can't get the door open" line has become infamous to most players. Let me think about that one for English...

> you can point to any string of any file?

No, it must be a string that's currently loaded into memory. So while you're in Town East, `stage_town_east_msg_*` is loaded into memory, along with `common_msg_*` and probably a couple others.

**Comment by Badore90** [comment]
> What about "I can't open it"
> 
> I'm a little hesitant to change it like that for English. Mostly because the "I can't get the door open" line has become infamous to most players. Let me think about that one for English...
> 
> you can point to any string of any file?
> 
> No, it must be a string that's currently loaded into memory. So while you're in Town East, stage_town_east_msg_* is loaded into memory, along with common_msg_* and probably a couple others.

I see. 
About this phrase:

**There's no reason to go back.**
	**I'm going to look for Mary...**

may be good. I think it's not perfect, since it's clear that the gate is blocked (with confirmation banners too :D).

If the couple others files you said are stable, it'd be usefull to know which they are. I think we stumbled upon 3 or 4 unused lines.

**Comment by Badore90** [comment]
> I'm a little hesitant to change it like that for English. Mostly because the "I can't get the door open" line has become infamous to most players. Let me think about that one for English...

What do you mean this line become infamous?  Sorry for the curiosity, I don't know this story.

**Comment by Polymega** [comment]
With 90% of the doors being broken, this line, word-for-word, has become ingrained in so many peoples' heads.

**Comment by Bruno3589** [comment]
> With 90% of the doors being broken, this line, word-for-word, has become ingrained in so many peoples' heads.

I might be wrong, but isn't "It looks like the lock is broken. I can't open it" the line you're referring to?

To be clear, I'm not against using the "I'll go look for Mary" one, it's just a clarification.

**Comment by Polymega** [comment]
> I might be wrong, but isn't "It looks like the lock is broken. I can't open it" the line you're referring to?

No, you're right. My mind is kind of all over the place at the moment. I'll update the English version from "I can't get the door open," to "I can't open it."

**Comment by Bruno3589** [comment]
> No, you're right. My mind is kind of all over the place at the moment. I'll update the English version from "I can't get the door open," to "I can't open it."

Ok! We'll update italian accordingly.

**Comment by Bruno3589** [comment]
@IlDucci you may want to fix Spanish translation too.
In short:
### common_msg_*
Change
`I can't get the door open.`
to
`I can't open it.`

### stage_hospital_3f_b_*
"Lady of the Door" riddle, first find: make sure it says there's a piece of paper on the **bed** and not on the ground.

**Comment by IlDucci** [comment]
Thanks for the heads-up! Here's the changes. I think @Polymega can do the bed fix for the remaining languages, as the correct option is displayed later on in every language.

[102 CHANGES ESN.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4421215/102.CHANGES.ESN.zip)

**Comment by Polymega** [comment]
Thank you, gentlemen.

**IlDucci:** I'll add these updated Spanish files for the next package release, and hand-correct the French and German versions for the bed fix.

**Comment by elishacloud** [comment]
Closing this out.
