### ISSUE TITLE
Game opens with a black screen, then it closes

### ISSUE THREAD

**Issue by DlukKnight** [elishacloud/Silent-Hill-2-Enhancements#260]
Hi, I've been trying to make this work, but it just closes after a while. I tried with a clean installation in a folder not in Program Files, puting one enhancement and trying, eliminating the IndirectSound files, etc. It seems to always crash in the same part all the time. I am on Windows 10, game was working fine with Windows 7 a year ago.

My log file: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4451882/d3d8.log)

Thanks a lot for the support and for the awesome work you did with this!

**Comment by Polymega** [comment]
Hi there, 

> but it just closes after a while [...] It seems to always crash in the same part all the time.

Is it a specific point in the game when the crash happens? If so, can you describe this in more detail?

**Comment by DlukKnight** [comment]
Just starting it does this, however, yesterday I managed to solve this, but it was strange. The problem went away when installing de x64 versión of Visual C++ 2010 Redistributable Package, which doesn't make sense, since the x86 version was the requisite for IndirectSound, which wasn't present in the folder when this error happened. Maybe the installation fixed something internal, I don't know. I've been trying to solve this for a few days, I'm glad I managed to make it work but I'd like to know what happened so others can benefit from it.

**Comment by DlukKnight** [comment]
I've been playing until the hospital and this issue seems to be fully gone. Dunno how installing the x64 versión of the redist solved this, but the game runs perfect every time I open it now.

**Comment by Polymega** [comment]
I'm glad you got this figured out! Thanks for further testing and following up with this.

In the future, we plan to remove our dependency on IndirectSound, which would also remove the need to download either version of the C++ 2010 Redistributable Pack.

**Comment by DlukKnight** [comment]
> 
> 
> I'm glad you got this figured out! Thanks for further testing and following up with this.
> 
> In the future, we plan to remove our dependency on IndirectSound, which would also remove the need to download either version of the C++ 2010 Redistributable Pack.

No problem, I'm glad to be able to replay this awesome game, so thanks a lot for the work and effort! I hope more people get to experience the Enhanced Edition, is really beautiful.

Thanks!
