### ISSUE TITLE
Black Screen on Startup

### ISSUE THREAD

**Issue by vu-j** [elishacloud/Silent-Hill-2-Enhancements#261]
Hey the game was working perfectly fine, but I just installed new GeForce drivers and now it gets stuck on startup. Black/Blank screen. I tried uninstalling the whole game and re-installing but same exact problem. What to do?

**Comment by Polymega** [comment]
Hello,
To start things off simple: Have you restarted your PC after updating your video drivers? Sometimes that's needed (even if the update says no restart is required) to get game applications working again like before.

**Comment by vu-j** [comment]
Hey - haha, yeah I have. I tried pretty much everything, I even found another thread saying I have to set SingleCoreAffinity to 2 in the .ini, and still nothing :(

**Comment by vu-j** [comment]
I have no idea what happened but it started working out of the blue.

I went into DXwebsetup.exe, it said I had the latest version, closed it. Then I restarted the game and it magically worked!

**Comment by Polymega** [comment]
That's good to hear! I'm glad things worked out quickly and painlessly.
