### ISSUE TITLE
Can you help me 

### ISSUE THREAD

**Issue by maratmine1** [elishacloud/Silent-Hill-2-Enhancements#262]
I have trouble with the sound. Sound getting faster than cutscene each second. Cold you please help me

**Comment by Polymega** [comment]
**Remove** the following files/folders and see if this fixes the cutscene pacing issue: 

```
reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by maratmine1** [comment]
Thank you a lot! It helped!

**Comment by elishacloud** [comment]
Closing this out.

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
