### ISSUE TITLE
Controller triggers not working

### ISSUE THREAD

**Issue by grammstack** [elishacloud/Silent-Hill-2-Enhancements#263]
Hey, I believe i've gotten all the enhancement stuff working, and it's all fantastic, but when i go into the options to change controller button mapping, the game doesn't recognize the controller's trigger presses. i'm using an xbox one controller, and i ran xinput plus and set sh2pc as the target program, which created the xinput dll and ini files in the silent hill 2 folder. maybe i'm missing something else, but this is currently the only thing stopping me from enjoying what appears to be a wonderful experience.

**Comment by Polymega** [comment]
Hi grammstack,

Try downloading and using our premade XInput Plus files and see if it works for you then: 
http://enhanced.townofsilenthill.com/SH2/files/XInputPlus_4.15.2.zip

We've preconfigured the files to work out of the box.

**Comment by grammstack** [comment]
Yep, that fixed it. Thanks a bunch. Problem was that i just downloaded xinput plus yesterday from the source, so when i saw the silent hill enhanced edition installation guide had a link that said download the version of xinput i already had, i assumed i already had what i was being asked to download. my bad lol. once again, problem solved.  thank you.
