### ISSUE TITLE
Menus not showing up

### ISSUE THREAD

**Issue by JvanHaughm** [elishacloud/Silent-Hill-2-Enhancements#264]
Hi, i downloaded all the necessary stuff to make the enhanced version of SH2 work, and it's perfect, except for the issue with the menus, it won't display the texts in the options menu, nor the pause menu as well. I have read and tried pasting the new messages files in the etc folder as suggested in another thread, but it is still not working for me, I appreciate the help.

![unknown2](https://user-images.githubusercontent.com/63740226/79366341-677bbe80-7f22-11ea-8507-d7ef1edcbc89.png)

![unknown](https://user-images.githubusercontent.com/63740226/79365793-7ca41d80-7f21-11ea-9403-2354367cfd14.png)

![unknown3](https://user-images.githubusercontent.com/63740226/79366429-9134e580-7f22-11ea-8047-7af575a85253.png)

**Comment by Polymega** [comment]
It seems like you may have the same issue as this person: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/240

Can you please attach a copy of your `d3d8.log` file?

**Comment by JvanHaughm** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4482715/d3d8.log)
Hi @Polymega this is the file!

**Comment by Polymega** [comment]
Thanks. It looks like you have the same issue as the link I sent. Your integrated graphics chipset can't handle the incredibly large resolution of the HD font package. IGP graphics around 2010 and earlier weren't made with gaming in mind.

Here is my suggestion to get the best experience on your Windows computer. 

**Set in d3d8.ini file:**

```
UseCustomFonts = 0
Nemesis2000FogFix = 0
```

**Remove the following files/folders from the game's directory:**

```
reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

This will:
- Disable the HD fonts. The resolution of the HD font file is too large for this old integrated graphics chipset to handle.
- Disable the Fog Fix. Your chip will very likely not be able to handle the increased fog effects. My Intel HD 4400 IGP can't even handle the Fog Fix on my Surface Pro 3 laptop.
- Remove ReShade, if you were using it. ReShade is too demanding for weaker/older computers.

**Comment by JvanHaughm** [comment]
Yes, i was reading the other user's issue and yeah, it's basically the same. Thanks for your time, I'll try and see if that works for me.

**Comment by elishacloud** [comment]
Closing this out.
