### ISSUE TITLE
Hospital Elevator Crash

### ISSUE THREAD

**Issue by ZimSan** [elishacloud/Silent-Hill-2-Enhancements#265]
I'm right now at the hospital in Silent Hill 2 and the game keeps crashing when I use the elevator. Doesn't matter if it's the hell dimension or not. No message gets shown. It happens often enough to be annoying.

**Comment by Polymega** [comment]
Hello,
Please attach a copy of your d3d8.log file.

**Comment by ZimSan** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4495714/d3d8.log)

**Comment by Polymega** [comment]
Thank you. From your initial post, I had a hunch that the [single core affinity fix](http://enhanced.townofsilenthill.com/SH2/config.htm#SingleCoreAffinity) wasn't active or working. Looking at your log file, that seems to be the case. Can you open your `d3d8.ini` and ensure `SingleCoreAffinity` is set to a value of `1` or higher?

**Comment by ZimSan** [comment]
SingleCoreAffinity is set to 1 already but I set it to 4 now.

**Comment by Polymega** [comment]
Okay, give that a try. Here is what you're looking for:

After launching/closing the game, open your `d3d8.log` file again (it should update itself everytime you relaunch/close the game). If the `SingleCoreAffinity` fix is working, you'll find a line near the bottom of the log file that looks something like this:

```
19964 02:16:32.434 Setting SingleCoreAffinity...
```

If you see that, the `SingleCoreAffinity` fix is working, which should fix the game randomly freezing/crashing/sound looping.

**Comment by ZimSan** [comment]
Nope. Didn't work.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4495759/d3d8.log)

**Comment by Polymega** [comment]
Okay, we might need to get @elishacloud involved to see why the `SingeCoreAffinity` fix isn't working for you.

**Comment by ZimSan** [comment]
Thanks

**Comment by elishacloud** [comment]
> we might need to get @elishacloud involved to see why the `SingeCoreAffinity` fix isn't working for you.

Most likely it is crashing before the module has time to set the core affinity.  I created an update that has a bunch of extra logging.  Can you try this build and send me the log file?

Updated build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4519616/d3d8.zip)

**Comment by ZimSan** [comment]
Played through the Hospital again and it seems to be working now thanks to the fix. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4523137/d3d8.log)

**Comment by Polymega** [comment]
Great! Lastly, use this build instead:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4520174/d3d8.zip

It's the same exact build, but disables all the extensive, extra logging for the `d3d8.log` file. The test build you're currently using logs a lot of extra stuff for troubleshooting and, when playing the game for too long, will make the log file's size huge due to all the logging.

**Comment by ZimSan** [comment]
Thanks again. You guys have been really helpful and I hope your Enhancement project continues to succeed.

**Comment by Polymega** [comment]
I'll close this ticket. Please feel free to re-open it if the issue arises again.
