### ISSUE TITLE
Game will not launch

### ISSUE THREAD

**Issue by djbeema** [elishacloud/Silent-Hill-2-Enhancements#266]
I've tried multiple clean installs, restarts, etc, the same problem persists. The game simply won't launch at all when I try to open the exe or via the CD menu, start menu, etc. Nothing happens, although it does generate the log files (attached) if they weren't there previously. I'm using the version of the game from myabandonware. Running Windows 7 x64, have an AMD 955 cpu and GeForce GTX 770 vid card.

[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4497991/d3d9.log)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4497992/d3d8.log)

**Comment by Polymega** [comment]
Thanks for doing some preemptive tests and providing the log files.

Whenever the SH2 Enhancements module has an update there will be a pop-up box on game launch informing you of this, if you have `AutoUpdateModule = 1` in the `d3d8.ini` file.

Looking at your log file, this is the last thing it does before your game stays on a black screen.

What I think is happening is that the update box is popping up _behind_ the game window, so you don't see it. And the game will not continue to launch until you make a selection on this update box screen.

For the time being, you can try setting `AutoUpdateModule = 0` and relaunch the game. This should hopefully fix it for you.

We're not 100% happy with how the current modupdater works for reasons such as what you're experiencing, and hope to address this and possibly make a new, different form of update for the module in the future.

Let me know if that fixes it for you.

**Comment by djbeema** [comment]
Okay so I changed it to `AutoUpdateModule = 0`, and trying to open the exe still wasn't doing anything. Then I went to open the original exe, the one re-labeled to `sh2pcBACKUP.exe` and... 
the game launched, with EE working on it I believe, and works fine!

**Comment by Polymega** [comment]
How odd, but I'm glad things seem to be working now! I wonder why the game is only launching with the myabandonware executable?

**Comment by djbeema** [comment]
yeah weird as hell, but thanks for the work on the game, enjoying it now!

**Comment by elishacloud** [comment]
I am guessing it is the compatibility settings.  Sometimes Windows automatically adds compatibility settings.  You can test this by renaming `sh2pcBACKUP.exe` back to `sh2pc.exe` and see if it stops working.  If it does stop working then you can try resetting the compatibility settings in Windows for this process.

![image](https://user-images.githubusercontent.com/25625456/79677846-285f9e80-81aa-11ea-9c15-25d50baf6101.png)
