### ISSUE TITLE
Silent Hill 2 Enhanced BrookHaven Hospital Crashes

### ISSUE THREAD

**Issue by Corvus-Ludens** [elishacloud/Silent-Hill-2-Enhancements#267]
Hello, I installed the game and all the Enhanced edition files a few days ago (excluding the ReShade) and played through the intro and the Apartments with a crash here or there but they were few and far between. When i entered BrookHaven i noticed an increase in crashes, and i made it to the Alternate hospital and whenever i enter the game i get a couple of minutes before the game crashes and i'm back at my desktop. Any help at all would be amazing! Thank you in advance

**Comment by Corvus-Ludens** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4500311/d3d8.log)

**Comment by Corvus-Ludens** [comment]
As some additional info (not sure if its any help) but i had a crash or 2 in the apartments but as mentioned before it was only a couple, and not enough to be annoying. However when i entered the hospital and it seems more frequent with an encounter of more than one Nurse the crashes are more frequent, like on the 2nd floor of the Alternate Hospital there's the room with 2 nurses, I have been able to enter twice without crashing before getting there, but every time i entered the room and started fighting the 2 Nurses i have crashed shortly after engaging them.

**Comment by Polymega** [comment]
Hi Corvus-Ludens, 

Sorry you're having troubles with the game randomly crashing. From your initial post, I first thought that the [SingleCoreAffinity](http://enhanced.townofsilenthill.com/SH2/config.htm#SingleCoreAffinity) fix wasn't working for you, [similar to this person's problem.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/265)

But looking at your log file, it seems that `SingleCoreAffinity` is hooking into the game, so I guess that's not the problem.

Can you check something for me? Right click `sh2pc.exe` and go to **Properties**. Under the **Compatibility** tab can you check and ensure **Compatibility Mode** is NOT checked? Are there any other things that might also be checked under the **Compatibility** tab?

**Comment by Corvus-Ludens** [comment]
Thanks for getting back to me so quickly! I've had a look in the area you mentioned and everything is off, compatibility mode and everything else is NOT on.

**Comment by Polymega** [comment]
Perfect. Thanks for checking. I have some other things we can try, but first, can you send a snapshot of the game's installation directory? Just the main directory that the game is housed in, please.

**Comment by Corvus-Ludens** [comment]
![Troubleshooting (2)](https://user-images.githubusercontent.com/63979997/79701193-f118ec80-8292-11ea-88c3-4ac4201617d8.png)
Here you go! and please ignore my Meme folder..

**Comment by Polymega** [comment]
No judgment; memes are the life force of the internet. 😆 

Okay, your installation directory is impeccable. I was hoping there was some rogue/foreign file in there causing the problems, but that doesn't seem to be the case.

So there is typically some culprits that can cause crashes/freezes in the game. So let's trying disabling them just to see if you no longer experience crashes afterwards:

(If you need to enable file extensions,[ steps to do so can be found here](https://www.wikihow.tech/Show-File-Extensions-on-Windows).)

In the `d3d8.ini` file:
- Set `d3d8to9 = 0`. This will disable both d3d8to9 and ReShade.
- Set `AutoUpdateModule = 0`.
- Set `SingleCoreAffinity` to a value **greater** than `1`. Try setting it to `3` or `4`. Perhaps there's too much load from other programs on the first core of your CPU causing these hang-ups/crashes.

Additionally:
- Temporarily remove `dsound.dll` from the game's directory. This will disable IndirectSound.
- Enable High DPI Scaling for the game. [Instructions found here.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#a-burntin-image-appears-during-screen-fade-transitions) I don't think this has anything to do with your issue, but it doesn't hurt to try.

We're going to throw everything and the kitchen sink at this in hopes of fixing it. If this does fix the crashing, we can then re-enable things one-by-one to hopefully determine what is causing the issue.

**Comment by Polymega** [comment]
Oh! By the way, can you also confirm you have our updated audio files under `sh2e\sound\`?

I remember watching streamers a while back who either forgot to download that package or put the files in the wrong spot. Not only did it cause audio problems, but it would also sometimes crash the game as a result.

The `sh2e\sound\` folder should look like this:

![image](https://user-images.githubusercontent.com/27395260/79701402-d0d53780-826a-11ea-8aaa-3f98f8e89264.png)

**Comment by Corvus-Ludens** [comment]
![Sound Folder (2)](https://user-images.githubusercontent.com/63979997/79701426-ef502880-8294-11ea-9577-260e14c7f271.png)
Heres the sound folder, icons are different though but i think the file is the same.

**Comment by Corvus-Ludens** [comment]
Just finished adjusting the things you mentioned and removing the file, i'm gonna give it a test for a little bit and see if theres a change, thanks again for the help so far ^^

**Comment by Polymega** [comment]
Yep, your `sh2e\sound\` folder looks good. My `sddata.bin` file is a different file size as I use [a slightly adjusted version of it.](https://www.youtube.com/watch?v=nPMzjrEDjB4)

Good luck! I hope this will resolve the issue. If so, we can slowly add back some of those disabled features one-by-one to hopefully determine what specifically is causing the crashes.

**Comment by Corvus-Ludens** [comment]
Ok, i just tried the game, i went up the elevator and walked into the first Nurse, and seconds after seeing her on screen it crashed.
I'll be sure to send another log file.

**Comment by Corvus-Ludens** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4500428/d3d8.log)

**Comment by Polymega** [comment]
Damn. One last things, maybe: Do you have anti-aliasing or any other kind of GPU feature(s) enabled for the game through your Nvidia control panel? Or maybe you have a **global** setting that affects all games you launch/play?

![image](https://user-images.githubusercontent.com/27395260/79701751-8b663980-826d-11ea-9970-2d8a89112db6.png)

**Comment by Corvus-Ludens** [comment]
![AA Troubleshoot (2)](https://user-images.githubusercontent.com/63979997/79701808-fc224b80-8297-11ea-9cde-0ec1c0eded73.png)
Heres what mine looks like, looks the exact same as the one you sent me so i'm not sure.

**Comment by Polymega** [comment]
This one's a head-scratcher. We may need to get our expert @elishacloud to look at this. He's tagged now so hopefully he'll have an idea I didn't think of.

**Comment by Corvus-Ludens** [comment]
Ah right, guess i'll head back to waiting but i do wanna thank you again for helping me through some things, it really is appreciated ^^

**Comment by Badore90** [comment]
> Ah right, guess i'll head back to waiting but i do wanna thank you again for helping me through some things, it really is appreciated ^^

You're using the USA 1.0 executable right??

Because (at least for me) it is the more stable. I got some crashes with the 1.1 version. 
The european exe is even worse.

**Comment by Corvus-Ludens** [comment]
It's fine, I was originally using the EU exercise but switched to the NA to try and fix the issue, I haven't noticed a change this far.

**Comment by Corvus-Ludens** [comment]
As an update I started playing through today and managed to make it through the entirety of BrookHaven hospital without a crash. I haven't changed any of my settings and have gotten to the Historical Societu building so far with no issues at all. Unsure what has changed in all honesty

**Comment by Corvus-Ludens** [comment]
As another update I have continued playing from the previous update, made all the way to the Hotel at the end, and have not had a single issue since last reported, still no change to the settings changed previously

**Comment by Polymega** [comment]
Sometimes a simple, good ole fashioned reboot of the PC can do the trick. Perhaps there was another program running in the background as you were playing the other night which was creating the conflicts?

Either way, I'm happy to hear things have smoothed out for you now!

**Comment by Corvus-Ludens** [comment]
You're probably right, still I'm cautious to change any settings back that we changed, but thanks again for all the help its greatly appreciated!

**Comment by Polymega** [comment]
Out of everything we tested/disabled last night, the only one I'd really recommend re-enabling is IndirectSound by placing the `dsound.dll` file back in the game's directory. It fixes some of the audio clicks/pops you'd otherwise be hearing.

Try putting that file back in and relaunching the game. If you get crashes again you'll know that's likely the culprit.
