### ISSUE TITLE
Camera Editor problem

### ISSUE THREAD

**Issue by Badore90** [elishacloud/Silent-Hill-2-Enhancements#268]
I just downloaded **sh2pc_camera_editor.exe** but couldn't make it to normally start.

I double click on it, then it requires admin privileges, I press Ok and this pops up:

![Immagine](https://user-images.githubusercontent.com/44087144/80806894-1a534a00-8bbc-11ea-9e48-d8505b0e4141.jpg)

It happened to someone else??

**Comment by Polymega** [comment]
You need to also have Cheat Engine on your PC to use the camera tool. I didn't realize that at the time. I probably need to delete my YouTube video on it for that reason, as I know most people will not want to download Cheat Engine for a variety of reasons.

**Comment by Polymega** [comment]
PS - I'd you decide to download Cheat Engine be careful how you install it. Their normal installer is... questionable. You can try this package instead:

![Screenshot_20200501-112348~2](https://user-images.githubusercontent.com/27395260/80816913-68595500-8b9e-11ea-900b-9740c161b4eb.png)

Download at your own risk.

**Comment by Badore90** [comment]
> PS - If you decide to download Cheat Engine be careful how you install it. Their normal installer is... questionable. You can try this package instead:
> 
> Download at your own risk.

Thank you very much. 

I think that video is really good, I already saw it much time ago but forgot it. You could leave it and just add the cheat engine infos in the description (or just leave it as it is, as you prefer. Anyway it's a cool demostration video, imho there's non need to delete it).

**Comment by Polymega** [comment]
Sure thing. Also, never have Cheat Engine running while using Steam or Origin. Cheat Engine can be used as a cheating device for games and will be flagged as such on Steam/Origin/etc, which could ban your account for online play.

I also set the video to unlisted so it's still there if people have the link: https://youtu.be/G-XvyIjZQoE

**Comment by Badore90** [comment]
Just tried it. Downloaded as you suggested me, from here: https://www.cheatengine.org/download/CheatEngine7.1_MissingSetup.rar

I just unzipped the folder and pointed the camera editor to open with **cheatengine-x86_64.exe**

No problems at all. All solved, thank you again :D

**Comment by Badore90** [comment]
> Sure thing. Also, never have Cheat Engine running while using Steam or Origin. Cheat Engine can be used as a cheating device for games and will be flagged as such on Steam/Origin/etc, which could ban your account for online play.

I understand. I just pointed the camera editor to be opened with Cheat Engine, so as soon as I close the camera editor cheat engine stops running too, right?

**Comment by Polymega** [comment]
It should. You can always do Task Manager > Processes to ensure it's no longer running after closing the camera tool.

**Comment by Badore90** [comment]
> It should. You can always do Task Manager > Processes to ensure it's no longer running after closing the camera tool.

Yes I checked it. However it wasn't that simple, the camera editor boot but doesn't work with the game. Maybe I have the move the cheat engine to Program Files x86 or copy the dll files to the corresponding Windows folders. I'll try that Tomorrow and make you know if I manage to make it to work.

**Comment by Badore90** [comment]
It's strange, if there were problems the program simply shouldn't run I think…

It seems like it doesn't connect with the game. I need some particular settings on the game, like to run it in Fullscreen?

**Comment by Polymega** [comment]
You shouldn't have to place Cheat Engine in your `Program Files (x86)` directory. I don't and it works for me. 

Typically, you need to launch SH2 PC first, then launch the camera tool after (so it can hook into the game). It can sometimes work by launching the tool first, but typically you want to launch the game first.

No special settings required within the game to make it work; you just need to ensure [you're using the North American 1.0 executable](http://enhanced.townofsilenthill.com/SH2/files/SH2PC_Enhanced_EXE_NA_v1.0.zip), is all.

**Comment by Badore90** [comment]
> Typically, you need to launch SH2 PC first, then launch the camera tool after (so it can hook into the game).

This is what I was doing wrong, thank you! 

![sh2pc 2020-05-02 16-06-10](https://user-images.githubusercontent.com/44087144/80866500-55727d80-8c8f-11ea-8523-bf02ab7fd7c3.png)

**Comment by Polymega** [comment]
Very cool! Have fun!
