### ISSUE TITLE
Runtime error when attempting to launch Silent Hill 2 with Enhancements

### ISSUE THREAD

**Issue by JikissGamer** [elishacloud/Silent-Hill-2-Enhancements#27]
I followed the installation instructions very carefully, but whenever I try to run Silent Hill 2 with the enhancements I get this "Runtime Error!"

It says:

---------------------------------------------------------------------------------------------------
Microsoft Visual C++ Runtime Library

Runtime Error!

Program C:\Users\Sean\Documents\KONAMI\SILENT HILL 2\sh2pc.exe

This application has requested the Runtime to terminate it in an unusualway.
Please contact the application's support team for more information.
----------------------------------------------------------------------------------------------------

Anyone know how to solve this issue?

**Comment by Polymega** [comment]
Hi @JikissGamer , 

Did you install the [Microsoft Visual C++ 2010 Runtime Libraries](https://www.microsoft.com/en-us/download/details.aspx?id=5555) to see if that fixes your issue?

**Comment by JikissGamer** [comment]
I downloaded and installed this but it still gives me the same error. I even tried it on my other PC and it gets the same message.

**Comment by Polymega** [comment]
I see, what if you set `d3d8to9 = 0` in the `d3d8.ini` file? Does it run then?

If it runs then, trying downloading the [DirectX 9 Runtime Libraries](https://www.microsoft.com/en-us/download/details.aspx?id=35).

**Comment by JikissGamer** [comment]
Ah that did the job, now it's working. Thanks for the help!
