### ISSUE TITLE
Fix flashlight at end of failed clock push cutscene

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#271]
This is an issue that affects all versions of the game. After James tries to unsuccessfully push the apartment clock, his flashlight no longer affects/influences the clock at the end of the event:
https://youtu.be/6UDLkMD40pA?t=2217

Fixed: https://www.youtube.com/watch?v=NQhPyoQOAIg

----------------------

The approach to this fix will be a little different than other cutscene ID fixes. An explanation why:

The final frame of animation for this cutscene is when the flashlight glitches out. But the cutscene is also technically over on the final frame of animation as well (it changes back to `0x00` right before the flashlight glitches).  So the flashlight glitch happens between the end of the cutscene and before the user presses a button to regain control of the character.

So for this fix, we need to use the cutscene ID only as a flag/trigger, and then use another address to monitor/know when to enable/disable the fix for the flashlight here.

- When cutscene ID `0x0C` is triggered:
   - Monitor [`full screen image event`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/118#issuecomment-621375513)
      - If `full screen image event` == `0`
         - Set `0048E85A 4 bytes` to `0xFFFFFFEF` (one write, no constant iteration)
      - When `full screen image event` == `1`
         - Set `0048E85A` to `0xFFFFFF3F` (default value, one write, no constant iteration)
         - Finish monitoring `full screen image event`

This cutscene can be triggered numerous times, so the script would need to reset upon completion.

------------------------

Thank you to Bigmanjapan and Aero_ for the research and optimization, respectively.

**Comment by elishacloud** [comment]
Implemented a fix for this in a test build.

Here is the testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4679743/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha. For this one, I don't see the fix taking effect. `0048E85A 4 bytes` is staying at `0xFFFFFFEF` while `fullscreen image event` == `0` after the trigger of cutscene `0x0C`.

**Comment by Polymega** [comment]
Slight adjustment to the pseudo code, if it might help:

- When cutscene ID `0x0C` is triggered:
   - Stop monitoring for cutscene `0x0C`
   - Monitor [`full screen image event`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/118#issuecomment-621375513)
      - If `full screen image event` == `0`
         - Set `0048E85A 4 bytes` to `0xFFFFFFEF` (one write, no constant iteration)
      - When `full screen image event` == `1`
         - Set `0048E85A` to `0xFFFFFF3F` (default value, one write, no constant iteration)
         - Finish monitoring `full screen image event`
         - Start monitoring for cutscene `0x0C` trigger again

This cutscene takes place in room `0x18`.

**Comment by elishacloud** [comment]
Ok, try this one below.  It turns out I was using the wrong variable for the fullscreen image value.

New testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4679931/d3d8.zip)

**Comment by Polymega** [comment]
Thanks. For this one, once `fullscreen image event == 0` then `0048E85A` starts constantly flucuating between `0xFFFFFFEF` and `0xFFFFFF3F` until `fullscreen image event == 1`.

**Comment by elishacloud** [comment]
Ok, I see.  I made a dumb logic mistake.  This update should fix that.

New testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4679953/d3d8.zip)

**Comment by Polymega** [comment]
This works good, but after being able to test it "live" it won't work. Sorry about that. `fullscreen image event` changes back to `1` too slow after the user regains control of the character so you can see James' flashlight shifting back to its correct state, which looks wrong.

So sorry to ask you to abandon this current code structure, but can we try a simpler approach?

- If in room `0x18` && [`InGameCameraYOrientation`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/dc8a64964c42513a63f51f9343f5926ab735628e/Patches/FogAdjustments.cpp#L218-L220) == `-112.6049728f`
   - Set `0048E85A 4 bytes` to `0xFFFFFFEF` (one write, no constant iteration)
- Else
   - Set `0048E85A 4 bytes` to `0xFFFFFF3F` (one write, no constant iteration)

**Comment by elishacloud** [comment]
> So sorry to ask you to abandon this current code structure, but can we try a simpler approach?

Sure, no problem.  Below is a quick testing build.  This is a safe fix.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4680060/d3d8.zip)

**Comment by Polymega** [comment]
> This is a safe fix.

The game crashes as soon as it loads into this room!  :stuck_out_tongue_closed_eyes:

**Comment by Polymega** [comment]
> This is a safe fix.

The game crashes as soon as it loads any room/area!  :stuck_out_tongue_closed_eyes:

**Comment by elishacloud** [comment]
Ok, wrong jmp value.  Try this one.

New testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4680092/d3d8.zip)

**Comment by Polymega** [comment]
This one's the ticket! Works correctly and works well across all binaries. Thanks for helping with this and letting me pull your chain a little. :)

**Comment by Polymega** [comment]
Forgot about this. Possible suggestion: 

```ini
; Fixes flashlight rendering on the apartment grandfather clock after a failed attempt to push it. (0|1)
FixAptClockFlashlight = 1
```

Also, you'll want to add a `(0|1)` to the end of `AudioClipDetection` in the INI. Thanks again.

**Comment by elishacloud** [comment]
Ok, I fixed this up a bit.  Below is the final testing build.  It should work the same as the last.

Final testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4680183/d3d8.zip)

**Comment by Polymega** [comment]
Yes sir; all still working well across all binaries.

**Comment by elishacloud** [comment]
Great.  Code done:  192bdc4a15ec02c4b5c561a1f6489afc7d247b7c
