### ISSUE TITLE
How the fog fix was implemented?

### ISSUE THREAD

**Issue by 894-572** [elishacloud/Silent-Hill-2-Enhancements#274]
http://www.enhanced.townofsilenthill.com/SH2/config.htm#fog_custom_on

> Enables the Fog Fix, which makes the game's fog closer resemble the PlayStation 2's version, which is considered the best.
> 
> - Initial R&D, proposed solution, and testing: [Nemesis2000](http://www.enhanced.townofsilenthill.com/SH2/credit.htm#Nemesis2000)
> - Solution developed and written in C++: Nemesis2000
> - Mod implemented: [Elisha Riedlinger](http://www.enhanced.townofsilenthill.com/SH2/credit.htm#Elisha_Riedlinger)

Can you clarify if the fog was recreated programmatically or by comparing with the PS2 version and manually tweaking the values? [I'm afraid that I can't find this out myself...](https://github.com/elishacloud/Silent-Hill-2-Enhancements/search?q=fog&unscoped_q=fog)

**Comment by Polymega** [comment]
The latter; through comparison and adjusting. Some additional, unique code was added to further flesh out the fog fix, though.

**Comment by Polymega** [comment]
Closing this ticket out.
