### ISSUE TITLE
Ray Tracing Global Illumination Shader

### ISSUE THREAD

**Issue by Tuscarorachief081** [elishacloud/Silent-Hill-2-Enhancements#276]
Ever thought about creating Material based Maps/Textures that would work with the ReShade Ray Tracing shader by Pascal Glicher? https://reshade.me/forum/shader-discussion/5450-guide-to-ray-tracing-with-reshade
Silent Hill 2 with Ray Tracing and realistic textures to match would be beyond amazing!

**Comment by Polymega** [comment]
Hi Tuscarorachief081,
Thanks for the suggesting! At this time, we haven't planned to do any sort of ray tracing for the game. The results with that shader on the right games looks great, though!

**Comment by Polymega** [comment]
Closing this ticket out.
