### ISSUE TITLE
d3d8.ini changes not reflecting in the game

### ISSUE THREAD

**Issue by ummauricio** [elishacloud/Silent-Hill-2-Enhancements#279]
I wanted to change the fogdensity value cause the game is running slow in outside areas, but it doesnt really seem to be actually changing in game... I tried turning the fog fix value to 0 to test the functionality of the d3d8.ini but it didn't worked...

**Comment by Polymega** [comment]
Do you have a `d3d8.log` file in the game's directory? If you don't, that means the module isn't hooking. If you do, can you please attach it?
