### ISSUE TITLE
[Low Priority] Title screen loads in 4:3

### ISSUE THREAD

**Issue by SpaceCowboy3514** [elishacloud/Silent-Hill-2-Enhancements#280]
Hey just wanted to let you know that this is not a big issue and to not worry about it but for me the title screen loads in 4:3 instead of 16:9, thanks for the cool mod either way, it gives me the best possible experience playing this game

**Comment by Polymega** [comment]
Hi SpaceCowboy3514,

The main menu and save screens should be in 16:9. Be sure you've updated both the [SH2 Enhancements Module](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) and the [Essential Files package](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE).

(Do note we haven't made any of the other 2D, full screen images widescreen yet.)
