### ISSUE TITLE
DualShock 4 = Crash on freeze.

### ISSUE THREAD

**Issue by ThunderStormOwl** [elishacloud/Silent-Hill-2-Enhancements#281]
Hey guys,

First of all great work on this fantastic game.
I have a pretty werid issue for you. After tons of testing and trying I found out that my ps4 controler being conected via USB was crashing the game. First I thought it was the reshader because it appeared to crash on the loading effects message but after I uninstalled it and ran the game it crashed on back screen before konami logo. Unpluged my DS4 and it worked. Re-installed reshader and it worked, ran DS4Windows without conecting my controler and it worked. Conected my controler and crash on start every time with the controler on, runs fine everytime with the controler off. Weird huh?

I tried a bunch of stuff using the xinput files and restorecam = 2, no files and restoream = 1, with files and restorecam= 1. When the controler is plugged it just doesn't work. I realise this is a minor issue but you have anything that I can try please let me know. I love this game and if the only way to play it is to buy an Xbox controler just for it I will I just want to exaust every other possibility before doing that, also do garanties an xbox controler would work so might be a waste.

Anyway thanks, and keep up the great work. 
Cheers!

**Comment by Polymega** [comment]
Hi ThunderStormOwl,

That is weird. On both my Windows 7 and 10 machines I can play with my DS4 controller plugged in (it's the only way I can play with a DS4 as I don't have the wireless dongle or Bluetooth in my PCs). Even though you tested it without having DS4Windows running, I wonder if there's something else running in the background causing hiccups?

Unfortunately, I wouldn't know where to start with troubleshooting this, as I haven't experienced it myself. Can you include a copy of your `d3d8.log` file? We can check and see if maybe there's a weird file in the game's directory giving you trouble.

Do you have a friend who can lend you an Xbox 360 or Xbox One controller just to see that would work on your PC?

**Comment by AeroWidescreen** [comment]
I can also confirm that I don't have any trouble with crashing when using my DS4.

Also, if you're DS4Windows by Jays2Kings, then I believe that version is old and deprecated. This fork is what you should use: https://github.com/Ryochan7/DS4Windows

**Comment by AeroWidescreen** [comment]
I can also confirm that I don't have any trouble with crashing when using my DS4.

Also, if you're using DS4Windows by Jays2Kings, then I believe that version is old and deprecated. This fork is what you should use: https://github.com/Ryochan7/DS4Windows

**Comment by ThunderStormOwl** [comment]
Hey guys, thanks for your replies!
I am so sorry it took so long to get to you I kinda forgot about this post, my bad.

AeroWidescreen your solution worked! I was using the deprecated version I belive. I downloaded the version you provided and the game loaded no problem! 

Thanks again, I'll try to mark this issua as resolved!

Cheers!
