### ISSUE TITLE
SH2 ED Keeps closing right after I open it

### ISSUE THREAD

**Issue by NerroEx** [elishacloud/Silent-Hill-2-Enhancements#284]
I run as admin changed Resolution to my monitor, I turned off and on full screen, it says its downloading 4 updates and updates are available but it closes right away. Please help

**Comment by Polymega** [comment]
After trying to launch the game, can you please attach a copy of your `d3d8.log` file here?

**Comment by NerroEx** [comment]
I think this is it 
4656 19:28:41.515 Starting Silent Hill 2 Enhancements! v1.5.1750.0
4656 19:28:41.515 MSI MS-7850 1.0 (Desktop)
4656 19:28:41.515 MSI Z87-G41 PC Mate(MS-7850) 1.0 (Desktop)
4656 19:28:41.515 "NVIDIA GeForce GTX 1070"
4656 19:28:41.516 Windows 10 Home 64-bit (10.0.18362)
4656 19:28:41.516 "sh2pc.exe" (PID:16672)
4656 19:28:41.516 Game binary version: v1.0
4656 19:28:41.533 Running from: "D:\SILENT HILL 2\CD 1 OG\sh2pc.exe"
4656 19:28:41.533 Config file: "D:\SILENT HILL 2\CD 1 OG\d3d8.ini"
4656 19:28:41.533 |----------- SETTINGS -----------
4656 19:28:41.533 |- ResX: 1920
4656 19:28:41.533 |- ResY: 1080
4656 19:28:41.533 |- EnableWndMode: 0
4656 19:28:41.533 |- WndModeBorder: 0
4656 19:28:41.533 |- FullscreenWndMode: 1
4656 19:28:41.533 |- d3d8to9: 1
4656 19:28:41.533 |- AnisotropicFiltering: 1
4656 19:28:41.533 |- FixGPUAntiAliasing: 1
4656 19:28:41.533 |- AutoUpdateModule: 1
4656 19:28:41.533 |- EnableSFXAddrHack: 1
4656 19:28:41.533 |- EnableTexAddrHack: 1
4656 19:28:41.533 |- NoCDPatch: 1
4656 19:28:41.533 |- DisableHighDPIScaling: 1
4656 19:28:41.533 |- UseCustomModFolder: 1
4656 19:28:41.533 |- SingleCoreAffinity: 2
4656 19:28:41.533 |- CheckForAdminAccess: 1
4656 19:28:41.533 |- DisableScreenSaver: 1
4656 19:28:41.533 |- DisableGameUX: 1
4656 19:28:41.533 |- ImproveStorageSupport: 1
4656 19:28:41.533 |- DPadMovementFix: 1
4656 19:28:41.533 |- GamepadControlsFix: 1
4656 19:28:41.533 |- RestoreSearchCamMovement: 1
4656 19:28:41.533 |- RestoreVibration: 1
4656 19:28:41.533 |- Southpaw: 0
4656 19:28:41.533 |- PadNumber: 0
4656 19:28:41.533 |- DisableRedCrossInCutScenes: 1
4656 19:28:41.533 |- DisableRedCross: 0
4656 19:28:41.533 |- IncreaseNoiseEffectRes: 512
4656 19:28:41.533 |- DisableCutsceneBorders: 1
4656 19:28:41.533 |- FMVWidescreenMode: 1
4656 19:28:41.533 |- FMVWidescreenEnhancementPackCompatibility: 2
4656 19:28:41.533 |- ReduceCutsceneFOV: 1
4656 19:28:41.533 |- Fix2D: 1
4656 19:28:41.533 |- FullscreenImages: 1
4656 19:28:41.533 |- LockResolution: 1
4656 19:28:41.533 |- MainMenuFix: 1
4656 19:28:41.533 |- MainMenuTitlePerLang: 1
4656 19:28:41.533 |- UseCustomExeStr: 1
4656 19:28:41.533 |- UnlockJapLang: 0
4656 19:28:41.533 |- LockScreenPosition: 1
4656 19:28:41.533 |- UseBestGraphics: 1
4656 19:28:41.533 |- CatacombsMeatRoomFix: 1
4656 19:28:41.533 |- CemeteryLightingFix: 1
4656 19:28:41.533 |- ClosetCutsceneFix: 1
4656 19:28:41.533 |- CreateLocalFix: 1
4656 19:28:41.533 |- DisableSafeMode: 1
4656 19:28:41.533 |- EnableSoftShadows: 1
4656 19:28:41.533 |- FastTransitions: 1
4656 19:28:41.533 |- FixChainsawSpawn: 1
4656 19:28:41.533 |- FixCreatureVehicleSpawn: 1
4656 19:28:41.533 |- FixDrawingTextLine: 1
4656 19:28:41.533 |- FixHangOnEsc: 1
4656 19:28:41.533 |- FixMissingWallChunks: 1
4656 19:28:41.533 |- FixTownWestGateEvent: 1
4656 19:28:41.533 |- Fog2DFix: 1
4656 19:28:41.533 |- FogParameterFix: 1
4656 19:28:41.533 |- FogSpeedFix: 1
4656 19:28:41.533 |- GameLoadFix: 1
4656 19:28:41.533 |- HalogenLightFix: 1
4656 19:28:41.533 |- HospitalChaseFix: 1
4656 19:28:41.533 |- HotelWaterFix: 1
4656 19:28:41.533 |- IncreaseBlood: 1
4656 19:28:41.533 |- IncreaseDrawDistance: 1
4656 19:28:41.533 |- LightingFix: 1
4656 19:28:41.533 |- LightingTransitionFix: 1
4656 19:28:41.533 |- PauseScreenFix: 1
4656 19:28:41.533 |- PistonRoomFix: 1
4656 19:28:41.533 |- PS2CameraSpeed: 1
4656 19:28:41.533 |- PS2FlashlightBrightness: 1
4656 19:28:41.533 |- PS2StyleNoiseFilter: 1
4656 19:28:41.533 |- RemoveEnvironmentFlicker: 1
4656 19:28:41.533 |- RemoveEffectsFlicker: 1
4656 19:28:41.533 |- RestoreSpecialFX: 1
4656 19:28:41.533 |- Room312ShadowFix: 1
4656 19:28:41.533 |- RowboatAnimationFix: 1
4656 19:28:41.533 |- SetBlackPillarBoxes: 1
4656 19:28:41.533 |- SteamCrashFix: 1
4656 19:28:41.533 |- WhiteShaderFix: 1
4656 19:28:41.533 |- WoodsideRoom205Fix: 1
4656 19:28:41.533 |- WidescreenFix: 1
4656 19:28:41.533 |- fog_custom_on: 1
4656 19:28:41.533 |- fog_transparency_layer1: 128
4656 19:28:41.533 |- fog_transparency_layer2: 90
4656 19:28:41.533 |- fog_layer1_x1: 0.250
4656 19:28:41.533 |- fog_layer1_x2: 0.250
4656 19:28:41.533 |- fog_layer1_y1: 0.125
4656 19:28:41.533 |- fog_layer1_y2: 0.125
4656 19:28:41.534 |- fog_layer2_density_mult: 1.4
4656 19:28:41.534 |- fog_layer2_density_add: 100.0
4656 19:28:41.534 |- fog_layer2_complexity: 0.08
4656 19:28:41.534 |- UseCustomFonts: 1
4656 19:28:41.534 |- DisableEnlargedText: 1
4656 19:28:41.534 |- CustomFontCol: 100
4656 19:28:41.534 |- CustomFontRow: 14
4656 19:28:41.534 |- CustomFontCharWidth: 20
4656 19:28:41.534 |- CustomFontCharHeight: 32
4656 19:28:41.534 |- NormalFontWidth: 20
4656 19:28:41.534 |- NormalFontHeight: 30
4656 19:28:41.534 |- SmallFontWidth: 16
4656 19:28:41.534 |- SmallFontHeight: 24
4656 19:28:41.534 |- LetterSpacing: 2
4656 19:28:41.534 |- SpaceSize: 7
4656 19:28:41.534 |- LoadPlugins: 0
4656 19:28:41.534 |- LoadFromScriptsOnly: 0
4656 19:28:41.534 |- LoadD3d8FromScriptsFolder: 0
4656 19:28:41.534 |--------------------------------
4656 19:28:41.534 |- 
4656 19:28:41.534 |-  Directory of "D:\SILENT HILL 2\CD 1 OG"
4656 19:28:41.534 |- 
4656 19:28:41.534 |- 02/28/2003  09:43 AM    <DIR>          Crack
4656 19:28:41.534 |- 05/26/2020  06:48 PM    <DIR>          data
4656 19:28:41.534 |- 02/28/2003  09:43 AM    <DIR>          dxsetup
4656 19:28:41.535 |- 02/28/2003  10:10 AM    <DIR>          movie
4656 19:28:41.535 |- 02/28/2003  10:08 AM    <DIR>          res
4656 19:28:41.535 |- 05/26/2020  07:03 PM    <DIR>          reshade-shaders
4656 19:28:41.535 |- 05/26/2020  07:02 PM    <DIR>          sh2e
4656 19:28:41.535 |- 11/20/2002  02:36 PM           450,560 Autorun.exe
4656 19:28:41.535 |- 11/20/2002  02:36 PM                43 autorun.inf
4656 19:28:41.535 |- 06/25/2002  09:50 AM           358,963 binkw32.dll
4656 19:28:41.535 |- 05/26/2020  07:03 PM                24 cin.dat
4656 19:28:41.535 |- 01/31/2020  11:39 PM             2,081 d3d8.dat
4656 19:28:41.535 |- 05/02/2020  03:50 PM         1,822,720 d3d8.dll
4656 19:28:41.535 |- 05/26/2020  07:25 PM            14,398 d3d8.ini
4656 19:28:41.535 |- 05/26/2020  07:28 PM                   d3d8.log
4656 19:28:41.535 |- 02/02/2020  03:52 AM         2,603,864 d3d9.dll
4656 19:28:41.535 |- 05/26/2020  07:28 PM             4,906 d3d9.log
4656 19:28:41.535 |- 11/20/2002  02:19 PM         3,161,241 data1.cab
4656 19:28:41.535 |- 11/20/2002  02:35 PM           371,734 data1.hdr
4656 19:28:41.535 |- 11/20/2002  02:21 PM        13,336,576 data2.cab
4656 19:28:41.535 |- 09/26/2002  06:19 PM            12,332 device.fix
4656 19:28:41.535 |- 11/18/2019  10:34 PM           633,344 dsound.dll
4656 19:28:41.535 |- 11/18/2019  10:35 PM            22,187 dsound.ini
4656 19:28:41.535 |- 05/26/2020  07:28 PM             1,770 dsound.log
4656 19:28:41.535 |- 10/31/2002  07:35 PM           344,923 ikernel.ex_
4656 19:28:41.535 |- 07/25/2002  11:02 AM                77 Konami Homepage.url
4656 19:28:41.535 |- 11/20/2002  02:35 PM               531 layout.bin
4656 19:28:41.535 |- 11/20/2002  02:36 PM            37,970 Leggimi.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            16,906 Leggimi.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            38,261 LiesMich.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,192 LiesMich.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,154 Lisez-Moi.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,949 Lisez-Moi.txt
4656 19:28:41.535 |- 08/25/2019  08:02 PM                37 local.fix
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,056 Léeme.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            18,056 Léeme.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM           487,424 msvcp70.dll
4656 19:28:41.535 |- 11/20/2002  02:36 PM           339,968 msvcr70.dll
4656 19:28:41.535 |- 11/20/2002  02:36 PM            37,303 ReadmeDC.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            15,710 ReadmeDC.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            38,253 readme_de.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,192 readme_de.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            37,295 readme_en.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            15,702 readme_en.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,048 readme_es.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            18,056 readme_es.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,146 readme_fr.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,949 readme_fr.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            37,962 readme_it.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            16,906 readme_it.txt
4656 19:28:41.535 |- 02/02/2020  03:55 AM             1,308 ReShade.ini
4656 19:28:41.535 |- 10/21/2019  07:18 PM               578 ReShade_sh2pc.ini
4656 19:28:41.535 |- 02/28/2003  05:21 PM       785,370,432 rzr-sh21.bin
4656 19:28:41.535 |- 02/02/2020  02:07 AM               309 settings.ini
4656 19:28:41.535 |- 08/09/2002  05:46 PM           450,056 Setup.bmp
4656 19:28:41.535 |- 11/03/1999  06:34 PM           127,488 Setup.exe
4656 19:28:41.535 |- 11/20/2002  02:18 PM               218 Setup.ini
4656 19:28:41.535 |- 11/20/2002  02:18 PM           130,651 setup.inx
4656 19:28:41.535 |- 11/20/2002  02:36 PM             2,238 sh2.ico
4656 19:28:41.535 |- 11/20/2002  02:36 PM            28,111 SH2DClogo.JPG
4656 19:28:41.535 |- 11/30/2017  06:22 PM         5,459,968 sh2pc.exe
4656 19:28:41.535 |- 11/20/2002  09:17 AM         6,180,307 sh2pcBACKUP.exe
4656 19:28:41.535 |--------------------------------
4656 19:28:41.535 Loading as dll: "d3d8.dll"
4656 19:28:41.537 Wrapper created for "d3d8.dll"
4656 19:28:41.663 Hooking the FileSystem APIs...
4656 19:28:41.663 Hooking the CreateProcess APIs...
4656 19:28:41.664 CD patch already set!
4656 19:28:41.664 Patching binary...
4656 19:28:41.664 Finding SFX file locations...
4656 19:28:41.749 Updating SFX memory address locations...
4656 19:28:41.749 Allocating memory buffer for sddata.bin file...
4656 19:28:41.762 Updating Texture memory address locations...
4656 19:28:41.763 Disabling High DPI Scaling...
4656 19:28:41.764 Disabling Screensaver...
4656 19:28:41.764 Setting 2TB hard disk Fix...
4656 19:28:41.764 Setting PS2 Style Noise Filter...
4656 19:28:41.764 Increasing the Draw Distance...
4656 19:28:41.765 Setting Cemetery Lighting Fix...
4656 19:28:41.765 Fixing tree lighting conditions...
4656 19:28:41.765 Setting Rowboat Animation Fix...
4656 19:28:41.765 Updating the Catacomb Meat Cold Rooms color...
4656 19:28:41.765 Updating Fog Parameters...
4656 19:28:41.765 Setting Piston Position Fix...
4656 19:28:41.765 Setting Hotel Room 312 Shadow Flicker Fix...
4656 19:28:41.765 Hiding Red Cross health indicator during cutscenes...
4656 19:28:41.765 Enabling PS2 Flashlight Fix...
4656 19:28:41.765 Fixing behavior of Lying Figures that are hiding under vehicles...
4656 19:28:41.765 Add fix to prevent chainsaw from spawning on first playthrough...
4656 19:28:41.765 Enabling XInput Vibration Fix...
4656 19:28:41.799 Enabling Custom Fonts...
4656 19:28:41.800 Enabling Custom Exe Strings...
4656 19:28:41.800 Enabling Main Menu title selection by language...
4656 19:28:41.800 Enabling post Processing Special FX...
4656 19:28:41.800 Enabling Town West Gate Event Fix...
4656 19:28:41.800 Enabling Screen Position option lock...
4656 19:28:41.800 Enabling Best Graphics settings...
4656 19:28:41.800 Enabling Fog Fix...
4656 19:28:41.800 Loading the "WidescreenFixesPack" module...
4656 19:28:41.893 Loading the "modupdater" module...
4656 19:28:41.931 Silent Hill 2 Enhancements module loaded!
4656 19:28:42.024 CheckForAdminAccess Checking if administrator access is required.
4656 19:28:42.080 Starting D3d8to9 v1.11.0.0
4656 19:28:42.080 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
4656 19:28:42.612 Enabling Resolution Lock...
4656 19:28:42.612 Setting Hotel Room 312 Resolution Fix...

**Comment by Polymega** [comment]
Thanks. Can you upload the actual file (drag and drop the `d3d8.log` into the text window where you reply). I see a lot of foreign files in your game's directory. Chances are, one of these is causing the issue. [You want your directory to look like this.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

**Comment by NerroEx** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4685635/d3d8.log)
 i might have installed the CD1 and the installation file in the same folder

**Comment by NerroEx** [comment]
im oging to do a clean install, but it keeps saying catastrophic failure now

**Comment by Polymega** [comment]
Thanks. It's easier to read the contents of the log file through the actual file.

> i might have installed the CD1 and the installation file in the same folder

To confirm: Did you use all three (3) CDs to install the game? That might be why the game won't launch if you only ran the first CD. 

I'm not sure how you're installing the game, but if you're not doing it through the actual, physical discs, you'll want to virtually mount the Disc 1 image and run `setup.exe` to begin installation. As the game begins to install, it will eventually ask you to insert Disc 2. You would then unmount Disc 1 and virtually mount Disc 2, then click "Continue" on the installation box for the game. You'll repeat this for Disc 3, then back to Disc 1 (near the end of installation).

If you've went through all three discs to install the game, then chances are there are foreign files in your game's directory causing the issues. I can't guarantee all files/folders are in there right spots, but I can instruct that the following files/folders should **not** be in the game's main directory:

```
4656 19:28:41.534 |- 02/28/2003  09:43 AM    <DIR>          Crack
4656 19:28:41.534 |- 02/28/2003  09:43 AM    <DIR>          dxsetup
4656 19:28:41.535 |- 02/28/2003  10:10 AM    <DIR>          movie
4656 19:28:41.535 |- 02/28/2003  10:08 AM    <DIR>          res
4656 19:28:41.535 |- 11/20/2002  02:36 PM           450,560 Autorun.exe
4656 19:28:41.535 |- 11/20/2002  02:36 PM                43 autorun.inf
4656 19:28:41.535 |- 11/20/2002  02:19 PM         3,161,241 data1.cab
4656 19:28:41.535 |- 11/20/2002  02:35 PM           371,734 data1.hdr
4656 19:28:41.535 |- 11/20/2002  02:21 PM        13,336,576 data2.cab
4656 19:28:41.535 |- 10/31/2002  07:35 PM           344,923 ikernel.ex_
4656 19:28:41.535 |- 11/20/2002  02:35 PM               531 layout.bin
4656 19:28:41.535 |- 11/20/2002  02:36 PM            37,970 Leggimi.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            16,906 Leggimi.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            38,261 LiesMich.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,192 LiesMich.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,154 Lisez-Moi.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            17,949 Lisez-Moi.txt
4656 19:28:41.535 |- 11/20/2002  02:36 PM            39,056 Léeme.htm
4656 19:28:41.535 |- 11/20/2002  02:36 PM            18,056 Léeme.txt
4656 19:28:41.535 |- 02/28/2003  05:21 PM       785,370,432 rzr-sh21.bin
4656 19:28:41.535 |- 08/09/2002  05:46 PM           450,056 Setup.bmp
4656 19:28:41.535 |- 11/03/1999  06:34 PM           127,488 Setup.exe
4656 19:28:41.535 |- 11/20/2002  02:18 PM               218 Setup.ini
4656 19:28:41.535 |- 11/20/2002  02:18 PM           130,651 setup.inx
```

**Comment by NerroEx** [comment]
ah, its a, um.. Copy i downloaded from the internet. I do not have the original discs

**Comment by Polymega** [comment]
No judgments. But unfortunately there's no way to guarantee the files weren't modified/tampered with in the download, depending on where it was obtained. You can try a fresh install as you mentioned. But do take notes on my comments above, about how all three discs need to be used for the installation.

**Comment by NerroEx** [comment]
Yes I definitely used 3 discs. I had them on my laptop and i transferred them to my PC, Last time i played it on my laptop it was fine so I am so confused here why it isnt working.

**Comment by Polymega** [comment]
It might be those foreign files. Try deleting the files/folders I listed first to see if that will allow the game to launch.

**Comment by NerroEx** [comment]
ok i restarted my computer and... for some reason now it works. But its in widescreen. Im going to mess with some options

**Comment by NerroEx** [comment]
the only thing I did different was open something called autorun which had an option to download Directx8.1, which my PC wasnt letting me because it said i already had a new version of DX (prob DX11/12) also It didnt let me install Visual studio 2010 because I currently use visual studio 2020 for coding.

**Comment by NerroEx** [comment]
you were right. It was a bad copy. Got another copy and its working now 😏

**Comment by Polymega** [comment]
Good to hear! I'll close this ticket out.
