### ISSUE TITLE
DirectInput vibration is not working

### ISSUE THREAD

**Issue by k1mk4t** [elishacloud/Silent-Hill-2-Enhancements#288]
i'm not sure if this is because of my controller or something else entirely? i'm using a dualshock 2 for SH2:EE, using [this ps2 to pc usb adapter](https://www.amazon.com/DUAL-CONTROLLER-ADAPTER-CONVERTER-80001/dp/B000SPA46M/ref=pd_lpo_147_t_2/140-0595247-7991402?_encoding=UTF8&pd_rd_i=B000SPA46M&pd_rd_r=08db59ba-7116-4ca5-91d7-ab0f09e17bae&pd_rd_w=ZOYDw&pd_rd_wg=ndJgL&pf_rd_p=7b36d496-f366-4631-94d3-61b87b52511b&pf_rd_r=M4RNS1A7RYJ95FYWR33V&psc=1&refRID=M4RNS1A7RYJ95FYWR33V). when plugged in using the adapter, my DS2 is recognised like as if it was just a normal directinput pc gamepad in my pc. i honestly expected rumble to not work since i know that these pc adapters and their drivers won't guarantee 100% functionality. then i found out that vibration works perfectly fine when i played on the Silent Hill 3 PC port with my DS2, so im curious to why it isn't working on SH2:EE? here is my d3d8 log file to see what's the matter
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4742220/d3d8.log)
one thing that caught my eyes is that the search camera didn't work correctly for me until i set the value of RestoreSearchCamMovement to 3, thats all i got. if you have any questions for anything and incase my report wasn't clear, please do address them and i am sorry if my report wasn't clear

**Comment by Polymega** [comment]
I can't speak for DS2, but DS4 doesn't rumble for a lot of games as a DirectInput device, even though it should. If you Google search "dualshock 4 pc rumble" you'll see all sorts of PC games have trouble with it, such as Tomb Raider, Rocket League, For Honor, and more.

Steam fixed this issue for their own Steam Big Picture Mode, but we have no idea how they did it. A big part of the problem is Sony has no public documentations on how their DS4 works in Windows, so we don't know how to troubleshoot the vibration issue for DS4.

Perhaps the issue with DS4 not accepting DirectInput Force Feedback calls relates to DS2, as well. We're not sure.

**Comment by k1mk4t** [comment]
dang that sucks to hear, but i guess ur right. in fact, steam recognises my DS2 as DS3 instead so maybe the certain fixes for DS3 and DS4 might work for my DS2........hopefully. otherwise i'll just have to play SH2 without vibration, besides ive already managed to make it far into brookhaven hospital without it anyways

**Comment by AeroWidescreen** [comment]
> Steam fixed this issue for their own Steam Big Picture Mode, but we have no idea how they did it. 

I believe Steam emulates an Xbox 360 controller, not much different than DS4Windows. It won't do anything for old games that don't support XInput, like Silent Hill 2. The improvements we (Silent) made were likely intended for XInput, so that's why Xbox 360 / One devices have no trouble with rumble support.

**Comment by Polymega** [comment]
IIRC, Silent's fix sends _both_ Force Feedback (DirectInput) and vibration (XInput) calls when the game requests rumble. So either controller type should accept it and rumble. Elisha then when back and added code to change rumble intensity for both APIs.

For whatever reason, I don't think the software inside a DS4 (and maybe DS2/3 by association) was programmed in a way to accept either of these calls when used on Windows? 

In any case, @k1mk4t, I use an 8bitdo SN30 Pro+ controller and it's done me well. Works on PC, Android, Mac, Steam, and Switch and can change between XInput and DirectInput. Can be used wireless or wired and is shaped similarly to DualShock controllers.

- https://www.8bitdo.com/sn30-pro-plus/
- https://twitter.com/theRatiocinator/status/1190059292356939779?s=09

**Comment by Polymega** [comment]
Forgot I asked Ryochan7 about this roughly a year ago: https://github.com/Ryochan7/DS4Windows/issues/698

And that http://html5gamepad.com indeed makes a DS4 rumble.

**Comment by Polymega** [comment]
> Windows lacks DirectInput support for DS4 gamepads. In general there's no standard way to do haptics for HID gamepads, and the DS4 isn't even really a standard HID gamepad.
> 
> To get this working in Chrome I had to send the vibration commands as raw HID packets:
> 
> https://cs.chromium.org/chromium/src/device/gamepad/dualshock4_controller_base.cc?l=45
> 
> https://cs.chromium.org/chromium/src/device/gamepad/dualshock4_controller_win.cc?l=38
> 
> You can also use third-party drivers like DS4Windows to make your DS4 behave like an XInput device.

https://gamedev.stackexchange.com/a/162399

----------------------

Not sharing this to suggest we integrate it into our own project or anything (the less moving parts, the better), but this Git project "reads DualShock 4, JoyCon, and Pro Controller input on PC," so maybe something could be gathered from how it detects rumble data for the DS4:

https://github.com/JibbSmart/JoyShockLibrary

**Comment by AeroWidescreen** [comment]
>Silent's fix sends both Force Feedback (DirectInput) and vibration (XInput) calls when the game requests rumble. So either controller type should accept it and rumble. Elisha then when back and added code to change rumble intensity for both APIs.

I see, thanks for the clarification. I used to have a DirectInput PC gamepad and I remember rumble would work for the old games I played. But nowadays the only non-Xbox gamepad I use is a DS3/DS4, which never had rumble. Now that I think about it, it all makes sense now.

**Comment by k1mk4t** [comment]
i tried following the steps of #168 and #222 to see if rumble works but unfortunately steam couldn't launch the game??? i have no clue why its happening, but from what i can search i am not the first person to encounter this issue and i cannot find any solutions for it. i guess we all can just conclude that dualshock controllers are kinda wonky for pc usage in general huh? i'll keep in mind to save up for a new controller someday. hopefully you guys can solve this issue for SH2:EE

> In any case, @k1mk4t, I use an 8bitdo SN30 Pro+ controller and it's done me well. Works on PC, Android, Mac, Steam, and Switch and can change between XInput and DirectInput. Can be used wireless or wired and is shaped similarly to DualShock controllers.
> 
> * https://www.8bitdo.com/sn30-pro-plus/
> * https://twitter.com/theRatiocinator/status/1190059292356939779?s=09

thank you for the suggestion!! i'll keep my eyes on this controller!

**Comment by mirh** [comment]
https://github.com/x360ce/x360ce/issues/399
https://stackoverflow.com/questions/54532968/is-there-any-way-to-make-my-ps4-control-vibrate-rumble-with-java
I suspect something like that could also apply to DS3. 

Of course one option is always using a better driver than the lousy ones that windows or sony give you.
