### ISSUE TITLE
Playing SH2 on Linux via WINE

### ISSUE THREAD

**Issue by jcplemons** [elishacloud/Silent-Hill-2-Enhancements#289]
I recently installed SH2 via the installation guide at http://www.enhanced.townofsilenthill.com/SH2/install.htm and played via WINE on Linux.  I was wondering why I couldn’t see much evidence of the improvements in the Enhanced Edition and then finally figured out that, even though I had followed all of the steps in the installation guide, the “enhanced” exe was still launching the original/non-enhanced version of SH2.

I’m not sure if the game truly doesn’t work in WINE currently or if I have just not completely performed any necessary additional steps ([issue 134](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/134) mentions installing d3dcompiler_43 and d3dx9_43 via winetricks, copying files from the sh2e folder into the data folder, others?).  As a starting point I suppose, is there a tested/formalized list of any additional steps which should be performed to play on Linux via WINE?

Happy to provide any additional information/log files/etc. (although d3d8.log doesn’t currently exist – presumably because I am not yet actually launching the Enhanced Edition to begin with).

**Comment by elishacloud** [comment]
> the “enhanced” exe was still launching the original/non-enhanced version of SH2.

> although d3d8.log doesn’t currently exist – presumably because I am not yet actually launching the Enhanced Edition to begin with

This is most likely related to the [load order](https://unix.stackexchange.com/questions/367600/what-is-the-order-that-linuxs-dynamic-linker-searches-paths-in) in Linux.  You will need to configure Linux to load the local instance of `d3d8.dll` rather than the system version.

**Comment by jcplemons** [comment]
Sweet!  Overriding WINE’s built-in d3d8 was the piece I was missing.

For future reference, here’s what I had to do to get Silent Hill 2 Enhanced Edition running on Linux (Mint) via a clean 64-bit prefix in the current development WINE 5.11 (did not test a 32-bit prefix) after completing all steps in the Installation Guide:

- Initially, sh2pc.exe starts the original version of SH2 rather than the “Enhanced Edition”.
- Via winecfg, override d3d8 to “(native, builtin)”.  This causes sh2pc.exe to start the “Enhanced Edition”.  However, the main menu “fades in” extremely slowly (from its first appearance, it took about 10 seconds for me), scrolling through the main menu options or moving the mouse pointer is also extremely slow and choppy, and I couldn’t even get through the main menu options to start the game without the game either freezing or moving so slowly it appeared to be frozen.
- Via winetricks, install “dxvk” (“d9vk” appeared to work as well – not sure of the differences between the two).  This solved the lag issues and allowed me to play the game successfully.

All gameplay, cutscenes, audio, etc. seem to work fine so far – only remaining issue I see is that ReShade returns several “Failed to compile” errors on start (see [d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4842743/d3d9.log)).  Is there anything additional I can do/try here?

**Comment by Polymega** [comment]
> only remaining issue I see is that ReShade returns several “Failed to compile” errors on start (see d3d9.log). Is there anything additional I can do/try here?

We're planning to drop ReShade for the next update, as we want to integrate our own shaders into the project. For now, I'd recommend just removing the ReShade files from the game's directory until the next update comes out.

**Comment by jcplemons** [comment]
Will do.  Thanks again!
