### ISSUE TITLE
Unable to load the game

### ISSUE THREAD

**Issue by OregonPacifist** [elishacloud/Silent-Hill-2-Enhancements#29]
I have followed the Enhanced Edition directions to a T, and this is what happens when I attempt to start the game:

I get a blank, black screen with small text at the top that reads:

ReShade 3.4.1
Visit https://reshade.me for news, updates, shaders and discussion.
Loading (4 effects remaining) … This might take a while. The application could become unresponsive for some time.

The problem is that I've left it on this screen for over an hour and nothing changes. The computer has a Radeon GPU and I've made sure to not install the Wine3D files during installation. There are no anti-virus software installed. Any thoughts? Thanks in advance.

**Comment by Polymega** [comment]
Hi @OregonPacifist , 
Temporarily set `d3d8to9 = 0` in the `d3d8.ini` file. Does the game boot up then?

**Comment by OregonPacifist** [comment]
Thanks for the suggestion. When I did that, the game launches, it's just a blank, black screen and the program isn't responding (basically the exact same issue as before but without the text on top).

**Comment by Polymega** [comment]
Okay, can you please ZIP archive your `d3d8.log` and `d3d8.ini` files and attach them to this GitHub thread?

**Comment by OregonPacifist** [comment]
Thanks again for the help. For what it's worth, I was unable to play the game from the start (using the original, unmodified files). After installing all of the enhancements, nothing changed in that regard.

My PC specs:

Windows 10
Intel i7-7700K 4.2 GHz
16 GB DDR 4 RAM
Radeon Pro 575 w/ 4 GB VRAM

[Logs.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2341277/Logs.zip)

**Comment by OregonPacifist** [comment]
I copied the entire Silent Hill 2 directory over to the C:\Program Files (x86) folder, then right-clicked the sh2pc.exe file and chose "Run as Administrator". This caused the game to crash almost immediately, then I was prompted to re-open it after Windows did a quick compatibility test. When it was re-opened, it behaved the same as it did before. The program is unresponsive, the same text appears at the top and the screen is totally black.

The only other thing I can think of trying is to start the whole Enhanced Edition steps all over again from scratch, and attempt to open the game after each step to see where the problem lies (unless you have any other suggestions).

**Comment by OregonPacifist** [comment]
OK, so the plot thickens...

I have an original, unmodified KONAMI/Silent Hill 2 folder on an external hard drive. When I launch the game straight from the USB drive, it works perfectly.

If I copy that exact folder to C:\ (so that the path is C:\KONAMI\Silent Hill 2\), the game stops responding at launch and will not close unless I end the task in Task Manager.

I tried copying the game to a whole different directory on the C:\ but the result is the same. For some reason, the game will only launch when it's done directly from the USB drive. This is super weird (I've never actually played through SH2 on this newer computer).

The internal hard drive is a SSD but I'm not sure that would cause this problem to occur. Very odd though. Worst case scenario is I can try to just play the Enhanced Edition game via the USB drive.

**Comment by Polymega** [comment]
I'm not the best qualified to answer this but I don't know if just copying the files from one directory to another would work? Because when the game installs it creates a registry key in Windows and where you installed it may be tied only to that location. So a full uninstall and reinstall may be in order.

**Comment by Polymega** [comment]
Yes, per the [troubleshooting portion](http://enhanced.townofsilenthill.com/SH2/#troubleshooting) of the guide this is a unique issue for AMD GPUs when playing the game in fullscreen mode. To fix this:

Set `EnableWndMode = 1`, `WndModeBorder = 0`, `ResX = 0`, and `ResY = 0 `in the `d3d8.ini` file.

**Comment by OregonPacifist** [comment]
Thanks for the tip. For some reason, I must have missed that in the Troubleshooting Guide. Now the game works beautifully. This is great!

**Comment by Polymega** [comment]
No worries! Glad you got it working. If you ever figure out why it wouldn't install to your `C:\` please do let us know. The more we know about these types of things the more easily/quickly we can help others with similar problems.

Regards

**Comment by elishacloud** [comment]
Issue resolved.  Closing.
