### ISSUE TITLE
Question about possible corrections!

### ISSUE THREAD

**Issue by SONIC0798** [elishacloud/Silent-Hill-2-Enhancements#290]
### Hello!
 I wanted to thank your whole team for your work.
 You made a masterpiece from a rather crooked desk, but as I understand it, there is still something left to fix.
 I want to show what errors or shortcomings I noticed.
 I hope in the future you can fix them.

In most cutscenes, the movie freezes for a millisecond at the time of sound playback.  this problem was also on xbox, but on ps2, as always, everything is fine.
![Image4](https://user-images.githubusercontent.com/67099262/85014761-8b03f500-b16f-11ea-850e-1b2753a9eb96.jpg)

There is no shine in James's eyes, his eyes seem lifeless, unlike the ps2 version.

James has a lower jaw in the end "in the water"
![Без имени-1](https://user-images.githubusercontent.com/67099262/85017553-5181b880-b174-11ea-8d47-fe2c989f43b7.png)

Maybe it’s just not overlooked, but Angela has an unpainted texture behind her ear.
![45](https://user-images.githubusercontent.com/67099262/85018685-4891e680-b176-11ea-8477-ab485fde1cf3.png)

Thank you again for your good work.

**Comment by Polymega** [comment]
Hi Sonic 0789,

> In most cutscenes, the movie freezes for a millisecond at the time of sound playback. this problem was also on xbox

Yes, as you mentioned, this is something carried over from the Xbox version. We're aware of this and it is something we would like to look into sometime in the future.

> There is no shine in James's eyes, his eyes seem lifeless, unlike the ps2 version.

We plan to restore specularity across the game. We've done early tests with its restoration. Here is a test shot:

![image](https://user-images.githubusercontent.com/27395260/52151635-ce74c680-2641-11e9-93a3-adb2d36d653c.png)

> James has a lower jaw in the end "in the water"

Indeed. [It's quite scary.](https://www.youtube.com/watch?v=8cxeUV1ianQ)

It's like this on all versions of the game. We haven't fully reverse engineered the cutscene .anm files, so we can't fix this at this time. Also, Maria's left shoulder is dislocated as she walks back to her prison bed in the labyrinth (after all the cutscenes here). This also happens on all versions of the game. Again, I'm not sure if we can ever address this.

> Maybe it’s just not overlooked, but Angela has an unpainted texture behind her ear.

This is Angela's hair clip. It's gray in color with a red oval inside it.

**Comment by SONIC0798** [comment]
It looks funny, like you get the saddest ending, but when I look at James's face, I have a smile on my face.

 And thanks for explaining what Angela had behind her ear, otherwise I thought it was a bug.

 By the way, regarding the eyes of James, in the PS2 version his eyes are rather light, but for some reason it is darker on the PC, I climbed the textures and added brightness to my eyes so that they were more similar to the PS2 version, it turned out to be normal.
![2519](https://user-images.githubusercontent.com/67099262/85069000-ff648580-b1bb-11ea-94b3-59326b397d79.png)

**Comment by Polymega** [comment]
PS2 version uses beta build of his eyes which are wrong and look off/creepy. Team Silent fixed this when they ported it to Xbox (which the PC version is based off of).

You can see his creepy bright eyes in this prototype build here, as well: https://youtu.be/LtGjRe-LEfg

**Comment by SONIC0798** [comment]
I understand, then I’d better bring it back
 thank

**Comment by Polymega** [comment]
I'm going to close this ticket. I think we've address most of your notes and/or fixed things from them. We still plan to look into the issue of the game momentarily "freezing" during a cutscene right before the cutscene's dialogue audio starts. Thanks!
