### ISSUE TITLE
What issues still need to be fixed?

### ISSUE THREAD

**Issue by snigelpasta** [elishacloud/Silent-Hill-2-Enhancements#292]
I know the lying figure vomit effects are not on par with the PS2 version. That's the only issue I can think of as of writing this. I'm sure there's more.

Would someone more in the loop than me mind writing a comprehensive check list?

Maybe one of the people involved already has something like this on their computer.

**Comment by Polymega** [comment]
![image](https://user-images.githubusercontent.com/27395260/85216889-32438080-b358-11ea-9b66-eed58c6eaa79.png)

(This list isn't concrete; some things might be dropped.)

> I know the lying figure vomit effects are not on par with the PS2 version.

I looked into this when researching 60 fps issues (their spray reaches out twice as far (too far) when playing in 60 fps). The spray effect for the PC version is the same as the Xbox version. I believe Team Silent changed its appearance for a more natural look for the Xbox build. 

It's good to note Team Silent changed and/or improved on things where they were able when they ported the game to Xbox. Not _everything_ different in the Xbox/PC version is necessarily "downgraded" from the PS2 version.

Examples include Team Silent trying to hide the piston behind the open door in the Angela flesh room, fixing James' eyes from creepily "glowing," per-pixel flashlight effects, and using a better-looking font for the game.
