### ISSUE TITLE
Easy installation

### ISSUE THREAD

**Issue by HollyDJones** [elishacloud/Silent-Hill-2-Enhancements#293]
Hello! 

¿Its possible a single executable for all installation steps in the future?

**Comment by Polymega** [comment]
It's something we'd like to do, but we're not sure if/when that'll happen.

**Comment by aggserp4** [comment]
Hey there, I wrote a quick little PowerShell script that, when executed, installs all of the mod's components, downloading them if necessary.

Unfortunately I don't have an actual installation of the game to test this on right now, but based on some tests I ran it should work.

It has plenty of limitations such as the fact that it becomes outdated should any of the components be updated (it should still work if the updated components have been downloaded manually and placed on the script's directory). It will stop working if the directory structures of any of the components change, and it requires admin permissions if the game is installed in the default directory.

You can download it [here](https://github.com/aggserp4/SH2EEInstallScript/releases/download/v1/SH2EEInstallScript.ps1). Just put it in a folder along with any components you might have downloaded and run. If it does work, make sure to get rid of any leftover .zip files.

**Comment by Polymega** [comment]
Thanks aggserp4!

The use of a batch or PowerShell script is a great idea. This is also something we'd like to look into more as a possible "one-click" solution for installation. Give us time to look into this more as a long-term/permanent usage, as we all want to get our bearings in a row before releasing such an installation method.

In the meantime, @HollyDJones, you can try out aggserp4's PowerShell script for installation using the current package releases.

**Comment by Polymega** [comment]
Hi there,
For our next project update we will be launching an installer for the project. I will close this ticket out. Please look forward to the installer in the future! You can know when we release the next project update by following us on Twitter. https://twitter.com/whereallbegins
