### ISSUE TITLE
Inconsistent melee attacks

### ISSUE THREAD

**Issue by HazNut** [elishacloud/Silent-Hill-2-Enhancements#294]
I've noticed that when trying to switch between light and heavy melee attacks (at least with the wooden plank), it is inconsistent. I know you are supposed to hold down the attack button for a light swing, and tap for a heavy swing. However, it seems you have to 'buffer' holding the attack button to get a light swing. 

For example, if you enter the attack stance and afterwards hold the attack button to get light swings, you just get a heavy swing, then you start doing light swings afterwards. But if you hold down the attack button just before entering the attack stance, you will get light swings. It's probably because there isn't enough time to hold the attack button to get a light swing before the heavy swing animation starts.

Don't know if I explained this very well, but can be kinda annoying if you want to do the light swings while moving forwards and it comes out with a heavy attack instead.

**Comment by Polymega** [comment]
I know it's not a solution to anything, but the best thing is to work within the confines of what the game has to offer for this. PS2 and Xbox had pressure sensitive buttons, but PC doesn't, so this affects melee attack patterns.

At least the PC version programmed quick tap/long hold button presses to try and differentiate attack patterns, so it's better than nothing. (PCSX2 version can only do heavy melee attacks.)
