### ISSUE TITLE
Fullscreen green filter after NVIDIA 451 driver update

### ISSUE THREAD

**Issue by AmSolidSnek** [elishacloud/Silent-Hill-2-Enhancements#295]
Hello all. I've been using SH2EE for about a month and a half now and have never had any issues with it until now. I have just updated windows 10 to ver.2004, as well as installing NVIDIA game ready driver 451 dated 6/21/2020, for an RTX 2060 SUPER running at 3840X2160. As a force of habit, I always test my games after major updates like this to make sure that everything still works properly. I booted SH2EE to find that after a brief moment while loading the logos, the entire fullscreen window is covered in a bright green filter that will not go away. At first I thought it was an issue with reshade, but uninstalling that didn't help at all. I tried getting a screen capture of the effect through my PC but the internal screen capture shows up clear as if nothing is wrong, with no green filter. I can only capture it by taking a picture of the physical screen. This issue doesn't exhibit in any other game on my computer, including other Silent Hill titles. I have attached my d3d8.log as well as a photo taken of my monitor by my phone to demonstrate the problem. If anyone else is experiencing this problem, any insight would be much appreciated. Thank you in advance.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4832381/d3d8.log)
![silenthill2greenscreen](https://user-images.githubusercontent.com/67429569/85751879-ecc8df80-b6d8-11ea-9b65-0f37991784e4.jpg)

**Comment by Polymega** [comment]
Hi AmSolidSnek,

If you play in windowed mode (`EnableWndMode = 1`) does the green filter still persist? 

If so, try setting `d3d8to9 = 0` to see if that removes the green filter. A long time ago d3d8to9 would tint FMVs red for integrated graphics cards, maybe something similar is going on here.

**Comment by Badore90** [comment]
It seems a problem related to some color encoding incompatilibity. It happens i.e. outputting a Y-Pb-Pr signal through a RGB cable.

It happens with every resolution?

**Comment by AmSolidSnek** [comment]
> Hi AmSolidSnek,
> 
> If you play in windowed mode (`EnableWndMode = 1`) does the green filter still persist?
> 
> If so, try setting `d3d8to9 = 0` to see if that removes the green filter. A long time ago d3d8to9 would tint FMVs red for integrated graphics cards, maybe something similar is going on here.

Actually, using windowed mode fixes the problem. There is no longer a green filter in fullscreen windowed mode. What could be causing this?

**Comment by AmSolidSnek** [comment]
Sorry for the super late replies, I work 3rd and this is the only time I am up. Anyway, I think I have fixed the issue for myself so hopefully if anyone else has the same problem, this is how I solved it:
In d3d8.ini set
ResX = 0
ResY = 0
EnableWndMode = 1
FullscreenWndMode = 1

This just fixed the specific issue that cropped up after updating to the most recent NVIDIA driver for 16XX and 20XX series video cards. It may be something unique to my system, but if the issue is more widespread this might help someone else fix it.
Thanks to all for the input!

**Comment by Badore90** [comment]
> Sorry for the super late replies, I work 3rd and this is the only time I am up. Anyway, I think I have fixed the issue for myself so hopefully if anyone else has the same problem, this is how I solved it:
> In d3d8.ini set
> ResX = 0
> ResY = 0
> EnableWndMode = 1
> FullscreenWndMode = 1
> 
> This just fixed the specific issue that cropped up after updating to the most recent NVIDIA driver for 16XX and 20XX series video cards. It may be something unique to my system, but if the issue is more widespread this might help someone else fix it.
> Thanks to all for the input!

What if you set your monitor's screen resolution instead of 0??

When in windowed mode, If I set 0 to ResX and ResY, sometimes it happens that the game's window is not centered on the screen. It appears at the bottom left (so most of the game's screen is out of the monitor), when it happens I have to exit and re-boot the game. 

Setting the actual native resolution (1920x1080 in my case), that issue never happens.

**Comment by AmSolidSnek** [comment]
> > Sorry for the super late replies, I work 3rd and this is the only time I am up. Anyway, I think I have fixed the issue for myself so hopefully if anyone else has the same problem, this is how I solved it:
> > In d3d8.ini set
> > ResX = 0
> > ResY = 0
> > EnableWndMode = 1
> > FullscreenWndMode = 1
> > This just fixed the specific issue that cropped up after updating to the most recent NVIDIA driver for 16XX and 20XX series video cards. It may be something unique to my system, but if the issue is more widespread this might help someone else fix it.
> > Thanks to all for the input!
> 
> What if you set your monitor's screen resolution instead of 0??
> 
> When in windowed mode (maybe even in full-screen, I don't remember for sure), If I set 0 to ResX and ResY, sometimes it happens that the game's window is not centered on the screen. It appears at the bottom left (so most of the game's screen is out of the monitor), when it happens I have to exit and re-boot the game.
> 
> Setting the actual native resolution (1920x1080 in my case), that issue never happens.
> 
> I had this same behavior with Dark Souls (setting options through the DSfix)

That's just the opposite in my case, setting those values to my native res (3840x2160) and also using fullscreen windowed mode causes the window to display offset. The point here is that exclusive fullscreen is now borked for me after the driver updates (I haven't changed anything else on my PC that would cause it), so this is the only way I can fix it.

**Comment by Polymega** [comment]
I'm not sure why the latest Nvidia driver for you would be doing this when played in fullscreen mode. AFAIK, no one else has reported such a thing, either.

Do you have any custom profiles for `sh2pc.exe` set up in your Nvidia's Control Panel? Something that might would cause this?
