### ISSUE TITLE
Random appearing dots, texture glitches

### ISSUE THREAD

**Issue by SilentastheWinds** [elishacloud/Silent-Hill-2-Enhancements#296]
Hi, today I've finally gotten SH2E to work, and when i play the enhanced edition, I'm noticing some weird bugs. The one that's constant is this weird, almost film reel sort of effect, where dots of white, green, purple, or other colors pop on the screen for a millisecond then disappear, like an old film reel in a way.
Another issue seems to be more random, but every time I play the game I find one. I keep running into glitched textures, or some form of odd graphical glitching, that will remain until the game is closed. Once restarted, these areas won't posses the glitches, as far as I can tell from loading a save in these areas after restarting the game.[Example of glitched graphics](https://gfycat.com/remarkableagilekookaburra)
I can't really post much about the film reel effect I'm getting, though I could make a Youtube channel and upload some footage to help showcase it for you all, as well as well show how the weird graphical glitches appear. Some of the gifs I have may show off the film reel glitch better.[Another example of glitched graphics](https://gfycat.com/plumpeveryhen)

**Comment by SilentastheWinds** [comment]
The film reel effect always happens, even as the game starts up and gets to the main menu, its always present. The texture glitch is something I've always found manifesting in some spot, usually in an area I'm just arriving in.
Also, here's the [d3d8.log](https://gofile.io/d/NKEeZ)

**Comment by Polymega** [comment]
Hi there,

The first thing I'd test is to see if ReShade is causing this. **Remove** the following files and see if that alleviates the issue:

`d3d9.dll`, `d3d9.log`, `ReShade.ini`, `ReShade_sh2pc.ini`

If that doesn't work, check and ensure no settings are enabled in your AMD Radeon Control Panel for this program (`sh2pc.exe`) or as a global setting for games that might cause such issues.

If that doesn't work, try setting `d3d8to9 = 0` in the `d3d8.ini` file.

**Comment by SilentastheWinds** [comment]
I removed the files from the game, still saw the dots, and a glitched texture. What settings in the Radeon control panel may cause issues with the game?

**Comment by SilentastheWinds** [comment]
Just finished trying out the game with DX9 disabled in the d3d8.ini, still saw the dots, and when the camera moved closer to a table with a red square on it, the building behind it became cut off, the upper part of it was not there.[Building glitch](https://ibb.co/gWMtWqD)

**Comment by SilentastheWinds** [comment]
disabled any sort of graphical settings in the radeon software, re-enabled dx9, game runs well. The dots do reappear, though it may be due to my graphics card having run the game for a while, though i don't get why, my gpu(Radeon RX Vega 56)  should be able to handle it.

**Comment by Badore90** [comment]
Using different resolutions the dots keep appearing?

**Comment by Polymega** [comment]
> What settings in the Radeon control panel may cause issues with the game?

I'm not certain as I don't really use AMD. I've used Nvidia on all my PCs.

Chances are this is one of two things:

- The GPU is not playing nice with the game. Do you have issues with other games on your PC? Perhaps updating its drivers might fix the issues.

- If you obtained the game somewhere online, there's a chance files were modified/altered that might be causing the issues. We've had people have issues with the game in the past because of a sketchy download for the game that altered game files.

**Comment by SilentastheWinds** [comment]
I used to have issues with the card previously, I sent it to the manufacturer to be checked, and I think they sent me a replacement card, which has so far run smooth so far. And yes, my game is downloaded from online, it's from myabandonware, which was recommended by an individual on the Silent Hill reddit.

**Comment by Polymega** [comment]
I've never used an online version of the game, but from what I understand, the "MyAbandonware" copy seems to be fine, judging by others who use it.

I hate to say it, but my guy is saying some sort of compatibility issue with the game and this GPU. Perhaps updating the GPU's drivers might help/fix it. Beyond that, I'm not sure what else to recommend.

**Comment by SilentastheWinds** [comment]
> 
> 
> I've never used an online version of the game, but from what I understand, the "MyAbandonware" copy seems to be fine, judging by others who use it.
> 
> I hate to say it, but my gut is saying some sort of compatibility issue with the game and this GPU. Perhaps updating the GPU's drivers might help/fix it. Beyond that, I'm not sure what else to recommend.

Yeah, turned out it was just my Vega 56, the card has been a pain in my rear, and never seems to function properly. I got a GTX 1070 and everything is running fine, so it was a hardware issue ^-^'

**Comment by Polymega** [comment]
Appreciate you following up with this! And glad your new graphics card is treating you better. :)
