### ISSUE TITLE
Panda Dom reports sh2pc.exe as a virus

### ISSUE THREAD

**Issue by LoicHa** [elishacloud/Silent-Hill-2-Enhancements#297]
![image](https://user-images.githubusercontent.com/28562111/86511430-73786d80-bdf9-11ea-8436-a597f8ddfe3c.png)

**Comment by Polymega** [comment]
Using the executable from our website is safe; this virus protection looks to be reporting a false positive. If you're using an executable obtained elsewhere from the Internet, then there might be a chance it's malicious.

**Comment by w1lddog2** [comment]
https://www.virustotal.com/gui/file/49e5d27491bd395636eb3a014887df68d36147cf557fe387c94492fb7b873fc8/detection

I think you may using a file from somewhere else, this is a scan from the sh2pc.exe that i got with the patches.

**Comment by Polymega** [comment]
Thanks, w1lddog2.

I'm going to close this ticket.

@LoicHa 
Make sure you only use the files provided from our website when installing the mod packages.
