### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by kartur** [elishacloud/Silent-Hill-2-Enhancements#30]
Hi,

I tried the enhancements according to http://www.enhanced.townofsilenthill.com/SH2/index.htm and it works great! (I did everything except the reshade stuff)

However I noticed some minor stuff

- Website says "Rename sh2.exe to sh2.exe.bak" but it's actually sh2pc.exe
- Using "Multilanguage Enhanced .exe (Director's Cut)." fonts are not rendered in the menu. The english version works fine.
- Markings on the map are rendered outside the actual map in the black borders

Otherwise these enhancements work really well and I really enjoy all the improvements, especially the sound! 👍

**Comment by Polymega** [comment]
Hi @kartur 

> Website says "Rename sh2.exe to sh2.exe.bak" but it's actually sh2pc.exe

Thanks for catching this! I'll update/correct the installation guide soon. 

> Using "Multilanguage Enhanced .exe (Director's Cut)." fonts are not rendered in the menu. The english version works fine.

This issue has now been resolved for future people who download the "Enhanced Edition Essential Files." You can fix this yourself by going here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/20#issuecomment-417506612

> Yes, this is a current limitation of the game engine. We hope to fix this in the future (by creating a "Fullscreen Image Enhancement Pack") but in the meantime you you can stretch the map to fill the entire width of your screen to hide this. Follow these steps here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/25#issuecomment-416053229

**Comment by kartur** [comment]
> We hope to fix this in the future (by creating a "Fullscreen Image Enhancement Pack")
Sounds great. Personally I think with the map fix SH2 on PC would be pretty much perfect.

I forgot to mention one thing:

- "3. Install SH2 Enhancements" it says to "Download SH2 Enhancements" but what it really means is the d3d8.zip from the latest release. This might be confusing for people who don't know that the enhancements are based on a modified d3d library.

**Comment by elishacloud** [comment]
Issue resolved.  Closing.  @kartur, you can open it back up if you are not happy with the resolution.
