### ISSUE TITLE
Resolution suddenly turns low resolution and 4:3

### ISSUE THREAD

**Issue by k1mk4t** [elishacloud/Silent-Hill-2-Enhancements#301]
hey its me again if you recognise me, 

i've just reinstalled Silent Hill 2 again (dont worry my saves have been backed up haha). this time i got it from myabandonware so that i could clear any sort of potential malware from my previous install of the game which i got from another website that probably wasnt safe... wish i could just buy the pc game but geez they are so goddamn expensive and that they're not on steam either. doesnt help that my laptop doesnt have a disc driver too so i dont really have much of a choice :( . 

anyways, i downloaded and installed the game along with the other files included in the SH2 myabandonware download page (nocd, the official patch and modern systems fix) and installed all the necessary files to set up SH2 Enhanced Edition. but for some reason when ResX and ResY's values are set to 0, the game doesnt load with my pc's native resolution, instead its in 4:3 and it looks like the 800x600 resolution.. this can be fixed when i set ResX and ResY to my pc's exact native height and width in their values, but it still annoys me that my desktop screen still shrinks back to that 800x600-ish resolution whenever i click the SH2 enhanced executable and that “User Account Control” prompt pops up and asks my permission because SH2 requires administrator access to launch the game. 

it makes loading the game longer than it should thanks to my pc busy shrinking the screen res before the UAC permission prompt can appear. i could live with this if i have to but blegh idk i just dont like it when my pc suddenly shrinks into a low resolution when i didnt ask it to do that in the first place. despite that happening, the game loads in my pc's native res as expected once i set the d3d8 res values to my native res. my guess is that its one of those fixes included in the myabandonware download that caused all this, but im not sure. 

ive tried uninstalling and reinstalling SH2 again after all this happened but alas, it did nothing. i just want to load SH2 in fullscreen while just leaving ResX and ResY's values as 0. heres my d3d8 log to see whats up.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4965532/d3d8.log)

EDIT: i forgot to mention that when i alt-tab out of SH2:EE whenever its in that 4:3 resolution. my entire desktop is also stuck in that resolution until i close the game!!!! the loading the game windowed doesnt help either, same outcome as before, just without the alt-tabbing! this window also pops up whenever i close the game too. (https://prnt.sc/tn7ar2) < heres what it looks like

**Comment by Polymega** [comment]
> i downloaded and installed the game along with the other files **included in the SH2 myabandonware download page (nocd, the official patch and modern systems fix)** and installed all the necessary files to set up SH2 Enhanced Edition

You didn't install any files from that download except for the game files, correct? If you installed/ran things like the patch they include in their download, or their 'modern systems fix', that might be a source of concern. [From our own website:](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

![image](https://user-images.githubusercontent.com/27395260/88322792-39f79b80-ccef-11ea-970e-a05e7ec61ff8.png)

> but for some reason when ResX and ResY's values are set to 0, the game doesnt load with my pc's native resolution

> i forgot to mention that when i alt-tab out of SH2:EE whenever its in that 4:3 resolution. my entire desktop is also stuck in that resolution until i close the game!!!!

Looking at your log file, you have disabled windowed mode (`EnableWndMode = 0`). If playing in fullscreen mode, your display's resolution will change to fit/match the resolution you set for the game. Trying leaving windowed mode on (`EnableWndMode = 1`) and see what that does for you.

> i just want to load SH2 in fullscreen while just leaving ResX and ResY's values as 0.

You can simply play in windowed mode while setting `ResX and `ResY` to `0` for a fullscreen experience. [More info here.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#transition-times-between-navigating-menus-areas-etc-is-noticeably-delayed-or-sluggish)

> it makes loading the game longer than it should thanks to my pc busy shrinking the screen res before the UAC permission prompt can appear. i could live with this if i have to but blegh idk i just dont like it when my pc suddenly shrinks into a low resolution when i didnt ask it to do that in the first place. 

Yeah, that doesn't sound right.

> this window also pops up whenever i close the game too. (https://prnt.sc/tn7ar2) < heres what it looks like

That's Windows itself wanting to confirm the program launched and ran as expected. I would answer "Yes" to that either way, to ensure Windows doesn't apply any sort of compatibility settings to the executable that you'd be unaware of.

**Comment by k1mk4t** [comment]
> Looking at your log file, you have disabled windowed mode (EnableWndMode = 0). If playing in fullscreen mode, your display's resolution will change to fit/match the resolution you set for the game. Trying leaving windowed mode on (EnableWndMode = 1) and see what that does for you.

i tried this but my display resolution still shrinks into the low 4:3 resolution again

> You didn't install any files from that download except for the game files, correct? If you installed/ran things like the patch they include in their download, or their 'modern systems fix', that might be a source of concern.
i think i did install those files, my bad... lemme see if reinstalling SH2 without those files would fix this

**Comment by k1mk4t** [comment]
update: reinstalled SH2:EE and it is still not working!!!

**Comment by Polymega** [comment]
> reinstalled SH2:EE without installing any other additional files in it and its still stuck in that goddamn crunched 4:3 resolution!!

Do you have any programs/software running in the background that could be hooking into the game and forcing its own resolution/display settings for the game? You might want to check that.

> also suddenly, there aren't anymore d3d8 and d3d9 logs being made too for some reason.

That means the SH2 Enhancements module isn't hooking into the game. Or, in other words, it's not working so anything you'd adjust in the `d3d8.ini` wouldn't take effect in the game. You're 100% sure no new `d3d8.log` files are being produced? 

If you view the game folder through the "Detailed" view and enable the "Date modified" table you can note the timestamp to see when the `d3d8.log` file was latest modified:

![image](https://user-images.githubusercontent.com/27395260/88417823-a090be00-cdb0-11ea-8dff-58ac5c0abf14.png)

**Comment by k1mk4t** [comment]
> Do you have any programs/software running in the background that could be hooking into the game and forcing its own resolution/display settings for the game? You might want to check that.

oh my god thank you for telling me this, i found the program that has been causing all this trouble! its called "Silent Hill 2 Processor Affinity Fix", i think this is that modern systems fix that was in the myabandonware download page. uninstalling this got rid of the 4:3 resolution immediately!!!

> That means the SH2 Enhancements module isn't hooking into the game. Or, in other words, it's not working so anything you'd adjust in the d3d8.ini wouldn't take effect in the game. You're 100% sure no new d3d8.log files are being produced?

im not sure, but as of now there still aren't any logs being made. at least in the game folder that is, but adjusting any settings in d3d8.ini would work and be applied into the game. the game folder is already in the detailed view and then i enabled the date modified table, but no trace of d3d8.log whatsoever.

**Comment by Polymega** [comment]
> update: found the d3d8.log file. its in "C:\Users\User\AppData\Local\VirtualStore\Program Files (x86)\KONAMI\Silent Hill 2" now all of a sudden?

This is due to installing the game to an admin-protected directory (such as `Program Files (x86)`) and not running the game as administrator. [Enabling `CheckForAdminAccess` should automatically check if the game needs to be run as an administrator](http://enhanced.townofsilenthill.com/SH2/config.htm#CheckForAdminAccess) and provoke the UAC prompt according.

Ensure `CheckForAdminAccess = 1` in the `d3d8.ini` file.

**Comment by k1mk4t** [comment]
CheckForAdminAccess is already 1, dunno why is isn't working. but i got d3d8.log back into the SH2:EE directory files by setting the SH2 Enhanced Executable to run it as an administrator via its properties, provoking the UAC prompt manually without having to tamper with d3d8.ini. thanks alot for helping me get rid of that program too btw!

**Comment by AeroWidescreen** [comment]
@Polymega It might be best to advise people not install their games in Program Files due to the aforementioned permissions. It's not a good idea to install any of your games in that directory, actually.

**Comment by AeroWidescreen** [comment]
@Polymega It might be best to advise people not to install their games in Program Files due to the aforementioned permissions. It's not a good idea to install any of your games in that directory, actually.

**Comment by Polymega** [comment]
@AeroWidescreen How about this?

![image](https://user-images.githubusercontent.com/27395260/88701225-b9161680-d0d7-11ea-80bb-51b5344f78ad.png)

**Comment by AeroWidescreen** [comment]
Yeah, that's perfect.

**Comment by k1mk4t** [comment]
> It's not a good idea to install any of your games in that directory, actually.

ill take note from that. when i have the time, ill move most of my games, including SH2, 3 and 4, out of there! dunno bout steam games tho

**Comment by AeroWidescreen** [comment]
>ill take note from that. when i have the time, ill move most of my games, including SH2, 3 and 4, out of there! dunno bout steam games tho

You can have Steam install your games in a different directory by default. You don't _really_ need to do that though. I was mostly speaking from the perspective of modding.

**Comment by k1mk4t** [comment]
> You don't really need to do that though. I was mostly speaking from the perspective of modding.

ah okay i understand now, just any games i have that are moddable then.

**Comment by Polymega** [comment]
The general idea is a lot of mods use `.dll` files, so if you accidentally place a `.dll` file in a wrong folder within your Windows directory is _could_ cause a lot of trouble for you PC.

So by not installing in an admin protected directory (such as `Windows\ Program Files (x86)`) you're less likely to accidentally do that.
