### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by Kreeplix** [elishacloud/Silent-Hill-2-Enhancements#302]
![unknown](https://user-images.githubusercontent.com/68778333/88457088-8243c480-ce7b-11ea-888e-bd2e26d979a4.png)

I thought that it was the PS2 noise filter but even after tweaking on the in-game options menu and d3d8, I couldn't manage to do it

**Comment by Polymega** [comment]
This looks like a post-processing filter being applied to the game. If you remove the ReShade files from the game's directory, does it fix the issue? Remove these files and folders:

```
\reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by Kreeplix** [comment]
Sorry for making you wait so long. It worked. Everything is back to normal. Can't I use ReShade?

**Comment by Polymega** [comment]
> Can't I use ReShade?

I'm not sure why the noise filter is looking like that for you. You can either [re-download ReShade from the website](http://enhanced.townofsilenthill.com/SH2/install.htm#installReShade) and see if that fixes it (perhaps some filter settings were accidentally changed for you) or simply forgo using ReShade.

It's worth noting that it is **not** critical to have ReShade for the best experience. In fact, we plan on dropping ReShade with the next project update.

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
