### ISSUE TITLE
Game was running fine before, today it freezes/ won't respond when open

### ISSUE THREAD

**Issue by dathaniel** [elishacloud/Silent-Hill-2-Enhancements#304]
As titled, screen freezes at launch black screen and it reads (1/2/3/4 effects remaining, the game might be unresponsive)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4992264/d3d8.log)

Thank you!

**Comment by Polymega** [comment]
Hi dathaniel,

If you remove the ReShade files from the game's directory, will the game launch for you then? Remove the following files:

```
\reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
