### ISSUE TITLE
Pyramid Head Fight Music & Angela Stairs Music

### ISSUE THREAD

**Issue by valtielfilms** [elishacloud/Silent-Hill-2-Enhancements#305]
There are a few consistent errors that happen every time I play; well I should say one is sporadic and the other one is very consistent.
The consistent one is the music doesn't play when I fight Pyramid head. After Maria is killed and then James does his speech after he gets up off the floor, the music is non-existent. One play through, it kicked in at the end of the fight, as if it needed to run after a silent loop ended or something (I don't know how to describe it). That aside, I guess the simple issue is that the music doesn't play during the Pyramid Head fight.

The second issue is that the music playing during Angela's staircase scene will start to skip and then continue to loop that skip like a broken record. Thankfully it stops after you leave the stairwell part but it certainly ruins the dramatic moment when it sounds like someone's trying to turn the cutscene into a dubstep mix.

If these are known or already addressed issues, I apologize for the re-post here but if not, any assistance would be appreciated! Many thanks!

**Comment by Badore90** [comment]
Is your PC doing some quite heavy process while playing?

I'm asking 'cause it happened to me something similar when playing on my old PC (dual core 2.0 and integrated card).
I was recording using the Xbox game bar and it affected cut-scene performance (video couldn't keep up with the audio) and some musics were missing (i.e. at the beginning, just after exiting the toilet, music was missing during the lecture, it only started at the track change when James starts speaking).

I don't know if it has to do with the fact that SH2 use 100% of CPU all the time,
However being just a performance issue (in my case) I can solve simply lowering resolution, disabling reshade and some other tricks when recording.

Try the game with lowere settings to check if it's a performace issue.

**Comment by lainshikinami** [comment]
I've also encountered both of these issues. The PH fight music can be fixed by reloading that area again at least. I haven't tweaked any settings yet though for either case.

**Comment by Polymega** [comment]
I believe Badore90 is correct on this; if there's other processes running on your PC that demand a lot of resources it could slow the game just enough to desync things such as audio loop timing.

You can also try following these steps to see if it helps any. This video tutorial will be posted on the website after the next project update release: https://youtu.be/0u8pY2dUyF0

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
