### ISSUE TITLE
I have a problem with silent hill 2: improved edition, such problem is the null presence of text.

### ISSUE THREAD

**Issue by benjamin112334** [elishacloud/Silent-Hill-2-Enhancements#306]
I have a problem with silent hill 2: enhanced Edition, such problem is the lack of text in the game, the subtitles do not appear, neither in the settings nor in the objects menu, only in the main menu and in the selection of the difficulty, please I would appreciate it if you help me.

**Comment by Polymega** [comment]
Hi Benjamin,

Without seeing your `d3d8.log` file, I'd assume you're using an older integrated graphics processor (IGP) to play the game. Older IGPs can't render the large resolution of the HD font. You can find similar tickets here:

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/299
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/264
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/240

To fix this, open the `d3d8.ini` file and set `UseCustomFonts = 0`. This will disable the HD fonts and use the original, low resolution font instead.

**Comment by benjamin112334** [comment]
thank you
