### ISSUE TITLE
Faulting module path: D:\SilentHill2\MSVCR70.dll

### ISSUE THREAD

**Issue by trondmg** [elishacloud/Silent-Hill-2-Enhancements#308]
Hi, I have the Directors Cut version of Silent Hill 2 for PC.
I followed the installation guide and did exactly what the guide told me to do.
When I try to open the game nothing happens.
When I check the eventlog on windows it tells me this.

Faulting application name: sh2pc.exe, version: 0.0.0.0, time stamp: 0x3d93137b
Faulting module name: MSVCR70.dll, version: 7.0.9254.0, time stamp: 0x3b1f6202
Exception code: 0xc0000005
Fault offset: 0x00006bb4
Faulting process ID: 0x2eac
Faulting application start time: 0x01d67258b0a0fec9
Faulting application path: D:\SilentHill2\sh2pc.exe
Faulting module path: D:\SilentHill2\MSVCR70.dll
Report ID: 4670cf2b-4596-4766-be76-7a62750a57fe
Faulting package full name: 
Faulting package-relative application ID: 

I have Installed dx9 multiple times now, and the redistributable package won't install because windows tells me that I allready have a newer or the same one installed allready.

**Comment by Polymega** [comment]
Hi there,

After trying to run the game, is there a `d3d8.log` in the game's directory? If so, please attach it to a follow up response.

**Comment by trondmg** [comment]
here are both the d3d8 and d3d9 files if you need them.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5077192/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5077193/d3d9.log)

**Comment by Polymega** [comment]
Thanks. Looking at your log file, you have some extra files in your game's directory. These might be causing conflicts/issues. [You want your directory to look like this.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree) 

So try removing `libwine.dll` and `wined3d.dll` and see if that fixes things.

I also noticed in your log the following:

```
1520 18:33:50.040 Warning: Unknown game binary hash: 0afa171ea93ee1441682f49969e6f02c
```

[Be sure you are using the executable provided on our site.](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE)

**Comment by trondmg** [comment]
Thank you so much for the help, and for the quick responses. The comment about the extra files was very helpfull, and I do not know why they were there. I basically uninstalled the whole thing and started with a totally clean install of Silent Hill 2. It is now working as it should.
