### ISSUE TITLE
Everything goes black when being under light / Reshade problem 

### ISSUE THREAD

**Issue by AlanRdzA** [elishacloud/Silent-Hill-2-Enhancements#309]
So I was playing all normal until I entered the apartments, everything went black and if I pause the game all the text stayed on the screen and went crazy blue, I think the image explains it better
![sh2pc 2020-08-19 16-23-49](https://user-images.githubusercontent.com/56949281/90694324-123c1a80-e23e-11ea-8189-32a0fae3096c.png)
Somehow I managed to get trough one door and I was able to play again then got under the lamp and the problem came back and that's why I think that the problem has to do with the light of the game
![sh2](https://user-images.githubusercontent.com/56949281/90694760-d190d100-e23e-11ea-9bb5-0bbba4c272be.png)

I went here to see if anyone has the same problem and it seems that its not the case so thats why I'm making this post, the only thing I found is that reshade could make trouble on some systems so I removed the reshade files which are the following:

reshade-shaders (its a folder)
d3d9.dll
ReShade.ini
ReShade_sh2pc.ini

**And it worked properly again**, I am using an integrated gpu on the AMD Ryzen 2300U had no performance issues running at 60 fps,

**Comment by Polymega** [comment]
Hi AlanRdzA,

Nice work doing the research and testing to figure out the culprit! Yes, [we've had reports in the past of this bug](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-flashlights-light-creates-a-brightlycolored-rainbow-effect), and it seems to be a rare bug that we have no solution for other than to remove the ReShade files.

The good news is we plan to drop ReShade from the installation process for the next project update, so by removing ReShade as you've done, you're just one step ahead of the curve now. Our plan is to include our own built-in shaders to do what ReShade did for us, minus the visual bugs as you're experiencing, of course. :)

**Comment by Polymega** [comment]
PS - Those white lines in the second photo you posted? [You should be able to remove them by using these settings for anti-aliasing in your AMD control panel.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-antialiasing-should-i-use-for-the-game)

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
