### ISSUE TITLE
Flash light issue

### ISSUE THREAD

**Issue by DexterityJosh** [elishacloud/Silent-Hill-2-Enhancements#31]
I'm having trouble with the flash light. Every time I toggle it on, it goes with a lighting bug I think...
![bug](https://user-images.githubusercontent.com/37750885/44940728-19ee2480-adc5-11e8-97eb-2a54606b5872.png)
![bug1](https://user-images.githubusercontent.com/37750885/44940730-1ce91500-adc5-11e8-9c45-529fc884f6d7.png)

**Comment by Polymega** [comment]
Hi @DexterityJosh, 
Please download the DirectX 9 SDK and see if that solves your issue:
https://www.microsoft.com/download/details.aspx?id=35

**Comment by DexterityJosh** [comment]
The DirectX installer mentioned that I have already the latest version and I've checked in my SysWOW64, there's already D3DX9, 10 and 11.

**Comment by elishacloud** [comment]
@DexterityJosh, can you describe in a bit more detail what the issue is when you toggle on and off the flashlight?

**Comment by Polymega** [comment]
It may be similar/the same as this issue. They solved it by updating the fix files:
https://github.com/ThirteenAG/WidescreenFixesPack/issues/490

**Comment by DexterityJosh** [comment]
Even updating and renaming the file didn't work , but I've finally solved the issue by setting the value of d3d8to9 to 0.
I tested it, but does it actually disables the shaders?

**Comment by Polymega** [comment]
Disabling d3d8to9 will disable ReShade and/or WineD3D. For AMD/Intel GPUs it's not too detrimental to keep d3d8to9 deactivated. For Nvidia GPUs you will experience a few visuals bugs without the use of d3d8to9/WineD3D.

**Comment by DexterityJosh** [comment]
My laptop uses an AMD GPU, so does it means it's fine?

**Comment by Polymega** [comment]
Yep, AMD GPUs are actually the most stable video cards to use with this game. By disabling d3d8to9 the only thing you won't be able to use is ReShade. 

ReShade slightly adjusts levels/color balance and has built-in anti-aliasing. It is not necessary to use to get the full experience with this game.

**Comment by DexterityJosh** [comment]
Well, that's a bummer. At least, the enhanced SFX make little things better

**Comment by DexterityJosh** [comment]
Thanks for the help guys. I didn't see much big difference when turning the value of d3d8to9 = 0. I just miss the Silent Hill series though...
