### ISSUE TITLE
When i open the game it becomes unresponsive

### ISSUE THREAD

**Issue by Catmaster309** [elishacloud/Silent-Hill-2-Enhancements#310]
When I launch the game, it becomes unresponsive shortly after loading the screen below, or it gets to a white screen and becomes unresponsive. It happens every time, even if I run it as admin, though the # of effect remaining seems to change when I run it as admin.

![Silent hill 2 error](https://user-images.githubusercontent.com/70117832/90992331-fc4f9200-e57c-11ea-9cb4-0394fc18111b.PNG)

Heres my d3d8 log
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5115226/d3d8.log)

**Comment by Catmaster309** [comment]
I look at the other post with a similar issue and removing the Reshade files didnt seem to do anything

**Comment by Polymega** [comment]
Hi there, 

Try running through this list to see if it resolves your issue:
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

Although, looking at your log file, I would assume it'd be the ReShade files, as integrated graphic processors (such as the Intenl HD Graphics 530 you're using) typically can't handle ReShade.

To be sure, the ReShade files are:

```
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by Catmaster309** [comment]
alright, thank you! I can sometimes get it to work if i just spam close and open it so hopefully i can make it smooth

**Comment by Catmaster309** [comment]
So removing all the files still had no effect. I put the game onto my Nvidia drive, and that changed it so now it always says there's 1 effect remaining, but it still freezes

**Comment by elishacloud** [comment]
> now it always says there's 1 effect remaining, but it still freezes

If it says there are effects remaining then you have not completely removed ReShade.  Only ReShade shows that screen.

From your log file it looks like you have two "Silent Hill 2" folders:

```log
C:\Users\nobur\Desktop\Silent hill 2 enhanced\Silent Hill 2
```

It is possible that you are running the game using a shortcut and the shortcut is pointing to a Silent Hill 2 folder that still has ReShade in it.

**Comment by Catmaster309** [comment]
oh sorry, I meant I put the game onto my Nvidia driver after removing the ReShade files. Removing the ReShade files just puts me on either a black screen or a white screen

**Comment by Polymega** [comment]
Try removing the IndirectSound files next to see if the game launches for you then. Remove:

```
dsound.dll
dsound.ini
dsound.log
```

**Comment by Catmaster309** [comment]
Alright, that seemed to do the trick, I closed and opened the game three times and it worked each time. Also, I was able to get the game to run before, but it only seemed to work the first time I opened it after restarting my computer. Any idea why that was happening?

**Comment by Catmaster309** [comment]
It froze again the fourth time

**Comment by Polymega** [comment]
So you're saying it runs without issue when you remove the IndirectSound files but freezes when you keep them in? If so, keep the IndirectSound files removed.

I'm not sure why, but on some rare occasions people have launch issues with IndirectSound. In any case, for the next project update, we're planning to remove IndirectSound from the installation process anyways.

**Comment by Catmaster309** [comment]
yeah, it has like a 50/50 chance to freeze when they're in. That sounds promising, I look forward to it!

**Comment by Polymega** [comment]
We've released the next update which officially drops IndirectSound in favor of DSOAL. You can get the DSOAL files here and see if you no longer experience launch issues: http://enhanced.townofsilenthill.com/SH2/install.htm#changelog

Note that we've also dropped our external use of ReShade as well, so you will still keep these removed from the game's directory.

**Comment by Catmaster309** [comment]
Thanks for the notice, I managed to run it enough to beat the game, but if
I ever replay it ill definitely come back to you guys. Thank you.

**Comment by Polymega** [comment]
Sounds good. Thanks for getting back with us. I'll close this ticket.
