### ISSUE TITLE
Pool room normal problem

### ISSUE THREAD

**Issue by DropsMJay** [elishacloud/Silent-Hill-2-Enhancements#311]
There a normal problem on the door model on the pool room:

https://i.imgur.com/GjXnelE.jpg

![image](https://user-images.githubusercontent.com/27395260/92185105-f41b1080-ee20-11ea-9f93-bd6e03c8ac3c.png)

**Comment by Polymega** [comment]
Great catch! Thank you for letting us know. I believe the smaller railings here are a 2D texture and this particular part of the fence was not set to render the texture double-sided.

I'll add this to our list of environment edits we hope to address. Thank you again 👍

**Comment by Polymega** [comment]
I'm going to close this ticket but I have added this to my to-do list for when Phillip finalized the level editor. Thanks again!
