### ISSUE TITLE
Proper mouse support

### ISSUE THREAD

**Issue by rlsprite** [elishacloud/Silent-Hill-2-Enhancements#313]
I know most people play the game using a controller but recently my faithful PS3 pad died and decided to try the game without it, thing is while you can use the mouse in menus you can't use it ingame. 

It would be nice to have proper mouse support like SH3 and 4 ports have.

**Comment by Polymega** [comment]
Team member Silent (CookiePLMonster) has expressed interest in doing this; to have mouse movement control the search camera movement and left click = select, right click = back during normal gameplay. However, it's low on the list of things to do at this time.

Before this would be looked into, Silent said he wants to look into restoring specularity across the game first. (It's the last "big thing" we need to restore to restore all big features missing from the PC version, when compared to PS2/Xbox.)

Good suggestion, though!
