### ISSUE TITLE
SH2:EE Window/Screen Flickering Issue

### ISSUE THREAD

**Issue by cakel0rd** [elishacloud/Silent-Hill-2-Enhancements#315]
Howdy.

Been doing a few test runs on SH2:EE recently ahead of a stream planned soon. 

A beautiful piece of work in all facets. The game itself performs well, but I do occasionally (every 30 seconds or less) experience moments where the game client briefly flashes white, usually with my mouse icon displaying the loading circle symbol. 

The flashes last a fraction of a second but are disruptive for immersion and presentation. The flashes usually show a brief glimpse of whichever window is behind the client. I am unable to troubleshoot a direct cause, as it can occur whilst standing still in all areas I've reached on my trial runs so far

I am playing on Windows 10 and adjusting my resolution, setting to windowed, etc doesn't seem to be a quick fix. Although I should likely note that my attempts to set the game to windowed mode, border and all, have been unsuccessful after editing the .ini. Also on the most recent update for the mod.

Any insight would be greatly appreciated.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5201842/d3d8.log)

**Comment by Polymega** [comment]
> The flashes usually show a brief glimpse of whichever window is behind the client. I am unable to troubleshoot a direct cause, as it can occur whilst standing still in all areas I've reached on my trial runs so far

I don't think this is an issue with our project, but sounds like something running in the background that might be causing this. Does this happen every time, even after restarting your PC? Does this also happen when running another game in windowed mode? Have you tried opening Task Manager as the game is running to see if there's any other programs running that might be trying to fight for focus on your screen?

> Although I should likely note that my attempts to set the game to windowed mode, border and all, have been unsuccessful after editing the .ini.

Note that in order for the window border to appear you must set `ResY` to a value of 32 pixels or less than your display's vertical resolution. This is a safety check to ensure the border doesn't get cropped out of your display area. [More info here.](http://enhanced.townofsilenthill.com/SH2/config.htm#WndModeBorder)

**Comment by Polymega** [comment]
I also noticed you're using an integrated graphics processor (IGP) to run the game. [Others' have had issues with the HD font while running the game using IGP.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/299) I've never heard reports of screen flashing from this, but you can also try setting `UseCustomFonts = 0` in the `d3d8.ini` file and see what that does.

My Surface Pro 3 uses IGP (Intel HD 4400). While it can handle the HD font, I have to disable the Fog Fix (`fog_custom_on = 0`) and can't use super high resolutions when playing the game otherwise I get bad lag. Not related to screen flashes, but just to say IGPs have to make some compromises with certain features of our project.

**Comment by cakel0rd** [comment]
@Polymega thank you for your feedback. I'll take these pointers into consideration and run some more tests. 

It doesn't appear to occur with other games. I previously thought my streaming client might've been intruding, but tests without it running have the same issues. This is likely entirely an issue on my side rather than the mod. 

I believe it's defaulting to the IGP, I may've tried with my gfx card directly, but I'll attempt again.

**Comment by cakel0rd** [comment]
It would seem that opting out of windowed mode entirely and forcing fullscreen has been a solution to the flickering. A few cons to this, but it's a strong compromise and I'm unsure why I didn't try earlier. I guess I'm more used to certain cons with fullscreen that otherwise! 

It's still somewhat likely that another program may be fighting for attention during windowed mode. I'll look into that a little further but it's safe to say it's not the mods issue, I would imagine.

I'll close this threat, thank you for your insight nonetheless.

**Comment by Polymega** [comment]
Here's how to use your dedicated graphics card over your integrated one: 

https://www.techadvisor.co.uk/how-to/pc-components/how-set-default-graphics-card-3612668/

This is a fairly usual thing we get a ticket on that has an easy way to fix it.
