### ISSUE TITLE
Game doesn't run with a DS4 connected

### ISSUE THREAD

**Issue by Nitsug72** [elishacloud/Silent-Hill-2-Enhancements#316]
Hi. I'm able to run the game just fine without any gamepad connected (keyboard/mouse only), but when I try to run it with a DS4 (via usb) it just crashes. I checked if there was any other device detected as a gamepad and that wasn't the case.
Is there a known solution?

**Comment by Polymega** [comment]
Hi there. If you're also using DS4Windows with your DS4 refer to this thread for a possible solution: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/281

**Comment by Nitsug72** [comment]
I'm not, I'm using my DS4 without any program like DS4Windows or xinput plus.

**Comment by Polymega** [comment]
Thanks for the info. I haven't experienced any issues when using my DS4, same for Aero_ on our team. In terms of troubleshooting I can think of two things to try:

- DS4s are detected as DirectInput devices by Windows. I was going to suggest trying to remove the Xinput Plus files, but you've already tested this one.
- Do you have any other controller to try and test? An Xbox 360 or Xbox One controller? If you can confirm whether or not it works with another controller, it can help determine if the issue is just with the DS4 or something more broad.

**Comment by Polymega** [comment]
Oh, one other thing: In the next update to our project the `d3d8.log` file will log which control SH2 PC has detected for use. Try this test build out:

https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4922188/d3d8.zip

Launch the game and, after it freezes, check and see if it created/made a new `d3d8.log` file. In this log file, near the bottom, it should tell you what gamepad SH2 PC has detected, if any.

**Comment by Nitsug72** [comment]
I just tried the build. It does recognize it (i think) but the game still crashes.
[d3d8 nitsug72's log.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5228030/d3d8.nitsug72.s.log.log)

**Comment by Nitsug72** [comment]
I don't have any other controller to test, unfortunately.

**Comment by Polymega** [comment]
Looking at your log file, this might have something to do with it? @elishacloud ?

```
10688 16:51:51.309 Loading as dll: "d3d8.dll"
10688 16:51:51.312 Wrapper created for "d3d8.dll"
10688 16:51:51.314 CheckMemoryAddress Error: memory address not found!
10688 16:51:51.317 SearchAndGetAddresses searching for memory address! Found = 00406403
10688 16:51:51.317 Hooking the FileSystem APIs...
```

**Comment by elishacloud** [comment]
Yes.  That error typically means that the sh2pc.exe binary file is unknown.  It is updating some random code in the binary, which could very easily lead to a crash.  I recommend downloading the file we have posted here:

http://www.enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE

**Comment by elishacloud** [comment]
Also, see this message in the log file:

```log
10688 16:51:51.304 Warning: Unknown game binary hash: 0afa171ea93ee1441682f49969e6f02c
```

It is telling you that the binary file is unknown.  Can you upload your sh2pc.exe file so I can take a look at it and compare it to what we have?

**Comment by Nitsug72** [comment]
I'm 100% sure that's the one I'm using already.
I tried the american 1.0 exe. in the installation guide and the same happens.

**Comment by Nitsug72** [comment]
https://mega.nz/file/mfwjEJ6B#GeiQFvQK8bTJteG6pyC34fHZBxMUYNeHoefSqCx1U1A
This is the one I'm using just in case, though I'm very sure it's the same one in the installation guide.

**Comment by elishacloud** [comment]
Looking more at the log file, where did you get build 1808?  That is an unreleased build.

```log
10688 16:51:51.254 Starting Silent Hill 2 Enhancements! v1.5.1808.0
```

Can you try using the latest released build 1750?  You can download the latest build from [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases).

**Comment by Nitsug72** [comment]
Polymega lend me the build in an earlier reply. I just tried build 1750, the exact same happens, the game crashes only when I have the DS4 connected.

**Comment by elishacloud** [comment]
Can you upload the logs from build 1750?

**Comment by Nitsug72** [comment]
Here you go.
[d3d8 nitsug 1750 log.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5229034/d3d8.nitsug.1750.log.log)

**Comment by elishacloud** [comment]
Thanks!  I don't see anything in the logs that indicate an issue.  Since the crash only happens with the DS4 and not with the keyboard and mouse, I am not sure if there is much I can do unless I can reproduce it.  But I don't have a DS4 pad.

One last thing you can try is using our latest build, there may be other issues in here but at least it will help for testing:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5229045/d3d8.zip)

**Comment by Nitsug72** [comment]
Ok, thanks a lot for your time. I'll try emulating a x360 controller with DS4windows to see if the same happens.

**Comment by Polymega** [comment]
Let us know if you get any success with DS4Windows, thanks. Also be sure to use this fork (continuation) of the DS4Windows project here: https://github.com/Ryochan7/DS4Windows

**Comment by Nitsug72** [comment]
Just tried DS4windows and the same happended. I checked the log and both the DS4 and the emulated x360 controller were recognized.
I thought about keeping the emulated x360 controller "connected" and then try to connect the DS4 after the game launches, so it doesn't even detect the physical DS4, but it seems like DS4windows just disconnects the 360 controller when there's no DS4 plugged in.

**Comment by AeroWidescreen** [comment]
You need to select "Hide DS4 Controller" in the DS4Windows settings. Also, I personally don't recommend DS4Windows since it has caused me (and other people I know) many issue in older games. It's much easier to use Steam's controller support instead. No drivers need to be installed, and it'll only apply to the games you launch through Steam.

**Comment by Nitsug72** [comment]
Hi, good afternoon. I just wanna let you know that I managed to test a Dualshock3 through an emulated x360 controller (using scptoolkit) and the game worked just fine. Now I'm pretty sure that booting the game with a DS4 especifically is causing the issue.

**Comment by Polymega** [comment]
Check and see if plugging in your DS4 makes Windows change your default audio input/output to the controller, which reportedly crashes the game on launch: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/329

**Comment by Nitsug72** [comment]
Hi. That's exactly what was happening. Now I can finally play xD
Thanks a lot for your help! <3
![20201215_134305](https://user-images.githubusercontent.com/71330403/102244909-af048100-3edb-11eb-8a95-559ca6c28b2c.jpg)

**Comment by Polymega** [comment]
Great! And nice picture too!
