### ISSUE TITLE
New game opens to black screen with music?

### ISSUE THREAD

**Issue by FunkyKonga** [elishacloud/Silent-Hill-2-Enhancements#319]
So I boot up the game and its fine but when i press new game select my difficulties its opens to a black screen and nothing but music and when i hit esc it closes program no explanation (I waited 10 mins before closing)

**Comment by Polymega** [comment]
Please attach a copy of your `d3d8.log` file.

**Comment by FunkyKonga** [comment]
I have no idea how to do that
 could you tell me?

**Comment by FunkyKonga** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5322313/d3d8.log)
 sorry here it is

**Comment by Polymega** [comment]
Thank you. It looks like you're launching the game from `sh2pcBACKUP.exe`. Try instead running it from `sh2pc.exe` and see if that fixes the audio problem.

**Comment by FunkyKonga** [comment]
sadly it didnt work... i screen recorded the issue if that helps? github just doesnt suport mp4 so idk how i could post it

**Comment by Polymega** [comment]
No worries. If it's just a black screen I guess there wouldn't be much to show. :-p

On the game's main menu screen, go to MOVIES. Select any video. Does the video play for you?

**Comment by FunkyKonga** [comment]
[https://www.youtube.com/watch?v=GihzjyFxuoM](url) ok i made a youtube url, but it cuts off after a min of black screen, as it just goes on like that...

**Comment by FunkyKonga** [comment]
no the movies dont play

**Comment by Polymega** [comment]
Okay. When you installed the game, it would have asked if you wanted to also install the movies to your hard disk. When it asked you this, did you select "yes"? Otherwise, the game would try to read the videos files from the game's disc, and if you don't have the disc inserted, it can't play the videos.

**Comment by FunkyKonga** [comment]
hm, i don't remember a option like that, should i try re installing the game?

**Comment by Polymega** [comment]
Another way to check: Do you have video files in the following folder?

`<path-to-game>\Silent Hill 2\data\movies\`

Note that you're checking the `data` folder, and not the `sh2e` folder for this.

**Comment by FunkyKonga** [comment]
no i don't have a movie folder within data

**Comment by Polymega** [comment]
This is the first time someone's reported this issue, but I'm thinking this might be the cause of your issue. Try re-installing the game and make sure to also install the movie files to your hard disk when the game's installer asks you.

I recommend reading this step in full for the re-install attempt:
http://enhanced.townofsilenthill.com/SH2/install.htm#installGame

**Comment by FunkyKonga** [comment]
yep ill re install, i actually followed that tutorial beforehand (obviously not well enough lol) but i think i might have just missed something

**Comment by FunkyKonga** [comment]
OK Awesome i think it works now! thanks for the help, this is my first play through ever and I'm really exited i'm so glad there are people who care about restoring classic games such as this thanks for the help!

**Comment by Polymega** [comment]
Glad the solution was relatively easy! Have a fun time!
