### ISSUE TITLE
Can't see the main menu / no surround sound

### ISSUE THREAD

**Issue by Mkilbride** [elishacloud/Silent-Hill-2-Enhancements#32]
I installed to my documents as per your guides instructions. I followed your guide, setting up indirectsound (Wonderful program, I've used it in a few others over the years, especially the F.E.A.R games and helps restore great audio.) 

It launches. I have to use Wine though because I'm using a NVIDIA GPU. Abit annoying, but oh well. 

Game loads to main menu, but there's nothing there. I see the menu backrounds, but no options. I can however, still select them and even get into the game itself or E3 trailers or the option menu. But it's all guess work.

The default controls on my DS4 are really strange as well. Square to select and when I try moving I seem to always be moving in the opposite direction for some reason. 

I have a 5.1 surround system connected via HDMI Audio through a A/V receiver on my GPU.  It shows Hardware being used in the options menu, but says Stereo. Trying to change it, it won't save, and I am only getting Stereo audio.

So the two main issues - no Surround Sound and no main menus, options don't seem to save in-game either. 

Full specs

8700K
1080 Ti (398.36 because the latest ones have issues for Monster Hunter World) 
32GB RAM
1TB SSD
Windows 10 64-bit Professional

My ini file:

https://pastebin.com/Br9D6hW8

My directory(not using Reshade or xinput):

https://i.imgur.com/wcNwH7F.png

To get the game to run at all, I had to put it into Windows XP Compatibility mode and disable DPI scaling by application. 

Appears to have been this:

https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/30

Replacing the .exe with the non multi-lingual one fixed it. However I still can't get Surround Sound. 

Here's a dsound log, if it helps anyone:

https://pastebin.com/JfqM4ByL

**Comment by Polymega** [comment]
Hi @Mkilbride ,

> Game loads to main menu, but there's nothing there. I see the menu backrounds, but no options.

This has been resolved for all future people who download the fix packages. You can also fix this yourself by following the steps on this post: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/20#issuecomment-417506612

> The default controls on my DS4 are really strange as well. Square to select and when I try moving I seem to always be moving in the opposite direction for some reason.

I haven't played/tested this game using DS4 (only an Xbox 360 controller) so I unfortunately can't assist with this. @seagull may be able to help, as he got the game to work using DS4.

> It shows Hardware being used in the options menu, but says Stereo. Trying to change it, it won't save, and I am only getting Stereo audio.

So long as it says hardware is being used then IndirectSound (simulated surround sound) is working for the game. Despite not being able to change the sound method to anything other than Stereo, I still have the surround sound effect with my setup when IndirectSound is in use. 

So, despite it saying Stereo is being used, do you still have the surround sound effect when using IndirectSound?

**Comment by Mkilbride** [comment]
In other games, I do. In this I am stereo only. Nohing is coming out of my rear channels.

Also I didn't play much, but I just got the map, went to the foggy area down the steps and my characters hair turned black. As well as his shirt and pants and shoes. His coat was still fine. I attempted to a take a screenshot, only to crash the game.

**Comment by seagull** [comment]
Hi;
1) Download the [Lavendy Xi driver](http://lavendy.net/special/driver/xi/index.html) to enable force feedback.
2) Grab [DS4Windows ](https://github.com/Ryochan7/DS4Windows) and set it up so it treats your PS4 controller like an Xbox pad.
3) Source a copy of Xpadder (I will not be providing links) and set it up thus:
![image](https://user-images.githubusercontent.com/241834/44949474-ff01cb80-ae29-11e8-8310-b51382729ebe.png)
4) Use attached keyconf.dat (stick it in the install directory, replacing the original).
[keyconf.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2342723/keyconf.zip)

That should get you more or less set up.  
Cheers - seagull

**Comment by Mkilbride** [comment]
Having troubles with the game resetting my controls on boot if I switch to using Steam Overlay. ( I want to stream it via Steam Link to my TV)

I have to disable Steam DS4 support so I can use the triggers.  But each time I restart the game, they reset to the defaults.  Also I was getting really weird slowdowns with Steam Link, but probably had to do with that Wine3D stuff.

**Comment by Polymega** [comment]
> Also not sure if it's just me or not, but the fog seems...excessive? There are times my entire screen is nothing but fog and I can't even see my character.

That extreme?! That's not normal/default. You can change fog values in the `d3d8.ini` file.

**Comment by Mkilbride** [comment]
I guess it is normal, I was looking online. Seemed excessive to me ah well. My only issues remaining now are no surround sound and for some reason characters are losing their lighting or something. As mentioned above, after cutscenes, characters hair often turns black or other parts of them like it lost textures. No clue. It's a fresh install of the game with a fresh mod. Wine3D related is all I can guess. Wish I didn't have to use it.

**Comment by seagull** [comment]
Yeah, it works fine with the setup above. Windows 10 x64.

**Comment by Hunk4TH** [comment]
> 
> 
> Yeah, it works fine with the setup above. Windows 10 x64.

Strange I can't get it to work. I'm also running Windows 10 x64. Using the Windows 7 force feedback driver. Could you please tell me what else you have setup? Like DS4Windows etc? You can pm me if that's easier?

**Comment by seagull** [comment]
I don't think Github _has_ any sort of PM support.
Besides, the instructions I posted are really all the information I have. I use a Sony DS4 USB adaptor and DS4Windows to locate it, I use the default settings so it thinks it's an Xbox pad, and then I turn force feedback on in the game options. This is as verbose as it gets I'm afraid.

**Comment by Hunk4TH** [comment]
> 
> 
> I don't think Github _has_ any sort of PM support.
> Besides, the instructions I posted are really all the information I have. I use a Sony DS4 USB adaptor and DS4Windows to locate it, I use the default settings so it thinks it's an Xbox pad, and then I turn force feedback on in the game options. This is as verbose as it gets I'm afraid.

Oh ok thanks for the info anyway! Still no luck but it isn't a big deal.

**Comment by Polymega** [comment]
I'll be honest: In not opposed to Xpadder but I'd prefer not to have to launch a separate piece of software each time to use a controller. I'm looking for a true "launch the game and go" type of thing. 

And I pretty much play SH2 with the d-pad using tank controls so the loss of the left joystick isn't _as_ detrimental as it could be for me.

That, and this is mostly a pure testing thing in regards to vibration. 'Cause I'm curious why it stopped working for certain configs and want to see if an old school gamepad still works out the gate.

**Comment by Hunk4TH** [comment]
Awesome hopefully it'll work! I use a DS4 pad and it too is a direct input controller. I even tried it by it self to no avail far as rumble goes. However it works just fine in SH3 so I'm not sure what the deal is. 

I know it used to work for me a few years ago using a 360 controller and that force feedback driver.

**Comment by Polymega** [comment]
I wonder if the way the vibration code was written for SH2 wasn't fully up-to-snuff (written to a specific standard) and that's why it borked? And perhaps it was written more solidly for SH3 PC which is why it still works there? 

I'm not a programmer to save my life so I'm just fully speculating here...

**Comment by Hunk4TH** [comment]
> 
> 
> I wonder if the way the vibration code was written for SH2 wasn't fully up-to-snuff (written to a specific standard) and that's why it borked from a supposed Windows update mid last year? And perhaps it was written more solidly for SH3 PC which is why it still works there?
> 
> I'm not a programmer to save my life so I'm just fully speculating here...

That's a good question but like I said above I got it to work by uninstalling the x64 force feedback driver and installing the x86 one. Not sure why it makes it a difference unless it's because SH2 is a 32bit app? Shame SH2 and SH3 can't get the same custom controller mod treatment that the GTA games have gotten :P

**Comment by Polymega** [comment]
Going back to your previous post: 

> However it works just fine in SH3 so I'm not sure what the deal is. 

Did you mean for SH3 PC your controller has/had vibration _without_ having to use the Force Feedback driver?

**Comment by Hunk4TH** [comment]
You might be right about SH2's vibration being a lil broken. It's definitely a mystery as to why it doesn't work with Xinput Plus. I'm gonna try SH4 too as it too didn't work with Xinput Plus.

Sadly I don't know anyone like that. It would probably be best to ask in the GTA community as they've done an amazing job with things suchs as Ginput etc.

**Comment by Polymega** [comment]
Perfect. Searching for "Ginput" led me to its creator, Silent, over at the GTA Forums. I've messaged them asking if they'd be interested in helping us out with this game. :) With a username like "Silent" I'm hoping they'd be interested in helping restore Silent Hill 2 PC's controller functionalities. Fingers crossed!

**Comment by AeroWidescreen** [comment]
Silent is on Github as well. https://github.com/CookiePLMonster

**Comment by Polymega** [comment]
Very nice. This man has been around the block; he's involved with a lot of game improvement projects and also ThirteenAG's UAL and d3d8to9. Here's hoping we can pick his brain for controller issues and maybe other things for SH2 PC as well then!

**Comment by elishacloud** [comment]
Closing this out.
