### ISSUE TITLE
Silent Hill 2 doesn't open with ReShade

### ISSUE THREAD

**Issue by snackbottle** [elishacloud/Silent-Hill-2-Enhancements#320]
I tried reinstalling it, changing the EnableWndMode to 0 and 1, change SingleCoreAffinity, change UseCustomFolder, opening as admin or not, and it always stucks at loading effects. I installed DirectX from the official links from SHEE and also the Visual. Tried changing resolutions also, tried putting 0 on the resolutions, tried disabling XI input and audio enhancements. I've seen more people with the same problem as well but we can't find the solution

d3d8 log:
9660 03:18:51.276 Starting Silent Hill 2 Enhancements! v1.5.1750.0
9660 03:18:51.276 To be filled by O.E.M. To be filled by O.E.M. To be filled by O.E.M. (Desktop)
9660 03:18:51.276   X79 To be filled by O.E.M. (Desktop)
9660 03:18:51.277 "Radeon RX 570 Series"
9660 03:18:51.277 Windows 10 Enterprise 64-bit (10.0.19041)
9660 03:18:51.277 "sh2pc.exe" (PID:14280)
9660 03:18:51.277 Game binary version: v1.0
9660 03:18:51.316 Warning: Unknown game binary hash: 0afa171ea93ee1441682f49969e6f02c
9660 03:18:51.316 Running from: "C:\Program Files (x86)\Konami\Silent Hill 2\sh2pc.exe"
9660 03:18:51.316 Config file: "C:\Program Files (x86)\Konami\Silent Hill 2\d3d8.ini"
9660 03:18:51.316 |----------- SETTINGS -----------
9660 03:18:51.316 |- ResX: 0
9660 03:18:51.316 |- ResY: 0
9660 03:18:51.316 |- EnableWndMode: 0
9660 03:18:51.316 |- WndModeBorder: 0
9660 03:18:51.316 |- FullscreenWndMode: 1
9660 03:18:51.316 |- d3d8to9: 1
9660 03:18:51.316 |- AnisotropicFiltering: 1
9660 03:18:51.316 |- FixGPUAntiAliasing: 1
9660 03:18:51.316 |- AutoUpdateModule: 0
9660 03:18:51.316 |- EnableSFXAddrHack: 1
9660 03:18:51.316 |- EnableTexAddrHack: 1
9660 03:18:51.316 |- NoCDPatch: 1
9660 03:18:51.316 |- DisableHighDPIScaling: 1
9660 03:18:51.316 |- UseCustomModFolder: 1
9660 03:18:51.316 |- SingleCoreAffinity: 0
9660 03:18:51.316 |- CheckForAdminAccess: 1
9660 03:18:51.317 |- DisableScreenSaver: 1
9660 03:18:51.317 |- DisableGameUX: 1
9660 03:18:51.317 |- ImproveStorageSupport: 1
9660 03:18:51.317 |- DPadMovementFix: 1
9660 03:18:51.317 |- GamepadControlsFix: 1
9660 03:18:51.317 |- RestoreSearchCamMovement: 1
9660 03:18:51.317 |- RestoreVibration: 1
9660 03:18:51.317 |- Southpaw: 0
9660 03:18:51.317 |- PadNumber: 0
9660 03:18:51.317 |- DisableRedCrossInCutScenes: 1
9660 03:18:51.317 |- DisableRedCross: 0
9660 03:18:51.317 |- IncreaseNoiseEffectRes: 512
9660 03:18:51.317 |- DisableCutsceneBorders: 1
9660 03:18:51.317 |- FMVWidescreenMode: 1
9660 03:18:51.317 |- FMVWidescreenEnhancementPackCompatibility: 2
9660 03:18:51.317 |- ReduceCutsceneFOV: 1
9660 03:18:51.317 |- Fix2D: 1
9660 03:18:51.317 |- FullscreenImages: 1
9660 03:18:51.317 |- LockResolution: 1
9660 03:18:51.317 |- MainMenuFix: 1
9660 03:18:51.317 |- MainMenuTitlePerLang: 1
9660 03:18:51.317 |- UseCustomExeStr: 1
9660 03:18:51.317 |- UnlockJapLang: 0
9660 03:18:51.317 |- LockScreenPosition: 1
9660 03:18:51.317 |- UseBestGraphics: 1
9660 03:18:51.317 |- CatacombsMeatRoomFix: 1
9660 03:18:51.317 |- CemeteryLightingFix: 1
9660 03:18:51.317 |- ClosetCutsceneFix: 1
9660 03:18:51.317 |- CreateLocalFix: 1
9660 03:18:51.317 |- DisableSafeMode: 1
9660 03:18:51.317 |- EnableSoftShadows: 1
9660 03:18:51.317 |- FastTransitions: 1
9660 03:18:51.317 |- FixChainsawSpawn: 1
9660 03:18:51.317 |- FixCreatureVehicleSpawn: 1
9660 03:18:51.317 |- FixDrawingTextLine: 1
9660 03:18:51.317 |- FixHangOnEsc: 1
9660 03:18:51.317 |- FixMissingWallChunks: 1
9660 03:18:51.317 |- FixTownWestGateEvent: 1
9660 03:18:51.317 |- Fog2DFix: 1
9660 03:18:51.317 |- FogParameterFix: 1
9660 03:18:51.317 |- FogSpeedFix: 1
9660 03:18:51.317 |- GameLoadFix: 1
9660 03:18:51.317 |- HalogenLightFix: 1
9660 03:18:51.317 |- HospitalChaseFix: 1
9660 03:18:51.317 |- HotelWaterFix: 1
9660 03:18:51.317 |- IncreaseBlood: 1
9660 03:18:51.317 |- IncreaseDrawDistance: 1
9660 03:18:51.317 |- LightingFix: 1
9660 03:18:51.317 |- LightingTransitionFix: 1
9660 03:18:51.317 |- PauseScreenFix: 1
9660 03:18:51.317 |- PistonRoomFix: 1
9660 03:18:51.317 |- PS2CameraSpeed: 1
9660 03:18:51.317 |- PS2FlashlightBrightness: 1
9660 03:18:51.317 |- PS2StyleNoiseFilter: 1
9660 03:18:51.317 |- RemoveEnvironmentFlicker: 1
9660 03:18:51.317 |- RemoveEffectsFlicker: 1
9660 03:18:51.317 |- RestoreSpecialFX: 1
9660 03:18:51.317 |- Room312ShadowFix: 1
9660 03:18:51.317 |- RowboatAnimationFix: 1
9660 03:18:51.317 |- SetBlackPillarBoxes: 1
9660 03:18:51.317 |- SteamCrashFix: 1
9660 03:18:51.317 |- WhiteShaderFix: 1
9660 03:18:51.317 |- WoodsideRoom205Fix: 1
9660 03:18:51.317 |- WidescreenFix: 1
9660 03:18:51.317 |- fog_custom_on: 1
9660 03:18:51.317 |- fog_transparency_layer1: 128
9660 03:18:51.317 |- fog_transparency_layer2: 90
9660 03:18:51.317 |- fog_layer1_x1: 0.250
9660 03:18:51.317 |- fog_layer1_x2: 0.250
9660 03:18:51.317 |- fog_layer1_y1: 0.125
9660 03:18:51.317 |- fog_layer1_y2: 0.125
9660 03:18:51.317 |- fog_layer2_density_mult: 1.4
9660 03:18:51.317 |- fog_layer2_density_add: 100.0
9660 03:18:51.317 |- fog_layer2_complexity: 0.08
9660 03:18:51.317 |- UseCustomFonts: 1
9660 03:18:51.317 |- DisableEnlargedText: 1
9660 03:18:51.317 |- CustomFontCol: 100
9660 03:18:51.317 |- CustomFontRow: 14
9660 03:18:51.317 |- CustomFontCharWidth: 20
9660 03:18:51.317 |- CustomFontCharHeight: 32
9660 03:18:51.317 |- NormalFontWidth: 20
9660 03:18:51.317 |- NormalFontHeight: 30
9660 03:18:51.317 |- SmallFontWidth: 16
9660 03:18:51.317 |- SmallFontHeight: 24
9660 03:18:51.317 |- LetterSpacing: 2
9660 03:18:51.317 |- SpaceSize: 7
9660 03:18:51.317 |- LoadPlugins: 0
9660 03:18:51.317 |- LoadFromScriptsOnly: 0
9660 03:18:51.317 |- LoadD3d8FromScriptsFolder: 0
9660 03:18:51.318 |--------------------------------
9660 03:18:51.318 |- 
9660 03:18:51.318 |-  Directory of "C:\Program Files (x86)\Konami\Silent Hill 2"
9660 03:18:51.318 |- 
9660 03:18:51.319 |- 10/04/2020  02:31 AM    <DIR>          data
9660 03:18:51.319 |- 10/04/2020  02:47 AM    <DIR>          reshade-shaders
9660 03:18:51.319 |- 10/04/2020  02:45 AM    <DIR>          sh2e
9660 03:18:51.319 |- 06/25/2002  09:50 AM           358,963 binkw32.dll
9660 03:18:51.319 |- 10/04/2020  02:48 AM                24 cin.dat
9660 03:18:51.319 |- 01/31/2020  11:39 PM             2,081 d3d8.dat
9660 03:18:51.319 |- 05/02/2020  03:50 PM         1,822,720 d3d8.dll
9660 03:18:51.319 |- 10/04/2020  03:18 AM            14,392 d3d8.ini
9660 03:18:51.319 |- 10/04/2020  03:18 AM                   d3d8.log
9660 03:18:51.319 |- 02/02/2020  03:52 AM         2,603,864 d3d9.dll
9660 03:18:51.319 |- 10/04/2020  02:48 AM             5,338 d3d9.log
9660 03:18:51.319 |- 09/26/2002  06:19 PM            12,332 device.fix
9660 03:18:51.319 |- 12/01/2019  03:20 AM           202,752 Dinput.dll
9660 03:18:51.319 |- 12/01/2019  03:20 AM           203,264 Dinput8.dll
9660 03:18:51.319 |- 11/18/2019  10:34 PM           633,344 dsound.dll
9660 03:18:51.319 |- 11/18/2019  10:35 PM            22,187 dsound.ini
9660 03:18:51.319 |- 10/04/2020  02:48 AM             3,127 dsound.log
9660 03:18:51.319 |- 03/17/2019  03:05 PM               504 keyconf.dat
9660 03:18:51.319 |- 07/25/2002  11:02 AM                77 Konami Homepage.url
9660 03:18:51.319 |- 08/25/2019  08:02 PM                37 local.fix
9660 03:18:51.319 |- 01/05/2002  12:40 PM           487,424 msvcp70.dll
9660 03:18:51.319 |- 06/07/2001  12:14 PM           339,968 msvcr70.dll
9660 03:18:51.319 |- 10/01/2002  04:33 PM            35,574 Readme.htm
9660 03:18:51.319 |- 10/01/2002  04:33 PM            16,083 Readme.txt
9660 03:18:51.319 |- 02/02/2020  03:55 AM             1,308 ReShade.ini
9660 03:18:51.319 |- 10/21/2019  07:18 PM               578 ReShade_sh2pc.ini
9660 03:18:51.319 |- 02/02/2020  02:07 AM               309 settings.ini
9660 03:18:51.319 |- 08/16/2002  03:44 PM             2,238 sh2.ico
9660 03:18:51.319 |- 03/21/2013  02:09 PM               648 sh2.sdb
9660 03:18:51.319 |- 09/30/2002  06:41 AM            71,078 sh2logo.jpg
9660 03:18:51.319 |- 01/11/2003  03:13 AM         5,476,352 sh2pc.bak
9660 03:18:51.319 |- 11/30/2017  08:22 PM         5,464,064 sh2pc.exe
9660 03:18:51.319 |- 12/01/2019  02:45 AM           531,968 XInput1_3.dll
9660 03:18:51.319 |- 12/02/2019  02:15 PM             2,816 XInputPlus.ini
9660 03:18:51.319 |--------------------------------
9660 03:18:51.319 Loading as dll: "d3d8.dll"
9660 03:18:51.321 Wrapper created for "d3d8.dll"
9660 03:18:51.509 Hooking the FileSystem APIs...
9660 03:18:51.511 Hooking the CreateProcess APIs...
9660 03:18:51.511 CD patch already set!
9660 03:18:51.511 Patching binary...
9660 03:18:51.511 Finding SFX file locations...
9660 03:18:51.672 Updating SFX memory address locations...
9660 03:18:51.672 Allocating memory buffer for sddata.bin file...
9660 03:18:51.680 Updating Texture memory address locations...
9660 03:18:51.681 Disabling High DPI Scaling...
9660 03:18:51.683 Disabling Screensaver...
9660 03:18:51.683 Setting 2TB hard disk Fix...
9660 03:18:51.683 Setting PS2 Style Noise Filter...
9660 03:18:51.683 Increasing the Draw Distance...
9660 03:18:51.683 Setting Cemetery Lighting Fix...
9660 03:18:51.683 Fixing tree lighting conditions...
9660 03:18:51.683 Setting Rowboat Animation Fix...
9660 03:18:51.683 Updating the Catacomb Meat Cold Rooms color...
9660 03:18:51.683 Updating Fog Parameters...
9660 03:18:51.683 Setting Piston Position Fix...
9660 03:18:51.683 Setting Hotel Room 312 Shadow Flicker Fix...
9660 03:18:51.683 Hiding Red Cross health indicator during cutscenes...
9660 03:18:51.683 Enabling PS2 Flashlight Fix...
9660 03:18:51.683 Fixing behavior of Lying Figures that are hiding under vehicles...
9660 03:18:51.683 Add fix to prevent chainsaw from spawning on first playthrough...
9660 03:18:51.683 Enabling XInput Vibration Fix...
9660 03:18:51.726 Enabling Custom Fonts...
9660 03:18:51.728 Enabling Custom Exe Strings...
9660 03:18:51.728 Enabling Main Menu title selection by language...
9660 03:18:51.728 Enabling post Processing Special FX...
9660 03:18:51.728 Enabling Town West Gate Event Fix...
9660 03:18:51.728 Enabling Screen Position option lock...
9660 03:18:51.728 Enabling Best Graphics settings...
9660 03:18:51.728 Enabling Fog Fix...
9660 03:18:51.728 Loading the "WidescreenFixesPack" module...
9660 03:18:51.847 Silent Hill 2 Enhancements module loaded!
9660 03:18:53.040 CheckForAdminAccess Checking if administrator access is required.
9660 03:18:53.362 Starting D3d8to9 v1.11.0.0
9660 03:18:53.362 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
9660 03:18:55.591 Enabling Resolution Lock...
9660 03:18:55.591 Setting Hotel Room 312 Resolution Fix...

d3d9 log:
03:18:51:324 [09660] | INFO  | Initializing crosire's ReShade version '4.5.3.756' (32-bit) built on '2020-01-12 15:49:01' loaded from "C:\Program Files (x86)\Konami\Silent Hill 2\d3d9.dll" into "C:\Program Files (x86)\Konami\Silent Hill 2\sh2pc.exe" ...
03:18:51:470 [09660] | INFO  | Registering hooks for "user32.dll" ...
03:18:51:470 [09660] | INFO  | > Libraries loaded.
03:18:51:471 [09660] | INFO  | > Found 13 match(es). Installing ...
03:18:51:507 [09660] | INFO  | Registering hooks for "ws2_32.dll" ...
03:18:51:507 [09660] | INFO  | > Delayed.
03:18:51:507 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\d3d9.dll" ...
03:18:51:507 [09660] | INFO  | > Delayed until first call to an exported function.
03:18:51:507 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\d3d10.dll" ...
03:18:51:507 [09660] | INFO  | > Delayed.
03:18:51:507 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\d3d10_1.dll" ...
03:18:51:508 [09660] | INFO  | > Delayed.
03:18:51:508 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\d3d11.dll" ...
03:18:51:508 [09660] | INFO  | > Delayed.
03:18:51:508 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\d3d12.dll" ...
03:18:51:508 [09660] | INFO  | > Delayed.
03:18:51:508 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\dxgi.dll" ...
03:18:51:508 [09660] | INFO  | > Delayed.
03:18:51:508 [09660] | INFO  | Registering hooks for "C:\WINDOWS\system32\opengl32.dll" ...
03:18:51:508 [09660] | INFO  | > Delayed.
03:18:51:508 [09660] | INFO  | Initialized.
03:18:53:041 [09660] | INFO  | Redirecting RegisterClassExA(lpWndClassEx = 0019FE94 { SH2PC Class }) ...
03:18:53:041 [09660] | INFO  | > Adding 'CS_OWNDC' window class style flag to 'SH2PC Class'.
03:18:53:144 [06912] | INFO  | Installing delayed hooks for "ws2_32.dll" (Just loaded via LoadLibrary("ext-ms-win-mininput-inputhost-l1-1-1.dll")) ...
03:18:53:144 [06912] | INFO  | > Found 8 match(es). Installing ...
03:18:53:362 [09660] | INFO  | Redirecting Direct3DCreate9(SDKVersion = 32) ...
03:18:53:366 [09660] | INFO  | Installing export hooks for "C:\WINDOWS\system32\d3d9.dll" ...
03:18:53:366 [09660] | INFO  | > Found 9 match(es). Installing ...
03:18:53:478 [09660] | INFO  | Redirecting IDirect3D9::CreateDevice(this = 02865600, pAdapter = 0, DeviceType = 1, hFocusWindow = 005609FC, BehaviorFlags = 0x40, pPresentationParameters = 0019F774, ppReturnedDeviceInterface = 0019F7AC) ...
03:18:53:478 [09660] | INFO  | > Dumping presentation parameters:
03:18:53:478 [09660] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:18:53:478 [09660] | INFO  |   | Parameter                               | Value                                   |
03:18:53:478 [09660] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:18:53:478 [09660] | INFO  |   | BackBufferWidth                         | 1360                                    |
03:18:53:478 [09660] | INFO  |   | BackBufferHeight                        | 768                                     |
03:18:53:478 [09660] | INFO  |   | BackBufferFormat                        | 21                                      |
03:18:53:478 [09660] | INFO  |   | BackBufferCount                         | 1                                       |
03:18:53:478 [09660] | INFO  |   | MultiSampleType                         | 0                                       |
03:18:53:478 [09660] | INFO  |   | MultiSampleQuality                      | 0                                       |
03:18:53:478 [09660] | INFO  |   | SwapEffect                              | 1                                       |
03:18:53:478 [09660] | INFO  |   | DeviceWindow                            | 00000000                                |
03:18:53:478 [09660] | INFO  |   | Windowed                                | FALSE                                   |
03:18:53:478 [09660] | INFO  |   | EnableAutoDepthStencil                  | TRUE                                    |
03:18:53:478 [09660] | INFO  |   | AutoDepthStencilFormat                  | 75                                      |
03:18:53:478 [09660] | INFO  |   | Flags                                   | 0x1                                     |
03:18:53:478 [09660] | INFO  |   | FullScreen_RefreshRateInHz              | 0                                       |
03:18:53:478 [09660] | INFO  |   | PresentationInterval                    | 0x1                                     |
03:18:53:478 [09660] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:18:55:585 [09660] | INFO  | Recreated runtime environment on runtime 1127CFF0.
03:18:55:597 [07512] | INFO  | Successfully loaded "C:\Program Files (x86)\Konami\Silent Hill 2\reshade-shaders\Shaders\DPX.fx".
03:18:55:603 [15496] | INFO  | Successfully loaded "C:\Program Files (x86)\Konami\Silent Hill 2\reshade-shaders\Shaders\HQ4X.fx".
03:18:55:606 [11664] | INFO  | Successfully loaded "C:\Program Files (x86)\Konami\Silent Hill 2\reshade-shaders\Shaders\Levels.fx".
03:18:55:674 [14556] | INFO  | Successfully loaded "C:\Program Files (x86)\Konami\Silent Hill 2\reshade-shaders\Shaders\SMAA.fx".

dsoundlog:
[[============================================================]]
  This file is created every time that IndirectSound is loaded
[[============================================================]]

IndirectSound was loaded statically at process startup
The IndirectSound library being loaded is located at C:\Program Files (x86)\Konami\Silent Hill 2\DSOUND.dll
	Version -- 0.20
The process loading IndirectSound is located at C:\Program Files (x86)\Konami\Silent Hill 2\sh2pc.exe
	File version info doesn't exist
Initializing User Settings
Loaded Local User Settings file: C:\Program Files (x86)\Konami\Silent Hill 2\dsound.ini
hardwareBufferCount: 128
	128 hardware-accelerated buffers will be emulated
eax1: false
	EAX 1.0 support will be disabled
eax2: false
	EAX 2.0 support will be disabled
surroundPanning: "constantPower"
	3D sounds will be positioned in speakers using constant power (-3 dB) panning
maxFrequencyRatio: 2
	Sounds can be played up to 2 times faster than their original frequency
	(pitch can be raised 2 times higher)
monoSourceBehavior: "center"
	2D sounds with mono sources will play out of the front center speaker if it exists
	and the front left and right speakers otherwise
disabled3dBehavior: "2D"
	3D sounds with disabled processing will play out of the same speakers that they would if they were 2D
earlyStopFadeOutTime: 0.002
	Sounds that are stopped before they are finished will fade out over 0.002 seconds
nearDistanceToStartNormalizing: 0.083
	3D sounds will gradually be normalized in all speakers when they are located 0.083 world units or closer to the listener
speedOfSound: 343.5
	Doppler shift will be calculated with a reference speed of sound of 343.5 meters per second
milesCompatibility: false
	Miles Sound System compatibility mode will be disabled
Audio Device: Fone de ouvido do headset (Wireless Controller)
	Role: Global default device
	Device ID: {0.0.0.00000000}.{f0772664-00b9-451a-b9ce-f9601c1ec6da}
	Format: 16 bit, 32000 Hz
Speaker Configuration: "Direct Out"
	This is intended for pro audio applications where each output channel is associated with some arbitrary external destination
		(e.g. each channel might represent a musical instrument)
	IndirectSound can not function properly with your audio device configured like this;
		consider changing your audio device properties
There is a discrepancy between the speaker configuration that XAudio2 and DirectSound report for your audio device
	DirectSound reports a speaker configuration of 4 (DSSPEAKER_STEREO)
	This may be because you're using Dolby Digital Live or DTS Connect. See the following:
		http://xboxforums.create.msdn.com/forums/t/22533.aspx
	If you are not using Dolby Digital Live or DTS Connect and see this message please contact indirectsound@gmail.com
	(IndirectSound can't change your audio device's speaker configuration;
	if you want to change it you must configure the playback device in Windows)
Your audio device is set to "Direct Out", which is incompatible with IndirectSound
The new instance of IDirectSound8 didn't successfully initialize

**Comment by Polymega** [comment]
Hello, 

Try removing the ReShade files to see if the game launches for you then. Remove these files/folders from the game's directory:

```
\reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by snackbottle** [comment]
> Hello,
> 
> Try removing the ReShade files to see if the game launches for you then. Remove these files/folders from the game's directory:
> 
> ```
> \reshade-shaders\
> d3d9.dll
> d3d9.log
> ReShade.ini
> ReShade_sh2pc.ini
> ```

Hmm I really thought it was an issue with ReShade, but after reinstalling the game without it the issue persists. It happens after I install the Enhanced Edition. The game is forever stuck at a black screen, and it gets even worse if I disable ForcedWindowedMode, it gets stuck and doesn't let me Alt+Tab so I have to restart the PC or sign out. That's weird. Changing between Dx8 and Dx9 is not doing anything as well

**Comment by Polymega** [comment]
Alright, let's try this next:

Remove the IndirectSound files and see if the game launches for you then.

```
dsound.dll
dsound.ini
dsound.log
```

**Comment by snackbottle** [comment]
> Alright, let's try this next:
> 
> Remove the IndirectSound files and see if the game launches for you then.
> 
> ```
> dsound.dll
> dsound.ini
> dsound.log
> ```

It works! Now the resolution is completely messed up but that's on me. I'm gonna reinstall everything again and try ReShade without the IndirectSound and report back to you guys because it can be important to maybe find an issue.

**Comment by Polymega** [comment]
That's good to hear! The resolution can be changed in the `d3d8.ini` file.

The good news is, for our next update release, we're planning on removing **both** ReShade and IndirectSound from the installation process. :)

**Comment by snackbottle** [comment]
> That's good to hear! The resolution can be changed in the `d3d8.ini` file.
> 
> The good news is, for our next update release, we're planning on removing **both** ReShade and IndirectSound from the installation process. :)

Alright. Can you keep the thread open just so I can update it for now with ReShade installed and no IndirectSound? Either way, I'll play it without ReShade if it doesn't work, I just wanna report back

**Comment by Polymega** [comment]
Sure thing. You can also close this ticket if everything is running well after your further testings.

**Comment by snackbottle** [comment]
> Sure thing. You can also close this ticket if everything is running well after your further testings.

It worked with everything on (including ReShade) and IndirectSound OFF. Thanks!
Just to be clear: everything in the package is working except the IndirectSound. Disabling it makes the game work just fine. Just reporting back in case someone has the same issue.

**Comment by Polymega** [comment]
Great! IndirectSound crashing the game is a fairly uncommon issue, but it's still an issue that seldom gets reported. 

For the next update, we will be using DSOAL instead of IndirectSound, and plan to integrate our own shaders directly into the project so as to drop ReShade.

**Comment by snackbottle** [comment]
> Great! IndirectSound crashing the game is a fairly uncommon issue, but it's still an issue that seldom gets reported.
> 
> For the next update, we will be using DSOAL instead of IndirectSound, and plan to integrate our own shaders directly into the project so as to drop ReShade.

Nice! Thanks for the help

**Comment by Polymega** [comment]
Closing issue. We've released the next update which officially drops IndirectSound in favor of DSOAL. You can get the DSOAL files here: http://enhanced.townofsilenthill.com/SH2/install.htm#changelog
