### ISSUE TITLE
Grey screen after loading the game

### ISSUE THREAD

**Issue by Ignacionoel** [elishacloud/Silent-Hill-2-Enhancements#321]
Hello, 
I'm having this problem where after loading either a new game or a saved one all I can see is a grey screen. The game loads succesfully, I can hear the audio and even move if press the buttons, but all I can see is a grey fog-like wall. 

Here's my [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5324692/d3d8.log) and thanks in advance.

**Comment by Polymega** [comment]
Hi there, 

It looks like you're using an integrated graphics processor (IGP). We don't recommend using ReShade if you're using an IGP. Try removing the ReShade files/folders and see if that fixes your issue:

```
\reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by Ignacionoel** [comment]
Hi, I tried it but it didn't fixed it.

**Comment by elishacloud** [comment]
A grey screen after starting a new game or loading an existing game could mean that you are missing the DirectX9 shader APIs.  These APIs are needed to convert the DirectX8 shaders to DirectX9.  Try disabling `d3d8to9`.  If that works then you will need to install the [DirectX 9 SDK](https://www.microsoft.com/download/details.aspx?id=35).

**Comment by Ignacionoel** [comment]
Ok, apparently that worked. Thank you very much!

**Comment by elishacloud** [comment]
Very good!  With the latest update (not yet released), the only remaining code we use from the DirectX 9 SDK is one dll and three APIs.  I have considered integrating these APIs into the project by using code from WineD3D to avoid this type of issue in the future.  I will look into this when I get some spare time.  But glad you are up and running now!
