### ISSUE TITLE
SH2 Engine Decompilation

### ISSUE THREAD

**Issue by Kneesnap** [elishacloud/Silent-Hill-2-Enhancements#322]
Dear everyone who works on this. I run a Frogger modding community.
One of the games we're working on in terms of creating mod tools is `Frogger: The Great Quest`.
The PS2 releases of the game contain debug symbols (structs, function names / locations, source code file names, etc.)
It uses the same engine as Silent Hill 2.

We're hoping to fully decompile the game, including the engine.
Would anyone be interested in joining us? The engine has much more code than the Frogger game itself does.
A decompiled engine would be useful for the work being done on Silent Hill 2 too.

Thank you, and apologies for not posting this somewhere else. I couldn't find a better place to post this.

**Comment by Polymega** [comment]
Hi @Kneesnap,

I can only speak for myself on the team, but my role for the project isn't coding or programming based, so decompiling isn't an interest personally for me at this time.

I do know @quaker762 has been studying and reverse engineering SH3's engine (which is iterated from SH2's engine) in the hopes of rebuilding that game from the ground up. I've tagged him in case he might be interested with your team's goals and ambitions.

**Comment by Kneesnap** [comment]
@Quaker672 Any thoughts?

**Comment by Bigmanjapan** [comment]
https://twitter.com/RSolidSnake11/status/1145974851808763905

Could help.

**Comment by Kneesnap** [comment]
Ooh good find.

**Comment by Quaker762** [comment]
Hi @Kneesnap and @Polymega 

Sorry for the late reply. I've been super busy lately and honestly haven't worked on Silent Hill related stuff, especially since the (most likely, unless this has changed) discovery was made that most of the game logic etc was baked into the executable. It didn't help that no one had found the mocap data, and many of my attempts to reverse where this was had yielded no results.

Id be more than happy to lend a hand when I have some time. I was thinking of restarting the project for Silent Hill 2 (and not 3) and actually trying to get some more RE work done. The best bit of advice I can give is to hook the game up to Ghidra and see what you can find.

**Comment by Kneesnap** [comment]
Hey! Happy to hear from you!

I don't know anything about what you mean by mocap data, however I've
figured out the formats of all of the data inside of the frogger exe. Could
you explain in more detail what you mean by this?

I also got really lucky and managed to find the exact compiler down to
matching the exact version Konami used. I've set it up and have it
successfully building C code. C++ is going to be more tricky because the
PS2 SDK which is publicly available is from 2005, and does not appear to
fully support the older tools. However, it should be doable.

I'm currently in the process of working with the author of the ps2 ghidra
support plugin to fix issues that will allow reverse engineering ps2 games,
and I'm also working on my own to import all of the relevant debug data
into a ghidra project. Given how well that's been going, I'm very
optimistic about this. The amount of work it takes to recreate equivalent
source code (not necessarily byte for byte match) is very little.

**Comment by Polymega** [comment]
Oh, and I shared a prototype build of SH2 that contains debug shops as well: https://hiddenpalace.org/Silent_Hill_2_(Jul_13,_2001_prototype)

**Comment by Kneesnap** [comment]
Forget the xmap, this prototype build contains debug symbols galore.

![image](https://user-images.githubusercontent.com/6562913/96637058-05d24d80-12d3-11eb-82ab-ec27863482ee.png)

**Comment by Kneesnap** [comment]
Unfortunately, I think this has led me to realize that SH2 does not use the same engine. Which is strange, I was fairly certain they did use the same engine given the similarity of many file formats and how they were both developed by konami at the same time.

**Comment by Quaker762** [comment]
> I don't know anything about what you mean by mocap data, h

Ahh Sorry, I should've been more clear. "Mocap" is the "Motion Capture Data" they used for the in-game cutscenes. All of it was acted out by real actors (the character voice actors IIRC)

> I also got really lucky and managed to find the exact compiler down to
matching the exact version Konami used. I've set it up and have it
successfully building C code.

Ahh that's really interesting, what toolchain were they using? I take it that it's some really old version of GCC??

> I'm currently in the process of working with the author of the ps2 ghidra
support plugin to fix issues that will allow reverse engineering ps2 games

Yeah this would probably be the best approach. I was thinking of trying to hook a debugger up to a PS2 or do it via PCSX to see what I could find. 

> Unfortunately, I think this has led me to realize that SH2 does not use the same engine.

This doesn't surprise me. We learnt pretty early on that the engine isn't an "engine" per se; it was most likely a "write once and don't bother" program for the game. I don't even think it's fully data driven like, say, a game like Dark Cloud is. As for the formats, I do have some code I can send you from Mike Meinhardt that described in some detail the 3D models/inbuilt texture formatting that I can email to you. There's also a pretty solid texture loader on sh3redux that you can take if you want to play with. 

> Forget the xmap, this prototype build contains debug symbols galore.

How in the name of Christ did you get a dump like that? Ghidra? I didn't know it could do that hahaha! How do I do the same?

**Comment by Kneesnap** [comment]
> Ahh that's really interesting, what toolchain were they using? I take it that it's some really old version of GCC??
It's using the MW MIPS Compiler (Metrowerks for PS2 w/CodeWarrior)
I'm not entirely clear to what extent GCC is used, because gcc is included, however it appears there is a Metrowerks proprietary DLL which is used. I've uploaded it here: https://archive.org/details/metrowerks-ps2-compiler In addition to this, you will need the PS2 SDK, which can also be found on archive.org

> This doesn't surprise me. We learnt pretty early on that the engine isn't an "engine" per se; it was most likely a "write once and don't bother" program for the game. I don't even think it's fully data driven like, say, a game like Dark Cloud is. As for the formats, I do have some code I can send you from Mike Meinhardt that described in some detail the 3D models/inbuilt texture formatting that I can email to you. There's also a pretty solid texture loader on sh3redux that you can take if you want to play with.
Thanks for the offer, I don't think I need it though. I already have a pretty good idea of how the relevant formats work, and for everything I don't I have full struct data from the executable.

> How in the name of Christ did you get a dump like that? Ghidra? I didn't know it could do that hahaha! How do I do the same?
Not quite, though theoretically this functionality could be added to Ghidra. I made some changes to a program called dwarf2cpp. https://github.com/Kneesnap/dwarf2cpp/ If you need a pre-compiled exe, let me know. It should be pretty simple to setup & compile in VS2019 though.

**Comment by Kneesnap** [comment]
I'm currently working on a way to import this DWARF data into Ghidra too. Unfortunately it seems the PS2's architecture makes working with PS2 games in ghidra a bit annoying. Mainly that pointers seem to be relative to a value in the 'gp' register, which can be changed at runtime. Currently looking into ways to make dealing with that easier.

**Comment by Quaker762** [comment]
> It's using the MW MIPS Compiler (Metrowerks for PS2 w/CodeWarrior)
> I'm not entirely clear to what extent GCC is used, because gcc is included, however it appears there is a Metrowerks proprietary DLL which is used. I've uploaded it here: https://archive.org/details/metrowerks-ps2-compiler In addition to this, you will need the PS2 SDK, which can also be found on archive.org

Cheers, I'll grab a copy of that and take a look around.

> Not quite, though theoretically this functionality could be added to Ghidra. I made some changes to a program called dwarf2cpp. https://github.com/Kneesnap/dwarf2cpp/ If you need a pre-compiled exe, let me know. It should be pretty simple to setup & compile in VS2019 though.

That's pretty neat, I'm gonna have to have a bit of a play with it ahahaha

> Unfortunately it seems the PS2's architecture makes working with PS2 games in ghidra a bit annoying. Mainly that pointers seem to be relative to a value in the 'gp' register, which can be changed at runtime. Currently looking into ways to make dealing with that easier.

This sounds like a pretty big SONY moment if you ask me. Though I suppose that's an inherent design decision with MIPS processors?

**Comment by Kneesnap** [comment]
I'm fairly certain the PSX did not have these register shenanigans, and
that was a MIPS R3000. The PS2 uses a custom chip designed for it, I
believe it's called the emotion engine, which is kind of a weird name for a
chip. I kind of doubt sony was behind the decision though.

**Comment by Quaker762** [comment]
This is completely off topic, but I've had a bit of a dig through these symbols and done some step through debugging through PCSX2. Anyone that had money on "All Game Logic is Hardcoded" wins. There's some pretty quirky abstraction going on maintained through an events list that's loaded per stage. 

```cpp
struct stage
{
	_anon3* ev_list;
	unsigned char* ev_pos;
	int(*ev_prog)();
	_anon0* gi_list;
	Model_List* mdl_list;
	_anon2* en_list;
	void(*stage_init)();
	void(*room_init)();
	void(*alltime_func)();
	int glb_crd;
	int reserve_05;
	int reserve_06;
	int reserve_07;
	int reserve_08;
	int reserve_09;
	int reserve_10;
	int reserve_11;
};
```
`int(*ev_prog)();` looks like this:

```cpp
// Start address: 0x22ae10
int EvProgFirstMeetTrihead()
{
}
```

Hahahahahaha!

@Polymega Is there a forum/IRC you guys hang out where we can discuss this stuff? It might be best to start _seriously_ reversing the game/formats now that we have a full layout of the structs used in engine. We can pretty much just memory scan our way to victory at this point.

**Comment by Kneesnap** [comment]
I'm working on an automated way to import all of this data into Ghidra too.
It should make reversing the game very easy.

**Comment by umbrellacorp53** [comment]
I'm not a coder, just a pleb that's following the project because I love SH2... this here sounds huge... Almost all the work that's been done so far from what I've gathered has been through poking and prodding at the game from various angles through cheat engine and other methods, but everything has been trial and error with educated guesses. Are you guys figuring out how to decompile the game back readable source code right now or am I dramatizing what's happening?

**Comment by Polymega** [comment]
``` C++
int EvProgFirstMeetTrihead()
```

Holy cow. There's a 110% chance that variable name has been reversed correctly, so it looks like you guys are on to something big here!

> Is there a forum/IRC you guys hang out where we can discuss this stuff? It might be best to start seriously reversing the game/formats now that we have a full layout of the structs used in engine.

We don't have a Discord or anything; just this Git repository for discussions. There's [Silent Hill Community](http://silenthillcommunity.com/), but I don't know how well/conducive it'd be for discourse on programming. I'm also not sure how suitable something like Discord would be for searching/preservation on reverse engineering discussions either. (I haven't used Discord a ton!)

Would making a new repository on GitHub be best suited? Would it fit well in your sh3redux repository? Whatever you end up deciding, I'll definitely be following it!

**Comment by Kneesnap** [comment]
I say making a discord server would be best as a hub for efforts on a
decomp. A new repository is a must. Ideally we could follow the process
that seems to have been perfected by the n64 decomp team.

1. Create an assembly project which builds into a byte for byte match of
the original executable. Have a build setup which makes it so when you
build it checks to make sure the output is a byte for byte match, so you
know if you screwed anything up.
2. Split it up into different compile units/files.
3. Replace all hardcoded addresses with labels. (Allowing for code to be
shifted around in the binary for modding)
4. Turn the assembly into equivalent C code, compiling at every step.


The good news is that we can automate a LOT of this by utilizing ghidra and
the debug symbols.

The bad news is that doing this is currently outside of my knowledge. I
don't know how to create a project which builds into a byte for byte
replica of the original executable. Hopefully someone else knows. If not, I
can talk with people who do know, and work to figure it out myself.

The other option is just forgetting about a byte for byte match, which
might be a good idea because it will be very difficult to match line number
debug info exactly, and instead just focus on creating equivalent C code.
This normally isn't doable for most projects, but given all of the debug
information present it seems realistic to me.

Does anyone want to lead the decompilation effort for sh2? I've not
actually played silent hill 2 yet, I really just enjoy reverse engineering,
and I want to use this as an opportunity to learn and contribute to a cool
project. Ie: I don't think it makes sense for me to lead the effort on
something like this, even if I do want to contribute. Maybe the person who
is designated as the leader can create the discord.

**Comment by Kneesnap** [comment]
> I'm not a coder, just a pleb that's following the project because I love SH2... this here sounds huge... Almost all the work that's been done so far from what I've gathered has been through poking and prodding at the game from various angles through cheat engine and other methods, but everything has been trial and error with educated guesses. Are you guys figuring out how to decompile the game back readable source code right now or am I dramatizing what's happening?

That's exactly what we're discussing. It would be a pre-release of the prototype version of the game, but that's still absolutely massive. It would be possible to complete it with the rest of the game too.

**Comment by Polymega** [comment]
That's really great you'd like to throw your hat into the ring, even if you've never played SH2 before. It reminds me of our very own Elisha here, as he never played the game before, but our SH2:EE project basically wouldn't exist without him.

> Does anyone want to lead the decompilation effort for sh2? I don't think it makes sense for me to lead the effort on
something like this, even if I do want to contribute.

It's not my place at all to be throwing others' names around like this, but if Quaker762 himself here [isn't well suited to lead such an effort](https://github.com/Palm-Studios/sh3redux), I wouldn't know who is! But I'll shut up on the matter as this isn't my wheelhouse.

**Comment by Quaker762** [comment]
> Are you guys figuring out how to decompile the game back readable source code right now or am I dramatizing what's happening?

When a program is compiled with Debug Information, the "symbols", or the names of important information such as functions, structures, local variables, source `.c` file names etc is stored in a "section" of the executable. The program that @Kneesnap linked very early on in the discussion allows all of these symbols to be dumped into the relevant files, meaning we can see the direct correlation between data structure members (e.g `Event/stage/stg_apart_e1f.c` has an array called `ev_list[17]`, meaning we know that there are 17 events in that particular level. We also know the events data member names, meaning we can also correlate the triggers and reverse engineer how _they_ work too. We can also load up the game in PCSX2's debugger for further investigation.

@Kneesnap 

> I say making a discord server would be best as a hub for efforts on a
decomp. 

I agree. Does someone here want to make one?

> 1. Create an assembly project which builds into a byte for byte match of
the original executable. Have a build setup which makes it so when you
build it checks to make sure the output is a byte for byte match, so you
know if you screwed anything up.
2. Split it up into different compile units/files.
3. Replace all hardcoded addresses with labels. (Allowing for code to be
shifted around in the binary for modding)
4. Turn the assembly into equivalent C code, compiling at every step.

> The bad news is that doing this is currently outside of my knowledge. I
don't know how to create a project which builds into a byte for byte
replica of the original executable. Hopefully someone else knows. If not, I
can talk with people who do know, and work to figure it out myself.

This sounds like a pretty good plan. Though I'm not 100% sure about doing a 1:1 recompilation. That might be a good start for us to actually try and build the binary on PC and hook up an OpenGL renderer like the SM64 guys. One issue I can see is the amount of global state and cruft in the source here. There seems to be symbols that are in the executable that aren't used anywhere (at least, according to PCSX2).

Maybe it'd be best to start with the [E3 trial version](silenthillforum.com/viewtopic.php?t=19459)? That has full symbols as well, but less assets and less stage/event code. Might be a good test initially to reduce the volume of work required to get us used to the source base.

> It's not my place at all to be throwing others' names around like this, but if Quaker762 himself here isn't well suited to lead such an effort, I wouldn't know who is! But I'll shut up on the matter as this isn't my wheelhouse.

I mean, sure. If you guys want me to host the repo on my GitHub profile no problem, I do get busy sometimes with work so it might be best for someone to manage the repo/discord (not to mention better programmers). If there's more of us working on it together we should be able to get something done. One of the reasons I stopped work on sh3redux was because of the amount of uphill work that was required to actually do any reverse engineering, and I just didn't have to time to work on it. I know @JokieW had a fair bit of stuff worked out, but he'd gone through some _serious_ reverse engineering over a long period of time. This could probably help him out a fair bit too.

> Does anyone want to lead the decompilation effort for sh2?

I was planning on better documenting all of the formats, so at least we have a good start and a better idea of how the engine works.

**Comment by Kneesnap** [comment]
Alright. How about we setup a discord tomorrow. I don't know how long I'll
be the discord owner, but I can create the discord server. I think it would
be best to post on this on any silent hill related forums. Quaker can
create the repository, or me. I don't think that part matters as much. We
should then post about it in silent hill forums / communities and make sure
everyone who contributes to sh2e knows about it, so we can get as many
people helping on this as possible / people interested can know it exists.

In the meantime, I've been working on importing this data into Ghidra. We
made a breakthrough today and fixed some of the key issues with reverse
engineering ps2 games in ghidra. (I say we, but it was really mostly a dude
named astrelsky, I just helped debug the issue.) This means all that's left
is actually being able to import this data into Ghidra.

**Comment by Quaker762** [comment]
Repo is up [here](https://github.com/Palm-Studios/sh2_source)

> In the meantime, I've been working on importing this data into Ghidra. We
made a breakthrough today and fixed some of the key issues with reverse
engineering ps2 games in ghidra. (I say we, but it was really mostly a dude
named astrelsky, I just helped debug the issue.) This means all that's left
is actually being able to import this data into Ghidra.

Oh sweet, is this just a modification to the ps2ee plugin that's on GitHub?

**Comment by Kneesnap** [comment]
**Discord Server Invite Link:** [https://discord.gg/eytCUdx](here)
We should move discussion to this discord server.

**Comment by Polymega** [comment]
I'm going to close this ticket but God speed to you guys and your decompiling efforts. 

### Once more, for anyone who finds this thread: Keep track of them on Discord at: https://discord.gg/BWTRJ5F
