### ISSUE TITLE
Apartment whisper missing

### ISSUE THREAD

**Issue by rlsprite** [elishacloud/Silent-Hill-2-Enhancements#323]
Title pretty much self explanatory. When I get to Lynn's apartment, just before Pyramid head fight there's no whisper when I enter the room or when exploring it completely for that matter. I tried disabling the sh2e folder (making the game use the original sound folder) but again, no whisper. I found this very odd. 

I don't remember needing to do anything to trigger this sound... Is just me or the whisper is absent in the PC port?

**Comment by AeroWidescreen** [comment]
This is the room where you find the key for the stairwell where you fight Pyramid Head, right? Because I've heard whispering in that location several times during recent playthroughs / testing. Perhaps it's randomly triggered and you had a case of bad luck?

**Comment by Polymega** [comment]
The whisper is determined if you'll get it or not the moment you start a new game. On a new game, a seed is generated. Within this seed will determine if the whisper will happen or not.

It's completely RNG if you get it. Same with knocking on the bathroom door in the prison; it's random how many knocks it'll take to provoke the audio jumpscare.

**Comment by rlsprite** [comment]
Ah that explain it. Maybe I had a bad luck with RNG because I've done like 3 like playthroughs in recent months and I haven't heard it. Thanks for the clarification! I was just about to reinstall the game, thinking it was some sort of issue on my side.
