### ISSUE TITLE
Blackscreen when forcing AA from AMD Drivers

### ISSUE THREAD

**Issue by rlsprite** [elishacloud/Silent-Hill-2-Enhancements#324]
Well I seem to be opening a few of these lately lol

Anyway, a few months ago I manage to finally upgrade my lowly HD 6950 to a RX 570. 

Using the 6950 I managed to force AA in the drivers for the game with no issues but now with the new GPU I get a blacksreen anytime shadows are present and the pause menu looks like this 

![KlI21tk](https://user-images.githubusercontent.com/33965548/95361377-a586e900-089a-11eb-9f16-720ed2046cf8.png)

I tried all AA options (Multisampling, Adaptative Multisampling and Supersampling), they all produce they same result.

Is worth mentioning I'm using the latest drivers (I also tried with the previous version and the same happens)

**Comment by Polymega** [comment]
It looks to be this issue:

http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-flashlights-light-creates-a-brightlycolored-rainbow-effect

It's a rare bug with certain GPUs. Follow the solution posted in that link to disable d3d8to9 and see if that fixes the problem for you.

**Comment by rlsprite** [comment]
You're right, disabling d3d8to9 does fix the issues but I've to sacrifice reshade and I would rather not. I can live without forcing AA but not with those washout colors the game originally have.
