### ISSUE TITLE
Silent Hill 2 Enhanced Edition Not Responding

### ISSUE THREAD

**Issue by FaisalNajm** [elishacloud/Silent-Hill-2-Enhancements#326]
Hey,
I've recently come across SH2 Enhanced Edition and decided to give it a go. I've followed the instructions on the website, and proceeded to download all the required files, made sure my pc could handle the game, and made sure everything was present in the Directory Tree.
Whenever I used to start the game, it used to tell me that it was Loading 4 - 8 shaders then stopped responding. I proceeded to remove the shader files all together after following specific instructions found on  other threads. This made the game function for around a day. Today, when I was idle on the screen and was sent to the idle cut scene, the game stopped responding all together. From that point on, every time I attempted to launch the game I'd be met with a black screen that prevents me from proceeding, then states that it's not responding. I've waited over 5 mins in hopes of it working again but it never does. I got a Silent Hill 2 ISO from Myabandonware.
The base game works, but the enhanced edition keeps crashing.

Thank you,

[d3d8 - Copy.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5379008/d3d8.-.Copy.txt)

![image](https://user-images.githubusercontent.com/72876074/96006434-29664580-0e46-11eb-8561-e1b4fcc41a0d.png)

**Comment by Polymega** [comment]
Hi there,
Can you please attach a copy of your `d3d8.log` file. (You attached a copy of the `d3d8.ini` file.)
Thanks

**Comment by FaisalNajm** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5379855/d3d8.log)
My bad! 
Thanks

**Comment by Polymega** [comment]
Thanks. Everything in your log file looks to be fine. Let's start simple and do what any IT tech would suggest: If you restart your PC will the game launch correctly for you once more?

**Comment by FaisalNajm** [comment]
Nope. I've attempted restarting the PC, nothing changes. I've closed all my applications, unplugged my controller etc.

**Comment by Polymega** [comment]
It's strange it was working for you one day, and then not the next day.

> Today, when I was idle on the screen and was sent to the idle cut scene, the game stopped responding all together.

Actually, have you ever seen a cutscene (FMV) play in the game before you had these issues? [If not, you might be experiencing the same problem this user had.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/319)

**Comment by FaisalNajm** [comment]
I did watch the cut scenes up until I reached the apartment building. So I've seen the spawning of the first monster, the encounter in the cemetary, the opening cut scene etc. I just found it strange that when the SH2 trailer was playing while I was idle in the menu, everything broke. Should I try the link above?

**Comment by Polymega** [comment]
This is a bit tricky to troubleshoot as your log file looks fine. This is a shot in the dark, but try removing the IndirectSound files from the game's directory to see if it launches for you then. Remove these files:

```
dsound.dll
dsound.log
dsound.ini
```

In a few rare cases, the game won't launch for some people using IndirectSound. I doubt this would be your issue, since it was working the other day, but it wouldn't hurt to try.

**Comment by FaisalNajm** [comment]
Nope, I'm still getitng the black screen sadly.

**Comment by Polymega** [comment]
Okay we may have to bring in the big guns and ask @elishacloud if he has any ideas on this.

**Comment by FaisalNajm** [comment]
Btw, I got my Silent Hill 2 copy via ISO, so this is what my current directory looks like, is everything in order? 
![image](https://user-images.githubusercontent.com/72876074/96025404-c4b6e500-0e5d-11eb-9479-793a3f1e6a2f.png)

**Comment by Polymega** [comment]
It looks to be fine to me. You can try removing the `_MASOSX\` and `Silent Hill 2 ISO\` folders from the directory to see if it launches for you then. Those folders shouldn't be affecting how the game reads the other files/folders, but you never know...

One other thing we could test: Open the `d3d8.ini` and set `UseCustomModFolder = 0`. See if the game launches for you then. [This essentially "disables" the `sh2e\` folder.](http://enhanced.townofsilenthill.com/SH2/config.htm#UseCustomModFolder) This can test to see if there's something within the `sh2e\` folder that might be causing your launch issues.

**Comment by FaisalNajm** [comment]
I've attempted both of the suggestions above, neither of them worked.

Sorry for dragging you into this haha, seems like I'm putting you through a lot of stress.

**Comment by Polymega** [comment]
Not at all. :) We're just trying to do a process-of-elimination in the hopes of figuring out the issue. The most common culprits (ReShade, IndirectSound, restarting PC) don't seem to be it, unfortunately.

Let's see if Elisha has any ideas on this. He's the smart one in the group!

**Comment by FaisalNajm** [comment]
Okay thanks.

**Comment by elishacloud** [comment]
@FaisalNajm, are you sure the issue is with this module?  Can you get the game working without the Silent Hill 2 Enhanced Edition module?

You could try disabling the following items:
```ini
AutoUpdateModule = 0
d3d8to9 = 0
EnableWndMode = 0
```

**Comment by FaisalNajm** [comment]
Thank you for taking time out of your day to contact me regarding this!
![image](https://user-images.githubusercontent.com/72876074/96106328-c4f9c380-0ee3-11eb-920e-b4e5d6c978dd.png)
![image](https://user-images.githubusercontent.com/72876074/96106352-ce832b80-0ee3-11eb-93ef-48528152f291.png)
Below are two images of the game working without the module, other than a few audio issues, it works just fine.
I tried what you suggest above, I still get the black screen, except this time its not unresponsive, but I can't close the window by any regular means, including alt f4, task manager etc. I'd just be stuck on a black screen without being able to do much else.

**Comment by FaisalNajm** [comment]
Is there any way I can move the new audio to the non enhanced version and make it work, then? Like I can slowly move specific files over and see which one officially crashes the game if you think that could help

**Comment by Polymega** [comment]
Something you can try is launching the game between every step from following the installation guide on the site.

So...

- Install base game + executable.
   - Does the game still run?
- Install SH2 Enhancements module.
   - Does the game still run?
- Install Enhanced Edition Essential Files.
   - Does the game still run?
- etc etc etc

Doing this you could hopefully determine if it's a specific package causing the problems. You said it's probably the SH2 Enhancement module, and doing this process could help confirm that.

**Comment by FaisalNajm** [comment]
It seems to crash directly after I try the adding the NA executable. I tried running it, I got the same black screen etc.

**Comment by Polymega** [comment]
That's very odd. The executable on our site is just stripped of the DRM. To be sure: You uninstalled and reinstalled the game and are saying the base (vanilla) game works without using the executable provided on our site? I wonder if MyAbandonWare recently changed their download for the game or something...

**Comment by Polymega** [comment]
Is your antivirus preventing the game from running?

**Comment by FaisalNajm** [comment]
I've reinstalled every game file on the SH2EE website then proceeded to install them in a copy of the functioning game folder to no avail. I'm still getting the same black screen etc. I've also disabled my antivirus / firewall, but I'm still getting the same result.

**Comment by Polymega** [comment]
I'm real sorry to say but I have no idea what the issue may be then. [You mentioned](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/326#issuecomment-710585865) that the game is immediately crashing with just the base/vanilla game when only using the cracked executable, which would mean our project files wouldn't be causing the crash then. Sorry I can't lend any other ideas on this. :-/

**Comment by elishacloud** [comment]
@FaisalNajm, what your seeing is not normal.  We have not seen this before.  However, there are several things that could be causing an issue.

1. Downloading the NA executable is optional.  If this executable does not work for you, no problem.  Just use the one you have.

2. If you download the executable from our website then you may need to unblock it.  Windows by default restricts what executable can do if they are downloaded from the internet.  See screenshot below:

![image](https://user-images.githubusercontent.com/25625456/96356445-624f2600-10a3-11eb-9745-7c35624cfa62.png)

3. There could be compatibility options that are causing issues.  I am playing with all compatibility options disabled:

![image](https://user-images.githubusercontent.com/25625456/96356472-e0abc800-10a3-11eb-8844-ade3f071ae44.png)

4. Check your DPI.  Try playing with high DPI set to 100%:

![image](https://user-images.githubusercontent.com/25625456/96356485-249ecd00-10a4-11eb-9199-ad3cde48d66c.png)

5. Check your Nvidia Control Panel and make sure you have all the 3D settings for Silent Hill 2 set to default for your video card.

![image](https://user-images.githubusercontent.com/25625456/96356505-6af42c00-10a4-11eb-834c-8f69ece51352.png)

6. Make sure you have the [DirectX 9 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=35) installed.

7. Finally, if you still have issues, try with this debug build.  This will produce a lot more logs.  Once the game hangs, zip up the logs and send it to us.

Debug build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5396932/d3d8.zip)

**Comment by FaisalNajm** [comment]
My first attempt at replacing the executable with the one I have appears to have worked! I'll keep this thread open for a day or so just in case it crashes again if that's okay with you, I really enjoy the game and I think this mod might be the best one I've seen so far!

Thanks for being patient with me!

**Comment by elishacloud** [comment]
@FaisalNajm, can you upload a copy of the executable that you are using that works?  I want to see how it is different than the one we have.

**Comment by FaisalNajm** [comment]
This is the executable that I'm currently using, sorry for the late reply!
[sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5402556/sh2pc.zip)

**Comment by elishacloud** [comment]
> This is the executable that I'm currently using, sorry for the late reply!
> [sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5402556/sh2pc.zip)

That file v1.0 and is identical to the one I am using.  The only difference between this and the one we have posted is that we added an icon to the one we posted.

**Comment by FaisalNajm** [comment]
I don't completely understand why mine works and the one I got from SH2EE doesn't if the only difference is the icon .

**Comment by elishacloud** [comment]
It is most likely related to your computer not trusting the executable downloaded (for security reasons) and thus limiting what it can do.  Anyways, you are not missing anything by using your executable.

**Comment by FaisalNajm** [comment]
Alright thank you very much!
