### ISSUE TITLE
Game freezes on launch only when controller is plugged in

### ISSUE THREAD

**Issue by InfiniteBeak** [elishacloud/Silent-Hill-2-Enhancements#329]
Hi, I just got the game and enhanced edition installed, I launched the game without my controller (official Dualshock 4) plugged in, just to check everything was working, and all was fine; I closed the game, plugged in my controller, and now the game freezes whenever I open it up. If I unplug the controller, everything works fine again.

Thanks in advance :) 

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5432436/d3d8.log)

**Comment by InfiniteBeak** [comment]
Well damn I somehow figured it out, I'll leave my solution here in case anyone runs into a similar issue; when I plugged in my Dualshock, Windows was switching my default input and output audio device to the PS4 controller, I switched them back and now the game launches fine. Very weird!

**Comment by Polymega** [comment]
Glad you figured it out! It's odd Windows detected your DS4 as an audio device as well. I've never heard it do that before. Typically, if you connect it and don't use any software wrappers for the controller, Windows will simply detect it as a DirectInput gamepad.

**Comment by George22x** [comment]
>It's odd Windows detected your DS4 as an audio device as well. I've never heard it do that before. Typically, if you connect it and don't use any software wrappers for the controller, Windows will simply detect it as a DirectInput gamepad.

There are two versions of DS4 controller: V1 with no audio support and V2 that detects also as audio device and supports DS4 headphone jack. BTW, I do not have new DualSense for PS5, but presume that it supports audio too.

**Comment by AeroWidescreen** [comment]
I have V2 as well and I can confirm that Windows detects it as an audio device. I have to manually switch the audio source back, but it works fine after I do that.

**Comment by Polymega** [comment]
Thanks for the info, guys. I'll write a thing about this on the troubleshooting page in the near future then. If I can find someone with a DS5 I'll try and get them to test if this audio thing happens with it as well.

**Comment by Polymega** [comment]
I added something to this on the troubleshooting page.

Here: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

And here: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#there-is-no-audio-in-the-game

**Comment by George22x** [comment]
Nice, but I hope it is only temporary solution and the crash will be fixed in the future.

**Comment by Polymega** [comment]
Elisha is aware of this problem and has expressed interest in trying to find a solution in the future. 👍

**Comment by George22x** [comment]
Great. 👍
