### ISSUE TITLE
Run sh2pc.exe Issue

### ISSUE THREAD

**Issue by BinariGuy** [elishacloud/Silent-Hill-2-Enhancements#33]
Just opening the sh2pc.exe this window appears every time
Help pls!!!
![issue sh2](https://user-images.githubusercontent.com/42665650/44952653-4ac46d00-ae4a-11e8-9fba-eb98a3c33cd9.png)

**Comment by Godzie** [comment]
It says you need to install MSVC++ libraries. Some of mod components using them.
Yeah, FAQ says IndirectSound using [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555). You should try to install it.

**Comment by Polymega** [comment]
Download the package @Godzie linked and, if you still receive this error, download the DirectX 9 SDK next:
https://www.microsoft.com/download/details.aspx?id=35

**Comment by BinariGuy** [comment]
@Godzie I already have a newer version it says
![issue](https://user-images.githubusercontent.com/42665650/44962303-cb837780-aee3-11e8-8a07-d91e1eb118c3.png)

**Comment by BinariGuy** [comment]
@Polymega I successfully installed but the problem belongs

**Comment by BinariGuy** [comment]
@Polymega Im still having this problem, but after 2 tries, it open the game normally...

**Comment by Polymega** [comment]
If you open the game now (after installing the DirectX 9 SDK) and leave it sit for at least 60 seconds each time does it eventually run each time?

**Comment by BinariGuy** [comment]
Yes

**Comment by Polymega** [comment]
Okay, it's good it boots up/runs every time for you now, at least. There is no singular cause as to why the game may take longer to load for some than others but is most likely a combination of PC spec factors.

By chance, are you running this game on a laptop?

**Comment by Polymega** [comment]
That's nothing to worry about then. It can take longer to load for some than others, and I think it is mostly due to how robust your PC hardware may be. 

I'm glad it's working for you now!

**Comment by BinariGuy** [comment]
@Polymega Thank you for this Mod!!!

**Comment by elishacloud** [comment]
This issue has been resolved.  Closing the issue.
