### ISSUE TITLE
Image Enhancement Pack not working

### ISSUE THREAD

**Issue by HayabusaZeroZ** [elishacloud/Silent-Hill-2-Enhancements#330]
I've tried three times now to install the new Image Enhancement Pack, but when I check my menu afterward, I'm still seeing the older, lower resolution images.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5456265/d3d8.log)

**Comment by elishacloud** [comment]
It looks like you have 5 folders under Silent Hill 2:

1. data
2. Enhanced Edition
3. sh2e
4. SILENT HILL 2
5. XInputPlus Ver4.15.2

Most of these folders should not be there.  The items under these folder should be here.  For example:

This folder: `C:\Program Files (x86)\KONAMI\Silent Hill 2\SILENT HILL 2\sh2e`
Should be here:  `C:\Program Files (x86)\KONAMI\Silent Hill 2\sh2e`

This file:  `C:\Program Files (x86)\KONAMI\Silent Hill 2\XInputPlus Ver4.15.2\XInput1_3.dll`
Should be here:  `C:\Program Files (x86)\KONAMI\Silent Hill 2\XInput1_3.dll`

Etc...

Check out this page to see what your folder should look like:
http://www.enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

**Comment by Polymega** [comment]
Hello,

Looking at your log file, it seems you've placed some of the enhancement pack files/folders in the wrong folders. These directories should **not** exist:

```
3404 21:59:52.746 |- 06/14/2020  01:24 PM    <DIR>          Enhanced Edition
3404 21:59:52.746 |- 10/28/2020  09:30 PM    <DIR>          SILENT HILL 2
3404 21:59:52.746 |- 10/28/2020  09:33 PM    <DIR>          XInputPlus Ver4.15.2
```

There should **not** be a `SILENT HILL 2` folder _within_ your `Silent Hill 2` folder. Same is true for an `Enhanced Edition` and `XInputPlus Ver4.15.2` folder. 

I believe there has been confusion on where to place the enhancement package files from their ZIP folders into the game folder. For example, from our website for the "Install Enhanced Edition Essential Files" step:

> Unzip the download package and move the contents within the `SILENT HILL 2` folder from the download to `<path-to-game>\Silent Hill 2\`.

You can refer to the directory tree on our site to ensure you have the files places in the right spots:
http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

**Comment by HayabusaZeroZ** [comment]
Thank you for the help; did some cleaning up and now the new images are loading in correctly. Thanks!
