### ISSUE TITLE
Crashing as I attempt to leave the graveyard at the start of the game.

### ISSUE THREAD

**Issue by SourArmoredHero** [elishacloud/Silent-Hill-2-Enhancements#338]
Hello,

I recently installed Silent Hill 2: Enhanced Edition, which loads up fine and runs really well up until I attempt to leave the graveyard following the cutscene with Angela.  The game immediately crashes to the desktop as I try to walk around the church.   I've attached a screenshot of the events viewer showing an issue with a .dll file, as well as the d3d8.log.  Any help in fixing this would be great! 

Thank you.

![EventsViewerScreenshot](https://user-images.githubusercontent.com/73809179/97828571-1698a100-1c8d-11eb-9b38-190aa246042b.png)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5472700/d3d8.log)

**Comment by Polymega** [comment]
Hello, 

Looking at your log shows this line, which I personally haven't seen before:

```
7960 21:50:36.324 Environment variable __COMPAT_LAYER = "RunAsAdmin Installer"
```

So we'll need Elisha or Aero_'s feedback on this. It might have to do with the crashing you're experiencing.

> The game immediately crashes to the desktop as I try to walk around the church.

If it's only crashing when you get near the vicinity of the church in the graveyard, it might have to relate to the [`LightingFix`](http://enhanced.townofsilenthill.com/SH2/config.htm#LightingFix) feature of our project. We change values for a memory address when you get near the vicinity of the church. But `LightingFix` shouldn't be crashing your game though. So let's see what Elisha or Aero_ have to say about that `__COMPAT_LAYER` message first.

**Comment by SourArmoredHero** [comment]
> Hello,
> 
> Looking at your log shows this line, which I personally haven't seen before:
> 
> ```
> 7960 21:50:36.324 Environment variable __COMPAT_LAYER = "RunAsAdmin Installer"
> ```
> 
> So we'll need Elisha or Aero_'s feedback on this. It might have to do with the crashing you're experiencing.
> 
> > The game immediately crashes to the desktop as I try to walk around the church.
> 
> If it's only crashing when you get near the vicinity of the church in the graveyard, it might relate to the [`RoomLightingFix`](http://enhanced.townofsilenthill.com/SH2/config.htm#RoomLightingFix) feature of our project. We change values for a memory address when you get near the vicinity of the church. But `RoomLightingFix` shouldn't be crashing your game though. So let's see what Elisha or Aero_ have to say about that `__COMPAT_LAYER` message first.

Thanks for the swift response.

**Comment by Polymega** [comment]
Sure. In the meantime, [we can look at this thread](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/334) of someone who had a similar--albeit different still--issue. [Going off of Elisha's suggestions](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/334#issuecomment-720016294) in that thread, you can try making a copy of `sh2pc.exe` and renaming it to something like `sh2pc_ee.exe` and see if it runs correctly for you then.

**Comment by Polymega** [comment]
Actually, before you even do that, right click `sh2pc.exe` and select **Properties.** Make sure nothing is checked on this screen, such as "Run this program as an administrator", in case this is the cause of that line we're seeing in your log file:

![image](https://user-images.githubusercontent.com/27395260/97915962-52307b00-1d20-11eb-8960-7ef87caf5817.png)

**Comment by SourArmoredHero** [comment]
Hello,

I unchecked the "run this program as administrator" option, and it crashed.  Copying and renaming the .exe also resulted in the same crash.

**Comment by SourArmoredHero** [comment]
This issue can be closed.  I reinstalled everything and it's working perfectly fine now.
