### ISSUE TITLE
Silent Hill 2 - Gameplay crashing

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#341]
My game launch but when im playing the game crash, i dont know why, 
I will send you a d3d8.ini file information bellow of my Silent Hill Game.

Thank You.

[ADVANCED OPTIONS]
AnisotropicFiltering = 1
AutoUpdateModule = 1
CheckForAdminAccess = 1
DisableHighDPIScaling = 1
DisableScreenSaver = 1
EnableSFXAddrHack = 1
EnableTexAddrHack = 1
FixGPUAntiAliasing = 1
NoCDPatch = 1
UseCustomModFolder = 1
d3d8to9 = 1

[CONTROLLER SETTINGS]
DPadMovementFix = 1
GamepadControlsFix = 1
PadNumber = 0
RestoreSearchCamMovement = 1
RestoreVibration = 1
Southpaw = 0

[CUTSCENE SETTINGS]
DisableCutsceneBorders = 1
FMVWidescreenEnhancementPackCompatibility = 1
FMVWidescreenMode = 1
ReduceCutsceneFOV = 1

[DIRECTX SETTINGS]
d3d8to9 = 1

[FOG]
fog_custom_on = 1
fog_layer1_x1 = 0.250
fog_layer1_x2 = 0.250
fog_layer1_y1 = 0.250
fog_layer1_y2 = 0.250
fog_layer2_complexity = 0.066406
fog_layer2_density_add = 100.0
fog_layer2_density_mult = 1.4
fog_transparency_layer1 = 128
fog_transparency_layer2 = 138

[FONT]
CustomFontCharHeight = 32
CustomFontCharWidth = 20
CustomFontCol = 100
CustomFontRow = 14
DisableEnlargedText = 1
LetterSpacing = 2
NormalFontHeight = 30
NormalFontWidth = 20
SmallFontHeight = 24
SmallFontWidth = 16
SpaceSize = 7
UseCustomFonts = 1

[FULL SCREEN IMAGE SETTINGS]
Fix2D = 1
FullscreenImages = 1

[GAME FIXES]
AudioClipDetection = 1
CatacombsMeatRoomFix = 1
CemeteryLightingFix = 1
ClosetCutsceneFix = 1
CreateLocalFix = 1
DisableHighDPIScaling = 1
DisableSafeMode = 1
EnableSFXAddrHack = 1
EnableSoftShadows = 1
EnableTexAddrHack = 1
FPSLimit = 60
FastTransitions = 1
FixAptClockFlashlight = 1
FixChainsawSpawn = 1
FixCreatureVehicleSpawn = 1
FixDrawingTextLine = 1
FixHangOnEsc = 1
FixMissingWallChunks = 1
FixTownWestGateEvent = 1
FlashlightFlickerFix = 1
Fog2DFix = 1
FogParameterFix = 1
FogSpeedFix = 1
GameLoadFix = 1
HalogenLightFix = 1
HospitalChaseFix = 1
HotelWaterFix = 1
ImproveStorageSupport = 1
IncreaseBlood = 1
IncreaseDrawDistance = 1
LightingFix = 1
LightingTransitionFix = 1
PS2CameraSpeed = 1
PS2FlashlightBrightness = 1
PS2StyleNoiseFilter = 1
PauseScreenFix = 1
PistonRoomFix = 1
RemoveEffectsFlicker = 1
RemoveEnvironmentFlicker = 1
RestoreSpecialFX = 1
Room312PauseScreenFix = 1
Room312ShadowFix = 1
RoomLightingFix = 1
RowboatAnimationFix = 1
SetBlackPillarBoxes = 1
SteamCrashFix = 1
WhiteShaderFix = 1
WoodsideRoom205Fix = 1

[HUD & NOISE FILTER SETTINGS]
DisableRedCross = 1
DisableRedCrossInCutScenes = 1
IncreaseNoiseEffectRes = 512

[INTEGRATED PACKAGES]
Nemesis2000FogFix = 1
WidescreenFix = 1

[MENU & LANGUAGE SETTINGS]
LockResolution = 1
LockScreenPosition = 1
LockSpeakerConfig = 1
MainMenuFix = 1
MainMenuTitlePerLang = 1
UnlockJapLang = 0
UseBestGraphics = 1
UseCustomExeStr = 1

[MISC]
SelfUpdate = 1

[MODS]
d3d8.dll = https://github.com/elishacloud/Silent-Hill-2-Enhancements

[PERFORMANCE SETTINGS]
CheckForAdminAccess = 1
DisableGameUX = 1
DisableScreenSaver = 1
FixGPUAntiAliasing = 1
ImproveStorageSupport = 1
SingleCoreAffinity = 8

[PLUGINS]
LoadD3d8FromScriptsFolder = 0
LoadFromScriptsOnly = 0
LoadPlugins = 1

[RESOLUTION & DISPLAY SETTINGS]
EnableWndMode = 1
FullscreenWndMode = 0
ResX = 1450
ResY = 960
WndModeBorder = 1

[SHADERS]
AdjustColorTemp = 1
EnableSMAA = 1
RestoreBrightnessSelector = 1

[d3d8.dll]
PlaceToRoot

**Comment by shahzebgit** [comment]
Try running the game in Administrator mode every time you play or else re-install all the packages properly.

**Comment by AeroWidescreen** [comment]
You need to upload **d3d8.log**, not d3d8.ini. Thanks.

**Comment by ppsalvador** [comment]
my game crash when im playing normally, not on cutscene or menu, just on gameplay

**Comment by Polymega** [comment]
You'll need to upload your d3d8.log file for us.

**Comment by ppsalvador** [comment]
d3d8.log file here
> 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5489842/d3d8.log)

**Comment by Polymega** [comment]
It might relate to this error in your log:

```
10128 17:23:25.216 rs_Direct3D9EnableMaximizedWindowedModeShim Error finding 'Direct3D9EnableMaximizedWindowedModeShim'
10128 17:23:25.216 Hook::HotPatch Error: Failed to find 'Direct3D9EnableMaximizedWindowedModeShim' api
```

We'll have to see what Elisha says about that.

In the meantime, try removing these files and folders from the game's directory to see if that fixes things. Removing the following:

```
reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by ppsalvador** [comment]
One more thing, can i play on 120FPS or only works at 60FPS?

**Comment by Polymega** [comment]
> One more thing, can i play on 120FPS or only works at 60FPS?

We recommend playing in 30 fps [because of documented issues](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28). If you're going to play at a higher framerate, I wouldn't push it past 60.

**Comment by Polymega** [comment]
Have you been playing the game at 120 fps? There's a possibility that's why the game might be crashing; certain audio cues and physics are tied to the framerate and setting it that high could crash the game.

**Comment by ppsalvador** [comment]
No, i been playing at 60FPS

**Comment by elishacloud** [comment]
> It might relate to this error in your log:
> 
> ```
> 10128 17:23:25.216 rs_Direct3D9EnableMaximizedWindowedModeShim Error finding 'Direct3D9EnableMaximizedWindowedModeShim'
> 10128 17:23:25.216 Hook::HotPatch Error: Failed to find 'Direct3D9EnableMaximizedWindowedModeShim' api
> ```
> 
> We'll have to see what Elisha says about that.

Yeah this was an issue I just recently fixed.  The fix will be in the next update.  Here is a pre-release of the fix:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5983657/d3d8.zip)

> No, i been playing at 60FPS

There are issues on anything other than 30FPS.  We recommend running at 30FPS.
