### ISSUE TITLE
Xbox controller triggers not working.

### ISSUE THREAD

**Issue by LionKnight413** [elishacloud/Silent-Hill-2-Enhancements#343]
I have installed all the files from the website and everything seems to work except the controller's default layout is not the same described in the instructions and the triggers do not register. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5488188/d3d8.log)

**Comment by LionKnight413** [comment]
[General]
iniFileVersion=4150
[KeyAssign]
LS=LS|DPAD
RS=RS
LT=LT
RT=RT
DPAD_UP=DPAD_UP
DPAD_DOWN=DPAD_DOWN
DPAD_LEFT=DPAD_LEFT
DPAD_RIGHT=DPAD_RIGHT
A=A
B=B
X=X
Y=Y
LB=LB
RB=RB
LSB=LSB
RSB=RSB
BACK=BACK
START=START
GUIDE=GUIDE
ThresholdA2D=40
DPAD4Direction=False
[LeftStick]
DeadZone=0
Saturation=32767
Linearity=1
Response=32767
RectCorrection=0
Scale=1
CenterOffsetX=0
CenterOffsetY=0
InvertX=False
InvertY=False
DisableX=False
DisableY=False
[RightStick]
DeadZone=0
Saturation=32767
Linearity=1
Response=32767
RectCorrection=0
Scale=1
CenterOffsetX=0
CenterOffsetY=0
InvertX=False
InvertY=False
DisableX=False
DisableY=False
[LeftTrigger]
DeadZone=0
Saturation=255
Linearity=1
Response=255
[RightTrigger]
DeadZone=0
Saturation=255
Linearity=1
Response=255
[RapidFire]
Buttons=
Speed=1
ToggleONOFF=False
ONOFF_Button=START|GUIDE
MaskToggleONOFF=False
EnableAtStart=False
[Hold]
Buttons=
ToggleONOFF=False
ONOFF_Button=BACK|GUIDE
MaskToggleONOFF=False
EnableAtStart=False
[Advance]
ForcePause=False
Pause_Button=START|BACK
Reset=True
Reset_Button=LB|RB|GUIDE
[Vibration]
LeftMotor_Strength=1
RightMotor_Strength=1
ToggleONOFF=False
ONOFF_Button=RSB|GUIDE
MaskToggleONOFF=True
EnableAtStart=True
[ProxyDll]
FileName=
FileNamex64=
[Misc]
UseInitBeep=False
SoundVolume=0.75
FileVersion=x86
UseXInput1_3=True
UseXInput1_1=False
UseXInput1_2=False
UseXInput1_4=False
UseXInput9_1_0=False
[ControllerNumber]
Controller1=1
Controller2=2
Controller3=3
Controller4=4
[SwitchSettings]
SwitchKey1=DPAD_UP|GUIDE
SwitchKey2=DPAD_RIGHT|GUIDE
SwitchKey3=DPAD_DOWN|GUIDE
SwitchKey4=DPAD_LEFT|GUIDE
Setting2=
Setting3=
Setting4=
[X2DInput]
EnableX2Dinput=True
LS_X=X_Axis
LS_Y=Y_Axis
RS_X=X_Rot
RS_Y=Y_Rot
LT=Button7
RT=Button8
DPAD_UP=Button14
DPAD_RIGHT=Button15
DPAD_DOWN=Button16
DPAD_LEFT=Button17
A=Button2
B=Button3
X=Button1
Y=Button4
LB=Button5
RB=Button6
BACK=Button9
START=Button10
LSB=Button11
RSB=Button12
GUIDE=Button13
SHIFT+LS_X=X_Axis
SHIFT+LS_Y=Y_Axis
SHIFT+RS_X=X_Rot
SHIFT+RS_Y=Y_Rot
SHIFT+LT=Button28
SHIFT+RT=Button29
SHIFT+DPAD_UP=Button30
SHIFT+DPAD_RIGHT=Button31
SHIFT+DPAD_DOWN=Button32
SHIFT+DPAD_LEFT=Button33
SHIFT+A=Button18
SHIFT+B=Button19
SHIFT+X=Button20
SHIFT+Y=Button21
SHIFT+LB=Button22
SHIFT+RB=Button23
SHIFT+BACK=Button24
SHIFT+START=Button25
SHIFT+LSB=Button26
SHIFT+RSB=Button27
SHIFT+GUIDE=Button34
SHIFT=
DisableUnmappedObject=False
ForceFeedBack=True
FFB_ConstantForce=0.25
FFB_RampForce=0.25
FFB_PeriodicForce=1
DeviceID1=
DeviceID2=
DeviceID3=
DeviceID4=
DisableXInput=False
DisableOtherGamingDevice=False
OverrideDeviceName=False
DeviceName=XInputPlus DirectInput Emurator
AddControllerNumberToInstanceName=False

**Comment by AeroWidescreen** [comment]
Which gamepad are you using exactly? Because this is what an Xbox One (Wireless) Controller shows up as:

> Controller (Xbox One For Windows)

While your gamepad shows up as:

> Bluetooth XINPUT compatible input device

**Comment by LionKnight413** [comment]
Xbox one wireless. So what do I need to change?

**Comment by Polymega** [comment]
Two things you can try:

1. Go to the game's Options > Control Options menu and see if you can assign any inputs to your triggers while in this menu. This will at least fully confirm if the game is detecting your triggers or not. On the "Install Controller" step on the site there's a box that tells you how to assign controller inputs in the game.
2. If you're able, plus the controller directly into your PC via a USB cable and see if the controller behaves any differently then.

**Comment by LionKnight413** [comment]
I cannot assign inputs and plugging the controller in does not change the behavior

**Comment by Polymega** [comment]
When you plug it directly in, then relaunch the game, close the game, then recheck your d3d8.log file does it still say:

```
Bluetooth XINPUT compatible input device
```

...under the `Gamepad` section?

**Comment by LionKnight413** [comment]
33040 09:42:20.625 |- Name: 'Controller (Xbox One For Windows)' GUID: {5BE80980-1E81-11EB-8001-444553540000}

**Comment by Polymega** [comment]
Sorry, I just now looked at your original log file. It seems you don't have the XInput Plus files installed! That, or you placed them in the wrong folder. 

Downloading XInput Plus should fix your issue.

**Comment by LionKnight413** [comment]
Where do they go? I put them where the instructions told me to.

**Comment by LionKnight413** [comment]
![silent hill files](https://user-images.githubusercontent.com/12215049/98126419-8f614e00-1e83-11eb-8c29-6c67f8a2ca34.png)

**Comment by LionKnight413** [comment]
Give me a second I just reread everything and I might be fixing it as we speak

**Comment by Polymega** [comment]
They go in the game's main directory, as seen here:
http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

If we look at your log file, they aren't present in the game's directory:
![Screenshot_20201104-095130](https://user-images.githubusercontent.com/27395260/98126311-70fb5280-1e83-11eb-9a41-997d3fd22ce1.png)

Actually looking at your directory it seems you have nearly all packages misplaced, so you also wouldn't experienced improved audio, FMVs, images, etc. There shouldn't be a `SILENT HILL 2` folder _within_ your `SILENT HILL 2` folder.

From our site, found on most installation steps:

> Unzip the download package and move the contents **within** the `Silent Hill 2` folder from the download to `<path-to-game>\Silent Hill 2\`.

You can try simply moving all the files in your `<path-to-game>\Silent Hill 2\Silent Hill 2\` folder to `<path-to-game>\Silent Hill 2\` folder and see if that fixes everything in one go for you.

Refer back to the directory tree for guidance.

**Comment by LionKnight413** [comment]
Yep, I figured it out. I misread the instructions. Move the contents of the Silent Hill 2 folder not move the Silent Hill 2 folder. a couple of words make a big difference.
