### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by rnz-ca** [elishacloud/Silent-Hill-2-Enhancements#344]
Hi,

I used to run the previous releases of sh2e in the past successfully.  However, with the latest release I am seeing a black screen on launch.  After this, I went into d3d8.ini and changed "d3d8to9" to 0 and then when I launch the game I see the Main Menu, I start a new game, i see the FMV of James in the washroom and then it freezes after that.  I am attaching the log file.  Seems stuck when setting SingleCoreAffinity.

[I am pretty sure I had installed DX9 before when trying the previous releases... but anyway, I tried to install it again just in case and it says I have a more modern version of dx and because of this it won't install it]

Thanks!

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5489448/d3d8.log)

**Comment by rnz-ca** [comment]
I am also attaching the dirs of the sh2e in case I did something wrong during installation.
[dir.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5489480/dir.txt)

**Comment by Polymega** [comment]
Thanks for the log file and detailed directory file. Everything looks to be in order and in place.

Your attached documents are so thorough I'm honestly not seeing what the issue might be! I think we'll need to get @elishacloud involved.

In the meantime, can you set `UseCustomModFolder = 0` in the d3d8.ini under the [ADVANCED OPTIONS] category and try again? This will disable the `sh2e` folder from being read. This could at least tell us if there's a modified game file by us that might be cause the game to not run for you.

**Comment by rnz-ca** [comment]
Thanks for the response!  I tried that but it's still staying on that black screen at launch and the log indicates the same thing (setting single core affinity)...  so this means it's not the custom data files.  it's just something with the executable I'd say.

**Comment by rnz-ca** [comment]
Another thing I found is that if I set "d3d8to9" to "0" i can start Maria's scenario and actually get to gameplay (I didn't try leaving the first room though, but at least i got to move my character).  I also tried James' scenario after that and it just freezes after the first FMV.  

Of course with "d3d8to9" set to "1" (default) i just get a black screen on launch.

**Comment by Polymega** [comment]
Can you try this INI file? [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5489838/d3d8.zip)

This is a nuclear option where just about everything is disabled in the INI. If the game will launch and play for you, that could help us determine if it's a particular feature within the project causing the problems. Note that you'll probably experience the audio loop bug pretty quickly in your tests, singe `SingleCoreAffinity` will be disabled.

**Comment by rnz-ca** [comment]
Tried it.  Still getting the same behavior.

![image](https://user-images.githubusercontent.com/73958390/98154509-e1fe3280-1ea2-11eb-90c5-60c7714e5222.png)

**Comment by rnz-ca** [comment]
In the next try, it launched actually.  I got that popup from the game you get after the game knows it crsahed last time.

This time I could play, of course without enhancements.

![image](https://user-images.githubusercontent.com/73958390/98154696-28539180-1ea3-11eb-9858-d1262fbae98a.png)

**Comment by Polymega** [comment]
Are you able to play for a little while without it crashing (minus the inevitable audio looping that might mess with the game)? 

If so, and this won't be very fun to do, but try re-enabling features in the d3d8.ini one-by-one. Once the game crashes for you again, you'll hopefully know what feature is causing the issue.

If it helps, these are the features we've added/modified since the last update:

- AdjustColorTemp
http://enhanced.townofsilenthill.com/SH2/config.htm#AdjustColorTemp

- AudioClipDetection
http://enhanced.townofsilenthill.com/SH2/config.htm#AudioClipDetection

- AutoUpdateModule
http://enhanced.townofsilenthill.com/SH2/config.htm#AutoUpdateModule

- DisableRedCrossInCutscenes
http://enhanced.townofsilenthill.com/SH2/config.htm#DisableRedCrossInCutscenes

- EnableSMAA
http://enhanced.townofsilenthill.com/SH2/config.htm#EnableSMAA

- EnableTexAddrHack
http://enhanced.townofsilenthill.com/SH2/config.htm#EnableTexAddrHack

- FixAptClockFlashlight
http://enhanced.townofsilenthill.com/SH2/config.htm#FixAptClockFlashlight

- FullscreenImages
http://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenImages

- GameLoadFix
http://enhanced.townofsilenthill.com/SH2/config.htm#GameLoadFix

- LockSpeakerConfig
http://enhanced.townofsilenthill.com/SH2/config.htm#LockSpeakerConfig

- PauseScreenFix
http://enhanced.townofsilenthill.com/SH2/config.htm#PauseScreenFix

- RestoreBrightnessSelector
http://enhanced.townofsilenthill.com/SH2/config.htm#RestoreBrightnessSelector

- RoomLightingFix
http://enhanced.townofsilenthill.com/SH2/config.htm#RoomLightingFix

**Comment by rnz-ca** [comment]
after this try, I alt-f4ed.  launched the game again and it again didn't work.  alt-f4 again, relaunch, get the popup saying it will use safe options for graphics and then it didn't start.  so at this point, i'm confused, i'm getting mixed results.  after this, I deleted cin.dat and restarted the game, it said using safe options and this time it actually started.

**Comment by Polymega** [comment]
Hmm... temporarily remove these files from the game's directory:

```
d3d8.dll
Dinput.dll
Dinput8.dll
dsound.dll
dsoal-aldrv.dll
```

What we're doing here is removing all the external packages that would hook into the vanilla game. This way, you are strictly playing the vanilla game and nothing else. If the game is still having launch issues, then we can probably safely say it's an issue with the executable, and not something else.

**Comment by rnz-ca** [comment]
Okkk, I did all that  (removing those files and using the basic d3d8.ini) and the game still stayed at the black screen in 3/3 tries.

Now, what I did is bring the executable from that previous sh2e version (which I still keep) and the game launched successfully 3/3.

The problem has to be some change in the executable because if I compare both, they are different in size.  See screenshot below.  The old one is 5332 Kb and this new exe is 5336 kb.

I also assume that because it's an older exe, I am missing on some improvements as well.

**Comment by Polymega** [comment]
> Now, what I did is bring the executable from that previous sh2e version (which I still keep) and the game launched successfully 3/3.

Very interesting. The only thing we changed within the executable was that we added the SH2 icon within it; something that should have no affect at all on how the executable itself runs/functions.

Here is a link to the EXE we were providing previously (without the icon added into it). Do me a favor and download this and compare it to your EXE. **I am going to remove this link shortly:** [sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5490071/sh2pc.zip)

Right click on both executables and select **Properties**. Are their sizes (down to the byte) identical? Can you also try using that executable I provided to see if the game still runs for you every time?

> I think these images are getting compressed by github? they don't look so dark in my monitor :)

It's probably because, since you were running the game in Safe Mode before, it sets the brightness level to 0 and, since we've restored the brightness selector for the game, it's dark for you now (as it should be). Go to the game's Options > Advanced Options menu and you can increase the brightness level.

**Comment by rnz-ca** [comment]
Yes, the one you just sent is basically the same I was testing from a previous version of SH2E, referenced in my screenshot below as "sh2pc.exe-provided-by-devs.exe" (which is the one you just sent) and "sh2pc.exe.previous-version-i-had.exe".

"sh2pc.latest-version-in-site.exe.bak" is the executable that I downloaded from your site today, the one that for me is causing issues.

I also did 6 tests.  3 for "sh2pc.exe-provided-by-devs.exe" and 3 for "sh2pc.latest-version-in-site.exe":

- All **good** for the **"sh2pc.exe-provided-by-devs.exe"**.
- **None** of the tests were successful for the **"sh2pc.latest-version-in-site.exe"**

There is probably some other change that went in the EXE apart from the icon?  or some settings are different in terms of how it was reassembled ? (if not compiled)

Also, out of curiosity, do you guys have the source code for the game? or just using some tool to add resources (icon) to the executable?

![image](https://user-images.githubusercontent.com/73958390/98159363-6f915080-1eaa-11eb-88c4-7a958147c330.png)

**Comment by Polymega** [comment]
Great. Thanks for providing results to your tests. I am going to revert the executable provided on the site back to the previous one (without the integrated SH2 icon) to be safe. 

And to be sure: You're also using the latest version of the SH2 Enhancements module (if you open your `d3d8.log` file, the first line should say "Starting Silent Hill 2 Enhancements! v1.7.1850.0")?

> Also, out of curiosity, do you guys have the source code for the game? or just using some tool to add resources (icon) to the executable?

I wish we had the source code! But no, we used a program like Rcedit to add the icon into the executable, [similar as the steps shown here.](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Add_icon_to_executable_file)

(@AeroWidescreen just to give you a heads up on this, too.)

**Comment by Polymega** [comment]
PS - By chance, when you tested the previous executable (before I sent you another copy to compare), were you launching it as `sh2pc.exe`, or were you launching it as a different name?

**Comment by rnz-ca** [comment]
Interesting.  Yeah, I just read in a site that Konami lost the source code for SH2 and SH3, hence why that HD collection released on PS3 was bad.

I just checked the d3d8.log and indeed i have the lines you just said: pasting it here again just in case:
1864 14:34:20.500 Starting Silent Hill 2 Enhancements! v1.7.1850.0

Maybe that software you guys used to add resources changed something it shouldn't?  idk.  I'm a videogame dev too btw.  Thanks for doing this enhancements to this game which is one of my all-time favorites.  I'm so sad that Konami has "apparently" dropped silent hill although there are some rumors here and there but nothing concrete.  At least not yet.

As for your question regarding the name of the executables yes, all 3 executables I have tested before as "sh2pc.exe".  The last tests I just ran and sent you were done by just running the "renamed" executables but I still got the same results, so, it looks like executable name does not affect anything.

It is a bit strange that other people haven't complained about this, though.

**Comment by Polymega** [comment]
> It is a bit strange that other people haven't complained about this, though.

Definitely. While it's nice to have the icon built-in to the executable, if there's a chance it's causing launch issues then the safer call is to revert this. I'll change this on the site by the end of today. Thanks for sticking with me and doing all these tests. It took a bit, but I'm glad we seemingly found the culprit.

And from all of us: Thanks for the kind words! Having others enjoy SH2 for the first time or all over again with the project is the best thing we can ask for. :)

**Comment by rnz-ca** [comment]
Thanks again!  Grats and props to all of you!

**Comment by Polymega** [comment]
Thanks again rnz-ca, I've updated (reverted) the executable on the website. 👍

**Comment by AeroWidescreen** [comment]
Well, that's a shame.

>While it's nice to have the icon built-in to the executable, if there's a chance it's causing launch issues then the safer call is to revert this.

Indeed. Sounds like it was causing more harm than good. Oh well.

**Comment by rnz-ca** [comment]
@AeroWidescreen maybe tool that was used to embed the icon into the executable has a bug?  it is the only thing I can think of.  embedding an icon should normally not cause issues.

**Comment by AeroWidescreen** [comment]
I used [Resource Hacker](http://www.angusj.com/resourcehacker/).  I added the icon and saved. I dunno. 

> embedding an icon should normally not cause issues.

Yeah, that's what I was telling Polymega. This is the first time we've done this to the exe, so who knows? Maybe I did something wrong or the application is bugged like you said.  I dunno, I'll look into it later.

**Comment by AeroWidescreen** [comment]
@rnz-ca @Polymega Can you guys tell me if this works? Icon is just a placeholder.

[SH2 Icon Test](https://mega.nz/file/ACBXjIDL#kLrv7Io-nPcUYXcgn1oA_Ed-aMR5G4XMbaTdM4l-kMU)

**Comment by Polymega** [comment]
Quick tests and everything seems fine. But I'm not the best to test as the previous iteration (with the icon) also worked for me without problems. Also, for this new executable, I got this Windows warning message:

![image](https://user-images.githubusercontent.com/27395260/98315989-87023380-1fa7-11eb-9655-54ce4bdc42bc.png)

And upon second launch:

![image](https://user-images.githubusercontent.com/27395260/98317121-e3665280-1fa9-11eb-9e2b-4bd3a07b3dd3.png)

...then Windows Defender deleted the executable.

**Comment by AeroWidescreen** [comment]
🤷 I don't know then. Nothing pops up for me, even when I scan it with Windows Defender and Malwarebytes. Did you try the one that [Psycho-A uploaded](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/346#issuecomment-722710997)?

**Comment by Polymega** [comment]
Yeah, sorry man, I don't know what's up either. I haven't gotten around to trying Psycho-A's version yet.
