### ISSUE TITLE
Unable to configure controller

### ISSUE THREAD

**Issue by proshot82** [elishacloud/Silent-Hill-2-Enhancements#347]
In control options menu, i am unable to navigate to "Function" and "Joypad" sections, they are greyed out and don't react to mouse clicks or any keys as far as i can tell, only "Keyboard" section is active. My controller (f710) is connected as i can navigate options menu with it. I just can't access the Joypad menu to reconfigure the controller.

**Comment by AeroWidescreen** [comment]
You can't click on it. You have to scroll down using your dpad or keyboard until you reach "Cycle Target Left", then move to the right to access the Joypad section.

![Options](https://i.imgur.com/Lc25Cd3.png)
