### ISSUE TITLE
Enhanced Edition crashes right after launch (Black Screen)

### ISSUE THREAD

**Issue by StylishDevil** [elishacloud/Silent-Hill-2-Enhancements#348]
I just installed the game. When I try to launch it, I can see a quick yellow loading bar at the bottom. It instantly disappears and my cursor keeps on "loading". I waited for nearly 5 minutes but nothing happened. When I changed tabs and opened the task manager, it says that the game is not responding. I already went through the troubleshooting guide. Any leads on what should I be doing? Maybe I'm doing something wrong?

Here's my specs if they're of any use:

Processor: AMD FX(tm)-8300 Eight-Core Processor            (8 CPUs), ~3.3GHz
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
DirectX Version: DirectX 12
Card name: Radeon(TM) RX 460 Graphics
Ram I own: 8gb

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5528497/d3d8.zip)

**Comment by AeroWidescreen** [comment]
Hi, could you upload your d3d8.**log** file? It should be in the same folder you got d3d8.ini from. Thanks.

**Comment by StylishDevil** [comment]
Sure, here it is.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5532949/d3d8.log)

**Comment by Polymega** [comment]
You are totally missing your `data` folder. [This folder contains all the files the game needs to launch/run.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-is-the-purpose-of-the-sh2e-folder)

I suggest completely deleting all the files in your `Silent Hill 2` folder and starting over. 

After following our installation guide, you want your directory tree to look like this: http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

Also, your log file says you're using the Director's Cut executable, [which is known to be less stable than the North American version.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-occasionally-freezescrashes-as-im-playing) So be sure to use the executable provided on our site as well.

**Comment by StylishDevil** [comment]
Trying random solutions I replaced the enhanced executable with the original one but didn't make any difference. I'll reinstall everything again now and let you know if the data folder is still missing. I have no idea what could have happened to it.

**Comment by Polymega** [comment]
100% it's not running because of the lack of the `data` folder. I was meaning that after you reinstall everything, be sure to use the executable provided on our site as it's more stable than the "no CD" European executable.

**Comment by StylishDevil** [comment]
I was checking the directory tree, after finishing the instalation of the main game I see that some files that are supposed to be in the base game are not there. Should I be using a different version of the game? Or is it okay if I continue with the installation of the enhanced edition on top of the one I have? Here's a pic of my folder. 

The missing files according to the directory tree are:

- cin.dat
- keyconf.dat
- language.ini
- local.fix
- options.ini
- settings.ini
- sh2logo.jpg/SH2DClogo.JPG (I doubt not having this one will be an issue, being just an image)

![](https://cdn.discordapp.com/attachments/776299856167829508/776552845175947314/unknown.png)

**Comment by Polymega** [comment]
You should be fine. The files you listed are created for you by the game after first launching it, so no worries there.

Some examples:

- cin.dat - Stores what FMVs you've unlocked in the game.
- keyconf.dat - Stores keybindings you set in the game's Control Options menu.
- language.ini - Stores what language you have selected/saved in the game's Options menu.
- etc...

**Comment by StylishDevil** [comment]
Alrigh then! Will continue the installation of the enhanced edition. Hopefully the data folder won't disappear this time. When I played it in the past (the regular director's cut edition) you had to launch the game as admin and select afinity to only use 1 core of the processor (or something like that, sorry, my english is not very well regarding these things, pc is in spanish as you could see on the earlier pic). Should I do anything in specific when launching this version of the game for the first time?

**Comment by Polymega** [comment]
> When I played it in the past you had to launch the game as admin and select afinity to only use 1 core of the processor. Should I do anything in specific when launching this version of the game for the first time?

Nope, you no longer need to worry about these types of things. :) We've integrated a feature to [have the game automatically detect if it's needs to run as an administrator](http://enhanced.townofsilenthill.com/SH2/config.htm#CheckForAdminAccess), and also integrated a feature to [have the game run on a single core.](http://enhanced.townofsilenthill.com/SH2/config.htm#SingleCoreAffinity)

[Here's a section on things you'd likely adjust.](http://enhanced.townofsilenthill.com/SH2/config.htm#commonsettings) Basically, chances are, you'll only need to adjust `ResX`, `ResY`, and `EnableWndMode` in the `d3d8.ini` file.

**Comment by StylishDevil** [comment]
Everything seems to be there! And the game opens normally now. Thank you very much!

**Comment by StylishDevil** [comment]
Everything seems to be there! And the game opens normally now. Thank you very much!
