### ISSUE TITLE
Lag and freezes during cutscenes.

### ISSUE THREAD

**Issue by StylishDevil** [elishacloud/Silent-Hill-2-Enhancements#349]
Hello! I'm having issues while playing the video cutscenes either when triggering them or manually watching them from the menu. It doesn't happen with every cutscene, but some in particular. For example, the first cutscene of James looking at himself in the mirror, the one where James meets Laura at the wall and also when James meets María for the first time. The video cutscene lags, but for the second cutscene (the one more gameplay-like) the audio falls a bit behind. 

I'm uploading the d3d8.log file as requested and also pasting my specs if they're of any use. 

Processor: AMD FX(tm)-8300 Eight-Core Processor (8 CPUs), ~3.3GHz
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
DirectX Version: DirectX 12
Card name: Radeon(TM) RX 460 Graphics
Ram I own: 8gb

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5539532/d3d8.log)

**Comment by Polymega** [comment]
Temporarily remove `dsoal-aldrv.dll` and `dsound.dll` from the game's directory and see if the FMVs still lag for you. On the game's main menu, you can select **MOVIES** to quickly test FMV playback there.

**Comment by StylishDevil** [comment]
Sorry for the late reply, I'm moving tomorrow morning and had to pack things up. I'll try that in a bit and let you know if that works.

**Comment by StylishDevil** [comment]
Tested it and it's not lagging anymore. Thank you very much!

**Comment by StylishDevil** [comment]
I won't be able to try it today, but I surely will as soon as possible tomorrow. Will reply later to tell you how that went! Thanks!

**Comment by StylishDevil** [comment]
The new files seem to work fine! No lag at all replaying cutscenes from the menu. Thank you! :)

**Comment by Polymega** [comment]
Thanks for testing! We're running some tests on our end with this updated build as well and, if our tests also go well, we'll update DSOAL on the website.
