### ISSUE TITLE
Add New font

### ISSUE THREAD

**Issue by YouKnow-sys** [elishacloud/Silent-Hill-2-Enhancements#350]
Hi, its not an issues, so sorry if here is wrong place for asking this
I want to translate this game to my native language, for doing this job i need to create a new font for game (i mean create a new font and **add like 300 new character to it**)
my question is its possible to create new font for game?
and other thing after that i can translate ps2 text too? (btw I more interest in translate PS2 version then PC)

I appreciate any help
Thanks

**Comment by Polymega** [comment]
Hello,

There's some other threads here you can read over to get an understanding of how to make a new translation pack. Here are some of them:

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/144
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/234
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/328

I'm not sure you can add an additional 300 characters to the game's character list; I don't imagine that's possible. And our project and the tools you see in those linked threads above are for the PC version of the game.

**Comment by YouKnow-sys** [comment]
> Hello,
> 
> There's some other threads here you can read over to get an understanding of how to make a new translation pack. Here are some of them:
> 
> * #144
> * #234
> * #328
> 
> I'm not sure you can add an additional 300 characters to the game's character list; I don't imagine that's possible. And our project and the tools you see in those linked threads above are for the PC version of the game.

thanks for reply and good information
I want to translate this game into Persian Language
I overdid it on the need for **300** new characters I check it now and I find out I need to add 150 new character
![persian](https://user-images.githubusercontent.com/17937017/99275799-2d202a00-2841-11eb-9062-f357bb52f820.png)
for create font I need to edit character mapping too, because as you see I cant only replace some character with other character, you think its possible?
and if you maybe know, Persian Language use RTL Text-Direction, so I need to make some edit to game texts in order to show correctly in game, SH2 support any kind of line breaker in text file? (I mean like **\n**)

**Comment by Polymega** [comment]
I'll tag @belek666 on this, as he's our subject matter expert with font work for the game. He would be the one to tell you whether or not right-to-left text direction is possible, or if more/new characters can be added.

**Comment by Polymega** [comment]
@YouKnow-sys I'm going to close this ticket as it looks like belek666 may be off GitHub for the time being, unfortunately. I do recommend opening a ticket for this over on his repo for SH2/3 PC fonts in the hopes he may be able to assist there: https://github.com/belek666/fontsh234
