### ISSUE TITLE
Slow Movies

### ISSUE THREAD

**Issue by taraxxx** [elishacloud/Silent-Hill-2-Enhancements#353]
Hi guys, during the normal session ingame i dont have problems but when there is a movie segment the video is so slowdown... what is the problem? i have disabled all the filters in hi res but i dont think is this because its not happening in game but during the movie segments. Can you help me?

**Comment by Polymega** [comment]
Hi taraxxx,

We think this might be caused by DSOAL. The other day we updated this package to hopefully alleviate this issue. Can you download this new version of DSOAL and try the FMVs again? 

http://enhanced.townofsilenthill.com/SH2/install.htm#changelog

Simply replace the files. On the game's main menu, you can select **MOVIES** to quickly test out FMVs.

**Comment by taraxxx** [comment]
Hi,

I did but is the same. I ask you a question: i used this fantastic enhanced game at the beginning of march, now today, checking on the website i saw that since the day i used the game last time 4 updates were release so i thught to install all of it from the oldest to the newest. I did it right or i just had to install the last one (the ine you linked me)?


Can i attach a file to help you?

**Comment by taraxxx** [comment]
other thing: when i start silent hill it tells me that an update is available  but as i said to you i updated all the releases of the project today

**Comment by Polymega** [comment]
> checking on the website i saw that since the day i used the game last time 4 updates were release so i thught to install all of it from the oldest to the newest. I did it right or i just had to install the last one (the ine you linked me)?

Yep! You did things right.

> Can i attach a file to help you?

Yes, please upload a copy of your `d3d8.log` file from the game's directory. Thanks.

**Comment by taraxxx** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5576820/d3d8.log)

**Comment by Polymega** [comment]
Try this first:

**Delete** the following files/folders from the game's directory:

```
\reshade-shaders\
d3d8.dat
d3d8.dll.deleteonnextlaunch
d3d9.dll
d3d9.log
dsound.log
ReShade.ini
ReShade_sh2pc.ini
```

See if that fixes FMV playback.

**Comment by taraxxx** [comment]
Wait a sec, i solved it maybe. I have a all in one pc and it has two graphic card, 1 the integrated intel hd 560 and the other nvidia geforce GTX950M . Opening my control panel nvidia i discovered that windows was managing the choice of which graphic card to use case by case. Usually it is smart and for games it uses nvidia but this time he was using my integrated intel card so for this reason the movies was slow... now the game is more smoother too. Damn Windows! . Tomorrow i'll continue the game and if it continues to give me problems I'll let you know. Thank so much for the fast answer. I really appreciated man.

**Comment by Polymega** [comment]
Ah! Yeah, integrated graphics can do that. Nice catch with that and having SH2 PC run off your Nvidia card now. That will also help with the HD fonts and other things.

You should still remove those files and folders I mentioned, as they are no longer needed/used with the latest updates to the project.

**Comment by taraxxx** [comment]
Oh ok, are you sure that if i delete that folder and the others files i can continue to play and im gonna have a crash right? :P

**Comment by Polymega** [comment]
Yes, they are no longer needed/used with the latest updates to the project.

**Comment by taraxxx** [comment]
Ok perfect. Considering that you are so kind I'll ask you another thing: why they  never thought to do this fantastic job on silent hill 1?

**Comment by Polymega** [comment]
SH1 never came to PC; it's a PS1 exclusive game. It can be played on a PS1 emulator through PC, though.

I'll close out this ticket since the FMV issue is resolved. I'm glad you figured it out. :)

**Comment by taraxxx** [comment]
Thank you again :)

**Comment by Polymega** [comment]
I included something for this on the troubleshooting page, in hopes it may help others with your same situation:
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general
