### ISSUE TITLE
First Person Camera

### ISSUE THREAD

**Issue by Rainnvod** [elishacloud/Silent-Hill-2-Enhancements#354]
Are you planning to create a first person camera?

**Comment by Polymega** [comment]
We have no plans to do so. SH fan and modder Nekorun has made a first person camera for the PS2 version via PCSX2. You can view a video of it in action here: https://www.youtube.com/watch?v=iWZr0q6zCpI

You can try and ask Nekorun if he'd share his first person tool with you by reaching out to him here: https://twitter.com/NekorunUltimax
