### ISSUE TITLE
Any chance of proper Keyboard and Mouse support in the future?

### ISSUE THREAD

**Issue by themanwiththeplan911** [elishacloud/Silent-Hill-2-Enhancements#356]
Hi, love the project & the sweat and effort you put into it is just pure dedication. I'd like to request/talk about one feature that not many PS2 to PC port got right at the time - keyboard and mouse. I'll get straight to it is it feasible to implement without any source code? Here's a quick mock-up I did of how I imagine it could look.
![layout](https://user-images.githubusercontent.com/75482550/101364731-8eb93e80-38ab-11eb-991c-8c58e89b68ab.jpg)

Let me know what you think. 
Thanks for the mod again!

**Comment by Polymega** [comment]
Hi there,

Good suggestions! Minus the mouse controls as seen in your diagram, all of SH2's keybinds can be changed on the keyboard (through the Options > Control Options menu).

Team member Silent has expressed interest in trying to give the game some form of mouse support. This would entail what you described (similar to SH3 PC):

**Left click:** Action/confirm
**Right click:** Back/cancel
**Mouse movement:** Search camera control/character turning
(The game auto aims when pressing the action button near an enemy with a weapon equipped.)

However, there's no guarantee if/when Silent will get around to looking into this. But rest assured it's something he's aware of as something to possibly explore down the line.

**Comment by Polymega** [comment]
We have added full mouse support to the game/project now! All game functions can already be remapped to the keyboard, so closing this as resolved.

Thanks
