### ISSUE TITLE
d3d8to9 freezes game

### ISSUE THREAD

**Issue by SlowJones** [elishacloud/Silent-Hill-2-Enhancements#36]
hey, great work and thanks on the enhancements. everything works perfectly fine for me other than when activating d3d8to9. the game runs fine without it enabled, but doesnt even launch with it enabled. i copied the necessary files from the wined3d zip. any idea how i can fix this?

**Comment by Polymega** [comment]
Hi @SlowJones ,
To confirm: You have an Nvidia GPU? Also, are you using version 1.7.52 of WineD3D?

**Comment by SlowJones** [comment]
thanks for the fast reply. yes, i have a gtx 750 ti and i'm also using 1.7.52 for wind3d

![image](https://user-images.githubusercontent.com/42977564/45048087-da4c6480-b072-11e8-9f0f-e21fa25291b0.png)

doesnt give me any specifics when it crashes, just the plain old default crash. i tried waiting for around 2 minutes and it still wasn't responding

![image](https://user-images.githubusercontent.com/42977564/45048214-39aa7480-b073-11e8-8503-e21512c13ce9.png)

here is also what my silent hill 2 folder looks like

**Comment by SlowJones** [comment]
the d3d8to9 command worked previous to the latest enhanced edition updates, if that helps narrow down the problem

**Comment by Polymega** [comment]
Thanks for the info. Have you tried installing the DirectX 9 SDK? If your PC doesn't have this installed and you try to use d3d8to9 it won't run: 
https://www.microsoft.com/download/details.aspx?id=35

**Comment by SlowJones** [comment]
unfortunately, that isnt the issue. still gives me the same crash after updating

**Comment by Polymega** [comment]
Try these things next: 

1. Temporarily remove `dsound.dll` from the directory. Does the game launch now? 

If not, then try: 

2. Temporarily remove `d3d9.dll`, `libwine.dll`, and `wined3d.dll` from the directory but keep `d3d8to9 = 1` **enabled** in the `d3d8.ini` file. Does the game launch now?

**Comment by Polymega** [comment]
Okay, this tells us it's not d3d8to9 causing the issue but WineD3D. We had another person experience the same issue with the same Nvidia card. Unfortunately, for right now, we don't have a solution for this. I apologise. 

However, our next goal is to fix what WineD3D fixes without having to actually use WineD3D. This is because out of all the fixes, WineD3D is what causes people the most trouble. If you don't mind waiting a little while we hope to have this addressed sometime soon.

**Comment by SlowJones** [comment]
thats perfectly fine, i understand it isnt your fault. i look forward to this issue being resolved.

i just tried testing out deleting all of the 3 dll files except one and any combination of 2 of them then running the game, and the game launched each time. only when all 3 files are present is when it crashes, if that narrows anything. i'll continue to tinker around and see if im able to get anywhere

**Comment by MilkManEX** [comment]
@Polymega 
WineD3D is only being used to fix like a handful of white shader issues, right?

**Comment by Polymega** [comment]
Yes, it fixes three Nvidia-specific things for the game found here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/10

**Comment by elishacloud** [comment]
@MilkManEX, I just added a fix for the white shader issue.  You can download it here:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2408422/d3d8.zip)

**Comment by elishacloud** [comment]
Closing out this issue since this is related to WineD3D and the WineD3D issues are covered in #10.

**Comment by lu1291** [comment]
After some time and dll tests, i think i found a solution. You have to download a brand 32bit d3d9.dll and paste into game folder and the game will open normally.

Here's the site: https://pt.dll-files.com/d3d9.dll.html.
