### ISSUE TITLE
Black screen freeze - MacBook Pro 16 Bootcamp Windows 10

### ISSUE THREAD

**Issue by shinshichirou** [elishacloud/Silent-Hill-2-Enhancements#360]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5745337/d3d8.log)

hello, I need some help to make game running on MacBook Pro 16 with Windows 10 (installed with Bootcamp)

the game doesn't show anything regarding loading indicators from reshade, just black screen

hope log file can show what is wrong here

thanks

**Comment by shinshichirou** [comment]
btw, tried different versions of game and didn't manage to make any of them to work, even without EE it does not run, not sure why, could it be high dpi internal display?

**Comment by shinshichirou** [comment]
Specs:
MacBookPro16,1
Intel(R) Core(TM) i9-9880H CPU 
AMD Radeon Pro 5500M 4Gb
DirectX:  27.20.14501.28009
Native resolution: 3072 x 1920
Ram: 16GB

**Comment by shinshichirou** [comment]
Also if making Alt-Tab and then go back to game i get the same message as in issue Silent Hill 2 Enhanced Edition Not Responding #326

**Comment by elishacloud** [comment]
Try renaming or removing the `dsound.dll` file.

**Comment by bluewool37** [comment]
I have the same problem and also on MacBook BootCamp Windows 10.

**Comment by bluewool37** [comment]
> Try renaming or removing the `dsound.dll` file.

This does not work.
