### ISSUE TITLE
No Widescreen in macOS Mojave with Wine

### ISSUE THREAD

**Issue by gustavopi** [elishacloud/Silent-Hill-2-Enhancements#361]
Silent Hill 2 runs fine in Mac with macOS 10.14.6 with Wine 5.0, both original Director's Cut and the EE. But the image is always 3:4. I tried to change d3d8.ini settings but nothing changes, it will be always in fullscreen mode with de definition set by the game. What I can do is change graphic definitions inside the game, in options, put all to maximum/best/on and than I have a nice image, but 3:4 fullscreen.
Will be nice to fix this, Mac users will be able to play it with no need of booting in Windows.

**Comment by elishacloud** [comment]
Are you getting a `d3d8.log` file generated?  I assume that the game is not loading the `d3d8.dll` module in.  With Wine you need to change the load order to make sure that the game loads the local copy of `d3d8.dll` rather than the Wine version of the dll.
