### ISSUE TITLE
Addendum for `RoomLightingFix`

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#362]
Hi Elisha,

An addition to [LightingPatch](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/LightingPatch.cpp) (`RoomLightingFix`), this fixes lighting levels for outdoor areas that would be incorrect if you load directly back into them. This is due to these areas relying on the previous rooms' levels to know what to set themselves to. 

`0089FFC0 (float) - Room levels based on flashlight state` is a new address to the project. 

--------------
   
- If [`ChapterID == 0x01 // side campaign`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L262-L267) ([example being used](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Wrappers/d3d8/IDirect3DDevice8.cpp#L518))
   - If `Room ID =  0x08 (Town West)` || `0xD3 (Mansion outside main entrance)`
      - Set `0089FFC0` to `1.0f`
   - ElseIf `Room ID =  0xD4 (Mansion outside guest entrance)`
      - Set `0089FFC0` to `0.0f`
- Else `// main campaign`
   - If `Room ID = 0x04 (Wood Side outside entrance)` || `0x07 (Wood Side courtyard)` || `0x08 (Town West)` ||  `0x0E (Lake)`
      - Set `0089FFC0` to `0.0f`

--------------

For `0089FFC0`, have it set to run a single time on each of these Room ID checks. aka: run once, no constant checks for each Room ID load.

Thank you

![001](https://user-images.githubusercontent.com/27395260/103489365-18442980-4de2-11eb-8dfc-28eebc3ea444.gif)
![002](https://user-images.githubusercontent.com/27395260/103489366-1a0ded00-4de2-11eb-8fb3-efdbc96b0d02.gif)

**Comment by elishacloud** [comment]
Implemented in the latest testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5985821/d3d8.zip)

**Comment by Polymega** [comment]
Thanks for looking into this. Tried the test build and it doesn't seem to be working. The float values for `0089FFC0 float` aren't changing on the room ID loads.

**Comment by elishacloud** [comment]
Ok, I was wondering about that.  I change the float values for `0089FFC0` on the first frame when entering the room.  It is possible that I update it too soon.  I am going to try and update it on the second frame.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5985895/d3d8.zip)

**Comment by Polymega** [comment]
Nice. Seems to be working well with both 30 and 60 fps. Thank you!
