### ISSUE TITLE
Resolution not changing

### ISSUE THREAD

**Issue by AmnesticsNotFound** [elishacloud/Silent-Hill-2-Enhancements#363]
Title sums it up. The resolution isn't updating at all, tried setting it to read only, but to no avail. Help would be appreciated.

![Screenshot (47)](https://user-images.githubusercontent.com/50062894/104522728-10e00580-55c4-11eb-8ff4-3148759a997c.png)

**Comment by Polymega** [comment]
None of the files are in the right spot. You want your directory tree to look like this: http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

Most of the steps when downloading the packages will say:
> zip the download package and move the contents within the Silent Hill 2 folder from the download to <path-to-game>\Silent Hill 2\.
