### ISSUE TITLE
Blue Creek Map Mistake

### ISSUE THREAD

**Issue by meatball76** [elishacloud/Silent-Hill-2-Enhancements#366]
Hi,
The remade map for the 2F Blue Creek Apartment buildings shows an extra door to Room 201 which doesn't exist in-game and doesn't appear on the original PC map (I haven't checked PS2 but I doubt it's different). I haven't seen any other mistakes on the maps, but I'm not that far into my current playthrough; Might be a good idea to do another double check though.
New Image:
![new map](https://user-images.githubusercontent.com/77625634/104925421-aaf0d680-5953-11eb-8d87-1b68baf84f8b.png)
Old image from a 2011 YT let's play for comparison:
![old map](https://user-images.githubusercontent.com/77625634/104925429-adebc700-5953-11eb-9387-c0860e82328d.png)

**Comment by Polymega** [comment]
Oh my. 😱 Thank you for catching this! I can't believe this slipped by me. There's a future planned update for the Image Enhancement Pack that will be released with our next project update, and I'll be sure to include this fix with it. Thanks again.

**Comment by AeroWidescreen** [comment]
I'm surprised I missed this during my playtesting. I made sure to check every door, room, and barricade to see how it correlates with the map. I guess this one slipped by me as well. Good eye.

**Comment by Polymega** [comment]
That extra door is in the same spot on the third floor of Blue Creek as well.  must've accidentally pasted the door barrier here while working on this file. I've corrected it for the next project update now:

![Screenshot 2021-01-19 13-33-17](https://user-images.githubusercontent.com/27395260/105077837-15d90500-5a5b-11eb-8ff8-91a527941455.png)
