### ISSUE TITLE
Xbox Series X Controller Triggers Not Detected

### ISSUE THREAD

**Issue by mbushnaq00** [elishacloud/Silent-Hill-2-Enhancements#367]
Nothing happens when pressing the RT and LT triggers in-game. Also I am unable to map the triggers in the Joypad settings menu as it seems that it's not being detected.

**Comment by Polymega** [comment]
You'll need to have XInput Plus installed in order to use the triggers of Xbox controllers with SH2 PC. Make sure you have this package downloaded and installed: http://enhanced.townofsilenthill.com/SH2/install.htm#controllerSetup

**Comment by mbushnaq00** [comment]
I already have Xinput plus installed, and the Xbox one controller used to work perfectly, however as I mentioned, the Xbox Series X controller seems to have a compatibility issue with the game since the triggers are not detected.

**Comment by Polymega** [comment]
I don't have a XSX controller at hand for testing (and none of my friends purchased an XSX either), so I'm not sure when I'll be able to look into this, unfortunately.

**Comment by mbushnaq00** [comment]
thanks for the response anyways

**Comment by Polymega** [comment]
For future reference whenever I can test: Do you have the controller connected to your computer through a wire (USB) or are you using Bluetooth or a wireless dongle?

**Comment by Polymega** [comment]
Follow-up to my question for you earlier: I've heard reports today that the DS4's and DualSense's triggers work when connected via wired, but no longer work when connected to a PC via Bluetooth. If you're using your XSX controller wirelessly, that may be the reason why.

**Comment by mbushnaq00** [comment]
> Follow-up to my question for you earlier: I've heard reports today that the DS4's and DualSense's triggers work when connected via wired, but do not work when connected to a PC via Bluetooth. If you're using your XSX controller wirelessly, that may be the reason why.

I found a workaround, basically, the game needs to be added to steam, then through steam big picture, Xbox Controller configuration needs to be enabled in settings. After which open the controller configuration of the game in steam and browse configs, you will find someone in the community who already has a config made similar to the PS2 controls, choose that and the triggers should work.

**Comment by Polymega** [comment]
Good to hear! So it sounds like, without the use of something like Steam, trigger inputs aren't being detected when using the controller wirelessly.
