### ISSUE TITLE
So, my game now looks like this...

### ISSUE THREAD

**Issue by JavierJirafa** [elishacloud/Silent-Hill-2-Enhancements#37]
I don't know what did I make wrong, help me please.
![ssue 1](https://user-images.githubusercontent.com/42982172/45056995-702bc380-b062-11e8-83f0-753e3e43e468.PNG)
![ssue 2](https://user-images.githubusercontent.com/42982172/45056997-702bc380-b062-11e8-9643-e38abe83772d.PNG)
![ssue 3](https://user-images.githubusercontent.com/42982172/45056998-70c45a00-b062-11e8-8421-0c4bf2d08b1f.PNG)
![ssue 4](https://user-images.githubusercontent.com/42982172/45056999-70c45a00-b062-11e8-9212-315331474766.PNG)
![ssue 5](https://user-images.githubusercontent.com/42982172/45057001-70c45a00-b062-11e8-80e7-aa6f34cf19d3.PNG)

**Comment by Polymega** [comment]
Hi @JavierJirafa ,

If you temporarily remove `d3d9.dll`, `libwine.dll`, and `wined3d.dll` from the directory does this fix the issue?

**Comment by JavierJirafa** [comment]
@Polymega That worked!! Thank you so much!! Now it looks like this, is it ok?
![4cap](https://user-images.githubusercontent.com/42982172/45063828-2c46b780-b07e-11e8-91a8-cfdb6915933a.PNG)
![1cap](https://user-images.githubusercontent.com/42982172/45063829-2c46b780-b07e-11e8-9280-b7825db126ac.PNG)
![2cap](https://user-images.githubusercontent.com/42982172/45063830-2cdf4e00-b07e-11e8-83a3-283be864ba7f.PNG)
![3cap](https://user-images.githubusercontent.com/42982172/45063831-2cdf4e00-b07e-11e8-9caf-dc70ff19180f.PNG)

**Comment by Polymega** [comment]
Okay, so this is an issue with WineD3D then. 

Can you tell me what graphics card you are using? Nvidia? AMD/ATI? Something else?

> Now it looks like this, is it ok?

Good! You will also want to go to the game's Options menu and **enable** High Resolution Textures for the best results: 

![sh2pc 2018-09-04 20-22-25](https://user-images.githubusercontent.com/27395260/45064186-5ac59200-b080-11e8-89f5-3af2285f8b60.png)

**Comment by JavierJirafa** [comment]
@Polymega I'm using intel core i5, hahaha.

**Comment by Polymega** [comment]
Okay, this is why. You should not use WineD3D unless it is with an Nvidia graphics card. Using WineD3D with integrated (Intel) graphics can result in issues such as what you experienced... or the game not running at all. 

By chance, did you follow this install video? https://www.youtube.com/watch?v=fFVwI487ORo

**Comment by Polymega** [comment]
Thanks for the info and I'm glad you have it working now!

**Comment by JavierJirafa** [comment]
@Polymega  Thank you for your help!! This mod is awesome, I hope you make more for other games!!

**Comment by elishacloud** [comment]
This issue has been resolved.  Closing.
