### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by DracoCW** [elishacloud/Silent-Hill-2-Enhancements#371]
When I try to start Silent Hill 2 it immediately crashes with an error (0xc0000005). This happens as soon as I put the d3d8 - files into the SH2 folder. If I remove the d3d8.dll the game starts. Setting d3d8to9 = 0 does not help either. I have nothing else installed from the enhancements except the sh2pc.exe and the d3d8 - files.

In addition I get a 404 error, when I try to download the DirectX 9 SDK you linked in the installation guide. I installed the Windows SDK, but this does not help either. I would like to add the d3d8.log, but no such file can be found on my system.

**Comment by Polymega** [comment]
Can you provide a snapshot of the game's installation directory? [Are all the files that are installed with the vanilla game accounted for?](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

> In addition I get a 404 error, when I try to download the DirectX 9 SDK you linked

@elishacloud it may just be a temporary site issue, but it looks like Microsoft recently removed this package: https://www.microsoft.com/download/details.aspx?id=35

I'm not sure what's going on here...

**Comment by Polymega** [comment]
It's looking like Microsoft's Download Center might be down at the moment, as the whole site is behaving a little odd. At least, I hope that's all it is.

Anyway, @DracoCW, can you right click `sh2pc.exe`, select **Properties**, go to the **Compatibility** tab, and ensure all compatibility settings are turned off/disabled.

Also double-check the game's installation directory files. If you downloaded the game from somewhere on the internet, there's a chance it includes extra, foreign files that might be conflicting with our project files (such as the `d3d8` files).

**Comment by DracoCW** [comment]
Holy cow! Turning off the compatibility settings worked! Thank you @Polymega for this tip, now I can try to play SH2 in the enhanced edition :)
I was already writing about how I have the original 3 cd version and that the install is basically vanilla SH2 and I made screenshots of the folder structure. But that is all not important anymore, it works now :)

**Comment by Polymega** [comment]
Great! Glad we were able to figure that out.

As for the DirectX 9 SDK download being taken down: I'll talk with Elisha about that to determine what we should do.
