### ISSUE TITLE
Graphics tone down after first launch?

### ISSUE THREAD

**Issue by Hauhnter** [elishacloud/Silent-Hill-2-Enhancements#372]
Hello! I recently downloaded the Enhanced Edition and I got it all installed and launched it and it looked beautiful, after I got off and relaunched the game the graphics toned down alot (I noticed the resolution reset as well) I did change the resolution back to 1920x1080 but the game is not the same as the first launch it looks entirely different...I did uninstall it once already because I thought I didn't follow the instructions for the mods right, but it happened again the second time the same way (after first launch), If I could get some help that would be great :) ty!

**Comment by Polymega** [comment]
Hi there,

Can you please attach a copy of your `d3d8.log` file?

In the meantime, try this for me:

 - Right click `sh2pc.exe`
 - Select **Properties**
 - Go to the **Compatibility** tab
 - Ensure all compatibility settings are turned off/disabled

**Comment by Hauhnter** [comment]
Hi, I checked and all options under Compatibility are turned off. 
This is my log!

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5892203/d3d8.log)

**Comment by Polymega** [comment]
I believe we've had tickets similar to this where an unorthodox solution was used. Try this for me:

- Make a copy of `sh2pc.exe` and rename this copy to something like `sh2pc_ee.exe`
- Then launch the game through `sh2pc_ee.exe` and see if that fixes the issues you were experiencing.

**Comment by Hauhnter** [comment]
That method fixed it, thank you @Polymega !

**Comment by elishacloud** [comment]
I suspect that this was the issue:

```txt
11596 02:22:07.984 Environment variable __COMPAT_LAYER = "640X480 Installer"
```

It looks like you were running in 640x480 resolution.

I ran a quick test and that means that the following compatibility setting was enabled:

![image](https://user-images.githubusercontent.com/25625456/106245739-d2e90100-61c1-11eb-96f4-2fe872f637a1.png)

It was probably set for "all users".  If you rename it back to `sh2pc.exe` you can remove this by right clicking `sh2pc.exe`, select **Properties**, go to the **Compatibility** tab, and ensure all compatibility settings are turned off/disabled.  Then click the **Change settings for all users** button and ensure all compatibility settings are turned off/disabled on this page also.

**Comment by Polymega** [comment]
Nice one, Elisha! Please try his suggestion @Hauhnter: Go back to `sh2pc.exe` and also ensure **Change settings for all users** is selected after disabling the compatibility options.

Ideally it would good to continue launching the game through `sh2pc.exe` instead.

**Comment by Hauhnter** [comment]
@Polymega @elishacloud I did check under Compatibility and the settings for all users and ALL options are disabled even the "Run in 640 x 480 resolution" and the problem still persists with sh2pc.exe...so I'm not entirely sure why it was running in that resolution, is there something else that could be activating compatibility mode?

**Comment by AeroWidescreen** [comment]
I remember someone else having this problem, and indeed, disabling compatibility mode didn't work either. They had to rename the exe.

Something must've went wrong, because I don't remember anyone reporting this issue prior to the last update.

**Comment by elishacloud** [comment]
@Hauhnter, I created a quick build to remove the unsupported compatibility mode options automatically.  Can you test with this update?

You may need to run the game more than once for the full test.  The first run will attempt to remove the unsupported compatibility options.  The second run should load normally.  Please upload log files after the second run and let us know what the results are.

Here is the test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5897515/d3d8.zip)

**Comment by Hauhnter** [comment]
@elishacloud I tested it three times and now sh2pc.exe seems to run correctly without changes in the resolution and such.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5897529/d3d8.log)

**Comment by elishacloud** [comment]
Thanks for your quick response.  I am glad it is working now.  However, I am not sure why this is still seen in the log:

```txt
13404 02:12:18.424 Environment variable __COMPAT_LAYER = "640X480 Installer"
```

**Comment by Hauhnter** [comment]
@elishacloud Not sure, was going to mention I found when I run the game without administrator the part where it asks for permissions is in shitty resolution but the game runs perfect, when I run it with administrator the game reverts to the Compatibility resolution, sorry if I explained that bad.

**Comment by elishacloud** [comment]
It should be running with administrator rights because it is running under the `Program Files` folder.  It looks like everything is good now.

**Comment by Polymega** [comment]
Wanted to mention that I ran a test with the new test build enabling these settings:

![image](https://user-images.githubusercontent.com/27395260/106362957-ab925100-62f3-11eb-97f7-45e8e71813b3.png)

And it launch four instances of the game at once.

**Comment by elishacloud** [comment]
That was a testing build.  I added a bunch of other checks in the latest build.  This build should be more stable.

Here is the latest build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5898598/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha. Everything seems fine with my tests using this build as well. 

Oh, and as a safety/redundancy thing, I also added something on the site about the error code people received (it is due to enabling compatibility mode such as Win XP SP 2), so we can reference/link that as well now: 
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-crashes-and-i-receive-an-error-code-upon-launch

**Comment by mirh** [comment]
The game is pretty old and saves to its own installation folder.. But can't you just re-route files to the proper user directories?
I mean, it would hardly be the craziest hack you made here.

**Comment by Polymega** [comment]
Thanks for your great work here, Elisha. I'll close this ticket out.
