### ISSUE TITLE
Print Screen screenshots create transparent pngs.

### ISSUE THREAD

**Issue by levonnn** [elishacloud/Silent-Hill-2-Enhancements#375]
Tried to save a screenshot via Print Screen key. The file in imgs folder is png with just a transparent layer. I used 640x480 fullscreen mode.

**Comment by Polymega** [comment]
It appears to be an issue when running the game in fullscreen mode. Playing in windowed the image is captured correctly.

**Comment by levonnn** [comment]
Tried it out. Indeed windowed mode works.

**Comment by elishacloud** [comment]
Try this build.  I switched from using the front buffer to using the back buffer for screenshots:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5907545/d3d8.zip)

Note: this will NOT be in the upcoming hotfix.  It is too risky at this point.  However, this build has all the hotfix updates.  So if anyone has this issue they can use this build.

**Comment by levonnn** [comment]
Yes, it works with the new build.
