### ISSUE TITLE
Menu highlight.

### ISSUE THREAD

**Issue by levonnn** [elishacloud/Silent-Hill-2-Enhancements#376]
Sorry if it was reported.

PS2
![gsdx_20210202092553](https://user-images.githubusercontent.com/46363559/106556680-18465f00-6531-11eb-8640-bee19bd126e1.png)

PC
![Screenshot 2021-02-01 23-15-07](https://user-images.githubusercontent.com/46363559/106556686-1a102280-6531-11eb-98a8-44e32f7b27f0.png)

**Comment by elishacloud** [comment]
Here is what it looks like with the latest update in low res.  Looks great to me:
![Screenshot 2021-02-15 11-00-35](https://user-images.githubusercontent.com/25625456/107984578-0e831980-6f7d-11eb-85ea-4f9f7325dcf5.png)

**Comment by levonnn** [comment]
It's not the original menu, though.

**Comment by elishacloud** [comment]
Correct.  It is not the original PC menu.  If you want to go back to the original PC menu you can just delete all the files `start0*.*` files from the `sh2e\pic\etc` folder.  Then the game will just use the original PC menu.

**Comment by levonnn** [comment]
My mistake. I thought you're working on fixing issues with the PC version of Silent Hill 2.

**Comment by elishacloud** [comment]
We have been putting many fixes into the PC version of Silent Hill 2.  We probably won't be able to fix every issue in the PC version since for some the cost vs. severity may not be worth fixing.  However, with this update the PC version should play as good or better than the PS2 version in almost every way.

We are not trying to make the PC version identical to the PS2 version.  Instead, we are taking the best things of the PS2 and making them better.  For graphics, better means using a high resolution 2048x2048 (or higher) source graphics for this, rather than using low resolution 512x512 (or lower) textures.

Some users have nostalgia for the PS2 version of this game and want the PC version to look and play exactly like the PS2 version.  These users may not be the right users for this project.  For these users, PCSX2 may be a better option.  We are making an HD version of this game like the Silent Hill 2 HD version should have been.

I hope that helps explain what we are doing with this project here.

**Comment by levonnn** [comment]
It's not nostalgia. It's the way the game was built. SH2 belongs to it's time. It was released in 2001 with everything that comes along with that time - low resolution, low-res textures etc. One thing is adapting it to the modern tech: making it work on modern systems and keeping it's aesthetic appearance (in significant part dictated by technology of the era), while fixing bugs of bad ports. Limited tech played it's part in the way the game looks. It means they had limited poly count at their disposal and models look the way they are, and no amount of higher resolution or 4K textures will make them look better. If anything, higher resolution only exposes imperfections and cubic 2 decades old geometry. Grainy, dirty look of low-res image helped to conceal all that stuff. Fog grew out of tech. limitations of the era as well. Because limited processing power didn't allow good viewing distance etc.

No disrespect, but all this stuff belongs to modding. It's like trying to remove grain from film print, because "it doesn't look digital and smooth enough and modern enough with all those dancing dots on screen". Nevermind it turns image into wax and destroys the media it was created with. "Better" is subjective. What's better for you isn't better for the other guy. There's objective reality though - the game was created for PS2 and released as it was. And in that form it became part of history. People hated the ports not because they lacked hi-res assets. They were buggy and messy releases. And I reported this bug as I think it's also worth fixing, not replacing it with a different assets completely.

**Comment by Polymega** [comment]
> "Better" is subjective. What's better for you isn't better for the other guy. There's objective reality though - the game was created for PS2 and released as it was. And in that form it became part of history.

I too suggest playing the original PS2 game on original hardware using a CRT television, or the PCSX2 version. I've said in another thread we're not aiming to make a 1:1 recreation of the original PS2 game, but instead are giving people the HD Collection we never got. And the majority are happy with our efforts. We can't please everyone, but we seem to be pleasing most, and that's what we'll go for. If you want to play this game on PC, then PCSX2 sounds like the best choice for you. There are options to play the PS2 version untouched.

**Comment by elishacloud** [comment]
> If anything, higher resolution only exposes imperfections and cubic 2 decades old geometry. Grainy, dirty look of low-res image helped to conceal all that stuff.

I am not a graphics artist so I could be missing something, but I don't see any imperfections in our new menu highlight.

> I reported this bug as I think it's also worth fixing, not replacing it with a different assets completely.

Other than not looking exactly like the PS2 version, can you give more details on specifically what the issue is here with the new menu highlight?  What are the issues that are exposed with this higher resolution image?

**Comment by levonnn** [comment]
> I am not a graphics artist so I could be missing something, but I don't see any imperfections in our new menu highlight.

New menu is nice. The only problem it's not made by the devs who made SH2. It's not the original asset. So for people who want the original experience it's worthless, even if done well.

> Other than not looking exactly like the PS2 version, can you give more details on specifically what the issue is here with the new menu highlight? What are the issues that are exposed with this higher resolution image?

The new menu is made for high resolution. It looks fine. But it's not the original asset. The original asset is made for much lower resolution, so it doesn't look good in hi res. And I absolutely get the idea of replacing low-res renders with better still images because of this very reason. The issue is for purist guys like me it's still a mod. It's not the original experience. And on top of that, if in case of pre-rendered stuff it's possible to improve quality to modern standards, it's impossible to do with 3D assets. So it's inconsistent AF. Here we have hi-res images, the rest of the game looks like it was made 20 years ago. Even if we plaster hi-res upscaled textures on the old models.

**Comment by elishacloud** [comment]
> The only problem it's not made by the devs who made SH2. It's not the original asset. So for people who want the original experience it's worthless, even if done well.

Agreed.  However, that is not the direction that we have chosen to go.  If someone wants to use the original PC assets they can just delete the asset files from the `she2` folder and still use our update to get all the other fixes.  If they want to use the original PS2 assets then they can use PCSX2 for that.

> on top of that, if in case of pre-rendered stuff it's possible to improve quality to modern standards, it's impossible to do with 3D assets. So it's inconsistent AF. Here we have hi-res images, the rest of the game looks like it was made 20 years ago. Even if we plaster hi-res upscaled textures on the old models.

Yes, I agree with you here.  But there are many people that like to have the hi-res graphics.  Our project is open source and I would be happy if you, or someone else, wanted to take what we have done and add all the original PS2 assets to it.  I would be willing to work with them at this task.  But that is not what this particular project is about.

**Comment by levonnn** [comment]
Hopefully it won't take another 20 years for PCSX2 team to make SH2 bug free.

**Comment by elishacloud** [comment]
LOL.  Yeah, PCSX2 is not perfect yet.  But they have done some amazing things!
