### ISSUE TITLE
still some problems

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [elishacloud/Silent-Hill-2-Enhancements#382]
just some issues I encountered after playing with the latest patch. if they're already known, I apologize.

-strong shadow-flickering with driver-based AA enabled
-lip-sync-errors
-James does a weird jig while quick-turning
-James's character-shadow jumps noticably from front to back or vice versa in the entrance and stairwell of the Wood-Side-Apt-complex (don't remember if that is inherent to the PS2-version as well...)

running on Win10, Ryzen 5 3600+5700 XT

**Comment by Polymega** [comment]
Hello,

I think the issues you mentioned are inherent (normal) behaviors for the game.

1. Chances are, [you're seeing this type of behavior?](https://youtu.be/APW9Rpgj5FI) (Footage taken from PS2 version.) That's normal behavior. Shadow logic wasn't perfect with the game.
2. Yeah, lip syncing was never stellar with the game, either. Expect lip syncing to be either slightly off or completely off for any given spoken dialogue. We haven't cracked the lip syncing files, so don't expect much to be done for this. I'm not sure if we'll ever address the lip syncing.
3. Not sure what you mean about the jig, but likely part of his normal animation for the quick-turn.
4. This goes back to shadow behavior for the game. [I go into more detail about this here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/120)

**Comment by TommvinHuwaltzky** [comment]
heya, thanks for answering!

1. nope, it only happens when I turn on AA in my Radeon-settings. downsampling works fine, so I play at 2880p with your SMAA-shader enabled. but would help if it'd work, since streaming in that resolution is... well..... ^^"
2. ah ok, nvm then. just didn't know if it's a flaw of the PC-version or "normal" behavior.
3. well he kinda tap-dances and swings his foot around weirdly. has always been like that in the PC-version though. no idea about PS2.
4. hm, maybe I oughta try to actualy record some stuff so that I can exemplify what I'm talking about... would maybe help a bit, hehe.........

**Comment by Polymega** [comment]
Footage would probably help for the shadow flickering you mention. (All my PCs use Nvidia, and it might be an AMD-specific type of thing.)

For the shadow jumping in Wood Side and elsewhere, that probably is "normal" behavior. That same type of shadow jump happens as you're walking through the second flight of stairs in the main lobby. Here's an example from the PS2 version: https://youtu.be/DlmOMTAfBBk

**Comment by TommvinHuwaltzky** [comment]
ok, recorded some stuff.
for the shadow-jumping:
https://s2.gifyu.com/images/sh2pc_2021_02_11_18_58_50_212.gif
https://s2.gifyu.com/images/sh2pc_2021_02_11_18_59_07_979.gif

shadow-flickering bc of AMD-AA:
https://s2.gifyu.com/images/sh2pc_2021_02_11_19_31_28_633.gif
https://s2.gifyu.com/images/sh2pc_2021_02_11_19_31_56_133.gif
https://s2.gifyu.com/images/sh2pc_2021_02_11_19_32_40_300.gif

**Comment by Polymega** [comment]
> for the shadow-jumping:

This is normal behavior. You can see it happening on the PS2 version is the video I linked above this post. Also mentioned how it happens on the second flight of stairs in the main lobby.

> shadow-flickering bc of AMD-AA:

That's definitely a bug. 

> nope, it only happens when I turn on AA in my Radeon-settings. they rapidly flicker in and out of existence, so to speak. downsampling works fine, so I play at 2880p with your SMAA-shader enabled.

@AeroWidescreen do you enable AA through your AMD card for the game? Experience anything similar?

**Comment by TommvinHuwaltzky** [comment]
> This is normal behavior. 

ah ok, then that's settled.

> That's definitely a bug.

well, since Radeons are not widely spread it seems... but at least the transition-bug is gone as of the first RDNA...

**Comment by AeroWidescreen** [comment]
> Do you enable AA through your AMD card for the game? Experience anything similar?

I'm not sure what he means by "AMD-AA", but I tried MSAA, Adaptive MSAA, SSAA, and MLAA. No problems on my end.  1920x1080, driver version 21.2.1.
![shadows](https://i.imgur.com/TvkilfF.gif)

**Comment by TommvinHuwaltzky** [comment]
> I'm not sure what he means by "AMD-AA"

well, "AMD-Anti-Aliasing". the AA you activate through Radeon-Software.

MLAA btw does nothing, and "MSAA, Adaptive MSAA, SSAA" all cause the glitch. 
I am still on version 21.1.1. will try the new 21.2.2 later, but I doubt that it'll change anything, since I've had that shadow-bug for forever now.

**Comment by AeroWidescreen** [comment]
Well, I just tried your settings and it's still working fine on my end. No flickering in sight. I also tried disabling / enabling Surface Format Optimization to be on the safe side, but it made absolutely no difference.

![Settings](https://i.imgur.com/36k0P7L.png)

>MLAA btw does nothing, 

Are you sure? I can see it working pretty easily in the menus. Of course, you'd be better off enabling SMAA through the Enhanced Edition settings since MLAA sucks in my opinion.

![Compare](https://i.imgur.com/9Vvi8Vu.gif)

I'm not saying this is your fault or anything. Maybe it's a driver bug with the 5700 XT that AMD never fixed? The only problem I'm aware of is the menu fade lag you get when you play in fullscreen mode, but this is why the Enhanced Edition defaults to borderless windowed mode.

**Comment by TommvinHuwaltzky** [comment]
> The only problem I'm aware of is the menu fade lag you get when you play in fullscreen mode, but this is why the Enhanced Edition defaults to borderless windowed mode.

that problem is gone as of Navi/RDNA. at least on my end. that's why I can use VSR @2880p in (exclusive) fullscreen in SH2.

> Are you sure?

yup. I also did comparison-shots. MLAA does zilch, SSAA works same as your SMAA, but without blurring the screen, BUT I get the shadow-bug.
weird...

**Comment by AeroWidescreen** [comment]
> that problem is gone as of Navi/RDNA. at least on my end. that's why I can use VSR @2880p in (exclusive) fullscreen in SH2.

I see, that might explain our difference in experiences then. I'm far too poor to spend 800 dollars on a mid-tier GPU right now lmao. I'm still using my old RX580. 

Anyway, unless @elishacloud has access to a Navi/RDNA GPU, then I doubt there's anything we can do about it. The aliasing isn't that noticeable in my opinion; the noise filter, fog, and darkness do a good job hiding most of it. Enabling SMAA in the config file should be enough. Sorry that I couldn't help.

**Comment by TommvinHuwaltzky** [comment]
> I'm far too poor to spend 800 dollars on a mid-tier GPU

well I sold my old Vega 56 and got a 5700 XT used for around 300 bucks about 2 years ago. so I guess I got lucky there. I'm also far from rich, hehe.

> Sorry that I couldn't help.

nah, as it's not impacting the playing of the game, I can live with it. just so you know that there seems to be a weird bug.
thanks for trying to help (:

**Comment by elishacloud** [comment]
> unless @elishacloud has access to a Navi/RDNA GPU, then I doubt there's anything we can do about it.

I don't.  I am using an old AMD video card for testing.  For my main/dev PC I prefer Nvidia.

One other thing you could try is disabling `FixGPUAntiAliasing`.  This option changes the way the game handles the RenderTraget, which directly effects how the game handles shadows.

However, while the GPU's AA looks better it is still recommended to use the game's built-in SMAA for AA effects.  The game is designed in a way to make it very difficult to fully support the GPU's AA features.  We added a couple of hacks, but it's still not right.

**Comment by elishacloud** [comment]
I just realized that I made `FixGPUAntiAliasing` only work on Nvidia GPUs.  However, part of the fix could be applicable to newer AMD GPUs.  Can you try this update with `FixGPUAntiAliasing` enabled and see if that helps:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5984778/d3d8.zip)

**Comment by TommvinHuwaltzky** [comment]
> For my main/dev PC I prefer Nvidia.

better features or not, I always liked to support AMD. for GPU _and_ CPU. they're not called "Ngreedia" for nothing :P

> One other thing you could try is disabling FixGPUAntiAliasing.

I usualy disable all Nvidia-specific features inside the module, **but** I tried it with and without the fix.

> I made FixGPUAntiAliasing only work on Nvidia GPUs.

yeah, I thought so.


gonna try the update you provided later and will let you know, thanks (:

**Comment by TommvinHuwaltzky** [comment]
back @Polymega

so this is also part of the normal shadow-behavior I assume?

![sh2pc_2021_02_16_04_57_59_678](https://user-images.githubusercontent.com/65239175/108017029-32456e80-7014-11eb-88d2-201cfc06b29e.gif)

**Comment by Polymega** [comment]
It is. Happens on all versions.

The shadows are set to disappear at a certain point. But that point is at a different spot depending on whether you're going up or down the stairs.

**Comment by TommvinHuwaltzky** [comment]
so since you haven't done so, it can't be altered? 
hard-coded I guess, hm?

**Comment by Polymega** [comment]
I remember playing around with this on my own a year or two back and finding the relevant instruction that makes this happen and changing or nop'ing it to "fix" it, but I abandoned it for one reason or another. I can't remember why. 

If I were to guess, I think it's because [shadow logic isn't perfect in this game](https://www.youtube.com/watch?v=APW9Rpgj5FI&feature=youtu.be), and I was afraid of going down a rabbit hole obsessing over it (as the work would never end).

**Comment by TommvinHuwaltzky** [comment]
> I was afraid of going down a rabbit hole obsessing over it (as the work would never end).

oh I hear ya....

**Comment by AeroWidescreen** [comment]
Yeah, it's just the nature of the game being so old. Shadows don't blend with the room lighting at all, they lay on top like a veil, so they're constantly being disabled based on your direction and position.

**Comment by Polymega** [comment]
I think most points have been discussed and/or addressed. I'll close this ticket out. Thanks for your notes!
