### ISSUE TITLE
Wood Side Appartments First Doors Crash

### ISSUE THREAD

**Issue by SquareHead312** [elishacloud/Silent-Hill-2-Enhancements#383]
The two doors in the staircase at the woodside appartments lobby crash the game when entered, making me unable to proceed normally, i have tried a lot of things, none have worked and i have no idea what is causing this.

**Comment by SquareHead312** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5966209/d3d8.log)
here's my d3d8.log, to sepcify, the issue happens while the door transition occurs, leading into a black screen and a crash.

**Comment by Polymega** [comment]
Hi there,

The game consistently crashing at the same point (such as opening a door) is not a normal issue, so it's hard to troubleshoot. 

For example: [Someone else's game consistently crashed when traversing a certain point at the start of the town.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/377) They fixed this by completely reinstalling the game. (They might have also found a different copy of the game as well for their re-installation.)

So the first thing I'd suggest is a complete re-install of everything.

However, for your particular crash point, when you first enter Wood Side Apartments is also the first time in the game that soft shadows would be used. You can try setting `EnableSoftShadows = 0` in the `d3d8.ini` file to see if the game won't crash for you anymore. This would at least tell you if it's something in particular with this fix.

**Comment by SquareHead312** [comment]
Ok, I re-installed the game and the enchanced edition package and now It works! Thank you so much for helping me with this issue, have a good day!
