### ISSUE TITLE
"Catacomb bug"

### ISSUE THREAD

**Issue by Robinexis** [elishacloud/Silent-Hill-2-Enhancements#384]
-This glitch is very weird and I can't seem to find anything to fix this:
When I enter in the room with the flashlight mannequin, when you interact with it, it jut says Catacomb, and then I can't press anything and do nothing than just press windows key.

**Comment by Polymega** [comment]
It sounds like the game is polling the wrong message (.mes) files. May I ask where you obtained your copy of SH2 PC from?

**Comment by Polymega** [comment]
No response so I'll close this ticket out. Feel free to re-open it if you'd lilke.
