### ISSUE TITLE
Condemned man's diary - Typo

### ISSUE THREAD

**Issue by nolyroby** [elishacloud/Silent-Hill-2-Enhancements#387]
In the "Condemned man's diary" upscaled full screen image, there is a typo:
"Why must I **did** come the morning?"

The correct, subtitled text reads:
"Why must I **die** come the morning?"

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6018347/d3d8.log)
![Condemned man's diary upscale](https://user-images.githubusercontent.com/79420122/108636189-ad15eb80-7451-11eb-83aa-1ccafae78080.jpg)

**Comment by Polymega** [comment]
Thank you very much. I've corrected this and it will be included with the next update to our project. In the meantime, you can grabbed this fixed image here: [sh2e.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6018462/sh2e.zip)
