### ISSUE TITLE
Game screen turns gray when gameplay starts

### ISSUE THREAD

**Issue by zevaz13** [elishacloud/Silent-Hill-2-Enhancements#388]
I installed the game and the Enhancement mode, however when I start the game, after the first sequence when James is looking at himself in the mirror, the whole screen turns gray.
It is really weird because I am able to move the character (still listening to the sounds of the movement) and I can even pause the game and interact with the pause menu.
This is my folder for the game :
![image](https://user-images.githubusercontent.com/63179646/108962399-8a402e80-762d-11eb-9d3a-c290ce003f2c.png)

and the sh2e folder:

![image](https://user-images.githubusercontent.com/63179646/108962456-a6dc6680-762d-11eb-94fa-dca57eb0fffc.png)

Thanks in advance for your advice and time 

Sebastian

**Comment by elishacloud** [comment]
It looks like you are missing the actual `d3d8.dll` module file and the `d3d8.ini` config file.  Go to the [releases](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases) page and download the latest module and extract all the files it into your Silent Hill 2 folder.

**Comment by zevaz13** [comment]
Hi again, I downloaded the d3d8.dll and the d3d8 again and it does not change. this is how my game looks like 
![image](https://user-images.githubusercontent.com/63179646/109265471-775b6480-77bb-11eb-85cc-20b3331079ec.png)
I can interact with the game, but I can't see anything. I can browse the start menu, the music keeps playing and If I move the character I can hear the sounds. 
This is how my folder looks like now
![image](https://user-images.githubusercontent.com/63179646/109265605-aa055d00-77bb-11eb-90b8-c9f138155241.png)

Thanks for your help

**Comment by Polymega** [comment]
Hello,

Now that you've added `d3d8.dll` and `d3d8.ini` to the game's folder, you should also have a `d3d8.log` file after launching the game. Can you please attach your `d3d8.log` file? (You can click + drag the file to include it as an attachment.)

[Here's how you can shown known file extensions on your computer.](https://www.wikihow.tech/Show-File-Extensions-on-Windows)

**Comment by elishacloud** [comment]
The symptoms are identical to what would happen if DirectX9 runtime is missing.  However, the required files are included in the `d3d8.dll` module.  Therefore the only conclusion I can reach is that the DirectX9 runtime is installed but corrupted.  I would recommend reinstalling the latest DirectX9 runtime.

**Comment by zevaz13** [comment]
Hi to both of you,

thanks for your help

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6066118/d3d8.log)
Is this the file you requested?

about elishacloud's answer, is there any specific version of the DirectX9 runtime that I should install ?. I looked it up and I found a file that has lots of folders in it 

Thanks again,
Sebastian

**Comment by elishacloud** [comment]
> about elishacloud's answer, I think you were right, I just re installed it and now it works!

Ok, great.  Glad to hear that it is working now.
