### ISSUE TITLE
DisableGameUX param looks broken

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#389]
I'm using Windows 7 to play EE, and DisableGameUX param is set to "1" in d3d8.ini. But it seems like it doesn't work normally in last EE module versions, because every game launching does create shortcut in Game Explorer, which weren't noticed in older EE versions. I don't use GameUX at all and even disabled its activity in the registry, and SH2EE is only one game that behaves now this way, which is a bit annoying. I thought setting DisableGameUX should completely make game invisible for Game Explorer service.

**Comment by Psycho-A** [comment]
UPD: I've noticed that when I remove game from GameUX, rundll32.exe process keeps slow down to start game to add it to GameUX again. Yes, DisableGameUX param is definitely broken.

**Comment by elishacloud** [comment]
Can you attach your log file.  This may give a clue to why this is broken.

**Comment by Psycho-A** [comment]
Ah, I already completely removed Game Explorer from my system to not disturb anymore :(
Well, if I'll have a time to bring it back, I'll make the log.

**Comment by elishacloud** [comment]
No problem.  If you get a chance I would like to troubleshoot this and see if I can get it fixed.  Thanks.
