### ISSUE TITLE
Game Crashes While Playing... Its Normal or Not?

### ISSUE THREAD

**Issue by BinariGuy** [elishacloud/Silent-Hill-2-Enhancements#39]
Its me again Polymega and with a new problem
the game stops working while im playing it, that didnt happened when i was passing the Hospital and the Prison just entering to the labyrinth sometimes just stop working. i dont know if this is cause of the mod or its just simply a game incompatilibity.
Thanks for reading

**Comment by Polymega** [comment]
Hi,
Does it always crash at the same spot or same room? Or is it random when/where it crashes? Are there times when it won't crash at all in Labyrinth?

**Comment by BinariGuy** [comment]
Hi...
It started to crash when i complete the prison. No, it randomly crashes on different spots

**Comment by Polymega** [comment]
Can you tell me your PC specs? Processor, RAM, GPU, OS, etc.

**Comment by AeroWidescreen** [comment]
When you crash, open Event Viewer -> Windows Logs -> Application and look for an error. There should be a crash log that you can paste here that should give us a better idea of what's happening.

**Comment by BinariGuy** [comment]
Well... After completing the game i think i cant play it anymore without  the game crashing anytime and idk how to do the thing that @AeroWidescreen ask for

**Comment by ambystona** [comment]
Same case here, the game freezed when I tried to go the rooftop in the Hospital and the second room in the Historical Society. But using event viewer I saw that igfxCUIService2.0.0.0, the Intel graphics driver, has caused the problem. Maybe something like this causes the same problem with the AMD processor?

**Comment by Polymega** [comment]
@ambystona are you using ReShade and/or WineD3D with your game?

**Comment by ambystona** [comment]
I'm using the newest reshade version, 3.4.1.

**Comment by Polymega** [comment]
Try playing the game without it and see if you still get the crashes. You can set `d3d8to9 = 0` in the `d3d8.ini` file to quickly/easily disable it.

**Comment by Storm3000** [comment]
I have the same problem. The game freezes randomly. I'm not using Reshade.

**Comment by Polymega** [comment]
@Storm3000 unfortunately without a crash report we can't pin-point what the issue may be. The only thing I can suggest right now is disable features, using a process-of-elimination, until you can determine what, if any, fixes are causing the issues. I'm sorry I can't give a more direct solution to your problem. :-/

**Comment by Storm3000** [comment]
I moved yesterday all the files stored on the sh2e folder back to the original folders. I played almost all the game and it worked fine. I'll continue checking if the issue appears again, but it's working fine for now. Besides, I disabled the UseCustomModFolder option in d3d8.ini.

**Comment by elishacloud** [comment]
Closing as this is specific to the DC version of the game and we are moving to the NA version.
