### ISSUE TITLE
[Request] Enhance mouse usage

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#390]
Since mouse is supported by game to navigate menus and map, maybe it's possible to extend its usage by the means of EE module?

1. Pause menu have no mouse navigation, although it is inside of it, that's a bit illogical.

2. SH3 and SH4 have good mouse bindings: LMB is use/attack action, RMB is aiming pose and cancel action. It would be really nice to have the same for SH2 :)

**Comment by PunishedFiddle** [comment]
Would be great. Mouse if perfect for rotating in tank control mode.

**Comment by Polymega** [comment]
This is now added into the project!
