### ISSUE TITLE
Possibility of retake from Mr. Cihi.

### ISSUE THREAD

**Issue by snigelpasta** [elishacloud/Silent-Hill-2-Enhancements#394]
So in Fungo's let's play with Guy Cihi, Cihi mentions that he wishes he had seen an image of the lying figure before recording the line "Is it dead? What the hell is it?". He says he would have sounded more menacing in his voice if he had.

As we all know Mr. Cihi is active on the internet and in ,touch with the Silent Hill community. Maybe he'd be interested in re-recording that one line. I think it'd align with the vision of the project.

**Comment by Polymega** [comment]
I don't think it would be feasible for us to arrange a way to have Guy retake lines. I'm also not sure if he'd want to do it. Thank you for the suggestion on this, but at this time I think we'll hold off from doing anything like this.
