### ISSUE TITLE
2D-images

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [elishacloud/Silent-Hill-2-Enhancements#395]
hey guys, 

was just trying out the new update after watching the vid on youtube. 
the dynamic-resolution-option is pretty neat, but I noticed that 
![sh2](https://user-images.githubusercontent.com/65239175/111406421-92dad080-86d2-11eb-8898-369fa52cedf0.png)
was gone from the ini-file.
the video explains that you're cropping the images automaticaly, depending on the aspect-ratio.
I was actualy pretty happy when you added the option a few updates ago to choose for yourself (have seen other people wanting it as well), so I'm a bit confused why you got away with it. to not confuse ppl that are not as well-versed with modding?
is it possible to bring it back, or add the line back in manualy?
I realy don't mind the borders and like my images un-cropped.

a reply would be appreciated, and thanks for your work as always! (:

**Comment by Polymega** [comment]
> to not confuse ppl that are not as well-versed with modding?

Pretty much. The common end user just wants things "to work" with as little adjusting as possible. We automated it because, since the aspect ratio can now be dynamically changed at any given time (with `DynamicResolution`), we can't predict what the aspect ratio will be changed to. 

If you disable `DynamicResolution` you can override the automatic image scaling by adding `FullscreenImages` back to the INI file (you can then also re-add `ResX` and `ResY` to set a static resolution). More information here: http://enhanced.townofsilenthill.com/SH2/config.htm#additionalsettings

**Comment by TommvinHuwaltzky** [comment]
haha yeah, pretty much figured it out by myself just now.
`DynamicResolution` can still stay active (works too), but I just added

![sh2](https://user-images.githubusercontent.com/65239175/111411255-7a6eb400-86da-11eb-8af5-43cd358d4b91.png)
back in and works like a charm (forgot about the settings for the FMVs, so thanks for reminding me).

also, on a fresh vanilla install and then the EE "installed", map is automaticaly zoomed in, subtitles are on, and noise-filter is off. don't thinks that's from the game, is it?

thanks for replying! (:

**Comment by Psycho-A** [comment]
To avoid creating a new issue, I'd like to ask about the new 'UsePS2LowResTextures' parameter for 2D images. 

1. What's the purpose of duplicating textures in the ps2/ folder, if we could just read the original textures from the data/pic/ folder? They're better on something? If no, I think using 'EnableTexAddrHack' would be enough to just not read improved textures from sh2e/...

2. Will textures from the data/ps2/ folder be readable if I disable the use of the sh2e/ folder? I've asked something similar before about the 'CatacombsMeatRoomFix' parameter, and that time forcing the sh2e/ folder was fixed.

**Comment by TommvinHuwaltzky** [comment]
hm, was wondering about that option myself. thought it meant the overall game/world-textures, but you can disable them in the game-menu...

**Comment by Polymega** [comment]
> I'd like to ask about the new 'UsePS2LowResTextures' parameter for 2D images

This disables the sh2e\pic\ , sh2e\etc\effect\, and sh2e\menu\ directories and redirects to the sh2e\ps2\ directory. 

The way we have this set up will make it where all the original full screen images found in the data\ folder are used _along with_ a PS2-styled main menu found in the she2\ps2\ folder. This ps2\ directory [also includes a corrected carbon.tex image](https://youtu.be/uJi0_kJbCoU?t=900) for when the low res full screen images are used. 

> What's the purpose of duplicating textures in the ps2/ folder

We're not duplicating the original textures for this folder. This ps2\ folder houses a new PS2-styled main menu and a corrected carbon.tex image; that's all. The game will use these files and all the original full screen images found within the data\ folder.

This is to keep in line with us not replacing/overwriting any files found within the data\ folder.

> hm, was wondering about that option myself. thought it meant the overall game/world-textures

The environment textures are identical to the PS2/Xbox versions. Well, unless you enable low res textures in the game's options menu, that is...

**Comment by TommvinHuwaltzky** [comment]
> This is to keep in line with us not replacing/overwriting any files found within the data\ folder.

why not though? I always choose the "Movies on Disk"-option of the installer because they're redundant and just take up space with no use. why _not_ replace the old with the new?

**Comment by Polymega** [comment]
> why not though? I always choose the "Movies on Disk"-option of the installer because they're redundant and just take up space with no use. why not replace the old with the new?

So a person can easily revert back to the vanilla PC version, for whatever reason. (To speedrun the game, to test something in the vanilla version, or if you're a masochist, to see how jank the original version is.) 

You can move all the files from the she2\ directory to the data\ directory, but do so at your own risk. We've established this guideline of not overwriting original files since the beginning of the project, as we feel it's a good practice.

**Comment by Psycho-A** [comment]
Polymega, thanks for answer. I also meant, will **data**/ps2/ location be readable too if no sh2e/ folder is used? If no sh2e/ folder is used, this location could be used along with native data/ assets like you said above.

**Comment by Polymega** [comment]
> will data/ps2/ location be readable too?

No, I don't believe it would. This is because we disable sh2e\pic\ to use sh2e\ps2\ instead. But if you were to disable data\pic\ the game wouldn't boot (as it wouldn't be able to find all full screen images it needs).

**Comment by elishacloud** [comment]
> We've established this guideline of not overwriting original files since the beginning of the project

This is how all my updates work.  I try and make sure that users can use my updates and patches without modifying any of the game's original files.  Of course users can chose to overwrite the game's original files with our updated ones, but features like `UsePS2LowResTextures` won't work correctly if you do that.

> I always choose the "Movies on Disk"-option of the installer because they're redundant and just take up space with no use.

Interesting.  I don't know how much, if any, we have tested this install option.  Our sh2e folder does _not_ replicate every file in the `data` folder.  So not having some of the files on disk could be an issue for our module.  In fact, even if you copy the `sh2e` files into the `data` folder files could still be missing if you don't do a full install on the hard drive.

I was always thinking that most people don't have CD/DVD drives in their computer any more and thus would just install all files to disk to avoid mounting an ISO image or something of that nature...

**Comment by TommvinHuwaltzky** [comment]
> I was always thinking that most people don't have CD/DVD drives in their computer any more and thus would just install all files to disk to avoid mounting an ISO image or something of that nature...

well I mount my iso of the game, choose "Movies on Disk", then install your _EE_, and the game reads most files off the "sh2e"-folder anyway. and the exe  you provide hasn't got a CD-check, so the disc won't be needed to play after install anymore.

would be interesting to overwrite all files from _sh2e_ to the data-folder and then do a full playthrough, see what happens. maybe I'll do that (:

**Comment by Psycho-A** [comment]
> No, I don't believe it would. This is because we disable sh2e\pic\ to use sh2e\ps2\ instead. But if you were to disable data\pic\ the game wouldn't boot (as it wouldn't be able to find all full screen images it needs).

I meant, it would be nice if this setting would disable **only** sh2e\pic\ location, but wouldn't touch data\pic\ even if there's no sh2e\ folder in our game set. The we could use data\ps2\ along with data\pic\ for our purposes, including your image fixes.

**Comment by Polymega** [comment]
I see. I will leave that decision up to Elisha. But what you're saying is have the following take precedence over each other: sh2e\ps2\ > sh2e\pic > data\ps2\ > data\pic\

**Comment by Bullsquiddy** [comment]
I'm confused as to what the 'UsePS2LowResTextures' affects. I understand that it effectively turns off the Fullscreen Image Enhancement Pack, but does it also have an effect on the game's environmental textures?

**Comment by Polymega** [comment]
No, it doesn't have an effect on the game's environmental textures. [I explain its purpose here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/395#issuecomment-802141798)

**Comment by Bullsquiddy** [comment]
Oh I see - sorry, I didn't understand entirely when I first read the explanation. Thanks very much!

**Comment by elishacloud** [comment]
> it would be nice if this setting would disable only sh2e\pic\ location, but wouldn't touch data\pic\ even if there's no sh2e\ folder in our game set.

Yes, this is possible.  There is a hidden option that I created a while ago.  I just tested it works fine with the `UsePS2LowResTextures` option.

If you add the following line into the ini file then it will see the `data` folder as the mod folder and it will use the files in the `sh2e\ps2\` to overwrite any file in the `sh2e\pic\` folder:

```ini
CustomModFolder = data
```
