### ISSUE TITLE
[Update 7] Closing the game through the task bar won't shut down the audio

### ISSUE THREAD

**Issue by 0xlord** [elishacloud/Silent-Hill-2-Enhancements#398]
How to reproduce:
 * Start the game
 * (Optional?) Load a save or start a new game
 * ALT+TAB outside
 * Right click on the task bar symbol and close the game
 * The audio will continue to run in it's current loop (sounds like ingame e.g. radio beside a monster & ingame music) 

No idea if this was before Update 07 as well, sorry.

**Comment by elishacloud** [comment]
Yes, this is a problem with the game's multi-threading.  I don't think it is related to our update.  For this game you need to exit the game from the game's menu not from Windows.
