### ISSUE TITLE
Unable to launch game (iMac Pro, Bootcamp Windows 10)

### ISSUE THREAD

**Issue by katawajojo** [elishacloud/Silent-Hill-2-Enhancements#399]
I've been trying to run this game to no avail. I'm not sure if it because of an incompatibility with my system, but vanilla and Enhanced refuse to launch. I've attempted manually setting the CPU affinity (after setting `SingleCoreAffinity = 0`), and setting `d3d8to9  = 0`. What I run into is the game creating the window, then sitting at a black screen.

shortened DxDiag info:
```            Machine name: DESKTOP-UB2DJDC
               Machine Id: {6BC1A5A7-CF37-4F46-8DA6-EB67E92C0D4C}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: Apple Inc.
             System Model: iMacPro1,1
                     BIOS: 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0) (type: UEFI)
                Processor: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 CPUs), ~3.2GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32480MB RAM
                Page File: 30570MB used, 19677MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 144 DPI (150 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.0546 64bit Unicode

---------------
Display Devices
---------------
           Card name: Radeon Pro Vega 56
        Manufacturer: Advanced Micro Devices, Inc.
           Chip type: AMD Radeon Graphics Processor (0x6867)

-------------
Sound Devices
-------------
            Description: Speakers (MOTU Pro Audio)
 Default Sound Playback: Yes
 Default Voice Playback: No
            Hardware ID: USB\VID_07FD&PID_0005&REV_0200
        Manufacturer ID: N/A
             Product ID: N/A
                   Type: N/A
            Driver Name: MOTUProAudio.sys
         Driver Version: 4.0.8.2000 (English)
      Driver Attributes: Final Retail
            WHQL Logo'd: n/a
          Date and Size: 9/8/2019 5:00:00 PM, 168248 bytes
            Other Files: 
        Driver Provider: MOTU, Inc
         HW Accel Level: Emulation Only
              Cap Flags: 0x0
    Min/Max Sample Rate: 0, 0
Static/Strm HW Mix Bufs: 0, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No
```

Attached are the d3d8.log files for the normal hook and the debug version.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6156793/d3d8.log)
[d3d8.debug.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6156795/d3d8.debug.log)

**Comment by katawajojo** [comment]
Update: I just updated to the newest d3d8 release posted on the site, and am running into the same issue.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6157814/d3d8.log)

**Comment by elishacloud** [comment]
We have had issues on Apple computers in the past.  It might be ReShade causing the issue here.  Try disabling `AdjustColorTemp` and `RestoreBrightnessSelector`.

**Comment by katawajojo** [comment]
Thanks for the speedy reply! No dice, unfortunately.

**Comment by elishacloud** [comment]
Somehow you did not disable those options.  They are still enabled in the log file:

```log
19160 11:04:16.934 |- AdjustColorTemp: 1
19160 11:04:16.934 |- EnableSMAA: 0
19160 11:04:16.934 |- RestoreBrightnessSelector: 1
```

**Comment by katawajojo** [comment]
oh shit, my bad. Here ya go.
It seems to be dying at whatever happens after ReShade hooks?

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6159302/d3d8.log)
[d3d8.debug.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6159303/d3d8.debug.log)

**Comment by elishacloud** [comment]
Ok, try with this ini file:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6159692/d3d8.zip)

Just unzip it into the game folder.  This will help determine if it is something to do with the d3d8 module or the game itself.

**Comment by katawajojo** [comment]
Still nothing. I'm not sure if it's a hardware configuration issue? I know I've had issues with programs in the past because I use an external DAC, but here's the log: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6159725/d3d8.log)

**Comment by elishacloud** [comment]
Can you try renaming or removing the `d3d8.dll` file to see if the game will work without the enhancement module?

**Comment by katawajojo** [comment]
Nope, no dice. It just sits at a black screen.

**Comment by elishacloud** [comment]
> I moved the game to my external SSD, X:\KONAMI\Silent Hill 2, and it launches fine now? Computers are weird :/

Interestingly enough, we have seen this before.  We cannot reproduce it and don't know exactly what is going on here.  Anyways, I am glad you got it working!

**Comment by katawajojo** [comment]
I can test this on one of my other Mac systems to see if it is indeed something to do with their storage drivers and whatnot.

**Comment by katawajojo** [comment]
Just to touch on this, it does seem to be something with Bootcamp specifically. Unsure of what would be causing it, but this only occurred with my 2019 MacBook Pro, iMac Pro, and 2013 Mac Pro. Every other system I have works just fine. But, seeing as I just built a brand new desktop, I don't think I'll be running into this issue any time soon again. 🤷
