### ISSUE TITLE
Strange bug when using flashlight: all textures and meshes are inverted and very glitchy

### ISSUE THREAD

**Issue by WoodSpirit22** [elishacloud/Silent-Hill-2-Enhancements#40]
https://youtu.be/u6T4TkaDpHc

(The actual quality in-game is much much better than this, it's the render settings I used and the capture settings making it look terrible- also youtube).

Thanks a lot for all your work guys, really enjoying it so far. Everything seems to work perfectly, apart from this odd bug that I can't seem to find any information on so far. Here's a quick video I recorded of the issue. Happens every time I use the flashlight inside for some reason. Here are my specs: 
![untitled-1](https://user-images.githubusercontent.com/43076258/45238159-d7eb4400-b2d8-11e8-8bf4-1aa23f16f718.jpg)

I installed everything in the correct order as far as I can tell, only thing I didn't use was WINE as I have an AMD GPU and it said to skip if you are an AMD user.

![default](https://user-images.githubusercontent.com/43076258/45238231-17199500-b2d9-11e8-8c0f-89d96da2ff04.jpg)

Few stills of the issue: 
![vlcsnap-2018-09-07-19h54m37s612](https://user-images.githubusercontent.com/43076258/45238313-5ea02100-b2d9-11e8-80c5-e2b8aaef298d.png)
![vlcsnap-2018-09-07-19h52m56s359](https://user-images.githubusercontent.com/43076258/45238314-5f38b780-b2d9-11e8-9fc7-ee75e3a9377f.png)
![vlcsnap-2018-09-07-19h53m05s596](https://user-images.githubusercontent.com/43076258/45238315-5f38b780-b2d9-11e8-86c6-cf4b6fe86be3.png)
![vlcsnap-2018-09-07-19h53m23s547](https://user-images.githubusercontent.com/43076258/45238316-5f38b780-b2d9-11e8-91a4-e766d5da2845.png)
![vlcsnap-2018-09-07-19h53m43s675](https://user-images.githubusercontent.com/43076258/45238317-5f38b780-b2d9-11e8-8b9b-108d6e23252f.png)
![vlcsnap-2018-09-07-19h53m54s888](https://user-images.githubusercontent.com/43076258/45238318-5fd14e00-b2d9-11e8-818e-2edb850d6dce.png)
![vlcsnap-2018-09-07-19h54m12s086](https://user-images.githubusercontent.com/43076258/45238320-6069e480-b2d9-11e8-9a34-7e9e5a3c0940.png)

Any help would be much appreciated, although it's probably just my PC. Just can't seem to see where i've gone wrong. It was a clean install and with a decent-ish PC so I dunno.

Cheers!

**Comment by Polymega** [comment]
Hi @WoodSpirit22 ,

Try installing the DirectX 9 SDK and let us know if that fixes your issue.

https://www.microsoft.com/download/details.aspx?id=35

**Comment by WoodSpirit22** [comment]
Hi, no that didn’t seem to have any effect and it’s still in the same weird glitchy state. When I try to use the link you provided to downloaded that version of direct x, it just downloads the newest version, which I already have so it doesn’t actually download anything. When I manually search for direct x 9 SDK, i can download it from the official sources, but when I install it; it gets to the 99% and crashes and doesn’t actually install. If you need any more info please let me know, I can’t seem to solve it at all. Thanks!

**Comment by Polymega** [comment]
Okay, try this for me: While in the game, turn the flashlight on to produce the glitch, then press F12 to disable the ReShade filter effects. Does it become fixed then? 

If not, temporarily remove the d3d9.dll file from the directory but **ensure** `d3d8to9 = 1` is still enabled. Does it fix the glitch then?

**Comment by WoodSpirit22** [comment]
Hi. No that still didn't help, but I found that when d3d8to9 is turned off in the d3d8.ini, the bug goes away. When it's still on, if I turn off reShade manually with F12, the bug is still there just a fraction less dark. Not sure which part of d3d8to9 being turned off is fixing it, but it removes reShade completley and I really would prefer to be able to use reShade. Cheres

**Comment by Polymega** [comment]
Okay, this may be some type of pixel shader issue with certain GPUs or OS' for d3d8to9. Maybe @crosire or @elishacloud could take a peak into this in the future sometime.

**Comment by Polymega** [comment]
The good news here is that, looking at your directory, you're not using WineD3D, which means you're not using an Nvidia card? 

If that's the case the only thing you're missing by disabling d3d8to9 is the use of ReShade. ReShade _slightly_ adjusts color/level balances for the game to make it look closer to the PCSX2 version and also implements anti-aliasing. Neither of these things are absolutely required in order to enjoy the game and anti-aliasing can still be achieved through other methods, such as forcing it through your GPU's control panel. 

But let's get a comments from crosire or Elisha on this first as it may be a pixel shader issue with d3d8to9 that they can possibly address in the future.

**Comment by elishacloud** [comment]
@WoodSpirit22, if you enable d3d8to9 and remove ReShade does this issue still happen?  I am trying to determine if this is an issue with d3d8to9 or with ReShade.

**Comment by WoodSpirit22** [comment]
@elishacloud Hi sorry for the slow reply. 

I actually haven't tried that, although I did try manually disable it with F12 which didn't have any effect. Do you currently have or know where I could get a save file from in the apartments? That seemed to be the area that was the worst and I have saved over my file from anywhere near it. 

Also could you tell me exactly which files to delete to remove only ReShade? I also deleted the zip of the ReShade install thing so I don't know exactly which ones are for just ReShade, and my internet is so trash I can't even download a .jpg right now.

**Comment by Polymega** [comment]
@WoodSpirit22 thanks for following up with us. I wish we could replicate the bug you're having so as not to have folks like you doing all the testing; sorry about that. 

Here's a save file that'll load you directly into the room where you acquire the flashlight. Just load the "Quick Save" save file from the game's load menu: [Quick Save save file](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2447454/data.zip)

But this bug should happen _any_ time you turn on the flashlight, correct? No matter what area you're in? Or is it _just_ the apartment level this happens on? 

Please follow these steps: 
1. **Remove** the ReShade files from the game's directory (`d3d9.dll`, `d3d9.ini`, `d3d9.log`, `ReShade Filter - SH2 PC PS2.ini`, and the `\reshade-shaders\` folder)
2. Ensure `d3d8to9 = 1` is **active** in the `d3d8.ini` file
3. Ensure `WidescreenFix = 1` is **active** in the `d3d8.ini` file

Launch the game and turn on the flashlight/replicate the bug. Does it still happen? If not, then it is ReShade causing the issue. 

If the bug still happens:

1. Set `d3d8to9 = 0` **(disable)** in the `d3d8.ini` file

Relaunch the game and turn on the flashlight/replicate the bug. Does it still happen? If not, then it is d3d8to9 causing the issue.

**Comment by WoodSpirit22** [comment]
@Polymega Sorry again for the slow replies, I’m literally using my phone the internet is that awful. 

Yeah you’re right, it’s whenever the flashlight is on anywhere not just the apartments, my mistake I dunno why I said that haha.

Okay, so I followed all your steps and loaded the save, and the bug is still there. So that means it is definitely ReShade then? Also does no one on the team have a AMD GPU to try and replicate it, as that’s what I assumed it would be because I sometimes do run into issues with this card, but I really dunno lol. 

If there’s any other info I can provide or any other stuff to test I am happy to help!

**Comment by Polymega** [comment]
> Okay, so I followed all your steps and loaded the save, and the bug is still there.

To confirm, you also did the following (below)?

--------------

Please follow these steps: 
1. **Remove** the ReShade files from the game's directory (`d3d9.dll`, `d3d9.ini`, `d3d9.log`, `ReShade Filter - SH2 PC PS2.ini`, and the `\reshade-shaders\` folder)
2. Ensure `d3d8to9 = 1` is **active** in the `d3d8.ini` file
3. Ensure `WidescreenFix = 1` is **active** in the `d3d8.ini` file

Launch the game and turn on the flashlight/replicate the bug. Does it still happen? If not, then it is ReShade causing the issue. 

If the bug still happens:

1. Set `d3d8to9 = 0` **(disable)** in the `d3d8.ini` file

Relaunch the game and turn on the flashlight/replicate the bug. Does it still happen? If not, then it is d3d8to9 causing the issue. 

-----------

> Also does no one on the team have a AMD GPU to try and replicate it

Both AeroWidescreen and myself have AMD PCs but don't experience this bug.

**Comment by Polymega** [comment]
I wanted to confirm this with you as if you **removed** the ReShade files from the game's directory **and also** set `d3d8to9 =` to `0` in the `d3d8.ini` file and the bug still happens then that means it's **neither** ReShade or d3d8to9 causing the issue. It may be a issue unique to the AMD Radeon R9 200 card.

**Comment by WoodSpirit22** [comment]
@Polymega Hi, sorry I should of clarified. I deleted all the loose files you listed and activated d3d8to9 (set it to ‘1’), the widescreen Fix is already set to ‘1’, I loaded the save and the flashlight still had the bug. 

So following that like you just suggested I set ‘d3d8to9=0’ and the bug is no longer present, so it must be d3d8to9. I really wish I knew what is different about my PC lol, have you had a few other people with this issue since I posted this also? 

I am using a TV and it’s currently set as my 2nd monitor on a 2 screen set up, and it’s add a weird ‘200% custom zoom type deal thing, but I don’t think that would affect it much? If there’s some sort of spec list I can give you other than what’s already listed at the top let me know

**Comment by Polymega** [comment]
> So following that like you just suggested I set ‘d3d8to9=0’ and the bug is no longer present, so it must be d3d8to9.

Perfect. This confirms its d3d8to9 causing a bug for certain graphic cards then. 

> have you had a few other people with this issue since I posted this also?

Yes, I can't find them immediately but there has been at least another support ticket here about this and a person or two leaving a comment about this on the SH2:EE YouTube trailer video. 

> and it’s add a weird ‘200% custom zoom type deal thing, but I don’t think that would affect it much? 

I wouldn't think so... If you can temporarily disable that zoom feature and re-launch the game to see if it fixes the bug it wouldn't hurt anything!

**Comment by WoodSpirit22** [comment]
Also I seem to be having the flashlight bug that lights things like enemies and Maria behind the flashlight if that makes sense. Like the whole character will be illuminated despite being behind the light source, and that’s with ‘d3d8to9=0’ (off). Not sure if that’s related? And the main title menu screen is still in 4:3 and not full screen despite that being set in the settings .ini thing.

**Comment by Polymega** [comment]
> Also I seem to be having the flashlight bug that lights things like enemies and Maria behind the flashlight if that makes sense. 

Ensure `WidescreenFix =` is set to `1` and `LightingFix =` is set to `1` in the `d3d8.ini` file. The [LightingFix mod](http://enhanced.townofsilenthill.com/SH2/config.htm#LightingFix) fixes this specific issue you're referring to. And we have to enable the WidescreenFix in order to use the LightingFix.

> And the main title menu screen is still in 4:3 and not full screen despite that being set in the settings .ini thing.

This is normal. The [FullscreenImage mod](http://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenImages) only affects riddle/memo images, and not images like the main menu or save screen. This mod zooms in on images that have letterboxing on them and, because the main menu/save screen/etc do **not** have inherent letterboxing they don't get zoomed. 

We hope to make a "Fullscreen Image Enhancement Pack" mod sometime in the future to make all the images fill a 16:9 display nicely. But this will probably be some time off.

**Comment by WoodSpirit22** [comment]
@Polymega I followed the steps and everything is already set to those settings in ‘d3d8.ini’ and I redownloaded and overwritten the lighting fix again just to make sure but it’s still there. No idea why, must be something weird with my PC lol. It is fairly old, I got it in like 2013. 

Ah ok that makes sense, awesome I look forward to it if you do! The title screen for SH3 on PC bothers me so much, it looks really low quality on a decent monitor, and 4:3 too I guess. If there’s anything else you can think of let me know. I could try and send you the whole game folder but it’s like 10gb and probably illegal also haha.

**Comment by WoodSpirit22** [comment]
Also damn it could be because of me and whoever else encountering this bug using the same bootleg-ass copy of SH2. That would make sense? Maybe we all just got the same bad upload of the game? I can’t remember the link I got it from now and I’ve deleted the install files but I bet it’s that. I know it’s bogus to pirate games but they literally don’t sell this game anywhere 

I’ll delete this post if you want me to obviously

**Comment by Polymega** [comment]
Go ahead and delete that post @WoodSpirit22 and send me a message through this contact form: http://www.igotaletter.com/siteinfo/contact/

**Comment by WoodSpirit22** [comment]
@Polymega apologies, I just messaged you through there. 

Cheers!

**Comment by elishacloud** [comment]
@WoodSpirit22, can you attach your log file?  There may be other data in there that will help.  Also can you try upgrading to the latest AMD driver?  I suspect this is an issue with the AMD Radeon R9 200 driver.

**Comment by elishacloud** [comment]
@WoodSpirit22, Try this one: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2453473/d3d8.zip)

I made some changes to the d3d8to9 module to see if that is the issue.

**Comment by WoodSpirit22** [comment]
@elishacloud Hey, sorry for taking so long to reply, I didn't realise you had replied to me.

So I just tried the d3d8.zip you provided and the bug is still there, but the various other lighting issues I had noticed seem to be improved in this version.

**Comment by AeroWidescreen** [comment]
@WoodSpirit22 Have you tried disabling LightingFix in the ini? It can cause issues like this with the flashlight. It doesn't hurt to try if you haven't already.

**Comment by elishacloud** [comment]
@WoodSpirit22, someone mentioned on the forum on YouTube that this was fixed with the latest release.  Can you check with [v1.3.1340.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1340.0) and see if this issue still happens?

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.
