### ISSUE TITLE
[Request] Ability to swap Light/Heavy inputs

### ISSUE THREAD

**Issue by HeyItsLollie** [elishacloud/Silent-Hill-2-Enhancements#404]
Hi all, happy to see the work that's been done for SH2PC.

The way light/heavy inputs are currently handled feels kind of counter-intuitive. It'd be great if tap/hold inputs could be swapped (with an ini config option, or in the Game Options menu if possible) to match modern control paridigms, so that quick-taps = light attacks, and long-holds = heavy attacks.

**Comment by Polymega** [comment]
Hi there,

I'm not sure if we'll look into swapping the attacks, but I do agree with you that it feels counterintuitive. A while back I got to thinking why it's like this and the most likely reason I could think of is because melee weapons like the plank can do a continuous/infinite light attack animation if you keep the button held down. 

So when porting the game to platforms that don't support pressure sensitive buttons, I reckon they opted to make holding down the button the light attack for that reason. (It may actually be like this on the PS2/Xbox version as well, but I won't be able to test it for a while.)

**Comment by HeyItsLollie** [comment]
I ended up giving this a quick test on my PS2 (start of the game, fenced lot in Vachss Road).

Both light and heavy attacks will repeat when held - the pressure sensitivity when initially held is what determines the attach that will be repeated. Attacks can be repeated by spamming button presses too, although it's much easier to do this with light taps VS heavy presses.

Here's a quick video demonstrating these inputs, with input display. (Outlined button is light press, filled button is full press)
https://www.youtube.com/watch?v=8b6rWd-IJ_g&t=8s

**Comment by Polymega** [comment]
Thanks for testing that for me. And I really like the PS2 controller overlay in your video... that's super slick.

**Comment by Arthandas** [comment]
I think the PC controls are really bad and could be greatly improved. Unlike in PS2 version, you can't do a light attack from fighting stance even if you hold the attack button - the first attack will always be a heavy one and only then will James start light swings. To do a light attack you need to hold attack button right after entering fighting stance, wait too long and you'll need to re-enter it or do a heavy attack first...

And don't even start me on kicking. Apparently you need to:
1. Step out of enemy's "finishing range" after its knocked down
2. Hold the attack button and approach it
3. Before entering its "finishing range" (where you're able to trigger a stomp) tap Aim button (without letting go of attack button) and James will lift his weapon, then put it down and perform the kick
That's just ridiculous, it's more complicated than special moves in fighting games.
It should be something like tap to kick and double tap/hold to stomp. Also, what's even the difference between the two? Both just finish a downed enemy in the same way.

**Comment by Polymega** [comment]
> I think the PC controls are really bad and could be greatly improved.

The only difference between the PC and PS2 version's controls are the lack of pressure sensitive buttons on the former. PC actually allows you to customize controls greater than the PS2 version.

> And don't even start me on kicking. Apparently you need to:

You just press the action button next to a downed enemy without holding the ready weapon button to perform the stomp. It's very easy and also like this on the console versions.

**Comment by Arthandas** [comment]
> You just press the action button next to a downed enemy without holding the ready weapon button to perform the stomp. It's very easy and also like this on the console versions.

See, even you don't know about it :) Kicking and stomping are two different things.

**Comment by Polymega** [comment]
I'd hope I know about it.

There's two different stomp animations, yes. One is animated more like a kick, but they're both used to deliver the final blow to an enemy.

The stomp animation depends on how hard you press the button on the PS2/Xbox version. So platforms that don't support pressure sensitivity it'll will only do the one under most circumstances.

**Comment by Arthandas** [comment]
> So on platforms that don't support pressure sensitivity it'll only do the one under most circumstances.

You can reliably do the kick by following the obscure steps I posted previously and like I said, they are ridiculous, and 99.9% of PC players won't ever perform it (without reading about it online). That's why I'm suggesting to change its input.

**Comment by Polymega** [comment]
We have brought back the alternate stomp by making it a 50/50 chance of receiving either one through a normal button press to perform this action. Ticket can be found here:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/500

At this time, there's no plans to swap the tap/hold presses for heavy/light attacks. Thanks for your notes and I'm glad we were able to restore the kick animation which was otherwise honestly never seen in this version. :)

**Comment by HeyItsLollie** [comment]
> At this time, there's no plans to swap the tap/hold presses for heavy/light attacks.
Bummer, but fair enough. Hopefully this is considered again in the future. ✌

**Comment by jvne2134** [comment]
i stopped playing because i could not figure out how to finish enemies off

**Comment by Polymega** [comment]
In progress!

**Comment by Polymega** [comment]
This feature has been added.
