### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by OmniNeosX** [elishacloud/Silent-Hill-2-Enhancements#405]
No matter what I do, it always starts on a black screen. I've tried starting with no DS4 controller plugged in, I've tried starting while it was plugged in. I've tried copying files into it and moving into it, I've tried all "screen modes" (I.E Widescreen, Windowed, ETC) and still the same result.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6214940/d3d8.log)
Here's the log file for ya.

**Comment by Polymega** [comment]
Thanks for the log file. Everything looks to be in order with your log... which will make troubleshooting a bit tricky.

To start with testing, if you temporarily remove `dsound.dll` and `dsoal-aldrv.dll` from the directory, will the game boot for you then?

**Comment by OmniNeosX** [comment]
I moved those into a seperate file and tried to boot it without a controller plugged in, got the same result. A black screen with no advancement.

**Comment by Polymega** [comment]
Okay, you can place those files back in the directory then. Try these in order:

---------------------

If using a DS4 controller, make sure Windows doesn't change its audio output to the controller. [More info at the bottom of this troubleshooting step.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch)

-----------------------

Your directory for the game:

```
D:\Silent Hill 2\Silent Hill 2\Silent Hill 2\
```

I'm not sure if nesting the game in three folders with the same name might be confusing it, but try moving all the files/folders within `D:\Silent Hill 2\Silent Hill 2\Silent Hill 2\` to a new directory (such as just `D:\Silent Hill 2\`

You don't have to reinstall the game or anything; simply moving the files/folders over should be fine.

--------------------------

Temporarily remove `d3d8.dll` and launch the game. By doing this you're more-or-less launching the game in its vanilla state. Does the game launch for you then? (If it does, it'll launch in fullscreen mode at probably a low resolution.) If it still doesn't launch for you, then there may be an issue with the base game's installation (not related to our project.)

**Comment by OmniNeosX** [comment]
I'll try un-nesting it first and then I'll try removing the .dll file

**Comment by OmniNeosX** [comment]
Tried both and it still hasn't launched. One thing to note is that the cursor always makes the hourglass, not sure if that means anything.

**Comment by Polymega** [comment]
If you removed the `d3d8.dll` file and the game still wouldn't launch then it's likely there's an issue with the base (vanilla) game. 

I'd recommend reinstalling the game and, after doing so, [grab just the No-CD executable from our site for now](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE) and see if the game will launch for you. Maybe something went wrong during the vanilla game's installation.

If you can get the vanilla game to launch then you should be safe to download all the enhancement packages from our site afterwards.

**Comment by OmniNeosX** [comment]
So I tried that as well, just the original files with the enhanced executable added in but still the same result.

I suppose at this point I could try downloading the game somewhere since I have two real copies of the game anyhow?

**Comment by Polymega** [comment]
Do you mean you have two real copies of the PC version or just SH2 in general?

If you have a legitimate PC copy that would be odd if it's giving you troubles, as it's the online copies that usually cause problems (as they often include extra junk files that create conflicts).

If you right click `sh2pc.exe`, go to **Properties**, and select the **Compatibility** tab, can you check and see any/all compatibility options are disabled?

**Comment by OmniNeosX** [comment]
No no, I have the original PS2 and the HD Collection . I just don't have a CD Drive in my PC so I can't mount them.

Should I check that tab with the enhanced .exe or the original? And should I have the other EE files in the folder before checking?

**Comment by Polymega** [comment]
You can check the Compatibility tab using the EXE provided from our project page. The EXE that installs with the game has [SecuROM DRM](https://www.howtogeek.com/230773/how-to-play-pc-games-that-require-safedisc-or-securom-drm-on-windows-10-8.1-8-7-and-vista/), which Windows blocks, so it can't be used. (SecuROM was "a thing" back in the Windows XP days.) The EXE on our site provides a DRM-free ("no CD") version of the executable. 

And it wouldn't matter if the other EE files are in the directory. 

If anything, for right now, we need to get the vanilla game to launch for you without the EE files. Because if the vanilla game won't run, then our files on top of it won't make the game run, either.

**Comment by OmniNeosX** [comment]
I checked and none of the boxes are checked in the compatibility tab. So it's all on whatever is going on with the initial installation at this point.

I appreciate you trying to help this far in, thank you.

**Comment by Polymega** [comment]
No problem. We don't advocate getting a copy of the game online, but we understand we people do. You can try the version at MyAbandonware.

**Comment by OmniNeosX** [comment]
Funny enough, that's the version I downloaded. I usually don't support downloading games like this, but since the source was lost and I have two legitimate copies on disc for other systems, I feel that it's justifiable.

**Comment by OmniNeosX** [comment]
I've tried other options such as changing the Single Core Affinity and turning off the shaders but still no luck. Any chance that someone may have another idea?

**Comment by Polymega** [comment]
Have you tried starting over and just installing the base game with the cracked executable and seeing if the game will launch for you then? Maybe something went screwy with vanilla game's install and starting over might fix it.

**Comment by OmniNeosX** [comment]
I have tried that, although I never found this cracked file that I see mentioned. Any more info on that?

**Comment by Polymega** [comment]
The cracked executable is the one provided on our site; the no-CD EXE: http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE

Beyond that, I'm running out of ideas. My last suggestion might be trying to find another source for SH2 PC and seeing if that source's vanilla game will run for you (after replacing the executable with the cracked one).

**Comment by OmniNeosX** [comment]
Oh right. Then yes, we've tried it before. I'll try to find other sources and hopefully it'll work. Thank you for trying anyways.

**Comment by OmniNeosX** [comment]
I've got it figured out. Turns out it just didn't like being in my D: drive. I extracted the game and then all the files to my documents and now it works pretty well, I'd say.

**Comment by Psycho-A** [comment]
I have noticed that problems with black screen and other graphical artifacts are related to the use of integrated graphics cards such as Intel HD Graphics, as they often have stripped down 3D instructions. This usually applies to laptops and netbooks, but can also happen on stationary systems. Even very old, but full-format discrete graphics cards will work better in this case. Maybe disabling the UseD3D8To9 option might help somehow, but I'm not sure. Alternatively, you could also try the dgVoodoo2 D3D9 wrapper, as it solves some compatibility issues. Also, if your laptop has a dual graphics card, it's important to make sure it's the 3D-accelerated card used to run the game.
