### ISSUE TITLE
Problems with shadows

### ISSUE THREAD

**Issue by SONIC0798** [elishacloud/Silent-Hill-2-Enhancements#406]
![Screenshot 2021-03-28 16-36-50](https://user-images.githubusercontent.com/67099262/112754442-c8da5780-8fe4-11eb-9752-93c74ea3c2e9.png)
![Screenshot 2021-03-28 16-36-53](https://user-images.githubusercontent.com/67099262/112754447-d1329280-8fe4-11eb-8f88-aad4d0f8d1eb.png)
how can I solve this problem?

**Comment by Polymega** [comment]
[`FIxGPUAntiAliasing` fixes this.](http://enhanced.townofsilenthill.com/SH2/config.htm#FixGPUAntiAliasing)

Ensure you're using [the latest build of the SH2 Enhancements module](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) and that `FixGPUAntiAliasing = 1` in the `d3d8.ini` file.

**Comment by SONIC0798** [comment]
the game slows down a lot with this setting

**Comment by SONIC0798** [comment]
I solved the problem by disabling all anti aliasing settings in the NVIDIA panel

**Comment by elishacloud** [comment]
It would be good if you can figure out which option in the Nvidia Control Panel causes this issue.  It may give us clue to what the issue could be.

**Comment by Psycho-A** [comment]
> It would be good if you can figure out which option in the Nvidia Control Panel causes this issue. It may give us clue to what the issue could be.

Like I understood, he means the Anti-Aliasing override setting (multi-sampling values), and if some value if forced there, this leads these glitches... I can't say more as I never used GPU anti-aliasing anywhere...
