### ISSUE TITLE
Cursor issues

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#409]
1. The cursor doesn't use raw input, it has different ver and hor speeds. It's rather wonky, especially when moving diagonally.
2. The cursor is always present (map screen, main menu etc) even while using gamepad exclusively. Maybe add  hide cursor option to the ini file?

**Comment by Polymega** [comment]
Hi there,

For number 1, I don't think we have any plans to address this.

For number 2, we are working on a feature for this that will auto-hide the mouse after ~4 seconds of inactivity. 

I'm going to close this ticket early, but the second request will be a part of our next project update.

Thanks
