### ISSUE TITLE
Can't seem to enable White Shaders Fix.

### ISSUE THREAD

**Issue by JikissGamer** [elishacloud/Silent-Hill-2-Enhancements#41]
In the reveal trailer for the enhanced edition it shows the white shaders bug fix at the 8:09 mark: [https://www.youtube.com/watch?v=6v1USVhtfjQ&t=493s](url)

I've been getting this bug in my game in the room behind the clock in Woodside Apartment, on the door at Brookhaven hospital and in a number of other places. I can't seem to find the fix for this in the d3d8.ini file nor in any of the other ini files.

It looks like this
![white shaders bug](https://user-images.githubusercontent.com/42755022/45258848-70d79900-b385-11e8-81ee-2ea4221a4f5d.png)

**Comment by Polymega** [comment]
1) [Did you install WineD3D? ](http://enhanced.townofsilenthill.com/SH2/#installWineD3D)

2) [After temporarily disabling d3d8to9](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/27#issuecomment-416677796) for testing purposes, did you renable it?

**Comment by JikissGamer** [comment]
I have WineD3D installed, but when I enable d3d8to9 I get the runtime visual C++ error. And my PC won't let me install DirectX 9 SDK for some reason.

It gives me this error when i try to install it.
![snapcrab_noname_2018-9-8_17-3-20_no-00](https://user-images.githubusercontent.com/42755022/45259037-412a9000-b389-11e8-92cb-d7a90cb13cd6.png)

**Comment by Polymega** [comment]
WineD3D requires d3d8to9 to be activated to work, which will fix the white shaders bug. 

It seems you need the DirectX 9 SDK to be able to use d3d8to9. 

As for the installation error, what does the `DXError.log` and `DirectX.log` tell you?

**Comment by elishacloud** [comment]
@JikissGamer, I created a fix for the white shader issue.  You can download the fix here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2408426/d3d8.zip)

Note: this won't help with d3d8to9 or the DirectX 9 SDK, but it will allow you to play the game without seeing those annoying white shaders.

**Comment by elishacloud** [comment]
Closing this issue out since it is related to WineD3D and that is covered under #10.  @JikissGamer, if you are still having issues withthe latest fix above you can reopen this.
