### ISSUE TITLE
No Ambient Sounds

### ISSUE THREAD

**Issue by TimFlygare** [elishacloud/Silent-Hill-2-Enhancements#412]
Greetings. I'm not sure if this is an issue or just how the game is designed. Basically the game is dead silent when a music track isn't playing. No wind blowing or creaking or anything like that which is usually in horror games. Again if that's just how Silent Hill 2 is I've no problem with it, but it seems weird.

**Comment by Polymega** [comment]
It's hard to say without knowing which part of the game you're referring to, but it's likely that is correct behavior.

The music/sound director of the game was interviewed about his work on the series and, at one point, famously said, "silence is also a sound." (Which went on to be used in marketing campaigns, no less!)

**Comment by TimFlygare** [comment]
Basically everywhere but the last thing was a balcony between two apartments in blue creek. Complete silence even though it was outside. But I checked some youtube video and it seems to be how it's supposed to be.

**Comment by Polymega** [comment]
Okay great, glad to know there isn't any audio issues going on for you. I'll close this ticket out then. Feel free to re-open this if it turns out to be an audio issue, or you can make a new ticket.
