### ISSUE TITLE
SH2 Not working when installing Enhancement Edition Files 

### ISSUE THREAD

**Issue by GSilentBro** [elishacloud/Silent-Hill-2-Enhancements#413]
Hello all. I am trying to play Silent Hill 2 enhanced edition. 

I have the myabandonware.com clean files, and the game can run normally (I tested it) 

I follow the directions exactly as outlined on the enhanced installation page. http://enhanced.townofsilenthill.com/SH2/install.htm

Once I am done doing all the installing the game won't run!

I realized the reason it won't launch is step 3 INSTALL SH2 ENHANCEMENTS MODULE- and the three files d3d8.dll, d3d8.ini, and d3d8.res 

I am running windows 10, 3090 and 10900k. 

If I delete those three files the game can run!

I am not sure what is wrong. Do I need to install direct x8 as I've read? I at least narrowed it down to those files cause the game not to launch.

Thank you for the help! :)

**Comment by Polymega** [comment]
Hi GSilentBro,

When you attempted to launch the game while using the SH2 Enhancement module, did it produce a `d3d8.log` file in the game's directory? If so, can you upload it as an attachment here?

> Do I need to install direct x8 as I've read?

I don't think so, although Elisha would be better equipped to answer this.

**Comment by GSilentBro** [comment]
> Hi GSilentBro,
> 
> When you attempted to launch the game while using the SH2 Enhancement module, did it produce a `d3d8.log` file in the game's directory? If so, can you upload it as an attachment here?
> 
> > Do I need to install direct x8 as I've read?
> 
> I don't think so, although Elisha would be better equipped to answer this.

**Comment by GSilentBro** [comment]
PolyMega thanks for your reply. I have put back in the  three files d3d8.dll, d3d8.ini, and d3d8.res. I tried running the game and it just won't start even with all compatibility boxes checked etc. 

Here's a screenshot of the directory. I don't see a log to share d3d8.log sorry. 

If I delete the three files mentioned above, it  will launch. Strange. 

Thanks for any help. 


![directory](https://user-images.githubusercontent.com/82010955/113757467-a16c4480-96e0-11eb-8ce3-5946b75336fe.jpeg)

**Comment by Polymega** [comment]
Hmm... I'm not sure what's going on. [Someone else has recently submitted a ticket with a similar problem,](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/411) of which we have yet to find a solution for.

I'm sorry to say, but all I can think of is either trying reinstalling the base game again or, if you found this copy of SH2 on the internet, perhaps trying to find another source for it.

**Comment by elishacloud** [comment]
Try renaming `sh2pc.exe` to something else, like `sh2pc-new.exe` and then launching it.

**Comment by Polymega** [comment]
No follow-up so I'll close this ticket. Feel free to re-open for further troubleshooting.
