### ISSUE TITLE
Hospital map bug

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#417]
The map should indicate a door here:

<img width="1280" alt="Map" src="https://user-images.githubusercontent.com/41027064/114056475-00bd8680-9892-11eb-8a5b-3484aba0270d.png">

**Comment by Polymega** [comment]
Thanks for catching that! I have this corrected for our next project update. In the meantime, here is a "patch" of just this file for it to be replaced: [Brookhaven Hospital 1F Map Fix.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6282505/Brookhaven.Hospital.1F.Map.Fix.zip)
