### ISSUE TITLE
The game doesn't start

### ISSUE THREAD

**Issue by GhostRazgriz** [elishacloud/Silent-Hill-2-Enhancements#42]
First of all, congratulations for the great work they have done reviving this classic game of a lifetime.
As the title says the game doesn't start, I followed the installation of the page http://enhanced.townofsilenthill.com/SH2/index.htm step by step but after it is done it doesn't work.
The game before performing the installation of the files worked perfectly. I play from a laptop with the following characteristics:

Operating System: Windows 8 Enterprise 64-bit (6.2, Build 9200) (9200.win8_gdr.151112-0600)
Language: Spanish (Regional Setting: Spanish)
System Manufacturer: Acer
 System Model: Aspire V3-571G
BIOS: InsydeH2O Version 03.72.23V2.15
Processor: Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 CPUs), ~2.3GHz
Memory: 6144MB RAM
Available OS Memory: 5960MB RAM
Page File: 4075MB used, 8028MB available
Windows Dir: C:\Windows
DirectX Version: DirectX 11

And two Graphic Cards:
Card name:              Intel(R) HD Graphics 3000
Manufacturer:          Intel Corporation
Chip type:                Intel(R) HD Graphics Family
DAC type:                Internal
Device Type:            Full Device
Display Memory:     3687 MB
Dedicated Memory: 963 MB

Card Name:		   GeForce GT 630M
Direct3D level:	           11_0
CUDA Cores:	           96 
Central Clock :		   660 MHz 
Shading Clock:	   1320 MHz
Memory Data Speed: 1800 MHz
Memory Interface:	   128-bits 
Memory Bandwidth:   28.80 GB/s
Display Memory:	   3748 MB
Dedicated Memory:    1024 MB DDR3

I hope you can help me, I tried to start as an administrator and it did not work either.
greetings from Chile!

**Comment by Polymega** [comment]
Hi @GhostRazgriz ,

Could you please ZIP attach your `d3d8.ini` and `d3d8.log` file here exactly as you currently have it (where it crashes)? 

Also, you have two graphics cards and one of them is Intel HD Graphics 3000? Does this mean you are using a laptop then? If so, are you also using the WineD3D files?

**Comment by GhostRazgriz** [comment]
Here I attach the d3d8 files

Regarding if I used the Wine3D3 files, yes, I used them and also tried the other way, without them, I could not tell you if I have the "white shaders bug" after installing all the files because the game did not start with either of the two ways ... but before having installed everything, with the "normal game" I did have the "white shaders bug".
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2364436/d3d8.zip)

**Comment by AeroWidescreen** [comment]
Here's his d3d8 log for convenience:

> 11:01:29.139 Starting Silent Hill 2 Enhancements! v1.2.1260.0
> 11:01:29.139 Acer Aspire V3-571G V2.15 (Notebook)
> 11:01:29.139 Acer VA50_HC_HR Type2 - Board Version (Notebook)
> 11:01:29.139 Intel(R) HD Graphics 3000
> 11:01:29.141 Windows 8 64-bit (6.2.9200) 
> 11:01:29.141 Running from:  C:\Users\AccountName\Desktop\silent\Shd009\sh2pc.exe
> 11:01:29.141 Reading config file:  C:\Users\AccountName\Desktop\silent\Shd009\d3d8.ini
> 11:01:29.142 Loading as dll: d3d8.dll
> 11:01:29.146 Wrapper created for d3d8.dll
> 11:01:29.259 Hooking the FileSystem APIs...
> 11:01:29.263 DisableCDCheck Error: Could not find CD check function address in memory!
> 11:01:29.524 Updating SFX memory addresses...
> 11:01:29.530 Updating sddata.bin pointer memory addresses...
> 11:01:29.532 Setting PS2 Style Noise Filter...
> 11:01:29.533 Increasing the Draw Distance...
> 11:01:29.714 Setting Cemetery Lighting Fix...
> 11:01:29.716 Setting Rowboat Animation Fix...
> 11:01:29.740 Updating the Catacomb Meat Cold Rooms color...
> 11:01:29.744 Disabling Red Cross health indicator during cutscenes...
> 11:01:29.744 Loading the Nemesis2000 Fog Fix module...
> 11:01:29.746 Loading the WidescreenFixesPack and sh2proxy module...

Looks like he's having trouble when the widescreen fix is loaded, but I'm not entirely sure how to interpret this log like elishacloud does.

**Comment by Polymega** [comment]
Thanks, Aero. 

@GhostRazgriz , if you set `SingleCoreAffinity = 0` does the game boot up then?

**Comment by Polymega** [comment]
Also, did you wait at least 60 seconds after launching the game to see if it runs?

**Comment by Polymega** [comment]
@AeroWidescreen did the other person who had running issues when using the WSF also run it on Windows 8? I'm curious if that's the common denominator here or something else such as a virus protector preventing the game from starting.

**Comment by AeroWidescreen** [comment]
You mean @Smersh12? According to his d3d8 log, yes:

> 12:22:54.782 Windows 8 (6.2.9200) 

I still think that people should either disable their anti-virus or add an exception to the install folder until we can get this sorted, at least when troubleshooting.

**Comment by GhostRazgriz** [comment]
Well, I installed everything again, step by step and ... nothing ... I have and I had the antivirus and the firewall disabled in the whole process so I really don't know what could be the problem =/

**Comment by GhostRazgriz** [comment]
Well, now everything works perfectly!, the Scripts uploaded by @AeroWidescreen worked perfectly, solving both the vertical edges and the looping sound that sometimes occurred. (I don't change nothing respect to Core Afinnity this time.) 

>  https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/22#issuecomment-416113338

Now my only problem is the "The White Shades Bug" this... just persist but all the rest is Ok ;)

**Comment by Polymega** [comment]
Good! You can try and use WineD3D again to solve the white shaders issue as well. Ensure `d3d8to9 = 1` and place the WineD3D files in the game's main directory.

**Comment by Polymega** [comment]
@elishacloud worth noting that GhostRazgriz was able to load the WSF when called externally through the `\scripts` folder.

**Comment by GhostRazgriz** [comment]
This time I decided to play with the Intel HD Graphics configuration (the d3d8 log take information of this card as I see) so I did not install the Wine3d3 files mmm... Should I reinstall the game with the WineD3D files? in addition to the Scripts folder

**Comment by Polymega** [comment]
Oh! I didn't know you can change them. 

If you use Intel HD Graphics you don't need WineD3D as the white shaders bug doesn't happen with that GPU. 

You only need it for Nvidia cards.

**Comment by GhostRazgriz** [comment]
Okay, so I will make the change regarding the WinD3D files because the white shaders persist, give me a couple of minutes and I tell you how it goes.

**Comment by GhostRazgriz** [comment]
DONE!!! thank you so much @Polymega @AeroWidescreen 
Now everything works perfect !!!
I hope you keep moving forward with this great project that is becoming more and more spectacular, really thank you very much for all the time dedicated to solving the problem, I am very happy that you not only have affection for the game but also with the community that there is behind him, much success in everything for you, you are a great team!
You can close the topic.
Greetings from Chile!

**Comment by elishacloud** [comment]
This issue has been resolved.  Closing.
