### ISSUE TITLE
Menu Background and Sprites Problem

### ISSUE THREAD

**Issue by kyle-radames** [elishacloud/Silent-Hill-2-Enhancements#420]
I would like to share an issue here.

The menu backgrounds aren't in the correct size, they are tiny, and gone to the superior left corner of the screen.
![image](https://user-images.githubusercontent.com/82281596/114278453-4ef39680-9a06-11eb-997f-77bc678c4a81.png)
Also, the game sprites (mainly the inventory images and font sprites), are invisible.

I don't know how to fix this, I tried everything. Reinstalled the game and the archives, changed inumerous settings in d3d8.ini, changed resolution settings in game, tried another versions and etc. But the bug still persists.
I have Direct X9 in my system, and the latest version of Microsoft Network. The executable is withouth any currently active properties in the property window.

My operational system it's a windows 10 32 bits.

Here it's my log: 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6290374/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

It looks like you're running the game using an integrated graphics processor (IGP). We don't recommend using IGPs with our project. We've had reports in the past that older IGPs can't handle the high resolutions of the upscaled images. 

It can be hard to find specs on IGPs, especially older ones, but it appears the Intel R 4 chipset isn't ideal for gaming: https://forums.tomshardware.com/threads/mobile-intel-r-4-series-express-chipset-family-any-good-for-gaming.781454/

Have you tried running the game without the upscaled images? Remove these folders to remove the upscaled images:

```
\sh2e\menu\
\sh2e\pic\
```

**Comment by kyle-radames** [comment]
Ok, I'll remove the upscaled Images, I didn't want to do that, to not loose the quality, but don't have another way.

I already knew that the problem was with my machine. My PC died, this laptop that I'm using it's terrible. I just wanted to confirm that the fault is really of my cheap device.

Thank you by the answer :)

**Comment by Polymega** [comment]
> (And I think that would be cool, to put an advice (if you don't already putted it) about IGP issues. To spare future players of this type of problem.)

We don't specifically mention the issue with high res images and IGPs because we don't recommend IGPs to begin with under system requirements:

http://enhanced.townofsilenthill.com/SH2/#systemreq

And while not specifically about high res images, we talk about not using IGPs here as well:

http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general
