### ISSUE TITLE
Alternate hospital M4 room nurses bug

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#421]
There are two nurses in this room (on hard at least), if you exit and re-enter they will be gone.
This happened to me but I don't know if this was a one time bug or whether this can be reliably reproduced.

**Comment by Polymega** [comment]
Sorry, I somehow missed this. There are a couple other areas in the game where I distinctly remember an enemy will be in the room and, if you leave and re-enter, they may disappear. The prison room with the "Little Baroness" memo is one such example. I'm going to go out on a limb and say this is "normal" behavior and will consider it a non-issue. I'll close this ticket out but thanks for bring it to our attention all the same.
