### ISSUE TITLE
Another missing door (prison B1F)

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#422]
<img width="776" alt="Untitled" src="https://user-images.githubusercontent.com/41027064/114470100-99376c00-9bee-11eb-808a-5a910324f36e.png">

**Comment by Polymega** [comment]
I believe this is one of those "spooky" doors; one that shouldn't be there. I say this as there's no room drawn past this boundary, and the original map doesn't have a door here either:

![image](https://user-images.githubusercontent.com/27395260/114471925-5c07b580-9bbf-11eb-9f36-22f009ce833d.png)

This door is akin to the door that appears at the end of the "M" hallway on Brookhaven's 2F after speaking with Leonard on the phone.

**Comment by Arthandas** [comment]
Yes, I know what you mean, case closed :)
