### ISSUE TITLE
Killing the "Ritual" guys with the shotgun makes them scream very loud

### ISSUE THREAD

**Issue by The-King-of-Toasters** [elishacloud/Silent-Hill-2-Enhancements#426]
Another loudness bug. Shooting them with the pistol/rifle plays their pain sound, but shooting them with a shotgun plays the same sound but louder. [Example here](https://www.sgregoratto.me/paste/sh2/shotgun-ritual.mp4).

**Comment by Polymega** [comment]
Likely relates to audio positioning with DSOAL. With your second shot, the ritual monster was closer to the floor and DSOAL may think he's a lot closer to the camera than it really is.

**Comment by The-King-of-Toasters** [comment]
I tested this again, this time with the shotgun and then rifle. Again, the shotgun sound was much louder.

**Comment by Polymega** [comment]
Thanks for letting us know about this but I'm going to make the call to not worry about this.
