### ISSUE TITLE
Some help with re4HD Project

### ISSUE THREAD

**Issue by albertre4HD** [elishacloud/Silent-Hill-2-Enhancements#427]
Hello to all SH2 Enhanced Edition Team!
Sorry, I couldn't find another way to contact you...

I'm Albert from the "resident evil 4 HD project" (www.re4hd.com)
I was wondering if you know someone who could help us to fix some technical issues the PC port of re4 has (some broken effects, some sound issues, the limitation with the video codec and video resolution this game has, some memory and polygonal limitations, animation issues and a huge etc, etc...)

No need to say I'm amazed by all the work you've done so far and the level of perfectionism in order to achieve the perfect SH2 experience. And I'm aware you must be really busy. That's why I'm asking if you know some reliable person that would be interested in helping us.

I'm not sure if you are aware about our project, but as you can see I'm specialized on the texture part of the project. So, If there's something I can do for you in exchange I'm open to that idea, too.

In any case, thanks for your hard work and have a great day!
Albert

**Comment by GlitchyReal** [comment]
I certainly hope someone on the SH2:EE team answers this call for legend-to-legend collaboration!

**Comment by umbrellacorp53** [comment]
> I certainly hope someone on the SH2:EE team answers this call for legend-to-legend collaboration!

I know. I about fell out of my seat when I saw this post. I really hope there is some collaboration as well. Both projects could definitely benefit. RE4HD has some amazing texture work, Maybe a private email would be best? Anyone? I don't dare ping anyone from the team lol.

**Comment by elishacloud** [comment]
Hello, thanks for reaching out.  I have been aware of your project for a while.  It is nice to see what you have done so far!

I cannot speak for anyone else on the team, but I already have too many things I am working on and do not have time to add anything else to my list at this time.  However, you may want to try reaching out some of the other people on the [credit](http://www.enhanced.townofsilenthill.com/SH2/credit.htm) page.  Most of the modders I have worked with have somehow ended up on that page.

**Comment by albertre4HD** [comment]
Thanks a lot for answering me :)
Yeah, I'm aware these projects are really time-consuming, specially when we do them during our free time (if it's also your case)

Sure I'll do that. Fortunately during the last hours I've received an offer of help! (not confirmed yet, but I have high hopes) but no doubt I'll reach your team if extra help is needed.
Thanks for letting me know how to proceed!

I wish you the best luck and success with this phenomenal SH2EE and any future projects :D

Best regards,
Albert

**Comment by Polymega** [comment]
Hi Albert,
... and CONGRATULATIONS!!!! I'm so happy you guys released your amazing project to so much love and fanfare. It deserves nothing but admiration! I saw nipkow and emoose were able to help you guys to the finish line as well. 😊

I'll close this ticket out but, again, I'm so happy for you and your team!
