### ISSUE TITLE
Cant Select Disk 2

### ISSUE THREAD

**Issue by indychick1977** [elishacloud/Silent-Hill-2-Enhancements#428]
I am a noob when it comes to installing games like this, I am going through the installation and its asking for disk2 for the data3.cab. I select the folder where disk 2 is located however it tells me setup could not find file on that path, i can not complete the install. Can anyone help me get past this issue, How do I select that file?

**Comment by Polymega** [comment]
Hi indychick,

To virtually install the game (as in, install it without the physical discs but spoof your computer into thinking it's installing off of discs) all three discs need to be packaged in a format that works with virtual disc mounting. 

You know how people often say they have an ISO of a disc? ISO is a format (.iso) that contains ripped information off of a disc; it's all contained within that one .iso file. There are other formats that can work too, such as .bin and .daa, I believe.

For SH2 PC, you would need all three discs in ISO (or other acceptable) format, so you would have three different ISO files (one for each disc). 

[Windows 10 has a built-in disc mounting feature.](https://www.howtogeek.com/howto/windows-vista/mount-an-iso-image-in-windows-vista/) With this, you would right click the Disc 1 ISO and tell Windows to "mount" the disc image. Windows will create a virtual (fake) disc drive and read the ISO file as if it was actually on a disc. This allows you to run the installation disc.

As you install the game, the game will then ask you to insert Disc 2. So you would "eject" (unmount) Disc 1 that you virtually mounted and right click on Disc 2's ISO to mount that one. The game will then eventually ask you to insert Disc 3. Rinse and repeat the process.

Hope that helped some.

**Comment by AeroWidescreen** [comment]
I had an entire explanation written up, but Polymega beat me to it, so I'll just supplement his reply with example screenshots.

These are what disc images look like. They might be named something else for you, but it doesn't matter. They're usually ISO or IMG files.
![Disc Images](https://i.imgur.com/Ez6tFmS.png)

This is how to mount them in Windows 10.
![Mount](https://imgur.com/pG738ZS.png)

And lastly, this is what a virtual disc drive looks like. You select this when the installer asks you to insert another disc,
![Disc Drive](https://imgur.com/UQcCfts.png)

**Comment by indychick1977** [comment]
Thank you! This helped!
