### ISSUE TITLE
Are reflective surfaces already restored?

### ISSUE THREAD

**Issue by RypherSogun** [elishacloud/Silent-Hill-2-Enhancements#429]
![fc8045016cd2a8d2b0b2aaab9180194c](https://user-images.githubusercontent.com/13190944/116735287-f6a52880-a9f6-11eb-96a0-f7f46b8b73fc.png)

**Comment by elishacloud** [comment]
Yes, we added specularity throughout the game in the latest release.  This is why you see the extra reflections.

**Comment by AeroWidescreen** [comment]
It has been restored, although the walls in that hospital room don't have the specular highlight shown in your screenshot. That seems to be exclusive to the PS2 version. I don't know if there's a technical reason for this or if it was an oversight by @FrozenFish24 @Polymega.

**Comment by Polymega** [comment]
Sorry, I must've missed this.

The code for that reflection and the ones on the town store windows at night were either disabled or removed when Team Silent ported it to Xbox. With the PC build being based off the Xbox version, it's almost removed here.

They have not been added back yet. We're not sure if they can be added back at this time, but it's known and being looked into as time permits.

**Comment by RypherSogun** [comment]
thanks for answering
