### ISSUE TITLE
Flashlight's star burst texture gone?

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#430]
@AeroWidescreen @Bigmanjapan can you test if this also has happened to you? I'm not sure what happened or when this changed, but I no longer see the "star burst" light texture from the flashlight.

![Untitled-1](https://user-images.githubusercontent.com/27395260/117483433-b3d1dc00-af33-11eb-9427-2868e1f969e5.gif)

I used various builds, including the previous two public release builds; disabled just about every option in the ini; disabled the sh2e folder; disabled AA solutions through my GPU's control panel; and nothing seems to bring the star burst texture back for me.

I then went back to pure vanilla and it works there, but its buggy as it originally was. I thought maybe something broke for [FogLayerFix](http://enhanced.townofsilenthill.com/SH2/config.htm#FogLayerFix) (formerly Fog2DFix) but that doesn't look to be the case. Is this another Nvidia-specific bug? Do you see the star burst with your AMD card, Aero_?

Also @elishacloud the screenshot taker is no longer working for me with any of the builds. I had to get creative to take the screenshot above. Related? Very confused...

**Comment by Polymega** [comment]
The flashlight textures and screenshot taker work on my laptop, even with build 1909. Laptop uses IGP. It might be an Nvidia thing again. Looks like an update to Nvidia drivers may have bungled things up. 

![Screenshot 2021-05-07 13-13-55](https://user-images.githubusercontent.com/27395260/117485615-92262400-af36-11eb-9c05-f905bc86d3b9.png)

**Comment by Polymega** [comment]
Tested on my old Win7 desktop that uses Nvidia and it still works there. The Nvidia control panel on my Win7 desktop is version 430.60 there. On my Win10 desktop the Nvidia CP is version 456.71.

Not sure if I'm looking in the right spot, but this might be the API log for the flashlight texture, which is reporting errors on my Win10 machine:

![image](https://user-images.githubusercontent.com/27395260/117498523-e7b6fc80-af47-11eb-9fbe-e1c955a15350.png)
![image](https://user-images.githubusercontent.com/27395260/117498737-319fe280-af48-11eb-9d58-67abc2d7836c.png)

**Comment by AeroWidescreen** [comment]
It's still there on my end. 
![flare](https://i.imgur.com/HEI1Jra.png)

> The Nvidia control panel on my Win7 desktop is version 430.60. On my Win10 desktop the Nvidia CP is version 456.71.

Might be the driver then. Only way to know for sure is by downgrading your Win10 desktop.

**Comment by Polymega** [comment]
> Might be the driver then. Only way to know for sure is by downgrading the driver on your Win10 desktop.

What confuses me is that I haven't updated my Nvidia driver in Lord knows how long. Went to try and roll it back and I can't. Says it was last updated September of 2020. No clue...

![image](https://user-images.githubusercontent.com/27395260/117504097-ed184500-af4f-11eb-8488-b00c281f32e2.png)

**Comment by Polymega** [comment]
Thanks for the suggestion. I just did this, except I instead upgraded to a newer version (462.31 studio driver) and it didn't fix the issue. 

Nvidia's official site only goes back to driver 461.40 for my GPU (before this update I was running 456.71). I don't want to grab an older Nvidia driver from a non-Nvidia source. That, and if I'm now experiencing this issue then there's a chance others are also experiencing it. So I'm curious to see if there's a non-rollback-driver solution to this.

**Comment by AeroWidescreen** [comment]
You could also try upgrading the driver on your Win7 computer, assuming that's still possible 😛. But yeah, this sounds like an issue Elisha will have to address.

**Comment by Polymega** [comment]
Very quick tests and everything looks great now. Thanks, Elisha!
