### ISSUE TITLE
Windows 10 -- Superantispyware considers DSOUND.DLL from the Enhanced Audio pack a trojan??

### ISSUE THREAD

**Issue by mojius** [elishacloud/Silent-Hill-2-Enhancements#431]
Scanning my PC with SuperAntiSpyware and it labeled this DLL as:
Trojan.Agent/Gen-MSFake[Gen]
	C:\USERS\MOJIUS\DESKTOP\SILENT HILL 2 DIRECTOR'S CUT - PC\DSOUND.DLL

Like, I know the hard-working devs on the team aren't trying to give me a trojan, but I'm jut wondering. I downloaded from http://www.enhanced.townofsilenthill.com. Was that the legit site?

**Comment by elishacloud** [comment]
Yeah, its a false positive.  I complied the `dsound.dll` code myself from this repository [here](https://repo.or.cz/dsound-openal.git).

> I downloaded from http://www.enhanced.townofsilenthill.com. Was that the legit site?

Yes, that is a good site and is maintained by @Polymega and is the official site for this project.

**Comment by mojius** [comment]
Thank you both so much. Keep up the good work.
