### ISSUE TITLE
Black Screen on startup 

### ISSUE THREAD

**Issue by LoadingLoadin** [elishacloud/Silent-Hill-2-Enhancements#434]
Hi all, am currently trying to play the game, but get stuck on a black screen during boot. It then stops responding and I have to close the exe. I have made sure the folder is excluded from anti-virus, and have disabled all compatibility mode from Windows. Any help would be very much appreciated :)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6528263/d3d8.log)

**Comment by Polymega** [comment]
Hello,

You're using a very old version of this project's main module. Try using the latest version: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.8.1900.0

If you last used our project a long time ago note that a lot has changed, including what additional, external packages we've dropped or are now using. Double-check the game's directory and make sure you only have the following files/folders within it: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

You may want to play things safe and download all the other enhancement packages from our website as well to ensure you're using the latest ones.

**Comment by LoadingLoadin** [comment]
So I did as you said, and I completely re-installed everything. I checked the log and have a slightly different outcome, but still cannot boot the game. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6528557/d3d8.log)

**Comment by Polymega** [comment]
Try this next:

- Remove `dsound.ini` and `dsound.log` from the game's directory and see if the game will launch for you then.

If not:

- Move the entire game folder to another drive on your computer, such as your C:\ drive, and see if the game will launch for you then.

**Comment by LoadingLoadin** [comment]
It worked! Moving it to my external drive for some reason fixed it. Not the first time this has happened either, same thing occurred with Devil May Cry 4. Strange, but at least I can finally play. Thanks for the help!
