### ISSUE TITLE
My menu screen looks like this

### ISSUE THREAD

**Issue by saracatunga123** [elishacloud/Silent-Hill-2-Enhancements#435]
https://imgur.com/jnAP57p
When i start the game it shows the konami screen like normal and then the menu screen shows up like this. I can move and hear the buttons sounds, and the settings menu works well. Already reinstalled the game and patch 4 times and it still doesn't work. 
Thanks for all your hard work. :)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6557495/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

Your issues seem to mirror what other people experience when playing the game using older/weaker integrated graphic processors (IGPs). See here:

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/420

I did a quick Google search of your Nvidia GeForce 210 graphics card and it seems to be universally disliked for gaming. There's a chance this GPU can't handle the very high resolutions of the upscaled texture files. If this is the case, you might not be able to view the high resolution font, either. See here:

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/299
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/264
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/240
- 

You can disable the upscaled textures by opening the `d3d8.ini` file and adding the following **to its own line** in the file:

`UsePS2LowResTextures =  1`

This will disable the upscaled images. If it also turns out you can't see the high res font, you can disable this too by opening the `d3d8.ini` file and finding `UseCustomFonts` and disabling it (by changing it to `UseCustomFonts = 0`).

Hope that helps

**Comment by saracatunga123** [comment]
I tried what you said and also deleted the upscaled menus and fonts and now it looks like this
https://imgur.com/a/qB6teRX

**Comment by saracatunga123** [comment]
I guessed what to press an actually managed to start a game and it works pretty good but the icons in the inventory are invisible as well

**Comment by Polymega** [comment]
To play things safe, close the game and go to the game's directory **and fully delete these folders:**

```
\sh2e\menu\
\sh2e\pic\
```

Does the main menu display correctly for you then?

**Comment by saracatunga123** [comment]
i did that previously and it started looking like that https://imgur.com/a/qB6teRX

**Comment by Polymega** [comment]
Hmm... I'm not sure then. The symptoms of the issue seem to mirror when people who are using older IGPs try to use the upscaled images, but you're saying you also experience it when using the original, low res texture. 

We may need to get @elishacloud's opinion on this.

**Comment by elishacloud** [comment]
Try setting `ScreenMode = 3`.  Also, go into the options menu and use a smaller resolution.

**Comment by saracatunga123** [comment]
Tried that and it still looks the same

**Comment by elishacloud** [comment]
1. Does the game work ok without the enhancement module? If you rename `d3d8.dll` to `d3d8.old` does the game work ok?
2. Does this issue only happen on the menu items?  Does the game play work fine?

Try disabling the following:  `d3d8to9` and `WidescreenFix`

**Comment by saracatunga123** [comment]
Tried the game without the enhancements and it works well and the problem its only with menu items, also i can't see the inventory icons and map.

Also tried disabling that and it looks the same

**Comment by elishacloud** [comment]
Ok, I am guessing it has something to do with an incorrect or non-supported vertex.  Try disabling all the following options.  All of these affect the vertices:

* FixGPUAntiAliasing
* FixDrawingTextLine
* EnableSoftShadows
* SetBlackPillarBoxes
* AdjustColorTemp
* EnableSMAA
* RestoreBrightnessSelector

**Comment by saracatunga123** [comment]
Still the same

**Comment by Polymega** [comment]
In the `d3d8.ini` file, under the `[ADVANCED OPTIONS]` header, find and set `UseCustomModFolder = 0`. Does the main menu, map, and inventory work for you then?

**Comment by saracatunga123** [comment]
Tried it and

This is the map: https://imgur.com/a/ivQaPYK

And i still can´t see the items in the inventory: https://imgur.com/InaCpB2

**Comment by AeroWidescreen** [comment]
> Tried the game with and without the enhancements and it works well and the problem its only with menu items, also i can't see the inventory icons and map.

To be perfectly clear, you're saying that _without_ the enhancement module (d3d8.dll) installed, you can see the menu items, inventory icons, and map? _Everything_ works, correct?

If this is true, try using this file:
[d3d8.ini](https://mega.nz/file/IaokyRZI#ITmZa1fEYLwmf-3yZM9C8Byvj9oQ0ewFNCu4PbkscAU)

Replace your **d3d8.ini** file with the one provided above. Backup your file if you don't want to lose your existing settings.

**Comment by saracatunga123** [comment]
It looks the same but in a small window

**Comment by elishacloud** [comment]
Try with this ini file.  If it does not work, please upload your log file.  Thanks!

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6564008/d3d8.zip)

**Comment by saracatunga123** [comment]
Still looks the same
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6564109/d3d8.log)

**Comment by AeroWidescreen** [comment]
> It looks the same but in a small window

Wow. My idea was to disable almost everything possible. Maybe there was a feature not being accounted for, or maybe you weren't disabling them correctly, but this has made absolutely no difference to your problem. Hopefully Elisha will be able to help you, because I'm officially stumped on this.

**Comment by elishacloud** [comment]
> My idea was to disable almost everything possible.

That was my idea also.  However, I still noticed two things in the log file:

```log
5072 03:02:17.996 Set map scaling!
5072 03:02:17.996 Set texture scaling!
```

I tracked both of these down to the `FullscreenImages` option and noticed that this option was somehow missing from the ini file.

@saracatunga123, can you try one more time with this ini file:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6565730/d3d8.zip)

**Comment by saracatunga123** [comment]
It finally works, thank you so much guys! And sorry for the trouble

**Comment by elishacloud** [comment]
@saracatunga123, if you would not mind troubleshooting this a bit with me I want to figure out why that option is having an issue.

Can you try with this update and send me the log files:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6567423/d3d8.zip)

**Comment by saracatunga123** [comment]
With this the menu screen was all black on a small window
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6567561/d3d8.log)

**Comment by elishacloud** [comment]
> the menu screen was all black on a small window

Yes, that is what I want.  Here are the lines that are strange:

```log
7376 00:29:07.797 CheckLoadedTexture data/pic/etc/start00.tex 512x512 0 0
7376 00:29:07.930 CheckLoadedTexture data\pic\etc\start01e.tex 512x512 0 0
```

This should be saying `512x512 4 4` not `512x512 0 0`.

Can you zip up and attach the following two files:

1. C:\Program Files\Konami\Silent Hill 2 - Directors Cut\data\pic\etc\start00.tex
2. C:\Program Files\Konami\Silent Hill 2 - Directors Cut\data\pic\etc\start01e.tex

**Comment by saracatunga123** [comment]
I don´t have the file start01.tex so i attached the ones that i had
[start00.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6567988/start00.zip)

**Comment by elishacloud** [comment]
Thanks.  Those files seem fine.  For some reason the module is not able to get the resolution of those textures on your computer.

I added some more logging.  Can you try with this one and send me the log file:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568032/d3d8.zip)

**Comment by Polymega** [comment]
Thanks for taking the time to do this, @saracatunga123. This isn't an issue happening to us, so we aren't able to test any solutions for it. Your help here may ensure this never happens to anyone again.

**Comment by saracatunga123** [comment]
@Polymega I'm glad i could help!

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568075/d3d8.log)
Tried it and it looks exactly the same as before, the menu and FMVs are a black screen, and i cant see the icons and the map

**Comment by elishacloud** [comment]
Ok, I found the line of code that is failing.  I added more logging to try and figure out why it is failing.

Can you try again with this one and send me the log file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568280/d3d8.zip)

**Comment by saracatunga123** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568422/d3d8.log)
Here it is

**Comment by elishacloud** [comment]
Ok, I see what is happening.  I believe this one should solve the issue:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568494/d3d8.zip)

Let me know the results.  If it works I can send you a new build with the logging disabled.

**Comment by saracatunga123** [comment]
Now it looks like this
https://imgur.com/fP3e9tR
https://imgur.com/HitPceB

**Comment by elishacloud** [comment]
Ok, there may be other issues going on.  But before we test that out please redownload and install the `Enhanced Edition Essential Files` and the `Image Enhancement Pack` updates from [here](http://www.enhanced.townofsilenthill.com/SH2/install.htm).

If there are still issues after that please upload your log file again.

**Comment by saracatunga123** [comment]
Redownloaded the files and everything and looks exactly the same

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6568900/d3d8.log)

**Comment by elishacloud** [comment]
Thanks for your help so far.  If you don't mind we will need a little bit more troubleshooting.  It looks like the first issue is solved but now there may be an issue with `UseCustomModFolder`.  Can you disable `UseCustomModFolder` and let me know the results?

**Comment by saracatunga123** [comment]
Here it is, i could see the menu and the icons but i couldn't see the FMVs
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6572419/d3d8.log)

**Comment by elishacloud** [comment]
The FMV issue may be related to the same issue.  I added a bunch of logging to the custom mod feature.  Can you try with this one and send me the logs:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6572492/d3d8.zip)

**Comment by saracatunga123** [comment]
Looks like before with the bugged menu and icons
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6572598/d3d8.log)

**Comment by elishacloud** [comment]
Ok, I think I see what is happening here.  Try this one and let me know how it works:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6572649/d3d8.zip)

**Comment by saracatunga123** [comment]
Exactly the same as before
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6573008/d3d8.log)

**Comment by elishacloud** [comment]
It is still failing in the same function.  I added more logging to see why it is failing.  It should not be failing there.

Please try this one and upload the log files:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6573143/d3d8.zip)

Thanks for your continued support here!  I will get to the bottom of this soon!

**Comment by saracatunga123** [comment]
It's no problem, i'm glad i could help!
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6573204/d3d8.log)

**Comment by elishacloud** [comment]
Interesting.  The error message you are getting is this:

```log
Code: 998 Message:"PathFileExistsA failed with error 998: Se realizó un acceso no válido a la ubicación de memoria.
```

This is a Windows error and indicates an issue with Windows.  See [here](https://fliphtml5.com/pkypd/gcba/basic) for more details.

However, I tried using a different Windows API to see if that helps.  Here is an update to try.  Please attach your logs again:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6573320/d3d8.zip)

**Comment by saracatunga123** [comment]
Looks the same but i can see the FMVs, i updated some drivers and followed the guide you sent me don't know if i fixed anything
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6573494/d3d8.log)

**Comment by elishacloud** [comment]
> Looks the same but i can see the FMVs

Yeah, the FMVs had the same issue as the menu texture that I fixed back near the top of the thread.  I fixed this in my last update.

> i updated some drivers and followed the guide you sent me don't know if i fixed anything

It doesn't appear that anything is fixed here.

I am trying a different approach for this.  Try this new update and send me the log files:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6575231/d3d8.zip)

**Comment by saracatunga123** [comment]
Wow it actually works! It's the first time i see that menu screen in my life.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6580881/d3d8.log)

**Comment by elishacloud** [comment]
Great!  I removed the logging and cleaned up the code a bit.  Here is the latest update.  Let me know how this works:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6581458/d3d8.zip)

**Comment by elishacloud** [comment]
@AeroWidescreen, The fix I put in will only fix this for textures and videos.  The issue with the main menu had to do with incorrect scaling because of a texture issue.

I did a quick look at the custom font code and it does not appear like the same issue would happen here.  I would need to troubleshot that issue with someone who has the issue.  I have a iGPU and it works fine for me...

**Comment by saracatunga123** [comment]
@elishacloud Works great. thanks!

**Comment by elishacloud** [comment]
Very good.  The official fix for this will be in the next update.  However, you can use the latest build I gave you.  Should be a good stable build.  Thanks for your help and patience here.
