### ISSUE TITLE
Save file damaged

### ISSUE THREAD

**Issue by lesa021** [elishacloud/Silent-Hill-2-Enhancements#436]
I was playing and all the sudden my PC restarts and when i tried to load the save file it says save folder damaged.
Is there anyway to fix this without deleting the save file since i have 3 hours of gameplay on it?

**Comment by AeroWidescreen** [comment]
Don't think so, no. Sounds like your **sh2pc.sys** file got corrupted, in which case there's no way to recover that AFAIK.

**Comment by Polymega** [comment]
Yeah, sorry to say if it becomes corrupted you can't recover it. Here are steps to remove the corrupted files to start fresh though: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#i-cannot-save-my-game-progress

**Comment by lesa021** [comment]
Well that sucks, Thanks for the help for removing the corrupted files though
