### ISSUE TITLE
Hospital Box Broken

### ISSUE THREAD

**Issue by lewdking** [elishacloud/Silent-Hill-2-Enhancements#438]
So, the mod has been working great up until just now. I can't use the box whatsoever. I've looked for other instances of this occurring but have found none. I was able to use both keys on it but there was no change at all. I have tried restarting the game multiple times but with no luck. Loading a previous save file also does not help. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6692017/d3d8.log)

![](https://cdn.discordapp.com/attachments/807713742065893435/856781774347436072/image0.jpg)

**Comment by Polymega** [comment]
Are you using the Image Enhancement Pack? If so, the first thing I'd try is re-downloading that package and replacing all of its files:
http://enhanced.townofsilenthill.com/SH2/install.htm#installImageEnhancementPack

**Comment by lewdking** [comment]
Reinstalling the image enhancement pack fixed it. Thanks so much!
