### ISSUE TITLE
Bizarre lighting when using flashlight

### ISSUE THREAD

**Issue by Deeruss** [elishacloud/Silent-Hill-2-Enhancements#443]
I copied all files extra as described straight into my original file - does anyone have any idea what could be wrong??
Would really appreciate any help :)

This is with the flashlight:
![With flashlight](https://user-images.githubusercontent.com/87249313/125179091-5ce7cc00-e22e-11eb-8778-046c9e284c55.png)
This is without the flashlight:
![Without flashlight](https://user-images.githubusercontent.com/87249313/125179230-11362200-e230-11eb-8156-419018bdf96e.png)

And even when the flashlight is on the mannequin it does the same thing:
![Mannequin with flashlight](https://user-images.githubusercontent.com/87249313/125179131-b18b4700-e22e-11eb-98a5-a644873b181b.png)

This is the flashlight in my original copy:
![Original game](https://user-images.githubusercontent.com/87249313/125179222-eb108200-e22f-11eb-895e-63d8f9bf7917.png)

Everything else works amazing - love the updates - just isn't the same without the flashlight :(

**Comment by Deeruss** [comment]
Sorry here is my d3d8 file
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6796197/d3d8.log)

**Comment by Polymega** [comment]
Sorry you're having issues with the flashlight. This is a (very) rare bug that only happens to a (very) small amount of GPUs. To fix this, open the `d3d8.ini` file and set `d3d8to9 = 0`. 

Just note that disabling `d3d8to9` will also disable the [AdjustColorTemp](http://enhanced.townofsilenthill.com/SH2/config.htm#AdjustColorTemp), [EnableSMAA](http://enhanced.townofsilenthill.com/SH2/config.htm#EnableSMAA), and [RestoreBrightnessSelector](http://enhanced.townofsilenthill.com/SH2/config.htm#RestoreBrightnessSelector) shaders.

Elisha, for our records, they are using AMD Radeon Vega 8 Graphics.

**Comment by Deeruss** [comment]
No worries appreciate your help - that worked perfectly.

Its just the capabilities of my PC making this an issue would you say?

**Comment by Polymega** [comment]
It's a compatibility issue with certain graphics processors and the code that makes up [d3d8to9](https://github.com/crosire/d3d8to9). It's something Elisha said he'd like to look into at some point, but it affects so few people that it's never been a high priority for us.

**Comment by AeroWidescreen** [comment]
> It's a compatibility issue with certain graphics processors and the code that makes up [d3d8to9](https://github.com/crosire/d3d8to9). It's something Elisha said he'd like to look into at some point, but it affects so few people that it's never been a high priority for us.

This, and also the fact that laptops with integrated graphics aren't really recommended for gaming. They heat up very quickly, have to rely on slow system memory, and simply don't have the power that desktop computers have. Even an old game can give you trouble if you push the resolution too high.

Anyway, if everything is running well then you should be fine. I used to play these games on my laptop as well, and a Vega 8 is better than what I had.

**Comment by Deeruss** [comment]
Ok sweet thanks guys. And yeah that makes sense - have to agree hahaha its really not ideal for many games. It gets quite hot sometimes.
Really grateful I'm able to play this on it tho. Good stuff guys love your work
