### ISSUE TITLE
Fixing french translation!

### ISSUE THREAD

**Issue by Quatams** [elishacloud/Silent-Hill-2-Enhancements#444]
Hello everyone!

My name is Quatams. I'm really gratefull for your work on this Enhanced Edition for Silent Hill 2. It allowed me to discorvered this game, and wooooah. This game is very special to me. This was maybe my greatest videogame experience ever. So, thank tou so much.

As you read in the name of this post, i'm working on fixing french translation. This translation suffured of sentences which are really shorted in comparision of english version. The consequences? We lost A LOT of the sense, in some sentences. And some dialogue, aren't natural. For all this reason, i'm working on a fix for this translation. I have a good english and french level, and my translation aims not to transcribe word for word the English version, but to get as close as possible, in the composition of its sentences, in order not to betray the intentions, the emotions, and the ideas that Team Silent put, behind these sentences and dialogues. I count on the help of English friends to help me in this project, and also on French friends who know the game (or not), to know if the sentences do not sound wrong! I translated the subtitles of the observatory, the forest, and the cinematic showing us the meeting between Eddy and James. I still have a lot of work to do, but it's going well! If you want to contact me, you can do it via Discord : Quatams#6958

Thank you for reading, and congratulations again for all this work! I'm looking forward to every update!

**Comment by Polymega** [comment]
Hi there @Quatams,

Thanks for reaching out to us and we wish you the best on your improved French translation project! 

A group of fans have already cleaned up the English, Italian, and Spanish language files, so we'd certainly welcome a cleaned-up and faithful improvement for the French version. :)

I have a few tips and tricks for your endeavor:

- Make sure you are using the [sh2msgconvert tool](https://gitlab.com/sh2msgconvert/sh2msgconvert). It is a modern, feature-rich text editor for the game.
   - Its website has detailed documentation on how to use is.
   - @IlDucci is one of its creators and could help you with troubleshooting, if need be.
- Test your text changes while playing in a 4:3 aspect ratio.
   - Make sure edited lines do not go past 4:3 boundaries.
- I'd recommend using the English language files found in the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles) package as a base for your work.
   - We've adjusted things such as incorrectly colored text, trimming excessive uses of ellipses (...), and more.
   - Note that not all English files were adjusted for the Enhanced Edition Essential Files download, so some of them you would still need to find in the `<path-to-game>\data\etc\message\` folder for reference.
- Certain text are used in multiple `.mes` files.
   - For example: An adjustment to a memo line that can be read in the apartments (`stage_apart_*.mes`) can also be found and would need to be adjusted in the memos text file (`memo_*.mes`).
   - Be sure to keep tabs on what lines you've adjusted, in case these lines appear in other `.mes` files.
- The `.mes` file for the save folder requires special attention (namely character length restrictions). [Refer to this post for more details.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/111#issuecomment-568934361)
   - The "tab" text on the save screen needs to be 11 characters or less.
   - The "backspace" line on the save screen needs to be 27 characters or less.
   - Make sure your save file names are not too long. While on the save screen, you can press left or right to change the details on the right-hand side of the save tables. Change this to ensure its text is not overlapping your save file names.
   - We've altered the color-coding for save file names. Refer to the `m_card_x_msg_e.mes` file from the Enhanced Edition Essential Files for the changes.
- Lastly: Test, test, and test some more for every change you make.

@Badore90 did a translation adjustments for the Italian text, and @IlDucci did the same for the Spanish text. They might be able to offer guidance/support, should you have any questions. I worked on the English adjustments and can offer assistance when I'm able as well.

Hope that helps and best of luck to you!

**Comment by Quatams** [comment]
Whooah, thank you so much for this tips and trick! I will keep them in mind!

**Comment by Badore90** [comment]
I suggest you to edit with **Notepad++**

You should enable all characters visualization in order to see some keys the conversion program needs, here:

![Immagine](https://user-images.githubusercontent.com/44087144/126475860-e6d5f51e-7c64-4318-a16d-f229207a24fe.jpg)

For example you'll see that every time a dialogue go to head there's a symbol you can do with the **Tab key**
If you only go to head but don't press the Tab key at the new line start, the conversion program won't go to head (the entire phrase wil be on the same line once in game).

You can also download "compare" from the plugin options. It allows you to do a side by side comparison with the original files after you make the edited ones (make sure to do a backup copy of the french original ones), the program will enlight all the differences.

Also, keep in mind that the game is considered one of the best videogame experience/stories by the fans since 20 years. People are used to the original translation (also the wiki are based on original names).

So, you'll find quite a lot of grammatical and translation errors to correct. But when you're not very sure (i.e. you find a phrase that sounds better to you in another way, but you're not sure it would be an actual objective improvement) leave it as it is.
You can also ask here for any doubt.

**Comment by Quatams** [comment]
Thanks a lot for your suggestions and translation tips, i'll keep that in mind!

**Comment by Quatams** [comment]
Hello again!

So, the translation is going well, but i have some trouble with some sentences:

- (rebirth ending) In the sentence  _Olds Gods haven't left this place..._ "Olds and Gods are capitalized. Is there any particular reason?

- When James meets Angela for the first time, James use "Vouvoiement" on Angela (In French, if you talk to someone that you don't know, you will use a synonym to say "you", which is considered more polite : this action is called "vouvoiement").  The problem here, is that James begin to talk with vouvoiement, and stop at the end of the conversation, same thing for Angela. So, i don't know if it's better to jut avoid "vouvoiement" (By the way, Angela is underage, a lot of adult don't use "vouvoiement" for teenager or young adult).
The question of "vouvoiement" can really change relationship of them, and the mood of the meeting.

- The french translation of "Health drink" is really odd and unatural, but i don't know if this item have an equivalent irl, or if it is an item specific to video games in general.

That's all for now, thanks for your time !

**Comment by IlDucci** [comment]
>     * (rebirth ending) In the sentence  _Olds Gods haven't left this place..._ "Olds and Gods are capitalized. Is there any particular reason?

That's an English issue, I'd leave the comments to native speakers.

>     * When James meets Angela for the first time, James use "Vouvoiement" on Angela (In French, if you talk to someone that you don't know, you will use a synonym to say "you", which is considered more polite : this action is called "vouvoiement").  The problem here, is that James begin to talk with vouvoiement, and stop at the end of the conversation, same thing for Angela. So, i don't know if it's better to jut avoid "vouvoiement" (By the way, Angela is underage, a lot of adult don't use "vouvoiement" for teenager or young adult).
>       The question of "vouvoiement" can really change relationship of them, and the mood of the meeting.

We have something similar in Spanish with ustedeo (formal way to speak) and tuteo (informal way to speak). The official Spanish translation did something different in this case: both Angela and James talk to each other in a formal way, even if that might be inappropriate from James, as he's talking to an underage. This style is carried out throughout the entire game.

>     * The french translation of "Health drink" is really odd and unatural, but i don't know if this item have an equivalent irl, or if it is an item specific to video games in general.

Spanish also does something away from normal or from the literal translation of the English text... in Silent Hill 2. Instead, it took cues from SH1, where the drink was called "Tonic Drink", and called it "Isotonic drink". You could do something along the lines of actual, "healthy"-considered drinks.

**Comment by Quatams** [comment]
About the formal way to speach, in french translation, when James meet Eddy for the first timew the entire dialogue is in informal way to speech, this is why i'm a bit worried with Angela's one.
But thanks for your advice that helps a lot!

**Comment by Polymega** [comment]
Closing this ticket for now. If you're still working on an improved French translation please feel free to re-open this ticket.

Thanks!
