### ISSUE TITLE
Grey Screen After First FMV Cutscene, Persists Between Different Environments

### ISSUE THREAD

**Issue by ShadowArchos** [elishacloud/Silent-Hill-2-Enhancements#445]
Hello Silent Hill 2: Enhanced Edition Team,

I recently tried installing the Silent Hill 2: Enhanced Edition by following the installation guide on the Silent Hill 2: Enhanced Edition's website. However, after launching the game, I found that the game just goes to a grey screen as soon as the first FMV cutscene ends. I still seem to be able to pause the game and move James around the environment. However, I am unable to see anything when the game is not paused, and I am only able to see the pause screen text when the game is paused (I have attached an image to illustrate this). The issue also persists when I navigate James out of the first room. I have gotten this same result applying the Silent Hill 2: Enhanced Edition files to two separate copies of the game. Is there something important that I have overlooked? Any help would be much appreciated!

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6881865/d3d8.log)

![Screenshot](https://user-images.githubusercontent.com/88010893/127077430-b2ec07ff-42d9-422d-9ffa-537e7cf8131a.png)

**Comment by elishacloud** [comment]
The issue is almost certainly related to DirectX 9 SDK.   Try downloading and extracting [D3DX9.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Resources/D3DX9.zip?raw=true) into the Silent Hill 2 folder.

If that does not work then you will need to download and install Microsoft DirectX 9c SDK.

**Comment by ShadowArchos** [comment]
This solution worked for me! I'll be sure top update if I notice anything else off. Thank you very much!
