### ISSUE TITLE
Can't unpack Files

### ISSUE THREAD

**Issue by Luca306** [elishacloud/Silent-Hill-2-Enhancements#449]
Hi.
 when i try to unpack the Files, it keeps saying that there was an Data error or CRC Error.
Installing the Executable and Modules works just fine, but the rest not.

**Comment by Polymega** [comment]
Hi there,

Is it just one particular package giving you unpack troubles? Delete that ZIP package and redownload the package from the site.

**Comment by Luca306** [comment]
it's not only one pack, it's every pack after the Enhancements Module. I tried redownloading several time but it still say Archive corrupted

**Comment by Polymega** [comment]
I just downloaded four of the packs from the site and extracted them without issue. Try using a different ZIP extraction tool or restarting your computer.
