### ISSUE TITLE
SH2 60FPS stutterings. 

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#450]
When I play SIlent Hill2 at 60FPS, during gameplay the frames drop from 60 to 1 constantly.  How can I solve this problem?

**Comment by Polymega** [comment]
It is recommended to play the game at 30 fps. We haven't done any extensive tests/fixes for 60 fps.

**Comment by ppsalvador** [comment]
Ok thank you

**Comment by Polymega** [comment]
Closing ticket. 60 fps discussion can be continued here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28
