### ISSUE TITLE
Map shows a save icon where there is no save point

### ISSUE THREAD

**Issue by Zhnigo** [elishacloud/Silent-Hill-2-Enhancements#453]
Good day, and first of all, thanks for your work!

My issue is as follows: after leaving the hospital, retrieving the wrench and heading towards rosewater park, the town map shows a save point icon at Jack's Inn, where there seems to be no save point anywhere in the vicinity. I've searched the entire place high and low, and haven't found jack, and having played the game quite a lot in the past, I don't remember there being a save point either.

Running the last version of SE2E, no other fixes installed.

![20210825044620_2](https://user-images.githubusercontent.com/20024669/130714451-8138352d-1acf-426a-ba6c-674069ec0b4f.jpg)
![20210825044705_1](https://user-images.githubusercontent.com/20024669/130714456-5b5153e3-0040-4dda-b6b9-68b2a9388edc.jpg)

**Comment by Zhnigo** [comment]
Nevermind, upon returning from the park with the box, I stumbled onto the save point on one of the parked cars inside. It's quite a ways off from where it's marked on the map, so it's for you to decide whether that's a bug or not. It did give me a lot of frustration.
![20210825052438_1](https://user-images.githubusercontent.com/20024669/130716549-dddafbb1-c98a-4f6d-9107-f07c255d6c2c.jpg)
![20210825052555_1](https://user-images.githubusercontent.com/20024669/130716553-a1223261-1839-41f8-aa17-81518a72ff60.jpg)


Thanks for your time!

**Comment by Polymega** [comment]
Glad you found the save point. Yes, it's misaligned like that for all versions of the game. It's likely something we won't worry about adjusting, to be honest. But we'll make a not of it just on case.

I'll close this ticket out for you.
