### ISSUE TITLE
can't load enhanced edition. Just loads the original game 

### ISSUE THREAD

**Issue by JopeNope** [elishacloud/Silent-Hill-2-Enhancements#456]
Hi, 

I have an install of the game and I've followed all the steps on the enhanced edition website (unless I missed one by mistake), but when I try to run the executable it launches the original version of the game. 

I'm not very knowledgeable about this kind of thing, so sorry if I'm just missing something simple.  Thanks for your time and your hard work to make this game playable again!

**Comment by Polymega** [comment]
Hi there,

Thanks for providing a copy of your log file. If you rename `sh2pc-new.exe` to `sh2pc.exe` will the game launch with our project files then?

**Comment by JopeNope** [comment]
Thank you,

No, It still shows the original title screen. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7086612/d3d8.log)

**Comment by Polymega** [comment]
Can you describe in more detail how the game isn't hooking/using our project files? Because the game is able to produce a log file means the project files should be working (at least to some extent).

**Comment by JopeNope** [comment]
Ok, Yeah I wasn't sure if it was using your files or not, to be honest. I'm mostly basing it on the fact that it shows the original menu screens and not the one I have seen associated with the enhanced edition. When I look at the first log I sent you, it looks to me like maybe it _is_ using your files, so maybe it's just the menu screen that is different.  If it's just the menu, then that makes no difference to me. If you have a moment, could you look at that first log file and see if it looks like the enhanced edition, because that's the one from when I played a bit of the game: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7086198/d3d8.log  There it is again.  Thanks for your time.

**Comment by JopeNope** [comment]
The more I look at it, I see the enhancements module loaded, so it probably is working. But if you have a minute just to take a quick peek I'd really appreciate it, just to double check.  Thanks, you've been very helpful.

**Comment by Polymega** [comment]
May I ask you to take a snapshot of your `Silent Hill 2\sh2e` folder? For example, here is mine:

![image](https://user-images.githubusercontent.com/27395260/131577200-743de6e2-25d1-493f-944b-af3579bf0f1b.png)

**Comment by JopeNope** [comment]
Sure
![Screenshot (150)](https://user-images.githubusercontent.com/89868621/131577461-6c46a8c6-05c6-4458-970b-652c0cfd0f50.png)

**Comment by Polymega** [comment]
This is a real head-scratcher to me... You renamed the executable back to `sh2pc.exe`, your INI settings seem fine, and your files/folders all look to be correct.

So it seems like the only thing wrong/not working are the enhanced/upscaled full screen images (for things like the main menu background, save screen, and inventory images)? Can you take a snapshot of the following folders?
- `Silent Hill 2 \sh2e\pic\`
- `Silent Hill 2 \sh2e\pic\etc\`

**Comment by JopeNope** [comment]
![Screenshot (151)](https://user-images.githubusercontent.com/89868621/131578484-6432a430-dc89-4fbc-82a8-85e07542ded1.png)
![Screenshot (152)](https://user-images.githubusercontent.com/89868621/131578499-debebc9b-93ea-462f-876d-4fec9b5ea561.png)

**Comment by Polymega** [comment]
Ah, okay, so it looks like you either install the Image Enhancement Pack. This is what that directory should look like:

![image](https://user-images.githubusercontent.com/27395260/131578695-3e07c6ec-27e5-4cc3-bd5c-8333084eff13.png)

[You can download the Image Enhancement Pack here.](http://enhanced.townofsilenthill.com/SH2/install.htm#installImageEnhancementPack) Once downloaded, unzip the package and move all the contents found within that download's `SILENT HILL 2` folder into your game's `Silent Hill 2` folder.

**Comment by JopeNope** [comment]
OK thanks so much!

**Comment by JopeNope** [comment]
It works! This looks so good! You all did a great job. Must have been a ton of work. Thank you.

**Comment by JopeNope** [comment]
By the way, I edited a couple comments to remove the log file and screen shot that had my name, but other than that I'll leave this up for others to reference.

**Comment by Polymega** [comment]
Great! Glad everything is working as expected now. And thank you for the kind words to us. I'll close out this ticket. Feel free to open it back up or create a new one if you run into any other trouble.
