### ISSUE TITLE
The game doesn't start

### ISSUE THREAD

**Issue by dustbub** [elishacloud/Silent-Hill-2-Enhancements#458]
Hi I am unable to start the game. I only see a black screen and then the game stops and I see only my desktop. The game never starts after installing the enhancement data.

The game starts fine after a clean install from here https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd. I installed the fully extracted version and I applied the NOCD , the Patch and the FIX. The game starts fine at this point.

Then I installed the enhancements following this http:// enhanced.townofsilenthill.com/SH2/install.htm and then the game does not start anymore. No progress was lost since I just got the game.

One thing that changed that I noticed after installing enhancement is that the game asks me for admin permissions. Another thing the game also tries to connect to a github api and that didn't happen before.

Here's my logs: 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7169445/d3d8.log)

Here's my config (renamed because github restriction)
[d3d8.ini.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7169451/d3d8.ini.txt)

**Comment by dustbub** [comment]
I also want to note that I am using a windows 10 pro with directx 12 but I also installed an old directx from here http://www.microsoft.com/en-us/download/confirmation.aspx?id=8109

**Comment by dustbub** [comment]
I also want to note that I am not using any special graphical configuration for the game in my nvidia panel.

**Comment by Polymega** [comment]
> I installed the fully extracted version and I applied the NOCD , the Patch and the FIX. The game starts fine at this point.

This might be the cause of the issue. On MyAbadonware's website it mentions:

![image](https://user-images.githubusercontent.com/27395260/133480125-a751cf89-97c5-401b-9da5-4a44aead38b4.png)

These patches might be conflicting with our project. I'm not sure what exactly their NoCD/PATCH/FIX entails, but I would suggest removing or uninstalling whatever those files might have changed for the game and see if that works.

**Comment by dustbub** [comment]
My bad I should've read that. I tried again without the patches and the game works now. Many thanks! :)

**Comment by dustbub** [comment]
@Polymega can I request that you add the checksums to the file links at the enhanced webpage? Because I had to redownload everything again to rule out file corruption and it is a common thing to include checksums for large files. That would be very helpful.

**Comment by Polymega** [comment]
Yeah, that shouldn't be a problem. Behind the scenes our newest team member @nipkownix is working on an installer for the project, which I **believe** has a checksum feature. Can you confirm that, nipkownix?

**Comment by nipkownix** [comment]
Sorry for the delay! 
Yeah, earlier test versions of the installer had a checksum feature that got lost during some rewrites. I can easily reimplement it, however.
