### ISSUE TITLE
XB1 Controller just not working

### ISSUE THREAD

**Issue by Glimmstizzl** [elishacloud/Silent-Hill-2-Enhancements#459]
I tried everything to get it working somehow but wasnt very successful...
There no other controller or similar devices connected.
My controller is recognized by Windows.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7172398/d3d8.log)

**Comment by Glimmstizzl** [comment]
it seems to connect to a vjoy device gamepad, but i dont know what its supposed to be...
i uninstalled the vjoy drivers in the device manager and now it connects to nothing after starting the game again.

**Comment by Polymega** [comment]
Someone else had a similar issue with a "vJoy Device" and them disabling it fixed this issue. Here is that ticket: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/298#issuecomment-658715398

According to the official website, vJoy is:

> ... a device driver that bridges the gap between any device that is not a joystick and an application that requires a joystick. [...] vJoy is implemented as a joystick virtual-device driver for windows (XP and up) that does not represent an actual hardware device. The vJoy device is seen by Windows as a standard joystick device. However, it receives its signals through a simple software interface.

You can try disabling the vJoy Device via Windows Device Manager:

![image](https://user-images.githubusercontent.com/27395260/133488999-0e956cd3-3867-437f-9d05-25c480dc9722.png)

**Do so at your own risk.** Simply disabling the vJoy Device should be fine/safe; be careful not to disable anything else you don't want disabled. You can disable a device by right clicking it and selecting "Disable Device."

**Comment by Polymega** [comment]
> i uninstalled the vjoy drivers in the device manager and now it connects to nothing after starting the game again.

I missed your second post. If you've already disabled any/all vJoy Devices try unplugging your XB1 controller and plugging it back into your PC. SH2 PC uses the first controller it detects connected to your PC. You can also try restarting your PC first as well, in case any vJoy Device remnants are still there after you uninstalled their drivers.

**Comment by Glimmstizzl** [comment]
Uninstalled vjoy completely and restarted my pc. Still doesnt work... It now shows this in the log:
16604 20:32:57.051 |----------- GAMEPADS -----------
16604 20:32:57.179 |------------------------------------
The controller works completely fine in every other game.

**Comment by Glimmstizzl** [comment]
Just got it working by reinstalling the XB1 Controllers driver. Cant really understand how that fixed it, cause i already tried that 10 mins before. But i cant complain. Thanks very much!

**Comment by Glimmstizzl** [comment]
Just got it working by reinstalling the XB1 Controllers driver. Cant really understand how that fixed it, cause i already tried that 10 mins before. But i cant complain. Thanks very much!

**Comment by Polymega** [comment]
Awesome! Glad you figured it out as I was out of ideas at that point.
