### ISSUE TITLE
C++ problem

### ISSUE THREAD

**Issue by kajuki** [elishacloud/Silent-Hill-2-Enhancements#46]
so i tried installing the sdk but just tells me the newest version is already installed, but i get the runtime error still, but the werid thing is the game runs fine in the background, and yes i looked at the other threads but they didin't help with my issue.

https://gyazo.com/9dd6526f3f4f42c1c467660839f5ee3c

the link shows my issue. if i click ok or the "X" on it it closes the game. but as long as i leave it be the game runs ok.

**Comment by Polymega** [comment]
Hi @kajuki , 

There are two different SDKs you can install. To confirm: You tried both? In particular the [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555)?

**Comment by kajuki** [comment]
> Hi @kajuki ,
> 
> There are two different SDKs you can install. To confirm: You tried both? In particular the [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555)?

yeah i tried that to no avail.
![c7c71fc5dd1eac6413cfb8f5466f0ea3](https://user-images.githubusercontent.com/43329872/45646660-d8be6b80-ba78-11e8-8c42-f9ffe4c6e162.png)

**Comment by kajuki** [comment]
> Okay, thanks for confirming. We'll have to ask @elishacloud about this one as he's a lead programmer and C++ guru for this project.

ok, thank you for helping me out.

**Comment by kajuki** [comment]
> If it's already installed, why don't you try reinstalling it? You should see it in your control panel:
> 
> ![control panel](https://camo.githubusercontent.com/92021a57f02d1e2e9c4ac36520b45ad8208924a1/68747470733a2f2f692e696d6775722e636f6d2f4e4d364e6731722e706e67)

i just tried it and it didin't fix it.

**Comment by kajuki** [comment]
> Can you try with this update to see if it fixes the issue: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2409446/d3d8.zip)
> 
> If that does not work then try disabling each feature in the `d3d8.ini` file one-by-one and let me know if disabling any of these options helped. Most likely it is caused by the `AutoUpdateModule` feature.

yes that worked! it was the autoupdatemodule, thanks so much.
