### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by Freg317** [elishacloud/Silent-Hill-2-Enhancements#463]
Greetings! Recently, I'm having problems with the Enhanced Edition of Silent Hill 2. In game, at the moment of solving the clock puzzle in the Blue Creek Apartament, there's a fx bug. Moding the clockhand, the fx sound of clockhand manipulation will loop, over and over and over. The unique solution is exiting of the game. I tried to search, someone with my problem too, but i only understud that It's a GPU problem.

**Comment by Polymega** [comment]
Hello,

A few questions about this issue:

1. Has the sound looping issue happened anywhere else for you outside of the apartment clock?
2. Are you able to replicate the sound loop issue every time for the apartment clock? Or was this an issue that has only happened one time for you?

**Comment by Polymega** [comment]
No response so I'll close out this ticket. Feel free to re-open for further troubleshooting.
