### ISSUE TITLE
Editing Swizzled texture

### ISSUE THREAD

**Issue by Sonderhen13** [elishacloud/Silent-Hill-2-Enhancements#468]
Hi, first sorry if I'm posting in the wrong place, it's the first time I'm using github.

I'm working on the Silent Hill 2 Portuguese-Brazil dub project, we will be releasing the dub patch for PC, PS2 and Xbox versions.

I've been trying to edit some textures in the ps2 version for many years, but I've never been able to.

Some textures I can edit normally through shtexplorer, but some textures are Swizzled and I've never been able to edit them, do you know how to edit them?

Texture example that I can edit:

[etc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7331420/etc.zip)

**Comment by Polymega** [comment]
> I would like to ask if we can use the Enhanced Edition high resolution FMVs (the .bik files). Inserting your credits, of course

Sure thing, not a problem.

> Everything will be 100% localized, all FMVs, in-game audios and sound effects (damage and attack sounds, etc).

Oh wow, that's a massive undertaking! I wish you and your team the best with this endeavor.

Sorry I don't have any more information to help with the swizzled textures.

**Comment by Sonderhen13** [comment]
Thank you very much

About the .tex files, no problem.

Congratulations on your project, for dedicating yourselves and making the Silent Hill 2 experience the best possible.

**Comment by AeroWidescreen** [comment]
Try asking the people over at https://forum.xentax.com/ about the swizzling issue. They might be able to help you, assuming a tool doesn't already exist.

**Comment by Sonderhen13** [comment]
> Hey there, what textures are you looking for?
> 
> I did a port of the my Spanish revision of the Enhanced Edition to the PS2 and for the few textures I wanted to edit (the Konami logo to add the credits and the main menu's options), I used ConsoleTextureExplorer. It's a mid-to-advanced tool that can be used to point at the exact position of the textures and edit them, and it has swizzling support.

wow, just now i saw your post, sorry.

I would like to edit the title screen, and Konami logo (to add credits)

Do you have an email for me to contact you?

Thank you very much in advance.

**Comment by IlDucci** [comment]
> 
> 
> > Hey there, what textures are you looking for?
> > I did a port of the my Spanish revision of the Enhanced Edition to the PS2 and for the few textures I wanted to edit (the Konami logo to add the credits and the main menu's options), I used ConsoleTextureExplorer. It's a mid-to-advanced tool that can be used to point at the exact position of the textures and edit them, and it has swizzling support.
> 
> wow, just now i saw your post, sorry.
> 
> I would like to edit the title screen, and Konami logo (to add credits)
> 
> Do you have an email for me to contact you?
> 
> Thank you very much in advance.

I just wrote you on Twitter. Follow me so we can continue this conversation there.

**Comment by IlDucci** [comment]
Check your Twitter account, @Sonderhen13 .

**Comment by Polymega** [comment]
Thanks for helping Sonderhen out here, IlDucci. 👍
