### ISSUE TITLE
Suggestion: Unused audios

### ISSUE THREAD

**Issue by Sonderhen13** [elishacloud/Silent-Hill-2-Enhancements#469]
About file SCENE_45 (Mary reading Laura's letter) it was never used in the game.

I have a suggestion for this audio to be used:

**Option 1:** If it is possible to create a trigger when examining Laura's letter, activating the audio file. If the player presses the back button, the audio is stopped.

**Option 2:** I always liked unlockables in games, would it be possible to use the "Movies" screen? A new FMV (.bik) could be created containing the narration of the letter and the video would be unlocked only if the player completes the game once. If I'm not mistaken in the PS2 version the movie (open_voc.pss) is only available after completing the game.

Another unused file is the uncensored VHS tape, (satsugai). Maybe you could create a new .FMV containing the uncensored version, and it would only be available in the menu after completing some specific ending (In water, maybe?)

**Comment by Sonderhen13** [comment]
I see...

I wonder why the developers didn't just delete these files, it would save storage.

At Silent Hill 3 it's the same, with a photo of Heather and Harry, and a picture of Douglas' car parked in front of Jack's Inn

Also on Silent Hill 4, with the files of a likely UFO ending that was cancelled.


> There would also be no easy, immediate way to include both versions as a selectable or unlockable option, or to add it in as part of the MOVIE menu, and I don't think it's worth the effort for this case.

For Mary's Letter to Laura letter maybe it's worth it in the future...

Anyway, these are just suggestions for the future. I know the project's priority right now is fixing bugs and other improvements.

**Comment by Sonderhen** [comment]
@Polymega 

Sorry to post again here, but I preferred not to create a thread just for that.

I translated the dialogues from the Ufo Ending to Portuguese and I have no idea how to replace the high resolution .tex files (shtexexplorer doesn't work).

Could you convert these images to .tex?

Thank you very much in advance.

![words01](https://user-images.githubusercontent.com/25414844/147885216-9e33e881-0b99-4dcf-b397-262c6d955312.png)
![words02](https://user-images.githubusercontent.com/25414844/147885224-fa582b9e-70d6-4844-bfd8-b92d0b85012a.png)
![words03](https://user-images.githubusercontent.com/25414844/147885230-4751f2eb-8f6d-4011-a7e8-c93a66042e0f.png)
![words04](https://user-images.githubusercontent.com/25414844/147885235-c1df1df1-1bd4-4e00-aa36-8956404487c4.png)
![words05](https://user-images.githubusercontent.com/25414844/147885240-16bb1548-6c19-4515-979f-e50536cff13c.png)
![words06](https://user-images.githubusercontent.com/25414844/147885244-7c3149f1-fd36-46c6-82c7-5d3252a62bf4.png)
![words07](https://user-images.githubusercontent.com/25414844/147885249-82290d9f-70c7-4824-a76b-3be6b6f78c56.png)

**Comment by Polymega** [comment]
Here you go:
[UFO Words PTBR.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7816922/UFO.Words.PTBR.zip)

**Comment by Sonderhen** [comment]
> Here you go: [UFO Words PTBR.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7816922/UFO.Words.PTBR.zip)

Thank you very much. Worked perfectly.

The UFO Ending will also be dubbed but I also wanted to edit the texts.

Ah, I don't know if you know but there are considerable differences in the game texts in the different versions (PS2 and PC). The English translation of the PC version is much better and the PS2 one has some errors.

I would then like to create a table showing all the differences in the text files of the different versions of the game.

**Comment by Sonderhen** [comment]
@Polymega  Sorry for the delay, but now that I've noticed that the last image you sent me is misspelled.

You wrote: "Eposa" and the correct one is "Wife".

Wife = Wife in Portuguese.

Hah, there's a little "new": It's not something cool like that other audio I discovered (The unused audio of James seeing the hotel) but I discovered a never-used video inside the Movie.MGF of some PS2 versions.

It's the videotape scene, but without the reveal at the end.

https://www.youtube.com/watch?v=I6H-AX2JmdE

**Comment by Polymega** [comment]
So sorry about that. Here is the correction:
[UFO Words PTBR r1.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8011403/UFO.Words.PTBR.r1.zip)

 > It's the videotape scene, but without the reveal at the end.

Whoa! Very cool! Love how you're finding all these new, interesting things. Great find and keep up the good work!

**Comment by Sonderhen13** [comment]
> So sorry about that. Here is the correction: [UFO Words PTBR r1.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8011403/UFO.Words.PTBR.r1.zip)
> 
> > It's the videotape scene, but without the reveal at the end.
> 
> Whoa! Very cool! Love how you're finding all these new, interesting things. Great find and keep up the good work!

Thanks a lot for all the help.

Yesterday we released the dubbing patch for the PC and PS2 version. If you are curious to check out the dub, the direct link is this:

http://silentfandub.blogspot.com/2022/04/pc-silent-hill-2-enhanced-edition.html

Thank you again

**Comment by Polymega** [comment]
We've included an option to play the unused VHS audio into our project now. Unfortunately, it's impossible to include Mary's audio of reading Laura's letter as the pacing of this scene is entirely controlled by the player.
