### ISSUE TITLE
Suggestion: Option to invert axis

### ISSUE THREAD

**Issue by ChuckyIO** [elishacloud/Silent-Hill-2-Enhancements#470]
Add ability to invert Y-axis and/or X-axis for the ingame search camera.

**Comment by ChuckyIO** [comment]
Never mind, found in XInputPlus.ini under [RightStick] by changing _InvertY_ and/or _InvertX_ from False to **True**.

**Comment by Polymega** [comment]
Sorry for the silence. This thread completely slipped under my radar. Glad you got it figured out. So long as you're using an Xinput controller, the method you described should be fine.
