### ISSUE TITLE
In-game cutscenes slowed down

### ISSUE THREAD

**Issue by alejandrovgonzalez** [elishacloud/Silent-Hill-2-Enhancements#472]
Hello there!

First of all, thanks a lot for this amazing project. I've played the first hour of the game with no issues except for one, which is a very slow framerate while the in-game cutscenes are playing; this is 100% reproducible. It happened at the beginning of the game after the scene where James looks into the mirror, when the camera is on the other side of the toilet peeking at him, and it also happened during the first enemy encounter (see video). Apart from that, the game runs very smoothly during gameplay time and during pre-rendered cutscenes. It's worth mentioning I'm running the game on a Linux computer through wine :) If you need any more information, let me know.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7477469/d3d8.log)
[video](https://www.youtube.com/watch?v=Pstzzc3m9qI)
Close to the end, when the camera points at James, the framerate seems to get fixed.

**Comment by Polymega** [comment]
Hi alejandro,

Glad you're enjoying the game! Our project isn't typically ran through Linux and Wine, so that might have something to do with it. It's hard to say otherwise, unfortunately.

**Comment by alejandrovgonzalez** [comment]
Thank you, Polymega. I know Linux is not "officially" supported but, if you have any idea of what could be the issue or what configuration parameters I could play around with to see if the error gets fixed, I would gladly check it out and post here the results -- this way I might help someone with the same issue.

**Comment by Polymega** [comment]
Unfortunately, I'm ill-equipped to help in this situation for a few reasons. Elisha, our lead developer, may be able to offer some suggestions or guidance on this topic (though, I'm not sure) but he is taking an extended break at this moment so I'm not sure when he could get back to you.

**Comment by alejandrovgonzalez** [comment]
Thank you Polymega. I will leave the issue open for now, then.

**Comment by Polymega** [comment]
Closing ticket. If you'd like further assistance, please continue the discussion in our Linux troubleshooting thread: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/557
