### ISSUE TITLE
FMVs do not display in proper aspect ratio.

### ISSUE THREAD

**Issue by PCF13** [elishacloud/Silent-Hill-2-Enhancements#473]
Hello Enhanced Edition Team, I hope life is treating you well.

I've noticed that in more recent builds of the Enhanced Edition mod, the full-motion video cutscenes do not play in the proper aspect ratio. Instead, they display cropped to fit a 1.78:1 aspect ratio. Looking at the raw EE FMV files through a video player such as VLC, they display in the proper aspect ratio, so therefore it is not a problem with the files themselves rather how they are displayed in-game. Fiddling with the "FMVWidescreenMode" parameter doesn't do anything whatsoever. It should go without saying that these FMVs were not created to display this way and it crops information out of the frame. I am unsure if this is a technical issue or a creative change, but if it is the latter, I respectfully ask that the team provide an option for those who want to view them in their original aspect ratios. If the option is provided for the in-engine cutscenes I do not see how the FMVs are different.

Thank you very much for your time, and good luck with the project

(The first image is the raw file in VLC, the second is displayed in-game.)

![vlc_RorzuevkXy](https://user-images.githubusercontent.com/17348364/140427999-e3798083-df2d-4d1c-856f-a9fdabc6804b.jpg)
![sh2pc_Lrsyho4c34](https://user-images.githubusercontent.com/17348364/140428007-f4a22cde-1a53-4398-9cee-5512511d03b2.jpg)

**Comment by Polymega** [comment]
Hello PCF13,

> I respectfully ask that the team provide an option for those who want to view them in their original aspect ratios. 

We've totally retooled how FMV scaling works for the next project update, and will give the option to display the FMVs in full (with pillar or letterboxing) or cropped up to a 16:9 aspect ratio. You will also need to re-download the FMV Pack when this time comes.

We're not sure when the next update will release.

**Comment by PCF13** [comment]
Thank you very much for the reply, Polymega. It's good to hear that the team is working on giving fans the option to choose. PC gaming is all about options after all, so I'm glad the team is following that philosophy. Out of curiosity, what exactly is being retooled?

**Comment by Polymega** [comment]
How the game handles scaling for the FMVs. Basically cleaning up and optimizing features that fixes like `FMVWidescreenMode` handled.
