### ISSUE TITLE
Massive spoiler in radio cutscene

### ISSUE THREAD

**Issue by Shy-Shallows** [elishacloud/Silent-Hill-2-Enhancements#475]
In [this cutscene](https://www.youtube.com/watch?v=wcnPMoNDltk&ab_channel=MeadeCountyGirl), you can clearly hear "Why did you kill me?" even though it should cut off, sounding more like ".....id you k......"
This is an issue in all versions of the game.

**Comment by Polymega** [comment]
This is one of those neat things where you're supposed to hear it "clearly," but if you're playing the game blind for the first time you'd likely never interpret it as that. Once you beat the game and do a subsequent play through, you'll typically then hear it for what it is and have that "oh shit!" moment the developers wanted you to have.
