### ISSUE TITLE
Ui Text. Subtitle, Menu Text Didnt Show

### ISSUE THREAD

**Issue by KurosawaSei** [elishacloud/Silent-Hill-2-Enhancements#476]
Hello, i have a problem with my SH. So i download it from nyaa.si [ https://nyaa.si/view/1418336 ]. And try to run it and it works at first until i want to tweak the setting on "option". It didnt show anything so i'm a bit confuse. I search the text at google and finish tweaking the settings. Even i want to confirm "yes or no" it shows nothing. And i somehow click yes and resolution is change that means i click the right thing. But the text is still gone and i was like "oh ok, maybe its only on the menu, , maybe the in game might different". And i play the game and enter cutscene and the subtitle text is gone even though i turn it on. And not only that, the menu and map(i think. i dont know what square function is) is gone to. When i enter load or save, the text is also gone. Can anyone help? Thx
Edit: The map button "square" it works. it didnt show at first because i dont pick the map from the car. My bad.

![sh2(1)](https://user-images.githubusercontent.com/94154611/141404601-f32748b0-dd14-4a5d-b0fa-4e9b90ee8c4f.png)
![sh2(2)](https://user-images.githubusercontent.com/94154611/141404608-17ec7bad-3afa-43be-9c4f-66be99b57e50.png)
![sh2(3)](https://user-images.githubusercontent.com/94154611/141404610-4198e8c9-24da-43f7-af9e-546a62f1e34a.png)
![sh2(4)](https://user-images.githubusercontent.com/94154611/141404618-c13c265d-696a-427d-9b09-47056779965e.png)
![sh2(5)](https://user-images.githubusercontent.com/94154611/141404624-26204b51-e24b-4eb9-b10a-f5a9930a0626.png)
![sh2(6)](https://user-images.githubusercontent.com/94154611/141404637-784355e3-4246-48ba-b623-23a4c08720d1.png)
![sh2(7)](https://user-images.githubusercontent.com/94154611/141404810-9688bdce-d3fc-4f71-987f-111e83826fde.png)

Here is my d3d8.log file ( [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7524699/d3d8.log) )

**Comment by Polymega** [comment]
[We don't recommend using integrated graphics processors (IGPs) for the project.](http://enhanced.townofsilenthill.com/SH2/#systemreq) We've found that certain IGPs, especially older/weaker ones, cannot display the super high resolution of the HD font. There are other tickets on this page with the same issue.

You can disable the HD font by opening the `d3d8.ini` file and setting `UseCustomFonts = 0`. This will revert to using the original font texture file.

When using an IGP, if you also experience general lag/slow down while playing the game you can try any of these recommendation to reduce the issue:
- http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-only-during-outside-segments-while-in-the-townforest
- http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general

**Comment by Polymega** [comment]
Also, you are using several software packages that are no longer recommended for use with our project. This is unfortunately unavoidable for us if our project is downloaded as an "all-in-one" package from outside parties. We plan to release an installer/updater with our next project update, which will hopefully mitigate this concern for us down the line.

Anyway, **remove** the following files/folders from your game's directory:

```
\reshade-shaders\
d3d8.dat
d3d8.dll.deleteonnextlaunch
d3d9.log
device.7z
dsound.ini
dsound.log
dxgi.dll
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by KurosawaSei** [comment]
> Also, you are using several software packages that are no longer recommended for use with our project. This is unfortunately unavoidable for us if our project is downloaded as an "all-in-one" package from outside parties. We plan to release an installer/updater with our next project update, which will hopefully mitigate this concern for us down the line.
> 
> Anyway, **remove** the following files/folders from your game's directory:
> 
> ```
> \reshade-shaders\
> d3d8.dat
> d3d8.dll.deleteonnextlaunch
> d3d9.log
> device.7z
> dsound.ini
> dsound.log
> dxgi.dll
> ReShade.ini
> ReShade_sh2pc.ini
> ```

i deleted this file and i got a new problem. when i change the UseCustomFonts : 1 to 0 and save. its just the same thing. and i reopen the d3d8.log and it change back to 1. Am i doing wrong or what?

**Comment by KurosawaSei** [comment]
> Also, you are using several software packages that are no longer recommended for use with our project. This is unfortunately unavoidable for us if our project is downloaded as an "all-in-one" package from outside parties. We plan to release an installer/updater with our next project update, which will hopefully mitigate this concern for us down the line.
> 
> Anyway, **remove** the following files/folders from your game's directory:
> 
> ```
> \reshade-shaders\
> d3d8.dat
> d3d8.dll.deleteonnextlaunch
> d3d9.log
> device.7z
> dsound.ini
> dsound.log
> dxgi.dll
> ReShade.ini
> ReShade_sh2pc.ini
> ```

Ok, i already delete the file and change the customfonttext from 1 to 0 and now the game shows the text. Thanks a lot.
![sh22(1)](https://user-images.githubusercontent.com/94154611/141649317-a40622bd-88cc-4002-a9c3-59741315731d.png)
![sh22(2)](https://user-images.githubusercontent.com/94154611/141649322-400adeea-f63b-4d01-a12c-fd20671b9dc1.png)
![sh22(3)](https://user-images.githubusercontent.com/94154611/141649324-4c637769-e463-4537-a4bb-7fbd9a5aabb6.png)
![sh22(4)](https://user-images.githubusercontent.com/94154611/141649327-8f384e2d-2772-4d7d-b486-80d37037fde2.png)

If you guys have the same problem change the CustomFontText to 0 from the **CONFIG** not the **Log** like i just did which is dumb xD. 
Usually the **LOG** file is "text document" and the **CONFIG** file is "configuration settings"
![sh22(5)](https://user-images.githubusercontent.com/94154611/141649491-3a90721d-9904-4288-850e-790846e2c31e.png)
![image](https://user-images.githubusercontent.com/94154611/141649533-55442596-8086-4941-a131-efe32e76fc6b.png)


CASE CLOSED
