### ISSUE TITLE
Game Only Launches After Opening .exe File Twice

### ISSUE THREAD

**Issue by jackskellingt802** [elishacloud/Silent-Hill-2-Enhancements#477]
Hello!

First of all, thank you guys so much for your effort into this game. Silent Hill 2 never looked better than this enhanced version. I would like to know about the problem I'm facing right now. When I start up my PC and open Silent Hill 2, it doesn't launch on the first attempt. When I open it again for the second time, it launches. It keeps going on like this. Is it normal or is something wrong? 

Please, let me know and thanks again for this great work!

**Comment by Polymega** [comment]
Hi there,

That's not normal behavior. Do you have a `d3d8.log` file in your game's directory? If so, please attach it to your response here.

**Comment by jackskellingt802** [comment]
Hello. Here is the d3d8.log file attached below.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7538497/d3d8.log)

**Comment by jackskellingt802** [comment]
This is the d3d8.log file from enhanced edition applied to djDEVESTATE base game. I uploaded both files just in case.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7538627/d3d8.log)

**Comment by Polymega** [comment]
Hmm... looking at you log files, everything appears to be in order. I don't see anything unusual. I'm not sure at this moment why you have to launch the game twice each time. Have you restarted your PC to see if that fixes the issue?

**Comment by jackskellingt802** [comment]
Yea. I've tried restarting, reinstalling the game using different base game version. They all seem to be acting the same. I'm kinda confused.

**Comment by jackskellingt802** [comment]
I changed my windows to Windows 10 and reinstalled everything from the beginning. Now, it's working flawlessly! I'll close this ticket now. Keep up the great work, guys!
