### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by pablodt97** [elishacloud/Silent-Hill-2-Enhancements#481]
Hey,

My friend and I were installing the fixes on two different laptops, and we used the same base game file. We installed all of the enhanced files in order. However, his game wouldn't launch whereas mine did. It seems his sh2 executable file worked up until the moment he extracted and pasted the audio enhancement pack. After that, launching the game results in a black screen that seems to go on forever. We tried different options, the only thing that solved the problem was not installing the enhanced audio pack. We are both using windows 10. This is his d3d8.log file:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7636086/d3d8.log)

Some help would be appreciated :)

**Comment by Polymega** [comment]
Try removing the trademark symbol ("TM") from the game's directory and see if that works. I'd actually recommend making the overall directory more clean, such as `C:\Users\USER\Desktop\Juegos\Silent Hill 2\`

**Comment by pablodt97** [comment]
This worked! Thanks a lot

**Comment by Polymega** [comment]
Great! I'll close this ticket then.
