### ISSUE TITLE
Support for International Dubbing

### ISSUE THREAD

**Issue by noobynoob2** [elishacloud/Silent-Hill-2-Enhancements#483]
Hello, firstly I apologize if this isn't the most appropriate method for such communication but it's the only one I could find. Very recently a _phenomenal_ fandub of SH2 for Brazilian Portuguese was made by the team Silent Fandub, and I was wondering if it's possible to add support for dubbing in Silent Hill 2 Enhanced. Right now there's only a demo of the fandub for the demo version of SH2, exclusive to the PS2. That is, Silent Fandub released a demo of their work using the SH2 demo, and the full version (which obviously will be for the retail version of the game) will come out some time in the future. It would be very, very greatly appreciated if such feature could be added, as SH2E is the best way to experience the game and the dubbing made by Silent Fandub is of outstanding quality, thus for Brazilian players that would be amazing.

Since the demo wasn't released commercially, it can be download with the patch already applied here: [ [PS2] Silent Hill 2 0.10 Demo - Dublado e Legendado](http://silentfandub.blogspot.com/2021/10/ps2-silent-hill-2-010-demo-dublado-e.html)

Thank you very much for your attention.

**Comment by Polymega** [comment]
Hi there,

I believe [one of the creators of the fan dub has posted here before.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/468) Their project sounds very cool and ambitious! I wish the best for them on this. Compatibility with SH2:EE will be largely be dependent on their end. For audio/image/video repack work, the creator(s) would need to ensure their work can sit on top of or safely replace SH2:EE project files.

As the Silent Fandub team continues work, be sure to ask them if their work will be compatible for use with SH2:EE. If I were to guess, the installation of their fan dub pack will likely consist of overwriting files, which would be very simple. If that is the case, the only "issue" would be that if/when we release an update to our Audio Enhancement Pack, our update would overwrite the fan dub files. If that happens, you would simply have to re-overwrite the files again with the fan dub files.

**Comment by noobynoob2** [comment]
Thank you for your response!

I did not know that they already contacted you, that's very nice. I also believe that their pack only overwrites the audio files with the dubbed version, so making it compatible with EE should be pretty easy. I'm not counting the translated subtitles because EE already has them, but I think that after the full version is released maybe the translation used by EE could be updated so it matches the dub's dialogue, perhaps.

I realize this might be too much given that EE is made by fans, but given the excellent attention to detail and hard work poured into it, do you think that it could be possible to add a setting in-game to change the language of the dubbing, similar to how you can change the language for the UI and subtitles? Again, I completely understand that this might require too much work, but I think it would be amazing if that was possible since that's the most user-friendly way to do it. It would also possibly raise interest for other groups to dub the game to their language too, which would be very interesting in my opinion.

**Comment by Polymega** [comment]
> do you think that it could be possible to add a setting in-game to change the language of the dubbing, similar to how you can change the language for the UI and subtitles? Again, I completely understand that this might require too much work

Unfortunately, as you described, it would likely require a lot of work to accomplish. The game is hard-coded to only offer five language choices. And on top of that, as far as I'm aware, there's nothing in the game's code to change between audio files depending on language selected.

The easiest solution then is to overwrite text and audio files as needed. It's not the most elegant solution, I know, but it works and is easy to accomplish.

> It would also possibly raise interest for other groups to dub the game to their language too, which would be very interesting in my opinion.

This has been low on my to-do list, but I would like to include a list of "EE supported" language packs on the project's website. It would be a list that takes you to each language pack's own website where they host their files. Again, it's been low on my to-do list so I'm not sure when I'll get around to it. In the meantime, however, [there is a list of fan translation packs seen on PCGamingWiki.](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Localizations) I'd strongly recommend Silent Fandub add their work to this list once they're done.

**Comment by noobynoob2** [comment]
I figured it would be too complicated, but seeing how skillful the developers of EE are, I thought, maybe there's a possibility. :)

I'll contact them when the full release happens to let them know what was discussed. Thank you for your time!

**Comment by ForgotMyPassoword** [comment]
@Polymega Sorry for replying from another account, but I forgot my password for noobynoob and Gmail is acting up and won't let me log in.

I spoke with Silent Fandub and they said their work will encompass the dubbing, the subtitles and a installer. It should come out along with the PS2 patch very soon. I will have to ask for you to ignore what I previously said, as I didn't know they would work on all these three aspects. I had assumed they would be only working on the dubbing. I should have spoken with them first before posting here.

I also spoke with a professional company from Mexico that was dubbing Silent Hill 2-4 to Spanish, which I found because they released some dubbed scenes on their Youtube channel, and asked if they intended on releasing the voice files, but they said they do not.

**Comment by Polymega** [comment]
No worries @ForgotMyPassoword and sounds good. It's great to hear this team is able to accomplish all their subbing/dubbing goals. I wish them the best for continued progress!
