### ISSUE TITLE
"Leave" ending credits FMVs freeze for 2~10 seconds every few seconds

### ISSUE THREAD

**Issue by CalciumS** [elishacloud/Silent-Hill-2-Enhancements#484]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7791838/d3d8.log)

Hello! This is a very minor issue I encountered after replaying the Enhanced Edition. Unfortunately I wasn't recording, nor have I tried to repeat the ending to see if it happens again so I'm not sure if this was just a one-time bug or possibly something to do with my PC.

As the title said, once I finished the game and got the "Leave" ending (remains to be seen if it happens with other endings), the usual credits FMV began to play. For some reason while it was playing, it froze for around the time stated in the title, FMV resuming for another 5 - 20 seconds before it froze again with another random 2-10 second time interval. It's important to note that this only happened with both credits FMVs (Enhanced Edition credits included) **after I had finished the game**, and it did not happen with any of the other FMVs while I was playing.

I of course have the FMV Enhancement pack installed too. I don't recall taking any action that may have caused this issue. If any other info is needed, do let me know.

**Comment by Polymega** [comment]
Hi CalciumS and happy new year,

It's hard to pin-point what the issue might be. It may have be a quirk with your GPU. You're using an integrated GPU, correct? You can try playing at a lower resolution, disabling post-processing filters via the `d3d8.ini` file, or disabling `d3d8to9` in that same file to see if that fixes the issue.

Sorry I don't have a more concrete solution for you.

**Comment by Polymega** [comment]
I'll close out this ticket. Feel free to re-open for further troubleshooting.
