### ISSUE TITLE
Cutscene & General Game Lag When Multiple Characters Are On Screen

### ISSUE THREAD

**Issue by Luca-Fox** [elishacloud/Silent-Hill-2-Enhancements#487]
So at first I didn't know why my game was lagging as badly as it was (I run SH2EE at 60fps, but even when capped to 30fps I still get dips), but I think I finally figured out why. At first, I thought it was because of visual effects, but that's not the case, the game runs perfectly when I'm running around the town or inside of areas. However, whenever there's another human character on screen (except for Maria when she's following you and Laura weirdly), the game lags horribly.

I'm talking a 20-35fps dip with the game running at 60fps or a 10-15fps dip with it running at 30fps. This happens with the in-game cutscenes, as well as if a character is in the same room with you. Most notable with every Angela cutscene & the gameplay segments with her still there, every Eddie scene & gameplay segments with him there (his boss fight is ULTRA laggy), and most cutscenes with Maria in them (but the game runs fine when she's just following you). Laura's scenes run fine except for the hospital scene, which sees noticeable dips in the FPS (again, as long as her character model is on screen).

This issue started happening ever since the most recent major update (reinstating the shine to objects and improvement to inventory images) and I can't figure out a fix for it. My game already runs at a lowered resolution, and trying to adjust the options both in game and in the .ini files doesn't fix it. I don't have the most powerful PC, but seeing as it can run the game perfectly fine about 65% of the time, idk why it's having such issues with multiple characters.

**Comment by Luca-Fox** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7938941/d3d8.log)

Here's the d3d8 log file, I can upload clips of the game lag if need be, just don't want to clutter this post with a bunch of short snippets.

**Comment by Polymega** [comment]
It's hard for me to say what might be causing this. The `Squ1zZy_Silent_Hill_2_Resolution_v1.0.exe` file you have in the directory; [I found a post on this](https://www.silenthillforum.com/viewtopic.php?t=23610) and it looks to patch/modify the game executable. I'd first ensure you're not running an executable of the game that was modified from an external source.

Beyond that, I'm not totally sure at this time. You mention it only started happening since the last public release of our project... You can try disabling some of the new features within the `d3d8.ini` file that the last update introduced to see if that changes anything.

`SpecularFix`, `DynamicResolution`, `FixMemoFading`, `CheckCompatibilityMode`

You can also disable `d3d8to9` to see what that does.

**Comment by Luca-Fox** [comment]
> It's hard for me to say what might be causing this. The `Squ1zZy_Silent_Hill_2_Resolution_v1.0.exe` file you have in the directory; [I found a post on this](https://www.silenthillforum.com/viewtopic.php?t=23610) and it looks to patch/modify the game executable. I'd first ensure you're not running an executable of the game that was modified from an external source.
> 
> Beyond that, I'm not totally sure at this time. You mention it only started happening since the last public release of our project... You can try disabling some of the new features within the `d3d8.ini` file that the last update introduced to see if that changes anything.
> 
> `SpecularFix`, `DynamicResolution`, `FixMemoFading`, `CheckCompatibilityMode`
> 
> You can also disable `d3d8to9` to see what that does.

Ok so, disabling the 4 new features you listed had no improvement on the performance, but disabling the d3d8to9 did improve it (sort of). While the cutscenes overall improved (the Abstract Daddy fight is now actually playable), it introduced a new issue, the game stutters, dips, and hitches regularly during gameplay segments now. Outside, indoors, whatever, it noticeably loses FPS. Even worse is that there's no apparent improvement during the Eddie fight, it still lags a lot.

As for the actual .exe thing, I'm not really sure how I could check that it was modified, but I'm fairly certain that it wasn't. I've never used the Squ1zZy .exe file and the only modifications I've done to the game are these EE fixes.

**Comment by Luca-Fox** [comment]
Did a fresh install of both SH2 and the EE patches, it magically fixed itself. The only downside now is Eddie's first boss room still has a lot of lag, but I lowered the resolution using the in-game options, and it runs smoothly now. That scene's lag was caused by the fog though (tested with it on and off, got no lag with it gone). 

Hopefully all the scenes/gameplay segments are fixed, but all the ones I've test so far have worked great. The only minor thing is occasional hitching, but that could just be because of my hardware. Thank you for trying to help though, your suggestions probably would have worked if my original version of SH2 wasn't randomly borked.

**Comment by Polymega** [comment]
I'm glad a fresh install seems to have addressed most of your issues.

The occasional hitching may likely be "normal," in that the game can only run stable on one CPU core and it uses 100% of that core at all times, which causes bottleneck situations where the game is competing for resources over itself (and anything else using that core) on the one thread it has maxed out.
