### ISSUE TITLE
sh2pc.exe not start

### ISSUE THREAD

**Issue by merl1989** [elishacloud/Silent-Hill-2-Enhancements#488]
I try to start the game via sh2pc.exe, but, nothing happens ( nothing black screen or other ), is like i never start the exe file of the game.

I deleted my previus directory of the game and re-istalling SH2 with the update files in our website(included the exe), but the problem persist.

And also, the d3d8.log not been create after the start of sh2pc exe.

Anyone know the fix for this problem?
Or, is a critical issues caused of windows 10 updates?

Sorry for my bad english :(

**Comment by Polymega** [comment]
> And also, the d3d8.log not been create after the start of sh2pc exe.

That means the project isn't hooking into the game at all. Or, in other words, the project isn't taking effect.

Can you share a snapshot of the game's folder on your computer?

**Comment by Polymega** [comment]
Hm... Everything looks to be correct in your folder. I'm not totally sure why the game isn't launching for you. Perhaps your virus protector is preventing the game from launching? Have you tried restarting your PC?

You can also try these two things:

- Temporarily remove these files from the game's directory:
   - `alsonft.ini`, `dsoal-aldrv.dll`, `dsound.dll`

Does the game launch for you then? 

If not, open the d3d8.ini file and set `d3d8to9 = 0` inside the file. Does the game then launch?

**Comment by merl1989** [comment]
Thanks for the help :)

i when remove the three file the sh2pc.exe give one message error and say is impossible start the application correctly, with code (0x0000142).

The second solution not work.

I recent install one firewall third party on my pc (zonealarm).
Maybe is this the cause of my problem?

**Comment by merl1989** [comment]
No problem.

**Comment by Polymega** [comment]
Were you able to resolve your issue?

**Comment by merl1989** [comment]
I have uninstall zonealarm and now work fine.

**Comment by Polymega** [comment]
Great! Glad to hear it was a relatively simple fix. Enjoy the game!
