### ISSUE TITLE
Request as a composer

### ISSUE THREAD

**Issue by hikoentertainment** [elishacloud/Silent-Hill-2-Enhancements#489]
Hello, my name is Héctor and I am a composer :). 

I'm a fan of Silent Hill and more specifically Silent Hill 2 is one of my games in the saga, in fact it's my favorite of the whole saga and I'm very excited about this project. I would like to offer my knowledge as a composer for this project. I hope I can contribute my grain of sand to this incredible project 😊.

Greetings!!!!!!

Hector

**Comment by Polymega** [comment]
Hello Héctor,

Thanks for reaching out to us. At this time, all planned audio work has been complete for the game. For our project, the audio work mostly involved porting over all of the PlayStation 2 sound files for use on the PC version. 

I want to thank you very much for offering your time and help with the project. I will keep you and your message in mind if something comes up that will involve new audio work.

Thanks again!

**Comment by hikoentertainment** [comment]
> Hola Héctor,
> 
> Gracias por ponerte en contacto con nosotros. En este momento, se ha completado todo el trabajo de audio planificado para el juego. Para nuestro proyecto, el trabajo de audio involucró principalmente la transferencia de todos los archivos de sonido de PlayStation 2 para usar en la versión de PC.
> 
> Quiero agradecerte mucho por ofrecer tu tiempo y ayuda con el proyecto. Te tendré en cuenta a ti y a tu mensaje si surge algo que implique un nuevo trabajo de audio.
> 
> ¡Gracias de nuevo!

**Comment by hikoentertainment** [comment]
Many thanks!!!!! :D

**Comment by Polymega** [comment]
Thanks again for reaching out, hikoentertainment. I'm going to close out this ticket but I've got your notes on this!
