### ISSUE TITLE
I couldn't solve this insidious black menu problem for 2 hours now!

### ISSUE THREAD

**Issue by fumingnow** [elishacloud/Silent-Hill-2-Enhancements#490]
Hi, 

Sorry to disturb for a problem that is solved for some people before, but it persists for me for hours now. It is this black menu... I see the white mouse pointer over a complete black background. The pointer moves, the sound comes when it lands on the options, I blindly start the game, everything's fine, game plays beautifully but the in-game menu is black, like the main menu.

Here:

![Screenshot 2022-02-10 15-00-33](https://user-images.githubusercontent.com/99402883/153416599-78cf3f99-d304-4a41-8eba-f8de8face6dc.png)

I read everthing related here, did what is written... replacing the "option_msg" files with the provided TEST folder, deleting the "option_msg" files, moving the whole game folder to c: under program files, selecting different core affinity options, changing PauseMenuFix to 0 in the .ini file, removing dsound etc etc.. nothing works.  I'm at my wits' end here.

I obtained the game from myabandonware, it is "silent hill 2 restless dreams". OS is Win7 32bit, gfx 1030. 

I also removed the d3d8.dll to see if the vanilla game works, and yes it does.

I attach the log if anyone's interested. Have a nice day.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8040828/d3d8.log)

**Comment by fumingnow** [comment]
the save menu background is also black, as you've suspected. no maria or james face.

I've renamed the pic folder to disable to upscaled images, but no go again. the konami pic at the startup got larger, the mouse pointer returned to default blade icon, but other than that everything (black menu, black save background, black inventory) stayed the same.

this is really very baffling.

**Comment by Polymega** [comment]
> I've renamed the sh2e pic folder to disable the upscaled images, but no go again

If it's also not displaying the vanilla images then something else is going on. Try this next: Temporarily remove `d3d8.dll` from the game's directory. This removes the bulk of our project from the game. Are these images still black for you?

**Comment by fumingnow** [comment]
i removed the d3d8.dll and booted the game. at "konami" it froze and became unresponsive. i alt+tabbed and shut down the game. then the game opened in safe mode and the black backgrounds were all gone, everything was ok.

so... the plot thickens, eh... tomorrow i'll copy the whole folder to my other rig, 64 bit win10/1050 Ti, and see what happens.

**Comment by Polymega** [comment]
> i removed the d3d8.dll and booted the game. at "konami" it froze and became unresponsive.

Okay, that tells us it's likely not an issue with the project but a fault with the vanilla game install or another package. Try this next: Temporarily remove these files from the game's directory:

- **DSOAL package:** `alsoft.ini`, `dsoal-aldrv.dll`, `dsound.dll`
- **XInput Plus package:** `Dinput.dll`, `Dinput8.dll`, `XInput1_3.dll`, `XInputPlus.ini`

Keep `d3d8.dll` temporarily removed for now as well. Does the game launch and can you see the images then? If so, then it's an issue with either DSOAL or XInput Plus. If the game still freezes or you still can't see images it's likely an issue with the install of the base vanilla game. I'd then suggest reinstalling everything.

Start with [Step 1](http://enhanced.townofsilenthill.com/SH2/install.htm#installGame) on the guide **_and also_** perform to [Step 2](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE). After Step 2, launch the game to ensure everything works. If it does, proceed with Step 3 then test launch the game again. If everything works, proceed with Step 4 and test again. Do this for all steps.

> edit: btw, i realized something. there are no "D3DCompiler_43.dll" and "D3DX9_43.dll" in the game folder. In troubleshooting it says "This file is only created if needed. It is part of the D3DX library, which allows Silent Hill 2 to run in DirectX 9." My ini file has "d3d8to9 = 1" yet i cannot see these 2 files.

This should be fine. This means you have the necessary DX9 drivers already installed in your Windows, so there is no need to make local copies in the game folder for it to work.

**Comment by fumingnow** [comment]
I deleted everything and started from scratch.

I extracted the "silent hill 2" folder from the copy "Silent-Hill-2-Restless-Dreams_Win_EN_Fully-Extracted-Version.rar" (just exract and play, no install) and applied only the "sh2pc.exe" file from "SH2PC_Enhanced_EXE_NA_v1.0". Then I booted the game. It crashed at the konami screen, well not crash per se, just became unresponsive. So I alt+tab, the desktop resolution was 640*480 etc etc.... then I booted again, of course it started in safe mode, and everything was fine....

I obtained another version of the game (Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™). it was again, "extract and play", no installation. I again applied only the "sh2pc.exe" file from "SH2PC_Enhanced_EXE_NA_v1.0". Everything went exactly like the other copy. Crash at konami, boot safe, everything normal.

Wow, here is another twist.. I ran "djdevastate" version with its original exe, no crash at konami. Arrived at the menu, there was some flickering on and off, so I alt-tab and returned the game, it was fine. no crash happened. There must be something going on in the "sh2pc.exe" file from "SH2PC_Enhanced_EXE_NA_v1.0 for my system...

**Comment by AeroWidescreen** [comment]
> We have learned that older integrated graphic processors (IGPs) can't handle high resolutions. But I don't know if that may also be the case for the GTX 1030?

This was my first thought when I saw his GPU. The GT 1030 isn't that powerful; it has 2 GB of VRAM and low memory bandwidth. Absolutely better than your average Intel iGPU, but not by a huge margin. But even so, his system should be capable of running the original game at least.

@fumingnow 

This is a long shot, but have you tried updating your drivers? I see you're using Nvidia driver 382.23, but the latest version for your card appears to be 473.04. 

https://www.nvidia.com/Download/driverResults.aspx/186161/en-us

Could you also tell us which CPU you're using? If you're not sure, you can open Task Manager and it should be listed in the Performance tab.

**Comment by fumingnow** [comment]
@Polymega, no problem, thanks for the interest!

@AeroWidescreen, that driver you've included is for 64 bit. the latest drivers, i could find, for gt 1030 for 32 bit is 391.35. i updated to that, but zilch again.

my cpu is phenom X4 955. 

Anyway, I will try the folder with my other rig (i3-64bit win10-1050ti), and see what happens.

This is really an interesting case.

**Comment by fumingnow** [comment]
Yep, in the other rig (i3-64bit win10-1050ti), everything worked perfectly. no issue at all.

so it is clear that the problem was in the system. maybe i'll format, install a 64 bit and see then.
