### ISSUE TITLE
d3d8 don't work on crossover(wine) on m1 mac

### ISSUE THREAD

**Issue by shpatter** [elishacloud/Silent-Hill-2-Enhancements#494]
Hello, i downloaded all the resources for the sh2ee and when i run i only run the sh2dc and no d3d8.log file are created. I run this in a CrossOver(Wine) on M1 Macbook Air. Game works but it's a Silent Hill 2: Director's Cut not Silent Hill 2: Enhanced Edition. I tried to download the DirectX and it didn't help. I tried to run only with the d3d8 and it also did not help. Please Help! This is screenshot of my files.
[screenshot](https://user-images.githubusercontent.com/100710069/156208601-92ab207c-67cc-4486-8200-4772c4ea0b96.png)

**Comment by shpatter** [comment]
ohh i mean d3d8

**Comment by nipkownix** [comment]
I don't know about CrossOver or Mac OS, but on Wine (using linux), you have to set up dll overrides for dll wrapping mods (such as this one) to work.

You have to open WINE's configuration window and add a dll override for d3d8.dll. It should look like this:

![image](https://user-images.githubusercontent.com/33870163/156261655-fb2bcbf0-8557-449e-bc21-cf1287263502.png)

Of course, in this case, it is "d3d8.dll (native, builtin)"

**Comment by shpatter** [comment]
It works! Thanks
