### ISSUE TITLE
GPU (Nvidia) Anti-Aliasing settings are not enabled when playing in Fullscreen mode. 

### ISSUE THREAD

**Issue by UwUapple1** [elishacloud/Silent-Hill-2-Enhancements#496]
Hello and good day once more. 

I've come to report a curiosity in regard to a [workaround](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/495#issuecomment-1060018283) involving issue #495, where I changed the _**"ScreenMode"**_ from "Windowed fullscreen" (2) to "Fullscreen" (3) in order to properly realign the cutscene borders. However, in doing so I noticed that James and Maria looked "crispier" than I had remembered, making me experiment with the GPU settings and _"d3d8.ini"_ file. As a result, I found that despite having the Anti-aliasing settings enabled, the game would appear as if it were absent. While this may sound impertinent, is it also possible that this affects _Anisotropic filtering_ as well?

![ScreenShot_20220308080044](https://user-images.githubusercontent.com/101050238/157248896-58ec2645-bb0b-48a2-9822-64a0a5f5af2d.png)

![sh2pc exe Screenshot 2022 03 08 - 07 05 16 02](https://user-images.githubusercontent.com/101050238/157249028-b67d60a4-673e-45bb-98d0-cdaf4ed88153.png)

![sh2pc exe Screenshot 2022 03 08 - 07 00 06 68](https://user-images.githubusercontent.com/101050238/157254240-86fcdaaa-b74a-4d57-a14d-ab3e95f71802.png)

Of course, this could be an issue with the Nvidia Drivers itself―or even the latest GeForce update―and _**Silent Hill 2**_ being originally a PC port from the early 2000s doesn't exactly lend itself to compatibility. 

Setting the _**"ScreenMode"**_ back to "2" re-enables the Anti-aliasing (GPU) but causes cutscene borders to be misaligned when **_"DisableCutsceneBorders"_** is set to "0"; which I fully recognize is something not many people will utilize.

![sh2pc exe Screenshot 2022 03 08 - 07 15 20 07](https://user-images.githubusercontent.com/101050238/157254325-e2cc3e4f-ae84-496b-b6df-566dd24256a1.png)

![sh2pc exe Screenshot 2022 03 08 - 07 00 44 38](https://user-images.githubusercontent.com/101050238/157254523-29e5c862-189b-4d75-8087-1f9c6b27052b.png)

Fortunately, the **_"Enhanced Edition"_** comes with its own Anti-aliasing (SMAA) and works regardless of what _**"ScreenMode"**_ is set to; which I find very satisfactory.

Any assistance or insight would be greatly appreciated. 

As always, thank you for your time and work.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8206916/d3d8.log)

**Comment by Polymega** [comment]
Yes, this is a quirk of GPU anti-aliasing for us, unfortunately.

![image](https://user-images.githubusercontent.com/27395260/157276424-660310cd-3ed9-4757-99f9-0d0ed8734cb2.png)

Although, from my understanding, anisotropic filtering shouldn't be affected by any screen mode as this feature was essentially remade for the game/project by Elisha.

I wouldn't worry too much about the pixel gap in the cutscene borders; I'm confident this is another slight misalignment issue with vertex coordinates which would be a relatively straightforward thing Elisha could address.

**Comment by UwUapple1** [comment]
Many thanks for the response. To be honest, I'm a bit embarrassed for missing something like that. Please forgive me for my oversight, and feel free to close or remove the issue if you so wish.

Farewell, and good fortune towards you and rest of the team. Needless to say, the work put into this project is nothing short of exemplary.
