### ISSUE TITLE
Language issue on SH2 Config

### ISSUE THREAD

**Issue by JPCKAileen** [elishacloud/Silent-Hill-2-Enhancements#499]
![Captura de Tela (325)](https://user-images.githubusercontent.com/71686015/158020046-1fd455f0-0a50-45a0-bee8-7868deaeb76b.jpg)
how i fix this?

**Comment by nipkownix** [comment]
You're not using the enhanced edition, you're using a Russian mod called "new edition". There's probably no way to change the language.

I'd recommend you to get a clean copy of the game and then install the enhanced edition mod from the official website.
