### ISSUE TITLE
Woodside Apt. Room 205 Fixes

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#5]
@Bigmanjapan I'd like to keep the gravy train rolling with how knowledgeable you are with so many issues and their solutions. 

Is there a way to darken the mannequin dress, James' back, and dormant Mannequin before acquiring the flashlight? 

![sh2pc 2018-05-28 17-45-55](https://user-images.githubusercontent.com/27395260/40630292-765b4098-629f-11e8-9845-d02549d95c4b.png)
![sh2pc 2018-05-28 17-45-47](https://user-images.githubusercontent.com/27395260/40630293-7795197a-629f-11e8-8b4d-a87f3d91b3bd.png)

It also totally ruins the surprise of the Mannequin coming to life before you obtain the light. I also tested this on the vanilla PC version (no fixes being used) and these lighting issues are still present. In the PS2 version the Mannequin is as dark as the other objects around it before obtaining the light. 

If you turn off the flashlight after you obtain it the dress and Mannequin monster will be properly dark: 

![sh2pc 2018-05-28 17-46-24](https://user-images.githubusercontent.com/27395260/40630286-6f4b1a58-629f-11e8-9ae5-6b0ecf91c415.png)

Is there maybe a function that can be written such as: 

**IF** inside Room 205 **AND** flashlight is not in James' inventory **THEN** correctly darken dynamic objects (dress, James, Mannequin monster) inside this area?

**Comment by Polymega** [comment]
Here's a PS2 screenshot just for fun (the lighting it also a bit different overall; I wonder if that's affecting it any?): 

![image](https://user-images.githubusercontent.com/27395260/40630711-eca13958-62a2-11e8-8b52-69f910e500fb.png)

**Comment by Polymega** [comment]
I'm going to guess the light source is overall too strong from the flashlight before acquiring it in this room? So strong that it both lights up the Mannequin and James' backside even when he's looking directly at the light.

**Comment by Bigmanjapan** [comment]
Isn't it the same issue discussed here? https://github.com/ThirteenAG/WidescreenFixesPack/issues/409
Flashlight on the mannequin stand is controlled via the same code as the one James carries. A mannequin monster behind is a dynamic object, so there is no shadow on it? If the issue with flashlight is fixed, then the mannequin would be dimmed properly. 

It is possible to crank up shadows intensity tho: https://youtu.be/ShKi3itfhs8

sh2pc.exe+542A40 (00942A40) float red channel
sh2pc.exe+542A44 (00942A44) float green channel
sh2pc.exe+542A48 (00942A48) float blue channel

**Comment by Bigmanjapan** [comment]
Isn't it the same issue discussed here? ThirteenAG/WidescreenFixesPack#409
Flashlight on the mannequin stand is controlled via the same code as the one James carries. A mannequin monster behind is a dynamic object, so there is no shadow on it? If the issue with flashlight is fixed, then the mannequin would be dimmed properly.

It is possible to crank up shadows though: https://youtu.be/uk00OxQstV4

These two sets of addreses control lightning / shadows intensity:

sh2pc.exe+542A40 (00942A40) float red channel
sh2pc.exe+542A44 (00942A44) float green channel
sh2pc.exe+542A48 (00942A48) float blue channel

sh2pc.exe+542A50 (00942A50) float red channel
sh2pc.exe+542A54 (00942A54) float green channel
sh2pc.exe+542A58 (00942A58) float blue channel

**Comment by Polymega** [comment]
> Isn't it the same issue discussed here? ThirteenAG/WidescreenFixesPack#409

No, I don't believe so. Because this isn't an issue with shadows being cast on the dormant Mannequin. When James is in front of the flashlight the Mannequin in the back will not have a shadow cast on it (the same is true for the PS2 version). 

Please note when I say shadow I mean [this](https://upload.wikimedia.org/wikipedia/commons/b/b7/The_Skate_Park_Shadows.jpg). 
To confirm: When you say shadow are you referring to this (below)? 

![image](https://user-images.githubusercontent.com/27395260/40657565-5acf951e-6316-11e8-8b8c-031e5bfcc16b.png) 

If that is what you mean, then I think the issue may be a combination of "shadows" (dark areas on the model) and highlights (from the light intensity of the flashlight on the mannequin). If we brighten your photo (taken from the YouTube video) and look at it again we can see the Mannequin and James' back are still fairly luminescent which is not what we want. Also, the Mannequin's model looks "weird" because of how harsh the light-to-dark areas are on its body now: 

![image](https://user-images.githubusercontent.com/27395260/40657692-bd7edd78-6316-11e8-9283-14d7ebadf8c0.png)

And for comparison, here is the PS2 photo brightened. Notice how the dormant Mannequin blends in exactly the same as the random mannequin pieces behind it on the sofa. Also notice how James' back is still solidly dark overall: 

![image](https://user-images.githubusercontent.com/27395260/40657937-95246694-6317-11e8-97a9-e1cdb355b33c.png)

Also, if compare your photo to the PS2 photo we can notice how the mannequin dress is almost glowing because of how bright it is: 

![untitled-1](https://user-images.githubusercontent.com/27395260/40658074-0249e47e-6318-11e8-8932-7815aa5b76dc.gif)

This is why I think it may be the light's intensity causing issues? 

Is there a way to decrease the light intensity of the flashlight on the mannequin dress? Has this been attempted? I'm wondering if you decrease its intensity then perhaps the Mannequin monster and James' back would become correctly dark again as well? And maybe by decreasing the light intensity you would not have to adjust the "shadows" (dark areas on the models) as much or at all?

**Comment by Polymega** [comment]
> These two sets of addreses control lightning / shadows intensity:
> 
> sh2pc.exe+542A40 (00942A40) float red channel
> sh2pc.exe+542A44 (00942A44) float green channel
> sh2pc.exe+542A48 (00942A48) float blue channel
> 
> sh2pc.exe+542A50 (00942A50) float red channel
> sh2pc.exe+542A54 (00942A54) float green channel
> sh2pc.exe+542A58 (00942A58) float blue channel

Or can these values be compared to the PS2's version here before acquiring the flashlight?

**Comment by Polymega** [comment]
In the meantime, I'm still not really sure what I'm doing here but thanks to your notes Bigmanjapan I think I did something, lol. I did this on my laptop (the blacks are _very_ dark on this screen) so I would need to see how this looks on my home monitor as well but here's possibly something: 

![image](https://user-images.githubusercontent.com/27395260/40661124-ec909958-6320-11e8-9b6c-2516dd538542.png)

The dress is still glowing bright as ever but it's whatever. Although, the blinn/phong shader on the Mannequin monster is much more intense on the PC version. I wonder if @Aerowidescreen could disable it on the enemy for this room before the flashlight is acquired? 

![image](https://user-images.githubusercontent.com/27395260/40661343-7a9ee970-6321-11e8-93a9-43f20af24326.png)

**Comment by Polymega** [comment]
> These two sets of addreses control lightning / shadows intensity:
> 
> sh2pc.exe+542A40 (00942A40) float red channel
> sh2pc.exe+542A44 (00942A44) float green channel
> sh2pc.exe+542A48 (00942A48) float blue channel
> 
> sh2pc.exe+542A50 (00942A50) float red channel
> sh2pc.exe+542A54 (00942A54) float green channel
> sh2pc.exe+542A58 (00942A58) float blue channel

Please double-check my statement here but I don't think those addresses affect the Mannequin monster, James, or the dress as we'd like. 

If you set all these values to 0 the Mannequin monster, dress, and James will be darkened but so will the rest of the room. But the rest of the room (outside of the flashlight area) will be pitch black which is not the result we would be looking for. We'd be looking to keep the darkness of the room as-is but _only_ darken the Mannequin monster, dress, and James' to better match the current darkness of the room.

It seems like the Mannequin monster, dress, and James have another set of addresses/values that affect their luminosity _in addition_ to the values you stated above. 

So now that I understand that... 

> Isn't it the same issue discussed here? ThirteenAG/WidescreenFixesPack#409

This may be related to that issue after all...

**Comment by Polymega** [comment]
Okay, now I'm just unsure... Because once you equip the flashlight the Mannequin and dress are properly darkened even when the light is on so long as the objects are behind James' flashlight: 

![image](https://user-images.githubusercontent.com/27395260/40667167-74e18ae8-632f-11e8-8814-e99618e533aa.png)

And, as also mentioned, the Mannequin and dress are also properly dimmed once you obtain the light and turn it off: 

![image](https://user-images.githubusercontent.com/27395260/40630286-6f4b1a58-629f-11e8-9ae5-6b0ecf91c415.png)

So that means it's _not_ an issue with the flashlight with dynamic objects? Yes? But instead some sort of address(es) that are enabled special just for this room, prior to obtaining the light? 

I'm confused now...

**Comment by Bigmanjapan** [comment]
> To confirm: When you say shadow are you referring to this (below)?

Yes. I meant dimming on the models themselves.

> Please double-check my statement here but I don't think those addresses affect the Mannequin monster, James, or the dress as we'd like.

> So that means it's not an issue with the flashlight with dynamic objects

It is an issue with the mannequin stand flashlight lightning. Apparently it has a piece of it's own code.

https://youtu.be/UwbLcv6fEJI

sh2pc.exe+3F72F0 (007F72F0) float
sh2pc.exe+3F72F4 (007F72F4) float
sh2pc.exe+3F72F8 (007F72F8) float

Change these three to any value betwen 2 and 6. 

While it seems that these three addresses control only that situation when the flashlight is on the mannequin stand, I would advice to return the values back to 7 once James leaves the room.

**Comment by Polymega** [comment]
> It is an issue with the mannequin stand flashlight lightning. Apparently it has a piece of it's own code.

![image](https://i.imgur.com/ydm5h58.jpg)

@AeroWidescreen one of these days I'll stop tagging you but not today. :) @Bigmanjapan has done his black magic once again!

**Comment by Polymega** [comment]
Copying from the discussion [found here](https://github.com/elishacloud/dxwrapper/issues/9#issuecomment-395981292). @Bigmanjapan also found a way to hide the blood pool that forms around the mannequin when loading into this room _before_ the creature comes to life. This fix can go hand-in-hand nicely with the luminescence fix. 

Quoting from his post: 

> This blood stain is formed via three layers.
> Change their Y coordinates to shift them underneath the floor. I don't know if something else accesses the addresses, so a single change of value to 128 upon entering the room should be fine. Better to leave the addresses unfrozen to make sure it doesn't break anything else in the game later on.
> 
> sh2pc.exe+556364 (00956364) float
> sh2pc.exe+5563BC (009563BC) float
> sh2pc.exe+556414 (00956414) float
> 
> Change them to 128.
> 
> https://youtu.be/0Brt9z60Rew
> 
> Interestin fact: blood stain Y position is calculated from mannequin Y position. If you change mannequin Y position via address in the next message, freeze the value and re-enter the room — blood stain will also be shifted on Y axis following the mannquin.

**Comment by Polymega** [comment]
@Bigmanjapan I've changed the title of this support ticket, as Woodside Apt. Rm. 205 is apparently a mess that needs a lot of love and care put into it. Especially for the PC version, it seems like the game wants to spoil/ruin the mannequin surprise in any way it can.

Anyway, I'll also copy + paste [your post here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/13#issuecomment-420201493) below:

> Returning to the mannequin flashlight room. Dormant mannequin is still considered an enemy and on beginner / easy action difficulties James will often go into battle stance mode upon trying to pickup a flashlight if a player has a wooden plank equipped (because an enemy is behind the flashlight).
> 
> It's on all official console versions but still doesn't feel right logic wise. It should be possible to disable autoaim for this room until the mannequin is awake.

**Comment by Polymega** [comment]
So where does this leave us in terms of what to fix? 

### IF James is in Room 205 AND the flashlight is not in his inventory: 

| Fix found? | Description | Address (v1.0) | Original value | New value |
| --- | --- | --- | --- | --- |
| :heavy_check_mark: | Change "luminescence" values so James, mannequin, and dress no longer glow. | 007F72F0, 007F72F4, 007F72F8 | 7 | 0 |
| :heavy_check_mark: | Hide pre-made blood pool around dormant mannequin (happens if you Quick Load into room). | 00956364, 009563BC, 00956414 | -3 | 128 |
| | Remove "shine" on dormant mannequin. | | | |
| | Prevent dormant mannequin from spinning around when coming to life. | | | |
| | Prevent battle stance when near dormant mannequin. | | | |

### IF James RE-ENTERS Room 205 with flashlight NOW ACQUIRED

| Fix found? | Description | Address (v1.0) | Original value | New value |
| --- | --- | --- | --- | --- |
| :heavy_check_mark: | Slightly move blood pool up. This is because, if blood forms on carpet, it visually glitches as the blood will form _inside_ the carpet. | 00956364, 009563BC, 00956414 | 0(?) | -3 |

**Comment by Bigmanjapan** [comment]
> Remove "shine" on dormant mannequin until flashlight is acquired.

sh2pc.exe+4A0020 (008A0020) 4 bytes

Find you what writes to the address (F6) and NOP the only instruction that the scanner will show. 
Then set the value of the addresse to 0xFFFFFFFF.

I haven't check thoroughly if something else gets broken in the room if the instruction is NOPed. It seems to be only operation on the shine of the mannequin. If you freeze the address while the instruction is active, then the shine will be locked at one position regardless of James movement / camera change.

![default](https://user-images.githubusercontent.com/31383389/50738654-1ce0a200-1209-11e9-9612-6a29d62b3bc2.png)

**Comment by Bigmanjapan** [comment]
> Remove "shine" on dormant mannequin until flashlight is acquired.

sh2pc.exe+4A0020 (008A0020) 4 bytes (the value is actually a float but it's better to treat is as 4 byte in this case)

Find out what writes to the address (F6) and NOP the only instruction that the scanner will show. 
Then set the value of the address to 0xFFFFFFFF (in float terms you need to put a NaN (Not-a-Number) value here)

I haven't check thoroughly if something else gets broken in the room if the instruction is NOPed. It seems to only operate on the shine of the mannequin. If you freeze the address while the instruction is active, then the shine will be locked at one position regardless of James movement / camera change.

![default](https://user-images.githubusercontent.com/31383389/50738654-1ce0a200-1209-11e9-9612-6a29d62b3bc2.png)

**Comment by Polymega** [comment]
@Bigmanjapan 
Just for your records, `sh2pc.exe+1B9A903 (01F9A903)` byte might have something to do about whether or not the Mannequin in the flashlight room loads incorrectly before acquiring the flashlight.

The byte is set to `0` while in this room when the Mannequin is correctly positioned on the floor. The byte changes to `1` when he's loaded incorrectly before acquiring the light. 

After acquiring the light, that byte changes to `1` regardless. 

`sh2pc.exe+1B9A823 (01F9A823) byte` also might have something to do with it, but I'm not sure.
