### ISSUE TITLE
[SH2] WineD3D hangs/freezes at startup

### ISSUE THREAD

**Issue by lleeoo2010** [elishacloud/Silent-Hill-2-Enhancements#50]
Hello all, I've been following the instructions perfectly at enhanced.townofsilenthill.com/SH2/ and the game will work perfectly up until I add WineD3D for Windows. After that game will just hang at startup. I've looked at their troubleshooting page and everything seems to be in order, so I'm at a loss. I'd really like to get WineD3D working since, I have the issues that it's supposed to fix, otherwise I'd just skip it and play.

Just in case you need any specs. I'm running on an Intel 4790K 16GB RAM GTX 1080 on a ASUS Maximus VII Hero

Thanks in advance.

**Comment by Polymega** [comment]
Hi @lleeoo2010 ,

We've learned from others that the GTX 1080 card doesn't play nice with WineD3D. 

We're currently looking in to fixing what WineD3D fixes without having to use said software. That way, we'd keep the game running as DirectX and should run better/faster in general.

We don't have a time frame for when this will be done but you can keep track of progress here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/10

**Comment by lleeoo2010** [comment]
No worries, thanks for the quick response, will do!

**Comment by elishacloud** [comment]
@lleeoo2010, WineD3D can take up to 2 minutes to load on some computers. Just wait a bit longer and it should eventually load.  But as @Polymega mentioned WineD3D has some issues with Nvidia 1080 GTX.

Attached is an update that fixes some the WineD3D issues.  If you are going to play without WineD3D I recommend using this one: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2429028/d3d8.zip)

**Comment by lleeoo2010** [comment]
Waited longer but still didn't open. The d3d8 worked. Thanks for all of your hard work. You guys definitely have made this the definitive way to play this game!
