### ISSUE TITLE
Alternate Stomp Enabler

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#500]
The following assembly code enables an alternate ground stomp that was _extremely rare_ on PC due to the lack of pressure sensitive face buttons. With this code there will be a 50/50 chance that this ground stomp will happen, based on the game's internal timer. 

Big thank you to @Polymega for proposing the idea and assisting me.

```
005345E1 - call 00000000
005345E6 - nop 
```
DWORD TimerInt32;

```
00000000 cmp cl, 07
00000001 jne 00000010 // jumps to ExitCode if not Light Stomp

RNG:
00000002 fld dword ptr ds : [01DBBF94] // Loads Timer
00000003 fistp dword ptr ds : [TimerInt32] // Stores Timer as Integer
00000004 push edx
00000005 mov dl, byte ptr ds : [TimerInt32]
00000006 and dl, 01
00000007 pop edx
00000008 je 00000010 // jumps to ExitCode if TimerInt32 is not Even (50/50)

EnableHeavyStomp:
00000009 mov cl,03

ExitCode:
00000010 mov dword ptr ds : [eax+00000493], cl
00000011 ret
```

**Comment by Polymega** [comment]
Thank you very much, Aero_. What a nice and simple way to bring back an animation that otherwise would never really be seen.

```ini
; Restores alternate stomp animation. When performing a stomp, there is now a 50/50 chance of receiving either stomp animation. (0|1)
RestoreAlternateStomp = 1
```

https://user-images.githubusercontent.com/27395260/158183446-ab66ef02-dbb1-4404-9536-ec716635d1be.mp4

**Comment by elishacloud** [comment]
Try this update.  It only works on SH2 version 1.0, as I hard coded all the addresses.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8356386/d3d8.zip)

**Comment by Polymega** [comment]
Yep, this is good for 1.0.

Thank you very much, Elisha.

**Comment by elishacloud** [comment]
I believe this should work on all versions of the game.

Testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8356462/d3d8.zip)

**Comment by Polymega** [comment]
Yes sir, it does. Much appreciation.
