### ISSUE TITLE
Game is not using Nvidia graphics card on laptop

### ISSUE THREAD

**Issue by sr-fatman** [elishacloud/Silent-Hill-2-Enhancements#501]
Hi there.

I'm playing this game on a laptop, which has a intergrated intel graphics card and a Nvidia graphics card. But I can't run this game on the Nvidia one, even I set the global setting to Nvidia one in the Nvidia control panel or Windows display settings.

Here's the d3d8 log, sorry for my poor English.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8341265/d3d8.log)

**Comment by Polymega** [comment]
Hello,

Looking at your log files there are several things to discuss:

--------------------------------

It appears the game is using your nVidia GPU. This can be found here in your log file:

```
4608 19:52:29.500 |---------- VIDEO CARD ----------
4608 19:52:29.500 | m_IDirect3D8::CreateDevice Using video card: NVIDIA GeForce GTX 1050 Ti (0x10de)
4608 19:52:29.500 |--------------------------------
```

---------------------------

You have a lot of files/folders in your game's directory which probably shouldn't be there. These extra files/folders might be the cause of this log error:

```
4608 19:52:28.544 Hook::HotPatch Error: 'CreateProcessA' is not patch aware at addr=76F23AB0
4608 19:52:28.544 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\xD5\xC7\xA8\xFE\x5D\xFF
4608 19:52:28.544 Hook::HotPatch Error: 'CreateProcessW' is not patch aware at addr=76F088E0
4608 19:52:28.544 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\x65\x79\xAA\xFE\x5D\xFF
``` 

[You want your game's directory to only have these files/folders.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree) Remove all files/folders that are not shown in that directory tree.

**Comment by sr-fatman** [comment]
> 

OK thanks, maybe some of the extra files are for localization, I'll ask the translator about it.
