### ISSUE TITLE
Missing textures when entering Ernest's room in SH2 Born from a wish

### ISSUE THREAD

**Issue by aintnodawn** [elishacloud/Silent-Hill-2-Enhancements#502]
The game runs well before I make it to Ernest's room. I don't know if the rest of other areas are glitched as I can't explore any further now.
![屏幕截图(889)](https://user-images.githubusercontent.com/19627609/160247692-04f6035f-114e-4a2c-8f08-e9bae1e5d9f0.png)

**Comment by Polymega** [comment]
I don't believe this is an issue with our project, but you can test by _temporarily_ removing the `d3d8.dll` file from the game's directory. This file is the "brains" of our project. Removing it will essentially revert the game back to vanilla. Does the issue still persist after doing this? If so, your install of the base game might have been bad. I would recommend re-downloading and replacing the vanilla PC game files.

**Comment by aintnodawn** [comment]
Yes it seems there's something wrong with my base files
