### ISSUE TITLE
Fringe Case Crash Issue: Loading After Meeting Maria

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#503]
### Preface
This issue will unceremoniously crash the game back to desktop. The chances of a player following the steps to provoke this crash are slim, however. This is one of those things where it'd probably be good to fix, but we've also never received a report of anyone experiencing this issue, making it an outlier problem.

### Issue
If you meet Maria then make a custom save after (but before going up the flight of stairs in Rosewater Park heading towards Jack's Inn), load this save, then try to go back the way you came (towards the apartments), the cutscene where Maria says "where are you going?" will not play and instead freezes and crashes the game: https://www.youtube.com/watch?v=VdBAK4zfl8c

### Discussion
@Bigmanjapan has done a fair amount research on the game's behavior relating to this issue. You can click the dropdown arrow right below to read his notes. We'd welcome anyone's involvement in creating a fix for this.

<details>
  <summary>READ BIGMANJAPAN'S RESEACH NOTES (MOST RELEVANT PARTS AT BOTTOM)</summary>

------------------------------

Bigmanjapan's notes are below. 
> My responses are in quotes.

------------------------------

As for the Maria cutscene, the index for that cutscene is passed by eax register, not immediate value. It's probably a stack issue as well.

The cutscene in Rosewater Park that causes issues is automatically disabled if player walks past stairs that lead to the western exit from the park (towards Jack's Inn).

One thing I want to test is using Save Anywhere combination  in PS2 build to make a savefile there and see if it crashes the PS2 port too.

> When Aero_ was working on the save/load fix, he had to ensure certain bytes were written to the save file._
>
> I'm thinking whatever flag that indicates you've met Maria isn't being saved at this point. But the game knows you already met/have > Maria. So when you backtrack at Rosewater Park there is a confliction with flags._
> 
> That's my guess, anyways._

The crash doesn't happen in PS2 when Save Anywhere function is used. It also is not an issue with the rating points that the cutscene might or might now assign when watched or not watched.

Found address that store state of the cutscene being enabled or disabled after going away from the trigger for a certain amount of distance. No clues here. I can disable the cutscene and the crash won't happen in because obviously the cutscene is disabled.

I also tried finding large fields of addresses that get changed between two states of the location and none of them seem to fix the issue when their values are returned to the "correct" state, although there are many issues with this method.

I keep returning to the idea of stack being faulty. I usually do my scans in a range of 0x00400000-0x24000000 and stack is usually stored "above" 0x00400000.

I moved to searching for bugs that could happen with pointers that point to the cutscene assets. The cutscene in question is .\demo\mar_deai_00.

One thing I do see is that upon loading the quicksave made prior to triggering the crashing cutscene, no mar_deai_00.dds file is being loaded. This results in pointer which is supposed to point to that file, pointing at something else.

I manually loaded the mar_deai_00.dds file into memory, pointed to it and the cutscene began to play. The camera angle is correct since it's contained in .dds file.

The animation are broken because the pointers for both .anm files are needed to be introduced as well. The pointer address (which generates each new load or so) to mar_deai_00.dds file is located at:

sh2pc.exe+1946C5 - A1 A839D801 - mov eax,[sh2pc.exe+19839A8]
sh2pc.exe+19839A8

.anm files are loaded following each other with 12 bytes of data between them. Their pointer is stored here and at some other instruction, not sure how it matters:

sh2pc.exe+192AF2 - 8B 0D AC39D801 - mov ecx,[sh2pc.exe+19839AC]
sh2pc.exe+19839AC

Seems that quickloading misses some information about what room is being loaded, leading to lack of assets. Or in case with other quickloading issues, lack of settings for locations. The cutscene issue is possible to be fixed with a crude solution of loading .dds/.anm files and replacing the pointers on those addresses above.

At the same time I feel like if the root cause with the quickloading is identified and fixed, then it could potentionally be a unified solution for all other quickloading issues that are currently fixed by whatever we came up with. Or maybe not.

Right now I think that the issue is that both Rosewater Park cutscene assets are loaded together, not separately. To load the assets game engine checks if the first cutscene of meeting Maria was already played or not.

If it wasn't played yet, then assets for both cutscenes are loaded in upon loading process. If it was played, then no assets are loaded at all, leaving second cutscene without needed assets.

At least in PC build since it doesn't happen on PS2 probably due to different memory management.

sh2pc.exe+25D9A6 (0065D9A6) is a starting point of the strings that carry the cutscene assets filenames. As expected the strings are polled upon loading process when the first cutscene was not played yet, after that nothing polls the strings, therefore nothing gets loaded down the road.

Game engine is capable of loading assets during regular gameplay, not only via loading process.

sh2pc.exe+194CA3 - F6 05 F3A9F701 01 - test byte ptr [sh2pc.exe+1B7A9F3],01

This is one of the instructions that checks if the first cutscene was played.

If you watch the first cutscene, make savefile, load it up to setup a scenario for the second cutscene to crash and then change 0x01 to 0x00 in that instruction, then the second cutscene will be played normally.

This change is not for any sane use since it's just tricking game engine into thinking that the first cutscene was not played yet (Maria waiting model be spawned again).

What it shows though is that the strings for the second cutscene are getting polled upon changing that byte in the instruction. And the evening phase transition is cancelled too. All in all, it shows that the assets for the second cutscene could be loaded on the fly.

> The transition is cancelled from the quick save here or when changing that instruction's value back to 0x00?

Changing the byte to 0x00. 

Changing byte at 0x00594CA9 will also partially return the conditions before watching the first cutscene.

Nevermind, it's the same thing. Evening transition doesn't seem to be broken by changing that particular instruction, it was another one.

Main issue here is that, as I stated above, once the assets loading process is triggered (in this case via a hack that makes game think that the cutscene wasn't played yet), it loads assets for both cutscenes spawning Maria model again (trigger for the cutscene is not active though, so the first cutscene won't load again).

A very slipshod way of doing the fix might be triggering the assets loading process and corrupting/disabling new Maria model fast enough.

> Yeah that does sound rather slipshod. Hopefully we can find a better approach.

Otherwise, the code that is responsible for loading the assets needs to be copied and re-worked to load only for the second cutscene.

Bytes starting from 0x01F7A9F0 store some conditions related to the cutscenes.

0x01F7A9F3 byte is set to 0x00 prior to watching the first Rosewater Park cutscene. Set to 0x01 after wathing it (this is what that instruction polls to do its comparison to 0x01).

Set to 0x03 when the second cutscene is watched.

Set to 0x07 when player crosses the area that disables the second cutscene and so on.

That byte going from 0x00 to 0x01 is the perfect moment to initialize loading assets for the second cutscene.

I mean, it could be fixed even now. Upon finishing watching the first cutscene, load the assets into unreserved memory region and change two pointers that I shown above to point to these assets.

By load I mean, using d3d8.dll instead of game engine itself.

Thinking about it now, it might be the way to do it since it doesn't involve tinkering with whatever was initially coded by the developers. Apart from changing the pointers but that's a minor change.

> Do you know if 0x01F7A9F3 is exclusively used for these Maria cutscenes?
> 
> Or is it recycled elsewhere?

It is probably used for some cutscene ahead. The values themselves of that byte doesn't matter. Only the change from 0x00 to 0x01 matters.

> Wouldn't it matter if other cutscenes also use this address? Specifically if they change from a 0 to 1 value?

They probably don't. Those values are bitmasks similar to values that store weapons and items. I doubt that they repeat.

.dds/.anm files have several bytes in their headers changed upon loading into RAM. Haven't tested if it matters if raw data is loaded manually directly into memory. I personally copied the data from RAM (with already changed bytes), to minimize headache.

> > Only the change from 0x00 to 0x01 matters.

Since it's a bitmask even the change doesn't matter, only if first bit is set or not.

### Likely most relevant part
------------------------------

I guess I was tired yesterday when I typed all of the above. The checking of the 0x01F7A9F3 byte's state is not needed at all since when first cutscene is watched the assets for both cutscenes are already loaded. What needs to be done upon quickloading a savefile in Rosewater Park is checking if the second cutscene was played or not.

That would be second bit of 0x01F7A9F3 byte.

And more than that, the code that based on my idea will load the assets for the second cutscene must be disabled when third bit of 0x01F7A9F3 byte is set (when cutscene gets disabled if player walks away too far). It doesn't mater if player watched cutscene or not, the bit gets set either way upon entering particular area of the location, therefore it's handy to use.

Or, if you want to limit the code being active even further, you can set a condition for it to work only when first bit is set  (first cutscene was watched) and second or third bits are not yet set (the second cutscene was not watched or was forcefully disabled).

In general, a bunch of addresses starting from 0x01F7A9E4 are used to flag various events, including cutscene being watching, unique items picked up, unique objects inspected and so on.
</details>

**Comment by Polymega** [comment]
Here's an illustrative example of what goes on here. I suppose a Hail Mary fix would be to disable saving within the brightened area shown below, but that approach isn't the most elegant choice. Hopefully something more robust can be found for this.

![image](https://user-images.githubusercontent.com/27395260/161159898-7776d744-04b2-4a2f-af4f-55dc7848c7e1.png)

**Comment by Polymega** [comment]
@elishacloud @AeroWidescreen @Bigmanjapan
I will need your help with this, please.

Steam006 was kind enough to look into this and create a start for this fix (below). He and I have been going back and forth with testing. The problem we've found is that I will experience issues/crashes that he does not with testing. We haven't figured out why this is the case, and is why I need your help with testing.

The issues found are below. Some of these things have also been mentioned in Bigmanjapan's initial research notes (see first post in this ticket):

- Maria's model does not spawn before meeting her (image below)
- There is a duplicate of Maria's model after the cutscene of meeting here (image below)
- Game freezes/crashes after meeting Maria, saving, loading, then triggering the "Where are you going?" cutscene (original issue)
- Game may freeze/crashe upon triggering the Laura on Wall cutscene or exiting the bowling alley

![image](https://user-images.githubusercontent.com/27395260/161404500-4e2a9ed3-88f1-4ddb-b1b0-6d0b67626b71.png)
![image](https://user-images.githubusercontent.com/27395260/161352654-78f2172d-d139-43cf-9959-1a6dc928a6d6.png)

```c++
E8 ? ? ? ? 8B 44 24 04 85 C0 75 5E
typedef void(__cdecl* _LoadMaria)(int a1);

81 EC 08 02 00 00 53 55
typedef void(__cdecl* _MariaFunction)();

void __cdecl SilentHill2_MariaFunction()
{
	BYTE bFilesLoaded[4] = { 0 };
	SIZE_T BytesRead = 0;

	ReadProcessMemory(GetCurrentProcess(), (LPVOID)0x1D83A0C, bFilesLoaded, sizeof(bFilesLoaded), &BytesRead);

	_cprintf_s("bFilesLoaded --> %d --> %d --> %d --> %d\n", bFilesLoaded[0], bFilesLoaded[1], bFilesLoaded[2], bFilesLoaded[3]);

	BYTE CutsceneValue[4] = { 0 };
	SIZE_T BytesReadCutscene = 0;

	ReadProcessMemory(GetCurrentProcess(), (LPVOID)0x1F7A9F0, CutsceneValue, sizeof(CutsceneValue), &BytesReadCutscene);

	_cprintf_s("CutsceneValue --> %d --> %d --> %d --> %d\n", CutsceneValue[0], CutsceneValue[1], CutsceneValue[2], CutsceneValue[3]);

	if (bFilesLoaded[0] == 0)
	{
		if (CutsceneValue[3] < 10 && CutsceneValue[2] != 63)
			oLoadMaria(1);
	}
	return oMariaFunction();
}
```

**Comment by TheMachineAmbassador** [comment]
I'm working on this issue right now 😁. Thanks to @Bigmanjapan's notes there is so many nice info i found .

![Address to cutsene](https://user-images.githubusercontent.com/77938614/161463945-6620496f-dee7-4484-9f51-9c1418912fbd.png)

I set break point on this 0x04a1026 (that call function is just strncmp function in c), It compares this 0094db40 and 006b06d8. If comparison is false it simply returns 0 and breaks the program. But 006b06d8 is not import its just returns "dds", i dont know what it is, i think some sort of movie extension. Important memory is this: 0094db40, as you see on cheat engine window eax loads something on that memory. But if you
> If you meet Maria then make a custom save after (but before going up the flight of stairs in Rosewater Park heading towards Jack's Inn), load this save, then try to go back the way you came (towards the apartments), the cutscene where Maria says "where are you going?" will not play and instead freezes and crashes the game: https://www.youtube.com/watch?v=VdBAK4zfl8c

do this, eax becomes 0 and cant load anything to that memory. For now i will trace back until i found what is loads to that memory. If i found what is maybe that can help us to find where to find issue.

**Comment by TheMachineAmbassador** [comment]
Aaaand after all trace backig things, went the same way as the steam006's :). yeah whatever problem is in the 0x1F7A9F0. But it might be wrong i mean maybe there is some sort of byte changing after meeting with maria,I will look at that maybe i can find something.

**Comment by TheMachineAmbassador** [comment]
Nope there is no other values for that, only 0x1F7A9F0  controls he maria's cutscenes. Even we fix that value we have to find replay 0x94DB40 because it points to dds file and plays from there (of course if we want to trigger cutscene everytime when player tries to go different way). So we have 2 ways to fix this. First one is we can disable save option at that area, second one is we will try to inject our new code to some places.

**Comment by Polymega** [comment]
Hi Machine Ambassador,

DDS files, from what I understand, are for animation data. These files are used to animate characters, items, and camera movements during cutscenes. I might be slightly mistaken with this, though. You can find this files under `.\data\demo\*\*.dds`

Steam006's code/fix above seems to have addressed the issue except for if you save very close to the trigger point of the "Where are you going?" cutscene. If you save close to this point then reload, the game will still crash when triggering this cutscene.

**Comment by Polymega** [comment]
I've been speaking with Steam006 more today. After a lot of confusion, we've figured out why I was experiencing issues when he wasn't: It seems that my Windows was using cached, virtual store versions of the test DLL files. In other words, even though I placed the new test file in the game's directory, it was polling an older version someplace else. The amount of headaches this caused...

Anyway, I've updated Steam006's code fix for this a few posts up. It should be good now. He and I have done quick tests around the Rosewater Park area, and neither of us experienced any freezes/crashes. Once we get his fix implemented into this module, I plan to sit down and do a long playtest for this in the future.

**Comment by TheMachineAmbassador** [comment]
Thats a pretty good new. Now i can get back to the multiple core issue. Also i found too many nice memory things on sh2 demo. Today i will update repo i saw you guys trying to fix 60 fps problem maybe there is something might help you too (Of course i will look at what can i do about the issue).

**Comment by elishacloud** [comment]
I think I implemented everything correctly.  Try this out.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8414237/d3d8.zip)

**Comment by TheMachineAmbassador** [comment]
It works perfectly, i tested build, only issue i had is cutscene only triggers once. But that's not a big issue, even that might be needed for game ending calculation. So we better leave that memory addresses value. I mean first thing came to my mind is after cutscene ends changing 0x1F7A9F0 to 1FE414 but as i said how does it affects to game ending i don't know .

**Comment by Polymega** [comment]
That's great to hear it's working as intended. I will do a quick test myself tonight and do a more serious test later on.

> only issue i had is cutscene only triggers once. But that's not a big issue, even that might be needed for game ending calculation.

This is correct behavior. The cutscene should only trigger one time per save file that you load in. It's the same when you leave the bowling alley and go the wrong way Maria will say, "Where are you going? That's not the way that little girl went." That cutscene should also only happen one time.

> I mean first thing came to my mind is after cutscene ends changing 0x1F7A9F0 to 1FE414 but as i said how does it affects to game ending i don't know .

Is it supposed to normally change like this? One thing I was going to have Bigmanjapan test was to ensure this fix doesn't incorrectly affect ending calculations.

**Comment by Polymega** [comment]
This cutscene should have no affect on ending calculations, which is good:
https://github.com/JokieW/SilentHill2Endings#maria

**Comment by TheMachineAmbassador** [comment]
> This is correct behavior. The cutscene should only trigger one time per save file that you load in. It's the same when you leave the bowling alley and go the wrong way Maria will say, "Where are you going? That's not the way that little girl went." That cutscene should also only happen one time.

Then we don't have to trigger everytime, that would be strange already. Imagine Maria always saying the same thing, after all that trying I guess Maria would be the moth boss and show her real face to James in the middle of the game. Game ending type would be "early leave" ending. Aaand credits :).

> Is it supposed to normally change like this? One thing I was going to have Bigmanjapan test was to ensure this fix doesn't incorrectly affect ending calculations.

Nope if you want to trigger cutscene once you don't have to because 0x1F7A9F0 memory is becomes after cutscene to 3F3414 we can tell this is a "player watched cutscene" stuff. But if we change this to 1FE414 it becomes "player didn't watch" cutscene and cutscene triggers again if player goes to that direction. So we don't have to change anything. Thats the reason why i said it might affects to game ending calculation. Also if we want to trigger everytime we have to find a way to reset this pointer 94DB40 (it's just a buffer of dds file, game reads it byte to byte) already. So we can tell issue is fixed :). I don't think it affects to game ending but we already found game ending address 01F7AA2C, we can simply observe the value, if it changes after cutscene it's good but if not then we can tell there is problem (kinda because i saw in here [website](https://www.silenthillmemories.net/sh2/endings_en.htm)  it says if you go different location it affects to game ending).

**Comment by Polymega** [comment]
> Nope if you want to trigger cutscene once you don't have to because 0x1F7A9F0 memory is becomes after cutscene to 3F3414 we can tell this is a "player watched cutscene" stuff. But if we change this to 1FE414 it becomes "player didn't watch" cutscene and cutscene triggers again if player goes to that direction. So we don't have to change anything. 

Okay that's good, as triggering this cutscene [adds a point to the Leave ending.](https://github.com/JokieW/SilentHill2Endings#leave) So we definitely want to flag this as "player watched cutscene."

> I don't think it affects to game ending but we already found game ending address 01F7AA2C, we can simply observe the value, if it changes after cutscene it's good but if not then we can tell there is problem

I would like to find a way to determine that the game is adding a point to the Leave ending when triggering this cutscene while using this fix. I'm not sure what address to monitor to confirm this. If you know how to test this please do! Otherwise I will need to ask Jokie or BMJ to test this part.

> Imagine Maria always saying the same thing, after all that trying I guess Maria would be the moth boss and show her real face to James in the middle of the game. Game ending type would be "early leave" ending.

😆 James gets smacked across the face hard enough to send him across Toluca Lake!

**Comment by elishacloud** [comment]
> ```c++
> 	ReadProcessMemory(GetCurrentProcess(), (LPVOID)0x1D83A0C, bFilesLoaded, sizeof(bFilesLoaded), &BytesRead);
> 	ReadProcessMemory(GetCurrentProcess(), (LPVOID)0x1F7A9F0, CutsceneValue, sizeof(CutsceneValue), &BytesReadCutscene);
> ```

I just realized in my code I never changed 0x1D83A0C or 0x1F7A9F0, so the build I made may only work correctly on one version of the SH2 binary.  Though I am not sure which one.  Maybe v1.0.  I don't know which version of the code those addresses comes from.

**Comment by elishacloud** [comment]
Ok, this should work on all binaries.

New testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8420486/d3d8.zip)

**Comment by TheMachineAmbassador** [comment]
> I would like to find a way to determine that the game is ~adding~ subtracting a point to the Leave ending when triggering this cutscene while using this fix. I'm not sure what address to monitor to confirm this. If you know how to test this please do! Otherwise I will need to ask Jokie or BMJ to test this part.

Of course i know where should i look at already i was reverse engineered too many parts of game ending calculation before.

> 😆 James gets smacked across the face hard enough to send him across Toluca Lake!

Devs really should have added easter eggs on there, something like if you make maria angry 3 times, play angry maria anim 😂😂😂

**Comment by Polymega** [comment]
I did quick tests on all binaries and everything appears to be good, Elisha. After Machine Ambassador confirms whether or not the game is adding a score to the ending from triggering this cutscene with this fix I'll probably do a more thorough test this weekend.

**Comment by TheMachineAmbassador** [comment]
![ending_calc](https://user-images.githubusercontent.com/77938614/161854006-3aeb2757-8440-479e-8205-287f72af7607.png)

Game calculates 4 ending sequence here, dog and ufo endings are surprize endings they don't neet to be calculated :) Jokie already shared how it works so no need for me to explain. It's kind of harry potter movie, there 4 class in here and determines the scores of behaviors. At last it checks which is bigger that other then chooses biggest number and gives you that ending. I found this value 01F7AA31(byte), if  "Where are you going?" cutscene is triggered, it decreases maria's point minus one (It's not 1 byte actually this is the 01F7AA30 real value but i shared so for an example).

**Comment by Polymega** [comment]
> I checked this value and works correctly in latest build elisha shared.

Fantastic! Thanks for confirming this.

@elishacloud 
I don't anticipate any issues with this fix since Machine Ambassador confirmed the above and that 01F7A9F0 is exclusively used for handling the cutscenes in question here. 

When you're ready, this fix can be added to `GameLoadFix`.

**Comment by Polymega** [comment]
One change/edit for this, please. I got a message from Steam006:

> I noticed that it still has the "_cprintf_s" calls, these were just used for testing/logging and can be removed as they might have a performance impact.

**Comment by elishacloud** [comment]
Ok, good catch.  Here is the final checked-in build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8422283/d3d8.zip)
