### ISSUE TITLE
Bug Map(windows 10)

### ISSUE THREAD

**Issue by ghost** [elishacloud/Silent-Hill-2-Enhancements#508]
Hello, I installed your patch and everything worked perfectly, until you enter Silent Hill for the first time, the green icon the map that represents James disappears making exploration difficult, it happens every time you enter Silent Hill
is there any way to solve it?

![IMG_20220411_192627](https://user-images.githubusercontent.com/103466480/162849244-ad753f72-e722-4177-b672-4084aa23ed2e.jpg)
![IMG_20220411_160318](https://user-images.githubusercontent.com/103466480/162849253-a8834d13-374a-4202-9b9d-317e3de7e488.jpg)

**Comment by Polymega** [comment]
Hello,
Please attach a copy of your d3d8.log file found in the game's main directory.
