### ISSUE TITLE
Reshade & Filters issue

### ISSUE THREAD

**Issue by asmith985** [elishacloud/Silent-Hill-2-Enhancements#51]
Hi guys,
First of all. Thank you SO much... You guys are amazing bringing this classic back to life... I really hope you might turn your eyes to Silent Hill 3 & 4 eventually.

I'm running in 4K on Windows 10 64bit on an i7 8700k with GTX 1080 ti. The game runs flawless as long as I delete the reshade & filter files and turn off everything running in the background (it hates trend micro antivirus!..). 

But, when I use Reshade & Filters the game slows dramatically. For example, as I watch the Konami logo open after bootup It takes about 3-4 seconds per frame as it fades onto the screen - then continues like this even on arriving to the menu. Have you had known issues like this with the Reshade & Filters? Or is there something I could try? If not I will just continue to skip these files as the game looks just amazing anyway.

BTW - I still have a copy of Silentscape Studios rework of Silent Hill. Happy to send on a copy to say thanks. Send me an email and I will upload it to Wetransfer for you if you like. Maybe you can improve on it? 

Cheers guys, Alex.

**Comment by Polymega** [comment]
Hi Alex, 

Question: You're also using WineD3D then? And if you remove the ReShade files but keep the WineD3D files the game runs smoothly then? 

We've had several reports of the Nvidia GTX GPU line having severe running issues when using WineD3D. I'd like to confirm first that it's indeed ReShade causing you the problems and not WineD3D.

**Comment by asmith985** [comment]
WOW that was quick... 

You are correct. I am using Wind D3D but I have deleted the Reshade files. As soon as I removed the Reshade files the game ran perfect.

**Comment by Polymega** [comment]
Haha, email notifications, a cell phone, and past issues with Nvidia cards led me to the fast response. :) 

If you're having issues with ReShade I'd recommend one of the following: 

- Ensure you don't have a global setting or SH2 app specific setting enabled in your Nvidia control panel that could be conflicting with ReShade. 
- Press Ctrl + W in-game to open the ReShade control panel and disable the effects one-by-one to see if there's a specific filter causing your issues. 
- Update to the latest version of ReShade. I'm not sure what this may replace/overwrite in your game files in regards to this software. 
- Fully disable ReShade and implement an anti-aliasing solution through Nvidia's control panel instead. 
- Remove the WineD3D files and using the DirectX version of the ReShade files instead (as opposed to the OpenGL ReShade files you have to use while using WineD3D). 
   - Elisha, our lead programmer, is working on removing the need for WineD3D while retaining what it fixes for the game. This should be fullt released sometime in the future.

**Comment by asmith985** [comment]
Thanks Polymega,

So here are my results:

1. No global settings being used - double checked
2. Blocked from using the Ctrl + W and F12 functions for some reason? A message sits at the top of the screen and does not go away and hangs around even when eventually I get to the gameplay. The message says:

Reshade 3.4.8.345 by crossfire
Loading (4 effects remaining) … This might take a while. The application could become unresponsive for some time.

3. Reshade already updated to latest version by the self updater. I can see there is a newer version 4.1 out on the Reshade.me website but I'm not sure how to install it without screwing anything up LOL.
I tried lowering my resolution down to 1080p but the problem was not improved in the slightest. So I have opted to go without the reshade for now as I'm not confident enough to play around in the .ini file.

Thank you kindly for your time. If you want me to test anything I'm more than happy to help. Otherwise, It looks amazing (and lets be realistic - there isn't any real jaggies at 4k anyway! LOL).

Cheers,
Alex.

**Comment by Polymega** [comment]
> Reshade already updated to latest version by the self updater. 

Interesting. I didn't even know ReShade had a built-in auto updater. I'd recommend re-downloading the [ReShade files from the Installation Guide](http://enhanced.townofsilenthill.com/SH2/#installReShade) and seeing if those work (ensuring it doesn't auto-update itself). We've had someone else experience an issue when ReShade was updated (not identical to your problem, though) so I'm curious if that resolves it.

**Comment by Polymega** [comment]
Okay I downloaded the latest version of ReShade and have some notes: 

> Blocked from using the Ctrl + W and F12 functions for some reason? 

This is due to ReShade updating itself. I changed the key bindings for these. The default key bindings are different (it tells you what to press as it's loading in the filters). 

When you first install ReShade it has the option to download _a ton_ of filters for you to play around with. Every time you launch the game ReShade must load _all_ of these filters while the game launches. So while ReShade was loading 65+ filters I experienced the same issue you did: A hangup at the beginning a very choppy framerate while the filters finished loading in. 

I can only imagine the time it takes to load these in at 4K would be substantially longer vs. my 1080 resolution I tested at. For me, the hangup at the beginning was a small handful of seconds followed by choppiness for another handful of seconds. 

In addition to that, ReShade has to two different usage modes for all these filters: Configuration mode and performance mode. Config mode allows you to adjust any and all filters you have loaded in. Performance mode locks these adjustments in place to load the game in quicker. 

Okay... so what does this all boil down to? The ReShade files on the installation guide have removed ALL filters except for four; the four that it actually uses in-game. This _substantially_ reduces load time when starting the game. Additionally, the ReShade presets for this game are set to use the filters in "performance" mode, reduce load time even more. 

With all that said: I'd recommend re-downloading the ReShade files from the installation guide and ensuring the software doesn't auto-update itself. Let me know if that solves your load/run issues.

**Comment by asmith985** [comment]
So first I must apologize. It seems the update was the Silent Hill 2 enhancement not the shaders updating. Sorry for the misinformation...

I just reinstalled the game again (for a third time) and followed all the instructions word-for-word but the shaders are still causing major issues - namely I counted one frame per 2 seconds to be exact (not helped by reducing the resolution to 1080p either) and this did not improve with time. I waited 10+ minutes with nil improvement. Also, still cant use Ctrl+W or F12 and it still says "Loading... 4 effects remaining" etc which does not disappear. So It seems that the Reshade program is only trying to load 4 of the effects and not the 65+ you mentioned above which is good. 

So this is a list of the things I have tried to fix the issue:

- Turned off all background programs and antivirus
- Turned off SLI
- Ensured no 3D profile in Nvidia settings
- Ensured permissions were set exactly word-for-word as described in the install
- Tried updating to the newer reshade.me version - this messed up your settings for the game resulting in needing a reinstall
- Installed DirectX9 SDK
- Installed Microsoft Visual C++ 2010 Redistributable Package (x86)
- Kept noisefilter at 512 for Reshade testing (now running at 2048 perfectly without Reshade installed)

So I have uninstalled the Reshade again. And again the game runs flawless at 4K.

I'm now more trying to help you with a solution than myself (which I am more than happy to do). I don't mind not having the Reshade since it runs so well without it. I'm also happy to keep trouble shooting if it helps you guys out. But I don't wish to waste any more of your time unnecessarily.

**Comment by Polymega** [comment]
> So this is a list of the things I have tried to fix the issue:

You definitely covered all bases then! 

I'm honestly not sure what's causing the issue then. You can go into the `\KONAMI\Silent Hill 2\reshade-shaders\Shaders\` folder and removing filter files one-by-one (launching the game between each deletion) to see if it's a specific filter causing the issues. 

Besides that, I think you took the next best approach: Enjoying the game in 4K without ReShade. :) The main benefit for ReShade is its anti-aliasing features so if you're able to remove the "jaggies" without it then you're still pretty much golden!

**Comment by asmith985** [comment]
Well I gave it a try. Removed each one. Even tried just leaving only one effect in the folder. Still had the same effect. No difference...

Leaving off shaders from here on. Thanks very much for your help Polymega. 

As per my offer before, if you would like the Silentscape release of Silent Hill 1 flick me through an email and I will upload to Wetransfer. Its the least I can do to say thanks for your time. Take care! :) And hope to see an enhanced Silent Hill 3 & 4!

**Comment by Polymega** [comment]
@asmith985
If you're still around and would still like to try out ReShade with the game, download an updated version here and let us know if the game runs smooth for you with ReShade in effect: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/88#issuecomment-456635410

**Comment by asmith985** [comment]
Thanks Polymega. Will try it out and let you know. Cheers for that ;)

**Comment by elishacloud** [comment]
Closing as no response.  This can be reopened later if issue comes back.
