### ISSUE TITLE
Linux/Wine: White flash between transition and white pause menu background

### ISSUE THREAD

**Issue by legluondunet** [elishacloud/Silent-Hill-2-Enhancements#513]
Hello Elisha,
you remember I'm a Linux user and I play sh2dc with Wine.
I have a new issue, menu screen is white when I click on "escape":

![ArcoLinux_2022-05-06_09-31-13](https://user-images.githubusercontent.com/325405/167087391-15a95b67-5b8f-4ab7-b140-d204ced7f697.png)

Is it an issue or an option to change?
I can not reproduce this issue if I disable dx8 --> dx9 option in d3d8.ini

I joined the d3d8.log

Thank you for your help

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8638337/d3d8.log)
.

**Comment by legluondunet** [comment]
Hello Elisha,
This time I used the latest d3d8.dll testing version.
Same issue here: menu background is white.
I joined you a video for a better view of this issue and a new d3d8.log file

https://youtu.be/gtsao2fOXnA

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8685354/d3d8.log)

**Comment by elishacloud** [comment]
> warn: ConvertFormat: Unknown format encountered: D3D9Format::SSAA

You can ignore this one.  It is only related to antialiasing.

> warn: D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y
> warn: D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_CLIPPING

These are set by Silent Hill 2 itself, not by our enhancement project.  `D3DRS_ADAPTIVETESS_Y` is needed for Silent Hill 2.

> I have a new issue, menu screen is white when I click on "escape":

Try disabling `d3d8to9` in the ini file.

**Comment by legluondunet** [comment]
I can not reproduce this issue if I disable dx8 --> dx9 option in d3d8.ini

**Comment by legluondunet** [comment]
this issue seems to be related to this option:
ScreenMode = 1 (default)
if this option is set to 1 or 2, I have white flash before logo showing and game menu (escape) background is fully white.
If I set this option to 3, I have no flash before logo showing and game menu background is not white.

**Comment by legluondunet** [comment]
I finally don't think it's a bug on your side and I found a workaround, I close this issue.
Thank you for your help.

**Comment by legluondunet** [comment]
`ScreenMode = 3` option is not such a satisfying option: if I alt+tab after launching the game, I can not use the mouse cursor.

**Comment by JoonasPitk** [comment]
I had this issue as well about a year ago. Didn't have a GitHub account back then, so I didn't report it.
Came to the same conclusion as legluondunet, `ScreenMode = 3` fixes the issue. This does limits your choices for playing the game a bit, though.
Some change between the latest and previous version has caused this to appear.

**Comment by elishacloud** [comment]
Can you check if previous [releases](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases) of the d3d8.dll have this issue?  It would be nice to know at what point this issue was introduced.

Also, can you disable all the shaders (`AdjustColorTemp`, `EnableSMAA` and `RestoreBrightnessSelector`) and see if the issue happens then?

**Comment by JoonasPitk** [comment]
> Can you check if previous [releases](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases) of the d3d8.dll have this issue? It would be nice to know at what point this issue was introduced.
> 
> Also, can you disable all the shaders (`AdjustColorTemp`, `EnableSMAA` and `RestoreBrightnessSelector`) and see if the issue happens then?

Version 1.7.1860.0 is omit of white flashes and white pause menu background, but said background is now black... I don't remember it being like that before.
I've tried the settings you suggested on both latest and aforementioned version, which had no effect. I also tried `FullscreenWndMode = 1` on the version 1.7.1860.0, but pause background stays black.

Tried 1.5.1750.0 and 1.5.1700.0, with first not booting if `FullscreenWndMode = 1` was set, and the latter refused to boot altogether.

This could be a Wine-related change, since I can't recall having a black background in the pause menu before.

**Comment by elishacloud** [comment]
@legluondunet, thanks for testing this.  Would you mind testing this again with a new build?

For this new build please test both `ScreenMode = 1` and `ScreenMode = 2`.  I would like to see if either of these screen modes work now.

Also, please attach your log file for `ScreenMode = 1` so I can see some of the items in it.

Here is the new testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8953251/d3d8.zip)

**Comment by legluondunet** [comment]
with option `screenmode = 1`
--> white flash between logo transition + white background for escape menu
with option `screenmode = 2`
--> no white flash between logo transition + normal background for escape menu

I joined you log files
[d3d8.screenmode1.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8970686/d3d8.screenmode1.log)
[d3d8.screenmode2.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8970687/d3d8.screenmode2.log)
.

**Comment by legluondunet** [comment]
I tested all three screenmode with new d3d8 dll.
- screenmode 1 and 2: no more white flash transition, no more white backgound for pause menu, all is normal
- screenmode 3: all is normal too

You can watch tests videos here:
---> screenmode1: https://youtu.be/BdPGeWK-fmI
---> screenmode3: https://youtu.be/I0ouSFpXBpo

For my tests I used Wine 7.2 with virtual desktop mode.

**Comment by elishacloud** [comment]
Great.  Thanks for the tests @legluondunet!

**Comment by legluondunet** [comment]
Thank you very much @elishacloud.

**Comment by elishacloud** [comment]
@legluondunet, would you be willing to test one more time?  I cleaned up the code and fixed an issue on Windows 7.  I want to make sure it will work here also.  It should work correctly in all three screen modes.

Here is the test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8979059/d3d8.zip)

**Comment by legluondunet** [comment]
Thank you for this new build, everything is ok. There are still 2 white flash at start in screenmode 1 and 2.
But not between logo transition nor white background menu.
I posted you a video to look at the 2 white flash left at start. 
It seems related to resolution changes? 
https://youtu.be/Nr58nH5QzfA

**Comment by elishacloud** [comment]
Thanks @legluondunet.  Those white flash at startup is normal.  I might be able to remove one of them...

**Comment by legluondunet** [comment]
> Those white flash at startup is normal
Normal? I'm curious, could you explain me what produces this white flash?
Can you turn the white flash color in black color?

**Comment by Polymega** [comment]
> The fix I used was to change the background color of the window to black so that when it get displayed it will still show black. This has the side effect of fixing the white shader issue also. So I guess that fix is no longer needed.

This also fixes the one frame white flash when changing resolutions through the game's options menu as well. :)
