### ISSUE TITLE
Located Font file for ps2 silent hill 2?

### ISSUE THREAD

**Issue by kiminru** [elishacloud/Silent-Hill-2-Enhancements#517]
Does anyone know where the font files for the PS2 Silent Hill 2 are located? 
I extracted all the mgf files, but unfortunately there was no font file. 
There seems to be a font file in the .bin in the gx, gy, gz, and iop files, but I'm not sure

**Comment by Polymega** [comment]
For the PC version, the font files are located in the main binary of the game; they aren't a separate file. belek666 is the person whose researched the font files that ultimately led to us being able to use an HD font. He's sadly no longer active on GitHub, but you can check his repo with font work for some clues, maybe: https://github.com/belek666/fontsh234

**Comment by kiminru** [comment]
> For the PC version, the font files are located in the main binary of the game; they aren't a separate file. belek666 is the person whose researched the font files that ultimately led to us being able to use an HD font. He's sadly no longer active on GitHub, but you can check his repo with font work for some clues, maybe: https://github.com/belek666/fontsh234

thank you! I am currently making separate language patches for PS2 and PC Enhanced Edition, of which PS2 has the highest priority, followed by PC Enhanced Edition. I'm so glad I found some clues and thank you so much for the replies!

**Comment by kiminru** [comment]
Does anyone know where the font images for PS2 Silent hill 2 are?

**Comment by elishacloud** [comment]
The font is located under: `sh2e\font\font000.tga`.  But it is only there if you are using the Enhancement files.  Otherwise they are stored _inside_ the sh2pc.exe file!

See [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/cd72d5f5cae974caff76c17e7cd232d9f4be5770/Patches/Fonts.cpp#L169).

**Comment by Polymega** [comment]
I'm not sure where the font file would be stored in the PS2 version, but if you have no need to change any of the font characters to accommodate a different language, then you shouldn't have a need to change this file. All you'd need to do is change the `.mes` files appropriately.

If you require changing certain characters for use with a new language, then that would be a different story. But as it stands, here are all the Latin characters SH2 PC uses. I would assume SH2 PS2 uses all of the same Latin characters?

![image](https://user-images.githubusercontent.com/27395260/60744212-e29b5780-9f42-11e9-8c65-b716ad81c98a.png)

**Comment by kiminru** [comment]
![한글(소)](https://user-images.githubusercontent.com/84241069/169143142-b131f16d-22e9-4e5d-b326-99ccb0fed620.jpg)
![한글(대)](https://user-images.githubusercontent.com/84241069/169143161-82ce3285-30dc-4c54-81b5-946fb1f43e51.jpg)
[sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8720396/sh2pc.zip)

**Comment by kiminru** [comment]
> I'm not sure where the font file would be stored in the PS2 version, but if you have no need to change any of the font characters to accommodate a different language, then you shouldn't have a need to change this file. All you'd need to do is change the `.mes` files appropriately.
> 
> If you require changing certain characters for use with a new language, then that would be a different story. But as it stands, here are all the Latin characters SH2 PC uses. I would assume SH2 PS2 uses all of the same Latin characters?
> 
> ![image](https://user-images.githubusercontent.com/27395260/60744212-e29b5780-9f42-11e9-8c65-b716ad81c98a.png)

Unfortunately, it is a language that does not exist in the default game font. It's korean.

**Comment by Polymega** [comment]
> It means that there is a font in this exe, but all programs used not open at all...

Do you mean that only the Korean language can be used with your customized sh2pc.exe file?

> Unfortunately, it is a language that does not exist in the default game font. It's korean. [...] Can someone extract the fonts from the exe I uploaded?

Unfortunately I do not know how to do this. Maybe someone else does. Have you tried the Belek666's tool for font extraction? It might work: https://github.com/belek666/fontsh234/releases/tag/v0.4a

**Comment by kiminru** [comment]
> > Do you mean that only the Korean language can be used with your customized sh2pc.exe file?
> This file is replaced with Korean instead of French. 
All other languages are output (there is no Japanese. If you set it to French, Korean is output instead of French.)

> > Unfortunately I do not know how to do this. Maybe someone else does. Have you tried Belek666's tool for font extraction? It might work: https://github.com/belek666/fontsh234/releases/tag/v0.4a
> I haven't tried it yet. I'll have to test it out.

**Comment by kiminru** [comment]
This file is replaced with Korean instead of French.
All other languages are output (there is no Japanese. If you set it to French, Korean is output instead of French.)

I haven't tried it yet. I'll have to test it out.

**Comment by kiminru** [comment]
I tried fontsh234, but it still doesn't open, maybe I don't know how to use it...

**Comment by kiminru** [comment]
> > It means that there is a font in this exe, but all programs used not open at all...
> 
> Do you mean that only the Korean language can be used with your customized sh2pc.exe file?
> 
> > Unfortunately, it is a language that does not exist in the default game font. It's korean. [...] Can someone extract the fonts from the exe I uploaded?
> 
> Unfortunately I do not know how to do this. Maybe someone else does. Have you tried Belek666's tool for font extraction? It might work: https://github.com/belek666/fontsh234/releases/tag/v0.4a

I tried fontsh234, but it still doesn't open, maybe I don't know how to use it...

**Comment by kiminru** [comment]
> I'm sorry to say that I'm not sure how to extract the Korean font from that executable. You see, Belek666 handled all of the font modifications for our project, so none of us really have any experience working with the fonts or even using the tool he created. 😕

Too sad... PS2 has a fairly complex structure, and language patching on PS2 seems to be impossible forever...

**Comment by kiminru** [comment]
===========================================
StartSeg DataImport Big_Endian $0CB800 $0800
"common_msg_i.mes"
===========================================

The seg of common_msg_i.mes is $0CB800 $0800.
Is there any way to find out the seg of common_msg_f.mes?

**Comment by IlDucci** [comment]
> > I'm sorry to say that I'm not sure how to extract the Korean font from that executable. You see, Belek666 handled all of the font modifications for our project, so none of us really have any experience working with the fonts or even using the tool he created. 😕
> 
> Too sad... PS2 has a fairly complex structure...

The main thing I know is that you need to locate the actual beginning of the font space on whatever executable you are looking for (PS2' SLES/SLUS/SLPM/whatever ELF file or that PC executable) and then modify belek's tool so it recognises it. His tool targets a specific hex address, so if he did not cover the Korean version, you'll need to add it.

At least for PS2, seems that you need to edit around the line 45, here:

https://github.com/belek666/fontsh234/blob/master/font.cpp

**Comment by kiminru** [comment]
> > > I'm sorry to say that I'm not sure how to extract the Korean font from that executable. You see, Belek666 handled all of the font modifications for our project, so none of us really have any experience working with the fonts or even using the tool he created. 😕
> > 
> > 
> > Too sad... PS2 has a fairly complex structure...
> 
> The main thing I know is that you need to locate the actual beginning of the font space on whatever executable you are looking for (PS2' SLES/SLUS/SLPM/whatever ELF file or that PC executable) and then modify belek's tool so it recognises it. His tool targets a specific hex address, so if he did not cover the Korean version, you'll need to add it.
> 
> At least for PS2, seems that you need to edit around the line 45, here:
> 
> https://github.com/belek666/fontsh234/blob/master/font.cpp
> 
> EDIT: Okay, I've now seen the other post and fully understood your situation here. So yes, the font file is ALWAYS in the executables for Silent Hill 2: The ELF file on PS2 (I think you'll be after the Japanese version, so SLPM), the default.xbe file on XBOX (can't be edited as of right now without editing Belek's tool) and the sh2pc.exe file on PC.
> 
> IDK if you have dumped that Korean font table with Belek's tool. If you did, then you should be able to replace it easily. If it comes from somewhere else, you will be in a world of hurt, as Belek's format is a sheet of multiple characters in a single row, as you have seen. You would need to adapt the graphics.

Thanks so much for the detailed reply! I will try to work with the SLUS_202.28 file using a hex editor! In Korea, the creators of the language patch for PC and the language patch for XBOX are all different, and they are no longer active, so even if you ask a question, there is no answer. All the talented people in Korea have long since disappeared. However, there are a lot of talented people abroad, so I'm really grateful to have received this kind of help!

Is it okay if I ask a question again if I have a difficult part after working on it? I really want to complete the Korean port of PS2.

**Comment by IlDucci** [comment]
> Is it okay if I ask a question again if I have a difficult part after working on it? I really want to complete the Korean port of PS2.

Sure thing.

**Comment by kiminru** [comment]
> > Is it okay if I ask a question again if I have a difficult part after working on it? I really want to complete the Korean port of PS2.
> 
> Sure thing.

We are currently getting help with font support.
However, a problem arose along the way, so I asked this question.
The person with the ability to support fonts said this.

-
When I replaced 1400 fonts, I got a bug and gave up because I couldn't change the file, but just before I went to sleep, I suddenly remembered and changed about 600 characters, which is the existing character area, so 600 characters are entered properly.
After 700 characters or more, the data at the back seems to be broken.
The program seems to exit somewhere between 700 and 800 characters.
Of course, simple texture insertion and character coordinate hex work are completely separate, but...
In any case, I have no choice but to ask for a competent person to analyze it.
-

**Comment by IlDucci** [comment]
There are two problems here, as far as I can remember:
 - First, the amount of characters is limited. This should be obvious, but you are limited to the amount of characters that are contained in the original font (in this case, the SLUS's). Make sure you are not adding more characters than those found in the complete font sheet.
 - Second, the amount of overall space is also limited, since the font is embedded within a specific area of the ELF file, and it's also compressed. I suggest you blank out any Japanese characters that you are not going to use.
See if any of these help.

**Comment by kiminru** [comment]
> There are two problems here, as far as I can remember:
> 
> * First, the amount of characters is limited. This should be obvious, but you are limited to the amount of characters that are contained in the original font (in this case, the SLUS's). Make sure you are not adding more characters than those found in the complete font sheet.
> * Second, the amount of overall space is also limited, since the font is embedded within a specific area of the ELF file, and it's also compressed. I suggest you blank out any Japanese characters that you are not going to use.
>   See if any of these help.

Thank you, but the font technical support is on hold until someone else supports it again due to circumstances. 
I can't proceed because I have no knowledge about font insertion... Thanks for the reply though!

**Comment by elishacloud** [comment]
> [sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8720396/sh2pc.zip)
> [etc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8720458/etc.zip)
> The lines and notes were made based on the French version.
> 
> It means that there is a font in this exe, but all programs used not open at all... Can someone extract the fonts from the exe I uploaded?

I think the best way is to pull the font out of the executable.  Code [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/cd72d5f5cae974caff76c17e7cd232d9f4be5770/Patches/Fonts.cpp#L147-L149) should help us point to the location in the exe that stores the font.

**Comment by IlDucci** [comment]
> I think the best way is to pull the font out of the executable. Code [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/cd72d5f5cae974caff76c17e7cd232d9f4be5770/Patches/Fonts.cpp#L147-L149) should help us point to the location in the exe that stores the font.

> Thank you, but the font technical support is on hold until someone else supports it again due to circumstances.
> I can't proceed because I have no knowledge about font insertion... Thanks for the reply though!

I just confirmed that Belek's tool reads that Korean executable, so I guess it's based on the European version. I was not able to try things until now. So things might be much easier now.

Listen up, @kiminru :
 - Use Belek's fontsh234 with the Korean PC executable, using this command:
```
FONTSH234.EXE sh2pc.exe n b 100 16 sh2pc_KOR_b.tga
FONTSH234.EXE sh2pc.exe s b 100 16 sh2pc_KOR_s.tga
```

This will dump the normal and small versions of the font from the Korean executable, along with the width tables for the English texts (not that you will need them, I presume). Delete/blank out the wrong leftovers at the bottom.
 - Now use the tool with the SLUS file:
```
FONTSH234.EXE SLUS_202.28 n w 100 16 sh2pc_KOR_b.tga
FONTSH234.EXE SLUS_202.28 s w 100 16 sh2pc_KOR_s.tga
```

And see how this ends up.

**Comment by elishacloud** [comment]
> I'm able to extract the characters with Belek's tool, but it crashes and it crashes hard when trying to do a sample reinsertion on the same EXE file.

You shouldn't need to reinsert it.  The code from SH2EE will take the tga file from the hard drive located under the `sh2e\font` folder.  I believe we bypass the font in the executable and use the font on disk instead.

**Comment by Polymega** [comment]
> The code from SH2EE will take the tga file from the hard drive located under the sh2e\font folder.

It's worth noting the TGA file we use is only good for the first X amount of characters in the font sheet. We originally requested this of Belek to keep the TGA file size down, as otherwise it would be really large in size. More info on that here: https://github.com/belek666/fontsh234/issues/2#issuecomment-454547238

**Comment by kiminru** [comment]
> > I think the best way is to pull the font out of the executable. Code [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/cd72d5f5cae974caff76c17e7cd232d9f4be5770/Patches/Fonts.cpp#L147-L149) should help us point to the location in the exe that stores the font.
> 
> > Thank you, but the font technical support is on hold until someone else supports it again due to circumstances.
> > I can't proceed because I have no knowledge about font insertion... Thanks for the reply though!
> 
> I just confirmed that Belek's tool reads that Korean executable, so I guess it's based on the European version. I was not able to try things until now. So things might be much easier now.
> 
> Listen up, @kiminru :
> 
> * Use Belek's fontsh234 with the Korean PC executable, using this command:
> 
> ```
> FONTSH234.EXE sh2pc.exe n b 100 16 sh2pc_KOR_b.tga
> FONTSH234.EXE sh2pc.exe s b 100 16 sh2pc_KOR_s.tga
> ```
> 
> This will dump the normal and small versions of the font from the Korean executable, along with the width tables for the English texts (not that you will need them, I presume). Delete/blank out the wrong leftovers at the bottom, but do not change the tga's size.
> 
> * Now use the tool with the SLUS file:
> 
> ```
> FONTSH234.EXE SLUS_202.28 n w 100 16 sh2pc_KOR_b.tga
> FONTSH234.EXE SLUS_202.28 s w 100 16 sh2pc_KOR_s.tga
> ```
> 
> And see how this ends up.
> 
> For everybody else, it seems that the font compression has something very wrong in this Korean executable. After the last altered character (acording to kiminru's image), I get quite a lot of broken Korean characters before returning back to the original Japanese ones. There's a chance that there's characters missing from kiminru's sheet or that the Korean PC translator simply mangled the final characters, but since they are not used, nothing was happening. I'm able to extract the characters with Belek's tool, but it crashes and it crashes hard when trying to do a sample reinsertion on the same EXE file.

Thank you so much for the detailed explanation!

![font_normal 100 75](https://user-images.githubusercontent.com/84241069/170380100-60edbe2a-e739-4149-8e04-c790aa6f9c28.jpg)
I printed the font of the PC version through Belek's fontsh234. 
extracted up to a maximum of 'fontsh234.exe sh2pc.exe n b 100 75 font_normal.tga', that is, '100 75'.

![font_normal-100-6](https://user-images.githubusercontent.com/84241069/170380122-d6a40bd8-7c6d-4ea7-a043-daba9a6c4c4d.jpg)
But import, can only do it up to 'fontsh234.exe sh2pc.exe n b 100 6 font_normal.tga', that is, '100 6'.
This is a problem for both Normal and Small fonts.


![2](https://user-images.githubusercontent.com/84241069/170380343-120aa042-1cda-45ee-9f06-e513df5855d9.png)
![3](https://user-images.githubusercontent.com/84241069/170380348-b1cedf19-6192-4f08-841f-b73d4692d112.png)

The problem is that only 10% of the Korean language can be printed.
So I asked Belek if he could improve the program for this problem, if he does, it's 100% PS2 language patch portable!

PS.

**Comment by IlDucci** [comment]
> You shouldn't need to reinsert it. The code from SH2EE will take the tga file from the hard drive located under the `sh2e\font` folder. I believe we bypass the font in the executable and use the font on disk instead.

Not on PC, but remember that he is targeting PS2 first, before going with PC.



> I printed the font of the PC version through Belek's fontsh234. extracted up to a maximum of 'fontsh234.exe sh2pc.exe n b 100 75 font_normal.tga', that is, '100 75'.
> 
> ![font_normal-100-6](https://user-images.githubusercontent.com/84241069/170380122-d6a40bd8-7c6d-4ea7-a043-daba9a6c4c4d.jpg) But import, can only do it up to 'fontsh234.exe sh2pc.exe n b 100 6 font_normal.tga', that is, '100 6'. This is a problem for both Normal and Small fonts.

That is not good news if you are insisting on using the US edition to be patched. If I had to guess, characters were culled out. Can you test this in a Japanese release?

**Comment by kiminru** [comment]
> > You shouldn't need to reinsert it. The code from SH2EE will take the tga file from the hard drive located under the `sh2e\font` folder. I believe we bypass the font in the executable and use the font on disk instead.
> 
> Not on PC, but remember that he is targeting PS2 first, before going with PC.
> 
> > I printed the font of the PC version through Belek's fontsh234. extracted up to a maximum of 'fontsh234.exe sh2pc.exe n b 100 75 font_normal.tga', that is, '100 75'.
> > ![font_normal-100-6](https://user-images.githubusercontent.com/84241069/170380122-d6a40bd8-7c6d-4ea7-a043-daba9a6c4c4d.jpg) But import, can only do it up to 'fontsh234.exe sh2pc.exe n b 100 6 font_normal.tga', that is, '100 6'. This is a problem for both Normal and Small fonts.
> 
> That is not good news if you are insisting on using the US edition to be your base. If I had to guess, characters were culled out from the ELF file. Can you test this in a Japanese release?

If you're testing on the Japanese version, you'll have to redesign the etc.mgf replacement program. In the case of GHITS_NTSCU_201 you created, I know it is a program that replaces Italian language text. If it is possible to change the program to replace the Japanese language text, I think it is possible. In the case of PC, since it is uncompressed and easily accessible, it is a Korean language patch with the French language dialogue modified into Korean. However, in the case of PS2, because of the mgf file, the Italian language dialogue was corrected to Korean using the mgf replacement program.

But if it is the Japanese version, is it possible to import up to '100 16'? If the import does not work as it is, it is a little difficult. In the case of the text mes, the hex code is not simply written in Korean, and I do not know the Korean output of the hex code. As it is literally porting, you have to port the mes file with the hex code written on it.

**Comment by IlDucci** [comment]
> If testing on the Japanese version, redesign the etc.mgf replacement program. In the case of GHITS_NTSCU_201 you created, I know it is a program that replaces Italian language text. If it is possible to change the program to replace the Japanese language text, I think it is possible. In the case of PC, since it is uncompressed and easily accessible, it is a Korean language patch with the French language dialogue modified into Korean. However, in the case of PS2, because of the mgf file, the Italian language dialogue was corrected to Korean using the mgf replacement program.
> 
> But if it is the Japanese version, is it possible to import up to '100 16'? If the import does not work as it is, it is a little difficult. In the case of the text mes, the hex code is not simply written in Korean, and I do not know the Korean output of the hex code. As it is literally porting, you have to port the mes file with the hex code written on it.

Finding the addresses for the Japanese version should be relatively simple by using Nisto's https://github.com/Nisto/sh2ex . That could be used to locate the addresses and sizes of the Japanese ETC.

As for the Japanese version... My theory is that the US version removed a lot of Japanese characters to save space and that's why you can only import so few. The Japanese version should have a larger space for the font.

**Comment by kiminru** [comment]
> > If testing on the Japanese version, redesign the etc.mgf replacement program. In the case of GHITS_NTSCU_201 you created, I know it is a program that replaces Italian language text. If it is possible to change the program to replace the Japanese language text, I think it is possible. In the case of PC, since it is uncompressed and easily accessible, it is a Korean language patch with the French language dialogue modified into Korean. However, in the case of PS2, because of the mgf file, the Italian language dialogue was corrected to Korean using the mgf replacement program.
> > But if it is the Japanese version, is it possible to import up to '100 16'? If the import does not work as it is, it is a little difficult. In the case of the text mes, the hex code is not simply written in Korean, and I do not know the Korean output of the hex code. As it is literally porting, you have to port the mes file with the hex code written on it.
> 
> Finding the addresses for the Japanese version should be relatively simple by using Nisto's https://github.com/Nisto/sh2ex . That could be used to locate the addresses and sizes of the Japanese ETC.
> 
> As for the Japanese version... My theory is that the US version removed a lot of Japanese characters to save space and that's why you can only import so few. The Japanese version should have a larger space for the font.

This is the production process spoken by the person who made the Korean language patch in 2009.

"Fonts are included in the executable file and are self-compressed. Unfortunately, fortunately, while porting to XBOX and PC, the fonts included in the file were made with Japanese and Chinese characters included, so the total font included in the file was a little over 2000 characters. Among them, 500 characters. Some of them are used for English ASCII and extended ASCII areas, and the rest are areas that have fonts but are not used. When I compressed it, the shovel was compressed again, so it was put into the executable file and repeated again so that it was recognized.

The mes file where the lines are stored is also shoveled. The characters of the lines are in the order of the count number of the font. For example, the hex value of ' ' is 0x20, but it is used as 0x00, which is - 0x20 in the dialogue file. With this formula, all ASCII values ​​can be obtained as - 0x20, and for other characters, first check how many times they are stored, then change the font of the corresponding part to the newly created Korean font and match the Hangul number with the corresponding number. The complete Hangul is 2350 characters. Sahil 2 includes a hairdressing dialogue book. I was able to check the number of characters used in the dialogue book and translate it into about 640 characters including additional characters to be used. The dialogue file is a bit complicated because it contains unique codes such as color line breaks used in the game in addition to text. Also, if you just modify it, only ASCII value is output, so you need to change it so that it can recognize 2 bytes. The number of lines and offsets are written in the header, so if you increase the characters without modifying the header, it is also NG.

The analysis took a long time, but it seems that it took a long time to make a tool based on that.”

Literally speaking, he seems to have made it using the North American version of the PC version. First of all, it is difficult to find the Japanese version of the PS2 ISO file, but I will give it a try. First of all, I left a post to Belek in the mail and in the issue on github, but if he solves it, everything will be 100% resolved, but I don't know if he will get an answer, so I think you should give it a try! :)

**Comment by kiminru** [comment]
> > If testing on the Japanese version, redesign the etc.mgf replacement program. In the case of GHITS_NTSCU_201 you created, I know it is a program that replaces Italian language text. If it is possible to change the program to replace the Japanese language text, I think it is possible. In the case of PC, since it is uncompressed and easily accessible, it is a Korean language patch with the French language dialogue modified into Korean. However, in the case of PS2, because of the mgf file, the Italian language dialogue was corrected to Korean using the mgf replacement program.
> > But if it is the Japanese version, is it possible to import up to '100 16'? If the import does not work as it is, it is a little difficult. In the case of the text mes, the hex code is not simply written in Korean, and I do not know the Korean output of the hex code. As it is literally porting, you have to port the mes file with the hex code written on it.
> 
> Finding the addresses for the Japanese version should be relatively simple by using Nisto's https://github.com/Nisto/sh2ex . That could be used to locate the addresses and sizes of the Japanese ETC.
> 
> As for the Japanese version... My theory is that the US version removed a lot of Japanese characters to save space and that's why you can only import so few. The Japanese version should have a larger space for the font.

The Japanese version of Silent Hill 2 is SLPM_650.51. 
fontsh234 program does not support SLPM_650.51, so the font cannot be extracted.

**Comment by IlDucci** [comment]
> The Japanese version of Silent Hill 2 is SLPM_650.51. fontsh234 program does not support SLPM_650.51, so the font cannot be extracted.

There's two things wrong here:
 - On your side, that product ID seems to be of the first release of the game, not Saigo no Uta (the release that also contains the Born From a Wish scenario).
 - On Belek's side... OMG. He never actually gave support to Japanese releases: when I checked the list I just looked at the SLPM/SLES/SLUS codes, but now I read the actual code on Belek's end... It's a temporary one!
```
{ "SLPM_123.45", sh_font::PS2_SH2, 0x002DEAB8, 10065884, 0x000FFF80 },
```
So... the tool would indeed need some RE of the Japenese SLPM files, a simple change and then recompilation.

**Comment by kiminru** [comment]
> > The Japanese version of Silent Hill 2 is SLPM_650.51. fontsh234 program does not support SLPM_650.51, so the font cannot be extracted.
> 
> There's two things wrong here:
> 
> * On your side, that product ID seems to be of the first release of the game, not Saigo no Uta (the release that also contains the Born From a Wish scenario).
> * On Belek's side... OMG. He never actually gave support to Japanese releases: when I checked the list I just looked at the SLPM/SLES/SLUS codes, but now I read the actual code on Belek's end... It's a temporary one!
> 
> ```
> { "SLPM_123.45", sh_font::PS2_SH2, 0x002DEAB8, 10065884, 0x000FFF80 },
> ```
> 
> So... the tool would indeed need some RE of the Japenese SLPM files, a simple change and then recompilation.
> 
> @Polymega , do you or anyone else of your team have the Japanese discs around?

SLPM_650.51 is the version without the Born From a Wish scenario and you were right. The problem is that even the tool does not support all Japanese versions.

It's really difficult to port the language patch, I hope belek will reply as soon as possible and improve the program.

If the font is resolved, mes 'memo_x_msg_f.mes' and 'option_msg_f.mes' must also be revised. I couldn't replace the mes file because the two have different segment file sizes, so the text is still in Italian. There is a lot of work to be done, and I have to look at the fonts too, so I hope the font porting will be completed as soon as possible T.T

**Comment by IlDucci** [comment]
I could try to find the new offsets if someone has the original SLPM files. We would still need somebody to recompile the tool, though.

**Comment by kiminru** [comment]
> I could try to find the new offsets if someone has the original SLPM files. We would still need somebody to recompile the tool, though.

I just got a call from belek.

"Hi
For pc version I'm recommending using this modification http://www.enhanced.townofsilenthill.com/SH2/
With this mod You can use custom files as games fonts with higher resolution and specify its configuration. About problem with fontsh234 it's related to limited space for fonts inside games exe file. There are no checks for that in fontsh234 so the safest way would be to first delete all unneeded characters (blacking on bitmap or using program option) and then adding new. Also 'bitmap' option may be causing problems as it's not well tested."

Yes, I am hopeless now...

**Comment by kiminru** [comment]
Can someone extract the fonts inside the xbe on the xbox? 
This is a talented programmer in Korea who imported the fonts in the xbe file. 
He is a person ported the PC version korean language patch as it is. 
If extract the font you put in the xbe of the xbox version, I think can put it using that.

**Comment by IlDucci** [comment]
> He also used Silent hill 2's utility program. And he corrected the font.

Belek's version doesn't seem to be compatible with the XBOX executables. I do have the PAL equivalent, so I could take a look, but, again, it's going to be dependent on someone editing and recompiling Belek's tool.

**Comment by IlDucci** [comment]
Hey there. I have not checked the XBOX executables yet, but I've been toying with Belek's tool and developed a theory:

The tool might be a bit finicky. Too finicky, in fact, considering how limited is the TGA format it admits. I think it's not liking having to add new characters where, originally, there were blanks (I thought that by making a full sheet that removed all other Japanese characters it would simply erase/clear out space for the Korean ones), since it's crashing without any errors right after the last Katakana character is.

The tool is so finicky, in fact, that if I just extract the original character sheets from the US version and reinsert them as-is, the large font is inserted correctly, but the small font crashes the tool.

So... You could wait until someone makes the tool a bit less punishing or show more errors, or you could try to remap everything:
 - Try to move all Korean characters up to places where Japanese chars actually exist. It's going to be the pain I was worried, but at this point, it's going to be worth a shot.
 - After that, you will need to extract the text files of the PC version by changing the character mapping table from Infrid's tool to the current PC assignations, then change the character mapping table again so those assignations match the Japanese characters used.

**Comment by Polymega** [comment]
> Too finicky, in fact, considering how limited is the TGA format it admits

I don't know if this is the cause of your issues, but I remember Aero_ and I found out the it _only_ accepts **uncompressed** TGAs with **no** metadata attached.

For example: If you save the TGA out through Photoshop it won't work because Adobe adds some metadata to the file. We discovered that you must save out the uncompressed TGA through [GIMP](https://www.gimp.org/) as this program won't add any other data to the TGA except what's relevant to make the file work.

See these links for more information:
- https://github.com/belek666/fontsh234/issues/2#issuecomment-454025719
- https://github.com/belek666/fontsh234/issues/2#issuecomment-454142499

[It would be nice to use compressed TGAs, though...](https://github.com/belek666/fontsh234/issues/2#issuecomment-454952523)

**Comment by IlDucci** [comment]
I know, I was using paint.net to speed things up and the tool also doesn't f***ing like those files. Had to trim them with an hex editor to get the changes readed.

BTW; some quick details about the games, I got the SLPM from the Japanese Saigo no Uta from somebody else:
 - On Belek's tool, the line
```
{ "SLPM_123.45", sh_font::PS2_SH2, 0x002DEAB8, 10065884, 0x000FFF80 },
```
Should be changed to
```
{ "SLPM_650.98", sh_font::PS2_SH2, 0x001E49A0, 3147032, 0x000FFF80 },
```
(Not that it is actually needed by kiminru, considering the problem is Belek's tool and the US version has the entire Japanese sheet).

The font files in XBOX seem to have the same structures as the PC version, not as the PS2 ones. Still, if someone wants to beat that tool to a pulp, it's not going to detect the elements without the info, so...

Silent Hill 2: Inner Fears (Europe):
```
{ "default.xbe", sh_font::XBOX_SH2, 0x0038C550, 5054464, (THIS IS THE POINTER DIFFERENTIAL BETWEEN RAM POS AND LOCAL POS. UNKNOWN IF IT'S STILL NEEDED FOR XBOX },
```

Whatever version kiminru sent us (US?)
```
{ "default.xbe", sh_font::XBOX_SH2, 0x003782B0, 4960256, (THIS IS THE POINTER DIFFERENTIAL BETWEEN RAM POS AND LOCAL POS. UNKNOWN IF IT'S STILL NEEDED FOR XBOX },
```

**Comment by kiminru** [comment]
> The tool is so finicky, in fact, that if I just extract the original character sheets from the US version and reinsert them as-is, the large font is inserted correctly, but the small font crashes the tool.

That's right, re-import the extracted font after extracting 100 75 of the original font, it will be properly imported.

At first, the broken font was erased using Photoshop, and when I imported it, 'wrong tga format' appeared. 
So, using paint.net, I erased the broken part of the font, and when I used 'export as' using GIMP, it was recognized immediately.
Of course, the import still throws an error.
For reference, up to '100 7' is imported properly.

the font technical support person who helps with me gave me a 'table file for extracting Korean lines'.
[KOR_table.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8792432/KOR_table.txt)

He said that it can be done by changing the Chinese to Korean, but the problem is that to replace both normal fonts/small fonts, there is at least 2,000 characters, and even if they are all replaced, it is not recommended because there is a high probability that it will not work in the game.

**Comment by kiminru** [comment]
![1](https://user-images.githubusercontent.com/84241069/170864292-8feef9ea-b0a3-42e7-bfb7-90aa1097c11a.png)
![2](https://user-images.githubusercontent.com/84241069/170864296-1add1473-ff00-44e9-86f6-8411b994056d.png)

The language patch for PS2 seems to be over. It seems impossible...
