### ISSUE TITLE
Texture pack support

### ISSUE THREAD

**Issue by RainaAudron** [elishacloud/Silent-Hill-2-Enhancements#518]
Hello!

Does this project support any custom texture replacements? I would be interested in modding this game. However, I am unsure as to if you can dump the original textures and if SH2EE can even support texture replacement. Any help would be appreciated, thanks!

**Comment by Polymega** [comment]
Hello,

Our project doesn't have any texture swapping tools or features per se, but we do offer the ability for the game to _not crash_ when using higher resolution textures and audio. Really, it depends on what textures you want to replace:

- Our project supports higher resolution fullscreen image (.tex) textures. These are things like the main menu, save screen, riddle images, maps, etc.
- Everything within the game's environment (.map) files is self-contained. Meaning, if you know what you're doing, you can swap the textures in these files and even use higher resolution textures without crashing the game. [Some more info can be read here.](https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/Files/map.md)
- Character (.mdl) files should work the same as .map files, in that everything is self-contained. So you can replace character texture files and even use higher resolution textures if you know what you are doing. However, for our project, we've had little-to-no need to touch .mdl files. [Some more info can be read here.](https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/Files/mdl.md)

Again, we don't have any tools made for this except for what's already existed. In this case, you could use the [SH Texture Explorer tool](https://www.silenthillmemories.net/sh2/modding_en.htm), but this tool is quite old and limited in its functionality.

**Comment by RainaAudron** [comment]
Thank you for your help, much appreciated!

**Comment by Polymega** [comment]
No problem. Sorry I couldn't help you further, but the availability of mod tools is very limited for SH games. The tools that are currently around are very old and many of them are limited in their functionality. Almost all tools available can be found [on that site I linked](https://www.silenthillmemories.net/sh2/modding_en.htm). To give an example of what we had to do: When I upscaled the fullscreen image textures, I had to do this "by hand," so to speak, via hex editing each and every file. It wasn't the most fun thing to do!

**Comment by RainaAudron** [comment]
No worries, thank you for explaining! It was a bit of a long shot, tbh. I am not too skilled with Hex editor, so I do not think it would be viable for me to do this way, sadly. Kudos to you for doing the upscale like that, though, impressive but I imagine super tedious. Thanks again!
