### ISSUE TITLE
White screen upon launch

### ISSUE THREAD

**Issue by huiggi** [elishacloud/Silent-Hill-2-Enhancements#52]
Hi, I have white screen every time I launch the game. I followed every step in the guide. Here are my specs:
OS Windows 10 
CPU Intel Core i3 7100U
Motherboard KBL Charmander_KL
RAM 8GB DDR4
GPU NVIDIA GeForce 940MX 
SOUND Audiotrak Prodigy CUBE

I was going through troubleshooting steps but I don't know how to "Ensure you are not using traditional anti-aliasing methods such as MSAA or SSAA while using WineD3D For Windows".

**Comment by Polymega** [comment]
Hi @huiggi , 

Please **remove** the WineD3D files (`d3d9.dll`, `libwine.dll`, `wined3d.dll`) from your game's directory and use this version of SH2 Enhancements for the time being: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2429028/d3d8.zip)

**Comment by huiggi** [comment]
It worked! But I can't set the resolution to 1920x1080 in the settings. Only 1600x1200.

**Comment by Polymega** [comment]
Great! 

> But I can't set the resolution to 1920x1080 in the settings. Only 1600x1200.

Are you trying to change the resolution in the game's Options menu? If so, you can't do it there. 

Open the `d3d8.ini` file and change the resolution by setting `ResX = 1920` and `ResY = 1080` (or, you can set both of these values to `0` to inherently size the game to your display). 

More info can be found here: http://enhanced.townofsilenthill.com/SH2/config.htm#ResX&ResY

**Comment by huiggi** [comment]
Oh yeah, my bad. Thanks, it works great now!
