### ISSUE TITLE
UseCustomModFolder no longer working after win10 update

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#521]
First of all, thanks so much for this awesome project and effort. I'm truly thankful for being able to enjoy this game again with all the improvements.

As stated in the title, the useCustomModFolder is no longer working after a Windows10 update "KB5013624 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 10, version 20H2, Windows Server, version 20H2, Windows 10 Version 21H1, and Windows 10 Version 21H2" which updated the kernel32.dll file. When launching the game I get the following error in the D3D8.log file:

14876 15:12:09.379 Hooking the FileSystem APIs...
14876 15:12:09.379 Hook::HotPatch Error: 'CreateFileA' is not patch aware at addr=7776B280
14876 15:12:09.379 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\x09\x59\x6B\x08\x51\x51
14876 15:12:09.379 Hook::HotPatch Error: 'CreateFileW' is not patch aware at addr=77750E00
14876 15:12:09.379 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\xAB\xFD\x6C\x08\x83\xE4
14876 15:12:09.379 FAILED to hook the FileSystem APIs, disabling 'UseCustomModFolder'!

While checking the mod code,  the line 687: HMODULE h_kernel32 = GetModuleHandle(L"kernel32.dll"); that loads the kernel32.dll modules in https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/def917cd191e91a3f80fdb1567c27e53ff7663f7/Common/FileSystemHooks.cpp#L687 is no longer working as I suspect there was an API change in the new kernel32.dll file that was updated as part of the win10 update

Attached are the kernel32.dll version information after the win10 update and d3d8.log file:

![Kernel32 dll-version informaion](https://user-images.githubusercontent.com/8061991/169713069-12d67ef4-52a4-44ab-ac66-46aa7ec18e98.png)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8750154/d3d8.log)
.

**Comment by elishacloud** [comment]
This has been fixed in a previous check-in.  Try using the build [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/519#issuecomment-1133440672).

**Comment by Nicolas-Miranda** [comment]
Thanks for the updated version @elishacloud I tested it today and it loads the SH2 Enhanced UI and there are no errors in the logs. One thing that got my attention, is that the FMVs have black borders in the left and right side. I installed the FMV pack and I also have enabled the widescreen fix enabled in the d3d8.ini file (attached in the message). Before this patch the FMVs were displayed in fullscreen without black borders running at 1920x1080p. 

Do you know what I could be missing in configuration?

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8767411/d3d8.zip)

**Comment by Polymega** [comment]
This is due to a total overhaul in how we handle displaying/scaling the FMVs since the last public update. 

This change also needs to have the FMVs updated, which I've done but have not released yet. The updated FMVs will release along with everything else for our next public update.

**Comment by Nicolas-Miranda** [comment]
Hi @Polymega, so the properties mentioned here http://www.enhanced.townofsilenthill.com/SH2/config.htm#FMVWidescreenEnhancementPackCompatibility are no longer working with the current and provided d3d8.dll, right?

**Comment by Polymega** [comment]
That's correct. The information on the site is for the current _public_ release build. You are using a newer build that hasn't been publicly released yet which changes how the FMVs are scaled/displayed. When we launch the next project update, the site will be updated along with providing the new FMV pack for download.

**Comment by elishacloud** [comment]
> This is due to a total overhaul in how we handle displaying/scaling the FMVs since the last public update.

Ok, try with this update.  I recompiled the latest release build with this fix in it.  I think this should work and solve the scaling issues.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8774226/d3d8.zip)

**Comment by elishacloud** [comment]
This issue is fixed in the latest release.
