### ISSUE TITLE
D-pad not working on PS5 controller 

### ISSUE THREAD

**Issue by planttmatter** [elishacloud/Silent-Hill-2-Enhancements#523]
I have been using my PS5 controller connected to my PC via a wired connection, when playing the game. Control-wise everything is working fine, except for the fact that the game doesn't seem to detect the D-pad buttons at all.

Any help would be appreciated, thank you.

I am unable to locate a "d3d8.log" file. In the "D3D8" folder the only files I see are "d3d8.res", "d3d8.ini", and "d3d8.dil" .

**Comment by Polymega** [comment]
Hi plantmatter,

> I am unable to locate a "d3d8.log" file. In the "D3D8" folder the only files I see are "d3d8.res", "d3d8.ini", and "d3d8.dil"

It sounds like you don't have the files placed in the right folders. These files, for example, should be in the main folder for Silent Hill 2. You want your game's directory to look like this when all's said and done: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

**Comment by planttmatter** [comment]
![folder screenshot](https://user-images.githubusercontent.com/106044448/169736897-83d66c09-e81e-4085-9f41-173beff6ed93.png)

This is how my Silent Hill 2 folder looks.

**Comment by Polymega** [comment]
With the exception of the `data` folder, you want to move all the files/folders found in all those folders into the main directory (what you've pictured).

You want your game's directory to look like this when all's said and done: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

**Comment by planttmatter** [comment]
![screenshot sh2](https://user-images.githubusercontent.com/106044448/169740555-5fb0d7b6-6a92-4a2c-ae54-1c6b42c0bba7.png)
![screenshot sh2e](https://user-images.githubusercontent.com/106044448/169740590-adb7df43-b108-49d2-8ce6-4be29aa3d121.png)

It looks like I'm still missing  "d3d8.log"  along with "D3DCompiler_43.dll", "D3DX9_43.dll",  and the XInput Plus files. (I didn't download any Xinput files because I will only be using PlayStation controllers) 

In the SH2E folder there is a "ps2" folder that I haven't seen mentioned in the recommended directory tree page.

**Comment by planttmatter** [comment]
I just checked, the "ps2" folder in "sh2e" came from my "Enhanced_Edition_Essential_Files_1.2.1"

**Comment by planttmatter** [comment]
I just ran the game, the D-pad is working now, and a d3d8.log has been created. 

Should I do anything about the "ps2" folder from  "Enhanced_Edition_Essential_Files_1.2.1"  ?
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8751554/d3d8.log)

**Comment by Polymega** [comment]
Your directory looks good now and you don't need to worry about the `ps2` folder. Have fun!

**Comment by planttmatter** [comment]
Excellent, thank you so much for all your help.
