### ISSUE TITLE
i have installed the silent hill 2 enhancements but when i open the game its running the director cut and i never had this issue before 

### ISSUE THREAD

**Issue by L0NEW0LF4** [elishacloud/Silent-Hill-2-Enhancements#525]
the first time i downloaded silent hill 2 on pc i installed the enhanced version and it was working great didn't  have issues with it and 2 days ago when i tried playing the game it didnt open the enhanced version and i tried reinstalling everything and nothing was working and i don't know what happened or what the issue is. can someone please help me figure out why this is happening
[d3d8.log](https://github.
![Screenshot 2022-05-23 201955](https://user-images.githubusercontent.com/100493792/169941996-7e476b9f-806f-4d54-9d3c-69d515ed2440.png)
com/elishacloud/Silent-Hill-2-Enhancements/files/8759267/d3d8.log)
.

**Comment by Polymega** [comment]
Looking at your log file, this might have something to do with it:

```
21352 19:49:12.414 FAILED to hook the FileSystem APIs, disabling 'UseCustomModFolder'!
```

[Which is related to this ticket.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/521) Try using the build linked below to see if that fixes things for you:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/519#issuecomment-1133440672

**Comment by L0NEW0LF4** [comment]
Thank you so much that fixed the issue i appreciate your help and everyone in the community!

**Comment by Polymega** [comment]
Glad that fixes things! I'll close this ticket out then.
