### ISSUE TITLE
_BinkSetSoundtrack@8

### ISSUE THREAD

**Issue by TheGhost468** [elishacloud/Silent-Hill-2-Enhancements#528]
Hi, i have a problem when i want to start the game : _BinkSetSoundtrack@8

**Comment by Polymega** [comment]
It sounds like you are missing the Bink DLL file. Do you have a `d3d8.log` file in your game's directory? If so, please **attach** it as a response here. If not, please take a screenshot of the contents of your game's folder.

**Comment by elishacloud** [comment]
I guess it is probably the wrong version of the `binkw32.dll` file.  Try using this one.  Just unzip it into the Silent Hill 2 folder, overwriting any other file.

Correct bink file:  [binkw32.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8815357/binkw32.zip)

**Comment by Polymega** [comment]
Closing ticket from no follow-up.

**Comment by cohen312** [comment]
![resim_2024-05-20_101556287](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/170301830/e120bcba-a8b0-4689-a2c3-39a74882b400)
ah can i help me "Procedure entry point _binksetsoudtrack@8 was not found in the dynamin link library C:/ ..... SH2PC.exe"

**Comment by elishacloud** [comment]
@cohen312, that issue happens when there is an issue with the `binkw32.dll` file.  Where did you get your installation from?  You may need to remove and reinstall it or find another place to download it.

Here is the file you should have:  [binkw32.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15380366/binkw32.zip)

**Comment by Polymega** [comment]
Typically this happens when the base, vanilla PC game isn't downloaded/installed.

**Comment by elishacloud** [comment]
Make sure you have the actual Silent Hill 2 game installed.  The game needs to be installed before adding the Enhancements.

**Comment by cohen312** [comment]
Is it necessary to download both vanilla and enhanced version? I just downloaded the improved version

**Comment by Polymega** [comment]
You need to install the base, vanilla game first. Our project requires this as we patch our fixes into the game. Without the game, it won't run.

Read more here: https://enhanced.townofsilenthill.com/SH2/install.htm#installGame

**Comment by cohen312** [comment]
Sorry I can't do it. Ther
![Uploading resim_2024-05-20_235658328.png…]()
e is no setup.exe for the vanilla version. What should I do? I can't manage

**Comment by cohen312** [comment]
![resim_2024-05-20_235712361](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/170301830/10b707d4-38ba-4575-a896-e71ce2d21628)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/170301830/b91e448c-b294-49b1-a832-9d833241a86c)

**Comment by cohen312** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/170301830/f7f7784f-466a-4ec1-ba8d-8c3d0a68d3e3)
Sorry I can't do it. There is no setup.exe for the vanilla version. What should I do? I can't manage

**Comment by cohen312** [comment]
I'm sorry, I'm such an idiot, but I can't find how to download the vanilla version.

**Comment by elishacloud** [comment]
I am sorry, but we cannot help with acquiring the game.  You will need to do that on your own.  Our project is just a mod for the game but you need to own the game first, before you can use our mod.

**Comment by Polymega** [comment]
Retro Arch is an emulator. Our project is for the native PC version of SH2. Our project won't work on the PS2 or Xbox version of the game. You'll need the PC version of Silent Hill 2.
