### ISSUE TITLE
Visual C++ Runtime error

### ISSUE THREAD

**Issue by zel023** [elishacloud/Silent-Hill-2-Enhancements#53]
Hi, I'm very excited to try this enhanced version of SH2 but I have a problem. Whenever I launch the game I get this runtime error:
![runtime error](https://user-images.githubusercontent.com/44278696/47195405-15a8a700-d332-11e8-87d7-847c1d50bcc0.PNG)

I tried reinstalling the game and the visual c++ packs however the issue persists. Maybe I need a specific version? These are the ones that I have:

![c](https://user-images.githubusercontent.com/44278696/47195980-d0d23f80-d334-11e8-8091-76c2c0680ab8.PNG)

**Comment by Polymega** [comment]
Hi @zel023 , 

[You may be experiencing the same issue another user has had.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/46#issuecomment-424210965) 

Try downloading the [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2409446/d3d8.zip) Elisha provided and see if that works. If it still doesn't work, trying disabling the autoupdate module in the `d3d8.ini` file.

**Comment by zel023** [comment]
> Hi @zel023 ,
> 
> [You may be experiencing the same issue another user has had.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/46#issuecomment-424210965)
> 
> Try downloading the [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2409446/d3d8.zip) Elisha provided and see if that works. If it still doesn't work, trying disabling the autoupdate module in the `d3d8.ini` file.

That didn't fix it :(
Yes, I think the issues are similar but my game doesn't run in the background, I just get that empty window and the error message shown in the screenshot.

**Comment by Polymega** [comment]
Okay, could you please attach your `d3d8.log` file here?

**Comment by Polymega** [comment]
@zel023 I just finished helping my friend install this and he had the same issue as what you shared. Him disabling the mod autoupdater within the `d3d8.ini` file fixed the issue for him. 

To be sure: You also tried disabling this and relaunching the game?

**Comment by Polymega** [comment]
Thank you for double-checking and the log file. 

According to that file, it's freezing whenever d3d8to9 is trying to activate. Set `d3d8to9 = 0` and see if the game will launch then. 

Another question: You're not using the WineD3D files by chance, are you?

**Comment by zel023** [comment]
I disabled d3d8to9 and the game works now! But that means I won't be able to use the reshade filters, right? Is there something else I can try to make them work?
I'm not using WineD3D.

**Comment by Polymega** [comment]
> But that means I won't be able to use the reshade filters, right?

Unfortunately, that is correct. 

While ReShade is a nice addition for the game, SH2 PC is still perfectly playable without it. ReShade slightly adjusts color/levels for the game and adds anti-aliasing. Not having those add-ons doesn't hinder the game. 

However, you can force anti-aliasing through your GPU's control panel still. 

Perhaps this could be looked in to at a later date.

**Comment by zel023** [comment]
I see. Thank you so much for your help Polymega :+1:

**Comment by KojiKenshiro** [comment]
For the sake of not starting another thread for the exact same issue I'm typing this reply!  I'm having the exact same issue as the OP and was able to resolve it by turning off D3D8to9 in the D3D8.ini file!  Even though the effects of the ReShade+PS2 Filter are minor and I can turn on AA in my GPU settings, it does make the game look closer to that of the PS2 version!  If the developers have time to look into and fix this issue it will be greatly appreciated!  I would like to also thank the devs of the various SH2 PC Hacks/Fixes for doing a great job in making the PC version one of the best ways to play this great game!  Cheers!  :)

**Comment by Polymega** [comment]
@zel023  @KojiKenshiro try downloading the newest version of ReShade and see if that fixes it for you. [Installation steps can be found here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/88#issuecomment-456635410)

**Comment by KojiKenshiro** [comment]
By installing the new version of ReShade, it has fixed the Visual C++ Error I was having!  Thank you Polymega for the updated files!  It now plays great!  :)

**Comment by elishacloud** [comment]
Closing issue since new version of ReShade fixes it.
