### ISSUE TITLE
segment of the Japanese text file?

### ISSUE THREAD

**Issue by kiminru** [elishacloud/Silent-Hill-2-Enhancements#531]
Can you tell me the segment of the Japanese text file (ex: common_msg_j.mes)?
$0CB800 $0800 example for 'common_msg_i.mes' (Italian language file)

Segment of Japanese text file currently required
1. common_msg
2. item_x_msg
3. letter_msg
4. m_card_x_msg
5. memo_x_msg
6. option_msg
7. result_msg
8. stage_apart_e1f_msg
9. stage_apart_e2f_msg
10. stage_apart_e3fe_msg
11. stage_apart_e3fw_msg
12. stage_apart_out_msg
13. stage_apart_stair_msg
14. stage_apart_w1f_msg
15. stage_apart_w2f_msg
16. stage_bowling_msg
17. stage_delusion_2_msg
18. stage_delusion_3_msg
19. stage_eddie_boss_msg
20. stage_end_dog_msg
21. stage_end_maria_msg
22. stage_end_rebirth_msg
23. stage_end_recovery_msg
24. stage_end_suicide_msg
25. stage_forest_msg
26. stage_heaven_night_msg
27. stage_hospital_1f_f_msg
28. stage_hospital_1fe_b_msg
29. stage_hospital_1fw_b_msg
30. stage_hospital_2f_b_msg
31. stage_hospital_2f_f_msg
32. stage_hospital_3f_b_msg
33. stage_hospital_3f_f_msg
34. stage_hospital_bf_b_msg
35. stage_hospital_pass_msg
36. stage_hospital_rf_f_msg
37. stage_hotel_1f_b_msg
38. stage_hotel_1f_f_msg
39. stage_hotel_2f_b_msg
40. stage_hotel_2f_f_msg
41. stage_hotel_3f_b_msg
42. stage_hotel_3f_f_msg
43. stage_hotel_bf_b_msg
44. stage_hotel_bf_f_msg
45. stage_hotel_fire_msg
46. ​​stage_labyrinth_e_msg
47. stage_labyrinth_n_msg
48. stage_labyrinth_w_msg
49. stage_lake_msg
50. stage_observation_msg
51. stage_prison_bf_msg
52. stage_prison_n_msg
53. stage_prison_s_msg
54. stage_society_msg
55. stage_to_heaven_msg
56. stage_toilet_msg
57. stage_town_east_msg
58. stage_town_west_msg
59. stage_x_apart_msg
60. stage_x_heaven_msg
61. stage_x_mansion_1f_msg
62. stage_x_mansion_2f_msg
63. stage_x_mansion_bf_msg
64. stage_x_town_msg

I need segments of 64 japanese text files
Currently, the Korean language porting patch has been completed with the help of belek666, IlDucci.
We are working on a Korean translation of the untranslated text of the phrases that appear on PS2.

However, since the Italian language was replaced as the base, 
the wrong Korean was displayed when the Japanese language was set, 
so I would like to replace it with the Japanese text file.

To be honest, I think it would be difficult for anyone to recognize this large number of segments,
it's about 64 files and it's not easy to challenge.

Can someone please tell me how to find the segment?

This is the ported Korean version
Thank you 'belek666, IlDucci' for helping with font porting!
And many of you who have helped here!

![Slot__0___Speed__100_(59 96)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x](https://user-images.githubusercontent.com/84241069/172785449-79940e7f-a4c8-4b99-b82d-9e6346ccad7c.png)

Pausa is still output even though the Italian language file has been replaced with Korean text.
I looked all over Pausa's text file, but it didn't exist.

![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x](https://user-images.githubusercontent.com/84241069/172785477-aee5c2ea-ec5d-4e36-badd-655043e67ca1.png)
![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x (1)](https://user-images.githubusercontent.com/84241069/172785487-40ea9086-ee1a-4e18-bd7d-b6e4bb7c6d3b.png)
![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x (2)](https://user-images.githubusercontent.com/84241069/172785493-ff089ac2-6c02-4854-90a2-92d13dc13e10.png)
![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x (3)](https://user-images.githubusercontent.com/84241069/172785508-42ff06fa-1c61-4641-8c5c-eec90b34a40e.png)
![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x (4)](https://user-images.githubusercontent.com/84241069/172785521-a3f8f179-89f7-415d-8317-e8b803ea4323.png)
![Slot__0___Speed__101_(60 48)___NTSC___Limiter__Normal___GSdx_D3D11_HW___512x (5)](https://user-images.githubusercontent.com/84241069/172785536-95f04574-fb87-456d-bdc5-fa8796f5737a.png)

PS. Script Replacer program Created by: @IlDucci
PS. I have completed the Korean port porting of the Enhanced Edtion(PC version), and all that is left is the PS2.

**Comment by Polymega** [comment]
> Pausa is still output even though the Italian language file has been replaced with Korean text.

For the PC version, the text strings for the pause menu are not stored in external files, but instead are stored within the main binary of the game (sh2pc.exe). The PS2 version might do something similar.

**Comment by Polymega** [comment]
PS - Nice to see you back around @belek666! 😊

**Comment by kiminru** [comment]
> > Pausa is still output even though the Italian language file has been replaced with Korean text.
> 
> For the PC version, the text strings for the pause menu are not stored in external files, but instead are stored within the main binary of the game (sh2pc.exe). The PS2 version might do something similar.

thank you for the information. 
I'll have to look for it with a hex editor. :)

**Comment by belek666** [comment]
> PS - Nice to see you back around @belek666! 😊

Hi, I have been away for a while ;)

**Comment by kiminru** [comment]
Replaced 'Pausa' with 'Pause' using the current Hxd program. @Polymega Thanks!

Now all that's left is a segment of Japanese text.

I've been looking for it using HxD, but I'm not sure.
In a program that replaces segments in an Italian text file,
In the case of common_msg_i.mes ('f' is written as 'f' because of the Korean text file, it actually replaces 'i'), 
it is $0CB800 $0800.

But in HxD, it appears like picture that, how do I change it?
![a](https://user-images.githubusercontent.com/84241069/173168408-eba60aed-eb9c-43fb-b7f6-142713b3d83d.png)

**Comment by IlDucci** [comment]
> Now all that's left is to replace the Japanese text file and change the selection to 'O' instead of the 'X' key (selection is 'X' in North America, 'O' in Asia.)

That's going to be a romhacking issue, I'm afraid.

> I've been looking for it using HxD, but I'm not sure. In a program that replaces segments in an Italian text file, In the case of common_msg_i.mes ('f' is written as 'f' because of the Korean text file, it actually replaces 'i'), it is $0CB800 $0800.

common_msg_j.mes is located at $0CC000, size $800.

> ![a](https://user-images.githubusercontent.com/84241069/173168408-eba60aed-eb9c-43fb-b7f6-142713b3d83d.png)

Don't forget to credit me if you are using my scripts ;)

**Comment by kiminru** [comment]
> > Now all that's left is to replace the Japanese text file and change the selection to 'O' instead of the 'X' key (selection is 'X' in North America, 'O' in Asia.)
> 
> That's going to be a romhacking issue, I'm afraid.
> 
> > Now all that's left is to replace the Japanese text file and change the selection to 'O' instead of the 'X' key
> 
> I don't understand, are you looking for common_msg_j.mes? That's at $0CC000, size $800.
> 
> > ![a](https://user-images.githubusercontent.com/84241069/173168408-eba60aed-eb9c-43fb-b7f6-142713b3d83d.png)
> 
> Don't forget to credit me if you are using my scripts ;)

Wait, why did I forget this? I forgot you were the programmer who made this! In the beginning, I thought a language port patch was not promising, but it was a script program that showed the possibility of a language port patch when I was first introduced to this program by someone else.
To be honest, I wouldn't have gotten this far without this script program. Thank you very much!

Of the 64 programs listed above, a segment of a Japanese text file is required. I replaced the Italian language with Korean using your script program. Now I am trying to replace the Japanese language with Korean. Because Korean has replaced the Japanese language with Korean :)

PS. @IlDucci Your script program is awesome! Thanks to your script programming, the Korean language patch was successful :)

**Comment by IlDucci** [comment]
Guess that's what happens when somebody else uploads one's work without asking permission first.

Anyway, if you have the package I'm thinking, you should have a file called ETCDATA_ALL.txt. Open the ETC.XXX.GHITS_NTSCU_201.txt file, replace the text file with this one, and it will reinject all the MES files for every language (make sure you have the original files for English, French, German, Italian and Spanish).

**Comment by kiminru** [comment]
> Guess that's what happens when somebody else uploads one's work without asking permission first.
> 
> Anyway, if you have the package I'm thinking, you should have a file called ETCDATA_ALL.txt. Open the ETC.XXX.GHITS_NTSCU_201.txt file, replace the text file with this one, and it will reinject all the MES files for every language (make sure you have the original files for English, French, German, Italian and Spanish).

Unfortunately I only have the Italian language txt, because I initially went to your github to get this program, but couldn't find it, so I got this file from another Italian speaker.

**Comment by IlDucci** [comment]
Could you tell me an email address so I can send you an updated toolkit?

**Comment by kiminru** [comment]
> Could you tell me an email address so I can send you an updated toolkit?

Thank you :)
My email address : kiminru@naver.com

**Comment by kiminru** [comment]
> Could you tell me an email address so I can send you an updated toolkit?

Finally got a chance to replace the text file of JPN in Korean!
Thank you for your continued reply and help despite your busy schedule, it was a great help!

You are truly a talented programmer and such a hero to me as a great helper, I would like to express my sincere thank you! :)

**Comment by kiminru** [comment]
> Could you tell me an email address so I can send you an updated toolkit?

Hi, it's been working fine since I sent you the file back then. I foolishly backed up Italian, English, and Japanese, and deleted the segment text files for other languages. Could you please send me the segment text file collection again? All you need is a segment text file!

**Comment by Polymega** [comment]
@kiminru 
If you're interested, we'd be interested in hosting a Korean language pack on the site for our next project update. We now also have the means to support [a full font HD sheet](https://user-images.githubusercontent.com/27395260/186553032-82902734-f79c-430d-b23d-7b3f50b686e5.jpg).

In the link below, I have the Photoshop file I used to create the HD font sheet. All characters within this font sheet are editable. I would need you to replace all of the Japanese characters with Korean characters. (There is a grid layer in the Photoshop file that you can enable to ensure the Korean characters are properly sized/placed within the font sheet.) Then, of course, I would need you to test, test, test, test to ensure everything is displaying correctly for the Korean language:

If you'd like to make HD Korean characters for the game, please follow these steps:

- The native PSD file for you to create the Korean HD font sheet: [www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip](http://www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip) 
   - _Note: Download speeds may be slow at the moment as I'm experiencing server issues with my hosting provider._
- You will need to use a test build of the project that supports the full HD font sheet in PNG format. You can use this test build for the time being: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip
- You will need to save the HD font sheet in PNG format with a transparent background. Save the file as "font000.png" and place in the SILENT HILL 2\sh2e\font\ folder.

**Comment by kiminru** [comment]
> @kiminru If you're interested, we'd be interested in hosting a Korean language pack on the site for our next project update. We now also have the means to support [a full font HD sheet](https://user-images.githubusercontent.com/27395260/186553032-82902734-f79c-430d-b23d-7b3f50b686e5.jpg).
> 
> In the link below, I have the Photoshop file I used to create the HD font sheet. All characters within this font sheet are editable. I would need you to replace all of the Japanese characters with Korean characters. (There is a grid layer in the Photoshop file that you can enable to ensure the Korean characters are properly sized/placed within the font sheet.) Then, of course, I would need you to test, test, test, test to ensure everything is displaying correctly for the Korean language:
> 
> If you'd like to make HD Korean characters for the game, please follow these steps:
> 
> * The native PSD file for you to create the Korean HD font sheet: [www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip](http://www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip)
>   
>   * _Note: Download speeds may be slow at the moment as I'm experiencing server issues with my hosting provider._
> * You will need to use a test build of the project that supports the full HD font sheet in PNG format. You can use this test build for the time being: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip
> * You will need to save the HD font sheet in PNG format with a transparent background. Save the file as "font000.png" and place in the SILENT HILL 2\sh2e\font\ folder.

The lines in the cutscenes were perfectly translated by me, and other translations were not checked, but they are perfect. 
(I need to make some modifications...) 

I always want to include my translated Korean text file in the next patch of Silent Hill 2 Enhanced Edition. 
(I've gotten a lot of help here, so I want to help too!)

**Comment by Polymega** [comment]
> I always want to include my translated Korean text file in the next patch of Silent Hill 2 Enhanced Edition. (I've gotten a lot of help here, so I want to help too!)

Awesome! We'd love to include a Korean language pack on the site! 

I'm about to send you a long message, so apologies ahead of time. There's a couple of things I'd like to go over to help you along the way (some of these are repeated from before):

---------------

The link to the save file with most/everything unlocked should be working again. [You can grab it here.](https://igotaletter.com/temp/sh2pc/TranslationGuide/SH2PC_Translation-Guide_Save-Files.zip) Be sure to make a backup of your save files first and read the "README" file in the save folder from this download.

------------

I recommend you read over this translation guide. It covers almost all question you might have with translating SH2 PC to Korean: https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#

--------------

^ Within that document, there are some specific things we'd need you to do for use with our project. Please make sure these are accounted for:

1. [Have you kept translations within a 4:3 boundary?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a)
2. A few lines in the game, such as "I'll wait at BAR Neely's" and "The door what wakes in darkness, opening into nightmares" should be blue, not white. [Have these colors been fixed?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.1d337z371evw)
3. Nearly all of the save location names have their colors changed for the save menu, to make their coloring more consistent. [Have you changed the colors to be compliant?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
4. There are character limitations for a few strings in the pause menu. [Are you within these character limitations?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)
5. Certain strings found within the Control Options menu can change, depending on whether Directional (2D) or Rotational (3D) control type is selected. [Have these strings been translated correctly?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.r53nwexuz3m2)

-------------------

I can help you make a translated, Korean main menu for the game. [See here for an example.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/630#issuecomment-1287878913) I would need the following translated by you:

```
LOAD
CONTINUE
NEW GAME
OPTIONS
MOVIES
EXIT
ACTION LEVEL
RIDDLE LEVEL
HARD
NORMAL
EASY
BEGINNER
Main Scenario: LETTER FROM SILENT HEAVEN
Sub Scenario: BORN FROM A WISH
```
--------------

For the font sheet, [you can download this Photoshop file](http://www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip) that has the **full font sheet** editable. You can edit every character in this font sheet to accommodate the Korean language.

You will need to save the HD font sheet in PNG format with a transparent background. Save the file as "font000.png" and place in the SILENT HILL 2\sh2e\font\ folder.

Make sure you have updated the main SH2E module for testing, as the latest version of the module support PNG format for the font sheet.

---------------

If you have any questions along the way, please let me know!

**Comment by kiminru** [comment]
> > I always want to include my translated Korean text file in the next patch of Silent Hill 2 Enhanced Edition. (I've gotten a lot of help here, so I want to help too!)
> 
> Awesome! We'd love to include a Korean language pack on the site!
> 
> I'm about to send you a long message, so apologies ahead of time. There's a couple of things I'd like to go over to help you along the way (some of these are repeated from before):
> 
> The link to the save file with most/everything unlocked should be working again. [You can grab it here.](https://igotaletter.com/temp/sh2pc/TranslationGuide/SH2PC_Translation-Guide_Save-Files.zip) Be sure to make a backup of your save files first and read the "README" file in the save folder from this download.
> 
> I recommend [you read over this translation guide](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#). It covers almost all questions you might have with translating SH2 PC to Korean.
> 
> ^ Within that document, there are some specific things we'd need you to do for use with our project. Please make sure these are accounted for:
> 
> 1. [Have you kept translations within a 4:3 boundary?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a)
> 2. A few lines in the game, such as "I'll wait at BAR Neely's" and "The door what wakes in darkness, opening into nightmares" should be blue, not white. [Have these colors been fixed?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.1d337z371evw)
> 3. Nearly all of the save location names have their colors changed for the save menu, to make their coloring more consistent. [Have you changed the colors to be compliant?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
> 4. There are character limitations for a few strings in the pause menu. [Are you within these character limitations?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)
> 5. Certain strings found within the Control Options menu can change, depending on whether Directional (2D) or Rotational (3D) control type is selected. [Have these strings been translated correctly?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.r53nwexuz3m2)
> 
> I can help you make a translated, Korean main menu for the game. [See here for an example.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/630#issuecomment-1287878913) I would need the following translated by you:
> 
> ```
> LOAD
> CONTINUE
> NEW GAME
> OPTIONS
> MOVIES
> EXIT
> ACTION LEVEL
> RIDDLE LEVEL
> HARD
> NORMAL
> EASY
> BEGINNER
> Main Scenario: LETTER FROM SILENT HEAVEN
> Sub Scenario: BORN FROM A WISH
> ```
> 
> For the font sheet, [you can download this Photoshop file](http://www.igotaletter.com/temp/sh2pc/SH2PC_HD-Font-Sheet_Native-Files.zip) that has the **full font sheet** editable. You can edit every character in this font sheet to accommodate the Korean language.
> 
> You will need to save the HD font sheet in PNG format with a transparent background. Save the file as "font000.png" and place in the `SILENT HILL 2\sh2e\font\` folder. **Test your font sheet many, many times to ensure all the characters are aligned and displaying correctly!!**
> 
> Make sure you have updated the main SH2E module for testing, as the latest version of the module supports PNG format for the font sheet.
> 
> If you have any questions along the way, please let me know!

thank you, There are many good tips. 
First of all, we are translating the PS2 version. 
Fortunately for the PS2 Silent Hill 2 it's 4:3 aspect ratio and I'm setting the subtitles to fit the 4:3 aspect ratio.
Currently, it is still being translated and the inspection has been completed, so it is only in the stage of correction, 
but in the case of the PC version, there is a new character CRC, so it may take more time to resolve this. 
I'll let you know when it's finished or if I run into any problems along the way. thank you!
