### ISSUE TITLE
crc error while trying to unpack the image enhacement pack

### ISSUE THREAD

**Issue by onyxkid** [elishacloud/Silent-Hill-2-Enhancements#532]
hey, i was trying to install this component but both of my archive-reading programs produce a crc error while trying to unpack the file. i tried downloading it 2 times but every single time i download it it produces an error. someone help?

**Comment by onyxkid** [comment]
okay i dled the package another time and it looks like it's not broken, lol. sorry

**Comment by onyxkid** [comment]
okay so i am back and i still have this problem. like some time ago i also did download the whole thing without any problems so i don't think it's my connection. but still, every single time i try to download the bigger files i get crc errors and some file corruption. tried to download with a download manager but the problem STILL persists.

**Comment by Polymega** [comment]
Sorry you're having issues. We haven't received any other reports on this issue recently. Can you try downloading the files using a different browser? Do you have any software protection (virus/malware protector) that might be preventing you from opening the files?

**Comment by onyxkid** [comment]
i did try downloading with a different browser and the problem still persists. i do not have any other software protection other than windows defender.

**Comment by Polymega** [comment]
You mentioned it's all the big packages? So the Audio, FMV, and Image pack are causing issues?

**Comment by onyxkid** [comment]
yeah, those bigger than 50 mb or so. i've been trying to download the FMV and audio packages for a few days now and i cannot do it because the files get corrupted every single time.

**Comment by Polymega** [comment]
I just downloaded the Image Pack (300 MB), Essential Files pack (200 MB), and Audio pack (1.5 GB) from the project site. I extracted the ZIP files using Windows' built-in ZIP tool and 7Zip without issue.

I'm not sure what the issue might be. Can you try downloading these files on another computer? If it works, you can transfer the files back to your main computer through a flash drive.

Beyond that, I'm not sure what the issue might be.

**Comment by onyxkid** [comment]
i tried downloading on another browser and yeah the errors still continue. i have no idea what might be causing this, couple of months ago i did download the whole thing without any issues, not sure what might have happened now...

**Comment by Polymega** [comment]
If you're able, it might be worth testing trying to download at least one of these packages on another computer just to see if it'll go all the way through on there.

**Comment by Polymega** [comment]
We are _very_ close to releasing the next update for the project. With this update will come the introduction of an installer which will download/place all the files for you. Would you be okay to wait just a little bit in the hopes that the installer may fix this problem you're running into? My hope is we'll have the update ready no later than the end of this month.

**Comment by Polymega** [comment]
An update for this: We have since released an installer to help with downloading. Please check it out on the project's site if you haven't done so already. I'll close this ticket out.
