### ISSUE TITLE
symbols instead of words

### ISSUE THREAD

**Issue by Eden1289** [elishacloud/Silent-Hill-2-Enhancements#536]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8928902/d3d8.log)
hello! for some reason in menu and options there's no normal letters, just symbols
and i also keep "fighting" with joystick (PS 4, no problems in other games and here the character is just uncontrollable)
ps Thank you guys so much for everything you did and keep doing, that's amazing
![изображение_2022-06-17_185115525](https://user-images.githubusercontent.com/107695492/174333262-dcfa9aed-a91e-4469-be03-05550ddf4a68.png)

**Comment by Polymega** [comment]
Hi there,
Sorry you're having trouble. Thanks for attaching your d3d8.log file. Where did you obtain your copy of the base Silent Hill 2 PC from?

**Comment by Eden1289** [comment]
> 
to be honest, I used the first available torrent. it's impossible to get the original pc disk here (even if I had money for it)

**Comment by Polymega** [comment]
Delete the game folder and go to this site. This site is safe: 
https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

**Download the "Fully Extracted Version."** 

Unzip its contents into a fresh, empty `Silent Hill 2` folder. This is the base game. All files in this download are 100% original and untampered with.

Once you do this, do not attempt to launch the game. Go back to our project site and [proceed with Step 2 onwards.](http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE)

**Comment by Eden1289** [comment]
> 

thank you very much!!

**Comment by Eden1289** [comment]
one more thing - step 2 and 3 on the website have the same file in it, is that ok?

**Comment by Polymega** [comment]
Step 2 is a replacement for the game's executable. It contains a "no CD" version of **sh2pc.exe** with all the DRM stripped.

Step 3 is the "brains" of our project. It will contain files such as **d3d8.dll**, **d3d8.ini**, and more.
