### ISSUE TITLE
FMV cutscene stretching

### ISSUE THREAD

**Issue by CerealMastery** [elishacloud/Silent-Hill-2-Enhancements#539]
I would prefer to play SH2 with 16:9 FMVs pillarboxed, but using the FMVWidescreenEnhancementPackCompatibility function with the dynamic resolution disabled hasn't worked.

FMVWidescreenEnhancementPackCompatibility = 1/2
![image](https://user-images.githubusercontent.com/108477550/176708639-d6d1dc2f-ca51-4d7e-97d5-4a614fb3e00b.png)

FMVWidescreenEnhancementPackCompatibility = 3
![image](https://user-images.githubusercontent.com/108477550/176708981-1a67e136-6aa7-4210-abaa-4c8057419a6a.png)

Playing from the bik file directly (what I would like it to look like)
![image](https://user-images.githubusercontent.com/108477550/176709196-dabb9ca7-3241-4a25-949a-aa404f72b988.png)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9020920/d3d8.log)

**Comment by CerealMastery** [comment]
OK, thanks for the answer. Looking forward to the update

**Comment by Polymega** [comment]
The new update is live! Please update the SH2 Enhancements module and FMV Pack to fix the FMV scaling issues.
