### ISSUE TITLE
game crashes at loading screen

### ISSUE THREAD

**Issue by Vanish69** [elishacloud/Silent-Hill-2-Enhancements#540]
woodside apt, enterance to 3f (after clock riddle, before meeting pyramid head)

game is trying to load for few sec and then suddenly crashes.
is there any fix or do i have to reinstall base game/ee?
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9021498/d3d8.log)

**Comment by Vanish69** [comment]
well i downloaded the base game from this site, so i guess that is just a bad luck, gonna reinstall it anyway

**Comment by Polymega** [comment]
Please update to the latest version of our project files/packages. This crashing issue should be resolved now. If not, you can re-open this ticket. Thanks.
