### ISSUE TITLE
Setup tool tells me I don't have enough space (even though I do) and won't install the Audio Pack.

### ISSUE THREAD

**Issue by brian0057** [elishacloud/Silent-Hill-2-Enhancements#546]
I love the Enhanced Edition.
I've already beaten it and I wanted to stay up to date with it.
I downloaded the Setup Tool and was able to install every enhancement except for the Audio Pack.

Since the internet where I live is... modest, to be polite, I decided to just install those that were light in size. I originally installed everything but the FMV and Audio Packs, since those are the largest one, and leave those downloading overnight.
The problem was it woudln't let me. It told me I needed more free space. Then, I tried downloading just the FMV Pack by itself and that worked. But the Audio Pack keeps telling me that I need to free up more space (which is wrong as the screenshots below prove).

![Captura 1](https://user-images.githubusercontent.com/108583624/177006622-1867d91b-1a24-4d14-a9cc-1945e4c2bcc9.PNG)
![Captura 2](https://user-images.githubusercontent.com/108583624/177006625-6746bcf0-255e-4dc8-80fc-8e854df47ba9.PNG)
![Captura 3](https://user-images.githubusercontent.com/108583624/177006627-4fa198d3-4213-4c52-9b8f-1080658b69fa.PNG)
![Captura 4](https://user-images.githubusercontent.com/108583624/177006620-c3f6abac-283c-4f1f-803f-cf7fab1b7bd1.PNG)

And here's my d3d8 file:
(I don't know if this is the correct procedure. This is my first time using GitHub.)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9033222/d3d8.log)

**Comment by Polymega** [comment]
Can you try downloading it directly to see if this works in the meantime?

https://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

**Comment by brian0057** [comment]
> Can you try downloading it directly to see if this works in the meantime?
> 
> https://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

Sorry, I can't download it.

Here's what it looks like in Chrome:
![Capture 5](https://user-images.githubusercontent.com/108583624/177011567-e987b634-96a4-4997-949d-5492f59ceb72.PNG)

And here's what it looks like In Edge:
![Captura 6](https://user-images.githubusercontent.com/108583624/177011575-0ba0f72f-1494-4c59-8129-9fdc6bcb7b67.PNG)

**Comment by Polymega** [comment]
I don't understand what's happening at the moment. I'll see if I can figure it out.

**Comment by Polymega** [comment]
Please try again:
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

**Comment by brian0057** [comment]
Nice. Now it's downloading.
Once it's done, I'll let you know how it went.

![Captura 7](https://user-images.githubusercontent.com/108583624/177012212-0badeb16-54f6-4e72-91d3-2015564181a6.PNG)

And yes, my internet is that slow.

**Comment by brian0057** [comment]
Once it finished downloading, I pasted the files on the sh2e folder. Just like old times.
Out of curiosity, I started the Setup Tool, it updated itself and now the download for the Audio Pack is working.

![Captura 8](https://user-images.githubusercontent.com/108583624/177018971-38eab73f-41fc-4dd5-86e6-6051baca9363.PNG)

So, I guess this is solved?

**Comment by Polymega** [comment]
Great! Glad it worked out. 

> Out of curiosity, I started the Setup Tool, it updated itself and now the download for the Audio Pack is working. So, I guess this is solved?

nipkow (the Setup Tool's author) fixed a few quirks with the tool and we pushed out an update for it (which you got notified of).

I sent him your support ticket here and he looked into that issue as well and made a fix for it. I was going to ask you to test this but I would've felt bad in asking since your internet speed isn't great. But it looks like it has been fixed. ☺️ 

So here's what you can do to make the Setup Tool know you have the latest Audio Pack:

- Open the `SH2EEsetup.dat` with a text editor such as Notepad
- Find and replace the line (Line 9) for the Audio Enhancement Pack with the following:
   - `audio_pack,true,2.0.4`

**Comment by brian0057** [comment]
Sweet!
Now it works perfectly.
Thank you so much.

I can't wait for what you guys have in store for the future.

**Comment by Polymega** [comment]
Awesome! I'll close this ticket out. Thanks
