### ISSUE TITLE
Just curious: reshade compatibility?

### ISSUE THREAD

**Issue by tauruslondono** [elishacloud/Silent-Hill-2-Enhancements#547]
Just wondering if the latest release (as of July 2, 2022) is compatible with reshade?

**Comment by elishacloud** [comment]
Yes.  You can use ReShade with this release, but it is recommended that you disable the built-in shaders if you do that:

![image](https://user-images.githubusercontent.com/25625456/177009355-9978d790-7096-4e45-9f8a-5de680eada61.png)

**Comment by tauruslondono** [comment]
Thank you! And thank you *very much* for the wonderful work on the Enhanced Edition!
