### ISSUE TITLE
Can't bind LT,RT on XInput controller to replicate original PS2 control scheme.

### ISSUE THREAD

**Issue by brad86m** [elishacloud/Silent-Hill-2-Enhancements#548]
Looking to replicate the exact PS2 controls, but  am unable to bind Aim and Search View to the shoulder buttons.

**Comment by Polymega** [comment]
What controller are you using? Regardless of the controller, you should download XInput Plus. This makes modern (XInput) controllers compatible with game by restoring trigger a D-pad functionality. Our included package of XInput Plus also comes with a preconfigured file that maps buttons for XInput controllers to SH2's default control scheme.

![image](https://user-images.githubusercontent.com/27395260/177055960-543bfcec-f516-4277-8a99-c10c4208148d.png)

**Comment by brad86m** [comment]
Thank you for the reply. I'm using the optional XInput Plus already. The controller is Xbox Series X controller.

**Comment by Polymega** [comment]
Please attach a copy of your `d3d8.log` file from the game's directory.

**Comment by AeroWidescreen** [comment]
To add to this, what you're trying to do should not be necessary because the Enhanced Edition is already configured to have nearly identical controls as the PS2 version.

I have an Xbox Series X controller and LT / RT works as they should (search / aim) after installing all packages.

![Example](https://i.imgur.com/5mYglJI.png)

**Comment by brad86m** [comment]
My apologies. I had a XInput to DInput wrapper that I use for a racing wheel, and I didn't realize that it was open. Just hid itself in the taskbar. Must have been conflicting with XInput.

Works perfectly fine with that closed.
