### ISSUE TITLE
[Request] Bring back offline installer

### ISSUE THREAD

**Issue by UserGit-2021** [elishacloud/Silent-Hill-2-Enhancements#550]
Bring back offline installer.
Add an offline installer option.

**Comment by Rainoutt** [comment]
Im downloading the patch at 245 kb/s so this will be an amazing request.

**Comment by Polymega** [comment]
There never was an offline installer. It was packages individually downloaded by the user. We'll look into this in the future.

> Im downloading the patch at 245 kb/s so this will be an amazing request.

The files are hosted on the same server regardless if an installer is used or not. So these speeds should happen no matter the download method. It's likely the server has been throttled due to the spike in traffic/downloads on the site from the announcement of this update.

**Comment by Rainoutt** [comment]
I think it's a problem with my connection to the host from Argentina, a lot of sites are throttled around 300 KB/s here for no aparent reason, even Github was throttled not so long ago. Just a 4 hour download, nothing to cry about. Keep the amazing work.

**Comment by UserGit-2021** [comment]
> There never was an offline installer. It was packages individually downloaded by the user. We'll look into this in the future.

I would be grateful if you would return the manual installation offline.

**Comment by Polymega** [comment]
Were you having troubles installing any of the files through the installer? If so, what packages were they?

**Comment by UserGit-2021** [comment]
> Were you having troubles installing any of the files through the installer? If so, what packages were they?

My connection breaks when downloading through the installer (provider's fault). I don't understand why they removed the ability to download manually?
Or give a link where the mods are located.

**Comment by UserGit-2021** [comment]
> 

I demand to return the offline installer.  I do not want to use the installer to litter pc.

**Comment by Polymega** [comment]
Demanding and arguing is not how this works. Put that to the curb.

**Comment by aroenai** [comment]
I'd like to request an offline installer for the eventual project retirement/when it's no longer maintained so future generations can still enjoy the patch without having to rely on dead url's.

**Comment by UserGit-2021** [comment]
> 

![изображение](https://user-images.githubusercontent.com/91757058/177278425-d3233ee7-e79e-42de-b176-ded6fd32894d.png)

**Comment by UserGit-2021** [comment]
> I'd like to request an offline installer for the eventual project retirement/when it's no longer maintained so future generations can still enjoy the patch without having to rely on dead url's.
> 
> Edit: https://github.com/nipkownix/SH2EE-web-installer/blob/f08d78523b2453ec10fe9b4bab9da94f08d60a2c/SH2EE-web-installer.iss appears to have the url's defined in a separate CSV file link defined as SH2EE_CSV_URL. Just for anyone else annoyed by this decision.

Thank you very much!

**Comment by elishacloud** [comment]
Our project is open source, so you can see what is happening.  As mentioned, the code [here](https://github.com/nipkownix/SH2EE-web-installer/blob/f08d78523b2453ec10fe9b4bab9da94f08d60a2c/SH2EE-web-installer.iss#L5) shows where the setup tool downloads the files from.  If you want to manually download the files you can get the links for them from there.  You don't need to use the setup tool.  However, the setup tool makes it much easier and helps you maintain all the updates.

**Comment by reza-m91** [comment]
yeah. didn't know how good I had it with being able to schedule the download with IDM and pause/resume whenever I wanted. the new installer/updater is good for people that have very fast internet and can't be bother to follow simple instructions though

**Comment by Balthazor44** [comment]
I would like to point out that the installer downloads all the zip files to the temp directory. Let the installer do it's thing, but before you exit the installer, go to Start->Run and enter %temp% to get to the temp directory and dig around in there to find the zip files and copy them wherever you want. Easy peasy.

**Comment by UserGit-2021** [comment]
> I would like to point out that the installer downloads all the zip files to the temp directory. Let the installer do it's thing, but before you exit the installer, go to Start->Run and enter %temp% to get to the temp directory and dig around in there to find the zip files and copy them wherever you want. Easy peasy.

Thank you!

**Comment by aerg4zt3a4za43z** [comment]
![image](https://user-images.githubusercontent.com/116378024/197248234-5b03c13a-5ac5-4d4c-8b1e-c5e2516fecc3.png)

same fucking problem, just provide a torrent for people to download the files like any other project like this one does, thank you.

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

Note there is now an "offline installation" choice at the start of an installation using the tool:

![004](https://user-images.githubusercontent.com/27395260/198738024-160b6f75-17e0-418c-ba3f-8c1c1deef444.PNG)
