### ISSUE TITLE
Game Runs Great, minus the Flashlight

### ISSUE THREAD

**Issue by BiggestRonald** [elishacloud/Silent-Hill-2-Enhancements#551]
So, after some trouble, I finally got the EE working on Parallels. 17.1.4 on an M1 Mac.  The game runs great, looks great, minus one issue.  The dreaded flashlight.  As you can see below, it just turns on, but really shines no amount of light and funnily enough, makes the game darker.

If there is any extra information I need to provide to help out let me know.  Thanks!

![Screen Shot 2022-07-04 at 1 09 53 PM](https://user-images.githubusercontent.com/108505972/177197224-fbe112ac-0e24-4312-8bce-2ae77e085779.png)

**Comment by elishacloud** [comment]
Try disabling all the options in the SH2EEconfig.exe tool and see if that helps.  If it solves the issue than you can try enabling the options page by-page to see which one caused the issue.  Once we have isolated which option solves the issue we can see about getting a fix for that.

**Comment by BiggestRonald** [comment]
@elishacloud No luck!  I thoroughly tried what you suggested but with no results.  Is there any other info I can give you to help?

**Comment by elishacloud** [comment]
What happens if you temporarily rename or remove the d3d8.dll file?

**Comment by BiggestRonald** [comment]
@elishacloud When the d3d8.dll file is removed or renamed the game launches as the normal PC edition, without any of the Enhanced Edition additions.

**Comment by Polymega** [comment]
That's okay. His suggestion to do that was so you could test the vanilla version just to see if the flashlight works there.

**Comment by BiggestRonald** [comment]
@elishacloud @Polymega Ah yes, it works on the normal PC edition but, the light shows up as red


![Uploading Screen Shot 2022-07-06 at 5.34.03 PM.png…]()

**Comment by BiggestRonald** [comment]
Ah yes, it works on the normal PC edition but, the light shows up as red.

<img width="1440" alt="Screen Shot 2022-07-06 at 5 34 03 PM" src="https://user-images.githubusercontent.com/108505972/177647541-5faaa5c4-ed3f-4fc7-8f4f-35b7395f90d9.png">

**Comment by elishacloud** [comment]
It seems to have something wrong even with the base game.  Whatever is causing it to be red may be the same thing causing it to disappear with the enhanced edition.  You may want to try the steps in this comment [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/540#issuecomment-1171446122).

**Comment by BiggestRonald** [comment]
@elishacloud Hm this version was the extracted Abandonware version but I will redownload and let you know if it has been fixed.  Before I do that, how do I ensure my save file carries over?  I'm not very savvy with this type of stuff.  Thanks!

**Comment by Polymega** [comment]
I'm the person who provided the fully extracted version to MyAbandonware. What I sent them was a 100% original version of the game with all files intact. I don't think you need to redownload it but you can give it a shot. I'm wondering if the issue lies with running the game on Parallels. I'm not sure as I do not own/use a Mac. 

But for future reference, your save files are located at `<path-to-game>\data\save\Folder 01\`. So you'd make a backup of your `Folder 01` folder.

**Comment by BiggestRonald** [comment]
Hmm, after re-installing, it's likely an issue with Parallels, the game isn't unplayable but, thank you for your help.
