### ISSUE TITLE
the procedure entry point bink set soundtrack@8 could not be located in the dynamic library

### ISSUE THREAD

**Issue by b3rtn** [elishacloud/Silent-Hill-2-Enhancements#554]
Hello 

I'm trying to run SH2EE but after install i'm having 

the procedure entry point bink set soundtrack@8 could not be located in the dynamic library
And the game never start , crashed. 

How can i fix it? 

Thanks

**Comment by Polymega** [comment]
Do you have a `binkw32.dll` file in the game's main directory?

**Comment by elishacloud** [comment]
Also, check out the comment [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/528#issuecomment-1143727451).

**Comment by Polymega** [comment]
Did you download the PS2 version of the game instead of the PC version? Refer to this ticket: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/559

**Comment by Nafil984** [comment]
> Also, check out the comment [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/528#issuecomment-1143727451).

Hum ko aap se kuch madad chahiye

**Comment by Nafil984** [comment]
@elishacloud

**Comment by Nafil984** [comment]
@Nafil984
