### ISSUE TITLE
Silent Hill 2 German translation

### ISSUE THREAD

**Issue by ZimSan** [elishacloud/Silent-Hill-2-Enhancements#555]
My issue with it is that it occassionally sounds like it got put through Google Translate and doesn't sound very natural compared to the english script.
<img width="421" alt="sh2 compare" src="https://user-images.githubusercontent.com/63849135/177551148-2b9c2f78-b1a4-4dad-a58b-54cbc57dc140.png">

This is a small example. Here is what the german trans. would sound like in english: "This suitcase has nothing of interest." when it should actually say: "In dieser Vitrine ist nichts sonderbar interessantes." or "In der Vitrine befindet sich nichts von besonderem Interesse". 

It's like they didn't see that scene in the game and had to guess what this "case" could refer too. The translation ain't irredeemable or something but certain scenes might need some fixes here and there to sound more natural.

**Comment by Polymega** [comment]
Hi there,

Yes, we've heard from fans of all available non-English language options (French, German, Italian, and Spanish) that the official translations leave a lot to be desired. 

To "fix" this, a German super fan would need to clean up the German language files. This same type of clean-up was previously done by Spanish and Italian fans and we now offer their improved language packs as a base kit with our project installation. Ideally, we'd love to get a super fan fluent in German and French to clean up the respective language files.

**Comment by ZimSan** [comment]
How difficult would it be to edit these language files? I'd help out if it wasn't too much of a hastle.

**Comment by ZimSan** [comment]
Sure. Tell me how to do it and I'll try fixing some weird lines whenever I have some spare time. Would I need to restart the game and just save my way through it whenever a cutscene could appear?

**Comment by IlDucci** [comment]
> I can write a more thorough guide for these things in the near future. I'm sure other people who have helped with translation efforts would chime in, too.

Y'know it.

> Tell me how to do it and I'll try fixing some weird lines whenever I have some spare time. Would I need to restart the game and just save my way through it whenever a cutscene could appear?

IMHO, if you or anyone else decides to check the German translation, I'd say to check the entirety of the texts though. Konami seemed to tend to do rush jobs (which would explain that some lines were properly translated, but others had issues) during the period of time when SH2 was released.

You would need to have access to the entire game. While there is a set of saves [in this comment](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/111#issuecomment-509738695) that cover a runthrough of the game, it lacks access to all the Memo files and to all available endings, so you would need to do a few more runs to get to those cutscenes.

I'll stop there for the moment, at least until Polymega decides to do a full doc on the matter. On the meantime, if you really want to do a deep dive onto what's been discussed, but nor sorted out, all conversations regarding language proofreads and translations can be found at the following issues:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/111
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/199
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/328
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/444
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/531

**Comment by Polymega** [comment]
@TheMachineAmbassador 
IlDucci and I are writing a guide on how to translate the game. I'd like to provide a save file that has most/all of the items and memos unlocked to make it easier for someone to test their translation work. [I found the arrays for unlocking the inventory items.](https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/SH2%20PC%20memory%20addresses#L172-L189) Is there a way to unlock all of the memos in a similar way?

**Comment by TheMachineAmbassador** [comment]
Hello @Polymega I have the address of memos, let me write a cheat engine script to unlock all. It will be ready in 15 mins.

**Comment by ZimSan** [comment]
A video guide would also be welcome. Doesn't even have to say anything just some images here and there with highlights so to not get confused on how to do it.

**Comment by TheMachineAmbassador** [comment]
Well i've tried to do a script on cheat engine but i guess it was gonna took than i expected so i did this on cpp it was much more easy for me.  i was gonna use this program for @Polymega to test save text pos so you can see different things in this when you executed the program all you have to do is pressing NUMPAD 5. I hope windows doesen't see this as a virus.
[Silent Hill 2 Memory Full.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9079855/Silent.Hill.2.Memory.Full.zip)
Also note to @Polymega this address is 01F7A9E8 points to memo it's a 28 byte of uint data. when you fill data with FF's it will unlock all memos.

**Comment by Polymega** [comment]
Thanks a ton, Machine Ambassador!

@ZimSan 
Here is a guide that goes over general tips and tricks for translating the game:
https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg

Don't be intimidated by its length; we were just being thorough with our notes. We also includes images for certain topics to help illustrate things. The document also contains downloads for all the necessary tools/files you may need.

**Comment by ZimSan** [comment]
Thanks! I'll read through it

**Comment by Polymega** [comment]
I'll close this ticket out. We'd still very much welcome improvements to the base, German language in the future, though!
