### ISSUE TITLE
Can't see where I am on the map

### ISSUE THREAD

**Issue by Utapakata** [elishacloud/Silent-Hill-2-Enhancements#556]
When I open the map there should be a green arrow showing where I am and which direction I am facing but it just doesn't show up for me. 
how it is
![Screenshot 2022-07-06 17-51-24](https://user-images.githubusercontent.com/108821833/177595791-5360d3c0-8b96-418d-bbc0-ba8b0e5e7f72.png)
how it should be
![sh2 map](https://user-images.githubusercontent.com/108821833/177594198-94e75f1f-5749-44a0-93d0-497f9e8d6ff3.png)
This isn't a game breaking issue but it definitely pads out playtime since I get lost more often.

**Comment by Polymega** [comment]
![image](https://user-images.githubusercontent.com/108821833/177595791-5360d3c0-8b96-418d-bbc0-ba8b0e5e7f72.png)

Someone has made their own edits to the full screen textures (such as this map) which is causing this issue. This is known by the translated words at the top of this map image.

Without getting too technical, this is caused as the texture file for the map markings (the green player arrow, the purple map arrows, and the red, black, blue lines) is 4x native resolution (as it is being used from our Image Enhancement Pack) but the translated map texture you're using is still at native resolution. 

For textures that "work together," such as a map texture and the map markings that sit on top of the map texture, their resolutions _must_ be scaled identically. So, if you use a map marking texture that is 4x the native resolution, the map texture itself also needs to be 4x the native resolution.

There are a couple ways you can fix this:
- Ask the person who translated the full screen images to make their textures 4x native resolution to be compatible with our Image Enhancement Pack.
- Remove the translated full screen images. You can do this by redownloading the project's Image Enhancement Pack. This should overwrite these files.
- Disable the Image Enhancement Pack. This will use the original, low resolution vanilla PC textures. You can disable this by opening the Configuration Tool and enabling **Disable "sh2e\pic\" path** (found under the "Advanced" tab).

**Comment by Utapakata** [comment]
Thank you for the response. 
After removing the translation the arrows came back which I'm thankfull for.
Keep up the great work
