### ISSUE TITLE
Missing MSVCP70.dll and MSVCR70.dll

### ISSUE THREAD

**Issue by Athen3** [elishacloud/Silent-Hill-2-Enhancements#559]
As the title states, I seem to be missing these two files even after re-installing and attempting to launch the game numerous times. I would appreciate if I can be given these files and see if that completely fixes it!

![image](https://user-images.githubusercontent.com/81726522/177773695-91d5dad5-5c12-4317-b824-46942910309f.png)
![image](https://user-images.githubusercontent.com/81726522/177773722-e4f855ba-5f89-4af7-bfba-27bc8b6ca514.png)

**Comment by Polymega** [comment]
`MSCVP70.dll` comes with the vanilla game and is a core file needed in order for the game to run. Where did you obtain your copy of SH2 PC from?

**Comment by Athen3** [comment]
I got it from Vimms lair, and the game works perfectly fine on PCXS2

**Comment by Polymega** [comment]
> and the game works perfectly fine on PCXS2

Did you download an ISO of the PS2 version of Silent Hill 2? Note that you'd need the PC version of SH2 for use with our project; the PS2 version wouldn't work.

Can you take a snapshot of the game's directory? Or better yet, can you share the Vimm's Lair link?

**Comment by Polymega** [comment]
Thanks. You downloaded the PS2 version of the game, which can only be played on a PS2 or PS2 emulator. For our project, you need the PC version of the game. Here's what you can do. Go to this site and download the "fully extracted" version **to a new folder:**

https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Once downloaded, go back to this folder:

![image](https://user-images.githubusercontent.com/81726522/177784065-9723d281-b531-49a9-b058-15826f60c968.png)

And **move every file/folder** from this folder _**except**_ SLUS-20228 (2.01).iso to your new SH2 PC folder.

**Comment by Polymega** [comment]
You want your game's directory to look something like this once all is said and done:
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree
