### ISSUE TITLE
Problems with the instalator

### ISSUE THREAD

**Issue by albertcipe1997** [elishacloud/Silent-Hill-2-Enhancements#560]
Hello!
Firstly, thank you for yours harder work with this mod.
I have a problem trying to install the FMV Enhancement Pack and Audio Pack, I'm trying to install individually either and: Firsts, the download takes too slow (450 kbs) and the second thing is when the installation arrives to 50% aprox. I have the limit time error.
I tried to install some times, but in all cases finished equals.
Does any other option? )`:

Thanks!

**Comment by Polymega** [comment]
Please download the FMV and Audio pack using the links below. As you download them, can you please report back the average download speed and whether they were successful or not?

- https://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip
- http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

**Comment by Polymega** [comment]
Sorry about that. Can you please try the links again? If they work, please let me know what your average download speed is for them and whether they were successful or not.

**Comment by albertcipe1997** [comment]
The links now works!! Thanks!
Tomorrow I'll try to download them (around 3 hours to download but works for now).
When I'll know anything, I post the result.

**Comment by albertcipe1997** [comment]
Okey, i tried to dowload the two .zips and give me network error likly the installer. 
I'm stay on start point again.
Thanks!
![imagen_2022-07-08_153613292](https://user-images.githubusercontent.com/103900256/178002890-0f37558e-8187-4c1b-8abe-44e9b85fd785.png)

**Comment by Polymega** [comment]
Were your download speeds also around 500 kpbs this time when you tried to download them?

**Comment by albertcipe1997** [comment]
exactly

**Comment by albertcipe1997** [comment]
My speed is around 100 MB/s
![imagen_2022-07-08_165044178](https://user-images.githubusercontent.com/103900256/178016792-03bb2706-e76e-4299-abdf-757b86af6bdb.png)

I'm goin to try again the instaler, and take a capture.

**Comment by Polymega** [comment]
Hmm... I wonder if the download speed is based on location of the client from the server? 🤔  As I mentioned before, I was getting 10 MB/s with the download just a few hours ago. This same speed happens when you download the packages directly from the links shared further up? For example, on Chrome, I can see the download speed here:

![image](https://user-images.githubusercontent.com/27395260/178037203-894d6871-14a7-4f9e-8b8f-599d1e24987b.png)

^ I just re-did the download and that was my speed.

**Comment by albertcipe1997** [comment]
I download it and unzip on game's folder, do it true?

**Comment by Polymega** [comment]
Yep, that's what you do. If you downloaded both the FMV and Audio Packs, you can test to see if the files were placed correctly by going to the MOVIES menu (from the main menu) and seeing if the SH2 PC credits video looks like this:

![Screenshot 2022-07-10 15-41-23](https://user-images.githubusercontent.com/27395260/178159683-c5528e5e-eb51-44b1-90a5-4997bb686ff6.png)

**Comment by albertcipe1997** [comment]
okay, so just works perfectly. However, when i start a new game, the main character doesn't have voice. Is it normal? I can only read the subtitles

**Comment by Polymega** [comment]
No, that's not normal. At the very beginning you should hear him say, "Mary... Can you really be in this town?" while he's in the bathroom. Can you please attach a copy of your `d3d8.log` file?
