### ISSUE TITLE
Problem with installing The Setup Tool

### ISSUE THREAD

**Issue by InterzGhostz** [elishacloud/Silent-Hill-2-Enhancements#561]
Hello, I have had the newest update installed along with the setup tool since The newest Update came out and had no problems so far. But today when I launched Silent hill 2 Enhanced edition It asked me if I wanted to update silent hill 2 Enhanced edition so I thought it was a new update but when I clicked "yes" it deleted the setup tool and it won't let me install it again. everytime I go to the website to install the setup Tool it won't let me, I've tried to check if it's my anti-virus programs that's preventing me from downloading it doesn't seem to be the case, I've tried installing it on different kinda browsers Google Chrome Firefox Microsoft Edge etc. It just doesn't let me download it again it's so Irritating. I don't know what's preventing me from installing it again, i Installed it last week when the update dropped with no problems but now it won't let me, And I don't know what to do it didn't delete any other files only the setup tool.

**Comment by Polymega** [comment]
Are you using Windows Defender for your protection? If so, can you please try updating its security intelligence:

![image](https://user-images.githubusercontent.com/27395260/178058130-34fef5f7-3a50-40e6-9aab-709f2ed0b45e.png)

After you update this, try downloading the Setup Tool again and let us know if it will download for you.

Thanks

**Comment by InterzGhostz** [comment]
> Are you using Windows Defender for your protection? If so, can you please try updating its security intelligence:
> 
> ![image](https://user-images.githubusercontent.com/27395260/178058130-34fef5f7-3a50-40e6-9aab-709f2ed0b45e.png)
> 
> After you update this, try downloading the Setup Tool again and let us know if it will download for you.
> 
> Thanks

**Comment by InterzGhostz** [comment]
> Are you using Windows Defender for your protection? If so, can you please try updating its security intelligence:
> 
> ![image](https://user-images.githubusercontent.com/27395260/178058130-34fef5f7-3a50-40e6-9aab-709f2ed0b45e.png)
> 
> After you update this, try downloading the Setup Tool again and let us know if it will download for you.
> 
> Thanks

**Comment by InterzGhostz** [comment]
I also tried updating the security intelligence it didn't seem to work

**Comment by Polymega** [comment]
> but when I clicked "yes" it deleted the setup tool and it won't let me install it again. everytime I go to the website to install the setup Tool it won't let me

I believe this is happening due to an antivirus protection flagging it as a false positive and removing it. Are you using any other protection software besides Windows Defender?

**Comment by InterzGhostz** [comment]
Well yes, but its very weird my other anti-Virus program that I use doesn't give me a notification Or anything when I try to install it, It usually does when it thinks i installed a virus or something harmful on my pc, it also didn't have any problems last week when i installed the setup tool.

**Comment by InterzGhostz** [comment]
actually I just fixed it the reason behind it was because my anti-virus program I use was very bugged and it didn't even show on my pc that it was blocking The setup tool from installing. but I just fixed it thank you so much for your help I appreciate it.

**Comment by Polymega** [comment]
Great! Glad you got it figured out,
