### ISSUE TITLE
Three and a half hours to dowload 4gb

### ISSUE THREAD

**Issue by falopaaa** [elishacloud/Silent-Hill-2-Enhancements#562]
the setup only downloads at 300 kb/s even though my internet is much faster
![error setup](https://user-images.githubusercontent.com/56804251/178126323-c04ae7a1-d8e9-4aa2-95b5-a589c49b39e5.png)

**Comment by Polymega** [comment]
These slow speeds would happen with or without the tool. I believe it's due to location from the host server. I've activated a CDN for the site which should help improve download speeds for people far away from the site's hosting server.

**Comment by KaiserZandrich** [comment]
> These slow speeds would happen with or without the tool. I believe it's due to location from the host server. I've activated a CDN for the site which should help improve download speeds for people far away from the site's hosting server.

Would it be possible to get a standalone installer for offline/future installs? Suffered through the normal downloader, wasn't quite as bad as OPs case but inconvenient nonetheless.

**Comment by Polymega** [comment]
We're working on an offline mode for the installer. No matter what though, if you want to download updates or the like, you'll still need to "suffer."
