### ISSUE TITLE
Error: Download Failed

### ISSUE THREAD

**Issue by DrR0Ck** [elishacloud/Silent-Hill-2-Enhancements#563]
Hello - I searched here for similar issues, but didn't find anything.  When I run the Setup Tool, I immediately get an error: Download failed.  Couldn't download sh2ee.csv.  The installation cannot continue.

I am able to retry but it fails again and exits the tool.  I had been running a prior version of SH2EE (i.e. manually downloaded packages).

Installer is version 1.05.  I am running Windows 10 21H1.  SH2 is installed at D:\Games\Konami\Silent Hill 2.

Let me know if there is any further info I can provide to help troubleshoot.

Thanks!

**Comment by Polymega** [comment]
I enabled a CDN for the site and had some incorrect settings toggled. Can you try again? I think the issue should be fixed now.

**Comment by DrR0Ck** [comment]
Still no luck.  Same error.

**Comment by illusion0001** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/37698908/178129740-799ab495-e66f-4630-8c58-2333624e9619.png)

**Comment by Polymega** [comment]
Sorry all. I'm purging the cache of the CDN to see if that fixes it.

**Comment by Polymega** [comment]
I believe it's resolved now. I just tested it. Let me know. Sorry for the troubles here. I enabled a CDN to help with download speeds for everything for people who are far away from my host's server. Enabling that bungled a few things up that I'm hoping are resolved now.

**Comment by DrR0Ck** [comment]
Started up for me.  I think we're in business.  Thanks!

**Comment by illusion0001** [comment]
Works now

**Comment by Polymega** [comment]
Thanks for letting me know

**Comment by mbalc** [comment]
I'm getting the same error now @Polymega, can you help me out?

**Comment by Polymega** [comment]
Can you please confirm you've downloaded the newest version of the Setup Tool from the project site? Clear your browser's image/file cache first, then go back to the site and download the tool from here: https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

**Comment by ja3h** [comment]
Same as mbalc, I've re-downloaded the newest version of the setup tool too (MD5: 54B00D056C1CE967B444E0A2E3DB7101)

**Comment by ja3h** [comment]
No, nothing at all. Though it could be a temporary thing because I scraped the file URLs from sh2ee.csv via the URL in SH2EE-web-installer.iss and every direct link apart from SH2EEsetup.exe isn't working. A ping for each URL finds nothing either so I'll just wait a few days, I have a full (earlier) install of the project anyway.

**Comment by Polymega** [comment]
> Though it could be a temporary thing because I scraped the file URLs from sh2ee.csv via the URL in SH2EE-web-installer.iss and every direct link apart from SH2EEsetup.exe isn't working. A ping for each URL finds nothing either

This doesn't make sense. So, as an example, the link below does not work for you?
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip

**Comment by Polymega** [comment]
(You may need to right click > save as when clicking through GitHub)

**Comment by ja3h** [comment]
It didn't instantly work. It automatically redirects to http:// so Chrome blocks the download but when I overrode it I got 'Failed - Network error' (ERR_TOO_MANY_REDIRECTS). Firefox the same issue but when I overrode it, it did download fine. 
Knowing it was definitely being grabbed I went back to Chrome and tried a few times over (without changing the process) and it did successfully download in Chrome on the 4th attempt. I did wonder if it could just be some sort of ISP DNS issue before hence me being alright to wait it out and I still think it could be that in combination with modern browsers not liking direct http downloads.

**Comment by nipkownix** [comment]
>It automatically redirects to http://

Huh, that's odd. That was the site's old behavior, right, @Polymega? Before the https work? Weird.

**Comment by Polymega** [comment]
> Huh, that's odd. That was the site's old behavior, right, @Polymega? Before the https work? Weird.

Yes, it is weird. It sounds like their browser is redirecting "https" to "http", for whatever reason. This shouldn't happen unless there's some old cached files in their web browser forcing a wrong redirect.

Even still, the Setup Tool itself doesn't grabs these packages through a web browser, as far as I understand it? So, assuming the issue with the tool here is that it's trying to connect with "http" instead of "https", I don't know why it would do that for just a handful of people but be fine for everyone else.

**Comment by nipkownix** [comment]
Yeah, the Setup Tool doesn't use the browser at all. The tool also doesn't cache anything, so it wouldn't be a cache issue. Since both the tool and the browser are having the same issue, I can only imagine the host is doing some weird redirect for some people, but not for others?

**Comment by mbalc** [comment]
one week ago when I did the report, I later was at my parents' house to set SH2 up there for my dad and the setup went through just fine

I'm using the latest setup tool; right now I used the link you provided to download the tool again (I also get the same MD5 - 54b00d056c1ce967b444e0a2e3db7101), and on my personal computer I'm still getting the error

I tried to open the setup tool via CMD to get some sort of logs out of it, but it doesn't work like that, CMD just starts the .exe in the background and doesn't bind STDOUT to the terminal

maybe it's sth related to my network setup, since it worked fine at my parents' house; here I'm connected to a router with a cable, and that router is connected to yet another, main router - though I never had any issues with that

I don't have any antivirus besides what's the default on my Windows 10

**Comment by nipkownix** [comment]
@mbalc Do these links work for you when you try to download them in a browser?
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip
https://files.townofsilenthill.com/SH2EE/_sh2ee.csv

**Comment by Polymega** [comment]
Are either of your using a VPN? I don't know why that would be an issue, but I'm trying to figure out what the common denominator is here. 

Also, @mbalc, please test out those links nipkow shared right about this post and let us know if they work through a web browser. You might have to Right Click > Save As on the links,

**Comment by ja3h** [comment]
Really sorry, just catching up on this. @Polymega those files downloaded fine and also I'm not using a VPN. 
But with the recent Windows 10 22H2 update I can now use SH2EEsetup perfectly with no errors at all. I randomly tested the tool only yesterday with the same issue as before and have no other system changes in that time so I'm unsure quite what that update did - or if it's specifically what fixed things - but I'm not complaining.

**Comment by Polymega** [comment]
> I randomly tested the tool only yesterday with the same issue as before and have no other system changes in that time so I'm unsure quite what that update did - or if it's specifically what fixed things - but I'm not complaining.

Question: You mentioned you randomly tested the tool yesterday with the same (error) result. Did you perform your test--where it worked--just today then? 

I recently upgraded the site's hosting plan from a shared server to a dedicated server in the hopes of fixing this issue. The thing is, I'm pretty sure the site/files are still in the process of being migrated over to a dedicated server, so I'm not sure if this server change is what fixed the issue... at least not until I know the migration is 100% finished. 🤔

**Comment by ja3h** [comment]
> Question: You mentioned you randomly tested the tool yesterday with the same (error) result. Did you perform your test--where it worked--just today then? 

Yes I did, about 5 minutes before my post. So it could've been exactly as you say which makes more sense because this recent update was pretty light on features.

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

**Comment by filevans** [comment]
this is happening still

**Error: Download Failed

Couldn't download 'webcsv.url'.

The installation cannot continue.

Retry Download?**

**Comment by rekwin** [comment]
Still having this error :((

**Comment by Tominelis** [comment]
Has this become an issue again for anyone else? I have no idea what to do to fix this error and no one else seems to have reported it besides this thread

**Comment by Polymega** [comment]
I am trying to get to the bottom of this issue. Can you try again and let me know if it still happens?

**Comment by filevans** [comment]
@Polymega I tested it last week and it's working ok
