### ISSUE TITLE
Aligning Game Save Text to Bottom Left Corner

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#564]
@TheMachineAmbassador 
I have a potential formula for this. The only thing that bothers me with it is that I don't fully understand _why_ this seems to work. I'd like to understand why, but I'm overall math impaired. See what you think:

**What you will need:**
- [BufferHeight](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/8632c72103f28d319a152525f6bdb0bd554a0d37/Wrappers/d3d8/d3d8wrapper.h#L47)
- [BufferWidth ](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/8632c72103f28d319a152525f6bdb0bd554a0d37/Wrappers/d3d8/d3d8wrapper.h#L47)
- BufferHeight * 1.333333333 = `A` (determines the width if played in 4:3 by using current game height)
- BufferWidth / BufferHeight = `B` (determines current aspect ratio being used)

**Formula:**
( ( (`A` - BufferWidth) * `B` ) / BufferWidth ) * 195 + 20 = Final Value

The only part I don't quite understand is why multiplying by 195 seems to make this work? I just used this number because it "worked," but I don't like using something like this without understanding why it works. But maybe it doesn't matter? 🤷 

PS - Adding the 20 at the very end is to pad the text out from the left (so it isn't touching the edge).

I'm not sure if this formula is 100% fool proof, but it seems to work well even with the most extreme aspect ratios:

![Screenshot 2022-07-11 14-38-05](https://user-images.githubusercontent.com/27395260/178334771-e595cabe-d46c-4a07-8d92-09a61f81e066.png)
![Screenshot 2022-07-11 14-36-51](https://user-images.githubusercontent.com/27395260/178334520-228c8035-3e3e-4f41-9237-5ec430c93a36.png)
![Screenshot 2022-07-11 14-28-15](https://user-images.githubusercontent.com/27395260/178333653-ca32b76b-fde4-4c95-8cdf-5da76c193f72.png)
![Screenshot 2022-07-11 14-29-47](https://user-images.githubusercontent.com/27395260/178333704-87e7a004-beb2-4c5a-b01f-e30f02e5d64e.png)
![Screenshot 2022-07-11 14-30-37](https://user-images.githubusercontent.com/27395260/178333713-ed339247-a966-46ed-91f7-d52b8bf332cd.png)

**Comment by Polymega** [comment]
It looks to be solid! What do you think?

Since you're in this memory region, I have another question to ask:

Is it possible to clear this text if the user quickly presses the quick save button again? This is a vanilla "bug" where this text will overlap itself again and again until each text's timer is finished:

![Screenshot 2022-07-11 17-15-34](https://user-images.githubusercontent.com/27395260/178359757-901155d1-8f67-48f9-ba67-07e48dd72e0c.png)

Aero_ did some adjustments relating to the "Game Saved" text and its timer a while back, so you might be able to look at his work for this (and to ensure it doesn't conflict with the fixes he made): 
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/GameLoad.cpp#L75-L92
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/GameLoad.cpp#L75-L92
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/GameLoad.cpp#L75-L92

^ There may be other areas in this .cpp related to the Quick Save text. What Aero_ fixed here is an issue where if you press Quick Save (which starts its timer) and quickly interacted with something else in the game, the Quick Save timer would kick you out of whatever it was you were interacting with. He also disabled Quick Save during certain animations/events to prevent soft locking.

**Comment by TheMachineAmbassador** [comment]
> It looks to be solid! What do you think?

I think it looks ok for me too.

Well we can add another check at the quick save button event if you want to, kinda like "if interacted with something don't start the save process" but for doing that i have to make a bit research on disassembler.  Also i've noticed when we press quickly before entering last boss room it saves the game out there but also it says "Can't Save" :).

**Comment by Polymega** [comment]
> "if interacted with something don't start the save process" but for doing that i have to make a bit research on disassembler.

I believe this is already done/achieved by Aero_ somewhere in that code I linked. :) With `GameLoadFix`, if a text event is currently being displayed on the screen, the Quick Save feature is disabled until this text event disappears. Basically, the player can only Quick Save when there's no other on-screen text events happening.

> Also we already controlling render text function right now if you want to i can add simple code to there for not printing text more than 1.

Yes! This is what I was asking about! Right now, when you spam the Quick Save button the "GAME SAVED" or "CAN'T SAVE" text will keep stacking on top of each other over and over.

So if a user spams Quick Save, can the _previous_ "GAMED SAVED/CAN'T SAVE" message instantly disappear and the new one be shown? (The idea is to prevent this text stacking on top of each other.)

> Also i've noticed when we press quickly before entering last boss room it saves the game out there but also it says "Can't Save" :).

You always find a way to discover weird things in this game... You're a good playtester! 🤣

**Comment by TheMachineAmbassador** [comment]
Well i found great memory address 0x0932040. If pressed save button that address becomes 1 so i will do something like this "If 00932040 == 1 dont render text".

> You always find a way to discover weird things in this game... You're a good playtester! 🤣

There was much more interesting thing i discovered in this game 😁 but unfortunately i didn't captured them.  While ago I was doing "speedrunning" and trying to find some glitch points in games but I don't think I am better than you when it comes to playtesting you're usually pushing all limits of the game and when it comes to me i just expecting there could've been bug like that.

New build is also ready and i added that check in the code.
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9088361/Release.zip)

**Comment by Polymega** [comment]
Thanks a ton, Machine Ambassador! Could I ask you to test out a theory?

If 0932040 == 1 && 00932038 == 1 {
   Clear rendered Quick Save text
 }

If 0932040 ==0 && 00932038 == 1 {
   Display Quick Save text
}

This probably won't work the way I'm thinking, but I'm hoping it'll clear out the previous Quick Save text so the new Quick Save text can take its place. If you keep spamming Quick Save, the first/original Quick Save message will be the one that stays on the screen. So if you spam Quick Save then enter an area where saving is disabled, it will still say "GAME SAVED" in this area so long as you kept spamming the Quick Save prior to entering the no-save area. 

I'm hoping the pseudo code above will refresh the Quick Save message on each press (without this text overlapping itself). My gut says it won't, but maybe it'll work!

FYI: The d3d8.dll in your package was flagged as a false positive by Windows Defender.

**Comment by TheMachineAmbassador** [comment]
Well did you guys knew 0079b830 this is activates and deactivates quick save stuff. If it's 0 disables the quick save. You wasn't need to disable with patching code because there is a list in the game that specify the don't quick save points :).
![quickly_save](https://user-images.githubusercontent.com/77938614/178517634-85b6c81a-47e0-41de-8ca9-dcb236eb7247.png)

That 0x1dbbf80 means stage, room or something like that.

Well if we came to another issue of ours, I added your theory and the result is below 😁.

[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9094127/Release.zip)

But i guess you want to reverse this, something like after cleared it should render again.

**Comment by Polymega** [comment]
> But i guess you want to reverse this, something like after cleared it should render again.

Yeah, that's what I was going for! 😅

**Comment by TheMachineAmbassador** [comment]
Here it is... I hope it's fixed :)
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9104916/Release.zip)

**Comment by TheMachineAmbassador** [comment]
> Defender is flagging it as a false positive again but this time I can't allow this file to run as an exception. Strange... [Image](https://user-images.githubusercontent.com/27395260/178807606-aad97d3d-dbb4-4795-a4bb-066536609855.png)

I really should do something about it but i don't even know the reason of it :). I copied the code to the safe place and after then re-cloned the repo, let's see will Windows Defender give any false positives again :)

[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9106544/Release.zip)

> I temporarily disabled Defender to test the the build and this looks to be exactly what we want! 🥳 No more text overlapping and the save status instantly updates itself when the user presses the button. Awesome work as always, Machine Ambassador! 🤜🎇🤛

Thank you, without your formula and brain it wouldn't been possible :) I will PR the code after cleaning some useless codes and add support for the other versions of game.  Also i have to make some different variants of your UseCustomExeStr thing because after rewriting code it's gone too but it's easy to implement 

![comparison](https://user-images.githubusercontent.com/77938614/178850446-e4d1c59c-8642-428f-8aa3-633436b03944.png)

Left side is sh2 version 1.0 right side is 1.1, i guess you guys wanted to add missing code in the next building so while we have the rewritten function in our hands I can do it easily without needing the .res file.

**Comment by TheMachineAmbassador** [comment]
> Hmm... the build you just sent is also being flagged as a false positive. The culprit specifically is the d3d8.dll file. Maybe after cleaning the code it will fix this? I can test when the time comes. https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/555#issuecomment-1179797770

I don't think so, it was independent software from sh2ee. I don't understand why Windows gives false positive, maybe it started after last updates on source because i did what i said above, also i don't think this issue might related to new codes that i added. It just same stuff, i set a hook on render function and forwarded that call to my function.

I did a virus scan on virus total and lol even Microsoft says it's not a virus  😂😂😂
https://www.virustotal.com/gui/file/bd427c9eabd17c38c9652f3961c0d8f885813b1619f06de0f5b29e95566f0f1a?nocache=1

> Do you mean your new feature here can be added without modifying the d3d8.res file? We probably need to keep the d3d8.res file as it is used for two main things:

Not a problem we can simply call that hooks in our render function :)

**Comment by Polymega** [comment]
> Also i've noticed when we press quickly before entering last boss room it saves the game out there but also it says "Can't Save" :).

I wonder if we should try and fix this, which would be a new addition to the [`GameLoadFix`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/GameLoad.cpp) feature? (Elisha: _It's back..._ lol). 

In the video below, I press quick save right before entering this room. We have disabled quick saving in this room but I am still able to save it here using this glitch. To make matters worse, it loads `m_card_x_msg_*.mes` into memory and overwrites `stage_apart_e2f_msg_*.mes`. This is why I receive the "Catacomb" text:

https://user-images.githubusercontent.com/27395260/179294058-db94e4bf-f742-4a49-859d-7762679bcc56.mp4

^ Once I receive the "Catacomb" text I am now soft locked here because the game is waiting for me to press an input after acquiring the flashlight but the "Catacomb" text string [doesn't utilize an input press](https://gitlab.com/sh2msgconvert/sh2msgconvert/-/blob/master/ControlCodes.md#wait-altered).

That's one example of how this could break things.

One idea of how this can be prevented is to disable interaction while the quick save text is displayed. I believe `00932038 byte` is triggered when the game is saving to the quick save file. So we could do something like:

if 00932038 == 1
- Disable action/confirm

...now, do we know how to disable action/confirm? It should be fine for the user to still open their map/inventory/etc... we'd just need to disable the action/confirm button while 00932038 == 1.

![Screenshot 2022-07-15 15-11-17](https://user-images.githubusercontent.com/27395260/179295216-1bb8de07-02b3-4f63-813e-2d99bf5e952f.png)

**Comment by Polymega** [comment]
@TheMachineAmbassador 
If we add on to this code to do the following:

if 00932038 == 1
- Disable action/confirm && Disable pulling up the pause menu

It'll also fix this other bug you discovered:

https://user-images.githubusercontent.com/27395260/179297609-12e9b00d-ee67-4db0-a635-e143429603da.mp4

**Comment by TheMachineAmbassador** [comment]
> I wonder if we should try and fix this, which would be a new addition to the [`GameLoadFix`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/GameLoad.cpp) feature? (Elisha: _It's back..._ lol).

> In the video below, I press quick save right before entering this room. We have disabled quick saving in this room but I am still able to save it here using this glitch. To make matters worse, it loads `m_card_x_msg_*.mes` into memory and overwrites `stage_apart_e2f_msg_*.mes`. This is why I receive the "Catacomb" text:
> 
>  2022-07-15.15-00-52-1_1.mp4 
> ^ Once I receive the "Catacomb" text I am now soft locked here because the game is waiting for me to press an input after acquiring the flashlight but the "Catacomb" text string [doesn't utilize an input press]

I knew this :) When you do that on the final stage James and Maria start talking about which way they came.😁 If we came to your question yep we can. I mean it shouldn't be that so hard to fix this in theoretically we can simply add an comparison to where the game checks is player entered or not in the room and we can add our tiny comparison code into the game's quick save function.

![Screenshot 2022-07-12 16-04-19](https://user-images.githubusercontent.com/77938614/179368012-f7fab70f-b315-42d8-8bee-7c02b4abf44f.png)


(https://gitlab.com/sh2msgconvert/sh2msgconvert/-/blob/master/ControlCodes.md#wait-altered).
> 
> That's one example of how this could break things.
> 
> One idea of how this can be prevented is to disable interaction while the game is writing to the quick save file. I believe `00932038 byte` is triggered when the game is saving to the quick save file. So we could do something like:
> 
> if 00932038 == 1
> 
> * Disable action/confirm
> 
> ...now, do we know how to disable action/confirm? It should be fine for the user to still open their map/inventory/etc... we'd just need to disable the action/confirm button while 00932038 == 1.
> 
> ![Screenshot 2022-07-15 15-11-17](https://user-images.githubusercontent.com/27395260/179295216-1bb8de07-02b3-4f63-813e-2d99bf5e952f.png)

Game's key presses are controlled by this 00446690 function but unfortunately as you know controls are constantly working on games so it's hard to track with that but i guess i can find where the action stuffs are controlled in 1 hrs.

**Comment by Polymega** [comment]
> When you do that on the final stage James and Maria start talking about which way they came.😁

"In my restless Motorhome, I see that Hospital 1F Hallway, Lakeside Hotel..."

> theoretically we can simply add an comparison to where the game checks is player entered or not in the room and we can add our tiny comparison code into the game's quick save function.

The good/happy news is if this [pseudo code](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447) can be implemented we wouldn't have to worry about such a check and it would also fix [this other bug you found](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447). 😁

> Game's key presses are controlled by this 00446690 function but unfortunately as you know controls are constantly working on games so it's hard to track with that

Yeah. And the other tricky thing with 00446690 is that action/confirm can be many different values. It can be one value for _just_ pressing action/confirm, another value for moving forward while pressing action/confirm, another value for strafing while pressing action/confirm, etc etc. We'd need to find the "core" instruction for the action/confirm input.

**Comment by TheMachineAmbassador** [comment]
> The good/happy news is if this https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447 can be implemented we wouldn't have to worry about such a check and it would also fix https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447. 😁

And the funny thing is devs actually implemented that thing you said all the time 😂😂

This is can't save
![cant_save](https://user-images.githubusercontent.com/77938614/179374427-aac7fc39-5b59-4327-a603-c0aec8140583.png)

and is the quick saved stuff
![quick_save](https://user-images.githubusercontent.com/77938614/179374434-b7ae6e88-b5c0-4b50-bb87-77abfb34c93e.png)

While i'm looking this source i've discovered there is a else statement on there and that is sets this memory address 0932038 you said me to 0 and after that i tried on game and yes there is no such thing on can't save. I guess devs forgot to add else statement while programming 😂. And as you said me i will add that right now to quick saved stuff.  Also I don't know if you noticed but as you see on the can't save stuff there is a statement, something like (DAT_00932038 == 0)) && (DAT_0093203c == 0)", do you think it's same what you said me above for the overlapping issue

>If 0932040 == 1 && 00932038 == 1 {
>Clear rendered Quick Save text
>}
>
>If 0932040 ==0 && 00932038 == 1 {
>Display Quick Save text
>}

I guess again dev's forgot to add this things to the quick saved things :) i didn't tested if there is a isuue on while were can "quick save" room throught can't "quick save" room but i think there is no issue on there too.

**Comment by Polymega** [comment]
> I mean it shouldn't be that so hard to fix this in theoretically we can simply add an comparison to where the game checks is player entered or not in the room and we can add our tiny comparison code into the game's quick save function.

I just realized the importance of doing a check that way versus doing it this way:

> The good/happy news is if this [pseudo code](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447) can be implemented we wouldn't have to worry about such a check

...because there are several "rooms" throughout the game where James does not enter them via a door. 

Exiting the beginning bathroom... Walking down the stairs from the Observation Deck into the Forest... Going up/down the basement stairs in the Hotel... These parts of the game do not use a door, so adding a check to disable the action/confirm button while 00932038 == 1 wouldn't do any good here.

Although, you could still do the following [to fix this bug](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1185843447):

if 00932038 == 1
- Disable pulling up the pause menu

**Comment by TheMachineAmbassador** [comment]
Hello @Polymega, it's been 1 week i guess since i'm not looking at the project (if github's post timer is correct) and i'm here again. Well we can't tell i'm completely here, you might not see me around here for a few days but don't worry i'm still working on the project :).

If we go back to our little issue, I added a comparison that you said to me to the pause menu's code and it seems it worked.

[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9174474/Release.zip)

Now we have to find a way to disable action button :)  or maybe we can do something like "if fade out is still not over then don't save ..." but first i will try your method as plan A.

**Comment by Polymega** [comment]
> but don't worry i'm still working on the project :).

No worries, friend! There's no priority or rush for this so, please, take your time and enjoy yourself. :)

> If we go back to our little issue, I added a comparison that you said to me to the pause menu's code and it seems it worked.

Nice! Glad that one worked! I will test this out later on. 😊 

> Now we have to find a way to disable action button :) or maybe we can do something like "if fade out is still not over then don't save ..." but first i will try your method as plan A.

Actually, my plan/idea for this won't work. [I explain why here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/564#issuecomment-1188556995), but basically it's because there are certain ways to enter a room that do not require pressing the action button. 

So if it is possible to fix this, it will have to be done through your "if fade out is still not over then don't save ..." method. 

Here is what we know: When a user presses Quick Save:

- 00932038 changes to 1. I assume this means the game is currently writing to the Quick Save save file found in `data\save\Folder 01`
- After 00932038 changes back to 0, 00932040 will change to 1 for a short time. When 00932040 changes to 1, that is when the GAME SAVED text is shown.

Maybe we can use [`TransitionStateAddr`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Patches.h#L199-L201)`(01F7D490)` or [`EventIndexAddr`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Patches.h#L182-L196)`(00932178)` to know when a player has entered a new area? I'm not sure...

...to be honest, trying to fix this might be pretty messy and nasty. If it proves too hard or too time-consuming to do, then please don't worry about it. I don't want you to stress too much over this part.

**Comment by Polymega** [comment]
> If we go back to our little issue, I added a comparison that you said to me to the pause menu's code and it seems it worked.
> 
> [Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9174474/Release.zip)

Unfortunately, it corrupts your save folder if you press Quick Save then quickly press Esc > Save Game/Load Game:

![Screenshot 2022-07-23 18-29-17](https://user-images.githubusercontent.com/27395260/180624986-eabb3574-7e33-42dc-8809-03837516ff03.png)

Now, I was still able to pull up the pause menu while 00932038 == 1. Is this what you meant to happen?

It looks like your fix is doing this:

if 00932038 == 1 && you pull up the pause menu
- Change 00932038 to 0

If you go to Save Game or Load Game when this happens it corrupts the save folder. I think it should be:

if 00932038 == 1
- Prevent the player from pulling up the pause menu entirely

**Comment by TheMachineAmbassador** [comment]
>It looks like your fix is doing this:
>
>if 00932038 == 1 && you pull up the pause menu
>
>Change 00932038 to 0
>If you go to Save Game or Load Game when this happens it corrupts the save folder.

Yep and because of making that value to 0, i guess save process stopped at half and that corrupted save. Well i guess that was expected. I hope you didn't lose your save progress 😅.

> Now, I was still able to pull up the pause menu while 00932038 == 1. Is this the behavior you were intending?

Yeah i just wanted to stop quick save progress if the player pressed pause button while quick save active but obviously it seems that didn't work. In the new build I just prevented the player from pulling up the pause menu.


[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9175369/Release.zip)


> So if it is possible to fix this, it will have to be done through your "if fade out is still not over then don't save ..." method.

This won't work too i guess because if you watch 00932038 address on cheat engine, you don't even need to spam F5 button after you enter a new room if you spammed before and pressed the action button it stores 1 value until player enter new room and save's there automatically. I can make 00932038 to 0 but we saw the results already it just corrupts the save. As you said, even if we block the player pressing the action button until the save process is done we can't do that for specific places. I don't know if there are any "CAN'T SAVE" places in those specific places ? We might doesn't need to care them.

**Comment by Polymega** [comment]
> In the new build I just prevented the player from pulling up the pause menu.

This looks to work good! Thank you

> Also i wonder if Windows Defender still gives any false positive ?

Nope, I haven't received any false positives with the last two test builds you've sent over.

> you don't even need to spam F5 button after you enter a new room if you spammed before and pressed the action button it stores 1 value until player enter new room and save's there automatically. 

Yeah... I've spent the past hour trying to think of ways to make this work and I don't have any ideas. My thought was if 00932038 == 1 && the Transition State or Event Index variable has been triggered, delay the loading of a new Room until 00932038 == 0 again. A problem here is that 00932038 is programmed to hold a value of 1 until the Transition State or Event Index is returned back to normal.

I'll ping @AeroWidescreen on this to see if he's interested in poking around. I know how much Aero_ _looooves_ the Quick Save feature in this game. 😆 

Address I was using and/our found with my recent tests:

- 00932038 byte - When 1, I believe this means it's writing to the Quick Save save file
- 00932040 byte - When 1, displays GAME SAVED/CAN'T SAVE text
- 01F7D490 byte - Fade transition state
- 00932178 byte - Game event index address
- 0093C024 4 bytes (view value as hex) - Changes when a Quick Save is made. I noticed the values changes to 0x0 between room transitions when doing the glitch.
- 0093C027 byte - Changes to 0 when a Quick Save is made

**Comment by AeroWidescreen** [comment]
Yeah, no luck from me this time. 

> I'll ping @AeroWidescreen on this to see if he's interested in poking around. I know how much Aero_ looooves the Quick Save feature in this game. 😆

You joke about it, but I really do think we would be better off removing it. Either that or we just accept that these issues exist; it's not like the console versions have anything better offer. Feels like we're playing whack-o-mole with these bugs.

**Comment by Polymega** [comment]
I really appreciate you trying with this, though. Thank you.

> You joke about it, but I really do think we would be better off removing it.

I'm warming up to this idea. Let me think on it for a while; I really want to weigh the pros and cons first. What I'm talking about—and what I think you're meaning?—is totally disabling quick save/quick load, but keep the manual Esc > Save/Load Game feature? (These final save/load issues are relating to quick save and not manual save anywhere.)

It could be a hierarchy of fixes:
1. A new feature that totally disables quick save/quick load
   - I need to think on this, but this should fix any outstanding softlock issues relating to saving.
2. `GameLoadFix` works as it currently stands.
   - We can include Machine Ambassador's GAME SAVE/CAN'T SAVE position and color fix within this fix or make it its own fix.
3. Disable both of the above.
   - Vanilla saving experience. What speedrunners would use.
