### ISSUE TITLE
Silent Hill 2 with WTF fonts/subtitles

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#565]
I found in some spots of the game, after install all mods with installer.exe, some weird symbols in some subtitles.
Will this have a solution?
![sh2wtf](https://user-images.githubusercontent.com/57973510/178802735-11f0bc8c-4720-4120-96e2-c5d45efe15b0.png)

**Comment by Polymega** [comment]
Redownload these packages and see if that fixes the issue:

![image](https://user-images.githubusercontent.com/27395260/178806556-def26f75-94a1-45f5-9484-c95306c854be.png)
![image](https://user-images.githubusercontent.com/27395260/178806452-24f739e5-2c9a-4642-b366-1423df5125ca.png)

**Comment by ppsalvador** [comment]
Do not work.

**Comment by Polymega** [comment]
Are you using an external translation pack? Such as Brazilian Portuguese?

Also, please attach a copy of your d3d8.log file.

**Comment by ppsalvador** [comment]
Here ->
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9127311/d3d8.log)

**Comment by Polymega** [comment]
I am unsure of the issue. [Following these steps should fix the problem.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/565#issuecomment-1183551781) If you have downloaded and are using an external language pack, such as Brazilian Portuguese, you would likely need to re-download and re-place the files in the game's folder. 

When you update project files, it can overwrite external language packs being used. As a result, you typically need to place the external language files back into the game folder _after_ performing project updates.

**Comment by nikivarvar** [comment]
Had this exact issue, and I can confirm that the translation patches that switch languages around (in my case Russian was in place of English, and English was in place of Spanish) are the culprit and things don't break on vanilla installation. I didn't try re-applying the patch yet, since I was playing in English anyways.
![Screenshot 2022-09-06 20-25-02](https://user-images.githubusercontent.com/9913382/188876961-d0442020-5e8b-4ad4-abc1-7b32be34e38f.png)
![Screenshot 2022-09-07 15-19-13](https://user-images.githubusercontent.com/9913382/188877022-0f2ade07-36fa-48cd-905a-705c5f85163a.png)

**Comment by Polymega** [comment]
Thanks for following up on their behalf. I figured this was the case. I'll close the ticket out.

Languages that require changing the font sheet to accommodate that language's special characters will affect the display of the other language options in the game. That looks to be what happened here and, unfortunately, there's no way around that at this time. 

We're looking into providing fan translation packs on the site  in the future. One of our goals in doing this is to offer some semblance of quality control to help minimize any issues with using custom language packs.

But even still, if the language requires an altered font sheet, it will mess up characters for other languages.
