### ISSUE TITLE
errors: file unavailable. Failed to query one o more components. the installation cannot continue.

### ISSUE THREAD

**Issue by Tonybecks1** [elishacloud/Silent-Hill-2-Enhancements#566]
after starting the installer it comes out "errors: file unavailable. Failed to query one o more components. the installation cannot continue." how can i solve?
I tried to disable antivirus, I changed various installation folders, I downloaded the file several times, restarted the pc several times. but nothing, same problem.

**Comment by Polymega** [comment]
Does this error message happen early on when you try to run the Setup Tool? I ran the tool just a moment ago and didn't receive this message.

**Comment by Tonybecks1** [comment]
appears as soon as the program is started. The program stops for about one minute and this message appears.

**Comment by Tonybecks1** [comment]
i try to re-download now and see what happens

**Comment by Tonybecks1** [comment]
I tried, same problem.

**Comment by Polymega** [comment]
Are you running any antivirus software besides Windows Defender?

**Comment by Tonybecks1** [comment]
none, i even disabled windows defender.

**Comment by Polymega** [comment]
If you're on your home network, can you temporarily disable Windows' firewall to see if that allows you to make a connection to download the files?

![image](https://user-images.githubusercontent.com/27395260/179085604-e279f47f-6537-4140-9c03-d08f67587261.png)

Either way, be sure to re-enable your firewall afterwards.

**Comment by Polymega** [comment]
You may want to try temporarily disabling the public network firewall as well to test. Just remember to re-enable your firewalls after testing.

**Comment by Tonybecks1** [comment]
i have disabled firewalls, there is still the same problem.

**Comment by nipkownix** [comment]
Hmm, If I'm not mistaken, this specific error is shown when the installer is unable to get the file sizes from the server. The initial connection with the server was successful at this point, though, so I believe it might not be related to a firewall.
Would be interesting to see if Tonybecks1 can get a direct connection to the files through a browser, and if their browser can properly detect the file sizes.

**Comment by Tonybecks1** [comment]
so I have to install the files via a browser and not from the application, right?

**Comment by Tonybecks1** [comment]
In this case, where can I get the link?

**Comment by Polymega** [comment]
Try these links:

http://enhanced.townofsilenthill.com/SH2/files/SH2EEsetup.exe
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Enhancements_Module_2.0.2000.0.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Essential_Files_1.2.3.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Image_Enhancement_Pack_1.1.1.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_DSOAL_1.31a.02.zip
http://enhanced.townofsilenthill.com/SH2/files/packages/SH2EE_XInputPlus_4.15.2.zip

**Comment by Tonybecks1** [comment]
i downloaded the files and installed the mods manually, the game works great after 30 minutes of gameplay, thanks very much
