### ISSUE TITLE
Add icon to EXE? 

### ISSUE THREAD

**Issue by Clasurol** [elishacloud/Silent-Hill-2-Enhancements#569]
The game's executable shows up as blank in the taskbar, even when I reshack one in. Is there a way to do so so the game shows it when running, or could this be added in for a future release of the project?

I know this is a really small thing in the grand scheme of things, but you guys have done wonders with this mod, so I'd thought you might be the best to ask. Many thanks for all your amazing work.

**Comment by Polymega** [comment]
A few years back, we embedded the icon into the executable and it caused stability issues with the game. Upon releasing the executable with the icon, we had a lot of people open support tickets seemingly caused by this change. The section within the binary where we added the icon in should be totally safe to do, but for some inexplicable reason, it wasn't.

**Comment by AeroWidescreen** [comment]
> A few years back, we embedded the icon into the executable and it caused stability issues with the game. Upon releasing the executable with the icon, we had a lot of people open support tickets seemingly caused by this change. The section within the binary where we added the icon in should be totally safe to do, but for some inexplicable reason, it wasn't.

I also remember you or someone else getting false positives. Just weird behavior overall.

**Comment by ThirteenAG** [comment]
What about hooking RegisterClassEx? E.g.
https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SplinterCellDoubleAgent.WidescreenFix/dllmain.cpp#L770-L789

**Comment by KaiserZandrich** [comment]
I have a pretty decent ICO that I made for my vanilla SH2DC. I usually keep it in the same folder as my install files so I always hook them after installing. Would not mind sending if that would help in any way.

**Comment by elishacloud** [comment]
> What about hooking RegisterClassEx?

This is exactly what I was thinking about doing.  Thanks for the sample code!  I just need an icon file for this at some point.

**Comment by Polymega** [comment]
There's an icon in the folder by default (`sh2.ico`) but I'm not sure if that one would be satisfactory. I know the icon needs to be a certain size for larger icon displays, and that icon might not be suited for that?

**Comment by elishacloud** [comment]
What does the log file say?

![image](https://user-images.githubusercontent.com/25625456/180102568-0498c764-c126-4e4f-b218-d753a27ccd1a.png)

**Comment by Polymega** [comment]
[Attached.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9155115/d3d8.log) This is what I found in the log: 

```
13108 19:54:17.037 Patching window title...
13108 19:54:17.037 Patching window icon...
```

**Comment by elishacloud** [comment]
Ok, try this one.  I added a bit more logging:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9155194/d3d8.zip)

**Comment by Polymega** [comment]
Hmm... I didn't see any additional logging in this one, but I might have missed it within the file: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9155221/d3d8.log)

**Comment by elishacloud** [comment]
I tried it on Windows 10, Windows 11 and even on Windows XP.  Works every time for me.  The API calls to Windows are all succeeding.  The icon HAS been set.  For some reason in your copy of Windows it does not show the icon even though it has been set.

Try disabling the whiteshader fix and see if you are seeing the white anywhere or if the background still show up as black.  I know this sounds unrelated, but this is in the same API call.

**Comment by Polymega** [comment]
I disabled `WhiteShaderFix` but nothing is showing as white in the game. However, this is because I'm testing on my laptop using an Intel IGP. The white shader problem was only an issue for Nvidia GPUs.

![image](https://user-images.githubusercontent.com/27395260/180108401-9bab4dd1-43ed-4d92-b087-85e0a6b3ecbf.png)

**Comment by elishacloud** [comment]
> However, this is because I'm testing on my laptop using an Intel IGP. The white shader problem was only an issue for Nvidia GPUs.

Any possibility for you to test this on Nvidia?

**Comment by Polymega** [comment]
> Any possibility for you to test this on Nvidia?

Of course. Works with and without `WhiteShaderFix` enabled.

![image](https://user-images.githubusercontent.com/27395260/180109285-eb897b98-66e1-4316-9c22-e6f74280017f.png)

**Comment by elishacloud** [comment]
Your Intel IGP system seems like it might be showing the actual process icon rather than the Window icon.  Maybe there is a setting to change this?

Try this build and see what happens.  I changed the icon in this build to the setup icon, since that is a proper icon with all the officially required layers:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9155479/d3d8.zip)

Also check the Task Manager to see what it shows.  It should look like this:

![image](https://user-images.githubusercontent.com/25625456/180111638-446ccb0b-d62d-4dd9-9e87-a5ae01bbf21f.png)

**Comment by Polymega** [comment]
Unfortunately, still a no-go. 

![image](https://user-images.githubusercontent.com/27395260/180112399-07f32fe4-9fad-4813-bb30-409c03557975.png)

PS - Can I send you a new icon for you to make the appropriate sizes/layers in the near future? (Once this is figured out.)

**Comment by elishacloud** [comment]
BTW: do you have it pinned to the taskbar?  The icon for pinned items are set by the LNK file if you have it pinned to the taskbar.  In that case you can just unpin it from the taskbar to see the new icon.

**Comment by Polymega** [comment]
I do not have it pinned to the taskbar or Start menu.

![image](https://user-images.githubusercontent.com/27395260/180112634-7a2bf0e5-0009-47e9-a8a3-236f4d2ad3d7.png)

**Comment by elishacloud** [comment]
> Unfortunately, still a no-go.

Not true!  My code worked perfectly.  As you can see from the Task Manager the icon is set correctly.  You computer is showing the file icon rather than the Windows icon.  But you can see in the Task Manager that the icon is set correct for the sh2 window.

**Comment by elishacloud** [comment]
Maybe you have a shortcut somewhere else that is overwriting the icon?  Try renaming the sh2pc.exe file and then running it manually.

**Comment by Polymega** [comment]
> Maybe you have a shortcut somewhere else that is overwriting the icon? Try renaming the sh2pc.exe file and then running it manually.

Oh! So it can be a shorcut _anywhere_ on my PC that may be causing this? If so, then there is a very good chance I have a shortcut for this game somewhere...

**Comment by Polymega** [comment]
I did find a shortcut, deleted it, and it did change the icon in the taskbar... but to something else that's not what we're wanting. 😆 

![image](https://user-images.githubusercontent.com/27395260/180113553-829467e6-7126-4e66-9a4f-d0647a3224a7.png)

Ran on a search on my PC and couldn't find any other shortcuts. Can having other `sh2pc.exe` (non-shortcut) files in other directories cause this?

**Comment by elishacloud** [comment]
> Can having other `sh2pc.exe` (non-shortcut) files in other directories cause this?

Not sure.  It could be a registry key also.  Did you try renaming it?

**Comment by elishacloud** [comment]
> Bingo! Renamed binary:

Yeah, something in your computer is overwriting the icon I am specifying.  I don't know how many people will run into this. The things that Windows uses to determine the icon shown is complex and could be hard to troubleshoot.  Anyways, at least the code is working like it should.

**Comment by elishacloud** [comment]
> I did find a shortcut, deleted it, and it did change the icon in the taskbar... but to something else that's not what we're wanting. 😆

BTW: if you put this icon back you might be able to just change the icon in this shortcut to whatever you want and it may show up on the taskbar.

Also, if you search in google for "troubleshooting incorrect icon on taskbar" you can find all kinds of different solutions.  See [here](https://www.google.com/search?q=troubleshooting+incorrect+icon+on+taskbar).  One of them will probably fix your issue, if you want to try and troubleshoot it.

**Comment by Polymega** [comment]
> Also, if you search in google for "troubleshooting incorrect icon on taskbar" you can find all kinds of different solutions. See [here](https://www.google.com/search?q=troubleshooting+incorrect+icon+on+taskbar). One of them will probably fix your issue, if you want to try and troubleshoot it.

Fantastic! I just did the first suggestion [in this article](https://www.makeuseof.com/tag/5-steps-fix-windows-10-taskbar-issues/) (restarting Windows Explorer) and it fixed things up. I now see the icon using regular ole' `sh2pc.exe`. Thanks again, Elisha. 👍

**Comment by elishacloud** [comment]
Ok, great!  Here is the final build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9155838/d3d8.zip)

**Comment by MarioTainaka** [comment]
On Windows 10 Home if you're using a retail install of the PC version the new icon doesn't work like it shows. It shows in the window but not in the taskbar. renaming the exe to something else works

**Comment by MarioTainaka** [comment]
There are so many diffrent variables that can trip this up.. if the shortcut that has the old icon is in the start menu or  on the desktop somewhere it will use the old icon in the taskbar. not even deleting the ico file fixes it. the only way to get this to work is to rename the exe ><

**Comment by MarioTainaka** [comment]
Alright after clean installing the game and the EE again renaming the exe to something like Sh2PCEE is a sure fire way to get the new icon to show in both the taskbar and window. I even re-install without creating shortcuts.

**Comment by elishacloud** [comment]
> if the shortcut that has the old icon is in the start menu or on the desktop somewhere it will use the old icon in the taskbar.

Yes, that is the way Windows works.  Even if we added an icon into the sh2pc.exe binary it would use the shortcut icon over that one.  But that is ok, at least it is showing an icon.  Before it was not showing any icon at all.  Also, we will probably give users the ability to download the icon we are using so they can modify their shortcut to use the same icon as we are using.

At some point I would like to investigate adding an icon back into the binary.  But, other than that, there is not much more we can do here.

**Comment by Clasurol** [comment]
Apologies for the very late reply, I've had no internet for nearly a week. I've tried the recent d3d8 dll that elishacloud and I'm happy to report it works well.

![Screenshot_2](https://user-images.githubusercontent.com/46195405/180621706-c9cf22c7-76d9-4926-ab72-e3447d04ca9f.png)

Many, many thanks to everyone who commented in this thread.
