### ISSUE TITLE
Can't map L2 and R2 buttons

### ISSUE THREAD

**Issue by BetaVersionBY** [elishacloud/Silent-Hill-2-Enhancements#570]
Hi. I'm using ACME USB Wireless PS2-like gamepad and I can't map L2 and R2 buttons in Control Options and they do nothing in the game. L2/R2 buttons works ok in all other games and emulators and i tested gamepad with "wine control joy.cpl" (i'm using Linux) and everything works fine including L2/R2 buttons.

In Controller setting i tried all controller types (Disable, XInput, DirectInput and Alt.).

**Comment by kartur** [comment]
If you are using WINE, did you set the DLL overrides for dinput8.dll and xInput1_3.dll?

**Comment by BetaVersionBY** [comment]
I tried and i even installed xinput through winetricks, but that didn't help.

**Comment by JoonasPitk** [comment]
Setting the two overrides made L2 and R2 work for me when playing the game via Wine :+1:
