### ISSUE TITLE
Footstep Sound Bug

### ISSUE THREAD

**Issue by KaiserZandrich** [elishacloud/Silent-Hill-2-Enhancements#571]
Footsteps sound normal prior to the installation of SH2EE. After installing, footsteps sound almost 100% like the menu click when I move between options; I can only describe it as a ballpoint pen being tapped on a metal/glass table.

**Comment by Polymega** [comment]
> I'm beginning to suspect that I just have a corrupt SH2EE installation or something.

That might be the case. The video example you provided of the audio is something I've never ~~seen~~ heard before. 

Before you start over, try a few things for me:

1. Temporarily remove the `dsound.dll` and `dsoal-aldrv.dll` files. Does this fix the audio issues? If not, you can restore them back into the game's directory.
2. Open the Configuration Tool `SH2EEconfig.exe` and disable the **Audio > Audio > Use custom streaming audio** engine feature. If you do this and keep it disabled, you'll need to run the game on a single core affinity (**Advanced > Performance > Single core affinity**).

**Comment by KaiserZandrich** [comment]
> 

Uninstalling SH2EE brought about the infinite loop sound glitch, which I've not experienced in two complete playthroughs (+/- 12 hours playtime) - I've heard it's common but I've never restricted affinity, and don't recall ever applying a fix over the DVD install (apart from a WS fix).

I suspect something I adjusted, altered or added might have caused SH2EE to bug out, and was removed when I uninstalled SH2EE, bringing in the infinite audio loop glitch.

I'm doing a clean install and carrying my save over to test the sequence vanilla. I'll reinstall SH2EE after that and let you know if that/your suggestions altered anything. A standalone would be great right about now (*cough* #550 *cough*). I'm kidding, let me get on testing and report back.

**Comment by KaiserZandrich** [comment]
> > I'm beginning to suspect that I just have a corrupt SH2EE installation or something.
> 
> That might be the case. The video example you provided of the audio is something I've never ~seen~ heard before.
> 
> Before you start over, try a few things for me:
> 
> 1. Temporarily remove the `dsound.dll` and `dsoal-aldrv.dll` files. Does this fix the audio issues? If not, you can restore them back into the game's directory.
> 2. Open the Configuration Tool `SH2EEconfig.exe` and disable the **Audio > Audio > Use custom streaming audio engine** feature. If you do this and keep it disabled, you'll need to run the game on a single core affinity (**Advanced > Performance > Single core affinity**).

I'm not sure why, but option two "fixed" the issue, but my sound got slightly distorted on one core. I ended up reinstalling as in previous comment, tested vanilla (loop sound bug but everything's normal) and reinstalled SH2EE. So far, everything I noticed previously is gone/remedied.

Since the FMV with Angela didn't play earlier, and dialogue/other sounds were mixed up, I really do believe the culprit was the FMV/audio replacer I installed years ago. I've looked everywhere, but I can't find a backup of the replacer, it might be on another of my HDDs so if I ever find out which one it was specifically, I'll let you know.

The setup as a whole is running great. You folks should really make the 7.1 a selling point because it's honestly better than I remember the vanilla PS sound ever being. I really look forward to this next playthrough thanks to you guys.

**Comment by Polymega** [comment]
> You folks should really make the 7.1 a selling point because it's honestly better than I remember the vanilla PS sound ever being.

Thanks. This is primarily due to the use of DSOAL. SH2 PC's sound effects are saved out as mono, but DSOAL presents them in binaural audio. So what it's doing is it distorts the sounds for the left and right channels of these mono files to create 3D audio. This means that _all_ of SH2 PC's sound effects use 3D audio (when using DSOAL), versus the PS2 version only utilizing S-FORCE (a binaural audio solution) for two dozen sound effects or so. The PS2 version has it's own pluses with audio handling, though.

We do talk about this briefly on the project site: http://enhanced.townofsilenthill.com/SH2/compare.htm#sound

**Comment by KaiserZandrich** [comment]
> > You folks should really make the 7.1 a selling point because it's honestly better than I remember the vanilla PS sound ever being.
> 
> Thanks. This is primarily due to the use of DSOAL. SH2 PC's sound effects are saved out as mono, but DSOAL presents them in binaural audio. So what it's doing is it distorts the sounds for the left and right channels of these mono files to create 3D audio. This means that _all_ of SH2 PC's sound effects use 3D audio (when using DSOAL), versus the PS2 version only utilizing S-FORCE (a binaural audio solution) for two dozen sound effects or so. The PS2 version has it's own pluses with audio handling, though.
> 
> We do talk about this briefly on the project site: http://enhanced.townofsilenthill.com/SH2/compare.htm#sound

That's insane! The distortion works wonderfully - there is so much depth, I love it.

I've noticed a spatial twist to the FMVs, but that might very well just be the FMVs (I do remember them being pretty bad on PS2 and my vanilla install, which is why I originally applied the FMV/audio replacer that messed with SH2EE in this instance). I don't mind the spatial effect at all, though, these FMVs are very tidy.

Going through the boards, it's very clear everyone has poured a hell of a lot of time into this - I'm happy to say your efforts show in-game, there's no doubt.
