### ISSUE TITLE
SH2EE - 60FPS 

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#572]
Normaly silemt hill 2 run at 30FPS but how i can chenge that? to play at 60FPS

**Comment by Polymega** [comment]
You'd add the `FPSLimit = 60` line into the INI file as you've always done.

[Has this issue been resolved?](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/565)
