### ISSUE TITLE
New FMVs are horrible - erased and deformed little details, everything looks "Plastic" and "Artificial" now!

### ISSUE THREAD

**Issue by v00d00m4n** [elishacloud/Silent-Hill-2-Enhancements#573]
I appreciate effort of trying to improve FMVs but it needs to be done with understanding of how it needs to be done right, and whoever did latest update of FMV does not have such understanding nor does that person sharp eye for noticing how this "upgrade" actually downgraded FMV and killed all the little details, considering them as "noise".

Few examples:

https://youtu.be/LylafxQta9w?t=513

Look at Maria eyes and her medallion - in previous pack you can clearly see the iris of Maria eyes and can see details on medallion - now they all gone, eyes and medallion are washed out. 

Chocker also lost little details and they was interpolated and edges was sharpened, same happened to her hairs.

Skin and clothes was polished too much now they looks like they have no detailed texture and like it all made of plastic covered by vaseline.

https://youtu.be/LylafxQta9w?t=521

Now look at James - hairs and skin lost details. Look closely to shadow near his lips, even shadows got screwed - instead of being smoothly fading out, upscaller sharpened edges of shadows and not they have edgy and very unnatural look!

https://youtu.be/LylafxQta9w?t=529

Poor Laura - same mistake with shadows being edge sharpened turned her under nose shadows into mustaches, she is literally a Hittler now! And look at her eyes, her hairs, her skin... this reminds me how all characters of GTA Defective trilogy characters started to look.  Even background behind her while completely blured by DOF effect looks more detailed in original video!

https://youtu.be/LylafxQta9w?t=539

Oh god, what have you done with poor Angela? Did not she suffer enough? In original you can clearly see where her lips ends and face skin begins, it has clear contours, but look at her now - lips are fading out into skin, there is not even clear distinction between upper and lower lip as border between both is blurred as hell. Same with eyes - you can see clear eyes shape in original,  now its blurry mess in "improved" FMV!

https://youtu.be/LylafxQta9w?t=542

Here BEFORE FMV looks most detailed and natural, yes a little MPEG-blocky, but still much better than new FMV pack and during in-game playing it will be interpolated and less noticeable anyway! I dont know who did FMV pack before but that person did much better job, except maybe for compressing videos too much, if that someone still has sources before compression it better to use them and just do almost looseless settings for compression to avoid such compression artefact blocks before even trying to upscaling. 

Do they look like "improved" to you? You just made game more creepy, but not in right way.

All of this is typical mistake of lazy remasters where developers just use first denoise preset they find in software without doing over 9000 trial and error manual tunes of upscaller for each video and just releasing remastered games with whatever upscaler gave at the first try. Im not saying that whole SH2E is lazy remaster, actually its quite opposite, but exactly this FMV "upgrade" was a lazy effort.

Before even releasing it to public it needed to be fine tunned with many many trial and error attempts until best settings found that actually can keep details and improve image. This was not done, thats why i call it lazy. 

And i cant even believe that nobody of whole team noticed, especially someone who advertised and promoted this as improvement in a video? how actually it made everything worse.

Also comparison of interpolated screenshot with non interpolated and pixelated source image felt like "marketing trick" to sell some gimmicks, because those video in game actually never looked that pixelated as they shown in this promo video, as bik video player usually does interpolation of output image.

Denoising and deblocking of FMVs in general is a bad idea, because noise actually there for a reason, if you dont know it helps to avoid color banding and give some granulized details that serve almost like "detail texture" that you can find in some games where noise is applied to original not so detailed texture. 

Also in game noise and FMV noise is not the same. so while in game noise if its very noticeable and has very huge granules can be annoying, FMV noise is usually quite opposite, especially if noise granules are very little and some smarter noise technique applied.

Many game devs also fight color banding in 8 big color per channel by using noise, so instead of removing it completely both from game and FMVs its better to actually apply more smooth and less noticeable noise with smaller granules, also if possible applied only to luma of video without touching chroma or using colored noise for chroma.

SH2 CGI was ahead of its times, but with such a vaselined look it has now it feels more like some from PS1 era CGI and at some places like CGI based on colored geometry without texture mapping.

This whole CGI FMV pack needs to be redone from scratch based on highest quality available original sources with fine tuning and a lot of testing and comparision of every frame of original and resulting video.

And until its properl redone, i suggest to return back previous more detailed pack as default installation option, and remove this plastic abomination FMV pack from servers to avoid confusion.

Sorry if i was harsh in my criticism, but i was absolutely enraged by this false advertising of "improvement" and by fact that  a whole SH2E team did not notice that this FMV looking much worse!

More pixels and less noise does not mean better quality especially when it comes with erasing and deformation of details. Ai upscaler is not some 1 button magic tool that automatically makes everything better, it requires manual fine tunning for every single video file (or even better - for every single dumped frame or set of frames per scene! because each frame may have different lighting and amount of detail) and sometimes manual retouch, and if you dont know what you doing and how to do it right, it will make things looks worse despite higher resolution.

P.S. - I have done this before and at my spare time was making ai upscaled texture pack for SH2 few years ago, but dropped it because lack of tools for properly slicing and merging back atlas textures to prevent doing it manually per texture and because lack of tools to import back higher res texture, and because i was not very happy with Ai results and had no time for manual retouch. So i decide to wait few years until some better Ai algorithms and models will arrive. And back then i also experimented with couple of SH2 FMVs, so i know how exactly this thing should be done and how it can give horrible results if you cant spend a lot of time on manual tweaking (speaking of tweaking - there is an example of good tweaking of settings - Nier Automata 4k FMV pack which can be found on Nexus, author of it did incredible job to fine tune upscaler so well, that 4k FMVs upscaled from 900p look like true native 4k, my eyes barely can spot anything that was made worse, i even wanted to ask him for settings he used, and suggest you do it too or ask same guy to do upscaling of SH2 FMVs as he has sharp eyes and understanding how to set upscaling right!).

And i know with my own experience how time consuming it might be, but if you decided to dedicate your time and to do it not for yourself but for entire community as part of project that aims to improve game and if you advertise it as improvement - you have responsibilities to do it right and to actually improve it, not make it worse! if you cant achieve this goal and dont know how to upscale it right - you better not release half baked results and better step aside from this task and let someone more responsible, sharp-eyed and someone who actually know how to do it right do it instead, even if it will take more time. There are no publishers around that push you to release it at deadline, so there is no rush, we can wait another year or more until its done right!

**Comment by Darthagnon** [comment]
What was the version number of the "last known good" version of the FMV pack?

**Comment by kartur** [comment]
I have to be honest and say I don't see what you mean in your examples. To my eyes there are no details lost in the latest enhanced versions. Just my two cents.

**Comment by PunishedFiddle** [comment]
> What was the version number of the "last known good" version of the FMV pack?
It's 1.5.2 I guess and can be found on web archive I think.

**Comment by elishacloud** [comment]
We're sorry you do not enjoy the FMVs offered.  At this time we are not going to be adjusting the videos further.  As mentioned in the most recent update video, we may revisit the videos again as AI upscale technology further advances.  You can uninstall the new FMVs and just use the original PC FMVs if you like.

**Comment by v00d00m4n** [comment]
If you cant or dont want to fix this issue any time soon, at least make this new pack optional and revert back to previous pack of better visual quality as main one one your site and make this one as experimental option until you revisit it again.

You changed better fmv pack for worse, and saying "we are not going to do anything about it now" and clossing issue is not a good a way to deal with this issue. Please return previous FMV pack!

**Comment by matheusvb3** [comment]
If I may provide an insignificant comment on the new FMVs despite this issue being closed, I noticed that the videotape footage looks a little strange when upscaled, both in the intro sequence and in the videotape scene itself. Maria looks very "doll-like" and the high resolution made it not look like a videotape anymore, since they are normally very blurry, smudgy and full of artifacts (if you don't store them properly at least :P ). On the other hand the scene where James kills Maria is way, way more impactful when upscaled since in the original it was a little too hard to make out what happens since it's so quick. Now that I think about it, it would be pretty cool if the video switched to a higher resolution when James appears since that's supposed to be just an hallucination after all... xD

If I may also comment on the new FMVs, I also noticed that they lost some skin and clothing details (specially Laura) but that doesn't really bother me at all.

**Comment by matheusvb3** [comment]
Two days later and I realized since the issue is closed probably no one will be notified of what I wrote, so I'll mark @elishacloud to make sure it doesn't go unread 🤷

**Comment by Polymega** [comment]
At this time, we will not be revisiting the FMVs. You can refer to Elisha's post here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/573#issuecomment-1211343993

Thanks

**Comment by Darthagnon** [comment]
@v00d00m4n, I have archived the last known good version of the FMVs, v1.5.2 (according to @PunishedFiddle), and have attached a checksum file.

## Mirrors:
- [Archive.org](https://archive.org/details/sh-2-pc-enhanced-fmv-pack-1.5.2)
- [Google Drive](https://drive.google.com/drive/folders/1-BmcN9V4yzeracCRkpq4hdlSOMOtjPlN?usp=sharing)
- Hashes generated by [OpenHashTab](https://github.com/namazso/OpenHashTab/releases): [SH2PC_Enhanced_FMV_Pack_1.5.2.zip.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9550382/SH2PC_Enhanced_FMV_Pack_1.5.2.zip.txt)
