### ISSUE TITLE
Limited resolutions after launching the config tool

### ISSUE THREAD

**Issue by indeedwatson** [elishacloud/Silent-Hill-2-Enhancements#574]
I installed SH2EE on linux with no issues, it was smooth as butter, launched it, worked near perfect (besides the controller being incorrectly mapped, but that's easy enough to fix).

However I was curious about all the options this mod would present, so I launched the config tool. I didn't see anything interesting, so I made no changes at all.

However when I launched the game again (through the game exe, not through the config tool) the game was in 800x600, and going into the options only let me set it to 1280x1024 as the max (my native resolution is 1080p).

I have tried all three display options (fullscreen, windowed, fullscreen windowed) and the option to show all the resolutions in the menu is checked.

On top of that, I'm not able to move with the d-pad, only with the stick. I'm only mentioning this because it's another change that was introduced after launching the config tool, not because it's a real issue.

Launching the game through the config tool only yields a black screen, but I suspect that can be blamed on wine and I don't deem that important, but I'm trying to give as much detail as I can.

d3d8.log: https://paste.xinu.at/yF5Ou/

**Comment by indeedwatson** [comment]
Well I just set up the game through Lutris instead of plain wine, and everything's fixed. Not sure why or how but I ain't complaining.

**Comment by Polymega** [comment]
Glad you got it sorted out. If you run into any other issues you think might be Linux-related I'd recommend posting over at this thread: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/557

^ This thread has several Linux users helping each other out with issues and figuring out the best way to install and get everything working.
