### ISSUE TITLE
Error: Download Failed

### ISSUE THREAD

**Issue by iamag4mer** [elishacloud/Silent-Hill-2-Enhancements#575]
Hello! I just recently found this project and wanted to install it, only to be met with this error

![Capture](https://user-images.githubusercontent.com/30308463/182032444-cfe8cbb2-496f-4eee-8482-19479d609795.PNG)

I've tried to run as admin, but to no avail. Any help would be massively appreciated

**Comment by Polymega** [comment]
Hi there! Sorry for the troubles. I'm currently adding an SSL certificate to the website and have learned the hard way that an SSL with .htaccess redirects used in conjunction with a CDN is self-imploding a lot of things.

If you don't mind, hold off trying to install the project as it might still be a little wonky until I get this 100% sorted out. I'll respond back here once everything is sorted out to let you know when it should be okay to proceed with the downloads.

Thanks

**Comment by iamag4mer** [comment]
Thank you so much for the speedy reply! That probably explains why it was so hard to get into the website to begin with lmao. I'll hold off on installing then

**Comment by Polymega** [comment]
Phew... okay... I think everything is in order now. If you go back to the site using the link below:

http://enhanced.townofsilenthill.com/SH2/
http://www.enhanced.townofsilenthill.com/SH2/

It should automatically redirect you to:

https://enhanced.townofsilenthill.com/SH2/

More importantly, you should be able to run the Setup Tool to install the project files without issue now. 

If you don't mind, after you run the Setup Tool, please let me know if you were able to successfully install everything through it or not. 

Thanks for being patient

**Comment by iamag4mer** [comment]
The installer ran beautifully! Thank you so much for your help

**Comment by Polymega** [comment]
Fantastic! Thanks for letting me know. Looks like everything is in place again. I'll close this ticket out.
