### ISSUE TITLE
Soft Lock after Game Ending

### ISSUE THREAD

**Issue by Clasurol** [elishacloud/Silent-Hill-2-Enhancements#576]
Game soft locked on me after the credits, after beating the game - this is with the latest released version (2.0.2006.0).  Game was completed on Normal difficulty and Normal riddle difficultly. Ending was "Leave".

![Screenshot_5](https://user-images.githubusercontent.com/46195405/183907237-2f861ffa-8b5d-402b-ace1-84cf0458265a.png)

As you can see, James is stuck holding the hunting rifle here. Can't pause nor do I have control - had to ALT+F4 to close the game.

**Comment by Polymega** [comment]
I'm not at home to test at this moment, but can you replicate this every time you initiate the Leave ending? Or did this happen from loading a Game Result save file while in-game?

**Comment by Polymega** [comment]
I received the Leave ending and let everything play through. I was brought back to the main menu like normal afterwards. Are you able to replicate this bug?

**Comment by Clasurol** [comment]
Sorry for the delay in getting back to you - I replayed the game from the last save point I had from that playthrough (just before the two PHs fight) and completed the game, letting all the cut scenes play out. I was unable to reproduce the bug, so I guess it was one time thing?
