### ISSUE TITLE
SH2 Enhanced Edition Runtime Error

### ISSUE THREAD

**Issue by AJuicyOrange** [elishacloud/Silent-Hill-2-Enhancements#578]
When I open the installer and I'm at where I choose a full installation or custom and press next I get a 
Runtime error (at 134:426): 
Failed to check free space. 

I know this doesn't have to do with my computer space as I have plenty and I have no idea what's causing this if it's an issue with the installer or the game itself.

**Comment by Polymega** [comment]
@nipkownix 
My memory is a bit rusty here but has this issue been resolved for the upcoming update to the tool? If so, would we be safe to release a temporary/intermediary version of the tool in the meantime to help people with this issue?

![image](https://user-images.githubusercontent.com/27395260/184950055-efc54587-9f3b-4421-aac3-a41174d9ddd8.png)

**Comment by Polymega** [comment]
@AJuicyOrange 
I believe this error might be happening if you create a new folder _via the Setup Tool_ to install the files. To illustrate:

![image](https://user-images.githubusercontent.com/27395260/184951042-81aff2ba-8b5b-40be-9fbd-e8353b3f3793.png)

Did you create a New Folder through the tool itself when you attempted to install? If so, try creating the folder you want manually on your computer before running the tool, then select that folder as you run the tool.
