### ISSUE TITLE
A way to download with a translation package (including config tool)

### ISSUE THREAD

**Issue by PuggyDoggo** [elishacloud/Silent-Hill-2-Enhancements#579]
Hey, folks.

Not sure if you remember but I finished a translation of the game to PT-BR based on the Enhanced Edition a while ago. Since then, I remember that @Polymega said something about adding translation packages to the project's files. How is that going? I've had time to do some text revisions, so I think the in-game files should be fully done now.

In addition, I'd love to be able to translate the config tool as well. I believe it'd go a long way if Brazilian players (who I've seen playing it on Twitch every now and then) could also adjust the settings in the tools however they want. The same could go for people who speak other languages, too. Would that be possible?

Thanks for all the good work!

**Comment by Polymega** [comment]
Hi Roberto,

I haven't made any headway on the site for a page to include extra language packs yet, but I still have it on my list. 

The next update to the Setup Tool (installer) is planned to have a language selector. This tool's creator, nipkow, is a native Brazilian and he's already made a Brazilian Portuguese language file for this tool.

We also want to include a language option for using the Configuration Tool (launcher), and have both an English and Spanish version prepared for when we can implement a language picker for this tool. Here are the English and Spanish files for the Config Tool if you'd like to make a PTBR version (this would help us out!):

- English: https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config.xml
- Spanish: https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config_es.xml

**Comment by RobertoSAG** [comment]
Oh, that's perfect, thank you!

Once I'm done, should I provide you with a zip file containing the .xml and the translated game files (which include all the .mes files, the texture for the main menu, as well as d3d8.res and language.ini)?

**Comment by Polymega** [comment]
I'm not sure when I'll have the extra language page made for the site (it'll be some time...), but you can include your updated PTBR language pack here if you'd like. ☺️  [Also be sure to update the PTBR link in this table, if necessary.](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Localizations)

Please attach the translated .xml file here by itself once you're finished, as we can use that file in the near future for the next update to the Config Tool.

**Comment by Polymega** [comment]
@RobertoSAG 
Can you remind me what all your PTBR language pack contains? Specifically:

- What language does your pack replace?
- Does it include a translated main menu? (I think I made one for you?)
- Does it use a custom font sheet (`font000.tga`)?

**Comment by Polymega** [comment]
Also, does your pack follow these guidelines? 

- [Save screen color changes](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
- [Save screen character limitations](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)
- [Translating pause menu text](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.aavqhpb7ymz5)

**Comment by RobertoSAG** [comment]
> @RobertoSAG Can you remind me what all your PTBR language pack contains? Specifically:
> 
> * What language does your pack replace?
> * Does it include a translated main menu? (I think I made one for you?)
> * Does it use a custom font sheet (`font000.tga`)?

Hi! It replaces the Italian language, it does have a translated main menu, and it doesn't need a custom font sheet. And yes, it does follow all these guidelines!

**Comment by Polymega** [comment]
Awesome! Thanks for letting me know. I'm starting work on a language pack page for the site. Whenever you have your next round of updates ready, please package them in a ZIP with the root folder being the "sh2e" folder. That way, a user only has to unzip the package and move the contents over into the game folder. So this would be:

```
[FILENAME].zip
- \sh2e\
-- [all files/folders needed for your translation pack]
```

Please keep the XML file for the Config Tool out of your language pack; this will be implemented separately and directly into the Config Tool at some point.

**Comment by RobertoSAG** [comment]
> Awesome! Thanks for letting me know. I'm starting work on a language pack page for the site. Whenever you have your next round of updates ready, please package them in a ZIP with the root folder being the "sh2e" folder. That way, a user only has to unzip the package and move the contents over into the game folder. So this would be:
> 
> ```
> [FILENAME].zip
> - \sh2e\
> -- [all files/folders needed for your translation pack]
> ```
> 
> Please keep the XML file for the Config Tool out of your language pack; this will be implemented separately and directly into the Config Tool at some point.

Would this be okay?

![image](https://user-images.githubusercontent.com/38843453/185258077-f2eca92a-b990-48fe-860d-787ef6728dde.png)

**Comment by Polymega** [comment]
That's perfect!

**Comment by RobertoSAG** [comment]
Great! Once I'm done translating the XML, I'll make one final round of testing just to make sure and upload the ZIP and XML for you.

**Comment by Polymega** [comment]
Thanks so much! For your language pack: Please send me its permanent link address (wherever you decide to host it on) once you have everything finalized. I will use this link for the language pack on the project site.

**Comment by RobertoSAG** [comment]
Will do!

**Comment by Polymega** [comment]
@belek666 
I would like to add your Polish language pack to the site as well. Can you confirm the following for me?

1. What language does your pack replace?
   - If it is English, could you please change it to use a different language?
2. Does it include a translated main menu? (I think I made one for you?)
3. To confirm: I believe your language pack uses a modified `font000.tga` file?
4. Does your language pack also translate/replace any of the fullscreen images?
   - If so, were they modified using the new, high resolution fullscreen images?
5. Does your pack follow these guidelines? 
   - [Save screen color changes](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
   - [Save screen character limitations](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)
   - [Translated pause menu text](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.aavqhpb7ymz5)

If all of this is checked off, may I ask you to please package the files in a ZIP with the root folder being the `sh2e` folder. That way, a user simply has to unzip the package and move the contents from the root folder into the game folder.

The ZIP would need to have all the following placed in the correct directories within the `sh2e` folder:
- `*.mes` files
- a modified `d3d8.res` file
- a modified `start01*.tex` file (if applicable)
- modified `font000.tga` and `fontwdata.bin` files (if applicable)

Lastly, I would need the permanent host link for this package.

**Comment by Polymega** [comment]
Here's an idea of what I'm going for. By the way Roberto, I love the cartoon pug in your profile pictures. 😊

https://user-images.githubusercontent.com/27395260/185273636-85a5d633-b06f-4baa-83d7-c2b13d505c26.mp4

**Comment by IlDucci** [comment]
Looking sweet! Don't forget about me and my other Spanish (the one for Spain) package.

**Comment by Polymega** [comment]
Yeah! Your Spanish ones already included in our main project by default, but I totally forgot we can add your Castilian one in here! 👍

**Comment by RobertoSAG** [comment]
> Here's an idea of what I'm going for. By the way Roberto, I love the cartoon pug in your profile picture. 😊
> 
>  2022-08-17.21-41-52.mp4

That looks amazing! And yes, Bob is the best, haha.

**Comment by Polymega** [comment]
Hi Roberto,

Whenever you're Brazilian Portuguese pack is ready, may I ask you to package it up and send me a link?

Thanks!

**Comment by RobertoSAG** [comment]
> Hi Roberto,
> 
> Whenever your Brazilian Portuguese pack is ready, may I ask you to package it up and send me a link?
> 
> Thanks!

Hi! Will do. Things have been crazy at work, but I've been making progress. As soon as it's done, I'll share it here.
