### ISSUE TITLE
What things can't be helped?

### ISSUE THREAD

**Issue by Bullsquiddy** [elishacloud/Silent-Hill-2-Enhancements#58]
I hope this isn't annoying or rude to ask, but I was curious what aspects of the PC version couldn't be fixed/adjusted to match the PS2 version? At the moment I'm aware that:

- Certain audio tracks (such as bgm_124_0000) can't be looped the way the tracks on the PS2 version are (due to being multiplexed .AIX files), and are partially edited as a result.
- The "search" feature cannot be used while running, like it can in the PS2 version.

**Comment by Polymega** [comment]
Hi @Bullsquiddy , 

> Certain audio tracks (such as bgm_124_0000) can't be looped the way the tracks on the PS2 version are (due to being multiplexed .AIX files), and are partially edited as a result.

That's correct but I wouldn't consider this one to be an issue. Elisha did a fantastic job blending/looping the track(s) given the multiplexed circumstances and still sounds absolutely fantastic. 

> The "search" feature cannot be used while running, like it can in the PS2 version.

Perhaps there's a way to restore the way this works like it does on the console versions but, for now at least, I'd say it's safe to presume that this can't be done. 

As for anything else: Nothing really comes to mind. There seems to be the possibility to improve things elsewhere such as making a 16:9 map, higher res fullscreen images, and possibly the shadows (if we can find the right people(s) for the job).

**Comment by snigelpasta** [comment]
Looks like they figured out the search feature, lol.

**Comment by elishacloud** [comment]
Closing this out.
