### ISSUE TITLE
Cant get the setup working at all

### ISSUE THREAD

**Issue by Fugazi13** [elishacloud/Silent-Hill-2-Enhancements#580]
I made a post about this issue on reddit two days ago but unfortunately never found a solution , some suggested making a post here though , anyways my issue is I originally downloaded the game (fully extracted version) on myabondware , and installed the EE setup aswell , I originally tried opening up the sh2pc file and it kept asking me to put cd1 , then i tried with the EE setup but i kept getting a error (Error files unavailable failed to query for one or more components) , someone suggested to uninstall both then reinstall and do not open the vanilla game at all and just run the setup after installation. 
I tried again without opening up the vanilla game as suggested and I kept getting the same exact error , another commenter suggest it may be my anti virus , which is my default windows defender , so I tried turning off my firewall but with no avail , still the same exact error, any tips please? I've been trying for 2 days

![silenthill2error](https://user-images.githubusercontent.com/111527587/185457564-23017408-4458-4148-8be2-5abb6a99fbde.PNG)

**Comment by Polymega** [comment]
Hi there,
Sorry you're having troubles. To start things off with testing, are you able to access this file?
http://www.enhanced.townofsilenthill.com/SH2/files/_sh2ee.csv

**Comment by Fugazi13** [comment]
> http://www.enhanced.townofsilenthill.com/SH2/files/_sh2ee.csv
unfortunately link doesn't work at all , tried opening in other browser and it wont open at all

**Comment by Polymega** [comment]
If you right click and "Save As" does it give you the option to download it?

**Comment by Fugazi13** [comment]
> If you right click and "Save As" does it give you the option to download it?
if ur talking about the link it made me save it as a excel lmao , and when i open it up it has a bunch of links 
![sh2excel](https://user-images.githubusercontent.com/111527587/185479415-cdbded0b-cd50-4f9b-81e8-2e2f00a9a1a3.PNG)

**Comment by Polymega** [comment]
That's fine. I'm not sure why the tool isn't running for you, and I don't have a solution for you at this time. But as a work-around, you can copy the links in that file, paste them in your web browser, and download them one-by-one. You would do this for the URLs provided in **rows 4-11**. Once you download a package, unzip its contents and move the contents to the main game folder. 

The downside to this approach is that you will have to manually keep track of what version you've downloaded for each package. This is normally tracked by the Setup Tool to make future updating easy, but since you're having trouble with the Setup Tool, that isn't feasible for you at this time.

**Comment by Fugazi13** [comment]
> That's fine. I'm not sure why the tool isn't running for you, and I don't have a solution for you at this time. But as a work-around, you can copy the links in that file, paste them in your web browser, and download them one-by-one. You would do this for the URLs provided in **rows 4-11**. Once you download a package, unzip its contents and move the contents to the main game folder.
> 
> The downside to this approach is that you will have to manually keep track of what version you've downloaded for each package. This is normally tracked by the Setup Tool to make future updating easy, but since you're having trouble with the Setup Tool, that isn't feasible for you at this time.

currently downloading all them rn , am I supposed to extract and unzip them all in the main game folder?

**Comment by Polymega** [comment]
> am I supposed to extract and unzip them all in the main game folder?

Yep. You'll unzip their contents and move them to the game's main folder. You'll do this for each package.

When all's said and done, your game directory will look similar to this: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

**Comment by Fugazi13** [comment]
> > am I supposed to extract and unzip them all in the main game folder?
> 
> Yep. You'll unzip their contents and move them to the game's main folder. You'll do this for each package.
> 
> When all's said and done, your game directory will look similar to this: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

I have this file aswell , i assume I drop this aswell? it has the same name as the original vanilla game , would i replace it with this?
![sh2](https://user-images.githubusercontent.com/111527587/185490146-238123ea-4bde-4552-8ac1-cef5aba02e21.PNG)

**Comment by Polymega** [comment]
Yes, you'd replace your old file with that one. This is the game executable (what you run to play the game) with all the restrictions removed from it.

**Comment by Fugazi13** [comment]
> Yes, you'd replace your old file with that one. This is the game executable (what you run to play the game) with all the restrictions removed from it.

alright I did everything , anything else i should do? everything look alright?
![sh2ee](https://user-images.githubusercontent.com/111527587/185500101-48e29519-bc66-4fe4-9241-b627bc3231c5.PNG)

**Comment by Polymega** [comment]
Not quite. You want your directory to look like this:
https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

Make a new folder named `sh2e` and move **all of your folders** _besides_ the `data` folder into the `sh2e` folder.

**Comment by Fugazi13** [comment]
> Not quite. You want your directory to look like this: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree
> 
> Make a new folder named `sh2e` and move **all of your folders** _besides_ the `data` folder into the `sh2e` folder.

alrighty did all of that , game seems to be working just fine and it looks like everything applied , in the future updates how do i exactly get the newer updated files since the setup wont be able to auto get them

**Comment by Polymega** [comment]
> in the future updates how do i exactly get the newer updated files since the setup wont be able to auto get them

We should hopefully find a solution to your issue with the Setup Tool by that point so you can use the tool to manage downloads/updates.

I'll ping team member @nipkownix to see if he has an idea of why you got that error in the first place.

**Comment by Fugazi13** [comment]
Gotcha well I appreciate all your help and for you being patient , thanks so much for helping me with the issue , btw are the files i downloaded the most up to date fixes for EE?

**Comment by Polymega** [comment]
No problem. Glad we got you going for now. And yes, these are all the latest files.

**Comment by nipkownix** [comment]
> I'll ping team member @nipkownix to see if he has an idea of why you got that error in the first place.

Can't really say for sure, honestly. _Maybe_ their computer is blocking access to non-https links? Might be a firewall thing? We should probably use https in the installer, not that the website supports it, and then re-check if this issue stills persists. The installer did receive some bugfixes since the last release, so we'd be better checking if the issue still exists regardless.

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).
