### ISSUE TITLE
High CPU usage on EE Configuration tool

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#583]
When a new EE configuration utility is launched, the CPU goes crazy. This is clearly visible in the screenshot. Moreover, it is enough not to do anything at all in the utility - the load increases immediately after launch, and doesn't depend on our actions. And of course, it stops when I close the utility window. Maybe it's the operating system issue (I use it on Windows 7), but in any case I think it's abnormal, and I don't understand what the tool can do all this time.

![Screenshot_2022-08-27_051522](https://user-images.githubusercontent.com/1223276/187010528-7ccb6618-0f6c-488a-bda5-ab2baff9683d.png)

**Comment by elishacloud** [comment]
Yeah, its not doing anything, its [just looping](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/d4f76a42e739d8efe7a43882c15e5e46b9007938/Launcher/Launcher.cpp#L238-L245).  Try this version.  It should fix that:  [SH2EEconfig.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9437219/SH2EEconfig.zip)

**Comment by Psycho-A** [comment]
Thanks! It's okay now :)

**Comment by elishacloud** [comment]
Great.  This was fixed in check in: d7ba194f2c6b0651487f234ef114cd9d2b52322b
