### ISSUE TITLE
"Restore brightness selector" option makes game show black screen on loading

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#584]
When we're enabling "Restore brightness selector" checkbox in EE config, the game begins loading much longer, showing a black screen 30-50 seconds before loading logos. If option disabled, game always loads immediately. What could this be related to? This issue appeared on latest EE update only.

**Comment by elishacloud** [comment]
What do your logs look like?  Can you upload logs of the issue?

**Comment by Psycho-A** [comment]
Yes, here's the log. But judging last timestamps, nothing bad happens - just skipped about 40s of time...

```
7256 07:04:48.069 Enabling technique: LiftGammaGain
7256 07:05:26.912 Loading image files for textures ...
```

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9439065/d3d8.log)

**Comment by elishacloud** [comment]
Can you try with the latest [debug build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2006.0) and send us the log file?  I am trying to figure out where the delay comes from.
