### ISSUE TITLE
Manjaro Linux Error: files unavailable. 

### ISSUE THREAD

**Issue by Hunk4TH** [elishacloud/Silent-Hill-2-Enhancements#586]
Hey guys,

I'm having a strange issue that I don't ever recall having in Windows after the new setup tool was released. In Manjaro either by installing via the Lutris script or just copying over my SH2 folder from my Windows drive and then launching from Steam I keep getting that error whenever it says there is an update and I click on yes I get this error (in the screenshot" However if I click on no the game loads up with no problem lol. 
![Screenshot_20220828_194554](https://user-images.githubusercontent.com/2220768/187099733-1f18f000-6f39-4774-9a4d-c69113b13578.png)
Ignore the Steam Deck menu icon I'm using a Steam Deck theme for Plasma not on an actual Steam Deck.

Any help would be awesome! :)

**Comment by Polymega** [comment]
Sorry you're having troubles. I have asked our developer of the installer to make a test build for you to try and see if it resolves this issue. Once it's built, we will send you the installer to test. Please allow us some time to get this prepared.

**Comment by Polymega** [comment]
Can you try this update to the installer and see if you still receive the error message?
https://files.townofsilenthill.com/SH2EE/testbuild/SH2EEsetup.exe

I've just submitted it to Windows Defender for clearance, but that'll take a few hours/a day or two, so it might trigger a false positive in the meantime via Defender.

**Comment by Polymega** [comment]
This issue should now be resolved. Please re-download the Setup Tool from the project's website: [https://enhanced.townofsilenthill.com/SH2/install.htm](https://t.co/c54fqF7dVX)

If you are still experiencing this issue, please re-open this ticket for us to further troubleshoot.

**Comment by Hunk4TH** [comment]
That worked for me! Thanks so much! :)
