### ISSUE TITLE
Error: Files unavailable

### ISSUE THREAD

**Issue by normandy247** [elishacloud/Silent-Hill-2-Enhancements#587]
Error: Files unavailable
Failed to query for one or more components. 
![image](https://user-images.githubusercontent.com/112361754/187109199-5b809319-e893-4051-aeea-71a648ad9532.png)

My firewalls are all off, and i allowed setup tool in defender.

![image](https://user-images.githubusercontent.com/112361754/187109229-78165bce-f3aa-41f0-a3d0-b2016954fbbd.png)

I tried to go to the links shown in issue " Cant get the setup working at all #580 ", but i get sent to a 404 page.
These links;

![image](https://user-images.githubusercontent.com/112361754/187109365-8f849217-21c0-4056-a6af-5263d142fa82.png)

![image](https://user-images.githubusercontent.com/112361754/187109613-843089ee-6d4b-4e79-a482-18dc37823ed1.png)

**Comment by Polymega** [comment]
Can you try this update to the installer and see if you still receive the error message?
https://files.townofsilenthill.com/SH2EE/testbuild/SH2EEsetup.exe

I've just submitted it to Windows Defender for clearance, but that'll take a few hours/a day or two, so it might trigger a false positive in the meantime via Defender.

**Comment by evanbones** [comment]
Looks like that one works fine, I had the same issue. Thanks!

**Comment by m-rzb** [comment]
> Can you try this update to the installer and see if you still receive the error message? https://files.townofsilenthill.com/SH2EE/testbuild/SH2EEsetup.exe
> 
> I've just submitted it to Windows Defender for clearance, but that'll take a few hours/a day or two, so it might trigger a false positive in the meantime via Defender.

This installer fixed the issue for me as well. I was able to install on steamdeck. it probably should work for #586 as well.

**Comment by Polymega** [comment]
This issue should now be resolved. Please re-download the Setup Tool from the project's website: [https://enhanced.townofsilenthill.com/SH2/install.htm](https://t.co/c54fqF7dVX)

If you are still experiencing this issue, please re-open this ticket for us to further troubleshoot.
