### ISSUE TITLE
SH2 Enhanced Edition - Crashing upon entering new area's 

### ISSUE THREAD

**Issue by YungYajirobe** [elishacloud/Silent-Hill-2-Enhancements#591]
Hello, Any advice on game crashing (freezing & programme not responding) when entering new areas? Game is running very smooth no other issues to report. however, this just happened to me in the blue creek apartments level when leaving the 3rd floor to enter the hallway / foyer stairwell. 

PS Unable to drag / drop d3d8 file so copy + pasted contents below. 

5188 21:02:59.261 Starting Silent Hill 2 Enhancements! v1.5.1700.0
5188 21:02:59.261 MSI MS-7917 1.0 (Desktop)
5188 21:02:59.261 MSI Z97 GAMING 5 (MS-7917) 1.0 (Desktop)
5188 21:02:59.261 "AMD Radeon (TM) R9 390 Series"
5188 21:02:59.262 Windows 10 Home 64-bit (10.0.18362)
5188 21:02:59.262 "sh2pc.exe" (PID:5844)
5188 21:02:59.262 Game binary version: Director's Cut
5188 21:02:59.281 Running from: "C:\Users\Corey\Downloads\Silent.Hill.2.Enhanced.Edition\Silent.Hill.2.Enhanced.Edition\Silent.Hill.2.Enhanced.Edition\sh2pc.exe"
5188 21:02:59.281 Config file: "C:\Users\Corey\Downloads\Silent.Hill.2.Enhanced.Edition\Silent.Hill.2.Enhanced.Edition\Silent.Hill.2.Enhanced.Edition\d3d8.ini"
5188 21:02:59.281 Loading as dll: "d3d8.dll"
5188 21:02:59.284 Wrapper created for "d3d8.dll"
5188 21:02:59.286 Hooking the FileSystem APIs...
5188 21:02:59.387 Hooking the CreateProcess APIs...
5188 21:02:59.387 Bypassing CD check...
5188 21:02:59.387 CheckMemoryAddress Error: memory address not found!
5188 21:02:59.387 Patching binary...
5188 21:02:59.387 Finding SFX file locations...
5188 21:02:59.475 Updating SFX memory address locations...
5188 21:02:59.475 Allocating memory buffer for sddata.bin file...
5188 21:02:59.487 Updating Texture memory address locations...
5188 21:02:59.488 Setting 2TB hard disk Fix...
5188 21:02:59.488 Setting PS2 Style Noise Filter...
5188 21:02:59.488 Increasing the Draw Distance...
5188 21:02:59.488 Setting Cemetery Lighting Fix...
5188 21:02:59.488 Fixing tree lighting conditions...
5188 21:02:59.488 Setting Rowboat Animation Fix...
5188 21:02:59.506 Updating the Catacomb Meat Cold Rooms color...
5188 21:02:59.506 Updating Fog Parameters...
5188 21:02:59.506 Setting Piston Position Fix...
5188 21:02:59.506 Setting Hotel Room 312 Shadow Flicker Fix...
5188 21:02:59.506 Hiding Red Cross health indicator during cutscenes...
5188 21:02:59.506 Enabling PS2 Flashlight Fix...
5188 21:02:59.506 Fixing behavior of Lying Figures that are hiding under vehicles...
5188 21:02:59.506 Add fix to prevent chainsaw from spawning on first playthrough...
5188 21:02:59.506 Enabling XInput Vibration Fix...
5188 21:02:59.539 Enabling Custom Fonts...
5188 21:02:59.540 Enabling Custom Exe Strings...
5188 21:02:59.540 Enabling post Processing Special FX...
5188 21:02:59.540 Enabling Town West Gate Event Fix...
5188 21:02:59.540 Enabling Screen Position option lock...
5188 21:02:59.540 Enabling Best Graphics settings...
5188 21:02:59.543 Loading the "Nemesis2000 Fog Fix" module...
5188 21:03:00.503 Loading the "WidescreenFixesPack" module...
5188 21:03:00.827 Silent Hill 2 Enhancements module loaded!
5188 21:03:00.886 CheckForAdminAccess Checking if administrator access is required.
5188 21:03:00.942 Starting D3d8to9 v1.11.0.0
5188 21:03:00.942 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
5188 21:03:01.067 Enabling Resolution Lock...
5188 21:03:01.067 Setting Hotel Room 312 Resolution Fix...
5188 21:03:01.734 Setting Hotel Water Fix...
5188 21:03:01.734 Setting RPT Apartment Closet Cutscene Fix...
5188 21:03:01.734 Setting RPT Hospital Elevator Animation Fix...
5188 21:03:01.734 Fixing Esc while transition is active...
5188 21:03:01.734 Setting infinite rumble window hook...
5188 21:03:01.734 Enabling Lighting Transition Fix...
5188 21:03:01.734 Enabling Load Game Fix...
5188 21:03:01.734 Enabling Blood Size Fix...
5188 21:03:01.734 Fixing the rotating Mannequin glitch...
10696 21:03:05.964 Setting SingleCoreAffinity...
5188 21:03:09.662 GetDiskSpace Available disk space smaller than 2TBs: 740672028

**Comment by Polymega** [comment]
Hello,

Typically, if the game is consistently crashing in the same spot/area this usually means the download of the base (vanilla) game was bad or an error occurred while installing the EE project files.

Looking at your log file, you are also using a fairly old build of the project. (The current build for the SH2E module is 2.0.2006.0). My recommendation:

- Make a backup of your `SILENT HILL 2\data\save\Folder 01\` files. This will backup your save files.
- Delete your SILENT HILL 2 game folder.
- Download the "Fully Extracted Version" of Silent Hill 2 found [here](https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download).
   - Extract the contents to a new SILENT HILL 2 folder
- Download our project's Setup Tool found [here](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE). This is an installer for the project.
   - Follow the Setup Tool's instructions to install the project
- Move your backup save files back into `SILENT HILL 2\data\save\Folder 01\`.
