### ISSUE TITLE
Silent Hill System Error

### ISSUE THREAD

**Issue by h9qi** [elishacloud/Silent-Hill-2-Enhancements#593]
![image](https://user-images.githubusercontent.com/112734801/188245947-a88ae5ba-4f92-49b0-83a5-3d44b9933e4d.png)

![image](https://user-images.githubusercontent.com/112734801/188245954-6ad4184e-8e8f-444a-9d90-51547a9c4768.png)

**Comment by elishacloud** [comment]
Try unzipping these files into the Silent Hill 2 folder:  [msvcr70.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9481511/msvcr70.zip)

**Comment by h9qi** [comment]
> Try unzipping these files into the Silent Hill 2 folder: [msvcr70.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9481511/msvcr70.zip)

I tryed

**Comment by Polymega** [comment]
Can you please take a screenshot of the game's folder?

**Comment by h9qi** [comment]
> Can you please take a screenshot of the game's folder?

![image](https://user-images.githubusercontent.com/112734801/188247494-b8ded90e-15fd-42f8-a28c-19e549af5675.png)

**Comment by Polymega** [comment]
Thank you. What happened is you downloaded our project without downloading Silent Hill 2 PC.

Our project requires you to have Silent Hill 2 PC installed in order to work. Here's what you can do:

- Download the "fully extracted" version of Silent Hill 2 PC from here: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download
- Once downloaded, extract all of its files to your game folder.

If you do this, everything should then work.

**Comment by Polymega** [comment]
Oh, one important note: Before you do this, make a backup of your `sh2pc.exe` file from the game folder.

After you download Silent Hill PC and move all of its files to this folder, move your backup `sh2pc.exe` file back into this folder.

The `sh2pc.exe` file provided with Silent Hill 2 PC will not work. You will need to use our `sh2pc.exe` file.

**Comment by h9qi** [comment]
> Oh, one important note: Before you do this, make a backup of your `sh2pc.exe` file from the game folder.
> 
> After you download Silent Hill PC and move all of its files to this folder, move your backup `sh2pc.exe` file back into this folder.
> 
> The `sh2pc.exe` file provided with Silent Hill 2 PC will not work. You will need to use our `sh2pc.exe` file.

Okay Thank u 🙂

**Comment by Polymega** [comment]
Closing ticket out. Feel free to re-open, if need be.
