### ISSUE TITLE
Clipping pyramid in a closet scene

### ISSUE THREAD

**Issue by SiarMortal** [elishacloud/Silent-Hill-2-Enhancements#596]
Hello. So in a scene where James hides in a closet from PH, there's a pretty bad clipping going on with the pyramid and PH's shoulder.
https://www.youtube.com/watch?v=Lrt-5Xq4cD0
can be seen at around 2:04 and later.
Is there a way for you to fix it?

**Comment by Polymega** [comment]
Unfortunately there isn't. Animation files (.anm) have not been researched enough to be able to comfortably edit their contents. I'm also unsure if an editing tool exists out there to edit/handle SH2's .anm files.
