### ISSUE TITLE
weird palette on a texture - tex

### ISSUE THREAD

**Issue by OAleex** [elishacloud/Silent-Hill-2-Enhancements#598]
Hi, folks! First of all thanks for this great and dedicated project!

I'm looking at some textures for translation, and there's a specific one that's breaking my head, it's the "start01i.tex" texture, I tried to use the Silent Hill texture explorer to have a resolution base and RAWTEXT to extract, and, after extract it, the [palette](https://prnt.sc/e-r4--1XYJXC) doesn't come correctly, which is strange because I haven't had a similar problem with other textures. Did you use any other tool to make this edit?

Any information, tools and tips would help me a lot! Thanks!

[start01i.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9539532/start01i.zip)

**Comment by Polymega** [comment]
We changed this texture's format from DXT3 to 8.8.8.8 ARGB 32 bpp to give the "glow" effect around the letters the silkiest smooth gradients possible. I don't believe SH Texture Explorer is equipped to handle 8.8.8.8 ARGB 32 bpp, which is likely the problem.

I can assist you with creating this texture in a new language. What language are you translating to? We want to host fan translation packs on the project site in the future and, if you have a language that hasn't already been translated, we might be interested in hosting your work once finished.

We're discussing how our project can better support/handle fan translation packs. We haven't finalized the new method/format in how we'll support them just yet, but if you can wait until we get all of this finalized I can assist you in making sure you have all the translated files needed to support SH2:EE.

For start01.tex, I'd need the following translated from you:

```
LOAD
CONTINUE
NEW GAME
OPTIONS
MOVIES
EXIT
ACTION LEVEL
RIDDLE LEVEL
HARD
NORMAL
EASY
BEGINNER
Main Scenario: LETTER FROM SILENT HEAVEN
Sub Scenario: BORN FROM A WISH
```

**Comment by Polymega** [comment]
PS - I see in your GitHub profile you're from Brazil? Someone has already made a Brazilian Portuguese translation pack for the project, in case that's what you're wanting to translate the game to. I can try and find the link to that later on.

**Comment by OAleex** [comment]
Thanks for the answer!
Yes, there are several versions of Portuguese (Brazillian and European) in this specific version, me and Big Boss are working together to respect the fidelity of the game bringing a translation from Brazilian Portuguese.
About the project's situation, it's a project that's already ready, all that's missing is this texture and one more review to get everything ready.

Translation:
```
CARREGAR
CONTINUAR
NOVO JOGO
OPÇÕES
CENAS
SAIR
NÍVEL DA AÇÃO
NÍVEL DOS ENIGMAS
DIFÍCIL
NORMAL
FÁCIL
INICIANTE
Cenário Principal: Carta do Paraíso Silencioso
Cenário Secundário: Nascida de Um Desejo
```

**Comment by Polymega** [comment]
I have this ready for you except for one needed adjustment. The "main scenario" title is a bit too long and the glow around the lettering is getting cut off at the end:

![image](https://user-images.githubusercontent.com/27395260/189537838-96c7d6a7-6759-425d-af54-5b07a0ea623e.png)

Are you able to shorten this line? Here is what the "hit boxes" look like for these strings:

![image](https://user-images.githubusercontent.com/27395260/189537901-78e8aff8-c3fb-458f-bf43-723d51213d6c.png)

**Comment by Polymega** [comment]
Here is start01.text translated. The "main scenario" text has a _tiny_ bit of the glow chopped off on each end. This is due to the string being long and almost touching the boundaries of the "hit boxes."

[start01_ptbr.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9543045/start01_ptbr.zip)

**Comment by lucazandrade** [comment]
Hi, thank you for your attention, and the entire Enhanced Edition team for presenting us with the definitive version of this timeless classic!

I am in charge of reviewing this translation project, which consists of translating the game for the best and most faithful experience possible into the language of my country, with special attention to the rules of our language, respecting as much as possible the originality, and the great Team Silent's work with this great work, and also with great affection for this incredible version that you guys made.

Thank you so much for that, for helping us!!!

**Comment by Polymega** [comment]
Glad we could help!
