### ISSUE TITLE
Worked last year, now doesn't work at all.

### ISSUE THREAD

**Issue by JJOldaker** [elishacloud/Silent-Hill-2-Enhancements#599]
Last year I installed all the enhancements and everything and really enjoyed playing a bit during Halloween time but I quit playing til last week when I thought I'd see what had changed with the enhancements. Obviously now it's very much automated and after updating I get nothing, the EXE file seems to crash immediately and I have no idea why. I backed up the entire game last year to a disk and even last year's version also seems to crash immediately now on my current setup. Renaming the d3d8.dll to another name gets the game to run albeit just the original game with no enhancements. Here's the attached d3d8.log:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9561459/d3d8.log)
I'm running the latest Windows 10 on a Ryzen 5 2600X with an AMD RX580 video card. The funny thing is I copied it exactly as it is now with the latest enhancements to my fiancee's old AIO PC with an I3 3220 and no graphics card and the game ran flawlessly albeit probably at 15 frames per second!!
I am not sure what else to try as it gives no errors whatsoever, just never comes up.

**Comment by Polymega** [comment]
Sorry you're having issues. Can you also share a snapshot of the contents inside the game's main folder?

**Comment by JJOldaker** [comment]
![image](https://user-images.githubusercontent.com/109631449/190032058-90968544-09c9-48f2-82e2-6124d7118274.png)
![image](https://user-images.githubusercontent.com/109631449/190032082-1bc0baec-f242-45c2-9b70-cc18bace41ac.png)

**Comment by Polymega** [comment]
Thanks. Our project has changed quite a bit over the years, including dropping older supplemental software in favor of newer ones. Back before our installer, you'd have to keep up with project updates to know which files to remove before downloading/using the newer packages we provide. Since it's been a while since you've last updated the project, it looks like the newer supplemental software is conflicting with the older software.

[You want your directory to look something like this.](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree) Remove these files/folders from the directory and see if that fixes things:

```
\reshade-shaders\
d3d8.dat
d3d8.dll.deleteonnextlaunch
d3d9.dll
d3d9.ini
d3d9.log
DefaultPreset.ini
dsound.ini
dsound.log
dxgi.log
ReShade Filter - SH2 PC PS2.ini
ReShade.ini
ReShade.log
ReShade_sh2pc.ini
sh2_affinity_shortcut.exe
sh2pc.2
sh2pc.bak
Squizy_Silent_Hill_2_Resolution_v1.0.exe
```

**Comment by JJOldaker** [comment]
The same exact result with those files deleted.

**Comment by Polymega** [comment]
`d3d8.cfg` is created by our project upon first launch of the game with using our project. If you rename `sh2pc.exe` to something else, such as `sh2.exe`, does it launch then? If not, you can change its name back to `sh2pc.exe`.

**Comment by JJOldaker** [comment]
No, seems to have the same result no matter what the name.

**Comment by Polymega** [comment]
Okay, we may need to get @elishacloud's input on this when he's available.

**Comment by elishacloud** [comment]
@JJOldaker, can you try disabling the shaders and see if that helps.  If not can you upload a new log file?

**Comment by JJOldaker** [comment]
If you mean setting all the shader options to 0 in the d3d8.ini and trying I did that and no change.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9580693/d3d8.log)

**Comment by elishacloud** [comment]
What is the date on that log?  It is not complete.  The game has not even started.

Try disabling the "Admin privilege checker".

![image](https://user-images.githubusercontent.com/25625456/190557060-adfceb2e-0c9b-41d4-b112-1a66a5f35bc5.png)

**Comment by JJOldaker** [comment]
Seemed to take longer to crash though the same result in the end. Log file is a lot longer this time.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9581404/d3d8.log)

**Comment by elishacloud** [comment]
I noticed there is a missing `SH2EEsetup.dat` file in this folder.  This means that the setup tool did not run for this folder.  Can you try running it again and reinstalling everything in this folder?

**Comment by JJOldaker** [comment]
Okay reran the setup as you suggested and it still didn't run. I noticed the log file was now very short again (stopping at the compat layer part) so went back in and again disabled the admin privilege checker. Tried running the game again, but did not work. This time though the log file is a little different I think:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9585811/d3d8.log)

**Comment by Polymega** [comment]
> This time though the log file is a little different I think:

The next step in the log would be `Hooking the FileSystem APIs...`

I have a totally random thing for you to try. _Temporarily_ remove `dsound.dll` and `dsoal-aldrv.dll` from the game's directory. Does it launch for you then? If not, you can place those files back in the game's directory.

**Comment by JJOldaker** [comment]
No, it didn't launch, basically the same result.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9586219/d3d8.log)

**Comment by elishacloud** [comment]
Ok, I added some additional logging so we can see where it is failing.  Can you use this file, just unzip it into the game folder and they try running the game again and send us the log file.

With additional logging:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9586391/d3d8.zip)

**Comment by JJOldaker** [comment]
I'm so sorry I didn't get the usual email that there was a reply. I just happened to come back here on a whim to make sure there wasn't a reply. I will try this later as I am working right now and as soon as I do I will reply again probably later tonight.

**Comment by JJOldaker** [comment]
Okay got off work really early so got a chance to run it. Here's the log file:

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9629719/d3d8.log)

**Comment by elishacloud** [comment]
This is weird.  Try disabling the following options:

* AutoUpdateModule
* RestoreVibration

**Comment by JJOldaker** [comment]
No change but here's the new log file.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9629836/d3d8.log)

**Comment by elishacloud** [comment]
It looks like the module is fully loading now.  Can you check if the game works without the module?  Try renaming `d3d8.dll` to something else to see if the game works correctly on its own.

**Comment by JJOldaker** [comment]
Yes, the game does run with that file renamed but it's I think the vanilla game that way.

**Comment by elishacloud** [comment]
Ok, then we will need to figure out which option in the module is causing the issue.

Try this update.  Everything is disabled here:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630064/d3d8.zip)

**Comment by JJOldaker** [comment]
UseCustomModFolder = 0 is the problem. Setting this to 0 causes the game to not run.

**Comment by elishacloud** [comment]
Maybe there is something unexpected in the sh2e folder.  Can you try setting `UseCustomModFolder = 1` and renaming the `sh2e` folder?

**Comment by Polymega** [comment]
Can you rename the `sh2e` to something random, then create a new `sh2e` which is empty, and set `UseCustomModFolder = 1` to see if that works?

**Comment by JJOldaker** [comment]
Neither of those options work. It won't run when that setting is at 1 with the folder gone or empty.

**Comment by elishacloud** [comment]
Ok, I see.  Can you try with the attached debug build and upload the log files for me?

Debug build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630286/d3d8.zip)

**Comment by JJOldaker** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630315/d3d8.log)
 The game did load with those 2 files though.

**Comment by elishacloud** [comment]
Sorry, maybe I sent you the wrong build on accident.  Can you try again with this debug build?

Debug build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630336/d3d8.zip)

**Comment by JJOldaker** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630339/d3d8.log)
Here it is, didn't run this time.

**Comment by elishacloud** [comment]
Thanks for your help.  Hopefully we are getting closer to isolating the issue.  Can you try with this build and upload the logs:

New debug build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630389/d3d8.zip)

**Comment by JJOldaker** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9630680/d3d8.log)

**Comment by elishacloud** [comment]
I am experimenting with a new way to hook for the `UseCustomModFolder` feature.  Can you try with the update below?

Test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9691717/d3d8.zip)

**Comment by JJOldaker** [comment]
Well it didn't run but here is the log:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9691764/d3d8.log)

**Comment by elishacloud** [comment]
Something went wrong.  That log is not from the build I gave you.  Please try again with this build here:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9691717/d3d8.zip)

Just unzip these files directly into the Silent Hill 2 folder overwriting the existing dll and ini files.

**Comment by JJOldaker** [comment]
Okay, that's what I did last time or so I thought. With these, the game ran and it looked like it was running correctly. It's late and I will double-check it sometime later today but here's the log from the run:

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9691827/d3d8.log)

**Comment by elishacloud** [comment]
Ok, great.  We have not fully tested it yet, but you can go ahead and use this with the game.  Make sure to put the `sh2e` folder and other files back so you can get the full experience of the game.

**Comment by Polymega** [comment]
Hi Elisha,

Got your email and starting to do some tests now. I found one issue right out the gate, and that's the module is not pulling movies from \sh2e\movie\. It is instead pulling from \data\movie\.

I'll either update this post or make new replies here if/when I come across other things.

Thanks!

**Comment by elishacloud** [comment]
> the module is not pulling movies from \sh2e\movie. It is instead pulling from \data\movie.

Ok, movies should work correctly now.

Here is the testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9700251/d3d8.zip)

**Comment by Polymega** [comment]
Thanks! FMV scaling for [FullscreenVideos](https://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenVideos) doesn't appear to be working now.

### Correct
![sh2pc 2022-10-03 16-35-29](https://user-images.githubusercontent.com/27395260/193677425-de2cad36-e572-4ac4-89b0-b426a632d75e.png)

### Incorrect
![sh2pc 2022-10-03 16-34-58](https://user-images.githubusercontent.com/27395260/193677442-03c64d44-3da6-4999-84ad-bcc851178f15.png)

----------------

Unrelated to the new hooking method but something I noticed a long time ago but keep forgetting to mention:

Certain game resolutions will noticeably misalign the soft shadow layer. I figure this is when using "unusual" resolution that may divide into some formula a bit weird. Check out the shadow around James' feet:

### 1600x900 (correct)
![sh2pc 2022-10-03 16-40-57](https://user-images.githubusercontent.com/27395260/193678508-ca5d33b1-9572-4bae-aa6c-b4542538b6eb.png)

### 1360x768 (incorrect)
![sh2pc 2022-10-03 16-40-47](https://user-images.githubusercontent.com/27395260/193678564-557654b3-8dbc-4e62-b03d-a4e109905c2e.png)

Not sure if anything can be done for this, but figured I'd bring it to your attention.

**Comment by elishacloud** [comment]
> FMV scaling for [FullscreenVideos](https://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenVideos) doesn't appear to be working quite right now.

Oops.  One little mistake.  Try this one:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip)

> Certain game resolutions will noticeably misalign the soft shadow layer. I figure this is when using "unusual" resolutions that may divide into the shadow scaling formula a bit weird.

We should try to fix this separately.

**Comment by Polymega** [comment]
Yep, that looks to have fixed it. Thank you, Elisha!

**Comment by JJOldaker** [comment]
Seems to be working just fine for me now. Thanks!

**Comment by Polymega** [comment]
We believe the reason for these seemingly random (but consistent) freezes and crashes might be due to a Windows update conflicting with how our project hooks itself into the game and/or Windows files. We've just released a new build that uses an entirely new hooking method which should fix the issues you were experiencing. 

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks

**Comment by JJOldaker** [comment]
Updated to the new release and played the game for about an hour so it seems good to me. No issues.
