### ISSUE TITLE
Blue Creek Apt. Room 105 - Some geometry's normals reversed/non-conformed?

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#6]
# ap76.map 

@Bigmanjapan if you're up to the task I'd like to keep giving you some challenges. There seems to be no stopping your momentum at this point! 

In Room 105 of Blue Creek Apt. there seems to be, for all intents and purposes, [normals reversed/non-conformed](https://www.youtube.com/watch?v=8XE9pMm3KnA) on a few pieces of geometry (the door to the coin puzzle furniture and the carpet off to the side):

**Edit:** Another video example of normals adjustments:  https://youtu.be/G-K7WT9IIok?t=12m15s

![2018-05-28 18-00-16](https://user-images.githubusercontent.com/27395260/40689529-8595b12a-6370-11e8-8d02-1bd791a122f7.jpg)

This seems to only be an issue for the PC build (PC vs PS2 example): 
https://youtu.be/W4a_w7fS1KI 

I have no clue if this can possibly be resolved through hex editing but if anyone can determine this it is you. Also, I'm not 100% sure this is due to reversed geometry normals or something totally different... it just happens to look like reversed normals is all.

**Comment by Bigmanjapan** [comment]
Did you open ap76.map file in Maya in that video?

**Comment by Polymega** [comment]
I did. I exported the level (as OBJ) through the [SH Level Viewer](http://alchemillahospital.net/sh-234-level-viewer/). The normals retained their information through the export which confirmed this was the issue when I opened it in Maya.

**Comment by Polymega** [comment]
May need to keep an eye on this: 
http://lazov.ru/mr/index.php 

> In development: 
> Normal vectors support

**Comment by Bigmanjapan** [comment]
Is there any specific import setting you do in Maya during .obj files importing? Maya crashes if I try to open them. Metasequoia 4 works fine tho.

**Comment by Polymega** [comment]
It doesn't import into Maya without opening it in another program and re-saving it as an OBJ. If you try to open it in Maya as-is you'll get the error message "Index Out of range for face creation." There are ways to fix this but it requires _a lot_ of time and trial and error. 

I opened the file in Photoshop (Photoshop can open 3D files!) and exported to Collada 3D (.dae). Then I was able to import the file in Maya. 

In the past, I also had my friend open the OBJs in Rhino 3D and export for me as well. 

I use Maya simply because that was the software I was trained/educated to use.

**Comment by Bigmanjapan** [comment]
I nulled almost all of ap76.map and shading on carpet and cabinet is still preset: 

![default](https://user-images.githubusercontent.com/31383389/40998534-52077114-6932-11e8-8d8a-5ab5f002fe24.png)

There are still very small chunks of data that control those texture leftovers which I will inspect more. 

I tried importing ap76.obj file alone (without .tga and ap76.mtl files) in Photoshop CS3 and it rendered the model without any shading.

If you open ap76.mtl in hex editor, you'll see strings of information like this: 

newmtl             2215_mtl
Kd      1.0000 1.000 1.000
Ka      1.0000 1.000 1.000
Ks      1.0000 1.000 1.000
illum 0
d 1.000000
map_Kd            2215.tga

http://paulbourke.net/dataformats/mtl/ discribes this format thoroughly. 

The issue is that .obj / .tga / .mtl files are compressed (?) when they are stored in a single .map file and data between them is not in 1:1 format — there is no understanding what to hex edit in ,map file.

**Comment by Bigmanjapan** [comment]
I see, thanks for the info. That will take some time to research.
Maybe @Nisto can help with this? Since he did extractors for PS2 SH2 builds.

**Comment by Polymega** [comment]
@Bigmanjapan @elishacloud @AeroWidescreen

Hi team, 

I wanted to share some good and exciting news with you all. I've been in contact with Stan @sbobovyc Bobovych , [a multifaceted programmer/engineer](https://stan-bobovych.com/about), over the past month or so, and he has cracked open the secrets to the game's 3D data with the .map files. 

This isn't his first time reverse engineering a game file [as seen in one of his earlier blog posts here](https://sites.google.com/site/sbobovyc/writing/reverse-engineering/ply) (and it was this same post that initially led me to him). With his expertise and knowledge in such work he graciously accepted my request to look into and solve the bad normals for this room. 

[**You can read his first blog post on researching/testing/experimenting with the game's .map file on his site here.** ](https://stan-bobovych.com/blog/reverse-engineering-map-files-from-silent-hill-2)

![image](https://user-images.githubusercontent.com/27395260/48589447-98a92700-e909-11e8-8866-24d5f99ef55a.png)

To you programmers here, I'm sure this would be an interesting and fascinating read. And while we've been stumped with cracking this riddle since the beginning, if, after reading his post, any revelations come to you with how to see the solution through, please do chime in! 

To any fans currently reading this: If you'd like to send Stan a "thank you" tip for his time and skills put towards this fix, [please considering sending him a donation here](https://www.paypal.me/Bobovych). He's doing this on his spare/free time having never played the game before, so this is a pretty big deal for him to share his talents helping our fanbase out. 

And to Stan: Thank you so much again for all that you are doing!

**Comment by FrozenFish24** [comment]
![carpet](https://user-images.githubusercontent.com/12547453/48971233-f0563980-f051-11e8-8663-91134b555bad.jpg)
![cabinet](https://user-images.githubusercontent.com/12547453/48971234-f3512a00-f051-11e8-86ba-cbc3089a6dd8.jpg)
[ap76.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2612452/ap76.zip)

How's this look?

**Comment by Polymega** [comment]
Holy!! Okay, well, let me boot up the game soon as well and give her a test run. Looking at just your pictures it looks _seeeeexy_! 

This is awesome!

**Comment by Polymega** [comment]
@FrozenFish24 that's the ticket! Everything looks fantastic! Thank you! 

This is also great because now I can package up [all the recent, new fix files](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/49) and release them as v1.0.3 of the Enhanced Edition Essential Files for others to grab and enjoy. 

I'll start work on making an update video covering all this as well. Thank you again!

**Comment by FrozenFish24** [comment]
Great, glad I didn't introduce any new oddities. Looking forward to the video, the work you guys have done is really impressive!

**Comment by Polymega** [comment]
> Looking forward to the video, the work you guys have done is really impressive! 

Love your modesty. :) If you contribute, you're part of the team. [Welcome to the team!](https://www.youtube.com/watch?v=wJ6DL79sI0E) 

If I may ask, how deep/extensive is your background with this type of work? [Elisha is working on removing the need for WineD3D for Nvidia cards](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/10) but he's currently stuck on that last thing to fix: [Preventing chunks of the wall from disappearing when the camera is too close to the geometry.](https://www.youtube.com/watch?v=hzdAhOvpGfA) 

Are you familiar with such issues in games? Any clue on how approach this fix? This particular task is a milestone for us because, once we remove the need to WineD3D for Nvidia cards, we can unify the installation process for everyone and then start looking in to making a bonafide installer for all the fixes (instead of making people download each fix, one-by-one). That, and WineD3D causes most problems for people when trying to play the game. 

Here's Elisha's earlier notes on what he thinks the issue might be: 

> I already took a quick look at the chunks of the wall disappearing issue.  This appears to be an issue with how Nvidia handles vertices.  Troubleshooting vertex issues are not fun or easy!  The screens that have this issue have 10’s of thousands vertices.  I don’t have any tools to work with vertices (if I had the Silent Hill 2 source code then I could use off the shelf tools and this would be easy) so I need to do this by hand (i.e. create my own specific code/tools to help me troubleshoot this).  First I need to create code to extract all the vertices, then figure out exactly which vertex has the issue (it looks like it is only one, or at most two, vertices in each screen) and then I need to figure out why that vertex has an issue.  I have never worked with vertices before, so this will be a good learning experience!  Note: to understand vertices check out these pages:
> 
> - http://www.directxtutorial.com/Lesson.aspx?lessonid=9-4-4
> - http://www.directxtutorial.com/Lesson.aspx?lessonid=9-4-7

**Comment by FrozenFish24** [comment]
>[Welcome to the team!](https://www.youtube.com/watch?v=wJ6DL79sI0E)

:rofl: 

>If I may ask, how deep/extensive is your background with this type of work?

I've reversed a handful of binary formats here and there, mostly textures and archives. I have very little experience with graphics APIs though. This is the first 3D format I've attempted.

>First I need to create code to extract all the vertices, then figure out exactly which vertex has the issue (it looks like it is only one, or at most two, vertices in each screen) and then I need to figure out why that vertex has an issue. 

If he's thinking the problem lies in the actual vertex properties within the map files then I might be able to help. I can dump out the vertex buffers from the map files pretty easily and locate specific vertices using Blender. I'll have a look tomorrow.

**Comment by Polymega** [comment]
Thank you kindly! Any research will surely help just the same as what was done here with the vertex normals. 

Just a forewarning: There isn't necessarily a particular set of rooms (.map files) that experience this issue on Nvidia cards; it's more like any time, any where, when the camera gets too close to geometry it does this when not using WineD3D with Nvidia. 

Another example: When you and Maria are being chased down the tight hospital corridor by Pyramid Head you will see chunks of the walls loading/unloading consistently as you keep running.
