### ISSUE TITLE
Camera Editor

### ISSUE THREAD

**Issue by dwijlay** [elishacloud/Silent-Hill-2-Enhancements#600]
I've been searching for a while but had no success finding a download link to the camera editor and version 1.0 executable (the link from YouTube isn't working), is there some other way to get both?

**Comment by Polymega** [comment]
I've removed the link/program as it also requires downloading Cheat Engine and I didn't want to supervise people in how to safely download Cheat Engine. If you already have Cheat Engine, you can refer to this ticket to use the camera editor I made: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/351

**Comment by dwijlay** [comment]
Thank you very much, I already had CE since it's used for other games camera tools as well, it's working just fine!
