### ISSUE TITLE
Super Sampling Shadows bug.

### ISSUE THREAD

**Issue by nikosioannoy** [elishacloud/Silent-Hill-2-Enhancements#601]
If I use Super Sampling through the AMD Software the game`s shadows  start flickering. I use the fix Anti Aliasing option and disable the SMAA in the config.  I happened to be recording this so here is a recording of the recording showcasing the problem :D I can replicate this every time. I had the previous version of EE installed and yesterday just install on top of it the new latest ones with the setup tool and all. Hope that is fine but figured I had to mention it.

https://user-images.githubusercontent.com/32744524/190200528-5aff0431-dd7f-4345-b898-d10add34a2ec.mp4

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9567841/d3d8.log)

**Comment by TommvinHuwaltzky** [comment]
That is apparently an issue with AMD-cards. Happened on my 5700 XT as well (opened an issue here myself about that a few years back).

What you should do anyway, is use VSR combined with SMAA. In comparison the driver-SSAA is very blurry.
So downsampling will give you _far_ better image-quality.
