### ISSUE TITLE
Visual C++ Buffer Overrun Error

### ISSUE THREAD

**Issue by randevperera** [elishacloud/Silent-Hill-2-Enhancements#604]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9593811/d3d8.log)
Recently moved the SH2:EE installation folder to another drive to free up some space and now, for some reason, I can't _**navigate**_ the save menu. I can save to a slot already present but **pressing the directional keys** in this menu brings up this error.
Any assistance regarding this is greatly appreciated.

![Screenshot (744)](https://user-images.githubusercontent.com/75287368/190898382-ab143078-ea4a-49d0-aeee-3502d36761aa.png)

**Comment by elishacloud** [comment]
I guess it is crashing when you try and load a save. Try temporarily removing your old saves by renaming `Folder 01` under the `\Silent Hill 2\data\save\` folder to a different name.

**Comment by randevperera** [comment]
I will try that and get back to you. Thank you very much!

**Comment by randevperera** [comment]
I moved it back to my main drive after freeing up some space and it went back to normal from there, the hard disk space was showing up as well. I guess I'll keep it there. Maybe it has a problem with external drives because the error kept popping up. Thanks a lot for the help, anyways! Magnificent project :D
