### ISSUE TITLE
Is it Possible to Spoof a Save?

### ISSUE THREAD

**Issue by Schizotard** [elishacloud/Silent-Hill-2-Enhancements#605]
Hey, absolutely phenomenal work on the Enhanced Edition. I recently finished SH2 on PCSX2 and I want to do another playthrough. I'd like to fool around with some of the new game+ features (rebirth ending, chainsaw). Is it possible to spoof an already completed save? Thanks.

**Comment by Polymega** [comment]
I'm not sure about spoofing via editing through Cheat Engine or the like, but here are some general saves for the game that you can use, which includes a New Game+:

http://www.igotaletter.com/temp/sh2pc/General_Saves.zip

Replace the **entire contents** of your `data\save\Folder 01\` folder with the contents of this `Folder 01` folder. Make a backup of this folder if you have previous saves you wish to keep.

**Comment by Schizotard** [comment]
> 

I appreciate the response, however the link produced a corrupted file.

**Comment by Polymega** [comment]
No prob! I probably should have clarified that you need to fully nuke the contents of the `Folder 01` folder before placing those new files in there. Glad you got it sorted out. 👍
