### ISSUE TITLE
Gun used during Aim regardless of Equipped status

### ISSUE THREAD

**Issue by realNescius** [elishacloud/Silent-Hill-2-Enhancements#607]
**Description:**
Regardless of whether I have nothing/stick equipped, when I aim, the gun is used to aim.
While testing, I accidentally lost two bullets before noticing it.

**Prescription:**

1. Have Wooden Plank/Nothing equipped.
2. Have Handgun in inventory.
3. Press Aim.

**Demonstration:**
![video](https://user-images.githubusercontent.com/25656892/192083994-f9b07c20-8823-4987-b844-3a013558a00c.mp4)

---------------------------------------------
When adjusting the camera towards where James is facing, the stick shows up in his hands, and stays there until aiming once again.

**Comment by Unknow0059** [comment]
When the stick is equipped, holding aim as you go through a door will cause James to ready with the stick on the other side, and you can attack for as long as you hold aim.
Upon letting go of aim, and aiming again, the gun shows up instead of the stick.

**Comment by Polymega** [comment]
I am unable to replicate this bug. Are you using a controller? And, if so, are you using an external piece of software controller such as DS4Windows? 

> When the stick is equipped, holding aim as you go through a door will cause James to ready with the stick on the other side, and you can attack for as long as you hold aim.

This is also interesting as you shouldn't be able to interact with doors while you are aiming. You must let go of aim before James will open a door. The same goes if you change the "ready weapon" method to "toggle" (instead of "press").

**Comment by Unknow0059** [comment]
> I am unable to replicate this bug. Are you using a controller? And, if so, are you using an external software for your controller, such as DS4Windows?

Not using controller; keyboard.

> This is also interesting as you shouldn't be able to interact with doors while you are aiming.

I am not in the aiming state, no - I am going through the door (the in-between black screen) - I'm simply holding the aim button.

**Demonstration:**

https://user-images.githubusercontent.com/25656892/192174589-c7005a72-3891-414f-8327-25cf32da093b.mp4

Note, during the testing, I loaded the save prior to having the Handgun, and grabbed it again, to check if the bug persisted. It did. Here are my saves:

[save-Folder 01.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9642179/save-Folder.01.zip)

**Comment by Unknow0059** [comment]
![image](https://user-images.githubusercontent.com/25656892/192177332-3ebcfd76-81fa-4138-8713-101f986557a9.png)

**Comment by Unknow0059** [comment]
I switched the ready key from "3" (num row) to "Num 5" (numpad). The bug went away.

I can type 3 and e without interference, I don't think this is a hardware issue.

**Comment by Polymega** [comment]
Ah, the reason for this is that all of the weapons are hard-coded assigned to the non-numpad keyboard numbers. 1 is Plank, 2 is Pipe, 3 is Handgun, etc.

**Comment by Unknow0059** [comment]
Is it unfixable?

**Comment by Polymega** [comment]
This is something hardcoded into the game. It would need to have someone to look into it. I'm not sure who would look into it, but either all of the 0-9 weapon-specific bindings would need to be removed outright or we'd need to prevent the player from assigning any other functions to 0-9.

**Comment by Polymega** [comment]
Update for this: @mercury501 has created a solution to this. If you assign a function to one of the non-numpad 0-9 keys then the weapon that was hardcode assigned to that number will deactivate. If you ever remove your function from the number, it will restore whatever weapon is assigned to that number.

This will be included as a feature for our next project update.
