### ISSUE TITLE
SHEE LOADING TIMES

### ISSUE THREAD

**Issue by ppsalvador** [elishacloud/Silent-Hill-2-Enhancements#610]
Hello everyone,
Im here for asking a little thing.
It's possible turn off the loading times of SHEE?

Thank You all.

**Comment by matheusvb3** [comment]
You mean the time it takes to load the game when you launch it? Unfortunately I think you can only reduce it by turning off the "adjust color temperature" and "restore brightness selector" options, and SMAA antialiasing if you are using it. Maybe not using the HD images pack also helps. When the Creature Labs and Konami logos appear you can make them go away faster by pressing spacebar, I think you can also do it by pressing a button on the controller. This also used to annoy me a lot. 😅

**Comment by ppsalvador** [comment]
No that loadings. When u open a door or go to other location appears a footsteps loading. That loading im speeking about

**Comment by Polymega** [comment]
The purpose of the footsteps is that they appear whenever the game is taking longer then a second or two to load the next area. The footsteps are a visual indicator that the game hasn't froze or anything. At this time, there's no plans to remove the footsteps on the loading screen.
