### ISSUE TITLE
Pyramid Head hallway scene glitch

### ISSUE THREAD

**Issue by OregonPacifist** [elishacloud/Silent-Hill-2-Enhancements#611]
So this glitch happened while I was playing the game on my livestream. It made for some funny moments so I'm not complaining too much. However, it made this part unpassable. I'm talking about the scene at the end of the hospital where Pyramid Head chases James and Maria. What happened is that Pyramid Head appeared to be moving at 2x speed, killing Maria with ease before the ending cutscene could be triggered.

Here's the livestream replay (glitch and my confusion start at 50:44):

https://odysee.com/@OregonPacifist:0/sh2-ee3:b

**Comment by Polymega** [comment]
Looking at your stream, I don't _think_ he is glitching at 2x speed. More so, this is a...

![image](https://user-images.githubusercontent.com/27395260/193427201-99cc0371-55bc-4aaa-be3d-f683d7656688.png)

Hard Action Thing™️. This part of the game on Hard Action, simply put, _sucks_. You need precise movement (no slow downs, no wall bumps, etc), RNG in your favor for Maria to keep up, and you'll need to shoot RPT through the fence wall midway through.

Here are some tips that might help with this part (scroll down to the "Pyramid Head in the Basement Hallway - Note on Hard Action Level" section):
https://www.silenthillmemories.net/sh2/walkthrough_en.htm#06_Nightmare_Hospital

**Comment by Polymega** [comment]
I just tested on Hard Action, and the speed of RPT looks to be the same as what's seen in your stream. (On Hard Action, he'll thrusts that spear anywhere between _Insane Speed_ and _Ludicrously Insane Speed_.) Although it does appear that Maria on my tests took a few more hits than yours did before she died.

**Comment by OregonPacifist** [comment]
Dude you’re a legend for getting back to me so quickly. I thought the hard difficulty only increased the amount and strength of the enemies, not the speed of PH during this scene. I really appreciate your responses. Keep killing it!
