### ISSUE TITLE
Problems with movement

### ISSUE THREAD

**Issue by Sylwald** [elishacloud/Silent-Hill-2-Enhancements#619]
I'm having a hard time getting James to move correctly, to be exact, when I turn while running, James will slow down, almost walking speed, making impossible to run.

I'm using the Nintendo Switch Pro Controller with the Xinput Plus.
Curiously, If I use the controller while on Steam, the movement will be restored, but my triggers won't work.

**Comment by Polymega** [comment]
Are you using Directional (2D) movement or Rotational (3D) movement in the game? 2D should give you quick, snappy turning. For 3D, to have James continue running at full speed while turning, you typically have to turn fairly wide. To do a sharp turn in 3D, oftentimes you need to stop forward movement, press left/right to turn James, then press up to continue onwards.

**Comment by Sylwald** [comment]
I'm using Rotational movement, what I found weird is that if I play the game through Steam, It feels normal.
Just to be sure I used an PS2 emulator and I could confirm the movement feels better, I guess it's the deadzones on the Xinput?

**Comment by Polymega** [comment]
> I guess it's the deadzones on the Xinput?

That very well might be it. You can open the `XInputPlus.ini` file found in the game's main directory and adjust values in there. There is a `DeadZone=0` line for both `[LeftStick]` and `[RightStick]` that you can play around with.

**Comment by Polymega** [comment]
Also, truth be told, I can't remember the last time I used the joystick when playing with tank controls (rotational movement). Tank controls seem to perform better on a D-pad. 😅
