### ISSUE TITLE
Bad normals for "Leave" ending's James/Mary Room

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#62]
Son of a... (Posting this for posterity's sake.)

And here I thought it was just only [Blue Creek Apartment Room 105 with this issue](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/6). The consolation though is this _has to be_ the only other room in the game with bad normals. I seriously can't think of anywhere else this happens...

Anyway, James' and Mary's bedroom looks correct for the "In Water" ending: 

![sh2pc 2018-11-06 21-35-04](https://user-images.githubusercontent.com/27395260/48107033-f05dd900-e20b-11e8-9ce5-2b7b5f9350c6.png)

But the walls, floor, and ceiling are practically pitch black for the "Leave" ending: 

![sh2pc 2018-11-06 21-23-00](https://user-images.githubusercontent.com/27395260/48106749-ba6c2500-e20a-11e8-80bf-b8791a145207.png)

It's not supposed to look like that for the "Leave" ending... the lighting of the room should look similar (same?) as the "In Water" ending ([confirmed by comparing it to a PS2/Xbox playthrough](https://www.youtube.com/watch?v=JepSqkbUOyk)). 

I had a hunch this was bad normals when I swapped out qt01.map (the "Leave" ending bedroom) with qp01.map (the "In Water" bedroom) and the walls/ceiling/floor looked correct again (although the chair is in the wrong spot because I'm using the wrong .map file here for testing purposes):

![sh2pc 2018-11-06 21-51-21](https://user-images.githubusercontent.com/27395260/48107613-4cc1f800-e20e-11e8-8f5e-a5848b331ffd.png)

I then used the (very buggy) SH Texture Explorer to capture an OBJ of the room, converted it a bunch of times so Maya could open it, and, sure enough, it's normal issues again. Ugh. Here is a video showing the issue: 

https://youtu.be/C69UPP6dS-A

![image](https://user-images.githubusercontent.com/27395260/48111435-70da0500-e21f-11e8-98a2-bc2c67dc7b34.png)

**Comment by Polymega** [comment]
There may be a way to possibly fix this room, with the right person(s) to help us. 

`qp01.map` (good normals) and `qt01.map` (bad normals) are identical rooms with one exception: The chair is in a different position for each map: 

![image](https://user-images.githubusercontent.com/27395260/48232492-d5ac7100-e37f-11e8-8177-028c5de7ee40.png)
![image](https://user-images.githubusercontent.com/27395260/48232578-0ee4e100-e380-11e8-935b-8187520e969d.png)

_^ I fixed the bad normals for qt01.map in the photos above through Maya for illustrative purposes._

It's worth noting both of these .map files are not 1:1 and are different sizes: The 2D texture and 3D object data are in different ranges within the hex data for each .map file. But the geometry, from a finished rendered standpoint, is the same besides the chairs. 

------------------------

Theoretically, one of two things could be done via hex editing: 

1. Grab the chair's position data from `qt01.map` and transpose that data to `qp01.map` (so the chair is properly moved and rotated), then **rename** the edited `qp01.map` to `qt01.map` for the game to use.
2. Grab the geometry/normal hex data for the good walls/ceiling/floor from `qp01.map` and transpose that data to `qt01.map`.

**In regards to Option 1:** The .map files often group certain mesh objects together as seen here: 

![image](https://user-images.githubusercontent.com/27395260/48233386-fd510880-e382-11e8-837b-0d35a1135639.png)

^ In that photo, the chair in `qp01.map` is not grouped with anything else. Whereas the chair in `qt01.map` is also grouped with the window frame. I bring this up to say that the positional data for the chair in `qt01` will most likely take the median distance between the chair's mesh and the window frame's mesh. 

This is another way of saying that if you were to find the positional data for this chair from `qt01` and transpose it to `qp01` it probably won't be accurate. So the coordinates to adjust the chair within `qp01` would probably need to be manually changed to position the chair as close to the one from `qt01` as possible.

**In regards to Option 2:** The walls, ceiling, and floor are **not** grouped with any other objects in either file. Each wall piece, ceiling, and floor are there own entities. This means that it would theoretically be possible to find the normal data for each of these pieces and transpose it from `qp01` to `qt01`.

The problem here is that we have no easy and ready way to decipher the converted 3D data from the game's .map files, let alone have the ability to fix something like the normals then re-import that data back into the format the .map files understand. But hopefully that may change in the future with the right people lending their expertise and knowledge on reverse engineering 3D game file data. 

But I wanted to share these notes for future reference/help.

**Comment by FrozenFish24** [comment]
![room](https://user-images.githubusercontent.com/12547453/48902989-3619d300-ee95-11e8-8f56-a205829e19e9.jpg)
[qt01.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2608048/qt01.zip)

Does this work correctly?

**Comment by Polymega** [comment]
> Does this work correctly?

Why, yes! Yes it does! What a nice Thanksgiving Day treat! Thank you very much @FrozenFish24 ! In a nutshell, may I ask how you solved this problem? 

This will absolutely be included in the next release (1.0.3) of the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles) coming out soon. Wonderful work you've done here! 

One additional question for you: 

The Enhanced Edition Installation Guide includes a [credit/thanks portion seen here](http://enhanced.townofsilenthill.com/SH2/credit.htm). Would you be comfortable with me including your name/website/contact/donation link on this page? If so, may I get any relevant links from you and also ask you to write a short bio about yourself in regards to how you got into game modding?

Thank you again!

**Comment by FrozenFish24** [comment]
Sure,

Using a script I wrote I dumped out the vertices for the chair from both qp01.map and qt01.map to wavefront .obj files, I opened both of these in Blender, lined up the qp01 chair with the qt01 chair, exported the relocated qp01 chair back out as an .obj file. Then wrote another script to copy these updated positions back into qp01.map. Finally I swapped in the qt01 mat and floor textures using SH Texture Explorer.

I've been attempting to reverse and document the map format over the last few weeks. There's scant existing documentation I could find and all the current tools are closed source so it's been slow going (I'm also no 3DCG expert :stuck_out_tongue:) but I feel I've got the gist of the majority of the data it contains. Once I have something more comprehensive/presentable I can link you guys to it.

In regards to credit just mention my github page/username somewhere if you'd like to. Don't feel you have to though, my contributions are quite minor.

**Comment by Polymega** [comment]
> Don't feel you have to though, my contributions are quite minor.

Please never think like that. **ALL** contributions are important to making this beloved game the best it can be. :) 

> Using a script I wrote [...] I've been attempting to reverse and document the map format over the last few weeks.

Fantastic! Also, did you by chance happen to see [this post](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/6#issuecomment-439236652)? Before you shared your work I've been in touch with another programmer who specializes in reverse-engineering game files. He's found the location of the vertices, normals, tex coordinates, etc for the ap67.map file and [shared his initial research on his blog here](https://stan-bobovych.com/blog/reverse-engineering-map-files-from-silent-hill-2). His researcher may help you with your work as well?  

> In regards to credit just mention my github page/username somewhere if you'd like to.

Absolutely. Allow me some time to update the site with new credits; I've been busy with my spare time helping to fix the game in other avenues at this moment. Thank you again though, FrozenFish24! And do consider sending me a short bio about yourself if you'd like. :)

**Comment by Polymega** [comment]
Much love to FrozenFish24 on this one; ticket closed!

**Comment by FrozenFish24** [comment]
> Also, did you by chance happen to see [this post](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/6#issuecomment-439236652)?

Wow, not sure how I missed that. I hadn't thought to use apitrace with the sh map viewer, very clever.
