### ISSUE TITLE
Black Screen Crash after Eddie Museum Fight

### ISSUE THREAD

**Issue by rowleyfan3620** [elishacloud/Silent-Hill-2-Enhancements#622]
Hi there,

Currently playing through SH2 for my first time ever. Blown away by it!

I just got to the Eddie Fight in the Historical Society Museum (where you fight him in the room with all the hanging meat). Each time I enter the room, the audio gets glitchy (a skipping sound), and then I cannot exit the room following victory in the fight. When I attempt to exit the big doors, the game goes black and freezes.

I've been streaming the game, here's the twitch link to time in which you can see the glitch:
https://www.twitch.tv/videos/1628150653?t=3h7m31s

Do you have any advice on troubleshooting / any features I can disable? Really want to be able to finish this!

**Comment by Polymega** [comment]
There has been a small wave of people reporting the game freezing or going to a black screen consistently at seemingly random spots. Can you try this build to see if it still happens?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by rowleyfan3620** [comment]
Hey Polymega, that worked for me! Thank you. 

Can't wait to continue exploring the town!

**Comment by Polymega** [comment]
Thanks for letting us know!

@elishacloud 
I sent rowley a test build with the new hooking method. There's been a small spike in reports of the game consistently crashing at seemingly random spots/events. I know I mentioned this before, but I wonder if a Windows update has borked the old hooking method?
