### ISSUE TITLE
Something wrong with game language or smth

### ISSUE THREAD

**Issue by GreatestWave** [elishacloud/Silent-Hill-2-Enhancements#623]
I had this issue before, but solved it by adjust settings. After some time playing this happened again but with in game text then picked up key or investigated picture on the wall. I reinstalled the game but it happened again.
![image](https://user-images.githubusercontent.com/93007266/197073342-7868b905-181a-472a-a20a-85d2889942b4.png)

**Comment by elishacloud** [comment]
Just out of curiosity, can you try this build to see if it still happens?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by GreatestWave** [comment]
> What language are you wanting to play in?

English

**Comment by GreatestWave** [comment]
By the way I found out what then run game from setup.exe, its works fine but the bugged text still remains in some moments of the game. So i tried to change language to French in setup.exe run, then launched game from file shortcut and it worked just fine but the font changed and then I changed language back to English I found this. 
![image](https://user-images.githubusercontent.com/93007266/197076230-0025c24f-dbbf-46db-90b2-5f1ffd9e4090.png)
![image](https://user-images.githubusercontent.com/93007266/197076263-a943cdca-4fa7-46f1-96e1-6872d6616a5c.png)

**Comment by GreatestWave** [comment]
> Just out of curiosity, can you try this build to see if it still happens? https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

Still bugged text, but somehow bugged Japanese language were added 
![image](https://user-images.githubusercontent.com/93007266/197077248-df69acba-98df-483f-a570-00942f68f459.png)

**Comment by GreatestWave** [comment]
Now then I set English in the options it's make it all Spanish 
![image](https://user-images.githubusercontent.com/93007266/197077973-ebbe68c0-332d-4489-88aa-e0a11c814bb3.png)

**Comment by GreatestWave** [comment]
Could this problems be because when I downloaded game my Windows system language was not English, Spanish, German or French?

**Comment by Polymega** [comment]
Typically, this is a result of download the game with modifications for it to work in the Russian language. Where did you acquire the base (vanilla) game and can you share a screenshot of your game's directory?

**Comment by GreatestWave** [comment]
> Typically, this is a result of downloading the game with modifications for it to work with the Russian language. Where did you acquire the base (vanilla) game and can you share a screenshot of your game's directory?

I did actually get original game from the Russian torrent so maybe there were some Russification mods. I can show game’s directory but later

**Comment by Polymega** [comment]
You don't need to; that's the issue. Download the "fully extracted version" from this site and use that version instead:
https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Then, install our project files onto the base game.
