### ISSUE TITLE
Download is extremely slow and keeps crashing

### ISSUE THREAD

**Issue by iMSh4d0w-Github** [elishacloud/Silent-Hill-2-Enhancements#624]
I download with like 80-110 kb/s ( I normally have fast internet speed ) and after like 40 Minutes the download aborts which is extremely frustrating!! Is it possible to download the files from somewhere else, e.g. from a filehoster
![Screenshot 2022-10-21 232458](https://user-images.githubusercontent.com/116390867/197291726-9255bde2-f86c-4c51-866d-1cc1c715be0b.jpg)

**Comment by Polymega** [comment]
We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during the transfer. Please be patient with us.

**Comment by iMSh4d0w-Github** [comment]
> We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during the transfer. Please be patient with us.

Alright, I appreciate it. Thank you for your work!!

**Comment by Polymega** [comment]
Thanks for being understanding. 👍
