### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by RafaelAmauri** [elishacloud/Silent-Hill-2-Enhancements#626]
I am experiencing extremely slow download speeds, even though my internet is fast.

I've used the mod before in a playthrough last year and I don't remember having an issue downloading the files.

As a celebration for the announcement of the SH2 Remake I decided to revisit this classic, but the download speeds have been terrible!

10 Hours to download 1.6GB???
![Selection_001](https://user-images.githubusercontent.com/49131143/197308525-e9c6618b-f06f-4796-80ec-321914898ead.png)

I have fiber at home and a very stable connection, so I don't know what's causing this.
Here's a test I did right now, during the download process.

![Selection_002](https://user-images.githubusercontent.com/49131143/197308864-272ab73e-2be8-4e72-8e97-682c85a3fef5.png)

I'm on Linux, but even for the sake of testing I booted up my windows SSD and again, slow download speeds.

Is the remake announcement making everyone redownload the game and this put extra strain on the servers? I read #616 and tried downloading through the direct HTTP link, but even then I was hitting at max 300 kbps.

**Comment by Polymega** [comment]
We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during this server transfer. Please be patient with us.

I just spoke with the hosting provider and I'm hoping the migration will be complete by sometime tomorrow.

**Comment by RafaelAmauri** [comment]
Good luck with the server migration! :)

I'll download it later this week then, thanks for the quick reply!

**Comment by ADazedGamer** [comment]
I was having the same issues and i let it go all day to see if it would just be slow but i keep getting a timeout error ill do the same and wait till the migration is complete. Thanks
