### ISSUE TITLE
Can't use melee weapons, automatically switches to gun

### ISSUE THREAD

**Issue by MoisesFloress** [elishacloud/Silent-Hill-2-Enhancements#627]
This is an issue happening to someone I know and I can't figure out why. "I can’t use melee weapons, everytime I press the ready weapon button it switches to my handgun. i’ve gone to my inventory and unequip the gun and it still happens. i’ve gone through all my ammo and I still can’t use my melee weapon" 

Anyone got any idea what the issue is? It doesn't seem to be a keybinding error either. They hold the wooden plank, ready it to attack and the game switches to the handgun.

**Comment by Polymega** [comment]
I believe I know what the problem might be. Please read over this to see if this is the issue you're experiencing: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/607

**Comment by MoisesFloress** [comment]
That was the issue! thanks for the response
