### ISSUE TITLE
No Enhanced Edition menu? 

### ISSUE THREAD

**Issue by beepostudios** [elishacloud/Silent-Hill-2-Enhancements#632]
Thought I might have installed everything but I still have the Director's Cut menu instead of the Enhanced Edition menu. Not sure what I could have done wrong but it definitely bothers me. Pls help :) 

![2022-10-23 05_23_53-Silent Hill 2_ Enhanced Edition](https://user-images.githubusercontent.com/116487842/197384480-3c16a940-aa32-4a7e-adb6-656a1e078c1b.png)
![2022-10-23 05_24_04-Silent Hill 2](https://user-images.githubusercontent.com/116487842/197384524-9efb7279-f4b1-4b19-a0f2-720bdc760818.png)

**Comment by Polymega** [comment]
Does this file exist in this directory?
`<game folder>\sh2e\pic\etc\start00.tex`

**Comment by beepostudios** [comment]
> Does this file exist in this directory? `<game folder>\sh2e\pic\etc\start00.tex`

No actually! The installation must have gone wrong somehow because the "etc" folder is completely gone.

**Comment by Polymega** [comment]
Please give us some time to get our server situation sorted out, then you should be good to redownload any packages needed. You can keep up with our ~~woes~~ progress on the our server migration by following our project's Twitter page: https://twitter.com/whereallbegins

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).
