### ISSUE TITLE
SLOW DOWNLOAD

### ISSUE THREAD

**Issue by kxrku** [elishacloud/Silent-Hill-2-Enhancements#633]
It's been 24 hours but it's still downloading at 100/kb. I know you are migrating the server but there is no progress. Still downloading slowly please find a solution.

**Comment by YoruguaChamp** [comment]
Same...112/Kb,anyone knows why this happens?

**Comment by YoruguaChamp** [comment]
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/628#issuecomment-1287797727

**Comment by RyuSeisuke1992** [comment]
https://drive.google.com/file/d/1IugjqwMwPGVFnUDeB2UV6PMsk4Mu7pwd/view?usp=sharing - SH2EE_DSOAL_1.31a.02.zip
https://drive.google.com/file/d/1QzY_lBNQGahrOehTq7fjmZUTNBiEoQYS/view?usp=sharing - SH2EE_XInputPlus_4.15.2.zip
....is being uploaded - SH2EE_Audio_Enhancement_Pack_2.0.4.zip
....is being uploaded - SH2EE_Enhanced_EXE_NA_v1.0.zip
....is being uploaded - SH2EE_Enhancements_Module_2.0.2006.0.zip
....is being uploaded - SH2EE_Essential_Files_1.2.4.zip
....is being uploaded - SH2EE_Image_Enhancement_Pack_1.1.1.zip
....is being uploaded - SH2EE_FMV_Enhancement_Pack_1.5.3.zip

**Comment by RyuSeisuke1992** [comment]
@Polymega If it is not welcome, then please delete. I just want to help out in the matter temporarily. Would then delete the links themselves when the servers are working again.

**Comment by kxrku** [comment]
> iMSh4d0w

Can you combine it into a single .rar and convert it to a .torrent file?

**Comment by kxrku** [comment]
> https://drive.google.com/file/d/1IugjqwMwPGVFnUDeB2UV6PMsk4Mu7pwd/view?usp=sharing - SH2EE_DSOAL_1.31a.02.zip https://drive.google.com/file/d/1QzY_lBNQGahrOehTq7fjmZUTNBiEoQYS/view?usp=sharing - SH2EE_XInputPlus_4.15.2.zip https://drive.google.com/file/d/1jqGzwV2YVIdB7xl1vlCoRow7yEJ_iuUo/view?usp=sharing - SH2EE_Audio_Enhancement_Pack_2.0.4.zip https://drive.google.com/file/d/140jcARy20XI0ZxP4pqtJtKWSGZoNotfL/view?usp=sharing - SH2EE_Enhanced_EXE_NA_v1.0.zip https://drive.google.com/file/d/1__bXlPy_Rkknq3xyCDfcVCOVf3MQIyFD/view?usp=sharing - SH2EE_Enhancements_Module_2.0.2006.0.zip https://drive.google.com/file/d/1dQxDgf0kJfITm-E9WR67JwhqR4bDzzNd/view?usp=sharing - SH2EE_Essential_Files_1.2.4.zip https://drive.google.com/file/d/1TodPyLeLZAcrUl3HAQpzBWuNLDcLZG-i/view?usp=sharing - SH2EE_Image_Enhancement_Pack_1.1.1.zip https://drive.google.com/file/d/1v_x6NGK8apB98hydni1-JeDh1IXV3nCc/view?usp=sharing - SH2EE_FMV_Enhancement_Pack_1.5.3.zip

Can you combine it into a single .rar and convert it to a .torrent file?

**Comment by iMSh4d0w-Github** [comment]
@kxrku Why no Google Drive?

**Comment by matheusvb3** [comment]
@iMSh4d0w-Github I'll upload it to Drive and share when it's done downloading.

@Polymega Maybe something to consider for the future: distribute the FMV and audio enhancement packs in .tar.gz format instead of zip?

**Comment by Polymega** [comment]
We originally went with .zip as it comes standard on Windows and wouldn't require a user downloading another tool for extraction. However, I believe 7Zip is used within the Setup Tool (@nipkownix?) and we could maybe switch over to .7z moving forward.

**Comment by matheusvb3** [comment]
7-Zip can decompress and extract .tar.gz files as well. Of course if someone who's not tech-savvy is to install everything by hand they might end up getting confused, but that's what the installer is for...

**Comment by iMSh4d0w-Github** [comment]
> @iMSh4d0w-Github I'll upload it to Drive and share when it's done downloading.
> 
> @Polymega Maybe something to consider for the future: distribute the FMV and audio enhancement packs in .tar.gz format instead of zip?

I already got everything. @kxrku Just wanted those files as Torrent and I wanted to ask him why

**Comment by astorun** [comment]
> > https://drive.google.com/file/d/1IugjqwMwPGVFnUDeB2UV6PMsk4Mu7pwd/view?usp=sharing - SH2EE_DSOAL_1.31a.02.zip https://drive.google.com/file/d/1QzY_lBNQGahrOehTq7fjmZUTNBiEoQYS/view?usp=sharing - SH2EE_XInputPlus_4.15.2.zip https://drive.google.com/file/d/1jqGzwV2YVIdB7xl1vlCoRow7yEJ_iuUo/view?usp=sharing - SH2EE_Audio_Enhancement_Pack_2.0.4.zip https://drive.google.com/file/d/140jcARy20XI0ZxP4pqtJtKWSGZoNotfL/view?usp=sharing - SH2EE_Enhanced_EXE_NA_v1.0.zip https://drive.google.com/file/d/1__bXlPy_Rkknq3xyCDfcVCOVf3MQIyFD/view?usp=sharing - SH2EE_Enhancements_Module_2.0.2006.0.zip https://drive.google.com/file/d/1dQxDgf0kJfITm-E9WR67JwhqR4bDzzNd/view?usp=sharing - SH2EE_Essential_Files_1.2.4.zip https://drive.google.com/file/d/1TodPyLeLZAcrUl3HAQpzBWuNLDcLZG-i/view?usp=sharing - SH2EE_Image_Enhancement_Pack_1.1.1.zip https://drive.google.com/file/d/1v_x6NGK8apB98hydni1-JeDh1IXV3nCc/view?usp=sharing - SH2EE_FMV_Enhancement_Pack_1.5.3.zip
> 
> Can you combine it into a single .rar and convert it to a .torrent file?

Those links are not working sadly.

**Comment by MrAhmedElmoez69** [comment]
i ve checked now the links and unfortunately they are not working still ...

**Comment by MrAhmedElmoez69** [comment]
here is a mirror for the files , still missing 2 files 
https://www.mediafire.com/file/hikdsavvzq61rmw/SH2EE_XInputPlus_4.15.2.zip/file 
https://www.mediafire.com/file/xwly79a1fbqw3nz/SH2EE_DSOAL_1.31a.02.zip/file
https://www.mediafire.com/file/9yquavkzuiziuy3/SH2EE_Enhanced_EXE_NA_v1.0.zip/file
https://www.mediafire.com/file/vbb0z8b1rhij113/SH2EE_Enhancements_Module_2.0.2006.0.zip/file
https://www.mediafire.com/file/4nqkkjqfmd1zbyj/SH2EE_Essential_Files_1.2.4.zip/file
https://www.mediafire.com/file/gf2pykfpgu5u3f9/SH2EE_Image_Enhancement_Pack_1.1.1.zip/file

**Comment by MrAhmedElmoez69** [comment]
guys the other two files 
https://www.mediafire.com/file/3t19pgw7ygvtcpp/SH2EE_Audio_Enhancement_Pack_2.0.4.zip/file
https://www.mediafire.com/file/xb7jp4jpdp1wiy2/SH2EE_FMV_Enhancement_Pack_1.5.3.zip/file

**Comment by matheusvb3** [comment]
@MrAhmedElmoez69 You're a hero

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

You can find the Setup Tool here:
https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

Please report back whether or not the download times out for you. Also, please let us know the average speed of the download. (Speeds may start off slow at the start of downloading each new package, but should pick up speed within seconds.)

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).
