### ISSUE TITLE
buttons flipped?

### ISSUE THREAD

**Issue by Guapotoni** [elishacloud/Silent-Hill-2-Enhancements#635]
So i i’ve been playing the game lately but is are my buttons flipped or are the control inputs the game comes with the correct ones? the site says use “b” for flashlight but the game has L2 for it instead.

**Comment by Polymega** [comment]
If you downloaded the XInput Plus package, it comes with a pre-configured file that has the controller buttons pre-configured to what they normally would be for the game. This pre-configured file should work for both DirectInput and XInput controllers. Are you using a third party software with your PlayStation controller, such as DS4Windows? That might be creating a conflict.

**Comment by Guapotoni** [comment]
I have it but I turned it off for silent hill show it shouldn't be that which is why I'm here. ;[

**Comment by Guapotoni** [comment]
my mistake i meant to put i turned off DS4 when i plugged in my xbox controller, could it be because it’s connecting to steam maybe? gunna check that
