### ISSUE TITLE
Keeps crashing when i enter hospital

### ISSUE THREAD

**Issue by githubguy69** [elishacloud/Silent-Hill-2-Enhancements#636]
the game keeps crashing whenever i try interact with the hospital doors

**Comment by Polymega** [comment]
We believe a Windows update is conflicting with how our project hooks itself into the games' files, which creates these types of instabilities. Please use the build below which utilizes a new hooking method that should fix this: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by githubguy69** [comment]
> We believe a Windows update is conflicting with how our project hooks itself into the games' files, which creates these types of instabilities. Please use the build below which utilizes a new hooking method that should fix this: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

thank you but it didn't work, I think it might be a bad install but every time I try to redownload it through the setup it comes back with an error so I'm downloading the package on their own right now, but I'm not sure where I'm meant to put them in the files
