### ISSUE TITLE
including all the notes, riddles, and items save file or debug menu?

### ISSUE THREAD

**Issue by kiminru** [elishacloud/Silent-Hill-2-Enhancements#638]
Is it possible to do a save file or debug menu that collects all the collectors, 
including all the notes, riddles, and items from the PC version or PS2 version?

![SH2PC Title 2022-10-25 오후 12_18_29](https://user-images.githubusercontent.com/84241069/197675673-94db1186-f9b9-4641-ad8b-5eeb2740e9a2.png)
![SH2PC Title 2022-10-25 오후 12_17_07](https://user-images.githubusercontent.com/84241069/197675674-8709590f-c169-4dbf-b412-401545cf23c3.png)

![SH2PC Title 2022-10-25 오후 12_17_13](https://user-images.githubusercontent.com/84241069/197675721-bb84178d-c3da-4736-93a9-2bc5f4009c9a.png)
![SH2PC Title 2022-10-25 오후 12_18_39](https://user-images.githubusercontent.com/84241069/197675728-c40a619b-3c64-4e26-bc8a-3dcb96addb49.png)

![병원 3층 - 동의 반지 납의 반지로 열고 들어간 문의 3층 2층 사이의 계단에 메모 -마리아와 함께 삼각두에 쫒기는 지하복도로 가기전의 계단](https://user-images.githubusercontent.com/84241069/197676652-2e07a3bb-ab0a-4cdf-b47b-1ddc13d95715.jpg)
![병원3층 S11병실 - 메모 #12 - 그 사람은 천사](https://user-images.githubusercontent.com/84241069/197676659-5b9c4ce4-203b-4ca8-8428-a497a7a2da41.jpg)
![호텔에서 로라가 제임스에게 전달해주는 편지](https://user-images.githubusercontent.com/84241069/197676664-f1f04c88-516a-429f-8930-b49503c31b53.jpg)

There were also many misspelled sentences in Korean, These things are being checked.

Currently I am in charge of Korean translation of PS2 version. 
I plan to add the language of the PC version as soon as the PS2 Korean language Inspection is completed.
Because I don't have time, I can't check the inspections one by one, so I'm testing the save files for the PC version. 
However, I want to inspect all notes, riddles, items, etc, but it is difficult to do it in a short time. Do you have any way?

Silent Hill 2 does not have a Korean language. 
For the PC version, I changed the French language to Korean.
PS2 version, I changed the Italian language to Korean.

**Comment by Polymega** [comment]
Hi @kiminru,

This section of our PC translation guide has a link with a save file that includes most/all of the items unlocked. Be sure to read the "README" file in the save folder:

https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.sgte7nr06axv

**Comment by kiminru** [comment]
> Hi @kiminru,
> 
> This section of our PC translation guide has a link with a save file that includes most/all of the items unlocked. Be sure to read the "README" file in the save folder:
> 
> https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.sgte7nr06axv

The site is not responding. Can't download.

**Comment by Polymega** [comment]
Yeah. I'm having severe server issues with my hosting provider. It might be a few more days until it's sorted out.

**Comment by Polymega** [comment]
Please try the link again now.

**Comment by kiminru** [comment]
> Please try the link again now.

I was late and couldn't get it. And it's disconnected again. I'll test it out when I have time!
