### ISSUE TITLE
Installer says its going too take 14 plus hours too install

### ISSUE THREAD

**Issue by nucleargamer5050** [elishacloud/Silent-Hill-2-Enhancements#640]
Im not the best with editing games and such and thought the installer would make life easy but im sitting here waiting for like 2 hours and its barely done. Is there a way too fix this? its only going at 82 KB a second as well. im not sure.

**Comment by Polymega** [comment]
Please see here: https://twitter.com/WhereAllBegins/status/1584955604900007937

**Comment by nucleargamer5050** [comment]
> Please see here: https://twitter.com/WhereAllBegins/status/1584955604900007937

So its just going slow in general? is there any chance that it will speed up in the future? or is it still undertermined.

**Comment by Polymega** [comment]
We will be changing hosting providers in the future to remedy this.

**Comment by jshield** [comment]
this is a perfect use case for bittorrent or a similar p2p sharing solution to distribute the packs.

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).
