### ISSUE TITLE
Puzle de las monedas

### ISSUE THREAD

**Issue by Ceretesaurio** [elishacloud/Silent-Hill-2-Enhancements#641]
No me sale el cursor en el puzle de las monedas. Alguna solución o fichero que me falte o añadir? el instalador nunca termina de arrancar... no sé si seré el único o le pasará a más gente, pero cada vez que me encuentro un error o fallo en el juego se me quitan las ganas de jugar. Alguna ayuda, gracias.

**Comment by matheusvb3** [comment]
@Ceretesaurio Intenta descargar los archivos que MrAhmedElmoez69 ha adicionado en esta página https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/633 Haz un backup de la carpeta de save de tu juego, instala de nuevo y desempaqueta los archivos del enlace en el archivo del juego.
