### ISSUE TITLE
Discord Rich Presence Support?

### ISSUE THREAD

**Issue by ArhumMK** [elishacloud/Silent-Hill-2-Enhancements#646]
It might've already been suggested before, but leaving it here for future discussion. As the title says, adding Discord Rich Presence support would be pretty neat, as Silent Hill 2's .exe doesn't seem to be recognized by Discord by default (meanwhile SH3's .exe does get recognized but as "Silent Hunter 3", a different game). 

It could be made to display stats similar to Duckstation's displayed stats for Silent Hill 1, Such as Time played, Difficulty, number of kills, saves, retries and more. With the game's icon displayed or even better, a small snapshot of the general area the player is in currently. Thanks!

**Comment by Polymega** [comment]
Apologies, but we won't be adding this in.
