### ISSUE TITLE
Post server migration: Report issues of Setup Tool here

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#647]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

If you run into any troubles still with the Setup Tool, please report them here.

**Comment by Balthazor44** [comment]
Something I just noticed, I ran the game and got a message that an update was available and I chose the option to close the game and run the setup tool. I let it install the update, but now when I run the game, it still tells me that an update is available, even though the setup tool says there isn't.

**Comment by Polymega** [comment]
The next time you launch the Setup Tool you should receive a message that the tool itself needs to be updated. Let it update and see if that fixes the update loop issue.

**Comment by Balthazor44** [comment]
I ran the setup tool and it did update, but unfortunately that just made things stranger. Now when I run the game, it still tells me an update is available, but now when I choose the option to run the updater I get a screen telling me it's downloading SH2EEsetup_New.exe, then it launches the configuration tool.

**Comment by nipkownix** [comment]
Seems to be some logic problem we missed during testing. Sorry about that. I'll take a look at the issue tomorrow, but you can safely ignore the update dialogue for now.

**Comment by Balthazor44** [comment]
> Seems to be some logic problem we missed during testing. Sorry about that. I'll take a look at the issue tomorrow, but you can safely ignore the update dialogue for now.

Okie dokie, let me know if there's anything else you need from me.

**Comment by Moonwalwer** [comment]
Im having a problem here, im dowloading this for the first time, when i run the setup tool and  start installing it says "runtime error at 308:1926 out of range, what do i do?

**Comment by nipkownix** [comment]
Thanks! Could you please upload here your "SH2EEsetup.dat" file? Should be in the game's folder.

**Comment by Polymega** [comment]
@nipkownix 
For this particular "out of range" error I suggested they restart their computer and it fixed the problem. [See ticket here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/651) I Google searched this error and there wasn't many results, but one of the very few pages had someone suggest rebooting their PC. 😅

**Comment by Polymega** [comment]
@Balthazor44 
At your earliest convenience, can you please upload the `SH2EEsetup.dat` file found in the game's main directory? Just click + drag the file onto into the text field here when you respond. Thanks!

**Comment by Balthazor44** [comment]
[SH2EEsetup.dat.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894363/SH2EEsetup.dat.txt)

Sure thing. I renamed it since this site apparently doesn't support the .dat file type.

**Comment by nipkownix** [comment]
> Now when I run the game, it still tells me an update is available, but now when I choose the option to run the updater I get a screen telling me it's downloading SH2EEsetup_New.exe, then it launches the configuration tool.

And this happens consistently every time? Could you test it one more time, please? The package versions in your .dat file seem to match ours correctly. The fact ``SH2EEsetup_new.exe`` means the d3d8 module thinks there's an update for the installer available, even though there isn't one.

**Comment by Balthazor44** [comment]
> And this happens consistently every time? Could you test it one more time, please? The package versions in your .dat file seem to match ours correctly. The fact `SH2EEsetup_new.exe` means the d3d8 module thinks there's an update for the installer available, even though there isn't one.

Yes it happens every time. I just tried it again now and same thing, says an update is available, downloads the _New file, then launches the configuration tool.

**Comment by nipkownix** [comment]
Alright, I'll add some more logging so we can try to find out what is going on. Just a moment.

**Comment by nipkownix** [comment]
@Balthazor44 Could you replace your d3d8.dll with this one?
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894490/d3d8.zip)

Try running the game again, and if the update stuff shows up, please upload your d3d8.log here.

**Comment by Balthazor44** [comment]
I tried that dll several times and I didn't get the update dialogue at all. Then I went back to the last dll and got the update dialogue again. One thing I notice, not sure if it's related, is that when I run the setup tool SH2EEsetup.exe manually, it defaults to "Adjust Settings" which just launches the configuration tool. I'm wondering if that's related to how I have the update dialogue launching the configuration tool.

**Comment by nipkownix** [comment]
> I tried that dll several times and I didn't get the update dialogue at all. Then I went back to the last dll and got the update dialogue again. 

Huh, that's odd. @elishacloud, the dll I posted is up-to-date with the current master from the git repo.
I've had to change some stuff though: Retargeted the solution to compile with VS2022, added some logging, and also commented these two lines out:
![image](https://user-images.githubusercontent.com/33870163/198850861-7014ddc7-19a1-4093-93d1-6f23f85ec58e.png)

Had to do this to avoid these errors:
![image](https://user-images.githubusercontent.com/33870163/198850912-0b46edfc-016c-4e11-b0ad-11e689821430.png)


This most likely breaks some other things, but it shouldn't matter for this test, correct? Not sure why the public release of the dll is triggering this false positive.

**Comment by Balthazor44** [comment]
I should mention, if I try this with an old d3d8.dll from back in May I get the same behavior, so whatever is causing this doesn't seem to be a recent change to that dll anyhow.

**Comment by Balthazor44** [comment]
I just tried this out on my other machine, when I ran SH2 it came up with the update dialogue, then launched the setup tool and updated the SH2 Enhancements Module, and then the game ran as expected. So in other words, this issue is only happening on this one machine and not the other.

**Comment by nipkownix** [comment]
Strange. Will see if I can get VS 2017 to try to build the dll with as little changes as possible, so we can try to get the window the dialogue to show up with logging.

**Comment by Polymega** [comment]
> I just tried this out on my other machine, when I ran SH2 it came up with the update dialogue, then launched the setup tool and updated the SH2 Enhancements Module, and then the game ran as expected. So in other words, this issue is only happening on this one machine and not the other.

I spoke with nipkow about this as well and I _think_ the error might happen when the installer is open while an update is pushed to the CSV file. Or maybe if the installer is manually updated and the local CSV file is still old.

I'm not sure what the cause is, but I believe it has something to do with some facet of the chain being updated that breaks the rest of the chain.

Since, on your other computer, everything was done "fresh" outside of me updating the CSV the other day, nothing broke for you on that PC.

Thats my theory, anyways...

**Comment by nipkownix** [comment]
That wouldn't explain the loop, though. Their ``SH2EEsetup.dat.txt`` file shows the ``setup_tool`` entry with a version of ``1.1.0``. When the game opens, the d3d8 module checks the version in our web .csv file, and it compares the web version with the local version. The fact it is showing the update dialogue, and then trying to update the setup tool, means the module somehow is thinking the versions are not matching, when they should be, based on the info we have.

**Comment by Polymega** [comment]
Explained out like this, that makes sense. The silver lining is that it sounds like the issue is isolated to the SH2E module?

**Comment by Balthazor44** [comment]
What's weird too is if I copy an older version of the setup tool into the directory and run that, it updates itself and works fine after that. Meaning it doesn't keep trying to update itself. It's just when I launch the game.

**Comment by nipkownix** [comment]
@Balthazor44 Can you check if the update dialogue shows up with this version?
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894649/d3d8.zip)

**Comment by Balthazor44** [comment]
That one does not give me the update dialogue. I did a couple tests with it. What I did was first I tried updating the SH2EEsetup.date to set the setup_tool version to 1.0.0 and ran the game. It gave me the update dialogue and updated the setup tool and launched the config tool. Then running the game again I got no update dialogue. Then I tried the same test but updating the sh2emodule version to 2.0.2024.0 and ran the game and it gave me the update dialogue again, and the update installed a different d3d8.dll, which naturally put me right back into the loop.

**Comment by nipkownix** [comment]
Hmm, something might be wrong with the d3d8 from the update server, then. My last build was built on vs2017 with the xp toolset, so no changes but the additional logging. Strange.

**Comment by Balthazor44** [comment]
Well now it appears to have magically fixed itself, because suddenly I can't duplicate the issue anymore, no matter what dll I try.

**Comment by nipkownix** [comment]
@elishacloud Any possibility of this being a weird caching issue? Could whatever API the module uses to download the .csv be using an older cache or something like that? 
Can't think of any other reason the issue could magically solve itself like that. Meh.

**Comment by Balthazor44** [comment]
It's completely baffling. It seems like it would likely be something specific to this machine, since my other one worked just fine, but whatever it might have been appears to have cleared itself up. Kinda makes this all feel like it was a total waste of time. I suppose I'll keep monkeying with it a bit to see if I can get it to happen again, but for now it seems like it's working fine.

**Comment by Polymega** [comment]
This same thing happened to me months ago when I was recording footage for Update Video #8. I "fudged the numbers" in my local .dat to make the tool think there was an update so I could record footage, and I believe that's what messed things up for me. The symptoms sound the same as what you were just experiencing.

Anyway, I don't think it was a waste of time. There's clearly _something_ going on here. In any case, you been doing excellent work with helping us test all sort of things, Balthazor. Thank you for that!

**Comment by elishacloud** [comment]
> @elishacloud Any possibility of this being a weird caching issue? Could whatever API the module uses to download the .csv be using an older cache or something like that?

I don't think this is a caching issue.  But either way hopefully the logging you added will help.

**Comment by filevans** [comment]
this is happening still

**Error: Download Failed

Couldn't download 'webcsv.url'.

The installation cannot continue.

Retry Download?**
