### ISSUE TITLE
How should I do to play at 60fps?

### ISSUE THREAD

**Issue by Renton881** [elishacloud/Silent-Hill-2-Enhancements#648]
Buenas, 

¿Cómo debo hacer para jugar a 60fps? He instalado correctamente todo pero AfterBurner me muestra 30fp/s...

**Comment by Polymega** [comment]
We recommend you play in 30 fps for now, as there are high framerate issues we are actively working to fix. If you still want to play at a higher framerate, [see here.](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#High_frame_rate)

**Comment by Renton881** [comment]
Oh thank you.

I will play at 30fps then.

Keep pushing guys, we wont this version to be better than new Unreal Engine 5 Remake ;)

**Comment by Polymega** [comment]
Thanks! You can keep track of 60 fps progress on this ticket: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/28
