### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Guapotoni** [elishacloud/Silent-Hill-2-Enhancements#649]
After updating the "update" message keep showing up after doing so, I've tried the recommended install as well, then made a backup of my save to not lose any progress and still nothing. The game works fine and runs well it's just a message that wasn't showing up before.

**Comment by Polymega** [comment]
Can you try this and see if the update loop still happens? [SH2EEsetup_1.1.0.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9892689/SH2EEsetup_1.1.0.zip)

**Comment by Guapotoni** [comment]
checking it out right

**Comment by Polymega** [comment]
Hold tight on that test. I'll let you know. Thanks.

**Comment by Guapotoni** [comment]
didnt work sadly, but fs lmk when it's ready i'll test it out.

**Comment by Polymega** [comment]
Okay. The next time you launch the Setup Tool you should receive a message that the tool itself needs to be updated. Let it update and see if that fixes the update loop issue.

**Comment by Guapotoni** [comment]
Will do. trying again right now

**Comment by Guapotoni** [comment]
same thing, sadly. game is working fine tho

**Comment by nipkownix** [comment]
Could you please upload your "SH2EEsetup.dat" file here, please? Should be in your game's directory.

**Comment by Guapotoni** [comment]
Sure thing.

**Comment by Polymega** [comment]
@Guapotoni 
At your earliest convenience, can you please upload the `SH2EEsetup.dat` file found in the game's main directory? Just click + drag the file onto into the text field here when you respond. Thanks!

**Comment by Guapotoni** [comment]
keeps saying it doesnt support the file

**Comment by Polymega** [comment]
You can right click the file and select Send To > Compressed (zipped) folder and upload the .zip file. Or, you can _make a copy_ of your `SH2EEsetup.dat` file and rename this file to `SH2EEsetup.dat.txt`. 

Thanks again for your help here

**Comment by Guapotoni** [comment]
[SH2EEsetup.dat.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894412/SH2EEsetup.dat.txt)
anytime!! had a bit of a headache getting an old MMO to work a while back so i know any help is appreciated anyways heres the dat

**Comment by Polymega** [comment]
Closing ticket. Feel free to re-open if you'd like further assistance.
