### ISSUE TITLE
The game doesn't use full screen space.

### ISSUE THREAD

**Issue by HerrSchiller** [elishacloud/Silent-Hill-2-Enhancements#65]
![sh2issue](https://user-images.githubusercontent.com/45268904/48915162-f98ead00-ee7d-11e8-9038-0778becbc067.png)
I have the problem that my Silent Hill 2 installation doesn't fully use my screen. I reinstalled everything 3 times now going by the Silent Hill Enhanced Guide. I run on Windows 10 64 bit and the game is installed on my C drive (not in the programs folder).

PC:

AMD Ryzen 5 1600
Geforce 970 (Using Wine3D)
16 GB RAM
Windows 10 64 Bit

**Comment by Polymega** [comment]
Hello,

Yes, your windowed game is definitely no centered on your screen. 

Can you please attach your `d3d8.ini` file here with the setting you're currently using?

**Comment by HerrSchiller** [comment]
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2608931/d3d8.zip)

Here it is. Also, should I update reshade to the latest version or could that potentially break things? I didn't mess with any reshade settings.

**Comment by Polymega** [comment]
Thank you for sharing your d3d8.ini file. Lastly, can you also take a screenshot of your installation directory for the game (so I can see all the files in there)? 

> Also, should I update reshade to the latest version or could that potentially break things?

It's best to leave it alone (not update) for the time being as I haven't tested the game with a newer version of ReShade yet. Also, unless absolutely required, there is no immediate need to upgrade ReShade for SH2 PC.

**Comment by HerrSchiller** [comment]
![folder 1](https://user-images.githubusercontent.com/45268904/48918641-40849e80-ee8e-11e8-8712-2ee9244e6363.png)

Do you need screenshots from the subfolders too or is that enough?

**Comment by Polymega** [comment]
> I should also mention that I'm using a multi-monitor setup. I have deactivated my second monitor in the Windows settings now, though. Could that have caused the problem?

No, it shouldn't. I also use dual monitors on my PC and that's never been an issue. 

> Do you need screenshots from the subfolders too or is that enough?

No, this is perfect. All your folders/files seem to be accounted for and correct. So there shouldn't be any issue there. 

The only thing that stood out to me as strange is your `d3d8.ini` file. First: The structure of all the fix options in that file are arranged oddly. [They should be arranged like this.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Common/Settings.ini) Although the arrangement of your fix options shouldn't affect anything. 

However, looking into your `d3d8.ini` file some more I noticed that you have the game set to NOT run in windowed mode. [Yet, your game is running windowed on the desktop image you shared.](https://user-images.githubusercontent.com/45268904/48915162-f98ead00-ee7d-11e8-9038-0778becbc067.png) That shouldn't happen? It's like there's another .ini file somwhere overriding your settings? 

Let's try this: 

1. [Download this work-in-progress build of the SH2 Enhancements mod.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2453473/d3d8.zip)
2. Replace the previous `d3d8.dll`, `d3d8.ini`, and `d3d8.dat` files with the new ones. 

See if that fixes things.

**Comment by HerrSchiller** [comment]
The game is still off-center after using the work-in-progress build. I think I'm now reinstalling the game step by step and test the game during each step starting with the initial unmodded installation. Maybe I can pinpoint at what point it starts to go wrong.

**Comment by AeroWidescreen** [comment]
> The game is still off-center after using the work-in-progress build. I think I'm now reinstalling the game step by step and test the game during each step starting with the initial unmodded installation. Maybe I can pinpoint at what point it starts to go wrong.

I wish more people took the time to do this. There's only so much we can do when someone isn't willing to spend time helping themselves. Anyway, it really does sound like something is causing windowed mode to enable when it shouldn't. If it still doesnt work, try disabling the widescreen fix in d3d8.ini:

>  [General]
> AutoUpdateModule = 1 
> d3d8to9 = 1
> UseCustomModFolder = 1
> WidescreenFix = 0

Also, if d3d8.dll prompts you for an update when you launch the game, make sure you select the second option: 
> INI files: replace all and discard settings

That should prevent the structure of the ini file getting messed up. I think it's a bug with modupdater. Keep in mind that this will discard your settings, so I suggest updating before editing the ini file.

**Comment by HerrSchiller** [comment]
So I got it to work as intended now. I had to reinstall Windows 10 because upon trying to install SH2 I got an error message that said I'm missing some support data. So I figured a clean install should do the trick. And now it works after I went though each step. I guess there was something wrong with my Win10 installation.

**Comment by Polymega** [comment]
> I had to reinstall Windows 10

Oh, wow. Sorry you had to go that extreme with the troubleshooting to fix the issue. I wonder what it ultimately was? In any case, I'm glad you got things fixed and as Aero stated: We appreciate you also taking the troubleshooting into your own hands. Typically there's only so much we can do on our end.

**Comment by HerrSchiller** [comment]
> > I had to reinstall Windows 10
> 
> Oh, wow. Sorry you had to go that extreme with the troubleshooting to fix the issue. I wonder what it ultimately was? In any case, I'm glad you got things fixed and as Aero stated: We appreciate you also taking the troubleshooting into your own hands. Typically there's only so much we can do on our end.

It's all good, I had planned to do a fresh install anyways. Thanks for the help!
