### ISSUE TITLE
Can no longer start game after update

### ISSUE THREAD

**Issue by tisaga** [elishacloud/Silent-Hill-2-Enhancements#650]
Hey I opened up the game to play some more and it told me there was an update available so I updated. Now after updating I can't load any saves nor can I start any new games with both the main and sub scenarios. I've tried repairing everything, reinstalling, nothing has worked.

**Comment by Polymega** [comment]
Do you mean that you can't see the main menu selections?

**Comment by tisaga** [comment]
I can get to the main menu and can use it normally but once I click continue or load a save or try to start a new game, the game freezes for a second and closes.

**Comment by Polymega** [comment]
Can you look over this ticket, follow its suggestions, and let us know: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/653

**Comment by tisaga** [comment]
Okay sorry for the wait, I looked at it and tried a bunch of the stuff recommended.

First off, I took out those files and ran the game and it was stuck on a black screen. I had trouble closing out of it, so this would suggest it's a problem with the base game files then yeah? Which is strange because it was working fine, I have a save about 2 hours into the game that's right after the Flesh Lips boss fight.

Anyway, I also tried a few of the fixes they recommended. I'll post the log files, sorry for not doing that earlier.

This is with no changes done, just running Enhanced Edition normally
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9896223/d3d8.log)

This is with the "use sh2e folder" option deselected (the game crashed before even getting to the main menu this time)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9896224/d3d8.log)

This is no widescreen fix
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9896227/d3d8.log)

Finally this is with the update in the zip folder EurikaDude provided and with default settings turned on
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9896233/d3d8.log)

All of those (except the "use sh2e folder" one as mentioned) crashed after selecting new game or loading a save. I did look at the logs a little bit and they seem to all have "GetDiskSpace Available disk space smaller than 2TBs: 1479867064" at the end.

Anyway hope this is useful and thanks for the help

**Comment by Polymega** [comment]
> All of those (except the "use sh2e folder" one as mentioned) crashed after selecting new game or loading a save.

Do you mean that the game ran and didn't crash at all when you did **not** use the `sh2e` folder? If so, please try the following next: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/659#issuecomment-1296371113

**Comment by tisaga** [comment]
No it crashed before getting to the main menu when I deselected "use sh2e folder" I'll look into that other ticket just in case though

**Comment by elishacloud** [comment]
Ok, I created an update that I hope can fix some of these issues.  Can you try this update?

Here is the update.  Unzip this into the Silent Hill 2 game folder overwriting the existing file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905745/d3d8.zip)

**Comment by tisaga** [comment]
Still gives the same issue sadly, here's the log for it just in case. I also tried a couple of the other fixes and they didn't seem to work either. Appreciate the effort though.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905893/d3d8.log)

**Comment by elishacloud** [comment]
I noticed that you are using the Nvidia card.  Have you tried switching the GPU to use the integrated (Intel??) card instead?  I just want to check if this is somehow related to the GPU.

**Comment by tisaga** [comment]
Sorry just got around to this, I don't have any spare cables for my integrated card (if the ports on the back are what they connect to) so I'll try it tomorrow or Thursday when I have the time and get back to you. I did want to ask, I would be able to find the previous update that I had installed before Friday right? Would reinstalling that update work?

**Comment by elishacloud** [comment]
> I would be able to find the previous update that I had installed before Friday right? Would reinstalling that update work?

The previous update is here:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2006.0

**Comment by tisaga** [comment]
Okay reverting to that update worked, I can play the game normally now. I can still try the GPU idea with the most recent update if you'd want.

**Comment by elishacloud** [comment]
If you have a chance can you try this update:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2027.0

**Comment by tisaga** [comment]
Same issue as before still, I attached the log in case maybe it helps. I will try swapping to the integrated graphics tonight and see what happens with the current update.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9941628/d3d8.log)

**Comment by elishacloud** [comment]
> I will try swapping to the integrated graphics tonight and see what happens with the current update.

No need.  I just wanted to make sure everything is working for you.

**Comment by elishacloud** [comment]
It looks like it is failing here:

```log
9908 16:08:37.801 GetDiskSpace Available disk space smaller than 2TBs: 1495777856
```

Can you try disabling the "Fix 2+ TB storage limit" feature?

![image](https://user-images.githubusercontent.com/25625456/200143109-af527430-becb-482d-b44c-6c5b1bd94243.png)

**Comment by tisaga** [comment]
Okay so I tried with the option on and off because I forgot to download the config exe. Sadly neither worked, logs are below.

This is without the fix.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9947219/d3d8.log)

This is with the fix.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9947225/d3d8.log)

**Comment by Polymega** [comment]
Closing ticket. Feel free to re-open if you'd like further assistance.
