### ISSUE TITLE
Out of range error

### ISSUE THREAD

**Issue by Moonwalwer** [elishacloud/Silent-Hill-2-Enhancements#651]
Im having a problem here, im dowloading this for the first time, when i run the setup tool and start installing it says "runtime error at 308:1926 out of range, what do i do?

**Comment by Polymega** [comment]
I am unsure of this error. Does restarting your PC alleviate the issue?

**Comment by Moonwalwer** [comment]
i somehow didnt think to do that lol, but it worked, thanks!
