### ISSUE TITLE
[Configuration Tool] Old version of SH2EEconfig.xml conflicts with new language system

### ISSUE THREAD

**Issue by IlDucci** [elishacloud/Silent-Hill-2-Enhancements#652]
I just used the official updater to update the base pack, and after that, I went to the Configuration tool, saw the new language selector, but when selecting a language I saw this:
![imagen](https://user-images.githubusercontent.com/5641681/198825221-a77df8ad-5803-449c-ae18-306481d5df34.png)
This happens only because I still have the old SH2EEconfig.xml next to the executable file. Deleting that file will solve the issue (and also let the Configuration tool actually change the language).

You might have problems with keeping this legacy file into consideration.

**Comment by Polymega** [comment]
> This happens only because I still have the old SH2EEconfig.xml next to the executable file. Deleting that file will solve the issue (and also let the Configuration tool actually change the language).
> You might have problems with keeping this legacy file into consideration.

Great point. I ran into this same issue myself a few months back. At least for now, the best way to view/approach an external XML file like this is to only use it for testing purpose when doing translation work. Once translated, a person can send their completed XML to us for proper integration (which also removes the external XML dependency).
