### ISSUE TITLE
Upon starting a game and selecting difficulty it just crashes

### ISSUE THREAD

**Issue by EurikaDude** [elishacloud/Silent-Hill-2-Enhancements#653]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894100/d3d8.log)
https://user-images.githubusercontent.com/116967768/198841674-da00a47a-a3df-4613-8b99-df4cd2a6067f.mp4

I was going to start a new game and had just downloaded it for the first time but all the times after i selected the difficulty for it, the game just crashed back to the desktop.  I got in once when i selected normal and normal but everything except James and his reflection was missing after which it crashed again. Id appreciate any feedback or help because i have a windows 11 with no GPU and was wondering if that was causing the problem, or is it a faulty version of the game?

**Comment by Polymega** [comment]
_Temporarily_ remove the following files from the game's main folder:

```
d3d8.dll
dsound.dll
dsoal-aldrv.dll
```

Do this game launch/play for you then?

**Comment by EurikaDude** [comment]
> _Temporarily_ remove the following files from the game's main folder:
> 
> ```
> d3d8.dll
> dsound.dll
> dsoal-aldrv.dll
> ```
> 
> Do this game launch/play for you then?

Yes it does but i think it just launches as the regular directors cut version since the enhanced edition menu wasnt there but i might be wrong, Do i have to do anything after this?

**Comment by Polymega** [comment]
Yes, what we're doing here is essentially testing the vanilla version to see if the issue lies with something in our project files. Did you test beyond the main menu? Did the bathroom load in correctly? Etc

**Comment by EurikaDude** [comment]
> Yes, what we're doing here is essentially testing the vanilla version to see if the issue lies with something in our project files. Did you test beyond the main menu? Did the bathroom load in correctly? Etc

Yeah it seems to be working fine and theres no issues with fps or things like that either.

**Comment by EurikaDude** [comment]
> > Yes, what we're doing here is essentially testing the vanilla version to see if the issue lies with something in our project files. Did you test beyond the main menu? Did the bathroom load in correctly? Etc
> 
> Yeah it seems to be working fine in vanilla and theres no issues with fps or things like that either.

i tried putting the files back in one by one and it seems that something in the d3d8.dll is causing the crashes

**Comment by Polymega** [comment]
Thanks for testing. I'll ping @elishacloud to see if he has any ideas about this one.

**Comment by EurikaDude** [comment]
> Thanks for testing. I'll ping @elishacloud to see if he has any ideas about this one.

thanks for your help anyway

**Comment by elishacloud** [comment]
We need to figure out which option is causing the issue.  Can you disable options in the SH2EEconfig.exe to see which option may be causing this issue?

**Comment by EurikaDude** [comment]
> We need to figure out which option is causing the issue. Can you disable options in the SH2EEconfig.exe to see which option may be causing this issue?

Disable the Fix advanced options right?

**Comment by elishacloud** [comment]
It is hard to say which option could cause the issue.

Here are some possible options, but it is best to try everything:
* Widescreen Fix
* Use custom "sh2e" folder
* High resolution text
* Use translated main menu text
* Run the game game in DirectX 9
* Etc.

**Comment by EurikaDude** [comment]
> It is hard to say which option could cause the issue.
> 
> Here are some possible options, but it is best to try everything:
> 
> * Widescreen Fix
> * Use custom "sh2e" folder
> * High resolution text
> * Use translated main menu text
> * Run the game game in DirectX 9
> * Etc.

tried them all and it seems that the "Use custom sh2e folder" was the one making the game crash, it works just fine after turning that off apart from the different menu screen.

**Comment by elishacloud** [comment]
Ok can you try with the update below?  Set all settings back to default in the SH2EEconfig.exe and then upload the log file.

Here is the update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894391/d3d8.zip)

**Comment by EurikaDude** [comment]
Sure but now with the default settings it crashes agian
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9894405/d3d8.log)

**Comment by elishacloud** [comment]
All the hooks look correct.  Try renaming the sh2e folder.  See if the issue still happens after that,

**Comment by EurikaDude** [comment]
> All the hooks look correct. Try renaming the sh2e folder. See if the issue still happens after that,

That works just fine apart from the menu being vanilla again but i think thats a more than tolerable compromise.

**Comment by elishacloud** [comment]
It looks like there may be some issues in the sh2e folder.  Can you try reinstalling everything again?

**Comment by EurikaDude** [comment]
> It looks like there may be some issues in the sh2e folder. Can you try reinstalling everything again?

sure but its gonna take a while

**Comment by Polymega** [comment]
Starting from the post in this thread that I linked, can you follow the steps outlined to see if this resolves your issue?

https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/644#issuecomment-1296313427
