### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by K5K5K5K5** [elishacloud/Silent-Hill-2-Enhancements#655]
Hi, the game does not start after installation. I can see only black window for 2 seconds and then close itself. When I select "Disable sh2e\pic\ path" in the settings, game starts normally.

This log is after installation when it's craching on start
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9895476/d3d8.log)

and this without sh2e\pic\
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9895481/d3d8.log)

**Comment by Polymega** [comment]
> and this without sh2e\pic
> [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9895481/d3d8.log)

It seems like it's crashing on when the `sh2e\pic\` folder is present. There is one main package that utilizes this folder, which is the Image Enhancement Pack. Open `SH2EEsetup.exe` found in the game's directory. This should run the tool in Maintenance Mode. On the main window, select "Install or Repair Packages" and redownload the Image Enhancement Pack. 

Upon repairing this pack, see if this issue persists.

**Comment by K5K5K5K5** [comment]
I've tried it several times and it doesn't help.

**Comment by Polymega** [comment]
What drivers did you update? GPU drivers or something else?

**Comment by K5K5K5K5** [comment]
I ran the driverbooster and installed everything, and there was a bit of it because the system was freshly installed and only had standard drivers that it installed itself. I also marked missing vc ++ packages there. 
I found this [Report.wer.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905482/Report.wer.txt) in `C:\ProgramData\Microsoft\Windows\WER\ReportArchive`

**Comment by elishacloud** [comment]
Ok, I created an update that I hope can fix some of these issues.  Can you try this update?

Here is the update.  Unzip this into the Silent Hill 2 game folder overwriting the existing file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905745/d3d8.zip)

**Comment by elishacloud** [comment]
> This log is after installation when it's craching on start
> [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9895476/d3d8.log)

This crash happened because the game could not get a [list of supported resolutions](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/91da303bf888edbd1b19794135097f8575beec25/Patches/Resolution.cpp#L396-L403).  I have never seen this before.  Seems like it was an issue with Windows.
