### ISSUE TITLE
Transitioning manual install to installer

### ISSUE THREAD

**Issue by Phononenom** [elishacloud/Silent-Hill-2-Enhancements#656]
Hi! So, not a bug or a real hard issue. I installed the enhanced edition during the chaos of the past week, despite all the server shenanigans (sorry that happened to y'all,) by manually downloading the files from the csv listing, as I can manually resume timed out downloads on a web browser instead of the installer timing out.

After the recent update of the main enhancements module, I figured out and made a SH2EEsetup.dat on my own from what I saw on another issue on here, which lets me finally use the maintenance mode and everything so I can update properly as things come out. I still have all my individual modules downloaded though, and I was hoping to set it up where it can use the local files. 

I understand there is a local_sh2ee.dat that is missing that can assist with that, would it be possible to see an example version of this file, with information on where to drop it (if not just the main folder?) Thank y'all for your time

**Comment by Polymega** [comment]
Hi there,
In the folder you chose to specific where the backup is placed, it would look like this:

![image](https://user-images.githubusercontent.com/27395260/198885614-4bcc0256-a4fb-46dc-808a-c167004402c0.png)

And the `local_sh2ee.dat` would look like this (I changed the version numbers to "#" for this demo):

```csv
# SH2EE local csv
id,name,fileName,version
setup_tool,SH2:EE Setup Tool,SH2EEsetup.exe,#.#.#
sh2emodule,SH2 Enhancements Module,SH2EE_Enhancements_Module_#.#.####.#.zip,#.#.####.#
ee_exe,Enhanced Executable,SH2EE_Enhanced_EXE_NA_v#.#.zip,#.#
ee_essentials,Enhanced Edition Essential Files,SH2EE_Essential_Files_#.#.#.zip,#.#.#
img_pack,Image Enhancement Pack,SH2EE_Image_Enhancement_Pack_#.#.#.zip,#.#.#
fmv_pack,FMV Enhancement Pack,SH2EE_FMV_Enhancement_Pack_#.#.#.zip,#.#.#
audio_pack,Audio Enhancement Pack,SH2EE_Audio_Enhancement_Pack_#.#.#.zip,#.#.#
dsoal,DSOAL,SH2EE_DSOAL_#.###.##.zip,#.###.##
xinput_plus,XInput Plus,SH2EE_XInputPlus_#.##.#.zip,#.##.#
```

**Comment by Phononenom** [comment]
Thank you! To make sure I understand this properly, when I launch the setup in the main game folder, this will use the web to update and "verifies" the current installed version, and when I launch the installer from my local saved module folder, it will launch it local mode, right?

**Comment by Phononenom** [comment]
So I put this copy of the .dat file next to the installer in my separate module folder. It is next to the zipped copies of all the different modules, all of which are installed except xinput plus (as I am using the fix in issue 168 for dualshock support through steam input, with only the keyconf.dat copied from the xinput plus folder.) 

My file looks like the following

`# SH2EE local csv
id,name,fileName,version
setup_tool,SH2:EE Setup Tool,SH2EEsetup.exe,1.1.0
sh2emodule,SH2 Enhancements Module,SH2EE_Enhancements_Module_2.0.2025.0.zip,2.0.2025.0
ee_exe,Enhanced Executable,SH2EE_Enhanced_EXE_NA_v1.0.zip,1.0
ee_essentials,Enhanced Edition Essential Files,SH2EE_Essential_Files_1.2.4.zip,1.2.4
img_pack,Image Enhancement Pack,SH2EE_Image_Enhancement_Pack_1.1.1.zip,1.1.1
fmv_pack,FMV Enhancement Pack,SH2EE_FMV_Enhancement_Pack_1.5.3.zip,1.5.3
audio_pack,Audio Enhancement Pack,SH2EE_Audio_Enhancement_Pack_2.0.4.zip,2.0.4
dsoal,DSOAL,SH2EE_DSOAL_1.31a.02.zip,1.31a.02
xinput_plus,XInput Plus,SH2EE_XInputPlus_4.15.2.zip,4.15.2
`

When I launch the setup in the main game folder, I get the expected maintenance mode, fully working as I used it to update the enhancement module. When I launch the setup in the module folder, I get a runtime error:
`Runtime error (at 241:599):

List out of bounds (1)
`

**Comment by Polymega** [comment]
> Thank you! To make sure I understand this properly, when I launch the setup in the main game folder, this will use the web to update and "verifies" the current installed version, and when I launch the installer from my local saved module folder, it will launch it local mode, right?

Yep. When ran inside the game folder, it'll run in maintenance mode and check online for updates.

When you run it through your local backup/"offline" folder it'll 
ask like it's a first-time install using your local copies of all the .zip files (pending you have the correct `.dat` file included in the folder).

> When I launch the setup in the main game folder, I get the expected maintenance mode, fully working as I used it to update the enhancement module. When I launch the setup in the module folder, I get a runtime error:

It sounds like this is happening because in your local .dat file it says XInput Plus was installed but it can't find that .zip package in the folder since you didn't install/need it.

You can change that line to: 

`xinput_plus,XInput Plus,notDownloaded,#.##.#`

...and it should fix things. (Again, the "#" part would be for whatever version it was when available for download or not.)

**Comment by Phononenom** [comment]
I just changed over the dat file, which I will upload this time. It's odd, because I do have the xinput zip downloaded. I will also upload a screenshot of the folder. I am still getting a runtime error after changing the dat file. The extension is changed to .txt here to support upload, but it is a .dat in the folder 
[local_sh2ee.dat.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9897173/local_sh2ee.dat.txt)
![screenshot](https://user-images.githubusercontent.com/64574232/198910522-11ffd5ee-2c1d-497f-ab34-9ff4fd60a44e.png)

**Comment by Polymega** [comment]
Huh... that's weird. Could it be those two line breaks at the end of your .dat file?

![image](https://user-images.githubusercontent.com/27395260/198910746-21d4d8a8-5d55-478b-8062-273fae245048.png)

**Comment by Polymega** [comment]
I think it is. Only include **a single line break at the bottom** and see if that fixes things.

**Comment by Phononenom** [comment]
Can't believe I didn't catch that! Works perfectly, thank you so much!
