### ISSUE TITLE
Crash when saving or loading

### ISSUE THREAD

**Issue by WazzurRr** [elishacloud/Silent-Hill-2-Enhancements#657]
The game runs well and everything works good but when I try to save it just crashes (for some reason quicksave doesn't crash), I interact with the saving thing and when the red screen appears it inmediately crashes, and from the main menu when I press Load Game it crashes too, everything else aside from this is perfectly fine

**Comment by Polymega** [comment]
From the specific post I linked below, can you follow the suggestions to try and let us know if it resolves your issues?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/644#issuecomment-1296313427
