### ISSUE TITLE
Cannot not uninstall. Mac wine.

### ISSUE THREAD

**Issue by klnn** [elishacloud/Silent-Hill-2-Enhancements#658]
I am running on mac using wine 6. There does not seem to be an uninstall option in SH2EEsetup.exe. 
It's not detected by wine unistaller either.

**Comment by Polymega** [comment]
I'm not sure if any of us on the team are using Mac with Wine or Parallels. 

However, our project doesn't create any registries or anything so, if push comes to shove, you can manually delete the project files from the game's folder. You can [refer to this directory tree](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree) to see what files are added to the game folder by our project.
