### ISSUE TITLE
Game Crashes during hospital cutscene with laura

### ISSUE THREAD

**Issue by RegionLocked123** [elishacloud/Silent-Hill-2-Enhancements#659]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9896777/d3d8.log)
During the cutscene in the hospital before the second boss fight the game will crash as it fades to black before james enters the examining room

**Comment by Polymega** [comment]
Launch `SH2EEsetup.exe` found within the game's main folder. This will launch the tool in Maintenance Mode. On the main window of this tool, select "Install or Repair Packages" and re-download the "Enhanced Edition Essential Files" pack and see if that fixes things.

**Comment by RegionLocked123** [comment]
I've tried that but the game is still crashing at the same point

**Comment by Polymega** [comment]
In the main game folder you'll see a `sh2e` folder. Temporarily rename this folder to something else. Does the game still crash at this spot?

**Comment by RegionLocked123** [comment]
its working now thank you very much. should i rename the folder back to its original name after the cutscene or is it ok to leave it changed

**Comment by Polymega** [comment]
I'd like to figure out what specifically is causing the issue. If you don't mind, rename the folder back to `sh2e`. Then, go inside this folder and temporarily rename the `bg` folder to something else. Does it still crash here?

If so, set `bg` back to its original name and then temporarily rename the `pic` folder to something else. Does it still crash here?

Let me know if renaming either of these folders fixes the crash. Be sure to rename them one at a time while testing so you can know which folder is the culprit.

**Comment by RegionLocked123** [comment]
its crashing after either of theses two changes it seems that changing the first sh2e is the only thing stopping it from crashing

**Comment by Polymega** [comment]
Okay next favor, please: Rename the `bg` and `pic` folder back to their original names. Go back to the main game folder and rename the `sh2e` folder to something else temporarily then make a new/empty folder named `sh2e`.

Does it still crash? I don't think it will, but I'd like to confirm. We have been getting a handful of similar issues like the one you're experiencing and I'm trying to find any correlation between all these tickets.

**Comment by RegionLocked123** [comment]
no it doesn't crash now

**Comment by Polymega** [comment]
Thanks for your help testing here. You can delete that empty/blank `sh2e` folder and rename the real `sh2e` back to that name.

Inside this folder you'll see other folders. You already tested temporarily renaming `bg` and `pic` to something else. If you don't mind, temporarily rename the other folders insider here, doing so one-and-one between tests until you determine what folder inside `sh2e` is causing the crash.

**Comment by RegionLocked123** [comment]
so I've been doing that one by one and reloading my save and I cant see that any of them are causing the crash anymore

**Comment by Polymega** [comment]
> so I've been doing that one by one and reloading my save and I cant see that any of them are causing the crash anymore

Interesting. So ultimately the `sh2e` folder is back to how it originally was? And now you're not experiencing crashes here any more?

**Comment by elishacloud** [comment]
Ok, I created an update that I hope can fix some of these issues.  Can you try this update?

Here is the update.  Unzip this into the Silent Hill 2 game folder overwriting the existing file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905745/d3d8.zip)

**Comment by Polymega** [comment]
Hi @RegionLocked123,
If you tried the new test build Elisha shared above this post, please let us know of its results. Thanks!

**Comment by RegionLocked123** [comment]
YEs sorry for the late reply. the build seems to have worked as there is no more crashes during gameplay
