### ISSUE TITLE
Game crashes on my way to Silent hill historical society

### ISSUE THREAD

**Issue by roldan1999** [elishacloud/Silent-Hill-2-Enhancements#660]
I have the key and everything to go to Silent hill historical society, but when I'm on the road arriving there my game closes. It must be because of the enhanced edition because I try playing without it and I can pass through.

**Comment by Polymega** [comment]
Hi there,

Did you install the project through the Setup Tool (`SH2EEsetup.exe`), or did you download the files from somewhere else such as a MediaFire/Mega/Internet Archive link?

**Comment by roldan1999** [comment]
Through the Setup Tool. I tried something I saw on another post and i changed the name on the folder "sh2e" and renamed "sh2e". Now it doesn't crash but all the street now it's black. I played without the enhanced edition, it works and when i entered the Silent hill historical society, i saved and restarted with the enhanced edition. It works that way, it only crashes that road.

**Comment by Polymega** [comment]
There's something really unusual going on and I'm not sure what's the cause at this time...

**Comment by Polymega** [comment]
Please upload a copy of your `d3d8.log` file here. Just drag + drop the file into the text field here as you respond. Thanks

**Comment by elishacloud** [comment]
Ok, I created an update that I hope can fix some of these issues.  Can you try this update?

Here is the update.  Unzip this into the Silent Hill 2 game folder overwriting the existing file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905745/d3d8.zip)

**Comment by Polymega** [comment]
Hi @roldan1999 ,
If you tried the new test build Elisha shared above this post, please let us know of its results. Thanks!
