### ISSUE TITLE
Game is still using 100% of one CPU core.

### ISSUE THREAD

**Issue by ilhass** [elishacloud/Silent-Hill-2-Enhancements#665]
Hello. I am using latest updates etc. Any way to fix this? Single core affinity is disabled in config.
![Screenshot 2022-11-04 10-03-10](https://user-images.githubusercontent.com/84805528/199912996-d9b7be3b-25ce-4664-be23-e671b9b1da6e.png)

**Comment by Polymega** [comment]
Please upload a copy of your `d3d8.log` file.

**Comment by ilhass** [comment]
Here it is 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9941105/d3d8.log)

**Comment by elishacloud** [comment]
I think this may be normal. The game does a lot of the work in one or two threads.  That is just the way the game engine works.  Whether that thread is distributed into multiple CPU cores or not has to do with your operating system.  That is not related to the game.  But as long as the game runs smooth at 30 FPS then everything is good.

BTW: that looks like some in-game display.  It may just be showing the data from the graphics engine not the other threads.  I recommend using Task Manager for this instead.  Just open it up and move it to a corner of the screen.  Then change the game's resolution to a smaller one so you can see Task Manager while your playing the game.

**Comment by ilhass** [comment]
> I think this may be normal. The game does a lot of the work in one or two threads. That is just the way the game engine works. Whether that thread is distributed into multiple CPU cores or not has to do with your operating system. That is not related to the game. But as long as the game runs smooth at 30 FPS then everything is good.
> 
> BTW: that looks like some in-game display. It may just be showing the data from the graphics engine not the other threads. I recommend using Task Manager for this instead. Just open it up and move it to a corner of the screen. Then change the game's resolution to a smaller one so you can see Task Manager while your playing the game.

I tried this and yes still 100% on 1st core and others are idling.

**Comment by elishacloud** [comment]
I think this may be normal. The game does a lot of the work in one or two threads.  That is just the way the game engine works.  Whether that thread is distributed into multiple CPU cores or not has to do with your operating system.  That is not related to the game.  But as long as the game runs smooth at 30 FPS then everything is good.

BTW: that looks like some in-game display.  It may just be showing the data from the graphics engine not the other threads.  I recommend using Task Manager for this instead.  Just open it up and move it to a corner of the screen.  Then change the game's resolution to a smaller one so you can see Task Manager while your playing the game.

**Comment by elishacloud** [comment]
Here is an example using Task Manager. You can see how when I start the game it uses more CPU time:

![image](https://user-images.githubusercontent.com/25625456/200051156-27f405b8-2338-41f3-b06a-1fdf059090d5.png)

**Comment by elishacloud** [comment]
Here is an example using Task Manager. You can see how when I start the game it uses more CPU time:

![image](https://user-images.githubusercontent.com/25625456/200051156-27f405b8-2338-41f3-b06a-1fdf059090d5.png)

**Comment by elishacloud** [comment]
Check your process affinity:

![image](https://user-images.githubusercontent.com/25625456/200052268-9554759c-76a6-4f31-9f5c-d1f84e6c9675.png)

![image](https://user-images.githubusercontent.com/25625456/200052298-fe179e78-2a56-4ec3-9024-8d6116d74165.png)

**Comment by ilhass** [comment]
> Check your process affinity:
> 
> ![image](https://user-images.githubusercontent.com/25625456/200052268-9554759c-76a6-4f31-9f5c-d1f84e6c9675.png)
> 
> ![image](https://user-images.githubusercontent.com/25625456/200052298-fe179e78-2a56-4ec3-9024-8d6116d74165.png)

Bingo! But resets to 1 again after restarting the game
![32d](https://user-images.githubusercontent.com/84805528/200053943-40b50ec4-3690-49f7-b9f9-8fc04ac61b4d.JPG)

**Comment by elishacloud** [comment]
Try renaming the d3d8.dll file and running the game again.

**Comment by ilhass** [comment]
No effect..

**Comment by elishacloud** [comment]
The issue is related to something other that our module.  You have something causing the game to use only a single processor.

**Comment by ilhass** [comment]
Other games programs working normally on all cores. Only SH2 don't. Real mystery.

**Comment by elishacloud** [comment]
It could be the version of SH2 you are using.  I would recommend competently removing it and reinstalling it.  Get it working correctly without any of the Enhanced Edition updates before adding the Enhanced Edition.

**Comment by ilhass** [comment]
Tried different versions of SH2, no luck. I tried everything, but then i just renamed sh2pc.exe and...its working on all cores for whatever reason. So the problem in windows don't know why its treating sh2pc.exe differently.

**Comment by elishacloud** [comment]
I suspect this is some compatibility setting.  Try following the steps [here](https://github.com/FunkyFr3sh/cnc-ddraw/issues/159#issuecomment-1147173520).

**Comment by ilhass** [comment]
> I suspect this is some compatibility setting. Try following the steps [here](https://github.com/FunkyFr3sh/cnc-ddraw/issues/159#issuecomment-1147173520).

It worked! Thank you so much! That issue drove me crazy.
