### ISSUE TITLE
Update DSOAL

### ISSUE THREAD

**Issue by justtoask** [elishacloud/Silent-Hill-2-Enhancements#666]
I noticed that DSOAL isn't up to date. Could you update it? The latest version is available [here](http://vaporeon.io/hosted/dsoal-builds/). And on a side note, I noticed that someone made a [HD Collection Voice Pack](https://www.moddb.com/mods/silent-hill-2-hd-voice-pack), and I've been wondering if you could include it in the installer, just disabled by default.

**Comment by Polymega** [comment]
### DSOAL
We haven't updated it for a while as more recent updates broke the radio static sound effect in the game. We last tested newer updates to DSOAL more than a year ago. Recently, user 3DJ (a 3D audio enthusiast) informed me that the latest versions of DSOAL should have fixed this issue. I tested on Win10 and confirmed everything works fine. I plan to do some quick tests on Win7. If all goes well, then yes, we will push out an update to DSOAL with the next project update.

### HDC Voices
There's two concerns with the HDC voices. The first is the more apparent one: The HDC is very controversial and divisive, so I don't feel comfortable at this time including it into the installer. However, when anyone asks about using these voices, I always redirect them to MarioTainaka's (the HDC voice pack creator) download for this pack at NexusMods.

The other concern is one most people don't think about: Providing gigabytes worth of project data for people to download has been a constant thorn in my side. I'm actually currently trying to find a new, suitable method to distribute these files moving forward (it's not as easy as uploading to Mega or something). So providing another pack that's ~1.2 GB would add on to this pain point.

**Comment by justtoask** [comment]
For the upload issue I would recommend uploading it to archive.org (so the files from the project would be safely preserved) and compressing them to 7z instead of zip.

**Comment by nipkownix** [comment]
> For the upload issue I would recommend uploading it to archive.org

archive.org's download speed is extremely slow, though. At least it has been for me.

**Comment by ElTioRata** [comment]
> > For the upload issue I would recommend uploading it to archive.org
> 
> archive.org's download speed is extremely slow, though.

Download speed is variable in my experience. It's usually better to download through the torrent that the site generates.

**Comment by Polymega** [comment]
Our next project update will include an updated version of DSOAL. Look forward to it whenever we release the next update in the near future! Thanks
