### ISSUE TITLE
`FullscreenImages` Bug

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#667]
When viewing a memo that utilizes a fullscreen image for its background, the fullscreen image doesn't appear to retain its scaling mode on subsequent viewings:

https://user-images.githubusercontent.com/27395260/200068561-ad2d6a2c-ba80-4aa3-9833-9186f4c2624b.mp4

Tested and this only seems to happen when viewing the fullscreen images through your memos list.

**Comment by elishacloud** [comment]
Did this happen with previous releases?  I changed how the caching works with the latest release.

Can you try this one and see if it works?  I disabled the caching here:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9942219/d3d8.zip)

**Comment by Polymega** [comment]
It does not do this in build [2.0.2000.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2000.0).

It also does not do this in the [test build you just sent here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9942219/d3d8.zip)

**Comment by elishacloud** [comment]
Ok, can you try with this one?  I tried to change the caching to fix this issue:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9942546/d3d8.zip)

**Comment by Polymega** [comment]
Quick tests look to be fine! I mostly tested the fullscreen images in the memos list, but also tested a few spots where fullscreen images are used within environments, as well.

**Comment by elishacloud** [comment]
This should be fixed here:  c33133366239098122d5f60ff6ce67b3bb2c9232

**Comment by Polymega** [comment]
Thank you, sir.
