### ISSUE TITLE
PS2 Silent Hill 2 Is it possible to default to controller type 2?

### ISSUE THREAD

**Issue by kiminru** [elishacloud/Silent-Hill-2-Enhancements#669]
![PCSX2 2022-11-09 오전 2_54_02](https://user-images.githubusercontent.com/84241069/200644948-78c2be56-be1e-4a49-97ea-981435df3dd1.png)
In Silent Hill 2 of the Korean version(The Korean version has no Korean language, as it is the North American version.), 
etc.mgf could not be extracted, so the CRC code (ex @:0000) 'SILENT HILL 2 File 01'
could not be found in the m_card_x_msg.mes, yeah translation failed. 
However, in North America version, the language of 'SILENT HILL 2 File 01' is output in Korean language.

![Slot_ 0 _ Speed_ 100% (59 93) _ NTSC _ Limiter_ Normal _ GSdx D3D11 HW _ 512x448 _ None _ Interlaced _ EE_   0% _ GS_   0% 2022-11-09 오전 3_02_34](https://user-images.githubusercontent.com/84241069/200644974-f668cd4d-5abb-49ea-aa2f-f078ef3f8b14.png)

Korean language patch inspection is almost finished.
Is it possible to disable (or remove) the Japanese language for language in the settings of PS2 Silent Hill 2
(North American version: SLUS_202.28)?

Korean has replaced the Japanese language, so if you set the Japanese language, all the characters are broken.
And is it possible to make the type 2 of the controller button settings default in the settings? 
Unlike North America and Europe, Korea is in Asia, so it is not Type 1 but Type 2. 
(ex: Silent Hill 3 and 4 were released in Korean.)

I've been looking for a way, but I can't seem to figure out how to do it.
The skills our team can do right now are just to change the OK key (X) to (O), which completely ruins the type 2 controller button layout.

1. Can I disable Japanese in settings or remove Japanese from settings? 
2. Can I set the controller button layout to default type 2?

https://drive.google.com/file/d/14KKhuh09HJoW51feJsiphdsrtfoxlZr2/view?usp=sharing
We shared our modified SLUS_202.28 file to Google Drive.

If anyone can help, please help us. T.T

**Comment by Polymega** [comment]
Have you successfully completed your Korean translation pack for the game? If so, we'd love to work with you to also include it for the PC project as part of our project. We would also work with you to create an HD Korean font sheet for the game.

**Comment by kiminru** [comment]
> Have you successfully completed your Korean translation pack for the game? If so, we'd love to work with you to also include it for the PC version as part of our project. We would also work with you to create an HD Korean font sheet for the game.

I've finished all the Korean outputs, but the Korean checks aren't perfect at the moment, but they're still good enough to play in Korean.  However, I haven't translated any of the languages that only exist in the PC version yet. If you want my work, I'll upload it. :)

**Comment by Polymega** [comment]
Oh nice! Glad to hear things are going well for the translation project. 👍 

> However, I haven't translated any of the languages that only exist in the PC version yet. If you want my work, I'll upload it. :)

I'm okay to wait until you have translated the extra PC text strings. Once you start on the PC version, I would be happy to help assist you and answer questions along the way. What's also really exciting is that we could make an HD Korean font sheet for your translation pack!

**Comment by kiminru** [comment]
This is a Korean string file. It's too late, the file I've given you is sufficient to be understood in Korean. 
Damn, South Korea is a really damn busy country. 
I can't tell you when, but I'll send you the final, hand-checked language file as well.




-----Original Message-----
