### ISSUE TITLE
Radio not working

### ISSUE THREAD

**Issue by zmarotrix** [elishacloud/Silent-Hill-2-Enhancements#67]
Maybe not the right place for this but it's the only place I could find to contact you.
I'm using the Audio Enhancement Pack 2.0.0 and when it's installed my Radio stops working. It's working for the first encounter but now once I get into town.

**Comment by Polymega** [comment]
Do you have the radio turned off/the volume turned way down by chance? Go to your inventory, select the radio, and you can toggle its on/off switch or volume.

**Comment by elishacloud** [comment]
Closing issue.  If this happens again you can reopen it.
