### ISSUE TITLE
Controller trigger bindings

### ISSUE THREAD

**Issue by Arikkusu** [elishacloud/Silent-Hill-2-Enhancements#674]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10005950/d3d8.log)
Not urgent, now that I've set the strafe buttons to L3 and R3, but it would be nice to be able to set the only two buttons I cannot...I'm using a Dual Shock 3 (with Steam and/or DS4 Windows) and I've tried every tip I could find (playing w/ and without steam, checking drivers, recalibrating, and some things I prolly forgot), even using my HORI Fighting Commander instead (only other USB controller is a fight stick of mine) but even then whatever equivalent to the trigger buttons is unable to be set.

Again, not urgent, but it would be nice if I could get some tips regarding my specific circumstances. I can do what I can to provide more information.

**Comment by Polymega** [comment]
I don't have a DualShock 3, but the DS4 works as a simple plug-and-play device with the project. With a DS4--which I believe is detected as a DirectInput controller--you don't need to use a Steam controller overlay or DS4Windows; you just plug it in and it'll work (minus vibration), even when XInput Plus is also installed in the game's directory.

> I'm using a Dual Shock 3 (with Steam and/or DS4 Windows) and I've tried every tip I could find (playing w/ and without steam, checking drivers, recalibrating, and some things I prolly forgot)

Have you tried using the DS3 without these extra programs like DS4Windows?

**Comment by Arikkusu** [comment]
Certainly, I've even tried all the input settings in the configuration exe (although I know that's for search cam movement).

**Comment by Arikkusu** [comment]
Oh, and I should note that search view works when I put on Xinput, not Dinput.

**Comment by Polymega** [comment]
> Oh, and I should note that search view works when I put on Xinput, not Dinput.

[Do you mean for the "Restore search camera movement" feature?](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#search-camera-movement-is-not-working-correctlyat-all-with-my-gamepad) If so, using DS4Windows spoofs Windows into think your DualShock (DirectInput) controller is an XInput controller, so that would make sense.

**Comment by Arikkusu** [comment]
Yea
Although now I've actually downloaded Xinputplus seperately for SH3, so I can try using that later I suppose...perhaps I misinterpreted something idk!

**Comment by Arikkusu** [comment]
Hmm well I managed to follow the directions needed to get it to work for SH3 (namely setting LT/RT to buttons 11/12; admittedly I should have looked further on the PCGamingWiki pages), so I tried the same options for SH2 (checking its own page to be sure, of course) but it's still not working. It's less urgent now that I'm playing through other games first of course, but it's worth noting in case anyone else runs into this I suppose.

**Comment by Arikkusu** [comment]
ACTUALLY, NEVERMIND
Turns out I've been plugging my controller into the wrong USB slot for DS4 Windows, didn't notice until I tried to use the triggers on SH3 lol. Now I can actually set the buttons in the options menu! I hope this helps anyone else...

**Comment by Polymega** [comment]
Glad you got it figured out! I'll close this ticket out then.
