### ISSUE TITLE
Game can't launch because of a dll error

### ISSUE THREAD

**Issue by Coldhaz** [elishacloud/Silent-Hill-2-Enhancements#675]
The files that are missing are MSVCP70.dll,binkw32.dll, and MSVCR70.dll does anyone have them

**Comment by Polymega** [comment]
Hi,
Did you download an ISO of the PlayStation 2 version of Silent Hill 2 instead of the PC version? Can you share a screenshot of your game's directory?

**Comment by Coldhaz** [comment]
![Desktop Screenshot 2022 11 17 - 17 24 43 56](https://user-images.githubusercontent.com/108432942/202573272-131a1c53-1e3c-4342-a029-d4f39e0dab6b.jpg)

**Comment by Coldhaz** [comment]
I did none of those and I am a certified dumbass

**Comment by Coldhaz** [comment]
I managed to fix the problem Thank you for your help
