### ISSUE TITLE
Erro na Dublagem do Brasil

### ISSUE THREAD

**Issue by Gabriel9806** [elishacloud/Silent-Hill-2-Enhancements#678]
Recentemente lançou a dublagem do silent hill 2 unhanced editon mas aa dublagem fica incompleta por que diz que se caso surgir alguma atualização do silent hill 2 unhanced é pra atualizar...
mas não pode atualizar os seguintes arquivos voice.afs sddata.bin
existe alguma solução pra resolver esse problema ?

**Comment by Polymega** [comment]
For our next project update, we will be introducing a new way to handle fan translation packs. Our new approach will help ensure fan translation files are not overwritten by SH2:EE project updates.

Until we release our next project update, you will need to re-download the PTBR fan dun and overwrite files as you originally did.

**Comment by matheusvb3** [comment]
@Gabriel9806 Instala a dublagem e não atualiza o Enhanced Edition caso peça para você fazer isso. Caso isso não funcione, dá para jogar o jogo com a dublagem e sem o Enhanced Edition (testei e funciona perfeitamente) ou baixar o patch para a versão de Play 2 e jogar no PCSX2. O Polymega (comentário acima) disse que no futuro eles vão modificar o Enhanced Edition para que caso saia uma atualização nova as traduções não sejam sobrescritas, mas por enquanto é só não atualizar que a tradução vai funcionar. Desde quando saiu a dublagem (março desse ano) até hoje não mudaram muitas coisas no mod Enhanced Edition, eles fizeram as cutscenes em vídeo terem uma resolução um pouco melhor e ajeitaram um bug de áudio que podia fazer o jogo travar.

**Comment by Gabriel9806** [comment]
Muito obrigado!! Se caso aconteça alguma coisa volto aqui.

**Comment by matheusvb3** [comment]
Tranquilo! Caso tiver algum problema, prende o grito.
