### ISSUE TITLE
RPT Closet Cutscene Fixes (Woodside Apt Rm 307)

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#68]
@AeroWidescreen

There's a possibility of four fixes that can be done during this cutscene. I have solutions for the first three: 

1. Restore missing lens flare during one camera cut.
2. Darken the closet bars and blur more during first person perspective.
3. Adjust room/dynamic objects for one shot (expiremental).
4. ~~Adjust the boundaries of the blur effect.~~ **FIXED VIA WSF MODULE**

------------------------

## DURING cutscene ID: 01F7A7C4 (4 bytes): **0000000E**

------------------------

### 1. Restore missing lens flare

![001](https://user-images.githubusercontent.com/27395260/49052114-860bd900-f1b8-11e8-8b50-2838835a1f8f.gif)

**One of two options available for this:** 

When cutscene camera position X 0094E064 (float) is set to -20902.57031:

Disable ReduceCutsceneFOV for this particular shot, or:

Description | Address | Original Value | New Value
-- | -- | -- | --
Cutscene camera position X | 0094E064  (float) | -20902.57031 | -20850.57031

The camera stays stationary during this part so this should be fine. The reason James' lens flare goes missing here is due to ReduceCutsceneFOV. If you'd like to keep ReduceCutsceneFOV active for this particular camera shot, adjust camera position X to the value mentioned above (also showcased in the .gif above) and it should restore the lens flare. However, I believe I recall Bigmanjapan saying it isn't easy to adjust camera positionings for cutscenes. So it may be easier to disable the FOV fix for this one shot.

------------------------

### 2. Darken & blur more closet bars

![002](https://user-images.githubusercontent.com/27395260/49260014-a8e0fc00-f409-11e8-9a19-9251c7472ee8.gif)

When cutscene camera position X 0094E064 (float) is set to -21376.56445:

Description | Address | Original Value | New Value
-- | -- | -- | --
"Time of Day" | 009428E2 (byte) | 11 | 15
Closet bar blur intensity | 005999CA (byte) | 3 | 7

IMPORTANT: Once this particular camera angle is changed/gone it must be set back to 11. (It doesn't reset on its own.) To play it safe (in case the address is ever used again elsewhere) it would be advised to change blur intensity back to 3 after this shot as well. 

------------------------

### 3. Adjust room/dynamic objects for one shot (expiremental values)

![003](https://user-images.githubusercontent.com/27395260/49052282-2661fd80-f1b9-11e8-9a99-79ba6709ffbe.gif)

When cutscene camera position X 0094E064 (float) is set to -20133.99805:

Description | Address | Original Value | New Value
-- | -- | -- | --
PC location textures + models colour R (set 1) | 00942A50 (float) | 0.150000006 | -0.2
PC location textures + models colour G (set 1) | 00942A54 (float) | 0.150000006 | -0.2
PC location textures + models colour B (set 1) | 00942A58 (float) | 0.150000006 | -0.2
PC location textures + models colour R (set 2) | 00942A70 (float) | 0.04500000179 | 1
PC location textures + models colour G (set 2) | 00942A74 (float) | 0.04500000179 | 1
PC location textures + models colour B (set 2) | 00942A78 (float) | 0.04500000179 | 1

IMPORTANT: Once this particular camera angle is changed/gone those values must be set back to their prior values. They won't reset on camera changes _during_ the remainder of the cutscene. If they're not changed back after this camera shot, the remainder of the cutscene looks very wrong. 

While the PS2 version is the bar we're aiming for we must also improve on and better the PS2 version when possible. As of right now, the closet door and characters are practically glowing neon during this one particular shot and it doesn't look right. So we can even out the dynamic objects' and room's levels for a more natural look. Once this particular camera angle is done, it goes back to defaults. 

I also spliced this adjustment with the rest of the cutscene (this video doesn't implement the other aformentioned fixes) to better illustrate: https://youtu.be/H-Vv0gmRia8

------------------------

### ~~4. Adjust the boundaries of the blur effect~~ **FIXED VIA WSF MODULE**
~~@Aerowidescreen there are portions outside of the closet bars that are blurred which shouldn't happen. About 2/3 over from the left there's a boundary line where the blur starts. It seems to be locked to the camera's position and enabling/disabling ReduceCutsceneFOV doesn't fix it. Can the boundaries of this effect be adjusted any? Video example: https://youtu.be/pQILkFTz6FY~~

![image](https://user-images.githubusercontent.com/27395260/49055548-f2d9a000-f1c5-11e8-98ec-e2f20985c59d.png)

**Comment by Bigmanjapan** [comment]
@Polymega 

Closet bars and blur effect are parts of the advanced filters, they can be enabled/disabled on the fly via sh2pc.exe+633408 (00A33408) byte address. 

From what I can tell, it's actually like this: 

![49055548-f2d9a000-f1c5-11e8-98ec-e2f20985c59d](https://user-images.githubusercontent.com/31383389/49153719-15e08d00-f349-11e8-822e-0d357fc08277.jpg)

Red area blur is applied to the closet bars while purple blur is not rendered as a part of the game's world but as a screen overlay. No matter how you change the camera angle during this part of the cutscene (when the closet bars and blur effect is invoked) the purple area blur will stay on the same place like an overlay.

Both of those blurs are powered by the same function, so if I corrupt it, purple area blur will disappear making closet bars blur not work too:

![default](https://user-images.githubusercontent.com/31383389/49154000-e5e5b980-f349-11e8-8359-e40ea44e7aa1.png)

I found addresses that control geometry of the closet bars (you can fully disable them by nulling all the values) but I doubt it will help much. Finding that overlay blur controls will take some time.

**Comment by Bigmanjapan** [comment]
So, I guess it happens because that blur overlay has a predefined size that is calculated for 4:3 resolutions and when 16:9 hack is activated that blur overlay is shifted to the left side of the screen dragging cutout section with it. 

sh2pc.exe+633480 (00A33480)  4 byte - blur overlay width
sh2pc.exe+633484 (00A33484)  4 byte - blur overlay height

Unfortunately, if you manually stretch the width of the blur area, then it stretches the visuals that we see through the blur.

**Comment by AeroWidescreen** [comment]
> Unfortunately, if you manually stretch the width of the blur area, then it stretches the visuals that we see through the blur.

I'll take a look at this later today.

**Comment by Bigmanjapan** [comment]
Random addresses: 

sh2pc.exe+1999CA (005999CA) byte — blur intensity
sh2pc.exe+6333D8 (00A333D8) byte (change from 1 to 0) — make blur less blurry (preset?)
sh2pc.exe+199754 (00599754) byte (change from 7 to something less) — disables closet bars outside of the blur wall
sh2pc.exe+1997E7 (005997E7) byte (change to 0) — Hotline Miami closet bars

**Comment by Polymega** [comment]
Also may help, provided by Bigmanjapan: 

> sh2pc.exe+63334A (00A3334A) byte 
> 
> This one controls internal game speed. Set it to, let's say, 150-200 to slow down the process (useful if you want to have more time to change something during a cutscene), 10-20 to speed up the game.
> While Cheat Engine's speehack function does similar thing, it operates on framerame and makes gameplay choppy while it's being slowed down. The game's internal speed control maintains smoothness of gameplay when slowed down.

Also, @Bigmanjapan , this is pretty exciting to see: 

> sh2pc.exe+1999CA (005999CA) byte — blur intensity

Because I'd imagine other effects throughout the game (such as depth of field and the fake bloom in the Hotel room) would also have such values present to change their intensities after all? It's just nice to see, for the closet effect anyway, that this can be adjusted through value changes like that.

**Comment by AeroWidescreen** [comment]
Thanks guys, that gamespeed address made this much easier to test. So I think the blurry bar is fixed... ?

`005995918 fild dword ptr []`

![blur](https://i.imgur.com/DdBia3u.gif)

**Comment by Polymega** [comment]
@AeroWidescreen with the advent on Bigmanjapan's closet blur intensity discovery I've revised my initial post to alter that as well as darken the bars. This brings it much closer to the PS2 version as seen [in this image](https://i.postimg.cc/jt4F7dRF/sh2ee-reflective-surfaces.jpg) (near the bottom).

**Comment by Bigmanjapan** [comment]
> This brings it much closer to the PS2 version as seen in this image (near the bottom).

While I was corrupting stuff, I once managed to make RPT pyramide to reflect lightning. What is interesting that, in addition a shadow of Great Knife appeared next to his right hand, I'm not sure but it looked like it started using some assets from Blue Creek cutscene. 

Maybe his ability to reflect lightning isn't present in the assets in the mannqeuin scene? Like the eyes issue discussed in the other thread.

**Comment by Polymega** [comment]
> What is interesting that, in addition a shadow of Great Knife appeared next to his right hand

Oh wow, that's a remnant of a [pre-release build of the game](http://www.igotaletter.com/rarities/prerelease/):

![image](https://user-images.githubusercontent.com/27395260/49290727-bdf37480-f475-11e8-8996-1bc8c34934a9.png)

> Maybe his ability to reflect lightning isn't present in the assets in the mannqeuin scene? Like the eyes issue discussed in the other thread.

I'm hoping, if this is the case for many areas, that the specular effect and cube map [can be called in](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/66#issuecomment-442524366) before being written as FrozenFish24 suggested.

**Comment by Polymega** [comment]
I'm not sure if James ever has reflection in his eyes on the PC version but Pyramid Head does for his helmet during the cutscene/fight on the apartment stairway.

**Comment by AeroWidescreen** [comment]
@Bigmanjapan I just realized I posted the wrong memory address for the blur fix, sorry. I edited my original post above. I've also opened on an issue about this problem [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues/578) since the widescreen fix is what needs to be updated.

**Comment by Bigmanjapan** [comment]
@AeroWidescreen Thanks! That nine digit address puzzled me for a bit initially.

**Comment by Polymega** [comment]
(Removed this post from the other thread)

@elishacloud , the SH2 WSF has received an update which you can now grab here: https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/sh2

This fixes # 4 found in the first post of this thread: #68

^ Because that specific fix is related to playing in widescreen Aero passed it to ThirteenAG and the WSF project.

**Comment by elishacloud** [comment]
Thanks @Polymega.  I will add the updated WSF to the build.

**Comment by Polymega** [comment]
Wonderful work everybody! This cutscene is looking better than ever now!

An update has been released with this fix in it. See [v1.3.1340.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1340.0)

**Comment by Polymega** [comment]
Hi Elisha, 

A change for the `ClosetCutsceneFix`: 

[For this part of the code](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/ClosetCutscene.cpp#L136-L157) we set `Closet bar blur intensity - 005999CA (byte)` to `7` during this camera cut then restore it back to `3` upon either a new camera angle change or cutscene end.

A YouTube comment pointed out an issue with this solution: 

![image](https://user-images.githubusercontent.com/27395260/60777023-17074300-a0fe-11e9-85a6-dcdc18e969e5.png)

It seems the game only renders the blur pass within the camera boundaries and not past it any, so the blur "bends in" on itself near the camera projection edges. 

**To fix this:** 

- Drop the `Closet bar blur intensity - 005999CA (byte)` part of the fix (but keep the `Time of Day - 009428E2 (byte)` part of the fix during this camera angle cut intact).
- Replace the dropped part with: 
   - During this camera angle cut set the following:
      - `00631614 (float)` to `1.5` (one write, no constant iteration)
      - `00633460 (float)` to `-1.5` (one write, no constant iteration)
   - On camera angle change or upon cutscene ID end, set:
      - `00631614 (float)` to `0.3333333433` (one write, no constant iteration)
      - `00633460 (float)` to `0.6666666865` (one write, no constant iteration)

So the stipulations for when these addresses change/go back is the same as the current `Closet bar blur intensity - 005999CA (byte)`, we're just dropping that address fix and using two others in its place.
