### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by metorikku04** [elishacloud/Silent-Hill-2-Enhancements#681]
I downloaded the base game from My Abandonware (https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd).
Then I downloaded the Setup Tool for the Enhanced Edition.
I clicked sh2pc and SHEE2config to open it. It showed a black screen for a few seconds then switched to white screen which later gave an error.
How do I fix this?
P.S. I'm using Windows 11
![image](https://user-images.githubusercontent.com/119971215/206006237-65d3fb51-30f9-4f0b-b930-0b213739fe1f.png)

**Comment by metorikku04** [comment]
I made a folder and named into SILENT HILL 2 to put the stuff in
I placed in C:Windows/SILENT HILL 2

**Comment by Polymega** [comment]
Yes, but do you have a `data` folder in this directory (the image you shared)?

**Comment by Polymega** [comment]
Okay, you'll need this folder as it contains all of the files the game uses to run. Without this folder, the game will not run. This folder would have been included with the download of the base (vanilla) game you got from MyAbadonware, so I'm not sure what happened to it.

Here's what you can do:
1. Redownload the base (vanilla) game from MyAbandonware.

I would recommend extracting the files from this download to a _local_ user directory such as `C:\Users\<your-username>\Games\Silent Hill 2\` or `C:\Users\<your-username>\Documents\Silent Hill 2\`. I would **not** recommend placing the game in `C:\Windows\Silent Hill 2\` as you've done.

2. Once you've redownloaded the base (vanilla) game to a local user directory, you can then copy + paste all of the files/folders currently in your `C:\Windows\Silent Hill 2\` folder to this new location.

**Comment by metorikku04** [comment]
Is it called something like KONAMI

**Comment by Polymega** [comment]
Try following the steps I mentioned above. If you do not have a `data` folder within your `Silent Hill 2` folder the game will not run.

**Comment by metorikku04** [comment]
So I just copy and paste everything shown in the image currently in C:\Windows\Silent Hill 2\ to the new location?

**Comment by Polymega** [comment]
Yes, but first you need to re-download the base (vanilla) game through MyAbandonware. 

Re-download the package from MyAbandonware, extract its files to a new location, _then_ move all of the files from `C:\Windows\Silent Hill 2\` to this new location.

**Comment by metorikku04** [comment]
I want to place in my documents. Do I need to make a new folder within it?

**Comment by Polymega** [comment]
Move all of those files and folders into that `Silent Hill 2` folder, then share a new screenshot of your folder with everything in it.

**Comment by metorikku04** [comment]
It displayed this message when I tried to moved them all into the folder. Should I replace the files?

**Comment by Polymega** [comment]
Yes, replace files.

**Comment by metorikku04** [comment]
I did that. Now what do I do?

**Comment by Polymega** [comment]
Move all of those files and folders into that `Silent Hill 2` folder, then share a new screenshot of your folder with everything in it.

**Comment by metorikku04** [comment]
![image](https://user-images.githubusercontent.com/119971215/206020936-1526095f-96aa-46a8-a3d7-b4edaa4d16a2.png)

**Comment by Polymega** [comment]
Everything looks to be in order. Trying launching `sh2pc` now.

**Comment by metorikku04** [comment]
Is it alright if the SH2EEsetup is there (as shown in the image)?

**Comment by Polymega** [comment]
Yes, that is fine.

**Comment by metorikku04** [comment]
You are such a lifesaver! I cannot believe it when I saw the Konami symbol first pop up. This issue has been bugging me for 2 days so thank you for your support. I can't wait to play and record this phenomenal game.
![Silent Hill 2_ Enhanced Edition 06_12_2022 20_58_20](https://user-images.githubusercontent.com/119971215/206022669-ebbe48e5-2e84-422e-87aa-dbec0793173f.png)

**Comment by Polymega** [comment]
Glad to hear it! I will close out this ticket. You can remove that empty `C:\Windows\Silent Hill 2\` folder since you have moved everything out of it.

**Comment by metorikku04** [comment]
Sure thing!
