### ISSUE TITLE
Disk apparently too full

### ISSUE THREAD

**Issue by gdtharpe** [elishacloud/Silent-Hill-2-Enhancements#684]
During the setup, near the end, when it completes, I get an error saying "disk too full", followed by another one that says "out of range." I have 34 GB of space on my drive, so this shouldn't be happening. I confirmed this by downloading an unrelated game from my steam library.

**Comment by Polymega** [comment]
@nipkownix 
Would you be able to lend any thoughts on this?
Thanks for any help here!

**Comment by nipkownix** [comment]
Hmm, not sure what could cause this.
@gdtharpe, what is the full path to the directory your copy of Silent Hill 2 is installed?

**Comment by gdtharpe** [comment]
It's in (D:)/Games/Silent Hill 2

**Comment by Grey421** [comment]
bumping this, i'm facing more or less the exact same problem except it triggers about halfway through

**Comment by Polymega** [comment]
The way this works is that the download essentially makes two copies of itself; one for it to download to a temporary directory and another to extract it to its final destination.

Near the start of installation, try selecting "Install and Backup Enhancement Packages." This will only make "one" copy of itself:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/8cd06979-4667-4e0a-b96b-0ff7467f38f5)
