### ISSUE TITLE
Audio Hooking Issue

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#686]
This appears to be affecting all audio: SFX, BGM, and Dialogue.

With the new hooking methods, the game doesn't seem to be using audio from the `sh2e\sound\` directory. However, the game also doesn't seem to be using the vanilla sound files, either. It seems like it's using a cache of these files from a virtual Windows directory?

I tested and confirmed this is happening with the latest release build. I then tested a build before the new hooking method ([2.0.2006.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2006.0)) and the issue is not present there.

**Comment by Polymega** [comment]
Some more notes on the matter: 

- SFX (`sh2e\sound\sddata.bin`) are **NOT** affected by this.
- Dialogue (`sh2e\sound\voice\voice.asf`) **IS** affected by this.
- BGM (`sh2e\sound\*\*.aix/adx`) **IS** affected by this.

If the `sh2e\sound\` directory doesn't exist, the game will use the vanilla audio files. 

However, if this directory exists, the game is pulling the BGM and dialogue audio from... somewhere else. I'm not sure where. Probably a virtual directory?

**Comment by Polymega** [comment]
Here is a test `sound` folder to use. Just make sure you back up your real `sh2e\sound\` folder first: 

www.igotaletter.com/temp/sh2pc/SH2EE_Sound_Random_Audio_Test_Files.zip

With this test folder...

- **SFX** are low quality audio of a woman saying different numbers. (example: `sddata014` is her saying "fourteen.")
- All **Dialogue** is of a man saying, "this is a test."
- All **BGM** is a ~10 second sample of Mining Melancholy from Donkey Kong Country 2.

**Comment by Polymega** [comment]
It has something to do with `EnableCriWareReimplementation`. When this feature is disabled, the game correctly pulls audio files from their intended locations.

**Comment by Polymega** [comment]
> However, the game also doesn't seem to be using the vanilla sound files, either. It seems like it's using a cache of these files from a virtual Windows directory?

The game _is_ pulling from the `data` folder. So, using the new hooking method and with `EnableCriWareReimplementation` enabled, this is what's happening:

- SFX (`sddata.bin`) is being pulled from the `sh2e` folder.
- Dialogue (`voice.asf`) is being pulled from the `data` folder.
- BGM (`sound\*\*.aix/adx`) is being pulled from the `data` folder.

... and now this is making more sense, as Gemini never touches the SFX files with his Criware solution, iirc. In vanilla SH2 PC, only the BGM and dialogue files would bug out, so this is what Gemini fixed.

**Comment by mercury501** [comment]
So me and @Polymega were digging around and found out that the way the new criware implementation opened files accessed only the original data folder and not the sh2e folder, here is my suggested fix for this issue:
[criware_fix](https://github.com/mercury501/Silent-Hill-2-Enhancements/blob/96172e38e90a6d2096757ab6d735ba29c8ea17d2/Include/criware/criware_file.cpp#L19)

Do you think it's an appropriate solution? @Gemini-Loboto3 @elishacloud 
Thanks!

**Comment by elishacloud** [comment]
@mercury501, thanks for looking into this and finding the issue!  However, I would not recommend calling the handler directly.  Instead I made a function for that.  I would recommend this code here:

```c++
HANDLE ADXF_OpenFile(const char* filename)
{
	char tmpfilename[MAX_PATH];
	return CreateFileA(GetFileModPath(filename, tmpfilename), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_READONLY /*FILE_ATTRIBUTE_NORMAL*/, nullptr);
}
```

I have attached a test build that I hope @Polymega can test and make sure it works.  If this works then I will check it in.

Here is the build:  
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10355601/d3d8.zip)

**Comment by mercury501** [comment]
Seems to work fine to me!

**Comment by elishacloud** [comment]
Great.  Thanks @mercury501.  This issue should be solved now.

**Comment by Polymega** [comment]
Yep! It's resolved now. Thank you so much, Elisha.
