### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by ArkadKud** [elishacloud/Silent-Hill-2-Enhancements#688]
Hello does someone know why my game just have black screen and crash for 2 seconds on launch?

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10303761/d3d8.log)

**Comment by Polymega** [comment]
Are you trying to play the game with a controller? If so, disconnect the controller from your PC to see if it'll launch correctly. 

If, in particular, you're trying to use a DualShock 4 or DualSense controller, read this portion on the site: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

You can also check and ensure you don't have any other peripherals that are plugged into your PC that might be detected as gamepads which could be creating conflicts with the game when launching.

**Comment by ArkadKud** [comment]
tried disconnecting my controller but its still crashing 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10304698/d3d8.log)

**Comment by Polymega** [comment]
Open `SH2EEconfig.exe` in the game's folder and, on the first window under "DirectX", uncheck "Run the game in DirectX 9". Then click "Save & Launch Game". Does the game boot for you then?

**Comment by ArkadKud** [comment]
nope still crashing

**Comment by Polymega** [comment]
Try these two things next:

_Temporarily_ remove `d3d8.dll` from the game's folder. This will essentially have you playing the original/vanilla version of the game. Does the game launch for you? If so...

Place `d3d8.dll` back in the game's folder. Then, launch `SH2EEconfig.exe` and uncheck/disable everything. Does the game launch for you? If so...

Start enabling everything on a per-tab basis within `SH2EEconfig.exe`. For example: Enable everything on the first tab/page ("Display") then launch the game. If it launches, close the game then enable everything on the next tab/page. Keep doing this until the game no longer launches for you. By doing this, you can start to pin-point what fix/feature is causing the game to not launch for you.

**Comment by ArkadKud** [comment]
well the moment i put the file back it starts crashing even with everything disabled so i'll just reinstall the game or something

**Comment by eglatz27** [comment]
Having this exact issue. Everything disabled and still errors
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12667354/d3d8.log)

**Comment by elishacloud** [comment]
It seems to be crashing while searching for gamepads.  Try removing `dinput8.dll` and setting the following item in the ini file:

```ini
HookDirectInput = 0
```

**Comment by Polymega** [comment]
Closing ticket. Feel free to re-open if you'd like further assistance.
