### ISSUE TITLE
No player Icon on the map

### ISSUE THREAD

**Issue by OhBoyTomato** [elishacloud/Silent-Hill-2-Enhancements#690]
Hello!

So I started my journey with the game. Everything's works well, but there is one thing that I cannot fix - James is not visible on the map (any). I was looking through solution on the Internet, but I couldn't find anything (besides many spoilers...).

Do you know how to fix this issue?

Thank you in advance!

**Comment by Polymega** [comment]
Did you download a translation pack for the maps and other images? Please refer to this post for troubleshooting: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/556#issuecomment-1176530353

**Comment by OhBoyTomato** [comment]
I did. But, following instructions on troubleshooting post #556 , I have managed to fix the issue (I disabled the Image Enhancement Pack). 

I'm sharing this solution: "Disable the Image Enhancement Pack. This will use the original, low resolution vanilla PC textures. You can disable this by opening the Configuration Tool and enabling Disable "sh2e\pic" path (found under the "Advanced" tab)".

Thank you for your help.
