### ISSUE TITLE
"SH2_Enhanced_EXE_NA_v1.0.zip is corrupted"

### ISSUE THREAD

**Issue by silentshill** [elishacloud/Silent-Hill-2-Enhancements#699]
When I attempt to install the enhanced edition, I get this popup just as the download finishes.

Error: checksum mismatch.

File 'SH2_Enhanced_EXE_NA_v1.0.zip' is corrupted.

The installation cannot continue.

I tried again and got the same error, and so I am reporting the issue to the developers. This happens even if I uncheck everything that isn't essential. I've googled around and can't find evidence of anyone else having this issue. Thank you for all of your hard work!

**Comment by Polymega** [comment]
Thanks for the quick ticket on this! This was an error on my part with file management. Can you please try it again? It should be fine now.

**Comment by silentshill** [comment]
no, thank YOU for the quick followup. Works like a charm now.
