### ISSUE TITLE
Error: SH2EE_FMV_Enhancement_Pack_1.5.3.zip is corrupted

### ISSUE THREAD

**Issue by strifeknot** [elishacloud/Silent-Hill-2-Enhancements#704]
![sh2 error](https://user-images.githubusercontent.com/124281443/216366124-335448a3-d64f-4694-a8c9-dda99a55436f.jpg)
I keep getting this error during download. There's plenty of available space on my drive, and I've restarted the computer, but the error continues to pop up.

**Comment by Polymega** [comment]
Sorry you're having issues. I just checked the SHA256 checksum and it's correct to the file that's being downloaded. I also ran the tool myself and was able to download the FMV Pack.

However, I have just removed the checksum requirement for installing the package. Please try again, when possible.

**Comment by strifeknot** [comment]
That took care of the problem. All files were successfully downloaded and installed. Thanks so much.
