### ISSUE TITLE
White Screen upon launch when trying to use widescreen fix

### ISSUE THREAD

**Issue by thedeverwhoa** [elishacloud/Silent-Hill-2-Enhancements#71]
First off, thanks so much for your guys' constant work on this, you guys rock and this is an awesome game!  So I've just installed sh2 and I'm trying to run it with the widescreen fix.  I've looked at similar discussion posts and nothing suggested have worked for me.  I'm using a GTX 970 and I'm not using the Nvidia wine fixes at all, but instead the new versions of stuff.  changing core affinity does nothing but whenever I turn widescreenfix - 0 It launches fine but of course w/o the fix.  Just not really sure what to do at this point as it seems I've tried everything you guys have suggested.  Thx for the help!
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2655475/d3d8.log)

**Comment by Polymega** [comment]
Hi @thedeverwhoa , 

Sorry you're having troubles. Can you also share your `d3d8.ini` file exactly as you have it whenever the white screen issue occurs?

**Comment by thedeverwhoa** [comment]
sure!
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2655609/d3d8.log)

**Comment by Polymega** [comment]
@AeroWidescreen I recall you mentioning you know why the order of the d3d8.ini settings can become different than normal? Would whatever caused that have any bearing on why thedeverwhoa can't run the WSF?

**Comment by AeroWidescreen** [comment]
> Would whatever caused that have any bearing on why thedeverwhoa can't run the WSF?

I don't think so, no. The other problem has something to do with the [modupdater](https://github.com/ThirteenAG/modupdater) module, also referred to as "AutoUpdateModule" in the ini file. It shouldn't affect anything else.

I'm not sure why @thedeverwhoa is having trouble. Maybe he could try installing it manually? You know, he disables the widescreen fix module and enables the LoadPlugins feature. Then he downloads the WSF asi from here: https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/sh2

At that point all he has to do is drag and drop the scripts folder to his Silent Hill 2 folder while ignoring dinput8.dll. Apparently doing that worked for someone here, I don't remember who though.

**Comment by thedeverwhoa** [comment]
@AeroWidescreen yeah I tried that as well, didn't work out using the Scripts folder either :/

**Comment by AeroWidescreen** [comment]
> yeah I tried that as well, didn't work out using the Scripts folder either :/

Did it crash? What happened exactly? And you disabled the widescreen fix in d3d8.ini, right?

**Comment by thedeverwhoa** [comment]
@AeroWidescreen same thing that usually happens with the widescreen fix enabled, pops up a white screen for a few seconds and then immediately crashes.  
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2683054/d3d8.log)

**Comment by thedeverwhoa** [comment]
@AeroWidescreen same thing that normally happens for me with widescreen fix enabled, pops up a white screen for a few seconds and immediately crashes.  (totally did not mean to close the thread by the way, my bad!)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2683055/d3d8.log)

**Comment by elishacloud** [comment]
Closing this out.
