### ISSUE TITLE
Error _BinkSetSoundtrack@8

### ISSUE THREAD

**Issue by Joseto3011** [elishacloud/Silent-Hill-2-Enhancements#716]
Hello, when I open the game it tells me, _BinkSetSoundtrack@8. I have done everything, any solution?

**Comment by Polymega** [comment]
Typically, in situations like this, one of two things is happening:

1. A user has downloaded our project files but has not downloaded the base (vanilla) SH2 PC game.
2. A user has mistakenly downloaded an ISO of the PS2 version of SH2, and not the PC version.

Can you share a screenshot of your folder where all of the SH2 files are housed in?

**Comment by Joseto3011** [comment]
![image](https://user-images.githubusercontent.com/126119564/220777799-781f8033-4937-4e28-8ed8-42bc65b07081.png)
![image](https://user-images.githubusercontent.com/126119564/220777835-38b2ccff-9d3e-445d-a52d-dd2dbb4e454b.png)

**Comment by Joseto3011** [comment]
Don't worry, I have already solved the problem, I was missing the vanilla version to play, thank you very much for your attention

**Comment by Polymega** [comment]
Glad it was an easy issue to sort out. [You can grab the base game from here.](https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download) Download the "fully extracted version" then unzip its contents into the SH2 folder.

**Important:** Do not transfer over the vanilla game's `sh2pc.exe` file. It has DRM in it which is blocked by all modern Windows operating systems. If you already accidentally did this, run the Setup Tool (`SH2EEsetup.exe`) found in the SH2 folder and select "Install or Repair Packages" and redownload the "Enhanced Executable".

![image](https://user-images.githubusercontent.com/27395260/220787988-610da721-d7c0-4c9d-9ec2-944149076ede.png)
![image](https://user-images.githubusercontent.com/27395260/220788011-a305a427-cd33-4b67-9dde-548504c3f831.png)
