### ISSUE TITLE
Replacing characters in font sheet for use with prospective Turkish fan translation language pack

### ISSUE THREAD

**Issue by oz-orz** [elishacloud/Silent-Hill-2-Enhancements#718]
Greetings,

I want to contribute to your project by writing up a Turkish translation. I have found the [Language Translation Guide](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#) and it guided me to open an issue here.

The Turkish alphabet has six accented characters: `ç,ğ,ı,ö,ş,ü` and their uppercase counterparts `Ç,Ğ,İ,Ö,Ş,Ü` (technically `ı` and `İ` are different letters but the substitution will work perfectly fine for my purposes here). All other Turkish characters are included in the English alphabet, although the script might also require the use of â (an accented variant of a and not a letter unto its own). Turkish also does not have w, q or x.

All told I will be replacing seven special characters in the font sheet. I would like to learn more about the process, and would love to hear recommendations on which language to replace.

**Comment by Polymega** [comment]
Hi there,
Another Turkish user @Tanshaydar has been working on a Turkish translation pack. [You can visit this ticket to see progress on it.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/234) It includes a translated HD main menu and Turkish font sheet.

Tanshaydar is wanting to go back and review his work as some users have reported typos and missing translations ([see here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/234#issuecomment-1279722635)). Perhaps you two can work together to finish the translation already started?

For recommendations on which language to replace: You should replace any Latin language that isn't English. So French, German, Italian, or Spanish are good to replace.
