### ISSUE TITLE
SH2EEsetup Error outdated Version

### ISSUE THREAD

**Issue by c7r4x** [elishacloud/Silent-Hill-2-Enhancements#719]
First thanks for all the work provided here. <3

But I get an error with the SH2EEsetup downloaded through the website.

Error: Outdated Version
The SH2:EE Setup Tool must be updated in order to use.
Update the Setup Tool?

And when I proceed, I get this :

Error: Invalid components list size
The installer should be updated to handle the new components from 'sh2ee.csv'

Kinda strange

Thanks a lot

**Comment by Polymega** [comment]
Apologies for the inconvenience. If you have been previously using our project, please manually download the updated Setup Tool (SH2EEsetup.exe) from our project site at [https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE) and place the tool in the game's directory. Launch the Setup Tool, select "Update Packages" and proceed from there.

**Comment by c7r4x** [comment]
Thanks for the quick aswer.

Unfortunatly, the error comes from the setup I've just downloaded right now through your website.
On a fresh install by the way

**Comment by Polymega** [comment]
Can you try clearing your browser's file/image cache then redownloading the tool from that link?

**Comment by c7r4x** [comment]
Nice one man.

Download the file through another browser did the trick.

Thanks a lot for helping me.
<3
