### ISSUE TITLE
Extra difficulty?

### ISSUE THREAD

**Issue by bigdeb** [elishacloud/Silent-Hill-2-Enhancements#72]
Hey all, just found out about this great mod. Amazing job! Do you know if there's any way to modify the save files so that extra difficulty can be unlocked without beating the game over and over again?

**Comment by bigdeb** [comment]
That totally works too! Hard difficulty please. Thanks!

**Comment by Polymega** [comment]
@bigdeb Bigmanjapan provided me the addresses to change riddle/action levels for another project so I was able to get you a save file as well. This is a Quick Save save file at the beginning of the game (bathroom) on Hard Action and Extra Riddle difficulties. Back up your save files before replacing them to be safe: [sh2pcsave2e.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2669928/sh2pcsave2e.zip)

**Comment by bigdeb** [comment]
Wow, thanks so much!
