### ISSUE TITLE
Installer keeps timing out

### ISSUE THREAD

**Issue by TheBlindGay** [elishacloud/Silent-Hill-2-Enhancements#720]
I live in the boonies, so my average download speed is about 1.5 mb/s, and the installer keeps timing me out for this. Is there a way to download the necessary files without using the installer?

**Comment by RataQuemada** [comment]
> I live in the boonies, so my average download speed is about 1.5 mb/s, and the installer keeps timing me out for this. Is there a way to download the necessary files without using the installer?

I have the same issue as you, and my download speed is 100 mb/s, i think it is not your internet's fault. Maybe the servers they use to host the files are down, idk really

**Comment by maxdunbar** [comment]
How is the installer timing you out? Is there an error message? I am getting similar results with an appropriate download speed. In my case `Error: Download Failed`  `Couldn't download webcsv.url`
Seems like the website has had issues in the past see #647. After refreshing (not too many times) I got `_sch2ee.csv` from this [link](https://raw.githubusercontent.com/elishacloud/Silent-Hill-2-Enhancements/master/Resources/webcsv.url) which webcsv.url redirects to downloaded. However not sure where I can put the file in the directory.

**Comment by petersid2022** [comment]
> Error: Download Failed Couldn't download webcsv.url

Have you managed to resolve this? I am also getting the same error.

**Comment by filevans** [comment]
me too
