### ISSUE TITLE
Xidi Broken on Linux/Steam Deck

### ISSUE THREAD

**Issue by ComicSansKing** [elishacloud/Silent-Hill-2-Enhancements#725]
Hello, I run Linux for my main PC and also SteamOS on my Steam Deck. I tried installing the new Enhanced Edition update today on both systems and found that no matter what I did the game would crash if Xidi was installed. Without Xidi installed, the game will launch 100% of the time, however the input buttons are completed wrong and the triggers do not work. I had the previous Xinput+ version installed earlier today, and that version did work correctly as intended. I am not sure if there is a way to revert back to Xinput+ for this game or not however. Thank you for anyone's help in advance!

**Comment by Polymega** [comment]
Hi there,

Sorry you're having issues. For Xidi compatibility with Linux, it would be best to contact Xidi's creator and see what they might be able to do. To explain our rationale real quick: With SH2 PC being made for Windows, we focus on updating or changing packages for the betterment of the game on this operating system. 

However! We also try to support and accommodate other platforms such as Linux and Steam Deck where and how we can (within reason). For controller support, here is a link to the XInput Plus package the project was previously using:
https://enhanced.townofsilenthill.com/SH2EE/legacy/SH2EE_XInputPlus_4.15.2.zip

Xidi will likely be our software-of-choice long-term for controller support with the project, so keep that link/package handy in the meantime for Linux use.

**Comment by ComicSansKing** [comment]
Thank you very much! I also actually discovered how to get Xidi to work in Linux for anyone who has future issues.
It requires it's dependencies installed into the same Proton directory (changing the exe to these additional installers in Steam).
It requires Visual C++ Runtime for Visual Studio 2022 installers in both the x86 and x64 versions. 
Thank you for your help as well hopefully anyone else with this issue can find the solution in this thread!

**Comment by elishacloud** [comment]
Can you try with this Xidi update: [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10835098/dinput8.zip)
