### ISSUE TITLE
An error occurred in the secure channel support

### ISSUE THREAD

**Issue by ironbutter** [elishacloud/Silent-Hill-2-Enhancements#727]
Hello

I keep getting "Download failed: An error occurred in the secure channel support" when trying to update to the latest version (#9) I've also tried a fresh install, but the same thing happens. Any ideas how to fix this ? 

Cheers

**Comment by Polymega** [comment]
Sorry you're having issues. If you give it another go now, does the issue persist?

**Comment by ironbutter** [comment]
Unfortunately it keeps happning. 

If it's any help, it seems most of the time it's when the file "SH2EE_Image_Enhancement_Pack_1.1.2.zip (314.22 MB)" is finished downloading that it keeps happning. Never gotten past this point anyway

**Comment by ironbutter** [comment]
> Sorry you're having issues. If you give it another go now, does the issue persist?

Unfortunately it keeps happning.

If it's any help, it seems most of the time it's when the file "SH2EE_Image_Enhancement_Pack_1.1.2.zip (314.22 MB)" is finished downloading that it keeps happning. Never gotten past this point anyway

**Comment by Polymega** [comment]
Is your firewall preventing or cutting off the connection made to download the files?

**Comment by ironbutter** [comment]
> Is your firewall preventing or cutting off the connection made to download the files?

Tried to turn off the firewall and any anti-virus program. It still happens tho. But it seems like it's more of a problem at my end, so don't worry about it

**Comment by Polymega** [comment]
We believe the issue has since been resolved. 

Closing ticket. Feel free to re-open if you'd like further assistance.
