### ISSUE TITLE
"There is not enough disk space" error while installing

### ISSUE THREAD

**Issue by VarlusMD** [elishacloud/Silent-Hill-2-Enhancements#728]
Hello. I would like to know the exact paths involved when the Setup tool installs the Enhanced Edition packages.

To clarify: my current C: drive is a very small partition of my SSD, used only to house Windows and a few more essentials.

When trying to update SH2EE, the Setup tool, even though it was downloaded on another drive with plenty of space available, gives me the "Not enough disk space" error, and I see that my C: drive is full.

Presumably, while downloading packages, it temporarily stores them in my C: drive before moving them to the specificied SH2 folder. I would like to know the exact path the installer uses, so I can clean up this faulty installation and try again.

I think it would also benefit the project for the installer to temporarily download files in the same folder the installer is located, not in the C: drive (assuming that's the case).

Thank you for your time.

**Comment by MarioTainaka** [comment]
> Hello. I would like to know the exact paths involved when the Setup tool installs the Enhanced Edition packages.
> 
> To clarify: my current C: drive is a very small partition of my SSD, used only to house Windows and a few more essentials.
> 
> When trying to update SH2EE, the Setup tool, even though it was downloaded on another drive with plenty of space available, gives me the "Not enough disk space" error, and I see that my C: drive is full.
> 
> Presumably, while downloading packages, it temporarily stores them in my C: drive before moving them to the specificied SH2 folder. I would like to know the exact path the installer uses, so I can clean up this faulty installation and try again.
> 
> I think it would also benefit the project for the installer to temporarily download files in the same folder the installer is located, not in the C: drive (assuming that's the case).
> 
> Thank you for your time.

The path currently is a temp folder where the setup is also run from. It's uh... AppData\Temp\randomly generated numbers

If you use the create a backup option the backups will be created in a folder of your choosing.

**Comment by VarlusMD** [comment]
> 

Thank you! This worked perfectly.

Perhaps a small mention of disk C: usage would be helpful? If there is, I missed it. In any case, thank you very much for the quick response time.

**Comment by Polymega** [comment]
Sorry I'm late to respond; a lot going on! But I was also going to say that you can choose the "Offline Installation" method that's asked near the start of the Setup Tool. Doing it this way, you can specifically choose which folder the files are downloaded to for installation purposes.

> Perhaps a small mention of disk C: usage would be helpful?

I'll pass this note along to see what we can do! Thanks

**Comment by Polymega** [comment]
Wanted to update you that, for the next update to the Setup Tool this string:

`Downloads the enhancement packages to a temporary folder for project installation.`

will change to this:

`Downloads the enhancement packages to a temporary Windows AppData folder for project installation.`

...where we added "Windows AppData" to it. While very unusual, a user _can_ install Windows to a drive other than C:\, so we opted to just say "temporary Windows AppData folder" instead.
