### ISSUE TITLE
Application Error (0xc0000142)

### ISSUE THREAD

**Issue by xscabini** [elishacloud/Silent-Hill-2-Enhancements#729]
I did the installation and went like usual but when i try to start the game this message prompt shows up.

![image](https://user-images.githubusercontent.com/110368045/221364626-8c318ecd-cac5-4640-b7ad-c8eb529aadfb.png)

**Comment by MarioTainaka** [comment]
> I did the installation and went like usual but when i try to start the game this message prompt shows up.
> 
> ![image](https://user-images.githubusercontent.com/110368045/221364626-8c318ecd-cac5-4640-b7ad-c8eb529aadfb.png)

Please don't install the game in C:\Programfiles. That dir is write protected in modern versions of Windows and files can't be written to without permission.

Also turn of your Virus Scanner or add an exception

**Comment by xscabini** [comment]
Thank you for your response. I reinstalled the game but in my secondary disk and I still receive this Application Error.
![image](https://user-images.githubusercontent.com/110368045/221369273-35b67b9f-6c91-4374-8c61-bb6b8e0370a7.png)

**Comment by nipkownix** [comment]
@xscabini Does the error go away if you delete ``dinput8.dll``?

**Comment by xscabini** [comment]
It worked! Thank you a lot! I really I didn't how to resolve the issue. I hope you have a great weekend :)

**Comment by Polymega** [comment]
Looks like there's still an external VS runtime dependency needed for Xidi. [See here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/732)

**Comment by elishacloud** [comment]
Can you try with this Xidi update: [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10835098/dinput8.zip)
