### ISSUE TITLE
Add new "hybrid" DPadMovementFix that A. doesn't break in-game dpad bindings, while B. allowing dpad movement in-menus

### ISSUE THREAD

**Issue by ronjouch** [elishacloud/Silent-Hill-2-Enhancements#731]
**EDIT** This bug was initially asking two things (see "The ideal setup" points 1. and 2.)

1. Point 1. (bindability of dpad buttons) is fixed! Addressed thanks to https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/722#issuecomment-1445237435, which will be pushed into an upcoming Xidi update.
2. Point 2. (preserving dpad in menus while allowing in-game bindings to work) remains TODO. See https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/731#issuecomment-1445239050 .

---

Hi! Regardless of whether I enable [`DPadMovementFix`](https://enhanced.townofsilenthill.com/SH2/config.htm#DPadMovementFix), in the game's options screen I'm unable to bind any action (e.g. prev weapon, next weapon, first aid kit) to controller dpad left/right/up.

## Steps to Reproduce

1. Go to in-game options
2. Using keyboard, navigate for example to "Next Weapon", right "Controller" column
4. Press ENTER
5. The `???` placeholder appears, indicating game awaits controller button press
6. Press for example the controller's DpadRight button

**Expected**: DpadRight gets bound to "Next Weapon"
**Actual**: nothing happens.

## The ideal setup

To precise further, I'm trying to have this:

1. **In-game**: WITHOUT `DPadMovementFix`: I use the analog stick to move around so I don't care about dpad movement. However, I'd love to be able to bind actions (like prev/next weapon and first aid kit) to dpad buttons.
2. **In-menus**: WITH `DpadMovementFix`: In menus I'd like to keep `DpadMovementFix` though, because I tend to naturally use dpad up/down/left/right to navigate menus. No particular reason, just pure muscle memory of hours playing games where dpad is the *only* way to navigate the menus :shrug: .

That being said, if it isn't feasible to have both points 1. (bindability of dpad buttons) and 2. (preserving dpad in menus) at the same time, only fixing point 1 would already be awesome.

## Environment

- SH2EE Update 9 (60fps release, fully updated/repaired on 2023-02-25)
- All default options in SH2EEConfig.exe , except I set display to fullscreen
- In particular, I am (I think I am?) using Xidi. In doubt, I repaired my install to force reinstall of Xidi, and I confirm that I have Xidi.ini and no XInput dlls/ini.
    - Should I try without Xidi? My memory is fuzzy, but I think it used to be possible to bind dpad arrows before Xidi.
- Standard Xbox360 controller
- Windows 10 up-to-date
- Happy to provide a d3d8.log or more details if necessary

Thanks for your work 🙂. Am happily playing SH2 for real for the first time now (I was waiting for 60FPS to land), and it's a joy.

**Comment by Polymega** [comment]
Hi there!

Please see this post about allowing the ability to assign functions to the D-pad of controllers: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/722#issuecomment-1445237435

> In-menus: WITH DpadMovementFix: In menus I'd like to keep DpadMovementFix though, because I tend to naturally use dpad up/down/left/right to navigate menus. No particular reason, just pure muscle memory of hours playing games where dpad is the only way to navigate the menus 🤷 .

I think we can do this fairly easy. It would be a case of detecting whenever we're in a menu and enabling `DpadmovementFix`, then disabling it again during regular gameplay. 

I actually know the perfect team member to possibly look into this. @mercury501, up for the task in the future? No rush here.

**Comment by mercury501** [comment]
Sure thing @Polymega, I can look into it, although I'm unable to give an eta. Thank you @ronjouch for the wonderful and detailed issue.

**Comment by ronjouch** [comment]
> see this post about allowing the ability to assign functions to the D-pad of controllers: [#722 (comment)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/722#issuecomment-1445237435)

@Polymega worked perfectly, thanks :ok_hand: ! And amen to _"include the INI changes shared above as part of [an upcoming Xidi] update"_ as you say in the issue.

> (Polymega) I think we can do this fairly easy. It would be a case of detecting whenever we're in a menu and enabling DpadmovementFix, then disabling it again during regular gameplay.
>
> (mercury) Sure thing @Polymega, I can look into it, although I'm unable to give an eta. Thank you @ronjouch for the wonderful and detailed issue.

:heart: @Polymega @mercury501 you're the loveliest friendliest warmest game preservers.

Thanks again for SH2EE. And now that my gamepad config issue is solved with https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/722#issuecomment-1445237435 (and will be made standard in the upcoming Xidi update), renaming the issue.

**Comment by Polymega** [comment]
_The following code/work would need to be added to the `DPadMovementFix` feature. I'm not exactly sure where all it's used/stored, but here are some locations:_
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/3247f72518c926b51111d9c9382bdefe0f7e7725/Patches/ControllerTweaks.cpp#L54-L66
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/3247f72518c926b51111d9c9382bdefe0f7e7725/Patches/ControllerTweaks.cpp#L224-L238

The `DPadMovementFix` fix restores character movement to the D-pad, like how it is in the console versions. By restoring character movement to the D-pad, it also doubles as restoring menu movement with the D-pad as well. When `DPadMovementFix` is disabled, you cannot controller the character _**or**_ navigate menus with the D-pad.

There are people who would prefer to have this feature disabled, so that they can assign additional functions to the D-pad (such as Left and Right on the D-pad cycling weapons). However, it would be nice if the D-pad could still be used to navigate menus _while in a menu or during text selections while playing._

To achieve this, we should add a third option to `DPadMovementFix`: Disable (0), Enable (1), and a new "Menus Only" (2) option.

For a "Menus Only" option, the pseudo code would be something like this:

```c++
if (GetEventIndex() != EVENT_IN_GAME || (GetEventIndex() == EVENT_IN_GAME && IsInFullScreenImageEvent())) { //Not currently in-game, so in a menu || In-game but a text prompt is currently on-screen. See example here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/InputTweaks.cpp#L386
enable `DPadMovementFix`
} else {
disable `DPadMovementFix`
}
```

**Comment by Polymega** [comment]
Er, there's a little snafu with that pre-made `Xidi.ini` file. If I include:

```
DpadUp			= Button(13)
DpadDown		= Button(14)
DpadLeft		= Button(15)
DpadRight		= Button(16)
```

...in the INI, then `DPadMovementFix` doesn't work, even when enabled. This is probably because the Xidi wrapper is sitting on top/overwriting input fixes from the project.

I'm not sure how best to handle this at the moment. Right now, I'm thinking of simply _omitting_ those lines in the `Xidi.ini` file and a user would have to manually enter them in, if they wish. Hopefully we can think of a more elegant solution.

**Comment by Polymega** [comment]
@ronjouch 
We have included a feature for this. You can test this by downloading the build below. Open the `d3d8.ini` file and change `DPadMovementFix = 2` to test: [d3d8_b2.1.2057b.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10982876/d3d8_b2.1.2057b.zip)

This will allow you to assign game functions to the D-pad but the D-pad will act as movement inputs while in menus or text prompts.

NOTE: Be sure to _revert_ your `Xidi.ini` file back to its original form. Copy the code below and replace **the entire contents** of your `Xidi.ini` file with the code:

```ini
[Mapper]
Type			= ModifiedStandardGamepad

[CustomMapper:ModifiedStandardGamepad]

; Imports all of the element mappers from StandardGamepad.
; This line is allowed to appear anywhere in the section, including between or after the element mappers below.
Template		= StandardGamepad

; These changes are applied on top of the template.
ButtonA			= Button(2)
ButtonB			= Button(3)
ButtonX			= Button(1)
```

**Comment by ronjouch** [comment]
@Polymega :tada: ! Yup, works great for me.

Of course, this game is your baby and you know better to test it than I do. So, I cannot vouch for exhaustiveness or covering corner cases, but after a first smoke test it seems to work perfectly for me in { menus, map, inventory } with an Xbox360 controller 🙂.

ThaaaaaaaAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaanks! Letting you close the issue as you please, now or when merged.

**Comment by lucazandrade** [comment]
Done!
https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/757#issue-1627686323

**Comment by IlDucci** [comment]
Done!

**Comment by mercury501** [comment]
And italian is also done!

**Comment by Polymega** [comment]
Thank you, gentlemen!

Request integrated as of commit https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/3c4e65e80b8cea087597a27ada80f7297bf2d980
