### ISSUE TITLE
sh2pc.exe is missing

### ISSUE THREAD

**Issue by HomoFunkyChunky** [elishacloud/Silent-Hill-2-Enhancements#734]
I just downloaded the latest update as of 2/25/23 and played Silent Hill 2 twice since the update. I was going to play it again until I realized that the games .exe is missing and now unplayable. I checked my recycling to no avail. Tried to move the untouched exe from the games zip and it wouldn't let me. I have no clue what else to do.

**Comment by AeroWidescreen** [comment]
Do you have an anti-virus? It sounds like it's removing the exe. Also, don't install Silent Hill 2 (or any game in general) in Program Files. It's better to use a different folder, like `C:\MyGames\`, if you want to avoid permission issues.

**Comment by HomoFunkyChunky** [comment]
> 
Yea I think it was my Anti Virus software (AVG) that caused it. None of my games including SH2 is in program files though.
