### ISSUE TITLE
Failed to open

### ISSUE THREAD

**Issue by Cacorat** [elishacloud/Silent-Hill-2-Enhancements#740]
I've been trying to get it to work but After installing it it just says failed to open error code (0xc0000142) I got the copy of silent Hill from my abandon ware both the iso and unmodified version do not work and troubleshooting it with windows just says incompatible I've tried running it in all compatibility modes and were greeted with the same error

**Comment by Polymega** [comment]
If you temporarily remove the `dinput8.dll` file from the game's directory does the game then launch for you?

**Comment by Cacorat** [comment]
That seemed to work but what do you mean by temporarily do I need to put it back in?

> If you temporarily remove the `dinput8.dll` file from the game's directory does the game then launch for you?

**Comment by Cacorat** [comment]
Thank you for your help

**Comment by Polymega** [comment]
I'm going to reopen this as we hope to have a new test build of Xidi for you to try at some point. When that time comes, your testing will be really appreciated.

**Comment by elishacloud** [comment]
Can you try again with this updated module?  I removed enhanced processor instructions and removed runtime requirements.  Just unzip this into the Silent Hill 2 folder where the `sh2pc.exe` file exists.

Here is the update:  [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10864688/dinput8.zip)

**Comment by Cacorat** [comment]
I'm a bit busy right now but in a few hours I will be able to

**Comment by Cacorat** [comment]
A few hours turned to a few minutes but after putting in the file everything works fine

**Comment by elishacloud** [comment]
Ok, great.  Thanks for checking.

**Comment by EchoesDustin** [comment]
I was getting a missing "MVSCP140_ATOMIC_WAIT.dl" file error when trying to launch it, and finding that file from my Windows folder and dragging it into my SH2 directory instead just gave me the same (0xc0000142) error as well.
**But simply deleting the dinput8.dll file or replacing the old one with the new one posted here made it launch just fine.**
[Video_2023.webm](https://user-images.githubusercontent.com/127061012/222995102-d18c15ae-a7a7-4cbb-ad90-9d200b55094f.webm)

**Comment by Polymega** [comment]
> But simply deleting the dinput8.dll file or replacing the old one with the new one posted here made it launch just fine.

We will be pushing out a hotfix for the project in the near future to address this. The hotfix will contain the updated version of Xidi that Elisha has posted here in this thread.

**Comment by GustavoVR11** [comment]
Can someone please share their old dinput8 with me please? I replaced it with the updated one and started getting the error.

**Comment by Polymega** [comment]
> Can someone please share their old dinput8 with me please? I replaced it with the updated one and started getting the error.

Have you tried [this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/740#issuecomment-1450975157) that Elisha shared?

**Comment by GustavoVR11** [comment]
> > Can someone please share their old dinput8 with me please? I replaced it with the updated one and started getting the error.
> 
> Have you tried [this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/740#issuecomment-1450975157) that Elisha shared?

Yup, that`s exactly the one I tried, but without it the game works just fine. Is that file necessary? What does it do?

**Comment by Polymega** [comment]
That file is used for Xidi, which brings compatibility fixes for modern controllers when used with the game.

**Comment by GustavoVR11** [comment]
> That file is used for Xidi, which brings compatibility fixes for modern controllers when used with the game.

I see. I'm using a 360 controller. Is that the reason why I cannot assign either the L2/R2 or the d-pad buttons in-game? The default mapping was also a bit weird, e.g. start was set as "ready weapon"

**Comment by Polymega** [comment]
Xbox 360 controllers are classified as XInput controllers, which is a type of controller that SH2 PC doesn't correctly recognize. Back when SH2 PC came out, only DirectInput controllers existed for use with computers, so that's all the game knows.

To have all the inputs of a XInput controller be recognized by the game, you need to use an XInput wrapper such as Xidi or XInput Plus.

I'd like to confirm one more time with you, if that's okay? If you [download this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10865686/dinput8_4.1.1b.zip) and place the `dinput8.dll` file in the game's directory, it doesn't launch for you? Can you upload a copy of your `d3d8.log` file found in the game's directory?

**Comment by GustavoVR11** [comment]
> Xbox 360 controllers are classified as XInput controllers, which is a type of controller that SH2 PC doesn't correctly recognize. Back when SH2 PC came out, only DirectInput controllers existed for use with computers, so that's all the game knows.
> 
> To have all the inputs of a XInput controller be recognized by the game, you need to use an XInput wrapper such as Xidi or XInput Plus.
> 
> I'd like to confirm one more time with you, if that's okay? If you [download this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10865686/dinput8_4.1.1b.zip) and place the `dinput8.dll` file in the game's directory, it doesn't launch for you? Can you upload a copy of your `d3d8.log` file found in the game's directory?

Magic, it works just fine now! l2/r2 buttons are assignable, but not yet the d-pad. Is there a workaround for this? Other than that - an unrelated topic - is it normal that the shadows are buggy at times?

[https://www.youtube.com/shorts/IeKbE4tyoH0](url)

**Comment by Polymega** [comment]
> Magic, it works just fine now!

Great! I think perhaps before you were using an older build and not the latest one Elisha provided here.

> buttons are assignable, but not yet the d-pad. Is there a workaround for this?

Yes, there is a work-around. [See this post.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/722#issuecomment-1445237435) Just note if you do this then our **Restore D-pad movement** feature will no longer work as the changes you do to the `Xidi.ini` file will override this feature. 

This shouldn't be an issue if you never plan to use the D-pad for character/menu movement, but be aware. You can "revert" this change by removing the following lines from the `Xidi.ini` file:

```ini
DpadUp			= Button(13)
DpadDown		= Button(14)
DpadLeft		= Button(15)
DpadRight		= Button(16)
```

> - an unrelated topic - is it normal that the shadows are buggy at times?

You'd be surprised how often we get this question about shadows due to this specific spot. 😆  Yes, that's normal behavior exhibited in all versions of the game.

**Comment by Polymega** [comment]
@GustavoVR11 
We have included a feature for this. You can test this by downloading the build below. Open the `d3d8.ini` file and change `DPadMovementFix = 2` to test: [d3d8_b2.1.2057b.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10982876/d3d8_b2.1.2057b.zip)

This will allow you to assign game functions to the D-pad but the D-pad will act as movement inputs while in menus or text prompts.

NOTE: Be sure to _revert_ your `Xidi.ini` file back to its original form. Copy the code below and replace **the entire contents** of your `Xidi.ini` file with the code:

```ini
[Mapper]
Type			= ModifiedStandardGamepad

[CustomMapper:ModifiedStandardGamepad]

; Imports all of the element mappers from StandardGamepad.
; This line is allowed to appear anywhere in the section, including between or after the element mappers below.
Template		= StandardGamepad

; These changes are applied on top of the template.
ButtonA			= Button(2)
ButtonB			= Button(3)
ButtonX			= Button(1)
```

**Comment by GustavoVR11** [comment]
Yuuuup, it works! Great job to all those involved! :)

**Comment by nasovic** [comment]
Hello everybody. Had similar problem (0xc000001d error) and using updated dinput8.dll resolved the issue for me as well :)

**Comment by Badore90** [comment]
Also I'm getting a error when launching sh2pc.exe

![image](https://user-images.githubusercontent.com/44087144/226736937-406358e2-a9f7-4f4b-806f-50f14c22a872.png)

The game was working fine on this PC with the previous build. When I updated to the newer build (when the 60fps patch was released) I couldn't launch the game.

Today I got some time so I completely uninstalled the EE and also the vanilla game itself. Installed everything from scratch but it keeps giving me the same error.

**Comment by Badore90** [comment]
> Can you try with this dll: [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10864688/dinput8.zip) Just unzip this into the Silent Hill 2 game folder.
> 

It works with that, thank you. What do you changed if I may ask? I'm curious to know what was causing the problem.

I played a little (the mouse support is great :D ) and noticed an error, see:

![image](https://user-images.githubusercontent.com/44087144/226930789-f4d548f1-607e-4a45-bada-097d23e7e064.png)


Yes and not for exiting the game, in italian it shoud be "Si". It was correct before.

**Comment by Badore90** [comment]
I installed everything from scratch so it is all updated. Some connection problem perhaps that causes corruption, I'll download the essential files package again.

**Comment by Polymega** [comment]
Before you do that. Go to `.\sh2e\etc\` and delete the `resource` folder in here. Then, launch the game. Does it resolve the issue?

**Comment by Badore90** [comment]
I just tried re-downloading the essential files and the issue is still present. I'll try now your suggestion

**Comment by Badore90** [comment]
> Before you do that. Go to `.\sh2e\etc\` and delete the `resource` folder in here. Then, launch the game. Does it resolve the issue?

Renaming the resource folder solved, thank you. What use this folder should have? What I lose by deleting it?

**Comment by Badore90** [comment]
I opened it with notepad++ and I see the word "Si" is not correct, it is "Sì" with the accent, it is wrong. Btw it escapes me why in the game it is writed in a different way.

**Comment by Polymega** [comment]
Do you mean for this line?

> Si prega di inserire il disco Silent Hill 2

If so, please let us know of any other issues and we will correct them. The file can be found here:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Resources/exe_str_i.txt

**Comment by Badore90** [comment]
No sorry, I was wrong, everything is correct. I wonder why at first startup it gave me that error. Maybe 'cause I launched the game in english first time?
