### ISSUE TITLE
SHEE Error Message

### ISSUE THREAD

**Issue by JaceyRiley** [elishacloud/Silent-Hill-2-Enhancements#742]
Hi all,

I've been using SHEE on my Steam Deck with no issues, but after installing the latest update, I came across this message after trying to start the game:

![SHEE_Error](https://user-images.githubusercontent.com/126703397/222211282-de8f4fd4-1aea-436f-a280-638ae582b842.png)

The steps I took were:

1. Adding the SHEE Setup tool to my Steam Deck library (changing the compatibility layer to Proton 7.0-6)
2. Running the tool (I did choose the install option)
3. After the installation was complete, the dialogue box "this program is running with wine/proton...."
4. I then added the sh2pc.exe file to my library, and changed the Proton 7.0-6, and that's when the error message (attached) comes up)

I've also attached a copy of my d3d8.log.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10863654/d3d8.log)

Any help is greatly appreciated!

Thanks,

J.

**Comment by Polymega** [comment]
If you temporarily remove the `dinput8.dll` file from the game's directory, does the game launch for you then?

**Comment by JaceyRiley** [comment]
@Polymega so an interesting thing happens. I removed it from the folder, and the game WILL start up, but will revert to the original game (i.e., Director's Cut) that I go originally. It seems like no enhancements have been applied. I'm wondering whether the enhancements were extracted to a different directory? If so, I'm not able to find them :s

**Comment by Polymega** [comment]
> It seems like no enhancements have been applied. I'm wondering whether the enhancements were extracted to a different directory? If so, I'm not able to find them :s

Your game's directory should look something like this upon installing the project files: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

**Comment by JaceyRiley** [comment]
Okay I think that's where I'm running into the issue. This is what my game directory looks like:

![SHEE_GameDirectory](https://user-images.githubusercontent.com/126703397/222260009-2e761bdb-3b06-4125-973b-917130a30e64.png)

But this is what it looks like on my PC as well, and it runs fine on there.

I reviewed my d3d8 log again (on my Steam Deck), and this directory is showing up:

8992 00:09:02.952 Running from: C:\Users\owner\Downloads\Silent Hill 2 Enhanced Edition\sh2pc.exe

Which is the directory that I pointed to on my PC. Like, it looks as though my Steam Deck is picking up my PC directory? I'm thinking that's what's causing the error? I just can't even seem to locate the enhancement files on my Deck. I'm pointing the installer to the directory on my Deck, but yeah, I'm not sure where the problem is occurring.

**Comment by Polymega** [comment]
Unfortunately, no one on the team has a Steam Deck afaik. I'd recommend sharing your issues [over on this thread](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/505) to see if other Deck users can help with this. 

If/when Deck users have determined what the cause of the issue is, we can think look into trying to resolve it. 

Thanks

**Comment by JaceyRiley** [comment]
@Polymega 

Great, thanks for helping with troubleshooting! Really hoping to get this up and running again as it's incredible.
