### ISSUE TITLE
Error on startup after update msvcp140_atomic_wait.dll

### ISSUE THREAD

**Issue by flaviosalas** [elishacloud/Silent-Hill-2-Enhancements#744]
base game runs fine but when i installed the update it doesnt open, it says msvcp140_atomic_wait.dll missing (i have the latest visual c++ runtimes).

**Comment by elishacloud** [comment]
Can you try again with this updated module?  I removed enhanced processor instructions and removed runtime requirements.  Just unzip this into the Silent Hill 2 folder where the `sh2pc.exe` file exists.

Here is the update:  [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10864696/dinput8.zip)

**Comment by flaviosalas** [comment]
now it's working! thanks!!
