### ISSUE TITLE
Where can I delete the new update?

### ISSUE THREAD

**Issue by Blunderless** [elishacloud/Silent-Hill-2-Enhancements#746]
The new enhancements module package is really awful and makes my game completely dysfunctional to where i can't pause the game without crashing, and the in-game menu is sped up way too fast as well as certain cutscenes

i really appreciate the work of the people who did sh2e, but i can do without this update

surely there's a way of making the game less volatile and likely to crash without disabling all these features that once worked in harmony prior to this god-awful update. 

this update was nothing but trying to add petty little things to make the game appear nicer and these touches like 60fps were completely extraneous and make no difference at all to a game with no stuttering or framerate issues

**Comment by Polymega** [comment]
> surely there's a way of making the game less volatile and likely to crash without disabling all these features that once worked in harmony prior to this god-awful update.

Yes, you need to help us in order for us to help you, starting off by doing tests [with the troubleshooting suggestions](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/738#issuecomment-1446842459) I gave you. If we aren't experiencing this issue, we can't test for it.

If you'd rather not help resolve this issue for you and other who may be experiencing this, you can use an earlier build of the main module that runs out project, [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2027.0).
