### ISSUE TITLE
Gray Noise Effect?

### ISSUE THREAD

**Issue by davidedby** [elishacloud/Silent-Hill-2-Enhancements#749]
Turning on the Noise effect seems to make the game dull and gray? I like how the Noise effect adds grit to the visuals, but how it is right now really lessens the atmosphere of the game's darker areas. Here's a little comparison with a simple Levels edit. I am using the Ultra Fine option for the noise effects, since the Default and Fine options are a lot grayer.

Off:
https://ibb.co/fdFYVyD
On:
https://ibb.co/HzG4kv8
Edited Levels:
https://ibb.co/CWwCD2g

I know its prolly accurate to the PS2 version, but CRT's blend them enough to not make them so apparent and dull looking.
Can you guys implement an option to lower the intensity just a little bit, or where black areas are still nice and dark with the filter on just like in SH3? Thanks!

**Comment by elishacloud** [comment]
You can use the new CRT filters we added into the project that may help with this.  Also, you could hook your PC up to a CRT and play the game off of that.
