### ISSUE TITLE
Strange characters in certaion scenarios

### ISSUE THREAD

**Issue by gtxSeries** [elishacloud/Silent-Hill-2-Enhancements#75]
Greetings!

I just ran into this issue: the text on the save/load screen, as well as on certain interaction texts is messed up. To demonstrate, I attached a screenshot:
https://i.ibb.co/3MdCrNT/K-perny-felv-tel-4.png

This also appears when I try to examine certain objects, like a painting in a room, or picking up an object and the affirmation text is displayed in this matter too. Any ideas what could be causing this?

**Comment by Polymega** [comment]
Hi @gtxSeries ,

Here are some things I think it may be:

- Did you install an external, third party language pack for the game (outside of what's provided from the Enhanced Edition)?
- Are you using a `sh2pc.exe` file other than what's provided from the Enhanced Edition?
- If you change the language in the game's Options menu is the text still corrupted? Or is it displaying correctly for the other languages?

**Comment by gtxSeries** [comment]
Hi, @Polymega,
None that I know of. I can't select anything outside english anyway. I might try re-installing. I'm using the EE executable.

**Comment by Polymega** [comment]
Glad to hear! If you use the North American .exe you can only select English as a language. Sorry, I should've clarified that from the get-go. 

In any case, glad everything is working well for you now.

**Comment by elishacloud** [comment]
Closing issue.
