### ISSUE TITLE
does enhanced edition has a laa patch?

### ISSUE THREAD

**Issue by mikeoxmaull** [elishacloud/Silent-Hill-2-Enhancements#753]
does enhanced edition have a laa patch, is it necessary?

**Comment by MarioTainaka** [comment]
> does enhanced edition have a laa patch, is it necessary?

If you mean Large Address Aware then no, it's not required.

**Comment by mikeoxmaull** [comment]
> > does enhanced edition have a laa patch, is it necessary?
> 
> 
> 
> If you mean Large Address Aware then no, it's not required.
ty, for the answer!
