### ISSUE TITLE
cant launch the game. it says the code execution cannot proceed because im missing msvp140.DLL, msvp140_ATOMIC_WAIT.dll, and CONCRT140.DLL (Three seperate errors).

### ISSUE THREAD

**Issue by pizzaboy221** [elishacloud/Silent-Hill-2-Enhancements#755]

**Comment by pizzaboy221** [comment]
heres my main folder also
![image](https://user-images.githubusercontent.com/127804045/224862521-d40fcc45-4b8e-4193-b854-954b73c78387.png)

**Comment by elishacloud** [comment]
Can you try again with this updated module?  I removed enhanced processor instructions and removed runtime requirements.  Just unzip this into the Silent Hill 2 folder where the `sh2pc.exe` file exists.

Here is the update:  [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10864696/dinput8.zip)

**Comment by pizzaboy221** [comment]
now it says this
![image](https://user-images.githubusercontent.com/127804045/224863204-1e381ccd-d05d-4ecb-81bc-af93dab70f3a.png)


> Can you try again with this updated module? I removed enhanced processor instructions and removed runtime requirements. Just unzip this into the Silent Hill 2 folder where the `sh2pc.exe` file exists.
> 
> Here is the update: [dinput8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10864696/dinput8.zip)

**Comment by elishacloud** [comment]
Ok, try the new version is "4.1.1b".  Here is the update: [dinput8_4.1.1b.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10865686/dinput8_4.1.1b.zip)

Also, you may want to try temporarily renaming the `dsound.dll` file.

**Comment by pizzaboy221** [comment]
> Ok, try the new version is "4.1.1b". Here is the update: [dinput8_4.1.1b.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10865686/dinput8_4.1.1b.zip)
> 
> Also, you may want to try temporarily renaming the `dsound.dll` file.

this worked. thank you!!! ive been trying on my own for a little while now. it wouldn't launch until i renamed the dsound.dll, but ive seen someone else in this thread mention some sort of popping that they only hear when they remove the dsound file, will there be any drawbacks like that?

**Comment by elishacloud** [comment]
> it wouldn't launch until i renamed the dsound.dll, but ive seen someone else in this thread mention some sort of popping that they only hear when they remove the dsound file, will there be any drawbacks like that?

Yes, you lose the 3D audio.  If you want it to work with the dsound.dll then you need to install the [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53840).
