### ISSUE TITLE
SH2EEsetup.exe Runtime Error

### ISSUE THREAD

**Issue by raisedupfire** [elishacloud/Silent-Hill-2-Enhancements#756]
Opening SH2EEsetup.exe from the base installation folder gives me an error "Runtime error (at 203:599): List index out of bounds (1)

**Comment by Polymega** [comment]
Let's test and try a couple things to hopefully fix the issue. Right click `SH2EEsetup.exe`, go to **Properties**, then click the **Details** tab. What product version number does it say? If it says 1.1.1 then please re-download the Setup Tool from our project site: https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

Once downloaded, make sure it is now version 1.1.2. If it isn't, clear your internet browser's image/file cache and re-download the tool from our project site.

**Comment by raisedupfire** [comment]
Checked the setup tool and it was very outdated (1.0.5). I downloaded the setup tool and replaced it with the new setup tool and now it works. Thanks.
