### ISSUE TITLE
Implementation of Self Shadows

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#76]
This is very likely going to be a beastly fix to implement correctly so I'm making this its own thread.

---------------------

@FrozenFish24 I finished play testing your "self shadows" fix and by-and-large it worked like a charm! Here are my notes on the shadows; I very likely may have missed some areas... it was a lot of rooms to go over in detail! Think of the notes below as a first-pass for this fix. I'm sure there will be adjustments down the line for these, especially if/when we can implement soft shadows:

- There are several camera cuts within cutscenes (not the whole cutscene; just a particular camera cut) or entire rooms/areas (especially near the end in the Hotel) where James should not have a self shadow. 
   - However, for many of these areas where the PS2 version has disabled his shadow, James having a self shadow in these rooms/cutscenes actually looks good! Because of this--and because of _how many_ specific, individual rooms near the end/in the hotel that the PS2 version disables it on--I'm only going to list cutscenes/rooms that disable his self shadow in the PS2 version that look bad if left enabled for the PC version. This will hopefully save us a nice chunk of time and potential headache. 
- The console versions seems to adjust the darkness/opacity of self shadows for certain areas/cutscenes. Whereas, for the PC version right now, all self shadows are the same intensity throughout the board. For example: While in Hotel Room 312 self shadows are so light you almost can't see them. I'm not sure if/how we can adjust that down the line? The good news is, for most of the time, things like James' self shadow stays the same intensity _usually_.
- Any time we only disable James' shadow from the list below it should be fine because, during the cutscenes or rooms where I mention it to be disabled, he's never behind another dynamic object [so this issue](https://youtu.be/7UonECv1ZT4) should never occur.
   - However, I wonder if there's a call/function the game sends to know when/where James' self shadow should be enabled/disabled that we can utilize? Or do you think we have to manually disable his shadow from the lists below? @Bigmanjapan , thoughts? 

**The images below show the cutscenes/rooms looking _incorrect_ with shadows enabled/disabled where they shouldn't be.**

---------------------

### Disable ONLY James' self shadow for the following: 

If James' shadow is being disabled for a cutscene and it mentions a camera position (camera cut) then only disable his shadow for that particular camera position. Restore his shadow elsewhere, for the remainder of the cutscene.

1. [For this particular cutscene camera cut.](https://user-images.githubusercontent.com/27395260/50744028-a59d1500-11ec-11e9-9c6b-343a06f2f893.png) The self shadows around his hands look a little glitchy and the PS2 version also has it disabled for this camera cut.
   - Cutscene ID: 01F7A7C4 (4 bytes): 00000028
      - When cutscene camera position X: 0094E064 (float): -142102.8125

2. [While in the Maria cell room.](https://user-images.githubusercontent.com/27395260/50744039-c7969780-11ec-11e9-8513-5c37ad36e938.png) His self shadow is a little too "extreme" in here (visually distracting) and is fully disabled for the PS2 version as well.
   - Room ID: 01FB7DAC (4 bytes): 00000089

3. Changed to remove on cutscene ID instead (notes a few posts below).
~~[While in the noose pulling room.](https://user-images.githubusercontent.com/27395260/50744372-a5067d80-11f0-11e9-9dc1-1aa15dc16646.png) Similar to the room mentioned above, his shadow can get a little too extreme here as well and is also fully disabled in the PS2 version here.~~
   - ~~Room ID: 01FB7DAC (4 bytes): 0000008C~~

4. [For this particular cutscene camera cut.](https://user-images.githubusercontent.com/27395260/50746522-793dc480-11fd-11e9-9c8c-2d2ff1f27070.png) Otherwise his self shadow gets very glitchy looking as the camera cut goes on. His self shadow is also disabled for this camera cut in the PS2 version as well.
   - Cutscene ID: 01F7A7C4 (4 bytes): 00000054
      - Cutscene camera position X: 0094E064 (float): -19418.82617

5. Changed to remove on cutscene ID instead (notes a few posts below).
~~[While in the Dog Ending room.](https://user-images.githubusercontent.com/27395260/50911477-f6378c80-13fd-11e9-92be-49234aaf3049.png) James doesn't have a self shadow for the Dog Ending in the PS2 version and it's a little too visually distracting to keep enabled otherwise.~~
   - ~~Room ID: 01FB7DAC (4 bytes): 000000BD~~

6. [For this WHOLE cutscene.](https://user-images.githubusercontent.com/27395260/50915396-ba54f500-1406-11e9-8f4f-5f6145eeffb8.png) This is for the bedroom dialog in the Leave ending.
   - Cutscene ID: 01F7A7C4 (4 bytes): 00000059

------------------------

### _Enable_ James' self shadow for the following: 

This is a weird category, I know, but it'd be easier to tell you when to _enable_ his self shadow for particular cutscenes as opposed to the other way. 

So, keep self shadows activated **except** for James' self shadow. Keep his self shadow **disabled** for the following cutscenes **until** a specific camera cut is triggered then **enable** his self shadow **only** during that camera cut: 

1. [For this particular cutscene camera cut.](https://user-images.githubusercontent.com/27395260/50916178-7531c280-1408-11e9-90b4-a970554966b2.png) This is for the bedroom dialog in the In Water ending. If his self shadow remains enabled the whole time there is a camera cut or two where it "blinks" in and out. The PS2 version also has his self shadow fully disabled until (and only during) this particular camera cut.
   - Cutscene ID: 01F7A7C4 (4 bytes): 0000005F
      - Cutscene camera position X: 0094E064 (float): -19443.98438

------------------------

### Disable ALL self shadows for the following: 

Not just James' self shadow, but **all** self shadows for these rooms/cutscenes:

1. [For this particular cutscene camera cut.](https://user-images.githubusercontent.com/27395260/50873701-0bc19d80-138f-11e9-8cc5-cf255911a19f.png) The self shadows here glitch and instantly disappear midway through the camera cut. Interestingly, it actually does this on the PS2 build, as well. 
   - Cutscene ID: 01F7A7C4 (4 bytes): 00000052
      - Cutscene camera position X: 0094E064 (float): 61455.5

- A laundry list of rooms (mostly in the Hotel) need to have ALL self shadows disabled. The PS2 version disables shadows for many of these rooms and leaving them enabled can be visually too distracting due to how the self shadows cast on James or the like: 
   - Room ID: 01FB7DAC (4 bytes): 
      - 00000099 (Hotel main entrance hallway)
      - 00000092 (Hotel lobby area)
      - 000000B2 (Alternate Hotel West hallway)
      - 000000B1 (Alternate Hotel West rooms hallway)
      - 000000B4 (Alternate Hotel East rooms hallway)
      - 000000B3 (Alternate Hotel East hallway)

------------------------

### Blacklist specific geometry from receiving any shadows:

These are geometry pieces that should never receive _any_ type of dynamic shadows: 

1. [The apartment room TV static.](https://user-images.githubusercontent.com/27395260/50747484-14d13400-1202-11e9-85da-f07ef1a67ae1.png) Not the whole TV but just the TV static and only when the TV is on/is displaying the static: 

2. [These three windows in Heaven's Night.](https://user-images.githubusercontent.com/27395260/50747486-21558c80-1202-11e9-8d3e-73638f2ea65a.png)

3. [This window at the end of the 2F west hallway in the Hotel.](https://user-images.githubusercontent.com/27395260/50747583-9923b700-1202-11e9-8df8-f01fdfce677f.png)

-------------------------

Again, there are surely other areas I missed that have self shadows disabled. And there are areas where it's disabled in the PS2 version that I purposefully didn't mention here because keeping them enabled in many of these rooms still looks really good! (That, and it saves us trouble.) 

I'm hopeful maybe there's a function/call that determines when James receives his own self shadow or not, and we can utilize that to know when to enable/disable his self shadow. If there is such an address(es), it would make things significantly easier and theoretically match when James has a self shadow 1:1 to the PS2/Xbox versions right there and then. 

Lastly, I'm not sure if/how we can change the intensity/opacity of self shadows for particular areas/cutscenes. Or perhaps that's something that could be done if/when we find someone to help us restore soft shadows or the like down the line?

**Comment by elishacloud** [comment]
I already started to code some of this up last night, using FrozenFish24's fix from [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/63#issuecomment-445864307).  I _should_ be able to fully implement the following items this weekend:
* Disable ONLY James' self shadow for the locations mentioned
* Enable James' self shadow for the locations mentioned
* Disable ALL self shadows for the locations mentioned

The item I am not sure how to implement is blacklisting specific geometry pieces.  @FrozenFish24, if you can take a look at this, I will work on coding up the other ones.

**Comment by Polymega** [comment]
Thanks, Elisha!

**Comment by elishacloud** [comment]
I finished the first prototype of the "self shadows" feature.  This should have all the items listed above except the blacklisting of specific geometry pieces.  This requires a modification to the ini file.  You need to set `EnableSelfShadows = 1` for this to work.  This prototype also requires SH2 NA v1.0.  I will make this work with other binary files later.

Here is the test module for this:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2743368/d3d8.zip)

**Comment by Polymega** [comment]
Thanks again, Elisha! This will probably be a slow work-in-progress fix to fine tune but now we have the ball rolling thanks to you! 

Also @elishacloud , the SH2 WSF has received an update which you can now grab here: https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/sh2

This fixes #4 found in the first post of this thread: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/68

^ Because that specific fix is related to playing in widescreen Aero passed it to ThirteenAG and the WSF project.

**Comment by Polymega** [comment]
@elishacloud 
Dammit, I was thinking if you disable the self shadows for a room ID then it'd also disable them for cutscene IDs that take place in the room ID. That doesn't seem to be the case. If you wouldn't mind, please add the following: 

### Disable ONLY James' self shadow for the following:

Cutscene ID: 01F7A7C4 (4 bytes):
- 00000045 (James pulling noose)
- 0000003F (James and Maria in the labyrinth cell)
- 00000062 (Dog ending cutscene)

Keep the room IDs included in your fix **except** for: 

- **Remove** Room ID: 01FB7DAC (4 bytes): 
- 0000008C (noose pulling room)
- 000000BD (Dog ending room)

Thank you sir

**Comment by elishacloud** [comment]
Ok, below is an update.  I fixed the rooms and cutscenes that remove James' self shadow.  However I am not sure how to only have James self shadow, so I did not put that one in.  So room ID 00000018 (Apartment dead man & TV room) is not fixed yet.

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2743822/d3d8.zip)

**Comment by FrozenFish24** [comment]
Amazing work guys!

To blacklist geometry you'll have to move the renderstate check into the DrawPrimitive functions, e.g:

```
DWORD stencilPass;
HRESULT hr = GetRenderState(D3DRS_STENCILPASS, &stencilPass);
if (SUCCEEDED(hr) && (stencilPass == D3DSTENCILOP_ZERO || stencilPass == D3DSTENCILOP_REPLACE))
    SetRenderState(D3DRS_STENCILPASS, D3DSTENCILOP_KEEP);
```

then we can check for specific geometry similar to how you did for the 2D fog, here I check for the Apt. television (`DrawIndexedPrimitive`):
```
if (Type == D3DPT_TRIANGLESTRIP && MinVertexIndex == 0 && NumVertices == 4 && startIndex == 0 && primCount == 2)
    SetRenderState(D3DRS_STENCILPASS, D3DSTENCILOP_ZERO);
```

this may be too broad though, so we can expand it further by checking the "tv static" texture dimensions, this will also ensure it only disables shadows when the TV is on:

```
if (Type == D3DPT_TRIANGLESTRIP && MinVertexIndex == 0 && NumVertices == 4 && startIndex == 0 && primCount == 2) {
    LPDIRECT3DTEXTURE8 texture;
    D3DSURFACE_DESC desc;

    hr = GetTexture(0, (LPDIRECT3DBASETEXTURE8 *)&texture);
    if(SUCCEEDED(hr) && texture)
        hr = texture->GetLevelDesc(0, &desc);
        if(SUCCEEDED(hr) && desc.Width == 684 && desc.Height == 512)
            SetRenderState(D3DRS_STENCILPASS, D3DSTENCILOP_ZERO);
}
```

This should probably be further expanded by first checking for the correct room ID. I'm very inexperienced when it comes to directx so tell me if this looks sensible, and I'll move on to the rest.

**Comment by elishacloud** [comment]
> I was thinking if you disable the self shadows for a room ID then it'd also disable them for cutscene IDs that take place in the room ID.

@Polymega, I check the cutscene ID first.  If you are in a cutscene then I ignore the room ID.  My thoughts are that you should be either in a cutscene or in a room.  I could change this if you prefer.

@FrozenFish24, good work.  I will check out your solution later.

**Comment by Polymega** [comment]
> My thoughts are that you should be either in a cutscene or in a room. I could change this if you prefer.

No, that's perfectly fine to keep as-is. I wasn't aware of this when making the list but it's easy enough to change/adjust as you've already done. :)

**Comment by Polymega** [comment]
We'd probably need to find a way to disable it for specific NPCs as well while they're in certain room IDs.

James and all other dynamic objects have self-shadows while in the Woodside 2F Apt hallways, but when RPT spawns in behind the bars (after you hear the man screaming), RPT's self shadow also produces a shadow of his Great Knife which he is not actually holder. Additionally, when James turns his light on/off against him RPT's self shadow looks glitchy.

The PS2 version does **not** produce a self shadow for RPT while in this hallway: 

![sh2pc 2019-01-10 20-01-03](https://user-images.githubusercontent.com/27395260/51006760-b1514a00-1512-11e9-90b8-fb53516209bf.png)

Also, thinking ahead @FrozenFish24 , if you figure out a way to call code/scripts based on geometry could we theoretically determine James' eyeball meshes and could apply our own vertex/pixel shaders to it? AKA restore specularity? Because things like his flashlight and eye meshes theoretically should never change.

**Comment by elishacloud** [comment]
I made a check in for this initial code so that you guys can check out the code changes and how I check for room ID, cutscene ID and camera position.  See [e80d40f](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/e80d40f023caa2c42965d7754fd2e180caba2202).

**Comment by FrozenFish24** [comment]
@elishacloud Looking good!

If it's of any interest I've been experimenting with a patch based solution, so far it only gets us to the same point as the current fix but it may have potential:

Patch the following to `push 1` in the NA v1.0 exe:
`00503A74 push 2` = Fixes e.g. Grandfather Clock Shadow (File offset: 0x103A74)
`004FFFC6 push 3` = Enables James self-shadow (File offset: 0xFFFC6)
`004FFFE5 push 2` = Fixes e.g. Abstract Daddy Door (File offset: 0xFFFE5)

@Polymega 
>could we theoretically determine James' eyeball meshes and could apply our own vertex/pixel shaders to it?

I'm pretty sure we could, though I don't currently have the DirectX know how to implement it myself.

**Comment by Polymega** [comment]
> If it's of any interest I've been experimenting with a patch based solution

Nice! I can possibly already see an immediate benefit for this in regards to RPT behind the bars in the apartment. This one confused me for a while and I still don't really know what's going on here, but: 

https://youtu.be/ksdTKRIhI78

RPT _does_ have self shadows here. For the PS2 version, the prison bars will cast shadows on his body if James orients his light in the right direction. But, unlike the PS2 version, RPT seems to also have a self shadow when the flashlight is off. So whenever James turns on his light, that self shadow he had (with no lights on him) "flickers" away and it looks a bit buggy. 

Interestingly, if I use free cam and orient the camera at certain angles, RPT no longer has that self shadow when the flashlight is off. Thus, he smoothly lights up when James turns his light back on. I'm not sure what's causing this but it looks like RPT is inside an invisible box because his shadow is cast upon an invisible wall just a few feet behind him. 

In any case, I don't know if there's something special here that could be patched out so RPT can retain his self shadows (for when the prison bar shadows hit him) but without having that self shadow when the flashlight is off? 

I'm particularly being nitpicky about this one because of the significance: This is the first time we ever see RPT in the game; it's meant to be impactful as it is scary. So presentation here is more important than normal.

**Comment by elishacloud** [comment]
Added support for Self Shadows for all versions of SH2.  Check-in is: [be799cf](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/be799cf4fb79f2e689f022d1aa64681e6212ff0a).

@Polymega, Can you run a quick smoke test on this build? It does not need to be a thorough test.  I just want to validate that the functions are able to get the correct room ID, cutscene ID and cutscene position.  The following things should be tested:
1. `DisableRedCrossInCutScenes` - I modified this to use a new function to get the cutscene ID address.
2. `EnableSelfShadows` - Do a quick test on all three SH2 versions.  I am mainly concerned that the exclusions mentioned [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/76#issue-397467857) and [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/76#issuecomment-452959210) work.  You don't need to test all the exclusions, just a couple for each version of SH2 to make sure that it's getting the correct ID's and camera positions in each SH2 version.

Test module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2754188/d3d8.zip)

**Comment by Keith94** [comment]
Are you planning to remove `ResetScreenRes` now that it's deprecated?

**Comment by elishacloud** [comment]
I have no plans to remove the `ResetScreenRes` feature unless there is an issue with it.

**Comment by Polymega** [comment]
> @Polymega, Can you run a quick smoke test on this build?

Yes, sir. Using your new test .dll:

### `DisableRedCrossInCutScenes` 
- **All executable versions:** The red cross is no longer working at all. Meaning, it's not even display normally in-game (during non-cutscenes). I confirmed that I was not using the `DisableRedCross` mod. 

### Self Shadows: 
- **All executable versions:** Things seem to be working fine. Self shadow becomes disabled during specific camera cuts/rooms as intended. 
The only thing I believe got mixed up is the room and cutscene IDs for the Labyrinth prison cell. Right now, _nothing_ has self shadows in the Room ID and _everything_ has self shadows during the cutscene ID. To confirm, **only James'** self shadow should be disabled for these IDs:
   - Room ID: 01FB7DAC (4 bytes): 00000089 (Labyrinth cell)
   - Cutscene ID: 01F7A7C4 (4 bytes): 0000003F (Labyrinth cell)

**Comment by elishacloud** [comment]
@Polymega,

1. I think I fixed the `DisableRedCrossInCutScenes` issue.
2. I am not sure what is happening for the Labyrinth cell room ID 00000089 and cutscene ID 0000003F.  Both of these IDs are already in the code, see [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/be799cf4fb79f2e689f022d1aa64681e6212ff0a/Wrappers/d3d8/IDirect3DDevice8.cpp#L267) and [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/be799cf4fb79f2e689f022d1aa64681e6212ff0a/Wrappers/d3d8/IDirect3DDevice8.cpp#L264).
3. I added Labyrinth cell cutscene ID 00000040.

Test module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2757894/d3d8.zip)

**Comment by Polymega** [comment]
> I think I fixed the DisableRedCrossInCutScenes issue.

Yes sir, issue is fixed and works across all executables. Nicely done, Eilsha! 

> I am not sure what is happening for the Labyrinth cell room

Yeah, that's strange how Maria has lost her self shadow as well for cutscene 0000003F and 00000040. 

Also, could you please add another cutscene that **only** removes James' self shadow? 
- Cutscene ID: 00000047

To recap for my own records, only James' self shadow should be disabled for the following: 
- Room ID: 00000089 (Labyrinth cell)
- Cutscene ID: 0000003F (Labyrinth cell, talking to Maria before FMV)
- Cutscene ID: 00000040 (Labyrinth cell, talking to Maria after FMV)
- Cutscene ID: 00000047 (Labyrinth cell, finding Maria dead on bed)

I plan on making a Google Sheet with these IDs sometime in the future if that would help with organization?

And apologies on the add-them-as-they-go type of inclusions. I anticipated this would very much be a trial-and-error thing for such a large fix!

**Comment by Polymega** [comment]
>Code updated:
> Added Cutscene ID: 00000047 (Labyrinth cell, finding Maria dead on bed)

Thanks Elisha! 

May I ask you to double-check and ensure the following IDs are under "only James' self shadow disabled" and not "all self shadows disabled"? Because this new ID also has Maria's self shadow disabled as well (she should keep her's): 

Room ID: 00000089
Cutscene ID: 0000003F, 00000047, 00000047

**Comment by elishacloud** [comment]
> May I ask you to double-check and ensure the following IDs are under "only James' self shadow disabled" and not "all self shadows disabled"?

Yes, verified.  You can see it in the code [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/dc7759c85d20701444c71881a447abdf868634e6/Wrappers/d3d8/IDirect3DDevice8.cpp#L264).  Those IDs are along side other IDs, which also have "only James' self shadow disabled":
* Cutscene ID: 00000028, Cutscene camera position: -142102.8125
* Cutscene ID: 00000054, Cutscene camera position: -19418.82617
* Cutscene ID: 00000059
* Etc.

When these IDs are found I send `D3DSTENCILOP_REPLACE` which you can see [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/dc7759c85d20701444c71881a447abdf868634e6/Wrappers/d3d8/IDirect3DDevice8.cpp#L278) and [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/dc7759c85d20701444c71881a447abdf868634e6/Wrappers/d3d8/IDirect3DDevice8.h#L9).

My understanding from this [comment](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/63#issuecomment-452485133) was that I simply needed to send `D3DSTENCILOP_REPLACE` to disable only James' self shadows.  Is it possible that in this part of the game `D3DSTENCILOP_REPLACE` effects both James and Maria?

**Comment by Polymega** [comment]
Thank you for checking. 

> Is it possible that in this part of the game `D3DSTENCILOP_REPLACE` effects both James and Maria?

It definitely seems like that's the case now. Let's hold off adding any new IDs for the moment. I've asked @Bigmanjapan if there's a way to simply enabled ALL self shadows (as we've done) but then perhaps find a specific address to only kill James' self shadow in-game. If such an address exists, we can use this approach to only kill his shadow instead of doing the `D3DSTENCILOP_REPLACE` method we're currently doing. Hopefully that will also resolve issues such as those found in the Labyrinth Cell Room.

**Comment by Polymega** [comment]
Thank you for checking. 

> Is it possible that in this part of the game `D3DSTENCILOP_REPLACE` effects both James and Maria?

It definitely seems like that's the case now. 

Let's hold off adding any new IDs for the moment. I've asked @Bigmanjapan if there's a way to find a specific address to only kill James' self shadow in-game. If such an address exists, we can simply enabled ALL shadows as we've currently done, then use that specific address/approach to only kill his shadow, instead of doing the `D3DSTENCILOP_REPLACE` method we're currently doing. 

Hopefully that will also resolve issues such as those found in the Labyrinth Cell Room.
