### ISSUE TITLE
Proper written changelog?

### ISSUE THREAD

**Issue by metatronicsauce** [elishacloud/Silent-Hill-2-Enhancements#760]
Sorry if this seems silly or redundant but there's been plenty of times in the development of this project that I've been wondering which features are being added, or when certain features were added. Usually when I wasn't sure if I had updated the mod or not. I know I can watch the update videos, and compare with my current game if needed. But having a written changelog on the website would be nice. I didn't even know the CRT filter was now included because I skimmed the update video.

Though I also understand this project has been going for a long time and it might be inconvenient to have to start a changelog at this current point, so it's fine if it never happens, just thought I would bring that up.

I'm very grateful for all your hard work regardless

**Comment by elishacloud** [comment]
You can check out this page for a log of features and when they were added:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases
