### ISSUE TITLE
How do I open Silent hill 2 enhanced edition

### ISSUE THREAD

**Issue by Supaboi2323** [elishacloud/Silent-Hill-2-Enhancements#763]
So I just installed Silent hill 2 enhanced edition today and I've been playing for about 2 hours. I just quit out of it but I don't know how to get back in. I don't know what application or file I need to access in order to start playing again. I completed all the steps in order to out the enhanced edition inside of the file that held silent hill 2 in it. Did all my data get deleted? Where do I go to access Silent Hill 2 Enhanced Edition? It might have something do with the fact that the file im trying to use doesnt have the enhanced edition files. Any ideas?

**Comment by Polymega** [comment]
Go to the folder where you installed the game and look for `sh2pc.exe`. You'd click/launch this file to run the game. You can also right click this file and select **Send to > Desktop (create shortcut)**. This will create a shortcut to the game so you can launch/run it from your desktop instead.
