### ISSUE TITLE
Font error with umlauts quitting the game (letter "ü")

### ISSUE THREAD

**Issue by frankyfife** [elishacloud/Silent-Hill-2-Enhancements#764]
Font error with umlauts when ending the game (german language).

Reproducible as follows: Start or load a game, go ingame, go to the pause menue and select quit (in german "Beenden"). The letter "Ü" insn't displayed correctly.

Can this be replicated each time? Yes

Please provide a photo/video/audio of the issue

![Screenshot 2023-03-22 112830](https://user-images.githubusercontent.com/16177808/226875742-18f5589c-aed3-4998-922c-fec3374ec1d3.png)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11038909/d3d8.log)

**Comment by frankyfife** [comment]
Nope i have a legal retail copy of this game used for the installation. The screenshat was taken from a todays brand new and clean install from today, using the german retail release (3 disc, EAN 4012927070260,  Setup.exe MD5	3D76B2AC0A3EB4449F3677D5F0ACA230). No custom files, only the ones that came with the ee setup-tool  (online installer, downloaded today) on top of the clean game installation. nothing else, not even my old save files.

![Screenshot 2023-03-22 155624](https://user-images.githubusercontent.com/16177808/226945057-630ae170-f68e-4a6d-8bdf-1dbdac8915be.png)

there is no update available, which make sense, since the installation is from today.

anyway, i deleted **all** files an did a second run (clean install, SH2EEsetup.exe from online source, not a single custom file or manual change within the configuration menue), same behaviour. Within the menues (options, item menue etc.) the umlauts are displayed correctly.

the following screenshot is from my **old** installation (i did a backup), same install source, no problems at all.

![sh2pc 2023-03-22 16-00-20](https://user-images.githubusercontent.com/16177808/226946615-b7fa5d60-e958-44ad-b938-a8f93fa2c550.png)

**Comment by Polymega** [comment]
Can you navigate to `.\sh2e\etc\resource\` and attach your copy of the `r_menu_g.res` file here?

**Comment by frankyfife** [comment]
Sure.

[r_menu_g.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11042833/r_menu_g.zip)

Encoding is, according to np+, UTF-8. I convertet it to ANSI and the Problem is gone.

**Comment by Polymega** [comment]
Thanks for testing. I'm not sure how they got encoded to UTF-8 but I will make a note of this and ensure all the Latin `r_menu_*.res` files are in ANSI. We will be pushing out a hotfix update for our project soon and I will include this as part of that update.
