### ISSUE TITLE
[Request] V-Sync control

### ISSUE THREAD

**Issue by 60d74** [elishacloud/Silent-Hill-2-Enhancements#765]
add ability to turn on and off vertical sync in the game 
(i know you can force off vsync in the graphics card panel, but apparently amd has some problems with this, and i cant manage sync via the driver for all d3d9 games)

**Comment by elishacloud** [comment]
Are you getting screen tearing?  The only reason to add vsync is for screen tearing.

**Comment by mikeoxmaull** [comment]
> Are you getting screen tearing?  The only reason to add vsync is for screen tearing.

no i dont get screen tearing. i know that disabling vsync will cause this, but i prefer the smallest input lag

so i want to turn it off, but the game doesnt provide that

(there are also other ways to get rid of tearing, like ssync)

**Comment by mikeoxmaull** [comment]
> It wouldn't be of much use because currently the game is capped at 60FPS. uncapping from that would result in issues.

i always use rtss to limit frames, even with vsync, for better framepacing and input lag

i just think people need to be warned that disabling lock completely can cause problems and give them a choice

**Comment by elishacloud** [comment]
Turning on and off vsync is mainly for fixing screen tearing.  As far as input lag, turning off vsync in this game shouldn't change input lag since the game is limited to 60 FPS and it only captures input twice each frame.  So this game will have the same amount of input lag with or without vsync on.
