### ISSUE TITLE
Cannot open SH2EEsetup.exe

### ISSUE THREAD

**Issue by stormyshark** [elishacloud/Silent-Hill-2-Enhancements#767]
Hello! I'm having a bit of an issue with the SH2EEsetup.exe file, as every time I try to open it, I get this pop-up error:

![image](https://user-images.githubusercontent.com/129906376/229933359-6171a808-1ff6-41b4-b928-91c016992449.png)

I'm not exactly sure how to rectify this issue, nor am I sure how this started happening. I have auto-updates turned on so I'm wondering if that has something to do with this, but again, I am unsure.

Here's a copy of my d3d8.log file down below:

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11153644/d3d8.log)

Thank you!

**Comment by Polymega** [comment]
Hi there,

We ran into an issue with the Setup Tool (`SH2EEsetup.exe)` auto updating itself to the latest version. Can you grab the newest version of the Setup Tool ([found here](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE)) and place it in your game's directory? Run the tool like normal and see if you still have this problem.

Thanks

**Comment by stormyshark** [comment]
It worked! Thank you so much!

**Comment by Polymega** [comment]
Great! I'll close this ticket out
