### ISSUE TITLE
SH2EE simply not downloading.

### ISSUE THREAD

**Issue by pawtttt** [elishacloud/Silent-Hill-2-Enhancements#769]
I followed the steps on the website, and have a full copy of the original game from myabandonware (let me know if this is the problem, but it does include the original exe file for the game as stated on the website and people on reddit said this was the best way).

I downloaded the setup. I let it through my firewall and it downloads and opens, so I'm assuming that isn't the issue: it comes in the actual downloading of the files themselves.

I click download, I click my Silent Hill 2 file, and it downloads; but then nothing appears. After the download is finished, the files are simply... not there, lmao. 

So I tried to run the official sh2 exe file assuming that maybe it had downloaded, and was working in the background or maybe I'm just stupid and didn't see the files added, but no. Ofc, it didn't run. I've completed the setup like 4 times now and each time I see nothing new added to the folder I selected. Nothing changes regarding the running of sh2, and I just can't seem to find the problem.

Any help? I really wanna play this game :,)

**Comment by Polymega** [comment]
Sorry you're having issues. To start: Can you share a snapshot of your SH2 game folder?

The Setup Tool (`SH2EEsetup.exe`) you downloaded from our project site: Right click the file, select **Properties**, then go to the **Details** tab. What is the "Product Version" number?

**Comment by pawtttt** [comment]
product version: 1.1.2

here's the screenshot! :)
![silenthill2gamefolder](https://user-images.githubusercontent.com/130002281/230237638-935f8f3d-218b-4db4-aeb2-ca992568d039.png)

**Comment by Polymega** [comment]
I'm wondering if your antivirus protector or firewall is preventing you from download and/or extracting the files. Can you check either or these to confirm? Here's what I'd recommend:

After confirming those things, the next time you run the Setup Tool, only install the required packages, which are the **SH2 Enhancement Module**, **Enhanced Executable**, and **Credits**. This way, your overall download time will be a lot less which is what we want for quick testing purposes.

![image](https://user-images.githubusercontent.com/27395260/230244190-8aa256b2-ace5-4b66-8f9d-2a972b8771c5.png)

If the files are successfully downloaded and placed in the game's directory, you should see these new files in the game's directory:

```
sh2e\movie\credits.bik
d3d8.dll
SH2EEconfig.exe
SH2EEsetup.dat
SH2EEsetup.exe
```

[Here's how to shown known file types for Windows.](https://www.wikihow.tech/Show-File-Extensions-on-Windows)

If the files are successfully downloaded and placed in the game's directory, you can then run `SH2EEsetup.exe` **found in the game's folder**, select "Install or Repair Packages", and download the remaining packages you haven't already downloaded.

![image](https://user-images.githubusercontent.com/27395260/230244725-502bd3fb-fa72-4205-b4cb-455be39c56e0.png)

![image](https://user-images.githubusercontent.com/27395260/230244770-3a25b566-5e2e-4dcb-9960-97fc0513785a.png)

**Comment by pawtttt** [comment]
I rechecked whether the exception in my firewall worked, and I have the installer with netguard off and access to designated ports. I'm wondering if there's anything else I should add as an exception? I tried downloading again, this time with only the three selected, this is what my game file looks like (still the same, basically :,))
![Screenshot 2023-04-06 123339](https://user-images.githubusercontent.com/130002281/230365041-f17becf8-2f7b-4bc6-9795-13116fee459a.png)
![Screenshot 2023-04-06 123145](https://user-images.githubusercontent.com/130002281/230365056-7c35138d-ddf9-48c8-b880-86b36864574d.png)

**Comment by Polymega** [comment]
I just tested on a fresh install using the tool and everything downloaded/extracted fine. What antivirus software are you using?

**Comment by pawtttt** [comment]
McAfee!

**Comment by Polymega** [comment]
Can you please check your protection history with McAfee to see if it's either blocking the download outright, preventing the files from being downloaded to a temporary folder for installation, or preventing the tool from extracting the files at the end of the process? I'm led to believe this might be the issue.

I'm not sure if you're able to sign in and see it, but here is the tool cleared by Windows Defender:
https://www.microsoft.com/en-us/wdsi/submission/b8610e48-0afe-4ee9-aece-4247fa3095b5

![image](https://user-images.githubusercontent.com/27395260/230472828-2654305a-b6e7-4cdc-bcc1-3da9d65b7aef.png)
![image](https://user-images.githubusercontent.com/27395260/230472915-9432bfa3-8674-4a42-b234-119c348ee0b8.png)

and Avast:

![image](https://user-images.githubusercontent.com/27395260/230473016-d66bcb91-6199-449e-91b4-466e71fde680.png)

**Comment by pawtttt** [comment]
My security history does show when the setup was flagged as a virus in a false positive, but I'm pretty certain this was when it refused to download the setup tool at all:

![sh2virus](https://user-images.githubusercontent.com/130002281/230659498-70405359-08de-44dc-8d9f-6590993a63a1.png)
![shh2222](https://user-images.githubusercontent.com/130002281/230659505-c6abcb27-9e50-45d9-a433-302abd044f72.png)
