### ISSUE TITLE
sh2pc.exe app error

### ISSUE THREAD

**Issue by mbl2592** [elishacloud/Silent-Hill-2-Enhancements#77]
Everytime I run the exe after installing the d3d8.zip the app instantly closes with the msg "unable to start correctly 0xc0000005

I´ve set d3d8to9 = 0 and installed the DX and Visual libraries to no avail.

**Comment by Polymega** [comment]
A cursory Google search suggests your anti virus/anti malware software is preventing the game from running. Try white listing the game through your protection software and see if that solves your issue.

**Comment by mbl2592** [comment]
I´ve added the folder and file to windows defender whitelist, still getting the same error

**Comment by mbl2592** [comment]
![capture](https://user-images.githubusercontent.com/39779441/50944826-a71e4580-1457-11e9-8e24-5397b1a2fb66.PNG)

**Comment by Polymega** [comment]
Thank you. Have you tried using an .exe provided on the Installation Guide to see if it will launch for you then? http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE 

If that doesn't work, can you lastly upload a copy of your `d3d8.ini` file here?

**Comment by mbl2592** [comment]
[d3d8.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2743550/d3d8.txt)

**Comment by Polymega** [comment]
Thanks @BinariGuy ! This was a new issue to me so I wasn't sure where to go with it. Some other Google results for other games/programs mentioned the same thing about uninstalling and reinstalling.

**Comment by BinariGuy** [comment]
Any news on this?
the problem remains?

**Comment by mbl2592** [comment]
Reinstalled the game and still have the same error msg

**Comment by mbl2592** [comment]
Seems that moving the folder to C:/ did the trick, wonder why the game refused to work on a different drive

**Comment by elishacloud** [comment]
Closing issue.
