### ISSUE TITLE
D-Pad not working only when on "Action Level" selection

### ISSUE THREAD

**Issue by XanoPhobious** [elishacloud/Silent-Hill-2-Enhancements#770]
Hi...this is a simple bug: I use "Hybrid Mode" for D-Pad and when you suppose to choose what "Action Level" you want, the D-Pad will not work (analog stick is still working); happens in Main and Sub Scenario.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11173231/d3d8.log)

**Comment by Polymega** [comment]
Hi there, can you also attached your `Xidi.ini` file here?
Thanks

**Comment by XanoPhobious** [comment]
Sure. I cannot upload ".ini" file, so I change it to ".txt".
[Xidi.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11173350/Xidi.txt)

**Comment by Polymega** [comment]
Thanks. Your Xidi.ini file looks fine. I'm not sure what exactly is going on. What type of controller are you using? And to confirm: Once you're in the game, the D-pad will navigate menus such as the pause screen, inventory screen, etc?

**Comment by XanoPhobious** [comment]
My controller is Xbox One controller.
That's correct in every menu the D-Pad is working, except the Action Level.

**Comment by Polymega** [comment]
_Oh oh oh..._ sorry, I tested the main menu but not _up to_ the Action/Riddle selection. Yes, I have the same problem. It looks like the checks we have in place to know when we're in a menu changes _just for this selection._ How dumb...

We will need to patch this in the future so, for now, it won't work on this selection. Sorry about that.

@elishacloud 
Glad we didn't publicly advertise this feature yet! 😅  To fix this, we can add 'GetMenuEvent' as part of the check: 

Change [this line](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/ControllerTweaks.cpp#L62) to:

```c++
const bool IsIngame = (GetEventIndex() != EVENT_IN_GAME || GetMenuEvent() == 7 || (GetEventIndex() == EVENT_IN_GAME && InputTweaksRef.IsInFullScreenImageEvent()));		// Not currently in-game, so in a menu || Within any selection on the main menu screen || In-game but a text prompt is currently on-screen.
```

**Comment by elishacloud** [comment]
Ok, try this one:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11173744/d3d8.zip)

**Comment by XanoPhobious** [comment]
Awesome that fix the bug.
Thank you so much.
