### ISSUE TITLE
It's not responding

### ISSUE THREAD

**Issue by olu7540** [elishacloud/Silent-Hill-2-Enhancements#773]
![Desktop 2023 04 17 - 03 41 50 01_Moment](https://user-images.githubusercontent.com/130928662/232334897-63ed4378-6a55-41b4-a760-35dd4a3e22e4.jpg)
Is there a solution?

**Comment by olu7540** [comment]
![Desktop Screenshot 2023 04 17 - 03 48 20 22](https://user-images.githubusercontent.com/130928662/232334994-e31fb9b5-317a-487e-9469-b266ce711a1b.png)

**Comment by Polymega** [comment]
Hello,

Where did you download our project files from?

Also, I'm wondering if the Asian (Korean?) characters in the folder path is causing this to happen. As a test, can you temporarily move the Silent Hill 2 game folder to a directory that only uses regular Latin characters?

**Comment by olu7540** [comment]
It's because I'm Korean!

**Comment by olu7540** [comment]
It's because I'm Korean

**Comment by Polymega** [comment]
Can you tell me where you downloaded our project files from?

**Comment by sunnflower40** [comment]
Help please, i have this exact problem. I got the files from Myabandonware and some missing dlls from dlldownloader.
