### ISSUE TITLE
Graphics bug at final level

### ISSUE THREAD

**Issue by NotEvenFlinched** [elishacloud/Silent-Hill-2-Enhancements#774]
Hi guys
Here is the bug I accidentally found on last level with Mary on the roof
To reproduce just try to change camera angle by pressing ctral + move mouse
https://user-images.githubusercontent.com/41795843/232336733-2a8cc0b5-d84d-4bcb-b6a3-b4b31502b5f0.mp4

**Comment by Polymega** [comment]
How weird... 

@Bigmanjapan
Is this something you could look into? I tested with a controller and on vanilla SH2 PC but it doesn't occur there. This seems to be caused from our feature that allows the mouse to control James/the camera (`EnableEnhancedMouse = 1`). Seems really strange emulating controller joystick movements on the mouse would cause this to happen.

Anyway, it looks to only happen within a specific area while under this camera angle:

https://user-images.githubusercontent.com/27395260/232340045-f6e9590e-c45b-4eb3-8192-dc1286d9fba8.mp4

I was wondering if this is related to a similar visual bug when you disable complex fog, but they look to be two different things:

https://user-images.githubusercontent.com/27395260/232340185-087474ec-db54-474d-8546-0dc415f74b6f.mp4

**Comment by Polymega** [comment]
I don't know why it's doing it, but here's what's happening:

Once you get to the top of the stairs, the game de-spawns the bottom half of this room and replaces it with, what I assume is, a solid black cube. When this bug happens, the game is re-spawning the bottom half of this room. When it does this, the bottom of the room is getting "sliced" off because the draw distance only goes so far. 

https://user-images.githubusercontent.com/27395260/232340687-ea4f3f83-796b-4e5d-80b6-074ff4959100.mp4

**Comment by Polymega** [comment]
Here is a solution for this. It will fix the bug reported and also the vanilla rendering bug when advanced fog is disabled for this room:

**On game launch:**
- Set `FinalBossDrawDistance` == 2400f
- nop `FinalBossBlackBoxCover`

-----------

if Room ID == 0xBB && [JamesPosYAddr](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L33) <= -14600f
- `FinalBossBottomWalkwaySpawn` == -20000f
- `FinalBossBottomFloorSpawn` == -20000f

else

- `FinalBossBottomWalkwaySpawn` == -8000f
- `FinalBossBottomFloorSpawn` == -4000f

--------------

| Variable | 1.0 | 1.1 | DC |
| --- | --- | --- | --- |
| `FinalBossDrawDistance` | 00800614 float | 008041FC float | 008031FC float |
| `FinalBossBlackBoxCover` |  004413C3 - fcomp dword ptr [0063B85C] | 00441583 - fcomp dword ptr [0063C83C] | 00441583 - fcomp dword ptr [0063B83C] |
| `FinalBossBottomWalkwaySpawn` | 006388F4 float | 006398D4 float | 006388D4 float |
| `FinalBossBottomFloorSpawn` | 006388F8 float | 006398D8 float | 006388D8 float |

--------------

This should be made into its own, new fix named something like `FinalBossRoomFix`.

**Comment by mercury501** [comment]
@Polymega I'll implement this soon, will keep you posted

**Comment by mercury501** [comment]
I've implemented @Polymega 's fix, here's a test build:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11409664/d3d8.zip)

Cheers!

**Comment by Polymega** [comment]
Thanks, Mercury! 1.0 looks great, but the draw distance pointer for 1.1 and DC isn't correct:

![Screenshot 2023-05-05 17-05-37](https://user-images.githubusercontent.com/27395260/236568935-c5c101c0-6ca5-41aa-81fe-9301ace1d30d.png)

I believe all the other variables are correct/accounted for in all binaries, though.

**Comment by mercury501** [comment]
The address retrieval wasn't correct, here's a correct build:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11415833/d3d8.zip)

**Comment by Polymega** [comment]
Thank you! All looks good now. Great job on this, Mercury!

Upon testing, there's one other change we'll need to do that I overlooked. Sorry about that. Can you please add `FinalBossBlackBoxCover2` to this fix? It would be placed in the conditional check. So:

if Room ID == 0xBB && JamesPosYAddr <= -14600f

- `FinalBossBlackBoxSpawn` == -25000f

else 

- `FinalBossBlackBoxSpawn` == -12000f

Thank you!

| Variable | 1.0 | 1.1 | DC |
| --- | --- | --- | --- |
| `FinalBossBlackBoxSpawn` | 0063B854 float | 0063C834 float | 0063B834 float |

**Comment by Polymega** [comment]
Actually Mercury, with the inclusion of `FinalBossBlackSpawn` we can **remove** `FinalBossBlackCover` from the fix (the one that nops code). Also, let's please bump the float change from -25000f to -30000f.

Here's how things would change:

**On game launch:**
- Set `FinalBossDrawDistance` == 30000f

-----------

if Room ID == 0xBB && [JamesPosYAddr](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L33) <= -14600f 
- `FinalBossBottomWalkwaySpawn` == ~~-25000f~~ -30000f
- `FinalBossBottomFloorSpawn` == ~~-25000f~~ -30000f
- **NEW:** `FinalBossBlackBoxSpawn` == ~~-25000f~~ -30000f
- ~~nop `FinalBossBlackBoxCover`~~

else

- `FinalBossBottomWalkwaySpawn` == -8000f
- `FinalBossBottomFloorSpawn` == -4000f
- **NEW:** `FinalBossBlackBoxSpawn` == -12000f
- ~~"un-nop" `FinalBossBlackBoxCover`~~

--------------

| Variable | 1.0 | 1.1 | DC |
| --- | --- | --- | --- |
| `FinalBossDrawDistance` | 00800614 float | 008041FC float | 008031FC float |
| `FinalBossBottomWalkwaySpawn` | 006388F4 float | 006398D4 float | 006388D4 float |
| `FinalBossBottomFloorSpawn` | 006388F8 float | 006398D8 float | 006388D8 float |
| `FinalBossBlackBoxSpawn` | 0063B854 float | 0063C834 float | 0063B834 float |
| `FinalBossBlackBoxCover` |  004413C3 - fcomp dword ptr [0063B85C] | 00441583 - fcomp dword ptr [0063C83C] | 00441583 - fcomp dword ptr [0063B83C] |

--------------

This should be made into its own, new fix named something like `FinalBossRoomFix`.

**Comment by mercury501** [comment]
Here you go, with your latest suggested fixes!

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11423574/d3d8.zip)

**Comment by Polymega** [comment]
Thanks for reporting this! We have a fix in place for this which will officially be a part of our next project update.
