### ISSUE TITLE
silent hill enhanced edition error 0xc00007b/how to fix?

### ISSUE THREAD

**Issue by nazal04** [elishacloud/Silent-Hill-2-Enhancements#776]

**Comment by Polymega** [comment]
If you _temporarily_ remove the `dsound.dll` file from the game's directory, does the game then launch for you?

**Comment by 60Fman** [comment]
> If you _temporarily_ remove the `dsound.dll` file from the game's directory, does the game then launch for you?

Thank you Polymega, i had the same problem and wasn't able to solve it, i looked for it on google and found your solution, now the SH2EE works and start. 
Thank you very much, i signed up here just to say thanks. ^_^
