### ISSUE TITLE
Creeper room puzzle is bugged

### ISSUE THREAD

**Issue by Vomitt** [elishacloud/Silent-Hill-2-Enhancements#779]
The keys that are lit are 2 and 4. No combination of these numbers will open the door.

I can refer you to a twitch vod of my playthrough if links are allowed here.

**Comment by Vomitt** [comment]
Nevermind, it was 244 lol

Must have forgot to input it. Forget what I said!

**Comment by Polymega** [comment]
No worries. SH2 puzzles can be tricky. 😛 Glad you got it figured out.
