### ISSUE TITLE
Multilanguage Enhanced .exe hangs if not run as admin

### ISSUE THREAD

**Issue by seanamosw** [elishacloud/Silent-Hill-2-Enhancements#78]
I initially tried playing with with the `Multilanguage Enhanced .exe (Director's Cut)` but found it would hang with a black screen and need to be killed with the task manager. However, running `sh2pc.exe` as administrator works around the issue.

Changing to `English Enhanced .exe`, running as admin is not required.

**Comment by Storm3000** [comment]
I think this is related with the random freezes that I'm having with this game. In your case, surely has to do with the single core affinity option. Disable the singlecoreaffinity option on d3d8.ini and try again. While playing, you will have to activate the single core affinity on task manager to avoid crashes or sound issues.

**Comment by Polymega** [comment]
@seanamosw @Storm3000 

[The newest release of the project](https://www.youtube.com/watch?v=377H3K9jAGA) allows you to change the language in the North American executable. Try using the North American .exe (and change it to your desired language) and see if you still have running issues with this .exe.

**Comment by Polymega** [comment]
@seanamosw 
Elisha has made some behind-the-scenes improvements with how the project handles custom files. [Would you mind downloading the latest build of the project](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3133197/d3d8.zip) and playing the game with the European (Director's Cut) executable to see if the crashes still persist?

**Comment by Storm3000** [comment]
@Polymega 
No, it doesn't work for me.

Anyway, I'm using the American .exe now. It works so much better than the European version. Even the random stuttering it's fixed. I wouldn't recommend to use the European .exe anymore. And the American .exe is the same thing, the only difference are the main titles in english.

**Comment by Polymega** [comment]
Thanks for following up, Storm3000. A few more questions, if you don't mind me asking: What version of Windows are you using and what GPU do you have? 

I palytested the EU exe on my Win7/Nvidia computer and ran into no issues. I'm curious if certain versions of Windows/GPUs may have any affect on that executable's performance.

**Comment by elishacloud** [comment]
@Storm3000, if you could send us the log file when it crashes that would help.  The log file has OS, GPU and other information in it.

**Comment by Storm3000** [comment]
I'm sorry for the delay to answer, guys.

I use Windows 7 Ultimate Service Pack 1 x64. My processor is: AMD Phenom II X4 850 3.30 GHz. RAM: 4 GB.  My GPU: Nvidia GeForce GT 520 (2 GB).

How can I make a log file?

**Comment by elishacloud** [comment]
Closing as this is specific to the DC version of the game and we are moving to the NA version.
