### ISSUE TITLE
Translation Pack Discussion - Filipino

### ISSUE THREAD

**Issue by WrichmondChua** [elishacloud/Silent-Hill-2-Enhancements#785]
Hello. I need help on how to run the sh2msg converter tool. I still don't understand how to run it using cmd or more like it's difficult for me to set it up altogether. Thanks.

**Comment by WrichmondChua** [comment]
The error that I need help to troubleshoot:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/3e75c201-280f-4058-a6e0-5e735875dca7)

**Comment by Polymega** [comment]
@IlDucci may I ask you to help with this?

**Comment by Infrid** [comment]
Hi, I am the developer of this tool. Might be intimating at first if you never used a command-line program.

Don't worry, make sure you read the README careful. There are examples here

https://github.com/loadwordteam/SH2MSGConvert

Basically you need the msg files and the tool on the same directory, it's the easier way, then follow the example.

Let me know!

**Comment by WrichmondChua** [comment]
> Hi, I am the developer of this tool. Might be intimating at first if you never used a command-line program.
> 
> Don't worry, make sure you read the README careful. There are examples here
> 
> https://github.com/loadwordteam/SH2MSGConvert
> 
> Basically you need the msg files and the tool on the same directory, it's the easier way, then follow the example.
> 
> Let me know!

Thanks for the help, man. I was able to figure out how to use this tool last night through following the instructions thoroughly and through trial and error as well.

**Comment by WrichmondChua** [comment]
Hello. I need help on how to move or fit these texts accordingly.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/a1ab7ea3-3f29-44df-9f3b-1d18c32e98ad)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/06aadc1b-749a-4d4e-8d5a-55593b16edf7)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/12660a15-9beb-494f-ae32-267ecc9b1090)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/2a778acc-b6c7-44a0-9acd-edb6710dc3e4)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/f7f671d9-5bec-4320-9306-d6f85206ad85)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/89e4ca79-ca05-4c9f-aada-418a4bbe56f4)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/92995154-e277-4442-9f70-dab600236dd0)

**Comment by WrichmondChua** [comment]
Hello, How do I fit these in a screen accordingly?

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/780e04b1-67b8-41a3-99b2-857e0cf5e012)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/59139222/d036546b-cbe2-4bd4-bec4-a3a2f464bbce)

**Comment by IlDucci** [comment]
> ![image](https://user-images.githubusercontent.com/59139222/239675523-780e04b1-67b8-41a3-99b2-857e0cf5e012.png)

Those hint lines at the bottom of the OPTIONS screens must be one line long and fit inside the window. If the text is long, you must abbreviate, summarize or rewrite it so it fits. There's nothing else we can do.

> ![image](https://user-images.githubusercontent.com/59139222/239675540-d036546b-cbe2-4bd4-bec4-a3a2f464bbce.png)

Have you tried to add a line jump in that overflowed line, like the ones seen in the Memory Card screen or ingame? If that does not work, you will also have to summarize/abbreviate/rewrite, I'm afraid.

**Comment by Polymega** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/9aa0e916-65b7-4698-8205-221e4da6fa83)

^ This particular string is weird. It doesn't behave like all of the other text strings in the game. I remember I had to add a bunch of spaces at the beginning of the line to give the illusion that it's centered on the screen. The same goes for the BFaW warning text ([see here](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/issues/8#issuecomment-1511417141)); that text string also doesn't behave like all of the other. 

> you will also have to summarize/abbreviate/rewrite, I'm afraid.

Indeed. And remember t[his very important rule](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.uqvary8gm8zv): 

### **Do all of your edits while playing in a 4:3 aspect ratio!** 

Your translated work must comfortably fit within a 4:3 aspect ratio. [See here for more information.](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a)

**Comment by WrichmondChua** [comment]
> 

I haven't tried using linejump as I have no idea how to use it but for the meantime, I will try to make my translation fit and accurate as much as possible.

**Comment by WrichmondChua** [comment]
> > ![image](https://user-images.githubusercontent.com/59139222/239675523-780e04b1-67b8-41a3-99b2-857e0cf5e012.png)
> 
> Those hint lines at the bottom of the OPTIONS screens must be one line long and fit inside the window. If the text is long, you must abbreviate, summarize or rewrite it so it fits. There's nothing else we can do.
> 
> > ![image](https://user-images.githubusercontent.com/59139222/239675540-d036546b-cbe2-4bd4-bec4-a3a2f464bbce.png)
> 
> Have you tried to add a line jump in that overflowed line, like the ones seen in the Memory Card screen or ingame? If that does not work, you will also have to summarize/abbreviate/rewrite, I'm afraid.

I haven't tried using linejump as I have no idea how to use it but for the meantime, I will try to make my translation fit and accurate as much as possible.

**Comment by WrichmondChua** [comment]
Thank you, guys.

**Comment by WrichmondChua** [comment]
For those who are looking forward for this translation pack, this will take a while to finish. It might even take years for me to finish it as I only have a limited time to do so. Thank you for your kind understanding.

**Comment by WrichmondChua** [comment]
Announcement: This project will be officially dropped for the meantime due to lack of time in developing this fan translation project. Also, I need to focus on bigger life responsibilities that are coming along the way in the future after my college graduation. This fan translation may/might be resumed in the future. Thank you for your kind understanding.
