### ISSUE TITLE
Pre rendered cutscenes audio popping issue

### ISSUE THREAD

**Issue by RalseiButCoding** [elishacloud/Silent-Hill-2-Enhancements#789]
I just downloaded the modbwith the fully extracted version of the game. So far I am running into an issue where the audio is poppin when pre rendered cutscenes play in game. And It's only the pre rendered cutscenes.

The other movies like the trailers have no audio issues what so ever

**Comment by Polymega** [comment]
Hello,

Please attached a copy of your `d3d8.log` file, which can be found in the game's main folder.
