### ISSUE TITLE
[Question] Reshade SH2

### ISSUE THREAD

**Issue by BinariGuy** [elishacloud/Silent-Hill-2-Enhancements#79]
Hi its me again and how the title says i have a question about the reshades:
How i can configure the reshades for OpenGL?
There is another alternative?
Thanks in advance ;)
![reshade issue](https://user-images.githubusercontent.com/42665650/51019799-f8a2ff00-1541-11e9-825c-61fa9a0a5f4f.png)
(Pic related in the red circles there are white lines)

**Comment by Polymega** [comment]
Hi @BinariGuy ,

> (Pic related in the red circles there are white lines)

ReShade won't fix this. You're running the game with low resolution textures. Go to the game's `Options > Advanced Options` and set `High Res. Textures = ON`. You'll need to reload the room you're currently in to see the changes to effect. 

> reshades for OpenGL

You should no longer be using the OpenGL version of ReShade. We have removed the requirement for WineD3D for Nvidia users which also means you no longer use ReShade OpenGL (you now use ReShade DirectX). Refer to this video: https://www.youtube.com/watch?v=cv2l_fNhnRA

(I forgot to mention one other file you need to delete in that video. You will also need to delete `opengl32.dll` file as well.)

> How i can configure the reshade

Refer to here: http://enhanced.townofsilenthill.com/SH2/#installReShade
Crtl + W opens ReShade's control panel.

**Comment by Chopser** [comment]
When you start Silent Hill 2: Enhanced Edition with ReShade game does not run, and gives here is a window:
![2019-01-15_194618](https://user-images.githubusercontent.com/43382291/51194472-2b5f4580-18fc-11e9-906e-21dd7918dcb2.png)

What to do with it? I did everything according to the instructions from here:

Silent Hill 2: Enhanced Edition - http://enhanced.townofsilenthill.com/SH2/#installReShade

**Comment by elishacloud** [comment]
Closing issue.  Solution has been posted.
