### ISSUE TITLE
Enemies glitch, "rubber banding".

### ISSUE THREAD

**Issue by metatronicsauce** [elishacloud/Silent-Hill-2-Enhancements#790]
So, I've experienced this only on the PC version, but have seen it both with and without your fixes, and on all hardware I've ever played the PC version on. Basically, the enemies (nurses most often) will "rubber band" very rapidly between two positions, in somewhat close proximity to the other. I thought it was intentional at first as it doesn't seem to affect my ability to hit them and it's kinda creepy, but I'm now realizing I've never seen it while emulating.

It seems to happen at random. On my crappy old PC it would happen more frequently and be more pronounced, but on my current hardware it happens much less frequently, and for a shorter amount of time.

It used to be much more pronounced when I was using weaker hardware, but even now on my proper gaming setup I still experience it, it's just much more brief.

So I ask, are you aware of this, is this normal, and is there anything that can be done if it's not normal.
Current specs:
12th Gen Intel(R) Core(TM) i5-12400F
RTX 3060

**Comment by Polymega** [comment]
Would you be able to submit a video clip of it in action?

**Comment by metatronicsauce** [comment]
> Would you be able to submit a video clip of it in action?

I will when I have some time

**Comment by metatronicsauce** [comment]
> > Would you be able to submit a video clip of it in action?
> 
> I will when I have some time

https://www.youtube.com/watch?v=YnGwuRrN1tg

Look very closely at 1:52. You can see it very briefly. You will see the nurse quickly jump to another spot close by, then back again. On weaker computers, I've seen it happen many times in rapid succession, as in, jumping around a lot within a second or two. Here, it only jumps to one place and back immediately. I've seen it jump back and forth many times rapidly. it's mostly nurses but I've also seen it happen with mannequins as well.

And like I said before, it's much more brief on better hardware. On weaker computers, it happens much more obviously.

**Comment by metatronicsauce** [comment]
> > > Would you be able to submit a video clip of it in action?
> > 
> > 
> > I will when I have some time
> 
> https://www.youtube.com/watch?v=YnGwuRrN1tg
> 
> Look very closely at 1:52. You can see it very briefly. You will see the nurse quickly jump to another spot close by, then back again. On weaker computers, I've seen it happen many times in rapid succession, as in, jumping around a lot within a second or two. Here, it only jumps to one place and back immediately. I've seen it jump back and forth many times rapidly. it's mostly nurses but I've also seen it happen with mannequins as well.
> 
> And like I said before, it's much more brief on better hardware. On weaker computers, it happens much more obviously.

It's seemingly impossible to reproduce from my end, I just replayed the area over and over again until I got it. On my weaker computers it happened much more frequently.

**Comment by Polymega** [comment]
Interesting. I can't recall ever seeing this even semi-frequently happening, even on my older computers back in the day. I wonder if it has something to do with collision, as the nurse was on the corner of a wall as she was turning around to you.

**Comment by Polymega** [comment]
It looks to be something with collision detection. Here is the same thing happening in the PS2 version:

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/5029a4e1-137c-4695-ad27-bf83e1b0a777

Maybe on older/weaker PCs the calculations needed to run the collision logic is a little slower resulting in this happening more often. Hard to say.

**Comment by metatronicsauce** [comment]
> It looks to be something with collision detection. Here is the same thing happening in the PS2 version:
> 001-1.mp4
> 
> Maybe on older/weaker PCs the calculations needed to run the collision logic is a little slower resulting in this happening more often. Hard to say.

 Interesting! Thanks for the reply. I remember having a real hard time avoiding hits or trying to hit enemies at it's worst, but for me as of now it's nothing but a slight visual issue. If you need anything more from me, let me know.
