### ISSUE TITLE
Download failed: The operation timed out

### ISSUE THREAD

**Issue by Carcharadroid** [elishacloud/Silent-Hill-2-Enhancements#791]
So, I've been trying my darndest to get this thing downloaded and working. After some searching to see if anyone was having similar issues (couldn't find anything exact but a few general issues downloading) I ended up going the route of using the installer to one-by-one install the various packs and files. All was going well until I got to the Image Enhancement Pack and the FMV Enhancement Pack. They'll make it anywhere from less than a quarter of the way downloaded to almost halfway before timing out and forcing me to start over.

Anyone else having this issue? My internet's fine, so I'm assuming it's some kind of server congestion maybe. Idk, I'm just wondering if I'm the only one struggling with this.

**Comment by matheusvb3** [comment]
Did you solve this? I can upload these packages if you want.

@Polymega It's none of my business, but I really think the developers could set up a ModDB page for this project and host the most up to date files there for people who are having issues... It's good to have server redundancy.

**Comment by Carcharadroid** [comment]
> Did you solve this? I can upload these packages if you want.
> 
> @Polymega It's none of my business, but I really think the developers could set up a ModDB page for this project and host the most up to date files there for people who are having issues... It's good to have server redundancy.

I haven't solved it, no u_u Still unfortunately unable to download those last two packs. If you can upload those packs that would be awesome, I really wanna check this thing out! I'm assuming the issues I'm having are just because of server congestion or something to that effect?

**Comment by Polymega** [comment]
Sorry for the delay. I downloaded both of these packages through the tool on two different days and they both went through without issue. I'm not sure what the issue might be. If you download the packages directly are you able to download them?

- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.5.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.4.zip

**Comment by Carcharadroid** [comment]
> Sorry for the delay. I downloaded both of these packages through the tool on two different days and they both went through without issue. I'm not sure what the issue might be. If you download the packages directly are you able to download them?
> 
>     * https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.5.zip
> 
>     * https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.4.zip

Hey, no biggie, we're all busy!

Anyway I was able to download both of these zip files. It did fail a few times but I was able to just tell it to try again and gradually complete the download, vs the installer which forces me to restart completely every time it messes up. So it looks like downloading them this way does work, yes! No idea why my computer wants so badly to reject em but oh well.

Would I be able to pester you or anyone to possibly direct me towards directly downloading the Image Enhancement Pack? It was that one and the FMV one I needed and thanks to you I have the FMV one now. :)

**Comment by matheusvb3** [comment]
Here you go: [download link](https://drive.google.com/file/d/1cZXnJIOMfZMITqNt31CaMoFbGhLQP2ZW/view?usp=drive_link)

Just decompress and drop the sh2e folder into the Silent Hill 2 folder. It should ask if you want to merge the two "sh2e" folders, say yes.

**Comment by Polymega** [comment]
> Would I be able to pester you or anyone to possibly direct me towards directly downloading the Image Enhancement Pack?

Oh, yes, sorry I got confused and linked another package. 

https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.2.zip

> Anyway I was able to download both of these zip files. It did fail a few times but I was able to just tell it to try again and gradually complete the download, vs the installer which forces me to restart completely every time it messes up

This tells me it's not necessarily an issue with the installer. I've downloaded the larger project packages a few times upon your ticket creation and it always downloaded for me without issue. I have a few questions, if you don't mind answering:

- What country are you located in?
- What is the download speed your ISP advertises for your internet package?

**Comment by Carcharadroid** [comment]
> This tells me it's not necessarily an issue with the installer. I've downloaded the larger project packages a few times upon your ticket creation and it always downloaded for me without issue. I have a few questions, if you don't mind answering:
> 
>     * What country are you located in?
> 
>     * What is the download speed your ISP advertises for your internet package?

Hey, sorry for the lateness of this reply. Also thank you for the file, very excited to check it all out!

Anyway to answer your questions: I'm in the USA, and my current provider (Spectrum) says up to 500 mbps. Though my husband and I have been discussing switching to something cheaper/faster, but that's what we have for the moment.
