### ISSUE TITLE
update the credits.bik file

### ISSUE THREAD

**Issue by justtoask** [elishacloud/Silent-Hill-2-Enhancements#794]
I noticed that the SH2 PC credits file from the movies menu isn't the ending one, and that it also isn't updated like the ending movies. Can you fix it?

**Comment by Polymega** [comment]
Can you open your `d3d8.log` file and tell me what version of the project you're running? It should be at the top and look something like this:

```
12752 15:35:52.388 Starting Silent Hill 2 Enhancements! v2.1.2103.0
```

Can you also take a screenshot of the files in your `sh2e\movies\` folder?

**Comment by justtoask** [comment]
The version is v2.1.2070.0.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/72657053/c0acf9d7-8e3a-4b8c-9a8f-e953806df74a)
here's the movie folder from sh2e
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/72657053/be8d3c35-8aac-4283-860e-4ada0e3877cc)
here's the one from the data folder for comparison

**Comment by Polymega** [comment]
Upgrade the SH2 Enhancements module package and that should fix the issue.

**Comment by justtoask** [comment]
The setup doesn't detect any update through.

**Comment by Polymega** [comment]
I had a brainfart and forgot I'm using a test build of a higher number. So the issue you're saying is the game is using the old/original credits video that shipped with the vanilla game?

Launch the Config Tool from the game's directory and select **Install or Repair Packages**

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/fde8417b-9ac7-4ae9-8d4a-2459549c3ce0)

Next, select the **Credits** package then proceed to download it

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/0afff921-5278-4dd1-95e1-4ad333a8551f)

See if that addresses the issue.

**Comment by justtoask** [comment]
Yeah, it's there now. Thank you.
