### ISSUE TITLE
missing binkw32.dll files and msvcr70.dll do u know how to fix?

### ISSUE THREAD

**Issue by ravenraveraven** [elishacloud/Silent-Hill-2-Enhancements#795]
missing binkw32.dll files and msvcr70.dll do u know how to fix?

**Comment by Polymega** [comment]
Please see this ticket for a possible solution: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/675

**Comment by ravenraveraven** [comment]
it still says the MSVR70. thing

**Comment by Polymega** [comment]
Please take a screenshot of your game's directory.

**Comment by ravenraveraven** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/135710994/8ed49d65-0c31-4b8f-81c9-caf97f6aee08)

**Comment by Polymega** [comment]
Move all of those files/folders _back_ one folder.

In other words, move everything found in `C:\Program Files (x86)\Konami\Silent Hill 2\Silent Hill 2\` to `C:\Program Files (x86)\Konami\Silent Hill 2\`

Additionally, we don't recommend running the game from an admin-protected directory such as `Program Files (x86)`. I'd suggest moving your `Silent Hill 2` folder to a local user directory, such as `My Documents` or `My Games`.

**Comment by ravenraveraven** [comment]
it still doesn't work its like blank a black thing for less an a second

**Comment by Polymega** [comment]
Please attach a copy of your `d3d8.log` file from the game's main directory.

**Comment by bonk0022** [comment]
it is missing  binkw32.dll files and msvcr70.dll how can i fix this

**Comment by Polymega** [comment]
Refer to this ticket for a possible solution: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/675
