### ISSUE TITLE
installer fails to download

### ISSUE THREAD

**Issue by borklaser69** [elishacloud/Silent-Hill-2-Enhancements#796]
when i start the installer it just shows this error 

> Error: Download Failed Couldn't download 'webcsv.url'. The installation cannot continue. Retry Download?

every time.  i've been trying to download it for a week with no success.

**Comment by Polymega** [comment]
Sorry you're having issues. Can you right click `SH2EEsetup.exe`, go to **Properties > Details** and tell me what the **Product Version** number is?

Also, please double check that your antivirus software or firewall isn't preventing a connection through the installer to our project's server.

**Comment by borklaser69** [comment]
![sh](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/136278179/414c1673-cd9b-4d85-8135-4594ad100a97)

no antivirus and i've turned of the firewall and tried to run it still the same problem so i don't think it's the firewall.

**Comment by Polymega** [comment]
Are you still experiencing this issue?

Closing ticket. Feel free to re-open if you'd like further assistance.
