### ISSUE TITLE
The game does not start with ReShade

### ISSUE THREAD

**Issue by Chopser** [elishacloud/Silent-Hill-2-Enhancements#80]
When you start Silent Hill 2: Enhanced Edition with ReShade game does not run, and gives here is a window:
![2019-01-15_194618](https://user-images.githubusercontent.com/43382291/51194472-2b5f4580-18fc-11e9-906e-21dd7918dcb2.png)

What to do with it? I did everything according to the instructions from here:

Silent Hill 2: Enhanced Edition - http://enhanced.townofsilenthill.com/SH2/#installReShade

**Comment by Polymega** [comment]
@elishacloud are there any specific runtime libraries that need to be installed for d3d8to9? I wouldn't think so, [especially because of this post](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/53#issue-371794152), but I wasn't sure.

**Comment by Polymega** [comment]
@Chopser if you install the game instead to your C:\ drive does it work then?

**Comment by Chopser** [comment]
I always install games on a non-system drive - D:\Games\Game_Name. Never put the game in C:\Program Files. To the same I have included built-in Administrator. Under him and sit.

**Comment by Chopser** [comment]
I tried to install on C: \ and on D: \ the same result - an error.

**Comment by Chopser** [comment]
**@Polymega** 
I downloaded the new package Reshade 4.1.0 from this comment [https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/88#issuecomment-456635410](url) Everything is working! Only does not work off input. When you open the ReShade menu, the character starts walking. And so it works, thank you very much!

**Comment by Polymega** [comment]
Really?! It was ReShade the whole time? Never would have guessed that! Well, I'm very happy it's working for you now! 

To open ReShade you press Ctrl + W and it sounds like you may have remapped the movement keys for James to be WASD. So when you press Ctrl + W it will also make James move. 

While you're in the ReShade control panel you can change that key bind (Ctrl + W) to something different.

**Comment by Polymega** [comment]
> When you open the ReShade menu, the character starts walking. And so it works, thank you very much!

The shortcut keys to open ReShade are Ctrl + W. If you rebind the game's inputs to make James move with WASD then when you press Crtl + W it will also make James walk forward (since you're pressing W). 

You can open the ReShade control panel and change the shortcut key presses to something else that isn't also being used by the game. That way, the key press won't be "stuck" in-game when you open the ReShade control panel.

**Comment by elishacloud** [comment]
Closing issue.
