### ISSUE TITLE
Flashlight Sound

### ISSUE THREAD

**Issue by SalesMoura** [elishacloud/Silent-Hill-2-Enhancements#804]
Hello, congratulations to everyone and thank you for the wonderful translation into Brazilian Portuguese, it is indeed the definitive one for the game in Brazil. Anyway, it's not necessarily a bug that I come to report, but a suggestion that I've heard a lot of people say would be good. The sound in the flashlight, which the SH2 does not have, which causes strangeness in a bad way. I think it would be very cool if it were possible to add the sound, when turning it on and off, it could even be used with the sound of the SH3, which has the sound of the flashlight, the PS2 version of course. It's a detail, but it would be nice. Thanks.

**Comment by Polymega** [comment]
Hi there,

That's a cool suggestion! Unfortunately, I'm not sure if it would be possible to add, since the file that house all of the game's sound effects has a hard, set number and because there's no code in the game to play a sound on flashlight change to begin with.
