### ISSUE TITLE
Arabic translation file

### ISSUE THREAD

**Issue by lgxs7** [elishacloud/Silent-Hill-2-Enhancements#805]
Is there an Arabic language in Silent Hill 2? To download with other languages? If not, why hasn't it been added yet? I know that there are several people who created a complete translation file for the Arabic language, but it was not added with other languages, and I do not know the reason. The account of the team that created the translation file is ((@EternalDreamAR)) on the Twitter platform. I hope to communicate with them so that the Arabic translation is added On your site with other languages, thank you

**Comment by Polymega** [comment]
We have been in discussion with someone who is making an Arabic translation pack for the project. You can view the ticket here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/630

There are special requirements needed for a translation pack to be accepted/hosted on our site, and Adam-Saeed has been working with us to ensure compliancy. Also, he has made an HD font sheet for the Arabic language. 

Unfortunately, he seems to have dropped the translation project as we haven't heard from him in quite some time.

**Comment by scigward** [comment]
There is actually an Arabic translation file that @AdamSaeed did but you may see that some of the letters at the end of the game are missing, I finished the game with the Arabic translation, Its not bad at all some of the letters are missing but yet you still can understand, Its the best that we have currently.
