### ISSUE TITLE
Hospital bug music piano

### ISSUE THREAD

**Issue by IvNergal** [elishacloud/Silent-Hill-2-Enhancements#806]
Hello, I don't know if this bug is present in other versions of the game...

After Maria is killed by Pyramid Head in the hallway. James goes down in the elevator, where in the Hospital Hall beautiful music is playing, a melody on the piano, right?

So if you go out of the hospital into the dark streets, go back into the hospital, and come out again, the music plays forever along the entire length of the dark streets...

**Comment by Polymega** [comment]
Hi there,

We are aware of this quirk but consider it a non-issue to fix. The reason being is that you have to time going in/out of the hospital at a very specific time to make it happen. For practically all casual players, this issue will never present itself. And for those who know how to do it, they quite enjoy it as they have the beautiful piano music play as they traverse the dark streets of Silent Hill at night.
