### ISSUE TITLE
Files are missing re-install Silent Hill 2

### ISSUE THREAD

**Issue by S1MD** [elishacloud/Silent-Hill-2-Enhancements#809]
hello, my problem is that when I start the game, the screen goes black and after half a minute it displays the text below Files are missing re-install Silent Hill 2. I reinstall 3 times and doesn't work. Can anyone help ?

**Comment by S1MD** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11936442/d3d8.log)

here is the d3d8

**Comment by Polymega** [comment]
Hi there,

It looks like you installed our project but not the actual game (Silent Hill 2 PC). You must install Silent Hill 2 PC in order for our project to sit on top of the game and work.

Follow these steps:

1. Go to your Silent Hill 2 game folder and make a backup of the `sh2pc.exe` file (make a copy somewhere else on your computer).
2. Download the game from this site: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download
   - Download the "Fully extracted version"
3. Unzip the download and place all of its contents within your Silent Hill 2 game folder.
   - Say "yes" if it asks you to overwrite the other file that's already there.
5. Find the `sh2pc.exe` backup you made and place it back into your Silent Hill 2 game folder.
   - Say "yes" if it asks you to overwrite the other file that's already there.
