### ISSUE TITLE
Some Sounds Not Fading Out Properly (Indirect Sound)?

### ISSUE THREAD

**Issue by KojiKenshiro** [elishacloud/Silent-Hill-2-Enhancements#81]
I'm not sure if this particular problem is due to how the PC port handles sound files or if it's a minor problem with the Enhanced Audio Pack?  The problem I'm experiencing is that when Loading A Save while in-game causes two Audio Clicks to happen and also when there are multiple enemies moving around James their footsteps keep getting cut-off and don't sound very good!  Everything else so far sounds good and other than these two minor issues the game has played beautifully!  I have set the EarlyStopFadeOutTime in DSound.ini to 0.002 as recommended in the Installation Guide!  I'd like to thank the devs of the SH2 PC Hacks/Fixes for their time spent on making this version one of the best ways to play this great game!  Cheers!  :)

**Comment by Polymega** [comment]
The "game start" sound isn't technically a SFX file but instead a dialogue file (for whatever odd reason). IndirectSound's fade out fix only works for SFX files. The good news is you'd only hear that particular click when loading a game while NOT in the main menu do that should be few and far between. 

As for the footsteps: Yes, I've experienced this myself. My guess is the PC version handles multiple sounds overlapping each other and coming from different directions not all that well. I don't know if anything can be done for that.

**Comment by KojiKenshiro** [comment]
Ah I see!  I agree that it's a minor problem at best but would be cool if it could be dealt with one day!  Thanks again for all the work that you and the other devs have done to make this a good way to play this great game!  I guess this topic can either be closed or kept open for possibly addressing the "Game Start" sound in the future!  Cheers!  :)

**Comment by Polymega** [comment]
Thanks for the kind words! We're happy you've been enjoying this classic on a modern display/system. :)

**Comment by KojiKenshiro** [comment]
I'd also be open to helping you guys play-test the various Fixes/Updates if you guys want another person to help out with testing?

**Comment by Polymega** [comment]
Sure! The next major play test we have I can ping you. Thanks!

**Comment by Polymega** [comment]
Someone posted this on another thread then deleted it but, this mod brings back surround sound (at least through headphones) and it sounds really amazing: https://www.youtube.com/watch?v=36l1nTb9dNY

There is a noticeable difference/improvement in spatial sound vs. IndirectSound.

It doesn't fix the issues you mentioned such as the Lying Figure's footsteps cancelling each-other's out but it's a marked audio spatial improvement. 

But there's one big caveat with this mod: It doesn't support the "pop" and "click" removal fix as IndirectSound does. For that reason alone, IndirectSound is still the best solution to restore audio for the game.

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
