### ISSUE TITLE
Game freezes for 2-4 seconds when exploring new area

### ISSUE THREAD

**Issue by DeemSleep** [elishacloud/Silent-Hill-2-Enhancements#811]
I’m playing the Enhanced Edition and the game randomly freezes for 2-4 seconds when going into a new area. This is only when entering a new part of town I haven’t been in yet. It starts freezing every few seconds as if it’s loading. When I go back through that same area of town I’m never hitches again. Only the first time I enter it.

**Comment by Polymega** [comment]
Please upload a copy of your `d3d8.log` file.

**Comment by DeemSleep** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11995248/d3d8.log)

**Comment by Polymega** [comment]
It's hard to say what's causing this to happen, but from looking at your log file, I'd try experimenting with any of the following:

- Your BitDefender security software is hooked into the game while it's running. It might be doing a file check every time the game requests new files to load in (such as loading in new environment files). Try telling BitDefender _to not_ hook/run into SH2 PC. This is likely the cause why.
- The game is running using an integrated graphics processor (IGP). We don't recommend IGPs for use with our project; we recommend dedicated graphics cards. You can try playing the game at a lower resolution to see if that helps any.

**Comment by DeemSleep** [comment]
I turned BitDefender completely off while playing the game and this solved the problem thanks! Good Catch!

**Comment by DeemSleep** [comment]
I turned BitDefender completely off while playing the game and this solved the problem thanks! Good Catch!
