### ISSUE TITLE
set up tool files issue

### ISSUE THREAD

**Issue by Moatthekk** [elishacloud/Silent-Hill-2-Enhancements#813]
[
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/139095407/199370c4-df16-4749-88c4-9783f70d0134)](url) why do not the other folders appear in the set up tool and just windows(C") and data (d") appear

**Comment by Polymega** [comment]
I'll close this ticket out. Please continue your discussion on your original ticket: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/812

**Comment by Polymega** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/74b43027-b7ed-4ebc-8e07-737972279116)

You need to click the little arrows (circled red) to see the other files/folders in these drives. For further questions though, please continue discussion in the other ticket.

Thanks
