### ISSUE TITLE
How to erase the cord from the refrigerator?

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#82]
Hi!

I tried recently the new changes of the Enhanced Essential Files. I love almost everything you've done, except the cord from the refrigerator in the Brookhaven hospital. That cord doesn't appear in the original PS2 version as far as I know, and I think it not make sense try to add logical elements to the Silent Hill world.

Is there any way to delete the file of the cord to erase it in-game?

**Comment by Polymega** [comment]
Remove `hp190.map` from within the `\sh2e\bg\hp\` folder.

**Comment by Storm3000** [comment]
@Polymega Thank you. :)

**Comment by EhvinnTee** [comment]
So, just how many of these brand new and unnecessary changes have you made to the game? At what point in the development process did it change from solely preservation to 'hey, we can make our own additions or changes here and there'?
You changed the 'Blookhaven' sign too, I imagine?

**Comment by Polymega** [comment]
It was never solely about preservation.

You're welcome to not use the project.

**Comment by umbrellacorp53** [comment]
@EhvinnTee 
> So, just how many of these brand new and unnecessary changes have you made to the game? At what point in the development process did it change from solely preservation to 'hey, we can make our own additions or changes here and there'?
> You changed the 'Blookhaven' sign too, I imagine?

Do you know this comment sounded extremely rude? The SH2:EE team have poured their hearts and souls into this project for years with little fanfare or thanks.  

To answer your question, there is a thorough changelog both in video form on YouTube and listed on the main project page that has every change listed. From what I've seen the only changes outside of restoration, bug fixes, and quality improvements for modern hardware are: (1) Language fixes that were not caught by the original localization team, and (2) the addition of the refrigerator cord. I encourage you to look at the changelog yourself though. There is also the option to pick and choose fixes and enhancements that you would like to use, and if you run into any issues there is a knowledgeable and resourceful community here to help.

**Comment by Polymega** [comment]
Thank you, umbrellacorp53. His message was demeaning and confrontational, so I responded appropriately.

They want to pick a fight. I have no time for this.

**Comment by EhvinnTee** [comment]
Well, Umbrella, let me first apologize, to _you_, for coming off rude. I was.
But I respectfully and strongly disagree that they get little to no fanfare. We've all proudly praised the wonderful work that team has been doing for ages! And it _IS_ excellent work! Newcomers to Silent Hill 2 are being constantly pointed to the EE by the community! Even _I_ have walked a friend through the installation process! 
"It's the definitive Silent Hill 2 experience!" I myself among many others in the SH community have proclaimed.
But I can't anymore, cause it's not Silent Hill 2. It's _they're_ Silent Hill 2. "We've truly enhanced it! It's better now!" And I get it. "Oh, most of it's language fixes. Oversights from the localization team." That's how it always starts. But now you're putting little touches cause it makes more sense in _your_ eyes. You know better. Ooh, how about _this_? I like that more. It's enhanced! Arrogance.
Hope everyone knows how to pour through a changelog!!

**Comment by Storm3000** [comment]
@EhvinnTee  I think you're overreacting. This began only to fix the PC version of Silent Hill 2 that was really a mess, now it's something else:  an enhanced edition made by fans, for fans. There's a lot effort behind these mods. I'm following this project since the beginning, and believe me, they didn't change the original game so much as you think. The only differences are this added cord, the urinals in the bathroom at the beginning, the main screen title and the subtitles. I didn't like those new details, so I opted to preserve the original details by asking kindly how to change it. The other changes are some fixed textures and camera angles that looked wrong or bugged in the original game. Believe me, this is the most faithful version of Silent Hill 2. There's no reason to no use this fantastic edition, you can change manually those details as I did if you don't like it.

**Comment by elishacloud** [comment]
Hello @EhvinnTee, thank you for your interest in this project and your feedback.  All of us on this team are working hard to try and produce an update to Silent Hill 2 that is good for everyone, though we don't always meet that goal.  I just added a [comment in another thread](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/258#issuecomment-607328044), but I think this comment may be relevant to this discussion as well:

> This project is open source and, as such, pretty much any part of this project can be disabled.  There are three main ways to disable things in this project:
>
> 1. The first way is by modifying settings in the `d3d8.ini` file.
>
> There are many settings in the ini file which allows you to disable pretty much any code change we made to the game.  These options are pretty granular and allow for isolated changes to disable items you don't want.  See the [Configuration Details](http://www.enhanced.townofsilenthill.com/SH2/config.htm) page for a list of the options.
>
> 2. The second way is by removing items out of the `sh2e` folder.
>
> One of the core mandates of this project is to not overwrite any file in the Silent Hill 2 folder.  All of the replaced data files are stored in a separate folder called `sh2e`.  By simply deleting files in this folder you can undo many of the changes.  For example, by removing all the `.msg` files you can undo most of the dialog/text changes in the game, by removing the `Silent Hill 2\sh2e\pic\etc\MousePointer.png` file you can undo the mouse cursor change, etc.
>
> 3. The third way is by modifying the code.
>
> In some cases more than one change is packaged together.  For example all the sound effects are stored in a single file called `sddata.bin`.  If you want to make a change to only one of sound effect files you will need to repack the `sddata.bin` file.  In these cases, since this is a 100% open source project, [we give you the tools](https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/5dc7ac3604fd2c86ca3eb101b5d32f4cb6855879/AudioScripts/SFX) as part of this project to make those changes yourself.  But in most cases you won't need to since (1) or (2) above will allow you to undo 90% of the items you would want to undo.

**Comment by AeroWidescreen** [comment]
@EhvinnTee The problem with a project like this is that it's impossible to satisfy everyone. We fix things, then people complain because it's not like the original. We leave things alone, then people complain that it hasn't been fixed. People hated pillarboxing in the FMVs, so we got rid of it. Now people hate the fullscreen FMVs, so we re-rendered the videos and re-wrote the code just to give people more options. There comes a time where we have to put our feet down and say "no".

Unless you have a solid argument for why any of the changes we've made shouldn't be done, then I personally don't care what you or anyone else thinks because we'd be running in circles if we listened to everyone. Remove / disable a feature if you don't like it, or just play the PS2 version if you're that much of a purist.

**Comment by SilentHeII** [comment]
@AeroWidescreen @elishacloud @Polymega The problem with the argument about "disabling/removing" stuff we don't like is that there is no detailed changelog of certain files, mainly the .map files. I think there are a lot of good things done here, ESPECIALLY changes to match the PS2 version.

So I guess my question is, is there a program I can use to view the map files to determine which rooms they are/what changes have been made? Hell, I'd even document these changes myself and offer them to you if it gave people like @EhvinnTee and @Storm3000 options, because I, too, value some authenticity to the games preservation.
