### ISSUE TITLE
corrupted files when installing silent hill 2  enhanced edition

### ISSUE THREAD

**Issue by princessluna123** [elishacloud/Silent-Hill-2-Enhancements#820]
when I try to install the enhanced edition, I get two errors that show that the audio enhancement pack and the fmv enhancment pack are corrupted. 
![Screenshot_30](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/111598731/0c746555-d133-4790-9449-a570b7f597c5)
![Screenshot_26](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/111598731/ec89175a-a85b-4e17-9f01-e39d53c9ba54)

**Comment by Olavia09** [comment]
same problem, but only the audio one :(

**Comment by Polymega** [comment]
This should now be resolved. Thanks
