### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nassasa** [elishacloud/Silent-Hill-2-Enhancements#823]
Hello

I'm trying to run SH2EE but after install i'm having

the procedure entry point bink set soundtrack@8 could not be located in the dynamic library
And the game never start , crashed, and i have  a binkw32.dll

**Comment by Polymega** [comment]
Please share a screenshot of the files in the game's main folder.

**Comment by elishacloud** [comment]
It sounds like you have the wrong version of binkw32.dll.  The binkw32.dll is tied to the game.  You can't just replace it for another one.  Not all of them will work.

Here is the one you should have:  [binkw32.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12176358/binkw32.zip)
