### ISSUE TITLE
Black Screen on Startup

### ISSUE THREAD

**Issue by Generic304** [elishacloud/Silent-Hill-2-Enhancements#825]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12236357/d3d8.log)
Here's my log file (I think that's what I'm supposed to post). Anyways, as the title or whatever says, I get a black screen whenever I start up the game. It has happened when I've used the director's cut or the normal PC version, it has happened whether it was on my C: drive (my main) or my D: drive, and it has happened whether I used a preinstalled version of the game or with me installing it myself. No matter what I do, I still have this black screen issue. I've looked everywhere and seen posts about this, but the fixes they recommend or talked about in their posts haven't worked for me. Please, if you can think of any fix, let me know.

**Comment by Generic304** [comment]
> Sorry you're having issues. Quickly looking over your log file, all files and settings seem to be in place. One thing that caught my attention is the use of Intel HD Graphics for the graphics processing. We don't recommend integrated graphics processors (IGPs) as they can have issues running/display the game correctly--in particular very old or weak IGPs.
> 
> One thing you could try is opening the Configuration Tool (`SH2EEconfig.exe`) and disabling **Run the game in DirectX 9** (found on the first page) to see if it'll run for you then.

I just tried your fix, but I still got the black screen. I also tried using doing with integrated graphics on and high-performance Nvidia processor on, but both didn't seem to work. My computer should be more than able to handle this game. Thank you for the suggestion. Can you think of anything else I could try?

**Comment by Polymega** [comment]
Find these files in the game's main folder and _temporarily_ move them somewhere else (as in, remove them temporarily from this folder):

```
alsoft.ini
dinput8.dll
dsoal-aldrv.dll
dsound.dll
Xidi.ini
```

This will remove the Xidi and DSOAL packages for testing purposes. If the issue persists, you can place these files back in the game's directory.

If that doesn't work, open the Configuration Tool, go to the **Advanced** tab, and uncheck **Use custom "sh2e" folder**. See if that works. This will keep the "brains" of our project enabled, but will only use vanilla game assets/files.

**Comment by Generic304** [comment]
Doing your fix where I removed that stuff worked. What does this mean for my game and how will it differ from the normal enhanced project?

**Comment by Polymega** [comment]
**DSOAL** consists of `alsoft.ini`, `dsound.dll`, and `dsoal-aldrv.dll`
**Xidi** consists of `dinput8.dll` and `Xidi.ini`

DSOAL brings 3D spatial audio to the game, making its audio presentation particularly impactful when playing with headphones. Xidi brings support to modern controllers.

What you can do next is restore the files for DSOAL first to see if the game still runs. If not, then you know DSOAL is causing the issue. If so, then you know Xidi is causing the issue.

If we can determine which particular package is the culprit, we could hopefully guide you to install any runtime dependencies the piece of software needs.

**Comment by Generic304** [comment]
I just tried it, and DSOAL is the culprit.

**Comment by Polymega** [comment]
Please download the Microsoft Visual C++ 2015 Redistributable Update 3 and see if that resolves the issue when using DSOAL with the game:

https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by Generic304** [comment]
Should I uninstall the newer version of this?

**Comment by Polymega** [comment]
Newer versions of VS C++ Redistributables? No, you should keep those as other software may require that particular version of the redist to function.

**Comment by Generic304** [comment]
I guess it wouldn't matter cuz it didn't work anyway.

**Comment by Polymega** [comment]
The only other thing I can think to check would be this: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

> Windows may automatically change your audio output source to your controller's built-in speaker (such as for the DualShock 4 or DualSense controller) upon connecting your controller to your PC. If this happens, the game may freeze/crash on launch. Ensure Windows is set to use the correct audio output source. This must be done prior to launching Silent Hill 2 PC.

Beyond that, I'm unfortunately unsure what else to do. You may need to forgo using DSOAL.

**Comment by Generic304** [comment]
What's the downside to not having it? Just worse audio?

**Comment by Generic304** [comment]
I haven't connected a controller or anything (I plan on using keyboard + mouse). So I don't know what it is.

**Comment by Polymega** [comment]
Audio quality is the same. DSOAL just changes it's sound presentation to binaural audio; aka it gives the illusion of 3D audio through a stereo setup. It's not critical to have, especially if you aren't planning to use a headset.

**Comment by Generic304** [comment]
By the way it says something about audio in here now: 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12246015/d3d8.log)

**Comment by Generic304** [comment]
I do plan to use a headset, but it's not the end of the world if I don't have like "3D" audio or whatever. Thanks for helping me out, I was worried this just wouldn't work on my computer.

**Comment by Polymega** [comment]
> By the way it says something about audio in here now: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12246015/d3d8.log)

```
2772 21:35:49.240 Redirecting 'DirectSoundCreate8' ...
2772 21:35:59.527 'DirectSoundCreate8' Failed! Error: DSERR_NODRIVER
```

Maybe our lead developer Elisha has some thoughts on this error he can share at a later time. But in the meantime, DSOAL isn't critical to have in order to play.

**Comment by Generic304** [comment]
Sweet! Thanks for the help.
