### ISSUE TITLE
Flashlight Visual Glitch 

### ISSUE THREAD

**Issue by GamingBlanket** [elishacloud/Silent-Hill-2-Enhancements#826]
I have an ongoing issue when turning my flashlight on in the apartment section of the game. I tried to look for ways to resolve this issue but the latter were, at last, inconclusive. 
![43549579-4459bad2-95e1-11e8-80cf-4f73d7435c0f](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/141350933/4cac7cd6-1efa-4116-bd5f-ba0603b725b3)

**Comment by Polymega** [comment]
This is a very rare bug that affects a few GPUs. Disable d3d8to9 to remedy this. Open the Configuration Tool (`SH2EEconfig.exe`) and, on the first page, uncheck **Run the game in DirectX 9**.

**Comment by GamingBlanket** [comment]
May both sides of your pillow always be cold.
