### ISSUE TITLE
sh2pc.exe system error

### ISSUE THREAD

**Issue by aimyeee** [elishacloud/Silent-Hill-2-Enhancements#827]
Hello, so I wanted to download the enchanced edition of Silent Hill 2 on pc and I followed the instruction step by step but when I launch sh2pc.exe click on "save and lauch the game" I have an error message...

[Capture d'écran 2023-08-05 215415](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/141522677/3ca51a13-26e8-45e9-bbc1-0639d52a8f0c)

It's in french but that mean "Could not execute code because MSVCR70.dll was not found. Reinstalling the program may correct this problem"
When I close this I have an other message like this :
"Could not execute code because binkw32.dll was not found. Reinstalling the program may correct this problem"
And another :
"Could not execute code because MSVCP70.dll was not found. Reinstalling the program may correct this problem"

Do someone have a solution?

**Comment by Polymega** [comment]
Hi there,

Can you please share a screenshot of all the files/folders found within your Silent Hill 2 folder?

**Comment by aimyeee** [comment]
I solved the problems but now when I launch sh2pc.exe I have a japanese message that pop up...
![Capture d'écran 2023-08-06 160349](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/141522677/0f8cb462-e4c3-4fce-a6c8-86d6a0ba5eb5)

**Comment by Polymega** [comment]
Try this: Open `SH2EEsetup.exe` and select **Install or Repair packages**. Then, select **Enhanced Executable**. Update this package and see if that resolves your issue.

**Comment by Polymega** [comment]
Closing ticket. Feel free to re-open if you'd like further assistance.
