### ISSUE TITLE
Added additional language .mes files for Enhanced Edition Essential Files

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#83]
(I'll close this ticket in a few days. Just posting here for posterity.)

_I've simply stealth-added these files into v1.0.3 of the Enhanced Edition Essential Files as no one has come to me about this problem before._

**ISSUE:** If you installed the North American version of the game but then decide to use the Director's Cut (European) executable certain lines/segments in any other language besides English either won't display or appear corrupt. 

**CAUSE:** While the North American version installs the .mes files for subtitles in other languages, it does not contain any translated data for "common" .mes files for things such as the Options text and Save/Load file text. While I've previously added the correct multi language .mes files for things like the Options menu text (taken from a Director's Cut install), I forgot to do so for the Save/Load file text. So custom save spots would simply appear as "X" or "?":

![sh2pc 2019-01-16 23-27-14](https://user-images.githubusercontent.com/27395260/51295730-f7148380-19e6-11e9-8cf9-8ff1062cb732.png)

**SOLUTION:** I've now included the `m_card_msg_*.mes` and `m_card_x_msg_*.mes` files from the Director's Cut installation within `\sh2e\etc\message\`

![sh2pc 2019-01-16 23-26-43](https://user-images.githubusercontent.com/27395260/51295737-01cf1880-19e7-11e9-875a-776b66038cf6.png)

This is now included as part of v1.0.3 of the Enhanced Edition Essential Files.

**Comment by Storm3000** [comment]
@Polymega That's great. Thank you so much. I've been playing a while in spanish with the english .exe (I'm checking if the game freezes again or not) and works fine till now, however the pause menu in-game looks wrong. For example, now appears "Load game sp" instead of "Cargar partida". Is there any way to fix this?

**Comment by Polymega** [comment]
> however the pause menu in-game looks wrong. For example, now appears "Load game sp" instead of "Cargar partida". Is there any way to fix this?

I don't believe so. That particular text (the in-game PC pause menu text) is hard-coded into each executable, so it doesn't use any type of external .mes files to retrieve the verbiage here. 

If you use the Director's Cut (European) executable, all non-English languages work for this pause menu.

**Comment by Polymega** [comment]
Here is the North America .exe: 

![image](https://user-images.githubusercontent.com/27395260/52592789-4ea2e500-2e15-11e9-97fa-6eb13c1c4e48.png)

And the European .exe: 

![image](https://user-images.githubusercontent.com/27395260/52592818-624e4b80-2e15-11e9-9b7e-2f1797fa2bb1.png)

I wouldn't dare try and change any of this myself as I'm not from a modding/programming background.
