### ISSUE TITLE
Open up config file manually (steam deck)

### ISSUE THREAD

**Issue by thestuartcarson** [elishacloud/Silent-Hill-2-Enhancements#831]
Hey everyone, sorry I hope this question is okay.

I’ve had Enhanced Edition work beautifully on my steam deck. Today there was an update and after pressing yes it opened up the config file and updated it. However I saw on twitter there is a way on the config file to add a CRT filter. But I can’t open the config file on steam decks desktop mode. I tried using Bottles to open it up but nothing happened. I don’t really want to wait until the next update for it to open up the config file. Especially if I want to disable the CRT filter.

I added/installed Enhanced edition to my steam library.

Any tips?

**Comment by Polymega** [comment]
Hi there,

The Config Tool is found in the game's folder as `SH2EEconfig.exe`. I don't believe anyone on the team owns a Deck, so I'm unsure how to assist you. I do recommend asking in our dedicated Steam Deck thread, as other Deck users have been assisting each other there: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/505

**Comment by thestuartcarson** [comment]
> Hi there,
> 
> The Config Tool is found in the game's folder as `SH2EEconfig.exe`. I don't believe anyone on the team owns a Deck, so I'm unsure how to assist you. I do recommend asking in our dedicated Steam Deck thread, as other Deck users have been assisting each other there: #505

Oh okay, thanks very much!
