### ISSUE TITLE
SH2EE does not boot on Steam Deck

### ISSUE THREAD

**Issue by cheggins** [elishacloud/Silent-Hill-2-Enhancements#833]
After installing SH2EE through Steam, once I try booting the game, it either doesn't open or opens to a black screen and immediately closes. I have also tried installing the game through Lutris with no luck. I really want to play this but it just is not working on Steam Deck when I KNOW it does work. I'm at a loss and have tried everything I can think of. It is currently my 3rd or 4th day of several-hour sessions of trying to get this game to work. Any help is much appreciated. Any suggestions that allow me to boot the game from Game Mode are also appreciated.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12444589/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

The Config Tool is found in the game's folder as SH2EEconfig.exe. I don't believe anyone on the team owns a Deck, so I'm unsure how to assist you. I do recommend asking in our dedicated Steam Deck thread, as other Deck users have been assisting each other there: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/505
