### ISSUE TITLE
Please Insert Silent Hill 2, CD1

### ISSUE THREAD

**Issue by Thomas20232030** [elishacloud/Silent-Hill-2-Enhancements#837]
Since I installed the last updates via the installer I got the message above "Please Insert Silent Hill 2, CD 1" when starting an new game or when I load a saved file. What can I do? A new install? Ifo so, can I save my saved games? 

Thank you very much for hte great experience with Silent Hill 2 Enhanced!!!!

Thomas

**Comment by Polymega** [comment]
Hi there,
Can you please update a copy of your `d3d8.log` file found in your game's main folder?

**Comment by Thomas20232030** [comment]
15600 12:35:32.483 Starting Silent Hill 2 Enhancements! v2.1.2070.0
15600 12:35:32.483 Game binary version: v1.0
15600 12:35:32.483 Disabling High DPI Scaling...
15600 12:35:32.483 Setting GUI theme...
15600 12:35:32.498 Setting theme properties...
15600 12:35:32.498 Hooking the CreateProcess APIs...
15600 12:35:32.498 Setting delayed startup...
15600 12:35:32.498 LENOVO 2325OG0 ThinkPad X230 (Notebook)
15600 12:35:32.498 LENOVO 2325OG0 Not Defined (Notebook)
15600 12:35:32.514 Windows 10 Enterprise 64-bit (10.0.19041)
15600 12:35:32.514 sh2pc.exe (PID:6940)
15600 12:35:32.514 Checking for Compatibility Settings!
15600 12:35:32.514 Environment variable __COMPAT_LAYER = ""
15600 12:35:32.514 Checking if administrator access is required.
15600 12:35:32.514 Detected relaunch with administrator rights!
15600 12:35:32.545 Running from: C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\sh2pc.exe
15600 12:35:32.545 Config file: C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\d3d8.ini
15600 12:35:32.545 |----------- SETTINGS -----------
15600 12:35:32.545 |- AdjustColorTemp: 1
15600 12:35:32.545 |- AudioClipDetection: 1
15600 12:35:32.545 |- AutoUpdateModule: 1
15600 12:35:32.545 |- CatacombsMeatRoomFix: 1
15600 12:35:32.545 |- ChangeClosetSpawn: 1
15600 12:35:32.545 |- CheckCompatibilityMode: 1
15600 12:35:32.545 |- CheckForAdminAccess: 1
15600 12:35:32.545 |- ClosetCutsceneFix: 1
15600 12:35:32.545 |- CommandWindowMouseFix: 1
15600 12:35:32.545 |- CreateLocalFix: 1
15600 12:35:32.545 |- d3d8to9: 1
15600 12:35:32.545 |- DelayedFadeIn: 1
15600 12:35:32.545 |- DisableCutsceneBorders: 1
15600 12:35:32.545 |- DisableEnlargedText: 1
15600 12:35:32.545 |- DisableGameUX: 1
15600 12:35:32.545 |- DisableHighDPIScaling: 1
15600 12:35:32.545 |- DisableLogging: 0
15600 12:35:32.545 |- DisableRedCross: 0
15600 12:35:32.545 |- DisableRedCrossInCutScenes: 1
15600 12:35:32.545 |- DisableSafeMode: 1
15600 12:35:32.545 |- DisableScreenSaver: 1
15600 12:35:32.545 |- DynamicResolution: 1
15600 12:35:32.545 |- EnableDebugOverlay: 1
15600 12:35:32.545 |- EnableEnhancedMouse: 1
15600 12:35:32.545 |- EnableInfoOverlay: 1
15600 12:35:32.545 |- EnableMenuTest: 0
15600 12:35:32.545 |- EnableMenuTestIGT: 1
15600 12:35:32.545 |- EnableMouseWheelSwap: 1
15600 12:35:32.545 |- EnableScreenshots: 1
15600 12:35:32.545 |- EnableSFXAddrHack: 1
15600 12:35:32.545 |- EnableSMAA: 0
15600 12:35:32.545 |- EnableSoftShadows: 1
15600 12:35:32.545 |- EnableTexAddrHack: 1
15600 12:35:32.545 |- EnableToggleSprint: 1
15600 12:35:32.545 |- FastTransitions: 1
15600 12:35:32.545 |- Fix2D: 1
15600 12:35:32.545 |- FixAdvancedOptions: 1
15600 12:35:32.545 |- FixAptClockFlashlight: 1
15600 12:35:32.545 |- FixChainsawSpawn: 1
15600 12:35:32.545 |- FixCreatureVehicleSpawn: 1
15600 12:35:32.545 |- FixDrawingTextLine: 1
15600 12:35:32.545 |- FixFMVResetIssue: 1
15600 12:35:32.545 |- FixFMVSpeed: 1
15600 12:35:32.545 |- FixGPUAntiAliasing: 1
15600 12:35:32.545 |- FixHangOnEsc: 1
15600 12:35:32.545 |- FixInventoryBGM: 1
15600 12:35:32.545 |- FixMemoFading: 1
15600 12:35:32.545 |- FixMissingWallChunks: 1
15600 12:35:32.545 |- FixSaveBGImage: 1
15600 12:35:32.545 |- FixTownWestGateEvent: 1
15600 12:35:32.545 |- FlashlightFlickerFix: 1
15600 12:35:32.545 |- FmvSubtitlesNoiseFix: 1
15600 12:35:32.545 |- FogParameterFix: 1
15600 12:35:32.545 |- FogSpeedFix: 1
15600 12:35:32.545 |- ForceTopMost: 0
15600 12:35:32.545 |- GameLoadFix: 1
15600 12:35:32.545 |- GamepadControlsFix: 1
15600 12:35:32.545 |- HalogenLightFix: 1
15600 12:35:32.545 |- HookDirect3D: 1
15600 12:35:32.545 |- HookDirectInput: 1
15600 12:35:32.545 |- HookDirectSound: 1
15600 12:35:32.545 |- HookWndProc: 1
15600 12:35:32.545 |- HospitalChaseFix: 1
15600 12:35:32.545 |- HotelWaterFix: 1
15600 12:35:32.545 |- ImproveStorageSupport: 1
15600 12:35:32.545 |- IncreaseBlood: 1
15600 12:35:32.545 |- IncreaseDrawDistance: 1
15600 12:35:32.545 |- LightingFix: 1
15600 12:35:32.545 |- LightingTransitionFix: 1
15600 12:35:32.545 |- LoadD3d8FromScriptsFolder: 0
15600 12:35:32.545 |- LoadFromScriptsOnly: 0
15600 12:35:32.545 |- LoadModulesFromMemory: 0
15600 12:35:32.545 |- LoadPlugins: 0
15600 12:35:32.545 |- LockResolution: 1
15600 12:35:32.545 |- LockScreenPosition: 1
15600 12:35:32.545 |- LockSpeakerConfig: 1
15600 12:35:32.545 |- MainMenuFix: 1
15600 12:35:32.545 |- MainMenuTitlePerLang: 1
15600 12:35:32.545 |- MemoScreenFix: 1
15600 12:35:32.545 |- NoCDPatch: 1
15600 12:35:32.545 |- PauseScreenFix: 1
15600 12:35:32.545 |- PistonRoomFix: 1
15600 12:35:32.545 |- PS2CameraSpeed: 1
15600 12:35:32.545 |- PS2FlashlightBrightness: 1
15600 12:35:32.545 |- PS2StyleNoiseFilter: 1
15600 12:35:32.545 |- QuickSaveTweaks: 1
15600 12:35:32.545 |- ReduceCutsceneFOV: 1
15600 12:35:32.545 |- RemoveEffectsFlicker: 1
15600 12:35:32.545 |- RemoveEnvironmentFlicker: 1
15600 12:35:32.545 |- RestoreAlternateStomp: 1
15600 12:35:32.545 |- RestoreBrightnessSelector: 1
15600 12:35:32.545 |- RestoreSpecialFX: 1
15600 12:35:32.545 |- RestoreVibration: 1
15600 12:35:32.545 |- Room312ShadowFix: 1
15600 12:35:32.545 |- RoomLightingFix: 1
15600 12:35:32.545 |- RowboatAnimationFix: 1
15600 12:35:32.545 |- SaveGameSoundFix: 1
15600 12:35:32.545 |- SetBlackPillarBoxes: 1
15600 12:35:32.545 |- SetSixtyFPS: 1
15600 12:35:32.545 |- Southpaw: 0
15600 12:35:32.545 |- SpecificSoundLoopFix: 1
15600 12:35:32.545 |- SpecularFix: 1
15600 12:35:32.545 |- SteamCrashFix: 1
15600 12:35:32.545 |- UnlockJapLang: 1
15600 12:35:32.545 |- UseBestGraphics: 1
15600 12:35:32.545 |- UseCustomExeStr: 1
15600 12:35:32.545 |- UseCustomFonts: 1
15600 12:35:32.545 |- UseCustomModFolder: 1
15600 12:35:32.545 |- UsePS2LowResTextures: 0
15600 12:35:32.545 |- WhiteShaderFix: 1
15600 12:35:32.545 |- WidescreenFix: 1
15600 12:35:32.545 |- WndModeBorder: 1
15600 12:35:32.545 |- WoodsideRoom205Fix: 1
15600 12:35:32.545 |- AnisotropicFiltering: 0
15600 12:35:32.545 |- AntiAliasing: 0
15600 12:35:32.545 |- AudioFadeOutDelayMS: 10
15600 12:35:32.545 |- CRTShader: 0
15600 12:35:32.545 |- CustomFontCharHeight: 32
15600 12:35:32.545 |- CustomFontCharWidth: 20
15600 12:35:32.545 |- CustomFontCol: 25
15600 12:35:32.545 |- CustomFontRow: 17
15600 12:35:32.545 |- DPadMovementFix: 1
15600 12:35:32.545 |- EnableCriWareReimplementation: 1
15600 12:35:32.545 |- fog_transparency_layer1: 128
15600 12:35:32.545 |- fog_transparency_layer2: 112
15600 12:35:32.545 |- FogFix: 1
15600 12:35:32.545 |- FogLayerFix: 1
15600 12:35:32.545 |- FrontBufferControl: 0
15600 12:35:32.545 |- FullscreenImages: 3
15600 12:35:32.545 |- FullscreenVideos: 3
15600 12:35:32.545 |- IncreaseNoiseEffectRes: 768
15600 12:35:32.545 |- LetterSpacing: 2
15600 12:35:32.545 |- NormalFontHeight: 30
15600 12:35:32.545 |- NormalFontWidth: 20
15600 12:35:32.545 |- PadNumber: 0
15600 12:35:32.545 |- RemoveForceFeedbackFilter: 1
15600 12:35:32.545 |- RestoreSearchCamMovement: 2
15600 12:35:32.545 |- ResX: 0
15600 12:35:32.545 |- ResY: 0
15600 12:35:32.545 |- ScreenMode: 1
15600 12:35:32.545 |- SingleCoreAffinityLegacy: 0
15600 12:35:32.545 |- SmallFontHeight: 24
15600 12:35:32.545 |- SmallFontWidth: 16
15600 12:35:32.545 |- SpaceSize: 7
15600 12:35:32.545 |- fog_layer1_x1: 0.25
15600 12:35:32.545 |- fog_layer1_x2: 0.25
15600 12:35:32.545 |- fog_layer1_y1: 0.125
15600 12:35:32.545 |- fog_layer1_y2: 0.125
15600 12:35:32.545 |- fog_layer2_complexity: 0.055
15600 12:35:32.545 |- fog_layer2_density_add: 100
15600 12:35:32.545 |- fog_layer2_density_mult: 1.4
15600 12:35:32.545 |- CustomModFolder: 
15600 12:35:32.545 |- WrapperType: 
15600 12:35:32.545 |- AutoScaleImages: 1
15600 12:35:32.545 |- AutoScaleVideos: 1
15600 12:35:32.545 |- EnableCustomShaders: 1
15600 12:35:32.545 |--------------------------------
15600 12:35:32.545 |- 
15600 12:35:32.545 |-  Directory of C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut
15600 12:35:32.545 |- 
15600 12:35:32.561 |- 02/08/2022  01:21 AM    <DIR>          data
15600 12:35:32.561 |- 02/18/2022  10:27 PM    <DIR>          imgs
15600 12:35:32.561 |- 07/08/2023  05:59 PM    <DIR>          sh2e
15600 12:35:32.561 |- 11/01/2020  03:23 PM               237 alsoft.ini
15600 12:35:32.561 |- 06/25/2002  10:50 AM           358,963 binkw32.dll
15600 12:35:32.561 |- 09/03/2023  12:33 PM                24 cin.dat
15600 12:35:32.561 |- 01/26/2022  09:01 PM            15,662 d3d8.bak
15600 12:35:32.561 |- 04/04/2023  09:39 AM        10,786,816 d3d8.dll
15600 12:35:32.561 |- 09/03/2023  12:33 PM            23,771 d3d8.ini
15600 12:35:32.561 |- 09/03/2023  12:35 PM                   d3d8.log
15600 12:35:32.561 |- 09/26/2002  05:19 PM            12,332 device.fix
15600 12:35:32.561 |- 03/15/2023  12:37 PM           490,496 dinput8.dll
15600 12:35:32.561 |- 06/27/2022  05:43 PM           856,064 dsoal-aldrv.dll
15600 12:35:32.561 |- 06/27/2022  05:43 PM           143,360 dsound.dll
15600 12:35:32.561 |- 03/15/2023  12:37 PM               504 keyconf.dat
15600 12:35:32.561 |- 07/25/2002  12:02 PM                77 Konami Homepage.url
15600 12:35:32.561 |- 09/03/2023  12:30 PM                26 language.ini
15600 12:35:32.561 |- 11/20/2002  07:36 PM            38,261 LiesMich.htm
15600 12:35:32.561 |- 11/20/2002  07:36 PM            17,192 LiesMich.txt
15600 12:35:32.561 |- 08/25/2019  07:02 PM                37 local.fix
15600 12:35:32.561 |- 01/05/2002  12:40 PM           487,424 msvcp70.dll
15600 12:35:32.561 |- 06/07/2001  01:14 PM           339,968 msvcr70.dll
15600 12:35:32.561 |- 09/03/2023  12:30 PM               290 options.ini
15600 12:35:32.561 |- 09/03/2023  12:30 PM               433 settings.ini
15600 12:35:32.561 |- 07/21/2022  01:51 PM           224,254 sh2.ico
15600 12:35:32.561 |- 11/20/2002  07:36 PM            28,111 SH2DClogo.JPG
15600 12:35:32.561 |- 04/04/2023  09:36 AM         1,080,832 SH2EEconfig.exe
15600 12:35:32.561 |- 09/03/2023  12:33 PM               284 SH2EEsetup.dat
15600 12:35:32.561 |- 08/27/2023  01:23 PM         3,844,243 SH2EEsetup.exe
15600 12:35:32.561 |- 11/30/2017  05:22 PM         5,459,968 sh2pc.exe
15600 12:35:32.561 |- 01/26/2022  08:57 PM         5,459,968 sh2pc.exe.bak
15600 12:35:32.561 |- 03/15/2023  12:12 PM               412 Xidi.ini
15600 12:35:32.561 |- 01/26/2022  09:17 PM               465 _README.txt
15600 12:35:32.561 |--------------------------------
15600 12:35:32.577 Patching window title...
15600 12:35:32.577 Patching window icon...
15600 12:35:32.577 Loading d3d9.dll
15600 12:35:32.577 Enabling XInput Vibration Fix...
15600 12:35:32.577 Loading the "WidescreenFixesPack" module...
15600 12:35:32.577 Setting resolution: 1920x1080
15600 12:35:32.577 Setting Hotel Room 312 Resolution Fix...
15600 12:35:32.702 Hooking the FileSystem APIs...
15600 12:35:32.717 CD patch already set!
15600 12:35:32.717 Patching binary...
15600 12:35:32.717 Finding SFX file locations...
15600 12:35:32.905 Updating SFX memory address locations...
15600 12:35:32.905 Allocating memory buffer for sddata.bin file...
15600 12:35:32.953 Setting texture buffer size: 44761280
15600 12:35:32.984 Updating Texture memory address locations...
15600 12:35:32.984 Disabling Screensaver...
15600 12:35:32.984 Setting 2TB hard disk Fix...
15600 12:35:32.984 Setting PS2 Style Noise Filter...
15600 12:35:32.984 Increasing the Draw Distance...
15600 12:35:32.984 Setting Room Lighting Fix...
15600 12:35:32.984 Fixing tree lighting conditions...
15600 12:35:32.984 Setting Rowboat Animation Fix...
15600 12:35:32.984 Updating the Catacomb Meat Cold Rooms color...
15600 12:35:32.984 Updating Fog Parameters...
15600 12:35:32.984 Setting Piston Position Fix...
15600 12:35:32.984 Setting Hotel Room 312 Shadow Flicker Fix...
15600 12:35:32.984 Hiding Red Cross health indicator during cutscenes...
15600 12:35:32.984 Enabling PS2 Flashlight Fix...
15600 12:35:32.984 Fixing behavior of Lying Figures that are hiding under vehicles...
15600 12:35:32.984 Add fix to prevent chainsaw from spawning on first playthrough...
15600 12:35:32.984 Updating James' spawn point position...
15600 12:35:32.984 Applying Fixes for 60 FPS...
15600 12:35:32.984 Applying Meat Locker Fixes...
15600 12:35:32.984 Hooking Fog Animation Rate...
15600 12:35:32.984 Hooking Bullet Animation...
15600 12:35:32.984 Patching motion blur...
15600 12:35:32.984 Patching water animation speed...
15600 12:35:32.984 Patching flashlight speed...
15600 12:35:32.984 Patching low health indicator flashing speed...
15600 12:35:32.984 Patching flame staircase lighting...
15600 12:35:32.984 Patching water level speed...
15600 12:35:32.984 Enabling Prisoner Timer Fix...
15600 12:35:32.984 Enabling Lying Figure Spray Effect Fix...
15600 12:35:32.984 Enabling Hyper Spray Effect Fix...
15600 12:35:32.984 Enabling Map Transcribe Animation Speed Fix...
15600 12:35:32.984 Patching bug room flashlight...
15600 12:35:32.984 Enabling Enemy Hold Damage Fix...
15600 12:35:32.984 Patching Double Footstep Fix...
15600 12:35:32.984 Done applying 60 FPS fixes...
15600 12:35:32.984 Fixing Flashlight Flicker...
15600 12:35:32.984 Fixing memo brightness...
15600 12:35:32.984 Setting Pause Menu Fix...
15600 12:35:33.999 loadExternalFontData: Using font file: sh2e\font\font000.png fontColumnNumber 100 fontRowNumber 150
15600 12:35:33.999 Enabling Custom Fonts...
15600 12:35:33.999 PatchCustomFonts Could not find font width data file
15600 12:35:33.999 Enabling Custom Exe Strings...
15600 12:35:33.999 Enabling Main Menu title selection by language...
15600 12:35:34.015 Enabling post Processing Special FX...
15600 12:35:34.015 Enabling Alternate Stomp...
15600 12:35:34.015 Enabling Town West Gate Event Fix...
15600 12:35:34.015 Enabling Screen Position option lock...
15600 12:35:34.015 Fixing Flashlight Clock Push...
15600 12:35:34.015 Fixing Game Results loading crash...
15600 12:35:34.015 Patching Quick Save Text Position...
15600 12:35:34.015 Fixing "Save Game" Sound...
15600 12:35:34.015 Fixing Inventory BGM...
15600 12:35:34.015 Fixing Moth Sound Looping...
15600 12:35:34.015 Fixing Chainsaw Sound Looping...
15600 12:35:34.015 Enabling Save Background Images Fix...
15600 12:35:34.015 Enabling Best Graphics settings...
15600 12:35:34.015 Enabling Speaker Config Lock...
15600 12:35:34.015 Enabling Fog Fix...
15600 12:35:34.015 Set map scaling!
15600 12:35:34.015 Set texture scaling!
15600 12:35:34.015 Fixing Movies ratio crash...
15600 12:35:34.015 Enabling Dynamic Resolution...
15600 12:35:34.046 Enabling Advanced Options fix...
3848 12:35:34.109 CheckForUpdate SH2EEsetup.dat exists, using CSV for update checking...
15600 12:35:34.359 Enabling Criware...
15600 12:35:34.359 Patching FMV speed...
15600 12:35:34.359 Patching Delayed Fade-in...
15600 12:35:34.359 Patching FMV subtitles to draw over noise grain...
15600 12:35:34.359 Patching Command Window Mouse Fix...
15600 12:35:34.359 Silent Hill 2 Enhancements module loaded!
15600 12:35:34.359 Redirecting 'DirectInput8Create' ...
15600 12:35:34.390 LogAffinity System has '4' cores and Silent Hill 2 is using '4' cores.
15600 12:35:34.390 |-------- MODULES LOADED --------
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\sh2pc.exe
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\ntdll.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\KERNEL32.DLL
15600 12:35:34.390 |- C:\WINDOWS\System32\KERNELBASE.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\USER32.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\win32u.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\GDI32.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\gdi32full.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\msvcp_win.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\ucrtbase.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\ADVAPI32.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\msvcrt.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\sechost.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\RPCRT4.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\ole32.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\combase.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\WINMM.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\DINPUT8.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\SHELL32.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\d3d8.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\PSAPI.DLL
15600 12:35:34.390 |- C:\WINDOWS\System32\SHLWAPI.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\OLEAUT32.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\DSOUND.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\binkw32.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\MSVCR70.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\MSVCP70.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\IMM32.DLL
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\windows.storage.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\Wldp.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\SHCORE.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\uxtheme.dll
15600 12:35:34.390 |- C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\dsoal-aldrv.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\MSVCP140.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\version.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\d3d9.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\kernel.appcore.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\dwmapi.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\xinput1_4.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\cfgmgr32.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\DEVOBJ.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\inputhost.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\CoreMessaging.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\WS2_32.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\PROPSYS.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\wintypes.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\bcryptPrimitives.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\ntmarta.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\urlmon.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\iertutil.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\srvcli.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\netutils.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\WININET.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\SspiCli.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\profapi.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\winhttp.dll
15600 12:35:34.390 |- C:\WINDOWS\system32\mswsock.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\WINNSI.DLL
15600 12:35:34.390 |- C:\WINDOWS\System32\NSI.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\CRYPT32.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\DPAPI.DLL
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\MSASN1.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\WINTRUST.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\CRYPTSP.dll
15600 12:35:34.390 |- C:\WINDOWS\system32\rsaenh.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\bcrypt.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\DNSAPI.dll
15600 12:35:34.390 |- C:\Windows\System32\rasadhlp.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\fwpuclnt.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\schannel.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\mskeyprotect.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\NTASN1.dll
15600 12:35:34.390 |- C:\Windows\System32\cryptnet.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\ncrypt.dll
15600 12:35:34.390 |- C:\WINDOWS\system32\ncryptsslp.dll
15600 12:35:34.390 |- C:\WINDOWS\System32\MSCTF.dll
15600 12:35:34.390 |- C:\WINDOWS\system32\dinput8.dll
15600 12:35:34.390 |- C:\WINDOWS\SYSTEM32\HID.DLL
15600 12:35:34.390 |- C:\WINDOWS\System32\SETUPAPI.DLL
15600 12:35:34.390 |--------------------------------
15600 12:35:34.421 Redirecting 'Direct3DCreate8' ...
15600 12:35:34.421 Starting D3d8to9 v1.11.1.0
15600 12:35:34.421 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
15600 12:35:34.421 Initializing crosire's ReShade version '4.5.3.797' (32-bit) built on '2020-10-03 01:58:54' loaded ...
15600 12:35:34.421 |------------- GPUs -------------
15600 12:35:34.421 m_IDirect3D9::LogAdapterNames | - Adapter: 0 \\.\DISPLAY1 Intel(R) HD Graphics 4000
15600 12:35:34.421 |--------------------------------
15600 12:35:34.453 |---------- VIDEO CARD ----------
15600 12:35:34.453 | Using video card: Intel(R) HD Graphics 4000 (0x8086)
15600 12:35:34.453 |--------------------------------
15600 12:35:34.453 Setting Window theme...
15600 12:35:34.468 Setting Window Attributes...
15600 12:35:34.578 Running on Intel(R) HD Graphics 4000 Driver 51.61
15600 12:35:34.578 Recreated runtime environment on runtime 15AE7E38.
15600 12:35:34.578 m_IDirect3D8::CreateDevice Created device!
15600 12:35:34.734 m_IDirectInput8A::CreateDevice Created device!
15600 12:35:34.749 |----------- GAMEPADS -----------
15600 12:35:34.843 |- Name: 'Xidi Virtual Controller 1' GUID: {FFFFFFFF-0000-0000-5849-444900000000}
15600 12:35:34.843 |- Name: 'Xidi Virtual Controller 2' GUID: {FFFFFFFF-0000-0000-5849-444901000000}
15600 12:35:34.843 |- Name: 'Xidi Virtual Controller 3' GUID: {FFFFFFFF-0000-0000-5849-444902000000}
15600 12:35:34.843 |- Name: 'Xidi Virtual Controller 4' GUID: {FFFFFFFF-0000-0000-5849-444903000000}
15600 12:35:35.171 |--------------------------------
15600 12:35:35.171 Removing Force Feedback filter!
15600 12:35:35.296 Using gamepad device GUID: {FFFFFFFF-0000-0000-5849-444900000000}
15600 12:35:35.318 Redirecting 'DirectSoundCreate8' ...
15600 12:35:35.843 m_IDirectSound8::CreateSoundBuffer Created buffer!
15600 12:35:36.164 Patching Quick Save Text Fading Too Quickly...
15600 12:35:36.164 Setting Hotel Water Fix...
15600 12:35:36.164 Setting RPT Apartment Closet Cutscene Fix...
15600 12:35:36.164 Setting RPT Hospital Elevator Animation Fix...
15600 12:35:36.164 Fixing Esc while transition is active...
15600 12:35:36.164 Setting infinite rumble window hook...
15600 12:35:36.164 Enabling Lighting Transition Fix...
15600 12:35:36.165 Enabling Load Game Fix...
15600 12:35:36.165 Enabling Blood Size Fix...
15600 12:35:36.165 Fixing the rotating Mannequin glitch...
15600 12:35:36.165 Setting Fog Speed Fix...
15600 12:35:36.487 Destroyed runtime environment on runtime 15AE7E38.
15600 12:35:36.487 Recreated runtime environment on runtime 15AE7E38.
15600 12:35:36.491 Successfully loaded MinimalColorGrading.fx
15600 12:35:36.494 Successfully loaded LiftGammaGain.fx
15600 12:35:36.494 Enabling technique: MinimalColorGrading
15600 12:35:36.494 Enabling technique: LiftGammaGain
15600 12:35:36.500 Successfully loaded MinimalColorGrading.fx
15600 12:35:36.503 Successfully loaded LiftGammaGain.fx
15600 12:35:36.503 Enabling technique: MinimalColorGrading
15600 12:35:36.503 Enabling technique: LiftGammaGain
15600 12:35:36.504 m_IDirect3DDevice9::Present Skipping frame after gamma change!
15600 12:35:36.535 m_IDirect3DDevice9::Present Skipping frame after gamma change!
15600 12:35:36.577 Loading image files for textures ...
15600 12:35:42.908 m_IDirect3DDevice8::FakeGetFrontBuffer Using GDI to get front buffer data.
15600 12:35:43.543 GetDiskSpace Available disk space smaller than 2TBs: 296247336
15600 12:37:12.612 GetFMVRes Error: failed to open file: 'data\movie\hakaba.bik'
15600 12:37:12.612 GetFMVRes Error: failed to open file: 'data\movie\hakaba.bik'

**Comment by Thomas20232030** [comment]
> > I have found the file d3d8.log in my main folder C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut. What do you mean with update? How can I update this file? A little hint woud be very helpful, thanks in advance!
> > Thomas
> 
> Polymega means upload. please upload your d3d8.log here.

OK, thank you, there it is;=)

**Comment by Thomas20232030** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12515188/d3d8.log)

**Comment by Polymega** [comment]
There is an error in the log file at the bottom:

```
15600 12:37:12.612 GetFMVRes Error: failed to open file: 'data\movie\hakaba.bik'
```

Can you navigate to `C:\Program Files (x86)\Konami\Silent Hill 2 - Directors Cut\data\movie\` and take a snapshot of the contents inside this folder?

**Comment by Thomas20232030** [comment]
![Directory](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/93368933/0ae0067d-35de-4606-a73d-00e0ffa0274d)

**Comment by Thomas20232030** [comment]
As you can see in the screenshot there is no subdirectory "movie" in the directory "data".  Do you think this causes the error? 

Thomas

**Comment by Polymega** [comment]
Most likely. I'd recommend starting over from the beginning. When installing the vanilla game, be sure to follow all the steps outlined on our website: https://enhanced.townofsilenthill.com/SH2/install.htm#installGame

In particular:

- When selecting a path to install the game, it is recommended to choose a local user directory.
   - _I'd recommend **not** installing the game to `Program Files (x86)`. Instead, install it to a local user directory such as `My Games` or `My Documents`_
- Near the start of installation, when prompted, save the movie files to your hard disk.
- At the end of installation, select "**NO**" when Silent Hill 2 PC asks if you want to install any necessary DirectX 8.1 drivers.

**Comment by Polymega** [comment]
Yes, go to `data\save\` and make a **backup** of the `Folder 01` folder found here.

Then, once you reinstall everything, move your backed up `Folder 01` folder into the `data\save\` directory.

**Comment by Thomas20232030** [comment]
Thank you very much, everything now runs perfect;=)
