### ISSUE TITLE
Missing camera fix

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#84]
Hi!

Playing today I discovered that one of the camera fixes it's missing again. It's on the parking lot at the beginning, when James walks to the right trying to leave the town. You can see a missing texture on the little wall. This was fixed before, but it's appearing again, maybe during the process of the changes made on the room.

**Comment by Polymega** [comment]
@Bigmanjapan 
When you made use [this new camera angle fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/49#issuecomment-425261808) for the Observation Deck I forgot to tell you that there was [a previous camera angle fix](https://github.com/ThirteenAG/WidescreenFixesPack/issues/340#issuecomment-375665740) for another area in `ob01.cam`. I'm sorry about that. 

Would you please re-implement [the previous camera angle](https://github.com/ThirteenAG/WidescreenFixesPack/issues/340#issuecomment-375665740) into the new file? 

Thank you

Here is the new file: [ob01.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2427886/ob01.zip)
Here is the older file (with the previous fix): [ob01.zip](https://github.com/ThirteenAG/WidescreenFixesPack/files/1844647/ob01.zip)

These are the two fixes for that file: 
![image](https://user-images.githubusercontent.com/27395260/37831799-15ff29b8-2e7d-11e8-90f2-88ecf8cdad35.jpg)
![image](https://user-images.githubusercontent.com/27395260/46177847-71779700-c282-11e8-9575-87fc55d05c3b.png)

**Comment by AeroWidescreen** [comment]
@Polymega 

Try this: [ob01.cam](https://mega.nz/#!VXQ1QKKA!qjC1qO6u3M5V-LrThVqzv6-NxEa0ntOhKQCX3M7lVIQ)

**Comment by Polymega** [comment]
Perfect and confirmed both camera fixes are here. Thank you so much, Aero_, and thank you always Bigmanjapan. I've added this file into the Essential Files download. v.1.0.4 of this package should be released in the near-future (thanks to the upcoming HD font fix) so people will be able to get this rectified .cam file then.

@Storm3000 you can grab the revised .cam file from Aero_'s link above. Place it in `\sh2e\bg\ob\`.

Also Storm3000, would you mind closing this ticket and [this one](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/82) whenever you're able?
