### ISSUE TITLE
Error to download almost all files on Setup tool

### ISSUE THREAD

**Issue by Toan-5** [elishacloud/Silent-Hill-2-Enhancements#842]
Hello

The setup tool fails to download the files.
I tried to manually download the audio file via the link found in [this thread](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/835), I try again and the same thing happens but with other files.
A list of updated direct downloads is needed, so every user who has the same problem as me can download them themselves

![Untitled](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/145114728/b028918e-5f58-4d74-88de-9d20e1c508da)

thank you in advance

**Comment by Polymega** [comment]
Sorry you're having problems with the installer. Please refer to this ticket for manual downloads: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/830
