### ISSUE TITLE
Image ghosting after load screen.

### ISSUE THREAD

**Issue by GreenBeanMech** [elishacloud/Silent-Hill-2-Enhancements#843]
In the Wood Side Apartments after the scene with Pyramid Head in the sink, the final image of that scenes persists on every subsequent loading screen. I think it gets overwritten by the last frame on the next cutscene but I'm unable to confirm this.

Either way please fix it, it's very jarring in this otherwise fantastic remaster!

[https://www.youtube.com/watch?v=PBO3lhgpJfs](url)

**Comment by Polymega** [comment]
This feature should address and prevent that issue:
https://enhanced.townofsilenthill.com/SH2/config.htm#DisableHighDPIScaling

Can you confirm it is enabled? Also, closing and relaunching the game should also fix it.

**Comment by GreenBeanMech** [comment]
> This feature should address and prevent that issue: https://enhanced.townofsilenthill.com/SH2/config.htm#DisableHighDPIScaling
> 
> Can you confirm it is enabled? Also, closing and relaunching the game should also fix it.

Already done that a few times also:
<img width="1025" alt="dpi_scaling_disabled" src="https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/19272886/f96576d2-c7f2-499f-852a-1e5263264068">

**Comment by GreenBeanMech** [comment]
It seems that after doing the pyramid head fight I'm no longer getting that issue, so maybe it's something specific about Wood Side Apartments.
