### ISSUE TITLE
Controller Inputs seem to be wrong

### ISSUE THREAD

**Issue by ValentinesNapkin** [elishacloud/Silent-Hill-2-Enhancements#844]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12643486/d3d8.log)
I use a Razer Wolverine Xbox controller and the controller in the game seems to work fine. However my inputs are in some weird way reversed, for example, "run" is activated when pressing "a" instead of "x", when selecting something in the game settings the action button is "x", when exiting it uses "y" etc. The Inputs don't allign with the actual/real controls. Is there a way to fix this? 

I also think the "search camera movement" doesnt work as well, should the game camera move in some way with this or something else? I am sorry for the confusion, I am new to the game.

Thank you in advance for the help!!!!!

**Comment by ValentinesNapkin** [comment]
Here is my Log
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12643484/d3d8.log)

**Comment by ValentinesNapkin** [comment]
Here is a video for reference

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/145286514/3fe7b251-7cc8-4993-b871-fc01275c2c8f

**Comment by AeroWidescreen** [comment]
Did you mean the Razer Wolverine? Because there's no Razer Raiju for Xbox that I can find. Anyway, this problem is likely because of the extra buttons your controller has, which you would have to disable through your driver software. It's really hard to say since it's not a typical Xbox or PlayStation controller. 

https://mysupport.razer.com/app/answers/detail/a_id/5629

**Comment by ValentinesNapkin** [comment]
> d

oh yeah my bad, that was the wrong name for the controller. But the extra buttons being the problem is something I will look into. Thank you!!!!!

**Comment by Polymega** [comment]
Hi there,

It's always tricky to figure things out with controllers, as different controller manufacturers can do things differently, and this doubly becomes a problem if the controller wasn't inherently made for PC (but can still work on PC).

The good news is that this seems like a simple case of remapping inputs through the game. Please refer to the link below to see the typical controller layout for SH2:

https://enhanced.townofsilenthill.com/SH2/install.htm#controller

In the game, go to Options > Control Options. **With your keyboard**, navigate to the **Joypad** column, highlight the input you wish to reassign, press **Enter** on your keyboard, _then_ press the input on your controller you wish to assign to that function.

To **clear** an assigned function, use your keyboard again, navigate to the function, press Enter, then press Esc to clear out the function.

**Comment by ValentinesNapkin** [comment]
> Hi there,
> 
> It's always tricky to figure things out with controllers, as different controller manufacturers can do things differently, and this doubly becomes a problem if the controller wasn't inherently made for PC (but can still work on PC).
> 
> The good news is that this seems like a simple case of remapping inputs through the game. Please refer to the link below to see the typical controller layout for SH2:
> 
> https://enhanced.townofsilenthill.com/SH2/install.htm#controller
> 
> In the game, go to Options > Control Options. **With your keyboard**, navigate to the **Joypad** column, highlight the input you wish to reassign, press **Enter** on your keyboard, _then_ press the input on your controller you wish to assign to that function.
> 
> To **clear** an assigned function, use your keyboard again, navigate to the function, press Enter, then press Esc to clear out the functio

**Comment by ValentinesNapkin** [comment]
> Hi there,
> 
> It's always tricky to figure things out with controllers, as different controller manufacturers can do things differently, and this doubly becomes a problem if the controller wasn't inherently made for PC (but can still work on PC).
> 
> The good news is that this seems like a simple case of remapping inputs through the game. Please refer to the link below to see the typical controller layout for SH2:
> 
> https://enhanced.townofsilenthill.com/SH2/install.htm#controller
> 
> In the game, go to Options > Control Options. **With your keyboard**, navigate to the **Joypad** column, highlight the input you wish to reassign, press **Enter** on your keyboard, _then_ press the input on your controller you wish to assign to that function.
> 
> To **clear** an assigned function, use your keyboard again, navigate to the function, press Enter, then press Esc to clear out the function.

Respond: Thank you very much for the help. I just remapped all the buttons ingame. It appears that everthing just works fine. I thought the game would be corrupted in some way but good that I was wrong!!!
