### ISSUE TITLE
Hiccups in the outside area after Brookhaven Hospital

### ISSUE THREAD

**Issue by bongrippers** [elishacloud/Silent-Hill-2-Enhancements#845]
I'm replaying the game on a new graphics card (used RTX 2060 if that helps) and I don't think I've seen this issue before on my first playthrough before I upgraded but the game will slow down for half a second randomly, usually around enemies, and in bursts. The issue goes away completely when I turn the flashlight off. Is something wrong on my end or is this a bug? Around Saul St. near the barrier it happens most often.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12644637/d3d8.log)

**Comment by bongrippers** [comment]
Turning off the 3D fog doesn't help either but it's the night segment so I doubt it'd do anything

**Comment by Polymega** [comment]
I actually know of the exact hiccup you're referring to with Saul St. It happens only at night, after the hospital, at the intersection of Saul St. and Munson St.

I also experience this on my GTX 1660. A long time ago I brought this up to a couple other team members, one who had a different type of Nvidia GPU and the other who had an AMD card. For them, they didn't experience this issue.

It's not ideal, but this is a situation we might need to chalk up as, "it's a very old, janky-ish PC port of a PS2 game with a ton of quirks." In other words, these occasional hiccups might just have to be tolerated, unfortunately.

**Comment by Polymega** [comment]
We've found the culprit to be the shadows in this area.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/e99ab7b5-9aea-4e71-b8b4-cd0857edce92)

Disabling shadows prevents any lag here. We'll look into the possibility of adding a .kg2 (shadow file) editor to the tool to see if we can fix/improve this in any way down the line.

**Comment by Polymega** [comment]
[Using this documentation](https://github.com/Polymega/SilentHillDatabase/blob/master/SH2/Files/kg.md) on the `.kg*` format, here is a list of object counts per shadow file for Town West:

cc*.kg2 | Object Count
-- | --
01 | 17
02 | 47
03 | 33
04 | 11
05 | 117
06 | 27
07 | 55
08 | 4
09 | 20
10 | 22
11 | 106
12 | 51
13 | 60
14 | 43
15 | 113
16 | 70
17 | 57
18 | 5
19 | 43
20 | 36
21 | 13
22 | 40
23 | 38
24 | 32
25 | 97
26 | 44
27 | 23
28 | 29
29 | 31
30 | 30
31 | 11
32 | 10
33 | 47
34 | 55
35 | 29
36 | 26
37 | 6
38 | 21
39 | 76
40 | 85
41 | 19
42 | 27
43 | 65
44 | 33
45 | 64
46 | 98
47 | 34
48 | 29
49 | 31
50 | 37
51 | 55
52 | 59
53 | 105
54 | 108
55 | 98
56 | 86
57 | 51
60 | 115
62 | 50
63 | 68
64 | 79
65 | 30
66 | 24
67 | 103
68 | 33
69 | 56
70 | 56
71 | 67
72 | 4
74 | 25
75 | 24
76 | 24
77 | 24
99 | 11

With SH2, the game will load the chunk of the town you're currently in, along with surrounding chunks in anticipation for whichever direction you progress while in the town. The slowdown areas in question look to be these `cc` town chunks:

- cc13, cc14, cc15, cc25, cc33, and cc34.

Out of these files, I believe cc15, cc25, and cc34 .kg2 files are the main culprits for the slowdown. If I replace their `.kg2` files with other ones, I maintain 60 FPS the whole time in this area.

Let's look at these ones specifically from the table above:

cc*.kg2 | Object Count
-- | --
15 | 113
25 | 97
34 | 55

So while in this area, these three specific `.kg2` files are loading in **265 objects** alone. That's not counting the other ones also loaded while in this area that don't seem to be causing the slowdown (cc13, cc14, and cc33 which have a total of 150 objects between them).

So my theory is that there's simply too much shadow geometry going on in this one area for the game engine to handle.

Hopefully we can edit `.kg2` files in the future to possibly mitigate this slowdown.

**Comment by Polymega** [comment]
@elishacloud 
Through further testing, d3d8to9 might have a large play into this lag/hiccups. In relation to the ticket here, there's a particular area that experiences bad lag and stuttering. It became noticeable once we released the 60 FPS feature. It looks to happen--or become heavily exacerbated--when d3d8to9 is enabled. It can be resolved while d3d8to9 is enabled if you disabled dynamic shadows for the game (which is something we wouldn't want to do).

### d3d8to9 enabled, shadows enabled
https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/abea4e0b-d3a1-4df3-8617-dd6dd41a7ca1

### d3d8to9 enabled, shadows disabled
https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/761d3c10-42c4-4fcf-b7cf-02434f48961d

### d3d8to9 disabled, shadows enabled
https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/d56cab40-e9e8-4916-8402-ed6fada787ef

**Comment by Polymega** [comment]
I'm in the process of working on this. I'm going to update this post with stats as I work on them. 

### Town West - South East

cc*.kg2 | Original Object Count | New Object Count
-- | -- | --
06 | 27 | 24
13 | 60 | 45
14 | 43 | 32
15 | 113 | 60
16 | 70 | 51
25 | 97 | 58
26 | 44 | 30
33 | 47 | 35
34 | 55 | 33
39 | 76 | 39
40 | 85 | 53
68 | 33 | 30

**Comment by Polymega** [comment]
@bongrippers 
Can you place these files in `sh2e\bg\cc\` and see if it improved your performance in that area?
[cc.kg2.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14971804/cc.kg2.zip)

**Comment by Polymega** [comment]
Our most recent update aims to lessen the intensity of this issue. For some users, it makes the issue fully resolved. This is the best we can do for this particular issue.

**Comment by Tempest701** [comment]
If anyone is still having this issue what helped me was:

- Turning off all external fps caps (like RTSS) and only use the in game fps cap
- Set "Texture filtering quality" to "Performance"
- Experiment with tessellation settings. i use the Radeon control panel and setting it to "AMD Optimized" helped a lot
- Turn on "Surface Format Optimization"

Here is James standing in one of those problem areas before and after the changes i suggested:

Before:
![Image](https://github.com/user-attachments/assets/d0852078-7d31-4c65-b6b4-90cee982be9a)

After:

![Image](https://github.com/user-attachments/assets/0abe6a64-3eec-436d-a4c9-20a1cd51b191)
