### ISSUE TITLE
HELP NEEDED - List of "seams" caused by MSAA

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#846]
Hello all,

I'm in the process of addressing as many of the "seams" caused by using Multi-Sample Anti-Aliasing (MSAA) as I possibly can. Refer to images below for examples.

I would like anyone's help in finding more of these instances for me to correct. I'm going to try and correct as many of them as I can. But being one person, I may only spot/notice so many. If I have more eyes on this, we can correct more seams. 

What makes this even trickier is that some of the seams only show up when the camera is at particular angles or when the flashlight is turned on; so you really have to be deliberate with looking.

# To help test
You just need to be using MSAA while playing the game. [Refer here to learn how to correctly enable MSAA for the game (under "GPU-BASED ANTI-ALIASING").](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-antialiasing-should-i-use-for-the-game) Once enabled, simply play the game and keep an eye out for seams. Make sure you disable the project's built-in SMAA shader, if you were using it.

**NOTE:** Don't confuse _texture seams_ with _MSAA seams_. There are A LOT of texture seams throughout the game; this is caused by how the devs UV mapped everything and will display this way no matter what. For this exercise, we want to address MSAA seams--that is, seams that only appear due to using MSAA.

-------------------------

❗  ❗  **YOU WILL LIKELY NEED TO ENLARGE IMAGES TO SEE THE FINE SEAMS** ❗  ❗  

### Seams along ALL the roads for Town West - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/cf205d52-c4de-4889-8611-5da0aeca1959)

### Seams at end of ALL walls at hallway intersections for Wood Side & Blue Creek hallways  - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/09083a79-bfdf-4442-99c0-df88e1fa283b)

### Seams at end of ALL walls at hallway intersections for Hospital - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/7329205e-b325-4bcf-a8ca-3e4d28ba7793)

### Seams on door behind music box for Hotel - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/722c6c11-cc9b-434f-9b63-1466419da9b9)

### Seams at end of ALL walls at hallway intersections for Hotel - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/a37c2ef2-83c8-4675-b00b-d4bc69636215)

### Seams at edge of door for Strange Prison hallway - ✔️ FIXED
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/50aa8d97-11ed-4546-9c44-50192f646cf7)

**Comment by elishacloud** [comment]
Does this mean we can use Direct3D9's MSAA and Anisotropic Filtering?

**Comment by Polymega** [comment]
My gut says probably not, but we can try again. I believe what made MSAA behave so well with the game's textures (minus those outlier cases shared in the initial post in this ticket) is the use of [Nvidia's **Antialising - Transparency** setting](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-antialiasing-should-i-use-for-the-game) (and AMD's equivalent).

We can certainly test again, but I'm feeling certain it'll present a litany of those issues we found several times back when we were experimenting with it.

**Comment by Polymega** [comment]
Truth be told, I'm not 100% sure what AA method Nvidia's Control Panel force uses on games?
https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Tips_for_Setting_Antialiasing.htm

**Comment by elishacloud** [comment]
Ok, with the latest build I re-enabled full anisotropic filtering.  You can try with the latest build by enabling the following in the ini file:

```ini
AnisotropicFiltering = 1
AntiAliasing = 1
```

BTW: it looks amazing to me with these enabled, but I am still seeing seams.

**Comment by Polymega** [comment]
Can you give me an example of where you're seeing seams? I don't have time tonight to sit down and get serious with it, but a did test 2-3 spots I remember the project's built-in MSAA causing us issues with seams in the past, and they're not there.

I think this might be because of my fixed .map files (to address the seams as mentioned in the first post above). Perhaps the fixes were robust enough to fix them more broadly than I anticipated? I'll have to sit down and do a thorough test with it to be sure, though.

**Comment by elishacloud** [comment]
I was seeing seams in the trees at the beginning of the game when I have both AnisotropicFiltering and AntiAliasing enabled and I am using the latest build from [Actions](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6759367599).

**Comment by Polymega** [comment]
Interesting. I don't have them. I'll email you some test .map files before I go to bed tonight.

![Screenshot 2023-11-05 01-33-04](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/15274ebc-4dc0-496e-bba6-398b4250b45f)
![Screenshot 2023-11-05 01-33-07](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/bead15e4-60d0-4a65-9f9d-cb659ad1f04b)
![Screenshot 2023-11-05 01-33-15](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/12771ea2-c4b6-4bca-9070-3c60d085ee5e)

**Comment by elishacloud** [comment]
Yes, I am still seeing them with the new maps if I have `AnisotropicFiltering` enabled using the latest build (created today).  Or if I am using a non-Nvidia video card and have `AntiAliasing` enabled.

![Screenshot 2023-11-04 22-46-49](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/73a5fb0f-1a36-410e-a09a-880b2d26be2a)

**Comment by Polymega** [comment]
I wonder what we have different that seems to make things okay for me (so far, from the limited tests I did last night)?

I've disabled all AA overrides for the game in my Nvidia control panel to ensure I'm only use your AA and AF features in the module:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/ef72fa67-a6b4-4bb8-a874-5701553b186f)

**Comment by Polymega** [comment]
Elisha, do you have `FixGPUAntiAliasing` disabled? When I disable it, I see those lines:

![Screenshot 2023-11-05 11-50-21](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/77f17773-c9b8-43a9-a718-6b056d5c9fab)

**Comment by Polymega** [comment]
I don't have an AMD machine to test, but with an Intel IGP, those black lines are present with or without `FixGPUAntiAliasing` enabled when either AA or AF are enabled.

**Comment by elishacloud** [comment]
Just to make sure we are using the same thing, here is the dll and ini file I am using:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13273497/d3d8.zip)

I am testing this on a laptop that has a hybrid Intel-Nvidia adapter, so I can test both Intel and Nvidia.

**Comment by Polymega** [comment]
Yep. On my Nvidia PC, so long as `FixGPUAntiAliasing` is enabled, then the following work without any MSAA seams that I can see:

```ini
AnisotropicFiltering = 1
AntiAliasing = 1
```

If I disable `FixGPUAntiAliasing` on my Nvidia PC, I see the seams. On my Intel IGP laptop, I see the seams no matter what I enable/disable, so long as either of those INI options mentioned above are enabled.

**Comment by Polymega** [comment]
Here's another area I remember being really bad from our tests with this a few years back.

![Screenshot 2023-11-06 19-26-52](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/90004a15-86de-483a-adbd-90f20426052d)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/67c5e3a3-d3e6-451c-97a2-4186884a5a8e)

It's not a problem now when I have `FixGPUAntiAliasing` also enabled. Not sure what's changed? The only difference I can think of are my .map adjustments. 🤔

**Comment by Polymega** [comment]
Yep. 100% using the builds you sent to test. I also noticed AF either not being on at all or not as robust as on your's. I made sure any AA/AF overrides were disabled in my Nvidia control panel.

**Comment by Polymega** [comment]
Sure thing. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13274360/d3d8.log)

**Comment by elishacloud** [comment]
The log shows everything ok.  Maybe there is an issue with the way I am enabling AF in this module and it is not working on your computer.  Try enabling AF through the Nvidia Control Panel and see if the moire effect is gone from the bricks at the beginning.  If AF is enabled you will not see the moire effect at all.

**Comment by Polymega** [comment]
The plot thickens. I enabled it but it's still not taking effect.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2ff60bbd-2131-4003-9828-9a5c481489ff)
![Screenshot 2023-11-07 14-11-57](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/77b93f2b-6cd4-4017-a55f-66878f227c0e)

**Comment by elishacloud** [comment]
That is why you are seeing different results.  If I disable AF I get the same results as you.  I am not sure why AF is not working for you.
