### ISSUE TITLE
SH2EE Setup Tool not working, no antivirus

### ISSUE THREAD

**Issue by KatsuragiMisato2022** [elishacloud/Silent-Hill-2-Enhancements#849]
Hey, I'm struggling from the download failed: an error occurred in the secure channel support issue. I've checked to make sure I don't have any antivirus targeting either the SH2 folder or the setup tool application. I looked through the issues here for a bit and noticed it was suggested to try and install only the required files first to see if those install, and they do without issue, but when I have to install the larger files, I start getting this error about halfway through. My internet connection is pretty solid, so I'm not sure what exactly is going on. Any help is greatly appreciated! 
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/106928209/0e38f5dc-41ee-4c8c-b080-2d194ea6df3b)

Edit: As a note, the product version listed for the setup tool is 1.1.3, and to reiterate it works perfectly fine with all of the smaller files, it's only with the larger ones that it consistently stops the download to tell me there was an error. This is my first time trying to play the enhanced edition as well, so hopefully it's just a simple fix.

**Comment by Polymega** [comment]
Sorry you're having issues with the larger downloads. This is something we want to look into and hopefully rectify in the future for users. It works totally fine for some, but not others. We're still trying to figure out what makes it not work for some.

In the meantime, please refer to this solution as a workaround: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/830

**Comment by KatsuragiMisato2022** [comment]
Alright, will do. Thank you so much for the quick response!
