### ISSUE TITLE
Addendum to `Room312ShadowFix`

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#850]
### SPOILERS IN VIDEOS BELOW

This is an addendum to the [Room312ShadowFix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Room312Shadow.cpp) feature. This feature fixes buggy shadow behaviors while in this room. While we fixed the most egregious issues of shadow behavior, there still remained an instance of rather distracting "shadow" bugging out on the patio doors (pay attention to them over Laura's head here):

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/55528e18-6bf2-4a53-af09-54099f888b0d

This rendering error is _not_ caused by shadows but instead due to misplaced coordinates for the poly plane(s) that make up the bloom effect behind the patio doors. The coordinates for the top two vertices are different than the bottom two, creating a slight angle for the bloom plane which "cuts" through the patio doors halfway up, creating this glitch.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/3756caed-9e2a-4239-bce2-50ee6be20765

To fix it, we just need to move the bottom two verts that make up the bloom plane to match the coordinates of the top two verts.

### Solution: Change from `18336.5f` to `18344.0f`
**1.0:** `008C9640` & `008C964C`
**1.1:** `008CD310` & `008CD31C`
**DC:** `008CC310` & `008CC31C`

**Comment by elishacloud** [comment]
I believe I fixed this correctly.  I just set the value once on start.  Hopefully it does not need to be set again later.

Here is a test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13314132/d3d8.zip)

**Comment by Polymega** [comment]
Nailed it! Tested on all binaries and works great. And yes, just set once on game launch. Thank you!
