### ISSUE TITLE
How to revert the camera angle

### ISSUE THREAD

**Issue by magnum835** [elishacloud/Silent-Hill-2-Enhancements#853]
In your update vid 8 you show the cutscene where James digs in the dirt behind that goddess statue but you've changed the camera angle to not show his hands doing this. I would like to know if there's anyway to revert this back to its default angle?

**Comment by Polymega** [comment]
You can delete this file: \sh2e\demo\anahori\anahori.dds

**Comment by magnum835** [comment]
Thank you. I just finished the game a few of times with your mod and it is very excellent!

I'm sorry for the late reply my GPU died suddenly so had to wait to get a new one

I hope once everything is done that you will make it easier for people like me who wants to experience the game as close to
vanilla as possible. No offense of course i like much of your work but some of it not so much. I really wish you would make the refrigerator cord an optional toggle since it's not just a simple texture upgrade/edit/removal for instance.
I also think the noise filter should be toggled on by default (maybe it was just me but it was turned off by default in the menu even though the configurator allowed me to set the grain resolution).
I know some people think digital grain is ugly but I think it really works for horror games and that's the way Team Silent wanted you to experience the game.

**Comment by Nessu4K** [comment]
Thanks for this, I noticed the cutscene was not how I remembered it and wanted to change it back.
I wonder why you guys changed it?
