### ISSUE TITLE
Gedosato Downsampling Crash

### ISSUE THREAD

**Issue by kaaona** [elishacloud/Silent-Hill-2-Enhancements#854]
Well the game crashes to desktop whenever you hit esc to open the menu or if you navigate to the starting options menu, by way of the main menu, while downsampling with Gedosato.

It really helps with shimmering and shadow crawling*, and that can be seen from the start of the game on the side of the trash can and on the side wall of the WC. (This is so if someone else wants to try Gedosato they can check if its working.) Silent Hill 2 Enhanced Edition increases the resolutions of a lot of textures and adds specularity to many others, both of which increase these kinds of aliasing. Edit: Be warned that Gedosato seems to be incompatible with driver MSAA so your comprasion between downsampling vs. native resolution has to be with MSAA set to disabled in your driver utility.

See even if people might think that stuff like 10k or 16k resolution is needless***, regardless, a lot of people on the internet still use it for screenshots in the very least. So if there is a way to get it to work it would be cool. Gedosato has some compatability flags in its .ini but I don't know which one could make it work with Silent Hill 2. To reiterate the game works fine, only crashes if you use the menu.

(Guessing my dx8 log file is not needed on this one)
(Btw elisha, you asked how I got SGSSAA working on the last thread, you gotta switch to dx8 and if you have an Nvidia card, use both 8x MSAA and 8x Sparse Grid Supersampling Anti Aliasing together, the latter can be selected on the transperancy antialising tab in Nvidia Profile Inspector) --> Addendum to this: Apperantly this was a false positive on my part, I accidentally enabled driver FXAA and confused it's blur with SGSSAA's usual slight amount of blur addition. I just thought transperancy antialiasing was possible because you guys say to enable it in your website for the mod.

.* _If you downsample from exactly 4x your monitors native resolution that is, and use lanczos scaling._
**  _This description is for the far away camera with the scene that has the protaganist's car door open, where he reads a letter from a certain someone._
*** _Although people who retort as such don't really know how to distinguish shimmering/crawling from edge aliasing and don't understand that downsampling and/or super sampling is employed to counteract temporal aliasing instead of the regular stair-step artifacting on edges._

**Comment by elishacloud** [comment]
Try setting this option to "Use DirectX" and see if this prevents the crash:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/a6ea22eb-08ec-43b9-88fe-820fc2826ef9)

**Comment by kaaona** [comment]
Yeah that was the first thing I tried, same situation. Game runs fine but crashes when you hit escape.

**Comment by elishacloud** [comment]
Ok, I will look in to this later and see if I can reproduce and fix this.  I am pretty sure it has to do with how I access the front buffer data and a size mismatch between the two.

**Comment by kaaona** [comment]
Did you also see the other issue I opened? About the flashlight lens flare effect lowering fps by a ton at 4k+ resolutions and that resulting a crash at the first location you find it in? If you are at 4k with a powerful GPU you might not see the FPS drop, so to see how resource intensive this effect is I suggest you monitor your gpu usage with something like RivaTuner, the usage should go up considerably when the lens effect of the flashlight triggers.

**Comment by elishacloud** [comment]
Yes, but I probably won't look into that one.  I am hoping someone else on the team can look into it first.

**Comment by kaaona** [comment]
Do I need to open that issue in one of their github pages, i am new to github I don't know how it works? Do they know about the issue?

**Comment by elishacloud** [comment]
> I got SGSSAA working on the last thread, you gotta switch to dx8 and if you have an Nvidia card, use both 8x MSAA and 8x Sparse Grid Supersampling Anti Aliasing together, the latter can be selected on the transperancy antialising tab in Nvidia Profile Inspector

I tried that and I am not seeing any crashes.  I tried with fullscreen and with windowed mode.  Using Direct3D8 and Direct3D9.  Are you sure it is not something with your computer?

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/d2d0c8ea-3d9c-45a9-ba73-de16e663253c)

**Comment by kaaona** [comment]
No, Elisha I had written that because in the previous issue thread you mentioned that you didn't know that SGSSAA could be enabled, you must have forgotten. Trying the enable SGSSAA did not cause a crash for me. Also didn't you read the addendum at the end of the paranthesis sentence? Apperantly I was mistaken, I don't think SGSSAA can be enabled even if you make these changes in the profile inspector.
