### ISSUE TITLE
Crashing at Flashlight Pick up

### ISSUE THREAD

**Issue by kaaona** [elishacloud/Silent-Hill-2-Enhancements#855]
The game consistently crashes when James moves toward the dress that holds the flashlight. I guess the camera angle is supposed to change there to show the dress? I used dx8 and tried it without the driver forced antialising, you know to try to see if that caused it, and in the 30 fps mode. I reverted a lot of changes in the settings to default tried it that way and it crashes regardless.

Edit: I think I know what was causing the crash. I approached the flashlight from the side and picked it up that way. The game didn't crash this way but whenever the camera moves and the lens flare effect shows up my fps goes down by almost 30. I think the lens flare effect that would show when you go straight at the mannequin was causing the crash. Does the lens flare effect scale with resolution? Because my monitor is 5k. I can't think of another reason a lens flare effect would tank fps this way.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12853848/d3d8.log)

Ahhh also I'm seeing the Konami or the Team Silent logo each time I go through a door. It's supposed to be a black screen right? Edit: I also sometimes see snapshots from other locations I have been in in game. They get retained and show up during door transitions just for a second.

**Comment by shlubabub** [comment]
i have the same problem except when i turn with the flashlight to the camera it crashes, not too sure what the problem is. perhaps a lag spike in fps causes it?

**Comment by shlubabub** [comment]
alright i found a work around for me, so after i picked up the flashlight i turned it off, and then went downstairs to save the game and then turned it on.
