### ISSUE TITLE
Music transition not smooth at the beginning 

### ISSUE THREAD

**Issue by Slemuolbymas** [elishacloud/Silent-Hill-2-Enhancements#856]
Hi,

At the beginning of the game when James leaves the restroom, I noticed the cutscene music doesn't start before the previous one stopped, or at least the first music is cut before the new one plays. I compared with the PS2 game on original hardware and the transition is smooth, which gives a more dreamy feel to the scene, as I think it was intented.

Other transitions in the game might have the same issue but I haven't played the whole thing so i can't confirm, but it's easy to spot at the very beginning of the game comparing the two versions.

Thank you for your hardwork !

**Comment by Polymega** [comment]
Hello,
Due to how music and its transitions were changed from PS2 -> Xbox, this is normal behavior as the PC is a port from the Xbox version.
