### ISSUE TITLE
Mouse Cursor not auto hiding when using controller 

### ISSUE THREAD

**Issue by ebench10** [elishacloud/Silent-Hill-2-Enhancements#857]
Hi there (amazing project BTW)!

Minor issue - I've read online that the mouse cursor should auto-hide (or not appear at all) when using a controller with SH 2 EE. I have a clean windows install and the game is running flawless other than the mouse getting in the way of the inventory as it tends to show up in the center of the screen. Any help would be appreciated! I have the most recent version and updates installed using the SH2EEsetup.exe . For what it is worth I am using a Hyperkin Duke Xbox One controller.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12876008/d3d8.log)

**Comment by Polymega** [comment]
Hello,

The mouse autohide feature hasn't released as part of our stable, public update for the project yet. Currently, it's only available in test builds which we don't recommend using until we've ironed out as any/all issues we can with new code.

This feature will release as part of our next, public update. So look forward to it!

**Comment by ebench10** [comment]
Thanks so much - I will look forward to future updates! You and your team are doing gods work
