### ISSUE TITLE
New feature: `BFaWAtticFix`

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#859]
The fixes mentioned below are proposed to all be consolidated into one, new `BFaWAttacFix` feature. Thank you!

--------------------

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/3457eb4f-e2e5-4e56-bd98-39b287cfaaef

To help fix this behavior:

`atticShadowCutoffPoint` (float)
Pointer for 1.0 (006AF044): 
`0x0049D8D0 (Offset: 0x00)`
Pointer for 1.1 (006B0024): 
`0x0049DB4D (Offset: 0x00)`
Pointer for DC (006AF024):
`0x0049D40D (Offset: 0x00)`

Add the following code: 

if in RoomID == `0xC7` (BFaW Attic) && [`InGameCameraPosY`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L42) == `-1450.0f`
set `atticShadowCutoffPoint` to `-10.0f`
else set `atticShadowCutoffPoint` to `10.0f`

**Comment by Polymega** [comment]
Please hold off a moment before implementing this feature. 

Aero_ is working on a solution to fix the candle flame animation in this room as it goes wicked fast at 60 FPS. Depending on how he approaches the solution, it might be either implemented as part of this fix or integrated as part of the 60 FPS feature.

It's advised to wait until he's finished his work and go from there. Thanks!

**Comment by AeroWidescreen** [comment]
@elishacloud 
The following information is an addition to Polymega's original post.

## Attic Candle Speed

```
float CandleFPS = 20.0f;
float CandleFPSResult;
```

```
0x004D041A call CandleFlameSpeedHook

CandleFlameSpeedHook:
cmp dword ptr ds : [esi + 0x1C], 0x42C80000 // 100.0f : Loop limit
jl CandleFlameSpeedMath
mov dword ptr ds : [esi + 0x1C], 0x00000000 // 0.0f: Resets value to zero for infinite looping
jmp CandleFlameSpeedHook

CandleFlameSpeedHookMath:
fld dword ptr ds : [0x00932D48] // Frametime
fmul dword ptr ds : [CandleFPS] // Candle FPS
fstp dword ptr ds : [CandleFPSResult] // Result
fld dword ptr ds : [esi + 0x1C]
fadd dword ptr ds :  [CandleFPSResult]
fstp dword ptr ds : [esi + 0x1C]
fld dword ptr ds : [esi + 0x1C]
fistp dword ptr ds : [esi + 0x20]
mov eax, dword ptr ds : [esi + 0x20]
ret
```
```
004D0438:
nop
nop
nop

004D043D:
nop
nop
nop
nop
nop
nop

004D0444:
nop
nop
nop
```

Frametime Pointer for 1.0 (00932D48): 
`0x0044787D (Offset: 0x00)`
Frametime Pointer for 1.1 and DC (00936948):
`0x00447990 (Offset: 0x00)`

## Attic Candle Opacity

```
0x004D017D call CandleFlameOpacityHook
0x004D0182 nop
```
```
fadd dword ptr ds :  [ecx + 0x08]
mov eax, 0x432F0000 // 175.0f : Candle Opacity
ret
```

**Comment by Polymega** [comment]
Thank you, Aero_! @elishacloud this is now good to be implemented at your convenience.

Thanks gentlemen

**Comment by elishacloud** [comment]
Thanks @Polymega and @AeroWidescreen!  I will take a look at this once I finish trying to add new sounds effects to the game.

**Comment by robertesaum** [comment]
I noticed a similar problem in Heaven's Night, when I played Born From a Wish.

![Screenshot 2023-12-20 14-33-36](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/147220372/4199e9b0-f531-461e-989b-22ef417d58f6)
![Screenshot 2023-12-20 14-33-39](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/147220372/18fbc9f6-0b95-48e3-a635-02728f0eb169)

**Comment by elishacloud** [comment]
I think I implemented everything ok for this.  Let me know if this is correct:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14553354/d3d8.zip)

**Comment by elishacloud** [comment]
Um, ok try this one:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14561824/d3d8.zip)

**Comment by Polymega** [comment]
Thanks, Elisha. 

**1.0:** It's good/stable/everything is working.
**1.1:** It crashes to desktop upon lighting the candle.
**DC:** The shadow part of the fix is working but the ASM to fix the candle speed/opacity isn't working.

**Comment by elishacloud** [comment]
Thanks @Polymega.  Yeah, I hard coded the addresses for 1.0.  Will update this to work on 1.1 and DC.

**Comment by elishacloud** [comment]
@AeroWidescreen, the code in the DC version for CandleFlameSpeedHook and CandleFlameOpacityHook is very different from the code in 1.0.  It seems like your asm code won't work on the DC version of the binary.

**Comment by elishacloud** [comment]
I added checks and addresses for all binaries.  This update should work with v1.0 and v1.1.  DC won't work yet, but at least won't crash.  Will need to wait for @AeroWidescreen to check out DC before that can be fixed.

Here is the update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14565712/d3d8.zip)

**Comment by AeroWidescreen** [comment]
@elishacloud
The only problem I've found was with the Frametime memory address. I thought v1.1 and DC used the same address, but they don't. Everything else should fine, tested and confirmed with Cheat Engine.

The other issue here is that I didn't provide ASM addresses for v1.1 and DC; I only did it for the Frametime pointer, so I apologize for that. Here's the exact same ASM code but with _DC memory addresses_:


```
0x004CFF8A call CandleFlameSpeedHook

CandleFlameSpeedHook:
cmp dword ptr ds : [esi + 0x1C], 0x42C80000 // 100.0f : Loop limit
jl CandleFlameSpeedMath
mov dword ptr ds : [esi + 0x1C], 0x00000000 // 0.0f: Resets value to zero for infinite looping
jmp CandleFlameSpeedHook

CandleFlameSpeedMath:
fld dword ptr ds : [0x00935948] // Frametime
fmul dword ptr ds : [CandleFPS] // Candle FPS
fstp dword ptr ds : [CandleFPSResult] // Result
fld dword ptr ds : [esi + 0x1C]
fadd dword ptr ds :  [CandleFPSResult]
fstp dword ptr ds : [esi + 0x1C]
fld dword ptr ds : [esi + 0x1C]
fistp dword ptr ds : [esi + 0x20]
mov eax, dword ptr ds : [esi + 0x20]
ret
```



```
004CFFA8:
nop
nop
nop

004CFFAD:
nop
nop
nop
nop
nop
nop

004CFFB4:
nop
nop
nop
```

**Comment by elishacloud** [comment]
> The other issue here is that I didn't provide ASM addresses for v1.1 and DC; I only did it for the Frametime pointer, so I apologize for that.

No problem.  I was able to find this one.  It was the other addresses I was having trouble with for some reason.  I think I got it now.

@Polymega, this one should work on all binaries:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14578938/d3d8.zip)

**Comment by Polymega** [comment]
Thank you, Elisha, Could you reattach the build? The one you shared is a broken link.

**Comment by elishacloud** [comment]
That is weird.  I have never seen GitHub have a broken link like that.  Here it is: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14579623/d3d8.zip)

**Comment by Polymega** [comment]
Huh, your new link is also broken. GitHub must be having some issues at the moment.

**Comment by Polymega** [comment]
Tested on all binaries and working great! Thanks for handling this, Elisha, and thank you again Aero_ for your research and initial work to make this happen.
