### ISSUE TITLE
`ImproveStorageSupport` causes crash (mostly if <1GB of space is free)

### ISSUE THREAD

**Issue by makamys** [elishacloud/Silent-Hill-2-Enhancements#864]
I got a consistent crash on the save screen when selecting a new file. This only happened when `ImproveStorageSupport` was enabled. Both the latest release (v2.1.2070.0) and CI build (8d6a81e) had the issue.

With the help of x32dbg I determined that the crash happened on this line:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/8d6a81e7832f8eb5979aac80a3bd69771be6ab01/Patches/2TBHardDriveFix.cpp#L240

The issue appears to be that the buffer being allocated is too small, [only 12 characters large](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/8d6a81e7832f8eb5979aac80a3bd69771be6ab01/Patches/2TBHardDriveFix.cpp#L29). In my case the string being constructed was `\h335.980469 MB` (15 characters), which is too large to fit. After freeing up some disk space so there's `1.2 GB` free, the crash went away, further suggesting the string length to be the issue.

Above 1 GB, the fractional part of the number is truncated to up to 2 digits, making the issue only likely to be encountered if less than 1 GB of space is free.

**Comment by elishacloud** [comment]
Good catch.  Thanks for troubleshooting this.  I don't have a system to test this, at the moment.  Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13326367/d3d8.zip)

**Comment by makamys** [comment]
Seems to be fixed now, nice. Tested with >1GB free too.

![](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/13667520/806d1efb-bfd5-464d-ab6a-09af4b84eb98)

**Comment by elishacloud** [comment]
Thanks for checking @makamys!
