### ISSUE TITLE
Can't loot anything

### ISSUE THREAD

**Issue by 91I** [elishacloud/Silent-Hill-2-Enhancements#866]
After opening the brookhaven hospital room that has a shotgun and a teddybear i can't interact with the teddybear and can't pick up any type of loot. tried reinstaling the game 3 times and download the base game from other sites, still the same problem, i tried going in a previous save and made it to the same place, the same problem occurred.

**Comment by Polymega** [comment]
Please update our project files to the latest versions. Does the issue then still persist?

Closing ticket. Feel free to re-open if you'd like further assistance.
