### ISSUE TITLE
Otherworld Brookhaven staircase map inconsistency

### ISSUE THREAD

**Issue by matheusvb3** [elishacloud/Silent-Hill-2-Enhancements#873]
In Brookhaven hospital you have access to four maps:

1. A plant of the 2nd and 3rd floors as well as the rooftop
2. A plant of the 1st floor and the basement
3. A plant of the 2nd and 3rd floors as well as the rooftop (_Otherworld_)
4. A plant of the 1st floor and the basement (_Otherworld_)

When you enter the staircase that leads to the Pyramid Head chase in the alternate version of the hospital, the map correctly shows your position in the Otherworld version of the map, 3rd or 2nd floor depending on where you are standing (map no. 3 in the list I made above).

![Captura de tela de 2023-11-25 00-25-04](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/d73bb03c-15b6-4e2d-ba12-a88b9ceb5ffb)

Logically, when you get to the first floor the map should show your position in the Otherworld 1st floor (map no. 4). I marked in green where you should appear. Notice there's a broken door mark there in the map, next to the elevator, and a save point.

![Captura de tela de 2023-11-25 00-25-15](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/12f8d8c6-4e3d-4903-a114-b91b3f457f07)

When you open the map in that spot though, you appear in the "fog world" version of the 1st floor.

![Captura de tela de 2023-11-25 00-26-21](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/ca55382f-6bda-4094-b42b-aa95ea28a08c)

Also, even if you interact with that door right there, it will not get marked on the map, because James isn't in the fog world version of the hospital anymore.

As an addendum, imagine if the developers had made it so that door was locked from the side of the staircase, allowing you to the 1st floor patient wing hall and save in that corridor that leads to the garden before you go to the basement? Oh it would've made the chase on hard action so much more tolerable...

---

By the way, please forgive me for being a nosy sonuva but I was checking out the code for the project and here's a little something I noticed. This code is from the file [Patches/LightingPatch.cpp](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/c6c16d3d5032fd923535eb3a3cbebb4c4f836578/Patches/LightingPatch.cpp#L121) (line 121, as marked in the URL):

`if (CurrentRoomID == 0x08 /*Town West*/ || CurrentRoomID == 0xD3 /*Mansion outside main entrance*/)`

I see two ways that the readability here could be improved and possibly even the maintainability of the codebase as a whole. The first is simpler but less flexible and involves attributing these conditional statements to #defines, thus allowing you to assign names to these conditions and avoiding having to comment the name of the maps the IDs correspond to or keeping an external spreadsheet of IDs. This line, for example, could become:

`if (MAP_TOWN_WEST || MAP_MANSION_OUTSIDE_MAIN_ENTRANCE)`

Of course this would scale very poorly as more and more "RoomId ==" conditionals are created and it's a very hacky thing to do. The second would be to create an enumeration of room IDs in Patches/Common.cpp and alter the return type of the GetRoomID function to be of that enum, then perform a cast before returning. Let's say this is the enum we created:

```
enum RoomIDs {
FOO = 0x00,
BAR = 0x01,
BAZ = 0x02,
BIZ = 0x03,
TOWN_WEST = 0x08,
MANSION_OUTSIDE_MAIN_ENTRANCE = 0xD3
};
```

After altering GetRoomID to be of type enum RoomIDs and performing a cast to that type in [line 160](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L160C1-L160C1), you could then do so in LightingPatch.cpp:

`if (CurrentRoomID == TOWN_WEST|| CurrentRoomID == MANSION_OUTSIDE_MAIN_ENTRANCE)`

It becomes much easier to maintain an enum of all room IDs in the game and use their names in the code rather than their IDs. From a quick glance it appears there are a few other function that could similarly be altered, for example GetCutsceneID (would require an enum of all cutscenes in the game) and GetChapterID (a simple two-entry enum for LFSH and BFAW). However, I'm not really sure if that cast would be possible to perform, though I imagine so since `*pRoomID` is a pointer (`void*`). I'd love to see your thoughts on this.

**Comment by Polymega** [comment]
Oh wow! That's interesting about the map. I probably would've never noticed that before. I'll jot that down but I'm not sure if/when it'd be looked into.

Thanks, matheusvb3!

**Comment by Polymega** [comment]
> @Polymega, by any chance, do you have a spreadsheet of IDs for things like rooms, cutscenes, items etc? I imagine there must be one otherwise it'd be nearly impossible to maintain the codebase up to this point without memorizing the IDs.

One hasn't been made but it's something I can do in the future.

**Comment by matheusvb3** [comment]
> One hasn't been made but it's something I can do in the future.

All right, I can make a Google Docs spreadsheet using Mercury's debug overlay if you want. I think I'll start right now, even.

**Comment by matheusvb3** [comment]
Nice, I sent you a request to edit it. My e-mail is matheus.venturini@acad.ufsm.br

**Comment by Polymega** [comment]
Done! I just finished the hospital and am calling it a night there. Within the document there's two tabs for Room and Cutscene IDs. Feel free to add on and thanks!

**Comment by matheusvb3** [comment]
Polymega, my land internet went out because of course it did. I stopped right when the Pyramid Heads die, I didn't even get to annotate the ID for that hallway you must open with the rust and scarlet eggs. While I waited for my internet to return (it didn't) I annotated the IDs for BFaW, you can see them in the attached file.
[BFAW.ods](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13509171/BFAW.ods)

**Comment by elishacloud** [comment]
Thanks!  It seems I don't have access to view it.

**Comment by Polymega** [comment]
Sorry about that. I just now gave you access and will make it global to view.

**Comment by elishacloud** [comment]
Thanks, that works.

**Comment by matheusvb3** [comment]
> Matheus and I have compiled hex numbers for all cutscene and room IDs throughout the game

That was interesting. What do you say we do items as well?

**Comment by elishacloud** [comment]
I noticed that on the spreadsheet for the RoomIDs 0xC9 and 0xD2 has the same name: `MAN_S_STAIRCASE`

However, there is no way to distinguish them if they have the same name.

**Comment by Polymega** [comment]
Sorry, that's an oversight by me.

0xC9 = MAN_S_HALL_STAIRCASE
0xD2 = MAN_S_STAIRCASE
