### ISSUE TITLE
Trying to figure out if the textures are correct for SH2:EE

### ISSUE THREAD

**Issue by Nessu4K** [elishacloud/Silent-Hill-2-Enhancements#875]
So I installed this game a year ago and played through it. Since then it seems like it has gotten a slew of updates. I had it backed up (previously played on my gaming laptop) and dumped it on my PC. I just want to make sure it installed correctly. I just got the setup tool, threw it in the base folder and ran it. There was no update packages option (probably because it was never installed on this PC) so I just ran install. There were no problems with it and runs fine, even has my old saves. But I'm questioning some of the textures, I don't remember some of them being so muddy. I have a screenshot of an example of the water with Pyramid Head fight. Is this what it's supposed to look like? And if it's supposed to look like that, I guess there's no problems then. I just need to know there wasn't a weird problem bringing the "already installed" old version from my backup over to my PC and re-installing it.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13476514/d3d8.log)
![Untitled](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/152191189/4537a187-65d1-4aba-822f-c86366c923f4)

**Comment by Polymega** [comment]
Hi there,

Everything looks fine/correct in that image. The texture resolutions are quite low (but good for 2001's standards) for much of the game. It sounds like everything updated/installed without issue for you. Enjoy!
