### ISSUE TITLE
Black Screen and/or Crashing When Launching

### ISSUE THREAD

**Issue by cybrg1rl** [elishacloud/Silent-Hill-2-Enhancements#876]
Hi everyone! I recently decided to play Silent Hill 2 for myself, and figured out all the steps of downloading the enhanced edition. I downloaded the FULLY extracted edition from myabandonware, put the enhanced edition setup into the same extracted folder, and ran the setup. Everything went smoothly, but when I try to open the game, it launches full screen (despite being windowed in configuration tool), and is just on a black screen. No intro/intro music, no menu, not even a mouse cursor. Pressing ESC will just close it. Sometimes it will even just say "not responding" and crash. I tried to move it from my C: drive to my documents folder like I've seen others do on reddit, but I get the same issue. Can anyone help? Thanks

Note: I play on an ASUS Zenbook 13 OLED, and other games work fine on it.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13494755/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

It looks like your SH2 PC is in a different folder than the SH2:EE project files:

```
15352 19:20:34.863 |- 11/26/2023  08:30 PM    <DIR>          sh2e
15352 19:20:34.863 |- 11/26/2023  08:31 PM    <DIR>          Silent Hill 2
15352 19:20:34.863 |- 11/01/2020  03:23 PM               237 alsoft.ini
15352 19:20:34.863 |- 06/25/2002  09:50 AM           358,963 binkw32.dll
15352 19:20:34.864 |- 11/26/2023  08:25 PM                24 cin.dat
15352 19:20:34.864 |- 11/28/2023  07:18 PM             2,081 d3d8.dat
15352 19:20:34.864 |- 11/28/2023  07:20 PM        10,786,816 d3d8.dll
15352 19:20:34.864 |- 11/28/2023  07:20 PM            24,373 d3d8.ini
15352 19:20:34.864 |- 11/28/2023  07:20 PM                   d3d8.log
15352 19:20:34.864 |- 09/26/2002  06:19 PM            12,332 device.fix
15352 19:20:34.864 |- 03/15/2023  02:37 PM           490,496 dinput8.dll
15352 19:20:34.864 |- 06/27/2022  05:43 PM           856,064 dsoal-aldrv.dll
15352 19:20:34.864 |- 06/27/2022  05:43 PM           143,360 dsound.dll
15352 19:20:34.864 |- 03/15/2023  02:37 PM               504 keyconf.dat
15352 19:20:34.864 |- 08/25/2019  08:02 PM                37 local.fix
15352 19:20:34.864 |- 01/05/2002  12:40 PM           487,424 msvcp70.dll
15352 19:20:34.864 |- 06/07/2001  12:14 PM           339,968 msvcr70.dll
15352 19:20:34.864 |- 11/28/2023  07:17 PM                27 settings.ini
15352 19:20:34.864 |- 07/21/2022  02:51 PM           224,254 sh2.ico
15352 19:20:34.864 |- 04/04/2023  10:36 AM         1,080,832 SH2EEconfig.exe
15352 19:20:34.864 |- 11/26/2023  08:24 PM               284 SH2EEsetup.dat
15352 19:20:34.864 |- 11/26/2023  07:55 PM         3,844,243 SH2EEsetup.exe
15352 19:20:34.864 |- 11/30/2017  06:22 PM         5,459,968 sh2pc.exe
15352 19:20:34.864 |- 03/15/2023  02:12 PM               412 Xidi.ini
```

I'm going to guess/assume that the vanilla SH2 PC game is located in that `Silent Hill 2` folder? If you click into that folder, do you see a folder called `data`, along with other files? If so, _move all of the files/folders_ from that `Silent Hill 2` folder _back_ on directory (into your `Silent-Hill-2-Restless-Dreams_Win_EN_Fully-Extracted-Version` folder).

**Comment by Polymega** [comment]
Great! Enjoy the game!
