### ISSUE TITLE
Addendum to `Room312ShadowFix` (Part 2)

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#877]
@mercury501 @elishacloud 

This is an addendum request to the [`Room312ShadowFix`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Room312Shadow.cpp) feature. While in Room 312, _before_ you use the VHS tape, when attempting to toggle the flashlight, its light will momentarily flicker which bugs out the post-processing effects in this room (the bloom on the windows):

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/28b39c94-2509-4f76-a43f-27508257e0f3

_After_ you view the VHS, this no longer happens. When we added a flashlight toggle SFX into the game, we had to include code to know whether or not the VHS is in your inventory, so I believe all the heavy lifting is done. ([See here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/c6c16d3d5032fd923535eb3a3cbebb4c4f836578#diff-9da3d7005ff4bec5145d95e52d32c08bd5b22670ee27df315542ef797221819cR190))

The request is the following:

```c++
if in RoomID == 0xA2 && InventoryItem >= 0x80 /*VHSTape IS in player's inventory*/ {
   Disable the use of the flashlight input
}
```

@mercury501 I tagged you because you have disabled the use of numerous inputs (on both keyboard/controller) in the past for various features you've implemented. May I ask for your help with this?

**Comment by Polymega** [comment]
@elishacloud 
I just realized in that video I recorded [that this](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/c6c16d3d5032fd923535eb3a3cbebb4c4f836578#diff-9da3d7005ff4bec5145d95e52d32c08bd5b22670ee27df315542ef797221819cR190) code isn't working correctly again in the latest build. I can hear the toggle noise while still having the VHS in my inventory.

**Comment by elishacloud** [comment]
> I just realized in that video I recorded [that this](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/c6c16d3d5032fd923535eb3a3cbebb4c4f836578#diff-9da3d7005ff4bec5145d95e52d32c08bd5b22670ee27df315542ef797221819cR190) code isn't working correctly again in the latest build. I can hear the toggle noise while still having the VHS in my inventory.

Ok, I believe I fixed this issue with the latest check-in.

**Comment by mercury501** [comment]
Ok so if I understand it correctly, we need to detect when james is in room 312 and has the vhs in his inventory, and inhibit the toggle flashlight key right?

**Comment by Polymega** [comment]
Thanks, Mercury! Looks to be working great for keyboard, but not working for controller.

**Comment by mercury501** [comment]
oh right, keys and buttons are treated differently, i'll get back to you on that

**Comment by mercury501** [comment]
Great, I'll pr now!
