### ISSUE TITLE
Installer Won't Launch "The parameter is incorrect."

### ISSUE THREAD

**Issue by Nubzombie** [elishacloud/Silent-Hill-2-Enhancements#882]
Just downloaded installer v. 1.1.3.0 and when trying to launch the installer, I get an error showing the directory of the installer (my downloads folder) and the message "The parameter is incorrect."

Launcher fails to open entirely. SH2 PC is already installed and working on my PC. 

I've played/streamed SH2 EE many times in the past and have had no issues with installation previously - this is a newer PC and my first time running on Windows 11 so not sure if that is related to the issue.

**Comment by Nubzombie** [comment]
Sorry, I mean the SH2EEsetup Web Installer. 
Windows 11 is not blocking it, and attempting to launch it immediately just pops up the error message "the parameter is incorrect."

**Comment by Polymega** [comment]
Before running this, have you already placed the core SH2 PC files somewhere on your PC? If so, are they placed in an external hard drive?

**Comment by Nubzombie** [comment]
Yes, SH2 PC is installed and the core files are on my main M.2 drive, and the game launches/works correctly.

**Comment by Polymega** [comment]
We'll have to investigate this some more. But in the meantime, you can manually download the files here. Once downloaded, move the contents into the main SH2 PC folder.

**Just note** that by manually downloading, the project won't know you've already installed the packages if/when you get the installer working. So when you run the installer down the line, it'll act like a new/fresh installation in which you'll have to re-download everything.

name | version | url
-- | -- | --
SH2:EE Setup Tool | 1.1.3 | https://files.townofsilenthill.com/SH2EE/SH2EEsetup.exe
SH2 Enhancements Module | 2.1.2070.0 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhancements_Module_2.1.2070.0.zip
Enhanced Executable | 1 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip
Enhanced Edition Essential Files | 1.2.5 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.5.zip
Image Enhancement Pack | 1.1.2 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.2.zip
FMV Enhancement Pack | 1.5.4b | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.4b.zip
Audio Enhancement Pack | 2.0.5 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.0.5.zip
DSOAL | D.0.9.2.O.1.22.2 | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_0.9.2_OpenALSoft_1.22.2.zip
Xidi | 4.1.1b | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Xidi_4.1.1b.zip
Credits | 1.5.4b | https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Credits_1.5.4b.zip

**Comment by Nubzombie** [comment]
Thank you for that - manually adding everything to the directory worked for me as a workaround.
