### ISSUE TITLE
Launching game

### ISSUE THREAD

**Issue by falloutdeadshot1** [elishacloud/Silent-Hill-2-Enhancements#883]
At first i had the game installed on a SSD which i found out wont let you run it so i have installed it on a 32 gb usb stick as i dont have a HDD. When i load up the game it just black screens.

**Comment by falloutdeadshot1** [comment]
26968 17:47:54.882 Starting Silent Hill 2 Enhancements! v2.1.2070.0
26968 17:47:54.882 Game binary version: v1.0
26968 17:47:54.882 Disabling High DPI Scaling...
26968 17:47:54.882 Setting GUI theme...
26968 17:47:54.883 Setting theme properties...
26968 17:47:54.883 Hooking the CreateProcess APIs...
26968 17:47:54.883 Setting delayed startup...
26968 17:47:54.887 Gigabyte Technology Co., Ltd. B560 AORUS PRO AX -CF (Desktop)
26968 17:47:54.887 Gigabyte Technology Co., Ltd. B560 AORUS PRO AX x.x (Desktop)
26968 17:47:54.888 Windows 7 Ultimate 64-bit (10.0.19041)
26968 17:47:54.888 sh2pc.exe (PID:4532)
26968 17:47:54.888 Checking for Compatibility Settings!
26968 17:47:54.888 Environment variable __COMPAT_LAYER = "Win7RTM DetectorsAppHealth DetectorsXP"
26968 17:47:54.889 Checking if administrator access is required.
26968 17:47:54.889 Detected relaunch with administrator rights!
26968 17:47:54.903 Running from: G:\SH\sh2pc.exe
26968 17:47:54.903 Config file: G:\SH\d3d8.ini
26968 17:47:54.903 |----------- SETTINGS -----------
26968 17:47:54.904 |- AdjustColorTemp: 1
26968 17:47:54.904 |- AudioClipDetection: 1
26968 17:47:54.904 |- AutoUpdateModule: 1
26968 17:47:54.904 |- CatacombsMeatRoomFix: 1
26968 17:47:54.904 |- ChangeClosetSpawn: 1
26968 17:47:54.904 |- CheckCompatibilityMode: 1
26968 17:47:54.904 |- CheckForAdminAccess: 1
26968 17:47:54.904 |- ClosetCutsceneFix: 1
26968 17:47:54.904 |- CommandWindowMouseFix: 1
26968 17:47:54.904 |- CreateLocalFix: 1
26968 17:47:54.904 |- d3d8to9: 1
26968 17:47:54.904 |- DelayedFadeIn: 1
26968 17:47:54.904 |- DisableCutsceneBorders: 1
26968 17:47:54.904 |- DisableEnlargedText: 1
26968 17:47:54.904 |- DisableGameUX: 1
26968 17:47:54.904 |- DisableHighDPIScaling: 1
26968 17:47:54.904 |- DisableLogging: 0
26968 17:47:54.904 |- DisableRedCross: 0
26968 17:47:54.904 |- DisableRedCrossInCutScenes: 1
26968 17:47:54.904 |- DisableSafeMode: 1
26968 17:47:54.904 |- DisableScreenSaver: 1
26968 17:47:54.904 |- DynamicResolution: 1
26968 17:47:54.904 |- EnableDebugOverlay: 1
26968 17:47:54.904 |- EnableEnhancedMouse: 1
26968 17:47:54.904 |- EnableInfoOverlay: 1
26968 17:47:54.904 |- EnableMenuTest: 0
26968 17:47:54.904 |- EnableMenuTestIGT: 1
26968 17:47:54.904 |- EnableMouseWheelSwap: 1
26968 17:47:54.904 |- EnableScreenshots: 1
26968 17:47:54.904 |- EnableSFXAddrHack: 1
26968 17:47:54.904 |- EnableSMAA: 0
26968 17:47:54.904 |- EnableSoftShadows: 1
26968 17:47:54.904 |- EnableTexAddrHack: 1
26968 17:47:54.904 |- EnableToggleSprint: 1
26968 17:47:54.904 |- FastTransitions: 1
26968 17:47:54.904 |- Fix2D: 1
26968 17:47:54.904 |- FixAdvancedOptions: 1
26968 17:47:54.904 |- FixAptClockFlashlight: 1
26968 17:47:54.904 |- FixChainsawSpawn: 1
26968 17:47:54.904 |- FixCreatureVehicleSpawn: 1
26968 17:47:54.904 |- FixDrawingTextLine: 1
26968 17:47:54.904 |- FixFMVResetIssue: 1
26968 17:47:54.904 |- FixFMVSpeed: 1
26968 17:47:54.904 |- FixGPUAntiAliasing: 1
26968 17:47:54.904 |- FixHangOnEsc: 1
26968 17:47:54.904 |- FixInventoryBGM: 1
26968 17:47:54.904 |- FixMemoFading: 1
26968 17:47:54.904 |- FixMissingWallChunks: 1
26968 17:47:54.904 |- FixSaveBGImage: 1
26968 17:47:54.904 |- FixTownWestGateEvent: 1
26968 17:47:54.904 |- FlashlightFlickerFix: 1
26968 17:47:54.904 |- FmvSubtitlesNoiseFix: 1
26968 17:47:54.904 |- FogParameterFix: 1
26968 17:47:54.904 |- FogSpeedFix: 1
26968 17:47:54.904 |- ForceTopMost: 0
26968 17:47:54.904 |- GameLoadFix: 1
26968 17:47:54.904 |- GamepadControlsFix: 1
26968 17:47:54.904 |- HalogenLightFix: 1
26968 17:47:54.904 |- HookDirect3D: 1
26968 17:47:54.904 |- HookDirectInput: 1
26968 17:47:54.904 |- HookDirectSound: 1
26968 17:47:54.904 |- HookWndProc: 1
26968 17:47:54.904 |- HospitalChaseFix: 1
26968 17:47:54.904 |- HotelWaterFix: 1
26968 17:47:54.904 |- ImproveStorageSupport: 1
26968 17:47:54.904 |- IncreaseBlood: 1
26968 17:47:54.904 |- IncreaseDrawDistance: 1
26968 17:47:54.904 |- LightingFix: 1
26968 17:47:54.904 |- LightingTransitionFix: 1
26968 17:47:54.904 |- LoadD3d8FromScriptsFolder: 0
26968 17:47:54.904 |- LoadFromScriptsOnly: 0
26968 17:47:54.904 |- LoadModulesFromMemory: 0
26968 17:47:54.904 |- LoadPlugins: 0
26968 17:47:54.904 |- LockResolution: 1
26968 17:47:54.904 |- LockScreenPosition: 1
26968 17:47:54.904 |- LockSpeakerConfig: 1
26968 17:47:54.904 |- MainMenuFix: 1
26968 17:47:54.904 |- MainMenuTitlePerLang: 1
26968 17:47:54.904 |- MemoScreenFix: 1
26968 17:47:54.904 |- NoCDPatch: 1
26968 17:47:54.904 |- PauseScreenFix: 1
26968 17:47:54.904 |- PistonRoomFix: 1
26968 17:47:54.904 |- PS2CameraSpeed: 1
26968 17:47:54.904 |- PS2FlashlightBrightness: 1
26968 17:47:54.904 |- PS2StyleNoiseFilter: 1
26968 17:47:54.904 |- QuickSaveTweaks: 1
26968 17:47:54.904 |- ReduceCutsceneFOV: 1
26968 17:47:54.904 |- RemoveEffectsFlicker: 1
26968 17:47:54.904 |- RemoveEnvironmentFlicker: 1
26968 17:47:54.904 |- RestoreAlternateStomp: 1
26968 17:47:54.904 |- RestoreBrightnessSelector: 1
26968 17:47:54.904 |- RestoreSpecialFX: 1
26968 17:47:54.904 |- RestoreVibration: 1
26968 17:47:54.904 |- Room312ShadowFix: 1
26968 17:47:54.904 |- RoomLightingFix: 1
26968 17:47:54.904 |- RowboatAnimationFix: 1
26968 17:47:54.904 |- SaveGameSoundFix: 1
26968 17:47:54.904 |- SetBlackPillarBoxes: 1
26968 17:47:54.904 |- SetSixtyFPS: 1
26968 17:47:54.904 |- Southpaw: 0
26968 17:47:54.904 |- SpecificSoundLoopFix: 1
26968 17:47:54.904 |- SpecularFix: 1
26968 17:47:54.904 |- SteamCrashFix: 1
26968 17:47:54.904 |- UnlockJapLang: 1
26968 17:47:54.904 |- UseBestGraphics: 1
26968 17:47:54.904 |- UseCustomExeStr: 1
26968 17:47:54.904 |- UseCustomFonts: 1
26968 17:47:54.904 |- UseCustomModFolder: 1
26968 17:47:54.904 |- UsePS2LowResTextures: 0
26968 17:47:54.904 |- WhiteShaderFix: 1
26968 17:47:54.904 |- WidescreenFix: 1
26968 17:47:54.904 |- WndModeBorder: 1
26968 17:47:54.904 |- WoodsideRoom205Fix: 1
26968 17:47:54.904 |- AnisotropicFiltering: 0
26968 17:47:54.904 |- AntiAliasing: 0
26968 17:47:54.904 |- AudioFadeOutDelayMS: 10
26968 17:47:54.904 |- CRTShader: 0
26968 17:47:54.904 |- CustomFontCharHeight: 32
26968 17:47:54.904 |- CustomFontCharWidth: 20
26968 17:47:54.904 |- CustomFontCol: 25
26968 17:47:54.904 |- CustomFontRow: 17
26968 17:47:54.904 |- DPadMovementFix: 1
26968 17:47:54.904 |- EnableCriWareReimplementation: 1
26968 17:47:54.904 |- fog_transparency_layer1: 128
26968 17:47:54.904 |- fog_transparency_layer2: 112
26968 17:47:54.904 |- FogFix: 1
26968 17:47:54.904 |- FogLayerFix: 1
26968 17:47:54.904 |- FrontBufferControl: 0
26968 17:47:54.904 |- FullscreenImages: 3
26968 17:47:54.904 |- FullscreenVideos: 3
26968 17:47:54.904 |- IncreaseNoiseEffectRes: 768
26968 17:47:54.904 |- LetterSpacing: 2
26968 17:47:54.904 |- NormalFontHeight: 30
26968 17:47:54.904 |- NormalFontWidth: 20
26968 17:47:54.904 |- PadNumber: 0
26968 17:47:54.904 |- RemoveForceFeedbackFilter: 1
26968 17:47:54.904 |- RestoreSearchCamMovement: 2
26968 17:47:54.904 |- ResX: 0
26968 17:47:54.904 |- ResY: 0
26968 17:47:54.904 |- ScreenMode: 2
26968 17:47:54.904 |- SingleCoreAffinityLegacy: 0
26968 17:47:54.904 |- SmallFontHeight: 24
26968 17:47:54.904 |- SmallFontWidth: 16
26968 17:47:54.904 |- SpaceSize: 7
26968 17:47:54.904 |- fog_layer1_x1: 0.25
26968 17:47:54.904 |- fog_layer1_x2: 0.25
26968 17:47:54.904 |- fog_layer1_y1: 0.125
26968 17:47:54.904 |- fog_layer1_y2: 0.125
26968 17:47:54.904 |- fog_layer2_complexity: 0.055
26968 17:47:54.904 |- fog_layer2_density_add: 100
26968 17:47:54.904 |- fog_layer2_density_mult: 1.4
26968 17:47:54.904 |- CustomModFolder: 
26968 17:47:54.904 |- WrapperType: 
26968 17:47:54.904 |- AutoScaleImages: 1
26968 17:47:54.904 |- AutoScaleVideos: 1
26968 17:47:54.904 |- EnableCustomShaders: 1
26968 17:47:54.904 |--------------------------------
26968 17:47:54.904 |- 
26968 17:47:54.904 |-  Directory of G:\SH
26968 17:47:54.904 |- 
26968 17:47:54.916 |- 12/14/2023  05:06 PM    <DIR>          sh2e
26968 17:47:54.916 |- 11/01/2020  03:23 PM               237 alsoft.ini
26968 17:47:54.916 |- 06/25/2002  10:50 AM           358,963 binkw32.dll
26968 17:47:54.916 |- 12/14/2023  05:07 PM                24 cin.dat
26968 17:47:54.916 |- 04/04/2023  10:39 AM        10,786,816 d3d8.dll
26968 17:47:54.916 |- 12/14/2023  05:47 PM            24,373 d3d8.ini
26968 17:47:54.916 |- 12/14/2023  05:47 PM                69 d3d8.log
26968 17:47:54.916 |- 09/26/2002  06:19 PM            12,332 device.fix
26968 17:47:54.917 |- 03/15/2023  02:37 PM           490,496 dinput8.dll
26968 17:47:54.917 |- 06/27/2022  05:43 PM           856,064 dsoal-aldrv.dll
26968 17:47:54.917 |- 06/27/2022  05:43 PM           143,360 dsound.dll
26968 17:47:54.917 |- 09/19/2021  04:09 PM                38 engineer.cfg.txt
26968 17:47:54.917 |- 03/15/2023  02:37 PM               504 keyconf.dat
26968 17:47:54.917 |- 07/25/2002  12:02 PM                77 Konami Homepage.url
26968 17:47:54.917 |- 08/25/2019  08:02 PM                37 local.fix
26968 17:47:54.917 |- 07/08/2021  09:58 PM               147 movie rating.txt
26968 17:47:54.917 |- 01/05/2002  12:40 PM           487,424 msvcp70.dll
26968 17:47:54.917 |- 06/07/2001  01:14 PM           339,968 msvcr70.dll
26968 17:47:54.917 |- 10/01/2002  03:33 PM            35,574 Readme.htm
26968 17:47:54.917 |- 10/01/2002  03:33 PM            16,083 Readme.txt
26968 17:47:54.917 |- 07/21/2022  02:51 PM           224,254 sh2.ico
26968 17:47:54.917 |- 04/04/2023  10:36 AM         1,080,832 SH2EEconfig.exe
26968 17:47:54.917 |- 12/14/2023  05:06 PM               284 SH2EEsetup.dat
26968 17:47:54.917 |- 12/14/2023  04:51 PM         3,844,243 SH2EEsetup.exe
26968 17:47:54.917 |- 09/30/2002  05:41 AM            71,078 sh2logo.jpg
26968 17:47:54.917 |- 11/30/2017  06:22 PM         5,459,968 sh2pc.exe
26968 17:47:54.917 |- 09/26/2002  08:19 PM         6,229,455 sh2pc.exe.bak
26968 17:47:54.917 |- 03/15/2023  02:12 PM               412 Xidi.ini
26968 17:47:54.917 |--------------------------------
26968 17:47:54.926 Patching window title...
26968 17:47:54.926 Patching window icon...
26968 17:47:54.926 Loading d3d9.dll
26968 17:47:54.929 Enabling XInput Vibration Fix...
26968 17:47:54.929 Loading the "WidescreenFixesPack" module...
26968 17:47:54.929 Setting resolution: 1920x1080
26968 17:47:54.929 Setting Hotel Room 312 Resolution Fix...
26968 17:47:55.017 Hooking the FileSystem APIs...
26968 17:47:55.039 CD patch already set!
26968 17:47:55.039 Patching binary...
26968 17:47:55.039 Finding SFX file locations...
26968 17:47:55.121 Updating SFX memory address locations...
26968 17:47:55.121 Allocating memory buffer for sddata.bin file...
26968 17:47:55.122 PatchTexAddr Error: failed to find texture buffer size!
26968 17:47:55.122 Disabling Screensaver...
26968 17:47:55.122 Setting 2TB hard disk Fix...
26968 17:47:55.122 Setting PS2 Style Noise Filter...
26968 17:47:55.122 Increasing the Draw Distance...
26968 17:47:55.122 Setting Room Lighting Fix...
26968 17:47:55.122 Fixing tree lighting conditions...
26968 17:47:55.122 Setting Rowboat Animation Fix...
26968 17:47:55.122 Updating the Catacomb Meat Cold Rooms color...
26968 17:47:55.122 Updating Fog Parameters...
26968 17:47:55.122 Setting Piston Position Fix...
26968 17:47:55.122 Setting Hotel Room 312 Shadow Flicker Fix...
26968 17:47:55.122 Hiding Red Cross health indicator during cutscenes...
26968 17:47:55.122 Enabling PS2 Flashlight Fix...
26968 17:47:55.122 Fixing behavior of Lying Figures that are hiding under vehicles...
26968 17:47:55.122 Add fix to prevent chainsaw from spawning on first playthrough...
26968 17:47:55.122 Updating James' spawn point position...
26968 17:47:55.122 Applying Fixes for 60 FPS...
26968 17:47:55.122 Applying Meat Locker Fixes...
26968 17:47:55.123 Hooking Fog Animation Rate...
26968 17:47:55.123 Hooking Bullet Animation...
26968 17:47:55.123 Patching motion blur...
26968 17:47:55.123 Patching water animation speed...
26968 17:47:55.123 Patching flashlight speed...
26968 17:47:55.123 Patching low health indicator flashing speed...
26968 17:47:55.123 Patching flame staircase lighting...
26968 17:47:55.123 Patching water level speed...
26968 17:47:55.123 Enabling Prisoner Timer Fix...
26968 17:47:55.123 Enabling Lying Figure Spray Effect Fix...
26968 17:47:55.123 Enabling Hyper Spray Effect Fix...
26968 17:47:55.123 Enabling Map Transcribe Animation Speed Fix...
26968 17:47:55.123 Patching bug room flashlight...
26968 17:47:55.123 Enabling Enemy Hold Damage Fix...
26968 17:47:55.123 Patching Double Footstep Fix...
26968 17:47:55.123 Done applying 60 FPS fixes...
26968 17:47:55.123 Fixing Flashlight Flicker...
26968 17:47:55.123 Fixing memo brightness...
26968 17:47:55.123 Setting Pause Menu Fix...
26968 17:47:55.768 loadExternalFontData: Using font file: sh2e\font\font000.png fontColumnNumber 100 fontRowNumber 150
26968 17:47:57.326 Enabling Custom Fonts...
26968 17:47:57.338 PatchCustomFonts Could not find font width data file
26968 17:47:57.340 Enabling Custom Exe Strings...
26968 17:47:57.340 Enabling Main Menu title selection by language...
26968 17:47:57.348 Enabling post Processing Special FX...
26968 17:47:57.348 Enabling Alternate Stomp...
26968 17:47:57.348 Enabling Town West Gate Event Fix...
26968 17:47:57.348 Enabling Screen Position option lock...
26968 17:47:57.348 Fixing Flashlight Clock Push...
26968 17:47:57.349 Fixing Game Results loading crash...
26968 17:47:57.349 Patching Quick Save Text Position...
26968 17:47:57.349 Fixing "Save Game" Sound...
26968 17:47:57.349 Fixing Inventory BGM...
26968 17:47:57.349 Fixing Moth Sound Looping...
26968 17:47:57.349 Fixing Chainsaw Sound Looping...
26968 17:47:57.349 Enabling Save Background Images Fix...
26968 17:47:57.349 Enabling Best Graphics settings...
26968 17:47:57.349 Enabling Speaker Config Lock...
26968 17:47:57.349 Enabling Fog Fix...
26968 17:47:57.350 Set map scaling!
26968 17:47:57.350 Set texture scaling!
26968 17:47:57.354 Fixing Movies ratio crash...
26968 17:47:57.354 Enabling Dynamic Resolution...
26968 17:47:58.116 Enabling Advanced Options fix...
23516 17:47:58.168 CheckForUpdate SH2EEsetup.dat exists, using CSV for update checking...
26968 17:47:58.346 Enabling Criware...
26968 17:47:58.346 Patching FMV speed...
26968 17:47:58.346 Patching Delayed Fade-in...
26968 17:47:58.346 Patching FMV subtitles to draw over noise grain...
26968 17:47:58.346 Patching Command Window Mouse Fix...
26968 17:47:58.346 Silent Hill 2 Enhancements module loaded!
26968 17:47:58.350 Redirecting 'DirectInput8Create' ...
26968 17:47:58.436 LogAffinity System has '4' cores and Silent Hill 2 is using '4' cores.
26968 17:47:58.436 |-------- MODULES LOADED --------
26968 17:47:58.436 |- G:\SH\sh2pc.exe
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\ntdll.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\KERNEL32.DLL
26968 17:47:58.436 |- C:\Program Files\Avast Software\Avast\x86\aswhook.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\KERNELBASE.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\apphelp.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\AcLayers.DLL
26968 17:47:58.436 |- C:\WINDOWS\System32\msvcrt.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\USER32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\win32u.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\GDI32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\gdi32full.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\msvcp_win.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\ucrtbase.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\SHELL32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\SHLWAPI.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\OLEAUT32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\combase.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\RPCRT4.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\SETUPAPI.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\cfgmgr32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\bcrypt.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\MPR.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\sfc.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
26968 17:47:58.436 |- C:\WINDOWS\System32\shcore.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\sfc_os.DLL
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\SortWindows61.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\IMM32.DLL
26968 17:47:58.436 |- C:\WINDOWS\System32\ADVAPI32.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\sechost.dll
26968 17:47:58.436 |- G:\SH\DINPUT8.dll
26968 17:47:58.436 |- C:\WINDOWS\SYSTEM32\WINMM.dll
26968 17:47:58.436 |- C:\WINDOWS\System32\ole32.dll
26968 17:47:58.436 |- G:\SH\d3d8.dll
26968 17:47:58.436 |- G:\SH\DSOUND.dll
26968 17:47:58.436 |- G:\SH\binkw32.dll
26968 17:47:58.437 |- G:\SH\MSVCR70.dll
26968 17:47:58.437 |- G:\SH\MSVCP70.dll
26968 17:47:58.437 |- C:\WINDOWS\System32\PSAPI.DLL
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\windows.storage.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\Wldp.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\uxtheme.dll
26968 17:47:58.437 |- G:\SH\dsoal-aldrv.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\MSVCP140.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\version.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\d3d9.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\kernel.appcore.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\dwmapi.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\xinput1_4.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\DEVOBJ.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\inputhost.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\wintypes.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\PROPSYS.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\CoreMessaging.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
26968 17:47:58.437 |- C:\WINDOWS\System32\WS2_32.dll
26968 17:47:58.437 |- C:\WINDOWS\System32\bcryptPrimitives.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\ntmarta.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\urlmon.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\iertutil.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\srvcli.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\netutils.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\WININET.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\SspiCli.dll
26968 17:47:58.437 |- C:\WINDOWS\SYSTEM32\profapi.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\winhttp.dll
26968 17:47:58.438 |- C:\WINDOWS\system32\mswsock.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\WINNSI.DLL
26968 17:47:58.438 |- C:\WINDOWS\System32\NSI.dll
26968 17:47:58.438 |- C:\WINDOWS\System32\CRYPT32.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\DPAPI.DLL
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\MSASN1.dll
26968 17:47:58.438 |- C:\WINDOWS\System32\WINTRUST.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\CRYPTSP.dll
26968 17:47:58.438 |- C:\WINDOWS\system32\rsaenh.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\DNSAPI.dll
26968 17:47:58.438 |- C:\Windows\System32\rasadhlp.dll
26968 17:47:58.438 |- C:\WINDOWS\System32\fwpuclnt.dll
26968 17:47:58.438 |- C:\WINDOWS\System32\schannel.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\mskeyprotect.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\NTASN1.dll
26968 17:47:58.438 |- C:\Windows\System32\cryptnet.dll
26968 17:47:58.438 |- C:\WINDOWS\SYSTEM32\ncrypt.dll
26968 17:47:58.439 |- C:\WINDOWS\system32\ncryptsslp.dll
26968 17:47:58.439 |- C:\WINDOWS\System32\MSCTF.dll
26968 17:47:58.439 |- C:\WINDOWS\system32\dinput8.dll
26968 17:47:58.439 |- C:\WINDOWS\SYSTEM32\HID.DLL
26968 17:47:58.439 |--------------------------------
26968 17:47:58.455 Redirecting 'Direct3DCreate8' ...
26968 17:47:58.455 Starting D3d8to9 v1.11.1.0
26968 17:47:58.455 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
26968 17:47:58.455 Initializing crosire's ReShade version '4.5.3.797' (32-bit) built on '2020-10-03 01:58:54' loaded ...
26968 17:47:58.491 |------------- GPUs -------------
26968 17:47:58.491 m_IDirect3D9::LogAdapterNames | - Adapter: 0 \\.\DISPLAY1 NVIDIA GeForce RTX 3060
26968 17:47:58.491 m_IDirect3D9::LogAdapterNames | - Adapter: 1 \\.\DISPLAY2 NVIDIA GeForce RTX 3060
26968 17:47:58.491 |--------------------------------
26968 17:47:59.031 |---------- VIDEO CARD ----------
26968 17:47:59.031 | Using video card: NVIDIA GeForce RTX 3060 (0x10de)
26968 17:47:59.031 |--------------------------------
26968 17:47:59.031 Setting Window theme...
26968 17:47:59.032 Setting Window Attributes...
26968 17:47:59.209 Running on NVIDIA GeForce RTX 3060 Driver 536.23
26968 17:47:59.209 Recreated runtime environment on runtime 10471A38.
26968 17:47:59.209 m_IDirect3D8::CreateDevice Created device!
26968 17:47:59.298 m_IDirectInput8A::CreateDevice Created device!
26968 17:47:59.301 |----------- GAMEPADS -----------
26968 17:47:59.427 |- Name: 'OBINS
AnnePro2' GUID: {3D803F20-CF8F-11EB-8001-444553540000}
26968 17:47:59.501 |- Name: 'OBINS
AnnePro2' GUID: {3D81ECD0-CF8F-11EB-800E-444553540000}
26968 17:47:59.504 |- Name: 'Xidi Virtual Controller 1' GUID: {FFFFFFFF-0000-0000-5849-444900000000}
26968 17:47:59.504 |- Name: 'Xidi Virtual Controller 2' GUID: {FFFFFFFF-0000-0000-5849-444901000000}
26968 17:47:59.504 |- Name: 'Xidi Virtual Controller 3' GUID: {FFFFFFFF-0000-0000-5849-444902000000}
26968 17:47:59.504 |- Name: 'Xidi Virtual Controller 4' GUID: {FFFFFFFF-0000-0000-5849-444903000000}
26968 17:47:59.609 |--------------------------------
26968 17:47:59.609 Removing Force Feedback filter!
26968 17:47:59.734 Using gamepad device GUID: {3D803F20-CF8F-11EB-8001-444553540000}
26968 17:47:59.736 Redirecting 'DirectSoundCreate8' ...
26968 17:47:59.853 m_IDirectSound8::CreateSoundBuffer Created buffer!
26968 17:48:15.819 Unhooking library functions
26968 17:48:15.819 Reenabling Screensaver...
26968 17:48:15.844 Unloading Silent Hill 2 Enhancements!

**Comment by Polymega** [comment]
Looking at your log file, you're missing the `data` folder that should be in the Silent Hill 2 game folder. This likely means you don't have the base (vanilla) game installed. Our project requires the base game to be installed in order to work.

You can download the "fully extracted" version of the game here: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Then, move all of your Enhanced Edition project files into the folder where you placed the vanilla game files in.
