### ISSUE TITLE
Controller's vibration doesn't work when low health

### ISSUE THREAD

**Issue by A1truistic** [elishacloud/Silent-Hill-2-Enhancements#885]
I was playing silent hill 2 e.e and i just found out that my controller doesn't vibrate when i'm low on health, how the heck am i suppose to find out if my health's low or not??

**Comment by Polymega** [comment]
What controller are you using and how is it connected to your PC (wired or wireless)?

> how the heck am i suppose to find out if my health's low or not??

The PC version has a low health indicator. It's a flashing red cross symbol on the bottom right of the screen. You can also check the status of your health through the "STATUS" window while in the inventory screen.

**Comment by A1truistic** [comment]
> What controller are you using and how is it connected to your PC (wired or wireless)?
> Quantum T-Rex Qhm7468 wired with working vibration

I'm kind of lazy by checking the status😅 I wanted my full experience on playing silent hill 2, I already adjusted the vibration settings in the config, I tested my controller's vibration already and it works but barely in silent hill 2 enhanced edition, The vibration only works when you're hitting/shooting the monsters or the wall but not the character's status so is there another way to trigger the vibration when my status is very red so i can be aware if I'm battling with 2 pyramid head or maria/mary's boss fights?

**Comment by A1truistic** [comment]
Also i just found out that when you drain your health almost to red status, my controller only vibrates when im on pause menu/inventory with low health, on the ps2 version my controller vibrates like a heartbeat and this indicates that james is on low health and does the enhanced edition also got this feature too or my controller is just trash?

**Comment by Polymega** [comment]
> or my controller is just trash?

It might be the controller. I've re-tested my Xbox 360, Xbox One, 8bitdo SN30 Pro+, and Logitech RumblePad 2 controllers and they all vibrate correctly, as they should with the game.

**Comment by J3stheme** [comment]
>my controller is just trash?

Buddy all you need to do is to use the x360ce for this since your physical controller has the vibration but using x360ce is more advanced and probably vibrates your controller like a heartbeat. +Use the hidhide client if you are encountering the double clicking problem when playing and this hides your physical controller and your virtual controller can control your gameplay without any issues
