### ISSUE TITLE
Movement issues on silent hill 2 (enhanced edition)

### ISSUE THREAD

**Issue by lucastrev99** [elishacloud/Silent-Hill-2-Enhancements#887]
Hi guys. I ran into some issue over here. When I'm playing with the xbox gamepad on, I simply cannot run and turn left. If I do, James will stop moving for a second and then start walking. I'm using the 3d type. While using the 2d type, it doesn't happen and I can move james fine.

Any idea on why this happens? it happens on silent hill 3 as well, but oddly enough, it doesn't happen in Silent Hill 1.
update: It's all normal now, I've switched to my old generic pc gamepad. It looks like it only happens with the x360 joypad. What the hell?

**Comment by Polymega** [comment]
It might be a result of turning too much with the joystick while using 3D control type. One thing you can try is controlling James with the D-pad when using 3D control type. Keep your thumb on UP (to have him move forward) and use the side of your thumb to press LEFT or RIGHT at the same time. That should keep him at full speed when turning.
