### ISSUE TITLE
Random visual strobe effect then crash, and frequent crashes when attempting to save

### ISSUE THREAD

**Issue by GHOSTIE-NSG** [elishacloud/Silent-Hill-2-Enhancements#888]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13794443/d3d8.log)
I recently installed the enhanced edition modification for SH2 on PC, and I've been having a good time for the most part, the game runs at a solid 60fps, however sometimes when I pause, or open the inventory screen, the screen will begin to dissolve into a flurry of colors and then crash, this doesn't happen often though, what does happen constantly is whenever I try to save the game, it'll crash. Sometimes, I am able to save if I'm fast enough, but this is putting me off wanting to play the game.

**Comment by Polymega** [comment]
Is this issue still happening for you?

Closing ticket. Feel free to re-open if you'd like further assistance.
