### ISSUE TITLE
Removal of code fixed by editing room file

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#889]
Hi Elisha,

Up to you, but if you'd like, you can remove the portion of code highlighted in the link below along with any associated variables used for it. I was able to address this one via level editing now.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/c488215d8544cb115039497233e3b638173524c0/Patches/FogAdjustments.cpp#L43-L93

Thanks!

**Comment by Polymega** [comment]
The removal of that code is causing a crash to desktop when loading a save file in or entering the apartment area (the code which you removed was a fog fix for the apartment area).

**Comment by elishacloud** [comment]
Good catch.  It should be fixed.  You can test the fix [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/7920865274).

**Comment by Polymega** [comment]
Yep! It's fixed now. Thank you!
