### ISSUE TITLE
Game Freeze when using `lang` under certain condition

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#890]
The main menu uses two images: `start00.tex` (the background image) and `start01.tex/start01*.tex` (the main menu text selections).

We have a check in place where, within the `sh2e` directory, if a **high res** `start01.tex/start01*.tex` exists but a high res `start00.tex` _**does not**_ exist, the project will revert to using the original, low res `start01.tex` then. This is a safety check because both images must be scaled the same to display properly.

The problem lies with the `lang` directory. For the language packs, they include a translated, high res `start01*.tex` within the `lang` directory and utilize the high res `start00.tex` in the `sh2e` directory (from the Image Enhancement Pack). However, if a high res `start00.tex` does not exist within the `sh2e` folder the game will soft lock on the main menu because it'll still use the high res `start01*.tex` found in the `lang` folder while falling back to the different-scaled original `start00.tex` file within the `data` directory.

Solution: If a high res `start01.tex/start01*.tex` exists within the `lang` directory, have the project check if a high res `start00.tex` exists in the `lang` directory, _and also_ the `sh2e` directory, then, if it doesn't exist, revert to using the original/vanilla `start01.tex` found in the `data` folder.

**Comment by elishacloud** [comment]
I updated the code to check to make sure `start00.tex` exists in the same folder when the game is looking for `start01*.tex`.  This way the two files are paired in the same folder.  If `start00.tex` does not exist then it will fall back to `sh2e` and then to `data`.

_Note: this does not check the resolution of the tex files it just makes sure they both exist in the same folder._

To test this you can use the build [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/7895277658).

**Comment by Polymega** [comment]
Thanks, Elisha. Sorry to make this more complicated, but is it possible to still have just `start01*.tex` be in its own folder like before? I ask as all language packs currently out there have _just_ `start01*.tex` in the `lang` folder. With this change, it'll break things unless we update all language packs and all users then update those packs.

**Comment by elishacloud** [comment]
I am not quite sure how putting the `start01*.tex` in its own folder will help.  It already has a unique name, so whether all of the `start01*.tex` files are in the same folder or they each have a unique folder does not seem to matter.  Maybe putting the `start00.tex` file in a unique folder would help though.  But I am not sure.

Do we expect more than one language to be in the `lang` folder?  If only one language is in the `lang` folder then how does it help to put `start01*.tex` in its own folder?

I think the issue is that the `start01*.tex` and the `start00.tex` need to match.  If so then it would make sense to put both the matching `start01*.tex` and `start00.tex` into the same folder.  But maybe an even better way would be to just keep them all in the same folder and give the `start00.tex` a new name, like this `start00*.tex`, to match the `start01*.tex` file?

**Comment by Polymega** [comment]
> I am not quite sure how putting the start01*.tex in its own folder will help. It already has a unique name, so whether all of the start01*.tex files are in the same folder or they each have a unique folder does not seem to matter. Maybe putting the start00.tex file in a unique folder would help though. But I am not sure.

Sorry, you misunderstood me. Currently, the language packs only come with a `start01*.tex` file and _not_ a `start00.tex` file. So the language pack's `start01*.tex` resides in the `lang` folder and piggy-backs off of the `start00.tex` file in the `sh2e` folder.

If possible, a solution would be if ahigh res `start01*.tex` exists within the lang directory, have the project check if a high res `start00.tex` exists in the `lang` directory and, if not, then check the `sh2e` directory for the `start00.tex` file, then, if it doesn't exist, revert to using the original/vanilla `start01.tex` found in the data folder.

**Comment by Polymega** [comment]
To expand upon this a little more: Way back when we first made the `lang` directory for language packs, I wasn't aware of this issue I reported here. Because of that, I had it to where the language packs only included their respective `start01*.tex` file, since it could piggy-back off the `start00.tex` found in the `sh2e` folder. 

We can change it to where the language packs include _both_ `start00.tex` and `start01*.tex`. The only concern there is, if you change the code to _not_ use the `start01*.tex` in the `lang` folder if it isn't accompanied with a `start00.tex` in the same folder, it will 'break' compatibility with all currently used language packs out there unless the user re-downloads the language pack. 

We can certainly do this instead, but I was hoping to avoid any tickets in the future where we get, "My high res and translated main menu is gone, what happened?"

**Comment by elishacloud** [comment]
I see.  I can make it so that it checks for the high resolution `start00.tex` first under the `lang` folder then fail over to the `sh2e` folder and if it cannot find a high resolution `start00.tex` file then use the `start01*.tex` file from the `data` folder.

I can also create a log event if I find a mismatch.

Furthermore, I can check the resolution to see if the start00 and start01 files will work together.  On my system I can see that the `start01e.tex` has resolution of 2048x2048 and the `start00.tex` has resolution of 2732x2048.  So they don't match.  If I am checking for high resolution how can I tell if the resolutions of the two files work together?  Can I just check if the height of the textures match, since it appears that the width does not always match?

One more issue.  In my install I cannot find a `start01e.tex` file in the data folder.  So how would this work if there is no high resolution `start00.tex` file?  If I make it fail over to the `data` folder then it will not find anything...

**Comment by elishacloud** [comment]
> One more issue. In my install I cannot find a `start01e.tex` file in the data folder. So how would this work if there is no high resolution `start00.tex` file? If I make it fail over to the `data` folder then it will not find anything...

It looks like this is not an issue.  The game will just fail over to `start01.tex` if it cannot find the correct `start01*.tex` file.

**Comment by Polymega** [comment]
> I see. I can make it so that it checks for the high resolution start00.tex first under the lang folder then fail over to the sh2e folder and if it cannot find a high resolution start00.tex file then use the start01*.tex file from the data folder.

That would be good if it can work out that way, thank you.

> On my system I can see that the start01e.tex has resolution of 2048x2048 and the start00.tex has resolution of 2732x2048. So they don't match. 

`start00.tex` has a weird dimension as we made it specially in widescreen format. (`start00.tex` is the main menu BG image, and `start01*.tex` is the main menu text.)

> If I am checking for high resolution how can I tell if the resolutions of the two files work together? Can I just check if the height of the textures match, since it appears that the width does not always match?

You can do it that way or, if you prefer, go the opposite route for checking: If these textures **are not** 512x512 (the vanilla resolution for both `start00.tex` and `start01.tex`) then they can be assumed to be the high res versions.

**Comment by elishacloud** [comment]
> You can do it that way or, if you prefer, go the opposite route for checking: If these textures **are not** 512x512 (the vanilla resolution for both `start00.tex` and `start01.tex`) then they can be assumed to be the high res versions.

Are you sure that any highres size will work?  Maybe the game will always freeze if the height of these two textures are not the same?

**Comment by Polymega** [comment]
I'm not sure on that. You might be right that different heights could break things. However you think best to check/code this is the best way!

**Comment by elishacloud** [comment]
It is not easy to check the texture size to verify a match.

What if I just do something simple like check the `lang` and `sh2e` folders for `start00.tex`?  If no `start00.tex` file is found in those folders than load both the `start00.tex` and `start01*.tex` files from the `data` folder.

**Comment by Polymega** [comment]
Simple is sometimes better! Sounds good; thank you for doing that.

**Comment by Polymega** [comment]
Tested and works great. Thank you!

Moving forward, I will ensure language packs include both `start00` and `start01*` and go back and insert `start00` to existing language packs on the site. 

Your safety check here is to prevent problems from people who are using previous language packs without the inserted `start00` in them. This feature should ensure things still work for them like before.

@IlDucci @lucazandrade 
Moving forward, please ensure `start00.tex` also exists in your language pack under `lang\pic\etc\`. You can grab `start00.tex` for use in your language packs from `sh2e\pic\etc\`.

Thanks all

**Comment by lucazandrade** [comment]
@Polymega Done!
[SH2EE_LangPack_Brazilian_Portuguese.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14289360/SH2EE_LangPack_Brazilian_Portuguese.zip)
