### ISSUE TITLE
launch trouble

### ISSUE THREAD

**Issue by SHSUNDERLAND** [elishacloud/Silent-Hill-2-Enhancements#894]
Hi! I am having trouble launching the game. I keep getting a pop up that says sh2pc.exe is not responding. Every time i try to close the window it comes back right away. I have updated the enhanced edition and now the file is corrupted.

**Comment by elishacloud** [comment]
It could be that you have an old version of the module.  Try re-downloading the latest version of the d3d8.dll module from this GitHub page.

If you still have issues you can try running the game as an admin and disabling the following settings:

* Auto update module
* Admin privilege checker
