### ISSUE TITLE
when i open the game it says it doesnt responding

### ISSUE THREAD

**Issue by vicarnikitas** [elishacloud/Silent-Hill-2-Enhancements#897]

**Comment by Polymega** [comment]
Please see a screenshot of the game's folder.

**Comment by vicarnikitas** [comment]
![Screenshot 2024-01-23 032405](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/157364184/844d92d8-e026-4164-97d7-b168401d33df)

**Comment by vicarnikitas** [comment]
![εικόνα_2024-01-23_033704968](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/157364184/007711ba-c953-4ccc-8d7c-c7d932c43062)
