### ISSUE TITLE
ps4 buttons dont work

### ISSUE THREAD

**Issue by vicarnikitas** [elishacloud/Silent-Hill-2-Enhancements#898]
I finally can play silent hill 2, but i have a problem when i try to use my ps4 controller, some of the buttons dont respond

**Comment by Polymega** [comment]
Make sure you aren't using a third party controller software, such as DS4Windows, while playing the game. If you are playing wirelessly, try playing with a wired connection by plugging your DS4 into the computer through its USB port.
