### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by gerooo909** [elishacloud/Silent-Hill-2-Enhancements#899]
I noticed that the CPU usage is unusually high when playing the game compared to other stuff i play, and made no sense because this game is old and shouldnt use much resources especially since the gpu usage was super low, cpu usage was 80 to 100% and power consumption high too with the default multicore option, the problem is alleviated by setting single core affinity, CPU usage drops down to normal levels like 20% and power consumption drops down significantly, i personally have no issues playing the game limited 1 cpu core but would be nice if this issue can be addressed in the future. 
I run the game on a fresh installation of windows 10 and im using a haswell i5 cpu (4c4t ) and a nvidia gpu.

**Comment by elishacloud** [comment]
This sounds normal.  The game uses at least one busy-wait-loop that uses all the CPU time no mater how fast the CPU is.  This is the way the authors created the game engine.  We cannot fix that without rewriting the whole game engine, which is not planned.
