### ISSUE TITLE
PS3 Controller button mapping?

### ISSUE THREAD

**Issue by Cyberdemon87** [elishacloud/Silent-Hill-2-Enhancements#90]
Hello!

I'm using a PS3 Dualshock controller and the buttons mapping are a bit messed up.
Is there any way I can change them to my liking?
The "Joypad" option at the game's settings cannot be pressed for some reason so I can change the layout.

Please let me know.
Thanks!

**Comment by Polymega** [comment]
I don't use a PS3 controller for the game so would be unable to help. There's only one person I know of that uses a PS4 controller with the game. You can try following his steps and see if that also works for your controller: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/88#issuecomment-456726505

**Comment by AeroWidescreen** [comment]
@Polymega 
> You can try following his steps and see if that also works for your controller.

I don't think that'll work for him, at least not the DS4Windows part.

@Cyberdemon87 
Try following the steps here to get XInput support for your DS3: [PCGamingWiki](https://pcgamingwiki.com/wiki/Controller:DualShock_3#PS3_Controller_on_Windows_.28Wired.29)
Then follow the instructions here to install XInput Plus: [SH2 Enhanced Edition](http://www.enhanced.townofsilenthill.com/SH2/#installXinputPlus)

**Comment by elishacloud** [comment]
Closing as no response.  This can be reopened later if issue comes back.
