### ISSUE TITLE
Silent Hill 2 Director's Cut crashes at hospital when i try to use the elevator.

### ISSUE THREAD

**Issue by Falinger** [elishacloud/Silent-Hill-2-Enhancements#900]
After finding Maria and heading to the elevator to get to the second floor and get the fridge open, game freezes.
I'm talking about that one elevator next to the 3D woman painting on the 3rd floor.  Once i get in and press the 2nd floor, game freezes. I can still shoot around, move and all but I cant interact with the door nor the panel. Btw, at that point, a quiz should pop out but it doesn't. The sound of elevator moving loops forever to no ending. and im desperate for help now since I was really excited to play this game.

Here's a screenshot of my game files.
![resim_2024-01-26_180044589](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/82849865/72514960-c1f8-44fe-b6a0-714eb74b1ca2)

**Comment by Polymega** [comment]
Hi there,

It looks like you're not running the game with our project files. Additionally, there's additional files in the game's directory that aren't a part of our project that are likely causing you issues/conflicts.

Did you download the project files from our website? Or did you download a pre-packaged file from elsewhere? I recommend downloading and installing the base/vanilla game (with no extra files), and then running the Setup Tool from our website to install our project files.

Your directory should look like this after everything is installed, and there shouldn't be any extra files within the directory: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree
