### ISSUE TITLE
I can't click the Dear Tim note in the game

### ISSUE THREAD

**Issue by CrumbleCat** [elishacloud/Silent-Hill-2-Enhancements#901]
Hey hey. I'm playing this beautiful edition, but I've come across something strange. The note on door 209 at the blue creek apartments can't be clicked on/read. I've tried from every angle, but James just will not read it. He only enters the door. I did the coin puzzle first (the reward was the Lyne House Key), before I read the note. Maybe that's why? I'm unsure if I'm missing something obvious, or if it's a bug. 

![y85Or9QDy6](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/157997779/6798d6e0-11b8-45d1-8dff-6c9288db54db)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14078001/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

> I did the coin puzzle first (the reward was the Lyne House Key), before I read the note. Maybe that's why?

Yep, that's why. Also, if you happened to examine the door _before_ acquiring the key there will also be an additional piece of dialogue whenever James examines that key.

**Comment by CrumbleCat** [comment]
Well, I find that a bit goofy. I can imagine an imaginary scenario where there's some reason to collect all notes, like if it affected achievements, or an ending. I guess my James just won't have that note in his inventory for this playthrough. The poor bastard forgot his reading glasses.
