### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by SHmont** [elishacloud/Silent-Hill-2-Enhancements#903]
Hi,
I the game won't start after installing the enhanced edition. I download the myabandonware version. The game launch fine without the enhanced version but once it's installed nothing happen.
The sh2 process start but disappeared immediately from the task manager.

In the d3d8.log it just stop at "setting delayed statup".
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14130746/d3d8.log)

What I'm I doing wrong ?
If someone has an idea, I'll take it
Thank

**Comment by Polymega** [comment]
Can you please share a screenshot of the game's folder?

**Comment by SHmont** [comment]
Sure
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/158517352/e805ace1-75da-4550-b813-f33da81e5b46)

**Comment by elishacloud** [comment]
This looks like he same as #904

**Comment by elishacloud** [comment]
Try the steps outlined [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/904#issuecomment-1922590428).

**Comment by SHmont** [comment]
Just tried it. Nothing changes

**Comment by elishacloud** [comment]
Can you upload the new log file?

**Comment by SHmont** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132871/d3d8.log)
Look the same has before

**Comment by elishacloud** [comment]
That is weird.  It looks like something is changing how the binary loads in.  What antivirus are you using?  Are you running this on Windows or some other platform?

Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

**Comment by SHmont** [comment]
It work with the last file you gave me

**Comment by elishacloud** [comment]
I am trying to put a fix for this.  Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14470834/d3d8.zip)

**Comment by molokored** [comment]
Thanks, was also facing the same issue after installing today but with the new dll it started working correctly!
