### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by bpluto444** [elishacloud/Silent-Hill-2-Enhancements#904]
I try to launch it and nothing happens, I've tried uninstalling and reinstalling 3 times
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14131007/d3d8.log)

**Comment by Polymega** [comment]
Can you please share a screenshot of the game's folder?

**Comment by bpluto444** [comment]
![2024-02-01](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/158520020/085c6e13-f528-488f-b995-8c3297af0052)

**Comment by Polymega** [comment]
Hmm... Everything looks to be in order there. I'm not sure what might be causing this to happen, but we can try a few tests:

- Open `SH2EEConfig.exe` and click the "Default" button at the bottom left corner, then launch the game. Does the game launch then?
- _Temporarily_ move `dinput8.dll` and `dsound.dll` to another folder. Does the game launch then? 
   - If not, you can place these files back in the correct folder.
- _Temporarily_ move `d3d8.dll` to another folder. This is the "brains" of our project and removing it from this folder will essentially have you playing the vanilla version. Does the vanilla version boot up for you?

**Comment by bpluto444** [comment]
> * g

I moved d3d8.dll out and it launched. should i place it back in?

**Comment by Polymega** [comment]
Yes, as without that you aren't playing the game with our project files. We may need to get our lead programmer Elisha to weigh in on some probable causes for why this is happening.

@elishacloud 
Please see this ticket here. Looks to be the same issue as this ticket: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/903

**Comment by Polymega** [comment]
Also, can you confirm if your antivirus software is blocking the our project from running?

**Comment by elishacloud** [comment]
This looks like he same as #903

**Comment by elishacloud** [comment]
Try the following things:

1. Re-downloading and replacing the `sh2pc.exe`.
2. Try unzipping this into the Silent Hill 2 folder:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132632/d3d8.zip)

I disabled all of the items that run before the delayed startup and added logging to the delayed startup.

**Comment by bpluto444** [comment]
> Try the following things:
> 
> 1. Re-downloading and replacing the `sh2pc.exe`.
> 2. Try unzipping this into the Silent Hill 2 folder:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132632/d3d8.zip)
> 
> I disabled all of the items that run before the delayed startup and added logging to the delayed startup.

I did both of those and now when I try to launch it, it says I don't have a CD/DVD-ROM drive, which is true, I don't. I got the game off abandonware

**Comment by elishacloud** [comment]
Can you send me the new log file?

**Comment by bpluto444** [comment]
> Can you send me the new log file?

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14133820/d3d8.log)

**Comment by elishacloud** [comment]
Interesting.  I am seeing the below from the log file, which make me believe that there is some issue with the `sh2pc.exe` file or there is something else running on your computer that is modifying the code in memory before SH2EE loads.

Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

```log
13008 19:16:32.089 CheckMemoryAddress -> SetDelayedStart Error: memory address not found!
13008 19:16:32.091 SearchAndGetAddresses -> SetDelayedStart searching for memory address! Found = 00000000
13008 19:16:32.091 SearchAndGetAddresses -> SetDelayedStart Error: failed to find memory address!
13008 19:16:32.091 Error: failed to set delayed startup...
```

**Comment by bpluto444** [comment]
> Interesting. I am seeing the below from the log file, which make me believe that there is some issue with the `sh2pc.exe` file or there is something else running on your computer that is modifying the code in memory before SH2EE loads.
> 
> Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)
> 
> ```
> 13008 19:16:32.089 CheckMemoryAddress -> SetDelayedStart Error: memory address not found!
> 13008 19:16:32.091 SearchAndGetAddresses -> SetDelayedStart searching for memory address! Found = 00000000
> 13008 19:16:32.091 SearchAndGetAddresses -> SetDelayedStart Error: failed to find memory address!
> 13008 19:16:32.091 Error: failed to set delayed startup...
> ```

Did that and it still says No CD/DVD-Rom drive. If you can't figure this out, it's okay. I can still emulate it but I wanted to try this version

**Comment by Polymega** [comment]
With that CD message, try restarting your PC.

**Comment by Polymega** [comment]
Also, did you re-download the `sh2pc.exe` file from our project? Or the one from the MyAbandonware download? If the latter, you will get that message. You'll need to download the one from our project.

Open `SH2EEsetup.exe`, choose **Repair or Install Packages**, and select "Enhanced Executable".

**Comment by bpluto444** [comment]
> Also, did you re-download the `sh2pc.exe` file from our project? Or the one from the MyAbandonware download? If the latter, you will get that message. You'll need to download the one from our project.
> 
> Open `SH2EEsetup.exe`, choose **Repair or Install Packages**, and select "Enhanced Executable".

I did from abandonware, I did not know you guys had your own, let me try that

**Comment by bpluto444** [comment]
> > Also, did you re-download the `sh2pc.exe` file from our project? Or the one from the MyAbandonware download? If the latter, you will get that message. You'll need to download the one from our project.
> > Open `SH2EEsetup.exe`, choose **Repair or Install Packages**, and select "Enhanced Executable".
> 
> I did from abandonware, I did not know you guys had your own, let me try that

okay I did that, now it's back to the original problem, it just won't boot up, it does nothing. It didn't say no cd drive now

**Comment by Polymega** [comment]
Okay and to confirm, now that you're using the correct `sh2pc.exe` again, you're also using the test build Elisha sent found here? https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/904#issuecomment-1922770768

If so, please send an updated `d3d8.log` file after attempting to launch the game using that test build.

**Comment by bpluto444** [comment]
> Okay and to confirm, now that you're using the correct `sh2pc.exe` again, you're also using the test build Elisha sent found here? [#904 (comment)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/904#issuecomment-1922770768)
> 
> If so, please send an updated `d3d8.log` file after attempting to launch the game using that test build.

yes I am using the correct sh2pc.exe now
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14134964/d3d8.log)

**Comment by elishacloud** [comment]
Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

This should bypass the delayed startup.

**Comment by bpluto444** [comment]
> Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)
> 
> This should bypass the delayed startup.

It works. Thank your help and time

**Comment by callomello** [comment]
Hi there! I just wanted to mention that I was having this issue while using Bitdefender (which was fixed by the test d3d8) but I've since switched to Kaspersky and am no longer having the issue. In case this helps anyone else.
