### ISSUE TITLE
[Modding] Game Crashed after editing textures ! 

### ISSUE THREAD

**Issue by iliagaming** [elishacloud/Silent-Hill-2-Enhancements#906]
Hi 😅🖐
Sorry I know I shouldn't post something like this 😓 ( I thought it's the best way to contact u )
I decided to add HD textures for the game bc I thought SH 2 Enhancements mod would let me to use high re texture in the Game Files ( I mean **Texture Address Fix** ), well tnx to the **SH2tex** tool for a **test** I replaced texture of James body with HD textures **& Game crashed !**
Idk may be the problem is Data Size ? or the game doesn't support high res textures ??
![image_2024-02-03_223752151](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/156571237/51412aeb-479a-4124-81d8-07a57456aa43)
or may be I get it wrong & Texture Address  Fix is for something else !?

Any idea? is it even possible to add HD textures to the game like RE4 UH ( Not Actual adding, I mean replacing) ?🤔
SH 2 Enhancements is really amazing mod, literally fixed most of the known bugs & somehow remastered the game but personally I like to see HD textures too 😃
( thank u for reading this & sorry for my bad English, I'm Persian 😅 )

**Comment by Polymega** [comment]
I'm not really sure why it would be crashing. `.mdl` files (which are the textures you are editing in your post above) are something we haven't worked extensively with. While there's some good documentation on the format, there are very little modding tools for the format, which is in large part why our project has done very little with the format.

There might be some sort of texture limit for `.mdl` files. Unfortunately, I'm not really sure.

**Comment by iOrange** [comment]
While I'm not sure why exactly this crashes (@iliagaming migh provide us with the modified version of the model and or textures), but I have an idea on how we could make a simple system for textures replacement.
I can add to **sh2tex** an ability to calculate the md5 hash for the selected texture, and then we can at runtime when the game uploads the texture calc it's md5, and load the replacement texture instead from the  `sh2ee` folder that will be names as the md5 hash.

Should be easy to implement, I might even try that.

**Comment by certainmorning** [comment]
@iOrange

It would be absolutely awesome and game-changing (pun intended), if you manage to pull something like that. I had to freeze my neural upscaling project ([link](https://www.youtube.com/watch?v=fEpPNSw2w0o)) because older tools like texmod and umod eventually reached some engine limitations. I can provide sample textures if needed.
