### ISSUE TITLE
Game Crashing On Launch

### ISSUE THREAD

**Issue by wardrumsjr** [elishacloud/Silent-Hill-2-Enhancements#907]
I've gone through the other tickets and had no luck. 
Game opens to a black screen, holds for a few seconds, then closes.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14173524/d3d8.log)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/1920205/033df697-178f-4eb8-aa68-3ecabd3a1b71)

**Comment by Polymega** [comment]
```
5676 20:16:00.736 Enabling Transparency Antialiasing type SSAA
```

This might be why. Can you disable this to see if it resolves the issue?

**Comment by wardrumsjr** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/1920205/e33e9182-5bff-4075-842d-476a3415f140)
I believe it already is, atleast inside NVIDIA Control Panel. Is there another place this is enabled?

**Comment by Polymega** [comment]
Can you open `SH2EEconfig.exe` and, on that first window, disable "Run the game in DirectX 9" to see if it will launch then?

**Comment by wardrumsjr** [comment]
Nope, still black screen and crashing.

**Comment by wardrumsjr** [comment]
Problem solved, changed to Fullscreen and disabled Directx 9.
