### ISSUE TITLE
Flashlight sound in closet scene

### ISSUE THREAD

**Issue by DragonelOta** [elishacloud/Silent-Hill-2-Enhancements#909]
Hello, I have a suggestion.
Using the EE project, in the Pyramid Head scene (the scene with the mannequins, where James hides in the closet), you made James turn off the flashlight, which is cool, really good, it makes total sense, but it would be It's cool to add some sound to the scene, of the flashlight being turned off, even before James appears on the scene, so that it doesn't look so strange, if that's possible, of course.
It would be really cool to hear a "click" when the flashlight turns off, it would help to imagine that James turned off the flashlight so as not to attract Pyramid Head's attention (and a "click" before the scene ends, signaling that he turned on the flashlight again, like in the fade at the end of the scene, something like that) hehe... Congratulations on the project!!

**Comment by Polymega** [comment]
Apologies but this isn't something we'll be adding in.
