### ISSUE TITLE
Low Health Indicator Style

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#910]
@elishacloud 
This feature was created by @Polymega as a new option for the original low health indicator icon. It uses a more 
modern fullscreen effect instead of the the original red cross. It's easy to implement, but we mostly need your help with updating the texture path since the plan is for both textures to exist in the files so users can choose between the two styles.

I've attached the textures you need for testing.
[Textures.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14187352/Textures.zip)

![LowHealthIndicator](https://i.imgur.com/rO9UO4c.png)

## LowHealthIndicatorStyle = 1
The original default style.
Texture Path: `*\pic\etc\RedCrossIcon.png`

```
float LowHealthXPos = 0.85f
float LowHealthYPos = 0.95f
float LowHealthHeight = 0.1f
```

## LowHealthIndicatorStyle = 2
The new fullscreen style.
Texture Path: `*\pic\etc\LowHealthFade.png`

```
float LowHealthXPos = 0.0f
float LowHealthYPos = 1.001f
float LowHealthHeight = 0.25f
```

### 1.0
```
004F684C fmul dword ptr [LowHealthXPos]
004F6856 fmul dword ptr [LowHealthYPos]
004F6862 fld dword ptr [LowHealthYPos]
004F6876 fmul dword ptr [LowHealthHeight]
```

### 1.1
```
004F6AFC fmul dword ptr [LowHealthXPos]
004F6B06 fmul dword ptr [LowHealthYPos]
004F6B12 fld dword ptr [LowHealthYPos]
004F6B26 fmul dword ptr [LowHealthHeight]
```

### DC
```
004F63BC fmul dword ptr [LowHealthXPos]
004F63C6 fmul dword ptr [LowHealthYPos]
004F63D2 fld dword ptr [LowHealthYPos]
004F63E6 fmul dword ptr [LowHealthHeight]
```

**Comment by elishacloud** [comment]
Thanks @AeroWidescreen!  I will take a look at this soon.  After I finish a couple of other items.

**Comment by Polymega** [comment]
Thank you, both! 

```xml
      <Feature name="LowHealthIndicatorStyle">
        <Title>Low health indicator style</Title>
        <Description>Displays a visual indicator during normal gameplay when low on health.&#x0a;&#x0a;Red Cross: Displays a flashing red cross on the bottom right of the screen.&#x0a;Displays a flashing red vignette on the lower half of the screen. The lower your health, the brighter the vignette will become.&#x0a;&#x0a;Note: LowHealthFade.png must be present in "sh2e\pic\etc\" for the Lower Vignette graphic to display.</Description>
        <Choices type="list">
          <Value name="Red Cross">1</Value>
          <Value name="Lower Vignette" default="true">2</Value>
        </Choices>
      </Feature>
```

**Comment by CLPSAW** [comment]
how do I use this new vignette style, please?

**Comment by Polymega** [comment]
This feature isn't ready for use, yet. It will be fully stable and ready for use with our next project update.

**Comment by elishacloud** [comment]
I added this functionality in the latest build.  I think it works ok.  It only works if `LowHealthIndicatorStyle = 2` and `*\pic\etc\LowHealthFade.png` exists.  Otherwise nothing happens and it defaults to normal functionality.

You can get the latest build [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/8152486231).

**Comment by Polymega** [comment]
It works great! Thank you!

> It only works if LowHealthIndicatorStyle = 2 and *\pic\etc\LowHealthFade.png exists. Otherwise nothing happens and it defaults to normal functionality.

Ah, I love that you thought ahead for this safety check as I was going to request this otherwise. Thanks for being one step ahead. :)
