### ISSUE TITLE
Low-res Textures

### ISSUE THREAD

**Issue by CLPSAW** [elishacloud/Silent-Hill-2-Enhancements#913]
Hello there, first of all, let me say I'm a big fan of the EE project since it started many years ago and you guys are awesome!

Would it be possible to enhance these textures, especially considering we can interact with some of these billboards, which I would bet not many people know about, but now that the game is so good-looking thanks to EE, these signs stand out being too low-res.

![Captura de Tela (4003)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/116120236/ae150c83-ecf9-47b8-bc8d-f6d5fe7d89b4)
![Captura de Tela (4001)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/116120236/f6610298-8cb4-423e-8d5b-cecdb61b28be)
![Captura de Tela (4002)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/116120236/61a56faf-0b05-48fc-843b-187045380b20)

I hope it's even possible to do this but thanks in advance!

**Comment by iliagaming** [comment]
Unfortunadly it's not that easy 🥲
[Because of the game limitations ... Somehow ...](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/906)
But it's possible with TexMod to add upscaled textures but .... TexMod is a pain to eye tool ... So forget it ... At least for now 😅
