### ISSUE TITLE
my audio is not working

### ISSUE THREAD

**Issue by JordanDaUofL** [elishacloud/Silent-Hill-2-Enhancements#914]
I was trying to fix my controller and get it to work and i finally did  and as soon as i start the game there is no audio and my setup.exe takes me to a black browser tab

**Comment by elishacloud** [comment]
Try adding this line into the ini file:

```ini
HookDirectSound = 0
```

**Comment by Polymega** [comment]
If you're using a DualShock 4 or DualSense controller, make sure Windows didn't change your audio out to the controller. These controllers have built-in speakers and, when you plug them into your PC, Windows often automatically changes your audio out to the controller. You'll need to change your audio out back to your default device.
