### ISSUE TITLE
2 Visual Bugs / Localization issues

### ISSUE THREAD

**Issue by CLPSAW** [elishacloud/Silent-Hill-2-Enhancements#915]
This is technically just 1 and the same issue, it seems like the capital C is problematic, so the words "Clear"; "Crimson" and "Ceremony" are missing the letter C.

![Captura de Tela (4098)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/116120236/c5ce7615-0ea1-4297-b50d-4e9248c57ce1)
![Captura de Tela (4086)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/116120236/a7c5ec1e-794d-4198-99ce-9752f8dcaad5)

**Comment by Polymega** [comment]
That's interesting. Did you download the project files from our website? Can you share a screenshot of your game's directory?

**Comment by CLPSAW** [comment]
> That's interesting. Did you download the project files from our website? Can you share a screenshot of your game's directory?
> 
> I checked and things look fine on my end: ![Screenshot 2024-02-11 13-03-40](https://private-user-images.githubusercontent.com/27395260/303937936-84a36db0-73f8-4948-8fc3-7ebad982f567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjEzMzEsIm5iZiI6MTcwNzcyMTAzMSwicGF0aCI6Ii8yNzM5NTI2MC8zMDM5Mzc5MzYtODRhMzZkYjAtNzNmOC00OTQ4LThmYzMtN2ViYWQ5ODJmNTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA2NTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMGFjZDZiNjY2OTc3NWQ2ZjMzNjllZTk3MDAzNzZmMmM3MjdhNWUyMTJjNTIzMTUzY2Q2NzRhNDE0YjhmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vz10la3WGn-a3Ac7xlShEuPnDi7R_RLGDnlwiPNpuPc)

All 3 Silent Hill games are installed on a Konami folder in an external drive D: but why should that be the cause if all else is working? I did see a video of EE where the visual issue was NOT present, so please help me fix it somehow :)

**Comment by Polymega** [comment]
Please try making a backup of your save files then re-downloading the base (vanilla) game then our project files. 

Closing ticket. Feel free to re-open if you'd like further assistance.
