### ISSUE TITLE
Pre rendered cinematic lag and audio popping issue

### ISSUE THREAD

**Issue by MauriKLP** [elishacloud/Silent-Hill-2-Enhancements#917]
Hello, I recently installed the game and when watching the pre-rendered cinematic i noticed that the audio is broken, it cuts out in certain parts and there is a lot of lag (which does not happen in the rest of the game), is there any solution?
I clarify that in the scenes section of the main menu they work well but they still have audio problems.

**Comment by Polymega** [comment]
Hi there,

Can you upload a copy of your `d3d8.log` file?

**Comment by MauriKLP** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14233326/d3d8.log)

**Comment by Polymega** [comment]
We generally don't recommend using an integrated graphics processor for our project. I'm not sure how robust the AMD Radeon HD 6320 Graphics is. A couple things you can try:

- Play the game at a lower resolution.
- Open `SH2EEconfig.exe` and **disable** "Run the game in DirectX 9" (found on the first page)
- Open `SH2EEconfig.exe` and **disable** "Audio > Audio > Use custom streaming audio engine" and **enable** "Advanced > Performance > Single core affinity" (set it to a value between 0-9).

**Comment by MauriKLP** [comment]
Thanks, now it works fine 😁
