### ISSUE TITLE
Mini-map option SUGGESTION

### ISSUE THREAD

**Issue by CLPSAW** [elishacloud/Silent-Hill-2-Enhancements#918]
Please give us a tick-box to enable the hidden mini-map, I'm going through so much work to unlock it and I don't even know if it will work. Thanks a bunch in advance!

**Comment by Pocokk** [comment]
Wait, is there a hidden minimap? Now that's interesting!

**Comment by Polymega** [comment]
Unfortunately, the code for the mini map was outright removed from the PC version during its porting process, making it impossible to activate/restore.

**Comment by Pocokk** [comment]
I know (or strongly suspect) that the PS2 code is vastly different, but can't it be remade somehow based on that? Or that's just a feature not really worth THIS amount of work?
