### ISSUE TITLE
game crashes when launching

### ISSUE THREAD

**Issue by ahpierogi** [elishacloud/Silent-Hill-2-Enhancements#920]
game wont launch without crashing, tried temporarily removing d3d8.dll and it runs without that file in the vanilla version but not with the enhanced package?

![Screenshot 2024-02-13 191342](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/159969690/f67d1758-be4b-4d2b-b990-577c74f0e607)

**Comment by elishacloud** [comment]
Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

**Comment by ahpierogi** [comment]
i tried replacing with that file and it didn't work. i even redownloaded everything and still had the same issue

**Comment by Polymega** [comment]
Are you using BitDefender as your antivirus? If so, it might be preventing the game from launching.

**Comment by ahpierogi** [comment]
no i just checked and i dont have BitDefender installed

**Comment by PhantomR** [comment]
> Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

This file fixed the game for me, thank you!I was also unable to launch the game and I also have Bitdefender installed (haven't tried with it disabled or anything).

**Comment by elishacloud** [comment]
I am trying to put a fix for this.  Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14470834/d3d8.zip)

**Comment by PhantomR** [comment]
> I am trying to put a fix for this. Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14470834/d3d8.zip)

[To me the game was working with the previous experiemntal update]

I tried the new update, but the game wouldn't start. However, I discovered it is the INI file in this new update that's causing this as using the new DLL with the original INI I had (with a few settings modified) WORKS. 

Here's the log I get when using the new INI (I get a black screen for a few seconds and then crash to desktop):
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14474183/d3d8.log)

**Comment by ahpierogi** [comment]
Hi, i tried that update and it didnt work either? I just want to confirm that im replacing the file correctly tho. I downloaded the updated files you just sent, and put them in the silent hill game folder. then i  dragged the old d3d8.dll application extension and d3d8 config settings files out. should i be replacing the files in a different way? sorry im not the best with computer stuff like this :/

**Comment by elishacloud** [comment]
Interesting. Can you send me your working ini file?

**Comment by PhantomR** [comment]
> > I tried the new update, but the game wouldn't start. However, I discovered it is the INI file in this new update that's causing this as using the new DLL with the original INI I had (with a few settings modified) WORKS.
> 
> Interesting. Can you send me your working ini file?

Here it is :). I finished the game today with the new d3d8.dll (having started with the older one you previously uploaded here). I t think my INI (which I used with both DLL versions) is the one I get when first installing the game, but modified because I changed video settings in the configuration utility.

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14495217/d3d8.zip)

**Comment by PhantomR** [comment]
> Hi, i tried that update and it didnt work either? I just want to confirm that im replacing the file correctly tho. I downloaded the updated files you just sent, and put them in the silent hill game folder. then i dragged the old d3d8.dll application extension and d3d8 config settings files out. should i be replacing the files in a different way? sorry this is the first time ive had an issue like this with a game file so im not the best with knowing exactly what to do

Please try using the INI file I uploaded just above this post. Maybe it will help you.

**Comment by ahpierogi** [comment]
I wanted to come on here to let u know i fixed it!!! it was an issue with the vanilla game itself. i redownloaded the vanilla version of sh2 and then the most recent enhanced edition add-ons and it works!!! i didn't realize the game itself was the issue because it was running without the d3d8 file so im assuming something just got messed up :/ i moved over my save file and im as good as new.

**Comment by elishacloud** [comment]
Looks like this issue has been resolved.  Closing issue.
