### ISSUE TITLE
sh2 won't startup

### ISSUE THREAD

**Issue by Blunderless** [elishacloud/Silent-Hill-2-Enhancements#921]
clicking on "sh2pc.exe" doesn't seem to boot up the game.

i double click, the blue ring spins, the log reads "delayed startup" but nothing seems to happen

if there's any consolation, this may have occured due to me replacing the save folder to wipe the game. i did this before attempting to boot it up. haven't played this game in a year.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14304043/d3d8.log)

can someone please tell me what i'm missing or what's wrong? thank you very much.

**Comment by elishacloud** [comment]
This is most likely caused by your AV.  Are you using BitDefender by chance?

Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

**Comment by Blunderless** [comment]
> This is most likely caused by your AV. Are you using BitDefender by chance?
> 
> Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14132996/d3d8.zip)

yes, lol. thank you so much.
