### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by EdwaardSkeletrix** [elishacloud/Silent-Hill-2-Enhancements#924]
i start the sh2pc.exe and the cursour shows the loading wheel and nothing happens and it creates a log file
![image_2024-02-17_082638684](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/160340916/f96c73dc-ab6e-40aa-a771-8316c7fa3a76)

**Comment by Polymega** [comment]
Are you using BitDefender as your antivirus? If so, it might be preventing the game from launching.

Otherwise, can you try this test build? https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/920#issuecomment-1947637802

**Comment by EdwaardSkeletrix** [comment]
> Are you using BitDefender as your antivirus? If so, it might be preventing the game from launching.
> 
> Otherwise, can you try this test build? [#920 (comment)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/920#issuecomment-1947637802)

hello thanks for your reply, yes i use bitdefender

**Comment by EdwaardSkeletrix** [comment]
thank you so much it helped i think the test build very thankful

**Comment by elishacloud** [comment]
I am trying to put a fix for this.  Can you try with this update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14470834/d3d8.zip)

**Comment by koekmans4000** [comment]
> I am trying to put a fix for this. Can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14470834/d3d8.zip)

This fix worked for me, thank you!

**Comment by elishacloud** [comment]
Great.  Thank you for the update.  Are you by chance, using BitDefender?

**Comment by koekmans4000** [comment]
> Great. Thank you for the update. Are you by chance, using BitDefender?

Yes I am.

**Comment by elishacloud** [comment]
Perfect.  Thank you.
