### ISSUE TITLE
`PreserveSoundsOnLoad` causes CTD when starting new game using DC binary

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#926]
I believe when I originally tested this, I did so by clicking "Continue" on the main menu, so I didn't catch this crash to desktop.

Anyhow, when `PreserveSoundsOnLoad = 1`, the game immediately crashes to desktop upon selecting an Action Difficulty (NEW GAME > Main Scenario: Letter From Silent Heaven > Action Difficulty) when using the DC binary.

**Comment by elishacloud** [comment]
Should be fixed with the latest build.
