### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by sharjh** [elishacloud/Silent-Hill-2-Enhancements#927]
a black screen pops up and it crashes at launch.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14389192/d3d8.log)

**Comment by elishacloud** [comment]
Try disabling DirectX 9.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/2d0d3f85-f558-42c2-ba8c-9df0d69bcce5)

**Comment by elishacloud** [comment]
No, you cannot use shaders if Direct3D9 is disabled.  Are you using some other shaders besides what's in the game?  If so you should disable the shaders in SH2EE and then you can enable Direct3D9 and see if that works.

**Comment by sharjh** [comment]
I'm not using any external shaders, only sh2ee installed over the original game
