### ISSUE TITLE
Error (0xc0000142)

### ISSUE THREAD

**Issue by Marshall4IV** [elishacloud/Silent-Hill-2-Enhancements#928]
Hello, I have this problem since I installed the project, since before doing so the game opens and runs normally, with some errors of course, but when I install the project I get this error, I tried many ways to solve it but nothing seems to work

![Silent Hill 2 Director's Cut Repack 28_02_2024 21_27_45](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/161660433/513ede8e-c97c-49f8-9d14-b616bc419b7b)

**Comment by Black-tr3** [comment]
https://www.youtube.com/watch?v=5TWS4PJuLck&ab_channel=VictorExplains 
This is what I tried and it solved the problem
