### ISSUE TITLE
Silent Hill 2 Save issue

### ISSUE THREAD

**Issue by Vare3465** [elishacloud/Silent-Hill-2-Enhancements#93]
The above issue has already been described. Whenever you install SH2 on a + 2 TB HDD the game won't detect it and you won't be able to save your game. Is there any easy solution / fix for this?

**Comment by Polymega** [comment]
Hi @Vare3465 ,

Yes, we are aware of the issue and will hopefully have a fix for it in the future. You can keep track of progress for this by bookmarking this link: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/70

In the meantime, the only solution for now is to move all your game's files to a disk drive that's under 2TB. Once our fix solution is live, you could then move your files back to the 2TB+ hard disk.

**Comment by AeroWidescreen** [comment]
I could also modify the executable for you to use in the meanwhile. Just be sure to replace it with the one provided [here](http://www.enhanced.townofsilenthill.com/SH2/#installEnhancedEXE) once SH2E is officially updated.

Let me know.

**Comment by Vare3465** [comment]
> Hi @Vare3465 ,
> 
> Yes, we are aware of the issue and will hopefully have a fix for it in the future. You can keep track of progress for this by bookmarking this link: #70
> 
> In the meantime, the only solution for now is to move all your game's files to a disk drive that's under 2TB. Once our fix solution is live, you could then move your files back to the 2TB+ hard disk.

Thank you!

**Comment by Vare3465** [comment]
> I could also modify the executable for you to use in the meanwhile. Just be sure to replace it with the one provided [here](http://www.enhanced.townofsilenthill.com/SH2/#installEnhancedEXE) once SH2E is officially updated.
> 
> Let me know.

I won't be able to play for a while, in fact I beat the game not too long ago and I was just reinstalling it on my new PC so I could guide my friends through its tricky configuring (I've been hooked since I played it and now I want everyone to enjoy it). That means I can wait for you to release the fix, it's nothing urgent. Thanks for responding so fast :)

**Comment by elishacloud** [comment]
@Vare3465, I put a fix in for this.  I have not released it yet, but you can use the attached module for now.  This will allow you to save the game.

Download: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2912938/d3d8.zip)

**Comment by Polymega** [comment]
You did a really great job here, Elisha. Check out my game: I have a 1 TB hard drive that has ~250GB of free disk space left on it: 

### Before your fix: 
![sh2pc 2019-02-27 20-16-43](https://user-images.githubusercontent.com/27395260/53534402-b5d6bf80-3acc-11e9-9f14-91e375cc2d4f.png)

### After your fix: 
![sh2pc 2019-02-27 20-15-56](https://user-images.githubusercontent.com/27395260/53534405-b8d1b000-3acc-11e9-8935-66b0bbe528cd.png)

**Comment by elishacloud** [comment]
A fix has been released for this issue.  See [v1.3.1340.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1340.0)
