### ISSUE TITLE
the attack button doesn't work 

### ISSUE THREAD

**Issue by Berserker-2** [elishacloud/Silent-Hill-2-Enhancements#932]
hi i recently installed the silent hillenhenced edition in my computer, and was everything fine until the first combat, when James enter in tunnel and has to fight with first monster, but i try to press every button for james to attack and he doesn't . then i move to the page of the game, their i was advice to enable enhenced mouse input and mouse weapon swap, but the game still doesn't recognize when i press the action button , what i am supposed to do ?

**Comment by Polymega** [comment]
Make sure the attack (action) input is assigned to something on your keyboard in the Options > Control Options menu.
