### ISSUE TITLE
Binkw32.dll not found? 

### ISSUE THREAD

**Issue by Spritezx** [elishacloud/Silent-Hill-2-Enhancements#934]
it shows me this everytime I try launch I don’t know if I doing something wrong? I went through the set up stuff and that’s what it gives me, I’m kinda confused

![IMG_1620](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/163484627/a3a70d68-9400-4584-ae99-02f87905d200)

**Comment by AeroWidescreen** [comment]
As indicated by the error message, this is likely because you're missing the file **binkw32.dll** in your install folder. This is necessary for video playback and should've been included in your installation of Silent Hill 2. I would reinstall Silent Hill 2 or find a different source.

**Comment by Spritezx** [comment]
It still doesn’t work but thank you :(

**Comment by Polymega** [comment]
When this happens it's usually due to one of these things:

- The base, vanilla game isn't installed. Our project needs the base game in order to work.
- You accidentally downloaded a ISO of SH2 for PS2, and not the PC version.

**Comment by Spritezx** [comment]
This is what I have 
![IMG_1706](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/163484627/8b9be1bf-ff15-4dc7-9e7b-34b65b7572e0)


But it keeps saying binkw, msvcr and I think another one but I don’t remember the name, not found. I downloaded the fully extracted version on myabandonware

**Comment by Polymega** [comment]
The file at the very top is the base, vanilla game. However, it is contained in a ZIP folder. You will need to _extract_ the contents of that ZIP folder to some place on your computer. You can right click the file and select "Extract...". Choose a location. Then, run our Setup Tool and have the project install to the location where you extracted the game to.
