### ISSUE TITLE
The game crashes randomly

### ISSUE THREAD

**Issue by Kazura927** [elishacloud/Silent-Hill-2-Enhancements#936]
I'm playing, and near Piyamid Head's first appearance the game freezes for a second and closes.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14686179/d3d8.log)

**Comment by Polymega** [comment]
If it's consistently crashing in the same spot, then chances are you have a bad/corrupt game file somewhere. I'd recommend making a backup of your save files and redownloading the base/vanilla game files then our project.

Closing ticket. Feel free to re-open if you'd like further assistance.
