### ISSUE TITLE
Mouse Inputs are not working even after a fresh install

### ISSUE THREAD

**Issue by drpestilence** [elishacloud/Silent-Hill-2-Enhancements#937]
For some reason the mouse inputs are not working even after it's enabled and set to the correct movement option.
![image_2024-03-22_200051129](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/164555928/2e218b39-a1ce-4866-979c-56762007c3d5)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14727433/d3d8.log)

**Comment by Polymega** [comment]
Just to be sure, you have control type set to "Rotational (3D)" style?

**Comment by drpestilence** [comment]
> Just to be sure, you have control type set to "Rotational (3D)" style?

It was already on Rotational (3D) by default.

**Comment by Polymega** [comment]
Do you have something else plugged into your PC that could be detected as a mouse/input device? Perhaps when launching SH2 PC it's detecting this device first over your actual mouse for use.

**Comment by drpestilence** [comment]
> Do you have something else plugged into your PC that could be detected as a mouse/input device? Perhaps when launching SH2 PC it's detecting this device first over your actual mouse for use.

I used a controller, but it was for a different game. I have everything unplugged and it still doesn't work
