### ISSUE TITLE
Game won't launch, bitdefender does dumb shit

### ISSUE THREAD

**Issue by HeQtic** [elishacloud/Silent-Hill-2-Enhancements#939]
after installing the MAW extracted version and doing the setup, sh2pc.exe when opening just loads for a second before nothing. i followed instructions from https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/904#issuecomment-1922590428 and the game after setup tries to launch but bitdefender detects it as a threat and quarantines and blocks a bunch of shit, thing is it blocks things that don't really seem to be related to the config (some of the things include : 
C:\ProgramData\Lenovo\Vantage\AddinData\LenovoBatteryGaugeAddin\x64\LaunchPinVantageToolbarToast.lnk
C:\ProgramData\Lenovo\Vantage\Addins\LenovoBatteryGaugeAddin\1.0.4.9\Install.ps1
C:\ProgramData\Lenovo\Vantage\AddinData\LenovoBatteryGaugeAddin\x64\SetMenuItemNameofBatteryGauge.lnk.
)
after restart, bitdefender cleans my laptop and removes the config.exe. opening sh2pc.exe now just opens director's cut
need help

**Comment by HeQtic** [comment]
update: after following the 904 thread closer i now have another problem, for whatever reason i cannot drag the updated d3d8.dll into the folder to replace the old one. it asks me for admin permission which i give, yet somehow it keeps saying i need permissions despite me being the only user on my laptop and the admin. any help is appreciated

**Comment by HeQtic** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14790482/d3d8.log)

**Comment by Polymega** [comment]
Where do you have the game installed to on your computer? What directory?

**Comment by HeQtic** [comment]
Problem solved
