### ISSUE TITLE
Can't Launch Game 

### ISSUE THREAD

**Issue by MrOgden** [elishacloud/Silent-Hill-2-Enhancements#94]
I've followed your installation process step-by-step to the best of my ability, but when I try to launch the sh2pc I keep getting a message saying - 
The code execution cannot proceed because MSVCP100.dll was not found. Reinstalling the program may fix this problem. 

Any ideas?
Thanks.

**Comment by Polymega** [comment]
Hi MrOgden ,

Yes, refer to the troubleshooting portion:
http://enhanced.townofsilenthill.com/SH2/#troubleshooting

**Issue:**
Upon installing IndirectSound, the following error occurs on game launch:
"The program can't start because MSVCP100.dll/MSCVR100.dll is missing from your computer."

**Solution:**
Install Microsoft Visual C++ 2010 Redistributable Package (x86): https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by MrOgden** [comment]
It.....WORKS!! The game runs fine, except for 1 small problem. My tv isn't picking up any sound, just the visual. I kinda need that in order to hook up my Bluetooth headset so's I don't wake the wife. Couod you come to my rescue again? Thanks btw 😉

**Comment by Polymega** [comment]
I'll list anything I think it may be, including the obvious ones:

- Ensure BGM and SFX volume is turned up in the game's Options menu.
- Ensure your TV/headphone volume is turned up.
- Try removing IndirectSound if you're going to play it through your TV. Remove `dsound.dll` and `dsound.ini` from the game's directory. Remember you must fully exit and relaunch the game to see changes like this take effect.

**Comment by MrOgden** [comment]
I tried that, but it's still not picking up the laptop's sound. It's not my headphones or anything else cause I just watched a Youtube video and all was good. Really sorry for pestering you like this but I'm 99% there!

**Comment by Polymega** [comment]
You can try this:
https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-10-hdmi-audio-not-working/293eec79-e0f8-4837-bbd0-341cfc9bd446?auth=1

I just Google searched "windows 10 output sound and video to tv". You can see if other results may help you from there.

**Comment by MrOgden** [comment]
Mate, I've sorted all that out. Can you help me with 1 last thing (I
swear!). I've followed all steps for the controller mapping and when I
press Ok it says 'The program in the same folder as XinputPlus is not made
to a target program'.

**Comment by Polymega** [comment]
Search for and remove any of the following files from the game's directory:

`dinput.dll`
`dinput8.dll`
`XInput1_3.dll`
`Xinput.dll`

If you have any of these files in the directory, remove them. Then, re-try Xinput Plus.

**Comment by MrOgden** [comment]
Top man, worked like a charm. Now, final question. How and where would be
the best way to donate to you and your colleagues? For all the trouble you
guys went through to make this game great again and for personally helping
me.

Many thanks
Brian (Republic of Ireland)

**Comment by Polymega** [comment]
Thanks, Brian. Here are all the people who work on the project. If any are accepting donations, they'll have a donate link to the right of their names: 

http://enhanced.townofsilenthill.com/SH2/credit.htm

Elisha and ThirteenAG are the two main programmers for the project who are accepting donations.

**Comment by MrOgden** [comment]
Happy to do it. I just sent off $15 to both of those contacts. Worth every
penny.

**Comment by MrOgden** [comment]
Hi Again

I had the game working flawlessly last night except I couldn't find the
correct button to turn on/off the Flashlight on the fly. I'm using a PS4
controller.

That's no big deal as I could do it via the menu. I have, however, run into
a bigger problem today. When I go to launch the game it's giving me a
prompt to download some new ini files. When I try do it I receive this
message
'Runtime Error!
Program....Hill.2.Directors.Cut.PC.Game(djDEVASTATE)\shpc.exe.exe

This application has requested the Runtime to termi ate it in an unusual
way. Please contact the application's support team for more information.

Any ideas?
Thanks
Brian.

**Comment by MrOgden** [comment]
Also when I don't receive this message the game just crashes. Really sorry
for being a nuisance again!

**Comment by Polymega** [comment]
> I couldn't find the correct button to turn on/off the Flashlight on the fly. I'm using a PS4 controller.

Using a PS4 controller is a bit more involved than Xbox controllers, which is why it's not mentioned on the install guide. You can follow this thread that discusses in more detail how to set up and map game functions to a PS4 controller: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/92#issuecomment-467522162

> When I go to launch the game it's giving me a prompt to download some new ini files. When I try do it I receive this message [...] Also when I don't receive this message the game just crashes.

Open the `d3d8.ini` file and set `AutoUpdateModule = 0`. This will disable the mod updater. See if the game launches/runs for you then.

**Comment by MrOgden** [comment]
Thanks a million 👍

**Comment by Polymega** [comment]
If setting `AutoUpdateModule = 0` works, then we didn't fix the problem but simply prevent it from happening to begin with. If kept disabled, what this means is you'll have to manually download and update the [SH2 Enhancements mod](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases), whenever an update is available. 

All that entails is downloading the latest d3d8.zip package and replacing pre-existing files in the game's directory, though. And you can keep track of updates by following us here: 

https://twitter.com/WhereAllBegins
https://www.youtube.com/user/WhereAllBegins

I'm not sure why the mod updater is causing you troubles, but perhaps Elisha may have an idea down the road.

**Comment by MrOgden** [comment]
I see. I'll follow those instructions when I get home from work today and
let you know how I got on. Many thanks for your help. You're probably sick
of hearing me say that!

**Comment by MrOgden** [comment]
Hi
I followed the instructions regards changing the Auto Mod Updater and the
game started. I then closed game and hooked up my PS4 controller (without
altering any settings since the last time I used it) and my PC crashed.

I tried it another couple if times and it crashed again. Finally I
disconnected my PS4 controller and it started. Could it be something to do
with the controller? In the meantime I'm gonna try sort out compatibility
for my PS4 controller like you suggested 😉

**Comment by Polymega** [comment]
I don't use a PS4 controller on my PC or with this game so I wouldn't know. 

I do know you have to use several programs injunction with the Dual Shock 4 to get it working right with SH2 PC so there may be a chance something is conflicting there. 

I'd run tests as you plan to do and see if the game consistently runs/crashes when you have the controller plugged in/unplugged.

**Comment by MrOgden** [comment]
Hi Elishacloud

This will hopefully be my last message for a good while. I uncovered a
couple of interesting tid-bits about the PS4 controller's functionality in
relation to SH2 PC.

The flashlight DOES work with the controller in game and it works via the
L3 button. Also the game has a tendency to crach around 90% of the time if
you're trying to play via Bluetooth. I've been playing the last couole of
nights with a weird button setup, but honestly, it's very playable.

Hopefully this comment can help someone who might experience these issues
in the future. Thanks again for all your help. It's been great aying this
game again after all these years!

**Comment by Polymega** [comment]
@MrOgden when you were experiencing the crashes, were you using the European (Director's Cut) executable for the game?

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
