### ISSUE TITLE
Switch pro controller either isn't detected at all or is detected as a keyboard

### ISSUE THREAD

**Issue by HeQtic** [elishacloud/Silent-Hill-2-Enhancements#940]
If i turn off steam input on my pro controller the game dosen't see anything at all, if it is then the game recognizes it as a keyboard (right stick controls the cursor). The pro controller is DInput. What do i do to fix this?

**Comment by Polymega** [comment]
Switch Pro controllers are a bit weird. While I believe they're detected as DirectInput controllers by Windows, they don't behave as how normal DInputs would. I believe specialty, third party drivers and/or programs running in the background are needed to make Switch Pro controllers behave. I also believe Steam has created their own, unique driver solutions to handle this controller (along with others, such as the DualShock 4).

I've never gotten Switch Pro controller to work as-is on my PC, and I don't know if any others on the team have/use this controller, so we'd not be able to offer much assistance for this.
