### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by Gabolayv** [elishacloud/Silent-Hill-2-Enhancements#941]
i have installed the game, plus its EE , performance and everything is good, but ive noticed a 70% cpu usage on only that program, that is making me worry a bit if that should be normal,considering that sh2 is a bit old,.
i have an i5 9400, with a 1650.

**Comment by Polymega** [comment]
This is normal. The game wasn't optimally coded, even back in the day. See here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/899#issuecomment-1906785076
