### ISSUE TITLE
SKIDROW.dll missing?

### ISSUE THREAD

**Issue by crus4der64** [elishacloud/Silent-Hill-2-Enhancements#943]
Hi, I'm currently trying to run the game but for some reason it tells me that I am missing "SKIDROW.dll". Before this popup showed, it told me that I was missing three other DLL's but I've downloaded each one individually. However, I'm not aware of this 'SKIDROW' DLL nor do I know how to obtain it. Every website I visit to download it seems very sketchy and it doesn't appear in my regular DLL downloading website. Please help.
![Screenshot 2024-03-31 204932](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/165601027/9bab1424-7ee8-4948-a891-95c52f3416b9)

**Comment by Polymega** [comment]
SKIDROW.dll isn't included or is a part of the game or our project files. Can you please share a screenshot of your SILENT HILL 2 folder?

**Comment by crus4der64** [comment]
> SKIDROW.dll isn't included or is a part of the game or our project files. Can you please share a screenshot of your SILENT HILL 2 folder?

Hi. I started the process with a download from Myabandonware. Would you like to see that folder or the folder that the enhanced version automatically created after doing the setup? Here's a screenshot of the folder where I kept everything.
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/165601027/17dbcddb-8faf-4002-97f7-c6348b4d62ac)

**Comment by crus4der64** [comment]
> SKIDROW.dll isn't included or is a part of the game or our project files. Can you please share a screenshot of your SILENT HILL 2 folder?

Hi. I started the process with a download from Myabandonware. Would you like to see that folder or the folder that the enhanced version automatically created after doing the setup? Here's a screenshot of the folder where I kept everything.
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/165601027/17dbcddb-8faf-4002-97f7-c6348b4d62ac)

**Comment by Polymega** [comment]
Move _**all**_ of those files/folders you see there _into_ that `Silent-Hill2_Restless-Dreams_Win_EN...` folder.

**Comment by crus4der64** [comment]
> Move _**all**_ of those files/folders you see there _into_ that `Silent-Hill2_Restless-Dreams_Win_EN...` folder.

Gotcha. What could I do next? Do I also move them into the Silent Hill 2 folder inside the previous folder?
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/165601027/3747d9da-21d5-4128-bf23-5fd9ec0dbc97)

**Comment by crus4der64** [comment]
Good news! I just did that and got it to work! Thanks a lot!!
