### ISSUE TITLE
no cd/dvd-rom drive found it says

### ISSUE THREAD

**Issue by donik1234** [elishacloud/Silent-Hill-2-Enhancements#944]
![Screenshot 2024-04-02 183355](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/165859751/4f83508e-05b4-49ed-94e4-be6aabb87b26)

**Comment by elishacloud** [comment]
It looks like you are not even using the Enhanced Edition files at all.  Have you tried checking out this page:  https://enhanced.townofsilenthill.com/SH2/install.htm
