### ISSUE TITLE
audio plays on speaker when earphones are plugged in

### ISSUE THREAD

**Issue by directorwan** [elishacloud/Silent-Hill-2-Enhancements#945]
my earphones are plugged in but the audio keeps playing through the speaker. I tried listening to other audios when its plugged in like videos or website medias and i hear them through my earphones , but the game audio still plays through the speaker. Any help please?

**Comment by elishacloud** [comment]
There is no way in the game to select an audio device.  Here is what you need to do:

1. Verify that the audio head phones work with DirectSound.
2. Plug in the head phones first before starting the game.
3. Adjust settings in Windows to set the head phones as the default device in Windows itself.

**Comment by Polymega** [comment]
For point 3 that Elisha wrote, when you click the Speakers icon in the task tray, you want to make sure that whatever this says is the audio source you want to use for the game:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/18b421cb-5392-4310-bcb3-71b77a6220c2)
