### ISSUE TITLE
Cutscene lags sound 

### ISSUE THREAD

**Issue by JamesSunderland21** [elishacloud/Silent-Hill-2-Enhancements#95]
Dear Team,
I have encountered a little problem during the in-game cutscene of Angela with her knife in her apartment. The image was lagging the sound. What can I do in the settings to correct the issue? Recently, I have activated the noise effect option in the game menu and I don't know if this is the cause. Many thanks for the outstanding work!

**Comment by Polymega** [comment]
If you replay the cutscene does it fix itself? It sounds as though your computer may have had a momentary hitch that de-synced the audio to the video.

**Comment by JamesSunderland21** [comment]
I just tried 2 other times, the lag appears progressively during the cutscene. I tried without the noise effect option and it's still there. I wonder why... I'm afraid it might happen later during the Maria cutscenes. I'll keep you updated.

**Comment by JamesSunderland21** [comment]
The cutscene with Maria was perfect, no lag at all.

**Comment by Polymega** [comment]
Unfortunately I don't have a suggestion for you with this one. The Angela apartment cutscene plays fine for me (along with all other cutscenes).

**Comment by JamesSunderland21** [comment]
Yes @Polymega, the problem is probably independant... Thank you very much. The game is still so beautiful and how you guys improved the fog is impressive. This game is such a masterpiece...

**Comment by Polymega** [comment]
@JamesSunderland21 
I have a very important question to ask you with your issues of stuttering/lag: When you launch the game from a fresh PC reboot, does the game launch for you the first time? Or do you typically have to try and launch the game twice before it'll boot up?

**Comment by Badore90** [comment]
I don't know what cause this but I'm pretty sure it's a PC problem. It happens to me too on Angela FMV and Others too (I noticed it in the Open FMV, the collage intro).
The lag occur launching the videos with external programs too (like VLC media player). First time I launch the video (with VLC) all is perfect, from the second onward the sound starts late.

**Comment by elishacloud** [comment]
Closing issue.  It can be reopened if there is still an issue.

**Comment by deanff** [comment]
I have the same issue. The in-game cutscene with Angela starts in sync with the audio, but progressively goes out of sync as the scene plays out. Just restarted my computer and tested again. Same issue. Tried disabling sh2e mods. Same issue. 

Anything else I should try?
