### ISSUE TITLE
Cursor Color Adjustments

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#950]
@elishacloud 
The following information is to correct two issues with the mouse cursor that appears when interacting with buttons / puzzles. 

The first issue is visibility. The default gray color for the Hotel Employee Elevator blended into the background, making it difficult to see. We have decided to change this color to green, to match the color used for the Hospital door lock.

![Cursor](https://i.imgur.com/pK5S6pO.gif)

The second issue is actually a bug that was introduced in the Xbox and PC version of the game. When the cursor was changed to green using the Hospital door lock, the cursor would remain green until the game was restarted. Thanks to @Bigmanjapan we know this behavior did not exist in the PS2 version of the game, and so it has been fixed.

---

Hotel Employee Elevator Cursor Color

// 00 = Gray
// 01 = Blue
// 02 = Red
// 04 = Green

1.0

```
0057A671 push 04
0057A673 nop
```

1.1

```
0057AF21 push 04
0057AF23 nop
```

DC

```
0057A841 push 04
0057A843 nop
```

---

Cursor Color Bug Fix

1.0
```
004A2E29 jne CursorColorBugFix

CursorColorBugFix:
mov eax,[01DB95B8]
and eax,FF808080
or eax,00808080
mov [01DB95B8],eax
jmp 004A2ED6
```

1.1
```
004A30D9 jne CursorColorBugFix

CursorColorBugFix:
mov eax,[01DBD1B8]
and eax,FF808080
or eax,00808080
mov [01DBD1B8],eax
jmp 004A3186
```

DC
```
004A2999 jne CursorColorBugFix

CursorColorBugFix:
mov eax,[01DBC1B8]
and eax,FF808080
or eax,00808080
mov [01DBC1B8],eax
jmp 004A2A46
```

**Comment by Polymega** [comment]
Thank you, Aero_! This would probably be fine to keep as a hidden feature, but if we'd prefer to make it toggleable let me know and I'll write up an XML entry for it.

**Comment by elishacloud** [comment]
I believe that this should fix the issue:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15004811/d3d8.zip)

Currently, the fix is hard coded.  No way to turn it off.

**Comment by Polymega** [comment]
Did some tests and looks to be good on all binaries. Thank you!
