### ISSUE TITLE
Fan Translation Packs: New strings are required!

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#953]
✔️  @IlDucci (Castilian Spanish)
✔️  @lucazandrade (Brazilian Portuguese)
✔️ @lakeviewhotel (Simplified Chinese)
✔️ @destroytheardor (Polish)
✔️ @Virake (Ukrainian)

----------------------------------

Hello all,

We are in the process of adding some new, exciting features to the project which will require new text strings to be added to various files. This means we'll need your assistance in adding these new strings to your respect fan translation packs.

These features are: 

- A Master Volume slider
   - This will be found in OPTIONS
- An in-game option to toggle the low health indicator on and off
   - This will be found in OPTIONS > GAME OPTIONS
- An in-game option to switch between various display modes
   -  This will be found in OPTIONS > ADVANCED OPTIONS
- An in-game option to adjust the render scaling (also known as Render Resolution)
   - This will be found in OPTIONS > ADVANCED OPTIONS
- A re-worked 3D Sound option
   - This will be found in OPTIONS > ADVANCED OPTIONS

To start, you can grab a test build that has the new features in question here: 
[New Strings Test Build.zip](https://github.com/user-attachments/files/15518318/New.Strings.Test.Build.zip)

Next up, I recommend you grab these files which have the new strings included for Japanese, English, French, German, Italian, and Spanish: [New Strings Language Files.zip](https://github.com/user-attachments/files/15518319/New.Strings.Language.Files.zip)

Here is what needs to be added/translated into your respective language packs:

-------------------------------

### For the `lang\etc\resource\r_menu_*.res` file:
You will need to add the following strings **as new lines** (lines 28-34) in your file:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/599f4f52-c335-4e96-bc51-2997b34c6645)

```
\hMaster Volume
\hAdjust master volume
\hHealth Indicator
\hEnable the low health indicator
\hRender Resolution
\hAdjust rendering resolution
\h3D Sound
\hEnable 3D sound effects
```

_If your language is Latin-based, remember to keep the `\h` at the start of these strings!_

-------------------------

### For the `lang\etc\message\option_msg_*.mes` file:

You will need to **adjust** one of the strings and **add** five (5) new strings to this file. Make sure to use the [SH2MSGconvert](https://github.com/loadwordteam/SH2MSGConvert) tool to do this. Launch SH2MSGConvert, convert the .mes file to .txt for editing purposes, then open the .txt file in your text editor (Notepad++ is recommended).

Once opened, the first thing you should do is change `strings=254` to `strings=259` at the very top. This is because we will be adding five (5) new strings to this file:

<img width="319" alt="image" src="https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/93cd1cb2-63ec-4609-bf0a-b12fa1e53bdb">

Next, scroll to the very bottom of the file, copy the `---------------` (the amount of dashes MUST be exact!), and paste this five (5) times at the bottom, like this:

<img width="241" alt="image" src="https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2e8954ab-f5d9-44af-bcc6-6717c73fc8d6">

Then, add in the following lines in between each `---------------` like this:

<img width="221" alt="image" src="https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/09ea5018-20bb-4f5c-bf52-5e4836b86e7f">

These new lines are:

```
Display Mode
Change the display mode
Windowed
Full Screen Windowed
Full Screen
```

Next, on **line 340** change the string from "Resolution" to "Display Resolution":

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/eee5d398-58ad-4b1c-994b-3aa3dcb00ef5) ![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/e7663611-b8d8-4093-83cb-99f1b50dfa5a)

Once finished, use SH2MSGConvert again to change the .txt back to .mes for the game to use.

----------------------------

Next, test your translated strings and make sure they properly fit within their areas:

![Screenshot 2024-04-21 19-19-53](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/5ece9fb8-ed97-4ea9-a6cd-c261a3741af5)
![Screenshot 2024-04-21 19-12-32](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/f4489ead-6558-4a19-9bc3-1bebeaabfdba)
![Screenshot 2024-05-31 14-29-24](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/467966b7-d6cd-4539-a630-f0057358c7d4)
![Screenshot 2024-05-31 14-29-29](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/e657ba7c-3de5-44af-aaf4-1128fb2c9153)
![Screenshot 2024-05-31 14-29-33](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/8d71da2d-1203-4e4c-9613-c3b39e07e3b2)
![Screenshot 2024-05-31 14-29-36](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/533aeb9e-5f12-4ea0-a090-827e22d6da04)
![Screenshot 2024-05-31 16-14-07](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/90bed28a-b75b-479d-966e-58bcffa86549)

**Note that `Full Screen Windowed` might not fit within its space. You might need to shorten or abbreviate that string.**

----------------------

Once you have made these adjustments, please send me either an updated translation pack of all your files or just send over the `r_menu_*.res` and `option_msg_*.mes` file and I will add them into the translation pack for you.

### If you do not supply me these adjustments before our next project update then your translation pack will be temporarily removed as a download on the project site until these adjustments are received!

There's no immediate rush to have these sent to me; but please just make sure they're provided to me at some point.

Thanks all

**Comment by lucazandrade** [comment]
Brazilian Portuguese Done:
[SH2EE_LangPack_Brazilian_Portuguese.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15064754/SH2EE_LangPack_Brazilian_Portuguese.zip)

**Comment by Polymega** [comment]
Thank you for the fast work on this, Lucaz! I now have the edits for Brazilian Portuguese and Chinese Simplified.

**Comment by Polymega** [comment]
Thank you, IlDucci!

**Comment by Polymega** [comment]
@destroytheardor @virake
Reminder I'll need these edits for your translation pack before the next update release.

Thank you

**Comment by Virake** [comment]
@Polymega , I'm sorry to let you down, but you're gonna have to count me out. the work I initially did to adapt the fan translation was supposed to be a one-time thing.

**Comment by Polymega** [comment]
@Virake can I ask you to reconsider? It's just seven new strings, five of which are just 1-2 words each. I can assure you this is the last, new addition of features that will require new strings for the project.

**Comment by Virake** [comment]
@Polymega , urgh… I don't even remember how to do this anymore, but fine. when is the deadline?

**Comment by Polymega** [comment]
Deadline would be before our next project update. There isn't a date set for this yet. Let's say... a month from today?

**Comment by destroytheardor** [comment]
@Polymega Sorry it took so long, but here are the strings:
[New Strings Polish Pack.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15246182/New.Strings.Polish.Pack.zip)

**Comment by Polymega** [comment]
> @Polymega Sorry it took so long, but here are the strings: [New Strings Polish Pack.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15246182/New.Strings.Polish.Pack.zip)

Wonderful! Thank you very much <3

**Comment by Virake** [comment]
updated Ukrainian translation:
[SH2EE_LangPack_Ukrainian.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15298613/SH2EE_LangPack_Ukrainian.zip)
I checked the options menu, seems fine.

**Comment by Virake** [comment]
also, the original author of the translation is gone, so here's some contingency in case something happens to me as well.

### How to edit Silent Hill 2 Ukrainian translation files

tools:
[SH2EE_Ukrainian_Tools.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15299173/SH2EE_Ukrainian_Tools.zip)

`*.res`
are in plain text and can be opened with anything.

`*.mes`
drag and drop files onto `shtxtconv.exe` to convert
(change `.new.msg` to  `.mes` in the name after converting from `*.txt`)

the text is encoded with a simple character replacement algorithm.
- launch `Transliterator_6.0.exe`
- press `F2`, go to `Profile`, select `User1` in the dropdown list
- switch to `Export/Import` tab, specify the path to `sh2 profile.ini`
- press `Import`
- put the text in `LangTop` box to decode it
- put the text in `LangBottom` box to encode it

map texture PSD files:
https://drive.google.com/file/d/1kYqIwoGrFQxVedZUKdRPbhGpvImy1FLn/
(just in case)

**Comment by Polymega** [comment]
Excellent work here; thank you, Virake. And with that, I can close this ticket out.

I greatly appreciate the help and continued support all of you bring to ensure fans of your native tongue can continue to enjoy the latest project updates.

**Comment by Polymega** [comment]
@Virake , @lucazandrade , @lakeviewhotel , @destroytheardor , @IlDucci 

Gentlemen, I apologize having to come back to you one last time for this, but we need three string changes. One is an adjustment to an existing string and the other two are all-new strings.

Before I begin: We have managed to include supersampling (also known as "render scaling") to the project. This is a feature that already exists for SH3 PC (see image below). Render scaling involves adjusting the internal rendering resolution of the game without changing the output resolution of the display. This will render the game image larger than the output resolution and then downsample (shrink) the image to fit. 

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/4b08d3c1-2e4d-4d3f-89b2-2936535bf000)

Simply put, it is _the best form of anti-aliasing available_ and also fixes/addresses a multitude of front buffer issues we've always had with the game/project. There's no special requirements to use render scaling, either! It works with the game's native Direct 8.1 API!

This is a BIG achievement for our project and, long story short, we want to integrate the render scaling option into the game's Options > Advanced Options menu. This is where I need your help:

-------------------

### For the `lang\etc\resource\r_menu_*.res` file:
You will need to add the following strings **as new lines** (lines 32-33) in your file:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/277d2b38-cb4b-44f3-ab8c-81b3cdcbd3d0)

```
\hRender Resolution
\Adjust rendering resolution
```

_If your language is Latin-based, remember to keep the `\h` at the start of these strings!_

-----------------

### For the `lang\etc\message\option_msg_*.mes` file:

Open the file, find **line 340** and change it from "Resolution" to "Display Resolution":

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/eee5d398-58ad-4b1c-994b-3aa3dcb00ef5) ![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/e7663611-b8d8-4093-83cb-99f1b50dfa5a)

------------------

Unfortunately, we don't have a build ready yet for you to test the "Render Resolution"/"Adjust rendering resolution" strings within the game's menu, **so please be vigilant in ensuring the strings aren't too long and will fit appropriately.**

Below is a mockup of how this menu will change/look once everything is done:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/5d8fb1f2-fbee-4570-86f0-ec00b366f0f6)

Thank you!

**Comment by lucazandrade** [comment]
What amazing resources! Congratulations to everyone! And it's always a pleasure!
Brazilian Portuguese Done:
[SH2EE_LangPack_Brazilian_Portuguese.zip](https://github.com/user-attachments/files/15518189/SH2EE_LangPack_Brazilian_Portuguese.zip)

**Comment by Virake** [comment]
updated Ukrainian translation:
[SH2EE_LangPack_Ukrainian.zip](https://github.com/user-attachments/files/15518672/SH2EE_LangPack_Ukrainian.zip)

**Comment by Polymega** [comment]
Thank you very much, Virake. This render resolution wasn't planned to be added because, in the past, we could never make it work right. But Elisha had an epiphany a month or so ago and was able to fully realize it for our project. There's a lot of technical reasons why this is a big deal for our project, but I'll keep it simple in saying it's going to be an excellent addition once we fully integrate it.

> by the way, there's a mistake in the name of the language pack on the website, it should be spelled as Українська – sentence case, no accent.

I've just updated this as well on the website: https://enhanced.townofsilenthill.com/SH2/languagepacks.htm#ukrainian

Thanks again.

**Comment by lakeviewhotel** [comment]
Here's the updated Simplified Chinese language pack:
[SH2EE_LangPack_Chinese_Simplified.zip](https://github.com/user-attachments/files/15520344/SH2EE_LangPack_Chinese_Simplified.zip)

Thanks!

**Comment by Polymega** [comment]
Thanks, toni!

**Comment by Polymega** [comment]
@destroytheardor 
Would you be able to add/change a few strings? Please see here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/953#issuecomment-2142825766

**Comment by destroytheardor** [comment]
> @destroytheardor 
> 
> Would you be able to add/change a few strings? Please see here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/953#issuecomment-2142825766

Yes, I will do it closer to weekend, most probably on Friday.

**Comment by Polymega** [comment]
@IlDucci (Castilian Spanish)
@lucazandrade (Brazilian Portuguese)
@lakeviewhotel (Simplified Chinese)
@Virake (Ukrainian)

Gentlemen, a heads up that we have included a string you've changed in the `.mes` file into the `.res` files now. This is the change:

Before, line 34 was the description for the 3D sound feature:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/c4805664-7378-4772-93ea-0a12f72f6500)

Now, line 34 is the 3D Sound feature title and line 35 is the 3D sound description:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/210a2e82-5384-4d10-82ec-201338382d2e)

--------------

I've went in and made this adjustment to your respective language packs.

## Please download your updated language packs in the links below for your own records.

- IlDucci (Castilian Spanish): [SH2EE_LangPack_Castilian_Spanish.zip](https://github.com/user-attachments/files/15893692/SH2EE_LangPack_Castilian_Spanish.zip)
- lucazandrade (Brazilian Portuguese): [SH2EE_LangPack_Brazilian_Portuguese.zip](https://github.com/user-attachments/files/15893695/SH2EE_LangPack_Brazilian_Portuguese.zip)
- lakeviewhotel (Simplified Chinese): [SH2EE_LangPack_Chinese_Simplified.zip](https://github.com/user-attachments/files/15893696/SH2EE_LangPack_Chinese_Simplified.zip)
- Virake (Ukrainian): [SH2EE_LangPack_Ukrainian.zip](https://github.com/user-attachments/files/15893697/SH2EE_LangPack_Ukrainian.zip)

**If you don't mind, please let me know you received this message and have downloaded your updated language packs for your own record. Thanks.**

----------------------

@Virake we now have a test build made that includes the new "Render Resolution" option and this string in Ukraine is too long:

![Screenshot 2024-06-18 19-22-47](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/5d908fe4-8f4a-423c-9a23-0bdb2f81d56d)

May I ask you to shorten this? Here is a test build where you can see the string in action: [Workflow binaries reflections TAKE 3.zip](https://github.com/user-attachments/files/15893701/Workflor.binaries.reflections.TAKE.3.zip)

**NOTE: The features seen in this menu are still a WIP and are buggy in this build!**

Thanks

**Comment by lakeviewhotel** [comment]
> **If you don't mind, please let me know you received this message and have downloaded your updated language packs for your own record. Thanks.**

@Polymega Got it, thank you!!

**Comment by Virake** [comment]
@Polymega installing that file didn't make the string appear.

updated translation:
[SH2EE_LangPack_Ukrainian.zip](https://github.com/user-attachments/files/15901001/SH2EE_LangPack_Ukrainian.zip)
- shortened the string #32
- fixed grammar in #34 (nominative case)

**Comment by Virake** [comment]
@Polymega installing that file didn't make the string appear.

updated translation:
[SH2EE_LangPack_Ukrainian.zip](https://github.com/user-attachments/files/15901001/SH2EE_LangPack_Ukrainian.zip)
- shortened the string 32
- fixed grammar in 34 (nominative case)

**Comment by Polymega** [comment]
> updated translation: [SH2EE_LangPack_Ukrainian.zip](https://github.com/user-attachments/files/15901001/SH2EE_LangPack_Ukrainian.zip)

Thank you!

> @Polymega installing that file didn't make the string appear.

I attached the wrong test build; sorry about that. Please use this one: [Workflow binaries MENU TEST.zip](https://github.com/user-attachments/files/15903051/Workflow.binaries.MENU.TEST.zip)

-----------------

@destroytheardor I've update the main/first post to reflect this new change when you begin work.

**Comment by Polymega** [comment]
@destroytheardor 
Checking in to see if you're still good to make those edits soon? Here are the new edits needed: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/953#issuecomment-2142825766

Thanks

**Comment by Polymega** [comment]
Hey @destroytheardor , wanted to check in one last time with you? Please note I'll need the adjustments prior to our next project's update, otherwise I'll have to temporarily remove the language pack from the site.

Thanks

**Comment by destroytheardor** [comment]
@Polymega Here you go:
[New Strings Polish Pack Updated.zip](https://github.com/user-attachments/files/16082247/New.Strings.Polish.Pack.Updated.zip)
Sorry it took me so long :(

**Comment by Polymega** [comment]
Hi @destroytheardor.

Thank you! Can you please shorten this one string for me?

![Screenshot 2024-07-03 12-42-42](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/f9ef4038-5421-4c23-972b-4b598ea23e96)

**Comment by destroytheardor** [comment]
Okay, I've changed it a bit should fit better now:

[New Strings Polish Pack Updated 2.zip](https://github.com/user-attachments/files/16088324/New.Strings.Polish.Pack.Updated.2.zip)

**Comment by Polymega** [comment]
Looks good! Thank you!

![Screenshot 2024-07-03 14-15-55](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/047d0880-8a23-4572-b527-bc3a3aae416e)

**Comment by 60d74** [comment]
Can someone help me? I'm trying to update this [localization](https://github.com/ilyuXer/Silent-Hill-2-Enchanced-Edition-Rus) for the final version, but all the new lines I add to the r_menu_*.res file displayed as gibberish. 
[ru update.zip](https://github.com/user-attachments/files/17504335/ru.update.zip)

<details>
  <summary>screenshots</summary>
  
![sh2pc_2024_10_24_18_30_33_792](https://github.com/user-attachments/assets/587e7139-eb7f-44b7-8ab4-3bd7f40fcb7e)
![sh2pc_2024_10_24_18_29_30_974](https://github.com/user-attachments/assets/f9570482-4f91-4638-b399-c4d86a69fe5d)
![sh2pc_2024_10_24_18_29_03_558](https://github.com/user-attachments/assets/b04dfc95-c2d7-4c9f-b1e6-acf30292a2a8)  

</details>
