### ISSUE TITLE
Silent Hill 2 Enhanced Edition Won't Launch

### ISSUE THREAD

**Issue by KarateFools** [elishacloud/Silent-Hill-2-Enhancements#955]
Not sure if this is the right place to ask this but out of nowhere I can't launch silent hill 2. I didn't change anything drastic on my computer. It just won't launch. I'm on Windows 11. I've tried disabling my antivirus and launching with administrator but nothing is working. Is there any fix or ideas?

**Comment by Polymega** [comment]
Do you have a `d3d8.log` file in the game's directory? If so, please attach that. Also, can you take a snapshot of the contents inside the game's main folder?

**Comment by KarateFools** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15083647/d3d8.log)
 
![unknown_2024 04 23-18 19](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/167826234/17bf1260-5335-443d-810d-02d8d0162f6c) 


Here you go. I'm new to github so hopefully I did it correctly

**Comment by elishacloud** [comment]
Do you have BitDefender?  This looks like the same issue.  Try temporarily disabling your AV.

**Comment by elishacloud** [comment]
You could also try with the build [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/903#issuecomment-1922639849).

**Comment by KarateFools** [comment]
That worked. Thanks!
