### ISSUE TITLE
Game stopped working

### ISSUE THREAD

**Issue by HieiRaizen** [elishacloud/Silent-Hill-2-Enhancements#959]
Hey so I gott his to work with d3d8 zip. I downloaded a updated C++ for Dark and Darker and now i cant play It gives me VCRUNTIME140.dll was not found. I had the zip of the full extract of SH2 and repaired the enhanced edition but still nothing. Help I was so close to beating the game

**Comment by HieiRaizen** [comment]
![shhhh](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/168622589/fa47e170-67ad-4a70-b9cc-1fa0e756c76b)

**Comment by HieiRaizen** [comment]
I also downloaded that 2015 C++ referenced in one of these forums and it took away the warning and it still wont load I also replaced my d3d8 cause having bitdefender. I tried all I could think of to fix and load it if you have any other solutions lmk

**Comment by HieiRaizen** [comment]
I got it to get to a black screen now but it says its not responding and to close the program.

**Comment by Polymega** [comment]
Try these things:

1. Download the latest Microsoft Visual C++ Redistributable here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
   - You want to download the **x86** version as the game is a 32-bit application.
2. If that doesn't fix it, move your **Konami** folder to a different location, such as 'My Documents`. It's not recommended to install old PC games into an admin protected directory such as 'Program Files`.

**Comment by HieiRaizen** [comment]
I moved the file to documents i downloaded C++ earlier to stop the error message. I redownloaded everything and tried to start from scratch and im not even gettting black screened it wont load now

**Comment by Polymega** [comment]
Are you using BitDefender? If so, tell it to allow SH2 PC to launch.

**Comment by HieiRaizen** [comment]
Yeah but i turn it off when attempting to launch the game

**Comment by HieiRaizen** [comment]
I got it i had to go find enishas d3d8 in another forum that had the d3d8 and d3d8.dll i was able to bring my saave file over from the old one before i deleted it. Thanks for troubleshooting this with me
