### ISSUE TITLE
Where are joypad input configurations saved to?

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#96]
@AeroWidescreen
I wanted to make this a GitHub ticket in case you don't know the answer and someone else may. 

With your previous work making `GamepadControlsFix` and `SteamCrashFix` perhaps you'd have knowledge on this: 

**What I'm trying to do:** Simplify the [Installation Guide](http://enhanced.townofsilenthill.com/SH2/) and make it to where everything is good to go out of the box, so users don't have to do any steps beyond downloading then copy + pasting the files to the game's directory. 

I've already got this ready to go for things like IndirectSound and such, but not Xinput Plus. Why? Because I can't figure out where joypad inputs are saved to for this game. It makes sense that it'd be saved to `keyconf.dat` but, if I adjust joypad button inputs on one PC, then copy the appropriate files over to another PC, the joypad inputs do **not** carry over. 

Am I missing something here? Are they saved somewhere else?

**Comment by AeroWidescreen** [comment]
> It makes sense that it'd be saved to keyconf.dat but, if I adjust joypad button inputs on one PC, then copy the appropriate files over to another PC, the joypad inputs do not carry over.

That has to be it though. Removing that file resets the mapping, and bringing it back restores it. I've also confirmed this by hex editing the file to change the buttons.

**Comment by Polymega** [comment]
Would you try something for me if you have two PCs? 

1. Plug in your gamepad on one, and assign controller inputs _purposefully wrong_ for it. 
2. For your other PC, plug in the gamepad and set its inputs correctly. 
3. Copy the necessary files (Xinput Plus files + keyconf.dat) from the correct-input PC to the wrong-input PC. 

Do the controller input update for you and are assigned to the inputs from your other PC? When I tried this it didn't work/change anything. The wrong joypad inputs were still there.

**Comment by AeroWidescreen** [comment]
>Would you try something for me if you have two PCs?

I don't. 😞 You could upload your keyconf.dat from both of your computers and I could test them. Just make sure they both have custom button mapping and not the default settings.

**Comment by Polymega** [comment]
No worries! 

> You could upload your keyconf.dat from both of your computers and I could test them.

So I couldn't send the keyconf.dat from my Win10 laptop (more on that below) so I just made two profiles from my Win7 machine.

**Pressing Y will go to James' next weapon:** [v1.0_NextWeapon.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2948083/v1.0_NextWeapon.zip)
**Pressing Y will Quick Load your Quick Save:** [v1.0_QuickLoad.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2948084/v1.0_QuickLoad.zip)

This was done on v1.0, if that makes a difference.

And here's something interesting: I accidentally **deleted** keyconf.dat from the directory on my Win10 laptop a few weeks back. So I launched the game, assigned controller inputs, closed the game and... the game did **not** make a new keyconf.dat file. So I relaunched the game and it _still_ remembered my joypad input config. 

So I'm thinking this is saved within the main executable? And if that's the case we can't do anything to have that part work "out of the box" for first-timers.

One last request for this: Please don't spend more than 15 minutes looking into this. Only because there are other things that are much more deserving of all our time with this game. Worst case scenario: We just tell people how to assign their own input functions on the install guide, as it's not that hard to do.

**Comment by AeroWidescreen** [comment]
> Pressing Y will go to James' next weapon: v1.0_NextWeapon.zip
Pressing Y will Quick Load your Quick Save: v1.0_QuickLoad.zip

Yup, it works for me. I'm using North American version of the game with the v1.0 exe. I also tested it with the DC and v1.1 executables and it's the same deal. Pressing Y does exactly what you claim it should do.

Note: I did not overwrite any of my XInput Plus files since I already have it configured to SH2EE specifications.

>So I'm thinking this is saved within the main executable? And if that's the case we can't do anything to have that part work "out of the box" for first-timers.

I highly doubt something like this is being saved in the executable, in fact I've never seen a game do something like that before. Maybe it's being saved in the registry?

**Comment by Polymega** [comment]
> Yup, it works for me. I'm using North American version of the game with the v1.0 exe. I also tested it with the DC and v1.1 executables and it's the same deal. Pressing Y does exactly what you claim it should do.

:confused: Well then! I'm going to chalk it up for my Win10 laptop as a fluke. I'll include a keyconf.dat file in the download package then and just have a drop-down table on the guide in case people need to re-adjust any input settings.

Thanks for testing for me, Aero_!

**Comment by Polymega** [comment]
One more thing: It _possibly_ may be that if you installed the North American copy of the game it uses and will make a new keyconf.dat if you delete the previous one. But if you installed the European version it won't make a new keyconf.dat and grabs the input config info from somewhere else. Swapping out the executables post install doesn't change this, perhaps. 

(My Win7 machine had NA installed, and Win10 laptop has EU installed.)

One last question on the matter, Aero_: Do you remember which version you installed? An easy way to tell is look for this file in the main directory: 

`sh2logo.jpg` = SH2 NA
`SH2DClogo.JPG` = SH2 EU

**Comment by AeroWidescreen** [comment]
> One last question on the matter, Aero_: Do you remember which version you installed? An easy way to tell is look for this file in the main directory:

SH2 NA
