### ISSUE TITLE
Silent Hill 2 sddata.bin

### ISSUE THREAD

**Issue by farzeraa** [elishacloud/Silent-Hill-2-Enhancements#962]
hello from everyone in the project!, sorry for the inconvenience, I need help with this .bin file, I'm making a mod from a fan Brazilian dubbing for Silent Hill 2, I was able to access and modify the audio and video files without problems in the enhanced edition, except for the bin file that contains the characters' reactions. I would like to know if there is a way to extract the lines and recompile them.
ps: sorry for my bad english

**Comment by elishacloud** [comment]
Yes, check out this page:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts/SFX

**Comment by farzeraa** [comment]
> Yes, check out this page: https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts/SFX

Thank you!!!!
