### ISSUE TITLE
Silent hill 2 enhanced edition audio stuttering heavily <<please help>>

### ISSUE THREAD

**Issue by Mohamed-543** [elishacloud/Silent-Hill-2-Enhancements#965]
Hello, I just started playing silent hill Enhanced edition and for the first 2 days it ran perfectly with no problems, then after loading it today I noticed that every cutscene or cinematic has **VERY HEAVY AUDIO STUTTER/GLITCH** and also causing the cutscene to either have audio delay or to freeze completely for a few secs and sometimes gameplay is affected too but the non cutscene gameplay has been fixed (for now) so the main problem is the audio stutter in cutscenes 
—————————
I’ve tried to set d3d8t09 = 0 and tried turning off reshade and also tried removing sound.dll
Keep in mind I have a kind of an outdated laptop but that definitely didn’t affect it for the first 2 days of playtime. and considering that SH2 is an old game..so yeah. Any help would be appreciated since it’s my first time playing silent hill 2 and I want to enjoy it without the crippling audio stutter and  visual freezing and audio delay of cutscenes.

Thank you.

**Comment by Polymega** [comment]
Hi there,

We haven't pushed out any updates to the project in a while that would affect your experience from now and two days ago. Try some of these tips to see if it helps any: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general

**Comment by Mohamed-543** [comment]
I tried everything and nothing changed unfortunately, I don't think it has anything with any updates..it might be an unrelated problem..do you have any solutions that might fix the audio stutter/delay and visual freezing especially the audio stutter since it's the most apparent issue 

Sorry for the long reply but I really do need help with this..I love silent hill and really want to enjoy it normally 
Thank you

**Comment by elishacloud** [comment]
A few things to try:
1. Set FPS to 30, rather than 60
2. Set resolution lower
3. Disable "Fix GPU Anti-Aliasing"
4. Make sure "Single core affinity" is disabled
5. Make sure that you have no extra features (like Anti-Aliasing) enabled in your GPU Control Panel for this game

**Comment by Mohamed-543** [comment]
May I ask how to turn off/disable "anti-aliasing" ?
Thanks

**Comment by Mohamed-543** [comment]
Thank you, although there are a few glitches and stutters here and there..there has been some noticeable changes and it's actually watchable now 
 Thanks again for the tip !

**Comment by elishacloud** [comment]
Very good.  I am glad it is working better for you.
