### ISSUE TITLE
Introduction collage freezes at a certain point

### ISSUE THREAD

**Issue by ArtemidosS21** [elishacloud/Silent-Hill-2-Enhancements#969]
The game itself runs fine and doesn't freeze at this point, it's the video itself that freezes, I can still close the video and go back to the game, but does anyone know how to fix this? Here is the moment where the video freezes
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/129891649/7e08beaa-ba05-44f5-bb11-c9073e695d8b)

**Comment by Polymega** [comment]
Perhaps try redownloading the FMV Enhancement Pack, in case that particular movie file became corrupted during the original download/extraction. Run the Setup Tool `SH2EEsetup.exe`, select "Install or Repair Packages", select the FMV Enhancement Pack, and let it download.

**Comment by ArtemidosS21** [comment]
> Perhaps try redownloading the FMV Enhancement Pack, in case that particular movie file became corrupted during the original download/extraction. Run the Setup Tool `SH2EEsetup.exe`, select "Install or Repair Packages", select the FMV Enhancement Pack, and let it download.

Thank you, it worked!
