### ISSUE TITLE
Multi-multi language

### ISSUE THREAD

**Issue by HellbringerOnline** [elishacloud/Silent-Hill-2-Enhancements#97]
Hello. I'm trying to change the subtitle language to Russian by replacing *_e.mes files using Multilanguage Enhanced .exe (Director's Cut), but instead of the text I see broken symbols. Included with the Russian files is a fixed version of .exe, but I cannot replace it because it will delete the mod. Does the application support Russian encoding?

letter_msg_e.mes
CP1251 RUS
`# $ = H u ‡ ћ ґ В д ,Vђ№жъ!Goџ¬Ц 1B‹­Фч#Z}­¶ Ђb ЊЋ€• Ѓ…‘ЏЋЉЋ‰Ќ›• ‘ЌЂ•яэџ ‚€†“ ќ’Ћ’ ѓЋђЋ„яя  Ђ ЂшqЂ‰‹…Ќ’ u€‹‹яя  Ђ Ђш#r› ЋЃ…™Ђ‹ —’Ћ ЉЋѓ„Ђ
Ќ€Ѓ“„њяэ‘ЌЋ‚Ђ Џђ€‚…‡…њ Њ…Ќџ ’“„ЂяэmЋ ’ЂЉ ќ’ЋѓЋ € Ќ… ‘„…‹Ђ‹яя Ђ Ђшw’Ћ † ’…Џ…ђњ џ ’ЂЊ Ћ„ЌЂяя  Ђ Ђшb ЌЂ…Њ Ћ‘ЋЃЋЊ Њ…‘’…яэf„“ ’…Ѓџяя Ђ Ђшlf„“ ЉЋѓ„Ђ ’› Џђ€„…њ Њ…Ќџ ЏЋ‚€„Ђ’њяя Ђ Ђш#mЋ ’› Ќ… Џђ€•Ћ„€њяя  Ђ ЂшrЂЉ џ € †„“ ‡Ђ‚…ђЌ“‚€‘њ ‚ яэЏЋЉђ›‚Ђ‹Ћ ЃЋ‹€ € Ћ„€ЌЋ—…‘’‚Ђяя  Ђ Ђш ‡ЌЂћ —’Ћ Џђ€—€Ќ€‹Ђ ’…Ѓ… ЊЌЋѓЋяэ‘’ђЂ„ЂЌ€‰ ‡Ђ ЉЋ’Ћђ›… ’› Њ…ЌџяэЌ€ЉЋѓ„Ђ Ќ… ЏђЋ‘’€њяя  Ђ Ђш, Ѓ› •Ћ’…‹Ђ €‡Њ…Ќ€’њяэ‚‘… ќ’Ћ ЌЋ Ќ… ЊЋѓ“яя Ђ Ђш —“‚‘’‚“ћ ‘…Ѓџ ’ЂЉЋ‰яэЋЊ…ђ‡€’…‹њЌЋ‰ € †Ђ‹ЉЋ‰яэ‹…†Ђ ’“’ ‚ Ћ†€„ЂЌ€€ ’…Ѓџяя  Ђ ЂшjЂ†„›‰ „…Ќњ џ ‘ЊЋ’ђћ ЌЂяэ’ђ…™€Ќ› ‚ ЏЋ’Ћ‹Љ… € ‚‘… Ћ —…Њяэџ ЊЋѓ“ „“ЊЂ’њ ќ’Ћ Ћ ’ЋЊяэЉЂЉ ‚‘… Ќ…‘ЏђЂ‚…„‹€‚Ћяя Ђ ЂшАq…ѓЋ„Ќџ Џђ€•Ћ„€‹ „ЋЉ’ЋђяэnЌ ‘ЉЂ‡Ђ‹ —’Ћ џ ЊЋѓ“ Ќ…ЌЂ„Ћ‹ѓЋяэ‘љ…‡„€’њ „ЋЊЋ‰яя Ђ Ђш!}’Ћ Ќ… ‡ЌЂ—€’ —’Ћ ЊЌ… ‘’Ђ‹Ћ ‹“—…яэoђЋ‘’Ћ ќ’Ћ ‚Ћ‡ЊЋ†ЌЋяэЊЋ‰ ЏЋ‘‹…„Ќ€‰ ЂЌ‘яя  Ђ Ђш2d“ЊЂћ ’› ЏЋЌ€ЊЂ…њ Ћ —…Њ џяя  Ђ Ђшdb ‹ћЃЋЊ ‘‹“—Ђ… џ PЂ„Ђ ‚…ђЌ“’њ‘џяэ„ЋЊЋ‰  ЏЋ ’…Ѓ… “†Ђ‘ЌЋ ‘Ћ‘Љ“—€‹Ђ‘њяя Ђ ЂшmЋ џ ЃЋћ‘њ d†…‰Њ‘яэ ЃЋћ‘њ —’Ћ ’› Ќ… •Ћ—…њяэ—’ЋЃ› џ Џђ€…‡†Ђ‹Ђяя  Ђ Ђшxb‘џЉ€‰ PЂ‡ ЉЋѓ„Ђ ’› Џђ€•Ћ„€‹ ЉЋяэЊЌ… џ ‚€„…‹Ђ ЉЂЉ ’…Ѓ… ќ’Ћ ’џ†…‹Ћяя  Ђ Ђш( Ќ… ‡ЌЂћ Ќ…ЌЂ‚€„€њ ’› Њ…Ќџ €‹€яэ†Ђ‹……њ h‹€ ЊЋ†…’ Ѓ›’њ џ ’…Ѓ…яэЏђЋ‘’Ћ ЏђЋ’€‚ЌЂяя  Ђ Ђш- ‘Ћ†Ђ‹…ћ ЋЃ ќ’ЋЊяя Ђ Ђш#jЋѓ„Ђ џ ‚Џ…ђ‚›… “‡ЌЂ‹Ђ —’Ћяэ‘ЉЋђЋ “Њђ“ џ ЏђЋ‘’Ћ Ќ… ЊЋѓ‹Ђяэ‚ ќ’Ћ ЏЋ‚…ђ€’њяя  Ђ Ђш( ’ЂЉ PЂ‡Ћ‡‹€‹Ђ‘њ —’Ћ ЌЂ‚ђ…„€‹Ђяэ‚‘…Њ ЉЋѓЋ ‹ћЃ€‹Ђяэn‘ЋЃ…ЌЌЋ ’…Ѓ… d†…‰Њ‘яя Ђ ЂшPbЋ’ ЏЋ—…Њ“ џ ЏЋЌ€ЊЂћяэ…‘‹€ ’› Њ…Ќџ Ќ…ЌЂ‚€„€њяя  Ђ ЂшPmЋ џ •Ћ—“ —’ЋЃ› ’› ‡ЌЂ‹ d†…‰Њ‘яя  Ђ ЂшЇ ‚‘…ѓ„Ђ Ѓ“„“ ‹ћЃ€’њ ’…Ѓџяя Ђ Ђш†uЋ’џ ЌЂЂ ‘Ћ‚Њ…‘’ЌЂџ †€‡Ќњ € „Ћ‹†ЌЂяэ‡ЂЉЋЌ—€’њ‘џ ’ЂЉ џ Ѓ› Ќ… ЏђЋЊ…Ќџ‹Ђяэ…… Ќ€ ЌЂ —’Ћ ЌЂ ‘‚…’… l› ЏђЋ‚…‹€яэЌ…‘ЉЋ‹њЉЋ —“„…‘Ќ›• ‹…’ ‚Њ…‘’…яя Ђ Ђшyw’Ћ † Џ€‘њЊЋ ‡Ђ’џѓ€‚Ђ…’‘џяэ’ЂЉ —’Ћ Џђ€‹Ћ ‚ђ…Њџ ЏђЋ™Ђ’њ‘џяя Ђ Ђш( ЏЋЏђЋ‘€‹Ђ Њ…„‘…‘’ђ“ Ћ’„Ђ’њ …ѓЋяэ’…Ѓ… ЏЋ‘‹… ’ЋѓЋ ЉЂЉ Њ…Ќџ Ќ… ‘’ЂЌ…’яя Ђ Ђш(}’Ћ Ћ‡ЌЂ—Ђ…’ —’Ћ ЉЋѓ„Ђ ’› …ѓЋяэЏђЋ—€’Ђ…њ џ Ѓ“„“ “†… Њ…ђ’‚Ђяя Ђ ЂшP Ќ… ЊЋѓ“ ЏђЋ‘€’њ ’…Ѓџ ЏЋЊЌ€’њяэЊ…Ќџ ЌЋ џ Ќ… Џ…ђ…Ќ…‘“ …‘‹€яэ’› Њ…Ќџ ‡ЂЃ“„…њяя  Ђ ЂшP}’€ ЏЋ‘‹…„Ќ€… Ќ…‘ЉЋ‹њЉЋ ‹…’яэ—’Ћ џ ЃЋ‹…‹Ђ lЌ… ’ЂЉ †Ђ‹њ ‡Ђ ’Ћяэ—’Ћ џ ‘„…‹Ђ‹Ђ ’…Ѓ… ‘„…‹Ђ‹Ђ ЌЂЊяя  Ђ Ђш_r› „Ђ‹ ЊЌ… ’ЂЉ ЊЌЋѓЋ Ђ џ Ќ…яэ‘ЊЋѓ‹Ђ Ќ€—…ѓЋ „Ђ’њ ’…Ѓ… ‚‡ЂЊ…Ќяя  Ђ Ђш_bЋ’ ЏЋ—…Њ“ џ •Ћ—“ —’ЋЃ› ’› ’…Џ…ђњяэ†€‹ „‹џ ‘…Ѓџ d…‹Ђ‰ —’Ћ ‘—€’Ђ…њяэЌ“†Ќ›Њ d†…‰Њ‘яя  Ђ Ђш d†…‰Њ‘яя  Ђ Ђшxr› ‘„…‹Ђ‹ Њ…Ќџ ‘—Ђ‘’‹€‚Ћ‰яя Ђ`

7-bit ASCII ENG
`# $ ; E k }  ® » Э 
#E}¤Рд1T~Ќ№н,s•ґТы-W„Њ Ђ)N MY RESTLESS DREAMSяэ) SEE THAT TOWNяя Ђ Ђш3ILENT (ILLяя Ђ Ђш#9OU PROMISED YOUD TAKE MEяэTHERE AGAIN SOMEDAYяэ"UT YOU NEVER DIDяя Ђ Ђш7ELL )M ALONE THERE NOWяя  Ђ Ђш)N OUR SPECIAL PLACEяэ7AITING FOR YOUяя  Ђ Ђшl7AITING FOR YOU TOяэCOME TO SEE MEяя  Ђ Ђш#"UT YOU NEVER DOяя  Ђ Ђш!ND SO ) WAIT WRAPPED IN MYяэCOCOON OF PAIN AND LONELINESSяя Ђ Ђш) KNOW )VE DONE A TERRIBLEяэTHING TO YOU 3OMETHING YOULLяэNEVER FORGIVE ME FORяя Ђ Ђш,) WISH ) COULD CHANGE яэTHAT BUT ) CANTяя Ђ Ђш) FEEL SO PATHETIC AND UGLYяэLAYING HERE WAITING FOR YOUяя Ђ Ђш%VERY DAY ) STARE UP AT THE CRACKSяэIN THE CEILING AND ALL ) CAN THINKяэABOUT IS HOW UNFAIR IT ALL ISяя Ђ ЂшА4HE DOCTOR CAME TODAYяэ(E TOLD ME ) COULD GOяэHOME FOR A SHORT STAYяя  Ђ Ђш!)TS NOT THAT )M GETTING BETTERяэ)TS JUST THAT THIS MAY BEяэMY LAST CHANCEяя Ђ Ђш2) THINK YOU KNOW WHAT ) MEANяя  Ђ Ђшd%VEN SO )M GLAD TO BE COMINGяэHOME )VE MISSED YOU TERRIBLYяя  Ђ Ђш"UT )M AFRAID *AMESяэ)M AFRAID YOU DONT REALLYяэWANT ME TO COME HOMEяя  Ђ Ђшx7HENEVER YOU COME SEE MEяэ) CAN TELL HOW HARD IT IS ON YOUяя Ђ Ђш() DONT KNOW IF YOUяэHATE ME OR PITY MEяэ/R MAYBE ) JUST DISGUST YOUяя  Ђ Ђш-)M SORRY ABOUT THATяя  Ђ Ђш#7HEN ) FIRST LEARNED THATяэ) WAS GOING TO DIE ) JUSTяэDIDNT WANT TO ACCEPT ITяя Ђ Ђш() WAS SO ANGRY ALL THE TIME AND )яэSTRUCK OUT AT EVERYONE ) LOVED MOSTяэ%SPECIALLY YOU *AMESяя  Ђ ЂшP4HATS WHY ) UNDERSTANDяэIF YOU DO HATE MEяя  Ђ ЂшP"UT ) WANT YOU TOяэKNOW THIS *AMESяя Ђ ЂшЇ)LL ALWAYS LOVE YOUяя  Ђ Ђш†%VEN THOUGH OUR LIFE TOGETHER HADяэTO END LIKE THIS ) STILL WOULDNTяэTRADE IT FOR THE WORLD 7E HADяэSOME WONDERFUL YEARS TOGETHERяя  Ђ Ђшy7ELL THIS LETTER HAS GONE ONяэTOO LONG SO )LL SAY GOODBYEяя  Ђ Ђш() TOLD THE NURSE TO GIVEяэTHIS TO YOU AFTER )M GONEяя  Ђ Ђш(4HAT MEANS THAT AS YOU READяэTHIS )M ALREADY DEADяя Ђ ЂшP) CANT TELL YOU TO REMEMBER MEяэBUT ) CANT BEAR FOR YOU TOяэFORGET MEяя  Ђ ЂшP4HESE LAST FEW YEARS SINCE )яэBECAME ILL)M SO SORRY FORяэWHAT ) DID TO YOU DID TO USяя Ђ Ђш_9OUVE GIVEN ME SO MUCH ANDяэ) HAVENT BEEN ABLE TO RETURNяэA SINGLE THINGяя  Ђ Ђш_4HATS WHY ) WANT YOU TO LIVEяэFOR YOURSELF NOW яэ$O WHATS BEST FOR YOU *AMESяя  Ђ Ђш *AMESяя Ђ Ђшx9OU MADE ME HAPPYяя Ђ`

**Comment by HellbringerOnline** [comment]
I see the characters directly as they are displayed in the message.

**Comment by Polymega** [comment]
Hi @HellbringerOnline , 
We haven't tried changing the language to another that isn't inherently supported by the game. However, there have been a few other modders who have successfully done this. They may be able to lend you assistance on the matter.

@lakeviewhotel has [translated the game's text into Chinese.](https://github.com/lakeviewhotel/SH2)
@belek666 has translated the game's text into Polish [and also has a mod that may help with your goal.](https://github.com/belek666/fontsh234)
@Bigmanjapan [has cataloged Russian pirate copies](https://twitter.com/BigmanjapanSC/status/1101257354513793024) of the game that are already translated in Russian and may be able to help guide you to people who have previously done Russian translations for the game.

I hope this helps some.

**Comment by HellbringerOnline** [comment]
@belek666
> @HellbringerOnline
> You need Russian fonts which are included in fixed game's executable file. Just copy it to game folder if it's size is the same as those included in Silent Hill 2 Enhancements. Future release of Silent Hill 2 Enhancements will support loading external fonts from bitmaps.
I did not quite understand. Are fonts included in the sh2pc.exe? How do I extract fonts from sh2pc.exe?

**Comment by HellbringerOnline** [comment]
Features translated exe

*) All game texts are fully translated (and this is about 200kb in txt without markup tags). This is not editing the pirated translation, but the completely independent work
*) Own sh2pc.exe. The original exe from the European edition (the last of the officially released), patched with all the necessary patches and filled in with a new Russian font. NoCD enabled. Everything has been done to minimize problems with looping / sound loss

**Comment by belek666** [comment]
@HellbringerOnline 

> Are fonts included in the sh2pc.exe?

Yes. 
> How do I extract fonts from sh2pc.exe?

https://github.com/belek666/fontsh234/issues/2#issuecomment-455777997

> *) Own sh2pc.exe. The original exe from the European edition (the last of the officially released), patched with all the necessary patches and filled in with a new Russian font. NoCD enabled. Everything has been done to minimize problems with looping / sound loss

So it should be compatible with Silent Hill 2 Enhancements :)

**Comment by HellbringerOnline** [comment]
@belek666
If I replace the *_e.mes files, the game starts, a black screen appears, but the game does not load further. I extracted fonts to a TGA file, put it in a folder with a game, now the game is loading, but instead of text, i see symbols

**Comment by Polymega** [comment]
I just came across this link: Have you heard of or tried this Russian translation package? 
https://www.zoneofgames.ru/games/silent_hill_2/files/1458.html

**Comment by HellbringerOnline** [comment]
I tried, there is the same problem, but in your link the application is not even fixed, there are problems with sound, etc.
Now I'm trying to make it work this translation
https://www.zoneofgames.ru/games/silent_hill_2/files/312.html

**Comment by Polymega** [comment]
> but in your link the application is not even fixed,

It's important to note that this project doesn't fix the game by creating a new sh2pc.exe but instead patches the game on top of the original executable(s).

**Comment by HellbringerOnline** [comment]
> > but in your link the application is not even fixed,
> 
> It's important to note that this project doesn't fix the game by creating a new sh2pc.exe but instead patches the game on top of the original executable(s).

Wait, then how does the file that I downloaded differ from the original one, which I renamed to sh2pc.bak?

**Comment by Polymega** [comment]
On the installation guide, they're just No-CD executables found from the web. I didn't want to call them that on the guide, however, to help keep any trouble at bay. 

But this is a good example of what I mentioned earlier: The English (North American) No-CD executable seems to have been hacked correctly, with no additional edits done to it besides removing the DRM.  

However, the multi-language (European) No-CD executable may have additional edits done within it that we're unaware of because some people have reported crashes and instabilities when using this executable: 

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/85
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/78
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/44

Because we found this No-CD executable from the web, we have no clue what else has been modified within it. 

Perhaps one day we can circumvent the DRM on the original, untouched executables on our end to guarantee nothing else has been modified within them. This would help ensure the game runs without issue.

**Comment by HellbringerOnline** [comment]
Oh, then I just replace the executable file with the one that is downloaded along with the Russian files. Thank you for help

**Comment by elishacloud** [comment]
Closing.  Issue is resolved.
