### ISSUE TITLE
Game freezes but sounds keeps playing with high CPU usage

### ISSUE THREAD

**Issue by sergiolaverde0** [elishacloud/Silent-Hill-2-Enhancements#972]
At different points not too long after entering a new room the game freezes, the music keeps playing normally without any distortion, and CPU use hits 100% in 3 different cores out of 12 in my Ryzen 5 3600; Radeon 6600 GPU remains chill. This happened sparingly over the fist couple of hours but it is now happening consistently when entering the bowl, after the cinematic ends and Eddie begins to talk.

I have made sure I'm not using the "original" executable of the game but the "enhanced executable", and deleted and restored it with `SH2EEsetup.exe` to be sure. I did something similar with `d3d8.dll` from your releases and in both cases the checksums were the same so I was already using the "right" file.

I'm running this on a Linux desktop in which I frequently play Windows games via Wine/Proton without many issues, using wine-ge-8.26 and DXKV 2.3.1. The log doesn't seem to contain anything relevant, see it here: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/15444690/d3d8.log).

Please let me know if I can do something else to help you diagnose it.

**Comment by Polymega** [comment]
Upon updating all of our project files, does the issue persist? Assistance here is limited by our team as not many of us use Linux. I'll close the ticket for now. Feel free to re-open if you'd like for us to try and further assist.
