### ISSUE TITLE
Weird behavior of control settings when using a non-latin(?) keyboard layout

### ISSUE THREAD

**Issue by ilyuXer** [elishacloud/Silent-Hill-2-Enhancements#973]
English layout:
![EnLayout](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/29177194/542fd874-2c92-42ac-8c3d-44978069b1f0)
Russian layout with the same settings:
![RuLayout](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/29177194/1e70fa48-c693-4dec-b24f-7dc31d599b3f)
I don't think it's a feature.

**Comment by Polymega** [comment]
Apologies, but I'm not sure if we'll be able to assist with this.
