### ISSUE TITLE
where i can find tools for audio modding? 

### ISSUE THREAD

**Issue by Black-Thunder55** [elishacloud/Silent-Hill-2-Enhancements#974]
i want work on weapons sounds there is two tools mergebin.exe + splitbin

https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts/SFX

there is tools for download , can someone help me pls

**Comment by elishacloud** [comment]
The links to the tools are listed under that link that you copied in your question:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/f18a424c-4b17-458f-8a8f-2f431c10221a)

**Comment by Black-Thunder55** [comment]
thank u for help if i done i will send to u my mod " if u want it " or maybe upload it on nexus

**Comment by Black-Thunder55** [comment]
> The links to the tools are listed under that link that you copied in your question:
> 
> ![image](https://private-user-images.githubusercontent.com/25625456/337727131-f18a424c-4b17-458f-8a8f-2f431c10221a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODgxNDUsIm5iZiI6MTcxODE4Nzg0NSwicGF0aCI6Ii8yNTYyNTQ1Ni8zMzc3MjcxMzEtZjE4YTQyNGMtNGIxNy00NThmLThhOGYtMmY0MzFjMTAyMjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEwMjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjVkNDk4Y2VhOGFkMDdiMjc5MGYwOTNlY2JkOGNmNjNmN2MyYjlhM2NmOThmOGMwZTI3NWMwYzE5ZDY1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXtBdxTYuuAKc71DazfFVp73DpCo1i2TyYNycb0i5bI)

https://www.nexusmods.com/silenthill2directorscut/mods/30

its done u can try mod

**Comment by elishacloud** [comment]
Nice.  Thanks!

**Comment by Black-Thunder55** [comment]
> Nice. Thanks!

i add video , u can watch it , look if u don't like any sound i can mod it again with new sound

**Comment by elishacloud** [comment]
It sounds good to me.  Did you take the the Enhancement sounds and modify the sddata.bin file from there or did you start with the base PC version?

**Comment by Black-Thunder55** [comment]
> It sounds good to me. Did you take the the Enhancement sounds and modify the sddata.bin file from there or did you start with the base PC version?

i was thinking to mod 16mb u know the original one but after i checked Enhancement sound i found out some files re-work from u guys so yeah i just mod Enhancement one i dont change any sounds just the weapons

**Comment by Black-Thunder55** [comment]
> It sounds good to me. Did you take the the Enhancement sounds and modify the sddata.bin file from there or did you start with the base PC version?

what i don like the rifle sound same as pistol sound they use same file , i do work on RE games too sometimes two or three weapons share same file " just one" its common on pistols , but first time pistol sound same as rifle . idk what konami thinking

**Comment by elishacloud** [comment]
Ok, very good.

**Comment by Black-Thunder55** [comment]
> Ok, very good.

have a nice day 🫡
