### ISSUE TITLE
can't update the setup tool

### ISSUE THREAD

**Issue by arievv** [elishacloud/Silent-Hill-2-Enhancements#975]
hi, i haven't played the game in a while and when i tried to update the setup tool i got this error
![Zrzut ekranu (1490)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/171252650/0f2fb077-51dc-4da9-b327-2e683618ee6c)

 i don't really know how to fix it and would appreciate the help

**Comment by Polymega** [comment]
I'm not sure. You could try re-downloading the Setup Tool from the project site here: https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE
