### ISSUE TITLE
Suggestion to add the removed Maria audio from the demo.

### ISSUE THREAD

**Issue by Mauro2424** [elishacloud/Silent-Hill-2-Enhancements#976]
The sample of the audio can be viewed at https://youtu.be/0B3LRlJdfpg?si=jmwqKOx-1P6xY2VY&t=1254

The audio sample can probably be extracted from the demo disc of Silent Hill 2; it seems this was cut from the final release of the game for unknown reasons; listening to it is sounds like a great addition that can be done for the enhanced edition.

In case this is already added my apologies for the duplicate request as I don't remember when I was playing the enhanced edition few years back.

**Comment by Polymega** [comment]
Unfortunately, we cannot add this as the speed in which the letter is read is dictated by the player. If the player had no control/agency over when the next lines of the letter are presented, we could likely do it.

**Comment by Mauro2424** [comment]
> Unfortunately, we cannot add this as the speed in which the letter is read is dictated by the player. If the player had no control/agency over when the next lines of the letter are presented, we could likely do it.

Couldn't you edit the code to play the voice in segments or change from the controlled text to an automatic voice and text without it being dictated by the palyer?

**Comment by Polymega** [comment]
If it was something as simple as playing the audio file as-is whenever the letter pops up, that would be feasible. It's not worth the effort at this time to overhaul the code in such way to make it work given the current setbacks.

**Comment by Mauro2424** [comment]
> If it was something as simple as playing the audio file as-is whenever the letter pops up, that would be feasible. It's not worth the effort at this time to overhaul the code in such way to make it work given the current setbacks.

Ok no worries; hopefully one day it can be reconsidered.
