### ISSUE TITLE
Game doesn't start up, no matter what I change

### ISSUE THREAD

**Issue by GlitchyGlitched** [elishacloud/Silent-Hill-2-Enhancements#978]
Recently installed Silent Hill 2 Enhanced Edition, and the game just won't start up no matter what I do. I've tried configuring the settings and launching the 'sh2pc.exe' application numerous times to no avail. The log file isn't much to use either, but I'll still include it just in case:
[d3d8.log](https://github.com/user-attachments/files/15523991/d3d8.log)

Could be something's wrong with my game files in general, so have a screenshot of that too.
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/140921639/23136d06-8320-4c02-9f2d-44ca5d1596f2)

**Comment by Polymega** [comment]
Are you using BitDefender antivirus protection? That AVP has been known to block the game from running. If you are using it, tell BitDefender to allow the game to run.

**Comment by GlitchyGlitched** [comment]
Worked like a charm, knew it was BitDefender.. Appreciate the help!
