### ISSUE TITLE
Feature Request: Prevent player from pressing Esc while transition is active

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#98]
@AeroWidescreen

Perhaps this could be added to or simply compliment the `FastTransitions` mod but, if a user presses Esc (or the button equivalent on a gamepad) while a transition is still... transitioning it'll screencap the previous image before the transition starts: 

https://youtu.be/kgfFmuy55Gg

(This happens for transitions whether or not `FastTransitions` is being used.)

Could a fix be added that prevents the PC pause menu from being able to be pulled up while a transition is active?

**Edit:** It seems as though the game already does this for fade-ins (for example: when you interact with a door you can go through and it starts the fade-in to black) but doesn't do it for fade-outs (upon the black fading out to the next area after going through a door, for example).

**Comment by Bigmanjapan** [comment]
Some addresses that might help. 

sh2pc.exe+5408B8 (009408B8) 4 bytes — holds a key press value (128 for Esc button)
sh2pc.exe+53268C (0093268C) float — fade-in counter (doesn't count fade-outs)
sh2pc.exe+1B7D490 (01F7D490) 4 bytes — location transition state (1 = fade-in, 2 = solid black screen, 3 = fade-out)

Maybe an Esc keypress could be prevented when location transition state has a value of 3? Or something like that.

**Comment by Polymega** [comment]
Thanks for this, Bigmanjapan! The terminology can be a little funny with the fade effects so I'd like to describe these values in a little more detail: 

- sh2pc.exe+1B7D490 (01F7D490) 4 bytes — location transition state 
   - 1 - fades the game image to black
   - 2 - solid black screen
   - 3 - fades _from_ black back to the in-game screen

@elishacloud would ASM adjustments be needed to write a script such as the following? 

**If** 01F7D490 (4 bytes) **has a value of either** 1 or 3 **then prevent** 009408B8 (4 bytes) **from having a value of either** 16 or 128. 

As mentioned by Bigmanjapan, pressing Escape creates a value of 128. Pressing "P" (pause) on the keyboard or the button equivalent on a gamepad, the value is 16. These values do not change even if the keybind for them has been changed in the game's Control Options menu.

**Comment by Bigmanjapan** [comment]
This might be a better one. I think it directly tied to preventing keypresses on on-screen events.

sh2pc.exe+39B834 (0079B834) 4 bytes

During fade-outs (when it's not possible to press Esc and Pause) it has a value of 3.

If you freeze the value on 3 (or NOP the instruction that writes to the address and then set it to 3) during regular gameplay, then the Esc and Pause keypresses will be prevented. Works for the fade-ins too. 

Make it have a value of 3 when `sh2pc.exe+1B7D490 (01F7D490) 4 bytes` is `3 - fades from black back to the in-game screen`.

The issue with freezing the value (constant write) is that if an EE script value update interval is lower than the game's update interval a player would be able to press Esc or Pause if the buttons are pressed rapidly. 
There should be a smart way of readjusting the function, so it writes a value of 3 by itself during fade-ins.

**Comment by elishacloud** [comment]
> @elishacloud would ASM adjustments be needed to write a script such as the following?
>
> If 01F7D490 (4 bytes) has a value of either 1 or 3 then prevent 009408B8 (4 bytes) from having a value of either 16 or 128.

Yes, this requires ASM.  The only way I know of to prevent an address from having a specific value is to find what part of the code is setting that address and modifying that code.

> There should be a smart way of readjusting the function, so it writes a value of 3 by itself during fade-ins.

If I understand this correctly you want me to change `sh2pc.exe+39B834 (0079B834)` to a value of 3 when `sh2pc.exe+1B7D490 (01F7D490)` is also set to 3?

If so that should be pretty easy to do.  There are two options here:
1. I can set it to 3 once each time `sh2pc.exe+39B834 (0079B834)` changes from some other number to 3.
2. Or, I can set it to 3 at the beginning of every frame as long as `sh2pc.exe+39B834 (0079B834)` remains at 3.

**Comment by Polymega** [comment]
Thanks, Elisha! I'll play test the lighting transition fix tomorrow and report back. For this one: 

> If I understand this correctly you want me to change sh2pc.exe+39B834 (0079B834) to a value of 3 when sh2pc.exe+1B7D490 (01F7D490) is also set to 3?

From double-checking Bigmanjapan's notes that seems to be correct. 

> If so that should be pretty easy to do. There are two options here:

Either option could be playtested to make sure a user can't spam-mash the Esc during a fade-in that may override a fix solution. 

If you'd like to play around with this issue, I'd recommend temporarily disabling `FastTransitions` (this will extend the transition times to make play testing easier). Then, go through any door in the game. As the game loads the new area and fades back in from black, you can press the Esc key to experiment.

**Comment by elishacloud** [comment]
Ok, I implemented both solutions.  You can test it and let me know which one is better.

Test module option 1: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3025018/d3d8-1.zip)

Test module option 2: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3025019/d3d8-2.zip)

_Note: this only works on v1.0._

**Comment by Polymega** [comment]
Option 1 did not work but Option 2 did. :) 

I used to play Mario Party a lot so I'd like to think I'm a button-mashing king. Despite my best efforts, I couldn't make the PC pause menu pull back up during the fade-in.

**Comment by elishacloud** [comment]
Implemented in check-in: [c9f8b87](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/c9f8b87911263f63ede421b985446504d16e17d3)

Here is an updated module that works on all versions of SH2: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3025160/d3d8.zip)

**Comment by Polymega** [comment]
Confirmed working on all versions. Thank you both Bigmanjapan and Elisha!

**Comment by Polymega** [comment]
This fix may not be a front-runner for the "wow" factor but it really does make a very, very nice quality-of-life improvement for the game. Well done! 

An update has been released with this fix in it. See [v1.3.1340.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1340.0)
