### ISSUE TITLE
Game not Launching

### ISSUE THREAD

**Issue by Levisuke** [elishacloud/Silent-Hill-2-Enhancements#980]
Hi everyone, 

I wanted to try the Enhanced Edition on PC, I downloaded the good version on abandonware, I installed the SH2EEsetup and when I launch the game I have a black screen (nothing happens) and when I click on the screen I have the windows error (not working)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/171614627/56adcadf-89f9-44fa-90de-974fd322725e)

Here is the folder of the game 

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/171614627/d117a3ab-10d2-4f61-9275-356f97260d57)

Thanks for your help and support on the game !

**Comment by Polymega** [comment]
If you are using BitDefender, tell the program to allow sh2pc.exe to run.

**Comment by Levisuke** [comment]
I don't use BitDefender, nor any antivirus, only Windows defender and everything is off even the firewall

**Comment by Polymega** [comment]
Definitely re-enable your firewall. It's never a good idea to have that disabled while connected to the internet.

Try this next: 

- Download the latest Microsoft Visual C++ Redistributable here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
   - You want to download the **x86** version as the game is a 32-bit application.

**Comment by Levisuke** [comment]
It worked !! thanks !!

**Comment by Polymega** [comment]
You're welcome! Also make sure to re-enable Windows Defender, as well. Be safe out there on the Internet!
