### ISSUE TITLE
Suggestion: Crowd Control compatibility?

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#981]
Crowd Control--in case it isn't known--is a streaming app that allows viewers to interact with a game.
Since you guys are deep inside the code, I was wondering if integrating the ability to connect to CC was something you might be interested in.

I stream Silent Hill 2: Enhanced Edition quite a bit and was spit-balling some ideas for how it could work for SH2. I have no idea how difficult this is to implement but I'd like to share. Worst case, nothing happens. Doesn't hurt to ask, you know? Most of these below would be on a timer and expire after time is up or change upon entering an area require a load screen.

- Spawn normal monsters (Lying Figure, Mannequin, Nurse, Abstract Daddy)
- Give/take health
- Give/take ammo
- Randomize bullet adjust
- Randomize blood color
- Disable radio
- Disable flashlight
- Disable map
- Increase/decrease movement speed
- Cosmetics (color, size, etc.)
- Load and play SFX from a selection of available sounds
- Spawn Labyrinth Pyramid Head in area on room change
- Warp to random room in level area (i.e. Apartments) on room change
- Warp to Dog Room? (allow return to previous door)
- Play as Maria on room change
- Force Great Knife equipped
- Play tripping animation
- Upgrade/downgrade Hyper Spray
- Enable Maria follower on room change until timer depletes then disable upon room change
- Pure darkness (only James visible or lowest brightness setting?)
- Enable/disable fog
- Force constant 'L2' camera focus

**Comment by Polymega** [comment]
Apologies, but that's not something we'll be doing.
