### ISSUE TITLE
Game Black Screen on launch (60sec past + still stuck in black screen)

### ISSUE THREAD

**Issue by PuttipongP** [elishacloud/Silent-Hill-2-Enhancements#982]
hello there are issue after installing 
It seem i can't play neither fullscreen or windowmode
here my folder 
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/100659106/ae216f94-d183-49cd-b9f6-2ec8ca812179)

**Comment by PuttipongP** [comment]
When i disable direcx9 and change to 30 fps it stuck with this 
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/100659106/f5c97204-2157-4053-91d8-9ee4d5144ffd)

**Comment by PuttipongP** [comment]
my log 
[d3d8.log](https://github.com/user-attachments/files/15585134/d3d8.log)

**Comment by PuttipongP** [comment]
I move entire Silent Hill 2 folder to desktop it fix

**Comment by Polymega** [comment]
This was likely the issue:
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/a096c218-7be3-4a7d-813d-06eb3fcfa8b9)

I'm not sure how you were able to add an emoji to a folder's name, but I would recommend to NEVER do this. I can only imagine it breaking many pieces of software out there if a directory string it using non-standard characters/data in their paths.

**Comment by PuttipongP** [comment]
thankyou very much
