### ISSUE TITLE
I have a problem with the game Call of Duty Black Ops 2 

### ISSUE THREAD

**Issue by SHADOOW17** [elishacloud/Silent-Hill-2-Enhancements#983]
![لقطة الشاشة 2024-06-07 112345](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/158819642/4a044496-d830-4818-9801-066e212149e7)

**Comment by elishacloud** [comment]
Sounds like you have a missing or incorrect version of the `binkw32.dll` file.  But are you sure you commented on the right repository?  This is for Silent Hill 2 only.  We don't do anything for other games here.
