### ISSUE TITLE
Maria Shadow + Katz St. Glowing Planter

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#985]
Reporting two visual errors:

1) Maria's shadow renders above her head on or near the awning at the entrance of Pete's Bowl-o-Rama upon entering for the first time. Seems to be dependent on light conditions. Normal light doesn't have a problem, but the sunset lighting does.

Normal:
https://www.twitch.tv/videos/2176539349?t=04h05m55s

Sunset:
https://www.twitch.tv/videos/2176539349?t=01h30m12s

2) There's a planter on the south side of Katz St. during the night portion of the game after Brookhaven that seems to glow regardless of lighting conditions. Other similar planters do not do this.
https://www.twitch.tv/videos/2176539349?t=04h40m33s

**Comment by Polymega** [comment]
1. Will be fixed in our next update. See here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/6bd659df3d47a69cc48acdaebcf816dd21a445a2
2. This will also be fixed. I've done a fairly thorough sweep of all SH2 environments and addressed issues like this, among other things.
