### ISSUE TITLE
Translations for the Configuration Tool (Launcher)

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#988]
@mercury501 (Italian)
@IlDucci (Spanish)
@lucazandrade (Brazilian Portuguese)

Gentlemen, the time has come as we have locked down all new features for the Configuration Tool. May I please ask you to download the ZIP package (below), translate the necessary pieces in your respective language's XML file, and send your XML file back to me? Inside the file, you will see new features that will require translations **as well as existing features that have had their descriptions updated**, which means some old features will also need to be re-translated.

[config.zip](https://github.com/user-attachments/files/16073851/config.zip)

Thank you!

Edit: The adjustments have already been made in your XML files; they just need to be translated to your respective languages.

**Comment by lucazandrade** [comment]
Brazilian Portuguese Done!
[config_br.zip](https://github.com/user-attachments/files/16075815/config_br.zip)

**Comment by IlDucci** [comment]
Spanish updated and complete, though untested.
[config_es.zip](https://github.com/user-attachments/files/16086448/config_es.zip)

**Comment by mercury501** [comment]
Here you go, italian!

[config_it.zip](https://github.com/user-attachments/files/16087981/config_it.zip)

**Comment by Polymega** [comment]
You all are wonderful! Thank you for doing this.
