### ISSUE TITLE
Roshade can' filter quint_ssr not available

### ISSUE THREAD

**Issue by DragonVNYTB** [elishacloud/Silent-Hill-2-Enhancements#989]
Hi everyone, i have an issues with roshade, i can add alot of filter in roshade but can't add filter with filter qUINT
Can anyone help me please.!!

**Comment by elishacloud** [comment]
We already include ReShade in this project.  Try disabling all the Silent Hill 2 Enhancement shaders on the "Display" tab of the configuration tool before attempting to use ReShade.

**Comment by DragonVNYTB** [comment]
Can you guide me?

**Comment by elishacloud** [comment]
Here are the steps:

1. Open the SH2EEconfig.exe config tool.
2. Go to the "Display" tab.
3. At the bottom of the tab disable all three of the checkboxes under the "Shader" section.
4. Click the "Save" button at the bottom of the window.

This will disable all shaders in the Silent Hill 2 project and allow you to use the ReShade tool.

_Note: we cannot help you with the ReShade tool.  You will need to work with the author to get help on that tool._
