### ISSUE TITLE
Letterboxing when running the game at lower resolutions

### ISSUE THREAD

**Issue by M00nBr1ght** [elishacloud/Silent-Hill-2-Enhancements#990]
hi! I wanted to play SH2 at a lower resolution but still, in 16:9, the game refuses to scale properly and instead letterboxes and centers the image. 
I followed the troubleshooting steps on the site but could not resolve the issue alone.

![20240714_130513](https://github.com/user-attachments/assets/40847634-518e-479c-8159-fc3de83db8a2)
[d3d8.log](https://github.com/user-attachments/files/16228184/d3d8.log)

**Comment by Polymega** [comment]
We now include a "render resolution" in our project that might help achieve your goals. See here: https://youtu.be/wX2GpqHxIJ0?si=zAVZUL7Pa7vGGp7-&t=3913
