### ISSUE TITLE
Sound volume issue

### ISSUE THREAD

**Issue by FellaManBoy** [elishacloud/Silent-Hill-2-Enhancements#991]
Maybe this is a known issue but I have not seen anything about it. Cinematic or perhaps cutscene sound is completely separate from the volume sliders in the options menu. I lowered the volume to a pleasant volume for gameplay, and then when James started talking about the letter at the start the audio was extremely loud, unpleasantly so. Is there a workaround for this or do I just have to manually change the volume on my PC instead? Thanks!
[d3d8.log](https://github.com/user-attachments/files/16300901/d3d8.log)

**Comment by Polymega** [comment]
We'll have a solution for this in our upcoming update: https://www.youtube.com/watch?v=JEkH0E0rwUk

**Comment by FellaManBoy** [comment]
Awesome! Thank you!
