### ISSUE TITLE
Non Upscaled FMVs

### ISSUE THREAD

**Issue by thiagofmedeiros** [elishacloud/Silent-Hill-2-Enhancements#992]
Is there a way to use the non upscaled FMVs?

The artifacts generated by the AI upscaling are really terrible, specially when using a 4K display.
I believe having an option to use the original FMVs would be a great option.

**Comment by elishacloud** [comment]
Yes.  If you have the setup tool just uninstall the FMVs and the game will fail-over to the original ones.

**Comment by Pocokk** [comment]
Apologize, what do you mean really terrible? Can it be better to some extent or what do you mean?

**Comment by thiagofmedeiros** [comment]
> Yes. If you have the setup tool just uninstall the FMVs and the game will fail-over to the original ones.

Is it possible do it not only in the install process?

**Comment by thiagofmedeiros** [comment]
> Apologize, what do you mean really terrible? Can it be better to some extent or what do you mean?

The artifacts generated by the upscaler are really bad.

It can always be improved with better upscalers.

For example, the upsacler used with ["Nier: Automata"](https://www.nexusmods.com/nierautomata/mods/37) gave really good results, but its source had a much higher resolution to start.

I personally prefer the original low resolution than the upscaled video with artifcats.

**Comment by Polymega** [comment]
> For example, the upsacler used with ["Nier: Automata"](https://www.nexusmods.com/nierautomata/mods/37) gave really good results, but its source had a much higher resolution to start.

I used the same toolchain as them for these FMVs (Topaz Labs' software suite). I've never known someone who prefers the vanilla PC's FMVs, which are re-encodes of re-encoded videos, but you can delete the `sh2e/movie/` folder to bring back the vanilla FMVs.

**Comment by Bullsquiddy** [comment]
iirc, this project used to use high quality FMVs that were not AI Upscaled. The issue with them was that they were needlessly big files. For whatever reason they were made flatly unavailable - but I held onto them. Don't know if sharing them here would be frowned upon, though.

**Comment by PunishedFiddle** [comment]
See github.com/elishacloud/Silent-Hill-2-Enhancements/issues/573#issuecomment-1244062932
> @v00d00m4n, I have archived the last known good version of the FMVs, v1.5.2 (according to @PunishedFiddle), and have attached a checksum file.
> ## Mirrors:
> 
>     * [Archive.org](https://archive.org/details/sh-2-pc-enhanced-fmv-pack-1.5.2)
> 
>     * [Google Drive](https://drive.google.com/drive/folders/1-BmcN9V4yzeracCRkpq4hdlSOMOtjPlN?usp=sharing)
> 
>     * Hashes generated by [OpenHashTab](https://github.com/namazso/OpenHashTab/releases): [SH2PC_Enhanced_FMV_Pack_1.5.2.zip.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9550382/SH2PC_Enhanced_FMV_Pack_1.5.2.zip.txt)
