### ISSUE TITLE
sh2pc.exe entry point not found

### ISSUE THREAD

**Issue by emans2** [elishacloud/Silent-Hill-2-Enhancements#994]
![لقطة الشاشة 2024-07-28 052635](https://github.com/user-attachments/assets/77b35f6e-060d-4aa4-b3fc-018aeffea311)

I don't know what to do

**Comment by Polymega** [comment]
You need to download the base (vanilla) version of SH2 PC before installing our project. Some common scenarios for this:

- Make sure you the base (vanilla) version of SH2 PC before installing our project
- Make sure our project is installed in the same folder as the base (vanilla) version
- Make sure you've downloaded the _PC_ version of SH2 and not the PS2 version

**Comment by emans2** [comment]
Yes, I installed this version and followed the channel on YouTube. It works for them, but it doesn't work for me. I tried several times, but it doesn't work.
![Uploading لقطة الشاشة 2024-07-29 023150.png…]()

**Comment by emans2** [comment]
![لقطة الشاشة 2024-07-29 023150](https://github.com/user-attachments/assets/fb585753-6251-4b96-a156-2a06297f542b)

**Comment by Polymega** [comment]
You do not have the base (vanilla) version of the PC game installed. Our project requires you to have that installed.

**Comment by emans2** [comment]
Your project is already installed but give me the file you downloaded to install it

**Comment by emans2** [comment]
Please reply to me

**Comment by elishacloud** [comment]
@emans2, that error means you are missing the `binkw32.dll` file.  I can see from the screenshot that you have not installed the base Silent Hill 2 game.

Keep in mind that this Enhanced Edition is a mod for the Silent Hill 2 game, it does not include the actual game.  Make sure that the Silent Hill 2 game run ok first before installing this mod.  I recommend doing the following:

1. Remove this mod.
2. Install the base game.
3. Once the game is installed and working only then install this enhancement mod.

**Comment by Polymega** [comment]
Closing ticket. Feel free to re-open if you'd like further assistance.
