### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by VelvetLies** [elishacloud/Silent-Hill-2-Enhancements#996]
Im running Win10 on a Virtual Machine where SH2 is installed, the game wouldn't start so I looked up some fixes and the issue was the dsound.dll, so I removed that and the game worked, it had audio, but now when the controller was setup I have no audio in-game.

![image](https://github.com/user-attachments/assets/0e967a3e-b28f-4bf7-b580-1f73f5141232)

**Comment by Polymega** [comment]
Check out the point here about controllers and audio: https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

**Comment by VelvetLies** [comment]
I have a regular PC controller without speakers

**Comment by VelvetLies** [comment]
Okay so I ran it through wine, all the files are there and still no audio
[d3d8.log](https://github.com/user-attachments/files/16409613/d3d8.log)

**Comment by VelvetLies** [comment]
fixed it after doing this https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/557
