### ISSUE TITLE
Silent Hill 2 Crashes on launch unless ran in fullscreen

### ISSUE THREAD

**Issue by Zendettaa** [elishacloud/Silent-Hill-2-Enhancements#997]
i want to play in windowed or windowed fullcreen but everytime i try it crashes, ive reinstalled and everything but  it still wont work

[d3d8.log](https://github.com/user-attachments/files/16482992/d3d8.log)

**Comment by Zendettaa** [comment]
i looked at other posts of the game not launching and downloaded some update file and it fixed my issue

**Comment by Polymega** [comment]
After updating project files to the latest, does this issue persist?
