### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by TheMage24** [elishacloud/Silent-Hill-2-Enhancements#999]
Hi there! Played this a few years ago (amazing work, you guys are gods!) and wanted to try it again with the 60 FPS mode.

I installed SH2 director's cut, installed your EE, but the game simply will not open. When I try to launch it the cursor just loads for like 2-3 secs, then nothing happens. I've tried several re-installs, tried putting it in different folders, nothing works. In the task manager I see sh2pc.exe pop up but then it just disappears.

Any suggestions? Thanks in advance!

**Comment by Polymega** [comment]
Hi there,

Can you attach a copy of your `d3d8.log` file found in the game's main folder? If that doesn't exist, can you share a snapshot of the game's main folder here?

**Comment by TheMage24** [comment]
I just solved it by looking through other posts (should've done that first. my bad). BitDefender was the culprit, put in an exception and it works now. Thanks though!
